/**
 * Arts & Musique, troisième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Arts & Musique";

export const CG_ARTS_MUSIQUE_3: SeedSkill[] = [
  notion("am3-musees-france", S, "Les musées français",
    "Collections, histoire, organisation.",
    "La France compte plus de mille deux cents musées portant l'appellation Musée de France.",
    2, [
    ["Qu'est-ce que l'appellation Musée de France ?", ["Un label légal impliquant des obligations de conservation et de médiation", "Un label de qualité touristique", "Une reconnaissance des musées nationaux", "Un classement des collections"], 0,
     "Créée par la loi de 2002, elle concerne des musées de tous statuts."],
    ["Quel musée parisien conserve les collections d'art moderne et contemporain national ?", ["Le musée national d'Art moderne, au Centre Pompidou", "Le musée d'Orsay", "Le Louvre", "Le Palais de Tokyo"], 0,
     "Il possède l'une des plus vastes collections d'art moderne au monde."],
    ["Quel musée parisien est consacré à Auguste Rodin ?", ["Le musée Rodin, à l'hôtel Biron", "Le musée Bourdelle", "Le musée Zadkine", "Le musée Maillol"], 0,
     "Le sculpteur avait légué son œuvre à l'État en échange de la création du musée."],
    ["Quel musée lyonnais est consacré au cinéma ?", ["l'Institut Lumière", "Le musée des Confluences", "Le musée gallo-romain", "Le musée des Beaux-Arts"], 0,
     "Il est installé dans la maison familiale des frères Lumière."],
    ["Quel musée du Nord de la France a ouvert dans un ancien bassin minier ?", ["Le Louvre-Lens", "Le LaM", "Le Palais des Beaux-Arts de Lille", "La Piscine de Roubaix"], 0,
     "Ouvert en 2012, il présente des œuvres du Louvre dans une galerie chronologique unique."],
    ["Quel musée de Roubaix est installé dans une ancienne piscine Art déco ?", ["La Piscine", "Le LaM", "Le musée de la Chartreuse", "Le musée Matisse"], 0,
     "Le bassin a été conservé et intégré au parcours muséal."],
    ["Qu'est-ce que la nuit européenne des musées ?", ["Une ouverture nocturne gratuite un samedi de mai", "Une exposition nocturne annuelle", "Un festival de musées", "Une opération de mécénat"], 0,
     "Elle attire chaque année environ deux millions de visiteurs en France."],
    ["Qu'est-ce que le récolement des collections ?", ["La vérification périodique de la présence et de l'état des œuvres", "L'inventaire initial", "La restauration programmée", "Le classement documentaire"], 0,
     "Il est obligatoire tous les dix ans pour les Musées de France."],
    ["Qu'est-ce qu'une réserve de musée ?", ["Un espace de conservation des œuvres non exposées", "Une salle d'exposition temporaire", "Un atelier de restauration", "Un dépôt d'archives"], 0,
     "La grande majorité des collections d'un musée s'y trouve en permanence."],
    ["Qu'est-ce que la médiation culturelle ?", ["Un ensemble d'actions facilitant la rencontre entre publics et œuvres", "Une visite guidée", "Une politique tarifaire", "Une action de communication"], 0,
     "Elle est devenue une mission à part entière des musées, inscrite dans la loi.", 3],
  ]),

  notion("am3-peinture-france", S, "La peinture française",
    "Écoles, commandes, grandes figures.",
    "La peinture française a longtemps été structurée par l'Académie et le Salon.",
    2, [
    ["Qu'était le Salon officiel au XIXe siècle ?", ["L'exposition annuelle où se faisait la carrière des peintres", "Une galerie privée", "Un salon littéraire", "Une école de peinture"], 0,
     "Y être refusé pouvait ruiner une carrière ; y être remarqué la lançait."],
    ["Qu'est-ce que le prix de Rome ?", ["Un concours offrant un séjour à la Villa Médicis", "Un prix de peinture italien", "Une commande d'État", "Un prix de l'Académie française"], 0,
     "Créé en 1663, il a été supprimé en 1968."],
    ["Quel peintre français du XVIIIe siècle est célèbre pour ses natures mortes ?", ["Chardin", "Fragonard", "Boucher", "Watteau"], 0,
     "Ses objets ordinaires ont été redécouverts au XIXe siècle et admirés par Cézanne et Matisse."],
    ["Quel peintre invente la fête galante au XVIIIe siècle ?", ["Watteau", "Fragonard", "Boucher", "Nattier"], 0,
     "L'Académie a créé une catégorie spéciale pour l'accueillir."],
    ["Quel peintre français est célèbre pour ses vues de Paris sous la pluie ?", ["Gustave Caillebotte", "Camille Pissarro", "Claude Monet", "Édouard Manet"], 0,
     "Rue de Paris, temps de pluie est l'un des tableaux emblématiques de l'impressionnisme."],
    ["Quel peintre a peint plus de deux cent cinquante toiles de nymphéas ?", ["Claude Monet", "Alfred Sisley", "Camille Pissarro", "Berthe Morisot"], 0,
     "Les grandes compositions de l'Orangerie ont été offertes à l'État après la Première Guerre mondiale."],
    ["Quel peintre français est associé au néo-impressionnisme et au pointillisme ?", ["Georges Seurat", "Paul Signac seul", "Claude Monet", "Camille Pissarro"], 0,
     "Signac en fut le théoricien après la mort précoce de Seurat, à trente et un ans."],
    ["Quel peintre français a passé les dernières années de sa vie en Polynésie ?", ["Paul Gauguin", "Vincent van Gogh", "Émile Bernard", "Maurice Denis"], 0,
     "Il y est mort en 1903, aux Marquises."],
    ["Quel peintre français a réalisé de grands papiers découpés en fin de vie ?", ["Henri Matisse", "Pierre Bonnard", "Raoul Dufy", "André Derain"], 0,
     "Ne pouvant plus peindre debout, il dessinait avec des ciseaux dans la couleur."],
    ["Quel peintre français du XXe siècle a travaillé le noir comme matière lumineuse ?", ["Pierre Soulages", "Nicolas de Staël", "Jean Dubuffet", "Georges Mathieu"], 0,
     "Il parlait d'outrenoir, le noir devenant support de reflets.", 3],
  ]),

  notion("am3-sculpture-contemporaine", S, "La sculpture depuis 1900",
    "Matériaux, échelles, espaces.",
    "La sculpture du XXe siècle a quitté le socle et l'atelier.",
    2, [
    ["Qu'est-ce que l'abandon du socle en sculpture moderne ?", ["Une rupture plaçant l'œuvre dans l'espace du spectateur", "Une simplification technique", "Une économie de matériaux", "Un changement d'échelle"], 0,
     "Rodin l'avait déjà expérimenté avec les Bourgeois de Calais."],
    ["Quel sculpteur roumain a simplifié la forme jusqu'à l'épure ?", ["Constantin Brancusi", "Alberto Giacometti", "Hans Arp", "Henry Moore"], 0,
     "Son Oiseau dans l'espace a fait l'objet d'un procès douanier célèbre aux États-Unis."],
    ["Quel sculpteur britannique est connu pour ses figures allongées percées ?", ["Henry Moore", "Barbara Hepworth", "Anthony Caro", "Anish Kapoor"], 0,
     "Barbara Hepworth a également exploré le percement de la masse sculptée."],
    ["Qu'est-ce qu'un mobile en sculpture ?", ["Une sculpture suspendue mise en mouvement par l'air", "Une sculpture motorisée", "Une sculpture transportable", "Une sculpture cinétique électrique"], 0,
     "Alexander Calder en est l'inventeur ; le mot est de Marcel Duchamp."],
    ["Qu'est-ce que l'art cinétique ?", ["Un art fondé sur le mouvement réel ou apparent", "Un art vidéo", "Un art de la performance", "Un art numérique"], 0,
     "Jean Tinguely et Victor Vasarely en sont des figures majeures."],
    ["Quel sculpteur suisse a créé des machines autodestructrices ?", ["Jean Tinguely", "Alberto Giacometti", "Max Bill", "Hans Arp"], 0,
     "Hommage à New York, en 1960, s'est détruite en public au Museum of Modern Art."],
    ["Qu'est-ce qu'une sculpture monumentale in situ ?", ["Une œuvre conçue pour un lieu précis et indissociable de lui", "Une grande sculpture publique", "Une sculpture extérieure", "Une commande publique"], 0,
     "La déplacer revient souvent à en détruire le sens."],
    ["Qu'est-ce que le Un pour cent artistique appliqué à la sculpture ?", ["Une obligation de consacrer une part du budget d'une construction publique à une œuvre", "Une taxe sur l'art", "Une commande d'État", "Un fonds d'acquisition"], 0,
     "Plus de douze mille œuvres ont été installées en France depuis 1951."],
    ["Quel artiste américain a réalisé d'immenses interventions dans le paysage ?", ["Robert Smithson", "Donald Judd", "Richard Serra", "Carl Andre"], 0,
     "Spiral Jetty, en 1970, est régulièrement submergée par les variations du Grand Lac Salé."],
    ["Quel sculpteur américain travaille l'acier en immenses plaques courbes ?", ["Richard Serra", "Donald Judd", "Dan Flavin", "Sol LeWitt"], 0,
     "Ses œuvres exigent une expérience physique du parcours pour être appréhendées.", 3],
  ]),

  notion("am3-musique-formes", S, "Les formes musicales",
    "Sonate, variation, rondo, suite.",
    "Une forme musicale décrit l'organisation du discours, non son style.",
    2, [
    ["Qu'est-ce que la forme sonate ?", ["Une structure en exposition, développement et réexposition", "Une pièce pour piano seul", "Une œuvre en trois mouvements", "Une forme de danse"], 0,
     "Elle structure le premier mouvement de la plupart des symphonies classiques."],
    ["Qu'est-ce qu'un thème et variations ?", ["Une forme reprenant un thème sous des aspects transformés", "Une improvisation libre", "Une suite de danses", "Une fugue"], 0,
     "Les Variations Goldberg de Bach en comptent trente sur une même basse."],
    ["Qu'est-ce qu'un rondo ?", ["Une forme où un refrain alterne avec des couplets contrastés", "Une danse à trois temps", "Une forme fuguée", "Une pièce en canon"], 0,
     "Il conclut fréquemment une sonate ou un concerto classique."],
    ["Qu'est-ce qu'une suite baroque ?", ["Une succession de danses stylisées dans une même tonalité", "Une série de variations", "Un ensemble de préludes", "Une sonate en plusieurs parties"], 0,
     "Allemande, courante, sarabande et gigue en forment le noyau."],
    ["Qu'est-ce qu'un canon en musique ?", ["Une imitation stricte d'une voix par une autre, décalée dans le temps", "Une répétition d'un thème", "Une forme de fugue", "Un accord parfait"], 0,
     "Frère Jacques est le canon le plus connu du répertoire populaire."],
    ["Qu'est-ce qu'un ostinato ?", ["Un motif répété obstinément tout au long d'un passage", "Un thème principal", "Un accompagnement libre", "Une cadence finale"], 0,
     "Le Boléro de Ravel repose sur un ostinato rythmique de dix-sept minutes."],
    ["Qu'est-ce qu'une cadence en musique ?", ["Une formule harmonique concluant une phrase musicale", "Un passage rapide", "Un solo improvisé", "Un changement de tempo"], 0,
     "Le mot désigne aussi le passage virtuose improvisé du soliste dans un concerto."],
    ["Qu'est-ce qu'une modulation ?", ["Un changement de tonalité au cours d'un morceau", "Une variation de nuance", "Un changement de tempo", "Une transformation du thème"], 0,
     "Elle crée un effet de relance et structure les grandes formes."],
    ["Qu'est-ce qu'un prélude ?", ["Une pièce d'introduction, parfois autonome", "Une ouverture d'opéra", "Un mouvement lent", "Une improvisation notée"], 0,
     "Chez Chopin ou Debussy, il est devenu une forme brève entièrement autonome."],
    ["Qu'est-ce qu'une symphonie concertante ?", ["Une œuvre pour plusieurs solistes et orchestre", "Une symphonie chantée", "Un concerto pour orchestre", "Une symphonie en un mouvement"], 0,
     "Mozart en a laissé plusieurs, à mi-chemin entre la symphonie et le concerto.", 3],
  ]),

  notion("am3-jazz-histoire", S, "L'histoire du jazz",
    "Courants, figures, évolutions.",
    "Le jazz a changé de langage tous les quinze à vingt ans pendant un demi-siècle.",
    2, [
    ["Qu'est-ce que le ragtime ?", ["Un style pianistique syncopé antérieur au jazz", "Un style de blues", "Un courant du jazz moderne", "Une danse de La Nouvelle-Orléans"], 0,
     "Scott Joplin en est le compositeur le plus célèbre."],
    ["Qu'est-ce que le style New Orleans ?", ["Un jazz collectif à improvisation polyphonique", "Un jazz de grand orchestre", "Un jazz soliste", "Un jazz écrit"], 0,
     "Plusieurs instruments y improvisent simultanément, sans hiérarchie stricte."],
    ["Qu'est-ce que l'ère du swing ?", ["Une période où les grands orchestres de danse dominent le jazz", "Un style de piano", "Une technique rythmique seule", "Un courant vocal"], 0,
     "Des années 1930 aux années 1940, avec Count Basie, Duke Ellington et Benny Goodman."],
    ["Qu'est-ce qu'un big band ?", ["Un grand orchestre de jazz à pupitres organisés", "Un orchestre symphonique de jazz", "Un ensemble de danse", "Un quintette élargi"], 0,
     "Saxophones, trompettes, trombones et section rythmique en constituent l'ossature."],
    ["Quel courant succède au bebop dans les années 1950 ?", ["Le cool jazz et le hard bop", "Le free jazz", "Le jazz fusion", "Le swing"], 0,
     "Le cool privilégie la retenue, le hard bop renoue avec le blues et le gospel."],
    ["Qu'est-ce que le free jazz ?", ["Un courant abandonnant les grilles harmoniques fixes", "Un jazz gratuit", "Un jazz improvisé collectivement seulement", "Un jazz sans rythme"], 0,
     "Ornette Coleman et Cecil Taylor en sont des figures fondatrices."],
    ["Qu'est-ce que le jazz fusion ?", ["Un courant mêlant jazz, rock et instruments électriques", "Un mélange de jazz et de classique", "Un jazz latino", "Un jazz vocal"], 0,
     "L'album Bitches Brew de Miles Davis, en 1970, en marque un tournant."],
    ["Quelle chanteuse est surnommée Lady Day ?", ["Billie Holiday", "Ella Fitzgerald", "Sarah Vaughan", "Nina Simone"], 0,
     "Strange Fruit, qu'elle enregistre en 1939, dénonce les lynchages dans le Sud américain."],
    ["Quelle chanteuse est célèbre pour sa maîtrise du scat ?", ["Ella Fitzgerald", "Billie Holiday", "Dinah Washington", "Betty Carter"], 0,
     "Le scat consiste à improviser sur des syllabes sans signification."],
    ["Quel saxophoniste a marqué le jazz modal et spirituel des années 1960 ?", ["John Coltrane", "Charlie Parker", "Sonny Rollins", "Stan Getz"], 0,
     "A Love Supreme, enregistré en 1964, est l'un des albums les plus commentés du genre.", 3],
  ]),

  notion("am3-rock-pop", S, "Rock et musiques populaires",
    "Courants, groupes, industrie.",
    "Le rock s'est fragmenté en dizaines de sous-genres à partir des années 1970.",
    2, [
    ["Quel groupe britannique a transformé la musique populaire dans les années 1960 ?", ["Les Beatles", "Les Rolling Stones", "The Who", "Led Zeppelin"], 0,
     "Ils ont aussi révolutionné les pratiques de studio avec Sgt. Pepper en 1967."],
    ["Qu'est-ce que la British Invasion ?", ["L'arrivée massive de groupes britanniques sur le marché américain", "Une tournée européenne", "Un courant musical anglais", "Une vague de rachats de labels"], 0,
     "Elle commence en 1964 avec le succès américain des Beatles."],
    ["Qu'est-ce que le rock progressif ?", ["Un courant aux structures longues et complexes des années 1970", "Un rock politique", "Un rock expérimental électronique", "Un rock acoustique"], 0,
     "Pink Floyd, Genesis et Yes en sont des représentants majeurs."],
    ["Qu'est-ce que le punk ?", ["Un mouvement musical et culturel prônant simplicité et rupture", "Un style de rock lent", "Un courant électronique", "Un genre acoustique"], 0,
     "Né en 1976 à Londres et New York, en réaction à la complexité du rock progressif."],
    ["Quel groupe américain a marqué le grunge au début des années 1990 ?", ["Nirvana", "Metallica", "R.E.M.", "The Smashing Pumpkins"], 0,
     "Nevermind, en 1991, a fait basculer l'industrie musicale américaine."],
    ["Qu'est-ce que la musique électronique dansante ?", ["Un ensemble de genres conçus pour la piste de danse", "Une musique jouée sur synthétiseurs", "Un genre expérimental", "Une musique de club exclusivement"], 0,
     "House, techno, trance et drum and bass en font partie."],
    ["Quel duo français a popularisé la musique électronique dans le monde ?", ["Daft Punk", "Justice", "Air", "Cassius"], 0,
     "La French touch, à la fin des années 1990, a exporté une esthétique reconnaissable."],
    ["Qu'est-ce qu'un sample en musique ?", ["Un extrait sonore réutilisé dans une nouvelle composition", "Un enregistrement de démonstration", "Une piste d'accompagnement", "Un motif joué en boucle"], 0,
     "Son usage a donné lieu à une jurisprudence abondante sur le droit d'auteur."],
    ["Qu'est-ce qu'un label indépendant ?", ["Une maison de disques n'appartenant pas à un grand groupe", "Un label local", "Un label sans distribution", "Un label associatif"], 0,
     "Trois grands groupes contrôlent aujourd'hui la majorité du marché mondial du disque."],
    ["Comment se répartissent les revenus du streaming musical ?", ["Une part majoritaire va aux ayants droit, l'artiste ne percevant qu'une fraction", "L'artiste perçoit la majorité", "Les revenus sont partagés à parts égales", "La plateforme conserve tout"], 0,
     "La répartition proportionnelle au nombre d'écoutes est régulièrement contestée par les artistes.", 3],
  ]),

  notion("am3-danse-classique-repertoire", S, "Le répertoire du ballet",
    "Œuvres, chorégraphes, institutions.",
    "Le répertoire classique repose sur une poignée d'œuvres du XIXe siècle.",
    2, [
    ["Quel ballet de Tchaïkovski se déroule la nuit de Noël ?", ["Casse-Noisette", "Le Lac des cygnes", "La Belle au bois dormant", "Coppélia"], 0,
     "Il est devenu une tradition de fin d'année dans de nombreux pays."],
    ["Quel chorégraphe a créé les versions de référence des ballets de Tchaïkovski ?", ["Marius Petipa", "Michel Fokine", "August Bournonville", "Jules Perrot"], 0,
     "Français installé en Russie, il y a passé plus de cinquante ans."],
    ["Quel ballet romantique met en scène des esprits de jeunes filles ?", ["Giselle", "La Sylphide", "Coppélia", "Paquita"], 0,
     "Créé à Paris en 1841, il est le sommet du ballet romantique."],
    ["Quel ballet du XIXe siècle met en scène une poupée mécanique ?", ["Coppélia", "Giselle", "La Sylphide", "Le Corsaire"], 0,
     "Créé à l'Opéra de Paris en 1870, sur une musique de Léo Delibes."],
    ["Quel danseur russe a marqué les Ballets russes avant de sombrer dans la maladie ?", ["Vaslav Nijinski", "Serge Lifar", "Michel Fokine", "Léonide Massine"], 0,
     "Sa chorégraphie du Sacre du printemps a provoqué un scandale en 1913."],
    ["Quel chorégraphe américain a fondé le New York City Ballet ?", ["George Balanchine", "Jerome Robbins", "Martha Graham", "Merce Cunningham"], 0,
     "Formé en Russie, il a créé un style néoclassique épuré et musical."],
    ["Quel chorégraphe américain a travaillé avec le compositeur John Cage ?", ["Merce Cunningham", "George Balanchine", "Paul Taylor", "Alvin Ailey"], 0,
     "Ils ont développé des œuvres où musique et danse coexistent sans se subordonner."],
    ["Quel chorégraphe français a dirigé le Ballet de l'Opéra de Paris de 1930 à 1958 ?", ["Serge Lifar", "Maurice Béjart", "Roland Petit", "Pierre Lacotte"], 0,
     "Sa période sous l'Occupation lui a valu une exclusion temporaire à la Libération."],
    ["Quel chorégraphe français a fondé le Ballet du XXe siècle ?", ["Maurice Béjart", "Roland Petit", "Serge Lifar", "Jean Babilée"], 0,
     "Son Boléro, créé en 1961, est l'une des chorégraphies les plus reprises au monde."],
    ["Qu'est-ce que la hiérarchie du corps de ballet de l'Opéra de Paris ?", ["Une échelle de grades allant du quadrille à l'étoile", "Un classement annuel", "Une répartition par âge", "Une organisation par répertoire"], 0,
     "L'accès à chaque grade se fait par un concours interne annuel, sauf pour le titre d'étoile.", 3],
  ]),

  notion("am3-architecture-patrimoine", S, "Le patrimoine architectural français",
    "Protection, restauration, valorisation.",
    "La France compte plus de quarante-cinq mille monuments historiques protégés.",
    2, [
    ["Quelle différence sépare classement et inscription au titre des monuments historiques ?", ["Le classement offre une protection plus forte que l'inscription", "L'inscription est plus contraignante", "Le classement est temporaire", "Ce sont deux termes équivalents"], 0,
     "Toute modification d'un monument classé exige une autorisation ministérielle."],
    ["Qu'est-ce qu'un architecte des Bâtiments de France ?", ["Un fonctionnaire donnant son avis sur les travaux en secteur protégé", "Un architecte du patrimoine libéral", "Un restaurateur agréé", "Un conservateur de musée"], 0,
     "Son avis conforme s'impose dans les abords des monuments historiques."],
    ["Qu'est-ce que le périmètre des abords d'un monument historique ?", ["Un rayon de cinq cents mètres, adaptable, soumis à avis", "Une zone de cent mètres", "L'emprise du monument seule", "Le quartier environnant"], 0,
     "Depuis 2016, ce périmètre peut être délimité sur mesure plutôt qu'automatiquement."],
    ["Qu'est-ce qu'un site patrimonial remarquable ?", ["Un dispositif protégeant des ensembles urbains ou paysagers", "Un monument isolé classé", "Un site naturel protégé", "Un label touristique"], 0,
     "Il a remplacé en 2016 les secteurs sauvegardés et les zones de protection du patrimoine."],
    ["Qu'est-ce que la loi Malraux de 1962 ?", ["Une loi créant les secteurs sauvegardés pour protéger les quartiers anciens", "Une loi sur les musées", "Une loi sur les monuments isolés", "Une loi sur l'archéologie"], 0,
     "Elle répondait aux destructions massives de centres anciens dans les années d'après-guerre."],
    ["Qu'est-ce que l'archéologie préventive ?", ["Des fouilles réalisées avant un aménagement susceptible de détruire des vestiges", "Une fouille de recherche", "Une prospection systématique", "Une conservation de site"], 0,
     "L'INRAP en assure une large part en France depuis 2001."],
    ["Qu'est-ce qu'une fouille de sauvetage ?", ["Une fouille d'urgence menée avant destruction d'un site", "Une fouille programmée", "Une restauration de vestiges", "Une prospection aérienne"], 0,
     "Elle vise à documenter ce qui ne peut être conservé en place."],
    ["Qu'est-ce que le loto du patrimoine ?", ["Un jeu dont une part des recettes finance la restauration de monuments en péril", "Une souscription publique", "Un fonds de dotation", "Une taxe affectée"], 0,
     "Lancé en 2018, il a permis de soutenir plusieurs centaines de sites."],
    ["Qu'est-ce que la Fondation du patrimoine ?", ["Un organisme privé d'intérêt général soutenant le patrimoine de proximité", "Un service de l'État", "Une association de propriétaires", "Un fonds européen"], 0,
     "Elle finance surtout des édifices non protégés, souvent ruraux."],
    ["Qu'est-ce que la restauration à l'identique d'un monument ?", ["Une reconstitution respectant l'état antérieur documenté", "Une reconstruction moderne", "Une consolidation minimale", "Une réinterprétation contemporaine"], 0,
     "Elle est discutée : Viollet-le-Duc défendait une restitution idéale, Ruskin la conservation de l'usure.", 3],
  ]),

  notion("am3-design-objet", S, "Le design d'objet",
    "Fonction, production, création.",
    "Le design ne se réduit pas à l'apparence : il conditionne l'usage et la fabrication.",
    2, [
    ["Qu'est-ce que le design industriel ?", ["La conception d'objets destinés à une production en série", "La décoration d'objets", "L'artisanat d'art", "Le stylisme"], 0,
     "Il intègre contraintes de fabrication, d'usage et de coût dès la conception."],
    ["Qu'est-ce que l'ergonomie appliquée au design ?", ["L'adaptation de l'objet aux capacités et limites de l'utilisateur", "La recherche du confort visuel", "L'optimisation de la fabrication", "La réduction du poids"], 0,
     "Elle mobilise anthropométrie, biomécanique et psychologie cognitive."],
    ["Qu'est-ce que l'affordance d'un objet ?", ["Ce que sa forme suggère spontanément comme usage", "Sa facilité d'entretien", "Sa robustesse", "Son adaptabilité"], 0,
     "Une poignée verticale suggère de tirer, une plaque plate de pousser."],
    ["Qu'est-ce qu'un prototype en design ?", ["Un exemplaire d'essai permettant de valider un concept", "Un modèle de série", "Une maquette de présentation", "Un dessin technique"], 0,
     "Il peut être fonctionnel, esthétique ou les deux selon la phase du projet."],
    ["Qu'est-ce que le design thinking ?", ["Une méthode de conception centrée sur l'utilisateur et l'itération", "Une théorie esthétique", "Un style de design", "Une méthode de production"], 0,
     "Elle a été largement diffusée hors du design, avec des critiques sur sa banalisation."],
    ["Qu'est-ce que le mobilier des frères Bouroullec ?", ["Un design français contemporain reconnu internationalement", "Un mobilier Art déco", "Une collection industrielle du XXe siècle", "Un mobilier scandinave"], 0,
     "Ronan et Erwan Bouroullec travaillent pour des éditeurs européens et japonais."],
    ["Quel designer français a marqué les années 1980 et 1990 ?", ["Philippe Starck", "Jean Prouvé", "Pierre Paulin", "Charlotte Perriand"], 0,
     "Il a conçu aussi bien des brosses à dents que des hôtels entiers."],
    ["Quelle designer française a travaillé avec Le Corbusier ?", ["Charlotte Perriand", "Eileen Gray", "Andrée Putman", "Matali Crasset"], 0,
     "Longtemps créditée sous le seul nom de l'agence, sa contribution a été rétablie tardivement."],
    ["Qu'est-ce que le design scandinave ?", ["Un courant privilégiant simplicité, matériaux naturels et fonctionnalité", "Un design minimaliste japonais", "Un style industriel", "Un mouvement des années 1980"], 0,
     "Il s'est développé à partir des années 1930 avec une forte dimension sociale."],
    ["Qu'est-ce que l'éco-conception d'un objet ?", ["Une conception intégrant les impacts environnementaux sur tout le cycle de vie", "L'usage de matériaux recyclés", "Une réduction de l'emballage", "Une fabrication locale"], 0,
     "Les décisions prises en conception déterminent l'essentiel des impacts futurs du produit.", 3],
  ]),

  notion("am3-arts-numeriques", S, "Les arts numériques",
    "Œuvres génératives, interactives, immersives.",
    "L'art numérique pose des problèmes inédits de conservation.",
    2, [
    ["Qu'est-ce que l'art génératif ?", ["Un art où l'œuvre est produite par un système suivant des règles", "Un art assisté par ordinateur", "Un art aléatoire", "Un art programmé manuellement"], 0,
     "L'artiste conçoit le processus plutôt que le résultat final."],
    ["Qu'est-ce qu'une œuvre interactive ?", ["Une œuvre dont le déroulement dépend de l'action du spectateur", "Une œuvre projetée", "Une installation vidéo", "Une œuvre en réseau"], 0,
     "Le spectateur y devient un élément constitutif de l'œuvre."],
    ["Qu'est-ce qu'une installation immersive ?", ["Un dispositif enveloppant le spectateur par l'image et le son", "Une projection sur grand écran", "Une exposition en réalité virtuelle", "Une œuvre sonore spatialisée"], 0,
     "Les expositions immersives grand public ont connu un fort succès depuis 2015."],
    ["Qu'est-ce que le mapping vidéo ?", ["Une projection épousant la forme d'un bâtiment ou d'un objet", "Une cartographie numérique", "Une projection sur écran", "Une modélisation architecturale"], 0,
     "La Fête des Lumières de Lyon en a popularisé l'usage à grande échelle."],
    ["Qu'est-ce que la réalité augmentée ?", ["Une superposition d'éléments virtuels au monde réel", "Une immersion totale virtuelle", "Une projection holographique", "Une simulation informatique"], 0,
     "Elle se distingue de la réalité virtuelle, qui remplace entièrement l'environnement perçu."],
    ["Qu'est-ce que le net art ?", ["Un art conçu spécifiquement pour et par internet", "Un art diffusé en ligne", "Un art numérique exposé sur le web", "Une galerie virtuelle"], 0,
     "Apparu dans les années 1990, il pose des questions aiguës d'archivage."],
    ["Pourquoi les œuvres numériques sont-elles difficiles à conserver ?", ["Matériels, logiciels et formats deviennent rapidement obsolètes", "Elles sont fragiles physiquement", "Elles ne sont pas documentées", "Elles sont trop volumineuses"], 0,
     "L'émulation et la migration sont les deux stratégies principales, toutes deux imparfaites."],
    ["Qu'est-ce que l'art par intelligence artificielle ?", ["Des œuvres produites avec des modèles génératifs entraînés sur des corpus", "Un art robotique", "Un art algorithmique classique", "Un art de programmation"], 0,
     "La question des droits sur les données d'entraînement fait l'objet de nombreux litiges."],
    ["Qu'est-ce que la question de l'auteur dans l'art génératif ?", ["Déterminer qui, du programmeur, de la machine ou du hasard, est auteur", "Une question de propriété matérielle", "Une question de signature", "Une question de datation"], 0,
     "Le droit français exige une empreinte de la personnalité de l'auteur pour reconnaître une œuvre."],
    ["Qu'est-ce qu'un festival d'arts numériques ?", ["Une manifestation présentant créations et recherches en art et technologie", "Un salon professionnel", "Une exposition de jeux vidéo", "Un festival de cinéma numérique"], 0,
     "Ars Electronica, à Linz depuis 1979, en est le plus ancien et le plus reconnu.", 3],
  ]),

  notion("am3-photographie-pratique", S, "Pratiques photographiques",
    "Genres, usages, circulation des images.",
    "La photographie est aujourd'hui le média le plus produit et le moins regardé.",
    2, [
    ["Qu'est-ce que la photographie documentaire ?", ["Une pratique visant à rendre compte d'une réalité sociale sur la durée", "Un reportage d'actualité", "Une photographie d'archive", "Une photographie scientifique"], 0,
     "Elle se distingue du photojournalisme par le temps long et le point de vue d'auteur."],
    ["Qu'est-ce que la photographie de rue ?", ["Une pratique captant la vie publique sans mise en scène", "Une photographie urbaine d'architecture", "Un reportage social", "Une photographie de manifestation"], 0,
     "Elle pose des questions de droit à l'image dans plusieurs pays."],
    ["Qu'est-ce que le portrait photographique en studio ?", ["Un portrait réalisé avec un éclairage et un fond maîtrisés", "Un portrait posé", "Un portrait officiel", "Un portrait de commande"], 0,
     "Le contrôle total de la lumière permet un travail précis sur les volumes du visage."],
    ["Qu'est-ce que la photographie argentique ?", ["Une photographie sur support sensible chimique", "Une photographie noir et blanc", "Une photographie ancienne", "Une photographie sur plaque de verre"], 0,
     "Le nom vient des sels d'argent, sensibles à la lumière."],
    ["Qu'est-ce qu'un tirage photographique ?", ["La réalisation d'une épreuve à partir d'un négatif ou d'un fichier", "Une impression numérique seule", "Une copie d'exposition", "Un agrandissement"], 0,
     "Le tirage est une interprétation : deux tireurs donneront deux résultats différents du même négatif."],
    ["Qu'est-ce qu'une édition limitée en photographie ?", ["Un nombre défini de tirages numérotés d'une même image", "Un tirage unique", "Une série d'exposition", "Un tirage d'artiste"], 0,
     "La rareté organisée fonde une grande partie du marché de la photographie d'art."],
    ["Qu'est-ce que le photobook ?", ["Un livre où la séquence d'images constitue l'œuvre", "Un catalogue d'exposition", "Un album de famille", "Un recueil de photographies"], 0,
     "L'ordre, le rythme et la mise en page y font partie intégrante du propos."],
    ["Qu'est-ce que la retouche en photographie de presse ?", ["Une pratique strictement encadrée par la déontologie", "Une amélioration libre de l'image", "Un recadrage systématique", "Un traitement esthétique courant"], 0,
     "Ajouter ou supprimer un élément est une faute grave, régulièrement sanctionnée dans les concours."],
    ["Qu'est-ce que les métadonnées d'une photographie ?", ["Des informations techniques et descriptives associées au fichier", "Un filigrane", "Une légende visible", "Un identifiant de copyright"], 0,
     "Elles sont souvent supprimées par les réseaux sociaux, ce qui complique l'attribution."],
    ["Qu'est-ce que la photographie participative ?", ["Une pratique associant les personnes photographiées à la démarche", "Une photographie collective", "Une commande publique", "Un projet collaboratif en ligne"], 0,
     "Elle vise à corriger le déséquilibre entre celui qui photographie et celui qui est photographié.", 3],
  ]),

  notion("am3-arts-spectacle-vivant", S, "Le spectacle vivant",
    "Cirque, marionnettes, arts de la rue.",
    "Le cirque contemporain a largement abandonné les numéros animaliers.",
    2, [
    ["Qu'est-ce que le cirque traditionnel ?", ["Un spectacle de numéros juxtaposés sous chapiteau", "Un spectacle narratif", "Un théâtre itinérant", "Un spectacle équestre"], 0,
     "Il naît à Londres à la fin du XVIIIe siècle autour de la voltige équestre."],
    ["Qu'est-ce que le cirque contemporain ?", ["Un cirque privilégiant le récit, la dramaturgie et la mixité des disciplines", "Un cirque moderne sans animaux", "Un cirque de rue", "Un cirque acrobatique"], 0,
     "Il émerge en France dans les années 1970 et 1980."],
    ["Qu'est-ce que le mât chinois ?", ["Une discipline circassienne sur un poteau vertical", "Un agrès de gymnastique", "Une corde lisse", "Un trapèze fixe"], 0,
     "Le tissu aérien et la roue Cyr sont d'autres disciplines contemporaines."],
    ["Qu'est-ce que le théâtre de marionnettes à gaine ?", ["Un théâtre où la marionnette est enfilée sur la main", "Un théâtre de marionnettes à fils", "Un théâtre d'ombres", "Un théâtre de marottes"], 0,
     "Guignol, créé à Lyon vers 1808, en est la figure française la plus connue."],
    ["Qu'est-ce que le bunraku japonais ?", ["Un théâtre de marionnettes manipulées à vue par trois marionnettistes", "Un théâtre d'ombres", "Un théâtre masqué", "Un théâtre dansé"], 0,
     "Il est inscrit au patrimoine culturel immatériel de l'humanité."],
    ["Qu'est-ce que le théâtre d'ombres ?", ["Un spectacle de silhouettes projetées sur un écran translucide", "Un théâtre nocturne", "Un théâtre sans lumière", "Un théâtre de silhouettes découpées exposées"], 0,
     "Le wayang kulit indonésien en est l'une des formes les plus élaborées."],
    ["Qu'est-ce que les arts de la rue ?", ["Des spectacles conçus pour l'espace public", "Des spectacles improvisés", "Des animations de festival", "Des performances militantes"], 0,
     "Ils supposent de composer avec un public non captif et un espace non théâtral."],
    ["Quel festival français est le plus important pour les arts de la rue ?", ["Le festival d'Aurillac", "Le festival de Chalon", "Viva Cité à Sotteville", "Les Rencontres de Chalon seules"], 0,
     "Il se tient chaque août et transforme entièrement la ville pendant plusieurs jours."],
    ["Qu'est-ce que le mime ?", ["Un art du geste et du corps sans parole", "Une pantomime comique", "Un théâtre gestuel avec masque", "Une danse théâtrale"], 0,
     "Étienne Decroux et Marcel Marceau l'ont porté à un haut degré d'élaboration en France."],
    ["Qu'est-ce qu'une compagnie conventionnée ?", ["Une compagnie bénéficiant d'un soutien pluriannuel de l'État ou d'une collectivité", "Une compagnie professionnelle", "Une compagnie subventionnée ponctuellement", "Une compagnie permanente"], 0,
     "Ce cadre lui offre une visibilité budgétaire de trois à quatre ans.", 3],
  ]),

  notion("am3-musique-technique", S, "Enregistrement et production musicale",
    "Studio, prise de son, mixage.",
    "L'enregistrement a transformé la musique en objet reproductible et en objet de création.",
    2, [
    ["Qu'est-ce que le multipiste en studio ?", ["L'enregistrement séparé des différentes sources, mixées ensuite", "Un enregistrement en direct", "Un enregistrement stéréo", "Un mixage en temps réel"], 0,
     "Il permet de retravailler chaque élément indépendamment, ce qui a bouleversé la production."],
    ["Qu'est-ce que la prise de son de proximité ?", ["Un micro placé très près de la source", "Un enregistrement d'ambiance", "Une prise stéréo", "Un enregistrement de salle"], 0,
     "Elle isole la source du contexte acoustique, au prix d'un son moins naturel."],
    ["Qu'est-ce qu'un microphone directionnel ?", ["Un micro captant préférentiellement une direction", "Un micro omnidirectionnel", "Un micro à ruban", "Un micro à condensateur"], 0,
     "Cardioïde, hypercardioïde ou canon selon la sélectivité recherchée."],
    ["Qu'est-ce que la réverbération en enregistrement ?", ["La persistance du son par réflexions multiples dans un espace", "Un écho distinct", "Un effet de distorsion", "Un retard électronique"], 0,
     "Elle peut être naturelle, captée dans une salle, ou simulée par un traitement."],
    ["Qu'est-ce qu'un compresseur audio ?", ["Un traitement réduisant l'écart entre les sons forts et faibles", "Un réducteur de bruit", "Un filtre de fréquences", "Un limiteur de durée"], 0,
     "Son usage excessif a produit ce qu'on appelle la guerre du volume dans les années 2000."],
    ["Qu'est-ce que l'égalisation en mixage ?", ["Un réglage du niveau des différentes bandes de fréquences", "Un équilibrage des pistes", "Une compression douce", "Une correction de phase"], 0,
     "Elle permet de faire coexister des instruments occupant les mêmes registres."],
    ["Qu'est-ce que le mastering ?", ["La dernière étape harmonisant un album avant diffusion", "Le mixage final", "L'enregistrement définitif", "La duplication industrielle"], 0,
     "Il vise la cohérence entre les titres et l'adaptation aux supports de diffusion."],
    ["Qu'est-ce que l'autotune ?", ["Un traitement corrigeant la justesse de la voix", "Un effet de réverbération", "Un synthétiseur vocal", "Un doublage automatique"], 0,
     "Conçu comme un correcteur discret, il est devenu un effet esthétique assumé."],
    ["Qu'est-ce qu'un home studio ?", ["Un studio d'enregistrement personnel à coût réduit", "Un studio professionnel réduit", "Un studio de répétition", "Un studio mobile"], 0,
     "La baisse du prix du matériel numérique a transformé les conditions de production musicale."],
    ["Qu'est-ce que la spatialisation sonore ?", ["Un traitement plaçant les sons dans un espace perçu", "Un mixage stéréo", "Une amplification directionnelle", "Une diffusion multicanal seule"], 0,
     "Les formats immersifs récents permettent de placer une source en hauteur autour de l'auditeur.", 3],
  ]),

  notion("am3-arts-afrique-oceanie", S, "Arts d'Afrique et d'Océanie",
    "Formes, fonctions, circulation.",
    "Les objets présentés comme des œuvres d'art avaient souvent une fonction rituelle précise.",
    2, [
    ["Quelle fonction avaient de nombreux masques africains ?", ["Une fonction rituelle liée à des cérémonies précises", "Une fonction purement décorative", "Une fonction commerciale", "Une fonction protectrice individuelle"], 0,
     "Séparés de leur contexte, ils perdent une grande partie de leur signification."],
    ["Quel royaume africain est célèbre pour ses bronzes de cour ?", ["Le royaume du Bénin", "Le royaume ashanti", "Le royaume du Kongo", "Le royaume du Dahomey"], 0,
     "Ces plaques ornaient le palais royal et documentaient l'histoire de la dynastie."],
    ["Que s'est-il passé lors de l'expédition britannique de 1897 au Bénin ?", ["Le pillage de milliers d'objets aujourd'hui dispersés dans les musées", "Une négociation commerciale", "Un échange diplomatique d'objets", "Une expédition scientifique"], 0,
     "Leur restitution fait l'objet de négociations avec plusieurs pays européens."],
    ["Qu'est-ce que l'art nok ?", ["Une culture nigériane produisant des terres cuites il y a plus de deux mille ans", "Un art contemporain africain", "Un art de cour du XVIIIe siècle", "Un art rupestre saharien"], 0,
     "Ses statuettes comptent parmi les plus anciennes sculptures figuratives d'Afrique subsaharienne."],
    ["Qu'est-ce que l'art rupestre du Sahara ?", ["Des gravures et peintures témoignant d'un Sahara vert", "Un art contemporain touareg", "Un art funéraire égyptien", "Un art de l'âge du bronze"], 0,
     "Le Tassili n'Ajjer conserve des milliers de représentations d'animaux aujourd'hui disparus de la région."],
    ["Qu'est-ce qu'un moai ?", ["Une statue monumentale de l'île de Pâques", "Un totem maori", "Une sculpture aborigène", "Un masque mélanésien"], 0,
     "Près de mille exemplaires, taillés dans le tuf volcanique entre les XIIe et XVIIe siècles."],
    ["Qu'est-ce que le tatouage polynésien traditionnel ?", ["Un marquage codifié indiquant statut, lignée et parcours", "Une décoration esthétique", "Un rite de guérison", "Une pratique guerrière"], 0,
     "Le mot tatouage lui-même vient du tahitien tatau."],
    ["Qu'est-ce que l'art aborigène du désert ?", ["Une peinture évoquant des récits du Temps du Rêve", "Un art décoratif contemporain", "Un art rupestre uniquement", "Un art de sable éphémère seul"], 0,
     "La peinture acrylique sur toile s'est développée à partir des années 1970 à Papunya."],
    ["Qu'est-ce que le Temps du Rêve dans les cultures aborigènes ?", ["Un cadre de récits fondateurs liant territoire, ancêtres et lois", "Une mythologie de la création seule", "Un rituel onirique", "Une pratique chamanique"], 0,
     "Il structure à la fois la cosmologie, le droit et la cartographie du territoire."],
    ["Quel musée parisien présente les arts d'Afrique, d'Asie, d'Océanie et des Amériques ?", ["Le musée du quai Branly", "Le musée Guimet", "Le musée de l'Homme", "Le musée Dapper"], 0,
     "Ouvert en 2006, il a hérité de collections du musée de l'Homme et du musée des Arts africains et océaniens.", 3],
  ]),

  notion("am3-mode-histoire", S, "L'histoire du vêtement",
    "Formes, usages, distinctions sociales.",
    "Le vêtement a longtemps été un marqueur juridique du rang social.",
    2, [
    ["Qu'est-ce qu'une loi somptuaire ?", ["Une loi réglementant le luxe vestimentaire selon le rang", "Une taxe sur le textile", "Une norme de fabrication", "Une réglementation commerciale"], 0,
     "Elles interdisaient à certains rangs de porter soie, fourrure ou certaines couleurs."],
    ["Pourquoi le pourpre était-il réservé aux élites antiques ?", ["Son extraction à partir de coquillages était extrêmement coûteuse", "Sa couleur était sacrée", "Sa fabrication était secrète", "Il était importé de loin"], 0,
     "Il fallait des milliers de murex pour teindre un seul vêtement."],
    ["Quel vêtement masculin s'impose au XIXe siècle en Europe ?", ["Le costume sombre trois pièces", "La redingote colorée", "L'habit à queue", "Le gilet brodé"], 0,
     "La grande renonciation masculine a fait disparaître couleurs et ornements du vêtement d'homme."],
    ["Quand le pantalon devient-il légalement porté par les femmes en France ?", ["L'interdiction datant de 1800 n'a été abrogée qu'en 2013", "En 1900", "En 1968", "En 1946"], 0,
     "L'ordonnance était tombée en désuétude depuis longtemps, mais restait formellement en vigueur."],
    ["Qu'est-ce que le corset au XIXe siècle ?", ["Un sous-vêtement rigide modelant la silhouette féminine", "Une pièce de robe", "Un vêtement de protection", "Un accessoire de cérémonie"], 0,
     "Sa disparition progressive au début du XXe siècle accompagne un changement du rapport au corps."],
    ["Qu'est-ce que le prêt-à-porter a changé pour le vêtement ?", ["Il a rendu la mode accessible par la production en tailles standardisées", "Il a supprimé la couture sur mesure", "Il a réduit la qualité", "Il a créé les grandes marques"], 0,
     "Il suppose une normalisation des morphologies, elle-même construite statistiquement."],
    ["Qu'est-ce que le jean à l'origine ?", ["Un vêtement de travail robuste en toile rivetée", "Un vêtement de loisir", "Un uniforme militaire", "Un vêtement de cow-boy"], 0,
     "Levi Strauss et Jacob Davis en déposent le brevet en 1873."],
    ["Qu'est-ce que le tailleur Chanel ?", ["Un ensemble féminin en tweed devenu emblème d'élégance fonctionnelle", "Une robe du soir", "Un manteau de cérémonie", "Un uniforme de maison"], 0,
     "Sa coupe sans col et son confort rompaient avec la mode structurée d'après-guerre."],
    ["Qu'est-ce que la haute couture représente économiquement ?", ["Une activité déficitaire servant de vitrine à des marques", "Le cœur du chiffre d'affaires du luxe", "Un marché de masse", "Une production semi-industrielle"], 0,
     "Les revenus proviennent surtout des parfums, de la maroquinerie et des licences."],
    ["Qu'est-ce que le vintage dans la mode ?", ["Le réemploi de vêtements anciens comme choix esthétique", "Une reproduction de modèles anciens", "Un style rétro contemporain", "Une collection d'archives"], 0,
     "Son succès récent participe aussi d'une critique de la production textile de masse.", 3],
  ]),

  notion("am3-musique-france-institutions", S, "La vie musicale en France",
    "Institutions, enseignement, diffusion.",
    "La France dispose d'un réseau dense d'établissements d'enseignement musical public.",
    2, [
    ["Qu'est-ce qu'un conservatoire à rayonnement régional ?", ["Un établissement public d'enseignement artistique de haut niveau", "Un conservatoire national supérieur", "Une école privée agréée", "Un centre de formation professionnelle"], 0,
     "Il existe une quarantaine de conservatoires à rayonnement régional en France."],
    ["Combien de conservatoires nationaux supérieurs de musique la France compte-t-elle ?", ["Deux, à Paris et à Lyon", "Un seul", "Cinq", "Dix"], 0,
     "Ils forment les musiciens destinés à une carrière professionnelle de haut niveau."],
    ["Quelle institution parisienne réunit plusieurs salles et un musée de la musique ?", ["La Philharmonie de Paris", "l'Opéra Bastille", "Le Théâtre des Champs-Élysées", "La Salle Pleyel"], 0,
     "Ouverte en 2015, elle intègre la Cité de la musique créée en 1995."],
    ["Quel orchestre est l'orchestre national de Radio France ?", ["l'Orchestre national de France", "l'Orchestre de Paris", "l'Orchestre philharmonique de Radio France seul", "l'Orchestre de l'Opéra"], 0,
     "Radio France en abrite deux : le National et le Philharmonique."],
    ["Qu'est-ce que l'Orchestre de Paris ?", ["Un orchestre symphonique fondé en 1967, résident à la Philharmonie", "L'orchestre de l'Opéra de Paris", "Un orchestre de chambre", "L'orchestre de Radio France"], 0,
     "Il succède à la Société des concerts du Conservatoire, fondée en 1828."],
    ["Qu'est-ce qu'une scène de musiques actuelles ?", ["Un lieu labellisé de diffusion et d'accompagnement des musiques actuelles", "Une salle de concert privée", "Un festival labellisé", "Un studio de répétition public"], 0,
     "Le label SMAC concerne plus de cent lieux en France."],
    ["Qu'est-ce que le Centre national de la musique ?", ["Un établissement public soutenant la filière musicale française", "Un conservatoire national", "Un institut de recherche musicale", "Une société de gestion de droits"], 0,
     "Créé en 2020, il regroupe plusieurs organismes de soutien préexistants."],
    ["Qu'est-ce qu'une société de gestion collective des droits musicaux ?", ["Un organisme percevant et répartissant les droits pour ses membres", "Un syndicat d'artistes", "Un label collectif", "Une agence de production"], 0,
     "La SACEM pour les auteurs et compositeurs, la SPEDIDAM et l'ADAMI pour les interprètes."],
    ["Qu'est-ce que le dispositif Orchestre à l'école ?", ["Un programme constituant un orchestre au sein d'une classe", "Un cours de musique renforcé", "Une chorale scolaire", "Un partenariat avec un conservatoire"], 0,
     "Chaque élève reçoit un instrument et joue en orchestre dès la première année."],
    ["Qu'est-ce que la Fête de la musique a de particulier ?", ["Elle repose sur des concerts gratuits et souvent amateurs dans l'espace public", "Elle réunit des professionnels", "Elle se tient en salle", "Elle est payante"], 0,
     "Faites de la musique : le jeu de mots fondateur en résume le principe participatif.", 3],
  ]),

  notion("am3-couleurs-symbolique", S, "La symbolique des couleurs",
    "Histoire sociale et culturelle des couleurs.",
    "La signification d'une couleur change radicalement selon les époques et les cultures.",
    2, [
    ["Quel historien français a consacré son œuvre à l'histoire des couleurs ?", ["Michel Pastoureau", "Georges Duby", "Jacques Le Goff", "Philippe Ariès"], 0,
     "Il a montré que la couleur est d'abord un fait social et culturel."],
    ["Quelle était la place du bleu dans l'Antiquité romaine ?", ["Une couleur dévalorisée, associée aux barbares", "La couleur du pouvoir", "Une couleur sacrée", "La couleur du deuil"], 0,
     "Elle devient au contraire prestigieuse en Europe à partir du XIIe siècle."],
    ["Pourquoi le bleu devient-il valorisé au Moyen Âge ?", ["Il est associé au manteau de la Vierge et adopté par la royauté", "Il devient moins coûteux", "Il remplace le pourpre", "Il vient d'Orient"], 0,
     "Le bleu de France, semé de fleurs de lys, en fait une couleur royale."],
    ["Quelle couleur symbolisait le deuil en Europe avant le noir ?", ["Le blanc", "Le gris", "Le violet", "Le brun"], 0,
     "Les reines de France portaient le deuil blanc, d'où l'expression reine blanche."],
    ["Quelle couleur est associée au deuil dans plusieurs cultures d'Asie ?", ["Le blanc", "Le noir", "Le rouge", "Le jaune"], 0,
     "Ce contraste avec l'Europe contemporaine illustre le caractère culturel de ces associations."],
    ["Quelle était la symbolique du vert au Moyen Âge en Europe ?", ["Une couleur instable, associée au hasard et à la traîtrise", "Une couleur d'espérance", "Une couleur royale", "Une couleur sacrée"], 0,
     "Les pigments verts étaient chimiquement instables, ce qui a nourri cette symbolique."],
    ["Pourquoi le rouge a-t-il longtemps été la couleur du pouvoir ?", ["Les teintures rouges solides étaient les plus coûteuses à produire", "Il évoquait le sang", "Il était sacré", "Il était rare dans la nature"], 0,
     "Le kermès puis la cochenille en fournissaient les nuances les plus recherchées."],
    ["Quand le rose devient-il une couleur associée aux filles ?", ["Au XXe siècle, l'association étant récente et variable", "Au Moyen Âge", "Au XVIIIe siècle", "Dans l'Antiquité"], 0,
     "Au début du XXe siècle, certains manuels américains recommandaient encore le rose pour les garçons."],
    ["Qu'est-ce que le noir dans la mode depuis le XIXe siècle ?", ["Une couleur d'élégance et de sobriété devenue dominante", "Une couleur de deuil uniquement", "Une couleur populaire", "Une couleur de travail"], 0,
     "La petite robe noire de Chanel, en 1926, en a fait un emblème d'élégance moderne."],
    ["Qu'est-ce que le drapeau tricolore doit à la symbolique des couleurs ?", ["Une combinaison politique plutôt qu'une symbolique préexistante", "Une signification religieuse", "Une tradition héraldique ancienne", "Un choix esthétique"], 0,
     "Le bleu et le rouge de Paris encadrant le blanc royal traduisaient une alliance politique.", 3],
  ]),

  notion("am3-critique-art", S, "La critique et le regard sur l'art",
    "Jugement, réception, valeur.",
    "Le jugement esthétique se forme historiquement : ce qui est admiré change avec le temps.",
    2, [
    ["Qu'est-ce que la critique d'art ?", ["Un discours analysant et évaluant les œuvres pour un public", "Une expertise de marché", "Une histoire de l'art", "Une théorie esthétique"], 0,
     "Diderot est souvent considéré comme le premier critique d'art moderne, avec ses Salons."],
    ["Quel écrivain français a écrit des critiques du Salon au XIXe siècle ?", ["Charles Baudelaire", "Victor Hugo", "Gustave Flaubert", "Émile Zola seul"], 0,
     "Zola a également défendu Manet dans la presse avec une grande vigueur."],
    ["Qu'est-ce que le goût selon la sociologie de l'art ?", ["Une disposition socialement construite plutôt qu'un don individuel", "Une préférence innée", "Un jugement universel", "Une réaction émotionnelle pure"], 0,
     "Bourdieu a montré la forte corrélation entre origine sociale et pratiques culturelles."],
    ["Qu'est-ce que la réception d'une œuvre ?", ["La façon dont un public l'interprète et lui donne sens", "Sa reconnaissance officielle", "Son accueil critique", "Sa diffusion commerciale"], 0,
     "Une même œuvre peut être reçue de façon opposée selon les époques."],
    ["Qu'est-ce que la valeur d'une œuvre d'art ?", ["Une construction mêlant reconnaissance critique, rareté et marché", "Une qualité intrinsèque", "Un prix de vente", "Une valeur historique"], 0,
     "Ces dimensions ne coïncident pas toujours, comme le montrent de nombreux artistes reconnus tardivement."],
    ["Qu'est-ce que l'art dit dégénéré ?", ["Une catégorie de propagande nazie visant l'art moderne", "Un courant artistique", "Une critique esthétique", "Un mouvement d'avant-garde"], 0,
     "L'exposition de 1937 à Munich visait à ridiculiser les avant-gardes avant de les faire disparaître."],
    ["Qu'est-ce que le réalisme socialiste ?", ["Une esthétique officielle imposée dans les régimes communistes", "Un courant réaliste du XIXe siècle", "Une école de peinture russe", "Un mouvement documentaire"], 0,
     "Toute œuvre devait être compréhensible, édifiante et conforme à la ligne du parti."],
    ["Qu'est-ce que le scandale artistique ?", ["Une réaction publique violente à une œuvre transgressant des normes", "Une controverse de marché", "Une polémique de spécialistes", "Une critique négative"], 0,
     "Nombre d'œuvres aujourd'hui canoniques ont d'abord provoqué des scandales."],
    ["Qu'est-ce que le syndrome de Stendhal ?", ["Un malaise décrit face à une accumulation d'œuvres d'art", "Une passion pour l'art italien", "Un trouble de la perception esthétique", "Une théorie de la beauté"], 0,
     "Son statut clinique est très discuté ; il relève surtout de l'anecdote littéraire."],
    ["Pourquoi certains artistes sont-ils reconnus après leur mort ?", ["La reconnaissance dépend de circuits et de conjonctures qui peuvent leur échapper", "Leur œuvre est incomprise de leur vivant", "Ils manquent de talent commercial", "Le marché privilégie les artistes disparus"], 0,
     "Van Gogh n'a vendu presque aucune toile de son vivant, ce qui n'est pas un cas isolé.", 3],
  ]),

  notion("am3-art-espace-public", S, "L'art dans l'espace public",
    "Commandes, monuments, controverses.",
    "Une œuvre installée dans l'espace public s'impose à tous, y compris à ceux qui ne l'ont pas choisie.",
    2, [
    ["Qu'est-ce qu'une commande publique artistique ?", ["Une œuvre commandée par une collectivité pour un lieu accessible", "Une acquisition de musée", "Un achat d'œuvre existante", "Un mécénat d'entreprise"], 0,
     "Elle suppose un dialogue entre artiste, commanditaire et usagers du lieu."],
    ["Qu'est-ce qu'un monument commémoratif ?", ["Une œuvre destinée à entretenir le souvenir d'un événement ou d'une personne", "Une sculpture décorative", "Un édifice historique", "Un mémorial funéraire"], 0,
     "La France compte plus de trente mille monuments aux morts, presque un par commune."],
    ["Quand la plupart des monuments aux morts français ont-ils été érigés ?", ["Dans les années 1920", "Après 1945", "Avant 1914", "Dans les années 1960"], 0,
     "Une loi de 1919 a prévu une subvention de l'État pour leur édification."],
    ["Qu'est-ce que le débat sur le déboulonnage de statues ?", ["Une controverse sur le maintien de monuments honorant des figures contestées", "Un problème de conservation", "Une question d'urbanisme", "Un débat esthétique"], 0,
     "Les réponses vont du retrait à la contextualisation par un panneau explicatif."],
    ["Qu'est-ce que la contextualisation d'un monument controversé ?", ["L'ajout d'éléments explicatifs sans retirer l'œuvre", "Un déplacement en musée", "Une restauration", "Une transformation de l'œuvre"], 0,
     "Elle permet de conserver la trace du passé tout en explicitant les critiques."],
    ["Qu'est-ce qu'une œuvre éphémère dans l'espace public ?", ["Une installation temporaire prévue pour disparaître", "Une œuvre fragile", "Une performance", "Une œuvre non protégée"], 0,
     "Christo et Jeanne-Claude ont fait de cette temporalité un principe de travail."],
    ["Quel couple d'artistes a empaqueté le Pont-Neuf et l'Arc de triomphe ?", ["Christo et Jeanne-Claude", "Gilbert et George", "Les Poirier", "Anne et Patrick Poirier"], 0,
     "L'Arc de triomphe a été empaqueté en 2021, après la mort des deux artistes."],
    ["Qu'est-ce que le mobilier urbain artistique ?", ["Un équipement fonctionnel conçu comme une création", "Une sculpture utilitaire", "Un aménagement décoratif", "Un abri d'artiste"], 0,
     "Les entrées de métro de Guimard en sont l'exemple français le plus célèbre."],
    ["Qu'est-ce que l'appropriation d'une œuvre publique par les habitants ?", ["Le fait qu'ils s'en emparent par l'usage, le surnom ou le détournement", "Une dégradation", "Une revendication de propriété", "Une adoption officielle"], 0,
     "Elle est souvent le signe le plus sûr de la réussite d'une intervention artistique."],
    ["Pourquoi l'art dans l'espace public suscite-t-il des controverses ?", ["Il s'impose à tous sans possibilité d'évitement", "Il coûte cher", "Il est mal expliqué", "Il est souvent abstrait"], 0,
     "Le contribuable n'a pas choisi l'œuvre, à la différence du visiteur d'un musée.", 3],
  ]),
];
