/**
 * Cinéma & Médias, deuxième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Cinéma & Médias";

export const CG_CINEMA_MEDIAS_2: SeedSkill[] = [
  notion("cm2-metiers-cinema", S, "Les métiers du cinéma",
    "Qui fait quoi sur un tournage et en postproduction.",
    "Un générique de film compte souvent plusieurs centaines de noms, pour des métiers très distincts.",
    2, [
    ["Que fait un directeur de la photographie ?", ["Il définit la lumière et le cadre avec le réalisateur", "Il tient la caméra pendant les prises", "Il choisit les décors et les lieux de tournage", "Il monte les images une fois le tournage entièrement achevé"], 0,
     "Il dirige l'équipe image et prend les décisions techniques d'exposition et d'optique."],
    ["Que fait un chef opérateur du son ?", ["Il enregistre le son pendant le tournage", "Il compose la musique originale du film", "Il mixe le film en postproduction, en auditorium", "Il double les dialogues en studio"], 0,
     "Le perchman travaille sous sa direction, micro au bout d'une perche."],
    ["Que fait un monteur ?", ["Il assemble et rythme les plans pour construire le film", "Il installe les décors sur le plateau", "Il règle les caméras avant chaque prise", "Il synchronise seulement le son avec l'image, et rien d'autre"], 0,
     "Le montage est souvent décrit comme la dernière réécriture du scénario."],
    ["Que fait un scripte sur un tournage ?", ["Il assure la continuité entre les plans et tient le rapport de tournage", "Il écrit le scénario avant le tournage", "Il note les dialogues improvisés par les comédiens", "Il gère le planning de présence des acteurs"], 0,
     "Sans lui, les raccords de costume, de position ou de lumière deviennent incohérents au montage."],
    ["Que fait un producteur de cinéma ?", ["Il réunit le financement et assume la responsabilité économique du film", "Il dirige les acteurs sur le plateau", "Il distribue le film dans les salles de cinéma", "Il supervise le montage du film"], 0,
     "Il détient les droits sur le film et engage l'équipe."],
    ["Que fait un directeur de casting ?", ["Il recherche et propose les comédiens pour les rôles", "Il forme les acteurs avant le tournage", "Il négocie les contrats des comédiens et leur rémunération", "Il dirige les figurants pendant les prises"], 0,
     "La profession n'a longtemps été distinguée par aucun prix : l'Oscar du meilleur casting n'a été créé qu'en 2024, et les César n'ont pas d'équivalent."],
    ["Que fait un chef décorateur ?", ["Il conçoit l'univers visuel des lieux du film", "Il choisit les lieux de tournage lors des repérages", "Il installe l'éclairage du plateau", "Il dessine les costumes des personnages"], 0,
     "Il travaille en étroite relation avec le directeur de la photographie sur les couleurs et les matières."],
    ["Que fait un étalonneur ?", ["Il ajuste couleurs et contrastes de l'image finale", "Il calibre les caméras avant le tournage", "Il mesure la lumière sur le plateau pendant les prises", "Il synchronise l'image et le son au montage"], 0,
     "L'étalonnage numérique permet aujourd'hui des transformations chromatiques considérables."],
    ["Que fait un mixeur son ?", ["Il équilibre dialogues, ambiances, bruitages et musique", "Il enregistre le son direct sur le tournage", "Il compose la bande originale du film", "Il réalise les bruitages en auditorium"], 0,
     "Le mixage est la dernière étape avant la livraison du film."],
    ["Qu'est-ce qu'un régisseur général ?", ["Le responsable de l'organisation matérielle du tournage", "L'assistant du réalisateur", "Le gestionnaire du budget", "Le responsable des décors"], 0,
     "Autorisations, transports, repas et logistique dépendent de lui : sans lui, rien ne tourne.", 3],
  ]),

  notion("cm2-scenario", S, "L'écriture de scénario",
    "Structure, personnages, dialogue : comment se construit un récit filmé.",
    "Un scénario n'est pas une œuvre littéraire mais un document de travail destiné à disparaître.",
    2, [
    ["Qu'est-ce qu'un synopsis ?", ["Un résumé bref de l'histoire d'un film", "Le scénario complet du film avec ses dialogues", "Le découpage technique du film, plan par plan", "La liste des séquences numérotées du film"], 0,
     "Il tient généralement en une à quelques pages et sert à présenter le projet."],
    ["Qu'est-ce qu'un traitement ?", ["Un récit détaillé du film en prose, sans dialogues", "Une version entièrement dialoguée du scénario", "Une note d'intention du réalisateur", "Un découpage du film plan par plan"], 0,
     "Il précède l'écriture de la continuité dialoguée."],
    ["Qu'est-ce que le découpage technique ?", ["La transcription du scénario en plans avec indications de mise en scène", "Le montage prévisionnel du film, établi bien avant le premier jour de tournage", "La liste des décors et des accessoires nécessaires à chaque journée de tournage", "Le plan de travail organisant les journées de tournage"], 0,
     "Certains réalisateurs le rédigent minutieusement, d'autres improvisent sur le plateau."],
    ["Qu'est-ce qu'un storyboard ?", ["Une mise en images dessinée du découpage", "Un plan de tournage établi jour par jour par la production", "Une maquette du décor construite avant le tournage", "Un scénario illustré diffusé pour la promotion du film"], 0,
     "Indispensable pour les scènes à effets spéciaux, qui doivent être planifiées avant le tournage."],
    ["Qu'est-ce que la structure en trois actes ?", ["Exposition, confrontation, résolution", "Début, milieu et fin, sans aucune transition", "Trois lieux de tournage qui se succèdent dans le film", "Trois points de vue narratifs qui alternent"], 0,
     "Héritée du théâtre, elle domine le cinéma de fiction commercial."],
    ["Qu'est-ce qu'un point de bascule dans un scénario ?", ["Un événement qui fait basculer l'action dans une nouvelle direction", "Le point culminant de l'action du film", "La révélation finale qui dénoue l'intrigue", "La première scène d'action du récit"], 0,
     "Il intervient classiquement à la fin du premier acte et relance le récit."],
    ["Qu'est-ce qu'un MacGuffin ?", ["Un objet ou enjeu qui motive l'intrigue sans importer en lui-même", "Un personnage secondaire déterminant pour l'intrigue", "Un rebondissement placé à la toute fin du récit", "Un décor récurrent d'un film à l'autre"], 0,
     "Hitchcock a popularisé le terme : ce que contient la valise importe moins que la course pour l'obtenir."],
    ["Qu'est-ce qu'un arc narratif de personnage ?", ["La transformation intérieure du personnage au fil du récit", "Sa trajectoire géographique d'un lieu de tournage à l'autre", "La succession ordonnée de l'ensemble de ses actions dans le film", "Son rôle dans l'intrigue principale"], 0,
     "Certains récits reposent au contraire sur des personnages qui ne changent pas."],
    ["Qu'est-ce qu'une adaptation cinématographique ?", ["La transposition d'une œuvre préexistante à l'écran", "Un remake d'un film ancien tourné quelques années plus tôt", "Une traduction des dialogues pour le doublage", "Une version modifiée pour être diffusée dans un autre pays"], 0,
     "Elle suppose des droits d'adaptation négociés auprès de l'auteur ou de ses ayants droit."],
    ["Qu'est-ce que le doctorat de script ?", ["Une réécriture confiée à un scénariste extérieur, souvent non crédité", "La supervision du scénario par le producteur du film", "Une validation juridique du texte avant le tournage", "Une expertise universitaire du scénario"], 0,
     "La pratique est courante à Hollywood et donne parfois lieu à des arbitrages sur le générique.", 3],
  ]),

  notion("cm2-effets-speciaux", S, "Les effets spéciaux",
    "Trucages mécaniques, images de synthèse, capture de mouvement.",
    "Un effet spécial réussi est un effet que le spectateur ne remarque pas.",
    2, [
    ["Quelle différence sépare effets spéciaux et effets visuels ?", ["Les premiers sont réalisés sur le plateau, les seconds en postproduction", "Les seconds sont numériques par définition, les premiers toujours mécaniques", "Ce sont deux mots parfaitement synonymes", "Les premiers ne concernent que le son"], 0,
     "Explosions et maquillages sont des effets spéciaux ; les incrustations sont des effets visuels."],
    ["Qu'est-ce que le fond vert ?", ["Un fond uni permettant d'incruster un autre décor", "Un écran servant à la projection arrière", "Un filtre de couleur monté sur l'objectif", "Un panneau réfléchissant la lumière sur le plateau"], 0,
     "Le vert et le bleu sont choisis car éloignés des teintes de peau humaine."],
    ["Qu'est-ce que la capture de mouvement ?", ["L'enregistrement des mouvements d'un acteur pour animer un personnage numérique", "Un ralenti mécanique", "Un suivi automatique de la caméra sur le plateau", "Une stabilisation de l'image au tournage"], 0,
     "Le personnage de Gollum, en 2001, en a été une démonstration marquante."],
    ["Qu'est-ce que le rotoscoping ?", ["Le détourage image par image d'un élément filmé", "Un mode de projection en salle", "Une rotation de la caméra sur son axe", "Un effet de flou de mouvement ajouté à la postproduction"], 0,
     "Inventé en 1915 pour l'animation, il est aujourd'hui largement assisté par ordinateur."],
    ["Quel film de 1993 marque un tournant pour les créatures en images de synthèse ?", ["Jurassic Park", "Terminator 2", "Toy Story", "Le Seigneur des anneaux"], 0,
     "Terminator 2, deux ans plus tôt, avait montré la voie avec un personnage métallique liquide."],
    ["Qu'est-ce qu'une maquette au cinéma ?", ["Un décor ou objet miniature filmé pour simuler une grande échelle", "Un modèle de personnage en volume", "Un plan de décor entièrement dessiné avant sa construction en atelier", "Un accessoire de tournage"], 0,
     "Longtemps indispensables, elles restent utilisées pour leur rendu naturel de la lumière."],
    ["Qu'est-ce que le matte painting ?", ["Un décor peint ou numérique complétant l'image filmée", "Un fond volontairement flouté", "Un cache posé devant l'objectif", "Un filtre de couleur peint à la main sur la lentille de l'objectif"], 0,
     "Autrefois peint sur verre devant la caméra, il est aujourd'hui composé numériquement."],
    ["Qu'est-ce que le rendu en images de synthèse ?", ["Le calcul de l'image finale à partir d'une scène en trois dimensions", "La modélisation des objets en volume", "L'animation des personnages image par image", "L'éclairage virtuel de la scène"], 0,
     "Certains plans complexes demandent des heures de calcul par image sur des fermes de serveurs."],
    ["Qu'est-ce qu'un deepfake appliqué au cinéma ?", ["Un remplacement de visage par apprentissage automatique", "Un vieillissement numérique du visage par retouche image par image", "Un doublage synchronisé sur les lèvres", "Une reconstitution à partir d'archives"], 0,
     "Son usage soulève des questions de droit à l'image, notamment pour les acteurs décédés."],
    ["Qu'est-ce que le rajeunissement numérique d'un acteur ?", ["Une retouche image par image de son visage pour le montrer plus jeune", "Un maquillage assisté par ordinateur", "Un filtre appliqué en direct au tournage", "Un doublage assuré par un acteur beaucoup plus jeune"], 0,
     "Coûteux et long, il est souvent combiné à une doublure corporelle.", 3],
  ]),

  notion("cm2-genres-cinema", S, "Les genres cinématographiques",
    "Western, comédie musicale, horreur, documentaire : codes et évolutions.",
    "Un genre est un contrat implicite entre le film et son spectateur.",
    2, [
    ["Quel genre cinématographique est le plus spécifiquement américain ?", ["Le western", "La comédie romantique", "Le film noir", "Le film catastrophe"], 0,
     "Il met en scène le mythe de la frontière et la fondation de la nation."],
    ["Quel réalisateur est le plus associé au western classique ?", ["John Ford", "Howard Hawks", "Sergio Leone", "Anthony Mann"], 0,
     "Monument Valley, qu'il a filmé à de multiples reprises, est devenu l'image même du genre."],
    ["Qu'est-ce que le western spaghetti ?", ["Un western produit en Europe, souvent en Italie et en Espagne", "Un western parodique et burlesque", "Un western américain tourné à petit budget dans les studios de série B", "Un western tourné dans les années 1930"], 0,
     "Sergio Leone en est la figure majeure, avec les musiques d'Ennio Morricone."],
    ["Qu'est-ce que la comédie musicale au cinéma ?", ["Un film où chant et danse font partie intégrante du récit", "Un film racontant la vie de musiciens", "Un film où la musique d'accompagnement occupe une large place", "Une adaptation d'opérette pour l'écran"], 0,
     "Son âge d'or hollywoodien s'étend des années 1930 aux années 1950."],
    ["Quel film français de 1964 est intégralement chanté ?", ["Les Parapluies de Cherbourg", "Les Demoiselles de Rochefort", "Une femme est une femme", "Peau d'âne"], 0,
     "Jacques Demy et Michel Legrand y suppriment tout dialogue parlé."],
    ["Qu'est-ce que le film noir ?", ["Un genre marqué par le fatalisme, la ville nocturne et la corruption", "Un film tourné en noir et blanc", "Un film policier de facture française", "Un film d'épouvante tourné dans les premières années du parlant américain"], 0,
     "Le nom fut donné par des critiques français découvrant les films américains après 1945."],
    ["Comment Hitchcock distinguait-il le suspense de la surprise ?", ["Le suspense suppose que le spectateur en sache plus que le personnage", "Le suspense repose sur le seul effet de choc", "La surprise dure toujours plus longtemps", "Le suspense concerne l'action tandis que la surprise concerne le dialogue"], 0,
     "Une bombe sous une table crée du suspense si le spectateur la voit ; sinon elle ne produit qu'une surprise brève."],
    ["Qu'est-ce que le documentaire au cinéma ?", ["Un film construit à partir du réel, avec un point de vue assumé", "Un enregistrement parfaitement objectif de la réalité, sans aucun parti pris", "Un reportage télévisé de longue durée", "Un film tourné sans scénario"], 0,
     "Toute mise en forme documentaire suppose des choix : cadrage, montage, commentaire."],
    ["Quel film de 1922 est souvent cité comme premier documentaire de long métrage ?", ["Nanouk l'Esquimau", "Berlin, symphonie d'une grande ville", "L'Homme à la caméra", "Le Sang des bêtes"], 0,
     "Robert Flaherty y avait fait rejouer certaines scènes, ce qui a nourri un débat durable."],
    ["Qu'est-ce que le cinéma direct ou cinéma vérité ?", ["Un courant documentaire tournant en léger, sans mise en scène apparente", "Un cinéma d'actualités filmées", "Un documentaire didactique et pédagogique", "Un film d'archives commenté en voix off"], 0,
     "Les caméras portables et le son synchrone des années 1960 l'ont rendu techniquement possible.", 3],
  ]),

  notion("cm2-animation", S, "Le cinéma d'animation",
    "Techniques, écoles, grandes œuvres.",
    "L'animation n'est pas un genre mais un ensemble de techniques applicables à tous les genres.",
    2, [
    ["Qu'est-ce que l'animation image par image ?", ["La création du mouvement par photographies successives d'états fixes", "Un ralenti mécanique", "Un dessin animé entièrement réalisé par ordinateur, image après image", "Une capture des mouvements d'un acteur"], 0,
     "Le principe est identique quelle que soit la technique, du dessin à la pâte à modeler."],
    ["Combien d'images par seconde un dessin animé traditionnel utilise-t-il souvent ?", ["Douze, chaque dessin étant tenu deux images", "Vingt-quatre dessins tous différents par seconde", "Six", "Trente"], 0,
     "L'animation sur deux permet de diviser par deux le nombre de dessins sans gêner la perception."],
    ["Qu'est-ce que la technique de la stop-motion ?", ["L'animation d'objets réels photographiés position par position", "Un arrêt sur image en cours de projection", "Un ralenti progressif de l'action", "Une animation entièrement calculée par ordinateur, sans objet réel"], 0,
     "Wallace et Gromit ou L'Étrange Noël de monsieur Jack en sont des exemples célèbres."],
    ["Quel studio français est connu pour ses longs métrages d'animation d'auteur ?", ["Folimage", "Gaumont Animation", "Xilam", "Mac Guff"], 0,
     "La France est le troisième producteur mondial d'animation, derrière les États-Unis et le Japon."],
    ["Quel film d'animation français de 2003 se déroule dans un univers cycliste ?", ["Les Triplettes de Belleville", "Persepolis", "Kirikou et la Sorcière", "Ernest et Célestine, d'après Gabrielle Vincent"], 0,
     "Sylvain Chomet y raconte l'histoire presque sans dialogues."],
    ["Quel film d'animation français de 1998 est inspiré de contes africains ?", ["Kirikou et la Sorcière", "Azur et Asmar", "Les Triplettes de Belleville", "Le Roi et l'Oiseau"], 0,
     "Michel Ocelot en a réalisé plusieurs suites et un univers graphique reconnaissable."],
    ["Quel film d'animation français commencé dans les années 1940 sort finalement en 1980 ?", ["Le Roi et l'Oiseau", "Kirikou et la Sorcière", "La Bergère et le Ramoneur seule", "Gwen"], 0,
     "Paul Grimault et Jacques Prévert ont mis plus de trente ans à en achever la version qu'ils souhaitaient."],
    ["Quel studio japonais a produit Le Voyage de Chihiro ?", ["Le studio Ghibli", "Toei Animation", "Madhouse", "Production I.G"], 0,
     "Fondé en 1985 par Hayao Miyazaki, Isao Takahata et Toshio Suzuki."],
    ["Quelle particularité l'animation japonaise présente-t-elle souvent ?", ["Elle s'adresse à des publics de tous âges, avec des genres très variés", "Elle est réservée au jeune public", "Elle est exclusivement dessinée à la main, toujours en deux dimensions et jamais en volume", "Elle est toujours adaptée de mangas préexistants"], 0,
     "Les catégories éditoriales japonaises distinguent les publics par âge et par genre."],
    ["Quel film du studio Ghibli remporte l'Oscar du meilleur film d'animation en 2003 ?", ["Le Voyage de Chihiro", "Princesse Mononoké", "Le Château ambulant, de 2004", "Mon voisin Totoro, de 1988"], 0,
     "Il avait déjà obtenu l'Ours d'or à Berlin l'année précédente.", 3],
  ]),

  notion("cm2-economie-cinema", S, "L'économie du cinéma",
    "Financement, distribution, exploitation : comment un film gagne ou perd de l'argent.",
    "Un film ne devient rentable que bien après son passage en salles.",
    2, [
    ["Comment se répartit le prix d'un billet de cinéma en France ?", ["Entre la salle, le distributeur, le producteur et des taxes affectées", "Intégralement pour la salle qui projette le film", "Moitié pour la salle, moitié pour le producteur", "Principalement pour le distributeur du film"], 0,
     "La taxe affectée alimente le fonds de soutien géré par le CNC."],
    ["Qu'est-ce qu'un distributeur de films ?", ["L'intermédiaire qui met le film sur le marché et organise sa sortie", "Le propriétaire du réseau de salles dans lesquelles le film est projeté", "Le producteur exécutif chargé d'organiser le tournage sur le terrain", "L'exportateur qui vend le film à l'étranger"], 0,
     "Il finance souvent une partie du film en échange des droits de diffusion."],
    ["Qu'est-ce qu'un minimum garanti ?", ["Une avance versée par un distributeur au producteur", "Un plancher de recettes garanti à la salle de cinéma", "Un salaire minimum garanti aux techniciens du tournage", "Une garantie bancaire exigée avant le début de la production"], 0,
     "Elle se récupère sur les recettes avant tout partage."],
    ["Qu'est-ce que le préachat par une chaîne de télévision ?", ["L'achat des droits de diffusion avant le tournage, participant au financement", "L'achat des droits après la sortie du film en salle", "Une coproduction menée avec une chaîne de télévision", "Un droit de première diffusion réservé à la chaîne"], 0,
     "Il constitue une part majeure du financement du cinéma français."],
    ["Qu'est-ce que le box-office ?", ["Le classement des films selon leurs recettes ou entrées", "Le bureau où sont vendus les billets à l'entrée d'une salle", "La billetterie informatisée d'un complexe de cinéma", "Le chiffre d'affaires annuel d'une société de distribution de films"], 0,
     "La France compte en entrées, la plupart des pays en recettes, ce qui rend les comparaisons délicates."],
    ["Qu'est-ce qu'un film à budget indépendant ?", ["Un film financé hors des grands studios", "Un film tourné avec un budget très réduit", "Un film qui n'a pas trouvé de distributeur", "Un film entièrement autoproduit par son réalisateur"], 0,
     "L'indépendance désigne le mode de financement, non nécessairement le niveau de budget."],
    ["Qu'est-ce que le marché du film de Cannes ?", ["Un marché professionnel où s'achètent et se vendent les droits", "Une section de la compétition officielle", "Une vente de matériel de tournage d'occasion", "Un concours de projets de films en développement"], 0,
     "Il est l'un des principaux lieux de transaction de l'industrie mondiale."],
    ["Qu'est-ce que le crédit d'impôt cinéma ?", ["Un dispositif fiscal encourageant les tournages sur un territoire", "Une subvention directe versée au producteur avant le tournage du film", "Un prêt à taux bonifié accordé par une banque publique aux producteurs", "Une exonération de TVA sur les billets de cinéma"], 0,
     "La concurrence entre pays et régions sur ces dispositifs est vive."],
    ["Qu'est-ce que la sortie en salle simultanée avec le streaming ?", ["Une pratique remettant en cause la chronologie des médias", "Une avant-première mondiale organisée en salle", "Une diffusion en direct de la séance", "Une exclusivité réservée à une seule plateforme"], 0,
     "Expérimentée pendant la pandémie, elle a suscité de fortes tensions avec les exploitants de salles."],
    ["Pourquoi les studios misent-ils sur les franchises ?", ["Elles réduisent le risque grâce à un public déjà acquis", "Elles coûtent nettement moins cher à produire qu'un film original", "Elles se tournent plus vite que les autres films", "Elles échappent aux taxes qui pèsent sur les autres films"], 0,
     "Cette logique explique la domination des suites et adaptations au box-office mondial.", 3],
  ]),

  notion("cm2-critique-cinema", S, "Analyser un film",
    "Outils d'analyse, courants critiques, vocabulaire.",
    "Analyser un film, c'est décrire ce qu'il fait avant d'expliquer ce qu'il signifie.",
    2, [
    ["Qu'est-ce que la mise en scène au cinéma ?", ["L'organisation de tout ce qui apparaît dans le cadre et de sa durée", "La seule direction des acteurs sur le plateau", "Le choix des décors et des costumes", "Le découpage technique établi avant le tournage"], 0,
     "Elle englobe décor, lumière, mouvement, jeu et rapport au cadre."],
    ["Qu'est-ce que le hors-champ ?", ["Ce qui existe dans l'univers du film sans être visible à l'écran", "Une scène entièrement tournée puis retirée lors du montage définitif", "Un décor construit pour le film mais qui n'a finalement jamais été filmé", "Un plan de coupe inséré entre deux scènes"], 0,
     "Le suggérer plutôt que le montrer est l'un des ressorts les plus puissants du cinéma."],
    ["Qu'est-ce que la profondeur de champ dans l'analyse d'un film ?", ["L'étendue de netteté qui peut hiérarchiser ou égaliser les plans de l'image", "La distance séparant la caméra de son sujet", "Le nombre de plans successifs d'une séquence", "L'épaisseur réelle du décor construit"], 0,
     "Citizen Kane en a fait un usage systématique, plusieurs actions restant lisibles simultanément."],
    ["Qu'est-ce qu'une focalisation narrative au cinéma ?", ["Le point de vue depuis lequel l'histoire est racontée", "La mise au point optique réglée par l'assistant caméra", "Le centre géométrique de l'image projetée sur l'écran de la salle", "Le sujet principal que le cadrage du plan met en évidence"], 0,
     "Elle peut changer au cours du film, ce qui modifie ce que le spectateur sait."],
    ["Qu'est-ce que le rythme d'un film ?", ["La combinaison de la durée des plans, du mouvement et du son", "La seule vitesse du montage des plans", "Le tempo de la musique du générique", "La longueur totale du film en minutes"], 0,
     "Un film à plans longs peut être plus tendu qu'un film à montage rapide."],
    ["Qu'est-ce qu'un plan subjectif ?", ["Un plan montrant ce que voit un personnage", "Un plan accompagné d'un commentaire en voix off", "Un plan filmé caméra à l'épaule au plus près", "Un plan filmé depuis un point de vue extérieur"], 0,
     "Son usage prolongé est rare car il fatigue le spectateur et brise l'identification."],
    ["Qu'est-ce que le montage alterné ?", ["L'alternance de deux actions simultanées en des lieux différents", "Un montage présentant les scènes dans l'ordre inverse de leur récit", "Une succession de plans très courts, tous de durée rigoureusement égale", "Un montage procédant par associations d'idées"], 0,
     "Griffith en a systématisé l'usage pour créer du suspense."],
    ["Qu'est-ce que le montage parallèle ?", ["L'alternance de deux actions sans simultanéité nécessaire, pour les comparer", "Un montage projeté sur deux écrans côte à côte", "Un montage synchrone de l'image et du son", "Un montage comparant deux versions d'un même film"], 0,
     "Il produit un sens par rapprochement, indépendamment de la chronologie."],
    ["Qu'est-ce que le regard caméra ?", ["Un personnage regardant directement l'objectif", "Le cadrage choisi par l'opérateur de prise de vue", "Le point de vue personnel du réalisateur sur son sujet", "Un plan filmé depuis la caméra principale du dispositif"], 0,
     "Il brise l'illusion et interpelle le spectateur ; c'est une transgression volontaire des conventions."],
    ["Qu'est-ce que l'analyse filmique universitaire cherche à éviter ?", ["Confondre le récit du film avec un jugement de valeur", "Toute interprétation personnelle du sens des images du film", "Le vocabulaire technique de la mise en scène et du montage", "La description précise des plans du film"], 0,
     "La description précise précède l'interprétation : c'est le principe méthodologique de base.", 3],
  ]),

  notion("cm2-television-formats", S, "Les formats télévisuels",
    "Séries, journaux, magazines : comment la télévision structure ses programmes.",
    "La grille de programmes est un objet économique autant qu'éditorial.",
    2, [
    ["Qu'est-ce que le prime time ?", ["La tranche horaire de plus forte audience en soirée", "Le journal télévisé diffusé au tout début de la soirée", "La première diffusion d'un programme sur une chaîne nationale", "La tranche horaire réservée aux programmes de la matinée"], 0,
     "En France, elle commence traditionnellement vers vingt et une heures."],
    ["Qu'est-ce qu'une grille de programmes ?", ["La planification hebdomadaire des émissions d'une chaîne", "Le catalogue des programmes disponibles à l'achat", "Le budget de production annuel de la chaîne", "La liste des rediffusions prévues dans l'été"], 0,
     "Sa stabilité vise à fidéliser des habitudes de consommation."],
    ["Qu'est-ce qu'un pilote de série ?", ["Le premier épisode servant à tester ou vendre le projet", "L'épisode le plus coûteux à produire dans la saison entière", "Le résumé de l'ensemble de la série remis aux diffuseurs", "Le dernier épisode diffusé d'une saison"], 0,
     "Aux États-Unis, de nombreux pilotes sont tournés puis abandonnés sans diffusion."],
    ["Qu'est-ce qu'un showrunner ?", ["Le responsable créatif et exécutif d'une série", "Le producteur exécutif employé par la chaîne diffuseur", "Le réalisateur principal des épisodes d'une saison", "Le directeur de la fiction au sein d'une chaîne"], 0,
     "La fonction, née à la télévision américaine, mêle écriture, production et supervision."],
    ["Qu'est-ce qu'une série feuilletonnante ?", ["Une série dont l'intrigue se poursuit d'un épisode à l'autre", "Une série diffusée chaque jour de la semaine", "Une série comptant un très grand nombre d'épisodes", "Une série dont les épisodes sont indépendants"], 0,
     "Elle s'oppose au format bouclé, où chaque épisode se suffit à lui-même."],
    ["Qu'est-ce que le binge-watching ?", ["Le visionnage de plusieurs épisodes à la suite", "Une diffusion accélérée des épisodes d'une saison", "Un marathon télévisé programmé par la chaîne un dimanche", "Une rediffusion intégrale d'une saison complète"], 0,
     "Les plateformes ont adapté leur écriture à cette pratique, en atténuant les résumés d'épisode."],
    ["Qu'est-ce qu'un format en télévision ?", ["Un concept d'émission vendu et adapté d'un pays à l'autre", "La durée standard d'un programme", "La définition de l'image diffusée", "Le genre auquel appartient une émission"], 0,
     "Le marché des formats représente une part significative du commerce audiovisuel mondial."],
    ["Qu'est-ce qu'une part d'audience ?", ["La proportion de téléspectateurs présents devant leur poste regardant une chaîne", "Le nombre total de spectateurs ayant regardé le programme, du début jusqu'à la fin", "Le taux de pénétration d'une chaîne dans l'ensemble des foyers équipés d'un téléviseur", "Le pourcentage de la population touchée par la chaîne"], 0,
     "Elle se distingue de l'audience en valeur absolue, souvent plus parlante."],
    ["Qu'est-ce que le direct en télévision ?", ["Une diffusion simultanée à l'événement", "Un programme diffusé sans aucun montage préalable", "Une émission enregistrée sans public en studio", "Une captation d'un spectacle diffusée sans montage"], 0,
     "Il impose des contraintes techniques et juridiques particulières, notamment sur les propos tenus."],
    ["Qu'est-ce que la télévision de rattrapage ?", ["La mise à disposition d'un programme après sa diffusion", "Une chaîne consacrée aux rediffusions", "Un enregistrement personnel fait par le spectateur", "Un service payant de vidéo à la demande"], 0,
     "Sa durée de mise à disposition est encadrée par des accords avec les producteurs.", 3],
  ]),

  notion("cm2-radio-formats", S, "Les formats radiophoniques",
    "Information, musique, parole : comment se construit une antenne.",
    "La radio reste le média le plus écouté en situation de mobilité.",
    2, [
    ["Qu'est-ce qu'une matinale radio ?", ["La tranche d'information et de débat du début de matinée", "La toute première émission de la journée", "Un journal résumé en quelques minutes", "Une revue de presse quotidienne"], 0,
     "C'est généralement la tranche la plus écoutée et la plus rentable d'une station généraliste."],
    ["Qu'est-ce qu'une radio de format musical ?", ["Une station construite autour d'une programmation musicale ciblée", "Une station diffusant uniquement de la musique, sans aucune parole", "Une radio thématique consacrée aux seuls concerts de musique classique", "Une webradio automatisée sans animateur"], 0,
     "Le format définit un public cible, une rotation et un habillage sonore cohérents."],
    ["Qu'est-ce que la rotation musicale ?", ["La fréquence de repassage d'un titre à l'antenne", "L'ordre dans lequel les titres d'un album se suivent", "Le changement saisonnier de la programmation musicale", "La sélection hebdomadaire des nouveautés musicales"], 0,
     "Les titres en forte rotation peuvent passer plusieurs fois par jour."],
    ["Qu'est-ce qu'un habillage d'antenne ?", ["L'ensemble des éléments sonores identifiant une station", "Le décor du studio d'enregistrement", "La charte graphique de la station", "Le générique musical d'une seule émission"], 0,
     "Jingles, virgules et lits musicaux structurent l'écoute et identifient la station."],
    ["Qu'est-ce qu'un flash d'information ?", ["Un bref bulletin d'actualité à heure fixe", "Une édition spéciale consacrée à un événement", "Une alerte urgente interrompant les programmes", "Un résumé de l'actualité en fin de journée"], 0,
     "Sa brièveté impose une hiérarchisation très stricte de l'information."],
    ["Qu'est-ce qu'une revue de presse radiophonique ?", ["Une sélection commentée d'articles parus le jour même", "Un résumé des dépêches d'agence tombées pendant la nuit", "Une critique argumentée du travail de la presse écrite", "Un panorama hebdomadaire des magazines"], 0,
     "L'exercice suppose de citer les sources et de restituer des points de vue divergents."],
    ["Qu'est-ce qu'un documentaire radiophonique ?", ["Un récit sonore construit à partir de témoignages et d'ambiances", "Un reportage long diffusé en plusieurs parties", "Une émission composée d'archives sonores", "Une lecture de textes documentaires à l'antenne"], 0,
     "La création radiophonique française en a fait une forme reconnue, notamment avec les Nuits de France Culture."],
    ["Qu'est-ce qu'une fiction radiophonique ?", ["Une œuvre dramatique conçue pour l'écoute seule", "Une adaptation de roman lue au micro par un comédien", "Un feuilleton télévisé dont on ne diffuse que le son", "Un enregistrement d'une représentation théâtrale"], 0,
     "La panique provoquée par la Guerre des mondes en 1938 en illustre la puissance d'évocation."],
    ["Qu'est-ce qu'un podcast de conversation ?", ["Un format long fondé sur l'échange entre plusieurs voix", "Une interview radiophonique en tête à tête", "Un débat de plateau télévisé sans image", "Une table ronde entre professionnels du secteur"], 0,
     "Sa liberté de durée le distingue nettement des contraintes de la grille radio."],
    ["Pourquoi la radio conserve-t-elle une audience importante ?", ["Elle s'écoute en faisant autre chose", "Elle coûte moins cher que les autres médias", "Elle est plus rapide que la télévision à réagir", "Elle touche surtout un public jeune et urbain"], 0,
     "L'écoute en voiture et en cuisine reste un pilier de son audience quotidienne.", 3],
  ]),

  notion("cm2-desinformation", S, "Désinformation et vérification",
    "Mécanismes, acteurs, outils de vérification.",
    "Une fausse information circule plus vite qu'un démenti, et son démenti la fait parfois circuler davantage.",
    2, [
    ["Quelle différence sépare mésinformation et désinformation ?", ["L'intention de tromper", "L'ampleur de la diffusion du message", "Le support employé pour la diffuser", "La gravité des conséquences constatées"], 0,
     "Diffuser une fausse information sans le savoir n'est pas de la désinformation au sens strict."],
    ["Qu'est-ce que la malinformation ?", ["La diffusion d'informations vraies dans le but de nuire", "Une information mal formulée par la rédaction", "Une erreur de traduction d'un texte étranger", "Une information incomplète, publiée trop vite"], 0,
     "La divulgation malveillante de données privées authentiques en est un exemple."],
    ["Qu'est-ce que l'effet de rebond d'un démenti ?", ["Le démenti peut renforcer la mémorisation de la fausse information", "Le démenti n'atteint jamais le public que la fausse information a convaincu", "Le démenti fait naître de nouvelles rumeurs autour du même événement", "Le démenti est toujours plus lent que la rumeur"], 0,
     "Les recherches recommandent de réaffirmer le fait exact plutôt que de répéter l'erreur."],
    ["Qu'est-ce qu'une ferme à trolls ?", ["Une organisation produisant massivement des contenus manipulatoires", "Un groupe de commentateurs hostiles à un média", "Un forum de discussion strictement modéré", "Un réseau de robots diffusant de la publicité"], 0,
     "Plusieurs enquêtes ont documenté leur usage dans des campagnes d'influence étatiques."],
    ["Qu'est-ce qu'un bot sur les réseaux sociaux ?", ["Un compte automatisé publiant ou relayant des contenus", "Un compte anonyme dont l'identité ne peut être vérifiée", "Un compte piraté puis utilisé à l'insu de son titulaire", "Un compte publicitaire ouvert par une marque commerciale"], 0,
     "Leur détection est difficile : certains imitent finement un comportement humain."],
    ["Qu'est-ce que l'astroturfing ?", ["La simulation d'un mouvement populaire spontané", "Un financement participatif d'une campagne politique", "Une campagne publicitaire conçue pour devenir virale", "Un lobbying déclaré auprès des élus"], 0,
     "Le mot vient d'une marque de gazon artificiel : une fausse pelouse pour un faux mouvement de terrain."],
    ["Qu'est-ce qu'un deepfake ?", ["Une vidéo truquée par apprentissage automatique", "Un montage d'images d'archives", "Une photographie retouchée à la main", "Un faux compte entièrement automatisé"], 0,
     "Le repérer tient autant à l'examen du contexte de diffusion qu'à l'analyse du fichier."],
    ["Qu'est-ce qu'une source primaire en vérification ?", ["Un document ou témoin direct de l'événement", "Un article de référence publié par un grand journal", "Une agence de presse reprise par les rédactions", "Un expert reconnu et cité par les rédactions"], 0,
     "Remonter à la source primaire est le principe de base de toute vérification sérieuse."],
    ["Qu'est-ce que le biais d'ancrage dans la réception d'une information ?", ["La première information reçue influence durablement le jugement", "La tendance à croire les autorités officielles", "La préférence spontanée pour les informations récentes", "La confiance accordée au témoignage de ses proches"], 0,
     "Il explique pourquoi une première version erronée résiste aux corrections ultérieures."],
    ["Que prévoit le droit français contre la diffusion de fausses nouvelles ?", ["Des sanctions limitées à des cas précis, notamment en période électorale", "Une interdiction générale de tout mensonge exprimé publiquement dans les médias", "Une censure préalable de l'ensemble des contenus publiés en ligne en France", "Une obligation de rectification imposée à tous les médias"], 0,
     "La liberté d'expression protège largement l'erreur ; seuls certains cas ciblés sont sanctionnés.", 3],
  ]),

  notion("cm2-reseaux-sociaux", S, "Les réseaux sociaux",
    "Modèles, usages, effets sur le débat public.",
    "Chaque réseau social impose une forme d'expression par son architecture même.",
    2, [
    ["Qu'est-ce qu'un réseau social au sens technique ?", ["Un service permettant de créer un profil et des liens avec d'autres utilisateurs", "Un site où des inconnus discutent par messages publics", "Une messagerie permettant d'écrire à plusieurs personnes en même temps", "Un forum organisé par thèmes et par sujets de discussion"], 0,
     "La visibilité des liens entre profils est une caractéristique fondatrice du modèle."],
    ["Qu'est-ce que la modération de contenu ?", ["Le contrôle des publications selon des règles définies par la plateforme", "La censure exercée par l'État sur les publications", "L'encadrement juridique des messages publicitaires diffusés sur internet", "La vérification des faits avancés dans une publication"], 0,
     "Elle combine outils automatiques et modérateurs humains, souvent sous-traités à l'étranger."],
    ["Qu'est-ce que le signalement d'un contenu ?", ["Le fait pour un utilisateur d'alerter la plateforme sur une publication", "Une plainte judiciaire", "Un blocage de compte", "Une notification administrative"], 0,
     "Le règlement européen sur les services numériques encadre désormais le traitement de ces signalements."],
    ["Qu'est-ce que la viralité d'un contenu ?", ["Sa capacité à être massivement partagé en peu de temps", "La qualité éditoriale du contenu, de son écriture et de ses sources", "L'audience totale cumulée par le compte qui publie", "La durée pendant laquelle il reste visible en ligne"], 0,
     "Les contenus suscitant colère ou indignation circulent statistiquement plus vite."],
    ["Qu'est-ce qu'un influenceur ?", ["Une personne dont l'audience est mobilisée à des fins de recommandation", "Un créateur de contenu populaire", "Un expert d'un domaine, reconnu par ses pairs et invité à s'exprimer", "Un journaliste qui publie sans rédaction derrière lui"], 0,
     "La loi française de 2023 encadre leurs obligations de transparence commerciale."],
    ["Qu'est-ce que le shadow banning ?", ["Une réduction non annoncée de la visibilité d'un compte", "La suspension temporaire d'un compte, notifiée à son auteur", "Le blocage d'un compte par un très grand nombre d'autres utilisateurs", "L'exclusion d'un compte des recommandations publicitaires"], 0,
     "Sa réalité et son ampleur sont difficiles à établir de l'extérieur, faute de transparence des algorithmes."],
    ["Qu'est-ce que la modération algorithmique ?", ["Un tri automatique des contenus par apprentissage machine", "Le classement des contenus par ordre de publication", "Une modération assurée par les utilisateurs eux-mêmes, sans intervention", "Un filtrage reposant sur une liste de mots interdits"], 0,
     "Elle traite des volumes que nul humain ne pourrait examiner, au prix de nombreuses erreurs."],
    ["Qu'est-ce que l'économie des créateurs ?", ["Un modèle où des individus vivent directement de leur audience", "L'industrie du divertissement diffusé sur internet et ses sociétés de production", "Le marché de la publicité diffusée sur les plateformes", "Le financement participatif de projets culturels"], 0,
     "Abonnements, dons et partenariats en constituent les principales sources."],
    ["Qu'est-ce que le cyberharcèlement en meute ?", ["Une attaque coordonnée ou massive contre une personne en ligne", "Un désaccord exprimé publiquement entre deux comptes", "La critique répétée d'un même contenu par plusieurs comptes indépendants", "Le signalement d'une publication par plusieurs personnes"], 0,
     "Le droit français permet de le sanctionner même si chaque auteur n'a agi qu'une fois."],
    ["Quel effet les réseaux sociaux ont-ils sur le débat public selon les recherches ?", ["Des effets réels mais plus nuancés et contextuels que ne le disent les discours alarmistes", "Une polarisation du débat public systématique, prouvée et mesurée partout", "Aucun effet mesurable sur la formation des opinions", "Une amélioration générale de la qualité de l'information"], 0,
     "Les résultats varient fortement selon les pays, les plateformes et les publics étudiés.", 3],
  ]),

  notion("cm2-cinema-francais-2", S, "Le cinéma français depuis 1980",
    "Comédies populaires, cinéma d'auteur, nouvelle génération.",
    "Le cinéma français est l'un des rares en Europe à conserver une forte part de marché nationale.",
    2, [
    ["Quel courant esthétique marque le cinéma français des années 1980 ?", ["Le cinéma du look", "Le naturalisme social", "La nouvelle vague tardive", "Le réalisme poétique"], 0,
     "Beineix, Besson et Carax en sont les figures, avec une esthétique très travaillée."],
    ["Quel film de 1995 met en scène une journée dans une cité de banlieue ?", ["La Haine", "Le Thé au harem d'Archimède", "L'Esquive", "Ma 6-T va crack-er"], 0,
     "Mathieu Kassovitz y obtient le prix de la mise en scène à Cannes."],
    ["Quelle réalisatrice française obtient la Palme d'or en 2021 ?", ["Julia Ducournau", "Céline Sciamma", "Claire Denis", "Mia Hansen-Løve"], 0,
     "Deuxième femme à l'obtenir, vingt-huit ans après Jane Campion."],
    ["Quel film français de 2011 dépasse dix-neuf millions d'entrées ?", ["Intouchables", "Bienvenue chez les Ch'tis", "Les Visiteurs", "Le Fabuleux Destin d'Amélie Poulain"], 0,
     "Il a également connu un large succès international, rare pour un film français."],
    ["Quel film de Jean-Pierre Jeunet sort en 2001 et connaît un succès mondial ?", ["Le Fabuleux Destin d'Amélie Poulain", "Delicatessen", "La Cité des enfants perdus", "Un long dimanche de fiançailles"], 0,
     "Son image très retouchée numériquement a fait l'objet de nombreux commentaires."],
    ["Quelle réalisatrice française a construit une œuvre sur l'adolescence et la construction de soi ?", ["Céline Sciamma", "Claire Denis", "Catherine Breillat", "Rebecca Zlotowski"], 0,
     "Naissance des pieuvres, Tomboy et Bande de filles forment une trilogie sur cet âge-là."],
    ["Quel film français obtient la Palme d'or en 2008 sur le monde scolaire ?", ["Entre les murs", "La Graine et le Mulet", "Le Fils de l'autre", "Polisse"], 0,
     "Laurent Cantet y fait jouer des collégiens dans leur propre rôle."],
    ["Quel réalisateur français filme depuis quarante ans la banlieue marseillaise ?", ["Robert Guédiguian", "Cédric Klapisch", "Bertrand Tavernier", "Jacques Audiard"], 0,
     "L'Estaque et une troupe fidèle d'acteurs traversent l'ensemble de son œuvre."],
    ["Quelle particularité le cinéma français conserve-t-il en Europe ?", ["Une part de marché nationale élevée et une production abondante", "Un budget moyen supérieur", "Une absence d'aides publiques", "Un réseau de salles réduit"], 0,
     "Environ deux cent cinquante films produits par an, avec une part de marché nationale souvent supérieure à trente-cinq pour cent."],
    ["Qu'est-ce que la Fête du cinéma en France ?", ["Une opération annuelle de tarif réduit dans toutes les salles", "Un festival national", "Une semaine de projections gratuites", "Une remise de prix populaire"], 0,
     "Créée en 1985, elle vise à ramener en salle des publics occasionnels.", 3],
  ]),

  notion("cm2-acteurs-jeu", S, "Le jeu d'acteur",
    "Méthodes, écoles, direction d'acteurs.",
    "Il n'existe pas une méthode de jeu mais plusieurs traditions concurrentes.",
    2, [
    ["Quelle méthode russe influence durablement le jeu d'acteur au XXe siècle ?", ["Le système de Stanislavski", "La biomécanique de Meyerhold seule", "La méthode Copeau du Vieux-Colombier", "Le jeu brechtien"], 0,
     "Il repose sur la mémoire affective et la recherche des motivations du personnage."],
    ["Qu'est-ce que l'Actors Studio ?", ["Une école new-yorkaise développant une méthode inspirée de Stanislavski", "Un studio de production de cinéma installé à New York dans les années 1940", "Une agence de placement d'acteurs", "Un cours de diction et de pose de voix"], 0,
     "Lee Strasberg y forma Marlon Brando, James Dean, Al Pacino et bien d'autres."],
    ["Qu'est-ce que la distanciation brechtienne appliquée au jeu ?", ["L'acteur montre son personnage au lieu de s'y fondre", "Un jeu très retenu, presque entièrement immobile", "Un jeu directement adressé au public assis dans la salle", "Un jeu dépourvu de toute émotion"], 0,
     "Elle vise à maintenir l'esprit critique du spectateur plutôt que son identification."],
    ["Qu'est-ce que le jeu naturaliste au cinéma ?", ["Un jeu cherchant à reproduire les comportements ordinaires", "Un jeu entièrement improvisé, sans texte ni indication du réalisateur", "Un jeu laissé sans la moindre direction d'acteur", "Un jeu proche du documentaire"], 0,
     "Le gros plan a rendu le jeu appuyé du muet impraticable dans le cinéma parlant."],
    ["Qu'est-ce qu'un acteur non professionnel ?", ["Une personne sans formation ni carrière d'acteur engagée pour un rôle", "Un figurant sans texte", "Un acteur amateur venu du théâtre de province", "Un débutant encore en cours de formation"], 0,
     "Le néoréalisme italien en a fait un principe esthétique."],
    ["Qu'est-ce que la direction d'acteurs ?", ["Le travail du réalisateur pour orienter le jeu", "L'écriture des dialogues et des scènes du film", "Le choix des comédiens du film", "La répétition des scènes avec les comédiens avant la prise"], 0,
     "Les approches vont de l'indication technique très précise à la mise en situation."],
    ["Qu'est-ce que le doublage ?", ["Le remplacement des voix originales par des voix dans une autre langue", "L'enregistrement du son direct au tournage", "La postsynchronisation d'un acteur sur sa propre voix", "L'ajout de bruitages en auditorium"], 0,
     "La France est l'un des pays où il est le plus systématique, contrairement aux pays nordiques."],
    ["Qu'est-ce que la postsynchronisation ?", ["Le réenregistrement des dialogues par l'acteur après le tournage", "Le doublage du film dans une langue étrangère par d'autres acteurs", "Le mixage final", "L'ajout d'une voix off au montage"], 0,
     "Elle est parfois imposée par des conditions de tournage rendant le son direct inexploitable."],
    ["Qu'est-ce qu'une doublure ?", ["Une personne remplaçant l'acteur pour certaines scènes", "Un second rôle du film", "Un acteur chargé du doublage", "Une répétition de la scène menée juste avant la prise définitive"], 0,
     "Cascadeurs, doublures lumière et doublures corps ont des fonctions distinctes."],
    ["Qu'est-ce qu'un coordinateur d'intimité ?", ["Un professionnel encadrant le tournage des scènes intimes", "Un directeur de casting spécialisé dans le choix de certains rôles", "Un conseiller juridique de production", "Un assistant de production sur le plateau"], 0,
     "Ce métier s'est développé dans le sillage du mouvement MeToo pour protéger les comédiens.", 3],
  ]),

  notion("cm2-musique-film", S, "La musique de film",
    "Fonction, compositeurs, procédés.",
    "La musique de film travaille souvent à l'insu du spectateur.",
    2, [
    ["Quelle est la fonction principale d'une musique de film ?", ["Orienter l'émotion et la lecture des images", "Combler les silences du dialogue", "Illustrer l'époque où se déroule le récit", "Signaler les changements de scène au spectateur"], 0,
     "Elle peut aussi contredire l'image, ce qui produit un effet d'ironie ou de malaise."],
    ["Quel compositeur italien a signé les musiques des westerns de Sergio Leone ?", ["Ennio Morricone", "Nino Rota", "Riz Ortolani", "Piero Piccioni, jazzman"], 0,
     "Il a composé pour plus de cinq cents films en soixante ans de carrière."],
    ["Quel compositeur américain a écrit les musiques de nombreux films de Spielberg ?", ["John Williams", "Jerry Goldsmith", "Hans Zimmer", "James Horner"], 0,
     "Ses thèmes reposent souvent sur des leitmotivs associés aux personnages."],
    ["Quel compositeur italien travaille avec Fellini ?", ["Nino Rota", "Ennio Morricone", "Armando Trovajoli", "Carlo Rustichelli"], 0,
     "Il a aussi composé la musique du Parrain."],
    ["Quel compositeur français est associé aux films de Jacques Demy ?", ["Michel Legrand", "Georges Delerue", "Maurice Jarre", "Philippe Sarde"], 0,
     "Il signe notamment la partition intégralement chantée des Parapluies de Cherbourg."],
    ["Qu'est-ce qu'une musique diégétique ?", ["Une musique dont la source existe dans l'univers du film", "La musique du générique", "La bande originale composée spécialement pour accompagner le film", "Une musique préexistante réutilisée"], 0,
     "Un poste de radio à l'écran produit une musique diégétique, contrairement à l'orchestre invisible."],
    ["Qu'est-ce qu'un leitmotiv musical au cinéma ?", ["Un thème associé à un personnage ou une idée", "Un refrain répété tout au long", "Le thème principal qui revient tout au long du film", "Une transition musicale entre deux scènes"], 0,
     "Le procédé est emprunté à l'opéra wagnérien."],
    ["Qu'est-ce qu'une musique temporaire au montage ?", ["Une musique préexistante posée provisoirement avant la composition définitive", "Une musique d'essai composée pour le montage", "Un enregistrement fait lors d'une répétition", "Une piste de travail utilisée sans en détenir les droits"], 0,
     "Elle influence souvent fortement la commande finale, au risque d'un résultat imitatif."],
    ["Qu'est-ce qu'un spotting de musique ?", ["La séance déterminant où placer la musique dans le film", "L'enregistrement de l'orchestre en studio d'enregistrement", "Le mixage musical du film", "Le choix du compositeur par la production"], 0,
     "Réalisateur, monteur et compositeur y décident des entrées et sorties de musique."],
    ["Pourquoi certains films utilisent-ils des chansons préexistantes ?", ["Pour ancrer une époque ou créer un contraste immédiat", "Pour réduire les coûts d'une bande originale sur mesure", "Par manque de compositeur disponible", "Pour faciliter le montage des séquences"], 0,
     "Les droits d'utilisation peuvent coûter bien plus cher qu'une composition originale.", 3],
  ]),

  notion("cm2-histoire-presse", S, "L'histoire de la presse",
    "Naissance, âge d'or, crise du modèle.",
    "La presse quotidienne française a atteint son apogée de diffusion avant 1914.",
    2, [
    ["Quel périodique français est créé en 1631 par Théophraste Renaudot ?", ["La Gazette", "Le Journal des savants", "Le Mercure galant", "Les Nouvelles ordinaires"], 0,
     "Il bénéficiait d'un privilège royal et servait aussi la communication du pouvoir."],
    ["Quand la presse française connaît-elle son apogée de diffusion ?", ["Avant la Première Guerre mondiale", "Dans les années 1950, après-guerre", "Dans les années 1930, avant la guerre", "Après 1945, à la Libération"], 0,
     "Le Petit Parisien tirait alors à plus d'un million cinq cent mille exemplaires."],
    ["Qu'est-ce que la presse à un sou au XIXe siècle ?", ["Une presse populaire à bas prix financée par la publicité", "Une presse gratuite distribuée dans la rue", "Une presse d'opinion militante financée par les partis politiques", "Une presse d'annonces commerciales"], 0,
     "Émile de Girardin en France en fut le pionnier avec La Presse, en 1836."],
    ["Qu'est-ce qu'un roman-feuilleton ?", ["Un roman publié par épisodes dans un journal", "Un roman populaire vendu à bas prix en librairie", "Une nouvelle illustrée de gravures", "Un supplément littéraire du dimanche"], 0,
     "Il servait à fidéliser les lecteurs. Dumas, Sue et Balzac y ont écrit."],
    ["Quel quotidien français est fondé en 1944 à la demande du général de Gaulle ?", ["Le Monde", "Le Figaro", "Libération", "France-Soir"], 0,
     "Hubert Beuve-Méry en fut le premier directeur, avec une exigence marquée d'indépendance."],
    ["Quel quotidien français est fondé en 1973 par Jean-Paul Sartre et Serge July ?", ["Libération", "Le Monde", "L'Humanité", "Le Matin de Paris"], 0,
     "Il refusait au départ toute publicité et pratiquait l'égalité des salaires."],
    ["Qu'est-ce qu'une agence de presse photographique ?", ["Une structure vendant des images d'actualité aux rédactions", "Un studio de photographie de portrait", "Un service photographique interne à la rédaction d'un grand journal", "Une galerie d'exposition de photographies"], 0,
     "Gamma, Sygma et Sipa ont fait la réputation du photojournalisme français."],
    ["Qu'est-ce que la crise du modèle économique de la presse ?", ["La chute des recettes publicitaires et des ventes papier", "La baisse continue du nombre de journalistes employés en rédaction", "L'augmentation des coûts d'impression", "La concurrence entre titres"], 0,
     "Les plateformes numériques captent aujourd'hui l'essentiel de la publicité en ligne."],
    ["Qu'est-ce qu'un modèle payant en ligne pour un journal ?", ["Un accès aux articles conditionné à un abonnement", "Une vente au numéro numérique", "Un paiement à l'article uniquement", "Un accès gratuit financé par les dons"], 0,
     "Plusieurs formules coexistent : mur payant strict, compteur d'articles ou modèle mixte."],
    ["Qu'est-ce qu'une aide publique à la presse en France ?", ["Un soutien financier direct ou indirect de l'État aux titres", "Une exonération de charges sociales", "Une subvention aux journalistes", "Un financement des kiosques"], 0,
     "Tarifs postaux préférentiels, TVA réduite et aides directes en constituent les principaux volets.", 3],
  ]),

  notion("cm2-deontologie-journalisme", S, "La déontologie journalistique",
    "Règles, conflits d'intérêts, responsabilité.",
    "La déontologie journalistique repose sur des chartes professionnelles, non sur la loi.",
    2, [
    ["Qu'est-ce qu'une charte déontologique de journalisme ?", ["Un texte professionnel énonçant devoirs et droits", "Une loi encadrant l'exercice de la profession", "Un règlement intérieur propre à chaque salle de rédaction", "Un code pénal spécifique aux journalistes"], 0,
     "La charte de Munich de 1971 est la référence européenne la plus citée."],
    ["Qu'est-ce que la vérification croisée d'une information ?", ["La confirmation par plusieurs sources indépendantes", "La relecture par un confrère de la rédaction", "La comparaison avec les dépêches des agences de presse", "La validation par la hiérarchie du journal"], 0,
     "Deux sources se référant à la même origine ne constituent pas une vérification croisée."],
    ["Qu'est-ce qu'un conflit d'intérêts pour un journaliste ?", ["Une situation où un intérêt personnel peut altérer son indépendance", "Un désaccord de fond avec sa rédaction", "Un conflit entre deux sources", "Une concurrence entre médias rivaux"], 0,
     "La transparence sur les liens existants est généralement préférée à la seule abstention."],
    ["Qu'est-ce que le off dans une relation avec une source ?", ["Un échange convenu comme non publiable en l'état", "Une déclaration anonyme", "Une conversation privée", "Une information confidentielle transmise par erreur"], 0,
     "Ses conditions doivent être négociées explicitement avant l'échange, non après."],
    ["Qu'est-ce qu'un droit de suite pour un lecteur ?", ["Le droit d'être informé de la suite donnée à une affaire relatée", "Un droit de réponse dans le même journal", "Un droit à rectification des faits publiés", "Un droit d'accès aux sources sur lesquelles le journaliste s'appuie"], 0,
     "Il ne s'agit pas d'une obligation légale mais d'une exigence déontologique croissante."],
    ["Qu'est-ce que la présomption d'innocence dans le traitement médiatique ?", ["L'obligation de ne pas présenter un mis en cause comme coupable", "L'interdiction de citer son nom de famille", "L'obligation de flouter systématiquement son visage", "Le refus de couvrir la moindre affaire tant qu'elle est en cours d'instruction"], 0,
     "La loi française sanctionne la présentation d'une personne comme coupable avant condamnation."],
    ["Qu'est-ce que le respect de la dignité des personnes en reportage ?", ["Ne pas exposer une personne dans une situation dégradante sans nécessité", "Ne jamais montrer aucun visage", "Éviter purement et simplement les sujets sensibles", "Obtenir systématiquement un accord écrit de la personne"], 0,
     "La nécessité de l'information doit être mise en balance avec l'atteinte causée."],
    ["Qu'est-ce que le plagiat en journalisme ?", ["La reprise du travail d'un confrère sans citation", "La reprise d'une dépêche d'agence sans la citer", "La traduction d'un article paru dans la presse étrangère", "La citation d'un communiqué de presse"], 0,
     "Il est l'un des manquements les plus sévèrement sanctionnés par la profession."],
    ["Qu'est-ce qu'un conseil de déontologie journalistique ?", ["Une instance d'autorégulation examinant les manquements signalés", "Un tribunal spécialisé dans la presse", "Une autorité administrative indépendante placée auprès du ministère", "Un syndicat professionnel de journalistes"], 0,
     "La France s'en est dotée en 2019, sans pouvoir de sanction et avec une adhésion volontaire."],
    ["Qu'est-ce que l'indépendance éditoriale d'une rédaction ?", ["La capacité à décider du contenu sans pression de l'actionnaire ou des annonceurs", "L'absence de toute hiérarchie interne", "Le statut coopératif adopté par le média", "L'autonomie financière de la rédaction"], 0,
     "Chartes, sociétés de journalistes et clauses de conscience en sont les principaux instruments.", 3],
  ]),

  notion("cm2-jeux-video-culture", S, "Le jeu vidéo comme culture",
    "Narration, communautés, patrimoine.",
    "Le jeu vidéo est le seul média où le spectateur agit sur le déroulement de l'œuvre.",
    2, [
    ["Qu'est-ce que l'interactivité dans un jeu vidéo ?", ["La capacité du joueur à influer sur le déroulement de l'œuvre", "La possibilité de jouer à plusieurs en réseau", "La communication directe avec les développeurs pendant la partie", "L'adaptabilité automatique de la difficulté"], 0,
     "Elle distingue radicalement le jeu vidéo du cinéma et de la littérature."],
    ["Qu'est-ce que la narration environnementale ?", ["Un récit transmis par le décor plutôt que par le dialogue", "Un récit consacré à l'environnement naturel", "Une narration déployée en monde ouvert", "Un récit qui s'adapte au comportement du joueur en temps réel"], 0,
     "Des objets, des ruines et des traces racontent une histoire sans qu'aucun personnage ne l'énonce."],
    ["Qu'est-ce qu'un jeu narratif à choix ?", ["Un jeu où les décisions du joueur infléchissent le récit", "Un jeu ne comportant qu'une seule fin", "Un jeu entièrement textuel", "Un jeu d'aventure classique fondé sur des énigmes à résoudre"], 0,
     "La difficulté consiste à donner un poids réel aux choix sans multiplier indéfiniment les branches."],
    ["Qu'est-ce que le speedrun ?", ["La pratique consistant à terminer un jeu le plus vite possible", "Une course de vitesse disputée dans le jeu", "Un mode de difficulté accélérée", "Une compétition officielle organisée chaque année par l'éditeur"], 0,
     "Elle a donné naissance à des communautés très structurées, avec vérification collective des records."],
    ["Qu'est-ce que le modding ?", ["La modification d'un jeu par les joueurs eux-mêmes", "Un mode de jeu alternatif prévu à l'avance par l'éditeur", "Un piratage du code du jeu", "Une extension officielle vendue à part"], 0,
     "Plusieurs jeux commerciaux majeurs sont nés de modifications amateurs."],
    ["Qu'est-ce qu'un jeu en accès anticipé ?", ["Un jeu vendu inachevé et développé avec les retours des joueurs", "Une version d'essai gratuite, limitée dans le temps et le contenu", "Une préréservation avant la sortie", "Une bêta fermée réservée aux testeurs"], 0,
     "Le modèle finance le développement mais peut laisser des jeux inachevés indéfiniment."],
    ["Qu'est-ce que la préservation du jeu vidéo ?", ["L'effort pour conserver et rendre jouables les jeux anciens", "L'archivage des seuls codes sources chez les éditeurs de jeux", "La restauration graphique des jeux anciens", "La conservation des consoles et de leurs manettes"], 0,
     "L'obsolescence matérielle, les serveurs fermés et les droits rendent la tâche particulièrement difficile."],
    ["Qu'est-ce que l'émulation ?", ["Un logiciel reproduisant le fonctionnement d'une machine ancienne", "Une copie illégale d'un jeu", "Une remasterisation en haute définition", "Une réédition officielle sur les machines actuelles"], 0,
     "Juridiquement, l'émulateur est légal ; la distribution des jeux qu'il exécute ne l'est généralement pas."],
    ["Quelle institution française conserve les jeux vidéo au titre du dépôt légal ?", ["La Bibliothèque nationale de France", "Le CNC", "L'INA", "Le musée des Arts et Métiers, à Paris"], 0,
     "Le dépôt légal des jeux vidéo y est assuré depuis 1992."],
    ["Pourquoi le jeu vidéo est-il étudié dans les universités ?", ["Comme objet culturel, économique et social à part entière", "Uniquement pour ses effets sur le comportement des joueurs", "Pour former les futurs développeurs", "Pour ses seules applications pédagogiques"], 0,
     "Les game studies se sont constituées comme champ de recherche à partir des années 2000.", 3],
  ]),

  notion("cm2-documentaire", S, "Le documentaire",
    "Formes, éthique, diffusion.",
    "Un documentaire construit un point de vue : la neutralité totale n'existe pas.",
    2, [
    ["Qu'est-ce qu'un documentaire de création ?", ["Un film documentaire à écriture et point de vue affirmés", "Un reportage télévisé d'actualité", "Un film pédagogique destiné aux classes de collège et de lycée", "Un simple enregistrement d'un événement, sans montage ni commentaire"], 0,
     "Il se distingue du magazine par sa durée d'élaboration et sa liberté formelle."],
    ["Qu'est-ce que le documentaire animalier ?", ["Un genre filmant la faune, souvent avec de longues attentes", "Un film de fiction dont les personnages principaux sont des animaux", "Un reportage zoologique tourné en parc", "Un documentaire scientifique consacré à la nature et à ses milieux"], 0,
     "Certaines séquences supposent des mois d'affût pour quelques minutes utilisables."],
    ["Quelle question éthique se pose lors du tournage documentaire ?", ["Le consentement éclairé des personnes filmées", "La qualité de l'image et du son tout au long du tournage", "Le choix du format de diffusion", "La durée totale du tournage sur le terrain"], 0,
     "Ce que la personne accepte au tournage n'est pas toujours ce qu'elle découvre au montage."],
    ["Qu'est-ce qu'une reconstitution dans un documentaire ?", ["Une scène rejouée pour illustrer un fait passé", "Une image d'archive restaurée puis colorisée", "Une animation explicative réalisée en images de synthèse", "Un témoignage filmé face caméra"], 0,
     "Elle doit être clairement signalée pour ne pas être prise pour un document d'époque."],
    ["Qu'est-ce qu'une voix off documentaire ?", ["Un commentaire extérieur guidant la lecture des images", "Un dialogue enregistré séparément, puis ajouté au montage", "Une traduction affichée en surimpression", "Un témoignage donné en son seul"], 0,
     "Certains courants documentaires la refusent, y voyant une forme d'autorité imposée."],
    ["Qu'est-ce que le documentaire d'archives ?", ["Un film construit à partir d'images existantes", "Un documentaire historique consacré à une époque", "Un film consacré aux archives elles-mêmes", "Un montage de témoignages recueillis auprès des acteurs"], 0,
     "Le travail de recherche et de droits y représente une part majeure du budget."],
    ["Qu'est-ce que le webdocumentaire ?", ["Un documentaire à navigation non linéaire conçu pour internet", "Un documentaire simplement diffusé en ligne", "Un reportage court destiné au web", "Un documentaire participatif tourné par le public"], 0,
     "Sa conservation pose problème : les technologies employées deviennent vite obsolètes."],
    ["Qu'est-ce que le film ethnographique ?", ["Un documentaire issu d'une démarche d'anthropologie", "Un film consacré aux cultures étrangères les plus lointaines", "Un documentaire de voyage au long cours", "Un reportage sur les traditions populaires"], 0,
     "Jean Rouch en a été une figure majeure, avec une réflexion sur la place de la caméra."],
    ["Quel documentaire de Raymond Depardon filme des audiences de comparution immédiate ?", ["10e chambre, instants d'audience", "Profils paysans, l'approche", "Les Habitants", "La Vie moderne, troisième volet de Profils paysans"], 0,
     "Douze audiences filmées au tribunal de Paris, sans commentaire ni musique."],
    ["Pourquoi la diffusion du documentaire en salle reste-t-elle difficile ?", ["Le public y est plus restreint et la promotion limitée", "Les documentaires sont jugés trop longs", "Les salles refusent de les programmer", "La production en est bien plus coûteuse que celle d'une fiction"], 0,
     "Quelques succès ponctuels masquent une économie globalement fragile.", 3],
  ]),

  notion("cm2-education-medias", S, "Éducation aux médias",
    "Compétences, dispositifs, enjeux.",
    "Savoir chercher une information est devenu aussi important que la mémoriser.",
    2, [
    ["Qu'est-ce que le CLEMI en France ?", ["Le centre chargé de l'éducation aux médias dans l'enseignement", "Un observatoire indépendant des médias", "Une association professionnelle de journalistes de la presse écrite", "Un institut de sondage d'opinion"], 0,
     "Créé en 1983, il forme les enseignants et accompagne les médias scolaires."],
    ["Qu'est-ce que la semaine de la presse à l'école ?", ["Une opération annuelle rapprochant élèves et médias", "Un concours entre journaux scolaires", "Une formation destinée aux enseignants", "Une distribution de journaux gratuits dans les écoles"], 0,
     "Elle mobilise chaque année des milliers d'établissements et des centaines de médias partenaires."],
    ["Qu'est-ce qu'un journal scolaire ?", ["Un média réalisé par les élèves d'un établissement", "Un bulletin d'information rédigé par l'administration de l'école", "Une revue pédagogique pour les maîtres", "Un journal destiné aux parents d'élèves"], 0,
     "Sa réalisation constitue l'un des exercices d'éducation aux médias les plus complets."],
    ["Quelle compétence l'éducation aux médias cherche-t-elle à développer en priorité ?", ["L'esprit critique face aux informations reçues", "La maîtrise technique des outils numériques", "La capacité à produire soi-même des contenus", "La connaissance du droit de la presse et de ses limites"], 0,
     "Elle suppose de comprendre comment se fabrique une information avant de la juger."],
    ["Qu'est-ce que l'identité numérique d'une personne ?", ["L'ensemble des traces qu'elle laisse en ligne", "Son profil déclaré sur un réseau social", "Son pseudonyme habituel en ligne", "Son certificat d'authentification numérique officiel"], 0,
     "Elle se compose autant de ce que l'on publie que de ce que d'autres publient à notre sujet."],
    ["Qu'est-ce que le droit à l'image d'un mineur ?", ["Une protection renforcée exigeant l'accord des titulaires de l'autorité parentale", "Un droit strictement identique à celui d'un adulte", "Une interdiction absolue de toute publication", "Un droit exercé par l'établissement scolaire à la place des parents"], 0,
     "L'accord de l'enfant lui-même est également requis dès lors qu'il est en âge de comprendre."],
    ["Qu'est-ce qu'une source fiable ?", ["Une source identifiable, compétente et vérifiable", "Une source institutionnelle officielle", "Une source largement reprise par l'ensemble des médias", "Une source ancienne et reconnue de tous"], 0,
     "L'identification de l'auteur et la possibilité de remonter aux preuves sont les critères centraux."],
    ["Comment reconnaître un contenu sponsorisé ?", ["Par une mention obligatoire de partenariat ou de publicité", "Par son ton ouvertement commercial", "Par sa seule présence sur un réseau social plutôt qu'en presse écrite", "Par l'absence de toute source citée"], 0,
     "L'absence de mention constitue une pratique commerciale trompeuse, sanctionnée par la loi."],
    ["Qu'est-ce que le fact-checking pédagogique ?", ["Un exercice de vérification guidée d'informations en classe", "Une correction collective d'exercices", "Une évaluation écrite des connaissances", "Une lecture critique de la presse quotidienne faite en classe"], 0,
     "Il vise à faire pratiquer la méthode plutôt qu'à délivrer une liste de sources fiables."],
    ["Pourquoi l'éducation aux médias concerne-t-elle aussi les adultes ?", ["Les compétences requises évoluent avec les technologies et les usages", "Les adultes sont plus crédules que les jeunes", "Les jeunes sont déjà tous formés", "Les formations reçues à l'école suffisent"], 0,
     "Les enquêtes montrent que la diffusion de fausses informations n'est pas l'apanage des plus jeunes.", 3],
  ]),

  notion("cm2-cinema-technique-projection", S, "Salles et projection",
    "Formats, supports, exploitation des salles.",
    "Le passage au numérique a fait disparaître la copie physique en pellicule en quelques années.",
    2, [
    ["Quelle vitesse de projection s'est imposée pour le cinéma parlant ?", ["Vingt-quatre images par seconde", "Seize images par seconde, comme au muet", "Trente images par seconde, comme en vidéo", "Dix-huit images par seconde, comme en amateur"], 0,
     "Le muet tournait souvent plus lentement, d'où l'accéléré des projections modernes de films anciens."],
    ["Qu'est-ce que le format d'image d'un film ?", ["Le rapport entre largeur et hauteur de l'image", "La résolution du fichier numérique", "La taille de l'écran de projection", "Le nombre d'images projetées chaque seconde à l'écran"], 0,
     "Le 1,85 et le 2,39 sont les deux formats de projection les plus courants aujourd'hui."],
    ["Qu'est-ce que le CinemaScope ?", ["Un procédé anamorphique élargissant l'image projetée", "Un écran incurvé de grande largeur", "Une projection simultanée sur trois écrans placés côte à côte", "Un format de pellicule de soixante-dix millimètres"], 0,
     "Lancé en 1953, il répondait à la concurrence de la télévision par le spectacle."],
    ["Quand la projection numérique a-t-elle remplacé la pellicule en France ?", ["Autour de 2011-2013", "Dans les années 1990", "Après 2015", "Dans les années 2000 pour l'essentiel"], 0,
     "La transition a été rapide et a posé un problème de financement pour les petites salles."],
    ["Qu'est-ce qu'un DCP au cinéma ?", ["Le fichier numérique standardisé servant à la projection en salle", "Un format de compression vidéo pour la diffusion", "Un support de sauvegarde des rushes", "Un protocole de diffusion en réseau"], 0,
     "Il est généralement chiffré et accompagné d'une clé limitant sa période d'exploitation."],
    ["Qu'est-ce qu'une salle art et essai en France ?", ["Une salle classée pour sa programmation exigeante et soutenue à ce titre", "Une salle indépendante d'un grand circuit", "Un cinéma de quartier à petite jauge", "Une salle programmant uniquement des films anciens"], 0,
     "Le classement ouvre droit à des aides du CNC et à des majorations de subventions."],
    ["Qu'est-ce qu'un multiplexe ?", ["Un complexe de nombreuses salles sur un même site", "Une salle unique équipée de plusieurs écrans simultanés", "Un réseau de cinémas d'une même enseigne", "Un cinéma installé dans un centre commercial"], 0,
     "Leur développement à partir des années 1990 a transformé la géographie de l'exploitation."],
    ["Qu'est-ce que le son multicanal en salle ?", ["Une diffusion sur plusieurs enceintes réparties dans l'espace", "Un son stéréophonique amélioré", "Un son numérique fortement compressé", "Un système de sous-titrage sonore diffusé dans l'ensemble de la salle"], 0,
     "Les systèmes récents ajoutent des canaux au plafond pour un rendu tridimensionnel."],
    ["Qu'est-ce que l'audiodescription ?", ["Une piste sonore décrivant l'action aux spectateurs déficients visuels", "Un doublage adapté au public", "Un commentaire enregistré par le réalisateur", "Un sous-titrage lu à voix haute"], 0,
     "Elle s'insère dans les silences des dialogues, ce qui suppose une écriture spécifique."],
    ["Qu'est-ce que le sous-titrage pour sourds et malentendants ?", ["Un sous-titrage incluant dialogues, bruits et identification des locuteurs", "Un sous-titrage traduit en langue étrangère", "Une traduction simultanée en langue des signes", "Un résumé écrit distribué avant le film"], 0,
     "Il obéit à une norme de couleurs distinguant les locuteurs et les sons hors champ.", 3],
  ]),
];
