/**
 * Cinéma & Médias — treize notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Cinéma & Médias";

export const CG_CINEMA_MEDIAS: SeedSkill[] = [
  notion("cm-naissance-cinema", S, "La naissance du cinéma",
    "Des jouets optiques aux premières projections payantes : trente ans d'inventions concurrentes.",
    "Le cinéma n'a pas un inventeur mais une dizaine : les Lumière ont surtout inventé la projection collective payante.",
    2, [
    ["Quel appareil les frères Lumière brevettent-ils en 1895 ?", ["Le cinématographe", "Le kinétoscope d'Edison", "Le praxinoscope", "Le zootrope à bandes dessinées"], 0,
     "Il servait à la fois de caméra, de tireuse et de projecteur, ce qui le rendait très léger."],
    ["Où a lieu la première projection publique payante des Lumière ?", ["Au Grand Café à Paris, en décembre 1895", "À Lyon, dans l'usine Lumière", "À Londres, au Polytechnic de Regent Street", "À New York, au printemps 1896"], 0,
     "Trente-trois spectateurs assistèrent à la séance du 28 décembre 1895."],
    ["Quel appareil Edison met-il au point avant le cinématographe ?", ["Le kinétoscope, une visionneuse individuelle", "Le vitascope, projecteur de salle", "Le phénakistiscope", "Le mutoscope, visionneuse à feuillets"], 0,
     "On y regardait le film seul, par un œilleton, pièce de monnaie à l'appui."],
    ["Quel illusionniste français réalise Le Voyage dans la Lune en 1902 ?", ["Georges Méliès", "Émile Reynaud, du théâtre optique", "Léon Gaumont", "Charles Pathé"], 0,
     "Il invente les trucages, les décors peints et le récit de fiction, là où les Lumière filmaient le réel."],
    ["Quel procédé sonore, employé pour Le Chanteur de jazz en 1927, fait entrer le cinéma dans l'ère du parlant ?", ["Le Vitaphone", "Le Technicolor", "Le CinémaScope", "Le Movietone"], 0,
     "Le Vitaphone synchronisait un disque et le projecteur ; le son optique, gravé sur la pellicule, l'a supplanté dès 1930."],
    ["Quel réalisateur soviétique théorise le montage des attractions ?", ["Sergueï Eisenstein", "Dziga Vertov", "Vsevolod Poudovkine", "Alexandre Dovjenko"], 0,
     "La séquence des escaliers d'Odessa, dans Le Cuirassé Potemkine, en est la démonstration."],
    ["Qu'est-ce que l'effet Koulechov ?", ["Le sens d'un plan change selon le plan qui le précède", "Le mouvement perçu grâce à la seule persistance rétinienne", "Le raccord dans l'axe", "La profondeur obtenue par le seul éclairage"], 0,
     "Un même visage neutre paraît affamé, triste ou attendri selon l'image qui lui est associée."],
    ["Quel comédien crée le personnage du vagabond au chapeau melon ?", ["Charlie Chaplin", "Buster Keaton", "Harold Lloyd", "Max Linder"], 0,
     "Charlot apparaît en 1914. Chaplin résista au parlant jusqu'en 1940 avec Le Dictateur."],
    ["Quel film américain de 1941 est célèbre pour sa profondeur de champ et sa narration éclatée ?", ["Citizen Kane", "Autant en emporte le vent", "Casablanca", "Le Faucon maltais"], 0,
     "Orson Welles avait vingt-cinq ans. Le film fut un échec commercial avant de devenir une référence."],
    ["Qu'est-ce que le cinéma expressionniste allemand des années 1920 ?", ["Un courant aux décors déformés et aux ombres marquées", "Un cinéma documentaire sur le réel", "Un cinéma de propagande d'État", "Un cinéma tourné en couleurs naturelles et en décors réels"], 0,
     "Le Cabinet du docteur Caligari et Nosferatu en sont les emblèmes ; son influence marque le film noir américain.", 3],
  ]),

  notion("cm-langage-cinematographique", S, "Le langage du cinéma",
    "Plans, mouvements, montage, son : les outils par lesquels un film raconte.",
    "L'échelle des plans se définit par la place du corps humain dans le cadre.",
    2, [
    ["Qu'est-ce qu'un plan d'ensemble ?", ["Un plan montrant un décor et les personnages en entier", "Un plan resserré sur le seul visage du personnage", "Un plan cadrant le personnage à hauteur de taille", "Un plan isolant un objet, sans aucun personnage"], 0,
     "Il sert souvent à situer l'action, d'où son nom de plan de situation."],
    ["Qu'est-ce qu'un gros plan ?", ["Un plan cadrant le visage ou un détail", "Un plan cadrant un groupe de personnages ensemble", "Un plan large montrant l'ensemble du décor", "Un plan pendant lequel la caméra se déplace"], 0,
     "Il fut jugé choquant à ses débuts : le public s'inquiétait de voir des têtes coupées."],
    ["Qu'est-ce qu'un travelling ?", ["Un déplacement de la caméra elle-même", "Un changement de focale sans déplacer la caméra", "Un mouvement de rotation de la caméra sur son pied fixe", "Un montage rapide alternant des plans très courts"], 0,
     "Le zoom, lui, rapproche l'image sans déplacer la caméra : la perspective ne change pas."],
    ["Qu'est-ce qu'un panoramique ?", ["Une rotation de la caméra sur son axe", "Un déplacement latéral de la caméra le long de la scène", "Un plan très large embrassant tout le paysage", "Un mouvement de grue élevant la caméra au-dessus du sol"], 0,
     "Horizontal ou vertical, il balaie l'espace depuis un point fixe."],
    ["Qu'est-ce qu'un champ-contrechamp ?", ["Une alternance de plans opposés, typique du dialogue", "Un plan et son négatif projetés l'un après l'autre", "Un raccord dans l'axe, sans changement de point de vue", "Un plan filmé deux fois et monté dans les deux sens"], 0,
     "La règle des cent quatre-vingts degrés garantit que les regards restent cohérents d'un plan à l'autre."],
    ["Qu'est-ce qu'un plan-séquence ?", ["Une séquence entière filmée sans coupe", "Une suite de plans très courts montés bout à bout", "Un même plan répété à plusieurs moments du film", "Un plan de coupe"], 0,
     "L'ouverture de La Soif du mal et celle de The Player, qui la cite explicitement, comptent parmi les plus célèbres ; la difficulté tient à ce qu'aucune erreur ne peut être rattrapée au montage."],
    ["Qu'est-ce qu'une contre-plongée ?", ["Un cadrage de bas en haut, qui grandit le sujet", "Un cadrage plongeant, de haut en bas, qui écrase le sujet", "Un cadrage volontairement penché sur le côté", "Un cadrage neutre, à hauteur des yeux du personnage"], 0,
     "La plongée fait l'inverse et tend à écraser ou fragiliser le personnage."],
    ["Qu'est-ce qu'un son diégétique ?", ["Un son dont la source appartient au monde du film", "La musique du générique", "Un bruitage ajouté en studio après le tournage", "Une voix off qui commente l'action sans y appartenir"], 0,
     "La musique de fosse, extérieure à l'histoire, est dite extradiégétique."],
    ["Qu'est-ce que le bruitage, ou foley ?", ["La recréation des sons d'ambiance en studio", "Le doublage des voix des comédiens en studio", "Le mixage final", "L'enregistrement du son directement pendant le tournage"], 0,
     "Le nom vient de Jack Foley, technicien américain qui en systématisa la pratique dans les années 1930."],
    ["Qu'est-ce que le raccord dans l'axe ?", ["Un changement d'échelle de plan sans changer d'angle", "Un plan raccordé sur un mouvement du personnage", "Un raccord fondé sur la direction du regard d'un personnage", "Une coupe rendue invisible au spectateur par le montage"], 0,
     "Il faut un changement d'échelle net, sinon la coupe produit un saut désagréable à l'image.", 3],
  ]),

  notion("cm-cinema-francais", S, "Le cinéma français",
    "Réalisme poétique, Nouvelle Vague, comédie populaire : des courants et un système de financement singulier.",
    "La France finance son cinéma par une taxe sur les billets : chaque entrée alimente les films à venir.",
    2, [
    ["Quel courant du cinéma français des années 1930 associe décors urbains et destins tragiques ?", ["Le réalisme poétique", "La Nouvelle Vague", "Le naturalisme", "L'expressionnisme français"], 0,
     "Marcel Carné, Jean Renoir et Julien Duvivier en sont les principaux réalisateurs."],
    ["Quel film de Marcel Carné, tourné sous l'Occupation, est souvent élu meilleur film français ?", ["Les Enfants du paradis", "Quai des brumes", "Hôtel du Nord", "Le Jour se lève"], 0,
     "Tourné dans des conditions extrêmes, il sortit en 1945 avec des collaborateurs clandestins non crédités."],
    ["Quelle revue sert de foyer critique à la Nouvelle Vague ?", ["Les Cahiers du cinéma", "Positif", "L'Écran français", "La Revue du cinéma, d'avant-guerre"], 0,
     "Truffaut, Godard, Rohmer et Chabrol y écrivirent avant de passer à la réalisation."],
    ["Quel film de François Truffaut lance la Nouvelle Vague en 1959 ?", ["Les Quatre Cents Coups", "À bout de souffle", "Le Beau Serge", "Hiroshima mon amour"], 0,
     "Il y obtient le prix de la mise en scène à Cannes, un an après en avoir été exclu comme critique."],
    ["Qu'est-ce que la politique des auteurs défendue par les Cahiers du cinéma ?", ["L'idée que le réalisateur est le véritable auteur du film", "La défense du scénariste du film", "La primauté du producteur sur le tournage", "Le refus de toute adaptation d'une œuvre littéraire au cinéma"], 0,
     "Elle a durablement modifié la façon dont on parle de cinéma, y compris aux États-Unis."],
    ["Quelle réalisatrice, figure du groupe de la Rive gauche, tourne Cléo de 5 à 7 ?", ["Agnès Varda", "Marguerite Duras", "Chantal Akerman", "Nelly Kaplan"], 0,
     "Elle avait déjà réalisé La Pointe courte en 1955, souvent tenu pour un film annonciateur de la Nouvelle Vague."],
    ["Quel organisme public soutient le cinéma français ?", ["Le Centre national du cinéma et de l'image animée", "L'Institut Lumière, à Lyon", "La Cinémathèque française", "L'Avance sur recettes, à elle seule et sans autre dispositif"], 0,
     "Il redistribue notamment une taxe prélevée sur chaque billet vendu, y compris pour les films étrangers."],
    ["Qu'est-ce que l'avance sur recettes ?", ["Une aide sélective remboursable accordée avant tournage", "Un crédit d'impôt automatique pour la production", "Une avance consentie par les distributeurs", "Un prêt bancaire garanti par l'État"], 0,
     "Créée en 1959 par André Malraux, elle a permis à de nombreux premiers films d'exister."],
    ["Quelle institution fondée par Henri Langlois conserve et projette les films en France ?", ["La Cinémathèque française", "Le CNC", "L'INA", "Les archives du film de Bois-d'Arcy"], 0,
     "Son éviction en 1968 déclencha une mobilisation des cinéastes qui préfigura Mai 68."],
    ["Quel film français est le plus vu en salles en France de tous les temps ?", ["Bienvenue chez les Ch'tis", "Intouchables", "La Grande Vadrouille", "Astérix et Obélix : Mission Cléopâtre"], 0,
     "Sorti en 2008, il a dépassé La Grande Vadrouille, en tête depuis 1966.", 3],
  ]),

  notion("cm-hollywood-industrie", S, "Hollywood et l'industrie du cinéma",
    "Studios, genres, censure, blockbusters : comment le cinéma américain s'est organisé.",
    "Le code Hays a régi ce qu'on pouvait montrer à l'écran américain de 1934 à 1968.",
    2, [
    ["Pourquoi les studios se sont-ils installés en Californie au début du XXe siècle ?", ["Pour le climat, la lumière et l'éloignement des brevets d'Edison", "Pour la main-d'œuvre locale bon marché", "Pour la proximité des grandes salles de théâtre installées à Broadway", "Pour les aides fiscales de l'État"], 0,
     "Le trust d'Edison, basé sur la côte Est, poursuivait les producteurs indépendants."],
    ["Qu'est-ce que le code Hays ?", ["Un code d'autocensure régissant le contenu des films américains", "Une loi fédérale encadrant le cinéma", "Un règlement syndical des studios", "Un système de classification des films selon l'âge du public admis"], 0,
     "En vigueur de 1934 à 1968, il interdisait notamment de montrer un crime impuni ou un couple adultère heureux."],
    ["Qu'est-ce que le système des studios de l'âge d'or hollywoodien ?", ["Des studios contrôlant production, distribution et salles, avec des acteurs sous contrat", "Un partage des genres cinématographiques entre les studios", "Une coopérative de producteurs", "Un réseau de salles indépendantes"], 0,
     "L'arrêt Paramount de 1948 leur a imposé de vendre leurs salles, ce qui a désorganisé le modèle."],
    ["Qu'est-ce que la liste noire de Hollywood ?", ["L'exclusion d'artistes soupçonnés de sympathies communistes", "La liste des films interdits de projection", "Le classement des films américains selon leurs recettes en salle", "La liste des acteurs restés sans contrat"], 0,
     "Elle frappe des centaines de professionnels à partir de 1947, dans le contexte du maccarthysme."],
    ["Quel film de 1975 est souvent tenu pour le premier blockbuster estival moderne ?", ["Les Dents de la mer", "La Guerre des étoiles", "Le Parrain", "L'Exorciste"], 0,
     "Sortie massive et campagne télévisée nationale : la stratégie devient la norme."],
    ["Quel genre est né des romans policiers américains et de l'esthétique expressionniste ?", ["Le film noir", "Le western", "La comédie musicale", "Le film de gangsters"], 0,
     "Le terme a été forgé par des critiques français en 1946, découvrant d'un coup les films retenus pendant la guerre."],
    ["Quel studio d'animation Walt Disney fonde-t-il avec son frère en 1923 ?", ["Le Disney Brothers Cartoon Studio", "Pixar", "Warner Animation, en Californie", "Fleischer Studios, à New York"], 0,
     "Rebaptisé Walt Disney Studio en 1926, il ne prend le nom de The Walt Disney Company qu'en 1986."],
    ["Quel studio d'animation a produit Toy Story, premier long métrage entièrement en images de synthèse ?", ["Pixar", "DreamWorks", "Blue Sky", "Illumination"], 0,
     "Sorti en 1995, il a demandé plus de quatre ans de production."],
    ["Que récompense l'Oscar du meilleur film ?", ["Les producteurs du film", "Le réalisateur du film", "Le studio qui a produit le film", "Le scénariste du film"], 0,
     "Ce sont les producteurs qui montent sur scène. La récompense du réalisateur est distincte."],
    ["Quel film non anglophone remporte l'Oscar du meilleur film en 2020 ?", ["Parasite", "Roma", "Le Fabuleux Destin d'Amélie Poulain", "Tigre et Dragon"], 0,
     "Premier film en langue étrangère à l'obtenir, lors de la quatre-vingt-douzième cérémonie.", 3],
  ]),

  notion("cm-festivals-recompenses", S, "Festivals et récompenses",
    "Cannes, Venise, Berlin, les César, les Oscars : qui décerne quoi et sur quels critères.",
    "La Palme d'or récompense un film, pas un réalisateur : elle est remise au metteur en scène pour l'œuvre.",
    2, [
    ["En quelle année le Festival de Cannes est-il créé ?", ["1946", "1939", "1955", "1968"], 0,
     "Prévu en 1939 en réponse à la Mostra de Venise jugée trop favorable aux régimes fasciste et nazi, il fut ajourné par la guerre."],
    ["Quelle est la récompense suprême de la Mostra de Venise ?", ["Le Lion d'or", "La Palme d'or", "L'Ours d'or", "Le Grand Prix du jury"], 0,
     "Créée en 1932, la Mostra est le plus ancien festival de cinéma du monde."],
    ["Quelle est la récompense suprême du Festival de Berlin ?", ["L'Ours d'or", "Le Lion d'or", "La Palme d'or", "Le Prix du jury"], 0,
     "La Berlinale, fondée en 1951 dans une ville divisée, a longtemps eu une portée politique explicite."],
    ["En quelle année le Festival de Cannes est-il interrompu ?", ["En 1968", "En 1958", "En 1981", "En 1995"], 0,
     "Sur l'appel de cinéastes dont Godard et Truffaut, en solidarité avec les grèves et la contestation étudiante."],
    ["Quelle réalisatrice remporte la Palme d'or en 1993, première femme à l'obtenir ?", ["Jane Campion", "Agnès Varda", "Kathryn Bigelow", "Chantal Akerman"], 0,
     "Pour La Leçon de piano, ex æquo avec Adieu ma concubine de Chen Kaige."],
    ["Comment s'appellent les principales récompenses du cinéma français ?", ["Les César", "Les Molière", "Les Victoires", "Les Lumière"], 0,
     "Créés en 1976 sur le modèle des Oscars, ils doivent leur nom au sculpteur César, auteur du trophée."],
    ["Que récompensent les Molière ?", ["Le théâtre", "Le cinéma", "La musique", "La télévision"], 0,
     "Les Victoires de la musique récompensent la musique, les Sept d'or récompensaient autrefois la télévision."],
    ["Qui décerne les Oscars ?", ["L'Académie des arts et des sciences du cinéma", "Les critiques américains", "Le public", "Les studios de Hollywood"], 0,
     "Environ dix mille membres professionnels, votant chacun principalement dans sa branche pour les nominations."],
    ["Qu'est-ce que la Caméra d'or à Cannes ?", ["Le prix du meilleur premier film, toutes sections confondues", "Le prix de la meilleure photographie", "Un prix technique", "Le prix du public"], 0,
     "Créée en 1978, elle a révélé de nombreux cinéastes, dont Jim Jarmusch et Naomi Kawase.", 3],
    ["Que récompense le Grand Prix à Cannes ?", ["La deuxième distinction de la compétition, après la Palme d'or", "Le meilleur second rôle du film", "Le meilleur film étranger hors compétition", "Le meilleur film de la Semaine de la critique"], 0,
     "Il vient juste après la Palme d'or dans la hiérarchie du palmarès de la compétition officielle."],
  ]),

  notion("cm-cinemas-monde", S, "Les cinémas du monde",
    "Italie, Japon, Inde, Iran, Afrique : au-delà de Hollywood et de la France.",
    "L'Inde produit chaque année plus de films que n'importe quel autre pays.",
    2, [
    ["Quel courant italien de l'après-guerre filme dans la rue avec des acteurs non professionnels ?", ["Le néoréalisme", "Le vérisme", "La comédie à l'italienne", "Le cinéma d'auteur romain"], 0,
     "Rome ville ouverte et Le Voleur de bicyclette en sont les films emblématiques."],
    ["Quel réalisateur italien tourne La Dolce Vita et Huit et demi ?", ["Federico Fellini", "Luchino Visconti", "Michelangelo Antonioni", "Vittorio De Sica"], 0,
     "Son nom a donné l'adjectif fellinien, pour désigner un univers baroque et onirique."],
    ["Quel réalisateur japonais tourne Rashômon et Les Sept Samouraïs ?", ["Akira Kurosawa", "Yasujirō Ozu", "Kenji Mizoguchi", "Nagisa Ōshima"], 0,
     "Rashômon, Lion d'or à Venise en 1951, a fait découvrir le cinéma japonais à l'Occident."],
    ["Quel studio d'animation japonais Hayao Miyazaki cofonde-t-il ?", ["Le studio Ghibli", "Toei Animation", "Madhouse", "Production I.G"], 0,
     "Le Voyage de Chihiro a remporté l'Ours d'or et l'Oscar du meilleur film d'animation."],
    ["Quel pays produit le plus grand nombre de films par an ?", ["L'Inde", "Les États-Unis", "La Chine", "Le Nigeria"], 0,
     "Environ deux mille films par an, dans une vingtaine de langues, pas seulement en hindi."],
    ["Que désigne le mot Bollywood ?", ["Le cinéma en hindi produit à Mumbai", "L'ensemble du cinéma indien", "Le cinéma tamoul", "Les studios de New Delhi"], 0,
     "Mot-valise de Bombay et Hollywood. Le cinéma tamoul est appelé Kollywood, le télougou Tollywood."],
    ["Quel réalisateur iranien remporte la Palme d'or en 1997 pour Le Goût de la cerise ?", ["Abbas Kiarostami", "Jafar Panahi", "Asghar Farhadi", "Mohsen Makhmalbaf"], 0,
     "Le cinéma iranien s'est imposé internationalement malgré une censure très contraignante."],
    ["Quel réalisateur sénégalais est considéré comme le père du cinéma africain ?", ["Ousmane Sembène", "Souleymane Cissé", "Idrissa Ouedraogo", "Djibril Diop Mambéty"], 0,
     "Écrivain devenu cinéaste pour toucher un public non lecteur, il réalise La Noire de… en 1966."],
    ["Quel festival de cinéma africain se tient tous les deux ans au Burkina Faso ?", ["Le FESPACO, à Ouagadougou", "Le festival de Carthage", "Le festival de Marrakech", "Le festival de Durban"], 0,
     "Créé en 1969, c'est le plus important rendez-vous du cinéma africain."],
    ["Quel courant du cinéma de Hong Kong s'est illustré dans les films d'arts martiaux et de gangsters ?", ["Le cinéma d'action hongkongais des années 1980", "Le réalisme cantonais", "La nouvelle vague taïwanaise", "Le cinéma de la cinquième génération"], 0,
     "John Woo et Tsui Hark en sont des figures majeures ; leur influence sur Hollywood est reconnue.", 3],
  ]),

  notion("cm-television", S, "La télévision",
    "De l'ORTF au streaming : comment un média de masse s'est constitué puis fragmenté.",
    "En France, la télévision a été un monopole d'État jusqu'en 1982.",
    2, [
    ["Quel organisme détient le monopole de la radio-télévision française de 1964 à 1974 ?", ["L'ORTF", "La RTF", "La SFP", "L'INA"], 0,
     "Son éclatement en sept sociétés en 1974 marque la fin d'une information étroitement contrôlée."],
    ["En quelle année la publicité de marque apparaît-elle à la télévision française ?", ["1968", "1959", "1974", "1982"], 0,
     "Auparavant, seule la publicité collective, par produit générique, était autorisée."],
    ["Quelle chaîne française est privatisée en 1987 ?", ["TF1", "Antenne 2", "FR3", "La Cinq"], 0,
     "Une première en Europe : une chaîne publique historique cédée au privé, au groupe Bouygues."],
    ["Quelle chaîne franco-allemande est créée en 1992 ?", ["Arte", "La Cinquième", "TV5", "France Ô"], 0,
     "Née d'un traité entre la France et l'Allemagne, elle diffuse simultanément dans les deux langues."],
    ["Qu'est-ce que la TNT ?", ["La télévision numérique terrestre", "Une norme de télévision par satellite", "Un bouquet de chaînes payantes", "Un réseau câblé"], 0,
     "Déployée en France à partir de 2005, elle a multiplié le nombre de chaînes gratuites."],
    ["Quel institut mesure l'audience de la télévision en France ?", ["Médiamétrie", "L'Arcom", "L'INA", "Le CSA"], 0,
     "Les mesures reposent sur un panel de foyers équipés d'un boîtier, non sur une déclaration."],
    ["Quelle institution conserve les archives de la radio et de la télévision françaises ?", ["L'INA", "La BNF", "L'Arcom", "Le CNC"], 0,
     "Créé en 1975, l'Institut national de l'audiovisuel gère le dépôt légal de la radio et de la télévision."],
    ["Qu'est-ce que le format de la téléréalité ?", ["Un programme filmant des personnes non professionnelles dans un dispositif construit", "Un documentaire de société", "Un reportage en direct", "Une émission d'archives"], 0,
     "Loft Story, en 2001, marque son irruption en France et déclenche un vif débat public."],
    ["Qu'est-ce qu'un service de vidéo à la demande par abonnement ?", ["Une plateforme donnant accès à un catalogue contre un abonnement", "Une chaîne payante à la carte", "Un service de location à l'unité", "Une chaîne de rattrapage gratuite"], 0,
     "Netflix bascule vers ce modèle en 2007, dix ans après ses débuts d'envoi de DVD par la poste."],
    ["Quelle obligation la directive européenne impose-t-elle aux plateformes de streaming en matière de catalogue ?", ["Une part minimale d'œuvres européennes", "Un quota de films récents", "Une part de production nationale", "Une diffusion simultanée en salle"], 0,
     "La directive de 2018 fixe au moins trente pour cent d'œuvres européennes, avec une obligation de mise en avant.", 3],
  ]),

  notion("cm-presse-journalisme", S, "La presse et le métier de journaliste",
    "Comment se fabrique une information, qui la vérifie, et à quoi servent les agences.",
    "Une agence de presse vend de l'information brute aux rédactions : elle n'a pas de lecteurs directs.",
    2, [
    ["Quelle est la plus ancienne agence de presse mondiale encore en activité ?", ["L'Agence France-Presse", "Reuters", "Associated Press", "United Press International"], 0,
     "Elle descend de l'agence Havas, fondée en 1835 par Charles-Louis Havas."],
    ["Qu'est-ce qu'une dépêche d'agence ?", ["Une information brute diffusée aux rédactions abonnées", "Un article de fond documenté", "Un communiqué officiel d'une institution", "Une brève placée en toute fin d'édition, faute de place ailleurs"], 0,
     "Les rédactions la reprennent, la vérifient ou la complètent avant publication."],
    ["Qu'est-ce que la règle des cinq W en journalisme ?", ["Répondre à qui, quoi, où, quand et pourquoi", "Vérifier cinq sources différentes", "Écrire l'article en cinq paragraphes", "Utiliser cinq angles différents pour un même sujet"], 0,
     "Le comment s'y ajoute souvent. Elle structure l'attaque d'un article d'information."],
    ["Qu'est-ce que la pyramide inversée ?", ["Une structure plaçant l'essentiel en tête d'article", "Une organisation strictement chronologique", "Un plan en trois parties équilibrées", "Une progression allant du général vers le particulier"], 0,
     "Héritée du télégraphe, elle permettait de couper un article par la fin sans perdre l'information."],
    ["Qu'est-ce qu'une source anonyme protégée ?", ["Un informateur dont l'identité n'est pas révélée mais connue du journaliste", "Une source demeurée inconnue du journaliste lui-même", "Un témoignage recueilli sans vérification", "Un document dépourvu d'auteur identifié"], 0,
     "Les chartes déontologiques imposent au journaliste de connaître et d'évaluer sa source avant de la protéger."],
    ["Qu'est-ce que le fact-checking ?", ["La vérification systématique de déclarations et d'informations circulantes", "La relecture attentive d'un article", "La correction orthographique du texte", "La validation juridique d'un texte avant publication"], 0,
     "Les rubriques dédiées se sont multipliées dans les rédactions à partir des années 2010."],
    ["Qu'est-ce qu'une carte de presse en France ?", ["Un titre attestant l'exercice professionnel du journalisme", "Une accréditation temporaire de presse", "Une carte donnant accès aux conférences de presse officielles", "Un diplôme d'école de journalisme"], 0,
     "Délivrée par une commission paritaire, elle suppose de tirer l'essentiel de ses revenus de cette activité."],
    ["Qu'est-ce que le droit à l'oubli numérique ?", ["Le droit de demander le déréférencement d'informations obsolètes", "Le droit d'exiger l'effacement pur et simple d'un article de presse", "Le droit d'interdire toute republication ultérieure", "Le droit à l'anonymat complet en ligne"], 0,
     "Consacré par un arrêt de la Cour de justice de l'Union européenne en 2014, il vise les moteurs de recherche et non l'article source."],
    ["Qu'est-ce qu'un média de service public ?", ["Un média financé par des fonds publics avec des missions définies par la loi", "Un média détenu par l'État et dépourvu de toute autonomie", "Un média entièrement gratuit", "Un média associatif largement subventionné"], 0,
     "Indépendance éditoriale, pluralisme et couverture du territoire en sont les obligations classiques."],
    ["Qu'est-ce que la concentration des médias ?", ["Le contrôle de plusieurs titres ou chaînes par un même groupe", "Le regroupement de plusieurs rédactions", "La spécialisation d'un média sur un sujet", "L'alliance commerciale de plusieurs journaux concurrents sur un marché"], 0,
     "La loi française limite le cumul de participations dans la presse, la radio et la télévision sur un même territoire.", 3],
  ]),

  notion("cm-numerique-reseaux", S, "Internet, réseaux sociaux et information",
    "Comment circule l'information en ligne, ce que font les algorithmes, et comment se propage une rumeur.",
    "Un flux de réseau social n'est pas chronologique : il est trié par un algorithme d'engagement.",
    2, [
    ["Sur quoi repose le classement des contenus dans un flux de réseau social ?", ["Un algorithme optimisant l'engagement", "L'ordre chronologique de publication des messages", "Le seul nombre d'abonnés du compte qui publie", "Un choix éditorial fait par une équipe de la plateforme"], 0,
     "Ce tri favorise les contenus suscitant des réactions fortes, ce qui n'est pas synonyme de qualité."],
    ["Qu'est-ce qu'une chambre d'écho ?", ["Un espace où l'on n'entend que des opinions semblables aux siennes", "Un forum dont chaque message est relu par un modérateur avant sa publication", "Un groupe dont l'accès est réservé à ses membres", "Un fil de commentaires ouvert sous une publication"], 0,
     "Elle résulte à la fois des choix des utilisateurs et du tri algorithmique."],
    ["Qu'est-ce qu'une infox, ou fausse information ?", ["Une information fabriquée présentée comme vraie", "Une erreur commise de bonne foi par un journaliste", "Une opinion tranchée exprimée sans nuance", "Une information exacte mais donnée sans son contexte"], 0,
     "Le terme officiel recommandé en France est infox, formé sur information et intoxication."],
    ["Qu'est-ce qu'un hypertrucage, ou deepfake ?", ["Une vidéo ou un son synthétisés imitant une personne réelle", "Une photographie retouchée à la main avec un logiciel de dessin ordinaire", "Un montage assemblant des images d'archives réelles", "Une caricature animée d'une personnalité publique"], 0,
     "Les techniques d'apprentissage profond ont rendu ces contenus accessibles au grand public depuis 2018."],
    ["Qu'est-ce que le biais de confirmation ?", ["La tendance à privilégier l'information qui confirme ce qu'on croit déjà", "La déformation progressive d'un souvenir sous l'effet du temps qui passe", "L'alignement de son avis sur celui du groupe présent", "La confiance excessive dans son propre jugement"], 0,
     "Il explique pourquoi un démenti convainc rarement celui qui a d'abord cru l'information."],
    ["Qu'est-ce que le référencement naturel d'une page web ?", ["Sa position dans les résultats d'un moteur de recherche sans achat publicitaire", "Son inscription payante dans un annuaire de sites classés par catégorie", "Le nombre de visiteurs qu'elle reçoit chaque mois", "Son classement par date de dernière mise à jour"], 0,
     "Il dépend de nombreux critères, dont les liens entrants, l'ancienneté et l'adéquation au besoin exprimé."],
    ["Qu'est-ce qu'un cookie de navigation ?", ["Un petit fichier déposé sur l'appareil pour mémoriser une information", "Un programme espion installé à l'insu de l'utilisateur", "Un identifiant attribué au compte lors de l'inscription", "L'historique complet des pages visitées par l'utilisateur depuis son appareil"], 0,
     "Le règlement européen impose un consentement libre et éclairé pour les cookies non strictement nécessaires."],
    ["Qu'est-ce que le modèle économique de la publicité ciblée ?", ["Vendre l'attention des utilisateurs en exploitant leurs données", "Vendre directement les données personnelles à des tiers", "Faire payer aux utilisateurs un abonnement mensuel pour accéder au service", "Vendre des espaces publicitaires à prix forfaitaire"], 0,
     "L'annonceur achète une audience définie par des critères, non un emplacement fixe."],
    ["Qu'est-ce que le cyberharcèlement ?", ["Des propos ou comportements répétés visant à nuire à une personne en ligne", "Une insulte isolée adressée publiquement à quelqu'un lors d'un échange", "Le piratage du compte d'une personne par un tiers", "L'usurpation de l'identité de quelqu'un en ligne"], 0,
     "Il est puni en France de peines aggravées, y compris lorsque chaque auteur n'a agi qu'une fois dans une attaque concertée."],
    ["Qu'est-ce que l'éducation aux médias et à l'information ?", ["Un enseignement visant à former des usagers critiques des médias", "Un cours d'informatique et de programmation dispensé au collège et au lycée", "Une formation professionnelle aux métiers du journalisme", "Un module de communication écrite et orale en entreprise"], 0,
     "Inscrite dans les programmes scolaires français, elle est coordonnée par le CLEMI depuis 1983.", 3],
  ]),

  notion("cm-radio-podcast", S, "La radio et le son",
    "Un siècle de diffusion sonore, de la TSF aux podcasts.",
    "La radio est restée le média le plus accessible du monde : elle n'exige ni électricité stable ni lecture.",
    2, [
    ["Quel physicien italien met au point la télégraphie sans fil à la fin du XIXe siècle ?", ["Guglielmo Marconi", "Nikola Tesla", "Heinrich Rudolf Hertz", "Édouard Branly"], 0,
     "Il reçoit le Nobel de physique en 1909. Les travaux de Hertz et Branly l'avaient rendue possible."],
    ["Quelle est la première station de radio publique française à émettre régulièrement ?", ["Radio Tour Eiffel, au début des années 1920", "Radio Luxembourg, station privée émettant du Grand-Duché", "Radio Cité", "Radio Paris"], 0,
     "Les émissions expérimentales depuis la tour Eiffel commencent dès 1921."],
    ["Quel discours radiodiffusé du 18 juin 1940 appelle à poursuivre le combat ?", ["L'appel du général de Gaulle sur la BBC", "L'allocution de Pétain", "Le discours de Churchill adressé aux Français", "L'appel de Londres de Jean Moulin"], 0,
     "Il ne fut pas enregistré : le texte connu vient de la presse et d'une reprise ultérieure."],
    ["Qu'est-ce que la modulation de fréquence ?", ["Un mode de diffusion où la fréquence de l'onde varie avec le signal", "Une diffusion entièrement numérique", "Un mode de diffusion par satellite géostationnaire vers les récepteurs", "Une transmission par câble coaxial"], 0,
     "Elle offre une meilleure qualité sonore que la modulation d'amplitude, mais une portée plus réduite."],
    ["Quelle loi de 1981 autorise les radios privées locales en France ?", ["La loi mettant fin au monopole d'État sur la radiodiffusion", "La loi Léotard de 1986", "La loi sur l'audiovisuel de 1986, qui institue une autorité de régulation", "La loi Toubon"], 0,
     "Les radios dites libres émettaient auparavant dans l'illégalité, régulièrement brouillées."],
    ["Qu'est-ce que le RDS sur un autoradio ?", ["Un système transmettant des données comme le nom de la station", "Un mode de réception entièrement numérique", "Un décodeur des annonces publicitaires diffusées par la station", "Un correcteur automatique de fréquence"], 0,
     "Il permet aussi le basculement automatique vers un émetteur mieux capté et les messages d'information routière."],
    ["Qu'est-ce que la DAB+ ?", ["Une norme de radio numérique terrestre", "Une norme de diffusion de la radio par satellite", "Un format de fichier de podcast", "Une compression audio sans perte"], 0,
     "Elle permet de diffuser plusieurs stations sur une même fréquence, avec une qualité constante."],
    ["Qu'est-ce qu'un podcast natif ?", ["Un programme sonore conçu pour l'écoute à la demande, sans diffusion hertzienne", "Le replay d'une émission déjà passée à la radio", "Un enregistrement tiré des archives", "Une émission diffusée en direct sur internet puis mise en ligne pour l'écoute différée"], 0,
     "Il se distingue du podcast de rattrapage, qui reprend une émission déjà diffusée à l'antenne."],
    ["Quel format audio a démocratisé la diffusion de musique en ligne dans les années 1990 ?", ["Le MP3", "Le WAV", "Le FLAC", "L'AAC"], 0,
     "Mis au point par l'institut Fraunhofer, il réduit fortement la taille des fichiers en supprimant des informations peu audibles."],
    ["Qu'est-ce que le son binaural ?", ["Un enregistrement reproduisant la perception spatiale de deux oreilles humaines", "Un son stéréophonique classique", "Un son en relief obtenu par la multiplication des enceintes", "Un mixage réalisé sur deux pistes"], 0,
     "Il s'écoute au casque : la tête artificielle utilisée à l'enregistrement reproduit les décalages entre les deux oreilles.", 3],
  ]),

  notion("cm-jeu-video", S, "Le jeu vidéo",
    "Une industrie plus lucrative que le cinéma et la musique réunis, et ses grandes étapes.",
    "Le jeu vidéo est reconnu comme œuvre de l'esprit en France, à la fois logiciel et création audiovisuelle.",
    2, [
    ["Quel jeu d'arcade de 1972 lance l'industrie du jeu vidéo grand public ?", ["Pong", "Space Invaders", "Pac-Man", "Asteroids"], 0,
     "Édité par Atari, il s'inspire d'un jeu de tennis présent sur la console Magnavox Odyssey."],
    ["Quel krach frappe l'industrie américaine du jeu vidéo en 1983 ?", ["Une surproduction de jeux de mauvaise qualité", "Une pénurie mondiale de composants", "Une interdiction réglementaire de vente", "Une crise générale du secteur informatique américain"], 0,
     "Le marché américain s'effondre. Nintendo le relance en 1985 avec un contrôle strict de la qualité des titres."],
    ["Quel personnage de Nintendo apparaît pour la première fois dans Donkey Kong en 1981 ?", ["Mario", "Link", "Kirby", "Samus"], 0,
     "Il s'appelait alors Jumpman et était charpentier, non plombier."],
    ["Quel jeu conçu en Union soviétique en 1984 repose sur l'assemblage de pièces qui tombent ?", ["Tetris", "Arkanoid", "Columns", "Puyo Puyo"], 0,
     "Conçu par Alekseï Pajitnov, il fit l'objet d'un long conflit sur ses droits d'exploitation."],
    ["Qu'est-ce qu'un jeu en monde ouvert ?", ["Un jeu où le joueur peut explorer librement l'espace sans progression imposée", "Un jeu multijoueur en réseau", "Un jeu dépourvu de fin", "Un jeu librement modifiable par les joueurs eux-mêmes"], 0,
     "Le terme s'est imposé dans les années 2000, mais le principe existait dès les jeux d'aventure des années 1980."],
    ["Qu'est-ce que l'esport ?", ["La pratique compétitive du jeu vidéo", "Le sport simulé dans un jeu vidéo", "L'entraînement sportif assisté par écran", "Le jeu en ligne pratiqué occasionnellement"], 0,
     "Les finales des compétitions majeures réunissent des dizaines de millions de spectateurs en ligne."],
    ["Quel système de classification informe sur l'âge conseillé des jeux en Europe ?", ["PEGI", "ESRB", "CERO", "USK"], 0,
     "L'ESRB est le système nord-américain. PEGI signale aussi le contenu par des pictogrammes."],
    ["Qu'est-ce qu'un jeu indépendant ?", ["Un jeu développé sans le financement d'un grand éditeur", "Un jeu entièrement gratuit", "Un jeu vendu en accès anticipé, avant son achèvement complet", "Un jeu dépourvu de mode multijoueur"], 0,
     "La diffusion numérique a rendu ce modèle viable à partir de la fin des années 2000."],
    ["Qu'est-ce qu'une microtransaction ?", ["Un achat de faible montant à l'intérieur d'un jeu", "Un abonnement mensuel au service", "Une extension payante", "Un achat unique donnant accès à la version complète du jeu"], 0,
     "Les coffres à butin, dont le contenu est aléatoire, ont été assimilés à des jeux de hasard dans plusieurs pays."],
    ["Quel statut juridique le jeu vidéo a-t-il en France ?", ["Une œuvre complexe, à la fois logiciel et création audiovisuelle", "Un simple logiciel informatique", "Une œuvre audiovisuelle relevant du même régime qu'un film de cinéma", "Un produit industriel de consommation"], 0,
     "La Cour de cassation a retenu en 2009 cette qualification distributive, chaque composante relevant de son propre régime.", 3],
  ]),

  notion("cm-photographie-presse", S, "L'image d'actualité",
    "Photojournalisme, iconographie, manipulation : ce que fait une image quand elle informe.",
    "Une photographie d'actualité est un point de vue cadré, jamais un enregistrement neutre.",
    2, [
    ["Quelle agence photographique coopérative est fondée en 1947 par des photojournalistes ?", ["Magnum Photos", "Gamma, fondée en 1966", "Sipa", "Sygma"], 0,
     "Robert Capa, Henri Cartier-Bresson, David Seymour et George Rodger en sont les fondateurs."],
    ["Quel photographe est célèbre pour ses images du débarquement de Normandie ?", ["Robert Capa", "Henri Cartier-Bresson", "Eugene Smith", "Lee Miller"], 0,
     "Onze clichés seulement nous sont parvenus. La légende d'un accident de laboratoire, longtemps répétée, est aujourd'hui contestée : Capa n'aurait sans doute pas pris davantage d'images."],
    ["Qu'est-ce que le photojournalisme ?", ["Le récit d'un événement par l'image, soumis aux règles de l'information", "La photographie d'illustration de commande", "La photographie documentaire d'auteur au long cours", "La photographie institutionnelle de commande"], 0,
     "Il suppose de ne pas mettre en scène : la retouche du contenu est déontologiquement exclue."],
    ["Qu'est-ce qu'un World Press Photo ?", ["Un prix international de photojournalisme décerné chaque année", "Une agence de presse photographique", "Un festival de photographie de presse", "Une simple exposition itinérante de photographies, et rien de plus"], 0,
     "Créé en 1955, il a plusieurs fois retiré des prix pour des retouches jugées excessives."],
    ["Quel festival français est consacré au photojournalisme ?", ["Visa pour l'image, à Perpignan", "Les Rencontres de la photographie d'Arles", "Paris Photo", "Le Mois de la photo à Paris"], 0,
     "Créé en 1989, il expose chaque année les grands reportages de l'année écoulée."],
    ["Qu'est-ce qu'une légende de photographie de presse ?", ["Un texte indiquant qui, quoi, où et quand, et créditant l'auteur", "Un commentaire libre du rédacteur", "Un titre accrocheur pour attirer l'œil", "Une description technique complète des réglages de la prise de vue"], 0,
     "Sans légende exacte, une image d'archive peut être réattribuée à un événement qu'elle ne montre pas."],
    ["Qu'est-ce que le recadrage d'une photographie de presse ?", ["Une coupe du cadre qui peut modifier le sens de l'image", "Un agrandissement du tirage", "Un changement du format d'impression retenu pour la page", "Une correction de la perspective de l'image"], 0,
     "Il est autorisé mais engage la responsabilité éditoriale : couper un élément peut mentir sans rien ajouter."],
    ["Comment vérifie-t-on l'origine d'une image circulant en ligne ?", ["Par une recherche d'image inversée et l'examen des métadonnées", "En demandant simplement à la personne qui l'a mise en ligne la première", "En comparant sa qualité à d'autres images", "En vérifiant seulement sa date de publication"], 0,
     "Les métadonnées EXIF, quand elles subsistent, indiquent l'appareil, la date et parfois le lieu."],
    ["Qu'est-ce que le droit à l'image en France ?", ["Le droit de chacun de s'opposer à la diffusion de son image", "Le droit d'auteur que détient le photographe", "Le droit de photographier librement dans l'espace public", "Le droit d'utiliser librement une image sans autorisation"], 0,
     "Il connaît des exceptions liées à l'information du public, notamment pour les personnes publiques dans l'exercice de leurs fonctions."],
    ["Peut-on librement publier la photographie d'un bâtiment récent en France ?", ["Non, l'architecte détient un droit d'auteur sur son œuvre", "Oui, sans la moindre restriction", "Oui, dès lors que le bâtiment est visible depuis la voie publique", "Non, sauf pour un usage strictement privé"], 0,
     "La liberté de panorama a été introduite en 2016 pour les usages non commerciaux des particuliers.", 3],
  ]),

  notion("cm-publicite", S, "La publicité",
    "Comment une marque construit un message, et ce que la loi lui interdit.",
    "En France, la publicité comparative est légale mais strictement encadrée depuis 1992.",
    2, [
    ["Quel organisme régule la déontologie publicitaire en France ?", ["L'ARPP", "L'Arcom", "La DGCCRF", "Le CSA"], 0,
     "L'Autorité de régulation professionnelle de la publicité est une instance d'autorégulation de la profession."],
    ["Qu'est-ce qu'une publicité comparative ?", ["Une publicité citant explicitement un concurrent ou son produit", "Une publicité qui se contente de lister les caractéristiques du produit", "Un test comparatif réalisé par des consommateurs", "Une publicité citant seulement un prix moyen"], 0,
     "Légale en France depuis 1992, elle doit être objective, vérifiable et porter sur des biens comparables."],
    ["Quelle loi française de 1991 encadre la publicité pour l'alcool et le tabac ?", ["La loi Évin", "La loi Toubon", "La loi Sapin", "La loi Royer"], 0,
     "Elle interdit toute publicité pour le tabac et limite strictement les supports et le contenu pour l'alcool."],
    ["Qu'est-ce que le placement de produit ?", ["L'intégration payante d'une marque dans une fiction", "L'affichage du produit en tête de gondole", "Un partenariat noué avec la production", "Un encart publicitaire diffusé juste avant la fin du programme"], 0,
     "Autorisé en France depuis 2010 sous conditions, il doit être signalé au public."],
    ["Qu'est-ce que le greenwashing ?", ["Une communication surestimant l'engagement écologique d'un produit", "Un label environnemental officiel délivré par une autorité publique", "Une campagne de sensibilisation du public", "Une norme de production propre à l'industrie"], 0,
     "La loi française sanctionne depuis 2021 certaines allégations, dont l'emploi non justifié de la mention neutre en carbone."],
    ["Qu'est-ce qu'une pratique commerciale trompeuse ?", ["Une pratique reposant sur des allégations fausses ou de nature à induire en erreur", "Une publicité particulièrement agressive", "Une vente forcée au consommateur", "Une remise annoncée mais non appliquée"], 0,
     "Elle est punie pénalement, et l'omission d'une information substantielle suffit à la caractériser."],
    ["Qu'est-ce qu'un influenceur au sens de la loi française de 2023 ?", ["Une personne mobilisant son audience pour promouvoir des biens contre rémunération", "Un créateur de contenu suivi par un très large public en ligne", "Un ambassadeur de marque salarié par l'annonceur", "Un testeur de produits rémunéré"], 0,
     "La loi impose de signaler clairement les contenus commerciaux et interdit la promotion de certains produits."],
    ["Qu'est-ce que le taux de conversion en publicité en ligne ?", ["La part de personnes exposées qui accomplissent l'action visée", "Le nombre d'affichages de l'annonce", "Le coût payé pour chaque clic", "La part de l'audience effectivement touchée par l'ensemble de la campagne"], 0,
     "Il est distinct du taux de clic : cliquer n'est pas acheter."],
    ["Qu'est-ce qu'une marque déposée ?", ["Un signe enregistré conférant un monopole d'exploitation dans des classes de produits", "Un nom commercial employé publiquement par l'entreprise", "Un logo protégé au titre du droit d'auteur", "Une enseigne inscrite au registre du commerce et des sociétés"], 0,
     "En France, le dépôt à l'INPI vaut dix ans, renouvelable indéfiniment ; mais une marque non exploitée pendant cinq ans peut être annulée pour déchéance."],
    ["Qu'est-ce que la dégénérescence d'une marque ?", ["La perte de protection quand le nom devient le terme courant du produit", "L'abandon volontaire du dépôt par son titulaire", "L'expiration du dépôt faute de renouvellement", "La contrefaçon généralisée du produit par l'ensemble des concurrents du marché"], 0,
     "Frigidaire, Escalator ou Thermos ont subi ce sort dans certains pays : le succès du nom a détruit sa protection.", 3],
  ]),
];
