/**
 * Cinéma & Médias, troisième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Cinéma & Médias";

export const CG_CINEMA_MEDIAS_3: SeedSkill[] = [
  notion("cm3-cinema-muet", S, "Le cinéma muet",
    "Un art complet avant l'arrivée du son.",
    "Le cinéma muet n'a jamais été silencieux : il était accompagné en salle.",
    2, [
    ["Comment le cinéma muet était-il accompagné en salle ?", ["Par un pianiste, un orchestre ou un bonimenteur", "En silence complet", "Par un phonographe", "Par des bruitages"], 0,
     "Certaines grandes salles employaient des orchestres de plusieurs dizaines de musiciens."],
    ["Qu'est-ce qu'un carton dans un film muet ?", ["Un panneau de texte inséré entre les plans", "Un décor peint", "Un accessoire de tournage", "Une affiche promotionnelle"], 0,
     "Certains réalisateurs cherchaient à en limiter le nombre au maximum."],
    ["Quel comique américain est connu pour son visage impassible ?", ["Buster Keaton", "Charlie Chaplin", "Harold Lloyd", "Harry Langdon"], 0,
     "Il réalisait lui-même des cascades d'une dangerosité extrême."],
    ["Quel comique américain est célèbre pour une scène suspendue à une horloge ?", ["Harold Lloyd", "Buster Keaton", "Charlie Chaplin", "Fatty Arbuckle"], 0,
     "Il avait perdu deux doigts dans un accident de tournage quelques années plus tôt."],
    ["Quel film soviétique de 1925 est célèbre pour sa séquence d'escaliers ?", ["Le Cuirassé Potemkine", "La Grève", "Octobre", "L'Homme à la caméra"], 0,
     "La scène a été citée et pastichée d'innombrables fois depuis."],
    ["Quel documentaire soviétique de 1929 est un manifeste sur le cinéma lui-même ?", ["L'Homme à la caméra", "Le Cuirassé Potemkine", "La Terre", "Octobre"], 0,
     "Dziga Vertov y multiplie les procédés visuels et montre le cinéma en train de se faire."],
    ["Quel film allemand de 1927 dépeint une ville futuriste stratifiée ?", ["Metropolis", "Nosferatu", "Le Cabinet du docteur Caligari", "M le maudit"], 0,
     "Sa production ruineuse a failli faire disparaître le studio UFA."],
    ["Quel film de Murnau de 1922 adapte librement Dracula ?", ["Nosferatu", "L'Aurore", "Le Dernier des hommes", "Faust"], 0,
     "Faute de droits, les héritiers de Bram Stoker obtinrent la destruction des copies, heureusement incomplète."],
    ["Quelle actrice française fut une star du cinéma muet ?", ["Musidora", "Arletty", "Michèle Morgan", "Danielle Darrieux"], 0,
     "Son personnage d'Irma Vep, dans Les Vampires de Feuillade, en fit une icône."],
    ["Pourquoi de nombreux films muets ont-ils disparu ?", ["La pellicule nitrate était inflammable et jugée sans valeur commerciale", "Ils ont été censurés", "Ils n'étaient pas archivés légalement", "Ils ont été détruits pendant la guerre"], 0,
     "On estime que plus des trois quarts des films muets sont définitivement perdus.", 3],
  ]),

  notion("cm3-cinema-italien", S, "Le cinéma italien",
    "Néoréalisme, comédie, auteurs.",
    "La comédie à l'italienne a traité les sujets les plus graves sur le mode du rire.",
    2, [
    ["Quel film de Vittorio De Sica suit un ouvrier cherchant son vélo volé ?", ["Le Voleur de bicyclette", "Rome ville ouverte", "Umberto D.", "La Terre tremble"], 0,
     "Les acteurs y étaient des non-professionnels, principe du néoréalisme."],
    ["Quel film de Rossellini est tourné dans Rome à peine libérée ?", ["Rome ville ouverte", "Païsa", "Allemagne année zéro", "Stromboli"], 0,
     "Tourné en 1945 avec des moyens de fortune, il fonde le néoréalisme."],
    ["Qu'est-ce que la comédie à l'italienne ?", ["Un genre traitant les problèmes sociaux sur un mode comique et amer", "Une comédie légère", "Un théâtre filmé", "Une farce populaire"], 0,
     "Divorce à l'italienne et Affreux, sales et méchants en sont des exemples."],
    ["Quel film de Dino Risi met en scène un road movie tragique ?", ["Le Fanfaron", "Les Monstres", "Parfum de femme", "Une vie difficile"], 0,
     "Sorti en 1962, il se termine brutalement après une heure et demie de comédie."],
    ["Quel réalisateur italien filme l'incommunicabilité dans les années 1960 ?", ["Michelangelo Antonioni", "Federico Fellini", "Luchino Visconti", "Pier Paolo Pasolini"], 0,
     "L'Avventura, en 1960, fut sifflé à Cannes avant d'être reconnu comme un tournant."],
    ["Quel réalisateur italien était aussi poète, romancier et essayiste ?", ["Pier Paolo Pasolini", "Bernardo Bertolucci", "Ettore Scola", "Marco Bellocchio"], 0,
     "Assassiné en 1975 dans des circonstances jamais entièrement élucidées."],
    ["Quel film de Visconti adapte un roman sur la fin de l'aristocratie sicilienne ?", ["Le Guépard", "Rocco et ses frères", "Mort à Venise", "Senso"], 0,
     "Palme d'or en 1963, avec Burt Lancaster dans le rôle du prince."],
    ["Quel compositeur italien a écrit la musique d'Il était une fois dans l'Ouest ?", ["Ennio Morricone", "Nino Rota", "Armando Trovajoli", "Riz Ortolani"], 0,
     "Il a composé pour plus de quatre cents films ; Nino Rota, lui, est le compositeur attitré de Fellini."],
    ["Quel film de Giuseppe Tornatore évoque la nostalgie d'un cinéma de village ?", ["Cinema Paradiso", "La Légende du pianiste", "Malèna", "L'Homme des étoiles"], 0,
     "Oscar du meilleur film étranger en 1990."],
    ["Quel film italien de 1997 traite de la déportation sur un mode de conte ?", ["La vie est belle", "Le Voleur d'enfants", "Nuovo Cinema Paradiso", "Mediterraneo"], 0,
     "Le parti pris de Roberto Benigni a suscité autant d'éloges que de vives critiques.", 3],
  ]),

  notion("cm3-cinema-asiatique", S, "Les cinémas d'Asie",
    "Japon, Corée, Chine, Inde, Iran.",
    "Plusieurs cinémas asiatiques ont profondément influencé le cinéma occidental.",
    2, [
    ["Quel réalisateur japonais filme la famille en plans fixes à hauteur de tatami ?", ["Yasujirō Ozu", "Akira Kurosawa", "Kenji Mizoguchi", "Mikio Naruse"], 0,
     "Voyage à Tokyo, en 1953, figure régulièrement en tête des classements critiques mondiaux."],
    ["Quel film de Kurosawa raconte un même événement selon plusieurs versions ?", ["Rashômon", "Les Sept Samouraïs", "Vivre", "Ran"], 0,
     "L'effet Rashômon désigne depuis la divergence irréductible des témoignages."],
    ["Quel film de Kurosawa a pour remake direct le western américain Les Sept Mercenaires ?", ["Les Sept Samouraïs", "Rashômon", "Yojimbo", "Le Château de l'araignée"], 0,
     "Yojimbo a, par ailleurs, inspiré un autre western, Pour une poignée de dollars."],
    ["Quel réalisateur sud-coréen remporte la Palme d'or en 2019 ?", ["Bong Joon-ho", "Park Chan-wook", "Lee Chang-dong", "Kim Ki-duk"], 0,
     "Parasite a ensuite remporté l'Oscar du meilleur film, une première pour un film non anglophone."],
    ["Quel réalisateur taïwanais filme l'histoire de son île en longs plans ?", ["Hou Hsiao-hsien", "Edward Yang", "Ang Lee", "Tsai Ming-liang"], 0,
     "La Cité des douleurs, Lion d'or en 1989, aborde un épisode longtemps tabou de l'histoire taïwanaise."],
    ["Quel réalisateur chinois de la cinquième génération réalise Épouses et Concubines ?", ["Zhang Yimou", "Chen Kaige", "Tian Zhuangzhuang", "Jia Zhangke"], 0,
     "Cette génération est la première formée après la réouverture des écoles de cinéma en 1978."],
    ["Quel cinéaste iranien filme souvent des enfants et brouille documentaire et fiction ?", ["Abbas Kiarostami", "Jafar Panahi", "Mohsen Makhmalbaf", "Asghar Farhadi"], 0,
     "Close-up, en 1990, met en scène un fait divers rejoué par ses protagonistes réels."],
    ["Quel réalisateur iranien a été condamné à ne plus tourner ?", ["Jafar Panahi", "Abbas Kiarostami", "Asghar Farhadi", "Majid Majidi"], 0,
     "Il a néanmoins réalisé plusieurs films clandestinement, dont Ceci n'est pas un film."],
    ["Quel réalisateur indien est reconnu internationalement pour sa trilogie d'Apu ?", ["Satyajit Ray", "Mrinal Sen", "Ritwik Ghatak", "Guru Dutt"], 0,
     "Il tournait en bengali, loin des codes du cinéma commercial de Bombay."],
    ["Quelle caractéristique distingue le cinéma commercial indien ?", ["L'intégration systématique de séquences chantées et dansées", "Une durée courte", "Une absence de dialogues", "Un tournage en studio uniquement"], 0,
     "Les films dépassent fréquemment trois heures, avec un entracte prévu.", 3],
  ]),

  notion("cm3-television-histoire-monde", S, "La télévision dans le monde",
    "Modèles, chaînes, mondialisation.",
    "Les modèles télévisuels nationaux ont longtemps opposé service public et modèle commercial.",
    2, [
    ["Quel modèle télévisuel britannique repose sur une redevance ?", ["La BBC", "ITV", "Channel 4", "Sky"], 0,
     "Sa charte lui impose indépendance éditoriale et missions de service public."],
    ["Quel modèle domine historiquement la télévision américaine ?", ["Un modèle commercial financé par la publicité", "Un modèle public financé par une redevance", "Un modèle par abonnement payé par les foyers", "Un modèle mixte associant redevance et publicité"], 0,
     "La télévision publique y reste marginale, financée par dons et subventions limitées."],
    ["Qu'est-ce qu'un network américain ?", ["Un réseau national diffusant via des stations affiliées locales", "Une chaîne câblée diffusée par abonnement", "Un opérateur satellite couvrant tout le pays", "Une plateforme de streaming par abonnement"], 0,
     "ABC, CBS et NBC en sont les trois historiques."],
    ["Qu'est-ce que la télévision par câble ?", ["Une diffusion par réseau filaire, souvent payante", "Une diffusion hertzienne captée par une antenne râteau", "Une diffusion satellite reçue par parabole individuelle", "Une diffusion par internet vers un boîtier de salon"], 0,
     "Elle a permis l'essor des chaînes thématiques puis des séries à budget élevé."],
    ["Quelle chaîne américaine a transformé la fiction télévisée dans les années 2000 ?", ["HBO", "CBS", "NBC", "Fox"], 0,
     "Son modèle par abonnement l'affranchissait des contraintes publicitaires et de censure."],
    ["Quelle chaîne d'information continue a été lancée en 1980 ?", ["CNN", "BBC World", "Al Jazeera", "France 24"], 0,
     "La guerre du Golfe de 1991 a consacré son modèle de couverture en direct permanent."],
    ["Quelle chaîne d'information qatarie est lancée en 1996 ?", ["Al Jazeera", "Al Arabiya", "Sky News Arabia", "BBC Arabic"], 0,
     "Elle a modifié le paysage médiatique du monde arabe."],
    ["Qu'est-ce que la télévision publique européenne a en commun ?", ["Un financement public assorti d'obligations de service public", "Une absence totale de publicité à l'antenne", "Une gestion directe par l'État et ses ministères", "Un modèle unique imposé à tous les pays membres"], 0,
     "Les modes de financement et de gouvernance varient fortement d'un pays à l'autre."],
    ["Qu'est-ce que l'Eurovision au sens institutionnel ?", ["Un réseau d'échange de programmes entre télévisions publiques européennes", "Un concours de chanson qui oppose chaque année les pays européens entre eux", "Une chaîne de télévision européenne diffusée dans l'ensemble des pays de l'Union", "Un festival télévisé organisé chaque printemps"], 0,
     "Le concours de la chanson n'en est que la manifestation la plus visible."],
    ["Quel effet les plateformes mondiales ont-elles eu sur les télévisions nationales ?", ["Une concurrence forte sur les audiences et les talents", "Une disparition rapide des chaînes nationales historiques", "Aucun effet mesurable sur leurs audiences de soirée", "Un renforcement de leurs audiences en soirée"], 0,
     "Elles ont aussi fait monter les coûts de production des fictions.", 3],
  ]),

  notion("cm3-photographie-mode", S, "Photographie de mode et publicité",
    "Images construites et diffusion de masse.",
    "L'image de mode est entièrement construite, du casting à la retouche.",
    2, [
    ["Qu'est-ce qu'une photographie de mode ?", ["Une image construite mettant en scène des vêtements et un imaginaire", "Une photographie de vêtement prise en studio", "Un portrait de mannequin en pied", "Une image publicitaire commandée par une marque"], 0,
     "Elle mobilise stylistes, maquilleurs, décorateurs et retoucheurs."],
    ["Quel photographe américain a marqué la mode et le portrait au XXe siècle ?", ["Richard Avedon", "David Bailey, photographe britannique", "Helmut Newton", "Peter Lindbergh"], 0,
     "Irving Penn a également marqué durablement ce champ avec un style très différent."],
    ["Quel photographe allemand a marqué la mode par des mises en scène provocantes ?", ["Helmut Newton", "Peter Lindbergh", "Juergen Teller", "Wolfgang Tillmans"], 0,
     "Son travail suscite des lectures opposées sur la représentation des corps féminins."],
    ["Quel photographe a contribué à imposer un style plus naturel dans les années 1990 ?", ["Peter Lindbergh", "Helmut Newton", "Dominique Issermann", "Richard Avedon"], 0,
     "Il revendiquait un refus de la retouche systématique des visages."],
    ["Qu'est-ce que la retouche numérique en photographie de mode ?", ["Une modification des images devenue systématique", "Une correction technique légère de la lumière et des couleurs", "Un recadrage de l'image effectué avant sa publication", "Un étalonnage colorimétrique réalisé en laboratoire"], 0,
     "La loi française impose depuis 2017 une mention pour les photographies retouchées à usage commercial."],
    ["Qu'est-ce que la mention photographie retouchée en France ?", ["Une obligation légale d'informer sur la modification de la silhouette", "Une recommandation de la profession, sans valeur contraignante", "Une mention volontaire apposée par le magazine", "Une norme européenne applicable à toute la publicité"], 0,
     "Elle vise à limiter l'effet des images irréalistes sur l'image corporelle des jeunes."],
    ["Qu'est-ce qu'une campagne publicitaire visuelle ?", ["Un ensemble cohérent d'images diffusées sur plusieurs supports", "Une seule affiche déclinée dans toutes les grandes villes du pays", "Un spot télévisé diffusé chaque soir aux heures de grande écoute", "Une opération commerciale limitée dans le temps"], 0,
     "Sa cohérence sur tous les supports est ce qui construit la mémorisation."],
    ["Qu'est-ce que le placement de marque dans l'image ?", ["L'intégration visible d'un produit dans un contenu", "Une publicité classique diffusée dans un écran dédié", "Un partenariat commercial noué entre deux marques", "Un sponsoring d'événement sportif ou culturel"], 0,
     "Il doit être signalé au public lorsqu'il est rémunéré."],
    ["Qu'est-ce que la banque d'images ?", ["Un catalogue de photographies sous licence pour un usage commercial", "Une agence de presse spécialisée dans la photographie", "Un fonds d'archives conservé par une institution", "Un studio de production d'images publicitaires"], 0,
     "Son modèle économique a fortement pesé sur les revenus des photographes professionnels."],
    ["Qu'est-ce que la question du droit à l'image du mannequin ?", ["Un contrat définit la durée, le territoire et les supports d'exploitation", "L'image appartient au seul photographe, qui peut en disposer comme il l'entend", "L'image devient entièrement libre de droits dès sa toute première publication", "Le mannequin cède définitivement l'ensemble de ses droits à l'agence qui l'emploie"], 0,
     "Une utilisation hors contrat constitue une atteinte au droit à l'image.", 3],
  ]),

  notion("cm3-radio-france", S, "La radio en France",
    "Stations, formats, audiences.",
    "La radio française combine service public, réseaux privés et radios associatives.",
    2, [
    ["Combien de chaînes Radio France compte-t-elle ?", ["Sept", "Trois", "Dix", "Cinq"], 0,
     "France Inter, France Info, France Culture, France Musique, Fip, Mouv' et le réseau ici."],
    ["Quelle station de Radio France est consacrée à la création et au savoir ?", ["France Culture", "France Inter", "France Musique", "Fip"], 0,
     "Son audience a fortement progressé grâce au podcast."],
    ["Quelle station française diffuse de la musique sans animation parlée ?", ["Fip", "France Musique", "Radio Classique", "Nostalgie"], 0,
     "Sa programmation éclectique, assurée par des programmateurs humains, en fait une exception."],
    ["Qu'est-ce que le réseau ici, anciennement France Bleu ?", ["Un réseau de stations locales de service public", "Une chaîne nationale diffusée sur tout le territoire", "Un réseau associatif de radios locales bénévoles", "Une radio régionale privée financée par la publicité"], 0,
     "Il regroupe une quarantaine de stations locales."],
    ["Qu'est-ce qu'une radio associative de catégorie A ?", ["Une radio locale non commerciale bénéficiant d'un fonds de soutien", "Une radio commerciale locale financée par ses annonceurs", "Une radio thématique diffusée sur tout le territoire", "Une webradio diffusée uniquement sur internet"], 0,
     "Environ six cents radios de ce type existent en France."],
    ["Quelle station généraliste privée française est la plus ancienne ?", ["RTL", "Europe 1", "RMC", "Sud Radio"], 0,
     "Elle émettait depuis le Luxembourg pour contourner le monopole d'État français."],
    ["Pourquoi les radios périphériques émettaient-elles depuis l'étranger ?", ["Pour contourner le monopole d'État français sur la radiodiffusion", "Pour toucher un public international bien au-delà des frontières nationales", "Pour des raisons techniques tenant à la portée limitée des émetteurs", "Pour éviter la fiscalité française sur la publicité"], 0,
     "Luxembourg, Sarre, Monaco et Andorre ont ainsi accueilli des émetteurs."],
    ["Comment les fréquences de la bande FM sont-elles attribuées en France ?", ["Par l'Arcom, à l'issue d'appels à candidatures", "Par tirage au sort entre les candidats d'une même zone", "Par le ministère de la Culture, après avis des préfets", "Par ordre d'ancienneté des stations déjà installées"], 0,
     "Les autorisations sont délivrées zone par zone et pour une durée limitée."],
    ["Quelle particularité l'écoute de la radio présente-t-elle en France ?", ["Une écoute majoritairement en direct et souvent en voiture", "Une écoute en différé désormais dominante", "Une écoute uniquement numérique, sur applications", "Une écoute collective, en famille ou entre amis"], 0,
     "La matinale d'information reste le rendez-vous le plus suivi."],
    ["Qu'est-ce que la mesure d'audience radio en France ?", ["Une enquête déclarative par entretiens auprès d'un échantillon", "Une mesure automatique réalisée par des capteurs portés par un panel", "Un relevé automatique des connexions aux flux numériques des stations", "Une estimation obtenue par un sondage en ligne"], 0,
     "Médiamétrie interroge chaque année plus de cent mille personnes pour cette mesure.", 3],
  ]),

  notion("cm3-medias-numeriques", S, "Médias numériques et nouveaux formats",
    "Pure players, newsletters, vidéo courte.",
    "De nouveaux formats éditoriaux sont nés directement du numérique.",
    2, [
    ["Qu'est-ce qu'un média pure player ?", ["Un média existant uniquement en ligne", "Un média gratuit financé par ses seuls annonceurs", "Un média sans rédaction propre qui republie des dépêches", "Un agrégateur de contenus réservé aux abonnés payants"], 0,
     "Mediapart, en France, en est l'exemple le plus connu, financé par abonnement."],
    ["Qu'est-ce qu'un modèle sans publicité pour un média en ligne ?", ["Un financement reposant sur les seuls abonnements et dons", "Un média gratuit financé par une subvention publique", "Un modèle de micropaiement à l'article lu", "Un modèle coopératif imposé aux médias en ligne"], 0,
     "Il garantit une indépendance vis-à-vis des annonceurs mais impose un seuil d'abonnés élevé."],
    ["Qu'est-ce qu'une newsletter éditoriale ?", ["Un contenu éditorial envoyé directement par courrier électronique", "Une lettre d'information commerciale envoyée par une marque à ses clients", "Une revue de presse publiée chaque matin sur le site du journal", "Un bulletin interne diffusé aux salariés d'une entreprise"], 0,
     "Elle rétablit un lien direct avec le lecteur, hors des algorithmes des plateformes."],
    ["Qu'est-ce que le format vidéo vertical ?", ["Un format conçu pour l'écran d'un téléphone tenu à la verticale", "Un format d'écran large hérité des salles de cinéma panoramiques", "Un format carré imposé par les régies publicitaires des réseaux sociaux", "Un format cinéma recadré pour la diffusion télévisée"], 0,
     "Il a modifié la grammaire du cadrage pour toute une génération de créateurs."],
    ["Qu'est-ce qu'une vidéo courte sur les réseaux sociaux ?", ["Un format de quelques secondes à quelques minutes conçu pour la boucle", "Un extrait de programme télévisé remonté pour les réseaux", "Une bande-annonce diffusée avant la séance en salle", "Un teaser publicitaire commandé par un annonceur"], 0,
     "Son rythme de montage très rapide s'est diffusé au-delà des réseaux sociaux."],
    ["Qu'est-ce qu'un journalisme de solutions ?", ["Une approche rendant compte des réponses apportées à un problème", "Un journalisme optimiste qui ne publie que des nouvelles rassurantes", "Un journalisme militant qui défend ouvertement une cause politique", "Un journalisme de service donnant des conseils pratiques au lecteur"], 0,
     "Il vise à compléter le récit des problèmes sans renoncer à la rigueur d'enquête."],
    ["Qu'est-ce que le data journalisme ?", ["Un journalisme fondé sur l'analyse et la visualisation de données", "Un journalisme technologique consacré au secteur du numérique", "Un journalisme réservé aux rubriques économiques et boursières", "Un journalisme d'archives reconstituant des affaires anciennes"], 0,
     "Il suppose des compétences statistiques et une vigilance sur la qualité des sources."],
    ["Qu'est-ce que le journalisme automatisé ?", ["La production de textes courts par algorithme à partir de données structurées", "Un journalisme assisté par ordinateur où le rédacteur s'appuie sur des logiciels", "Une agrégation automatique des dépêches d'agence publiées sur un site", "Une traduction automatique des articles publiés par la presse étrangère"], 0,
     "Résultats sportifs et financiers en sont les domaines historiques d'application."],
    ["Qu'est-ce qu'un agrégateur d'actualités ?", ["Un service qui rassemble les articles de plusieurs sources", "Un moteur de recherche généraliste indexant l'ensemble du web", "Un réseau social où les abonnés commentent l'actualité du jour", "Un site de vérification des faits repérés en ligne"], 0,
     "Il capte une part de l'audience sans produire d'information : c'est ce qui a motivé le droit voisin."],
    ["Quel est le principal défi économique des médias en ligne ?", ["Capter une part suffisante de la valeur face aux plateformes", "Trouver des journalistes formés au numérique", "Produire assez de contenus pour alimenter le site", "Assurer la distribution technique sur tous les écrans"], 0,
     "Les droits voisins visent à faire rémunérer la reprise des contenus de presse par les plateformes.", 3],
  ]),

  notion("cm3-cinema-technique-image", S, "Les techniques de l'image animée",
    "Optiques, capteurs, formats.",
    "Le choix de l'objectif conditionne la perception de l'espace autant que le cadrage.",
    2, [
    ["Qu'est-ce qu'une focale courte, ou grand angle ?", ["Un objectif élargissant le champ et accentuant les perspectives", "Un objectif de longue portée destiné aux plans les plus lointains", "Un téléobjectif monté sur une caméra d'épaule", "Un objectif macro conçu pour les très gros plans"], 0,
     "Il exagère les distances entre premier plan et arrière-plan."],
    ["Qu'est-ce qu'un téléobjectif au cinéma ?", ["Un objectif écrasant les plans et isolant le sujet", "Un objectif de large champ monté sur un boîtier léger", "Un objectif à mise au point très rapprochée pour les détails", "Un zoom rapide déclenché pendant la prise"], 0,
     "Il donne l'impression d'un espace compressé, utilisé notamment dans les scènes de foule."],
    ["Qu'est-ce que la mise au point suivie ?", ["Un déplacement de la netteté accompagnant un mouvement", "Un réglage initial de l'objectif avant la prise", "Une correction automatique assurée par le boîtier", "Une profondeur de champ étendue sur tout le plan"], 0,
     "Elle est assurée par un assistant caméra dont c'est la spécialité."],
    ["Qu'est-ce qu'une caméra sur grue ?", ["Un dispositif permettant des mouvements verticaux amples", "Une caméra fixe surélevée installée en surplomb du plateau", "Une caméra portée à bout de bras", "Une caméra sur rail glissant le long du décor"], 0,
     "Le drone remplit aujourd'hui une partie de ces fonctions à moindre coût."],
    ["Qu'est-ce qu'un stabilisateur d'image porté ?", ["Un système isolant la caméra des mouvements du corps de l'opérateur", "Un trépied à roulettes déplacé par l'assistant caméra entre les prises", "Un rail de travelling posé au sol pour accompagner les déplacements", "Une suspension amortissant le bras d'une grue"], 0,
     "Le Steadicam, inventé en 1975, a rendu possibles des plans-séquences inédits."],
    ["Qu'est-ce que la caméra portée à l'épaule ?", ["Un cadrage instable volontaire renforçant l'impression de réel", "Un défaut technique dû à une caméra mal réglée", "Un mode de tournage économique sans machinerie lourde", "Une contrainte propre au tournage documentaire"], 0,
     "Elle est devenue une convention esthétique du réalisme au cinéma et en série."],
    ["Qu'est-ce que la focale d'un objectif ?", ["La distance qui détermine l'angle de champ et la perspective", "L'ouverture du diaphragme qui règle la quantité de lumière admise", "La sensibilité du capteur dans les conditions de faible éclairage", "La distance de mise au point séparant l'objectif du sujet net"], 0,
     "Un grand angle écarte les plans, un téléobjectif les écrase l'un sur l'autre."],
    ["Qu'est-ce que le ralenti au cinéma ?", ["Un enregistrement à cadence élevée restitué à vitesse normale", "Une lecture ralentie du film à la projection", "Un montage étiré par répétition des images", "Un effet numérique ajouté en postproduction"], 0,
     "Plus la cadence de tournage est élevée, plus le ralenti est fluide."],
    ["Qu'est-ce que le time-lapse ?", ["Un enregistrement à cadence très lente restitué à vitesse normale", "Un ralenti extrême appliqué à un plan déjà tourné", "Un montage accéléré enchaînant des plans de quelques images seulement", "Un plan fixe de très longue durée conservé au montage sans aucune coupe"], 0,
     "Il rend visibles des évolutions imperceptibles à l'œil, comme la croissance d'une plante."],
    ["Qu'est-ce que le format d'acquisition d'un film aujourd'hui ?", ["Un fichier numérique brut permettant un large travail en postproduction", "Une pellicule 35 millimètres développée en laboratoire", "Un fichier compressé au standard de diffusion", "Un format vidéo destiné à la diffusion télévisée"], 0,
     "Le tournage sur pellicule subsiste par choix esthétique chez certains réalisateurs.", 3],
  ]),

  notion("cm3-fiction-serie", S, "L'écriture sérielle",
    "Formats, arcs, production.",
    "Une série se conçoit comme un système, non comme un film long.",
    2, [
    ["Qu'est-ce qu'une bible de série ?", ["Un document fixant l'univers, les personnages et les règles narratives", "Un scénario complet écrit avant le tournage", "Un synopsis résumant la saison à venir", "Un plan de production détaillant le calendrier de tournage"], 0,
     "Elle permet à plusieurs auteurs d'écrire de façon cohérente."],
    ["Qu'est-ce qu'un atelier d'écriture de série ?", ["Une équipe d'auteurs travaillant collectivement sous la direction d'un responsable", "Un stage de formation à l'écriture destiné aux scénaristes débutants", "Une réunion de production réunissant le diffuseur et les producteurs", "Un comité de lecture chargé de sélectionner les projets de fiction soumis à la chaîne"], 0,
     "Ce modèle, venu des États-Unis, s'est diffusé en Europe dans les années 2010."],
    ["Qu'est-ce qu'un arc narratif de saison ?", ["Une trame se déployant sur l'ensemble des épisodes d'une saison", "L'intrigue d'un seul épisode, ouverte et résolue dans la même heure", "Un fil rouge courant sur l'ensemble des saisons d'une même série", "Un enchaînement de scènes ordonné par le monteur de la série"], 0,
     "Il coexiste souvent avec des intrigues bouclées épisode par épisode."],
    ["Qu'est-ce qu'un cliffhanger ?", ["Une fin d'épisode suspendue relançant l'attente", "Un rebondissement placé au milieu de l'épisode diffusé", "Une révélation finale qui clôt définitivement l'intrigue", "Un retour en arrière inséré dans le récit de l'épisode"], 0,
     "Le procédé vient des feuilletons imprimés du XIXe siècle."],
    ["Qu'est-ce qu'une série anthologique ?", ["Une série dont chaque saison ou épisode raconte une histoire indépendante", "Une série dont les épisodes se bouclent chacun en une heure", "Une série documentaire en plusieurs volets", "Une série suivant les mêmes personnages d'un épisode à l'autre"], 0,
     "Black Mirror et True Detective en sont des exemples contemporains."],
    ["Qu'est-ce qu'une mini-série ?", ["Une fiction en un nombre limité d'épisodes formant un tout", "Une série interrompue par la chaîne après quelques épisodes", "Une série réduite à son seul épisode pilote", "Une série de format court diffusée en access"], 0,
     "Le format connaît un fort développement, notamment sur les plateformes."],
    ["Qu'est-ce qu'un format court en fiction télévisée ?", ["Une série d'épisodes de quelques minutes", "Une mini-série tournée en une seule saison", "Un téléfilm unitaire produit pour une chaîne", "Un épisode pilote destiné à convaincre un diffuseur"], 0,
     "Le format a été popularisé en France par des séries diffusées avant le journal télévisé."],
    ["Qu'est-ce que le spin-off d'une série ?", ["Une nouvelle série dérivée d'un personnage ou d'un univers existant", "Une suite directe reprenant l'intrigue là où elle s'est arrêtée", "Un remake tourné dans un autre pays", "Un épisode spécial diffusé hors saison"], 0,
     "Il permet d'exploiter une notoriété acquise en réduisant le risque commercial."],
    ["Qu'est-ce que la co-production internationale de séries ?", ["Un financement partagé entre diffuseurs de plusieurs pays", "Un tournage réalisé à l'étranger pour bénéficier de décors naturels", "Une adaptation locale tournée à partir d'une série étrangère à succès", "Une vente de format à des diffuseurs d'autres pays"], 0,
     "Elle permet des budgets élevés mais impose des compromis éditoriaux."],
    ["Pourquoi les séries ont-elles gagné en prestige depuis vingt ans ?", ["Des budgets accrus, des auteurs reconnus et une liberté narrative", "Une baisse générale de la qualité des films de cinéma", "Une préférence marquée du public pour la télévision", "Une politique publique de soutien à la fiction"], 0,
     "Le format long permet un développement des personnages qu'un film ne peut offrir.", 3],
  ]),

  notion("cm3-image-verite", S, "L'image et la vérité",
    "Manipulation, mise en scène, preuve.",
    "Une photographie ne prouve rien par elle-même : elle exige un contexte.",
    2, [
    ["Pourquoi une photographie ne constitue-t-elle pas une preuve en soi ?", ["Elle dépend du cadrage, du moment et du contexte de production", "Elle est toujours retouchée avant publication", "Elle manque souvent de netteté sur le détail", "Elle est subjective par nature comme un dessin"], 0,
     "Une image authentique peut être utilisée dans un contexte totalement faux."],
    ["Qu'est-ce qu'une photographie mise en scène présentée comme spontanée ?", ["Une pratique documentée dès les débuts du photojournalisme", "Une invention récente apparue avec les appareils numériques", "Une pratique interdite dans la presse écrite mais tolérée à la télévision", "Un cas exceptionnel resté sans lendemain"], 0,
     "La photographie du soldat républicain de Capa fait encore l'objet de débats."],
    ["Qu'est-ce que la photographie de propagande ?", ["Une image produite pour servir un pouvoir ou une cause", "Une image censurée par une autorité publique avant sa diffusion", "Une image officielle diffusée par une administration", "Une image prise sur un théâtre d'opérations"], 0,
     "Les régimes totalitaires ont largement pratiqué la retouche pour effacer des personnes."],
    ["Qu'est-ce que l'effacement de personnes sur les photographies soviétiques ?", ["Une retouche systématique supprimant les disgraciés", "Une dégradation des tirages due à leur mauvaise conservation", "Une censure interdisant la publication de certains clichés", "Un archivage sélectif ne conservant qu'une partie des clichés"], 0,
     "L'ouvrage Le Commissaire disparaît en a rassemblé de nombreux exemples."],
    ["Qu'est-ce qu'une image sortie de son contexte ?", ["Une image authentique réutilisée pour illustrer un autre événement", "Une image truquée par un logiciel de retouche", "Une image recadrée pour en écarter un détail", "Une image mal légendée par simple erreur de la rédaction"], 0,
     "C'est le procédé de désinformation visuelle le plus fréquent aujourd'hui."],
    ["Qu'est-ce qu'un hypertrucage vidéo ?", ["Une vidéo synthétisée imitant une personne réelle", "Un montage vidéo qui inverse l'ordre des déclarations", "Un doublage remplaçant la voix d'origine par une autre", "Un effet spécial de cinéma classique"], 0,
     "Sa détection devient de plus en plus difficile à mesure que les modèles progressent."],
    ["Qu'est-ce que la provenance d'une image en vérification ?", ["L'identification de sa première publication et de son auteur", "Sa qualité technique et sa définition", "Son format de fichier et son taux de compression", "Sa date d'enregistrement lue dans les métadonnées"], 0,
     "La recherche d'image inversée est le premier outil pour l'établir."],
    ["Qu'est-ce que la géolocalisation d'une image ?", ["L'identification du lieu par comparaison avec des repères visuels", "La seule lecture des métadonnées enregistrées par l'appareil photo", "L'usage de la puce GPS intégrée à l'appareil de prise de vue", "L'analyse du réseau par lequel l'image a été mise en ligne pour la première fois"], 0,
     "Les enquêtes en source ouverte y recourent systématiquement."],
    ["Qu'est-ce que l'enquête en sources ouvertes ?", ["Une investigation à partir de données publiquement accessibles", "Une enquête menée sans aucune source identifiée ni document vérifiable", "Une enquête administrative ouverte par un service ministériel de l'État", "Une enquête judiciaire dont le dossier est ouvert au public et à la presse"], 0,
     "Elle a permis d'établir des faits dans plusieurs conflits récents."],
    ["Qu'est-ce que la certification d'origine d'un contenu ?", ["Un procédé technique attestant la provenance et les modifications d'un fichier", "Un filigrane visuel apposé sur l'image", "Un dépôt légal auprès d'une bibliothèque nationale", "Un droit d'auteur enregistré auprès d'une société de gestion"], 0,
     "Des standards de traçabilité des contenus se développent face aux images générées.", 3],
  ]),

  notion("cm3-metiers-medias", S, "Les métiers des médias",
    "Rédactions, production, technique.",
    "Un journal ou une chaîne repose sur des dizaines de métiers distincts.",
    2, [
    ["Que fait un rédacteur en chef ?", ["Il dirige la ligne éditoriale et coordonne la rédaction", "Il écrit les éditoriaux qui engagent la position du journal", "Il corrige les articles avant leur mise en page", "Il gère le budget et les effectifs de la rédaction du journal"], 0,
     "Il arbitre les sujets et la hiérarchie de l'information."],
    ["Que fait un secrétaire de rédaction ?", ["Il relit, titre et met en forme les articles", "Il rédige les brèves et les dépêches de dernière minute", "Il gère le planning des journalistes de la rédaction", "Il assiste le rédacteur en chef dans ses arbitrages"], 0,
     "Titres, chapôs et légendes relèvent souvent de lui, non de l'auteur de l'article."],
    ["Que fait un iconographe ?", ["Il recherche et sélectionne les images d'une publication", "Il retouche les photographies avant publication", "Il photographie l'actualité pour le journal", "Il archive les images déjà parues"], 0,
     "Il gère aussi les droits d'utilisation des images retenues."],
    ["Que fait un journaliste reporter d'images ?", ["Il filme, monte et parfois commente ses sujets", "Il photographie l'actualité pour la presse quotidienne", "Il dirige un tournage de fiction en studio", "Il monte les reportages rapportés par ses confrères"], 0,
     "Ce métier polyvalent s'est développé avec l'allègement du matériel."],
    ["Que fait un monteur en télévision ?", ["Il assemble images et sons pour construire le sujet", "Il enregistre les images sur le lieu même du reportage", "Il écrit le commentaire lu en voix off du sujet", "Il choisit les sujets traités dans le journal"], 0,
     "Sur les sujets d'actualité, il travaille souvent dans l'urgence avec le journaliste."],
    ["Que fait un réalisateur de télévision en direct ?", ["Il choisit en temps réel les images diffusées parmi plusieurs caméras", "Il met en scène le plateau et son décor", "Il dirige les intervenants pendant l'émission", "Il produit l'émission pour la chaîne"], 0,
     "Il travaille en régie, en dialogue permanent avec ses cadreurs."],
    ["Que fait un producteur audiovisuel ?", ["Il monte le financement et porte la responsabilité du projet", "Il réalise l'émission et en dirige le tournage sur le plateau", "Il vend le programme fini aux diffuseurs français et étrangers", "Il dirige la chaîne de télévision qui diffusera le programme"], 0,
     "Il détient les droits sur l'œuvre produite."],
    ["Que fait un documentaliste dans un média ?", ["Il recherche, vérifie et archive l'information et les documents", "Il rédige les résumés versés aux archives", "Il gère la bibliothèque du journal", "Il numérise les fonds anciens du média"], 0,
     "Son travail conditionne la fiabilité des rappels de faits et des chiffres publiés."],
    ["Que fait un community manager pour un média ?", ["Il anime la présence et les échanges sur les réseaux sociaux", "Il rédige les articles mis en ligne sur le site du média", "Il gère les statistiques d'audience du site et son référencement", "Il modère les commentaires laissés sous chaque article publié"], 0,
     "Il est souvent le premier point de contact entre le média et son public."],
    ["Que fait un directeur de la publication ?", ["Il assume la responsabilité juridique de ce qui est publié", "Il dirige la rédaction au quotidien", "Il représente les actionnaires du groupe de presse", "Il gère la diffusion et les abonnements"], 0,
     "En droit français, il est pénalement responsable en cas de délit de presse.", 3],
  ]),

  notion("cm3-censure-liberte", S, "Censure et liberté d'expression",
    "Contrôles, limites, débats.",
    "La censure préalable a disparu en France, mais des limites subsistent a posteriori.",
    2, [
    ["Qu'est-ce que la censure préalable ?", ["Un contrôle des contenus avant leur publication", "Une sanction prononcée après la diffusion du contenu", "Un retrait de contenu ordonné par le juge des référés", "Une interdiction de diffusion prononcée par une autorité"], 0,
     "Elle a été abolie pour la presse française en 1881."],
    ["Qu'est-ce que le visa d'exploitation d'un film en France ?", ["Une autorisation ministérielle assortie d'une classification par âge", "Une censure de contenu exercée par une commission", "Un agrément de production délivré au producteur", "Un label de qualité décerné par la profession"], 0,
     "La commission de classification propose l'un des visas possibles au ministre de la Culture."],
    ["Quelles classifications existent pour les films en France ?", ["Tous publics, moins de douze, seize et dix-huit ans", "Trois catégories, de tous publics à interdit aux mineurs", "Un système de notation par étoiles attribué par la commission", "Une classification unique pour toute l'Europe"], 0,
     "Certains films peuvent être interdits aux mineurs avec inscription sur une liste spécifique."],
    ["Qu'est-ce que le visa d'exploitation en France ?", ["Une autorisation de diffusion délivrée par le ministère de la Culture", "Un label de qualité attribué par les critiques de cinéma", "Une aide financière à la production versée par le Centre national du cinéma", "Un dépôt légal obligatoire d'une copie auprès des archives du film"], 0,
     "Il peut être assorti d'une interdiction aux mineurs, sur avis d'une commission de classification."],
    ["Quelles limites la loi française pose-t-elle à la liberté d'expression ?", ["Diffamation, injure, incitation à la haine et apologie de crimes", "Aucune limite depuis la loi de 1881", "Le blasphème, puni comme en droit ancien", "La critique des institutions de la République"], 0,
     "Ces limites sont définies par la loi et appréciées par le juge, non par une autorité administrative."],
    ["Qu'est-ce que la diffamation en droit français ?", ["L'allégation d'un fait portant atteinte à l'honneur d'une personne", "Une insulte adressée publiquement à une personne nommée", "Une critique sévère mais argumentée visant une personnalité publique", "Une opinion négative exprimée publiquement sur une personne connue"], 0,
     "La preuve de la vérité du fait peut constituer un moyen de défense."],
    ["Qu'est-ce que l'injure en droit de la presse ?", ["Une expression outrageante ne contenant l'imputation d'aucun fait", "Une accusation fausse portée contre quelqu'un", "Une critique blessante formulée en public", "Une diffamation légère sans conséquence pénale"], 0,
     "Contrairement à la diffamation, la vérité n'y constitue pas une défense."],
    ["Qu'est-ce qu'un procès-bâillon ?", ["Une action en justice visant à intimider et faire taire", "Un procès en diffamation engagé selon la procédure ordinaire", "Une procédure d'urgence permettant de suspendre une publication", "Un référé engagé pour obtenir un droit de réponse immédiat"], 0,
     "Une directive européenne de 2024 vise à en protéger journalistes et défenseurs des droits."],
    ["Qu'est-ce que la protection des sources journalistiques ?", ["Un droit de ne pas révéler l'identité de ses informateurs", "Un secret professionnel absolu et sans exception", "Une immunité judiciaire accordée aux journalistes", "Un droit d'accès aux documents administratifs"], 0,
     "Il connaît des exceptions justifiées par un impératif prépondérant d'intérêt public."],
    ["Qu'est-ce que l'autocensure ?", ["Une restriction que l'on s'impose par anticipation d'une sanction ou d'une réaction", "Une censure institutionnelle exercée par une autorité publique sur les contenus diffusés", "Un contrôle éditorial exercé par la direction du journal sur chaque article publié", "Une relecture juridique des textes avant publication"], 0,
     "Elle est plus difficile à mesurer que la censure explicite, mais souvent plus efficace.", 3],
  ]),

  notion("cm3-archives-audiovisuelles", S, "Conserver l'audiovisuel",
    "Archives, restauration, accès.",
    "Une part importante du patrimoine audiovisuel du XXe siècle a été perdue.",
    2, [
    ["Qu'est-ce que le dépôt légal du web média ?", ["La collecte automatique des sites liés à la radio et à la télévision", "Une obligation de sauvegarde pesant sur les chaînes et leurs éditeurs", "Un archivage volontaire organisé par les éditeurs de services en ligne", "Un catalogue commercial d'archives vendues aux producteurs"], 0,
     "Plusieurs dizaines de milliers de sites sont moissonnés périodiquement."],
    ["Qu'est-ce que le dépôt légal du web en France ?", ["La collecte automatisée de sites internet à des fins patrimoniales", "Un archivage volontaire confié aux hébergeurs", "Un enregistrement des noms de domaine déposés en France", "Une sauvegarde limitée aux sites des médias en ligne"], 0,
     "Il est partagé entre la BNF et l'INA selon la nature des sites."],
    ["Pourquoi de nombreuses émissions anciennes ont-elles disparu ?", ["Les bandes étaient effacées et réutilisées pour économiser", "Elles n'étaient pas enregistrées faute de matériel", "Les archives ont brûlé dans un incendie de studio", "Elles ont été censurées puis retirées des fonds"], 0,
     "Le direct dominait, et le support magnétique coûtait cher."],
    ["Qu'est-ce que la restauration numérique d'un film ?", ["Une numérisation suivie de corrections image par image", "Un simple transfert numérique de la copie d'exploitation", "Une colorisation des films anciens tournés en noir et blanc", "Une remasterisation portant sur la seule bande sonore du film"], 0,
     "Elle soulève la question du respect des choix esthétiques d'origine."],
    ["Qu'est-ce que le syndrome du vinaigre ?", ["Une dégradation chimique des pellicules acétate", "Une oxydation progressive des bandes magnétiques anciennes", "Une décoloration des films couleur mal stockés", "Un défaut de conservation des fichiers"], 0,
     "Elle est irréversible et contamine les bobines voisines."],
    ["Pourquoi les pellicules nitrate posent-elles problème ?", ["Elles sont extrêmement inflammables et se dégradent", "Elles sont trop fragiles pour être projetées", "Elles sont toxiques pour ceux qui les manipulent", "Elles perdent leurs couleurs en quelques années"], 0,
     "De nombreux incendies d'archives leur sont dus, dont plusieurs très destructeurs."],
    ["Qu'est-ce que la migration des supports numériques ?", ["Le transfert périodique des données vers des formats et supports actuels", "Une copie de sauvegarde des données conservée sur un second site géographique", "Un archivage sur bande magnétique conservé dans une chambre froide spécialisée", "Une conversion unique vers un format d'archivage définitif"], 0,
     "Sans elle, un fichier devient illisible en quelques décennies faute de lecteur ou de logiciel."],
    ["Qu'est-ce qu'un format ouvert en archivage ?", ["Un format dont la spécification est publique et documentée", "Un format gratuit et libre de redevance", "Un format non compressé occupant beaucoup d'espace", "Un format universel lisible par tous les logiciels"], 0,
     "Il réduit le risque de dépendre d'un éditeur disparu."],
    ["Qu'est-ce que la cinémathèque au sens patrimonial ?", ["Une institution collectant, conservant et projetant des films", "Une salle de cinéma d'art et essai programmant des films anciens", "Un musée consacré à l'histoire et aux techniques du cinéma muet", "Une bibliothèque de copies de films prêtées au public sur demande"], 0,
     "La Cinémathèque française a été fondée en 1936 par Henri Langlois et Georges Franju."],
    ["Pourquoi l'accès aux archives audiovisuelles est-il souvent limité ?", ["Les droits d'auteur et voisins restreignent leur diffusion", "Les supports anciens sont trop fragiles pour être manipulés", "Les archives conservées sont trop incomplètes pour être utiles", "L'accès y est payant dans la plupart des institutions"], 0,
     "Consulter sur place est souvent possible ; rediffuser exige de retrouver tous les ayants droit.", 3],
  ]),

  notion("cm3-cinema-documentaire-france", S, "Le documentaire en France",
    "Auteurs, financement, diffusion.",
    "Le documentaire français est largement soutenu par les diffuseurs télévisés.",
    2, [
    ["Comment le documentaire français est-il principalement financé ?", ["Par les diffuseurs télévisés et les aides publiques", "Par les recettes des salles de cinéma et de la vidéo à la demande", "Par le mécénat de fondations privées et de particuliers", "Par les plateformes de vidéo par abonnement"], 0,
     "Le préachat par une chaîne conditionne souvent l'accès aux autres financements."],
    ["Quel réalisateur français a filmé les paysans et les institutions ?", ["Raymond Depardon", "Chris Marker", "Nicolas Philibert", "Claire Simon"], 0,
     "Sa trilogie Profils paysans s'étale sur une dizaine d'années."],
    ["Qu'appelle-t-on le cinéma direct ?", ["Un documentaire en son synchrone, sans commentaire ni mise en scène", "Un film diffusé en direct à la télévision", "Un reportage de télévision commenté en voix off", "Un documentaire animalier tourné en milieu naturel"], 0,
     "Le matériel léger des années 1960 — caméra portable et magnétophone synchrone — l'a rendu possible."],
    ["Quel cinéaste français a mêlé essai, voyage et réflexion sur l'image ?", ["Chris Marker", "Jean Rouch", "Alain Resnais", "Agnès Varda"], 0,
     "Sans soleil, en 1983, est l'un des essais filmés les plus commentés."],
    ["Quel film d'Alain Resnais de 1956 porte sur les camps de concentration ?", ["Nuit et brouillard", "Hiroshima mon amour", "Toute la mémoire du monde", "Guernica"], 0,
     "Il a fait l'objet de pressions diplomatiques et d'une censure partielle à sa sortie."],
    ["Quel documentaire de 1969 traite de la France sous l'Occupation ?", ["Le Chagrin et la Pitié", "La Section Anderson de Pierre Schoendoerffer", "La Bataille du rail de René Clément", "Le Temps du ghetto"], 0,
     "Marcel Ophüls y bouscule le récit résistancialiste ; la télévision française l'a longtemps refusé."],
    ["Quel film de Claude Lanzmann interroge des témoins de la Shoah pendant neuf heures ?", ["Shoah", "Le Chagrin et la Pitié", "Nuit et brouillard", "Sobibor"], 0,
     "Il n'utilise aucune image d'archive, par choix méthodologique assumé."],
    ["Quelle cinéaste française mêle documentaire et fiction dans son œuvre ?", ["Agnès Varda", "Claire Denis", "Chantal Akerman", "Marguerite Duras"], 0,
     "Les Glaneurs et la Glaneuse, en 2000, en est un exemple emblématique."],
    ["Qu'est-ce que la case documentaire à la télévision française ?", ["Un créneau de programmation dédié dans une grille", "Une commande annuelle passée par la chaîne", "Une aide spécifique du fonds de soutien", "Un format imposé aux producteurs"], 0,
     "Ces cases déterminent largement les durées et les formes du documentaire produit."],
    ["Quel festival de documentaire se tient à Marseille chaque été ?", ["Le Festival international du documentaire, le FID", "Le Festival international du film d'animation d'Annecy", "Les États généraux du documentaire de Lussas", "Le festival Cinéma du réel, au Centre Pompidou"], 0,
     "Les États généraux du documentaire de Lussas en sont un autre rendez-vous majeur.", 3],
  ]),

  notion("cm3-publicite-medias", S, "La publicité dans les médias",
    "Formats, mesure, régulation.",
    "La publicité finance une part majeure des médias gratuits.",
    2, [
    ["Qu'est-ce qu'un spot publicitaire télévisé ?", ["Un message audiovisuel diffusé dans un écran publicitaire", "Une émission parrainée par une marque", "Un placement de produit dans une fiction", "Un publireportage publié dans la presse"], 0,
     "Sa durée standard est de vingt ou trente secondes."],
    ["Qu'est-ce que le parrainage d'émission ?", ["Un financement associant une marque à un programme", "Une publicité classique diffusée entre deux programmes", "Un placement de produit intégré au décor d'une émission", "Un soutien financier apporté à un événement sportif"], 0,
     "Il doit être clairement identifié et ne peut influencer le contenu éditorial."],
    ["Qu'est-ce que le prime time publicitaire ?", ["La tranche horaire où les tarifs publicitaires sont les plus élevés", "La première coupure publicitaire d'un programme", "L'écran publicitaire précédant le journal télévisé", "Le créneau du matin réservé aux annonceurs locaux"], 0,
     "Le prix d'un spot y peut dépasser plusieurs dizaines de milliers d'euros."],
    ["Qu'est-ce que le coût pour mille en publicité ?", ["Le coût pour atteindre mille personnes ou mille affichages", "Le prix facturé pour la diffusion de mille spots publicitaires", "Le tarif horaire pratiqué pour un espace publicitaire en télévision", "Le coût par clic d'une annonce multiplié par mille clics"], 0,
     "C'est l'indicateur de référence pour comparer des supports différents."],
    ["Qu'est-ce que la publicité programmatique ?", ["Un achat d'espaces automatisé et ciblé en temps réel", "Une programmation des écrans publicitaires d'une chaîne", "Une publicité planifiée plusieurs mois à l'avance", "Un achat groupé d'espaces par une centrale"], 0,
     "Elle domine aujourd'hui l'essentiel du marché publicitaire en ligne."],
    ["Qu'est-ce que le ciblage publicitaire comportemental ?", ["Un ciblage fondé sur l'historique de navigation de l'utilisateur", "Un ciblage géographique par région", "Un ciblage par âge et par sexe déclarés", "Un ciblage contextuel choisi par l'annonceur"], 0,
     "Le ciblage contextuel, fondé sur le contenu de la page, ne suppose pas de collecte de données personnelles."],
    ["Qu'est-ce que la fraude publicitaire en ligne ?", ["Des affichages ou clics générés artificiellement", "Une publicité mensongère sur les qualités d'un produit", "Un placement de produit non signalé au téléspectateur", "Un ciblage abusif visant délibérément des publics vulnérables"], 0,
     "Elle représenterait plusieurs dizaines de milliards de dollars par an dans le monde."],
    ["Qu'est-ce qu'un bloqueur de publicité ?", ["Un outil empêchant l'affichage des annonces sur un site", "Un filtre de contenu réservé aux mineurs", "Un antivirus installé sur le navigateur", "Un gestionnaire des cookies déposés par les sites"], 0,
     "Son usage massif a fragilisé le modèle des médias gratuits en ligne."],
    ["Qu'est-ce que le consentement aux cookies publicitaires ?", ["Une autorisation préalable requise pour le suivi à des fins publicitaires", "Une information obligatoire affichée au visiteur avant tout dépôt de cookie", "Une acceptation implicite déduite de la simple poursuite de la navigation", "Un réglage du navigateur laissé au choix de l'internaute"], 0,
     "Refuser doit être aussi simple qu'accepter, selon la doctrine de la CNIL."],
    ["Qu'est-ce que l'encadrement de la publicité pour les enfants ?", ["Des règles limitant certains messages dans les programmes jeunesse", "Une interdiction totale de la publicité sur toutes les chaînes françaises", "Une autorégulation volontaire des annonceurs, sans règle contraignante", "Une limitation des horaires de diffusion seulement"], 0,
     "La publicité a été supprimée des programmes jeunesse de la télévision publique française en 2018.", 3],
  ]),

  notion("cm3-medias-societe", S, "Médias et société",
    "Représentations, effets, réception.",
    "Les médias ne dictent pas les opinions, mais ils orientent ce dont on parle.",
    2, [
    ["Qu'est-ce que la théorie de l'agenda ?", ["L'idée que les médias déterminent moins ce qu'on pense que ce à quoi on pense", "Une théorie de la manipulation des esprits par la presse", "Une théorie expliquant la mesure de l'audience", "Un modèle de programmation des grilles de télévision"], 0,
     "Formulée par McCombs et Shaw en 1972, elle reste l'un des acquis les mieux établis."],
    ["Qu'est-ce que le cadrage médiatique ?", ["La manière dont un sujet est présenté, orientant son interprétation", "Le format retenu pour une émission et la durée de chacune de ses séquences", "Le choix des images qui viennent illustrer un sujet au journal télévisé", "La hiérarchie de l'information retenue par la rédaction"], 0,
     "Parler d'un plan social ou d'un licenciement collectif ne produit pas le même effet."],
    ["Qu'est-ce que la spirale du silence ?", ["La tendance à taire une opinion perçue comme minoritaire", "Un silence médiatique organisé sur un sujet", "Une absence de couverture d'un événement", "Un boycott de l'information par le public"], 0,
     "Théorisée par Elisabeth Noelle-Neumann dans les années 1970."],
    ["Qu'est-ce que le modèle de la réception active ?", ["L'idée que le public interprète activement les messages reçus", "Une théorie des effets directs et immédiats des médias sur le public", "Un modèle décrivant la diffusion des programmes vers le public", "Une théorie décrivant une audience captive et durablement fidélisée"], 0,
     "Il s'oppose au modèle d'une seringue hypodermique injectant des idées au public."],
    ["Qu'est-ce que la représentation des minorités dans les médias ?", ["Une question de visibilité et de qualité des rôles attribués", "Un quota de diffusion imposé aux chaînes", "Une obligation légale inscrite dans la loi", "Une politique éditoriale propre à chaque média"], 0,
     "L'Arcom publie chaque année un baromètre de la diversité à la télévision française."],
    ["Qu'est-ce que le test de Bechdel ?", ["Un critère simple évaluant la place des personnages féminins dans une fiction", "Une mesure de la part des femmes dans l'audience d'un programme de télévision", "Un indicateur de la parité entre femmes et hommes dans les équipes de production", "Un label attribué aux fictions soucieuses de représentation"], 0,
     "Deux femmes nommées y parlent entre elles d'autre chose que d'un homme."],
    ["Qu'est-ce que la parité dans le cinéma français ?", ["Un objectif encore loin d'être atteint parmi les réalisateurs", "Une réalité acquise depuis le début des années 2010", "Une obligation légale imposée aux producteurs", "Un critère de financement imposé par les chaînes"], 0,
     "Environ un quart des films français sont réalisés par des femmes, avec des budgets inférieurs."],
    ["Qu'est-ce que le mouvement MeToo dans l'audiovisuel ?", ["Une vague de témoignages sur les violences sexuelles dans le secteur", "Une campagne de communication lancée par les grands studios américains", "Une réforme du droit du travail applicable aux techniciens intermittents", "Une charte professionnelle signée par les syndicats du cinéma français"], 0,
     "Il a conduit à la création de dispositifs de prévention et de coordinateurs d'intimité."],
    ["Qu'est-ce que l'influence des médias sur les comportements ?", ["Un effet réel mais indirect, médiatisé par de nombreux facteurs", "Un effet direct et immédiatement mesurable sur les conduites individuelles", "Un effet inexistant, démenti par toutes les enquêtes récentes", "Un effet limité aux seuls enfants et adolescents"], 0,
     "Les recherches montrent des effets conditionnés par le contexte social et les prédispositions."],
    ["Qu'est-ce que l'exposition sélective à l'information ?", ["La tendance à choisir des contenus conformes à ses convictions", "Une limitation volontaire du temps que l'on passe devant les écrans", "Un ciblage algorithmique opéré par les plateformes de réseaux sociaux", "Une consommation aléatoire de contenus au fil du flux"], 0,
     "Elle existait bien avant les réseaux sociaux, qui l'ont facilitée sans la créer.", 3],
  ]),

  notion("cm3-son-cinema", S, "Le son au cinéma",
    "Conception sonore, écoute, effets.",
    "Le son représente une part considérable de l'expérience du spectateur, souvent inconsciente.",
    2, [
    ["Qu'est-ce que la conception sonore d'un film ?", ["La construction d'un univers sonore complet et cohérent", "L'enregistrement du son direct sur le plateau", "Le mixage final des pistes du film", "L'ajout de bruitages en auditorium"], 0,
     "Elle commence dès l'écriture chez certains réalisateurs."],
    ["Qu'est-ce que le son direct ?", ["Le son enregistré pendant la prise de vue", "Le son ajouté en postproduction par l'équipe de montage", "Le son d'ambiance capté après le tournage", "Le son des dialogues doublés en langue étrangère"], 0,
     "Sa qualité conditionne le naturel du jeu perçu par le spectateur."],
    ["Qu'est-ce qu'une ambiance sonore ?", ["Un fond sonore situant le lieu et l'époque", "Un bruitage ponctuel synchronisé sur un geste", "Une musique de fond composée pour accompagner la scène", "Un effet spécial sonore de synthèse"], 0,
     "Une même image peut changer complètement de sens selon l'ambiance qui l'accompagne."],
    ["Qu'est-ce que le montage son d'un film ?", ["L'assemblage des dialogues, des ambiances et des effets avant le mixage", "Le réglage final des niveaux en auditorium", "L'enregistrement du son sur le plateau de tournage", "La composition de la musique originale du film"], 0,
     "Il prépare les pistes que le mixage viendra ensuite équilibrer."],
    ["Qu'est-ce qu'un son hors champ ?", ["Un son dont la source n'est pas visible à l'image", "Un son ajouté au montage après coup", "Une voix off lisant un commentaire écrit à l'avance", "Un son d'ambiance lointain venu de l'extérieur du décor"], 0,
     "Il élargit l'espace du film au-delà du cadre."],
    ["Qu'est-ce qu'une voix off ?", ["Une voix extérieure à l'espace de la scène", "Un dialogue prononcé hors du champ de la caméra", "Une pensée intérieure formulée par un personnage", "Un commentaire documentaire lu sur les images"], 0,
     "La voix intérieure d'un personnage en est un cas particulier."],
    ["Qu'est-ce que le silence au cinéma ?", ["Un élément de dramaturgie sonore aussi construit que le bruit", "Une absence totale de son sur la bande", "Un défaut technique de la bande sonore", "Une coupure accidentelle de la bande son"], 0,
     "Un silence total est rare : il est souvent construit avec une ambiance très ténue."],
    ["Qu'est-ce qu'un son subjectif ?", ["Un son restituant la perception d'un personnage", "Un son d'ambiance enregistré sur le lieu du tournage", "Un son volontairement saturé au mixage", "Un son de synthèse entièrement fabriqué en studio"], 0,
     "L'assourdissement des scènes de combat traduit ainsi le traumatisme d'un personnage."],
    ["Qu'est-ce que la postsynchronisation ?", ["Le réenregistrement des dialogues en studio après le tournage", "Le mixage final réalisé en auditorium", "Le doublage du film en langue étrangère", "L'ajout de la musique originale au montage"], 0,
     "Elle sauve une prise dont le son direct est inutilisable, au prix d'un jeu à refaire."],
    ["Pourquoi le son est-il souvent sous-estimé par le spectateur ?", ["Il agit largement en dessous du seuil de l'attention consciente", "Il est moins travaillé que l'image par les équipes", "Il est ajouté tardivement, à la toute fin du montage", "Il est moins coûteux à produire que les effets visuels d'un film"], 0,
     "Couper le son d'une scène d'action suffit à mesurer son rôle dans l'émotion produite.", 3],
  ]),

  notion("cm3-cinema-economie-mondiale", S, "Le cinéma dans le monde",
    "Marchés, production, circulation.",
    "Le cinéma américain domine le marché mondial mais ne produit pas le plus de films.",
    2, [
    ["Qu'est-ce qu'une coproduction internationale ?", ["Un film financé par des sociétés de plusieurs pays", "Un film tourné à l'étranger avec une équipe locale réduite", "Un film doublé et sous-titré dans plusieurs langues étrangères", "Un film distribué dans le monde entier par un grand studio"], 0,
     "Les accords bilatéraux ouvrent alors l'accès aux aides publiques de chaque pays partenaire."],
    ["Quel surnom porte l'industrie cinématographique nigériane ?", ["Nollywood", "Bollywood", "Kannywood", "Ghallywood"], 0,
     "Elle produit à très bas coût des films destinés d'abord à la vidéo et au streaming."],
    ["Quel marché cinématographique a connu la croissance la plus rapide au XXIe siècle ?", ["La Chine", "L'Inde", "Le Brésil", "La Russie"], 0,
     "Le nombre d'écrans y est passé d'environ deux mille en 2003 à plus de quatre-vingt mille vingt ans plus tard."],
    ["Qu'est-ce qu'un quota d'écran ?", ["Une obligation de projeter une part de films nationaux", "Un plafond du nombre de films étrangers importés", "Une taxe sur les importations de films étrangers", "Un nombre maximal de séances par jour et par salle"], 0,
     "La Corée du Sud en a longtemps appliqué un, contesté par les États-Unis."],
    ["Qu'est-ce que l'exception culturelle dans les négociations commerciales ?", ["Le refus de traiter les biens culturels comme des marchandises ordinaires", "Une exonération fiscale accordée aux industries culturelles des États membres", "Une aide d'État autorisée par dérogation aux règles de la concurrence européenne", "Une clause de sauvegarde invocable en cas de crise"], 0,
     "Elle a permis d'exclure l'audiovisuel des accords de libéralisation des années 1990."],
    ["Qu'est-ce qu'un accord de coproduction cinématographique ?", ["Un traité permettant à un film de bénéficier des aides de plusieurs pays", "Un accord de distribution signé avec un exploitant étranger", "Un contrat de tournage liant le producteur à ses équipes", "Une vente de droits de diffusion à une chaîne étrangère"], 0,
     "La France a signé de tels accords avec plusieurs dizaines de pays."],
    ["Qu'est-ce que le marché du film en ligne pour les distributeurs ?", ["Un marché de droits par territoire, désormais concurrencé par les plateformes mondiales", "Un marché unique mondial où les droits sont cédés une seule fois pour tous les pays", "Un marché de licences libres où les films circulent sans droits exclusifs", "Un marché de gré à gré négocié salle par salle dans chaque ville"], 0,
     "Les plateformes achètent souvent des droits mondiaux, ce qui bouleverse ce découpage."],
    ["Qu'est-ce qu'un festival de catégorie A ?", ["Un festival international compétitif reconnu par la fédération des producteurs", "Un festival classé selon son importance médiatique et son audience internationale", "Un festival subventionné par les pouvoirs publics du pays qui l'organise chaque année", "Un festival réservé aux films d'auteur non commerciaux"], 0,
     "Cannes, Venise, Berlin et une dizaine d'autres en font partie."],
    ["Qu'est-ce que la sortie mondiale simultanée ?", ["Une diffusion coordonnée dans de nombreux pays le même jour", "Une avant-première internationale organisée dans plusieurs capitales", "Une sortie directe sur les plateformes de streaming du monde entier", "Une distribution par vagues successives selon les continents"], 0,
     "Elle vise notamment à limiter le piratage."],
    ["Quel effet le streaming a-t-il eu sur la circulation des films étrangers ?", ["Il a élargi l'accès à des cinématographies jusque-là peu diffusées", "Il a réduit la diversité des films accessibles au grand public", "Il n'a rien changé à la circulation internationale des longs métrages", "Il a favorisé les seuls films américains et leurs adaptations"], 0,
     "L'effet est ambivalent : plus d'accès théorique, mais une visibilité concentrée par les algorithmes.", 3],
  ]),

  notion("cm3-jeu-video-industrie", S, "L'industrie du jeu vidéo",
    "Studios, modèles, France.",
    "Le jeu vidéo pèse économiquement plus que le cinéma et la musique réunis.",
    2, [
    ["Quel est le poids économique du jeu vidéo dans le monde ?", ["Supérieur à celui du cinéma et de la musique réunis", "Comparable à celui du cinéma en salle", "Inférieur à celui de l'industrie de la musique enregistrée", "Marginal au regard des autres industries"], 0,
     "Le marché mondial dépasse les deux cents milliards de dollars annuels."],
    ["Qu'est-ce qu'un studio de développement ?", ["Une structure concevant et produisant le jeu", "Un éditeur", "Un distributeur de jeux en boîte", "Un studio spécialisé dans la capture de mouvement"], 0,
     "L'éditeur, distinct, finance et commercialise le titre."],
    ["Qu'est-ce que le crunch dans le jeu vidéo ?", ["Des périodes de surcharge de travail intense avant une échéance", "Une phase de test avant la sortie", "Une optimisation technique menée dans les dernières semaines du projet", "Une compression des fichiers du jeu"], 0,
     "Ses effets sur la santé des salariés ont fait l'objet de nombreux témoignages depuis 2004."],
    ["Quelle place la France occupe-t-elle dans le jeu vidéo ?", ["Un pôle important de création, avec plusieurs studios majeurs", "Un marché de consommation dépourvu de la moindre production locale", "Un acteur marginal du secteur", "Un simple distributeur de jeux étrangers"], 0,
     "Ubisoft, né en Bretagne en 1986, est devenu l'un des plus grands éditeurs mondiaux."],
    ["Qu'est-ce que le crédit d'impôt jeu vidéo en France ?", ["Un dispositif fiscal soutenant la création de jeux à contenu culturel", "Une subvention directe versée aux studios", "Un prêt public à taux réduit", "Une exonération de charges sociales pour les studios"], 0,
     "Il conditionne l'aide à des critères culturels et de localisation des dépenses."],
    ["Qu'est-ce qu'un jeu free-to-play ?", ["Un jeu gratuit financé par des achats intégrés", "Un jeu en accès libre, sans aucune source de revenus", "Un jeu de démonstration limité", "Un jeu au code source ouvert"], 0,
     "Une très faible minorité de joueurs y génère l'essentiel du chiffre d'affaires."],
    ["Qu'est-ce qu'un coffre à butin ?", ["Un contenu aléatoire acheté sans connaître son contenu", "Un bonus de progression accordé au joueur", "Une extension payante", "Un objet rare gagné en récompense au cours de la partie"], 0,
     "Plusieurs pays l'ont assimilé à un jeu de hasard et l'ont réglementé."],
    ["Qu'est-ce que le jeu en nuage ?", ["Un jeu exécuté sur des serveurs distants et diffusé en flux vidéo", "Un jeu en ligne à plusieurs joueurs", "Un jeu téléchargeable une fois pour toutes", "Un jeu dont les sauvegardes sont conservées à distance"], 0,
     "Il supprime le besoin de matériel puissant mais exige une connexion très stable."],
    ["Qu'est-ce qu'un studio de développement de jeu vidéo ?", ["L'équipe qui conçoit et réalise le jeu, souvent pour un éditeur", "Le distributeur du jeu en magasin", "Le fabricant de la console de jeu", "La plateforme qui vend le jeu en ligne"], 0,
     "L'éditeur finance et commercialise ; le studio fabrique, et dépend souvent de lui."],
    ["Qu'est-ce que le jeu vidéo indépendant a apporté ?", ["Une diversité de formes et de propos hors des logiques de blockbuster", "Une baisse générale des prix", "Une simplification technique des jeux", "Une concurrence directe avec les gros titres"], 0,
     "Des jeux comme Braid, Undertale ou Papers, Please y ont exploré des sujets et des formes que les gros budgets évitent.", 3],
  ]),

  notion("cm3-education-image", S, "Éduquer au regard",
    "Analyser les images, comprendre leur fabrication.",
    "Savoir lire une image s'apprend autant que savoir lire un texte.",
    2, [
    ["Qu'est-ce que l'éducation à l'image ?", ["Un apprentissage de l'analyse et de la fabrication des images", "Un cours d'arts plastiques du programme scolaire", "Une initiation au cinéma réservée aux lycéens", "Une formation technique aux métiers de l'image"], 0,
     "Elle combine analyse critique et pratique de création."],
    ["Qu'est-ce que le dispositif École et cinéma ?", ["Un programme faisant découvrir des films en salle aux élèves", "Un cours de cinéma inscrit à l'emploi du temps de tous les élèves", "Un festival scolaire où les classes présentent leurs propres films", "Une projection organisée dans la classe sur le temps scolaire"], 0,
     "Il existe des déclinaisons pour le collège et le lycée."],
    ["Qu'est-ce que le Prix Jean Renoir des lycéens ?", ["Un prix cinématographique décerné par des élèves", "Un concours de courts métrages réalisés par des lycéens", "Un prix de la critique remis par des journalistes de cinéma", "Une bourse d'études offerte à un jeune cinéaste"], 0,
     "Les lycéens y voient plusieurs films en salle et rédigent des critiques."],
    ["Qu'est-ce qu'un atelier de pratique audiovisuelle ?", ["Un atelier où les participants réalisent eux-mêmes un film", "Un cours théorique sur l'histoire du cinéma", "Une projection commentée par un intervenant", "Une visite guidée d'un studio de tournage"], 0,
     "Comprendre la fabrication est l'un des moyens les plus efficaces de développer l'esprit critique."],
    ["Qu'est-ce que l'analyse de plan ?", ["Un examen détaillé du cadrage, de la lumière et du mouvement d'une image", "Un résumé de la scène et de la place qu'elle occupe dans le récit du film", "Une critique argumentée du film, publiée après sa sortie dans les salles françaises", "Une description narrative de ce que montre l'image"], 0,
     "Elle précède l'interprétation et la fonde."],
    ["Qu'est-ce que la lecture d'une affiche de film ?", ["Une analyse des choix graphiques et de leur stratégie", "Une description de ce que montre l'affiche du film", "Une identification du film et de ses principaux interprètes", "Une critique esthétique du travail du graphiste"], 0,
     "Typographie, hiérarchie des noms et cadrage y répondent à des codes précis."],
    ["Qu'est-ce que l'analyse d'une une de journal ?", ["Un examen de la hiérarchie et des choix éditoriaux d'un média", "Une lecture des titres et des chapôs de la page", "Un résumé de l'actualité du jour en quelques lignes", "Une comparaison des ventes de plusieurs journaux"], 0,
     "Comparer plusieurs unes d'un même jour est l'un des exercices les plus révélateurs."],
    ["Qu'est-ce que la manipulation par le cadrage ?", ["Le fait d'inclure ou d'exclure des éléments pour orienter la lecture", "Un recadrage technique effectué pour ajuster l'image au format de la page", "Une déformation optique produite par l'emploi d'un objectif grand angle", "Un montage trompeur rapprochant deux photographies sans aucun rapport"], 0,
     "Une foule peut paraître dense ou clairsemée selon l'angle choisi."],
    ["Qu'est-ce que le point de vue dans une image ?", ["La position depuis laquelle l'image est prise, jamais neutre", "Le sujet principal représenté dans l'image", "L'opinion personnelle du photographe sur son sujet", "La légende associée à l'image lors de sa publication"], 0,
     "Photographier une manifestation depuis la police ou depuis les manifestants ne produit pas la même image."],
    ["Pourquoi l'éducation à l'image concerne-t-elle tous les âges ?", ["La production et la circulation des images évoluent constamment", "Les enfants sont les seuls à être réellement exposés à ces images", "Les adultes savent déjà lire les images sans apprentissage particulier", "L'école suffit à donner ces compétences"], 0,
     "Les compétences acquises il y a vingt ans ne suffisent pas face aux images générées aujourd'hui.", 3],
  ]),
];
