/**
 * Gastronomie & Art de vivre, troisième lot — quatorze notions ; les cours sont dans cours/gastronomie.ts.
 * Huit notions du lot d'origine (ga3-arts-table, ga3-conservation, ga3-cuisine-technique,
 * ga3-herbes-epices, ga3-produits-mer, ga3-restauration-metiers, ga3-histoire-repas,
 * ga3-alimentation-futur) ont été supprimées : elles reprenaient, souvent mot pour mot, des
 * questions des deux premiers lots (voir .travail-audit/rapports/gastronomie.md). ga3-agriculture-
 * alimentation, elle, a été conservée malgré le même défaut : c'est la cible d'une fusion interne
 * déclarée dans cours/fusions.ts (FUSIONS_INTERNES["ga-agriculture-alimentation"]) — la supprimer
 * ferait échouer cette fusion au chargement.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Gastronomie & Art de vivre";

export const CG_GASTRONOMIE_3: SeedSkill[] = [
  notion("ga3-cuisines-asie", S, "Les cuisines d'Asie",
    "Chine, Japon, Corée, Asie du Sud-Est.",
    "La cuisine chinoise réunit des traditions régionales très différentes entre elles.",
    2, [
    ["Quelle cuisine chinoise est réputée pour son usage du piment et du poivre du Sichuan ?", ["La cuisine sichuanaise", "La cuisine cantonaise du delta de la rivière des Perles", "La cuisine du Shandong", "La cuisine du Jiangsu, plus douce"], 0,
     "Le poivre du Sichuan produit une sensation d'engourdissement caractéristique."],
    ["Quelle cuisine chinoise a le plus influencé les restaurants chinois d'Occident ?", ["La cuisine cantonaise", "La cuisine du Hunan, très pimentée", "La cuisine pékinoise", "La cuisine du Fujian"], 0,
     "L'émigration depuis le Guangdong au XIXe siècle en explique la diffusion."],
    ["Qu'est-ce que le dim sum ?", ["Un ensemble de petites préparations servies à la vapeur ou frites", "Un plat cantonais unique, servi en fin de banquet", "Une soupe de nouilles au bouillon de porc, servie au petit-déjeuner", "Un dessert chinois sucré à la pâte de haricot rouge"], 0,
     "Traditionnellement servi le matin avec du thé, d'où le nom de yum cha."],
    ["Qu'est-ce que le dashi dans la cuisine japonaise ?", ["Un bouillon de base à l'algue kombu et au poisson séché", "Une sauce soja claire utilisée pour tous les assaisonnements", "Un vinaigre de riz doux employé pour assaisonner le riz à sushi", "Une pâte de soja fermenté délayée dans l'eau chaude"], 0,
     "Il est à l'origine de la découverte de l'umami par Kikunae Ikeda en 1908."],
    ["Qu'est-ce que le miso ?", ["Une pâte fermentée de soja", "Une sauce de poisson fermenté", "Un bouillon clair", "Un condiment au piment et à l'ail"], 0,
     "Sa fermentation peut durer de quelques mois à plusieurs années."],
    ["Qu'est-ce que le kimchi coréen ?", ["Un légume fermenté, le plus souvent du chou pimenté", "Une soupe épicée au piment rouge et au tofu de soja", "Un condiment au piment fermenté longuement en jarre de terre", "Un plat de riz sauté aux légumes"], 0,
     "La préparation collective d'automne, le kimjang, est inscrite au patrimoine immatériel."],
    ["Qu'est-ce que le nuoc-mâm ?", ["Une sauce de poisson fermenté vietnamienne", "Une sauce sucrée à base de caramel", "Un bouillon de poisson servi avec les nouilles", "Une pâte de crevettes séchées et pilées"], 0,
     "Le garum romain reposait sur un principe de fermentation comparable."],
    ["Qu'est-ce que le pho vietnamien ?", ["Une soupe de nouilles de riz au bouillon longuement mijoté", "Un plat de riz sauté au bœuf", "Une soupe de légumes verts au bouillon de volaille", "Un ragoût de bœuf mijoté à la citronnelle et à l'anis étoilé"], 0,
     "Née au début du XXe siècle dans le nord du Vietnam."],
    ["Qu'est-ce que le curry thaï vert ?", ["Une préparation à base de pâte d'épices fraîches et de lait de coco", "Un curry indien adapté au goût thaïlandais", "Une sauce au piment vert et au citron vert, sans aucune matière grasse", "Un bouillon épicé aux herbes, servi très clair et brûlant"], 0,
     "Sa couleur vient des piments verts frais broyés dans la pâte."],
    ["Quel principe structure de nombreuses cuisines d'Asie du Sud-Est ?", ["L'équilibre entre acide, sucré, salé et pimenté", "La domination du piment sur toutes les autres saveurs", "L'usage exclusif du riz comme féculent", "La cuisson à la vapeur de presque tous les plats"], 0,
     "Ce jeu d'équilibres se règle en fin de cuisson, au goût.", 3],
  ]),

  notion("ga3-cuisines-moyen-orient", S, "Les cuisines du Levant et du Maghreb",
    "Mezzés, épices, pains.",
    "Le partage des mezzés structure le repas dans une grande partie du Levant.",
    2, [
    ["Qu'est-ce que le houmous ?", ["Une purée de pois chiches au sésame", "Une purée d'aubergine grillée au sésame", "Une pâte de sésame pure", "Une sauce au yaourt et à la menthe"], 0,
     "Le tahini, pâte de sésame, en est l'autre ingrédient essentiel."],
    ["Qu'est-ce que le taboulé libanais ?", ["Une salade dominée par le persil, avec peu de boulgour", "Une salade de semoule fine où le persil est un simple décor", "Une salade de tomates, de concombres et d'oignons doux", "Un plat de boulgour chaud aux épices"], 0,
     "La version française, majoritairement composée de semoule, en est très éloignée."],
    ["Qu'est-ce que le za'atar ?", ["Un mélange d'herbes séchées, de sumac et de sésame", "Une épice unique récoltée au Levant", "Un piment doux moulu, d'une couleur très sombre", "Une herbe fraîche que l'on hache juste avant de servir"], 0,
     "Il désigne aussi la plante, une variété d'origan sauvage."],
    ["Qu'est-ce que le sumac ?", ["Une épice acidulée obtenue à partir de baies séchées", "Une graine aromatique", "Une écorce", "Une racine séchée que l'on râpe sur les plats"], 0,
     "Il apporte l'acidité là où d'autres cuisines emploient le citron."],
    ["Qu'est-ce que le couscous ?", ["Une semoule de blé dur roulée, cuite à la vapeur", "Un plat de semoule servi en bouillie sucrée", "Un ragoût de légumes qui accompagne la semoule", "Une préparation de blé concassé puis simplement bouilli"], 0,
     "Sa préparation est inscrite au patrimoine immatériel par quatre pays du Maghreb."],
    ["Qu'est-ce que le tajine ?", ["Un plat mijoté et le récipient conique qui lui donne son nom", "Un ragoût d'agneau aux pruneaux servi à la cuiller", "Un plat de légumes cuits séparément puis dressés en dôme sur le plat", "Une cocotte en terre vernissée, sans rapport avec le plat qu'on y cuit"], 0,
     "Le couvercle conique fait retomber la vapeur condensée sur les aliments."],
    ["Qu'est-ce que le ras el-hanout ?", ["Un mélange d'épices dont la composition varie selon le marchand", "Une épice unique venue du sud marocain", "Un piment marocain séché au soleil puis longuement moulu au mortier", "Un mélange strictement fixé à sept épices par une tradition ancienne"], 0,
     "Le nom signifie littéralement la tête de la boutique, soit le meilleur du commerçant."],
    ["Qu'est-ce que la harissa ?", ["Une pâte de piment tunisienne", "Une sauce tomate épicée servie froide", "Un mélange d'épices sèches", "Une huile pimentée d'olive"], 0,
     "Elle est inscrite au patrimoine immatériel de l'humanité depuis 2022."],
    ["Qu'est-ce que le citron confit ?", ["Un citron conservé au sel, utilisé dans les tajines", "Un citron entier séché au soleil pendant des semaines", "Un citron conservé au vinaigre blanc", "Un citron confit au sucre, comme une friandise"], 0,
     "Seule l'écorce est généralement employée, la pulpe étant écartée."],
    ["Qu'est-ce que la pâtisserie orientale au miel ?", ["Un ensemble de préparations à base de pâte fine, de fruits secs et de sirop", "Une pâtisserie unique, rigoureusement identique d'un pays à l'autre du Levant", "Un dessert au miel servi exclusivement lors des fêtes religieuses", "Une confiserie aux amandes et au miel, toujours sans pâte ni farine"], 0,
     "Baklava, cornes de gazelle et makrout relèvent de traditions distinctes.", 3],
  ]),

  notion("ga3-cuisines-ameriques", S, "Les cuisines des Amériques",
    "Mexique, Pérou, Brésil, États-Unis.",
    "La cuisine mexicaine traditionnelle est inscrite au patrimoine immatériel de l'humanité.",
    2, [
    ["Qu'est-ce que la nixtamalisation ?", ["Un traitement du maïs à l'eau alcaline", "Un broyage du maïs à la meule de pierre", "Une fermentation du maïs avant la mouture", "Un séchage traditionnel des épis au soleil"], 0,
     "Elle libère la vitamine B3 et a permis aux civilisations mésoaméricaines d'éviter la pellagre."],
    ["Qu'est-ce que le mole mexicain ?", ["Une sauce complexe mêlant piments, épices et parfois chocolat", "Un plat de viande de dinde longuement mijoté", "Une sauce au chocolat noir, sucrée, que l'on sert sur les desserts", "Un ragoût de viande de porc fortement épicé au piment rouge"], 0,
     "Le mole poblano peut compter plus de vingt ingrédients."],
    ["Quel piment mexicain est un jalapeño fumé ?", ["Le chipotle", "L'ancho", "Le guajillo", "Le habanero"], 0,
     "L'ancho est un poblano séché, le guajillo un mirasol séché."],
    ["Qu'est-ce que le ceviche péruvien ?", ["Du poisson cru mariné dans du jus d'agrume", "Un poisson réellement cuit par le jus de citron", "Une salade de poisson cuit et de légumes", "Un tartare de poisson relevé au piment"], 0,
     "L'acidité dénature les protéines sans cuisson thermique."],
    ["Qu'est-ce que le pisco ?", ["Une eau-de-vie de raisin du Pérou et du Chili", "Un alcool de canne à sucre du Brésil", "Un vin fortifié à l'eau-de-vie, comme le porto", "Une liqueur d'agrume andine"], 0,
     "Son origine fait l'objet d'un contentieux durable entre les deux pays."],
    ["Combien de variétés de pommes de terre le Pérou cultive-t-il ?", ["Plusieurs milliers", "Une centaine tout au plus", "Une vingtaine", "Une cinquantaine"], 0,
     "Le Centre international de la pomme de terre, à Lima, en conserve la diversité."],
    ["Qu'est-ce que la feijoada brésilienne ?", ["Un ragoût de haricots noirs et de viandes de porc", "Un plat de riz noir aux fruits de mer", "Une soupe épaisse de haricots noirs relevée au lard fumé", "Un ragoût de bœuf aux légumes et au manioc râpé"], 0,
     "Elle est traditionnellement servie le samedi dans une grande partie du Brésil."],
    ["Qu'est-ce que le barbecue du sud des États-Unis ?", ["Une cuisson lente à basse température et à la fumée", "Une grillade rapide sur des braises particulièrement vives", "Une cuisson au four, à couvert et à feu vif", "Une cuisson à la broche au-dessus d'un feu ouvert"], 0,
     "Chaque État revendique sa sauce et sa coupe de viande de référence."],
    ["Quelle boisson a été inventée à Atlanta en 1886 ?", ["Le Coca-Cola", "Le Pepsi", "Le Dr Pepper", "Le root beer"], 0,
     "Conçue par un pharmacien comme un tonique, elle contenait alors de la cocaïne."],
    ["Quel apport les Amériques ont-elles fait à la cuisine mondiale ?", ["Tomate, pomme de terre, maïs, cacao, piment et vanille", "Le café, le thé, la canne à sucre, la banane et le poivre noir", "Le riz, le blé et l'orge", "Les agrumes, l'olivier, la vigne et le figuier commun"], 0,
     "Sans cet échange, ni la cuisine italienne ni la cuisine indienne actuelles n'existeraient.", 3],
  ]),

  notion("ga3-cuisine-afrique", S, "Les cuisines d'Afrique subsaharienne",
    "Céréales, sauces, tubercules.",
    "Le mil, le sorgho et l'igname sont des bases alimentaires anciennes en Afrique.",
    2, [
    ["Qu'est-ce que le thiéboudienne sénégalais ?", ["Un plat de riz au poisson et aux légumes", "Un ragoût de poisson à la sauce tomate", "Une soupe de riz au poisson séché", "Un riz aux légumes cuit à l'étouffée sans poisson"], 0,
     "Considéré comme le plat national du Sénégal, il est inscrit au patrimoine immatériel."],
    ["Qu'est-ce que le fufu en Afrique de l'Ouest ?", ["Une pâte obtenue en pilant des tubercules cuits", "Une bouillie de maïs sucrée du matin", "Un pain de manioc cuit au four dans des feuilles", "Une semoule de mil roulée à la main"], 0,
     "Igname, manioc ou banane plantain servent selon les régions."],
    ["Qu'est-ce que l'attiéké ivoirien ?", ["Une semoule de manioc fermenté", "Une semoule de mil cuite à la vapeur", "Un couscous de maïs jaune", "Une farine de manioc grillée"], 0,
     "Sa préparation est inscrite au patrimoine immatériel de l'humanité depuis 2024."],
    ["Qu'est-ce que l'injera éthiopienne ?", ["Une galette spongieuse de teff fermenté", "Un pain plat de blé cuit contre la paroi du four", "Une crêpe de sorgho sans levain", "Une galette de maïs cuite sur la braise"], 0,
     "Elle sert à la fois d'assiette et d'ustensile pour saisir les préparations."],
    ["Qu'est-ce que le teff ?", ["Une céréale à très petits grains cultivée en Éthiopie", "Un mil africain cultivé depuis la plus haute Antiquité au Sahel", "Une variété de sorgho rouge propre aux hauts plateaux", "Un blé ancien à petits grains, proche de l'épeautre"], 0,
     "Ses grains comptent parmi les plus petits de toutes les céréales cultivées."],
    ["Qu'est-ce que le berbéré éthiopien ?", ["Un mélange d'épices dominé par le piment", "Un piment séché puis pilé au mortier", "Une sauce épicée servie avec l'injera", "Un condiment fermenté"], 0,
     "Il donne sa couleur et sa force aux ragoûts appelés wat."],
    ["Qu'est-ce que le jollof rice ?", ["Un riz cuit dans une base tomatée, populaire en Afrique de l'Ouest", "Un riz au poisson fumé et à l'huile de palme", "Un riz épicé strictement sénégalais, totalement inconnu ailleurs", "Un plat de riz propre au seul Nigeria, que ses voisins ignorent totalement"], 0,
     "La rivalité entre les versions nigériane et ghanéenne est un sujet de plaisanterie constant."],
    ["Qu'est-ce que le maafe ?", ["Un ragoût à la pâte d'arachide", "Un plat de mil à la viande", "Une sauce tomate longuement mijotée", "Un ragoût de légumes sans arachide"], 0,
     "Répandu de la Gambie au Mali, il se décline avec différentes viandes."],
    ["Quel rôle l'arachide joue-t-elle en Afrique de l'Ouest ?", ["Une culture alimentaire et d'exportation majeure", "Un condiment marginal réservé aux sauces", "Une culture récente, introduite au XXe siècle", "Un produit importé"], 0,
     "Elle a longtemps structuré l'économie sénégalaise sous le nom d'économie arachidière."],
    ["Qu'est-ce que la sauce gombo ?", ["Une sauce liée par la texture mucilagineuse du gombo", "Une sauce aux légumes verts et aux feuilles de manioc pilées", "Un ragoût épicé à l'huile rouge", "Une sauce épaissie à l'huile de palme rouge du Bénin"], 0,
     "Cette texture filante, recherchée en Afrique, a donné son nom au gumbo de Louisiane.", 3],
  ]),

  notion("ga3-vins-monde", S, "Les vins du monde",
    "Nouveaux pays producteurs, cépages, styles.",
    "L'Italie, la France et l'Espagne restent les trois premiers producteurs mondiaux.",
    2, [
    ["Quel pays produit le plus de vin au monde selon les années ?", ["L'Italie ou la France selon les millésimes", "L'Espagne, loin devant tous les autres pays", "Les États-Unis", "L'Argentine"], 0,
     "L'Espagne dispose en revanche du plus grand vignoble en surface."],
    ["Quel cépage a fait la réputation de l'Argentine ?", ["Le malbec", "Le cabernet-sauvignon", "Le tempranillo", "Le carménère"], 0,
     "Originaire du sud-ouest de la France, il s'est épanoui dans la région de Mendoza."],
    ["Quel cépage a été redécouvert au Chili en 1994 ?", ["Le carménère", "Le merlot", "La syrah", "Le malbec argentin"], 0,
     "Il avait été confondu avec le merlot pendant plus d'un siècle."],
    ["Quelle région californienne est la plus réputée pour ses vins ?", ["La Napa Valley", "La Sonoma Valley", "Le comté de Monterey", "La Central Valley"], 0,
     "Le jugement de Paris de 1976 a révélé au monde le niveau des vins californiens."],
    ["Qu'est-ce que le jugement de Paris de 1976 ?", ["Une dégustation à l'aveugle remportée par des vins californiens", "Un concours viticole organisé à Paris par des producteurs français", "Un salon professionnel du vin tenu à Paris", "Un classement officiel des crus établi à Paris"], 0,
     "Organisé par Steven Spurrier, il a durablement modifié la perception des vins du Nouveau Monde."],
    ["Quel cépage blanc est emblématique de la Nouvelle-Zélande ?", ["Le sauvignon blanc", "Le chardonnay de Marlborough", "Le riesling", "Le pinot gris d'Alsace"], 0,
     "La région de Marlborough en a imposé un style aromatique reconnaissable."],
    ["Quel cépage rouge est emblématique de l'Afrique du Sud ?", ["Le pinotage", "La syrah", "Le cabernet-sauvignon", "Le merlot"], 0,
     "Croisement de pinot noir et de cinsault créé en 1925."],
    ["Quel pays est le premier producteur de vin d'Asie ?", ["La Chine", "Le Japon", "L'Inde", "La Corée du Sud"], 0,
     "Son vignoble figure parmi les plus étendus au monde en surface plantée."],
    ["Qu'est-ce qu'un vin de garage ?", ["Un vin produit en très petite quantité, souvent à prix élevé", "Un vin artisanal élaboré dans une petite cave de village bordelaise", "Un vin de propriété mis en bouteille au château", "Un vin qui n'est ni filtré ni collé, vendu en vrac au domaine"], 0,
     "Le phénomène est apparu à Saint-Émilion dans les années 1990."],
    ["Qu'est-ce que le réchauffement climatique change pour la viticulture ?", ["Il avance les vendanges et déplace les zones favorables vers le nord", "Il n'a aucun effet mesurable sur la vigne", "Il réduit uniformément les rendements dans tous les vignobles", "Il améliore tous les millésimes, sans exception, partout dans le monde"], 0,
     "L'Angleterre développe désormais un vignoble d'effervescents de qualité.", 3],
  ]),

  notion("ga3-bieres-monde", S, "La bière dans le monde",
    "Styles, traditions, brasseries.",
    "La bière est la boisson alcoolisée la plus consommée au monde.",
    2, [
    ["Quel pays consomme le plus de bière par habitant ?", ["La République tchèque", "L'Allemagne, et de loin", "L'Irlande", "L'Autriche"], 0,
     "Elle occupe cette place depuis plus de trente ans."],
    ["Qu'est-ce qu'une pilsner ?", ["Une bière blonde de fermentation basse née à Plzeň en 1842", "Une bière allemande brassée depuis le Moyen Âge", "Une bière blonde belge d'abbaye, refermentée en bouteille sur lie", "Une bière de garde du nord de la France, brassée l'hiver"], 0,
     "Elle représente aujourd'hui l'écrasante majorité de la bière produite dans le monde."],
    ["Qu'est-ce que la fermentation haute ?", ["Une fermentation à température plus élevée donnant des bières plus aromatiques", "Une fermentation prolongée", "Une fermentation conduite directement dans un fût de chêne neuf et non toasté", "Une fermentation spontanée déclenchée sans le moindre ajout de levure de brasserie"], 0,
     "Elle caractérise les ales, par opposition aux lagers de fermentation basse."],
    ["Qu'est-ce qu'une bière de fermentation spontanée ?", ["Une bière fermentée par les levures présentes dans l'air", "Une bière non filtrée, trouble et riche en levures", "Une bière refermentée en bouteille après ajout de sucre", "Une bière brassée sans aucune levure, à partir du seul malt"], 0,
     "Le lambic belge en est l'exemple le plus connu."],
    ["Qu'est-ce que la gueuze ?", ["Un assemblage de lambics d'âges différents", "Une bière fruitée à la cerise ou à la framboise", "Une bière d'abbaye belge particulièrement forte", "Une bière de blé trouble"], 0,
     "L'assemblage provoque une refermentation en bouteille et une forte effervescence."],
    ["Qu'est-ce qu'une bière trappiste ?", ["Une bière brassée dans un monastère trappiste sous contrôle des moines", "Une bière d'abbaye brassée sous licence par un industriel", "Une bière belge forte titrant plus de huit degrés", "Une bière monastique ancienne dont la recette s'est perdue au XIXe siècle"], 0,
     "Une poignée de brasseries seulement peuvent porter le logo Authentic Trappist Product."],
    ["Qu'est-ce que la loi de pureté allemande de 1516 ?", ["Une règle limitant les ingrédients de la bière à l'eau, l'orge et le houblon", "Une norme de qualité moderne adoptée par les brasseurs bavarois", "Une loi fiscale taxant la bière selon son degré d'alcool", "Une charte que les brasseurs allemands se sont librement donnée au XVIe siècle"], 0,
     "La levure n'y figure pas : son rôle était encore inconnu."],
    ["Qu'est-ce qu'une IPA ?", ["Une bière fortement houblonnée d'origine britannique", "Une bière blonde très légère et faiblement alcoolisée", "Une bière ambrée aux notes de caramel", "Une bière américaine apparue dans les années 1980 en Californie"], 0,
     "Le style a été relancé par les brasseries artisanales américaines dans les années 1980."],
    ["Qu'est-ce que la bière artisanale ?", ["Une production indépendante en petite quantité, aux styles variés", "Une bière non industrielle brassée selon des recettes anciennes et secrètes", "Une bière vendue uniquement dans sa région de production", "Une bière non pasteurisée, livrée fraîche directement au consommateur"], 0,
     "Le mouvement craft a fait passer les États-Unis de moins de cent brasseries à plusieurs milliers."],
    ["Quel rôle le houblon joue-t-il dans la bière ?", ["Il apporte amertume, arômes et conservation", "Il fait fermenter la bière en libérant ses sucres", "Il apporte les sucres nécessaires à la fermentation", "Il colore la bière en brun"], 0,
     "Son usage systématique ne s'est imposé qu'à partir du Moyen Âge tardif.", 3],
  ]),

  notion("ga3-spiritueux", S, "Les spiritueux",
    "Distillation, familles, appellations.",
    "Un spiritueux est obtenu par distillation d'un liquide déjà fermenté.",
    2, [
    ["Sur quel principe physique la distillation repose-t-elle ?", ["Une séparation par évaporation puis condensation", "Une fermentation prolongée du moût en cuve", "Une filtration de l'alcool sur charbon actif", "Une concentration de l'alcool par le froid intense"], 0,
     "L'alcool s'évapore avant l'eau, ce qui permet de le concentrer."],
    ["De quoi le whisky est-il distillé ?", ["De céréales", "De raisin", "De canne à sucre", "De pommes de terre"], 0,
     "Orge, maïs, seigle ou blé selon les traditions."],
    ["Qu'est-ce qu'un single malt ?", ["Un whisky d'une seule distillerie, à base d'orge maltée uniquement", "Un whisky provenant d'un seul et unique fût de chêne américain neuf", "Un whisky qui n'a subi aucun assemblage", "Un whisky distillé au cours d'une seule et même année, comme un millésime"], 0,
     "Single désigne la distillerie unique, non le fût unique."],
    ["De quoi le cognac est-il distillé ?", ["De vin blanc", "De marc de raisin", "De cidre", "De céréales"], 0,
     "Le cépage ugni blanc, acide et peu alcoolique, y domine largement."],
    ["De quoi le calvados est-il distillé ?", ["De cidre", "De pommes fraîches", "De poiré uniquement", "De marc de pommes"], 0,
     "Certaines appellations autorisent l'ajout de poiré."],
    ["De quoi le rhum agricole est-il distillé ?", ["De jus de canne frais", "De mélasse de sucrerie", "De sucre blanc raffiné", "De sirop de canne cuit"], 0,
     "Le rhum traditionnel de mélasse domine la production mondiale."],
    ["De quoi la tequila est-elle distillée ?", ["De l'agave bleu", "De cactus", "De maïs", "De canne à sucre"], 0,
     "Le mezcal, plus large, peut employer d'autres variétés d'agave."],
    ["Qu'est-ce que l'absinthe ?", ["Un spiritueux aux plantes dont la grande absinthe", "Une simple liqueur anisée additionnée de sucre", "Un alcool de plantes médicinales préparé en pharmacie", "Un apéritif à base de vin aromatisé"], 0,
     "Interdite en France en 1915, elle a été autorisée à nouveau en 2011."],
    ["Qu'est-ce que le vieillissement en fût ?", ["Un échange entre l'alcool et le bois modifiant couleur et arômes", "Un simple stockage à l'abri de la lumière", "Une oxydation contrôlée de l'alcool au contact permanent de l'air", "Une filtration lente de l'alcool à travers les douves du fût de chêne"], 0,
     "La part des anges désigne le volume perdu par évaporation chaque année."],
    ["Pourquoi certains spiritueux portent-ils une appellation protégée ?", ["Pour lier un produit à une origine et à un mode de production", "Pour en garantir une qualité gustative rigoureusement constante", "Pour en fixer le prix de vente minimal", "Pour limiter la production annuelle autorisée à chaque distillerie"], 0,
     "Cognac, armagnac, scotch whisky et tequila bénéficient de telles protections.", 3],
  ]),

  notion("ga3-cafe-the", S, "Café et thé",
    "Origines, cultures, préparations.",
    "Le café et le thé sont les deux boissons chaudes les plus consommées au monde.",
    2, [
    ["D'où le café est-il originaire ?", ["De l'actuelle Éthiopie", "Du Yémen", "Du Brésil, par les Portugais", "De Colombie, en Amérique du Sud"], 0,
     "Le Yémen en a assuré la première diffusion commerciale, via le port de Moka."],
    ["Quelles sont les deux principales espèces de café cultivées ?", ["L'arabica et le robusta", "L'arabica et le liberica", "Le robusta et l'excelsa", "L'arabica et l'excelsa"], 0,
     "L'arabica représente un peu plus de la moitié de la production mondiale, environ 56 à 57 %, une part qui recule face au robusta."],
    ["Quel pays produit le plus de café ?", ["Le Brésil", "Le Viêt Nam", "La Colombie", "L'Éthiopie"], 0,
     "Le Viêt Nam est deuxième, essentiellement en robusta."],
    ["Qu'est-ce que la torréfaction ?", ["La cuisson des grains verts qui développe les arômes", "Le séchage des grains verts au soleil sur des claies", "Le broyage du café en poudre fine", "La fermentation des cerises de café juste avant le séchage"], 0,
     "Le café vert n'a presque aucun des arômes du café que nous connaissons."],
    ["Qu'est-ce qu'un espresso ?", ["Un café extrait sous forte pression en peu de temps", "Un café serré, simplement moins allongé d'eau chaude", "Un café italien traditionnel préparé à la cafetière de ménage", "Un café filtre particulièrement concentré"], 0,
     "La machine à pression a été mise au point en Italie au début du XXe siècle."],
    ["D'où le thé est-il originaire ?", ["Du sud-ouest de la Chine", "D'Inde", "Du Japon, dès l'Antiquité", "De Ceylan"], 0,
     "Toutes les variétés proviennent d'une même espèce, Camellia sinensis."],
    ["Qu'est-ce qui distingue le thé vert du thé noir ?", ["Le degré d'oxydation des feuilles", "L'espèce de plante", "La région de culture", "Le mode de séchage seul"], 0,
     "Le thé noir est complètement oxydé, le vert ne l'est pas."],
    ["Qu'est-ce que le thé oolong ?", ["Un thé partiellement oxydé", "Un thé fumé au bois de pin résineux", "Un thé longuement fermenté", "Un thé blanc à peine séché"], 0,
     "Son degré d'oxydation peut varier de dix à quatre-vingts pour cent."],
    ["Qu'est-ce que le pu-erh ?", ["Un thé chinois fermenté et vieilli", "Un thé noir fumé de la province du Fujian", "Un thé vert compressé en briques", "Un thé blanc de récolte ancienne"], 0,
     "Contrairement aux autres thés, il peut gagner en valeur avec les années."],
    ["Autour de quelle préparation la cérémonie du thé japonaise est-elle organisée ?", ["Un rituel codifié de préparation du matcha", "Une dégustation formelle de plusieurs grands crus de thé", "Une réception traditionnelle donnée au printemps", "Un service de thé cérémoniel en porcelaine"], 0,
     "Sen no Rikyū en a fixé les principes esthétiques au XVIe siècle.", 3],
  ]),

  notion("ga3-fromages-monde", S, "Fromages du monde",
    "Familles, affinage, appellations.",
    "La France, l'Italie et la Suisse comptent parmi les grandes traditions fromagères.",
    2, [
    ["Qu'est-ce que la coagulation du lait ?", ["La transformation du lait en caillé", "Un caillage naturel dû au seul temps", "Une fermentation lactique du lait entier", "Un égouttage du caillé"], 0,
     "Elle peut être obtenue par acidification ou par la présure."],
    ["Quelle substance fait coaguler le lait dans la plupart des fromages ?", ["La présure, une enzyme d'origine animale", "Un ferment lactique ajouté au lait tiède", "Un acide alimentaire versé dans le lait chaud", "Une culture bactérienne sélectionnée en laboratoire"], 0,
     "Des présures microbiennes ou végétales permettent des fromages sans produit animal."],
    ["Qu'est-ce qu'un fromage à pâte pressée cuite ?", ["Un fromage dont le caillé est chauffé puis pressé", "Un fromage que l'on cuit au four avant de le mouler", "Un fromage à croûte lavée puis pressée", "Un fromage à pâte dure jamais chauffée"], 0,
     "Comté, gruyère et beaufort en font partie, avec de longs affinages."],
    ["Qu'est-ce qu'un fromage à pâte persillée ?", ["Un fromage veiné de moisissures bleues", "Un fromage parsemé d'herbes hachées", "Un fromage à croûte fleurie et duveteuse", "Un fromage affiné en cave humide"], 0,
     "Le Penicillium roqueforti se développe grâce à des perforations qui apportent l'air."],
    ["Où le roquefort est-il affiné ?", ["Dans les caves naturelles de Roquefort-sur-Soulzon", "Dans des caves de montagne du Cantal", "Dans des celliers aveyronnais tenus par les affineurs", "Dans des grottes creusées sous le Larzac"], 0,
     "Les fleurines, failles naturelles, y assurent une ventilation constante."],
    ["De quel lait le roquefort est-il fait ?", ["De lait de brebis", "De lait de vache", "De lait de chèvre", "D'un mélange de laits"], 0,
     "C'est l'une des plus anciennes appellations protégées de France, reconnue dès 1925."],
    ["Qu'est-ce que le parmigiano reggiano ?", ["Un fromage italien à pâte pressée cuite, affiné longuement", "Un fromage à pâte dure d'invention récente, né au XXe siècle", "Un fromage de brebis des Apennins", "Un fromage que l'on affine six mois au maximum, jamais davantage"], 0,
     "Son affinage minimal est de douze mois, souvent bien davantage."],
    ["Qu'est-ce que la mozzarella di bufala ?", ["Un fromage à pâte filée au lait de bufflonne", "Une mozzarella faite au lait de vache", "Un fromage frais italien vendu en saumure", "Un fromage à pâte molle et à croûte fleurie du Sud"], 0,
     "La pâte est étirée dans de l'eau chaude, d'où le terme de pâte filée."],
    ["Qu'est-ce qu'un fromage à croûte lavée ?", ["Un fromage régulièrement frotté à la saumure durant l'affinage", "Un fromage simplement nettoyé juste avant la vente", "Un fromage à croûte naturelle que l'on ne touche jamais en cave", "Un fromage lavé exclusivement à l'alcool, à l'exclusion de l'eau salée"], 0,
     "Munster, époisses et maroilles doivent à ce traitement leur odeur puissante."],
    ["Combien de fromages français bénéficient d'une AOP ?", ["Une cinquantaine", "Une dizaine", "Plus de deux cents", "Une vingtaine tout au plus"], 0,
     "Le nombre total de fromages français produits est en revanche bien supérieur.", 3],
  ]),

  notion("ga3-pains-monde", S, "Les pains du monde",
    "Levains, cuissons, traditions.",
    "Le pain existe sous des formes très différentes sur tous les continents.",
    2, [
    ["Qu'est-ce qu'un levain naturel ?", ["Une culture de levures et bactéries entretenue par le boulanger", "Une levure de boulanger sélectionnée en laboratoire industriel", "Un ferment industriel vendu en sachet déshydraté", "Une pâte fermentée de la veille, ajoutée au tout début du pétrissage"], 0,
     "Les bactéries lactiques y apportent l'acidité caractéristique."],
    ["Quel rôle le gluten joue-t-il dans une pâte à pain ?", ["Un réseau de protéines donnant son élasticité à la pâte", "Un sucre du blé que les levures consomment en fermentant", "Un amidon particulier au grain de blé", "Une levure naturellement présente dans la farine de blé complet"], 0,
     "Il retient les gaz de fermentation, ce qui permet à la pâte de lever."],
    ["Qu'est-ce que la baguette de tradition française ?", ["Une baguette dont la composition et le procédé sont réglementés", "Une baguette artisanale façonnée à la main en boutique", "Une baguette au levain naturel exclusivement", "Une baguette de qualité supérieure vendue plus cher que les autres"], 0,
     "Un décret de 1993 interdit notamment tout additif et toute surgélation."],
    ["Qu'est-ce que le pain au levain de seigle ?", ["Un pain dense à mie serrée, typique d'Europe du Nord", "Un pain complet fait à la farine intégrale de blé", "Un pain de campagne à la farine bise", "Un pain noir que l'on ne trouve qu'en Allemagne et nulle part ailleurs"], 0,
     "Le seigle contient peu de gluten, ce qui explique la densité de la mie."],
    ["Qu'est-ce que le naan indien ?", ["Un pain plat cuit contre la paroi d'un four tandoor", "Une galette de blé sans levain cuite sur une plaque brûlante", "Un pain frit dans un bain d'huile bouillante", "Un pain cuit à la vapeur dans un panier de bambou"], 0,
     "Le chapati, lui, est cuit sans levain sur une plaque."],
    ["Qu'est-ce que le pita ?", ["Un pain plat qui gonfle à la cuisson et forme une poche", "Une galette de blé toujours plate, sèche et très compacte", "Un pain sans levain, plat et sec", "Un pain propre à la seule Grèce, inconnu du reste du Levant"], 0,
     "La vapeur produite à haute température sépare les deux faces."],
    ["Qu'est-ce que la tortilla mexicaine ?", ["Une galette de maïs nixtamalisé ou de blé", "Une omelette espagnole aux pommes de terre", "Une galette faite uniquement de farine de blé", "Un pain plat frit à l'huile"], 0,
     "La tortilla espagnole désigne au contraire une omelette aux pommes de terre."],
    ["Qu'est-ce que le mantou chinois ?", ["Un pain cuit à la vapeur", "Un pain frit à la poêle", "Une galette de blé cuite sans levure", "Un petit pain fourré à la viande"], 0,
     "La cuisson à la vapeur donne une croûte absente et une mie très blanche."],
    ["Pourquoi la cuisson à la vapeur du four est-elle importante ?", ["Elle retarde la formation de la croûte et permet le développement du pain", "Elle humidifie la mie et la rend plus moelleuse", "Elle donne à elle seule sa couleur dorée à la croûte", "Elle accélère nettement la cuisson en transmettant mieux la chaleur au pain"], 0,
     "Sans vapeur, la croûte se fige trop tôt et le pain ne se développe pas."],
    ["Qu'est-ce que la réaction de Maillard dans la cuisson du pain ?", ["Une réaction entre sucres et acides aminés produisant croûte et arômes", "Une caramélisation des seuls sucres naturellement présents dans la farine", "Une oxydation de la farine au contact de l'air chaud du four", "Une évaporation contrôlée de l'eau contenue dans la pâte"], 0,
     "Elle est responsable de la couleur et d'une grande partie du goût du pain.", 3],
  ]),

  notion("ga3-desserts-monde", S, "Desserts et pâtisseries du monde",
    "Traditions sucrées.",
    "Le sucre a longtemps été un produit de luxe avant de devenir un ingrédient courant.",
    2, [
    ["Qu'est-ce que le tiramisu ?", ["Un entremets italien à base de mascarpone et de biscuits imbibés de café", "Un gâteau au café monté à la crème au beurre", "Une crème au mascarpone servie seule, en coupe", "Un dessert vénitien fort ancien, dont on trouve mention dès la Renaissance"], 0,
     "Sa création est relativement récente, généralement située dans les années 1960 ou 1970."],
    ["Qu'est-ce que le pastel de nata ?", ["Une tartelette portugaise à la crème", "Un flan espagnol au caramel", "Une pâtisserie brésilienne à la noix de coco", "Un gâteau garni de crème pâtissière"], 0,
     "Née dans un monastère de Lisbonne, elle est cuite à très haute température."],
    ["Qu'est-ce que la Sachertorte ?", ["Un gâteau au chocolat viennois avec une couche d'abricot", "Un gâteau autrichien généreusement fourré de crème fouettée", "Une tarte au chocolat noir sur pâte sablée", "Un gâteau allemand aux cerises et à la crème"], 0,
     "Un procès de sept ans a opposé l'hôtel Sacher à la pâtisserie Demel sur son appellation."],
    ["Qu'est-ce que le mochi japonais ?", ["Une pâte de riz gluant pilé", "Un gâteau de riz cuit", "Une confiserie de haricot rouge", "Une pâtisserie à la farine de riz"], 0,
     "Sa préparation collective au maillet, le mochitsuki, est une tradition de nouvel an."],
    ["Qu'est-ce que le baklava ?", ["Une pâtisserie de pâte filo, fruits secs et sirop", "Un gâteau au miel et aux épices", "Une pâtisserie feuilletée aux amandes, sans aucun sirop", "Un dessert propre à la seule Turquie, et nulle part ailleurs"], 0,
     "Il est revendiqué par plusieurs traditions de l'ancien Empire ottoman."],
    ["Qu'est-ce que le gulab jamun indien ?", ["Des boulettes frites imbibées de sirop parfumé", "Un dessert au lait parfumé à la rose", "Une confiserie aux amandes et au sucre glace", "Un flan à la cardamome et au safran"], 0,
     "Le sirop est souvent parfumé à l'eau de rose ou à la cardamome."],
    ["Qu'est-ce que le dulce de leche ?", ["Une confiture de lait sud-américaine", "Un caramel au beurre salé", "Une crème préparée avec du lait concentré sucré", "Un flan argentin nappé de caramel"], 0,
     "Il s'obtient par cuisson lente du lait sucré, qui brunit par réaction de Maillard."],
    ["Qu'est-ce que la pavlova ?", ["Un dessert à base de meringue, crème et fruits", "Un gâteau russe à la crème aigre", "Une meringue française longuement séchée au four", "Un entremets australien à la crème et au chocolat blanc"], 0,
     "L'Australie et la Nouvelle-Zélande s'en disputent l'invention."],
    ["Qu'est-ce que le kouign-amann ?", ["Un gâteau breton feuilleté au beurre et au sucre", "Un far breton aux pruneaux", "Une brioche bretonne au beurre demi-sel", "Un gâteau moelleux au beurre salé, sans feuilletage"], 0,
     "Le nom signifie littéralement gâteau au beurre en breton."],
    ["Quel ingrédient a bouleversé la pâtisserie européenne au XIXe siècle ?", ["Le sucre de betterave, qui l'a rendu accessible", "Le chocolat, devenu bon marché", "La vanille, cultivée à La Réunion et à Madagascar", "La levure chimique, qui a remplacé le levain partout"], 0,
     "Le blocus continental a poussé la France à développer cette production.", 3],
  ]),

  notion("ga3-alimentation-sante", S, "Nutriments et repères nutritionnels",
    "Nutriments, régimes, repères.",
    "Les besoins nutritionnels varient selon l'âge, l'activité et l'état de santé.",
    2, [
    ["Que sont les macronutriments ?", ["Les glucides, les lipides et les protéines", "Les vitamines et les minéraux, en très petites quantités", "Les fibres alimentaires contenues dans les végétaux", "Les seuls acides gras essentiels"], 0,
     "Ils fournissent l'énergie, contrairement aux micronutriments."],
    ["Comment définit-on un acide aminé essentiel ?", ["Un acide aminé que l'organisme ne peut pas synthétiser", "Un acide aminé indispensable à la seule croissance de l'enfant", "Un acide aminé que seules les protéines animales apportent", "Un acide aminé rare dans l'alimentation"], 0,
     "Il en existe neuf chez l'adulte, à apporter par l'alimentation."],
    ["Qu'est-ce qu'un acide gras oméga-3 ?", ["Un acide gras insaturé essentiel", "Une graisse saturée d'origine animale", "Un acide gras trans issu de l'hydrogénation", "Un lipide de réserve"], 0,
     "Poissons gras, noix et huile de colza en sont de bonnes sources."],
    ["Qu'est-ce que l'indice glycémique ?", ["Une mesure de la vitesse d'élévation de la glycémie après un aliment", "La teneur totale en sucre d'un aliment, rapportée à son poids net", "La charge calorique apportée par les glucides d'un aliment", "Le taux de sucre présent dans le sang à jeun, tel que le mesure le laboratoire"], 0,
     "La charge glycémique tient en outre compte de la quantité consommée."],
    ["Qu'est-ce qu'une fibre alimentaire ?", ["Un glucide non digéré par l'intestin grêle", "Une protéine végétale que le corps assimile mal", "Un sucre lent des féculents", "Un composant totalement indigeste des végétaux"], 0,
     "Elles nourrissent le microbiote intestinal et régulent le transit."],
    ["Qu'est-ce que le microbiote intestinal ?", ["L'ensemble des micro-organismes du tube digestif", "La flore bactérienne du seul estomac", "Les seules bactéries pathogènes présentes dans l'intestin", "Les enzymes digestives sécrétées par le pancréas"], 0,
     "Il compte des dizaines de milliers de milliards de micro-organismes."],
    ["Qu'est-ce que le régime méditerranéen ?", ["Un mode alimentaire riche en végétaux, huile d'olive et poisson", "Un régime amaigrissant mis au point par des médecins", "L'ensemble des cuisines pratiquées dans tout le sud de l'Europe", "Un régime excluant totalement la viande et tous les produits laitiers"], 0,
     "Il est inscrit au patrimoine immatériel et associé à de meilleurs indicateurs de santé."],
    ["Qu'est-ce qu'un aliment ultra-transformé ?", ["Un produit issu de procédés industriels avec de nombreux additifs", "Un plat préparé vendu en barquette au rayon frais", "Tout aliment fabriqué en usine, quel qu'il soit et quelle que soit sa recette", "Un produit raffiné dont on a retiré toute l'enveloppe du grain"], 0,
     "La classification NOVA les distingue des aliments simplement transformés."],
    ["Sur quel critère la classification NOVA range-t-elle les aliments ?", ["Un classement des aliments selon leur degré de transformation", "Un étiquetage nutritionnel apposé sur la face avant", "Une norme sanitaire fixant les limites admissibles de contaminants", "Un classement des aliments établi d'après leur seul apport en calories"], 0,
     "Elle a été développée par des chercheurs brésiliens et est largement reprise."],
    ["À quoi sert le Nutri-Score ?", ["Un étiquetage nutritionnel simplifié à cinq classes", "Un label de qualité attribué par les industriels", "Une norme sanitaire européenne", "Un indicateur du degré de transformation industrielle"], 0,
     "Il évalue la qualité nutritionnelle, non le degré de transformation.", 3],
  ]),

  // Notion cible de la fusion interne ga-agriculture-alimentation -> ga3-agriculture-alimentation
  // (voir cours/fusions.ts, FUSIONS_INTERNES) : ne pas supprimer sans mettre à jour ce fichier.
  notion("ga3-agriculture-alimentation", S, "Agricultures et filières alimentaires",
    "Agricultures, labels, filières.",
    "Le contenu de l'assiette dépend de choix agricoles faits en amont.",
    2, [
    ["Qu'est-ce que l'agriculture biologique ?", ["Un mode de production excluant les produits chimiques de synthèse", "Une agriculture qui n'emploie strictement aucun engrais", "Une agriculture strictement locale, vendue sur place", "Une agriculture traditionnelle telle qu'on la pratiquait avant 1950"], 0,
     "Elle est encadrée en Europe par un règlement et un contrôle par organisme certificateur."],
    ["Qu'est-ce qu'une AOP ?", ["Une appellation liant un produit à un terroir et à un savoir-faire", "Un label de qualité supérieure décerné par l'État après contrôle", "Une indication d'origine simplement apposée par le fabricant sur l'emballage", "Une certification biologique européenne"], 0,
     "Toutes les étapes de production doivent avoir lieu dans l'aire délimitée."],
    ["Qu'est-ce qu'une IGP ?", ["Une indication géographique où une seule étape doit avoir lieu dans l'aire", "Une appellation d'origine exigeant que toutes les étapes se fassent sur place", "Un label régional attribué par le conseil régional", "Une certification de qualité portant sur le seul produit fini"], 0,
     "Elle est donc moins exigeante que l'AOP sur l'ancrage territorial."],
    ["Qu'est-ce que le Label rouge ?", ["Un signe français attestant une qualité supérieure", "Un label biologique reconnu dans toute l'Union", "Une appellation d'origine liée à un terroir précis", "Une certification sanitaire délivrée par les services vétérinaires"], 0,
     "Il repose sur un cahier des charges comparé à un produit courant de référence."],
    ["Que garantit le commerce équitable aux producteurs ?", ["Un prix minimum, indépendant des cours mondiaux", "Un commerce direct entre le producteur et le client", "Un label écologique portant sur les seules méthodes de culture", "Un circuit court comportant au plus un intermédiaire"], 0,
     "Il vise principalement des filières d'exportation comme le café ou le cacao."],
    ["Qu'est-ce qu'un circuit court ?", ["Une vente avec au plus un intermédiaire", "Une vente directe uniquement", "Une vente locale", "Une vente à la ferme"], 0,
     "Circuit court et proximité géographique ne sont pas synonymes."],
    ["Qu'est-ce qu'une AMAP ?", ["Une association liant consommateurs et producteur par un engagement", "Un marché où les producteurs viennent vendre directement leurs récoltes", "Une coopérative agricole détenue par ses membres exploitants", "Un magasin tenu en commun par plusieurs producteurs de la région"], 0,
     "Les adhérents s'engagent à l'avance, ce qui partage le risque climatique."],
    ["Qu'est-ce que l'agroécologie ?", ["Une approche mobilisant les processus écologiques dans la production", "Une agriculture biologique certifiée par un organisme agréé", "Une agriculture raisonnée limitant les intrants chimiques sans les exclure", "Une agriculture de conservation qui renonce totalement au labour des sols"], 0,
     "Elle concerne autant les pratiques agronomiques que l'organisation des filières."],
    ["Qu'est-ce que la politique agricole commune ?", ["La politique agricole de l'Union européenne", "Une politique nationale propre à la France", "Un accord commercial agricole entre États", "Un programme de subventions ponctuel voté chaque année"], 0,
     "Lancée en 1962, elle représente une part importante du budget européen."],
    ["Quel est l'enjeu majeur de l'alimentation mondiale ?", ["Nourrir tous les humains sans épuiser les ressources", "Augmenter les rendements à tout prix", "Réduire les prix payés par les consommateurs des pays riches", "Diversifier les cultures dans chaque exploitation"], 0,
     "La production actuelle suffirait en théorie ; la répartition et le gaspillage font l'écart.", 3],
  ]),

  notion("ga3-terroirs-france-3", S, "Terroirs français",
    "Spécialités régionales.",
    "Chaque région française revendique des produits et des plats identitaires.",
    2, [
    ["De quelle région la choucroute est-elle emblématique ?", ["L'Alsace", "La Lorraine", "La Franche-Comté", "La Champagne"], 0,
     "Le chou fermenté est une technique de conservation d'origine bien plus ancienne."],
    ["De quelle région la bouillabaisse est-elle emblématique ?", ["Marseille et la Provence", "Le Languedoc", "La Corse", "Le Pays basque"], 0,
     "Née comme une soupe de pêcheurs, elle est devenue un plat coûteux."],
    ["De quelle région le cassoulet est-il emblématique ?", ["Le Languedoc, autour de Castelnaudary et Carcassonne", "La Gascogne", "Le Périgord", "Le Roussillon"], 0,
     "Castelnaudary, Carcassonne et Toulouse en revendiquent chacune une version."],
    ["De quelle région la galette de sarrasin est-elle emblématique ?", ["La Bretagne", "La Normandie", "Le Maine", "Le Poitou"], 0,
     "Le sarrasin, appelé blé noir, n'est pas une céréale mais une polygonacée."],
    ["De quelle région la tarte flambée est-elle emblématique ?", ["L'Alsace", "La Lorraine", "La Moselle", "Les Ardennes"], 0,
     "Appelée flammekueche, elle était cuite dans le four à pain avant la fournée."],
    ["De quelle région l'aligot est-il emblématique ?", ["L'Aubrac, en Aveyron et Lozère", "L'Auvergne du nord", "Le Cantal", "Le Limousin"], 0,
     "La tome fraîche donne au mélange sa texture filante caractéristique."],
    ["De quelle région la piperade est-elle emblématique ?", ["Le Pays basque", "Le Béarn", "Le Roussillon", "La Gascogne"], 0,
     "Le piment d'Espelette y tient une place centrale."],
    ["De quelle région le far est-il emblématique ?", ["La Bretagne", "La Normandie", "La Vendée", "Le Poitou"], 0,
     "Le far breton aux pruneaux est le plus répandu, mais il en existe des versions salées."],
    ["De quelle région la fondue savoyarde est-elle emblématique ?", ["La Savoie", "La Suisse romande", "Le Jura", "Le Dauphiné"], 0,
     "Beaufort, comté et emmental de Savoie en constituent souvent la base."],
    ["Qu'est-ce qui explique la diversité des cuisines régionales françaises ?", ["La variété des climats, des sols et des histoires locales", "La taille du pays", "L'ancienneté de la gastronomie", "Le morcellement administratif"], 0,
     "L'unification tardive du territoire a permis à ces traditions de se maintenir.", 3],
  ]),
];
