/**
 * Gastronomie & Art de vivre, troisième lot — vingt-deux notions ; les cours sont dans cours/gastronomie.ts.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Gastronomie & Art de vivre";

export const CG_GASTRONOMIE_3: SeedSkill[] = [
  notion("ga3-cuisines-asie", S, "Les cuisines d'Asie",
    "Chine, Japon, Corée, Asie du Sud-Est.",
    "La cuisine chinoise réunit des traditions régionales très différentes entre elles.",
    2, [
    ["Quelle cuisine chinoise est réputée pour son usage du piment et du poivre du Sichuan ?", ["La cuisine sichuanaise", "La cuisine cantonaise du delta de la rivière des Perles", "La cuisine du Shandong", "La cuisine du Jiangsu, plus douce"], 0,
     "Le poivre du Sichuan produit une sensation d'engourdissement caractéristique."],
    ["Quelle cuisine chinoise a le plus influencé les restaurants chinois d'Occident ?", ["La cuisine cantonaise", "La cuisine du Hunan, très pimentée", "La cuisine pékinoise", "La cuisine du Fujian"], 0,
     "L'émigration depuis le Guangdong au XIXe siècle en explique la diffusion."],
    ["Qu'est-ce que le dim sum ?", ["Un ensemble de petites préparations servies à la vapeur ou frites", "Un plat cantonais unique, servi en fin de banquet", "Une soupe de nouilles au bouillon de porc, servie au petit-déjeuner", "Un dessert chinois sucré à la pâte de haricot rouge"], 0,
     "Traditionnellement servi le matin avec du thé, d'où le nom de yum cha."],
    ["Qu'est-ce que le dashi dans la cuisine japonaise ?", ["Un bouillon de base à l'algue kombu et au poisson séché", "Une sauce soja claire utilisée pour tous les assaisonnements", "Un vinaigre de riz doux employé pour assaisonner le riz à sushi", "Une pâte de soja fermenté délayée dans l'eau chaude"], 0,
     "Il est à l'origine de la découverte de l'umami par Kikunae Ikeda en 1908."],
    ["Qu'est-ce que le miso ?", ["Une pâte fermentée de soja", "Une sauce de poisson fermenté", "Un bouillon clair", "Un condiment au piment et à l'ail"], 0,
     "Sa fermentation peut durer de quelques mois à plusieurs années."],
    ["Qu'est-ce que le kimchi coréen ?", ["Un légume fermenté, le plus souvent du chou pimenté", "Une soupe épicée au piment rouge et au tofu de soja", "Un condiment au piment fermenté longuement en jarre de terre", "Un plat de riz sauté aux légumes"], 0,
     "La préparation collective d'automne, le kimjang, est inscrite au patrimoine immatériel."],
    ["Qu'est-ce que le nuoc-mâm ?", ["Une sauce de poisson fermenté vietnamienne", "Une sauce sucrée à base de caramel", "Un bouillon de poisson servi avec les nouilles", "Une pâte de crevettes séchées et pilées"], 0,
     "Le garum romain reposait sur un principe de fermentation comparable."],
    ["Qu'est-ce que le pho vietnamien ?", ["Une soupe de nouilles de riz au bouillon longuement mijoté", "Un plat de riz sauté au bœuf", "Une soupe de légumes verts au bouillon de volaille", "Un ragoût de bœuf mijoté à la citronnelle et à l'anis étoilé"], 0,
     "Née au début du XXe siècle dans le nord du Vietnam."],
    ["Qu'est-ce que le curry thaï vert ?", ["Une préparation à base de pâte d'épices fraîches et de lait de coco", "Un curry indien adapté au goût thaïlandais", "Une sauce au piment vert et au citron vert, sans aucune matière grasse", "Un bouillon épicé aux herbes, servi très clair et brûlant"], 0,
     "Sa couleur vient des piments verts frais broyés dans la pâte."],
    ["Quel principe structure de nombreuses cuisines d'Asie du Sud-Est ?", ["L'équilibre entre acide, sucré, salé et pimenté", "La domination du piment sur toutes les autres saveurs", "L'usage exclusif du riz comme féculent", "La cuisson à la vapeur de presque tous les plats"], 0,
     "Ce jeu d'équilibres se règle en fin de cuisson, au goût.", 3],
  ]),

  notion("ga3-cuisines-moyen-orient", S, "Les cuisines du Levant et du Maghreb",
    "Mezzés, épices, pains.",
    "Le partage des mezzés structure le repas dans une grande partie du Levant.",
    2, [
    ["Qu'est-ce que le houmous ?", ["Une purée de pois chiches au sésame", "Une purée d'aubergine grillée au sésame", "Une pâte de sésame pure", "Une sauce au yaourt et à la menthe"], 0,
     "Le tahini, pâte de sésame, en est l'autre ingrédient essentiel."],
    ["Qu'est-ce que le taboulé libanais ?", ["Une salade dominée par le persil, avec peu de boulgour", "Une salade de semoule fine où le persil est un simple décor", "Une salade de tomates, de concombres et d'oignons doux", "Un plat de boulgour chaud aux épices"], 0,
     "La version française, majoritairement composée de semoule, en est très éloignée."],
    ["Qu'est-ce que le za'atar ?", ["Un mélange d'herbes séchées, de sumac et de sésame", "Une épice unique récoltée au Levant", "Un piment doux moulu, d'une couleur très sombre", "Une herbe fraîche que l'on hache juste avant de servir"], 0,
     "Il désigne aussi la plante, une variété d'origan sauvage."],
    ["Qu'est-ce que le sumac ?", ["Une épice acidulée obtenue à partir de baies séchées", "Une graine aromatique", "Une écorce", "Une racine séchée que l'on râpe sur les plats"], 0,
     "Il apporte l'acidité là où d'autres cuisines emploient le citron."],
    ["Qu'est-ce que le couscous ?", ["Une semoule de blé dur roulée, cuite à la vapeur", "Un plat de semoule servi en bouillie sucrée", "Un ragoût de légumes qui accompagne la semoule", "Une préparation de blé concassé puis simplement bouilli"], 0,
     "Sa préparation est inscrite au patrimoine immatériel par quatre pays du Maghreb."],
    ["Qu'est-ce que le tajine ?", ["Un plat mijoté et le récipient conique qui lui donne son nom", "Un ragoût d'agneau aux pruneaux servi à la cuiller", "Un plat de légumes cuits séparément puis dressés en dôme sur le plat", "Une cocotte en terre vernissée, sans rapport avec le plat qu'on y cuit"], 0,
     "Le couvercle conique fait retomber la vapeur condensée sur les aliments."],
    ["Qu'est-ce que le ras el-hanout ?", ["Un mélange d'épices dont la composition varie selon le marchand", "Une épice unique venue du sud marocain", "Un piment marocain séché au soleil puis longuement moulu au mortier", "Un mélange strictement fixé à sept épices par une tradition ancienne"], 0,
     "Le nom signifie littéralement la tête de la boutique, soit le meilleur du commerçant."],
    ["Qu'est-ce que la harissa ?", ["Une pâte de piment tunisienne", "Une sauce tomate épicée servie froide", "Un mélange d'épices sèches", "Une huile pimentée d'olive"], 0,
     "Elle est inscrite au patrimoine immatériel de l'humanité depuis 2022."],
    ["Qu'est-ce que le citron confit ?", ["Un citron conservé au sel, utilisé dans les tajines", "Un citron entier séché au soleil pendant des semaines", "Un citron conservé au vinaigre blanc", "Un citron confit au sucre, comme une friandise"], 0,
     "Seule l'écorce est généralement employée, la pulpe étant écartée."],
    ["Qu'est-ce que la pâtisserie orientale au miel ?", ["Un ensemble de préparations à base de pâte fine, de fruits secs et de sirop", "Une pâtisserie unique, rigoureusement identique d'un pays à l'autre du Levant", "Un dessert au miel servi exclusivement lors des fêtes religieuses", "Une confiserie aux amandes et au miel, toujours sans pâte ni farine"], 0,
     "Baklava, cornes de gazelle et makrout relèvent de traditions distinctes.", 3],
  ]),

  notion("ga3-cuisines-ameriques", S, "Les cuisines des Amériques",
    "Mexique, Pérou, Brésil, États-Unis.",
    "La cuisine mexicaine traditionnelle est inscrite au patrimoine immatériel de l'humanité.",
    2, [
    ["Qu'est-ce que la nixtamalisation ?", ["Un traitement du maïs à l'eau alcaline", "Un broyage du maïs à la meule de pierre", "Une fermentation du maïs avant la mouture", "Un séchage traditionnel des épis au soleil"], 0,
     "Elle libère la vitamine B3 et a permis aux civilisations mésoaméricaines d'éviter la pellagre."],
    ["Qu'est-ce que le mole mexicain ?", ["Une sauce complexe mêlant piments, épices et parfois chocolat", "Un plat de viande de dinde longuement mijoté", "Une sauce au chocolat noir, sucrée, que l'on sert sur les desserts", "Un ragoût de viande de porc fortement épicé au piment rouge"], 0,
     "Le mole poblano peut compter plus de vingt ingrédients."],
    ["Quel piment mexicain est un jalapeño fumé ?", ["Le chipotle", "L'ancho", "Le guajillo", "Le habanero"], 0,
     "L'ancho est un poblano séché, le guajillo un mirasol séché."],
    ["Qu'est-ce que le ceviche péruvien ?", ["Du poisson cru mariné dans du jus d'agrume", "Un poisson réellement cuit par le jus de citron", "Une salade de poisson cuit et de légumes", "Un tartare de poisson relevé au piment"], 0,
     "L'acidité dénature les protéines sans cuisson thermique."],
    ["Qu'est-ce que le pisco ?", ["Une eau-de-vie de raisin du Pérou et du Chili", "Un alcool de canne à sucre du Brésil", "Un vin fortifié à l'eau-de-vie, comme le porto", "Une liqueur d'agrume andine"], 0,
     "Son origine fait l'objet d'un contentieux durable entre les deux pays."],
    ["Combien de variétés de pommes de terre le Pérou cultive-t-il ?", ["Plusieurs milliers", "Une centaine tout au plus", "Une vingtaine", "Une cinquantaine"], 0,
     "Le Centre international de la pomme de terre, à Lima, en conserve la diversité."],
    ["Qu'est-ce que la feijoada brésilienne ?", ["Un ragoût de haricots noirs et de viandes de porc", "Un plat de riz noir aux fruits de mer", "Une soupe épaisse de haricots noirs relevée au lard fumé", "Un ragoût de bœuf aux légumes et au manioc râpé"], 0,
     "Elle est traditionnellement servie le samedi dans une grande partie du Brésil."],
    ["Qu'est-ce que le barbecue du sud des États-Unis ?", ["Une cuisson lente à basse température et à la fumée", "Une grillade rapide sur des braises particulièrement vives", "Une cuisson au four, à couvert et à feu vif", "Une cuisson à la broche au-dessus d'un feu ouvert"], 0,
     "Chaque État revendique sa sauce et sa coupe de viande de référence."],
    ["Quelle boisson a été inventée à Atlanta en 1886 ?", ["Le Coca-Cola", "Le Pepsi", "Le Dr Pepper", "Le root beer"], 0,
     "Conçue par un pharmacien comme un tonique, elle contenait alors de la cocaïne."],
    ["Quel apport les Amériques ont-elles fait à la cuisine mondiale ?", ["Tomate, pomme de terre, maïs, cacao, piment et vanille", "Le café, le thé, la canne à sucre, la banane et le poivre noir", "Le riz, le blé et l'orge", "Les agrumes, l'olivier, la vigne et le figuier commun"], 0,
     "Sans cet échange, ni la cuisine italienne ni la cuisine indienne actuelles n'existeraient.", 3],
  ]),

  notion("ga3-cuisine-afrique", S, "Les cuisines d'Afrique subsaharienne",
    "Céréales, sauces, tubercules.",
    "Le mil, le sorgho et l'igname sont des bases alimentaires anciennes en Afrique.",
    2, [
    ["Qu'est-ce que le thiéboudienne sénégalais ?", ["Un plat de riz au poisson et aux légumes", "Un ragoût de poisson à la sauce tomate", "Une soupe de riz au poisson séché", "Un riz aux légumes cuit à l'étouffée sans poisson"], 0,
     "Considéré comme le plat national du Sénégal, il est inscrit au patrimoine immatériel."],
    ["Qu'est-ce que le fufu en Afrique de l'Ouest ?", ["Une pâte obtenue en pilant des tubercules cuits", "Une bouillie de maïs sucrée du matin", "Un pain de manioc cuit au four dans des feuilles", "Une semoule de mil roulée à la main"], 0,
     "Igname, manioc ou banane plantain servent selon les régions."],
    ["Qu'est-ce que l'attiéké ivoirien ?", ["Une semoule de manioc fermenté", "Une semoule de mil cuite à la vapeur", "Un couscous de maïs jaune", "Une farine de manioc grillée"], 0,
     "Sa préparation est inscrite au patrimoine immatériel de l'humanité depuis 2024."],
    ["Qu'est-ce que l'injera éthiopienne ?", ["Une galette spongieuse de teff fermenté", "Un pain plat de blé cuit contre la paroi du four", "Une crêpe de sorgho sans levain", "Une galette de maïs cuite sur la braise"], 0,
     "Elle sert à la fois d'assiette et d'ustensile pour saisir les préparations."],
    ["Qu'est-ce que le teff ?", ["Une céréale à très petits grains cultivée en Éthiopie", "Un mil africain cultivé depuis la plus haute Antiquité au Sahel", "Une variété de sorgho rouge propre aux hauts plateaux", "Un blé ancien à petits grains, proche de l'épeautre"], 0,
     "Ses grains comptent parmi les plus petits de toutes les céréales cultivées."],
    ["Qu'est-ce que le berbéré éthiopien ?", ["Un mélange d'épices dominé par le piment", "Un piment séché puis pilé au mortier", "Une sauce épicée servie avec l'injera", "Un condiment fermenté"], 0,
     "Il donne sa couleur et sa force aux ragoûts appelés wat."],
    ["Qu'est-ce que le jollof rice ?", ["Un riz cuit dans une base tomatée, populaire en Afrique de l'Ouest", "Un riz au poisson fumé et à l'huile de palme", "Un riz épicé strictement sénégalais, totalement inconnu ailleurs", "Un plat de riz propre au seul Nigeria, que ses voisins ignorent totalement"], 0,
     "La rivalité entre les versions nigériane et ghanéenne est un sujet de plaisanterie constant."],
    ["Qu'est-ce que le maafe ?", ["Un ragoût à la pâte d'arachide", "Un plat de mil à la viande", "Une sauce tomate longuement mijotée", "Un ragoût de légumes sans arachide"], 0,
     "Répandu de la Gambie au Mali, il se décline avec différentes viandes."],
    ["Quel rôle l'arachide joue-t-elle en Afrique de l'Ouest ?", ["Une culture alimentaire et d'exportation majeure", "Un condiment marginal réservé aux sauces", "Une culture récente, introduite au XXe siècle", "Un produit importé"], 0,
     "Elle a longtemps structuré l'économie sénégalaise sous le nom d'économie arachidière."],
    ["Qu'est-ce que la sauce gombo ?", ["Une sauce liée par la texture mucilagineuse du gombo", "Une sauce aux légumes verts et aux feuilles de manioc pilées", "Un ragoût épicé à l'huile rouge", "Une sauce épaissie à l'huile de palme rouge du Bénin"], 0,
     "Cette texture filante, recherchée en Afrique, a donné son nom au gumbo de Louisiane.", 3],
  ]),

  notion("ga3-vins-monde", S, "Les vins du monde",
    "Nouveaux pays producteurs, cépages, styles.",
    "L'Italie, la France et l'Espagne restent les trois premiers producteurs mondiaux.",
    2, [
    ["Quel pays produit le plus de vin au monde selon les années ?", ["L'Italie ou la France selon les millésimes", "L'Espagne, loin devant tous les autres pays", "Les États-Unis", "L'Argentine"], 0,
     "L'Espagne dispose en revanche du plus grand vignoble en surface."],
    ["Quel cépage a fait la réputation de l'Argentine ?", ["Le malbec", "Le cabernet-sauvignon", "Le tempranillo", "Le carménère"], 0,
     "Originaire du sud-ouest de la France, il s'est épanoui dans la région de Mendoza."],
    ["Quel cépage a été redécouvert au Chili en 1994 ?", ["Le carménère", "Le merlot", "La syrah", "Le malbec argentin"], 0,
     "Il avait été confondu avec le merlot pendant plus d'un siècle."],
    ["Quelle région californienne est la plus réputée pour ses vins ?", ["La Napa Valley", "La Sonoma Valley", "Le comté de Monterey", "La Central Valley"], 0,
     "Le jugement de Paris de 1976 a révélé au monde le niveau des vins californiens."],
    ["Qu'est-ce que le jugement de Paris de 1976 ?", ["Une dégustation à l'aveugle remportée par des vins californiens", "Un concours viticole organisé à Paris par des producteurs français", "Un salon professionnel du vin tenu à Paris", "Un classement officiel des crus établi à Paris"], 0,
     "Organisé par Steven Spurrier, il a durablement modifié la perception des vins du Nouveau Monde."],
    ["Quel cépage blanc est emblématique de la Nouvelle-Zélande ?", ["Le sauvignon blanc", "Le chardonnay de Marlborough", "Le riesling", "Le pinot gris d'Alsace"], 0,
     "La région de Marlborough en a imposé un style aromatique reconnaissable."],
    ["Quel cépage rouge est emblématique de l'Afrique du Sud ?", ["Le pinotage", "La syrah", "Le cabernet-sauvignon", "Le merlot"], 0,
     "Croisement de pinot noir et de cinsault créé en 1925."],
    ["Quel pays est le premier producteur de vin d'Asie ?", ["La Chine", "Le Japon", "L'Inde", "La Corée du Sud"], 0,
     "Son vignoble figure parmi les plus étendus au monde en surface plantée."],
    ["Qu'est-ce qu'un vin de garage ?", ["Un vin produit en très petite quantité, souvent à prix élevé", "Un vin artisanal élaboré dans une petite cave de village bordelaise", "Un vin de propriété mis en bouteille au château", "Un vin qui n'est ni filtré ni collé, vendu en vrac au domaine"], 0,
     "Le phénomène est apparu à Saint-Émilion dans les années 1990."],
    ["Qu'est-ce que le réchauffement climatique change pour la viticulture ?", ["Il avance les vendanges et déplace les zones favorables vers le nord", "Il n'a aucun effet mesurable sur la vigne", "Il réduit uniformément les rendements dans tous les vignobles", "Il améliore tous les millésimes, sans exception, partout dans le monde"], 0,
     "L'Angleterre développe désormais un vignoble d'effervescents de qualité.", 3],
  ]),

  notion("ga3-bieres-monde", S, "La bière dans le monde",
    "Styles, traditions, brasseries.",
    "La bière est la boisson alcoolisée la plus consommée au monde.",
    2, [
    ["Quel pays consomme le plus de bière par habitant ?", ["La République tchèque", "L'Allemagne, et de loin", "L'Irlande", "L'Autriche"], 0,
     "Elle occupe cette place depuis plus de trente ans."],
    ["Qu'est-ce qu'une pilsner ?", ["Une bière blonde de fermentation basse née à Plzeň en 1842", "Une bière allemande brassée depuis le Moyen Âge", "Une bière blonde belge d'abbaye, refermentée en bouteille sur lie", "Une bière de garde du nord de la France, brassée l'hiver"], 0,
     "Elle représente aujourd'hui l'écrasante majorité de la bière produite dans le monde."],
    ["Qu'est-ce que la fermentation haute ?", ["Une fermentation à température plus élevée donnant des bières plus aromatiques", "Une fermentation prolongée", "Une fermentation conduite directement dans un fût de chêne neuf et non toasté", "Une fermentation spontanée déclenchée sans le moindre ajout de levure de brasserie"], 0,
     "Elle caractérise les ales, par opposition aux lagers de fermentation basse."],
    ["Qu'est-ce qu'une bière de fermentation spontanée ?", ["Une bière fermentée par les levures présentes dans l'air", "Une bière non filtrée, trouble et riche en levures", "Une bière refermentée en bouteille après ajout de sucre", "Une bière brassée sans aucune levure, à partir du seul malt"], 0,
     "Le lambic belge en est l'exemple le plus connu."],
    ["Qu'est-ce que la gueuze ?", ["Un assemblage de lambics d'âges différents", "Une bière fruitée à la cerise ou à la framboise", "Une bière d'abbaye belge particulièrement forte", "Une bière de blé trouble"], 0,
     "L'assemblage provoque une refermentation en bouteille et une forte effervescence."],
    ["Qu'est-ce qu'une bière trappiste ?", ["Une bière brassée dans un monastère trappiste sous contrôle des moines", "Une bière d'abbaye brassée sous licence par un industriel", "Une bière belge forte titrant plus de huit degrés", "Une bière monastique ancienne dont la recette s'est perdue au XIXe siècle"], 0,
     "Une poignée de brasseries seulement peuvent porter le logo Authentic Trappist Product."],
    ["Qu'est-ce que la loi de pureté allemande de 1516 ?", ["Une règle limitant les ingrédients de la bière à l'eau, l'orge et le houblon", "Une norme de qualité moderne adoptée par les brasseurs bavarois", "Une loi fiscale taxant la bière selon son degré d'alcool", "Une charte que les brasseurs allemands se sont librement donnée au XVIe siècle"], 0,
     "La levure n'y figure pas : son rôle était encore inconnu."],
    ["Qu'est-ce qu'une IPA ?", ["Une bière fortement houblonnée d'origine britannique", "Une bière blonde très légère et faiblement alcoolisée", "Une bière ambrée aux notes de caramel", "Une bière américaine apparue dans les années 1980 en Californie"], 0,
     "Le style a été relancé par les brasseries artisanales américaines dans les années 1980."],
    ["Qu'est-ce que la bière artisanale ?", ["Une production indépendante en petite quantité, aux styles variés", "Une bière non industrielle brassée selon des recettes anciennes et secrètes", "Une bière vendue uniquement dans sa région de production", "Une bière non pasteurisée, livrée fraîche directement au consommateur"], 0,
     "Le mouvement craft a fait passer les États-Unis de moins de cent brasseries à plusieurs milliers."],
    ["Quel rôle le houblon joue-t-il dans la bière ?", ["Il apporte amertume, arômes et conservation", "Il fait fermenter la bière en libérant ses sucres", "Il apporte les sucres nécessaires à la fermentation", "Il colore la bière en brun"], 0,
     "Son usage systématique ne s'est imposé qu'à partir du Moyen Âge tardif.", 3],
  ]),

  notion("ga3-spiritueux", S, "Les spiritueux",
    "Distillation, familles, appellations.",
    "Un spiritueux est obtenu par distillation d'un liquide déjà fermenté.",
    2, [
    ["Sur quel principe physique la distillation repose-t-elle ?", ["Une séparation par évaporation puis condensation", "Une fermentation prolongée du moût en cuve", "Une filtration de l'alcool sur charbon actif", "Une concentration de l'alcool par le froid intense"], 0,
     "L'alcool s'évapore avant l'eau, ce qui permet de le concentrer."],
    ["De quoi le whisky est-il distillé ?", ["De céréales", "De raisin", "De canne à sucre", "De pommes de terre"], 0,
     "Orge, maïs, seigle ou blé selon les traditions."],
    ["Qu'est-ce qu'un single malt ?", ["Un whisky d'une seule distillerie, à base d'orge maltée uniquement", "Un whisky provenant d'un seul et unique fût de chêne américain neuf", "Un whisky qui n'a subi aucun assemblage", "Un whisky distillé au cours d'une seule et même année, comme un millésime"], 0,
     "Single désigne la distillerie unique, non le fût unique."],
    ["De quoi le cognac est-il distillé ?", ["De vin blanc", "De marc de raisin", "De cidre", "De céréales"], 0,
     "Le cépage ugni blanc, acide et peu alcoolique, y domine largement."],
    ["De quoi le calvados est-il distillé ?", ["De cidre", "De pommes fraîches", "De poiré uniquement", "De marc de pommes"], 0,
     "Certaines appellations autorisent l'ajout de poiré."],
    ["De quoi le rhum agricole est-il distillé ?", ["De jus de canne frais", "De mélasse de sucrerie", "De sucre blanc raffiné", "De sirop de canne cuit"], 0,
     "Le rhum traditionnel de mélasse domine la production mondiale."],
    ["De quoi la tequila est-elle distillée ?", ["De l'agave bleu", "De cactus", "De maïs", "De canne à sucre"], 0,
     "Le mezcal, plus large, peut employer d'autres variétés d'agave."],
    ["Qu'est-ce que l'absinthe ?", ["Un spiritueux aux plantes dont la grande absinthe", "Une simple liqueur anisée additionnée de sucre", "Un alcool de plantes médicinales préparé en pharmacie", "Un apéritif à base de vin aromatisé"], 0,
     "Interdite en France en 1915, elle a été autorisée à nouveau en 2011."],
    ["Qu'est-ce que le vieillissement en fût ?", ["Un échange entre l'alcool et le bois modifiant couleur et arômes", "Un simple stockage à l'abri de la lumière", "Une oxydation contrôlée de l'alcool au contact permanent de l'air", "Une filtration lente de l'alcool à travers les douves du fût de chêne"], 0,
     "La part des anges désigne le volume perdu par évaporation chaque année."],
    ["Pourquoi certains spiritueux portent-ils une appellation protégée ?", ["Pour lier un produit à une origine et à un mode de production", "Pour en garantir une qualité gustative rigoureusement constante", "Pour en fixer le prix de vente minimal", "Pour limiter la production annuelle autorisée à chaque distillerie"], 0,
     "Cognac, armagnac, scotch whisky et tequila bénéficient de telles protections.", 3],
  ]),

  notion("ga3-cafe-the", S, "Café et thé",
    "Origines, cultures, préparations.",
    "Le café et le thé sont les deux boissons chaudes les plus consommées au monde.",
    2, [
    ["D'où le café est-il originaire ?", ["De l'actuelle Éthiopie", "Du Yémen", "Du Brésil, par les Portugais", "De Colombie, en Amérique du Sud"], 0,
     "Le Yémen en a assuré la première diffusion commerciale, via le port de Moka."],
    ["Quelles sont les deux principales espèces de café cultivées ?", ["L'arabica et le robusta", "L'arabica et le liberica", "Le robusta et l'excelsa", "L'arabica et l'excelsa"], 0,
     "L'arabica représente un peu plus de la moitié de la production mondiale, environ 56 à 57 %, une part qui recule face au robusta."],
    ["Quel pays produit le plus de café ?", ["Le Brésil", "Le Viêt Nam", "La Colombie", "L'Éthiopie"], 0,
     "Le Viêt Nam est deuxième, essentiellement en robusta."],
    ["Qu'est-ce que la torréfaction ?", ["La cuisson des grains verts qui développe les arômes", "Le séchage des grains verts au soleil sur des claies", "Le broyage du café en poudre fine", "La fermentation des cerises de café juste avant le séchage"], 0,
     "Le café vert n'a presque aucun des arômes du café que nous connaissons."],
    ["Qu'est-ce qu'un espresso ?", ["Un café extrait sous forte pression en peu de temps", "Un café serré, simplement moins allongé d'eau chaude", "Un café italien traditionnel préparé à la cafetière de ménage", "Un café filtre particulièrement concentré"], 0,
     "La machine à pression a été mise au point en Italie au début du XXe siècle."],
    ["D'où le thé est-il originaire ?", ["Du sud-ouest de la Chine", "D'Inde", "Du Japon, dès l'Antiquité", "De Ceylan"], 0,
     "Toutes les variétés proviennent d'une même espèce, Camellia sinensis."],
    ["Qu'est-ce qui distingue le thé vert du thé noir ?", ["Le degré d'oxydation des feuilles", "L'espèce de plante", "La région de culture", "Le mode de séchage seul"], 0,
     "Le thé noir est complètement oxydé, le vert ne l'est pas."],
    ["Qu'est-ce que le thé oolong ?", ["Un thé partiellement oxydé", "Un thé fumé au bois de pin résineux", "Un thé longuement fermenté", "Un thé blanc à peine séché"], 0,
     "Son degré d'oxydation peut varier de dix à quatre-vingts pour cent."],
    ["Qu'est-ce que le pu-erh ?", ["Un thé chinois fermenté et vieilli", "Un thé noir fumé de la province du Fujian", "Un thé vert compressé en briques", "Un thé blanc de récolte ancienne"], 0,
     "Contrairement aux autres thés, il peut gagner en valeur avec les années."],
    ["Autour de quelle préparation la cérémonie du thé japonaise est-elle organisée ?", ["Un rituel codifié de préparation du matcha", "Une dégustation formelle de plusieurs grands crus de thé", "Une réception traditionnelle donnée au printemps", "Un service de thé cérémoniel en porcelaine"], 0,
     "Sen no Rikyū en a fixé les principes esthétiques au XVIe siècle.", 3],
  ]),

  notion("ga3-fromages-monde", S, "Fromages du monde",
    "Familles, affinage, appellations.",
    "La France, l'Italie et la Suisse comptent parmi les grandes traditions fromagères.",
    2, [
    ["Qu'est-ce que la coagulation du lait ?", ["La transformation du lait en caillé", "Un caillage naturel dû au seul temps", "Une fermentation lactique du lait entier", "Un égouttage du caillé"], 0,
     "Elle peut être obtenue par acidification ou par la présure."],
    ["Quelle substance fait coaguler le lait dans la plupart des fromages ?", ["La présure, une enzyme d'origine animale", "Un ferment lactique ajouté au lait tiède", "Un acide alimentaire versé dans le lait chaud", "Une culture bactérienne sélectionnée en laboratoire"], 0,
     "Des présures microbiennes ou végétales permettent des fromages sans produit animal."],
    ["Qu'est-ce qu'un fromage à pâte pressée cuite ?", ["Un fromage dont le caillé est chauffé puis pressé", "Un fromage que l'on cuit au four avant de le mouler", "Un fromage à croûte lavée puis pressée", "Un fromage à pâte dure jamais chauffée"], 0,
     "Comté, gruyère et beaufort en font partie, avec de longs affinages."],
    ["Qu'est-ce qu'un fromage à pâte persillée ?", ["Un fromage veiné de moisissures bleues", "Un fromage parsemé d'herbes hachées", "Un fromage à croûte fleurie et duveteuse", "Un fromage affiné en cave humide"], 0,
     "Le Penicillium roqueforti se développe grâce à des perforations qui apportent l'air."],
    ["Où le roquefort est-il affiné ?", ["Dans les caves naturelles de Roquefort-sur-Soulzon", "Dans des caves de montagne du Cantal", "Dans des celliers aveyronnais tenus par les affineurs", "Dans des grottes creusées sous le Larzac"], 0,
     "Les fleurines, failles naturelles, y assurent une ventilation constante."],
    ["De quel lait le roquefort est-il fait ?", ["De lait de brebis", "De lait de vache", "De lait de chèvre", "D'un mélange de laits"], 0,
     "C'est l'une des plus anciennes appellations protégées de France, reconnue dès 1925."],
    ["Qu'est-ce que le parmigiano reggiano ?", ["Un fromage italien à pâte pressée cuite, affiné longuement", "Un fromage à pâte dure d'invention récente, né au XXe siècle", "Un fromage de brebis des Apennins", "Un fromage que l'on affine six mois au maximum, jamais davantage"], 0,
     "Son affinage minimal est de douze mois, souvent bien davantage."],
    ["Qu'est-ce que la mozzarella di bufala ?", ["Un fromage à pâte filée au lait de bufflonne", "Une mozzarella faite au lait de vache", "Un fromage frais italien vendu en saumure", "Un fromage à pâte molle et à croûte fleurie du Sud"], 0,
     "La pâte est étirée dans de l'eau chaude, d'où le terme de pâte filée."],
    ["Qu'est-ce qu'un fromage à croûte lavée ?", ["Un fromage régulièrement frotté à la saumure durant l'affinage", "Un fromage simplement nettoyé juste avant la vente", "Un fromage à croûte naturelle que l'on ne touche jamais en cave", "Un fromage lavé exclusivement à l'alcool, à l'exclusion de l'eau salée"], 0,
     "Munster, époisses et maroilles doivent à ce traitement leur odeur puissante."],
    ["Combien de fromages français bénéficient d'une AOP ?", ["Une cinquantaine", "Une dizaine", "Plus de deux cents", "Une vingtaine tout au plus"], 0,
     "Le nombre total de fromages français produits est en revanche bien supérieur.", 3],
  ]),

  notion("ga3-pains-monde", S, "Les pains du monde",
    "Levains, cuissons, traditions.",
    "Le pain existe sous des formes très différentes sur tous les continents.",
    2, [
    ["Qu'est-ce qu'un levain naturel ?", ["Une culture de levures et bactéries entretenue par le boulanger", "Une levure de boulanger sélectionnée en laboratoire industriel", "Un ferment industriel vendu en sachet déshydraté", "Une pâte fermentée de la veille, ajoutée au tout début du pétrissage"], 0,
     "Les bactéries lactiques y apportent l'acidité caractéristique."],
    ["Quel rôle le gluten joue-t-il dans une pâte à pain ?", ["Un réseau de protéines donnant son élasticité à la pâte", "Un sucre du blé que les levures consomment en fermentant", "Un amidon particulier au grain de blé", "Une levure naturellement présente dans la farine de blé complet"], 0,
     "Il retient les gaz de fermentation, ce qui permet à la pâte de lever."],
    ["Qu'est-ce que la baguette de tradition française ?", ["Une baguette dont la composition et le procédé sont réglementés", "Une baguette artisanale façonnée à la main en boutique", "Une baguette au levain naturel exclusivement", "Une baguette de qualité supérieure vendue plus cher que les autres"], 0,
     "Un décret de 1993 interdit notamment tout additif et toute surgélation."],
    ["Qu'est-ce que le pain au levain de seigle ?", ["Un pain dense à mie serrée, typique d'Europe du Nord", "Un pain complet fait à la farine intégrale de blé", "Un pain de campagne à la farine bise", "Un pain noir que l'on ne trouve qu'en Allemagne et nulle part ailleurs"], 0,
     "Le seigle contient peu de gluten, ce qui explique la densité de la mie."],
    ["Qu'est-ce que le naan indien ?", ["Un pain plat cuit contre la paroi d'un four tandoor", "Une galette de blé sans levain cuite sur une plaque brûlante", "Un pain frit dans un bain d'huile bouillante", "Un pain cuit à la vapeur dans un panier de bambou"], 0,
     "Le chapati, lui, est cuit sans levain sur une plaque."],
    ["Qu'est-ce que le pita ?", ["Un pain plat qui gonfle à la cuisson et forme une poche", "Une galette de blé toujours plate, sèche et très compacte", "Un pain sans levain, plat et sec", "Un pain propre à la seule Grèce, inconnu du reste du Levant"], 0,
     "La vapeur produite à haute température sépare les deux faces."],
    ["Qu'est-ce que la tortilla mexicaine ?", ["Une galette de maïs nixtamalisé ou de blé", "Une omelette espagnole aux pommes de terre", "Une galette faite uniquement de farine de blé", "Un pain plat frit à l'huile"], 0,
     "La tortilla espagnole désigne au contraire une omelette aux pommes de terre."],
    ["Qu'est-ce que le mantou chinois ?", ["Un pain cuit à la vapeur", "Un pain frit à la poêle", "Une galette de blé cuite sans levure", "Un petit pain fourré à la viande"], 0,
     "La cuisson à la vapeur donne une croûte absente et une mie très blanche."],
    ["Pourquoi la cuisson à la vapeur du four est-elle importante ?", ["Elle retarde la formation de la croûte et permet le développement du pain", "Elle humidifie la mie et la rend plus moelleuse", "Elle donne à elle seule sa couleur dorée à la croûte", "Elle accélère nettement la cuisson en transmettant mieux la chaleur au pain"], 0,
     "Sans vapeur, la croûte se fige trop tôt et le pain ne se développe pas."],
    ["Qu'est-ce que la réaction de Maillard dans la cuisson du pain ?", ["Une réaction entre sucres et acides aminés produisant croûte et arômes", "Une caramélisation des seuls sucres naturellement présents dans la farine", "Une oxydation de la farine au contact de l'air chaud du four", "Une évaporation contrôlée de l'eau contenue dans la pâte"], 0,
     "Elle est responsable de la couleur et d'une grande partie du goût du pain.", 3],
  ]),

  notion("ga3-desserts-monde", S, "Desserts et pâtisseries du monde",
    "Traditions sucrées.",
    "Le sucre a longtemps été un produit de luxe avant de devenir un ingrédient courant.",
    2, [
    ["Qu'est-ce que le tiramisu ?", ["Un entremets italien à base de mascarpone et de biscuits imbibés de café", "Un gâteau au café monté à la crème au beurre", "Une crème au mascarpone servie seule, en coupe", "Un dessert vénitien fort ancien, dont on trouve mention dès la Renaissance"], 0,
     "Sa création est relativement récente, généralement située dans les années 1960 ou 1970."],
    ["Qu'est-ce que le pastel de nata ?", ["Une tartelette portugaise à la crème", "Un flan espagnol au caramel", "Une pâtisserie brésilienne à la noix de coco", "Un gâteau garni de crème pâtissière"], 0,
     "Née dans un monastère de Lisbonne, elle est cuite à très haute température."],
    ["Qu'est-ce que la Sachertorte ?", ["Un gâteau au chocolat viennois avec une couche d'abricot", "Un gâteau autrichien généreusement fourré de crème fouettée", "Une tarte au chocolat noir sur pâte sablée", "Un gâteau allemand aux cerises et à la crème"], 0,
     "Un procès de sept ans a opposé l'hôtel Sacher à la pâtisserie Demel sur son appellation."],
    ["Qu'est-ce que le mochi japonais ?", ["Une pâte de riz gluant pilé", "Un gâteau de riz cuit", "Une confiserie de haricot rouge", "Une pâtisserie à la farine de riz"], 0,
     "Sa préparation collective au maillet, le mochitsuki, est une tradition de nouvel an."],
    ["Qu'est-ce que le baklava ?", ["Une pâtisserie de pâte filo, fruits secs et sirop", "Un gâteau au miel et aux épices", "Une pâtisserie feuilletée aux amandes, sans aucun sirop", "Un dessert propre à la seule Turquie, et nulle part ailleurs"], 0,
     "Il est revendiqué par plusieurs traditions de l'ancien Empire ottoman."],
    ["Qu'est-ce que le gulab jamun indien ?", ["Des boulettes frites imbibées de sirop parfumé", "Un dessert au lait parfumé à la rose", "Une confiserie aux amandes et au sucre glace", "Un flan à la cardamome et au safran"], 0,
     "Le sirop est souvent parfumé à l'eau de rose ou à la cardamome."],
    ["Qu'est-ce que le dulce de leche ?", ["Une confiture de lait sud-américaine", "Un caramel au beurre salé", "Une crème préparée avec du lait concentré sucré", "Un flan argentin nappé de caramel"], 0,
     "Il s'obtient par cuisson lente du lait sucré, qui brunit par réaction de Maillard."],
    ["Qu'est-ce que la pavlova ?", ["Un dessert à base de meringue, crème et fruits", "Un gâteau russe à la crème aigre", "Une meringue française longuement séchée au four", "Un entremets australien à la crème et au chocolat blanc"], 0,
     "L'Australie et la Nouvelle-Zélande s'en disputent l'invention."],
    ["Qu'est-ce que le kouign-amann ?", ["Un gâteau breton feuilleté au beurre et au sucre", "Un far breton aux pruneaux", "Une brioche bretonne au beurre demi-sel", "Un gâteau moelleux au beurre salé, sans feuilletage"], 0,
     "Le nom signifie littéralement gâteau au beurre en breton."],
    ["Quel ingrédient a bouleversé la pâtisserie européenne au XIXe siècle ?", ["Le sucre de betterave, qui l'a rendu accessible", "Le chocolat, devenu bon marché", "La vanille, cultivée à La Réunion et à Madagascar", "La levure chimique, qui a remplacé le levain partout"], 0,
     "Le blocus continental a poussé la France à développer cette production.", 3],
  ]),

  notion("ga3-cuisine-technique", S, "Techniques de cuisine",
    "Cuissons, préparations, gestes.",
    "Les modes de cuisson déterminent autant le goût que la texture d'un plat.",
    2, [
    ["En quoi consiste la cuisson à basse température ?", ["Une cuisson longue à température contrôlée et modérée", "Une cuisson douce au four traditionnel, à chaleur tournante", "Une cuisson sous vide uniquement", "Une cuisson au bain-marie, la casserole posée dans l'eau chaude"], 0,
     "Elle limite la contraction des fibres et préserve le moelleux des viandes."],
    ["Comment se déroule une cuisson sous vide ?", ["Une cuisson en sachet hermétique dans un bain d'eau régulé", "Une cuisson menée sans air dans un four hermétique", "La conservation d'un aliment dans un sachet mis sous vide", "Une cuisson à la vapeur sous pression dans une cocotte fermée"], 0,
     "Georges Pralus l'a développée en France dans les années 1970."],
    ["Qu'est-ce que la réduction d'une sauce ?", ["Une évaporation concentrant les saveurs", "Un épaississement obtenu en ajoutant de la farine à la sauce", "Le filtrage de la sauce pour en retirer les impuretés", "Une cuisson menée rapidement sur un feu très vif"], 0,
     "Elle concentre aussi le sel : mieux vaut assaisonner en fin de réduction."],
    ["Qu'est-ce qu'un roux ?", ["Un mélange de farine et de matière grasse cuit ensemble", "Une sauce brune", "Un fond de veau", "Un liant à la crème"], 0,
     "Sa couleur, blanche, blonde ou brune, dépend du temps de cuisson."],
    ["Qu'est-ce qu'une émulsion ?", ["Une dispersion stable de deux liquides non miscibles", "Un mélange devenu parfaitement homogène après agitation", "Une sauce montée au beurre froid juste avant de servir", "Une mousse"], 0,
     "La mayonnaise disperse l'huile dans l'eau du jaune d'œuf, grâce à la lécithine."],
    ["Qu'est-ce que saisir une viande ?", ["La colorer rapidement à feu vif", "L'enfermer dans une croûte de pâte avant de la cuire", "La cuire rapidement jusqu'au cœur, sur un feu très vif", "La faire dorer doucement sur toutes ses faces, à feu moyen"], 0,
     "L'idée qu'elle emprisonne les jus est une croyance démentie par l'expérience."],
    ["Qu'est-ce que le repos d'une viande après cuisson ?", ["Un temps qui permet la redistribution des jus", "Un refroidissement", "Une détente des fibres seule", "Un temps de maturation"], 0,
     "Découpée immédiatement, la viande perd une quantité de jus nettement supérieure."],
    ["En quoi consiste le fait de blanchir un légume ?", ["Le plonger brièvement dans l'eau bouillante puis le refroidir", "Le cuire à blanc", "Le faire tremper", "Le cuire à la vapeur"], 0,
     "L'opération fixe la couleur et arrête l'action des enzymes."],
    ["Qu'est-ce que déglacer ?", ["Dissoudre les sucs de cuisson avec un liquide", "Refroidir une préparation", "Ajouter du liquide en cours de cuisson", "Décoller une préparation collée"], 0,
     "Les sucs caramélisés au fond du récipient contiennent l'essentiel des arômes."],
    ["Qu'est-ce que la gastronomie moléculaire ?", ["L'étude scientifique des transformations culinaires", "Une cuisine d'avant-garde", "Une technique de sphérification", "Une cuisine chimique"], 0,
     "Hervé This et Nicholas Kurti ont fondé la discipline en 1988 ; elle n'est pas un style de cuisine.", 3],
  ]),

  notion("ga3-conservation", S, "Conserver les aliments",
    "Sel, froid, fermentation, appertisation.",
    "La conservation a longtemps déterminé ce qu'il était possible de manger l'hiver.",
    2, [
    ["Qui a inventé l'appertisation ?", ["Nicolas Appert", "Louis Pasteur", "Peter Durand", "Antoine Parmentier"], 0,
     "Confiseur français, il commence ses essais vers 1795 et publie sa méthode en 1810, année où l'État le récompense, sans qu'il en comprenne la cause."],
    ["Qu'est-ce que l'appertisation ?", ["Une conservation par chauffage en récipient hermétique", "Une mise en conserve dans une boîte métallique sertie à chaud", "Une pasteurisation rapide du produit avant sa mise en pot", "Une stérilisation à froid par rayonnement"], 0,
     "Pasteur expliquera plus tard pourquoi le procédé fonctionne."],
    ["Qu'est-ce que la pasteurisation ?", ["Un chauffage modéré détruisant la plupart des micro-organismes", "Une stérilisation complète détruisant absolument tous les germes présents", "Une conservation par le froid seul, sans aucun chauffage préalable", "Un traitement chimique par ajout de conservateurs"], 0,
     "Elle prolonge la conservation sans détruire toutes les formes de vie microbienne."],
    ["Sur quel principe la lyophilisation repose-t-elle ?", ["Une déshydratation par sublimation à basse température", "Un séchage à chaud dans un four à air chaud longuement ventilé", "Une congélation lente en chambre froide", "Une déshydratation sous vide à chaud, dans une enceinte chauffée"], 0,
     "L'eau gelée passe directement à l'état gazeux, ce qui préserve la structure."],
    ["Par quel mécanisme le sel empêche-t-il l'altération des aliments ?", ["Il réduit l'eau disponible pour les micro-organismes", "Il tue directement toutes les bactéries présentes", "Il acidifie fortement le milieu", "Il forme à la surface une barrière protectrice imperméable"], 0,
     "Le sucre en forte concentration agit sur le même principe."],
    ["Qu'est-ce que le fumage ?", ["Une conservation combinant séchage et composés antimicrobiens de la fumée", "Une cuisson lente à la fumée", "Un séchage à chaud au-dessus du foyer", "Une simple aromatisation, sans le moindre effet conservateur sur le produit"], 0,
     "Certains composés de la fumée sont cependant classés comme cancérogènes probables."],
    ["Qu'est-ce que la fermentation lactique ?", ["Une transformation par des bactéries produisant de l'acide lactique", "Une fermentation alcoolique conduite par des levures de bière ou de vin", "Une fermentation acétique donnant du vinaigre", "Une putréfaction contrôlée que l'on interrompt juste à temps par le froid"], 0,
     "L'acidité produite empêche le développement des micro-organismes indésirables."],
    ["Que suppose le respect de la chaîne du froid ?", ["Le maintien continu d'une température basse de la production à la consommation", "Une conservation au congélateur du produit, depuis sa fabrication jusqu'à son achat", "Un transport réfrigéré entre l'usine et le magasin", "Un stockage à une température rigoureusement constante, quelle qu'elle puisse être"], 0,
     "Une seule rupture peut suffire à rendre un produit dangereux."],
    ["Quelle est la portée d'une date limite de consommation ?", ["Une date au-delà de laquelle le produit devient dangereux", "Une date purement indicative portant sur la seule qualité gustative", "Une date de fraîcheur optimale au-delà de laquelle le goût baisse", "Une simple recommandation du fabricant"], 0,
     "La date de durabilité minimale, à consommer de préférence avant, ne présente pas ce risque."],
    ["Quelle part de la production alimentaire mondiale est perdue ou gaspillée ?", ["Environ un tiers", "Environ dix pour cent", "Environ la moitié", "Environ cinq pour cent"], 0,
     "Estimation de la FAO publiée en 2011, depuis remplacée par deux mesures distinctes : environ 13 % de pertes entre la récolte et la vente (FAO), et environ 19 % de gaspillage au stade de la distribution, de la restauration et des ménages (PNUE, 2024).", 3],
  ]),

  notion("ga3-alimentation-sante", S, "Nutriments et repères nutritionnels",
    "Nutriments, régimes, repères.",
    "Les besoins nutritionnels varient selon l'âge, l'activité et l'état de santé.",
    2, [
    ["Que sont les macronutriments ?", ["Les glucides, les lipides et les protéines", "Les vitamines et les minéraux, en très petites quantités", "Les fibres alimentaires contenues dans les végétaux", "Les seuls acides gras essentiels"], 0,
     "Ils fournissent l'énergie, contrairement aux micronutriments."],
    ["Comment définit-on un acide aminé essentiel ?", ["Un acide aminé que l'organisme ne peut pas synthétiser", "Un acide aminé indispensable à la seule croissance de l'enfant", "Un acide aminé que seules les protéines animales apportent", "Un acide aminé rare dans l'alimentation"], 0,
     "Il en existe neuf chez l'adulte, à apporter par l'alimentation."],
    ["Qu'est-ce qu'un acide gras oméga-3 ?", ["Un acide gras insaturé essentiel", "Une graisse saturée d'origine animale", "Un acide gras trans issu de l'hydrogénation", "Un lipide de réserve"], 0,
     "Poissons gras, noix et huile de colza en sont de bonnes sources."],
    ["Qu'est-ce que l'indice glycémique ?", ["Une mesure de la vitesse d'élévation de la glycémie après un aliment", "La teneur totale en sucre d'un aliment, rapportée à son poids net", "La charge calorique apportée par les glucides d'un aliment", "Le taux de sucre présent dans le sang à jeun, tel que le mesure le laboratoire"], 0,
     "La charge glycémique tient en outre compte de la quantité consommée."],
    ["Qu'est-ce qu'une fibre alimentaire ?", ["Un glucide non digéré par l'intestin grêle", "Une protéine végétale que le corps assimile mal", "Un sucre lent des féculents", "Un composant totalement indigeste des végétaux"], 0,
     "Elles nourrissent le microbiote intestinal et régulent le transit."],
    ["Qu'est-ce que le microbiote intestinal ?", ["L'ensemble des micro-organismes du tube digestif", "La flore bactérienne du seul estomac", "Les seules bactéries pathogènes présentes dans l'intestin", "Les enzymes digestives sécrétées par le pancréas"], 0,
     "Il compte des dizaines de milliers de milliards de micro-organismes."],
    ["Qu'est-ce que le régime méditerranéen ?", ["Un mode alimentaire riche en végétaux, huile d'olive et poisson", "Un régime amaigrissant mis au point par des médecins", "L'ensemble des cuisines pratiquées dans tout le sud de l'Europe", "Un régime excluant totalement la viande et tous les produits laitiers"], 0,
     "Il est inscrit au patrimoine immatériel et associé à de meilleurs indicateurs de santé."],
    ["Qu'est-ce qu'un aliment ultra-transformé ?", ["Un produit issu de procédés industriels avec de nombreux additifs", "Un plat préparé vendu en barquette au rayon frais", "Tout aliment fabriqué en usine, quel qu'il soit et quelle que soit sa recette", "Un produit raffiné dont on a retiré toute l'enveloppe du grain"], 0,
     "La classification NOVA les distingue des aliments simplement transformés."],
    ["Sur quel critère la classification NOVA range-t-elle les aliments ?", ["Un classement des aliments selon leur degré de transformation", "Un étiquetage nutritionnel apposé sur la face avant", "Une norme sanitaire fixant les limites admissibles de contaminants", "Un classement des aliments établi d'après leur seul apport en calories"], 0,
     "Elle a été développée par des chercheurs brésiliens et est largement reprise."],
    ["À quoi sert le Nutri-Score ?", ["Un étiquetage nutritionnel simplifié à cinq classes", "Un label de qualité attribué par les industriels", "Une norme sanitaire européenne", "Un indicateur du degré de transformation industrielle"], 0,
     "Il évalue la qualité nutritionnelle, non le degré de transformation.", 3],
  ]),

  notion("ga3-agriculture-alimentation", S, "Agricultures et filières alimentaires",
    "Agricultures, labels, filières.",
    "Le contenu de l'assiette dépend de choix agricoles faits en amont.",
    2, [
    ["Qu'est-ce que l'agriculture biologique ?", ["Un mode de production excluant les produits chimiques de synthèse", "Une agriculture qui n'emploie strictement aucun engrais", "Une agriculture strictement locale, vendue sur place", "Une agriculture traditionnelle telle qu'on la pratiquait avant 1950"], 0,
     "Elle est encadrée en Europe par un règlement et un contrôle par organisme certificateur."],
    ["Qu'est-ce qu'une AOP ?", ["Une appellation liant un produit à un terroir et à un savoir-faire", "Un label de qualité supérieure décerné par l'État après contrôle", "Une indication d'origine simplement apposée par le fabricant sur l'emballage", "Une certification biologique européenne"], 0,
     "Toutes les étapes de production doivent avoir lieu dans l'aire délimitée."],
    ["Qu'est-ce qu'une IGP ?", ["Une indication géographique où une seule étape doit avoir lieu dans l'aire", "Une appellation d'origine exigeant que toutes les étapes se fassent sur place", "Un label régional attribué par le conseil régional", "Une certification de qualité portant sur le seul produit fini"], 0,
     "Elle est donc moins exigeante que l'AOP sur l'ancrage territorial."],
    ["Qu'est-ce que le Label rouge ?", ["Un signe français attestant une qualité supérieure", "Un label biologique reconnu dans toute l'Union", "Une appellation d'origine liée à un terroir précis", "Une certification sanitaire délivrée par les services vétérinaires"], 0,
     "Il repose sur un cahier des charges comparé à un produit courant de référence."],
    ["Que garantit le commerce équitable aux producteurs ?", ["Un prix minimum, indépendant des cours mondiaux", "Un commerce direct entre le producteur et le client", "Un label écologique portant sur les seules méthodes de culture", "Un circuit court comportant au plus un intermédiaire"], 0,
     "Il vise principalement des filières d'exportation comme le café ou le cacao."],
    ["Qu'est-ce qu'un circuit court ?", ["Une vente avec au plus un intermédiaire", "Une vente directe uniquement", "Une vente locale", "Une vente à la ferme"], 0,
     "Circuit court et proximité géographique ne sont pas synonymes."],
    ["Qu'est-ce qu'une AMAP ?", ["Une association liant consommateurs et producteur par un engagement", "Un marché où les producteurs viennent vendre directement leurs récoltes", "Une coopérative agricole détenue par ses membres exploitants", "Un magasin tenu en commun par plusieurs producteurs de la région"], 0,
     "Les adhérents s'engagent à l'avance, ce qui partage le risque climatique."],
    ["Qu'est-ce que l'agroécologie ?", ["Une approche mobilisant les processus écologiques dans la production", "Une agriculture biologique certifiée par un organisme agréé", "Une agriculture raisonnée limitant les intrants chimiques sans les exclure", "Une agriculture de conservation qui renonce totalement au labour des sols"], 0,
     "Elle concerne autant les pratiques agronomiques que l'organisation des filières."],
    ["Qu'est-ce que la politique agricole commune ?", ["La politique agricole de l'Union européenne", "Une politique nationale propre à la France", "Un accord commercial agricole entre États", "Un programme de subventions ponctuel voté chaque année"], 0,
     "Lancée en 1962, elle représente une part importante du budget européen."],
    ["Quel est l'enjeu majeur de l'alimentation mondiale ?", ["Nourrir tous les humains sans épuiser les ressources", "Augmenter les rendements à tout prix", "Réduire les prix payés par les consommateurs des pays riches", "Diversifier les cultures dans chaque exploitation"], 0,
     "La production actuelle suffirait en théorie ; la répartition et le gaspillage font l'écart.", 3],
  ]),

  notion("ga3-arts-table", S, "Arts de la table",
    "Service, couverts, protocole.",
    "Le service à la française et le service à la russe ont façonné le repas moderne.",
    2, [
    ["Qu'est-ce que le service à la française ?", ["Un service où tous les plats d'un même service sont posés ensemble", "Un service assiette par assiette", "Un service au guéridon", "Un service en plusieurs temps"], 0,
     "Il valorisait l'abondance visuelle plus que la température des mets."],
    ["Qu'est-ce que le service à la russe ?", ["Un service où les plats se succèdent l'un après l'autre", "Un service à l'assiette", "Un service simultané", "Un service au buffet"], 0,
     "Adopté en France au XIXe siècle, il permet de servir chaque plat à bonne température."],
    ["Quand la fourchette s'impose-t-elle en France ?", ["Au XVIIe siècle", "Au Moyen Âge", "Au XIXe siècle", "Au XVe siècle, à la Renaissance italienne"], 0,
     "Longtemps jugée efféminée, elle se diffuse d'Italie sous Henri III et Louis XIV."],
    ["Dans quel ordre les couverts sont-ils disposés ?", ["De l'extérieur vers l'intérieur, selon l'ordre des plats", "Par taille croissante, du plus petit couvert au plus grand, en partant de l'assiette", "Selon la main dominante de chaque convive", "Sans aucune règle particulière régissant leur placement"], 0,
     "On utilise donc toujours le couvert le plus éloigné de l'assiette en premier."],
    ["Où le verre à eau se place-t-il ?", ["En haut à droite de l'assiette, devant les verres à vin", "À gauche de l'assiette, du côté des fourchettes", "Au centre de la table, au-dessus des assiettes", "À droite du couteau, contre le bord de la table"], 0,
     "Les verres à vin s'alignent ensuite en diagonale vers la droite."],
    ["Qu'est-ce qu'un couvert de service ?", ["Un couvert destiné à servir les convives, non à manger", "Un couvert supplémentaire dressé pour un invité imprévu", "Un couvert réservé au maître de maison qui préside", "Un couvert purement décoratif, que l'on n'utilise pas"], 0,
     "Cuillère et fourchette de service se manient généralement d'une seule main."],
    ["Que fait-on de sa serviette de table en quittant la table, momentanément ou pour de bon ?", ["On la pose sur la chaise si l'on revient, sur la table si l'on part", "On la laisse toujours sur la table, à gauche de l'assiette", "On la pose toujours sur la chaise, y compris en partant", "On la replie dans l'assiette avant l'arrivée des convives, et on l'y laisse"], 0,
     "Ces conventions varient sensiblement selon les pays."],
    ["Qu'est-ce que la préséance à table ?", ["L'ordre de placement des convives selon leur rang ou leur statut", "L'ordre dans lequel les convives sont servis à table", "L'ordre dans lequel les convives sont arrivés", "La priorité de parole accordée à certains convives"], 0,
     "Le protocole diplomatique en fixe les règles avec une grande précision."],
    ["Qu'est-ce qu'un menu dégustation ?", ["Une succession de petites portions choisies par le chef", "Un menu où chacun choisit librement ses plats", "Un menu fixe, rigoureusement identique pour tous les convives", "Un menu composé uniquement de produits de saison choisis le matin même"], 0,
     "Il permet au cuisinier de composer une progression complète de saveurs."],
    ["Que traduisent les codes de la table ?", ["Des conventions sociales historiquement situées, non des règles universelles", "Des exigences d'hygiène héritées de la médecine ancienne", "Des nécessités pratiques liées au service des plats", "Des traditions immuables, valables en tout temps et en tout lieu"], 0,
     "Ils varient fortement d'une culture à l'autre et se sont beaucoup allégés.", 3],
  ]),

  notion("ga3-restauration-metiers", S, "Les métiers de la restauration",
    "Brigade, salle, formation.",
    "Escoffier a organisé la cuisine professionnelle en brigade hiérarchisée.",
    2, [
    ["Qu'est-ce que la brigade de cuisine ?", ["Une organisation hiérarchisée des postes de cuisine", "L'ensemble du personnel travaillant dans la cuisine", "Le personnel chargé du service en salle", "Une équipe de production affectée aux préparations en série"], 0,
     "Escoffier l'a formalisée à la fin du XIXe siècle, sur un modèle militaire."],
    ["Que fait un chef de partie ?", ["Il dirige un poste spécifique de la cuisine", "Il seconde le chef sur l'ensemble de la cuisine", "Il gère les commandes et les livraisons de marchandises", "Il supervise le service en salle"], 0,
     "Saucier, poissonnier, entremétier et pâtissier sont des chefs de partie."],
    ["Que fait un saucier ?", ["Il prépare les sauces et souvent les plats mijotés", "Il assaisonne les plats juste avant l'envoi", "Il ne prépare que les fonds et les bouillons de base", "Il supervise toutes les cuissons de la brigade"], 0,
     "C'est traditionnellement l'un des postes les plus prestigieux de la brigade."],
    ["Que fait un garde-manger en cuisine ?", ["Il prépare les préparations froides", "Il gère les stocks du garde-manger", "Il réceptionne et contrôle les marchandises livrées", "Il conserve les produits en chambre froide"], 0,
     "Entrées froides, terrines et découpes lui reviennent."],
    ["Que fait un sommelier ?", ["Il conseille et sert les vins", "Il gère la cave uniquement", "Il achète les vins", "Il dirige le service en salle"], 0,
     "Il assure aussi la gestion de la cave et l'accord des vins avec les plats."],
    ["Que fait un maître d'hôtel ?", ["Il dirige le service en salle", "Il dirige l'établissement", "Il accueille les clients uniquement", "Il coordonne cuisine et salle"], 0,
     "Il assure la coordination entre la salle et la cuisine pendant le service."],
    ["Qu'est-ce que le CAP cuisine ?", ["Un diplôme professionnel de niveau initial", "Un diplôme supérieur, de niveau licence", "Un certificat d'aptitude délivré par l'employeur", "Une formation continue pour adultes"], 0,
     "Il reste la voie d'entrée la plus courante dans le métier en France."],
    ["Qu'est-ce que le concours Meilleur Ouvrier de France ?", ["Un concours d'excellence dans les métiers manuels", "Un concours de cuisine réservé aux chefs étoilés", "Un prix professionnel remis chaque année", "Un titre honorifique accordé sans épreuve à des professionnels reconnus"], 0,
     "Créé en 1924, il couvre plus de deux cents métiers, bien au-delà de la cuisine."],
    ["Qu'est-ce que le Bocuse d'Or ?", ["Un concours international de cuisine créé en 1987", "Un prix décerné chaque année par un guide gastronomique", "Un titre honorifique de meilleur chef cuisinier du monde", "Un concours purement français"], 0,
     "Il se déroule à Lyon tous les deux ans, avec des sélections continentales."],
    ["Quelle difficulté le secteur de la restauration connaît-il ?", ["Des tensions durables de recrutement liées aux conditions de travail", "Une baisse de la fréquentation", "Un manque de formations", "Une réglementation trop stricte"], 0,
     "Horaires décalés, coupures et pénibilité sont les motifs les plus cités.", 3],
  ]),

  notion("ga3-histoire-repas", S, "Histoire du repas",
    "Rythmes, lieux, sociabilités.",
    "Le nombre et l'heure des repas ont changé plusieurs fois au cours de l'histoire.",
    2, [
    ["Quand le mot dîner désignait-il le repas du milieu de journée ?", ["Jusqu'au XIXe siècle en France", "Au Moyen Âge seulement", "Jusqu'au XVIIe siècle", "Il l'a toujours désigné le soir"], 0,
     "Le décalage progressif des horaires explique les usages différents entre régions francophones."],
    ["Qu'est-ce que le déjeuner à l'origine ?", ["Le repas rompant le jeûne de la nuit", "Le repas pris au milieu de la journée", "Un repas léger pris debout", "Un repas de travail partagé avec ses collègues"], 0,
     "Le verbe déjeuner signifie littéralement cesser de jeûner."],
    ["Quand les restaurants apparaissent-ils à Paris ?", ["À la fin du XVIIIe siècle", "Au XVIIe siècle, sous Louis XIV", "Au début du XIXe siècle", "Au Moyen Âge"], 0,
     "Le mot désignait d'abord un bouillon restaurant, servi dans ces établissements."],
    ["Quel événement a favorisé l'essor des restaurants parisiens ?", ["La Révolution, qui a libéré les cuisiniers des grandes maisons", "L'Empire et la cour de Napoléon", "L'exposition universelle et l'afflux d'étrangers dans Paris", "L'industrialisation, qui a vidé les campagnes au profit des villes"], 0,
     "La suppression des corporations en 1791 a également joué un rôle décisif."],
    ["Qu'est-ce qu'un bouillon parisien ?", ["Un restaurant populaire servant une cuisine simple à bas prix", "Une soupe traditionnelle servie dans les halles", "Un café-restaurant de quartier ouvert jour et nuit sans interruption", "Une auberge de faubourg où logeaient autrefois les voyageurs de passage"], 0,
     "Plusieurs bouillons du XIXe siècle sont aujourd'hui classés monuments historiques."],
    ["Qu'est-ce que le café comme lieu au XVIIIe siècle ?", ["Un lieu de sociabilité et de discussion intellectuelle", "Un simple débit de boisson, sans autre fonction", "Un lieu de commerce où se traitaient les affaires de la ville", "Un salon privé réservé à quelques rares invités choisis"], 0,
     "Le café Procope, à Paris, était fréquenté par Diderot et Voltaire."],
    ["Qu'est-ce que le banquet dans l'Antiquité grecque ?", ["Un symposion mêlant boisson, conversation et divertissement", "Un repas religieux offert aux dieux de la cité", "Un festin civique offert par la cité à l'ensemble de ses magistrats", "Un repas de fête réunissant toute la famille élargie du défunt"], 0,
     "Le Banquet de Platon en donne la mise en scène philosophique la plus célèbre."],
    ["Qu'est-ce que la commensalité ?", ["Le fait de partager un repas, comme lien social", "Un usage de table hérité de la cour", "Une convivialité alimentaire propre aux banquets", "Un partage de nourriture avec les plus pauvres"], 0,
     "Manger ensemble est un marqueur d'appartenance dans presque toutes les sociétés."],
    ["Qu'est-ce que le repas gastronomique des Français ?", ["Une pratique sociale inscrite au patrimoine immatériel en 2010", "Un classement officiel plaçant la cuisine française au premier rang mondial", "Un label gastronomique décerné aux restaurants", "Une tradition culinaire protégée par une loi française de 2010"], 0,
     "C'est bien la pratique sociale, non la cuisine elle-même, qui est reconnue."],
    ["Quelle évolution récente touche le repas en France ?", ["Une déstructuration partielle au profit de prises alimentaires plus courtes", "Un allongement continu de la durée des repas", "La disparition complète du repas de midi durant toute la semaine de travail", "Un retour massif au repas traditionnel de trois plats pris en famille chaque jour"], 0,
     "Le modèle des trois repas reste toutefois plus solide en France qu'ailleurs en Europe.", 3],
  ]),

  notion("ga3-produits-mer", S, "Produits de la mer",
    "Poissons, coquillages, pêche.",
    "Une part importante des stocks de poissons mondiaux est exploitée à la limite.",
    2, [
    ["Quels poissons qualifie-t-on de poissons gras ?", ["Les poissons riches en lipides, comme le maquereau ou le saumon", "Les poissons d'élevage", "Les poissons de fond", "Les poissons de grande taille"], 0,
     "Ils sont particulièrement riches en acides gras oméga-3."],
    ["Que recouvre le terme d'aquaculture ?", ["L'élevage d'organismes aquatiques", "La pêche en eau douce", "La conchyliculture uniquement", "L'élevage de poissons de mer"], 0,
     "Elle fournit désormais environ la moitié du poisson consommé dans le monde."],
    ["Qu'est-ce que l'ostréiculture ?", ["L'élevage des huîtres", "L'élevage des moules", "La pêche aux coquillages", "L'élevage des coquilles Saint-Jacques"], 0,
     "La mytiliculture désigne l'élevage des moules."],
    ["Comment appelle-t-on l'élevage des moules sur pieux ?", ["La mytiliculture sur bouchots", "L'ostréiculture", "La conchyliculture sur filières", "L'élevage en pleine eau"], 0,
     "La baie du Mont-Saint-Michel en est l'un des principaux sites français."],
    ["Qu'est-ce que la surpêche ?", ["Une exploitation supérieure à la capacité de renouvellement des stocks", "Une pêche industrielle menée par de très gros navires-usines étrangers", "Une pêche menée en dehors de toute réglementation nationale ou internationale", "Une pêche excessive limitée à une seule zone côtière"], 0,
     "Plus d'un tiers des stocks mondiaux évalués sont surexploités."],
    ["En quoi consiste le chalutage de fond ?", ["Une technique traînant un filet sur le fond marin", "Une pêche à la ligne pratiquée dans les eaux les plus profondes", "Un filet dérivant laissé en pleine eau", "Une senne tournante que l'on referme sur le fond"], 0,
     "Il est critiqué pour son impact sur les habitats et ses prises accessoires."],
    ["Qu'est-ce qu'une prise accessoire ?", ["Une espèce capturée involontairement", "Un surplus de pêche revendu à bas prix", "Une espèce protégée pêchée par erreur", "Une capture rejetée à la mer"], 0,
     "Elle représente une part considérable des captures dans certaines pêcheries."],
    ["Qu'est-ce que le label MSC ?", ["Une certification de pêche durable", "Un label biologique", "Une norme sanitaire", "Une appellation d'origine"], 0,
     "Sa rigueur fait l'objet de débats parmi les organisations environnementales."],
    ["Qu'est-ce que le thon rouge de l'Atlantique ?", ["Une espèce très prisée dont les stocks ont failli s'effondrer", "Un thon d'élevage engraissé en cages marines", "Une espèce commune et abondante dans toutes les mers du globe", "Un poisson pêché uniquement par les petits bateaux de pêche artisanale"], 0,
     "Des quotas stricts ont permis un rétablissement partiel depuis 2010."],
    ["Qu'est-ce que la vente à la criée ?", ["Une vente aux enchères du poisson au débarquement", "Un marché aux poissons", "Une halle de vente", "Un lieu de négoce"], 0,
     "Les enchères y sont souvent descendantes, le prix baissant jusqu'au premier acheteur.", 3],
  ]),

  notion("ga3-herbes-epices", S, "Herbes et épices",
    "Origines, usages, commerce.",
    "Le mot épice vient du latin species, la marchandise : longtemps, elles relevaient autant de l'apothicaire que du cuisinier.",
    2, [
    ["D'où vient la noix de muscade ?", ["Des îles Banda, en Indonésie", "Des côtes de l'Inde du Sud", "De Ceylan, aujourd'hui le Sri Lanka", "De Madagascar"], 0,
     "Le monopole hollandais sur ces îles a donné lieu à une violence extrême au XVIIe siècle."],
    ["Qu'est-ce que le macis ?", ["L'arille rouge entourant la noix de muscade", "Une variété de muscade cultivée aux Antilles", "Une épice indienne au goût poivré", "Un mélange d'épices du Kerala"], 0,
     "Il provient donc du même fruit que la muscade, avec un goût plus fin."],
    ["D'où vient le clou de girofle ?", ["Des Moluques, en Indonésie", "De Zanzibar, sur la côte est-africaine", "D'Inde", "De Madagascar et des Comores"], 0,
     "Madagascar et Zanzibar en sont aujourd'hui de grands producteurs."],
    ["Qu'est-ce que le clou de girofle botaniquement ?", ["Un bouton floral séché", "Un fruit séché du giroflier", "Une graine aromatique", "Une écorce"], 0,
     "Il est cueilli avant l'ouverture de la fleur."],
    ["D'où vient la cannelle de Ceylan ?", ["Du Sri Lanka", "De Chine du Sud", "D'Inde", "D'Indonésie"], 0,
     "La cannelle de Chine, ou casse, est plus commune et de goût plus âpre."],
    ["Qu'est-ce que le safran ?", ["Les trois stigmates séchés d'un crocus", "Une fleur entière séchée", "Une racine jaune râpée", "Une graine aromatique jaune d'or"], 0,
     "Il faut environ cent cinquante mille fleurs pour obtenir un kilogramme d'épice."],
    ["Qu'est-ce que la vanille ?", ["Le fruit d'une orchidée liane, longuement affiné après récolte", "Une graine broyée d'un arbuste tropical", "Une petite graine aromatique noire", "Une écorce parfumée"], 0,
     "Récoltée verte et inodore, la gousse ne développe son parfum qu'après échaudage, étuvage et plusieurs mois d'affinage. Sa pollinisation manuelle a été mise au point par Edmond Albius à La Réunion en 1841."],
    ["D'où vient le poivre noir ?", ["De la côte de Malabar, en Inde", "Des îles de l'archipel indonésien", "De Ceylan", "Du Viêt Nam, dans le delta du Mékong"], 0,
     "Le Viêt Nam en est aujourd'hui le premier producteur mondial."],
    ["Qu'est-ce qui distingue le poivre noir du poivre blanc ?", ["Le stade de récolte et le traitement du grain", "L'espèce de plante dont proviennent les grains", "L'origine géographique de la récolte", "Le degré de séchage atteint après la cueillette du grain"], 0,
     "Le poivre blanc est débarrassé de son enveloppe après trempage."],
    ["Qu'est-ce que le curcuma ?", ["Un rhizome séché et réduit en poudre", "Une graine jaune moulue très finement", "Une écorce jaune", "Une fleur séchée puis réduite en poudre jaune"], 0,
     "Il donne sa couleur à de nombreux mélanges dits curry.", 3],
  ]),

  notion("ga3-terroirs-france-3", S, "Terroirs français",
    "Spécialités régionales.",
    "Chaque région française revendique des produits et des plats identitaires.",
    2, [
    ["De quelle région la choucroute est-elle emblématique ?", ["L'Alsace", "La Lorraine", "La Franche-Comté", "La Champagne"], 0,
     "Le chou fermenté est une technique de conservation d'origine bien plus ancienne."],
    ["De quelle région la bouillabaisse est-elle emblématique ?", ["Marseille et la Provence", "Le Languedoc", "La Corse", "Le Pays basque"], 0,
     "Née comme une soupe de pêcheurs, elle est devenue un plat coûteux."],
    ["De quelle région le cassoulet est-il emblématique ?", ["Le Languedoc, autour de Castelnaudary et Carcassonne", "La Gascogne", "Le Périgord", "Le Roussillon"], 0,
     "Castelnaudary, Carcassonne et Toulouse en revendiquent chacune une version."],
    ["De quelle région la galette de sarrasin est-elle emblématique ?", ["La Bretagne", "La Normandie", "Le Maine", "Le Poitou"], 0,
     "Le sarrasin, appelé blé noir, n'est pas une céréale mais une polygonacée."],
    ["De quelle région la tarte flambée est-elle emblématique ?", ["L'Alsace", "La Lorraine", "La Moselle", "Les Ardennes"], 0,
     "Appelée flammekueche, elle était cuite dans le four à pain avant la fournée."],
    ["De quelle région l'aligot est-il emblématique ?", ["L'Aubrac, en Aveyron et Lozère", "L'Auvergne du nord", "Le Cantal", "Le Limousin"], 0,
     "La tome fraîche donne au mélange sa texture filante caractéristique."],
    ["De quelle région la piperade est-elle emblématique ?", ["Le Pays basque", "Le Béarn", "Le Roussillon", "La Gascogne"], 0,
     "Le piment d'Espelette y tient une place centrale."],
    ["De quelle région le far est-il emblématique ?", ["La Bretagne", "La Normandie", "La Vendée", "Le Poitou"], 0,
     "Le far breton aux pruneaux est le plus répandu, mais il en existe des versions salées."],
    ["De quelle région la fondue savoyarde est-elle emblématique ?", ["La Savoie", "La Suisse romande", "Le Jura", "Le Dauphiné"], 0,
     "Beaufort, comté et emmental de Savoie en constituent souvent la base."],
    ["Qu'est-ce qui explique la diversité des cuisines régionales françaises ?", ["La variété des climats, des sols et des histoires locales", "La taille du pays", "L'ancienneté de la gastronomie", "Le morcellement administratif"], 0,
     "L'unification tardive du territoire a permis à ces traditions de se maintenir.", 3],
  ]),

  notion("ga3-alimentation-futur", S, "L'alimentation de demain",
    "Protéines, climat, innovations.",
    "Nourrir demain plus de monde sans épuiser les sols ni le climat est l'un des grands défis du siècle.",
    2, [
    ["Quelle part des émissions mondiales l'alimentation représente-t-elle ?", ["Environ un quart", "Environ dix pour cent", "Environ la moitié", "Environ cinq pour cent"], 0,
     "L'élevage en constitue la part la plus importante."],
    ["Pourquoi l'élevage bovin émet-il beaucoup de gaz à effet de serre ?", ["La fermentation entérique produit du méthane", "Il consomme énormément d'énergie dans les bâtiments", "Il nécessite de longs transports d'animaux", "Il utilise beaucoup d'engrais azotés"], 0,
     "Le méthane a un pouvoir de réchauffement bien supérieur au dioxyde de carbone."],
    ["Qu'est-ce qu'une protéine alternative ?", ["Une source de protéines remplaçant la viande", "Une protéine végétale extraite du soja", "Un complément alimentaire vendu en pharmacie", "Une protéine transformée par l'industrie agroalimentaire"], 0,
     "Légumineuses, insectes, protéines fermentées et viande cultivée en font partie."],
    ["Qu'est-ce que la viande cultivée ?", ["De la viande produite à partir de cellules animales en laboratoire", "Une viande imitée à partir de protéines végétales texturées de soja", "Une viande transformée en steak haché industriel", "Une viande d'élevage intensif produite en batterie dans d'immenses hangars"], 0,
     "Singapour a été le premier pays à en autoriser la vente, en 2020."],
    ["Quel avantage les légumineuses présentent-elles ?", ["Elles fixent l'azote et sont riches en protéines", "Elles poussent absolument partout, sans le moindre engrais", "Elles ne nécessitent aucune rotation des cultures", "Elles ne réclament aucune eau, même en été"], 0,
     "Leur culture réduit le besoin d'engrais azotés de synthèse."],
    ["Qu'est-ce que l'agriculture urbaine ?", ["Une production alimentaire en ville ou à sa périphérie", "Un jardinage collectif pratiqué en parcelles partagées", "Une culture hors sol menée sous serre", "Une production de proximité vendue à moins de cent kilomètres"], 0,
     "Son apport quantitatif reste modeste, son rôle social souvent important."],
    ["Qu'est-ce que la culture hors sol ?", ["Une culture sur substrat ou en solution nutritive", "Une culture en serre chauffée toute l'année", "Une culture verticale empilée sur plusieurs niveaux d'étagères", "Une culture éclairée uniquement par des lampes"], 0,
     "Elle économise l'eau mais dépend d'intrants et souvent d'énergie."],
    ["Qu'est-ce qu'un insecte comestible d'élevage ?", ["Une source de protéines à faible impact autorisée en Europe", "Un aliment traditionnel européen consommé depuis la plus haute Antiquité", "Un complément alimentaire interdit à la vente", "Une protéine expérimentale encore totalement interdite en Europe"], 0,
     "Plusieurs espèces ont reçu une autorisation européenne comme nouvel aliment."],
    ["Comment la FAO définit-elle la sécurité alimentaire ?", ["L'accès de tous à une nourriture suffisante, saine et adaptée", "L'absence de tout risque sanitaire dans les aliments mis sur le marché", "L'autosuffisance alimentaire de chaque pays", "La stabilité durable des prix de tous les produits agricoles"], 0,
     "Elle repose sur quatre piliers : disponibilité, accès, utilisation et stabilité."],
    ["Quel levier réduit le plus l'empreinte d'une alimentation ?", ["Réduire la part des produits animaux", "Acheter uniquement des produits locaux", "Éviter tous les emballages", "Privilégier systématiquement le bio"], 0,
     "Le transport pèse généralement bien moins que le mode de production.", 3],
  ]),
];
