/**
 * Géographie, deuxième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Géographie";

export const CG_GEOGRAPHIE_2: SeedSkill[] = [
  notion("geo2-relief-france", S, "Le relief de la France",
    "Massifs anciens, chaînes jeunes, bassins sédimentaires : la structure du territoire.",
    "Les massifs anciens sont usés et arrondis, les chaînes récentes hautes et découpées.",
    2, [
    ["Pourquoi l'altitude officielle du mont Blanc varie-t-elle d'une mesure à l'autre ?", ["L'épaisseur de la calotte glaciaire du sommet change", "Les instruments manquent de précision", "Le massif s'élève rapidement", "Le point culminant se déplace de plusieurs kilomètres"], 0,
     "Une mesure est réalisée tous les deux ans par des géomètres ; l'écart atteint parfois plusieurs mètres."],
    ["Quel massif ancien occupe le centre de la France ?", ["Le Massif central", "Les Vosges", "Les Ardennes", "Le Massif armoricain"], 0,
     "Il porte des volcans éteints, dont la chaîne des Puys, inscrite au patrimoine mondial."],
    ["Quel massif français est formé de plis calcaires réguliers ?", ["Le Jura", "Le Massif central", "Les Vosges", "Les Ardennes"], 0,
     "Le mot jurassique, période géologique, vient de ce massif."],
    ["Où la Loire prend-elle sa source ?", ["Au mont Gerbier-de-Jonc, en Ardèche", "Dans les Vosges, au nord-est de la France", "Dans le Jura, près de la frontière suisse", "Dans les Pyrénées, au sud-ouest du pays"], 0,
     "Elle parcourt ensuite environ mille kilomètres avant de rejoindre l'Atlantique près de Saint-Nazaire."],
    ["Quel fleuve français a le débit le plus élevé ?", ["Le Rhône", "La Loire", "La Seine", "La Garonne"], 0,
     "Alimenté par les glaciers alpins et le Léman, il conserve un débit élevé même en été."],
    ["Quel massif ancien occupe la Bretagne et la Normandie occidentale ?", ["Le Massif armoricain", "Le Massif central, au cœur du pays", "Les Ardennes, au nord-est", "Le Bassin parisien et ses plateaux"], 0,
     "Fortement érodé, il ne dépasse guère quatre cents mètres d'altitude."],
    ["Qu'est-ce qu'un bassin sédimentaire ?", ["Une vaste dépression comblée de couches déposées au fil des ères", "Un bassin fluvial rassemblant les eaux d'un même fleuve", "Une plaine d'inondation recouverte par les crues du fleuve", "Une zone d'affaissement d'origine volcanique"], 0,
     "Le Bassin parisien et le Bassin aquitain en sont les deux grands exemples français."],
    ["Qu'est-ce qu'une cuesta ?", ["Un relief dissymétrique à front abrupt et revers en pente douce", "Une falaise littorale taillée par les vagues dans la roche tendre", "Une vallée glaciaire au profil en auge nettement caractéristique", "Un plateau calcaire fissuré par la dissolution de la roche"], 0,
     "Les côtes de Meuse et de Moselle en sont des exemples classiques du Bassin parisien."],
    ["Quel volcan endormi domine la chaîne des Puys ?", ["Le puy de Dôme", "Le mont Aiguille", "Le pic du Midi", "Le Cantal"], 0,
     "Un dôme de lave visqueuse, formé il y a environ onze mille ans. La chaîne compte plus de quatre-vingts volcans.", 3],
  ]),

  notion("geo2-climats-monde", S, "Les climats du monde",
    "Zones climatiques, facteurs, nuances locales : lire une carte des climats.",
    "La latitude explique les grandes zones, mais l'altitude, la mer et les courants font le reste.",
    2, [
    ["Quel climat caractérise les régions proches de l'équateur ?", ["Le climat équatorial, chaud et humide toute l'année", "Le climat tropical marqué par une longue saison sèche", "Le climat désertique chaud, sans pluie régulière", "Le climat subtropical humide des façades orientales des continents"], 0,
     "Les températures y varient plus d'un jour à l'autre que d'une saison à l'autre."],
    ["Qu'est-ce qu'un climat méditerranéen ?", ["Des étés chauds et secs, des hivers doux et pluvieux", "Des pluies régulières réparties sur toute l'année", "Des hivers très froids et très secs", "Une longue saison sèche en hiver"], 0,
     "On le retrouve en Californie, au Chili central, en Afrique du Sud et dans le sud-ouest australien."],
    ["Qu'est-ce que la mousson ?", ["Un renversement saisonnier des vents apportant de fortes pluies", "Un cyclone tropical formé chaque été au-dessus de l'océan Indien", "Un vent de désert chargé de poussières", "Une saison sèche prolongée de plusieurs mois"], 0,
     "Elle conditionne l'agriculture de plus d'un milliard de personnes en Asie du Sud."],
    ["Quel courant marin adoucit le climat de l'Europe de l'Ouest ?", ["La dérive nord-atlantique, prolongement du Gulf Stream", "Le courant froid du Labrador, descendu de l'océan Arctique", "Le courant froid des Canaries, le long des côtes africaines", "Le courant froid de Benguela, le long de l'Afrique australe"], 0,
     "Elle explique pourquoi Brest est plus douce que Terre-Neuve, à latitude comparable."],
    ["Comment appelle-t-on la phase inverse d'El Niño ?", ["La Niña", "El Viejo, et rien d'autre", "L'oscillation australe positive", "Le Niño froid du Pacifique ouest"], 0,
     "Elle correspond à un refroidissement anormal du Pacifique équatorial est et modifie aussi les pluies mondiales."],
    ["Pourquoi les déserts se situent-ils souvent vers trente degrés de latitude ?", ["L'air descendant des cellules de Hadley y est sec", "La seule distance à l'équateur y limite les pluies", "Les vents y sont trop violents pour former des nuages", "L'ensoleillement y est maximal toute l'année"], 0,
     "Le Sahara, l'Arabie, le désert australien et l'Atacama s'alignent sur ces latitudes."],
    ["Qu'est-ce qu'un effet de fœhn ?", ["Un vent chaud et sec descendant sous le vent d'une montagne", "Un vent glacial descendant d'une vallée glaciaire", "Une brise de mer estivale soufflant l'après-midi", "Un courant ascendant précédant l'orage"], 0,
     "L'air perd son humidité en montant, puis se réchauffe fortement en redescendant."],
    ["Qu'est-ce qu'un îlot de chaleur urbain ?", ["Une élévation de température des villes par rapport aux campagnes voisines", "Une zone volcanique située sous une agglomération", "Un point chaud industriel rejetant de la chaleur dans l'atmosphère urbaine environnante", "Une accumulation de pollution atmosphérique au-dessus des toits"], 0,
     "Minéralisation, imperméabilisation et chaleur rejetée peuvent créer plusieurs degrés d'écart la nuit."],
    ["Qu'est-ce que le permafrost ?", ["Un sol gelé en permanence depuis au moins deux ans", "La couche de neige permanente des régions polaires", "La glace de mer qui se forme chaque hiver sur l'océan", "Le gel hivernal ordinaire des sols des régions tempérées"], 0,
     "Son dégel libère du méthane et déstabilise les constructions en Sibérie et en Alaska."],
    ["Qu'est-ce que la classification de Köppen ?", ["Une classification des climats fondée sur températures et précipitations", "Une classification des sols fondée sur leur composition et leur profondeur", "Un découpage des grandes zones de végétation naturelle à la surface du globe", "Un indice de sécheresse calculé à partir des pluies annuelles"], 0,
     "Publiée à partir de 1900, elle reste la référence, avec des mises à jour successives.", 3],
  ]),

  notion("geo2-fleuves-monde", S, "Les fleuves du monde",
    "Longueur, débit, bassin versant : les grands cours d'eau et ce qu'ils charrient.",
    "Le Nil est le plus long, mais l'Amazone charrie à elle seule un cinquième de l'eau douce que les fleuves du monde déversent dans les océans.",
    2, [
    ["Quel est approximativement le débit de l'Amazone à son embouchure ?", ["Environ deux cent mille mètres cubes par seconde", "Environ vingt mille mètres cubes par seconde", "Environ deux mille mètres cubes par seconde", "Environ deux millions de mètres cubes par seconde"], 0,
     "Cela dépasse à soi seul le débit des sept fleuves suivants réunis, et représente un cinquième de l'eau douce rejoignant les océans."],
    ["Quel fleuve traverse Le Caire ?", ["Le Nil", "L'Euphrate", "Le Jourdain", "L'Oronte"], 0,
     "Le delta du Nil concentre la quasi-totalité de la population égyptienne."],
    ["Quel fleuve africain a le deuxième débit mondial ?", ["Le Congo", "Le Niger", "Le Zambèze", "Le Nil"], 0,
     "Son bassin couvre une grande partie de la forêt équatoriale africaine."],
    ["Quel fleuve traverse Shanghai avant de se jeter dans la mer de Chine ?", ["Le Yangzi", "Le fleuve Jaune", "Le Mékong", "La rivière des Perles"], 0,
     "Le plus long fleuve d'Asie. Le barrage des Trois-Gorges le barre en amont."],
    ["Quel fleuve chinois est surnommé le fleuve Jaune ?", ["Le Huang He", "Le Yangzi", "Le Xi Jiang", "L'Amour"], 0,
     "La couleur vient du lœss qu'il charrie. Ses crues meurtrières lui ont valu le surnom de fléau de la Chine."],
    ["Quel fleuve d'Asie du Sud-Est traverse six pays ?", ["Le Mékong", "L'Irrawaddy", "Le Chao Phraya", "Le Salouen"], 0,
     "Chine, Birmanie, Laos, Thaïlande, Cambodge et Vietnam. Les barrages amont sont un sujet de tension régionale."],
    ["Quel est le plus long fleuve d'Europe ?", ["La Volga", "Le Danube", "Le Rhin", "Le Dniepr"], 0,
     "Environ trois mille cinq cents kilomètres, entièrement en Russie, se jetant dans la mer Caspienne."],
    ["Qu'est-ce qu'un delta ?", ["Une embouchure ramifiée où le fleuve dépose ses sédiments", "Un estuaire élargi", "Un confluent de deux fleuves", "Une zone de rapides"], 0,
     "Un estuaire, à l'inverse, est une embouchure unique élargie où la marée pénètre.", 3],
  ]),

  notion("geo2-montagnes-monde", S, "Les montagnes du monde",
    "Chaînes, sommets, formation : le relief à grande échelle.",
    "Les plus hautes chaînes sont toutes le résultat de collisions de plaques encore actives.",
    2, [
    ["Quelle altitude la mesure conjointe sino-népalaise de 2020 attribue-t-elle à l'Everest ?", ["8 849 mètres", "8 848 mètres, l'ancienne mesure", "8 611 mètres, altitude du K2", "8 900 mètres, chiffre arrondi"], 0,
     "Le désaccord antérieur portait sur la prise en compte ou non de la couche de neige sommitale."],
    ["Quelle collision de plaques a formé l'Himalaya ?", ["La plaque indienne contre la plaque eurasiatique", "La plaque africaine contre la plaque européenne occidentale", "La plaque pacifique contre le continent asiatique", "La plaque arabique contre le plateau iranien"], 0,
     "La collision continue : la chaîne gagne encore quelques millimètres par an."],
    ["Quel est le plus haut sommet d'Amérique ?", ["L'Aconcagua", "Le Denali, en Alaska", "Le Chimborazo, en Équateur", "L'Ojos del Salado, à la frontière chilienne"], 0,
     "Près de sept mille mètres, en Argentine. Le Denali est le plus haut d'Amérique du Nord."],
    ["Quel sommet est le point de la surface terrestre le plus éloigné du centre de la Terre ?", ["Le Chimborazo", "L'Everest, au Népal", "Le Kilimandjaro, en Tanzanie", "Le Denali, en Amérique du Nord"], 0,
     "L'aplatissement de la Terre aux pôles avantage ce volcan équatorien malgré son altitude moindre."],
    ["Quel est le plus haut sommet d'Afrique ?", ["Le Kilimandjaro", "Le mont Kenya, à l'est du continent", "Le Ruwenzori, entre Ouganda et Congo", "Le Ras Dashen, en Éthiopie"], 0,
     "Un volcan isolé de cinq mille huit cent quatre-vingt-quinze mètres, dont les glaciers reculent rapidement."],
    ["Quelle chaîne longe toute la côte ouest de l'Amérique du Sud ?", ["Les Andes", "Les Rocheuses, en Amérique du Nord", "La Sierra Madre, au Mexique", "La cordillère de la Côte, en bord de mer"], 0,
     "Environ sept mille kilomètres, la plus longue chaîne continentale du monde."],
    ["Qu'est-ce que la ceinture de feu du Pacifique ?", ["Un alignement de volcans et de séismes autour du Pacifique", "Une zone de courants chauds du Pacifique", "Une ligne de récifs coralliens tropicaux", "Une zone de typhons récurrents en été"], 0,
     "Elle concentre environ soixante-quinze pour cent des volcans actifs émergés."],
    ["Quel massif sépare traditionnellement l'Europe de l'Asie ?", ["L'Oural", "Le Caucase, et lui seul", "Les Carpates, en Europe centrale", "L'Altaï, en Asie centrale"], 0,
     "La limite conventionnelle suit aussi le Caucase et la mer Caspienne, sans réalité physique tranchée."],
    ["Combien de sommets dépassent huit mille mètres sur Terre ?", ["Quatorze", "Dix exactement", "Vingt environ", "Huit seulement"], 0,
     "Tous situés dans l'Himalaya et le Karakoram."],
    ["Qu'est-ce qu'un point chaud volcanique ?", ["Une remontée de magma indépendante des limites de plaques", "Une zone de subduction active où une plaque plonge sous l'autre", "Une dorsale océanique au milieu d'un océan", "Une faille transformante décalant deux plaques"], 0,
     "Hawaï et La Réunion en sont des exemples : la plaque défile au-dessus, produisant un alignement d'îles.", 3],
  ]),

  notion("geo2-oceans-mers", S, "Océans et mers",
    "Cinq océans, des mers bordières, des courants qui règlent le climat.",
    "L'océan Austral n'a été proposé comme cinquième océan qu'en 2000, et sa reconnaissance reste inégale.",
    2, [
    ["Quel est le plus vaste océan du monde ?", ["Le Pacifique", "L'Atlantique, entre l'Europe et l'Amérique", "L'océan Indien, au sud de l'Asie", "L'océan Austral, autour de l'Antarctique"], 0,
     "Il couvre à lui seul environ un tiers de la surface du globe."],
    ["Quelle est la fosse océanique la plus profonde ?", ["La fosse des Mariannes", "La fosse des Tonga, dans le Pacifique sud", "La fosse du Japon, au large de Honshu", "La fosse de Porto Rico, dans l'Atlantique"], 0,
     "Près de onze mille mètres. L'Everest y tiendrait entièrement immergé."],
    ["Qu'est-ce qu'une dorsale océanique ?", ["Une chaîne sous-marine où se forme une nouvelle croûte", "Une fosse profonde de subduction", "Un plateau continental peu profond", "Une chaîne de volcans insulaires alignés"], 0,
     "La dorsale médio-atlantique émerge en Islande, où l'on peut l'observer à terre."],
    ["Qu'est-ce que la circulation thermohaline ?", ["Un mouvement océanique global lié aux différences de température et de salinité", "Un courant de surface saisonnier qui s'inverse à chaque changement de la mousson", "La circulation des masses d'eau sous l'effet des marées", "Un brassage vertical limité aux mers fermées"], 0,
     "Un tour complet demande environ mille ans. Son ralentissement est une préoccupation climatique."],
    ["Qu'est-ce qu'un upwelling ?", ["Une remontée d'eaux profondes froides et riches en nutriments", "Une descente d'eaux salées et denses vers les grandes profondeurs", "Un courant chaud équatorial dirigé vers l'ouest par les alizés", "Une marée de vive-eau à l'équinoxe"], 0,
     "Les zones d'upwelling, comme au large du Pérou, comptent parmi les plus poissonneuses du monde."],
    ["Quelle étendue d'eau est la plus salée du monde ?", ["La mer Morte", "La mer Rouge, entre l'Afrique et l'Arabie", "La Méditerranée, entre trois continents", "La mer Caspienne, le plus grand lac du monde"], 0,
     "Environ dix fois la salinité de l'océan. C'est un lac endoréique, non une mer au sens strict."],
    ["Quelle culture a motivé le détournement des fleuves alimentant la mer d'Aral ?", ["Le coton", "Le riz des plaines irriguées", "Le blé des steppes kazakhes", "La betterave à sucre"], 0,
     "L'Union soviétique visait l'autosuffisance cotonnière ; la mer a perdu l'essentiel de sa surface en quarante ans."],
    ["Qu'est-ce que le plateau continental ?", ["Le prolongement immergé peu profond d'un continent", "Le fond des grandes profondeurs océaniques, loin des côtes", "Une vaste plaine abyssale couverte de sédiments fins", "Une île sous-marine à sommet aplati"], 0,
     "Sa délimitation juridique conditionne les droits d'exploitation des ressources sous-marines."],
    ["Qu'est-ce qu'une zone économique exclusive ?", ["Une bande de deux cents milles marins où l'État côtier exploite les ressources", "Les eaux territoriales bordant immédiatement la côte", "Une zone de pêche ouverte à toutes les flottes", "Un espace de libre navigation pour tous les navires"], 0,
     "Les eaux territoriales, où s'exerce la pleine souveraineté, ne s'étendent que sur douze milles."],
    ["Qu'est-ce que le septième continent de plastique ?", ["Une concentration de microplastiques en suspension dans un gyre océanique", "Une île compacte de déchets flottants assez solide pour être cartographiée", "Un banc de sable pollué par les déchets rejetés", "Une zone morte du large"], 0,
     "L'image d'une île est trompeuse : il s'agit d'une soupe diffuse de particules, difficile à collecter.", 3],
  ]),

  notion("geo2-population-mondiale", S, "La population mondiale",
    "Répartition, croissance, transition démographique : combien nous sommes et où.",
    "Une population peut continuer à croître vite même quand chaque femme a moins d'enfants qu'avant : tout dépend de l'âge moyen de la population de départ.",
    2, [
    ["Qu'est-ce que la transition démographique ?", ["Le passage d'une forte natalité et mortalité à de faibles niveaux des deux", "Une chute brutale de la population d'un pays", "Le vieillissement progressif d'une population", "Une migration massive des campagnes vers les villes"], 0,
     "La baisse de la mortalité précédant celle de la natalité, la population augmente fortement entre les deux."],
    ["Qu'est-ce que l'indice de fécondité de remplacement ?", ["Environ deux virgule un enfants par femme", "Deux enfants exactement par femme", "Trois enfants par femme", "Un virgule cinq enfant par femme en moyenne"], 0,
     "Le dixième supplémentaire compense la mortalité avant l'âge de procréer et le léger déséquilibre à la naissance."],
    ["Quel continent connaît la croissance démographique la plus rapide ?", ["L'Afrique", "L'Asie et ses géants démographiques", "L'Amérique latine et les Caraïbes", "L'Océanie et ses archipels"], 0,
     "Sa population pourrait doubler d'ici le milieu du siècle selon les projections médianes."],
    ["Que révèle un creux marqué dans une pyramide des âges ?", ["Un déficit de naissances lié à un événement passé", "Une erreur de recensement dans les classes d'âge concernées", "Une vague d'émigration récente", "Un vieillissement accéléré de la population"], 0,
     "Les classes creuses des deux guerres mondiales restent visibles sur les pyramides françaises pendant des décennies."],
    ["Qu'appelle-t-on l'espérance de vie à la naissance ?", ["La durée de vie moyenne d'une génération soumise aux conditions de mortalité de l'année", "L'âge moyen au décès effectivement observé dans l'ensemble du pays au cours de l'année écoulée", "L'âge médian de la population du pays", "La durée de vie maximale jamais atteinte"], 0,
     "C'est un indicateur du moment, non une prédiction pour les personnes nées cette année-là."],
    ["Où se concentre l'essentiel de la population mondiale ?", ["En Asie de l'Est et du Sud", "En Afrique subsaharienne", "En Europe occidentale et centrale", "En Amérique du Nord et centrale"], 0,
     "Chine, Inde, Indonésie et Pakistan réunissent à eux seuls plus de quarante pour cent de l'humanité."],
    ["Qu'est-ce qu'un désert humain ?", ["Une zone très faiblement peuplée", "Une zone désertique aride et sans eau", "Une région en dépeuplement", "Une région dépourvue de ville"], 0,
     "Sahara, Amazonie, Sibérie, Australie centrale et hautes latitudes en sont les principaux."],
    ["Qu'est-ce que le solde migratoire d'un pays ?", ["La différence entre entrées et sorties de population", "Le nombre total d'immigrés résidant durablement dans le pays", "Le taux annuel de naturalisation des étrangers", "Le nombre de demandeurs d'asile enregistrés dans l'année"], 0,
     "Il s'ajoute au solde naturel pour donner la variation totale de population."],
    ["Quel pays a connu une politique de limitation des naissances de 1979 à 2015 ?", ["La Chine", "L'Inde et son programme de planification", "Le Vietnam, de 1988 à 2003", "La Corée du Sud, dans les années 1960"], 0,
     "La politique de l'enfant unique a laissé un déséquilibre durable entre les sexes et un vieillissement accéléré.", 3],
  ]),

  notion("geo2-urbanisation", S, "Villes et urbanisation",
    "Métropoles, mégalopoles, étalement urbain : où et comment vivent les citadins.",
    "La ville ne se définit pas de la même façon partout : le seuil de population retenu varie de 200 à 50 000 habitants selon les pays.",
    2, [
    ["Depuis quand la majorité de l'humanité vit-elle en ville ?", ["Depuis 2007 environ", "Depuis 1950, après-guerre", "Depuis 1990, à la fin du siècle", "Depuis 2020, tout récemment"], 0,
     "La proportion devrait dépasser deux tiers au milieu du siècle."],
    ["Qu'est-ce qu'une mégapole ?", ["Une agglomération de plus de dix millions d'habitants", "La capitale politique et économique d'un très grand pays", "Une ville mondiale de premier rang dans les classements", "Une conurbation de plusieurs villes voisines"], 0,
     "On en compte plus d'une trentaine, majoritairement en Asie."],
    ["Qu'est-ce qu'une mégalopole ?", ["Un chapelet continu de grandes villes reliées entre elles", "Une très grande ville isolée dans son pays", "Une capitale économique et financière d'un pays", "Une métropole comptant plus de vingt millions d'habitants au total"], 0,
     "La mégalopole américaine du Nord-Est, la japonaise et la dorsale européenne en sont les trois principales."],
    ["Quelle est l'agglomération la plus peuplée du monde ?", ["Tokyo", "Delhi, en Inde", "Shanghai, en Chine", "São Paulo, au Brésil"], 0,
     "Environ trente-sept millions d'habitants selon les définitions les plus larges."],
    ["Qu'est-ce que l'étalement urbain ?", ["L'extension de la ville en périphérie à faible densité", "La densification progressive des centres-villes anciens", "La croissance verticale des villes en tours et en gratte-ciel", "L'annexion administrative des communes voisines"], 0,
     "Il augmente les distances, la dépendance à la voiture et la consommation d'espaces agricoles."],
    ["Qu'est-ce que la gentrification ?", ["Le remplacement progressif des habitants modestes d'un quartier par des plus aisés", "La rénovation complète d'un centre historique classé", "La création d'un quartier d'affaires en périphérie", "L'installation de commerces de luxe dans une rue"], 0,
     "Le terme est forgé en 1964 par la sociologue Ruth Glass à propos de Londres."],
    ["Qu'est-ce qu'un bidonville ?", ["Un quartier d'habitat précaire souvent sans titre de propriété ni services", "Un quartier ouvrier ancien bâti autour d'usines aujourd'hui fermées et désaffectées", "Un lotissement informel régularisé par la commune", "Un camp de réfugiés géré par une organisation"], 0,
     "Plus d'un milliard de personnes y vivraient selon les estimations des Nations unies."],
    ["Qu'est-ce que la ville nouvelle ?", ["Une ville planifiée ex nihilo pour désengorger une métropole", "Un quartier récemment construit à la périphérie d'une grande ville", "Une ville entièrement reconstruite après les destructions de la guerre", "Une capitale administrative régionale"], 0,
     "Cinq ont été créées en région parisienne à partir des années 1960."],
    ["Qu'est-ce qu'un centre d'affaires comme La Défense ?", ["Un quartier spécialisé concentrant les sièges sociaux et les bureaux", "Un très grand centre commercial d'envergure régionale ouvert le dimanche", "Un quartier historique entièrement rénové et piétonnisé", "Une zone industrielle de périphérie"], 0,
     "Ce modèle de spécialisation fonctionnelle est aujourd'hui critiqué au profit de la mixité des usages."],
    ["Qu'est-ce que la ville du quart d'heure ?", ["Un modèle urbain où l'essentiel est accessible en quinze minutes à pied ou à vélo", "Une ville que l'on peut traverser d'un bout à l'autre en un quart d'heure seulement", "Un quartier desservi par les transports en commun toutes les quinze minutes de la journée", "Une ville entièrement fermée aux voitures"], 0,
     "Formulé par Carlos Moreno, il vise à réduire les déplacements contraints plutôt qu'à les rendre plus rapides.", 3],
  ]),

  notion("geo2-agriculture-monde", S, "L'agriculture dans le monde",
    "Systèmes agricoles, rendements, sécurité alimentaire : nourrir huit milliards de personnes.",
    "La faim dans le monde ne résulte pas d'un manque global de production mais de l'accès aux ressources.",
    2, [
    ["Quelle céréale est la plus produite dans le monde ?", ["Le maïs", "Le blé, cultivé en zone tempérée", "Le riz, cultivé en Asie de la mousson", "L'orge, surtout destinée au bétail"], 0,
     "Une large part sert à l'alimentation animale et aux agrocarburants, non à l'alimentation humaine directe."],
    ["Quelle céréale nourrit le plus grand nombre d'êtres humains directement ?", ["Le riz", "Le maïs, surtout utilisé pour le bétail", "Le blé, base du pain en Europe", "Le sorgho, cultivé en zones sèches"], 0,
     "Aliment de base pour plus de la moitié de l'humanité, principalement en Asie."],
    ["Qu'est-ce que l'agriculture vivrière ?", ["Une agriculture destinée d'abord à nourrir le producteur et sa famille", "Une agriculture de subsistance pratiquée sans aucun outil", "Une agriculture biologique de tradition ancienne", "Une petite agriculture des marges périurbaines"], 0,
     "Elle s'oppose à l'agriculture commerciale, orientée vers la vente et l'exportation."],
    ["Qu'appelle-t-on la révolution verte ?", ["La diffusion de variétés à haut rendement et d'intrants dans les années 1960", "Le passage généralisé de l'agriculture mondiale aux seules méthodes biologiques", "La mécanisation des campagnes au XIXe siècle", "L'irrigation généralisée des zones arides du globe"], 0,
     "Elle a fortement accru les rendements en Asie, au prix d'une dépendance aux engrais et à l'eau."],
    ["Qu'est-ce que la monoculture ?", ["La culture répétée d'une seule espèce sur une même parcelle", "Une culture unique pratiquée sur l'ensemble du territoire d'un pays", "Une exploitation agricole entièrement dépourvue de tout élevage", "Une culture menée sous serre"], 0,
     "Elle simplifie le travail mais fragilise face aux maladies et appauvrit les sols."],
    ["Qu'est-ce que l'agriculture sur brûlis ?", ["Une culture itinérante après défrichement par le feu", "Une technique de fertilisation des sols par les cendres", "Un mode de désherbage par le feu", "Une culture installée après un incendie naturel"], 0,
     "Soutenable à faible densité de population, elle devient destructrice quand les cycles de jachère raccourcissent."],
    ["Qu'est-ce que la sécurité alimentaire selon la FAO ?", ["L'accès physique et économique de tous à une nourriture suffisante et saine", "L'absence totale de contamination des aliments vendus", "L'autosuffisance alimentaire de chaque nation", "Le contrôle sanitaire des seules denrées importées"], 0,
     "Disponibilité, accès, utilisation et stabilité en sont les quatre dimensions."],
    ["Qu'est-ce que l'accaparement de terres ?", ["L'acquisition à grande échelle de terres agricoles par des acteurs étrangers", "La concentration progressive des exploitations agricoles à l'intérieur d'un pays", "L'expropriation de terres agricoles par l'État pour cause d'utilité publique reconnue", "Le remembrement des parcelles agricoles"], 0,
     "Le phénomène s'est accéléré après la flambée des prix alimentaires de 2008."],
    ["Qu'est-ce qu'un OGM ?", ["Un organisme dont le génome a été modifié par génie génétique", "Un hybride obtenu par croisement classique entre deux variétés", "Une variété sélectionnée sur plusieurs générations", "Une plante régulièrement traitée aux pesticides"], 0,
     "Leur culture est très encadrée dans l'Union européenne, largement répandue aux Amériques."],
    ["Qu'est-ce que l'élevage extensif ?", ["Un élevage sur de vastes surfaces à faible densité d'animaux", "Un élevage entièrement conduit en bâtiment fermé toute l'année", "Un élevage à très forte productivité rapportée à chaque animal", "Un élevage sans le moindre apport d'aliment venu de l'extérieur"], 0,
     "Il consomme beaucoup d'espace mais peu d'intrants, à l'inverse de l'élevage intensif.", 3],
  ]),

  notion("geo2-energie-ressources", S, "Ressources et matières premières",
    "Qui produit quoi, où, et quelles dépendances cela crée.",
    "La localisation des ressources ne coïncide presque jamais avec celle de la consommation.",
    2, [
    ["Quel pays est le premier producteur mondial de pétrole ces dernières années ?", ["Les États-Unis", "L'Arabie saoudite, dans le Golfe", "La Russie et sa Sibérie occidentale", "L'Irak, membre de l'OPEP"], 0,
     "Le pétrole de schiste les a placés en tête depuis le milieu des années 2010."],
    ["Qu'est-ce que l'OPEP ?", ["Une organisation de pays exportateurs de pétrole coordonnant leur production", "Une bourse pétrolière où se fixe le prix du baril", "Une agence internationale de régulation énergétique", "Un consortium des grandes compagnies pétrolières privées"], 0,
     "Fondée en 1960, elle influence les prix en ajustant les quotas de production de ses membres."],
    ["Quel pays détient les plus grandes réserves prouvées de gaz naturel ?", ["La Russie", "Le Qatar, dans le golfe Persique", "L'Iran, au nord du Golfe", "Les États-Unis d'Amérique"], 0,
     "L'Iran et le Qatar suivent de près, partageant un gisement commun dans le golfe Persique."],
    ["Qu'est-ce qu'une terre rare ?", ["Un groupe de dix-sept métaux essentiels aux technologies modernes", "Un minerai présent en très faible quantité dans l'écorce", "Une roche sédimentaire rare et précieuse", "Un métal précieux comparable à l'or"], 0,
     "Elles ne sont pas rares géologiquement, mais leur extraction et leur séparation sont difficiles et polluantes."],
    ["Quel pays domine largement le raffinage des terres rares ?", ["La Chine", "Les États-Unis d'Amérique", "L'Australie et ses mines de l'Ouest", "Le Brésil, en Amérique du Sud"], 0,
     "Cette concentration constitue un enjeu stratégique majeur pour l'électronique et les énergies renouvelables."],
    ["Quel métal est indispensable aux batteries des véhicules électriques ?", ["Le lithium", "Le cuivre, et lui seul", "Le zinc des batteries anciennes", "L'étain des soudures électroniques"], 0,
     "Cobalt, nickel et graphite y jouent aussi un rôle. Le triangle du lithium se situe en Amérique du Sud."],
    ["Quel pays produit la majorité du cobalt mondial ?", ["La République démocratique du Congo", "L'Australie et ses gisements de l'Ouest", "La Russie et sa péninsule de Kola", "Le Canada et son bouclier précambrien"], 0,
     "Les conditions d'extraction artisanale y posent de graves problèmes sociaux et sanitaires."],
    ["Qu'est-ce qu'une ressource non renouvelable ?", ["Une ressource dont le stock ne se reconstitue pas à l'échelle humaine", "Une ressource particulièrement difficile et coûteuse à extraire du sous-sol", "Une ressource entièrement importée de l'étranger", "Une ressource non recyclable en fin d'usage"], 0,
     "Le recyclage prolonge l'usage des métaux, mais les combustibles fossiles sont détruits à l'usage."],
    ["Qu'est-ce que le pic pétrolier ?", ["Le moment où la production mondiale atteindrait son maximum avant de décliner", "Le moment où le prix du baril atteint son record historique sur les marchés mondiaux", "Le moment où la consommation annuelle mondiale de pétrole atteindrait son maximum", "L'épuisement total des réserves connues"], 0,
     "Les prévisions ont été plusieurs fois démenties par de nouvelles techniques d'extraction."],
    ["Qu'est-ce que la malédiction des ressources ?", ["Le constat que des pays riches en ressources connaissent souvent une croissance faible", "L'épuisement toujours plus rapide des gisements les plus faciles à exploiter d'un pays producteur", "La dépendance durable d'un pays à ses importations de matières premières", "La pollution des sols et des eaux liée à l'extraction minière"], 0,
     "Rente, corruption, conflits et surévaluation monétaire en sont les mécanismes le plus souvent avancés.", 3],
  ]),

  notion("geo2-transports-mondialisation", S, "Transports et mondialisation",
    "Conteneurs, détroits, hubs : les infrastructures qui rendent possible l'économie mondiale.",
    "La mer porte l'essentiel du commerce mondial en volume — une part bien plus élevée qu'on ne l'imagine.",
    2, [
    ["Quelle part du commerce mondial passe par voie maritime en volume ?", ["Environ quatre-vingts pour cent", "Environ la moitié seulement du total", "Environ trente pour cent du total", "Environ quatre-vingt-quinze pour cent"], 0,
     "En valeur, la part est moindre, l'avion transportant les marchandises les plus précieuses."],
    ["Quel détroit relie la Méditerranée à l'Atlantique ?", ["Le détroit de Gibraltar", "Le détroit du Bosphore, à Istanbul", "Le détroit de Messine, entre Sicile et Italie", "Le canal de Sicile, vers la Tunisie"], 0,
     "Quatorze kilomètres au plus étroit. Le Bosphore relie la mer Noire à la Méditerranée."],
    ["Quel détroit sépare la péninsule malaise de Sumatra et concentre un trafic considérable ?", ["Le détroit de Malacca", "Le détroit de Bab-el-Mandeb, en mer Rouge", "Le détroit d'Ormuz, resserré entre deux rives", "Le détroit de Formose, face à Taïwan"], 0,
     "Un quart du commerce maritime mondial y passe, dans un couloir parfois large de moins de trois kilomètres."],
    ["Quel détroit contrôle la sortie du golfe Persique ?", ["Le détroit d'Ormuz", "Le détroit de Malacca, en Asie du Sud-Est", "Bab-el-Mandeb, au sud de la mer Rouge", "Le canal de Suez, en Égypte"], 0,
     "Environ un cinquième du pétrole mondial y transite, ce qui en fait un point de tension permanent."],
    ["Qu'est-ce qu'un hub de transport ?", ["Une plateforme de correspondance concentrant les flux", "Un port de commerce d'importance régionale", "Un entrepôt logistique de grande capacité", "Une gare de triage ferroviaire"], 0,
     "Le modèle en étoile permet de relier de nombreuses destinations avec moins de liaisons directes."],
    ["Quel est le premier port mondial pour le trafic de conteneurs ?", ["Shanghai", "Singapour, à la pointe de la Malaisie", "Rotterdam, aux Pays-Bas", "Busan, en Corée du Sud"], 0,
     "Il occupe la première place depuis 2010 ; les ports chinois occupent la majorité des dix premières places mondiales."],
    ["Quel est le premier port européen ?", ["Rotterdam", "Anvers, en Belgique", "Hambourg, sur l'Elbe", "Le Havre, à l'embouchure de la Seine"], 0,
     "Sa position à l'embouchure du Rhin lui donne accès à l'arrière-pays industriel européen."],
    ["Qu'est-ce que la route de la soie moderne lancée par la Chine ?", ["Un vaste programme d'infrastructures reliant l'Asie à l'Europe et à l'Afrique", "Un accord commercial régional signé avec l'ensemble des pays d'Asie du Sud-Est", "Une seule ligne ferroviaire transcontinentale reliant Pékin à l'Europe", "Un réseau de zones franches ouvertes aux investisseurs étrangers"], 0,
     "Lancé en 2013, il combine ports, voies ferrées, routes et investissements énergétiques."],
    ["Quelle place le fret aérien occupe-t-il dans le commerce mondial ?", ["Une faible part du volume mais une part importante de la valeur", "La majorité du volume des marchandises échangées à travers le monde", "La moitié de la valeur des marchandises échangées à travers le monde", "Une part négligeable, en valeur comme en volume"], 0,
     "Composants électroniques, médicaments et produits périssables en constituent l'essentiel.", 3],
  ]),

  notion("geo2-frontieres-conflits", S, "Frontières et territoires disputés",
    "Comment se tracent les limites politiques et pourquoi certaines restent contestées.",
    "Une frontière n'est jamais naturelle : même un fleuve suppose une convention sur la ligne exacte.",
    2, [
    ["Qu'est-ce qu'une frontière artificielle ?", ["Une frontière tracée sans suivre un élément du relief", "Une frontière contestée par l'un des deux États voisins", "Une frontière récente tracée après une guerre", "Une frontière fermée à toute circulation de personnes et de biens"], 0,
     "Nombre de frontières africaines suivent des méridiens ou des parallèles hérités du partage colonial."],
    ["Qu'est-ce qu'une enclave ?", ["Un territoire entièrement entouré par un autre État", "Une zone frontalière démilitarisée par un accord de paix", "Une région autonome dotée d'un parlement", "Un territoire non reconnu par ses voisins"], 0,
     "Le Lesotho, entouré par l'Afrique du Sud, en est un exemple à l'échelle d'un État entier."],
    ["Quel territoire est disputé entre l'Inde, le Pakistan et la Chine ?", ["Le Cachemire", "Le Sind, province pakistanaise", "Le Pendjab, au nord-ouest de l'Inde", "L'Assam, dans le nord-est indien"], 0,
     "Trois guerres et de nombreux affrontements depuis 1947. Une ligne de contrôle sépare les zones administrées."],
    ["Quel territoire est administré par le Maroc et revendiqué par un mouvement indépendantiste ?", ["Le Sahara occidental", "La Mauritanie, au sud du Maroc", "Le Rif, dans le nord du Maroc", "Ceuta, enclave espagnole"], 0,
     "Le statut du territoire reste inscrit à l'ordre du jour des Nations unies depuis 1965."],
    ["Quelle île est revendiquée par la Chine comme partie de son territoire ?", ["Taïwan", "Hainan, au sud de la Chine", "Okinawa, dans l'archipel japonais", "Hong Kong, sur la côte méridionale"], 0,
     "L'île dispose de ses propres institutions depuis 1949 sans reconnaissance internationale majoritaire."],
    ["Quelle mer voit s'affronter plusieurs revendications sur des îlots et récifs ?", ["La mer de Chine méridionale", "La mer d'Oman, au nord-ouest de l'Inde", "La mer Rouge, entre Afrique et Arabie", "La mer de Barents, en Arctique"], 0,
     "Six États y revendiquent tout ou partie des Spratleys et des Paracels, riches en ressources et stratégiques."],
    ["Qu'est-ce que le statut d'un État non reconnu ?", ["Un territoire disposant d'un pouvoir effectif sans reconnaissance internationale large", "Un territoire sous mandat confié par une organisation internationale", "Une région autonome au sein d'un État reconnu", "Un protectorat placé sous la tutelle d'une puissance étrangère"], 0,
     "Chypre du Nord, la Transnistrie et le Somaliland en sont des exemples."],
    ["Quelle zone démilitarisée sépare deux États depuis 1953 ?", ["Celle entre les deux Corées", "Celle entre l'Inde et le Pakistan depuis 1947", "Celle entre Israël et le Liban, le long de la ligne bleue", "Celle entre les zones nord et sud de Chypre"], 0,
     "Quatre kilomètres de large sur deux cent quarante-huit de long, l'une des frontières les plus militarisées du monde."],
    ["Qui exerce la souveraineté sur l'Antarctique ?", ["Personne : le traité de 1959 gèle les revendications", "L'ONU, qui l'administre directement depuis 1959", "Sept États s'en partagent effectivement la souveraineté", "Le Chili et l'Argentine, conjointement"], 0,
     "Le traité y interdit toute activité militaire et réserve le continent à la recherche scientifique."],
    ["Qu'est-ce qu'un couloir territorial ?", ["Une bande de territoire donnant accès à la mer ou reliant deux parties d'un État", "Une zone de libre circulation entre deux pays voisins", "Un corridor humanitaire ouvert en temps de guerre", "Une voie ferrée internationale traversant plusieurs États"], 0,
     "Le couloir de Dantzig, entre les deux guerres, en est l'exemple historique le plus connu.", 3],
  ]),

  notion("geo2-tourisme-mondial", S, "Géographie du tourisme",
    "Flux, destinations, effets : où vont les touristes et ce que cela produit.",
    "Le tourisme international reste très concentré : une poignée de pays capte la majorité des flux.",
    2, [
    ["Quelle région du monde reçoit le plus de touristes internationaux ?", ["L'Europe", "L'Asie et le Pacifique réunis", "L'Amérique du Nord, Mexique compris", "Le Moyen-Orient et le golfe Persique"], 0,
     "Elle capte environ la moitié des arrivées mondiales, favorisée par la proximité des pays émetteurs."],
    ["Qu'est-ce qu'un tourisme balnéaire ?", ["Un tourisme centré sur les littoraux et la baignade", "Un tourisme de croisière le long des côtes chaudes", "Un tourisme thermal dans les stations de cure", "Un tourisme insulaire limité aux seuls archipels tropicaux"], 0,
     "C'est la première forme de tourisme en volume, très saisonnière et concentrée sur d'étroites bandes côtières."],
    ["Qu'est-ce que la capacité de charge touristique d'un site ?", ["Le nombre de visiteurs qu'il peut accueillir sans dégradation", "Le nombre de lits disponibles dans les hébergements des alentours", "La fréquentation annuelle la plus élevée jamais observée", "Le seuil de rentabilité de son exploitation"], 0,
     "Elle combine des limites physiques, écologiques et sociales, parfois difficiles à chiffrer."],
    ["Quel musée est le plus visité au monde ?", ["Le Louvre", "Le British Museum, à Londres", "Le Metropolitan Museum, à New York", "Les musées du Vatican, à Rome"], 0,
     "Environ neuf millions de visiteurs par an. Les classements de sites, eux, varient selon qu'on compte les entrées payantes ou toutes les visites."],
    ["Quel effet économique le tourisme produit-il localement ?", ["Des emplois souvent saisonniers et une hausse des prix immobiliers", "Une industrialisation durable du territoire", "Une baisse générale du coût de la vie sur place", "Une stabilité de l'emploi tout au long de l'année"], 0,
     "La dépendance à une seule activité rend les territoires vulnérables aux crises."],
    ["Qu'est-ce que le tourisme de croisière ?", ["Un tourisme itinérant à bord de navires faisant escale", "Un tourisme de plaisance individuelle sur voilier privé", "Un tourisme exclusivement fluvial, sur les grands fleuves", "Un tourisme de simple traversée maritime"], 0,
     "Les escales génèrent des retombées limitées au regard du nombre de visiteurs déversés en quelques heures."],
    ["Quelle ville a instauré un droit d'entrée pour les visiteurs à la journée ?", ["Venise", "Barcelone, en Catalogne", "Amsterdam, aux Pays-Bas", "Dubrovnik, sur l'Adriatique"], 0,
     "Expérimenté à partir de 2024 pour réguler l'afflux dans le centre historique."],
    ["Qu'est-ce que le tourisme mémoriel ?", ["La visite de lieux liés à des événements historiques douloureux", "La visite des monuments du patrimoine ancien et des châteaux forts", "La visite des lieux saints et des grands pèlerinages", "La participation aux commémorations nationales"], 0,
     "Plages du Débarquement, camps de concentration, champs de bataille : il pose des questions éthiques spécifiques."],
    ["Quel effet le tourisme a-t-il sur le logement dans les villes très visitées ?", ["Il réduit l'offre de logements permanents au profit des locations courtes", "Il fait baisser les loyers en augmentant l'offre de logements disponibles", "Il n'a aucun effet mesurable sur le marché du logement dans les grandes villes", "Il augmente la construction de logements sociaux en centre-ville"], 0,
     "Plusieurs villes ont plafonné le nombre de nuitées annuelles autorisées par logement."],
    ["Quelle part des émissions mondiales de gaz à effet de serre le tourisme représente-t-il ?", ["Environ huit pour cent", "Environ un pour cent seulement", "Environ vingt pour cent du total", "Environ trente pour cent du total"], 0,
     "Le transport, et particulièrement l'aérien, en constitue la part dominante.", 3],
  ]),

  notion("geo2-risques-naturels", S, "Les risques naturels",
    "Aléa, vulnérabilité, prévention : ce qui transforme un phénomène en catastrophe.",
    "Un risque est le croisement d'un aléa et d'une population exposée : sans enjeu, pas de risque.",
    2, [
    ["Qu'est-ce qu'un risque naturel ?", ["Le croisement d'un aléa et d'enjeux exposés", "Un phénomène naturel d'une violence exceptionnelle", "Une catastrophe déjà survenue et officiellement recensée", "Une zone géographique réputée dangereuse"], 0,
     "Un séisme en plein désert est un aléa, pas un risque : il n'y a rien à endommager."],
    ["Que mesure l'échelle de Richter ?", ["L'énergie libérée par un séisme", "Les dégâts observés sur le terrain", "La profondeur du foyer sismique", "La durée totale des secousses ressenties"], 0,
     "L'échelle de Mercalli, elle, mesure les effets ressentis et les dégâts."],
    ["Qu'est-ce qu'un tsunami ?", ["Une série de vagues provoquée par un déplacement brutal d'eau", "Une marée d'amplitude exceptionnelle", "Une vague de tempête poussée par le vent", "Un raz de marée d'origine cyclonique"], 0,
     "Il se déplace à plusieurs centaines de kilomètres par heure en haute mer sans être perceptible."],
    ["Quel tsunami majeur frappe l'océan Indien en 2004 ?", ["Celui de Sumatra", "Celui de Tohoku, au Japon, en 2011", "Celui du Chili, en 1960", "Celui de Lisbonne, en 1755"], 0,
     "Plus de deux cent vingt mille morts. Aucun système d'alerte n'existait alors dans cet océan."],
    ["Qu'est-ce qu'une nuée ardente ?", ["Un écoulement de gaz et de cendres brûlants dévalant un volcan", "Une coulée de lave particulièrement rapide et fluide", "Un nuage de vapeur d'eau échappé du cratère juste avant l'éruption", "Une pluie de cendres retombant loin du volcan"], 0,
     "Elle peut dépasser plusieurs centaines de kilomètres par heure et des centaines de degrés."],
    ["Qu'est-ce qu'un cyclone tropical ?", ["Une dépression très creuse formée sur des eaux chaudes", "Une tempête de latitude moyenne née sur un front froid", "Un orage violent isolé de fin d'après-midi", "Un vent de mousson saisonnier venu de l'océan Indien réchauffé"], 0,
     "Appelé ouragan dans l'Atlantique, typhon dans le Pacifique nord-ouest."],
    ["Quelle température de surface de la mer est nécessaire à la formation d'un cyclone ?", ["Environ vingt-six degrés sur une épaisseur suffisante", "Environ vingt degrés en surface seulement", "Environ trente-cinq degrés en surface", "Aucune condition de température particulière n'est requise"], 0,
     "Le réchauffement des océans étend les zones et les saisons propices à leur formation."],
    ["Qu'est-ce qu'une crue centennale ?", ["Une crue ayant une chance sur cent de survenir chaque année", "Une crue qui revient exactement tous les cent ans, comme une horloge", "La plus forte crue jamais enregistrée au cours du siècle écoulé", "Une crue documentée depuis un siècle"], 0,
     "Deux crues centennales peuvent survenir à deux ans d'intervalle sans que la définition soit fausse."],
    ["Qu'est-ce qu'un plan de prévention des risques en France ?", ["Un document réglementant l'usage des sols dans les zones exposées", "Un plan de secours communal déclenché en cas d'alerte", "Un plan d'évacuation des populations menacées", "Un schéma d'alerte à l'échelle du département"], 0,
     "Il peut interdire de construire ou imposer des prescriptions techniques, et s'impose aux documents d'urbanisme."],
    ["Pourquoi les catastrophes font-elles plus de victimes dans les pays pauvres ?", ["La vulnérabilité y est plus forte : bâti fragile, alerte et secours limités", "Les aléas naturels y sont systématiquement plus intenses qu'ailleurs dans le monde", "La densité de population y est toujours plus forte", "Les phénomènes naturels y sont moins prévisibles"], 0,
     "Un séisme d'ampleur comparable peut faire mille fois plus de victimes selon le pays touché.", 3],
  ]),

  notion("geo2-biomes", S, "Les grands milieux naturels",
    "Forêts, savanes, steppes, toundras : la végétation à l'échelle planétaire.",
    "La répartition des grands biomes suit d'abord le climat, ensuite les sols et le relief.",
    2, [
    ["Qu'est-ce qu'un biome ?", ["Un grand ensemble écologique défini par son climat et sa végétation", "Une circonscription administrative créée pour la protection de la nature", "Un écosystème local limité à quelques hectares", "Une zone de biodiversité protégée par une convention internationale récente"], 0,
     "Forêt tropicale, savane, désert, forêt tempérée, taïga et toundra en sont les principaux."],
    ["Quelle forêt couvre les hautes latitudes de l'hémisphère nord ?", ["La taïga", "La toundra, au-delà du cercle polaire", "La forêt tempérée de feuillus", "La forêt équatoriale, près de l'équateur"], 0,
     "Dominée par les conifères, c'est le plus vaste biome forestier de la planète."],
    ["Qu'est-ce que la toundra ?", ["Une formation basse de mousses et d'arbustes sur sol gelé", "Une prairie d'altitude pâturée pendant le court été", "Une steppe froide parsemée de bouleaux nains et de saules rampants", "Une lande atlantique battue par les vents"], 0,
     "Le permafrost empêche les racines profondes et donc les arbres."],
    ["Qu'est-ce que la savane ?", ["Une formation herbacée parsemée d'arbres, sous climat à saison sèche", "Une prairie tempérée pâturée toute l'année", "Une steppe aride sans arbre ni buisson", "Une forêt claire méditerranéenne de chênes-lièges"], 0,
     "Le feu y joue un rôle écologique essentiel dans le maintien du milieu ouvert."],
    ["Quelle forêt tropicale est la plus étendue du monde ?", ["L'Amazonie", "Le bassin du Congo, en Afrique centrale", "La forêt indonésienne de Bornéo et Sumatra", "La forêt du bassin du Mékong"], 0,
     "Elle abrite une part considérable des espèces terrestres connues."],
    ["Qu'est-ce que la mangrove ?", ["Une forêt littorale tropicale adaptée à l'eau salée", "Une forêt marécageuse d'eau douce des plaines tropicales", "Une forêt d'altitude tropicale enveloppée de brouillard", "Une formation d'algues brunes côtières"], 0,
     "Elle protège les côtes de l'érosion et sert de nurserie à de nombreuses espèces marines."],
    ["Qu'est-ce que la garrigue ?", ["Une formation méditerranéenne basse sur sol calcaire", "Une lande atlantique d'ajoncs et de bruyères", "Une steppe aride des plateaux intérieurs", "Une forêt dense de chênes verts et de chênes-lièges du Midi"], 0,
     "Le maquis lui correspond sur sol siliceux, avec une végétation plus dense et plus haute."],
    ["Qu'est-ce qu'un récif corallien ?", ["Une structure calcaire construite par des animaux en symbiose avec des algues", "Une formation rocheuse sous-marine sculptée par les courants", "Un banc de sable colonisé par des herbiers marins", "Un dépôt de coquillages accumulés au fil des siècles"], 0,
     "Le blanchissement survient quand la chaleur pousse le corail à expulser ses algues symbiotiques."],
    ["Qu'est-ce qu'une zone humide ?", ["Un milieu saturé d'eau au moins une partie de l'année", "Un lac permanent alimenté toute l'année par une rivière", "Une zone inondable déjà urbanisée sur les bords d'un fleuve", "Un delta fluvial ramifié à l'embouchure d'un grand fleuve"], 0,
     "Marais, tourbières et prairies inondables filtrent l'eau, stockent le carbone et écrêtent les crues."],
    ["Qu'est-ce qu'un point chaud de biodiversité ?", ["Une région à forte richesse endémique et fortement menacée", "Une zone protégée par une convention internationale contraignante", "Une région tropicale humide très arrosée", "Un parc national de très grande superficie"], 0,
     "Une trentaine ont été identifiés ; ils couvrent une faible part des terres émergées mais abritent une part majeure des espèces.", 3],
  ]),

  notion("geo2-europe-geographie", S, "La géographie de l'Europe",
    "Un continent morcelé, fortement littoral, densément peuplé et très urbanisé.",
    "Aucun point de l'Europe de l'Ouest n'est très éloigné de la mer : c'est une clé de son histoire.",
    2, [
    ["Quel pays européen a la plus grande superficie hors Russie ?", ["L'Ukraine", "La France, hors outre-mer", "L'Espagne, dans la péninsule Ibérique", "La Suède, en Scandinavie"], 0,
     "Environ six cent mille kilomètres carrés. La France est la plus vaste de l'Union européenne."],
    ["Quel massif sépare la France de l'Italie ?", ["Les Alpes", "Les Pyrénées", "Les Apennins", "Le Jura"], 0,
     "Le tunnel du Mont-Blanc et celui du Fréjus en assurent la traversée routière."],
    ["Quelle chaîne parcourt l'Italie du nord au sud ?", ["Les Apennins", "Les Alpes dinariques", "Les Carpates", "Les Balkans"], 0,
     "Elle explique le contraste entre plaines littorales et intérieur montagneux du pays."],
    ["Quelle mer sépare la Suède du Danemark et de l'Allemagne ?", ["La mer Baltique", "La mer du Nord", "La mer de Norvège", "Le Skagerrak seul"], 0,
     "Peu salée et peu profonde, elle gèle partiellement chaque hiver dans sa partie nord."],
    ["Quel pays européen compte le plus d'habitants ?", ["L'Allemagne", "La France, deuxième par la population", "L'Italie, en Europe du Sud", "L'Espagne, à l'ouest du continent"], 0,
     "Environ quatre-vingt-trois millions, hors Russie."],
    ["Qu'est-ce que la dorsale européenne ?", ["Un axe fortement urbanisé et industrialisé de Londres à Milan", "La chaîne alpine qui traverse le continent d'ouest en est", "La ligne de partage des eaux du continent", "Le seul axe rhénan, de Bâle à Rotterdam"], 0,
     "Longtemps appelée banane bleue, l'expression est aujourd'hui jugée trop simplificatrice par les géographes."],
    ["Quel pays européen de taille significative a la plus forte densité de population ?", ["Les Pays-Bas", "La France et ses régions les plus denses", "L'Espagne, très urbanisée sur ses côtes", "La Pologne, au centre du continent"], 0,
     "Monaco et Malte ont des densités bien supérieures, mais sur de très petits territoires — la comparaison n'a de sens qu'entre pays de taille comparable."],
    ["Quel fleuve traverse quatre capitales européennes ?", ["Le Danube", "Le Rhin", "L'Elbe", "La Vistule"], 0,
     "Vienne, Bratislava, Budapest et Belgrade."],
    ["Quel pays européen est traversé par le cercle polaire arctique ?", ["La Finlande", "L'Estonie, sur la Baltique", "Le Danemark, au sud de la Scandinavie", "L'Irlande, à l'ouest de l'Europe"], 0,
     "La Suède et la Norvège également. Le soleil de minuit y est visible en été."],
    ["Qu'est-ce que le polder ?", ["Une terre gagnée sur la mer et protégée par des digues", "Une plaine alluviale déposée par un fleuve au fil des siècles", "Un marais littoral asséché naturellement par le jeu des marées", "Une île artificielle construite au large d'un port"], 0,
     "Les Pays-Bas en ont fait un art : une part importante du pays se situe sous le niveau de la mer.", 3],
  ]),

  notion("geo2-asie-geographie", S, "La géographie de l'Asie",
    "Le plus vaste et le plus peuplé des continents, aux contrastes extrêmes.",
    "L'Asie réunit à la fois le point le plus haut et le point émergé le plus bas de la planète.",
    2, [
    ["Quel plateau est surnommé le toit du monde ?", ["Le plateau tibétain", "Le plateau iranien", "Le plateau du Deccan", "Le plateau de Mongolie"], 0,
     "Environ quatre mille cinq cents mètres d'altitude moyenne. Il alimente les plus grands fleuves d'Asie."],
    ["Quel désert couvre une grande partie de la Mongolie et du nord de la Chine ?", ["Le Gobi", "Le Taklamakan", "Le Karakoum", "Le Thar"], 0,
     "Désert froid, il connaît des hivers rigoureux, contrairement à l'image du désert de sable chaud."],
    ["Quelle mer intérieure prolonge vers le sud la limite conventionnelle entre l'Europe et l'Asie ?", ["La mer Caspienne", "La mer d'Aral", "La mer Noire", "La mer de Marmara"], 0,
     "La plus grande étendue d'eau fermée du monde, riche en hydrocarbures."],
    ["Quel pays asiatique est composé de plus de dix-sept mille îles ?", ["L'Indonésie", "Les Philippines", "Le Japon", "La Malaisie"], 0,
     "Le plus grand État archipel du monde, quatrième pays le plus peuplé."],
    ["Quel détroit sépare la Corée du Japon ?", ["Le détroit de Corée", "Le détroit de Tsugaru", "Le détroit de Formose", "Le détroit de Malacca"], 0,
     "Environ deux cents kilomètres de large, partagés par l'île de Tsushima en deux passes d'une cinquantaine et d'une soixantaine de kilomètres."],
    ["Quelle région d'Asie centrale a subi un désastre écologique lié à l'irrigation ?", ["Le bassin de la mer d'Aral", "La vallée du Ferghana", "Le désert du Karakoum", "Le plateau kazakh"], 0,
     "Détournement du Syr-Daria et de l'Amou-Daria pour la culture du coton depuis les années 1960."],
    ["Quel pays asiatique est enclavé entre la Chine et l'Inde dans l'Himalaya ?", ["Le Népal", "Le Bangladesh", "Le Sri Lanka", "La Birmanie"], 0,
     "Le Bhoutan est dans une situation comparable, également sans accès à la mer."],
    ["Quelle mégalopole s'étend le long de la côte pacifique du Japon ?", ["La mégalopole de Tokaido", "La mégalopole du Kansai seule", "La conurbation de Hokkaido", "La zone de Kyushu"], 0,
     "Le Tokaido proprement dit relie Tokyo à Osaka ; prolongé jusqu'à Fukuoka par la ceinture du Taiheiyō, l'ensemble concentre la majorité de la population et de l'activité du pays."],
    ["Parmi les pays asiatiques les plus peuplés, lequel connaît la plus forte croissance démographique récente ?", ["Le Pakistan", "Le Japon", "La Corée du Sud", "La Thaïlande"], 0,
     "Le Japon et la Corée du Sud connaissent au contraire un déclin démographique marqué."],
    ["Qu'est-ce que la ligne de mousson en Asie du Sud ?", ["La limite atteinte par les pluies de mousson, très variable d'une année à l'autre", "La frontière climatique entre Inde et Chine", "La limite des cyclones", "La ligne de partage des eaux himalayenne"], 0,
     "Un retard ou une faiblesse de la mousson peut compromettre les récoltes de tout un sous-continent.", 3],
  ]),

  notion("geo2-afrique-geographie", S, "La géographie de l'Afrique",
    "Un continent massif, jeune démographiquement, aux ressources considérables.",
    "L'Afrique est trois fois plus vaste que l'Europe, ce que les cartes usuelles masquent.",
    2, [
    ["Quel désert est le plus vaste désert chaud du monde ?", ["Le Sahara", "Le Kalahari", "Le Namib", "Le désert de Libye seul"], 0,
     "Plus de neuf millions de kilomètres carrés, comparable à la superficie des États-Unis."],
    ["Quelle bande semi-aride borde le Sahara au sud ?", ["Le Sahel", "Le Soudan", "Le Kalahari", "La corne de l'Afrique"], 0,
     "Zone de transition très vulnérable à la variabilité des pluies et à la pression sur les sols."],
    ["Quelle vallée traverse l'Afrique de l'Est du nord au sud ?", ["Le grand rift", "La vallée du Nil seule", "Le fossé du Zambèze", "La dépression de l'Afar"], 0,
     "Une déchirure de la croûte terrestre longue de plusieurs milliers de kilomètres, qui pourrait un jour séparer un bloc du continent."],
    ["Quel lac africain est le plus vaste en superficie ?", ["Le lac Victoria", "Le lac Tanganyika", "Le lac Malawi", "Le lac Tchad"], 0,
     "Le Tanganyika est en revanche bien plus profond et contient beaucoup plus d'eau."],
    ["Quel lac africain a perdu la majeure partie de sa surface depuis les années 1960 ?", ["Le lac Tchad", "Le lac Victoria", "Le lac Turkana", "Le lac Albert"], 0,
     "Sécheresses, prélèvements pour l'irrigation et croissance démographique se conjuguent."],
    ["Quel fleuve africain forme une grande boucle avant de rejoindre l'Atlantique ?", ["Le Niger", "Le Congo", "Le Sénégal", "Le Zambèze"], 0,
     "Il coule d'abord vers le nord-est, contourne le Sahara méridional, puis redescend vers le sud."],
    ["Quelle est la ville la plus peuplée d'Afrique ?", ["Le Caire ou Lagos selon les définitions", "Kinshasa", "Johannesburg", "Nairobi"], 0,
     "Les estimations varient fortement selon le périmètre retenu pour l'agglomération."],
    ["Quel pays africain a la plus forte population ?", ["Le Nigeria", "L'Éthiopie", "L'Égypte", "La République démocratique du Congo"], 0,
     "Plus de deux cents millions d'habitants, avec une croissance parmi les plus rapides du monde."],
    ["Quelle particularité climatique caractérise la corne de l'Afrique ?", ["Une aridité marquée malgré une position équatoriale", "Un climat équatorial humide", "Un climat méditerranéen", "Un climat de mousson régulier"], 0,
     "La configuration des vents et le relief y limitent fortement les précipitations."],
    ["Qu'est-ce que la grande muraille verte africaine ?", ["Un projet de restauration des terres à travers le Sahel", "Une barrière contre les migrations", "Une forêt protégée transfrontalière", "Un corridor de faune sauvage"], 0,
     "Lancé en 2007, il vise moins un rideau d'arbres continu qu'une mosaïque de pratiques agricoles restauratrices.", 3],
  ]),

  notion("geo2-ameriques-geographie", S, "La géographie des Amériques",
    "Deux sous-continents reliés par un isthme, du cercle polaire au cap Horn.",
    "Le continent américain s'étend sur plus de quinze mille kilomètres du nord au sud.",
    2, [
    ["Quelle chaîne parcourt l'ouest de l'Amérique du Nord ?", ["Les montagnes Rocheuses", "Les Appalaches", "La Sierra Nevada seule", "La chaîne côtière"], 0,
     "Les Appalaches, à l'est, sont un massif ancien bien plus usé."],
    ["Quel est le plus long fleuve d'Amérique du Nord ?", ["Le système Mississippi-Missouri", "Le Saint-Laurent", "Le Colorado", "Le Rio Grande"], 0,
     "Son bassin draine une grande partie du centre des États-Unis."],
    ["Quels lacs forment la plus grande réserve d'eau douce de surface d'Amérique du Nord ?", ["Les Grands Lacs", "Le lac Winnipeg et ses voisins", "Les lacs de l'Ontario seuls", "Le Grand Lac de l'Ours"], 0,
     "Cinq lacs reliés, partagés entre le Canada et les États-Unis, débouchant sur le Saint-Laurent."],
    ["Quelle plaine céréalière traverse le centre des États-Unis ?", ["Les Grandes Plaines", "La vallée centrale de Californie", "La plaine côtière du Golfe", "Le bassin de l'Ohio"], 0,
     "L'épisode du Dust Bowl dans les années 1930 y a montré la fragilité de ces sols labourés."],
    ["Quel isthme relie l'Amérique du Nord à l'Amérique du Sud ?", ["L'isthme de Panama", "L'isthme de Tehuantepec", "La péninsule du Yucatán", "L'isthme du Costa Rica"], 0,
     "Sa fermeture il y a environ trois millions d'années a modifié les courants océaniques mondiaux."],
    ["Quel désert d'Amérique du Sud est le plus aride du monde ?", ["L'Atacama", "Le Patagonique", "Le Sechura", "Le désert de Monte"], 0,
     "Certaines stations n'y ont jamais enregistré de pluie mesurable."],
    ["Quel plateau occupe une grande partie du Brésil ?", ["Le plateau brésilien", "Le bouclier guyanais seul", "Le plateau patagonien", "Le Gran Chaco"], 0,
     "Vieux socle érodé, il porte les principales villes et une grande partie de l'agriculture du pays."],
    ["Quelle plaine argentine est le cœur agricole du pays ?", ["La pampa", "Le Chaco", "La Patagonie", "La Mésopotamie argentine"], 0,
     "Sols profonds et climat tempéré en font l'une des zones agricoles les plus productives du monde."],
    ["Quel détroit sépare l'Amérique du Sud de la Terre de Feu ?", ["Le détroit de Magellan", "Le passage de Drake", "Le canal de Beagle", "Le détroit de Le Maire"], 0,
     "Le passage de Drake, plus au sud, sépare l'Amérique du Sud de l'Antarctique."],
    ["Qu'est-ce que l'Amazonie légale au Brésil ?", ["Un périmètre administratif couvrant plus de la moitié du territoire brésilien", "La zone strictement protégée de la forêt", "Le bassin hydrographique de l'Amazone", "La zone d'exploitation autorisée"], 0,
     "Il sert de cadre à la politique de développement et de surveillance de la déforestation.", 3],
  ]),

  notion("geo2-oceanie-poles", S, "Océanie et zones polaires",
    "Îles du Pacifique, Australie, Arctique et Antarctique : les marges du peuplement.",
    "L'Arctique est un océan entouré de continents, l'Antarctique un continent entouré d'océans.",
    2, [
    ["Pourquoi l'Antarctique est-il nettement plus froid que l'Arctique ?", ["Parce que c'est un continent élevé et isolé, non un océan", "Parce qu'il est plus proche du pôle Sud céleste", "Parce que l'ozone y est plus mince toute l'année", "Parce que les vents y soufflent en permanence du continent vers la mer"], 0,
     "L'Arctique est un océan gelé entouré de terres ; l'Antarctique, un continent culminant à plus de trois mille mètres et entouré d'océans, dont l'altitude et l'isolement expliquent des températures bien plus basses."],
    ["Quelle part des glaces mondiales l'Antarctique contient-il ?", ["Environ quatre-vingt-dix pour cent", "Environ la moitié du total mondial", "Environ un tiers des glaces du globe", "Environ vingt pour cent des glaces mondiales"], 0,
     "Sa fonte complète élèverait le niveau des mers de plusieurs dizaines de mètres."],
    ["Quel peuple autochtone habite l'Arctique nord-américain ?", ["Les Inuits", "Les Samis, en Laponie", "Les Nenets, en Sibérie", "Les Aléoutes, et eux seuls"], 0,
     "Les Samis vivent en Scandinavie, les Nenets en Sibérie."],
    ["Qu'est-ce que le passage du Nord-Ouest ?", ["Une route maritime arctique entre Atlantique et Pacifique", "Un détroit séparant l'Alaska de l'extrême-orient russe", "Un canal artificiel creusé dans le Grand Nord canadien pour les navires", "Une route terrestre traversant toute la Sibérie du nord"], 0,
     "Longtemps impraticable, il s'ouvre certains étés du fait du recul de la banquise."],
    ["Quel est le plus grand pays d'Océanie ?", ["L'Australie", "La Papouasie-Nouvelle-Guinée", "La Nouvelle-Zélande et ses deux îles", "Les Îles Salomon, en Mélanésie"], 0,
     "À la fois le plus vaste, le plus peuplé et le plus riche de la région."],
    ["Quelle formation corallienne longe la côte nord-est de l'Australie ?", ["La Grande Barrière de corail", "Le récif de Ningaloo, sur la côte ouest", "L'atoll de Tuvalu", "Le récif de Nouvelle-Calédonie, en Mélanésie"], 0,
     "Plus de deux mille kilomètres. Elle a subi plusieurs épisodes de blanchissement massif depuis 1998."],
    ["Comment appelle-t-on les trois grands ensembles culturels du Pacifique ?", ["Mélanésie, Micronésie et Polynésie", "Australasie, Insulinde et Océanie lointaine", "Pacifique nord, Pacifique centre et Pacifique sud", "Nouvelle-Guinée, Fidji et Samoa"], 0,
     "Ce découpage du XIXe siècle est aujourd'hui discuté, mais reste d'usage courant."],
    ["Quel État insulaire du Pacifique est particulièrement menacé par la montée des eaux ?", ["Tuvalu", "Fidji, en Mélanésie", "Les Samoa, en Polynésie", "Vanuatu, dans le Pacifique sud"], 0,
     "Son point culminant ne dépasse pas cinq mètres. Il a engagé une réflexion sur sa survie juridique en tant qu'État."],
    ["Qu'est-ce qu'un atoll ?", ["Un anneau corallien entourant un lagon", "Une île volcanique récente", "Un récif frangeant collé à la côte", "Un banc de sable stabilisé"], 0,
     "Darwin en a proposé le premier une explication : le volcan s'enfonce, le corail continue de croître vers la surface."],
    ["Quel peuple autochtone habite l'Australie depuis au moins cinquante mille ans, et jusqu'à soixante-cinq mille selon certaines datations ?", ["Les Aborigènes", "Les Maoris, en Nouvelle-Zélande", "Les Papous, en Nouvelle-Guinée", "Les Polynésiens du Pacifique central"], 0,
     "La fourchette haute vient des datations du site de Madjedbebe, publiées en 2017. Les Maoris ont peuplé la Nouvelle-Zélande bien plus tard, vers le XIIIe siècle.", 3],
  ]),

  notion("geo2-cartographie", S, "Cartographie et représentation du monde",
    "Projections, échelles, systèmes de coordonnées : toute carte est un choix.",
    "Aucune projection ne conserve tout : il faut toujours sacrifier au moins une propriété, et savoir laquelle.",
    2, [
    ["Pourquoi aucune carte plane ne peut-elle être exacte ?", ["On ne peut aplatir une sphère sans déformation", "Les instruments de mesure demeurent trop imprécis", "La Terre change sans cesse de forme", "Les projections cartographiques sont toutes arbitraires"], 0,
     "Il faut choisir ce que l'on conserve : les angles, les surfaces ou certaines distances."],
    ["Quel territoire la projection de Mercator agrandit-elle le plus spectaculairement ?", ["Le Groenland", "L'Australie, dans l'hémisphère sud", "L'Inde, en Asie du Sud", "Le Brésil, à cheval sur l'équateur"], 0,
     "Il y paraît aussi vaste que l'Afrique, alors qu'il en fait environ le quatorzième."],
    ["Que conserve une projection équivalente ?", ["Les rapports de surface", "Les angles", "Les distances au point central", "La forme des littoraux"], 0,
     "La projection de Peters, très discutée, en est un exemple, au prix d'une déformation des formes."],
    ["Jusqu'à quelle valeur la latitude peut-elle monter vers chaque pôle ?", ["Quatre-vingt-dix degrés", "Cent quatre-vingts degrés", "Trois cent soixante degrés", "Soixante degrés"], 0,
     "Un degré de latitude correspond partout à environ cent onze kilomètres, ce qui n'est pas le cas de la longitude."],
    ["Où passe le méridien de référence international ?", ["Par Greenwich", "Par Paris", "Par Washington", "Par Rome"], 0,
     "Fixé lors d'une conférence internationale en 1884. La France a conservé son propre méridien jusqu'en 1911."],
    ["Qu'exprime l'échelle d'une carte ?", ["Le rapport entre une distance sur la carte et la distance réelle", "La précision des mesures reportées sur la carte", "La taille réelle du territoire représenté sur la feuille", "Le niveau de détail des noms de lieux portés sur la carte"], 0,
     "Une grande échelle correspond à un petit territoire très détaillé, contrairement à l'intuition."],
    ["Qu'est-ce qu'une courbe de niveau ?", ["Une ligne joignant les points de même altitude", "Une limite entre deux classes de pente sur la carte", "Un axe de vallée suivant le fond du talweg", "Une ligne de crête reliant entre eux les sommets voisins"], 0,
     "Leur resserrement traduit une pente forte, leur écartement une pente douce."],
    ["Qu'est-ce qu'un système d'information géographique ?", ["Un outil de gestion et d'analyse de données localisées", "Un logiciel de dessin cartographique assisté par ordinateur", "Une base de données rassemblant des cartes anciennes numérisées", "Un service de géolocalisation en temps réel"], 0,
     "Il superpose des couches d'information pour croiser des données spatiales."],
    ["Comment le GPS détermine-t-il une position ?", ["Par mesure du temps de trajet des signaux de plusieurs satellites", "Par triangulation à partir d'antennes relais terrestres", "Par mesure du champ magnétique terrestre local", "Par comparaison automatique avec des images satellite du sol"], 0,
     "Quatre satellites au minimum sont nécessaires pour obtenir position et altitude."],
    ["Qu'est-ce que le système européen de positionnement par satellite ?", ["Galileo", "Glonass, le système russe", "Beidou, le système chinois", "IRNSS, le système indien"], 0,
     "Opérationnel depuis 2016, il vise l'indépendance vis-à-vis du GPS américain.", 3],
  ]),
];
