/**
 * Géographie — treize notions sans cours.
 *
 * Le cahier traite les continents et les grands thèmes. Ces notions-ci
 * descendent à l'échelle du détroit, du fleuve, de la frontière ou de la
 * capitale : ce qu'on cherche vraiment quand on ouvre un atlas.
 */
import { notion, type Q } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Géographie";

export const CG_GEOGRAPHIE: SeedSkill[] = [
  notion("geo-detroits", S, "Les détroits et les canaux stratégiques",
    "Quelques kilomètres d'eau par où passe l'essentiel du commerce mondial, et que tout conflit régional menace aussitôt.",
    "Un détroit est naturel, un canal est creusé. Les deux créent la même dépendance.",
    2, [
    ["Quel détroit sépare l'Europe de l'Afrique ?", ["Le détroit de Gibraltar", "Le détroit du Bosphore", "Le détroit de Messine", "Le détroit d'Otrante"], 0,
     "Quatorze kilomètres au plus étroit. Il commande l'unique passage naturel entre la Méditerranée et l'Atlantique."],
    ["Quel détroit relie la mer Noire à la mer de Marmara ?", ["Le Bosphore", "Les Dardanelles", "Le détroit de Kertch", "Le canal de Corinthe"], 0,
     "Il traverse Istanbul. Avec les Dardanelles, il forme les Détroits turcs, régis par la convention de Montreux de 1936."],
    ["Par quel détroit passe un cinquième du pétrole mondial ?", ["Le détroit d'Ormuz", "Le détroit de Malacca", "Le canal de Suez", "Le détroit de Bab el-Mandeb"], 0,
     "Il relie le golfe Persique au golfe d'Oman. Sa fermeture est régulièrement brandie comme moyen de pression."],
    ["Quel détroit relie l'océan Indien à la mer de Chine méridionale ?", ["Le détroit de Malacca", "Le détroit de la Sonde", "Le détroit de Lombok", "Le détroit de Formose"], 0,
     "Long de huit cents kilomètres, il est l'un des plus fréquentés du monde et un point noir pour la piraterie."],
    ["Quel détroit sépare l'Asie de l'Amérique ?", ["Le détroit de Béring", "Le détroit de Davis", "Le détroit d'Hudson", "Le passage de Drake"], 0,
     "Quatre-vingt-deux kilomètres séparent la Russie de l'Alaska. Deux îles s'y font face de part et d'autre de la ligne de changement de date."],
    ["Quel détroit sépare l'Amérique du Sud de l'Antarctique ?", ["Le passage de Drake", "Le détroit de Magellan", "Le canal de Beagle", "Le détroit de Bransfield"], 0,
     "Neuf cents kilomètres de mer parmi les plus agitées du globe, sans aucune terre pour freiner les vents d'ouest."],
    ["Quel détroit sépare la France de l'Angleterre ?", ["Le pas de Calais", "Le détroit de Douvres seul", "La mer d'Irlande", "Le Solent"], 0,
     "Trente-quatre kilomètres. Le tunnel sous la Manche, ouvert en 1994, le franchit sur cinquante kilomètres dont trente-huit sous la mer."],
    ["Pourquoi le canal de Panama a-t-il des écluses ?", ["Le lac Gatún est à vingt-six mètres au-dessus du niveau des mers", "Les deux océans n'ont pas la même salinité", "Pour ralentir les navires", "Pour retenir les sédiments"], 0,
     "Les navires sont hissés jusqu'au lac artificiel, puis redescendus de l'autre côté. Le trajet dure une dizaine d'heures."],
    ["Quel détroit sépare l'Espagne du Maroc au niveau de Ceuta ?", ["Le détroit de Gibraltar", "Le détroit d'Alboran", "Le détroit de Tarifa", "Le détroit de Cadix"], 0,
     "Ceuta et Melilla sont deux villes espagnoles situées sur le continent africain, seules frontières terrestres de l'Union européenne avec l'Afrique.", 3],
  ]),

  notion("geo-capitales-monde", S, "Capitales : les cas qui surprennent",
    "Capitales déplacées, pays à plusieurs capitales, capitales qui ne sont pas la plus grande ville : les exceptions sont nombreuses.",
    "Beaucoup de capitales ont été choisies pour arbitrer entre deux villes rivales, ou pour déplacer le centre de gravité d'un pays.",
    2, [
    ["Pourquoi Canberra a-t-elle été bâtie de toutes pièces ?", ["Pour trancher la rivalité entre Sydney et Melbourne", "Pour rapprocher le pouvoir des mines", "Pour fuir le climat côtier", "Pour honorer un explorateur"], 0,
     "Le site fut choisi en 1908, à mi-chemin des deux rivales, et la ville inaugurée en 1927."],
    ["Qui a désigné Ottawa comme capitale du Canada en 1857 ?", ["La reine Victoria", "Le Parlement de Toronto", "Le gouverneur général", "Un référendum"], 0,
     "Le choix arbitre entre Canada anglophone et francophone, et éloigne la capitale de la frontière américaine."],
    ["Pourquoi le Brésil a-t-il déplacé sa capitale en 1960 ?", ["Pour tirer le peuplement vers l'intérieur du pays", "Parce que Rio était trop exposée aux tempêtes", "Pour se rapprocher de l'Amazonie", "Par manque de place à São Paulo"], 0,
     "Brasília sort de terre en quarante et un mois, au milieu du plateau central, sur un plan en forme d'avion."],
    ["Combien de capitales l'Afrique du Sud compte-t-elle ?", ["Trois", "Une", "Deux", "Quatre"], 0,
     "Pretoria est administrative, Le Cap législative, Bloemfontein judiciaire. C'est un cas unique au monde."],
    ["Quelle est la capitale de la Bolivie ?", ["Sucre est la capitale constitutionnelle", "La Paz uniquement", "Santa Cruz", "Cochabamba"], 0,
     "Le gouvernement siège à La Paz, à trois mille six cents mètres, mais la constitution désigne Sucre."],
    ["Pourquoi Atatürk a-t-il préféré Ankara à Istanbul en 1923 ?", ["Elle est au centre de l'Anatolie, loin des côtes et des puissances étrangères", "Elle était déjà la plus peuplée", "Elle abritait le palais impérial", "Elle était mieux reliée par le rail"], 0,
     "Istanbul, occupée après 1918 et trop marquée par l'Empire ottoman, ne pouvait incarner la république nouvelle."],
    ["Quelle est la capitale du Myanmar depuis 2006 ?", ["Naypyidaw", "Rangoun", "Mandalay", "Bago"], 0,
     "Bâtie ex nihilo et inaugurée en 2006, elle est restée très peu peuplée par rapport à sa superficie."],
    ["Quelle est la capitale du Nigeria ?", ["Abuja", "Lagos", "Kano", "Ibadan"], 0,
     "Construite au centre du pays et devenue capitale en 1991, pour équilibrer les régions et désengorger Lagos."],
    ["Quelle est la capitale des Pays-Bas ?", ["Amsterdam, mais le gouvernement siège à La Haye", "La Haye", "Rotterdam", "Utrecht"], 0,
     "La constitution désigne Amsterdam, où a lieu l'intronisation du souverain, mais les institutions siègent à La Haye."],
    ["Quelle est la capitale du Kazakhstan ?", ["Astana", "Almaty", "Chymkent", "Karaganda"], 0,
     "Transférée depuis Almaty en 1997, elle a changé plusieurs fois de nom, portant même celui du président de 2019 à 2022.", 3],
  ]),

  notion("geo-frontieres", S, "Les frontières et les enclaves",
    "Frontières tracées à la règle, enclaves oubliées, pays enfermés dans un autre : la carte politique est pleine de curiosités logiques.",
    "Une enclave est entourée par un seul pays ; un pays sans littoral est enclavé au sens large.",
    2, [
    ["Quels pays sont entièrement enclavés dans un seul autre État ?", ["Saint-Marin, le Vatican et le Lesotho", "Le Luxembourg et Andorre", "Monaco et le Liechtenstein", "La Suisse et le Népal"], 0,
     "Saint-Marin et le Vatican sont entourés par l'Italie, le Lesotho par l'Afrique du Sud."],
    ["Quels pays sont doublement enclavés, c'est-à-dire entourés de pays eux-mêmes sans littoral ?", ["L'Ouzbékistan et le Liechtenstein", "La Mongolie et le Népal", "La Bolivie et le Paraguay", "L'Autriche et la Hongrie"], 0,
     "Ce sont les deux seuls cas au monde. Il faut traverser au moins deux frontières pour atteindre la mer."],
    ["Quelle est la plus longue frontière terrestre du monde ?", ["Entre le Canada et les États-Unis", "Entre la Russie et la Chine", "Entre l'Argentine et le Chili", "Entre l'Inde et la Chine"], 0,
     "Environ huit mille huit cent quatre-vingt-onze kilomètres, Alaska compris. Une grande partie suit le 49e parallèle."],
    ["Quel pays a le plus de voisins terrestres ?", ["La Chine et la Russie, à égalité avec quatorze", "Le Brésil", "L'Allemagne", "L'Inde"], 0,
     "Le Brésil en compte dix, l'Allemagne neuf. La France, avec ses outre-mer, en compte onze."],
    ["Quel pays est enclavé dans deux États seulement, sans littoral, en Europe occidentale ?", ["Andorre", "Le Luxembourg", "Monaco", "Le Liechtenstein"], 0,
     "Située entre la France et l'Espagne, elle est dirigée par deux coprinces : le président français et l'évêque d'Urgell."],
    ["Quelle enclave russe est séparée du reste du pays ?", ["Kaliningrad", "La Crimée", "Sakhaline", "L'Adyguée"], 0,
     "Coincée entre la Pologne et la Lituanie, elle est devenue une exclave lors de la dissolution de l'URSS."],
    ["Quelle frontière est la plus militarisée du monde ?", ["Celle entre les deux Corées", "Celle entre l'Inde et le Pakistan", "Celle entre Israël et le Liban", "Celle entre les deux Chypres"], 0,
     "La zone démilitarisée, large de quatre kilomètres, sépare les deux États depuis l'armistice de 1953."],
    ["Que trace la ligne Durand ?", ["La frontière entre l'Afghanistan et le Pakistan", "La frontière entre l'Inde et la Chine", "La limite du Sahara occidental", "La frontière irano-irakienne"], 0,
     "Tracée en 1893 par les Britanniques, elle coupe le territoire pachtoune et n'a jamais été reconnue par Kaboul."],
    ["Quel pays africain a une frontière parfaitement rectiligne sur la majeure partie de son tracé ?", ["L'Égypte", "Le Nigeria", "L'Afrique du Sud", "Le Kenya"], 0,
     "Les frontières égyptiennes avec la Libye et le Soudan suivent des méridiens et parallèles, héritage du découpage colonial."],
    ["Qu'est-ce que la bande de Caprivi ?", ["Un couloir namibien vers le Zambèze", "Une région du Sahara occidental", "Une enclave angolaise", "Une frontière contestée au Tchad"], 0,
     "Ce corridor de quatre cent cinquante kilomètres a été obtenu par l'Allemagne en 1890 pour atteindre le fleuve Zambèze.", 3],
  ]),

  notion("geo-fleuves-monde", S, "Les grands fleuves et leurs bassins",
    "Longueur, débit, bassin versant : trois classements différents, et trois vainqueurs différents.",
    "L'Amazone gagne au débit et au bassin, le Nil ou l'Amazone à la longueur selon la source retenue.",
    2, [
    ["Quel fleuve traverse le plus de pays ?", ["Le Danube", "Le Nil", "Le Rhin", "Le Mékong"], 0,
     "Il en arrose dix, de l'Allemagne à l'Ukraine, et quatre capitales : Vienne, Bratislava, Budapest et Belgrade."],
    ["Où le Nil prend-il sa source la plus lointaine ?", ["Au Burundi ou au Rwanda, selon les sources", "Au lac Victoria", "En Éthiopie", "Au Soudan"], 0,
     "Le Nil Blanc vient de la région des Grands Lacs, le Nil Bleu du lac Tana en Éthiopie. Ils se rejoignent à Khartoum."],
    ["Quel fleuve se jette dans la mer Caspienne ?", ["La Volga", "Le Don", "Le Dniepr", "L'Oural seul"], 0,
     "Plus long fleuve d'Europe avec trois mille cinq cent trente kilomètres, il n'atteint aucun océan."],
    ["Quel fleuve arrose Bagdad ?", ["Le Tigre", "L'Euphrate", "Le Chatt-el-Arab", "Le Karoun"], 0,
     "Le Tigre et l'Euphrate se rejoignent en aval pour former le Chatt-el-Arab, qui se jette dans le golfe Persique."],
    ["Quel fleuve traverse la Chine du sud et se jette près de Shanghai ?", ["Le Yangzi Jiang", "Le fleuve Jaune", "Le Xi Jiang", "L'Amour"], 0,
     "Long de six mille trois cents kilomètres, c'est le troisième du monde. Le barrage des Trois-Gorges le barre depuis 2006."],
    ["Quel fleuve d'Afrique de l'Ouest décrit une grande boucle vers le Sahara ?", ["Le Niger", "Le Sénégal", "La Volta", "Le Congo"], 0,
     "Il naît à deux cent cinquante kilomètres de l'Atlantique, remonte vers le nord, puis redescend vers le golfe de Guinée."],
    ["Quel fleuve traverse deux fois l'équateur ?", ["Le Congo", "L'Amazone", "Le Nil", "Le Zambèze"], 0,
     "Cette particularité lui assure un débit régulier toute l'année : une partie de son bassin est toujours en saison des pluies."],
    ["Quel fleuve européen relie la mer du Nord aux Alpes ?", ["Le Rhin", "L'Elbe", "La Meuse", "Le Rhône"], 0,
     "Axe économique majeur, il est bordé par la plus grande concentration industrielle d'Europe et débouche à Rotterdam."],
    ["Quel fleuve américain se jette dans le golfe du Mexique après avoir drainé le centre du pays ?", ["Le Mississippi", "Le Colorado", "Le Rio Grande", "L'Ohio"], 0,
     "Son bassin couvre quarante et un pour cent du territoire des États-Unis contigus.", 3],
  ]),

  notion("geo-iles", S, "Les îles et les archipels",
    "La plus grande, la plus peuplée, la plus isolée : les records insulaires disent beaucoup sur le peuplement et les climats.",
    "Une île continentale s'est détachée d'un continent ; une île volcanique est sortie de la mer.",
    2, [
    ["Quelle est la plus grande île du monde ?", ["Le Groenland", "La Nouvelle-Guinée", "Bornéo", "Madagascar"], 0,
     "Plus de deux millions de kilomètres carrés. L'Australie n'est pas comptée : sa taille en fait un continent."],
    ["Quelle est la deuxième plus grande île du monde ?", ["La Nouvelle-Guinée", "Bornéo", "Madagascar", "Sumatra"], 0,
     "Partagée entre l'Indonésie et la Papouasie-Nouvelle-Guinée, elle abrite plus de huit cents langues."],
    ["Quelle est l'île la plus peuplée du monde ?", ["Java", "Honshu", "Grande-Bretagne", "Luçon"], 0,
     "Plus de cent cinquante millions d'habitants sur une superficie comparable à celle de la Grèce."],
    ["Quel archipel est le plus isolé du monde habité en permanence ?", ["Tristan da Cunha", "Les Kerguelen", "L'île de Pâques", "Sainte-Hélène"], 0,
     "À deux mille quatre cents kilomètres de Sainte-Hélène, la terre habitée la plus proche. Environ deux cent cinquante habitants."],
    ["Quel pays compte le plus d'îles ?", ["La Suède", "L'Indonésie", "Les Philippines", "Le Canada"], 0,
     "Plus de deux cent vingt mille selon les relevés récents, la plupart minuscules. L'Indonésie en compte environ dix-sept mille."],
    ["Quelle île est partagée entre Haïti et la République dominicaine ?", ["Hispaniola", "La Jamaïque", "Porto Rico", "Cuba"], 0,
     "Deuxième île des Antilles par la taille. La frontière suit approximativement un partage entre colonies française et espagnole."],
    ["Quelle île volcanique est apparue au large de l'Islande en 1963 ?", ["Surtsey", "Heimaey", "Jan Mayen", "Grimsey"], 0,
     "Sortie de la mer sous les yeux des observateurs, elle est classée réserve intégrale pour étudier la colonisation par le vivant."],
    ["Quel type d'île se forme autour d'un volcan effondré, en anneau de corail ?", ["Un atoll", "Un récif-barrière", "Un archipel volcanique", "Une île continentale"], 0,
     "Darwin a le premier expliqué leur formation : le corail continue de croître pendant que le socle volcanique s'enfonce."],
    ["Quel archipel a inspiré la théorie de l'évolution à Darwin ?", ["Les Galápagos", "Les Canaries", "Le Cap-Vert", "Les Malouines"], 0,
     "Il y observe en 1835 des pinsons dont le bec varie d'une île à l'autre selon la nourriture disponible."],
    ["Quelle île française de l'océan Indien abrite un volcan très actif ?", ["La Réunion", "Mayotte", "Les Kerguelen", "Tromelin"], 0,
     "Le piton de la Fournaise entre en éruption plusieurs fois par an, sans danger majeur pour les habitants.", 3],
  ]),

  notion("geo-climats-extremes", S, "Records et extrêmes de la planète",
    "Le plus chaud, le plus sec, le plus profond, le plus haut : des chiffres qui donnent l'échelle du monde physique.",
    "Attention aux records officiels, souvent contestés faute de stations de mesure dans les lieux les plus extrêmes.",
    2, [
    ["Où a été relevée la température la plus élevée officiellement reconnue ?", ["À Furnace Creek, dans la Vallée de la Mort", "À El Azizia, en Libye", "À Death Valley au Nevada", "Au Koweït"], 0,
     "56,7 °C en 1913. Le record libyen de 1922 a été invalidé en 2012 par l'Organisation météorologique mondiale."],
    ["Où a été relevée la température la plus basse à la surface du globe ?", ["À la station Vostok, en Antarctique", "À Oïmiakon, en Sibérie", "Au pôle Nord", "Au Groenland"], 0,
     "Moins 89,2 °C en 1983. Oïmiakon détient le record des lieux habités en permanence, avec moins 67,7 °C."],
    ["Quel est l'endroit habité le plus sec du monde ?", ["Le désert d'Atacama", "Le Sahara central", "La vallée de la Mort", "Le désert de Gobi"], 0,
     "Certaines stations n'y ont jamais enregistré de pluie. Sa sécheresse tient à un courant froid et à une double barrière montagneuse."],
    ["Quel est le point le plus profond des océans ?", ["La fosse des Mariannes", "La fosse des Tonga", "La fosse du Japon", "La fosse de Porto Rico"], 0,
     "Environ onze mille mètres au fond du Challenger Deep, soit plus que l'Everest en hauteur."],
    ["Quel est le point émergé le plus bas du monde ?", ["Les rives de la mer Morte", "La dépression de Danakil", "La vallée de la Mort", "La dépression du Qattara"], 0,
     "Environ quatre cent trente mètres sous le niveau de la mer, et le niveau baisse encore d'un mètre par an."],
    ["Quelle chute d'eau africaine porte le nom local de « fumée qui gronde » ?", ["Les chutes Victoria", "Les chutes Tugela", "Les chutes de Kalandula", "Les chutes de Boyoma"], 0,
     "Mosi-oa-Tunya en langue lozi. Larges de mille sept cents mètres sur le Zambèze, elles séparent la Zambie du Zimbabwe."],
    ["Quelle part de l'eau douce de surface du globe le lac Baïkal contient-il ?", ["Environ un cinquième", "Environ un centième", "Environ la moitié", "Environ un tiers"], 0,
     "Ses mille six cent quarante-deux mètres de profondeur en font aussi le lac le plus profond du monde."],
    ["Pourquoi le statut juridique de la mer Caspienne a-t-il été discuté trente ans ?", ["Mer ou lac, le partage des ressources n'obéit pas aux mêmes règles", "Deux États se disputaient sa rive nord", "Son niveau variait trop pour tracer des frontières", "Aucun traité n'existait avant 1991"], 0,
     "Un lac se partage entre riverains, une mer relève du droit maritime. La convention d'Aktaou de 2018 a tranché par un compromis."],
    ["Quel endroit reçoit les précipitations les plus abondantes du monde ?", ["Mawsynram, en Inde", "L'Amazonie centrale", "Le Cameroun côtier", "La Colombie pacifique"], 0,
     "Près de douze mètres d'eau par an, apportés par la mousson bloquée contre le relief."],
    ["Quel désert est le plus vaste du monde ?", ["L'Antarctique", "Le Sahara", "Le désert d'Arabie", "Le Gobi"], 0,
     "Un désert se définit par la faiblesse des précipitations, pas par la chaleur. L'Antarctique en est le plus grand.", 3],
  ]),

  notion("geo-villes-monde", S, "Les grandes villes du monde",
    "Mégapoles, capitales économiques, villes nouvelles : où vivent les habitants de la planète, et comment cela change vite.",
    "Depuis 2007, plus de la moitié de l'humanité vit en ville. La croissance urbaine est aujourd'hui surtout africaine et asiatique.",
    2, [
    ["Quelle est la plus grande agglomération du monde ?", ["Tokyo", "Delhi", "Shanghai", "New York"], 0,
     "Environ trente-sept millions d'habitants dans l'aire métropolitaine, malgré une population japonaise en baisse."],
    ["Quelle ville africaine est la plus peuplée ?", ["Lagos", "Le Caire", "Kinshasa", "Johannesburg"], 0,
     "Les estimations varient de quinze à vingt-cinq millions selon le périmètre retenu, faute de recensement récent fiable."],
    ["Quelle est la ville la plus haute du monde parmi les grandes capitales ?", ["La Paz", "Quito", "Bogota", "Lhassa"], 0,
     "Le siège du gouvernement bolivien se situe entre trois mille deux cents et quatre mille mètres selon les quartiers."],
    ["Quelle ville s'étend sur deux continents ?", ["Istanbul", "Le Caire", "Suez", "Athènes"], 0,
     "Le Bosphore la coupe en deux. Trois ponts et un tunnel ferroviaire sous-marin relient les rives."],
    ["Quelle ville a été bâtie sur un ancien lac asséché ?", ["Mexico", "Venise", "Amsterdam", "La Nouvelle-Orléans"], 0,
     "Bâtie sur le lac Texcoco, elle s'enfonce de plusieurs centimètres par an, ce qui fragilise ses monuments."],
    ["Quelle ville européenne compte le plus d'habitants intra-muros ?", ["Moscou", "Londres", "Paris", "Berlin"], 0,
     "Plus de douze millions d'habitants. Londres arrive ensuite avec environ neuf millions."],
    ["Quelle ville-État d'Asie du Sud-Est est aussi un pays ?", ["Singapour", "Hong Kong", "Macao", "Brunei"], 0,
     "Indépendante depuis 1965, elle a gagné du terrain sur la mer et occupe aujourd'hui un quart de plus qu'à sa fondation."],
    ["Quelle ville sainte est interdite aux non-musulmans ?", ["La Mecque", "Jérusalem", "Médine seule", "Kairouan"], 0,
     "La Mecque et Médine sont toutes deux fermées, mais La Mecque l'est le plus strictement, y compris à ses abords."],
    ["Quelle ville est le siège de plusieurs institutions internationales sans être capitale ?", ["Genève", "Bruxelles", "Vienne", "Lyon"], 0,
     "Elle abrite l'OMS, l'OMC, le Haut-Commissariat aux réfugiés et le siège européen de l'ONU."],
    ["Quelle ville nouvelle chinoise illustre l'urbanisation ultra-rapide du pays ?", ["Shenzhen", "Pékin", "Nankin", "Xi'an"], 0,
     "Village de pêcheurs de trente mille habitants en 1980, elle en compte plus de dix-sept millions aujourd'hui.", 3],
  ]),

  notion("geo-ressources", S, "Les ressources et leur géographie",
    "Pétrole, gaz, métaux rares, eau douce : où elles se trouvent, et pourquoi cela dessine la géopolitique.",
    "La rente minière ne fait pas la prospérité : c'est ce qu'on appelle la malédiction des ressources.",
    2, [
    ["Quel pays détient les plus grandes réserves prouvées de pétrole ?", ["Le Venezuela", "L'Arabie Saoudite", "Le Canada", "L'Iran"], 0,
     "Ses réserves d'huile extra-lourde de l'Orénoque dépassent celles de l'Arabie Saoudite, mais leur exploitation coûte cher."],
    ["Quel pays produit le plus de pétrole aujourd'hui ?", ["Les États-Unis", "L'Arabie Saoudite", "La Russie", "L'Irak"], 0,
     "La révolution du pétrole de schiste a fait des États-Unis le premier producteur mondial depuis les années 2010."],
    ["Quel pays domine la production de terres rares ?", ["La Chine", "Les États-Unis", "L'Australie", "Le Brésil"], 0,
     "Elle assure environ soixante à soixante-dix pour cent de l'extraction et une part encore plus forte du raffinage."],
    ["Quel pays produit le plus de cobalt ?", ["La République démocratique du Congo", "La Zambie", "L'Australie", "Le Canada"], 0,
     "Environ soixante-dix pour cent de la production mondiale, essentiel aux batteries lithium-ion."],
    ["Quel pays est le premier producteur mondial de lithium ?", ["L'Australie", "Le Chili", "La Bolivie", "L'Argentine"], 0,
     "L'Australie l'extrait de roches dures, tandis que le triangle du lithium sud-américain l'obtient par évaporation de saumures."],
    ["Quel pays possède les plus grandes réserves de gaz naturel ?", ["La Russie", "l'Iran", "le Qatar", "les États-Unis"], 0,
     "Russie, Iran et Qatar concentrent à eux trois plus de la moitié des réserves prouvées."],
    ["Quelle part de l'eau terrestre est de l'eau douce accessible ?", ["Moins de un pour cent", "Environ dix pour cent", "Environ trois pour cent", "Environ vingt pour cent"], 0,
     "L'eau douce représente environ deux et demi pour cent du total, mais l'essentiel est pris dans les glaces et les nappes profondes."],
    ["Quel bassin fluvial fait l'objet d'un contentieux entre l'Éthiopie et l'Égypte ?", ["Le Nil", "Le Niger", "Le Zambèze", "Le Congo"], 0,
     "Le barrage de la Renaissance, sur le Nil Bleu, inquiète l'Égypte, dont l'agriculture dépend entièrement du fleuve."],
    ["Qu'appelle-t-on malédiction des ressources ?", ["Le fait qu'une richesse minière freine souvent le développement", "L'épuisement rapide des gisements", "La pollution des sites miniers", "La dépendance aux importations"], 0,
     "La rente décourage les autres secteurs, gonfle la monnaie et alimente la corruption et les conflits."],
    ["Quel pays exporte le plus de blé au monde ces dernières années ?", ["La Russie", "Les États-Unis", "La France", "Le Canada"], 0,
     "Elle est devenue le premier exportateur mondial dans les années 2010. La France reste le premier exportateur européen.", 3],
  ]),

  notion("geo-france-regions", S, "Les régions françaises et leurs traits",
    "Treize régions métropolitaines depuis 2016, cinq départements d'outre-mer, et des identités bien plus anciennes que le découpage.",
    "La réforme de 2016 fait passer de vingt-deux à treize régions métropolitaines, par fusion et non par redécoupage.",
    1, [
    ["Combien de régions compte la France métropolitaine depuis 2016 ?", ["Treize", "Vingt-deux", "Dix-huit", "Douze"], 0,
     "La loi de 2015 fusionne plusieurs régions à partir du 1er janvier 2016. La Corse a un statut particulier de collectivité unique."],
    ["Quelle région française est la plus vaste en métropole ?", ["La Nouvelle-Aquitaine", "L'Occitanie", "Auvergne-Rhône-Alpes", "Le Grand Est"], 0,
     "Environ quatre-vingt-quatre mille kilomètres carrés, soit plus que l'Autriche."],
    ["Quel est le chef-lieu de la région Grand Est ?", ["Strasbourg", "Nancy", "Reims", "Metz"], 0,
     "La région réunit l'Alsace, la Lorraine et la Champagne-Ardenne. Strasbourg accueille aussi le Parlement européen."],
    ["Quel département français est le plus peuplé ?", ["Le Nord", "Paris", "Les Bouches-du-Rhône", "Le Rhône"], 0,
     "Environ deux millions six cent mille habitants. Paris intra-muros en compte un peu plus de deux millions."],
    ["Quel massif sépare la France de l'Espagne ?", ["Les Pyrénées", "Les Alpes", "Le Jura", "Les Cévennes"], 0,
     "Quatre cent trente kilomètres de frontière. Le point culminant français y est le Vignemale, à trois mille deux cent quatre-vingt-dix-huit mètres."],
    ["Quel est le plus long fleuve de France ?", ["La Loire", "La Seine", "Le Rhône", "La Garonne"], 0,
     "Mille six kilomètres. C'est aussi le fleuve européen le plus sauvage, très peu aménagé sur la majeure partie de son cours."],
    ["Quelle région française produit le plus de vin en volume ?", ["L'Occitanie", "La Nouvelle-Aquitaine", "La Bourgogne-Franche-Comté", "Le Grand Est"], 0,
     "L'ancien Languedoc-Roussillon en constitue le cœur. La Nouvelle-Aquitaine domine en valeur avec le bordelais."],
    ["Quelle collectivité française a un statut particulier depuis 2018 ?", ["La Corse, collectivité unique", "La Bretagne", "L'Alsace", "La Guyane"], 0,
     "La collectivité de Corse fusionne la région et les deux départements. La Guyane et la Martinique ont un statut voisin depuis 2015.", 3],
  ]),

  notion("geo-mers-oceans", S, "Les mers, les courants et les marées",
    "L'océan mondial est un système : courants de surface, circulation profonde, marées. Il gouverne le climat autant qu'il le subit.",
    "Le Gulf Stream fait partie d'une circulation thermohaline globale, parfois appelée le tapis roulant océanique.",
    2, [
    ["Quel courant chaud remonte l'Atlantique nord vers l'Europe ?", ["Le Gulf Stream", "Le courant de Humboldt", "Le courant de Benguela", "Le Kuroshio"], 0,
     "Il explique en partie la douceur des hivers ouest-européens, à latitude pourtant comparable à celle du Labrador."],
    ["Quel courant froid longe les côtes du Pérou et du Chili ?", ["Le courant de Humboldt", "Le courant des Canaries", "Le courant du Labrador", "Le courant de Californie"], 0,
     "Il remonte des eaux profondes riches en nutriments et fait de cette côte l'une des zones de pêche les plus productives du monde."],
    ["Qu'est-ce que le phénomène El Niño ?", ["Un réchauffement du Pacifique équatorial est", "Un refroidissement de l'Atlantique nord", "Un courant de mousson", "Un cyclone récurrent"], 0,
     "Il inverse les vents et les courants habituels, provoquant sécheresses en Australie et pluies en Amérique du Sud."],
    ["Quelle est la cause principale des marées ?", ["L'attraction de la Lune, et du Soleil dans une moindre mesure", "Les vents dominants", "La rotation de la Terre seule", "Les courants profonds"], 0,
     "La Lune compte pour environ deux tiers de l'effet, le Soleil pour un tiers. Leur alignement produit les grandes marées."],
    ["Où observe-t-on les plus fortes marées du monde ?", ["Dans la baie de Fundy, au Canada", "En baie du mont Saint-Michel", "Dans le golfe Persique", "En mer Baltique"], 0,
     "Jusqu'à seize mètres de marnage. Le mont Saint-Michel connaît les plus fortes marées d'Europe continentale, jusqu'à quatorze mètres."],
    ["Pourquoi la mer Méditerranée a-t-elle des marées très faibles ?", ["Elle est presque fermée et communique peu avec l'océan", "Sa salinité est trop élevée", "Elle est trop profonde", "Elle est trop au sud"], 0,
     "Le détroit de Gibraltar ne laisse pas passer assez d'eau pour qu'une onde de marée s'y développe. Le marnage y dépasse rarement quarante centimètres."],
    ["Quelle mer est la plus salée du monde ?", ["La mer Morte", "La mer Rouge", "La Méditerranée", "La mer d'Aral"], 0,
     "Environ trois cents grammes de sel par litre, dix fois la moyenne océanique. Aucun poisson n'y vit."],
    ["Quelle mer intérieure a presque disparu depuis les années 1960 ?", ["La mer d'Aral", "La mer Caspienne", "Le lac Tchad seul", "La mer de Marmara"], 0,
     "Le détournement de ses deux fleuves affluents pour irriguer le coton l'a réduite à une fraction de sa surface."],
    ["Qu'appelle-t-on zone morte océanique ?", ["Une zone privée d'oxygène où la vie animale disparaît", "Une fosse trop profonde pour la vie", "Une région sans courant", "Une zone couverte de plastique"], 0,
     "L'excès de nutriments agricoles provoque des proliférations d'algues dont la décomposition consomme tout l'oxygène."],
    ["Quel océan est le plus petit et le moins profond ?", ["L'océan Arctique", "L'océan Indien", "L'océan Austral", "L'Atlantique nord"], 0,
     "Environ quatorze millions de kilomètres carrés, en grande partie recouverts de banquise dont l'étendue estivale diminue.", 3],
  ]),

  notion("geo-population", S, "Population, migrations et démographie",
    "Huit milliards d'humains, une croissance qui ralentit, un vieillissement inégal et des migrations qui ne sont pas celles qu'on croit.",
    "L'essentiel des migrations internationales est régional : la majorité des migrants restent dans leur zone d'origine.",
    2, [
    ["Quand la population mondiale a-t-elle atteint huit milliards ?", ["En 2022", "En 2015", "En 2019", "En 2025"], 0,
     "L'ONU a retenu symboliquement le 15 novembre 2022. Le passage de sept à huit milliards a pris douze ans."],
    ["Quel pays est aujourd'hui le plus peuplé du monde ?", ["L'Inde", "La Chine", "Les États-Unis", "l'Indonésie"], 0,
     "L'Inde a dépassé la Chine en 2023, cette dernière ayant vu sa population commencer à décliner."],
    ["Qu'appelle-t-on transition démographique ?", ["Le passage d'une forte natalité et mortalité à de faibles taux", "Le vieillissement de la population", "L'exode rural", "La baisse de l'espérance de vie"], 0,
     "La mortalité baisse d'abord, puis la natalité : c'est le décalage entre les deux qui produit la poussée démographique."],
    ["Quel continent connaîtra la plus forte croissance démographique d'ici 2050 ?", ["L'Afrique", "L'Asie", "L'Amérique latine", "l'Océanie"], 0,
     "Sa population pourrait doubler d'ici le milieu du siècle, avec le Nigeria parmi les pays les plus peuplés du monde."],
    ["Quel indicateur mesure le nombre moyen d'enfants par femme ?", ["L'indice de fécondité", "Le taux de natalité", "Le taux d'accroissement", "L'indice de dépendance"], 0,
     "Le seuil de renouvellement des générations est d'environ deux virgule un enfants par femme dans les pays à faible mortalité."],
    ["Quel pays a la population la plus âgée du monde ?", ["Le Japon", "l'Italie", "l'Allemagne", "la Corée du Sud"], 0,
     "Près de trente pour cent de sa population a plus de soixante-cinq ans. L'Italie suit de près."],
    ["Où réside la majorité des migrants internationaux ?", ["Dans une région proche de leur pays d'origine", "En Europe occidentale", "En Amérique du Nord", "Dans les pays du Golfe"], 0,
     "La migration lointaine est minoritaire. Les déplacements internes à un pays sont encore plus nombreux."],
    ["Quel pays accueille le plus de réfugiés au monde ces dernières années ?", ["La Turquie", "l'Allemagne", "les États-Unis", "le Pakistan"], 0,
     "Elle héberge plusieurs millions de réfugiés, principalement syriens. Les pays voisins des crises accueillent l'essentiel des flux."],
    ["Qu'est-ce que la pyramide des âges ?", ["Une représentation graphique de la population par âge et par sexe", "Un classement des pays par âge médian", "Un indicateur de vieillissement", "Une projection démographique"], 0,
     "Sa forme raconte l'histoire d'un pays : les creux y marquent les guerres, les bosses les baby-booms."],
    ["Quel phénomène désigne le passage d'une population majoritairement rurale à urbaine ?", ["L'urbanisation", "La métropolisation", "L'exode rural seul", "La périurbanisation"], 0,
     "Le seuil de cinquante pour cent d'urbains a été franchi vers 2007 à l'échelle mondiale.", 3],
  ]),

  notion("geo-cartographie-outils", S, "Cartes, projections et repérage",
    "Toute carte ment : le problème n'est pas de l'éviter mais de savoir sur quoi elle ment, et pourquoi on l'a choisi.",
    "Une projection conserve soit les angles, soit les surfaces, jamais les deux : c'est un théorème, pas une limite technique.",
    2, [
    ["Que conserve la projection de Mercator ?", ["Les angles, donc les caps", "Les surfaces", "Les distances", "Les formes des continents"], 0,
     "Conçue en 1569 pour la navigation, elle permet de tracer un cap comme une droite. Elle exagère énormément les hautes latitudes."],
    ["Quel continent apparaît beaucoup trop grand sur une carte de Mercator ?", ["Le Groenland", "l'Afrique", "l'Inde", "le Brésil"], 0,
     "Il y semble aussi grand que l'Afrique, alors qu'il est environ quatorze fois plus petit."],
    ["Que conserve une projection équivalente comme celle de Peters ?", ["Les surfaces", "Les angles", "Les distances", "Les directions"], 0,
     "Elle rend justice aux surfaces tropicales mais déforme fortement les formes. Aucune projection ne conserve tout."],
    ["Qu'est-ce que la latitude ?", ["L'angle par rapport à l'équateur", "L'angle par rapport à Greenwich", "La distance au pôle Nord", "L'altitude au-dessus du niveau de la mer"], 0,
     "Elle va de zéro à l'équateur à quatre-vingt-dix degrés aux pôles. Un degré vaut environ cent onze kilomètres."],
    ["Où passe le méridien d'origine ?", ["À Greenwich", "À Paris", "À Ferro", "À Rome"], 0,
     "Adopté lors de la conférence de Washington en 1884. Le méridien de Paris resta pourtant en usage en France jusqu'en 1911."],
    ["Que représente l'échelle 1/25 000 sur une carte ?", ["Un centimètre sur la carte vaut deux cent cinquante mètres", "Un centimètre vaut vingt-cinq mètres", "Un centimètre vaut deux kilomètres et demi", "Un kilomètre est réduit à vingt-cinq centimètres"], 0,
     "C'est l'échelle des cartes de randonnée françaises. Plus le dénominateur est petit, plus la carte est détaillée."],
    ["Que relient les courbes de niveau sur une carte topographique ?", ["Des points de même altitude", "Des points de même température", "Des lignes de crête", "Les cours d'eau"], 0,
     "Plus elles sont resserrées, plus la pente est forte. Leur équidistance est indiquée en légende."],
    ["Quel système satellitaire américain permet le positionnement ?", ["Le GPS", "Galileo", "GLONASS", "Beidou"], 0,
     "Galileo est européen, GLONASS russe et Beidou chinois. Les récepteurs modernes utilisent souvent plusieurs constellations."],
    ["Qu'est-ce qu'un SIG ?", ["Un système d'information géographique", "Un satellite d'imagerie globale", "Un standard international de géodésie", "Un service d'information géologique"], 0,
     "Il superpose des couches de données localisées : relief, réseaux, population. C'est l'outil de base de l'aménagement."],
    ["Pourquoi les cartes anciennes placent-elles souvent l'est en haut ?", ["Elles étaient orientées vers Jérusalem ou le Levant", "Par convention chinoise", "Pour faciliter la navigation", "Par erreur de copie"], 0,
     "Le verbe orienter vient de là : tourner une carte vers l'orient. Le nord en haut ne s'impose qu'avec la boussole.", 3],
  ]),

  notion("geo-tourisme-patrimoine", S, "Patrimoine mondial et sites remarquables",
    "Une liste de l'UNESCO créée en 1972, plus de mille biens, et des critères qui font débat autant qu'ils protègent.",
    "Un bien peut être culturel, naturel ou mixte. L'inscription n'est pas un label touristique mais un engagement de protection.",
    1, [
    ["Quelle organisation gère la liste du patrimoine mondial ?", ["l'UNESCO", "l'ONU directement", "le Conseil de l'Europe", "l'ICOMOS"], 0,
     "La convention de 1972 crée la liste. L'ICOMOS et l'UICN instruisent les dossiers pour le comité."],
    ["Quel pays compte le plus de sites inscrits au patrimoine mondial ?", ["l'Italie", "la Chine", "l'Espagne", "la France"], 0,
     "Italie et Chine se disputent la première place, chacune avec une soixantaine de biens."],
    ["Quel site péruvien est inscrit depuis 1983 ?", ["Le Machu Picchu", "Les lignes de Nazca", "Chan Chan", "Cuzco seul"], 0,
     "Cité inca du XVe siècle, abandonnée puis révélée au monde en 1911. C'est un bien mixte, culturel et naturel."],
    ["Quel monument funéraire indien est inscrit au patrimoine mondial ?", ["Le Taj Mahal", "Le fort Rouge", "Le temple d'Or", "Les grottes d'Ajanta"], 0,
     "Bâti au XVIIe siècle par Shah Jahan pour son épouse. Il est menacé par la pollution atmosphérique de la région."],
    ["Quel site cambodgien est le plus vaste ensemble religieux du monde ?", ["Angkor", "Preah Vihear", "Sambor Prei Kuk", "Banteay Chhmar"], 0,
     "Capitale de l'empire khmer, elle couvre environ quatre cents kilomètres carrés avec ses temples et ses réseaux hydrauliques."],
    ["Quel site jordanien est taillé dans la roche rose ?", ["Pétra", "Jerash", "Umm er-Rasas", "Le wadi Rum"], 0,
     "Capitale nabatéenne, elle contrôlait les routes caravanières de l'encens. Le site fut redécouvert par les Européens en 1812."],
    ["Quel ensemble français est inscrit pour ses grottes ornées ?", ["La vallée de la Vézère", "Les gorges du Verdon", "Le massif de Fontainebleau", "Les calanques"], 0,
     "Elle regroupe Lascaux et une quinzaine d'autres grottes. Lascaux est fermée au public depuis 1963 pour préserver les peintures."],
    ["Quelle barrière de corail est inscrite au patrimoine mondial ?", ["La Grande Barrière de corail", "Le récif de Belize seul", "L'atoll d'Aldabra", "Le récif de Tubbataha"], 0,
     "Elle s'étend sur plus de deux mille kilomètres au large de l'Australie et subit des épisodes de blanchissement répétés."],
    ["Quel site égyptien a été déplacé pour échapper aux eaux d'un barrage ?", ["Les temples d'Abou Simbel", "Les pyramides de Gizeh", "Le temple de Karnak", "La vallée des Rois"], 0,
     "Découpés et remontés soixante mètres plus haut dans les années 1960, avant la mise en eau du lac Nasser. C'est cette campagne qui a inspiré la convention de 1972."],
    ["Que risque un site inscrit mal protégé ?", ["Le classement sur la liste du patrimoine en péril, voire le retrait", "Une amende internationale", "Une fermeture au public imposée", "Le transfert de sa gestion à l'UNESCO"], 0,
     "Le retrait est rare : Dresde l'a subi en 2009 après la construction d'un pont, Liverpool en 2021.", 3],
  ]),
];
