/**
 * Géographie, troisième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Géographie";

export const CG_GEOGRAPHIE_3: SeedSkill[] = [
  notion("geo3-regions-france", S, "Les régions françaises",
    "Découpage, identités, compétences.",
    "Le découpage régional français actuel date de 2016.",
    2, [
    ["Quelle région française est la plus peuplée ?", ["l'Île-de-France", "l'Auvergne-Rhône-Alpes", "Les Hauts-de-France", "l'Occitanie"], 0,
     "Environ douze millions d'habitants, soit près d'un Français sur cinq."],
    ["Quelle région française est issue de la fusion de trois anciennes régions en 2016 ?", ["La Nouvelle-Aquitaine", "La Bretagne", "La Normandie", "Les Pays de la Loire"], 0,
     "Aquitaine, Limousin et Poitou-Charentes. Le Grand Est et l'Occitanie ont aussi fusionné trois régions."],
    ["Quelle région française n'a pas été modifiée par la réforme de 2016 ?", ["La Bretagne", "La Normandie", "Le Grand Est", "L'Occitanie"], 0,
     "Corse, Île-de-France, Pays de la Loire et Provence-Alpes-Côte d'Azur non plus."],
    ["Quel statut particulier la Corse possède-t-elle ?", ["Celui de collectivité territoriale unique", "Celui de région ordinaire, sans particularité", "Celui de département d'outre-mer", "Celui d'un territoire autonome"], 0,
     "Elle exerce depuis 2018 les compétences de la région et des deux anciens départements."],
    ["Quelle est la principale compétence économique des régions françaises ?", ["Le développement économique et la formation professionnelle", "L'action sociale et l'aide aux personnes âgées", "La gestion des collèges et des transports scolaires", "L'urbanisme local et les permis de construire"], 0,
     "Elles élaborent aussi les schémas d'aménagement du territoire régional."],
    ["Quelle région française a la plus forte densité de population ?", ["L'Île-de-France", "Les Hauts-de-France", "Provence-Alpes-Côte d'Azur", "L'Alsace"], 0,
     "Plus de mille habitants au kilomètre carré, contre environ cent pour la moyenne nationale."],
    ["Quelle région française attire le plus de touristes étrangers ?", ["L'Île-de-France", "Provence-Alpes-Côte d'Azur", "L'Occitanie", "Auvergne-Rhône-Alpes"], 0,
     "Paris et Versailles y concentrent l'essentiel de la fréquentation internationale."],
    ["Quelle région française est la première pour la production agricole ?", ["La Nouvelle-Aquitaine", "La Bretagne", "Les Hauts-de-France", "Le Grand Est"], 0,
     "La Bretagne domine en revanche largement l'élevage porcin et avicole."],
    ["Qu'est-ce qu'un schéma régional d'aménagement ?", ["Un document fixant les orientations d'aménagement à l'échelle régionale", "Un plan local d'urbanisme opposable aux permis", "Un schéma de cohérence territoriale intercommunal", "Un plan de transports régional ferroviaire"], 0,
     "Il s'impose aux documents d'urbanisme locaux dans un rapport de compatibilité.", 3],
  ]),

  notion("geo3-departements-france", S, "Les départements français",
    "Création, numérotation, particularités.",
    "La numérotation des départements suit l'ordre alphabétique de leur nom d'origine.",
    2, [
    ["Combien de départements la France compte-t-elle ?", ["Cent un", "Quatre-vingt-quinze", "Quatre-vingt-seize", "Cent"], 0,
     "Quatre-vingt-seize en métropole et cinq outre-mer."],
    ["Pourquoi les départements sont-ils numérotés dans cet ordre ?", ["Par ordre alphabétique de leur nom d'origine", "Par ordre chronologique de création", "Par ordre décroissant de superficie", "Par ordre décroissant de population"], 0,
     "Les modifications ultérieures ont introduit des exceptions, comme la Savoie ou les départements d'Île-de-France."],
    ["Quel département porte le numéro un ?", ["l'Ain", "l'Aisne", "l'Allier", "Les Alpes-de-Haute-Provence"], 0,
     "L'ordre alphabétique initial explique cette place."],
    ["Combien d'habitants compte environ le département du Nord, le plus peuplé de France ?", ["Environ deux millions six cent mille", "Environ un million deux cent mille habitants", "Environ cinq millions deux cent mille", "Environ deux cent cinquante mille habitants"], 0,
     "Il doit sa densité à l'héritage industriel et minier de la région."],
    ["Quel département métropolitain est le plus vaste ?", ["La Gironde", "Les Landes", "La Dordogne", "Le Finistère"], 0,
     "Environ dix mille kilomètres carrés. La Guyane est de loin le plus vaste tous départements confondus."],
    ["Quand les départements d'Île-de-France actuels ont-ils été créés ?", ["En 1964, par division de la Seine et de la Seine-et-Oise", "En 1790, lors de la création des premiers départements français", "En 1968, après les élections municipales", "En 1982, avec les lois de décentralisation"], 0,
     "La réforme est entrée en application en 1968."],
    ["Quels départements ont été créés à partir de la Corse en 1976 ?", ["La Corse-du-Sud et la Haute-Corse", "La Corse et la Balagne", "Ajaccio et Bastia", "Le Cap Corse et la Plaine orientale"], 0,
     "Ils ont fusionné en 2018 dans la collectivité de Corse."],
    ["Quel département français est entièrement enclavé dans un autre ?", ["Aucun, mais le Vaucluse possède une enclave", "Le Territoire de Belfort, détaché du Haut-Rhin", "Le Val-de-Marne, entouré de trois départements", "La Haute-Corse, au nord de l'île"], 0,
     "Les communes de l'enclave des Papes appartiennent au Vaucluse mais sont entourées par la Drôme."],
    ["Quelle est la principale compétence des départements français ?", ["L'action sociale", "Le développement économique", "L'urbanisme", "Les transports régionaux"], 0,
     "Revenu de solidarité active, aide à l'enfance et autonomie représentent l'essentiel de leur budget."],
    ["Quel département a été créé en 2011 ?", ["Mayotte", "La Guyane", "Saint-Martin", "Saint-Barthélemy"], 0,
     "Après un référendum local, elle devient le cent unième département français.", 3],
  ]),

  notion("geo3-littoraux", S, "Les littoraux",
    "Formes, dynamiques, aménagement.",
    "Un littoral n'est jamais figé : il recule ou avance en permanence.",
    2, [
    ["Qu'est-ce qu'un littoral ?", ["La zone de contact entre la terre et la mer", "La ligne de rivage exactement tracée à marée haute", "La zone submersible lors des grandes tempêtes hivernales", "La bande côtière déjà urbanisée"], 0,
     "Sa largeur varie selon les critères retenus, physiques ou administratifs."],
    ["Qu'est-ce qu'une falaise vive ?", ["Une falaise activement érodée par la mer", "Une falaise de plus de cent mètres", "Une falaise taillée dans la craie", "Une falaise apparue depuis peu"], 0,
     "Les falaises normandes reculent en moyenne de plusieurs dizaines de centimètres par an."],
    ["Qu'est-ce qu'un cordon dunaire ?", ["Un ensemble de dunes protégeant l'arrière-pays", "Une plage de sable fin bordée de galets et de graviers", "Un banc de sable sous-marin mobile", "Une digue naturelle de galets roulés"], 0,
     "Sa végétation le stabilise ; son piétinement le fragilise durablement."],
    ["Qu'est-ce que la dérive littorale ?", ["Un transport de sédiments parallèle à la côte", "Un courant descendant vers le large après le déferlement", "Un mouvement des marées de vive-eau amplifié par le vent", "Un recul du trait de côte mesuré chaque décennie"], 0,
     "Les épis et les ports peuvent l'interrompre, provoquant une érosion en aval."],
    ["Qu'est-ce que le trait de côte ?", ["La limite entre la terre et la mer, mobile dans le temps", "La limite du domaine public maritime fixée par l'État", "La ligne des plus hautes eaux atteintes lors des marées d'équinoxe", "La limite de la zone constructible sur le rivage"], 0,
     "Son suivi est essentiel pour anticiper les risques de submersion et d'érosion."],
    ["Qu'est-ce que la loi Littoral de 1986 ?", ["Une loi encadrant l'urbanisation des communes côtières", "Une loi réformant la pêche artisanale et les quotas de captures", "Une loi réorganisant les ports maritimes de commerce français", "Une loi punissant les rejets d'hydrocarbures en mer par les navires"], 0,
     "Elle impose notamment une bande inconstructible de cent mètres hors des zones urbanisées."],
    ["Qu'est-ce que le Conservatoire du littoral ?", ["Un établissement public acquérant des terrains côtiers pour les protéger", "Un service de surveillance des côtes rattaché à la Marine", "Un organisme de gestion des ports de plaisance", "Une agence de l'eau chargée des bassins côtiers"], 0,
     "Créé en 1975, il protège aujourd'hui environ deux mille kilomètres de rivages, soit près d'un huitième du littoral métropolitain."],
    ["Qu'est-ce qu'un estuaire ?", ["Une embouchure élargie où la marée pénètre dans le fleuve", "Un delta ramifié en plusieurs bras déposant leurs alluvions", "Une baie fermée par un cordon de galets à son entrée", "Un bras de mer étroit s'enfonçant dans les terres glaciaires"], 0,
     "La Gironde, la Seine et la Loire en sont des exemples français."],
    ["Qu'est-ce qu'une lagune littorale ?", ["Une étendue d'eau séparée de la mer par un cordon", "Une baie profonde ouverte sur le large en permanence", "Un marais salant aménagé pour la récolte du sel", "Un estuaire fermé par un barrage anti-marée"], 0,
     "Les étangs languedociens en sont des exemples, riches en biodiversité."],
    ["Quel effet la montée du niveau marin a-t-elle sur les littoraux ?", ["Elle accélère l'érosion et la submersion des zones basses", "Elle stabilise les côtes en apportant des sédiments nouveaux", "Elle n'a pas d'effet mesurable sur les littoraux tempérés", "Elle avantage les deltas en y accélérant les dépôts fluviaux"], 0,
     "Certaines communes françaises ont déjà engagé des relocalisations de bâtiments.", 3],
  ]),

  notion("geo3-glaciers-cryosphere", S, "Glaciers et cryosphère",
    "Glaces continentales, banquise, permafrost.",
    "La fonte de la banquise ne fait pas monter le niveau de la mer, contrairement à celle des glaciers.",
    2, [
    ["Pourquoi la fonte de la banquise n'élève-t-elle pas le niveau de la mer ?", ["Elle flotte déjà et déplace son propre volume", "Elle se reconstitue intégralement chaque hiver austral", "Elle est trop peu épaisse pour peser sur le niveau marin", "Son eau est salée, donc plus dense"], 0,
     "Comme un glaçon dans un verre plein, sa fonte ne fait pas déborder le liquide."],
    ["Quelle calotte glaciaire est la plus vaste du monde ?", ["Celle de l'Antarctique", "Celle du Groenland, dans l'Arctique", "Celle de l'archipel arctique canadien", "Celle de l'Himalaya et du plateau tibétain"], 0,
     "Elle contient environ quatre-vingt-dix pour cent des glaces terrestres."],
    ["Qu'est-ce qu'un glacier de vallée ?", ["Un glacier s'écoulant dans une vallée depuis un cirque d'accumulation", "Un glacier de plateau recouvrant un relief entier", "Un glacier suspendu accroché à une paroi raide", "Un glacier rocheux mêlé de débris et de glace"], 0,
     "La mer de Glace, en France, en est l'exemple le plus connu."],
    ["Qu'est-ce que la ligne d'équilibre glaciaire ?", ["L'altitude où accumulation et fonte s'équilibrent", "La seule limite inférieure des neiges éternelles en été", "Le front du glacier, à son extrémité aval", "La limite amont de la zone crevassée"], 0,
     "Sa remontée en altitude traduit le recul général des glaciers."],
    ["Qu'est-ce qu'une moraine ?", ["Un dépôt de débris transportés par un glacier", "Une crevasse profonde ouverte dans la glace en mouvement", "Un lac glaciaire retenu par le front du glacier", "Une paroi rocheuse polie et striée par le passage de la glace"], 0,
     "Frontale, latérale ou de fond, elle témoigne de l'extension passée du glacier."],
    ["Qu'est-ce qu'un fjord ?", ["Une vallée glaciaire envahie par la mer", "Une baie profonde ouverte par un effondrement tectonique", "Un estuaire nordique soumis à de fortes marées", "Un canyon sous-marin creusé au large"], 0,
     "La Norvège, le Chili et la Nouvelle-Zélande en comptent parmi les plus spectaculaires."],
    ["Qu'est-ce qu'un lac glaciaire de surcreusement ?", ["Un lac occupant une cuvette creusée par un glacier", "Un lac retenu en amont par un barrage de moraine frontale", "Un lac de fonte estivale posé sur la glace", "Un lac de cirque perché en altitude"], 0,
     "Les Grands Lacs nord-américains et les lacs alpins en sont issus."],
    ["Quelle part des terres émergées de l'hémisphère nord le permafrost couvre-t-il ?", ["Environ un quart", "Environ un dixième des terres", "Environ la moitié des terres émergées", "Environ cinq pour cent seulement"], 0,
     "Sibérie, Alaska et nord du Canada en concentrent l'essentiel."],
    ["Quel risque le dégel du permafrost présente-t-il ?", ["La libération de méthane et la déstabilisation des infrastructures", "Une acidification durable des sols arctiques", "Une salinisation des eaux douces de surface", "Une érosion éolienne accélérée des sols nus"], 0,
     "Bâtiments, routes et pipelines reposent sur un sol qui perd sa portance."],
    ["Qu'est-ce que le recul général des glaciers de montagne implique ?", ["Une modification du régime des cours d'eau alimentés par la fonte", "Une hausse immédiate et brutale du niveau des mers sur tout le globe", "Un refroidissement local des vallées de haute montagne", "Une augmentation des précipitations neigeuses sur l'ensemble des massifs"], 0,
     "Des millions de personnes dépendent de cette eau de fonte en Asie et en Amérique du Sud.", 3],
  ]),

  notion("geo3-deserts", S, "Les déserts",
    "Formation, types, sociétés désertiques.",
    "Un désert se définit par son aridité, non par sa température.",
    2, [
    ["Comment définit-on un désert en géographie ?", ["Par une aridité marquée, avec des précipitations très faibles", "Par l'absence totale de végétation sur l'ensemble de son étendue", "Par sa température élevée toute l'année et son fort ensoleillement", "Par l'absence de population permanente"], 0,
     "Le seuil retenu est souvent de deux cent cinquante millimètres de pluie par an."],
    ["Quel est le plus grand désert du monde toutes catégories confondues ?", ["L'Antarctique", "Le Sahara, en Afrique du Nord", "L'Arctique, autour du pôle Nord", "Le désert d'Arabie, dans la péninsule Arabique"], 0,
     "C'est un désert froid : les précipitations y sont extrêmement faibles."],
    ["Qu'est-ce qu'un erg ?", ["Une étendue de dunes de sable", "Un plateau rocheux entaillé de ravins secs", "Une croûte de sel durcie au fond d'une cuvette", "Un lit d'oued asséché entre deux crues"], 0,
     "Il ne représente qu'une part minoritaire de la surface du Sahara."],
    ["Qu'est-ce qu'un reg ?", ["Une surface désertique couverte de graviers et de cailloux", "Une dune fixée par la végétation", "Une falaise désertique dominant une plaine", "Un massif montagneux aride et découpé"], 0,
     "Le vent y a emporté les particules fines, laissant un pavage de cailloux."],
    ["Qu'est-ce qu'un oued ?", ["Un cours d'eau temporaire de région aride", "Une nappe souterraine peu profonde exploitée par des puits", "Une oasis alimentée par une source pérenne", "Un canal d'irrigation à ciel ouvert"], 0,
     "Il peut connaître des crues brutales et meurtrières après un orage lointain."],
    ["Qu'est-ce qu'une oasis ?", ["Un espace cultivé rendu possible par un accès à l'eau en milieu aride", "Une source naturelle jaillissant au pied d'une dune", "Une palmeraie sauvage poussant sans entretien", "Un point d'eau temporaire après un orage"], 0,
     "L'étagement des cultures sous les palmiers y crée un microclimat protecteur."],
    ["Qu'est-ce qu'une foggara ou qanat ?", ["Une galerie souterraine drainant l'eau vers une oasis", "Un puits profond creusé jusqu'à la nappe fossile du Sahara", "Un barrage de retenue construit dans un oued", "Un canal à ciel ouvert bordé de palmiers"], 0,
     "Ce savoir-faire, d'origine persane, permet de limiter l'évaporation."],
    ["Quels facteurs expliquent l'aridité extrême du désert d'Atacama ?", ["Un courant marin froid et une barrière montagneuse", "Sa seule latitude tropicale, sous les hautes pressions", "Son altitude très élevée sur les hauts plateaux andins", "Sa grande distance à l'océan et aux masses d'air humides"], 0,
     "Le courant de Humboldt refroidit l'air côtier ; les Andes bloquent l'humidité amazonienne."],
    ["Qu'est-ce qu'un désert d'abri ?", ["Un désert dû à une barrière montagneuse bloquant les pluies", "Un désert littoral longé par un courant marin froid", "Un désert d'altitude installé sur un haut plateau glacé", "Un désert continental situé très loin de toute façade maritime"], 0,
     "L'air perd son humidité en montant du côté au vent et redescend sec de l'autre côté."],
    ["Qu'est-ce que la grande muraille verte au Sahel ?", ["Un programme de restauration des terres sur plusieurs pays africains", "Une barrière d'arbres continue plantée d'un océan à l'autre du Sahel", "Une clôture anti-érosion dressée le long de toute la bordure sud du Sahara", "Un projet d'irrigation géant alimenté par les nappes fossiles sahariennes"], 0,
     "Le projet initial d'un rideau d'arbres a évolué vers une mosaïque de pratiques agricoles.", 3],
  ]),

  notion("geo3-volcanisme", S, "Le volcanisme",
    "Types d'éruptions, répartition, risques.",
    "Le type d'éruption dépend surtout de la viscosité du magma.",
    2, [
    ["De quoi dépend principalement le type d'éruption volcanique ?", ["De la viscosité du magma et de sa teneur en gaz", "De la taille du volcan et de son altitude au-dessus du niveau de la mer", "De la profondeur de la chambre magmatique sous l'édifice", "De la latitude du volcan et du climat régional"], 0,
     "Un magma fluide donne des coulées, un magma visqueux des explosions."],
    ["Qu'est-ce qu'un volcan effusif ?", ["Un volcan émettant des coulées de lave fluide", "Un volcan explosif à magma acide", "Un volcan sous-marin de dorsale", "Un volcan éteint depuis l'Antiquité"], 0,
     "Les volcans hawaïens et le piton de la Fournaise en sont des exemples."],
    ["Qu'est-ce qu'un volcan explosif ?", ["Un volcan à magma visqueux produisant des nuées et des panaches", "Un volcan à coulées de lave rapides dévalant ses pentes en quelques heures", "Un volcan de point chaud intraplaque", "Un volcan de dorsale océanique"], 0,
     "Ils se situent principalement en zone de subduction."],
    ["Qu'est-ce qu'une caldeira ?", ["Une vaste dépression formée par l'effondrement d'un édifice volcanique", "Un cratère sommital progressivement élargi par les explosions successives", "Un lac de lave permanent occupant en continu le fond du cratère principal", "Un dôme de lave visqueuse accumulée au-dessus de la cheminée volcanique"], 0,
     "Celle de Santorin résulte d'une éruption majeure de l'âge du bronze."],
    ["Qu'est-ce qu'un lahar ?", ["Une coulée de boue volcanique", "Une coulée de lave refroidie en surface", "Une nuée ardente de gaz brûlants", "Une pluie de cendres fines retombées au loin"], 0,
     "Extrêmement destructeur, il peut survenir longtemps après l'éruption, à la faveur de pluies."],
    ["Qu'est-ce que l'indice d'explosivité volcanique ?", ["Une échelle mesurant la puissance d'une éruption", "Une mesure de la seule hauteur du panache de cendres au-dessus du cratère", "Un indice de dangerosité pour les populations", "Une mesure du volume de lave émis en une heure"], 0,
     "Il va de zéro à huit, chaque degré correspondant à un facteur dix en volume de matériaux éjectés."],
    ["Quelle éruption de 1815 a provoqué une année sans été ?", ["Celle du Tambora, en Indonésie", "Celle du Krakatoa, dans le détroit de la Sonde", "Celle du Vésuve, au-dessus de la baie de Naples", "Celle du Laki, en Islande"], 0,
     "Les récoltes ont été perdues jusqu'en Europe et en Amérique du Nord en 1816."],
    ["Quelle éruption islandaise de 2010 a paralysé le trafic aérien européen ?", ["Celle de l'Eyjafjallajökull", "Celle du Laki, dans le sud de l'Islande", "Celle du Grimsvötn, sous le glacier Vatnajökull", "Celle de l'Hekla, au sud-ouest de l'île"], 0,
     "Plus de cent mille vols annulés en une semaine, sans que l'éruption soit d'une ampleur exceptionnelle."],
    ["Comment surveille-t-on un volcan actif ?", ["Par la sismicité, la déformation du sol et les émissions de gaz", "Par l'observation visuelle du cratère uniquement", "Par la seule mesure de la température du cratère", "Par l'analyse chimique des cendres retombées"], 0,
     "L'observatoire du piton de la Fournaise est l'un des plus instrumentés au monde."],
    ["Quel bénéfice le volcanisme apporte-t-il aux sociétés ?", ["Des sols fertiles, de l'énergie géothermique et des ressources minérales", "Aucun bénéfice notable, seulement des destructions et des populations à déplacer", "Un climat plus doux sur les versants exposés grâce à la chaleur du sol", "Une protection contre les séismes par un relâchement régulier des tensions profondes"], 0,
     "C'est ce qui explique la densité de population autour de nombreux volcans actifs.", 3],
  ]),

  notion("geo3-seismes", S, "Les séismes",
    "Mécanismes, mesure, prévention.",
    "On ne sait pas prédire un séisme, mais on sait où et à quelle fréquence ils surviennent.",
    2, [
    ["Qu'est-ce qu'un séisme ?", ["Une libération brutale d'énergie accumulée le long d'une faille", "Un effondrement souterrain de cavités naturelles ou de galeries minières", "Une explosion volcanique transmise au sol environnant", "Un glissement de terrain profond entraînant tout un versant montagneux"], 0,
     "Les plaques se déplacent lentement, mais les blocages libèrent leur énergie d'un coup."],
    ["Quelle différence sépare foyer et épicentre ?", ["Le foyer est en profondeur, l'épicentre à la verticale en surface", "Le foyer est en surface, l'épicentre en profondeur", "Ce sont deux synonymes du même point", "L'épicentre est toujours le point le plus endommagé"], 0,
     "Un séisme profond est généralement moins destructeur qu'un séisme superficiel de même magnitude."],
    ["Que mesure une échelle de magnitude ?", ["L'énergie libérée par le séisme", "Les dégâts observés sur les bâtiments", "La durée totale des secousses ressenties", "La seule accélération du sol au point de mesure"], 0,
     "L'échelle est logarithmique : un degré de plus correspond à environ trente fois plus d'énergie."],
    ["Que mesure une échelle d'intensité comme Mercalli ou EMS ?", ["Les effets ressentis et les dégâts en un lieu donné", "L'énergie totale libérée au foyer du séisme", "La profondeur du foyer sous l'épicentre en kilomètres", "La magnitude corrigée de la distance"], 0,
     "Un même séisme a une seule magnitude mais des intensités différentes selon les lieux."],
    ["Qu'est-ce qu'une réplique sismique ?", ["Une secousse suivant le séisme principal sur la même faille", "Un second séisme indépendant survenant sur une faille voisine", "Une onde réfléchie par les couches profondes du manteau", "Un séisme induit par le remplissage d'un grand barrage-réservoir"], 0,
     "Elles peuvent achever des bâtiments fragilisés et durer des semaines."],
    ["Qu'est-ce que la liquéfaction du sol ?", ["La perte de cohésion d'un sol saturé d'eau sous l'effet des secousses", "Une fusion du sol sous l'effet de la chaleur", "Un glissement de terrain déclenché par la secousse", "Un affaissement souterrain de cavités karstiques"], 0,
     "Des bâtiments intacts peuvent s'enfoncer ou basculer sans se fissurer."],
    ["Où se produisent la majorité des séismes ?", ["Aux limites de plaques tectoniques", "Au centre des continents les plus anciens", "Sous les grandes fosses océaniques profondes", "Dans les seules zones volcaniques actives"], 0,
     "Des séismes intraplaques existent cependant, parfois destructeurs."],
    ["Peut-on prédire un séisme ?", ["Non, on peut seulement évaluer un aléa probabiliste", "Oui, quelques heures avant, grâce aux signaux précurseurs", "Oui, en observant le comportement des animaux", "Oui, avec les instruments modernes des réseaux sismiques"], 0,
     "Aucune méthode de prédiction à court terme n'a jamais été validée scientifiquement."],
    ["Qu'est-ce qu'un système d'alerte précoce sismique ?", ["Un dispositif exploitant le décalage entre ondes rapides et ondes destructrices", "Un système de prédiction annonçant à l'avance la date et le lieu du prochain séisme", "Un réseau de capteurs prédictifs enfouis le long des failles", "Un modèle de simulation des secousses à venir"], 0,
     "Il offre quelques secondes à quelques dizaines de secondes, suffisantes pour arrêter des trains."],
    ["Quelle est la meilleure protection contre les séismes ?", ["Des constructions parasismiques adaptées", "L'évacuation préventive des zones menacées", "La prévision précise de la date des secousses", "Les abris souterrains construits sous les maisons"], 0,
     "Ce ne sont pas les séismes qui tuent mais les bâtiments qui s'effondrent.", 3],
  ]),

  notion("geo3-forets", S, "Les forêts dans le monde",
    "Répartition, exploitation, déforestation.",
    "La forêt française a doublé de surface depuis le milieu du XIXe siècle.",
    2, [
    ["Quelle part des terres émergées les forêts couvrent-elles ?", ["Environ un tiers", "Environ la moitié des terres", "Environ un dixième des terres", "Environ deux tiers des terres"], 0,
     "Contre environ la moitié avant l'expansion agricole humaine."],
    ["Quel pays possède la plus grande superficie forestière ?", ["La Russie", "Le Brésil et son Amazonie", "Le Canada et ses forêts boréales", "Les États-Unis d'Amérique"], 0,
     "Sa taïga représente environ un cinquième des forêts mondiales."],
    ["Quelle est la principale cause de la déforestation tropicale ?", ["L'expansion agricole et l'élevage", "La seule exploitation commerciale du bois", "L'urbanisation des zones tropicales", "Les incendies naturels"], 0,
     "Soja, huile de palme et pâturages en constituent les principaux moteurs."],
    ["Qu'est-ce que la forêt primaire ?", ["Une forêt jamais exploitée ni fragmentée par l'homme", "Une forêt ancienne de plusieurs siècles", "Une forêt protégée par un statut légal", "Une forêt tropicale humide"], 0,
     "Elle abrite une biodiversité que les forêts secondaires ne retrouvent pas avant des siècles."],
    ["Qu'est-ce que la forêt secondaire ?", ["Une forêt repoussée après une perturbation majeure", "Une forêt de moindre importance économique", "Une forêt entièrement plantée par l'homme après une coupe rase", "Une forêt exploitée pour son bois"], 0,
     "Sa structure et sa composition diffèrent durablement de celles de la forêt d'origine."],
    ["Qu'est-ce qu'une plantation forestière ?", ["Une forêt cultivée d'espèces sélectionnées, souvent en peuplement unique", "Une forêt naturelle gérée durablement par un organisme public spécialisé de l'État", "Une forêt de protection contre l'érosion des sols", "Un boisement spontané sur des terres abandonnées"], 0,
     "Elle produit du bois efficacement mais accueille beaucoup moins de biodiversité."],
    ["Quelle évolution la forêt française a-t-elle connue depuis 1850 ?", ["Sa surface a environ doublé", "Elle a diminué de moitié depuis cette date", "Elle est restée stable", "Elle a triplé en un siècle et demi"], 0,
     "La déprise agricole et les politiques de reboisement en sont les principales causes."],
    ["Qui gère les forêts publiques en France ?", ["L'Office national des forêts", "Le ministère de l'Agriculture directement", "Les communes elles-mêmes, sans opérateur", "Les régions et leurs services"], 0,
     "Il gère les forêts domaniales et, par convention, les forêts communales."],
    ["Qui possède la majorité de la forêt française ?", ["Des propriétaires privés", "L'État et ses forêts domaniales", "Les communes et leurs forêts", "Les régions et les départements"], 0,
     "Environ trois quarts de la surface, très morcelée entre plusieurs millions de propriétaires."],
    ["Qu'est-ce que le puits de carbone forestier ?", ["La capacité d'une forêt en croissance à stocker du carbone", "Le seul carbone stocké dans les sols forestiers et les litières", "Le stockage du carbone dans le seul bois coupé et transformé", "L'absorption du carbone par les feuilles"], 0,
     "Le puits forestier français s'est nettement réduit ces dernières années, sous l'effet des sécheresses et des dépérissements.", 3],
  ]),

  notion("geo3-energie-territoires", S, "L'énergie dans les territoires",
    "Production, réseaux, conflits d'usage.",
    "Toute installation énergétique occupe de l'espace et suscite des arbitrages locaux.",
    2, [
    ["Où se situent les centrales nucléaires françaises ?", ["Le long de fleuves ou du littoral, pour le refroidissement", "En altitude, près des grands barrages hydroélectriques de montagne", "Près des anciennes mines d'uranium du Massif central", "À proximité immédiate des grandes agglomérations consommatrices"], 0,
     "Les canicules et les étiages peuvent contraindre leur production."],
    ["Quelles régions françaises concentrent l'essentiel du parc éolien terrestre ?", ["Les Hauts-de-France et le Grand Est", "La région Provence-Alpes-Côte d'Azur et la Corse", "L'Auvergne-Rhône-Alpes et la Bourgogne-Franche-Comté", "La Normandie et la Bretagne, sur les côtes de la Manche"], 0,
     "Deux conditions s'y rencontrent : des vents réguliers de secteur nord-ouest et de vastes plaines de grande culture, où les mâts trouvent place sans conflit d'usage. Le relief et le morcellement du bâti expliquent à l'inverse la faiblesse du parc dans le Sud-Est."],
    ["Qu'est-ce qu'un parc éolien en mer ?", ["Une installation d'éoliennes implantées au large", "Une éolienne flottante isolée ancrée par de longs câbles", "Un projet de recherche encore expérimental", "Une centrale marémotrice d'estuaire"], 0,
     "Le premier parc français commercial a été mis en service au large de Saint-Nazaire en 2022."],
    ["Qu'est-ce que l'énergie marémotrice ?", ["Une production exploitant le marnage des marées", "Une production tirée de la houle et des vagues du large", "Une production tirée des courants marins permanents", "Une production géothermique puisée sous le plancher océanique"], 0,
     "L'usine de la Rance, en service depuis 1966, en est l'une des rares au monde."],
    ["Qu'est-ce que l'énergie géothermique ?", ["Une exploitation de la chaleur du sous-sol", "L'exploitation des seules sources chaudes de surface", "Une production obtenue par le seul forage très profond", "Une énergie fossile extraite du sous-sol"], 0,
     "Elle sert au chauffage urbain en Île-de-France et à la production électrique en Islande."],
    ["Qu'est-ce que la biomasse énergie ?", ["Une énergie produite à partir de matière organique", "Une énergie issue des seuls déchets ménagers", "Une énergie tirée des seules cultures", "Un biocarburant liquide uniquement"], 0,
     "Le bois de chauffage en constitue la première source en France."],
    ["Qu'est-ce qu'une station de transfert d'énergie par pompage ?", ["Une installation stockant l'électricité sous forme d'eau remontée", "Une centrale hydraulique classique au fil de l'eau", "Un barrage de retenue destiné à l'irrigation", "Une usine marémotrice de fond d'estuaire"], 0,
     "C'est le principal moyen de stockage d'électricité à grande échelle aujourd'hui disponible."],
    ["Qu'est-ce que le réseau de transport d'électricité ?", ["Le réseau à haute et très haute tension reliant production et distribution", "Le réseau local de distribution basse tension qui alimente directement les habitations", "Le réseau de recharge des véhicules électriques", "Le seul réseau d'interconnexion avec les pays voisins"], 0,
     "En France, il est géré par RTE, filiale distincte du producteur historique."],
    ["Qu'est-ce que l'acceptabilité sociale d'un projet énergétique ?", ["Le degré d'adhésion des populations concernées", "L'autorisation administrative délivrée par le préfet", "La conformité environnementale attestée par une étude d'impact", "La rentabilité économique du projet pour son exploitant"], 0,
     "Elle dépend fortement des modalités de concertation et du partage des retombées."],
    ["Qu'est-ce qu'un conflit d'usage du sol lié à l'énergie ?", ["Une concurrence entre production énergétique et autres usages du territoire", "Un litige de propriété foncière opposant un exploitant et plusieurs riverains", "Un désaccord entre opérateurs concurrents au sujet du raccordement au réseau", "Un conflit de compétence administrative entre la région et l'État"], 0,
     "L'agrivoltaïsme, qui associe cultures et panneaux solaires, cherche à concilier ces usages.", 3],
  ]),

  notion("geo3-mondialisation-espaces", S, "Les espaces de la mondialisation",
    "Centres, périphéries, réseaux.",
    "La mondialisation ne supprime pas les distances : elle les hiérarchise.",
    2, [
    ["Qu'est-ce qu'une ville mondiale ?", ["Une ville concentrant des fonctions de commandement à l'échelle globale", "Une très grande ville de plus de dix millions d'habitants", "Une capitale politique reconnue par les organisations internationales", "Une ville touristique de renommée internationale"], 0,
     "New York, Londres et Tokyo figurent en tête de la plupart des classements."],
    ["Qu'est-ce qu'une place financière ?", ["Un lieu concentrant les activités de marché et de gestion d'actifs", "Un quartier d'affaires réunissant les sièges des grandes entreprises", "Une bourse de valeurs où se négocient les actions cotées", "Un centre bancaire national abritant le siège de la banque centrale du pays"], 0,
     "Leur classement dépend de la profondeur des marchés, du droit applicable et des compétences disponibles."],
    ["Qu'est-ce qu'un paradis fiscal du point de vue géographique ?", ["Un territoire souvent petit, spécialisé dans l'accueil de capitaux", "Un pays appliquant une imposition très faible à l'ensemble de ses entreprises", "Un centre bancaire international ouvert aux non-résidents", "Un État totalement dépourvu d'impôt sur le revenu"], 0,
     "Leur petite taille leur permet de faire du droit un avantage comparatif."],
    ["Qu'est-ce qu'une zone franche ?", ["Un territoire à régime douanier ou fiscal dérogatoire", "Une zone de libre-échange unissant plusieurs États voisins", "Une zone d'activité économique aménagée par une collectivité", "Un port ouvert sans aucune restriction aux navires étrangers"], 0,
     "Elles servent souvent à l'assemblage de produits destinés à la réexportation."],
    ["Qu'est-ce qu'une interface maritime ?", ["Une zone de contact entre l'arrière-pays et le monde par la mer", "Un port de commerce traitant marchandises et conteneurs", "Une façade littorale urbanisée en continu sur des centaines de kilomètres", "Une zone industrialo-portuaire de dimension régionale"], 0,
     "Sa performance dépend autant des dessertes terrestres que des installations portuaires."],
    ["Qu'est-ce qu'une zone industrialo-portuaire ?", ["Un espace associant port et industries lourdes", "Une zone d'entrepôts desservie par le rail et la route", "Un terminal à conteneurs équipé de portiques géants", "Un parc logistique installé à l'écart des villes"], 0,
     "Fos-sur-Mer, Dunkerque et Rotterdam en sont des exemples européens."],
    ["Qu'est-ce que la conteneurisation a changé pour les ports ?", ["Elle a déplacé les activités vers des sites en eau profonde très mécanisés", "Elle a maintenu les ports historiques au cœur des villes", "Elle a réduit le trafic maritime mondial de marchandises", "Elle a supprimé toute manutention sur les quais"], 0,
     "Les anciens docks urbains ont souvent été reconvertis en quartiers résidentiels et culturels."],
    ["Qu'est-ce qu'un hub aéroportuaire ?", ["Un aéroport organisé pour les correspondances", "Un aéroport international ouvert aux vols long-courriers", "Un aéroport réservé au fret et au courrier express", "Un aéroport à très forte fréquentation de passagers"], 0,
     "Les vagues d'arrivées et de départs y sont synchronisées pour minimiser les temps d'attente."],
    ["Qu'est-ce qu'un espace périphérique dans l'analyse de la mondialisation ?", ["Un territoire faiblement intégré aux flux dominants", "Un territoire rural éloigné des grandes agglomérations", "Une région frontalière traversée par une limite d'État", "Un pays pauvre au faible revenu par habitant"], 0,
     "La périphérie n'est pas nécessairement pauvre : elle est dépendante des centres de décision."],
    ["Qu'est-ce que le concept de flux dans l'analyse géographique ?", ["Un déplacement de biens, de personnes, de capitaux ou d'informations", "Un mouvement migratoire durable d'une région vers une autre", "Un échange commercial de marchandises entre deux pays partenaires signataires", "Un transfert financier d'un compte bancaire vers un autre pays"], 0,
     "Leur cartographie révèle des hiérarchies invisibles sur une carte des États.", 3],
  ]),

  notion("geo3-alimentation-monde", S, "Nourrir le monde",
    "Production, accès, inégalités alimentaires.",
    "La production alimentaire mondiale suffit théoriquement à nourrir toute la population.",
    2, [
    ["Combien de personnes souffrent de sous-alimentation dans le monde ?", ["Plusieurs centaines de millions", "Environ dix millions, presque tous en Asie", "Environ deux milliards, soit un humain sur quatre", "Environ cinquante millions, en majorité des enfants"], 0,
     "Le chiffre a remonté depuis 2015 après des décennies de baisse."],
    ["Qu'est-ce que la malnutrition par carence ?", ["Un déficit en nutriments essentiels malgré un apport calorique parfois suffisant", "Une insuffisance calorique durable de la ration quotidienne", "Un excès alimentaire chronique conduisant au surpoids", "Une maladie digestive empêchant l'absorption des aliments"], 0,
     "Les carences en fer, en vitamine A et en iode touchent des milliards de personnes."],
    ["Qu'est-ce que la double charge nutritionnelle ?", ["La coexistence de sous-nutrition et d'obésité dans un même pays", "Une double ration alimentaire distribuée aux populations vulnérables", "Un excès conjoint de protéines et de sucres dans la ration", "Une carence multiple en fer, en iode et en vitamine A"], 0,
     "Elle est fréquente dans les pays à revenu intermédiaire en transition nutritionnelle."],
    ["Quelle est la principale cause des famines contemporaines ?", ["Les conflits armés et l'effondrement des institutions", "Les mauvaises récoltes répétées dans les régions productrices", "La croissance démographique plus rapide que les rendements", "Le seul changement climatique et ses sécheresses"], 0,
     "Amartya Sen a montré que les famines résultent plus souvent d'un défaut d'accès que d'un manque global."],
    ["Qu'est-ce que le Programme alimentaire mondial ?", ["L'agence des Nations unies chargée de l'aide alimentaire", "Un programme agricole de la FAO destiné aux pays les plus pauvres", "Un fonds de développement rural géré par la Banque mondiale", "Un observatoire international des prix des produits agricoles"], 0,
     "Il a reçu le prix Nobel de la paix en 2020."],
    ["Qu'est-ce qu'une crise alimentaire liée aux prix ?", ["Une flambée des prix rendant l'alimentation inaccessible malgré une offre disponible", "Une pénurie physique de denrées sur les marchés locaux", "Une rupture d'approvisionnement des circuits d'importation", "Une mauvaise récolte mondiale de céréales sur plusieurs années"], 0,
     "Les émeutes de la faim de 2008 ont touché plus de trente pays."],
    ["Quel effet le régime alimentaire des pays riches a-t-il sur les ressources ?", ["Il mobilise beaucoup de terres et d'eau par calorie consommée", "Il est neutre pour les terres comme pour les ressources en eau", "Il économise des ressources grâce aux rendements élevés", "Il ne mobilise que de très faibles surfaces agricoles par habitant"], 0,
     "La part importante de produits animaux en est la principale raison."],
    ["Qu'est-ce que l'agriculture urbaine ?", ["Une production alimentaire dans ou à proximité immédiate des villes", "Un jardinage de loisir pratiqué dans les jardins familiaux des villes", "Une culture hors-sol sous serre chauffée", "Le seul maraîchage professionnel de la ceinture périurbaine"], 0,
     "Son apport nutritionnel réel reste limité mais ses fonctions sociales sont importantes."],
    ["Qu'est-ce que la souveraineté alimentaire selon les organisations paysannes ?", ["Le droit des peuples à définir leurs politiques agricoles et alimentaires", "L'autosuffisance alimentaire complète d'un pays", "L'indépendance totale vis-à-vis des importations agricoles", "La protection douanière des marchés agricoles nationaux"], 0,
     "Le concept a été formulé par Via Campesina en 1996, en opposition à la libéralisation des échanges."],
    ["Quel défi majeur l'alimentation mondiale affronte-t-elle ?", ["Nourrir davantage de personnes en réduisant l'impact environnemental", "Augmenter sans cesse les surfaces cultivées au détriment des forêts tropicales", "Accroître les rendements sans limite grâce aux seuls engrais de synthèse et aux pesticides", "Réduire volontairement la population mondiale pour ajuster la demande à l'offre"], 0,
     "Les scénarios convergent sur la nécessité de combiner rendements, réduction des pertes et changements de régime.", 3],
  ]),

  notion("geo3-eau-conflits", S, "L'eau, ressource et enjeu",
    "Partage, tensions, gestion transfrontalière.",
    "Plus de la moitié de l'eau douce mondiale provient de bassins partagés entre plusieurs pays.",
    2, [
    ["Qu'est-ce qu'un bassin transfrontalier ?", ["Un bassin versant partagé entre plusieurs États", "Un fleuve international navigable jusqu'à son embouchure", "Une nappe souterraine partagée, et elle seule", "Un lac frontalier bordé par deux pays voisins au moins"], 0,
     "Environ trois cents bassins de ce type dans le monde, concernant la majorité de la population."],
    ["Quel fleuve fait l'objet de tensions entre l'Égypte, le Soudan et l'Éthiopie ?", ["Le Nil", "Le Niger, en Afrique de l'Ouest", "Le Zambèze, en Afrique australe", "Le Congo, en Afrique équatoriale"], 0,
     "La construction du grand barrage de la Renaissance en Éthiopie a ravivé ces tensions."],
    ["Quel fleuve d'Asie fait l'objet de tensions liées aux barrages chinois ?", ["Le Mékong", "Le Gange, en Inde et au Bangladesh", "L'Indus, au Pakistan", "Le Brahmapoutre, et lui seul"], 0,
     "Les barrages amont modifient le régime des crues dont dépendent les agricultures aval."],
    ["Quel traité régit le partage des eaux de l'Indus ?", ["Le traité des eaux de l'Indus de 1960", "Le traité de Simla, signé par l'Inde en 1972", "La déclaration de Lahore, conclue en 1999", "Le seul accord de cessez-le-feu de Karachi"], 0,
     "Signé entre l'Inde et le Pakistan, il a survécu à plusieurs guerres entre les deux pays."],
    ["Qu'est-ce que le stress hydrique ?", ["Une situation où la demande en eau dépasse la ressource disponible", "Une sécheresse ponctuelle de quelques semaines", "Une pollution rendant l'eau impropre à la consommation", "Un manque d'infrastructures de distribution"], 0,
     "Il se mesure par le rapport entre prélèvements et ressources renouvelables."],
    ["Qu'est-ce qu'une nappe fossile ?", ["Une nappe qui ne se recharge pratiquement plus", "Une nappe très profonde située sous plusieurs couches", "Une nappe ancienne mais régulièrement rechargée par les pluies", "Une nappe salée impropre à l'irrigation"], 0,
     "Son exploitation revient à consommer un stock non renouvelable, comme une mine."],
    ["Qu'est-ce que la surexploitation d'une nappe ?", ["Un prélèvement supérieur à sa recharge naturelle", "Une pollution excessive par les nitrates agricoles", "Un forage trop profond dans l'aquifère", "Un usage agricole trop intensif"], 0,
     "Elle provoque des affaissements de terrain et des intrusions d'eau salée sur les littoraux."],
    ["Qu'est-ce qu'une agence de l'eau en France ?", ["Un établissement public gérant l'eau à l'échelle d'un grand bassin", "Un service de distribution d'eau potable communal", "Un organisme de contrôle sanitaire de l'eau potable", "Une régie municipale de l'assainissement"], 0,
     "Six agences couvrent le territoire, financées par des redevances sur les usages."],
    ["Qu'est-ce que le principe pollueur-payeur appliqué à l'eau ?", ["La prise en charge par l'usager des coûts liés à son impact", "Une taxe forfaitaire sur la consommation d'eau de tous les ménages", "Une amende infligée après constat de pollution", "Un tarif progressif appliqué selon les volumes annuels consommés"], 0,
     "Les redevances des agences de l'eau en constituent l'application principale en France."],
    ["Qu'est-ce qu'un arrêté sécheresse ?", ["Une mesure préfectorale restreignant les usages de l'eau", "Une déclaration de l'état de catastrophe naturelle par le gouvernement", "Une interdiction générale d'irriguer", "Une alerte météorologique de Météo-France"], 0,
     "Les niveaux vont de la vigilance à la crise renforcée, avec des restrictions croissantes.", 3],
  ]),

  notion("geo3-espaces-ruraux", S, "Les espaces ruraux",
    "Déprise, renouveau, diversité.",
    "La ruralité française n'est plus principalement agricole.",
    2, [
    ["Quelle part de la population française vit dans l'espace rural ?", ["Environ un tiers", "Environ un habitant sur dix", "Environ la moitié des Français", "Environ un habitant sur cinq"], 0,
     "La définition retenue par l'INSEE a été révisée en 2020, augmentant cette part."],
    ["Quelle part des ruraux français travaille dans l'agriculture ?", ["Une petite minorité", "La majorité des actifs ruraux", "Environ la moitié d'entre eux", "Environ un actif rural sur trois"], 0,
     "La plupart des actifs ruraux travaillent dans les services ou l'industrie, souvent en ville."],
    ["Qu'est-ce que la périurbanisation ?", ["L'extension de l'influence urbaine sur les campagnes proches", "L'urbanisation nouvelle des centres-villes anciens et de leurs abords", "La création de villes nouvelles à distance des agglomérations", "La densification des banlieues déjà construites"], 0,
     "Elle transforme des villages en communes résidentielles dépendantes de la ville-centre."],
    ["Qu'est-ce que la déprise agricole ?", ["L'abandon de terres agricoles peu productives", "Une baisse durable des prix payés aux producteurs agricoles", "Une réduction des aides publiques", "Un vieillissement rapide des exploitants"], 0,
     "Elle entraîne souvent un enfrichement puis un reboisement spontané."],
    ["Qu'est-ce que la multifonctionnalité de l'espace rural ?", ["La coexistence de fonctions productives, résidentielles et récréatives", "La diversification des productions agricoles", "La pluriactivité des exploitants agricoles", "Le tourisme rural et les gîtes à la ferme"], 0,
     "Elle est aussi source de conflits d'usage entre habitants et exploitants."],
    ["Qu'est-ce qu'un conflit d'usage en milieu rural ?", ["Un désaccord entre habitants sur des usages incompatibles de l'espace", "Un litige foncier portant sur la délimitation exacte de parcelles voisines", "Un conflit de voisinage ordinaire entre deux propriétaires", "Un désaccord entre agriculteurs sur le partage de l'eau"], 0,
     "Bruits d'élevage, épandages ou chasse en sont des motifs fréquents."],
    ["Qu'est-ce que la loi de 2021 sur les bruits et odeurs de la campagne ?", ["Une loi protégeant le patrimoine sensoriel des campagnes", "Une loi encadrant les nuisances sonores des exploitations agricoles", "Une loi réformant les troubles anormaux du voisinage en zone rurale", "Une loi réformant l'urbanisme des communes rurales"], 0,
     "Elle fait suite à des contentieux médiatisés, dont l'affaire du coq Maurice."],
    ["Qu'est-ce qu'un néo-rural ?", ["Une personne s'installant à la campagne après un parcours urbain", "Un agriculteur récemment installé sur une exploitation", "Un habitant d'une commune périurbaine récente", "Un résident secondaire présent quelques semaines par an"], 0,
     "Le phénomène, ancien, s'est accéléré après la pandémie de 2020."],
    ["Qu'est-ce que la désertification médicale rurale ?", ["Un manque de professionnels de santé accessibles", "L'abandon progressif des hôpitaux publics de proximité", "La fermeture des pharmacies dans les petites communes", "Un manque d'ambulances et de transports sanitaires"], 0,
     "Elle touche aussi des zones périurbaines et certains quartiers de grandes villes."],
    ["Qu'est-ce qu'une maison France Services ?", ["Un guichet regroupant plusieurs services publics dans un même lieu", "Une mairie annexe ouverte dans les communes rurales les plus étendues", "Un centre social géré par la commune", "Une maison de santé réunissant plusieurs praticiens"], 0,
     "Le dispositif vise à compenser le retrait des services publics des territoires ruraux.", 3],
  ]),

  notion("geo3-cartes-donnees", S, "Cartes et représentations",
    "Choix graphiques, statistiques, manipulations.",
    "Une carte est un discours autant qu'une description.",
    2, [
    ["Qu'est-ce qu'une carte choroplèthe ?", ["Une carte colorant des zones selon une valeur statistique", "Une carte de points implantés au lieu exact de chaque fait", "Une carte de flux figurés par des flèches d'épaisseur variable", "Une carte en relief ombré du terrain"], 0,
     "Elle exige des valeurs relatives, sinon elle traduit surtout la taille des unités."],
    ["Pourquoi ne faut-il pas cartographier des valeurs absolues en aplats de couleur ?", ["La surface des unités biaise la lecture", "Les couleurs disponibles sont en trop petit nombre", "Les données absolues sont toujours trop précises", "L'échelle de la carte est toujours inadaptée"], 0,
     "Un grand département apparaîtra toujours plus intense qu'un petit, à effectif égal."],
    ["Qu'est-ce qu'une carte en anamorphose ?", ["Une carte déformant les surfaces selon une variable", "Une carte dessinée dans une projection modifiée par l'auteur", "Une carte schématique très simplifiée", "Une carte en trois dimensions du relief"], 0,
     "Elle rend visibles des réalités que la géométrie physique masque, au prix d'une lecture déroutante."],
    ["Qu'est-ce qu'une discrétisation en cartographie ?", ["Le découpage des valeurs en classes", "La simplification du tracé des contours", "La réduction du nombre de figurés employés", "La sélection des données à représenter"], 0,
     "Changer la méthode de discrétisation peut transformer complètement l'aspect d'une carte."],
    ["Qu'est-ce qu'un figuré proportionnel ?", ["Un symbole dont la taille varie avec la valeur représentée", "Un aplat de couleur uniforme sur la zone", "Une hachure orientée selon la donnée", "Une isoligne reliant des points de même valeur"], 0,
     "Il convient aux valeurs absolues, contrairement aux aplats de couleur."],
    ["Qu'est-ce qu'un croquis de géographie ?", ["Une représentation simplifiée organisant l'espace autour d'une problématique", "Un dessin d'observation réalisé sur le terrain", "Une carte tracée à main levée sans instruments", "Un schéma de paysage vu depuis un point haut"], 0,
     "Sa légende organisée est aussi importante que le tracé lui-même."],
    ["Qu'est-ce qu'un schéma en géographie ?", ["Une représentation très simplifiée de l'organisation d'un espace", "Une carte très détaillée portant l'ensemble des éléments du terrain", "Un plan de ville détaillé indiquant le nom de chaque rue", "Un profil topographique tracé le long d'une coupe du relief régional"], 0,
     "Il ne conserve que les formes et les relations essentielles."],
    ["Comment une carte peut-elle induire en erreur ?", ["Par le choix de la projection, des classes, des couleurs et du cadrage", "Uniquement par l'emploi de données statistiques volontairement falsifiées", "Par sa taille et son format d'impression", "Par sa seule échelle de restitution"], 0,
     "Aucune de ces manipulations n'exige de falsifier une seule donnée."],
    ["Qu'est-ce que la cartographie participative ?", ["Une production de cartes par les habitants ou les usagers", "Une consultation du public sur un projet d'aménagement local", "Les seules cartes collaboratives produites en ligne par des bénévoles", "Une enquête cartographique menée par des chercheurs"], 0,
     "OpenStreetMap en est l'exemple le plus massif à l'échelle mondiale."],
    ["Qu'est-ce que la donnée ouverte en géographie ?", ["Des données publiques librement réutilisables", "Des données gratuites mais soumises à autorisation", "Des données publiques communiquées sur simple demande écrite", "Des données non protégées par le droit d'auteur"], 0,
     "L'IGN a ouvert l'essentiel de ses données en 2021, ce qui a transformé de nombreux usages.", 3],
  ]),

  notion("geo3-inegalites-territoriales", S, "Inégalités territoriales",
    "Mesures, dynamiques, politiques de rééquilibrage.",
    "Les inégalités entre territoires ne recoupent pas simplement l'opposition ville-campagne.",
    2, [
    ["Qu'est-ce qu'une inégalité territoriale ?", ["Un écart d'accès aux ressources selon le lieu de résidence", "Une différence de revenu entre les habitants d'une même commune", "Un écart de densité de population entre deux régions voisines", "Une différence de statut administratif entre collectivités"], 0,
     "Emploi, services, santé, transport et éducation en constituent les principales dimensions."],
    ["Qu'est-ce que la ségrégation socio-spatiale ?", ["La séparation des groupes sociaux dans l'espace urbain", "Une discrimination à l'embauche fondée sur l'adresse du candidat", "Une séparation administrative des quartiers", "Un zonage réglementaire du plan local d'urbanisme"], 0,
     "Elle concerne aussi bien les quartiers pauvres que l'entre-soi des quartiers aisés."],
    ["Qu'est-ce que l'indice de développement humain appliqué aux territoires ?", ["Une adaptation locale combinant santé, éducation et niveau de vie", "Un indice de richesse locale calculé par habitant", "Un indicateur de croissance du produit régional brut", "Un classement des villes selon leur attractivité"], 0,
     "Il révèle des écarts que le seul PIB par habitant ne montre pas."],
    ["Qu'est-ce que l'accessibilité aux services ?", ["Le temps ou la distance nécessaires pour atteindre un équipement", "La seule disponibilité d'un service public pendant les heures ouvrables", "La gratuité d'un service public pour tous les usagers du territoire", "L'ouverture d'un guichet physique dans chaque commune du département"], 0,
     "Elle dépend autant de l'offre de transport que de l'implantation des services."],
    ["Quelle part de la population française vit dans une zone sous-dotée en médecins ?", ["Environ un habitant sur dix", "Environ un habitant sur cent", "Environ la moitié des habitants", "Environ un habitant sur trois"], 0,
     "Le chiffre varie fortement selon la définition retenue et la spécialité considérée."],
    ["Qu'est-ce que la fracture numérique territoriale ?", ["Des écarts d'accès au très haut débit et aux compétences numériques", "Une différence d'équipement informatique entre les ménages ruraux et urbains", "Un manque d'opérateurs de téléphonie dans les campagnes", "Une inégalité tarifaire entre abonnements selon les régions"], 0,
     "Le plan France très haut débit vise une couverture généralisée en fibre optique."],
    ["Qu'est-ce qu'une zone blanche ?", ["Un secteur non couvert par un réseau de téléphonie mobile", "Une zone privée de raccordement au réseau électrique national", "Une zone non cartographiée par les services cadastraux de l'État", "Une zone sans aucun habitant permanent recensé"], 0,
     "Leur résorption fait l'objet d'obligations imposées aux opérateurs."],
    ["Qu'est-ce que la dotation globale de fonctionnement ?", ["Une dotation de l'État aux collectivités, partiellement péréquée", "Une subvention d'investissement versée au cas par cas", "Un impôt local perçu par les communes", "Un fonds européen de cohésion régionale"], 0,
     "La péréquation vise à réduire les écarts de ressources entre collectivités."],
    ["Qu'est-ce que la péréquation financière ?", ["Un transfert de ressources des collectivités riches vers les plus pauvres", "Une répartition strictement égale des dotations entre toutes les collectivités", "Un fonds d'urgence mobilisé après une catastrophe", "Une compensation fiscale des impôts locaux supprimés"], 0,
     "Elle peut être verticale, via l'État, ou horizontale, entre collectivités."],
    ["Qu'est-ce que le sentiment d'abandon territorial ?", ["Une perception de relégation exprimée par des habitants de certains territoires", "Une réalité statistique mesurée chaque année par les services statistiques de l'État", "Un indicateur officiel publié chaque année par l'INSEE dans ses rapports régionaux", "Un critère de zonage retenu pour l'attribution des aides publiques aux communes"], 0,
     "Il ne recoupe pas exactement les indicateurs objectifs, ce qui en fait un objet d'étude à part entière.", 3],
  ]),

  notion("geo3-espace-europeen", S, "L'espace européen",
    "Intégration, disparités, frontières.",
    "L'espace Schengen et l'Union européenne ne recouvrent pas exactement les mêmes pays.",
    2, [
    ["Quelle politique européenne vise à réduire les écarts entre régions ?", ["La politique de cohésion", "La politique agricole commune", "La politique de concurrence", "La politique commerciale commune"], 0,
     "Elle représente environ un tiers du budget européen."],
    ["Qu'est-ce qu'un fonds structurel européen ?", ["Un instrument financier soutenant le développement régional", "Un prêt accordé par la Banque européenne d'investissement aux États", "Une subvention agricole versée à l'hectare cultivé", "Un fonds d'urgence en cas de catastrophe naturelle"], 0,
     "Le FEDER et le Fonds social européen en sont les principaux."],
    ["Qu'est-ce que la coopération transfrontalière européenne ?", ["Des projets communs entre territoires de part et d'autre d'une frontière", "Un accord signé entre deux États voisins", "Une politique douanière allégée aux frontières", "Un jumelage entre deux villes de pays différents"], 0,
     "Le programme Interreg la finance depuis 1990."],
    ["Qu'est-ce qu'une eurorégion ?", ["Une structure de coopération entre régions frontalières de plusieurs États", "Une région administrative créée et directement gérée par l'Union européenne", "Une circonscription électorale pour les élections européennes", "Un regroupement de pays au sein d'un même traité"], 0,
     "Elle n'a pas de pouvoir souverain mais facilite la gestion de problèmes communs."],
    ["Combien de pays composent l'espace Schengen ?", ["Vingt-neuf, dont quelques non-membres de l'Union", "Vingt-sept, soit exactement les membres de l'Union", "Vingt-cinq, tous membres de l'Union européenne actuelle", "Trente-deux, en comptant les micro-États du continent"], 0,
     "L'Islande, la Norvège, la Suisse et le Liechtenstein en font partie sans être membres de l'Union."],
    ["Quel État membre de l'Union a négocié une clause d'exemption formelle le dispensant d'adopter l'euro ?", ["Le Danemark", "La Suède, membre depuis 1995", "La Pologne, membre depuis 2004", "La Hongrie, membre depuis 2004"], 0,
     "Le Danemark bénéficie d'une clause d'exemption ; la Suède a de facto choisi de ne pas y entrer."],
    ["Pourquoi les géographes critiquent-ils l'expression de banane bleue ?", ["Elle simplifie à l'excès une réalité économique bien plus fragmentée", "Elle est trop récente pour être utilisée", "Elle désigne une zone totalement inexistante", "Elle ignore complètement les frontières d'État"], 0,
     "Forgée en 1989, l'image a connu un succès médiatique que sa valeur analytique ne justifiait pas."],
    ["Qu'est-ce que l'élargissement de 2004 ?", ["L'adhésion de dix pays, principalement d'Europe centrale et orientale", "L'adhésion de la Grèce, du Portugal et de l'Espagne au marché commun européen", "L'adhésion de la Croatie, dernier pays à être entré dans l'Union européenne", "L'adhésion du Royaume-Uni et de l'Irlande"], 0,
     "Le plus important élargissement de l'histoire de l'Union en nombre de pays."],
    ["Qu'est-ce que le Brexit ?", ["La sortie du Royaume-Uni de l'Union européenne", "Un accord commercial signé entre Londres et Bruxelles", "Un traité de retrait britannique de l'espace Schengen", "Une clause d'exemption obtenue par Londres"], 0,
     "Décidée par référendum en 2016, effective en 2020 après une période de transition."],
    ["Quelle est la principale disparité économique dans l'Union européenne ?", ["Un écart persistant entre régions du Nord-Ouest et du Sud-Est", "Le seul écart entre les villes et les campagnes de chaque pays", "Un écart entre pays fondateurs et nouveaux venus", "Une opposition entre les îles et le continent"], 0,
     "La convergence est réelle mais lente, et inégale selon les régions.", 3],
  ]),

  notion("geo3-espace-mediterranee", S, "L'espace méditerranéen",
    "Une mer partagée entre trois continents.",
    "La Méditerranée concentre une part importante du trafic maritime mondial sur une surface réduite.",
    2, [
    ["Combien de pays bordent la Méditerranée ?", ["Une vingtaine", "Une dizaine seulement", "Une trentaine de pays", "Quinze exactement"], 0,
     "Répartis sur trois continents : Europe, Afrique et Asie."],
    ["Quelle proportion du trafic maritime mondial passe en Méditerranée ?", ["Environ un cinquième", "Environ la moitié du total", "Environ cinq pour cent du total", "Environ un tiers du trafic"], 0,
     "Sur environ un pour cent de la surface des océans du globe."],
    ["Qu'est-ce que le renouvellement des eaux méditerranéennes ?", ["Un processus très lent, la mer étant quasi fermée", "Un renouvellement complet des eaux profondes chaque année", "Un échange rapide et permanent par le détroit de Gibraltar", "Un brassage saisonnier de surface"], 0,
     "Environ un siècle, ce qui rend la mer très sensible aux pollutions persistantes."],
    ["Quel écart de développement caractérise les rives méditerranéennes ?", ["Un contraste marqué entre rive nord et rives sud et est", "Une homogénéité économique d'ensemble", "Un contraste marqué entre est et ouest", "Un écart entre les îles et le continent"], 0,
     "Le rapport de revenu par habitant peut varier de un à dix entre les deux rives."],
    ["Qu'est-ce que le processus de Barcelone ?", ["Un partenariat euro-méditerranéen lancé en 1995", "Un traité de libre-échange entre les deux rives", "Un accord environnemental sur la pollution marine", "Un pacte migratoire signé entre l'Europe et le Maghreb"], 0,
     "Devenu Union pour la Méditerranée en 2008, ses résultats sont jugés limités."],
    ["Quel risque naturel majeur concerne le pourtour méditerranéen ?", ["Les séismes et les incendies de forêt", "Les cyclones tropicaux venus de l'Atlantique", "Les inondations dues aux crues glaciaires", "Les tornades de grande ampleur"], 0,
     "La convergence des plaques africaine et eurasiatique explique la sismicité de la région."],
    ["Qu'est-ce qu'un épisode méditerranéen ?", ["Des pluies torrentielles automnales sur le pourtour nord-occidental", "Un vent chaud et sec soufflant du Sahara", "Une vague de chaleur estivale prolongée", "Une sécheresse hivernale de plusieurs mois"], 0,
     "Ils peuvent déverser en quelques heures l'équivalent de plusieurs mois de précipitations."],
    ["Quelle pression le tourisme exerce-t-il sur la Méditerranée ?", ["Elle est la première destination touristique mondiale, avec de fortes pressions locales", "Une pression modérée et bien répartie sur l'ensemble des rives, sans effet notable sur le littoral", "Une pression limitée aux seules îles de la Méditerranée occidentale", "Une pression uniquement estivale, sans conséquence durable"], 0,
     "Consommation d'eau, artificialisation du littoral et déchets en sont les principaux effets."],
    ["Qu'est-ce que la posidonie ?", ["Une plante marine formant des herbiers essentiels à l'écosystème méditerranéen", "Une algue verte invasive venue des mers tropicales et propagée par les navires", "Un corail rouge des fonds méditerranéens récolté depuis l'Antiquité pour la joaillerie", "Un poisson endémique des côtes rocheuses de la Méditerranée"], 0,
     "Ses herbiers stockent du carbone, protègent les côtes et abritent une faune abondante."],
    ["Quel enjeu migratoire concerne la Méditerranée ?", ["Des traversées maritimes dangereuses vers l'Europe", "Des migrations internes aux seuls pays riverains du bassin", "Des migrations saisonnières agricoles", "Un exode rural vers les grandes villes côtières"], 0,
     "Des dizaines de milliers de personnes y ont péri depuis le début des années 2000.", 3],
  ]),

  notion("geo3-arctique-enjeux", S, "L'Arctique, nouvel espace stratégique",
    "Fonte, ressources, gouvernance.",
    "L'Arctique se réchauffe bien plus vite que la moyenne mondiale, et les estimations récentes ont revu le facteur à la hausse.",
    2, [
    ["À quelle vitesse l'Arctique se réchauffe-t-il ?", ["Environ quatre fois plus vite que la moyenne mondiale", "Exactement à la même vitesse que le reste de la planète", "Deux fois moins vite que la moyenne des autres régions", "Dix fois plus vite que la moyenne de la planète entière"], 0,
     "L'amplification arctique s'explique notamment par la disparition de la glace réfléchissante."],
    ["Quelle instance réunit les États riverains de l'Arctique ?", ["Le Conseil de l'Arctique", "L'Organisation arctique des Nations unies", "Le traité de l'Arctique de 1959", "La commission polaire internationale"], 0,
     "Créé en 1996, il associe huit États et des organisations de peuples autochtones."],
    ["Quel statut juridique l'océan Arctique possède-t-il ?", ["Celui d'un océan régi par le droit de la mer", "Celui d'un territoire international sans souveraineté", "Celui d'un continent partagé entre huit États riverains", "Celui d'une zone démilitarisée par traité"], 0,
     "À la différence de l'Antarctique, il n'existe pas de traité spécifique gelant les revendications."],
    ["Quelles ressources l'Arctique recèle-t-il ?", ["Hydrocarbures, minerais et ressources halieutiques", "Uniquement du pétrole offshore", "Principalement de l'eau douce glaciaire", "Aucune ressource réellement exploitable"], 0,
     "Leur exploitation reste techniquement difficile et coûteuse."],
    ["Qu'est-ce que la route maritime du Nord ?", ["Un passage le long des côtes sibériennes reliant Europe et Asie", "Le passage du Nord-Ouest, à travers l'archipel arctique canadien", "Une route transpolaire passant par le pôle Nord", "Une liaison Atlantique-Pacifique contournant le Groenland"], 0,
     "Elle raccourcit considérablement le trajet entre l'Europe et l'Asie orientale."],
    ["Quel peuple autochtone est présent de la Sibérie à l'Alaska ?", ["Plusieurs peuples distincts, dont les Inuits et les Nenets", "Un seul peuple arctique réparti tout autour du cercle polaire", "Les seuls Samis, présents de la Norvège jusqu'à la péninsule de Kola", "Les seuls Aléoutes, sur leur archipel du Pacifique nord"], 0,
     "Une quarantaine de peuples autochtones vivent dans les régions arctiques."],
    ["Qu'est-ce que le Groenland sur le plan politique ?", ["Un territoire autonome du royaume de Danemark", "Un État indépendant depuis le référendum de 2009", "Une région ultrapériphérique de l'Union", "Un territoire sous tutelle de l'ONU"], 0,
     "Il a quitté la Communauté européenne en 1985 tout en restant lié au Danemark."],
    ["Quel effet la fonte du permafrost a-t-elle en Arctique ?", ["Elle libère du méthane et déstabilise les infrastructures", "Elle fertilise durablement les sols des toundras arctiques", "Elle stabilise durablement les côtes en y déposant des sédiments", "Elle réduit les émissions régionales de gaz à effet de serre"], 0,
     "Des villages sibériens et alaskiens ont déjà dû être déplacés."],
    ["Qu'est-ce que la militarisation de l'Arctique ?", ["Un renforcement des dispositifs militaires des États riverains", "Une occupation militaire d'un territoire voisin", "Un déploiement de l'OTAN et de lui seul", "Une zone d'exclusion militaire imposée par traité"], 0,
     "La Russie y a rouvert des bases datant de la guerre froide."],
    ["Quel enjeu la fonte de la banquise pose-t-elle pour la faune ?", ["La disparition d'un habitat essentiel pour plusieurs espèces", "Un accès facilité à la nourriture pour les grands prédateurs marins", "Une extension des territoires de chasse", "Aucun effet mesuré à ce jour"], 0,
     "L'ours polaire, dépendant de la banquise pour chasser, en est le symbole le plus connu.", 3],
  ]),

  notion("geo3-espace-urbain-france", S, "Les villes françaises",
    "Réseau urbain, métropolisation, dynamiques.",
    "Le réseau urbain français est marqué par le poids exceptionnel de Paris.",
    2, [
    ["Quel rapport de taille sépare Paris de la deuxième agglomération française ?", ["Environ un rapport de six à un", "Environ un rapport de deux à un", "Environ un rapport de vingt à un", "Environ un rapport de trois à un"], 0,
     "Cette macrocéphalie distingue la France de l'Allemagne ou de l'Italie."],
    ["Quelle est la deuxième agglomération française ?", ["Lyon", "Marseille, sur la côte méditerranéenne", "Lille, dans les Hauts-de-France", "Toulouse, en Occitanie"], 0,
     "Les classements varient selon que l'on considère la commune, l'unité urbaine ou l'aire d'attraction."],
    ["Qu'est-ce qu'une aire d'attraction des villes selon l'INSEE ?", ["Un ensemble de communes liées à un pôle par les déplacements domicile-travail", "Une agglomération au bâti continu", "Une intercommunalité à fiscalité propre", "Un bassin de vie organisé autour des équipements courants"], 0,
     "Ce zonage a remplacé les aires urbaines en 2020."],
    ["Qu'est-ce qu'une unité urbaine ?", ["Un ensemble de communes formant une continuité du bâti", "Une commune urbaine de plus de deux mille habitants", "Une intercommunalité regroupant plusieurs communes voisines", "Une aire d'influence urbaine et de ses marges"], 0,
     "Le critère est de moins de deux cents mètres entre constructions et plus de deux mille habitants."],
    ["Qu'est-ce que la métropolisation ?", ["Une concentration croissante des activités et des populations dans les grandes villes", "La création de métropoles au statut administratif particulier", "L'extension continue des banlieues pavillonnaires", "Un exode rural massif vers les villes industrielles"], 0,
     "Elle s'accompagne d'une spécialisation des grandes villes dans les fonctions de commandement."],
    ["Quelle ville française a la plus forte croissance démographique récente ?", ["Toulouse, parmi les grandes villes", "Paris, la plus peuplée des villes françaises", "Marseille, deuxième commune de France", "Lille, au cœur des Hauts-de-France"], 0,
     "L'attractivité de l'arc atlantique et du Sud caractérise la géographie démographique récente."],
    ["Qu'est-ce que le Grand Paris ?", ["Un projet de développement métropolitain incluant un réseau de transport", "Une fusion de toutes les communes de la petite couronne en une seule ville", "Un agrandissement de la ville de Paris par annexion des communes voisines", "Un plan d'urbanisme régional opposable aux communes"], 0,
     "Le Grand Paris Express prévoit environ deux cents kilomètres de lignes automatiques nouvelles."],
    ["Qu'est-ce qu'une ville moyenne en France ?", ["Une ville de vingt mille à cent mille habitants environ", "Une ville de plus de cent mille habitants et son agglomération", "Un chef-lieu de département quelle que soit sa population", "Une ville de moins de vingt mille habitants"], 0,
     "Le programme Action cœur de ville leur est spécifiquement destiné depuis 2018."],
    ["Qu'est-ce que la vacance commerciale en centre-ville ?", ["La proportion de locaux commerciaux inoccupés", "La fermeture saisonnière des commerces de centre-ville", "Le taux de rotation annuel des enseignes", "Le nombre de commerces pour mille habitants"], 0,
     "Elle a fortement progressé dans les villes moyennes depuis les années 2010."],
    ["Qu'est-ce que la renaissance des centres-villes ?", ["Un ensemble de politiques visant à réhabiliter logements et commerces centraux", "Un retour tout à fait spontané des habitants vers les logements anciens des cœurs de ville", "Une piétonnisation généralisée des rues commerçantes", "Une politique patrimoniale de restauration des façades anciennes"], 0,
     "Elle combine habitat, commerce, transport et espaces publics dans une approche globale.", 3],
  ]),

  notion("geo3-espaces-productifs", S, "Les espaces productifs",
    "Industrie, services, agriculture dans l'espace.",
    "Un espace productif se transforme au rythme des mutations économiques.",
    2, [
    ["Qu'est-ce qu'un espace productif ?", ["Un territoire organisé par une activité économique dominante", "Une zone industrielle aménagée en périphérie d'une grande agglomération", "Un bassin d'emploi délimité par les déplacements domicile-travail", "Une région où l'agriculture emploie plus d'un actif sur dix"], 0,
     "Il peut être agricole, industriel, de services ou touristique."],
    ["Qu'est-ce qu'un système productif localisé ?", ["Un ensemble d'entreprises d'un même secteur concentrées sur un territoire", "Une zone d'activité viabilisée par une collectivité locale", "Un groupement d'employeurs partageant des salariés à temps partagé", "Une chaîne logistique organisée autour d'un entrepôt régional"], 0,
     "La Vallée de l'Arve pour le décolletage en est un exemple français."],
    ["Qu'est-ce qu'un pôle de compétitivité ?", ["Un regroupement d'entreprises, laboratoires et écoles sur un territoire et un thème", "Une zone franche exonérant les entreprises de charges sociales pendant leurs cinq premières années", "Un parc d'activités doté d'équipements et de services mutualisés", "Un incubateur hébergeant de jeunes entreprises pendant leurs premiers mois"], 0,
     "Le dispositif a été lancé en France en 2005 pour stimuler l'innovation collaborative."],
    ["Qu'est-ce qu'une technopole ?", ["Un site associant recherche, formation et entreprises innovantes", "Une ville dont l'industrie ancienne a été entièrement modernisée", "Un parc technologique loué en totalité à des entreprises du numérique", "Une zone d'activité tertiaire regroupant bureaux et sociétés de services"], 0,
     "Sophia Antipolis, créée en 1969, est la plus ancienne de France."],
    ["Qu'est-ce qu'une friche industrielle ?", ["Un site d'activité abandonné, souvent pollué", "Une zone en construction dont le chantier est interrompu", "Un terrain agricole laissé sans culture depuis plusieurs années", "Un entrepôt vacant depuis la fermeture de son exploitant"], 0,
     "Leur reconversion est freinée par le coût de la dépollution."],
    ["Qu'est-ce que la reconversion d'un bassin industriel ?", ["Un processus de transformation économique après le déclin d'une activité dominante", "Une modernisation complète des usines existantes sans changement de la production fabriquée", "Un changement de propriétaire à la suite d'un rachat", "Un transfert de la production vers un pays à bas coûts"], 0,
     "Elle prend des décennies et ne réussit pas partout avec la même intensité."],
    ["Qu'est-ce qu'un espace logistique ?", ["Un territoire spécialisé dans le stockage et la distribution", "Une zone portuaire équipée pour le transbordement des conteneurs", "Un nœud autoroutier où convergent plusieurs grands axes de transit", "Un centre de transport routier doté d'ateliers et de parkings"], 0,
     "Le commerce en ligne a fortement accru la demande d'entrepôts près des grandes agglomérations."],
    ["Qu'est-ce que le tertiaire supérieur ?", ["Des activités de conception, de gestion et de décision à haute qualification", "Le commerce de détail et la distribution alimentaire dans les quartiers de proximité", "Les services à la personne rendus au domicile même des particuliers âgés ou dépendants", "L'administration publique et ses services déconcentrés"], 0,
     "Sa concentration dans les métropoles explique une grande part des écarts territoriaux."],
    ["Qu'est-ce que l'économie présentielle ?", ["Des activités destinées aux populations présentes sur un territoire", "L'économie locale traditionnelle des campagnes", "La seule économie touristique saisonnière", "Le seul commerce de proximité des bourgs"], 0,
     "Elle peut soutenir des territoires peu industrialisés mais attractifs pour les retraités ou les touristes."],
    ["Qu'est-ce qu'un espace touristique littoral aménagé ?", ["Un littoral équipé et transformé pour accueillir des flux touristiques", "Une station balnéaire ancienne héritée des bains de mer du dix-neuvième siècle", "Un port de plaisance aménagé pour accueillir les bateaux de tourisme et leurs équipages", "Une zone naturelle protégée et fermée à toute construction nouvelle sur le rivage"], 0,
     "La mission Racine a ainsi aménagé le littoral languedocien à partir de 1963.", 3],
  ]),
];
