/**
 * Histoire du monde, quatrième lot — vingt-deux notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Histoire du monde";

export const CG_HISTOIRE_MONDE_4: SeedSkill[] = [
  notion("hm4-mesopotamie", S, "Entre Tigre et Euphrate",
    "Cités, lois, écriture.",
    "Les premières cités-États du monde sont apparues entre le Tigre et l'Euphrate.",
    2, [
    ["Quelle civilisation a fondé les premières cités de Mésopotamie ?", ["Les Sumériens", "Les Akkadiens", "Les Assyriens", "Les Babyloniens"], 0,
     "Ur, Uruk et Lagash comptent parmi leurs cités les plus importantes."],
    ["Quel roi akkadien a fondé le premier empire connu ?", ["Sargon d'Akkad", "Hammurabi", "Gilgamesh", "Assurbanipal"], 0,
     "Son empire, au XXIVe siècle avant notre ère, réunit les cités sumériennes."],
    ["Qu'est-ce que le code de Hammurabi ?", ["Un recueil de lois babylonien gravé sur une stèle", "Un traité religieux sur le culte de Mardouk", "Un texte administratif de la cité d'Ur", "Un recueil de sentences royales assyriennes"], 0,
     "La stèle, découverte à Suse, est conservée au musée du Louvre."],
    ["Qu'est-ce qu'une ziggourat ?", ["Une tour à degrés surmontée d'un sanctuaire", "Une tour de défense", "Un palais royal", "Un tombeau monumental"], 0,
     "Bâtie en briques crues sous un parement de briques cuites, elle dominait le temple de la cité. Celle d'Ur est la mieux conservée."],
    ["Qu'est-ce que l'Épopée de Gilgamesh ?", ["Le plus ancien grand récit littéraire connu", "Une chronique royale des rois d'Akkad", "Un texte religieux babylonien sur la création du monde", "Un recueil de mythes sumériens sur les dieux"], 0,
     "Elle contient notamment un récit de déluge antérieur au texte biblique."],
    ["Quelle bibliothèque antique a été retrouvée à Ninive ?", ["Celle d'Assurbanipal", "Celle de Nabuchodonosor", "Celle de Sargon", "Celle de Hammurabi"], 0,
     "Des dizaines de milliers de tablettes y ont été mises au jour."],
    ["Qu'est-ce que l'empire néo-assyrien ?", ["Un empire militaire dominant le Proche-Orient aux IXe-VIIe siècles avant notre ère", "Un royaume babylonien tardif né après la chute d'Assur", "Un empire perse ancien antérieur aux Achéménides", "Un royaume araméen de haute Mésopotamie"], 0,
     "Sa chute en 612 avant notre ère marque un basculement régional."],
    ["Qui était Nabuchodonosor II ?", ["Un roi babylonien qui a détruit le Temple de Jérusalem", "Un roi assyrien conquérant qui a pris l'Égypte et pillé Thèbes", "Un souverain perse achéménide, successeur direct de Cyrus", "Un roi akkadien successeur de Sargon"], 0,
     "La déportation des Judéens à Babylone date de son règne."],
    ["Qu'est-ce que le système sexagésimal mésopotamien ?", ["Un système de numération en base soixante", "Un calendrier lunaire de douze mois", "Un système de poids et de mesures", "Une numération décimale, en base dix"], 0,
     "Nos soixante minutes et nos trois cent soixante degrés en descendent directement."],
    ["Qu'apporte la Mésopotamie à l'histoire mondiale ?", ["L'écriture, le droit écrit et l'urbanisation", "L'agriculture, inventée par les Sumériens", "La métallurgie du fer et du bronze", "La monnaie frappée"], 0,
     "L'agriculture est plus ancienne et la monnaie plus tardive.", 3],
  ]),

  notion("hm4-egypte-ancienne", S, "L'Égypte ancienne",
    "Dynasties, croyances, monuments.",
    "L'histoire pharaonique s'étend sur plus de trois mille ans.",
    2, [
    ["Quel pharaon la palette de Nekhen montre-t-elle coiffé des deux couronnes ?", ["Narmer, vers 3100 avant notre ère", "Djéser, à l'Ancien Empire", "Khéops, à la IVe dynastie", "Amenhotep III, au Nouvel Empire"], 0,
     "Elle le montre portant tour à tour la couronne blanche de Haute-Égypte et la rouge de Basse-Égypte : c'est la plus ancienne image connue de l'unification. Les listes royales postérieures attribuent celle-ci à un Ménès que les égyptologues identifient le plus souvent à Narmer lui-même."],
    ["Quelle pyramide est la plus ancienne pyramide égyptienne connue ?", ["La pyramide à degrés de Djéser", "La pyramide de Khéops, à Gizeh", "La pyramide rhomboïdale", "La pyramide rouge de Snéfrou"], 0,
     "Conçue par l'architecte Imhotep à Saqqarah."],
    ["Qu'est-ce que le Nouvel Empire égyptien ?", ["Une période d'apogée entre le XVIe et le XIe siècle avant notre ère", "La période des grandes pyramides de Gizeh", "L'époque ptolémaïque, après Alexandre", "La Basse Époque, avant la conquête perse"], 0,
     "Thoutmôsis III, Ramsès II et Toutânkhamon en sont des figures."],
    ["Quel pharaon a tenté d'imposer le culte d'un dieu unique ?", ["Akhenaton", "Ramsès II", "Toutânkhamon", "Aménophis III"], 0,
     "Le culte d'Aton a été abandonné dès après sa mort."],
    ["Quelle reine égyptienne a régné en tant que pharaon au XVe siècle avant notre ère ?", ["Hatchepsout", "Néfertiti, épouse d'Akhenaton", "Cléopâtre, bien plus tard", "Néfertari, épouse de Ramsès II"], 0,
     "Son temple de Deir el-Bahari est l'un des plus remarquables d'Égypte."],
    ["Quelle bataille Ramsès II a-t-il livrée contre les Hittites ?", ["La bataille de Qadesh", "La bataille de Megiddo", "La bataille de Karkemish", "La bataille de Pelusium"], 0,
     "Elle a débouché sur l'un des plus anciens traités de paix connus."],
    ["Que contenait le Livre des Morts égyptien ?", ["Un recueil de formules destinées à guider le défunt", "Une chronique funéraire des règnes royaux", "Un registre des sépultures de la Vallée des Rois", "Un traité religieux réservé à la famille royale"], 0,
     "Les formules étaient déposées dans la tombe, souvent sur papyrus."],
    ["Qu'est-ce que la momification ?", ["Une préparation du corps visant à le conserver pour l'au-delà", "Un embaumement réservé aux prêtres du temple", "Un rite funéraire réservé aux seuls pharaons et à leur famille", "Une conservation par dessiccation naturelle dans le sable du désert"], 0,
     "Le natron, un sel naturel, en était l'agent principal."],
    ["Qui a déchiffré les hiéroglyphes ?", ["Jean-François Champollion", "Thomas Young, le premier", "Auguste Mariette, fondateur du musée du Caire", "Karl Lepsius, l'Allemand"], 0,
     "En 1822, à partir de la pierre de Rosette."],
    ["Comment l'Égypte pharaonique s'achève-t-elle ?", ["Par l'annexion romaine après la mort de Cléopâtre", "Par la conquête perse de Cambyse", "Par la conquête d'Alexandre le Grand", "Par la conquête arabe du VIIe siècle"], 0,
     "Elle devient province romaine en 30 avant notre ère.", 3],
  ]),

  notion("hm4-perse", S, "L'empire perse",
    "Achéménides, satrapies, guerres.",
    "L'empire achéménide fut le plus vaste que le monde ait connu à son époque.",
    2, [
    ["Qui a fondé l'empire achéménide ?", ["Cyrus II", "Darius Ier", "Xerxès Ier", "Cambyse II"], 0,
     "Il conquiert la Médie, la Lydie et Babylone au VIe siècle avant notre ère."],
    ["Qu'est-ce que le cylindre de Cyrus ?", ["Une inscription babylonienne relatant sa prise de Babylone", "Un code de lois perse gravé sur argile", "Une déclaration des droits des peuples soumis", "Un traité de paix conclu avec les Mèdes"], 0,
     "Souvent présenté comme une première charte des droits, il relève d'une tradition royale babylonienne."],
    ["Qu'est-ce qu'une satrapie ?", ["Une province de l'empire perse dirigée par un gouverneur", "Une cité autonome dotée de ses propres lois", "Un district militaire commandé par un général", "Une région tributaire versant un impôt annuel"], 0,
     "Darius Ier en a organisé une vingtaine."],
    ["Qu'est-ce que la route royale perse ?", ["Un axe reliant Suse à Sardes sur plus de deux mille kilomètres", "Une voie commerciale reliant l'empire à l'Inde", "Une route militaire menant jusqu'en Égypte", "Un tronçon occidental de la route de la soie"], 0,
     "Des relais de poste permettaient d'en parcourir la longueur en une semaine."],
    ["Qu'est-ce que Persépolis ?", ["Une capitale cérémonielle achéménide", "La capitale administrative de l'empire", "Une cité fondée par Cyrus le Grand à Pasargades", "Une place forte médique dominant les hauts plateaux"], 0,
     "Alexandre le Grand l'a incendiée en 330 avant notre ère."],
    ["Quelle religion dominait l'empire perse ?", ["Le zoroastrisme", "Le mithraïsme", "Le manichéisme", "Le mazdéisme tardif"], 0,
     "Elle repose sur l'opposition entre un principe de bien et un principe de mal."],
    ["Quelle bataille a opposé Perses et Grecs en 490 avant notre ère ?", ["La bataille de Marathon", "La bataille de Salamine", "La bataille des Thermopyles", "La bataille de Platées"], 0,
     "La victoire athénienne y a un retentissement considérable."],
    ["Quel roi perse a mené la seconde guerre médique ?", ["Xerxès Ier", "Darius Ier", "Artaxerxès Ier", "Cyrus le Jeune"], 0,
     "Sa campagne s'achève par les défaites de Salamine et Platées."],
    ["Qu'est-ce que l'empire sassanide ?", ["Un empire perse rival de Rome du IIIe au VIIe siècle", "Un royaume parthe des IIe et Ier siècles avant notre ère", "Un empire achéménide tardif, avant Alexandre", "Un royaume perse hellénistique issu des Séleucides"], 0,
     "Il tombe face aux conquêtes arabes au VIIe siècle."],
    ["Quel héritage l'empire perse a-t-il laissé ?", ["Un modèle d'administration impériale tolérante des cultures locales", "Un système juridique unifié imposé à l'ensemble des provinces de l'empire", "Une langue commune imposée à l'ensemble des peuples soumis de l'empire", "Une religion universelle imposée par les Grands Rois"], 0,
     "Cette souplesse a servi de référence aux empires ultérieurs.", 3],
  ]),

  notion("hm4-inde-ancienne", S, "L'Inde ancienne",
    "Indus, Maurya, Gupta.",
    "La civilisation de l'Indus est l'une des trois grandes civilisations urbaines primitives.",
    2, [
    ["Qu'est-ce que la civilisation de l'Indus ?", ["Une civilisation urbaine du IIIe millénaire avant notre ère", "Une culture védique installée dans toute la plaine gangétique", "Un royaume maurya antérieur à Ashoka", "Une civilisation urbaine du bassin du Gange"], 0,
     "Mohenjo-daro et Harappa en sont les principaux sites."],
    ["Quelle particularité les villes de l'Indus présentaient-elles ?", ["Un urbanisme planifié avec un réseau d'évacuation des eaux", "Des fortifications monumentales entourant chacun des quartiers", "Des palais royaux imposants élevés au centre de chaque cité", "Des temples centraux dominant la ville basse"], 0,
     "Aucun palais ni temple monumental n'y a été identifié avec certitude."],
    ["Que sait-on de l'écriture de l'Indus ?", ["Elle n'a jamais été déchiffrée", "Elle est déchiffrée depuis 1950", "Elle dérive du cunéiforme", "Elle n'existait pas"], 0,
     "Les inscriptions connues sont très courtes, ce qui complique tout déchiffrement."],
    ["Qu'est-ce que la période védique ?", ["Une période marquée par la composition des Veda", "L'époque des royaumes de la plaine du Gange", "La période maurya, bien postérieure", "Le seul âge des Upanishad, plus tardif"], 0,
     "Elle succède au déclin de la civilisation de l'Indus."],
    ["Qui a fondé l'empire maurya ?", ["Chandragupta Maurya", "Ashoka, son petit-fils", "Bindusara, son fils", "Kanishka, bien plus tard"], 0,
     "Il unifie une grande partie du sous-continent à la fin du IVe siècle avant notre ère."],
    ["Quel empereur maurya s'est converti au bouddhisme ?", ["Ashoka", "Chandragupta", "Bindusara", "Harsha"], 0,
     "Après la guerre du Kalinga, dont il déplore la violence dans ses édits."],
    ["Qu'est-ce que les édits d'Ashoka ?", ["Des inscriptions royales gravées sur piliers et rochers", "Un code de lois bouddhiste imposé à l'empire", "Des décrets administratifs adressés aux gouverneurs", "Des textes religieux canoniques du bouddhisme ancien"], 0,
     "Ils constituent les plus anciens documents écrits déchiffrés d'Inde."],
    ["Qu'est-ce que l'empire gupta ?", ["Un empire du IVe au VIe siècle, âge classique de l'Inde", "Un empire bouddhiste du Deccan méridional", "Un royaume du Deccan contemporain de l'Empire romain", "Un empire médiéval du nord de l'Inde, postérieur à l'an mil"], 0,
     "Mathématiques, astronomie et littérature sanskrite y connaissent un apogée."],
    ["Quelle invention mathématique majeure vient de l'Inde ancienne ?", ["Le zéro comme nombre et la numération de position", "L'algèbre et la résolution des équations du second degré", "La géométrie des autels védiques", "La trigonométrie et les premières tables de sinus"], 0,
     "Brahmagupta en formule des règles d'usage au VIIe siècle."],
    ["Comment le bouddhisme s'est-il diffusé hors d'Inde ?", ["Par les routes commerciales vers l'Asie centrale et l'Asie de l'Est", "Par des conquêtes militaires en Asie centrale", "Par des migrations de populations entières vers l'est", "Par la colonisation de terres nouvelles"], 0,
     "Il a fini par décliner en Inde même, tout en s'implantant durablement ailleurs.", 3],
  ]),

  notion("hm4-chine-imperiale", S, "Les dynasties chinoises",
    "Dynasties, administration, inventions.",
    "L'empire chinois a duré plus de deux mille ans sous des dynasties successives.",
    2, [
    ["Qui a unifié la Chine en 221 avant notre ère ?", ["Qin Shi Huang", "L'empereur Wu des Han", "Liu Bang", "Le duc de Zhou"], 0,
     "Il unifie aussi les poids, les mesures et l'écriture."],
    ["Qu'est-ce que l'armée de terre cuite ?", ["Des milliers de statues enterrées près du tombeau du premier empereur", "Une garde impériale sculptée", "Un ensemble votif Han", "Un monument funéraire Tang"], 0,
     "Découverte en 1974 par des paysans creusant un puits."],
    ["Quelle dynastie a duré environ quatre siècles après les Qin ?", ["Les Han", "Les Tang", "Les Song", "Les Sui"], 0,
     "Les Chinois han tirent leur nom de cette dynastie."],
    ["Qu'est-ce que le système des examens impériaux ?", ["Un concours de recrutement des fonctionnaires fondé sur les classiques", "Une sélection militaire", "Un examen de noblesse", "Un système de recommandation"], 0,
     "Il a fonctionné jusqu'en 1905, avec des interruptions."],
    ["Quelle dynastie correspond à un apogée culturel aux VIIe-IXe siècles ?", ["Les Tang", "Les Song", "Les Ming", "Les Han"], 0,
     "Poésie, peinture et ouverture aux cultures étrangères y culminent."],
    ["Quelle dynastie a vu l'essor de l'imprimerie et de la monnaie de papier ?", ["Les Song", "Les Tang", "Les Ming", "Les Yuan"], 0,
     "Une véritable révolution économique s'y produit du Xe au XIIIe siècle."],
    ["Quelle dynastie mongole a régné sur la Chine ?", ["Les Yuan", "Les Qing", "Les Liao", "Les Jin"], 0,
     "Fondée par Kubilai Khan, petit-fils de Gengis Khan."],
    ["Quelle dynastie a fait construire la Cité interdite ?", ["Les Ming", "Les Qing", "Les Yuan", "Les Song"], 0,
     "Le transfert de la capitale à Pékin date du règne de Yongle."],
    ["Qui était Zheng He ?", ["Un amiral chinois ayant mené sept grandes expéditions maritimes", "Un explorateur terrestre", "Un ambassadeur Ming", "Un marchand de la route de la soie"], 0,
     "Ses flottes ont atteint l'Afrique de l'Est au début du XVe siècle."],
    ["Quelle dernière dynastie a régné sur la Chine ?", ["Les Qing, d'origine mandchoue", "Les Ming", "Les Yuan", "Les Han"], 0,
     "Elle s'achève avec l'abdication de Puyi en 1912.", 3],
  ]),

  notion("hm4-japon-histoire", S, "Le Japon, des shoguns à Meiji",
    "Shogunats, isolement, modernisation.",
    "Le Japon a connu près de sept siècles de gouvernement militaire.",
    2, [
    ["Qu'est-ce qu'un shogun ?", ["Un chef militaire exerçant le pouvoir réel au nom de l'empereur", "Un empereur militaire élu par les seigneurs", "Un seigneur régional maître d'un domaine", "Un gouverneur impérial nommé par la cour"], 0,
     "L'empereur conservait une légitimité religieuse sans pouvoir effectif."],
    ["Qu'est-ce qu'un daimyo ?", ["Un seigneur territorial japonais", "Un samouraï de haut rang", "Un ministre du shogun", "Un gouverneur de province impérial"], 0,
     "Ils entretenaient leurs propres armées de samouraïs."],
    ["Qu'est-ce que l'époque d'Edo ?", ["Une période de paix sous le shogunat Tokugawa, de 1603 à 1868", "Une longue période de guerre civile entre les seigneurs des provinces", "L'ère de la restauration impériale et de l'ouverture au monde", "La période Meiji, de 1868 à 1912"], 0,
     "Elle est marquée par une fermeture largement contrôlée du pays."],
    ["Qu'est-ce que le sakoku ?", ["Une politique de fermeture du Japon aux étrangers", "Un système féodal de vassalité militaire", "Un code d'honneur des samouraïs", "Une réforme agraire des domaines seigneuriaux"], 0,
     "Seuls quelques échanges très encadrés subsistaient, notamment à Nagasaki."],
    ["Qui a forcé l'ouverture du Japon en 1853 ?", ["Le commodore Perry", "Les Britanniques, depuis Hong Kong", "Les Russes, par le nord", "Les Néerlandais de Nagasaki"], 0,
     "Ses navires à vapeur, appelés les bateaux noirs, ont marqué les esprits."],
    ["Qu'est-ce que la restauration Meiji ?", ["Un retour du pouvoir à l'empereur en 1868, suivi d'une modernisation rapide", "Une restauration du shogunat Tokugawa après 1868", "Une réforme militaire de l'armée impériale", "Une révolution populaire menée par les paysans"], 0,
     "En une génération, le Japon se dote d'une industrie et d'une armée modernes."],
    ["Quelle guerre le Japon a-t-il gagnée contre la Russie en 1905 ?", ["La guerre russo-japonaise", "La première guerre sino-japonaise", "La guerre de Corée", "La guerre de Mandchourie"], 0,
     "C'est la première victoire d'une puissance asiatique sur une puissance européenne moderne."],
    ["Qu'est-ce que l'ère Shōwa ?", ["Le règne de l'empereur Hirohito, de 1926 à 1989", "La période Meiji tardive, avant 1912", "L'ère Taishō, de 1912 à 1926", "L'après-guerre japonais, à partir de 1945"], 0,
     "Elle couvre la guerre, la défaite et le miracle économique."],
    ["Quand le Japon a-t-il attaqué Pearl Harbor ?", ["Le 7 décembre 1941", "Le 1er septembre 1939", "Le 7 décembre 1942", "Le 8 décembre 1940"], 0,
     "L'attaque provoque l'entrée en guerre des États-Unis."],
    ["Sur quelle période s'étend le miracle économique japonais ?", ["Une croissance très rapide des années 1950 aux années 1980", "Une reconstruction d'après-guerre financée par l'aide américaine", "Une industrialisation commencée dès l'ère Meiji, avant 1900", "Une expansion des années 1990 et 2000"], 0,
     "Elle s'achève avec l'éclatement d'une bulle spéculative au début des années 1990.", 3],
  ]),

  notion("hm4-afrique-royaumes", S, "Royaumes et empires africains",
    "Ghana, Mali, Songhaï, Éthiopie.",
    "Plusieurs grands empires ont structuré l'Afrique de l'Ouest médiévale.",
    2, [
    ["Qu'est-ce que l'empire du Ghana médiéval ?", ["Un empire ouest-africain prospérant par le commerce transsaharien", "Le territoire de l'actuel Ghana, sur le golfe de Guinée", "Un royaume côtier du golfe de Guinée", "Un empire du Sahel oriental établi autour du lac Tchad et du Nil"], 0,
     "Il se situait bien plus au nord que l'État moderne qui a repris son nom."],
    ["Quel empereur du Mali a marqué son pèlerinage à La Mecque ?", ["Mansa Moussa", "Soundiata Keïta", "Askia Mohammed", "Sunni Ali"], 0,
     "Ses dépenses en or auraient déstabilisé les cours au Caire en 1324."],
    ["Qui a fondé l'empire du Mali ?", ["Soundiata Keïta", "Mansa Moussa", "Sunni Ali Ber", "Askia Mohammed"], 0,
     "La Charte du Manden lui est traditionnellement associée."],
    ["Qu'est-ce que le royaume d'Aksoum ?", ["Un royaume de la Corne de l'Afrique christianisé au IVe siècle", "Un royaume nubien christianisé du Moyen Nil", "Un sultanat somalien de la côte de l'océan Indien, converti à l'islam", "Un royaume yéménite installé des deux côtés de la mer Rouge, avant l'islam"], 0,
     "Il frappait sa propre monnaie et contrôlait le commerce de la mer Rouge."],
    ["Qu'est-ce que le royaume du Kongo ?", ["Un royaume d'Afrique centrale en contact précoce avec le Portugal", "Un royaume d'Afrique de l'Est ouvert sur l'océan Indien et l'Arabie", "Un empire sahélien du commerce transsaharien", "Un royaume du Congo créé à l'époque coloniale belge"], 0,
     "Son souverain s'est converti au christianisme dès la fin du XVe siècle."],
    ["Qu'est-ce que le Grand Zimbabwe ?", ["Une cité de pierre d'Afrique australe des XIIIe-XVe siècles", "Un royaume swahili", "Une cité minière portugaise", "Un site funéraire bantou"], 0,
     "Ses murailles sèches, sans mortier, s'élèvent à plus de dix mètres."],
    ["Qu'est-ce que la civilisation swahilie ?", ["Un ensemble de cités marchandes de la côte est-africaine", "Un empire intérieur des Grands Lacs", "Une confédération de cités arabes de la péninsule Arabique", "Un royaume insulaire de l'archipel de Zanzibar"], 0,
     "Kilwa, Mombasa et Zanzibar en étaient des pôles majeurs."],
    ["Pourquoi l'histoire africaine précoloniale est-elle longtemps restée méconnue ?", ["Elle a été négligée par une historiographie centrée sur l'écrit européen", "Elle n'a laissé aucune trace", "Les sources ont disparu", "Elle a été détruite lors de la colonisation"], 0,
     "Traditions orales, archéologie et sources arabes en permettent l'étude.", 3],
  ]),

  notion("hm4-amerique-precolombienne", S, "L'Amérique précolombienne",
    "Mayas, Aztèques, Incas.",
    "Trois grandes civilisations dominaient l'Amérique à l'arrivée des Européens.",
    2, [
    ["Quelle civilisation mésoaméricaine a développé une écriture complète ?", ["Les Mayas", "Les Aztèques", "Les Olmèques", "Les Zapotèques"], 0,
     "Leur écriture, largement déchiffrée depuis les années 1980, est logosyllabique."],
    ["Qu'est-ce que le calendrier maya à compte long ?", ["Un système datant les événements depuis une date d'origine", "Un calendrier lunaire de treize mois", "Un cycle agricole de trois cent soixante-cinq jours", "Un calendrier rituel de deux cent soixante jours"], 0,
     "Il a alimenté à tort les prédictions de fin du monde pour 2012."],
    ["Qu'est-ce que la civilisation olmèque ?", ["La plus ancienne grande civilisation mésoaméricaine connue", "Une culture maya primitive du Yucatán", "Une civilisation andine antérieure aux Incas", "Une culture toltèque du plateau central"], 0,
     "Ses têtes colossales de pierre en sont le vestige le plus spectaculaire."],
    ["Qu'est-ce que Teotihuacan ?", ["Une immense cité antérieure aux Aztèques", "La capitale toltèque de Tula", "Une cité maya du nord de la péninsule du Yucatán", "Une ville aztèque secondaire de la vallée de Mexico"], 0,
     "Son origine et l'identité de ses fondateurs restent débattues."],
    ["Qu'est-ce qu'une chinampa ?", ["Un jardin flottant cultivé sur les lacs aztèques", "Une terrasse agricole aménagée sur les pentes", "Un canal d'irrigation creusé entre les lacs", "Un champ surélevé des hautes terres andines"], 0,
     "Ce système offrait des rendements exceptionnels autour de Tenochtitlan."],
    ["Comment l'empire inca s'appelait-il ?", ["Le Tawantinsuyu", "Le Cuzco", "L'empire du Soleil", "Le Chinchaysuyu"], 0,
     "Le nom signifie les quatre régions réunies."],
    ["Qu'est-ce qu'un quipu ?", ["Un ensemble de cordelettes nouées servant à enregistrer des données", "Un calendrier inca fondé sur les cycles solaires", "Un instrument de mesure des distances le long des chemins de l'empire", "Une écriture pictographique peinte sur les tissus"], 0,
     "Leur capacité à encoder autre chose que des nombres reste discutée."],
    ["Qu'est-ce que le Machu Picchu ?", ["Un site inca d'altitude construit au XVe siècle", "Une forteresse de la résistance inca contre les Espagnols", "Une cité préinca de la vallée sacrée", "Un centre religieux colonial bâti par les jésuites"], 0,
     "Il a probablement servi de résidence royale et de centre religieux."],
    ["Quelle cause a le plus contribué à l'effondrement démographique amérindien ?", ["Les maladies apportées par les Européens", "Les guerres de conquête menées par les Espagnols", "Le travail forcé dans les mines d'argent", "Les famines provoquées par la conquête"], 0,
     "Variole, rougeole et typhus ont décimé des populations sans immunité.", 3],
  ]),

  notion("hm4-empire-byzantin", S, "Byzance, mille ans d'empire",
    "Constantinople, Justinien, chute.",
    "L'Empire romain d'Orient a survécu mille ans à la chute de Rome.",
    2, [
    ["Quand Constantinople a-t-elle été fondée comme capitale ?", ["En 330, par Constantin", "En 395, au partage de l'Empire", "En 476, à la chute de Rome", "En 285"], 0,
     "Sur le site de l'ancienne cité grecque de Byzance."],
    ["Quel empereur byzantin a reconquis une partie de l'Occident ?", ["Justinien", "Héraclius", "Basile II", "Constantin V"], 0,
     "Ses généraux reprennent l'Afrique du Nord, l'Italie et une partie de l'Espagne."],
    ["Qu'est-ce que le Code Justinien ?", ["Une compilation du droit romain au VIe siècle", "Un code entièrement nouveau en grec", "Un recueil de droit canonique oriental", "Un code militaire à l'usage des armées"], 0,
     "Il a transmis le droit romain à l'Europe médiévale et moderne."],
    ["Qu'est-ce que Sainte-Sophie ?", ["Une basilique construite sous Justinien à Constantinople", "Une église fondée par Constantin et jamais reconstruite", "Une cathédrale latine bâtie après 1204", "Un palais impérial voisin de l'hippodrome"], 0,
     "Devenue mosquée en 1453, puis musée en 1935, puis à nouveau mosquée en 2020."],
    ["Qu'est-ce que la querelle des images à Byzance ?", ["Un conflit sur la licéité des représentations religieuses", "Un débat théologique sur la Trinité et la nature du Christ", "Une controverse liturgique sur la langue des offices", "Un conflit sur le culte des reliques et des saints"], 0,
     "L'iconoclasme a divisé l'empire aux VIIIe et IXe siècles."],
    ["À quoi les Byzantins employaient-ils le feu grégeois ?", ["Une arme incendiaire navale byzantine", "Un explosif ancien à base de salpêtre", "Une flèche enflammée tirée depuis les remparts", "Un mélange de poudre noire venu de Chine"], 0,
     "Sa composition exacte reste inconnue aujourd'hui."],
    ["Quel événement de 1054 a divisé la chrétienté ?", ["Le schisme entre Rome et Constantinople", "La chute de Constantinople devant les Ottomans", "La première croisade et la prise de Jérusalem", "Le concile de Nicée et sa profession de foi"], 0,
     "Les excommunications mutuelles n'ont été levées qu'en 1965."],
    ["Que s'est-il passé lors de la quatrième croisade ?", ["Constantinople a été pillée par les croisés en 1204", "Jérusalem a été reprise aux musulmans par les croisés", "L'Égypte a été conquise, comme le prévoyait le plan initial", "Les croisés ont échoué devant les places fortes de Syrie"], 0,
     "L'empire ne s'en est jamais totalement remis."],
    ["Quand Constantinople est-elle tombée ?", ["En 1453, face aux Ottomans", "En 1204, un premier assaut", "En 1461, à la chute de Trébizonde", "En 1492"], 0,
     "Mehmed II en fait la capitale de l'Empire ottoman."],
    ["Quel héritage Byzance a-t-elle laissé ?", ["La transmission du droit romain et de la culture grecque", "Un empire commercial rival de Venise et de Gênes", "Une organisation militaire copiée par les Ottomans", "Un modèle politique républicain transmis à l'Italie"], 0,
     "L'exil de ses savants a nourri la Renaissance italienne.", 3],
  ]),

  notion("hm4-monde-musulman", S, "Le monde musulman médiéval",
    "Califats, savoirs, échanges.",
    "Le monde musulman médiéval a été un carrefour majeur de savoirs.",
    2, [
    ["Qu'est-ce que le califat omeyyade ?", ["Un califat dont la capitale était Damas, de 661 à 750", "Un califat de Bagdad, fondé par les Perses", "Un califat égyptien d'Alexandrie", "Le seul califat andalou, à Cordoue"], 0,
     "Une branche omeyyade s'est ensuite maintenue en al-Andalus."],
    ["Qu'est-ce que le califat abbasside ?", ["Un califat installé à Bagdad à partir de 762", "Un califat de Damas, au XIIe siècle", "Un califat fatimide de Kairouan", "Un califat ottoman établi à Istanbul après 1517"], 0,
     "Son apogée culturel se situe aux VIIIe et IXe siècles."],
    ["Qu'est-ce que la Maison de la sagesse ?", ["Un centre de traduction et de recherche à Bagdad", "Une université cairote fondée par les Fatimides en 970", "Une bibliothèque andalouse rassemblée par les califes de Cordoue", "Une école de droit malikite"], 0,
     "Des textes grecs, persans et indiens y ont été traduits en arabe."],
    ["Qui était al-Khwarizmi ?", ["Un mathématicien à l'origine du mot algorithme", "Un médecin persan de Bagdad", "Un astronome andalou de l'école de Tolède", "Un philosophe de Bagdad commentateur de Platon"], 0,
     "Le mot algèbre vient du titre de l'un de ses ouvrages."],
    ["Qui était Avicenne ?", ["Un médecin et philosophe persan auteur du Canon de la médecine", "Un mathématicien arabe auteur de tables astronomiques et de traités d'algèbre", "Un astronome égyptien de l'époque fatimide, auteur d'un traité d'optique", "Un juriste andalou de l'école malikite"], 0,
     "Son Canon a été enseigné dans les universités européennes pendant des siècles."],
    ["Qui était Averroès ?", ["Un philosophe andalou commentateur d'Aristote", "Un médecin de Bagdad, maître des hôpitaux", "Un juriste persan de l'école hanéfite", "Un astronome maghrébin de Marrakech"], 0,
     "Ses commentaires ont profondément marqué la scolastique latine."],
    ["Qu'est-ce qu'al-Andalus ?", ["La partie de la péninsule Ibérique sous domination musulmane", "Un royaume maghrébin des Almoravides", "Une province fatimide de Méditerranée occidentale", "Un émirat nord-africain rattaché à Kairouan"], 0,
     "Elle a duré de 711 à 1492, avec une emprise territoriale variable."],
    ["Qu'est-ce que le califat fatimide ?", ["Un califat chiite fondé au Maghreb puis établi au Caire", "Un califat sunnite égyptien rival de Bagdad", "Un califat syrien d'Alep", "Un califat andalou de Séville"], 0,
     "Il a fondé la ville du Caire en 969."],
    ["Qu'est-ce que la mosquée-université al-Qarawiyyin ?", ["Un établissement de Fès fondé au IXe siècle", "Une université cairote plus récente", "Une école de Bagdad, la madrasa Nizamiyya", "Une madrasa andalouse fondée à Grenade au XIVe siècle"], 0,
     "Elle est souvent présentée comme la plus ancienne institution universitaire encore en activité."],
    ["Quel rôle le monde musulman a-t-il joué dans la transmission des savoirs ?", ["Il a traduit, conservé et prolongé les héritages grec, persan et indien", "Il a seulement conservé les textes grecs sans les commenter", "Il a rompu avec les savoirs antiques au profit de la théologie religieuse", "Il a exclusivement produit des savoirs nouveaux, sans rien emprunter à personne"], 0,
     "Les traductions de l'arabe vers le latin ont irrigué l'Europe médiévale.", 3],
  ]),

  notion("hm4-mongols", S, "Gengis Khan et ses successeurs",
    "Conquêtes, organisation, héritage.",
    "L'empire mongol fut le plus vaste empire terrestre continu de l'histoire.",
    2, [
    ["Qui a unifié les tribus mongoles ?", ["Gengis Khan, en 1206", "Kubilai Khan, son petit-fils", "Ögödei, son fils et successeur", "Batu, chef de l'expédition d'Europe"], 0,
     "Le titre de Gengis Khan lui est conféré lors d'une assemblée des chefs."],
    ["Qu'est-ce que le yassa ?", ["Un code de lois mongol", "Un conseil tribal réuni pour élire le khan", "Un système militaire de garnisons frontalières", "Un tribut imposé aux peuples vaincus"], 0,
     "Son contenu exact ne nous est connu que par des mentions indirectes."],
    ["Comment l'armée mongole était-elle organisée ?", ["En unités décimales, jusqu'aux tumens de dix mille hommes", "En clans tribaux commandés par leurs chefs", "En légions sur le modèle romain", "En corps de cavalerie autonomes commandés par les princes"], 0,
     "Cette structure permettait une discipline et une coordination remarquables."],
    ["Quelle ville a été détruite par les Mongols en 1258 ?", ["Bagdad", "Damas", "Le Caire", "Samarcande"], 0,
     "La prise met fin au califat abbasside."],
    ["Où l'avancée mongole vers l'ouest a-t-elle été arrêtée ?", ["À Aïn Djalout, en 1260", "À Vienne, aux portes de l'Autriche", "À Constantinople, devant les murailles", "En Hongrie, après la bataille de Mohi"], 0,
     "Les Mamelouks d'Égypte y remportent une victoire décisive."],
    ["Qu'est-ce que la Horde d'Or ?", ["Un khanat mongol dominant les steppes russes", "Une armée d'élite de la garde du khan", "Un khanat persan converti à l'islam", "Un trésor impérial amassé par Gengis Khan"], 0,
     "Sa domination sur les principautés russes a duré plus de deux siècles."],
    ["Qu'est-ce que l'Ilkhanat ?", ["Un khanat mongol établi en Perse", "Un khanat d'Asie centrale", "Un khanat chinois", "Un khanat de la steppe occidentale"], 0,
     "Ses souverains ont fini par se convertir à l'islam."],
    ["Qu'est-ce que la paix mongole ?", ["Une période de sécurité des routes commerciales eurasiatiques", "Un traité signé entre les khanats mongols", "Une trêve avec la Chine des Song", "Une pacification durable des steppes d'Asie centrale"], 0,
     "Elle a facilité les voyages, dont celui de Marco Polo."],
    ["Quel effet la paix mongole a-t-elle eu sur les épidémies ?", ["Elle a favorisé la diffusion de la peste vers l'Europe", "Elle n'a eu aucun effet sur la propagation des maladies", "Elle a limité les contagions grâce à des quarantaines strictes", "Elle a causé des famines dans les steppes"], 0,
     "La peste noire de 1347 a suivi les routes commerciales réactivées."],
    ["Qui était Tamerlan ?", ["Un conquérant turco-mongol du XIVe siècle basé à Samarcande", "Un successeur direct de Gengis Khan par la lignée de son fils Djötchi", "Un khan de la Horde d'Or vaincu par les princes russes en 1380", "Un souverain ottoman vaincu à Ankara"], 0,
     "Sa dynastie a donné naissance à l'Empire moghol en Inde.", 3],
  ]),

  notion("hm4-ottomans", S, "L'Empire ottoman",
    "Expansion, apogée, déclin.",
    "L'Empire ottoman a duré plus de six siècles sur trois continents.",
    2, [
    ["Quand l'Empire ottoman a-t-il été fondé ?", ["Vers 1300, en Anatolie", "En 1453, à la prise de Constantinople", "En 1517, à la conquête de l'Égypte", "En 1250"], 0,
     "Osman Ier lui donne son nom."],
    ["Quel sultan a pris Constantinople ?", ["Mehmed II", "Bayezid Ier", "Selim Ier", "Soliman le Magnifique"], 0,
     "Il est surnommé le Conquérant."],
    ["Qu'est-ce que le système du devchirmé ?", ["Un prélèvement d'enfants chrétiens formés au service de l'État", "Un impôt annuel prélevé sur les sujets non musulmans", "Un service militaire obligatoire imposé aux provinces", "Un recrutement de mercenaires étrangers pour la garde"], 0,
     "Il alimentait notamment le corps des janissaires."],
    ["Qu'est-ce que les janissaires ?", ["Un corps d'infanterie d'élite au service du sultan", "La cavalerie ottomane des spahis", "Une garde palatiale du sultan au palais de Topkapi", "Une milice provinciale levée par les gouverneurs de province"], 0,
     "Leur puissance politique a conduit à leur suppression violente en 1826."],
    ["Qu'est-ce que le système des millets ?", ["Une organisation des communautés religieuses avec une autonomie interne", "Un découpage administratif de l'empire en provinces et en districts fiscaux", "Un système fiscal appliqué aux non-musulmans", "Une organisation militaire chargée de la défense des provinces frontalières"], 0,
     "Chaque communauté gérait son droit familial et ses institutions."],
    ["Quel échec militaire marque un tournant en 1683 ?", ["Le second siège de Vienne", "La bataille navale de Lépante, en 1571", "La perte de la Hongrie centrale", "La bataille de Mohács, en 1526"], 0,
     "Le recul territorial en Europe s'amorce ensuite durablement."],
    ["Qu'est-ce que les Tanzimat ?", ["Des réformes de modernisation menées au XIXe siècle", "Une constitution ottomane octroyée en 1876", "Une réforme militaire de l'armée et de la marine du sultan", "Un programme fiscal de recouvrement des impôts de l'empire"], 0,
     "Elles visaient à moderniser l'administration, l'armée et le statut des sujets."],
    ["Qu'est-ce que la question d'Orient ?", ["Les rivalités européennes autour du déclin ottoman", "Un conflit religieux entre les sunnites et les chiites de l'empire", "Une crise balkanique isolée, dans les années 1870", "Un différend russo-turc sur les Détroits"], 0,
     "Elle occupe la diplomatie européenne tout au long du XIXe siècle."],
    ["Comment l'Empire ottoman a-t-il pris fin ?", ["Par sa dissolution après la Première Guerre mondiale et la proclamation de la République turque", "Par la révolution des Jeunes-Turcs de 1908", "Par le seul traité de Sèvres, en 1920", "Par l'abdication du sultan en 1918"], 0,
     "La République est proclamée en 1923 par Mustafa Kemal.", 3],
  ]),

  notion("hm4-decouvertes", S, "Explorations et conquêtes maritimes",
    "Navigations, conquêtes, conséquences.",
    "Les voyages du XVe siècle ont mis en relation des mondes jusque-là séparés.",
    2, [
    ["Quel pays a lancé les premières grandes expéditions atlantiques ?", ["Le Portugal", "L'Espagne", "La France", "Les Provinces-Unies"], 0,
     "Henri le Navigateur y organise des expéditions le long de l'Afrique dès le XVe siècle."],
    ["Qui a contourné le cap de Bonne-Espérance en 1488 ?", ["Bartolomeu Dias", "Vasco de Gama", "Christophe Colomb", "Pedro Álvares Cabral"], 0,
     "Vasco de Gama atteint l'Inde dix ans plus tard."],
    ["Qu'est-ce que le traité de Tordesillas ?", ["Un partage du monde entre l'Espagne et le Portugal en 1494", "Un traité commercial sur les épices d'Orient", "Un accord de paix entre les deux couronnes ibériques", "Un traité de navigation dans l'Atlantique Sud"], 0,
     "Il explique que le Brésil soit devenu portugais."],
    ["Qui a réalisé le premier tour du monde ?", ["L'expédition de Magellan, achevée par Elcano", "Magellan seul, mort en route", "Francis Drake, un demi-siècle plus tard", "Vasco de Gama, par la route des Indes"], 0,
     "Magellan meurt aux Philippines en 1521 ; Elcano ramène l'unique navire survivant."],
    ["Qui a conquis l'empire aztèque ?", ["Hernán Cortés", "Francisco Pizarro", "Diego de Almagro", "Pedro de Alvarado"], 0,
     "Il s'appuie sur les rivalités entre peuples soumis aux Aztèques."],
    ["Qui a conquis l'empire inca ?", ["Francisco Pizarro", "Hernán Cortés", "Vasco Núñez de Balboa", "Diego de Almagro"], 0,
     "Il profite d'une guerre de succession entre Atahualpa et Huáscar."],
    ["Qu'est-ce que l'échange colombien ?", ["Le transfert d'espèces, de maladies et de personnes entre continents", "Un accord commercial entre l'Espagne et ses colonies", "Un système de troc entre colons et populations locales", "Un réseau de comptoirs fortifiés sur les côtes"], 0,
     "Il a transformé l'alimentation et la démographie des deux hémisphères."],
    ["Qu'est-ce que le système de l'encomienda ?", ["Une attribution de main-d'œuvre indigène à des colons espagnols", "Une concession de terres accordée aux ordres religieux et aux villes", "Un impôt colonial prélevé chaque année sur les récoltes et le bétail", "Un système de traite des captifs africains"], 0,
     "Il a fonctionné comme un travail forcé malgré son cadre juridique."],
    ["Qui a dénoncé le traitement des Amérindiens au XVIe siècle ?", ["Bartolomé de Las Casas", "Francisco de Vitoria seul", "Juan Ginés de Sepúlveda", "Hernán Cortés"], 0,
     "La controverse de Valladolid l'oppose à Sepúlveda en 1550."],
    ["Quelle conséquence les découvertes ont-elles eue sur l'Europe ?", ["Un afflux de métaux précieux et un déplacement des routes commerciales", "Un appauvrissement général des royaumes européens", "Une stagnation économique durable due au coût des expéditions lointaines", "Un repli commercial sur la Méditerranée"], 0,
     "L'Atlantique supplante progressivement la Méditerranée comme axe majeur.", 3],
  ]),

  notion("hm4-traite-esclavage", S, "La traite atlantique et l'esclavage",
    "Systèmes, abolitions, mémoire.",
    "La traite atlantique a déporté plus de douze millions d'Africains.",
    2, [
    ["Combien d'Africains ont été embarqués sur les navires de la traite atlantique ?", ["Plus de douze millions", "Environ trois millions", "Environ six millions", "Plus de vingt millions"], 0,
     "Les bases de données de traversées recensent environ douze millions et demi d'embarquements, pour un peu moins de onze millions de débarquements : l'écart est le nombre de morts pendant la traversée."],
    ["Quels continents le commerce triangulaire reliait-il ?", ["Un circuit reliant l'Europe, l'Afrique et les Amériques", "Un commerce entre trois puissances maritimes européennes", "Un échange colonial direct entre métropoles et colonies", "Un système de troc atlantique entre marchands"], 0,
     "De nombreux navires ne suivaient toutefois pas ce schéma en trois étapes."],
    ["Quelle étape de la traite appelle-t-on le passage du milieu ?", ["La traversée atlantique des captifs africains", "Une escale intermédiaire dans les îles du Cap-Vert", "Une route commerciale directe vers les Antilles", "Un port de transit sur la côte africaine"], 0,
     "La mortalité y atteignait fréquemment quinze pour cent."],
    ["Qu'est-ce que le Code noir ?", ["Un texte de 1685 réglementant l'esclavage dans les colonies françaises", "Une loi d'abolition de la traite négrière", "Un code colonial général appliqué à toutes les colonies", "Un règlement intérieur des plantations sucrières"], 0,
     "Il définissait les esclaves comme des biens meubles."],
    ["Quand la France a-t-elle aboli l'esclavage définitivement ?", ["En 1848", "En 1794", "En 1815", "En 1833"], 0,
     "L'abolition de 1794 avait été annulée par Bonaparte en 1802."],
    ["Qui a porté l'abolition de 1848 en France ?", ["Victor Schœlcher", "L'abbé Grégoire", "Alexis de Tocqueville", "Lamartine"], 0,
     "Le décret est signé le 27 avril 1848."],
    ["Quelle révolution a mené à l'indépendance d'Haïti ?", ["La révolution haïtienne, de 1791 à 1804", "La révolte des Marrons de la Jamaïque", "La guerre des Cacos, un siècle plus tard", "La révolte de Saint-Domingue de 1848"], 0,
     "C'est la seule révolte d'esclaves ayant abouti à la fondation d'un État."],
    ["Qui était Toussaint Louverture ?", ["Un chef de la révolution haïtienne", "Le premier président de la République d'Haïti", "Un général français de l'expédition de 1802", "Un gouverneur colonial nommé par Paris"], 0,
     "Déporté en France, il meurt au fort de Joux en 1803."],
    ["Quand les États-Unis ont-ils aboli l'esclavage ?", ["En 1865, avec le treizième amendement", "En 1863, à la proclamation d'émancipation", "En 1861, au début de la guerre", "En 1870, sous la présidence de Grant"], 0,
     "La proclamation d'émancipation de 1863 ne concernait que les États sécessionnistes."],
    ["Qu'est-ce que la loi Taubira de 2001 ?", ["Une loi française reconnaissant la traite et l'esclavage comme crime contre l'humanité", "Une loi de réparation financière pour les descendants", "Une loi mémorielle sur la colonisation française", "Une loi sur l'enseignement de l'histoire coloniale"], 0,
     "Elle prévoit aussi une place accrue de ce sujet dans les programmes scolaires.", 3],
  ]),

  notion("hm4-revolutions-atlantiques", S, "Les révolutions atlantiques",
    "Amérique, France, Amérique latine.",
    "Une vague révolutionnaire a traversé l'Atlantique entre 1776 et 1825.",
    2, [
    ["Quand les États-Unis ont-ils déclaré leur indépendance ?", ["Le 4 juillet 1776", "En 1783, au traité de Paris", "En 1774, au premier Congrès", "En 1789"], 0,
     "La guerre se poursuit jusqu'au traité de Paris de 1783."],
    ["Qui a rédigé l'essentiel de la Déclaration d'indépendance américaine ?", ["Thomas Jefferson", "Benjamin Franklin", "John Adams", "George Washington"], 0,
     "Franklin et Adams y ont apporté des corrections."],
    ["Quel rôle la France a-t-elle joué dans l'indépendance américaine ?", ["Un soutien militaire et financier décisif", "Une neutralité bienveillante jusqu'en 1778", "Un soutien diplomatique sans engagement militaire", "Une opposition initiale, par crainte de l'Angleterre"], 0,
     "L'effort financier a contribué à la crise des finances royales françaises."],
    ["Qu'est-ce que la Constitution américaine de 1787 ?", ["Le texte fondateur d'un régime fédéral et présidentiel", "Une déclaration de droits inspirée de la Virginie", "Un traité entre les treize États d'origine", "Une charte confédérale remplaçant les articles de 1777"], 0,
     "Elle est la plus ancienne constitution écrite encore en vigueur."],
    ["Qu'est-ce que le Bill of Rights américain ?", ["Les dix premiers amendements garantissant les libertés fondamentales", "La déclaration d'indépendance de 1776 elle-même", "Une charte des droits propres à chaque État fédéré", "Un préambule constitutionnel énonçant les buts de l'Union"], 0,
     "Ratifié en 1791, il répondait aux réticences de plusieurs États."],
    ["Qui était Simón Bolívar ?", ["Un dirigeant de l'indépendance de plusieurs pays d'Amérique du Sud", "Un général espagnol vaincu à Ayacucho", "Un président argentin du XIXe siècle", "Un révolutionnaire mexicain contemporain d'Hidalgo"], 0,
     "La Bolivie porte son nom."],
    ["Qui était José de San Martín ?", ["Un libérateur de l'Argentine, du Chili et du Pérou", "Un général espagnol resté fidèle à Madrid", "Un chef d'État vénézuélien de la Grande Colombie", "Un révolutionnaire colombien, compagnon d'armes de Bolívar"], 0,
     "Sa traversée des Andes en 1817 est restée célèbre."],
    ["Comment le Brésil est-il devenu indépendant ?", ["Par la proclamation d'un empire dirigé par l'héritier portugais", "Par une guerre de libération de dix ans contre Lisbonne", "Par une révolution républicaine menée par l'armée", "Par un accord négocié avec la couronne portugaise"], 0,
     "Pierre Ier proclame l'indépendance en 1822 et devient empereur."],
    ["Quelle idée circule d'une révolution à l'autre ?", ["La souveraineté du peuple et les droits naturels", "Le nationalisme ethnique des minorités d'Europe centrale", "Le socialisme des premiers penseurs", "Le libre-échange entre les deux rives de l'Atlantique"], 0,
     "Les textes révolutionnaires circulent d'un continent à l'autre en quelques mois."],
    ["Quelle limite ces révolutions ont-elles eue ?", ["Elles ont souvent maintenu l'esclavage et exclu les femmes", "Elles ont échoué militairement face aux armées royales d'Europe", "Elles n'ont pas duré au-delà d'une génération", "Elles ont été purement politiques, sans aucun effet social"], 0,
     "La révolution haïtienne fait exception sur la question de l'esclavage.", 3],
  ]),

  notion("hm4-nationalismes", S, "Nations et nationalismes au XIXe siècle",
    "Unifications, empires, identités.",
    "Le XIXe siècle voit naître ou s'unifier de nombreux États-nations.",
    2, [
    ["Quand l'unité italienne a-t-elle été proclamée ?", ["En 1861", "En 1870, à la prise de Rome", "En 1848, sous Charles-Albert", "En 1859"], 0,
     "Rome ne devient capitale qu'en 1871."],
    ["Qui était Giuseppe Garibaldi ?", ["Un chef militaire de l'unification italienne", "Le premier roi de l'Italie unifiée", "Un ministre piémontais artisan de l'unité", "Un théoricien républicain du Risorgimento"], 0,
     "L'expédition des Mille en Sicile est son fait d'armes le plus célèbre."],
    ["Qui a mené l'unification allemande ?", ["Otto von Bismarck", "Guillaume Ier seul", "Frédéric-Guillaume IV", "Helmuth von Moltke"], 0,
     "Trois guerres successives y ont conduit entre 1864 et 1871."],
    ["Où l'Empire allemand a-t-il été proclamé ?", ["Dans la galerie des Glaces de Versailles", "À Berlin, au palais royal", "À Francfort, siège du Parlement", "À Potsdam, résidence des Hohenzollern"], 0,
     "Le 18 janvier 1871, après la défaite française."],
    ["Qu'est-ce que le printemps des peuples ?", ["Une vague révolutionnaire européenne en 1848", "Une révolte nationaliste balkanique contre les Ottomans", "Un mouvement libéral limité à l'année 1830", "Une série de réformes octroyées par les empereurs"], 0,
     "Presque tous les mouvements ont été réprimés dans l'année."],
    ["Qu'est-ce que l'Empire austro-hongrois ?", ["Une double monarchie créée en 1867", "Un empire unifié sous une seule couronne", "Une confédération germanique héritée de 1815", "Une union personnelle héritée du Moyen Âge"], 0,
     "Le compromis reconnaît une large autonomie à la Hongrie."],
    ["Quelle question a déstabilisé les Balkans au XIXe siècle ?", ["L'émancipation des peuples face au recul ottoman", "Les rivalités religieuses entre orthodoxes et catholiques", "Les conflits frontaliers avec l'Empire russe voisin", "Les questions économiques et douanières"], 0,
     "Les puissances européennes y ont chacune poursuivi leurs intérêts."],
    ["Qu'est-ce que le nationalisme romantique ?", ["Une conception de la nation fondée sur la langue et la culture", "Un nationalisme d'État imposé par l'administration", "Un patriotisme constitutionnel fondé sur les institutions", "Un nationalisme économique de protection douanière"], 0,
     "Herder en est l'un des inspirateurs majeurs."],
    ["Qu'est-ce que la conception française de la nation au XIXe siècle ?", ["Une adhésion politique volontaire, selon Renan", "Une appartenance ethnique héritée par le sang", "Une communauté linguistique et culturelle homogène", "Une unité religieuse autour du catholicisme"], 0,
     "Renan la définit en 1882 comme un plébiscite de tous les jours."],
    ["Quel effet le nationalisme a-t-il eu au début du XXe siècle ?", ["Il a contribué au déclenchement de la Première Guerre mondiale", "Il a favorisé la paix et la coopération entre les nations européennes", "Il a affaibli les États au profit des grands empires multinationaux", "Il est resté marginal dans les opinions publiques"], 0,
     "Il s'est combiné aux rivalités impériales et aux alliances militaires.", 3],
  ]),

  notion("hm4-imperialismes", S, "Impérialismes et colonisation",
    "Partage, résistances, conséquences.",
    "L'Europe contrôlait une grande partie du monde à la veille de 1914.",
    2, [
    ["Qu'est-ce que la conférence de Berlin de 1884-1885 ?", ["Une réunion fixant les règles du partage colonial de l'Afrique", "Un traité de paix entre puissances européennes", "Un congrès international consacré à l'abolition de la traite et de l'esclavage", "Un accord commercial entre les États africains et les puissances européennes"], 0,
     "Aucun représentant africain n'y a été convié."],
    ["Qu'est-ce que le Congo de Léopold II ?", ["Un territoire exploité comme propriété personnelle du roi des Belges", "Une colonie belge administrée comme les autres", "Un protectorat placé sous le contrôle conjoint des puissances européennes", "Un comptoir commercial concédé à des sociétés privées belges et britanniques"], 0,
     "Les violences de l'exploitation du caoutchouc ont provoqué un scandale international."],
    ["Qu'est-ce que la révolte des Cipayes ?", ["Un soulèvement en Inde en 1857 contre la Compagnie britannique", "Une révolte paysanne du Bengale contre l'impôt foncier britannique", "Une guerre anglo-indienne opposant la Couronne aux princes du Deccan", "Une mutinerie navale dans le port de Bombay"], 0,
     "Elle conduit la Couronne britannique à administrer directement l'Inde."],
    ["Qu'est-ce que la guerre de l'opium ?", ["Un conflit imposant à la Chine le commerce de l'opium britannique", "Une guerre civile chinoise", "Un conflit commercial russe", "Une révolte antidrogue"], 0,
     "Hong Kong est cédée au Royaume-Uni à l'issue du premier conflit."],
    ["Qu'est-ce que la révolte des Boxers ?", ["Un soulèvement antiétranger en Chine autour de 1900", "Une révolte paysanne fiscale", "Un mouvement réformiste", "Une insurrection militaire"], 0,
     "Une coalition de huit puissances l'a réprimée."],
    ["Quel pays africain a résisté victorieusement à une colonisation européenne ?", ["L'Éthiopie", "Le Liberia", "Le Maroc", "Le Soudan"], 0,
     "La victoire d'Adoua en 1896 stoppe l'Italie ; le Liberia n'a pas connu de conquête coloniale."],
    ["Qu'est-ce que la crise de Fachoda ?", ["Une confrontation franco-britannique au Soudan en 1898", "Un conflit colonial en Afrique de l'Ouest", "Une crise marocaine", "Un incident au Congo"], 0,
     "Le recul français a ouvert la voie à l'Entente cordiale."],
    ["Qu'est-ce que le mandat colonial après 1919 ?", ["Une administration de territoires confiée par la Société des Nations", "Une annexion directe", "Un protectorat classique", "Une occupation militaire temporaire"], 0,
     "En pratique, il a souvent fonctionné comme une colonisation ordinaire."],
    ["Quelle justification idéologique la colonisation invoquait-elle ?", ["Une prétendue mission civilisatrice", "Un droit de conquête", "Une nécessité démographique", "Un impératif religieux seul"], 0,
     "Ce discours accompagnait des intérêts économiques et stratégiques concrets."],
    ["Quelle conséquence durable les frontières coloniales ont-elles eue ?", ["Des tracés arbitraires souvent source de conflits ultérieurs", "Une stabilisation régionale durable des frontières héritées", "Une organisation ethnique cohérente des territoires et des peuples", "Un effet limité sur la vie des populations"], 0,
     "Les États indépendants les ont pourtant majoritairement conservées.", 3],
  ]),

  notion("hm4-guerre-froide-2", S, "La guerre froide, seconde phase",
    "Détente, crises, effondrement.",
    "La guerre froide alterne périodes de tension et de détente.",
    2, [
    ["Que désigne la détente dans les relations Est-Ouest des années 1970 ?", ["Une phase de réduction des tensions entre blocs", "Une fin anticipée et négociée de la guerre froide", "Un désarmement complet des deux blocs", "Un rapprochement idéologique entre l'Est et l'Ouest"], 0,
     "Elle est marquée par les accords SALT et l'Acte final d'Helsinki."],
    ["Qu'est-ce que l'Acte final d'Helsinki de 1975 ?", ["Un accord reconnaissant les frontières et affirmant les droits de l'homme", "Un traité de désarmement nucléaire signé à Helsinki", "Un pacte de non-agression entre l'Est et l'Ouest", "Un accord commercial et douanier entre l'Est et l'Ouest"], 0,
     "Le volet droits de l'homme a été mobilisé par les dissidents de l'Est."],
    ["Qu'est-ce que l'invasion soviétique de l'Afghanistan ?", ["Une intervention de 1979 qui a relancé les tensions", "Une opération de maintien de la paix décidée par l'ONU", "Une intervention de courte durée, achevée en 1980", "Une occupation négociée avec le gouvernement afghan"], 0,
     "Elle dure jusqu'en 1989 et affaiblit durablement l'URSS."],
    ["Qu'est-ce que la crise des euromissiles ?", ["Un affrontement sur le déploiement de missiles en Europe dans les années 1980", "Une crise berlinoise des années 1980", "Un conflit sur les missiles installés à Cuba par Moscou", "Une crise interne de l'OTAN sur son commandement"], 0,
     "Le traité FNI de 1987 y met fin."],
    ["Qu'est-ce que la perestroïka ?", ["Une politique de restructuration économique en URSS", "La seule réforme politique des institutions", "Une libéralisation culturelle et médiatique", "Une réforme agraire des kolkhozes"], 0,
     "Elle est engagée par Mikhaïl Gorbatchev à partir de 1985."],
    ["Qu'est-ce que la glasnost ?", ["Une politique de transparence et de liberté d'expression", "Une réforme économique des entreprises d'État", "Une ouverture diplomatique vers l'Occident et la Chine", "Une décentralisation administrative au profit des républiques fédérées"], 0,
     "Elle a permis une critique publique inédite du système soviétique."],
    ["Qu'est-ce que le syndicat Solidarność ?", ["Un syndicat polonais indépendant fondé en 1980", "Un mouvement dissident tchèque né de la Charte 77", "Un parti d'opposition hongrois des années 1980", "Une organisation ouvrière est-allemande clandestine"], 0,
     "Lech Wałęsa en était le dirigeant."],
    ["Quand le mur de Berlin est-il tombé ?", ["Le 9 novembre 1989", "En octobre 1989, à Leipzig", "En décembre 1989, à Noël", "En 1990"], 0,
     "L'ouverture résulte en partie d'une annonce confuse d'un responsable est-allemand."],
    ["Quand l'URSS a-t-elle été dissoute ?", ["En décembre 1991", "En 1990", "En août 1991, lors du putsch", "En 1992, après les accords"], 0,
     "Le putsch manqué d'août 1991 en avait précipité le processus."],
    ["Quelle lecture peut-on faire de la fin de la guerre froide ?", ["Une combinaison d'essoufflement économique soviétique et de pressions internes", "Une victoire militaire remportée par l'Occident", "Un accord négocié entre les deux blocs à Malte", "Un effondrement imprévisible et sans causes identifiables"], 0,
     "Aucune analyse sérieuse n'avait anticipé le calendrier de cet effondrement.", 3],
  ]),

  notion("hm4-decolonisations", S, "Les décolonisations",
    "Indépendances, guerres, conséquences.",
    "La plupart des empires coloniaux ont disparu entre 1945 et 1975.",
    2, [
    ["Quand l'Inde est-elle devenue indépendante ?", ["En 1947", "En 1950", "En 1945", "En 1948"], 0,
     "La partition avec le Pakistan a provoqué des déplacements massifs et des violences."],
    ["Qui a dirigé la lutte non violente pour l'indépendance indienne ?", ["Gandhi", "Nehru", "Jinnah", "Ambedkar"], 0,
     "Nehru devient le premier chef du gouvernement indien."],
    ["Qu'est-ce que la conférence de Bandung ?", ["Une réunion afro-asiatique de 1955 affirmant l'émancipation des peuples colonisés", "Un sommet fondateur du mouvement des non-alignés, réuni à Belgrade quelques années plus tard", "Une conférence de l'Organisation des Nations unies consacrée à la décolonisation des territoires", "Un congrès panafricain réuni à Accra"], 0,
     "Elle prépare le mouvement des non-alignés."],
    ["Quand l'Indonésie a-t-elle proclamé son indépendance ?", ["En 1945", "En 1949", "En 1950", "En 1947"], 0,
     "Les Pays-Bas ne la reconnaissent qu'en 1949, après un conflit."],
    ["Quelle guerre a marqué la décolonisation française en Asie ?", ["La guerre d'Indochine", "La guerre de Corée", "La guerre du Viêt Nam", "La guerre de Madagascar"], 0,
     "Elle s'achève par la défaite de Diên Biên Phu en 1954."],
    ["Quand la plupart des colonies françaises d'Afrique sont-elles devenues indépendantes ?", ["En 1960", "En 1958", "En 1962", "En 1956"], 0,
     "L'année 1960 est souvent appelée l'année de l'Afrique."],
    ["Qu'est-ce que l'apartheid ?", ["Un régime de ségrégation légale en Afrique du Sud", "Une politique coloniale britannique", "Un système de ségrégation américain", "Une politique de développement séparé rhodésienne"], 0,
     "Institué en 1948, il voit ses lois abrogées en 1991 et s'éteint avec les élections multiraciales de 1994."],
    ["Qui a été le premier président noir d'Afrique du Sud ?", ["Nelson Mandela", "Desmond Tutu", "Thabo Mbeki", "Oliver Tambo"], 0,
     "Élu en 1994, après vingt-sept ans de détention."],
    ["Quelle difficulté les États nouvellement indépendants ont-ils rencontrée ?", ["Des économies dépendantes et des institutions fragiles", "Un manque de population active qualifiée", "Une absence totale de reconnaissance par les organisations internationales", "Des ressources naturelles jugées partout insuffisantes"], 0,
     "L'héritage colonial et les rivalités de la guerre froide ont pesé lourdement.", 3],
  ]),

  notion("hm4-monde-contemporain", S, "Le monde depuis 1990",
    "Mondialisation, conflits, recompositions.",
    "La fin de la guerre froide n'a pas mis fin aux conflits.",
    2, [
    ["Qu'est-ce que la guerre du Golfe de 1991 ?", ["Une coalition internationale libérant le Koweït envahi par l'Irak", "Une guerre entre l'Iran et l'Irak, achevée trois ans plus tôt", "Une intervention américaine unilatérale décidée sans l'ONU", "Un conflit régional limité aux frontières du Koweït"], 0,
     "Elle est menée sous mandat des Nations unies."],
    ["Qu'est-ce que le génocide des Tutsi au Rwanda ?", ["Un génocide ayant fait environ huit cent mille morts en 1994", "Une guerre civile entre l'armée et une rébellion", "Un conflit ethnique régional étendu aux pays voisins du Rwanda", "Une crise humanitaire née de l'afflux de réfugiés dans la région"], 0,
     "La communauté internationale n'est pas intervenue pour l'arrêter."],
    ["Qu'est-ce que la guerre de Bosnie ?", ["Un conflit de 1992 à 1995 marqué par des nettoyages ethniques", "Une guerre d'indépendance croate achevée dès la fin de 1991", "Un conflit serbo-kosovar réglé par l'OTAN en 1999", "Une guerre civile yougoslave unique, de la Slovénie jusqu'au Kosovo"], 0,
     "Le massacre de Srebrenica a été qualifié de génocide par la justice internationale."],
    ["Qu'est-ce que l'Organisation mondiale du commerce ?", ["Une organisation régulant le commerce international, créée en 1995", "Un accord douanier limitant les droits de douane européens", "Une institution financière prêtant aux pays en développement des fonds publics", "Un forum économique réunissant chaque année les chefs d'État et les entreprises"], 0,
     "Elle succède au GATT."],
    ["Qu'est-ce que la Cour pénale internationale ?", ["Une juridiction permanente jugeant les crimes les plus graves", "Un tribunal de l'ONU créé pour un conflit particulier", "Une cour d'arbitrage réglant les différends entre États", "Un tribunal européen des droits de l'homme siégeant à Strasbourg"], 0,
     "Créée par le statut de Rome en 1998, elle siège à La Haye."],
    ["Quel événement a marqué le 11 septembre 2001 ?", ["Des attentats aux États-Unis ayant fait près de trois mille morts", "Une attaque contre une ambassade américaine en Afrique de l'Est", "Un attentat commis dans une capitale européenne", "Une crise diplomatique majeure avec le monde arabe"], 0,
     "Ils déclenchent l'intervention en Afghanistan puis une reconfiguration sécuritaire mondiale."],
    ["Qu'est-ce que la crise financière de 2008 ?", ["Une crise partie du marché immobilier américain, devenue mondiale", "Une crise bancaire européenne partie des banques allemandes et suisses", "Une crise de dette souveraine née dans les pays de la zone euro", "Un krach boursier isolé sur les places asiatiques"], 0,
     "Elle a entraîné la plus grave récession mondiale depuis 1945."],
    ["Qu'est-ce que le printemps arabe ?", ["Une vague de soulèvements dans le monde arabe à partir de 2010", "Une révolution égyptienne isolée, sans écho régional", "Un mouvement réformiste conduit par les institutions en place", "Une crise politique régionale réglée par les monarchies du Golfe"], 0,
     "Ses issues ont été très différentes d'un pays à l'autre."],
    ["Qu'est-ce que l'accord de Paris sur le climat ?", ["Un accord de 2015 visant à limiter le réchauffement mondial", "Un protocole de réduction des émissions juridiquement contraignant", "Un traité européen sur la qualité de l'air", "Un accord sur la biodiversité et la protection des forêts signé à Nagoya"], 0,
     "Il vise à contenir la hausse nettement en dessous de deux degrés."],
    ["Quelle recomposition majeure marque le début du XXIe siècle ?", ["La montée en puissance de la Chine et le basculement vers l'Asie", "Le renforcement du bloc occidental face au reste du monde", "L'unification européenne complète et définitive", "Le retrait des grandes puissances des affaires du monde"], 0,
     "Le poids économique mondial s'est déplacé vers l'Asie orientale en une génération.", 3],
  ]),

  notion("hm4-histoire-sciences-monde", S, "Histoire des sciences dans le monde",
    "Circulations, ruptures, institutions.",
    "La science moderne s'est construite par des échanges entre plusieurs civilisations.",
    2, [
    ["D'où vient notre système de chiffres ?", ["D'Inde, transmis par le monde arabe", "De Grèce, avec les chiffres alphabétiques", "De Rome, par les chiffres romains", "De Chine, transmis par la route de la soie"], 0,
     "D'où l'expression chiffres arabes, malgré une origine indienne."],
    ["Qu'est-ce que l'astronomie de Maragha ?", ["Une école d'astronomes persans du XIIIe siècle", "Une observation grecque tardive de Ptolémée", "Une école indienne d'astronomie mathématique", "Un observatoire ottoman construit à Istanbul"], 0,
     "Ses modèles mathématiques ont peut-être influencé Copernic."],
    ["Quelle invention chinoise a transformé la navigation ?", ["La boussole", "L'astrolabe", "Le gouvernail d'étambot seul", "Le sextant"], 0,
     "La Chine en fait usage plusieurs siècles avant l'Europe."],
    ["Quelles sont les quatre grandes inventions traditionnellement attribuées à la Chine ?", ["Papier, imprimerie, poudre et boussole", "Papier, verre, poudre et boussole", "Imprimerie, papier, soie et poudre", "Poudre, boussole, porcelaine et papier"], 0,
     "Cette liste est une construction historiographique, mais chacune est bien attestée."],
    ["Qu'est-ce que la révolution scientifique du XVIIe siècle ?", ["Une transformation des méthodes et des théories en Europe", "L'invention de la seule méthode expérimentale par Francis Bacon", "La naissance des universités européennes", "La création des premières académies scientifiques nationales"], 0,
     "Galilée, Descartes et Newton en sont des figures centrales."],
    ["Qu'est-ce que la Royal Society ?", ["Une académie scientifique britannique fondée en 1660", "Une université anglaise fondée au Moyen Âge", "Un observatoire royal installé à Greenwich", "Un collège de médecine londonien"], 0,
     "Sa devise invite à ne rien tenir pour acquis sur parole."],
    ["Qu'est-ce que l'Académie des sciences française ?", ["Une institution scientifique fondée en 1666", "Une université d'État créée par la Révolution", "Un collège royal fondé par François Ier en 1530", "Un bureau des longitudes créé sous la Révolution"], 0,
     "Colbert en est à l'origine sous Louis XIV."],
    ["Qu'est-ce que la professionnalisation de la science au XIXe siècle ?", ["Le passage d'une pratique de savants isolés à des métiers institués", "Une spécialisation croissante des disciplines universitaires", "Une industrialisation de la recherche dans les laboratoires des grandes entreprises", "Un financement public généralisé de la recherche fondamentale et appliquée"], 0,
     "Le mot scientist apparaît en anglais dans les années 1830."],
    ["Qu'est-ce que la big science ?", ["Une recherche à très grande échelle mobilisant des moyens considérables", "Une science de la complexité et des systèmes", "Une recherche fondamentale sans application immédiate", "Une science internationale coordonnée par l'Unesco"], 0,
     "Le projet Manhattan et le CERN en sont des exemples."],
    ["Quelle idée fausse la mondialisation des sciences dément-elle ?", ["Que la science moderne serait une création purement européenne", "Que les échanges scientifiques entre continents sont récents", "Que les sciences seraient universelles dès leur origine", "Que la recherche serait par nature collective et anonyme"], 0,
     "Les historiens documentent des circulations continues entre aires culturelles.", 3],
  ]),

  notion("hm4-migrations-histoire", S, "Les migrations dans l'histoire",
    "Peuplements, exils, diasporas.",
    "Les migrations ont façonné le peuplement de tous les continents.",
    2, [
    ["Comment l'Homo sapiens a-t-il peuplé la planète ?", ["Par des migrations successives depuis l'Afrique", "Par une évolution parallèle sur chaque continent", "Par une migration unique et rapide le long des côtes", "Par un peuplement depuis l'Asie centrale"], 0,
     "Les données génétiques confirment une origine africaine commune."],
    ["Qu'est-ce que les grandes invasions du Ve siècle ?", ["Des migrations de peuples entrant dans l'Empire romain", "Des raids militaires isolés menés depuis la Germanie", "Une conquête organisée par les royaumes germaniques du Nord", "Une colonisation planifiée des provinces par Rome elle-même"], 0,
     "Le terme d'invasions a été largement nuancé par l'historiographie récente."],
    ["Que recouvre le terme de diaspora juive ?", ["La dispersion des communautés juives hors de Judée", "Un exil unique consécutif à la prise de Jérusalem en 70", "Une migration médiévale des communautés vers l'Europe centrale", "Un déplacement moderne lié à la création d'Israël en 1948"], 0,
     "Elle s'étale sur plusieurs siècles et prend des formes très diverses."],
    ["Qu'est-ce que l'émigration européenne du XIXe siècle ?", ["Un départ de plusieurs dizaines de millions de personnes vers les Amériques", "Une migration interne à l'Europe, des campagnes vers les villes", "Un mouvement colonial encadré par les États européens", "Un exil politique massif après les révolutions de 1848"], 0,
     "L'Irlande, l'Italie et l'Europe centrale y ont particulièrement contribué."],
    ["Qu'est-ce qu'Ellis Island ?", ["Un centre d'accueil des immigrants à New York", "Un port de départ européen vers les États-Unis", "Un centre de rétention moderne pour migrants clandestins", "Une île de quarantaine britannique au large de Liverpool"], 0,
     "Plus de douze millions de personnes y ont été enregistrées entre 1892 et 1954."],
    ["Qu'est-ce que la partition de l'Inde en 1947 ?", ["Un déplacement de plus de dix millions de personnes", "Une migration progressive étalée sur plusieurs décennies", "Un échange de populations organisé par traité international", "Un exode limité aux villes du Pendjab"], 0,
     "Les violences qui l'ont accompagnée ont fait des centaines de milliers de morts."],
    ["Qu'est-ce que le statut de réfugié ?", ["Une protection définie par la convention de Genève de 1951", "Un statut national temporaire accordé par chaque État membre", "Une protection humanitaire ponctuelle décidée au cas par cas", "Un droit d'asile inconditionnel garanti par les Nations unies"], 0,
     "Il repose sur une crainte fondée de persécution."],
    ["Qu'est-ce qu'un déplacé interne ?", ["Une personne déplacée à l'intérieur de son propre pays", "Un migrant économique installé dans une grande ville", "Un réfugié non enregistré par les autorités du pays d'accueil", "Un demandeur d'asile en attente d'une décision"], 0,
     "Ils sont plus nombreux que les réfugiés au sens strict."],
    ["Quelle part de la population mondiale vit hors de son pays de naissance ?", ["Environ trois à quatre pour cent", "Environ dix pour cent, soit huit cents millions de personnes", "Environ un pour cent", "Environ quinze pour cent, en forte hausse"], 0,
     "Cette proportion est remarquablement stable sur le long terme."],
    ["Que montre l'histoire des migrations ?", ["La mobilité est une constante des sociétés humaines", "Les migrations sont un phénomène récent et moderne", "Les sociétés sont majoritairement sédentaires", "Les déplacements sont presque toujours contraints"], 0,
     "Les périodes de fermeture des frontières sont historiquement récentes.", 3],
  ]),
];
