/**
 * Histoire du monde, quatrième lot — vingt-deux notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Histoire du monde";

export const CG_HISTOIRE_MONDE_4: SeedSkill[] = [
  notion("hm4-mesopotamie", S, "Entre Tigre et Euphrate",
    "Cités, lois, écriture.",
    "Les premières cités-États du monde sont apparues entre le Tigre et l'Euphrate.",
    2, [
    ["Quelle civilisation a fondé les premières cités de Mésopotamie ?", ["Les Sumériens", "Les Akkadiens", "Les Assyriens", "Les Babyloniens"], 0,
     "Ur, Uruk et Lagash comptent parmi leurs cités les plus importantes."],
    ["Quel roi akkadien a fondé le premier empire connu ?", ["Sargon d'Akkad", "Hammurabi", "Gilgamesh", "Assurbanipal"], 0,
     "Son empire, au XXIVe siècle avant notre ère, réunit les cités sumériennes."],
    ["Qu'est-ce que le code de Hammurabi ?", ["Un recueil de lois babylonien gravé sur une stèle", "Un traité religieux", "Un texte administratif", "Un recueil de sentences royales"], 0,
     "La stèle, découverte à Suse, est conservée au musée du Louvre."],
    ["À quoi servait une ziggourat mésopotamienne ?", ["Un temple à degrés mésopotamien", "Une tour de défense", "Un palais royal", "Un tombeau monumental"], 0,
     "Celle d'Ur est la mieux conservée aujourd'hui."],
    ["Qu'est-ce que l'Épopée de Gilgamesh ?", ["Le plus ancien grand récit littéraire connu", "Une chronique royale", "Un texte religieux babylonien", "Un recueil de mythes sumériens"], 0,
     "Elle contient notamment un récit de déluge antérieur au texte biblique."],
    ["Quelle bibliothèque antique a été retrouvée à Ninive ?", ["Celle d'Assurbanipal", "Celle de Nabuchodonosor", "Celle de Sargon", "Celle de Hammurabi"], 0,
     "Des dizaines de milliers de tablettes y ont été mises au jour."],
    ["Qu'est-ce que l'empire néo-assyrien ?", ["Un empire militaire dominant le Proche-Orient aux IXe-VIIe siècles avant notre ère", "Un royaume babylonien tardif", "Un empire perse ancien", "Un royaume araméen"], 0,
     "Sa chute en 612 avant notre ère marque un basculement régional."],
    ["Qui était Nabuchodonosor II ?", ["Un roi babylonien qui a détruit le Temple de Jérusalem", "Un roi assyrien conquérant", "Un souverain perse", "Un roi akkadien"], 0,
     "La déportation des Judéens à Babylone date de son règne."],
    ["Qu'est-ce que le système sexagésimal mésopotamien ?", ["Un système de numération en base soixante", "Un calendrier lunaire", "Un système de poids", "Une numération décimale"], 0,
     "Nos soixante minutes et nos trois cent soixante degrés en descendent directement."],
    ["Qu'apporte la Mésopotamie à l'histoire mondiale ?", ["L'écriture, le droit écrit et l'urbanisation", "L'agriculture", "La métallurgie du fer", "La monnaie"], 0,
     "L'agriculture est plus ancienne et la monnaie plus tardive.", 3],
  ]),

  notion("hm4-egypte-ancienne", S, "L'Égypte ancienne",
    "Dynasties, croyances, monuments.",
    "L'histoire pharaonique s'étend sur plus de trois mille ans.",
    2, [
    ["Qui a unifié la Haute et la Basse-Égypte ?", ["Narmer, vers 3100 avant notre ère", "Djéser", "Khéops", "Menès au Nouvel Empire"], 0,
     "La palette de Narmer en conserve la représentation la plus célèbre."],
    ["Quelle pyramide est la plus ancienne pyramide égyptienne connue ?", ["La pyramide à degrés de Djéser", "La pyramide de Khéops", "La pyramide rhomboïdale", "La pyramide rouge"], 0,
     "Conçue par l'architecte Imhotep à Saqqarah."],
    ["Qu'est-ce que le Nouvel Empire égyptien ?", ["Une période d'apogée entre le XVIe et le XIe siècle avant notre ère", "La période des grandes pyramides", "L'époque ptolémaïque", "La Basse Époque"], 0,
     "Thoutmôsis III, Ramsès II et Toutânkhamon en sont des figures."],
    ["Quel pharaon a tenté d'imposer le culte d'un dieu unique ?", ["Akhenaton", "Ramsès II", "Toutânkhamon", "Aménophis III"], 0,
     "Le culte d'Aton a été abandonné dès après sa mort."],
    ["Quelle reine égyptienne a régné en tant que pharaon au XVe siècle avant notre ère ?", ["Hatchepsout", "Néfertiti", "Cléopâtre", "Néfertari"], 0,
     "Son temple de Deir el-Bahari est l'un des plus remarquables d'Égypte."],
    ["Quelle bataille Ramsès II a-t-il livrée contre les Hittites ?", ["La bataille de Qadesh", "La bataille de Megiddo", "La bataille de Karkemish", "La bataille de Pelusium"], 0,
     "Elle a débouché sur l'un des plus anciens traités de paix connus."],
    ["Que contenait le Livre des Morts égyptien ?", ["Un recueil de formules destinées à guider le défunt", "Une chronique funéraire", "Un registre de sépultures", "Un traité religieux royal"], 0,
     "Les formules étaient déposées dans la tombe, souvent sur papyrus."],
    ["Qu'est-ce que la momification ?", ["Une préparation du corps visant à le conserver pour l'au-delà", "Un embaumement religieux", "Un rite funéraire royal", "Une conservation par dessiccation naturelle"], 0,
     "Le natron, un sel naturel, en était l'agent principal."],
    ["Qui a déchiffré les hiéroglyphes ?", ["Jean-François Champollion", "Thomas Young", "Auguste Mariette", "Karl Lepsius"], 0,
     "En 1822, à partir de la pierre de Rosette."],
    ["Comment l'Égypte pharaonique s'achève-t-elle ?", ["Par l'annexion romaine après la mort de Cléopâtre", "Par la conquête perse", "Par la conquête d'Alexandre", "Par la conquête arabe"], 0,
     "Elle devient province romaine en 30 avant notre ère.", 3],
  ]),

  notion("hm4-perse", S, "L'empire perse",
    "Achéménides, satrapies, guerres.",
    "L'empire achéménide fut le plus vaste que le monde ait connu à son époque.",
    2, [
    ["Qui a fondé l'empire achéménide ?", ["Cyrus II", "Darius Ier", "Xerxès Ier", "Cambyse II"], 0,
     "Il conquiert la Médie, la Lydie et Babylone au VIe siècle avant notre ère."],
    ["Qu'est-ce que le cylindre de Cyrus ?", ["Une inscription babylonienne relatant sa prise de Babylone", "Un code de lois perse", "Une déclaration des droits", "Un traité de paix"], 0,
     "Souvent présenté comme une première charte des droits, il relève d'une tradition royale babylonienne."],
    ["Qu'est-ce qu'une satrapie ?", ["Une province de l'empire perse dirigée par un gouverneur", "Une cité autonome", "Un district militaire", "Une région tributaire"], 0,
     "Darius Ier en a organisé une vingtaine."],
    ["Qu'est-ce que la route royale perse ?", ["Un axe reliant Suse à Sardes sur plus de deux mille kilomètres", "Une voie commerciale vers l'Inde", "Une route militaire vers l'Égypte", "Un tronçon de la route de la soie"], 0,
     "Des relais de poste permettaient d'en parcourir la longueur en une semaine."],
    ["Qu'est-ce que Persépolis ?", ["Une capitale cérémonielle achéménide", "La capitale administrative de l'empire", "Une cité fondée par Cyrus", "Une place forte médique"], 0,
     "Alexandre le Grand l'a incendiée en 330 avant notre ère."],
    ["Quelle religion dominait l'empire perse ?", ["Le zoroastrisme", "Le mithraïsme", "Le manichéisme", "Le mazdéisme tardif"], 0,
     "Elle repose sur l'opposition entre un principe de bien et un principe de mal."],
    ["Quelle bataille a opposé Perses et Grecs en 490 avant notre ère ?", ["La bataille de Marathon", "La bataille de Salamine", "La bataille des Thermopyles", "La bataille de Platées"], 0,
     "La victoire athénienne y a un retentissement considérable."],
    ["Quel roi perse a mené la seconde guerre médique ?", ["Xerxès Ier", "Darius Ier", "Artaxerxès Ier", "Cyrus le Jeune"], 0,
     "Sa campagne s'achève par les défaites de Salamine et Platées."],
    ["Qu'est-ce que l'empire sassanide ?", ["Un empire perse rival de Rome du IIIe au VIIe siècle", "Un royaume parthe", "Un empire achéménide tardif", "Un royaume perse hellénistique"], 0,
     "Il tombe face aux conquêtes arabes au VIIe siècle."],
    ["Quel héritage l'empire perse a-t-il laissé ?", ["Un modèle d'administration impériale tolérante des cultures locales", "Un système juridique unifié", "Une langue commune imposée", "Une religion universelle"], 0,
     "Cette souplesse a servi de référence aux empires ultérieurs.", 3],
  ]),

  notion("hm4-inde-ancienne", S, "L'Inde ancienne",
    "Indus, Maurya, Gupta.",
    "La civilisation de l'Indus est l'une des trois grandes civilisations urbaines primitives.",
    2, [
    ["Qu'est-ce que la civilisation de l'Indus ?", ["Une civilisation urbaine du IIIe millénaire avant notre ère", "Une culture védique", "Un royaume maurya ancien", "Une civilisation du Gange"], 0,
     "Mohenjo-daro et Harappa en sont les principaux sites."],
    ["Quelle particularité les villes de l'Indus présentaient-elles ?", ["Un urbanisme planifié avec un réseau d'évacuation des eaux", "Des fortifications monumentales", "Des palais royaux imposants", "Des temples centraux"], 0,
     "Aucun palais ni temple monumental n'y a été identifié avec certitude."],
    ["Que sait-on de l'écriture de l'Indus ?", ["Elle n'a jamais été déchiffrée", "Elle est déchiffrée depuis 1950", "Elle dérive du cunéiforme", "Elle n'existait pas"], 0,
     "Les inscriptions connues sont très courtes, ce qui complique tout déchiffrement."],
    ["Qu'est-ce que la période védique ?", ["Une période marquée par la composition des Veda", "L'époque des royaumes du Gange", "La période maurya", "L'âge des Upanishad seul"], 0,
     "Elle succède au déclin de la civilisation de l'Indus."],
    ["Qui a fondé l'empire maurya ?", ["Chandragupta Maurya", "Ashoka", "Bindusara", "Kanishka"], 0,
     "Il unifie une grande partie du sous-continent à la fin du IVe siècle avant notre ère."],
    ["Quel empereur maurya s'est converti au bouddhisme ?", ["Ashoka", "Chandragupta", "Bindusara", "Harsha"], 0,
     "Après la guerre du Kalinga, dont il déplore la violence dans ses édits."],
    ["Qu'est-ce que les édits d'Ashoka ?", ["Des inscriptions royales gravées sur piliers et rochers", "Un code de lois bouddhiste", "Des décrets administratifs", "Des textes religieux canoniques"], 0,
     "Ils constituent les plus anciens documents écrits déchiffrés d'Inde."],
    ["Qu'est-ce que l'empire gupta ?", ["Un empire du IVe au VIe siècle, âge classique de l'Inde", "Un empire bouddhiste", "Un royaume du Deccan", "Un empire médiéval du nord"], 0,
     "Mathématiques, astronomie et littérature sanskrite y connaissent un apogée."],
    ["Quelle invention mathématique majeure vient de l'Inde ancienne ?", ["Le zéro comme nombre et la numération de position", "L'algèbre", "La géométrie", "La trigonométrie"], 0,
     "Brahmagupta en formule des règles d'usage au VIIe siècle."],
    ["Comment le bouddhisme s'est-il diffusé hors d'Inde ?", ["Par les routes commerciales vers l'Asie centrale et l'Asie de l'Est", "Par des conquêtes militaires", "Par des migrations de populations", "Par la colonisation"], 0,
     "Il a fini par décliner en Inde même, tout en s'implantant durablement ailleurs.", 3],
  ]),

  notion("hm4-chine-imperiale", S, "Les dynasties chinoises",
    "Dynasties, administration, inventions.",
    "L'empire chinois a duré plus de deux mille ans sous des dynasties successives.",
    2, [
    ["Qui a unifié la Chine en 221 avant notre ère ?", ["Qin Shi Huang", "L'empereur Wu des Han", "Liu Bang", "Le duc de Zhou"], 0,
     "Il unifie aussi les poids, les mesures et l'écriture."],
    ["Qu'est-ce que l'armée de terre cuite ?", ["Des milliers de statues enterrées près du tombeau du premier empereur", "Une garde impériale sculptée", "Un ensemble votif Han", "Un monument funéraire Tang"], 0,
     "Découverte en 1974 par des paysans creusant un puits."],
    ["Quelle dynastie a duré environ quatre siècles après les Qin ?", ["Les Han", "Les Tang", "Les Song", "Les Sui"], 0,
     "Les Chinois han tirent leur nom de cette dynastie."],
    ["Qu'est-ce que le système des examens impériaux ?", ["Un concours de recrutement des fonctionnaires fondé sur les classiques", "Une sélection militaire", "Un examen de noblesse", "Un système de recommandation"], 0,
     "Il a fonctionné jusqu'en 1905, avec des interruptions."],
    ["Quelle dynastie correspond à un apogée culturel aux VIIe-IXe siècles ?", ["Les Tang", "Les Song", "Les Ming", "Les Han"], 0,
     "Poésie, peinture et ouverture aux cultures étrangères y culminent."],
    ["Quelle dynastie a vu l'essor de l'imprimerie et de la monnaie de papier ?", ["Les Song", "Les Tang", "Les Ming", "Les Yuan"], 0,
     "Une véritable révolution économique s'y produit du Xe au XIIIe siècle."],
    ["Quelle dynastie mongole a régné sur la Chine ?", ["Les Yuan", "Les Qing", "Les Liao", "Les Jin"], 0,
     "Fondée par Kubilai Khan, petit-fils de Gengis Khan."],
    ["Quelle dynastie a fait construire la Cité interdite ?", ["Les Ming", "Les Qing", "Les Yuan", "Les Song"], 0,
     "Le transfert de la capitale à Pékin date du règne de Yongle."],
    ["Qui était Zheng He ?", ["Un amiral chinois ayant mené sept grandes expéditions maritimes", "Un explorateur terrestre", "Un ambassadeur Ming", "Un marchand de la route de la soie"], 0,
     "Ses flottes ont atteint l'Afrique de l'Est au début du XVe siècle."],
    ["Quelle dernière dynastie a régné sur la Chine ?", ["Les Qing, d'origine mandchoue", "Les Ming", "Les Yuan", "Les Han"], 0,
     "Elle s'achève avec l'abdication de Puyi en 1912.", 3],
  ]),

  notion("hm4-japon-histoire", S, "Le Japon, des shoguns à Meiji",
    "Shogunats, isolement, modernisation.",
    "Le Japon a connu près de sept siècles de gouvernement militaire.",
    2, [
    ["Qu'est-ce qu'un shogun ?", ["Un chef militaire exerçant le pouvoir réel au nom de l'empereur", "Un empereur militaire", "Un seigneur régional", "Un gouverneur impérial"], 0,
     "L'empereur conservait une légitimité religieuse sans pouvoir effectif."],
    ["Qu'est-ce qu'un daimyo ?", ["Un seigneur territorial japonais", "Un samouraï de haut rang", "Un ministre du shogun", "Un gouverneur de province impérial"], 0,
     "Ils entretenaient leurs propres armées de samouraïs."],
    ["Qu'est-ce que l'époque d'Edo ?", ["Une période de paix sous le shogunat Tokugawa, de 1603 à 1868", "Une période de guerre civile", "L'ère de la restauration impériale", "La période Meiji"], 0,
     "Elle est marquée par une fermeture largement contrôlée du pays."],
    ["Qu'est-ce que le sakoku ?", ["Une politique de fermeture du Japon aux étrangers", "Un système féodal", "Un code des samouraïs", "Une réforme agraire"], 0,
     "Seuls quelques échanges très encadrés subsistaient, notamment à Nagasaki."],
    ["Qui a forcé l'ouverture du Japon en 1853 ?", ["Le commodore Perry", "Les Britanniques", "Les Russes", "Les Néerlandais"], 0,
     "Ses navires à vapeur, appelés les bateaux noirs, ont marqué les esprits."],
    ["Qu'est-ce que la restauration Meiji ?", ["Un retour du pouvoir à l'empereur en 1868, suivi d'une modernisation rapide", "Une restauration du shogunat", "Une réforme militaire", "Une révolution populaire"], 0,
     "En une génération, le Japon se dote d'une industrie et d'une armée modernes."],
    ["Quelle guerre le Japon a-t-il gagnée contre la Russie en 1905 ?", ["La guerre russo-japonaise", "La première guerre sino-japonaise", "La guerre de Corée", "La guerre de Mandchourie"], 0,
     "C'est la première victoire d'une puissance asiatique sur une puissance européenne moderne."],
    ["Qu'est-ce que l'ère Shōwa ?", ["Le règne de l'empereur Hirohito, de 1926 à 1989", "La période Meiji tardive", "L'ère Taishō", "L'après-guerre japonais"], 0,
     "Elle couvre la guerre, la défaite et le miracle économique."],
    ["Quand le Japon a-t-il attaqué Pearl Harbor ?", ["Le 7 décembre 1941", "Le 1er septembre 1939", "Le 7 décembre 1942", "Le 8 décembre 1940"], 0,
     "L'attaque provoque l'entrée en guerre des États-Unis."],
    ["Sur quelle période s'étend le miracle économique japonais ?", ["Une croissance très rapide des années 1950 aux années 1980", "Une reconstruction d'après-guerre", "Une industrialisation Meiji", "Une expansion des années 1990"], 0,
     "Elle s'achève avec l'éclatement d'une bulle spéculative au début des années 1990.", 3],
  ]),

  notion("hm4-afrique-royaumes", S, "Royaumes et empires africains",
    "Ghana, Mali, Songhaï, Éthiopie.",
    "Plusieurs grands empires ont structuré l'Afrique de l'Ouest médiévale.",
    2, [
    ["Qu'est-ce que l'empire du Ghana médiéval ?", ["Un empire ouest-africain prospérant par le commerce transsaharien", "Le territoire de l'actuel Ghana", "Un royaume côtier", "Un empire du Sahel oriental"], 0,
     "Il se situait bien plus au nord que l'État moderne qui a repris son nom."],
    ["Quel empereur du Mali a marqué son pèlerinage à La Mecque ?", ["Mansa Moussa", "Soundiata Keïta", "Askia Mohammed", "Sunni Ali"], 0,
     "Ses dépenses en or auraient déstabilisé les cours au Caire en 1324."],
    ["Qui a fondé l'empire du Mali ?", ["Soundiata Keïta", "Mansa Moussa", "Sunni Ali Ber", "Askia Mohammed"], 0,
     "La Charte du Manden lui est traditionnellement associée."],
    ["Quelle ville était un grand centre intellectuel du Sahel ?", ["Tombouctou", "Gao", "Djenné", "Ouagadougou"], 0,
     "Ses manuscrits témoignent d'une intense activité savante."],
    ["Quel empire a succédé au Mali dans la boucle du Niger ?", ["L'empire songhaï", "L'empire du Ghana", "L'empire du Kanem", "L'empire mossi"], 0,
     "Il s'effondre après la défaite de Tondibi face aux Marocains en 1591."],
    ["Qu'est-ce que le royaume d'Aksoum ?", ["Un royaume de la Corne de l'Afrique christianisé au IVe siècle", "Un royaume nubien", "Un sultanat somalien", "Un royaume yéménite"], 0,
     "Il frappait sa propre monnaie et contrôlait le commerce de la mer Rouge."],
    ["Qu'est-ce que le royaume du Kongo ?", ["Un royaume d'Afrique centrale en contact précoce avec le Portugal", "Un royaume d'Afrique de l'Est", "Un empire sahélien", "Un royaume du Congo colonial"], 0,
     "Son souverain s'est converti au christianisme dès la fin du XVe siècle."],
    ["Qu'est-ce que le Grand Zimbabwe ?", ["Une cité de pierre d'Afrique australe des XIIIe-XVe siècles", "Un royaume swahili", "Une cité minière portugaise", "Un site funéraire bantou"], 0,
     "Ses murailles sèches, sans mortier, s'élèvent à plus de dix mètres."],
    ["Qu'est-ce que la civilisation swahilie ?", ["Un ensemble de cités marchandes de la côte est-africaine", "Un empire intérieur", "Une confédération arabe", "Un royaume insulaire"], 0,
     "Kilwa, Mombasa et Zanzibar en étaient des pôles majeurs."],
    ["Pourquoi l'histoire africaine précoloniale est-elle longtemps restée méconnue ?", ["Elle a été négligée par une historiographie centrée sur l'écrit européen", "Elle n'a laissé aucune trace", "Les sources ont disparu", "Elle a été détruite lors de la colonisation"], 0,
     "Traditions orales, archéologie et sources arabes en permettent l'étude.", 3],
  ]),

  notion("hm4-amerique-precolombienne", S, "L'Amérique précolombienne",
    "Mayas, Aztèques, Incas.",
    "Trois grandes civilisations dominaient l'Amérique à l'arrivée des Européens.",
    2, [
    ["Quelle civilisation mésoaméricaine a développé une écriture complète ?", ["Les Mayas", "Les Aztèques", "Les Olmèques", "Les Zapotèques"], 0,
     "Leur écriture, largement déchiffrée depuis les années 1980, est logosyllabique."],
    ["Qu'est-ce que le calendrier maya à compte long ?", ["Un système datant les événements depuis une date d'origine", "Un calendrier lunaire", "Un cycle agricole", "Un calendrier rituel de deux cent soixante jours"], 0,
     "Il a alimenté à tort les prédictions de fin du monde pour 2012."],
    ["Qu'est-ce que la civilisation olmèque ?", ["La plus ancienne grande civilisation mésoaméricaine connue", "Une culture maya primitive", "Une civilisation andine", "Une culture toltèque"], 0,
     "Ses têtes colossales de pierre en sont le vestige le plus spectaculaire."],
    ["Quelle était la capitale aztèque ?", ["Tenochtitlan", "Teotihuacan", "Tula", "Cholula"], 0,
     "Bâtie sur une île du lac Texcoco, à l'emplacement de l'actuelle Mexico."],
    ["Qu'est-ce que Teotihuacan ?", ["Une immense cité antérieure aux Aztèques", "La capitale toltèque", "Une cité maya du nord", "Une ville aztèque secondaire"], 0,
     "Son origine et l'identité de ses fondateurs restent débattues."],
    ["Qu'est-ce qu'une chinampa ?", ["Un jardin flottant cultivé sur les lacs aztèques", "Une terrasse agricole", "Un canal d'irrigation", "Un champ surélevé andin"], 0,
     "Ce système offrait des rendements exceptionnels autour de Tenochtitlan."],
    ["Comment l'empire inca s'appelait-il ?", ["Le Tawantinsuyu", "Le Cuzco", "L'empire du Soleil", "Le Chinchaysuyu"], 0,
     "Le nom signifie les quatre régions réunies."],
    ["Qu'est-ce qu'un quipu ?", ["Un ensemble de cordelettes nouées servant à enregistrer des données", "Un calendrier inca", "Un instrument de mesure", "Une écriture pictographique"], 0,
     "Leur capacité à encoder autre chose que des nombres reste discutée."],
    ["Qu'est-ce que le Machu Picchu ?", ["Un site inca d'altitude construit au XVe siècle", "Une forteresse de résistance inca", "Une cité préinca", "Un centre religieux colonial"], 0,
     "Il a probablement servi de résidence royale et de centre religieux."],
    ["Quelle cause a le plus contribué à l'effondrement démographique amérindien ?", ["Les maladies apportées par les Européens", "Les guerres de conquête", "Le travail forcé", "Les famines"], 0,
     "Variole, rougeole et typhus ont décimé des populations sans immunité.", 3],
  ]),

  notion("hm4-empire-byzantin", S, "Byzance, mille ans d'empire",
    "Constantinople, Justinien, chute.",
    "L'Empire romain d'Orient a survécu mille ans à la chute de Rome.",
    2, [
    ["Quand Constantinople a-t-elle été fondée comme capitale ?", ["En 330, par Constantin", "En 395", "En 476", "En 285"], 0,
     "Sur le site de l'ancienne cité grecque de Byzance."],
    ["Quel empereur byzantin a reconquis une partie de l'Occident ?", ["Justinien", "Héraclius", "Basile II", "Constantin V"], 0,
     "Ses généraux reprennent l'Afrique du Nord, l'Italie et une partie de l'Espagne."],
    ["Qu'est-ce que le Code Justinien ?", ["Une compilation du droit romain au VIe siècle", "Un code byzantin nouveau", "Un recueil canonique", "Un code militaire"], 0,
     "Il a transmis le droit romain à l'Europe médiévale et moderne."],
    ["Qu'est-ce que Sainte-Sophie ?", ["Une basilique construite sous Justinien à Constantinople", "Une église fondée par Constantin", "Une cathédrale latine", "Un palais impérial"], 0,
     "Devenue mosquée en 1453, puis musée en 1935, puis à nouveau mosquée en 2020."],
    ["Qu'est-ce que la querelle des images à Byzance ?", ["Un conflit sur la licéité des représentations religieuses", "Un débat théologique sur la Trinité", "Une controverse liturgique", "Un conflit sur les reliques"], 0,
     "L'iconoclasme a divisé l'empire aux VIIIe et IXe siècles."],
    ["À quoi les Byzantins employaient-ils le feu grégeois ?", ["Une arme incendiaire navale byzantine", "Un explosif ancien", "Une flèche enflammée", "Un mélange de poudre"], 0,
     "Sa composition exacte reste inconnue aujourd'hui."],
    ["Quel événement de 1054 a divisé la chrétienté ?", ["Le schisme entre Rome et Constantinople", "La chute de Constantinople", "La première croisade", "Le concile de Nicée"], 0,
     "Les excommunications mutuelles n'ont été levées qu'en 1965."],
    ["Que s'est-il passé lors de la quatrième croisade ?", ["Constantinople a été pillée par les croisés en 1204", "Jérusalem a été reprise", "L'Égypte a été conquise", "Les croisés ont échoué en Syrie"], 0,
     "L'empire ne s'en est jamais totalement remis."],
    ["Quand Constantinople est-elle tombée ?", ["En 1453, face aux Ottomans", "En 1204", "En 1461", "En 1492"], 0,
     "Mehmed II en fait la capitale de l'Empire ottoman."],
    ["Quel héritage Byzance a-t-elle laissé ?", ["La transmission du droit romain et de la culture grecque", "Un empire commercial", "Une organisation militaire", "Un modèle politique républicain"], 0,
     "L'exil de ses savants a nourri la Renaissance italienne.", 3],
  ]),

  notion("hm4-monde-musulman", S, "Le monde musulman médiéval",
    "Califats, savoirs, échanges.",
    "Le monde musulman médiéval a été un carrefour majeur de savoirs.",
    2, [
    ["Qu'est-ce que le califat omeyyade ?", ["Un califat dont la capitale était Damas, de 661 à 750", "Un califat de Bagdad", "Un califat égyptien", "Un califat andalou seul"], 0,
     "Une branche omeyyade s'est ensuite maintenue en al-Andalus."],
    ["Qu'est-ce que le califat abbasside ?", ["Un califat installé à Bagdad à partir de 762", "Un califat de Damas", "Un califat fatimide", "Un califat ottoman"], 0,
     "Son apogée culturel se situe aux VIIIe et IXe siècles."],
    ["Qu'est-ce que la Maison de la sagesse ?", ["Un centre de traduction et de recherche à Bagdad", "Une université cairote", "Une bibliothèque andalouse", "Une école de droit"], 0,
     "Des textes grecs, persans et indiens y ont été traduits en arabe."],
    ["Qui était al-Khwarizmi ?", ["Un mathématicien à l'origine du mot algorithme", "Un médecin persan", "Un astronome andalou", "Un philosophe de Bagdad"], 0,
     "Le mot algèbre vient du titre de l'un de ses ouvrages."],
    ["Qui était Avicenne ?", ["Un médecin et philosophe persan auteur du Canon de la médecine", "Un mathématicien arabe", "Un astronome égyptien", "Un juriste andalou"], 0,
     "Son Canon a été enseigné dans les universités européennes pendant des siècles."],
    ["Qui était Averroès ?", ["Un philosophe andalou commentateur d'Aristote", "Un médecin de Bagdad", "Un juriste persan", "Un astronome maghrébin"], 0,
     "Ses commentaires ont profondément marqué la scolastique latine."],
    ["Qu'est-ce qu'al-Andalus ?", ["La partie de la péninsule Ibérique sous domination musulmane", "Un royaume maghrébin", "Une province fatimide", "Un émirat nord-africain"], 0,
     "Elle a duré de 711 à 1492, avec une emprise territoriale variable."],
    ["Qu'est-ce que le califat fatimide ?", ["Un califat chiite fondé au Maghreb puis établi au Caire", "Un califat sunnite égyptien", "Un califat syrien", "Un califat andalou"], 0,
     "Il a fondé la ville du Caire en 969."],
    ["Qu'est-ce que la mosquée-université al-Qarawiyyin ?", ["Un établissement de Fès fondé au IXe siècle", "Une université cairote", "Une école de Bagdad", "Une madrasa andalouse"], 0,
     "Elle est souvent présentée comme la plus ancienne institution universitaire encore en activité."],
    ["Quel rôle le monde musulman a-t-il joué dans la transmission des savoirs ?", ["Il a traduit, conservé et prolongé les héritages grec, persan et indien", "Il a seulement conservé les textes grecs", "Il a rompu avec les savoirs antiques", "Il a exclusivement produit des savoirs nouveaux"], 0,
     "Les traductions de l'arabe vers le latin ont irrigué l'Europe médiévale.", 3],
  ]),

  notion("hm4-mongols", S, "Gengis Khan et ses successeurs",
    "Conquêtes, organisation, héritage.",
    "L'empire mongol fut le plus vaste empire terrestre continu de l'histoire.",
    2, [
    ["Qui a unifié les tribus mongoles ?", ["Gengis Khan, en 1206", "Kubilai Khan", "Ögödei", "Batu"], 0,
     "Le titre de Gengis Khan lui est conféré lors d'une assemblée des chefs."],
    ["Qu'est-ce que le yassa ?", ["Un code de lois mongol", "Un conseil tribal", "Un système militaire", "Un tribut imposé"], 0,
     "Son contenu exact ne nous est connu que par des mentions indirectes."],
    ["Comment l'armée mongole était-elle organisée ?", ["En unités décimales, jusqu'aux tumens de dix mille hommes", "En clans tribaux", "En légions", "En corps de cavalerie autonomes"], 0,
     "Cette structure permettait une discipline et une coordination remarquables."],
    ["Quelle ville a été détruite par les Mongols en 1258 ?", ["Bagdad", "Damas", "Le Caire", "Samarcande"], 0,
     "La prise met fin au califat abbasside."],
    ["Où l'avancée mongole vers l'ouest a-t-elle été arrêtée ?", ["À Aïn Djalout, en 1260", "À Vienne", "À Constantinople", "En Hongrie"], 0,
     "Les Mamelouks d'Égypte y remportent une victoire décisive."],
    ["Qu'est-ce que la Horde d'Or ?", ["Un khanat mongol dominant les steppes russes", "Une armée d'élite mongole", "Un khanat persan", "Un trésor impérial"], 0,
     "Sa domination sur les principautés russes a duré plus de deux siècles."],
    ["Qu'est-ce que l'Ilkhanat ?", ["Un khanat mongol établi en Perse", "Un khanat d'Asie centrale", "Un khanat chinois", "Un khanat de la steppe occidentale"], 0,
     "Ses souverains ont fini par se convertir à l'islam."],
    ["Qu'est-ce que la paix mongole ?", ["Une période de sécurité des routes commerciales eurasiatiques", "Un traité entre khanats", "Une trêve avec la Chine", "Une pacification des steppes"], 0,
     "Elle a facilité les voyages, dont celui de Marco Polo."],
    ["Quel effet la paix mongole a-t-elle eu sur les épidémies ?", ["Elle a favorisé la diffusion de la peste vers l'Europe", "Elle n'a eu aucun effet", "Elle a limité les contagions", "Elle a causé des famines"], 0,
     "La peste noire de 1347 a suivi les routes commerciales réactivées."],
    ["Qui était Tamerlan ?", ["Un conquérant turco-mongol du XIVe siècle basé à Samarcande", "Un successeur direct de Gengis Khan", "Un khan de la Horde d'Or", "Un souverain ottoman"], 0,
     "Sa dynastie a donné naissance à l'Empire moghol en Inde.", 3],
  ]),

  notion("hm4-ottomans", S, "L'Empire ottoman",
    "Expansion, apogée, déclin.",
    "L'Empire ottoman a duré plus de six siècles sur trois continents.",
    2, [
    ["Quand l'Empire ottoman a-t-il été fondé ?", ["Vers 1300, en Anatolie", "En 1453", "En 1517", "En 1250"], 0,
     "Osman Ier lui donne son nom."],
    ["Quel sultan a pris Constantinople ?", ["Mehmed II", "Bayezid Ier", "Selim Ier", "Soliman le Magnifique"], 0,
     "Il est surnommé le Conquérant."],
    ["Sous quel sultan l'empire atteint-il son apogée ?", ["Soliman le Magnifique", "Mehmed II", "Selim Ier", "Murad IV"], 0,
     "Son règne, de 1520 à 1566, marque l'extension maximale en Europe."],
    ["Qu'est-ce que le système du devchirmé ?", ["Un prélèvement d'enfants chrétiens formés au service de l'État", "Un impôt sur les non-musulmans", "Un service militaire obligatoire", "Un recrutement de mercenaires"], 0,
     "Il alimentait notamment le corps des janissaires."],
    ["Qu'est-ce que les janissaires ?", ["Un corps d'infanterie d'élite au service du sultan", "La cavalerie ottomane", "Une garde palatiale", "Une milice provinciale"], 0,
     "Leur puissance politique a conduit à leur suppression violente en 1826."],
    ["Qu'est-ce que le système des millets ?", ["Une organisation des communautés religieuses avec une autonomie interne", "Un découpage administratif", "Un système fiscal", "Une organisation militaire"], 0,
     "Chaque communauté gérait son droit familial et ses institutions."],
    ["Quel échec militaire marque un tournant en 1683 ?", ["Le second siège de Vienne", "La bataille de Lépante", "La perte de la Hongrie", "La bataille de Mohács"], 0,
     "Le recul territorial en Europe s'amorce ensuite durablement."],
    ["Qu'est-ce que les Tanzimat ?", ["Des réformes de modernisation menées au XIXe siècle", "Une constitution ottomane", "Une réforme militaire", "Un programme fiscal"], 0,
     "Elles visaient à moderniser l'administration, l'armée et le statut des sujets."],
    ["Qu'est-ce que la question d'Orient ?", ["Les rivalités européennes autour du déclin ottoman", "Un conflit religieux", "Une crise balkanique isolée", "Un différend russo-turc"], 0,
     "Elle occupe la diplomatie européenne tout au long du XIXe siècle."],
    ["Comment l'Empire ottoman a-t-il pris fin ?", ["Par sa dissolution après la Première Guerre mondiale et la proclamation de la République turque", "Par une révolution en 1908", "Par le traité de Sèvres seul", "Par une abdication en 1918"], 0,
     "La République est proclamée en 1923 par Mustafa Kemal.", 3],
  ]),

  notion("hm4-decouvertes", S, "Explorations et conquêtes maritimes",
    "Navigations, conquêtes, conséquences.",
    "Les voyages du XVe siècle ont mis en relation des mondes jusque-là séparés.",
    2, [
    ["Quel pays a lancé les premières grandes expéditions atlantiques ?", ["Le Portugal", "l'Espagne", "La France", "Les Provinces-Unies"], 0,
     "Henri le Navigateur y organise des expéditions le long de l'Afrique dès le XVe siècle."],
    ["Qui a contourné le cap de Bonne-Espérance en 1488 ?", ["Bartolomeu Dias", "Vasco de Gama", "Christophe Colomb", "Pedro Álvares Cabral"], 0,
     "Vasco de Gama atteint l'Inde dix ans plus tard."],
    ["Qu'est-ce que le traité de Tordesillas ?", ["Un partage du monde entre l'Espagne et le Portugal en 1494", "Un traité commercial", "Un accord de paix ibérique", "Un traité de navigation"], 0,
     "Il explique que le Brésil soit devenu portugais."],
    ["Qui a réalisé le premier tour du monde ?", ["L'expédition de Magellan, achevée par Elcano", "Magellan seul", "Francis Drake", "Vasco de Gama"], 0,
     "Magellan meurt aux Philippines en 1521 ; Elcano ramène l'unique navire survivant."],
    ["Qui a conquis l'empire aztèque ?", ["Hernán Cortés", "Francisco Pizarro", "Diego de Almagro", "Pedro de Alvarado"], 0,
     "Il s'appuie sur les rivalités entre peuples soumis aux Aztèques."],
    ["Qui a conquis l'empire inca ?", ["Francisco Pizarro", "Hernán Cortés", "Vasco Núñez de Balboa", "Diego de Almagro"], 0,
     "Il profite d'une guerre de succession entre Atahualpa et Huáscar."],
    ["Qu'est-ce que l'échange colombien ?", ["Le transfert d'espèces, de maladies et de personnes entre continents", "Un accord commercial", "Un système de troc colonial", "Un réseau de comptoirs"], 0,
     "Il a transformé l'alimentation et la démographie des deux hémisphères."],
    ["Qu'est-ce que le système de l'encomienda ?", ["Une attribution de main-d'œuvre indigène à des colons espagnols", "Une concession de terres", "Un impôt colonial", "Un système de traite"], 0,
     "Il a fonctionné comme un travail forcé malgré son cadre juridique."],
    ["Qui a dénoncé le traitement des Amérindiens au XVIe siècle ?", ["Bartolomé de Las Casas", "Francisco de Vitoria seul", "Juan Ginés de Sepúlveda", "Hernán Cortés"], 0,
     "La controverse de Valladolid l'oppose à Sepúlveda en 1550."],
    ["Quelle conséquence les découvertes ont-elles eue sur l'Europe ?", ["Un afflux de métaux précieux et un déplacement des routes commerciales", "Un appauvrissement général", "Une stagnation économique", "Un repli commercial"], 0,
     "L'Atlantique supplante progressivement la Méditerranée comme axe majeur.", 3],
  ]),

  notion("hm4-traite-esclavage", S, "La traite atlantique et l'esclavage",
    "Systèmes, abolitions, mémoire.",
    "La traite atlantique a déporté plus de douze millions d'Africains.",
    2, [
    ["Combien d'Africains ont été déportés par la traite atlantique ?", ["Plus de douze millions", "Environ trois millions", "Environ six millions", "Plus de vingt millions"], 0,
     "Environ dix millions et demi ont survécu à la traversée."],
    ["Quels continents le commerce triangulaire reliait-il ?", ["Un circuit reliant l'Europe, l'Afrique et les Amériques", "Un commerce entre trois puissances", "Un échange colonial direct", "Un système de troc atlantique"], 0,
     "De nombreux navires ne suivaient toutefois pas ce schéma en trois étapes."],
    ["Quelle étape de la traite appelle-t-on le passage du milieu ?", ["La traversée atlantique des captifs africains", "Une escale intermédiaire", "Une route commerciale", "Un port de transit"], 0,
     "La mortalité y atteignait fréquemment quinze pour cent."],
    ["Qu'est-ce que le Code noir ?", ["Un texte de 1685 réglementant l'esclavage dans les colonies françaises", "Une loi d'abolition", "Un code colonial général", "Un règlement de plantation"], 0,
     "Il définissait les esclaves comme des biens meubles."],
    ["Quand la France a-t-elle aboli l'esclavage définitivement ?", ["En 1848", "En 1794", "En 1815", "En 1833"], 0,
     "L'abolition de 1794 avait été annulée par Bonaparte en 1802."],
    ["Qui a porté l'abolition de 1848 en France ?", ["Victor Schœlcher", "L'abbé Grégoire", "Alexis de Tocqueville", "Lamartine"], 0,
     "Le décret est signé le 27 avril 1848."],
    ["Quelle révolution a mené à l'indépendance d'Haïti ?", ["La révolution haïtienne, de 1791 à 1804", "La révolte de la Jamaïque", "La guerre des Cacos", "La révolte de Saint-Domingue de 1848"], 0,
     "C'est la seule révolte d'esclaves ayant abouti à la fondation d'un État."],
    ["Qui était Toussaint Louverture ?", ["Un chef de la révolution haïtienne", "Le premier président d'Haïti", "Un général français", "Un gouverneur colonial"], 0,
     "Déporté en France, il meurt au fort de Joux en 1803."],
    ["Quand les États-Unis ont-ils aboli l'esclavage ?", ["En 1865, avec le treizième amendement", "En 1863", "En 1861", "En 1870"], 0,
     "La proclamation d'émancipation de 1863 ne concernait que les États sécessionnistes."],
    ["Qu'est-ce que la loi Taubira de 2001 ?", ["Une loi française reconnaissant la traite et l'esclavage comme crime contre l'humanité", "Une loi de réparation", "Une loi mémorielle sur la colonisation", "Une loi sur l'enseignement de l'histoire"], 0,
     "Elle prévoit aussi une place accrue de ce sujet dans les programmes scolaires.", 3],
  ]),

  notion("hm4-revolutions-atlantiques", S, "Les révolutions atlantiques",
    "Amérique, France, Amérique latine.",
    "Une vague révolutionnaire a traversé l'Atlantique entre 1776 et 1825.",
    2, [
    ["Quand les États-Unis ont-ils déclaré leur indépendance ?", ["Le 4 juillet 1776", "En 1783", "En 1774", "En 1789"], 0,
     "La guerre se poursuit jusqu'au traité de Paris de 1783."],
    ["Qui a rédigé l'essentiel de la Déclaration d'indépendance américaine ?", ["Thomas Jefferson", "Benjamin Franklin", "John Adams", "George Washington"], 0,
     "Franklin et Adams y ont apporté des corrections."],
    ["Quel rôle la France a-t-elle joué dans l'indépendance américaine ?", ["Un soutien militaire et financier décisif", "Une neutralité bienveillante", "Un soutien diplomatique seul", "Une opposition initiale"], 0,
     "L'effort financier a contribué à la crise des finances royales françaises."],
    ["Qu'est-ce que la Constitution américaine de 1787 ?", ["Le texte fondateur d'un régime fédéral et présidentiel", "Une déclaration de droits", "Un traité entre États", "Une charte confédérale"], 0,
     "Elle est la plus ancienne constitution écrite encore en vigueur."],
    ["Qu'est-ce que le Bill of Rights américain ?", ["Les dix premiers amendements garantissant les libertés fondamentales", "La déclaration d'indépendance", "Une charte des États", "Un préambule constitutionnel"], 0,
     "Ratifié en 1791, il répondait aux réticences de plusieurs États."],
    ["Qui était Simón Bolívar ?", ["Un dirigeant de l'indépendance de plusieurs pays d'Amérique du Sud", "Un général espagnol", "Un président argentin", "Un révolutionnaire mexicain"], 0,
     "La Bolivie porte son nom."],
    ["Qui était José de San Martín ?", ["Un libérateur de l'Argentine, du Chili et du Pérou", "Un général espagnol", "Un chef d'État vénézuélien", "Un révolutionnaire colombien"], 0,
     "Sa traversée des Andes en 1817 est restée célèbre."],
    ["Comment le Brésil est-il devenu indépendant ?", ["Par la proclamation d'un empire dirigé par l'héritier portugais", "Par une guerre de libération", "Par une révolution républicaine", "Par un accord avec le Portugal"], 0,
     "Pierre Ier proclame l'indépendance en 1822 et devient empereur."],
    ["Quelle idée circule d'une révolution à l'autre ?", ["La souveraineté du peuple et les droits naturels", "Le nationalisme ethnique", "Le socialisme", "Le libre-échange"], 0,
     "Les textes révolutionnaires circulent d'un continent à l'autre en quelques mois."],
    ["Quelle limite ces révolutions ont-elles eue ?", ["Elles ont souvent maintenu l'esclavage et exclu les femmes", "Elles ont échoué militairement", "Elles n'ont pas duré", "Elles ont été purement politiques"], 0,
     "La révolution haïtienne fait exception sur la question de l'esclavage.", 3],
  ]),

  notion("hm4-nationalismes", S, "Nations et nationalismes au XIXe siècle",
    "Unifications, empires, identités.",
    "Le XIXe siècle voit naître ou s'unifier de nombreux États-nations.",
    2, [
    ["Quand l'unité italienne a-t-elle été proclamée ?", ["En 1861", "En 1870", "En 1848", "En 1859"], 0,
     "Rome ne devient capitale qu'en 1871."],
    ["Qui était Giuseppe Garibaldi ?", ["Un chef militaire de l'unification italienne", "Le premier roi d'Italie", "Un ministre piémontais", "Un théoricien du Risorgimento"], 0,
     "L'expédition des Mille en Sicile est son fait d'armes le plus célèbre."],
    ["Qui a mené l'unification allemande ?", ["Otto von Bismarck", "Guillaume Ier seul", "Frédéric-Guillaume IV", "Helmuth von Moltke"], 0,
     "Trois guerres successives y ont conduit entre 1864 et 1871."],
    ["Où l'Empire allemand a-t-il été proclamé ?", ["Dans la galerie des Glaces de Versailles", "À Berlin", "À Francfort", "À Potsdam"], 0,
     "Le 18 janvier 1871, après la défaite française."],
    ["Qu'est-ce que le printemps des peuples ?", ["Une vague révolutionnaire européenne en 1848", "Une révolte nationaliste balkanique", "Un mouvement libéral de 1830", "Une série de réformes impériales"], 0,
     "Presque tous les mouvements ont été réprimés dans l'année."],
    ["Qu'est-ce que l'Empire austro-hongrois ?", ["Une double monarchie créée en 1867", "Un empire unifié", "Une confédération germanique", "Une union personnelle ancienne"], 0,
     "Le compromis reconnaît une large autonomie à la Hongrie."],
    ["Quelle question a déstabilisé les Balkans au XIXe siècle ?", ["L'émancipation des peuples face au recul ottoman", "Les rivalités religieuses", "Les conflits frontaliers russes", "Les questions économiques"], 0,
     "Les puissances européennes y ont chacune poursuivi leurs intérêts."],
    ["Qu'est-ce que le nationalisme romantique ?", ["Une conception de la nation fondée sur la langue et la culture", "Un nationalisme d'État", "Un patriotisme constitutionnel", "Un nationalisme économique"], 0,
     "Herder en est l'un des inspirateurs majeurs."],
    ["Qu'est-ce que la conception française de la nation au XIXe siècle ?", ["Une adhésion politique volontaire, selon Renan", "Une appartenance ethnique", "Une communauté linguistique", "Une unité religieuse"], 0,
     "Renan la définit en 1882 comme un plébiscite de tous les jours."],
    ["Quel effet le nationalisme a-t-il eu au début du XXe siècle ?", ["Il a contribué au déclenchement de la Première Guerre mondiale", "Il a favorisé la paix", "Il a affaibli les États", "Il est resté marginal"], 0,
     "Il s'est combiné aux rivalités impériales et aux alliances militaires.", 3],
  ]),

  notion("hm4-imperialismes", S, "Impérialismes et colonisation",
    "Partage, résistances, conséquences.",
    "L'Europe contrôlait une grande partie du monde à la veille de 1914.",
    2, [
    ["Qu'est-ce que la conférence de Berlin de 1884-1885 ?", ["Une réunion fixant les règles du partage colonial de l'Afrique", "Un traité de paix européen", "Un congrès sur l'esclavage", "Un accord commercial africain"], 0,
     "Aucun représentant africain n'y a été convié."],
    ["Qu'est-ce que le Congo de Léopold II ?", ["Un territoire exploité comme propriété personnelle du roi des Belges", "Une colonie belge classique", "Un protectorat international", "Un comptoir commercial"], 0,
     "Les violences de l'exploitation du caoutchouc ont provoqué un scandale international."],
    ["Qu'est-ce que la révolte des Cipayes ?", ["Un soulèvement en Inde en 1857 contre la Compagnie britannique", "Une révolte paysanne bengalie", "Une guerre anglo-indienne", "Une mutinerie navale"], 0,
     "Elle conduit la Couronne britannique à administrer directement l'Inde."],
    ["Qu'est-ce que la guerre de l'opium ?", ["Un conflit imposant à la Chine le commerce de l'opium britannique", "Une guerre civile chinoise", "Un conflit commercial russe", "Une révolte antidrogue"], 0,
     "Hong Kong est cédée au Royaume-Uni à l'issue du premier conflit."],
    ["Qu'est-ce que la révolte des Boxers ?", ["Un soulèvement antiétranger en Chine autour de 1900", "Une révolte paysanne fiscale", "Un mouvement réformiste", "Une insurrection militaire"], 0,
     "Une coalition de huit puissances l'a réprimée."],
    ["Quel pays africain a résisté victorieusement à une colonisation européenne ?", ["l'Éthiopie", "Le Liberia", "Le Maroc", "Le Soudan"], 0,
     "La victoire d'Adoua en 1896 stoppe l'Italie ; le Liberia n'a pas connu de conquête coloniale."],
    ["Qu'est-ce que la crise de Fachoda ?", ["Une confrontation franco-britannique au Soudan en 1898", "Un conflit colonial en Afrique de l'Ouest", "Une crise marocaine", "Un incident au Congo"], 0,
     "Le recul français a ouvert la voie à l'Entente cordiale."],
    ["Qu'est-ce que le mandat colonial après 1919 ?", ["Une administration de territoires confiée par la Société des Nations", "Une annexion directe", "Un protectorat classique", "Une occupation militaire temporaire"], 0,
     "En pratique, il a souvent fonctionné comme une colonisation ordinaire."],
    ["Quelle justification idéologique la colonisation invoquait-elle ?", ["Une prétendue mission civilisatrice", "Un droit de conquête", "Une nécessité démographique", "Un impératif religieux seul"], 0,
     "Ce discours accompagnait des intérêts économiques et stratégiques concrets."],
    ["Quelle conséquence durable les frontières coloniales ont-elles eue ?", ["Des tracés arbitraires souvent source de conflits ultérieurs", "Une stabilisation régionale", "Une organisation ethnique cohérente", "Un effet limité"], 0,
     "Les États indépendants les ont pourtant majoritairement conservées.", 3],
  ]),

  notion("hm4-guerre-froide-2", S, "La guerre froide, seconde phase",
    "Détente, crises, effondrement.",
    "La guerre froide alterne périodes de tension et de détente.",
    2, [
    ["Que désigne la détente dans les relations Est-Ouest des années 1970 ?", ["Une phase de réduction des tensions entre blocs", "Une fin de la guerre froide", "Un désarmement complet", "Un rapprochement idéologique"], 0,
     "Elle est marquée par les accords SALT et l'Acte final d'Helsinki."],
    ["Qu'est-ce que l'Acte final d'Helsinki de 1975 ?", ["Un accord reconnaissant les frontières et affirmant les droits de l'homme", "Un traité de désarmement", "Un pacte de non-agression", "Un accord commercial Est-Ouest"], 0,
     "Le volet droits de l'homme a été mobilisé par les dissidents de l'Est."],
    ["Qu'est-ce que l'invasion soviétique de l'Afghanistan ?", ["Une intervention de 1979 qui a relancé les tensions", "Une opération de maintien de la paix", "Une intervention de courte durée", "Une occupation négociée"], 0,
     "Elle dure jusqu'en 1989 et affaiblit durablement l'URSS."],
    ["Qu'est-ce que la crise des euromissiles ?", ["Un affrontement sur le déploiement de missiles en Europe dans les années 1980", "Une crise berlinoise", "Un conflit sur les missiles cubains", "Une crise de l'OTAN"], 0,
     "Le traité FNI de 1987 y met fin."],
    ["Qu'est-ce que la perestroïka ?", ["Une politique de restructuration économique en URSS", "Une réforme politique seule", "Une libéralisation culturelle", "Une réforme agraire"], 0,
     "Elle est engagée par Mikhaïl Gorbatchev à partir de 1985."],
    ["Qu'est-ce que la glasnost ?", ["Une politique de transparence et de liberté d'expression", "Une réforme économique", "Une ouverture diplomatique", "Une décentralisation administrative"], 0,
     "Elle a permis une critique publique inédite du système soviétique."],
    ["Qu'est-ce que le syndicat Solidarność ?", ["Un syndicat polonais indépendant fondé en 1980", "Un mouvement dissident tchèque", "Un parti d'opposition hongrois", "Une organisation ouvrière est-allemande"], 0,
     "Lech Wałęsa en était le dirigeant."],
    ["Quand le mur de Berlin est-il tombé ?", ["Le 9 novembre 1989", "En octobre 1989", "En décembre 1989", "En 1990"], 0,
     "L'ouverture résulte en partie d'une annonce confuse d'un responsable est-allemand."],
    ["Quand l'URSS a-t-elle été dissoute ?", ["En décembre 1991", "En 1990", "En août 1991", "En 1992"], 0,
     "Le putsch manqué d'août 1991 en avait précipité le processus."],
    ["Quelle lecture peut-on faire de la fin de la guerre froide ?", ["Une combinaison d'essoufflement économique soviétique et de pressions internes", "Une victoire militaire occidentale", "Un accord négocié entre blocs", "Un effondrement imprévisible sans causes"], 0,
     "Aucune analyse sérieuse n'avait anticipé le calendrier de cet effondrement.", 3],
  ]),

  notion("hm4-decolonisations", S, "Les décolonisations",
    "Indépendances, guerres, conséquences.",
    "La plupart des empires coloniaux ont disparu entre 1945 et 1975.",
    2, [
    ["Quand l'Inde est-elle devenue indépendante ?", ["En 1947", "En 1950", "En 1945", "En 1948"], 0,
     "La partition avec le Pakistan a provoqué des déplacements massifs et des violences."],
    ["Qui a dirigé la lutte non violente pour l'indépendance indienne ?", ["Gandhi", "Nehru", "Jinnah", "Ambedkar"], 0,
     "Nehru devient le premier chef du gouvernement indien."],
    ["Qu'est-ce que la conférence de Bandung ?", ["Une réunion afro-asiatique de 1955 affirmant l'émancipation des peuples colonisés", "Un sommet des non-alignés", "Une conférence de l'ONU", "Un congrès panafricain"], 0,
     "Elle prépare le mouvement des non-alignés."],
    ["Quand l'Indonésie a-t-elle proclamé son indépendance ?", ["En 1945", "En 1949", "En 1950", "En 1947"], 0,
     "Les Pays-Bas ne la reconnaissent qu'en 1949, après un conflit."],
    ["Quelle guerre a marqué la décolonisation française en Asie ?", ["La guerre d'Indochine", "La guerre de Corée", "La guerre du Viêt Nam", "La guerre de Madagascar"], 0,
     "Elle s'achève par la défaite de Diên Biên Phu en 1954."],
    ["Quand la plupart des colonies françaises d'Afrique sont-elles devenues indépendantes ?", ["En 1960", "En 1958", "En 1962", "En 1956"], 0,
     "L'année 1960 est souvent appelée l'année de l'Afrique."],
    ["Quelle guerre d'indépendance a duré de 1954 à 1962 ?", ["La guerre d'Algérie", "La guerre du Maroc", "La guerre de Tunisie", "La guerre du Cameroun"], 0,
     "Les accords d'Évian y mettent fin en mars 1962."],
    ["Qu'est-ce que l'apartheid ?", ["Un régime de ségrégation légale en Afrique du Sud", "Une politique coloniale britannique", "Un système de ségrégation américain", "Une politique de développement séparé rhodésienne"], 0,
     "Institué en 1948, il prend fin en 1991."],
    ["Qui a été le premier président noir d'Afrique du Sud ?", ["Nelson Mandela", "Desmond Tutu", "Thabo Mbeki", "Oliver Tambo"], 0,
     "Élu en 1994, après vingt-sept ans de détention."],
    ["Quelle difficulté les États nouvellement indépendants ont-ils rencontrée ?", ["Des économies dépendantes et des institutions fragiles", "Un manque de population", "Une absence de reconnaissance internationale", "Des ressources naturelles insuffisantes"], 0,
     "L'héritage colonial et les rivalités de la guerre froide ont pesé lourdement.", 3],
  ]),

  notion("hm4-monde-contemporain", S, "Le monde depuis 1990",
    "Mondialisation, conflits, recompositions.",
    "La fin de la guerre froide n'a pas mis fin aux conflits.",
    2, [
    ["Qu'est-ce que la guerre du Golfe de 1991 ?", ["Une coalition internationale libérant le Koweït envahi par l'Irak", "Une guerre entre l'Iran et l'Irak", "Une intervention américaine unilatérale", "Un conflit régional limité"], 0,
     "Elle est menée sous mandat des Nations unies."],
    ["Qu'est-ce que le génocide des Tutsi au Rwanda ?", ["Un génocide ayant fait environ huit cent mille morts en 1994", "Une guerre civile", "Un conflit ethnique régional", "Une crise humanitaire"], 0,
     "La communauté internationale n'est pas intervenue pour l'arrêter."],
    ["Qu'est-ce que la guerre de Bosnie ?", ["Un conflit de 1992 à 1995 marqué par des nettoyages ethniques", "Une guerre d'indépendance croate", "Un conflit serbo-kosovar", "Une guerre civile yougoslave unique"], 0,
     "Le massacre de Srebrenica a été qualifié de génocide par la justice internationale."],
    ["Qu'est-ce que l'Organisation mondiale du commerce ?", ["Une organisation régulant le commerce international, créée en 1995", "Un accord douanier", "Une institution financière", "Un forum économique"], 0,
     "Elle succède au GATT."],
    ["Qu'est-ce que la Cour pénale internationale ?", ["Une juridiction permanente jugeant les crimes les plus graves", "Un tribunal de l'ONU", "Une cour d'arbitrage entre États", "Un tribunal européen"], 0,
     "Créée par le statut de Rome en 1998, elle siège à La Haye."],
    ["Quel événement a marqué le 11 septembre 2001 ?", ["Des attentats aux États-Unis ayant fait près de trois mille morts", "Une attaque contre une ambassade", "Un attentat en Europe", "Une crise diplomatique"], 0,
     "Ils déclenchent l'intervention en Afghanistan puis une reconfiguration sécuritaire mondiale."],
    ["Qu'est-ce que la crise financière de 2008 ?", ["Une crise partie du marché immobilier américain, devenue mondiale", "Une crise bancaire européenne", "Une crise de dette souveraine", "Un krach boursier isolé"], 0,
     "Elle a entraîné la plus grave récession mondiale depuis 1945."],
    ["Qu'est-ce que le printemps arabe ?", ["Une vague de soulèvements dans le monde arabe à partir de 2010", "Une révolution égyptienne isolée", "Un mouvement réformiste institutionnel", "Une crise politique régionale"], 0,
     "Ses issues ont été très différentes d'un pays à l'autre."],
    ["Qu'est-ce que l'accord de Paris sur le climat ?", ["Un accord de 2015 visant à limiter le réchauffement mondial", "Un protocole de réduction des émissions contraignant", "Un traité européen", "Un accord sur la biodiversité"], 0,
     "Il vise à contenir la hausse nettement en dessous de deux degrés."],
    ["Quelle recomposition majeure marque le début du XXIe siècle ?", ["La montée en puissance de la Chine et le basculement vers l'Asie", "Le renforcement du bloc occidental", "L'unification européenne complète", "Le retrait des grandes puissances"], 0,
     "Le poids économique mondial s'est déplacé vers l'Asie orientale en une génération.", 3],
  ]),

  notion("hm4-histoire-sciences-monde", S, "Histoire des sciences dans le monde",
    "Circulations, ruptures, institutions.",
    "La science moderne s'est construite par des échanges entre plusieurs civilisations.",
    2, [
    ["D'où vient notre système de chiffres ?", ["d'Inde, transmis par le monde arabe", "De Grèce", "De Rome", "De Chine"], 0,
     "D'où l'expression chiffres arabes, malgré une origine indienne."],
    ["Qu'est-ce que l'astronomie de Maragha ?", ["Une école d'astronomes persans du XIIIe siècle", "Une observation grecque tardive", "Une école indienne", "Un observatoire ottoman"], 0,
     "Ses modèles mathématiques ont peut-être influencé Copernic."],
    ["Quelle invention chinoise a transformé la navigation ?", ["La boussole", "L'astrolabe", "Le gouvernail d'étambot seul", "Le sextant"], 0,
     "La Chine en fait usage plusieurs siècles avant l'Europe."],
    ["Quelles sont les quatre grandes inventions traditionnellement attribuées à la Chine ?", ["Papier, imprimerie, poudre et boussole", "Papier, verre, poudre et boussole", "Imprimerie, papier, soie et poudre", "Poudre, boussole, porcelaine et papier"], 0,
     "Cette liste est une construction historiographique, mais chacune est bien attestée."],
    ["Qu'est-ce que la révolution scientifique du XVIIe siècle ?", ["Une transformation des méthodes et des théories en Europe", "L'invention de la méthode expérimentale seule", "La naissance des universités", "La création des académies"], 0,
     "Galilée, Descartes et Newton en sont des figures centrales."],
    ["Qu'est-ce que la Royal Society ?", ["Une académie scientifique britannique fondée en 1660", "Une université anglaise", "Un observatoire royal", "Un collège de médecine"], 0,
     "Sa devise invite à ne rien tenir pour acquis sur parole."],
    ["Qu'est-ce que l'Académie des sciences française ?", ["Une institution scientifique fondée en 1666", "Une université d'État", "Un collège royal", "Un bureau des longitudes"], 0,
     "Colbert en est à l'origine sous Louis XIV."],
    ["Qu'est-ce que la professionnalisation de la science au XIXe siècle ?", ["Le passage d'une pratique de savants isolés à des métiers institués", "Une spécialisation des disciplines seule", "Une industrialisation de la recherche", "Un financement public généralisé"], 0,
     "Le mot scientist apparaît en anglais dans les années 1830."],
    ["Qu'est-ce que la big science ?", ["Une recherche à très grande échelle mobilisant des moyens considérables", "Une science de la complexité", "Une recherche fondamentale", "Une science internationale"], 0,
     "Le projet Manhattan et le CERN en sont des exemples."],
    ["Quelle idée fausse la mondialisation des sciences dément-elle ?", ["Que la science moderne serait une création purement européenne", "Que les échanges scientifiques sont récents", "Que les sciences sont universelles", "Que la recherche est collective"], 0,
     "Les historiens documentent des circulations continues entre aires culturelles.", 3],
  ]),

  notion("hm4-migrations-histoire", S, "Les migrations dans l'histoire",
    "Peuplements, exils, diasporas.",
    "Les migrations ont façonné le peuplement de tous les continents.",
    2, [
    ["Comment l'Homo sapiens a-t-il peuplé la planète ?", ["Par des migrations successives depuis l'Afrique", "Par une évolution parallèle sur chaque continent", "Par une migration unique et rapide", "Par un peuplement depuis l'Asie centrale"], 0,
     "Les données génétiques confirment une origine africaine commune."],
    ["Qu'est-ce que les grandes invasions du Ve siècle ?", ["Des migrations de peuples entrant dans l'Empire romain", "Des raids militaires isolés", "Une conquête organisée", "Une colonisation planifiée"], 0,
     "Le terme d'invasions a été largement nuancé par l'historiographie récente."],
    ["Que recouvre le terme de diaspora juive ?", ["La dispersion des communautés juives hors de Judée", "Un exil unique", "Une migration médiévale", "Un déplacement moderne"], 0,
     "Elle s'étale sur plusieurs siècles et prend des formes très diverses."],
    ["Qu'est-ce que l'émigration européenne du XIXe siècle ?", ["Un départ de plusieurs dizaines de millions de personnes vers les Amériques", "Une migration interne à l'Europe", "Un mouvement colonial encadré", "Un exil politique massif"], 0,
     "L'Irlande, l'Italie et l'Europe centrale y ont particulièrement contribué."],
    ["Qu'est-ce qu'Ellis Island ?", ["Un centre d'accueil des immigrants à New York", "Un port de départ européen", "Un centre de rétention moderne", "Une île de quarantaine britannique"], 0,
     "Plus de douze millions de personnes y ont été enregistrées entre 1892 et 1954."],
    ["Qu'est-ce que la partition de l'Inde en 1947 ?", ["Un déplacement de plus de dix millions de personnes", "Une migration progressive", "Un échange de populations organisé", "Un exode limité aux villes"], 0,
     "Les violences qui l'ont accompagnée ont fait des centaines de milliers de morts."],
    ["Qu'est-ce que le statut de réfugié ?", ["Une protection définie par la convention de Genève de 1951", "Un statut national temporaire", "Une protection humanitaire ponctuelle", "Un droit d'asile inconditionnel"], 0,
     "Il repose sur une crainte fondée de persécution."],
    ["Qu'est-ce qu'un déplacé interne ?", ["Une personne déplacée à l'intérieur de son propre pays", "Un migrant économique", "Un réfugié non enregistré", "Un demandeur d'asile"], 0,
     "Ils sont plus nombreux que les réfugiés au sens strict."],
    ["Quelle part de la population mondiale vit hors de son pays de naissance ?", ["Environ trois à quatre pour cent", "Environ dix pour cent", "Environ un pour cent", "Environ quinze pour cent"], 0,
     "Cette proportion est remarquablement stable sur le long terme."],
    ["Que montre l'histoire des migrations ?", ["La mobilité est une constante des sociétés humaines", "Les migrations sont un phénomène moderne", "Les sociétés sont majoritairement sédentaires", "Les déplacements sont surtout contraints"], 0,
     "Les périodes de fermeture des frontières sont historiquement récentes.", 3],
  ]),
];
