/**
 * Histoire du monde, deuxième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Histoire du monde";

export const CG_HISTOIRE_MONDE_2: SeedSkill[] = [
  notion("hm2-mesopotamie", S, "La Mésopotamie",
    "Entre le Tigre et l'Euphrate : les premières cités, la première écriture, les premiers codes de lois.",
    "Sumer, Akkad, Babylone, Assyrie se succèdent sur le même territoire, pas côte à côte.",
    2, [
    ["Quelle civilisation invente l'écriture cunéiforme vers 3300 avant notre ère ?", ["Les Sumériens", "Les Akkadiens", "Les Assyriens", "Les Hittites"], 0,
     "D'abord pour la comptabilité des temples, avant de servir aux récits et aux lois."],
    ["Quel roi de Babylone fait graver un code de lois vers 1750 avant notre ère ?", ["Hammurabi", "Nabuchodonosor II", "Sargon d'Akkad", "Assurbanipal"], 0,
     "La stèle, conservée au Louvre, compte près de trois cents articles fondés sur la loi du talion."],
    ["Quel souverain fonde le premier empire connu, vers 2300 avant notre ère ?", ["Sargon d'Akkad", "Hammurabi", "Gilgamesh", "Ur-Nammu"], 0,
     "Il unifie les cités sumériennes sous une même autorité et impose l'akkadien comme langue administrative."],
    ["Quelle ziggourat est la mieux conservée de Mésopotamie ?", ["Celle d'Ur", "Celle de Babylone", "Celle de Ninive", "Celle d'Assur"], 0,
     "Restaurée sous Saddam Hussein, elle donne une idée de ces tours à degrés portant un temple à leur sommet."],
    ["Quel roi assyrien constitue une immense bibliothèque à Ninive ?", ["Assurbanipal", "Sargon II", "Salmanazar III", "Teglath-Phalasar III"], 0,
     "Plus de trente mille tablettes, dont la version la plus complète de l'Épopée de Gilgamesh."],
    ["Quelle cité mésopotamienne est célèbre pour ses jardins suspendus ?", ["Babylone", "Ninive", "Ur", "Assur"], 0,
     "Comptés parmi les sept merveilles du monde antique, aucun vestige n'en a été identifié avec certitude."],
    ["Quel roi babylonien déporte les élites de Jérusalem en 587 avant notre ère ?", ["Nabuchodonosor II", "Cyrus", "Hammurabi", "Assurbanipal"], 0,
     "L'exil à Babylone dure jusqu'à la conquête perse et marque profondément le judaïsme."],
    ["Quel empire met fin à l'indépendance de Babylone en 539 avant notre ère ?", ["L'Empire perse achéménide", "L'Empire assyrien", "L'Empire hittite", "L'Empire macédonien"], 0,
     "Cyrus II autorise le retour des exilés juifs, ce qui lui vaut une réputation favorable dans la Bible."],
    ["Quel système de numération les Mésopotamiens emploient-ils ?", ["Un système sexagésimal, en base soixante", "Un système décimal", "Un système binaire", "Un système duodécimal"], 0,
     "Nos soixante minutes et nos trois cent soixante degrés en descendent directement."],
    ["Quelle innovation agricole permet l'essor des cités mésopotamiennes ?", ["L'irrigation organisée à grande échelle", "La charrue à soc de fer", "L'assolement triennal", "La culture en terrasses"], 0,
     "Sa gestion collective explique en partie la naissance d'une administration et d'un pouvoir centralisé.", 3],
  ]),

  notion("hm2-egypte-pharaonique", S, "L'Égypte pharaonique",
    "Trois millénaires d'État centralisé, du premier pharaon à la conquête romaine.",
    "L'Ancien, le Moyen et le Nouvel Empire sont séparés par des périodes intermédiaires de division.",
    2, [
    ["Quel pharaon unifie la Haute et la Basse-Égypte selon la tradition ?", ["Narmer", "Khéops", "Ramsès II", "Djéser"], 0,
     "Sa palette, conservée au Caire, le montre coiffé des couronnes des deux royaumes."],
    ["Pour quel pharaon la grande pyramide de Gizeh est-elle édifiée ?", ["Khéops", "Khéphren", "Mykérinos", "Djéser"], 0,
     "Cent quarante-six mètres à l'origine : l'édifice le plus haut du monde pendant près de quatre mille ans."],
    ["Quelle femme règne comme pharaon au XVe siècle avant notre ère ?", ["Hatchepsout", "Néfertiti", "Cléopâtre VII", "Néfertari"], 0,
     "Elle se fait représenter avec la barbe postiche des pharaons. Son successeur tenta d'effacer son nom des monuments."],
    ["Quel pharaon règne soixante-six ans et couvre l'Égypte de monuments ?", ["Ramsès II", "Thoutmôsis III", "Amenhotep III", "Séthi Ier"], 0,
     "Il fait aussi graver partout le récit de la bataille de Qadesh, en réalité indécise."],
    ["Contre quel peuple Ramsès II livre-t-il la bataille de Qadesh ?", ["Les Hittites", "Les Assyriens", "Les Nubiens", "Les Perses"], 0,
     "Le traité qui suit, vers 1259 avant notre ère, est le plus ancien traité de paix connu dont le texte soit conservé."],
    ["Quel tombeau presque intact est découvert en 1922 dans la Vallée des Rois ?", ["Celui de Toutânkhamon", "Celui de Ramsès II", "Celui de Séthi Ier", "Celui d'Akhenaton"], 0,
     "Howard Carter y trouva plus de cinq mille objets. Le pharaon, mort vers dix-neuf ans, était mineur dans l'histoire égyptienne."],
    ["Quelle dynastie d'origine macédonienne règne sur l'Égypte après Alexandre ?", ["Les Lagides, ou Ptolémées", "Les Séleucides", "Les Antigonides", "Les Attalides"], 0,
     "Fondée par un général d'Alexandre, elle s'éteint avec Cléopâtre VII en 30 avant notre ère."],
    ["Quelle bataille scelle en 31 avant notre ère le sort de Cléopâtre et Marc Antoine ?", ["Actium", "Pharsale", "Philippes", "Alexandrie"], 0,
     "Octave, futur Auguste, y remporte une victoire navale décisive. L'Égypte devient province romaine."],
    ["Quel monument abrite la bibliothèque la plus célèbre de l'Antiquité ?", ["Le Mouseion d'Alexandrie", "Le temple de Karnak", "Le Sérapeum de Memphis", "La bibliothèque de Thèbes"], 0,
     "Sa disparition fut progressive, par incendies successifs et abandon, non par une destruction unique."],
    ["Quelle crue annuelle conditionnait l'agriculture égyptienne ?", ["Celle du Nil", "Celle du Tigre", "Celle de l'Euphrate", "Celle de l'Oronte"], 0,
     "Le limon déposé fertilisait les terres. Le barrage d'Assouan, achevé en 1970, y a mis fin.", 3],
  ]),

  notion("hm2-grece-classique", S, "La Grèce classique",
    "Cités rivales, guerres médiques, démocratie athénienne : un siècle qui a fondé beaucoup de nos références.",
    "La démocratie athénienne excluait femmes, métèques et esclaves, soit la grande majorité des habitants.",
    2, [
    ["Quelle bataille voit les Athéniens repousser les Perses en 490 avant notre ère ?", ["Marathon", "Salamine", "Platées", "Thermopyles"], 0,
     "La course du même nom commémore un messager dont l'existence est probablement légendaire."],
    ["Quelle bataille navale décide de la seconde guerre médique en 480 avant notre ère ?", ["Salamine", "Marathon", "Mycale", "Artémision"], 0,
     "Thémistocle attira la flotte perse dans un détroit où sa supériorité numérique devenait un handicap."],
    ["Quel roi spartiate meurt aux Thermopyles en 480 avant notre ère ?", ["Léonidas", "Cléomène", "Agésilas", "Pausanias"], 0,
     "Le sacrifice de son arrière-garde retarda l'armée perse et devint un symbole durable."],
    ["Quel homme d'État marque l'apogée d'Athènes au Ve siècle avant notre ère ?", ["Périclès", "Solon", "Clisthène", "Thémistocle"], 0,
     "Il fait reconstruire l'Acropole et rémunère les charges publiques, ce qui les ouvre aux citoyens pauvres."],
    ["Qu'est-ce que l'ostracisme à Athènes ?", ["Un bannissement de dix ans voté par l'assemblée", "Une exclusion de la citoyenneté", "Une peine d'amende", "Une privation du droit de vote"], 0,
     "Le nom vient de l'ostrakon, le tesson de poterie sur lequel les citoyens inscrivaient un nom."],
    ["Qui pouvait voter à l'assemblée athénienne ?", ["Les citoyens mâles adultes de naissance athénienne", "Tous les habitants libres", "Les propriétaires terriens", "Les hommes et les femmes citoyens"], 0,
     "Soit entre dix et vingt pour cent de la population, selon les estimations."],
    ["Quelle guerre oppose Athènes et Sparte de 431 à 404 avant notre ère ?", ["La guerre du Péloponnèse", "Les guerres médiques", "La guerre de Corinthe", "La guerre sacrée"], 0,
     "Thucydide en a écrit le récit, considéré comme un acte de naissance de l'histoire critique."],
    ["Quel philosophe athénien est condamné à boire la ciguë en 399 avant notre ère ?", ["Socrate", "Platon", "Aristote", "Anaxagore"], 0,
     "Accusé de corrompre la jeunesse et d'impiété. Il n'a laissé aucun écrit."],
    ["Quelle cité grecque était réputée pour son organisation militaire et son éducation collective ?", ["Sparte", "Corinthe", "Thèbes", "Argos"], 0,
     "L'agôgé retirait les garçons à leur famille dès sept ans. Les femmes y avaient plus de droits qu'ailleurs en Grèce."],
    ["Quelle bataille met fin à l'indépendance des cités grecques en 338 avant notre ère ?", ["Chéronée", "Leuctres", "Mantinée", "Coronée"], 0,
     "Philippe II de Macédoine y impose sa domination. Son fils Alexandre y commandait la cavalerie.", 3],
  ]),

  notion("hm2-alexandre-hellenistique", S, "Alexandre et le monde hellénistique",
    "Douze ans de conquêtes, trois siècles de royaumes grecs de l'Égypte à l'Inde.",
    "L'empire d'Alexandre se disloque à sa mort, mais la culture grecque reste dominante jusqu'à Rome.",
    2, [
    ["Qui fut le précepteur d'Alexandre le Grand ?", ["Aristote", "Platon", "Isocrate", "Diogène"], 0,
     "Philippe II l'avait fait venir en Macédoine pour former son fils entre treize et seize ans."],
    ["Quelle bataille de 331 avant notre ère ouvre la Perse à Alexandre ?", ["Gaugamèles", "Issos", "Le Granique", "l'Hydaspe"], 0,
     "Darius III y est mis en déroute malgré une nette supériorité numérique."],
    ["À quel âge Alexandre meurt-il ?", ["Trente-deux ans", "Quarante ans", "Vingt-cinq ans", "Quarante-cinq ans"], 0,
     "À Babylone, en 323 avant notre ère, d'une fièvre dont la cause reste discutée."],
    ["Quelle dynastie règne sur la Syrie et la Mésopotamie après Alexandre ?", ["Les Séleucides", "Les Lagides", "Les Antigonides", "Les Attalides"], 0,
     "Leur empire, le plus vaste des trois, s'effrite progressivement sous la pression parthe et romaine."],
    ["Qu'appelle-t-on la période hellénistique ?", ["Les trois siècles entre la mort d'Alexandre et la conquête romaine", "L'âge d'or d'Athènes", "L'époque des guerres médiques", "La période archaïque grecque"], 0,
     "Elle se caractérise par la diffusion du grec comme langue commune, la koinè, de l'Égypte à l'Asie centrale."],
    ["Quel savant d'Alexandrie mesure la circonférence de la Terre au IIIe siècle avant notre ère ?", ["Ératosthène", "Archimède", "Euclide", "Aristarque"], 0,
     "Par l'angle des ombres à Syène et Alexandrie. Son résultat est remarquablement proche de la valeur réelle."],
    ["Quel savant de Samos propose un modèle héliocentrique dans l'Antiquité ?", ["Aristarque", "Ptolémée", "Hipparque", "Eudoxe"], 0,
     "Son hypothèse fut écartée au profit du géocentrisme, qui dominera jusqu'à Copernic.", 3],
  ]),

  notion("hm2-rome-republique", S, "La République romaine",
    "Cinq siècles d'institutions, de conquêtes et de crises avant l'Empire.",
    "La République romaine n'était pas une démocratie : le vote y était pondéré par la fortune.",
    2, [
    ["En quelle année la tradition situe-t-elle la fondation de Rome ?", ["753 avant notre ère", "509 avant notre ère", "1000 avant notre ère", "600 avant notre ère"], 0,
     "Date calculée par les érudits romains eux-mêmes. L'archéologie atteste une occupation antérieure."],
    ["Quel événement marque le début de la République romaine ?", ["L'expulsion du dernier roi en 509 avant notre ère", "La fondation de la ville", "La conquête de l'Italie", "La victoire sur Carthage"], 0,
     "Tarquin le Superbe est chassé ; le pouvoir passe à deux consuls élus pour un an."],
    ["Combien de consuls dirigeaient la République romaine ?", ["Deux", "Un", "Trois", "Cinq"], 0,
     "Élus pour un an et disposant chacun d'un droit de veto sur l'autre, pour éviter tout pouvoir personnel."],
    ["Qu'est-ce qu'un tribun de la plèbe ?", ["Un magistrat chargé de défendre les plébéiens, doté d'un droit de veto", "Un chef militaire", "Un juge populaire", "Un percepteur d'impôts"], 0,
     "Sa personne était sacro-sainte : le frapper était un sacrilège puni de mort."],
    ["Quelles guerres opposent Rome à Carthage ?", ["Les guerres puniques", "Les guerres samnites", "Les guerres macédoniennes", "Les guerres serviles"], 0,
     "Trois guerres entre 264 et 146 avant notre ère, achevées par la destruction complète de Carthage."],
    ["Quel général carthaginois franchit les Alpes avec des éléphants ?", ["Hannibal", "Hasdrubal", "Hamilcar", "Magon"], 0,
     "En 218 avant notre ère. Il écrasera les Romains à Cannes deux ans plus tard sans pouvoir prendre Rome."],
    ["Quel général romain met fin à la deuxième guerre punique à Zama ?", ["Scipion l'Africain", "Caton l'Ancien", "Fabius Maximus", "Marcellus"], 0,
     "En 202 avant notre ère, en portant la guerre en Afrique pour forcer Hannibal à rentrer."],
    ["Quel esclave dirige une grande révolte contre Rome en 73 avant notre ère ?", ["Spartacus", "Eunous", "Salvius", "Athénion"], 0,
     "Gladiateur d'origine thrace, il tint tête aux légions deux ans avant d'être écrasé par Crassus."],
    ["Qu'est-ce que le premier triumvirat, conclu en 60 avant notre ère ?", ["Un accord privé entre César, Pompée et Crassus", "Une magistrature à trois", "Un conseil du Sénat", "Une alliance militaire officielle"], 0,
     "Sans existence légale, il permit aux trois hommes de se partager le contrôle de la République."],
    ["Quelle rivière César franchit-il en 49 avant notre ère en déclenchant la guerre civile ?", ["Le Rubicon", "Le Tibre", "Le Pô", "L'Arno"], 0,
     "Le franchir en armes équivalait à déclarer la guerre à la République. La formule « le sort en est jeté » lui est attribuée.", 3],
  ]),

  notion("hm2-empire-romain", S, "L'Empire romain",
    "D'Auguste à la chute de Rome : cinq siècles de domination sur la Méditerranée.",
    "L'Empire ne tombe pas en 476 : sa moitié orientale survit encore mille ans.",
    2, [
    ["Qui devient le premier empereur romain en 27 avant notre ère ?", ["Auguste", "Jules César", "Tibère", "Marc Antoine"], 0,
     "Il conserve les apparences républicaines tout en concentrant les pouvoirs. Le mot empereur vient d'imperator."],
    ["Qu'appelle-t-on la Pax Romana ?", ["Deux siècles de stabilité relative de l'Empire", "Un traité avec les Parthes", "La paix intérieure après les guerres civiles de César", "L'accord entre Rome et Carthage"], 0,
     "Du règne d'Auguste à celui de Marc Aurèle, avec un commerce et une circulation sans équivalent avant l'époque moderne."],
    ["Sous quel empereur l'Empire romain atteint-il son extension maximale ?", ["Trajan", "Auguste", "Hadrien", "Marc Aurèle"], 0,
     "Vers 117, jusqu'à la Mésopotamie. Hadrien abandonnera ensuite les conquêtes les plus difficiles à tenir."],
    ["Quel mur Hadrien fait-il construire au nord de la Bretagne romaine ?", ["Le mur d'Hadrien", "Le mur d'Antonin seul", "Le limes germanique", "La muraille de Sévère"], 0,
     "Cent dix-sept kilomètres, moins pour arrêter une invasion que pour contrôler les circulations."],
    ["Quel empereur divise l'Empire en quatre gouvernements en 293 ?", ["Dioclétien", "Constantin", "Théodose", "Valentinien"], 0,
     "La tétrarchie visait à répondre à la crise du IIIe siècle. Elle ne survécut pas à son fondateur."],
    ["Quelle ville Constantin fait-il devenir capitale en 330 ?", ["Constantinople", "Ravenne", "Milan", "Nicomédie"], 0,
     "Bâtie sur le site de Byzance, elle restera capitale de l'Empire d'Orient pendant plus de mille ans."],
    ["Quel empereur fait du christianisme la religion officielle en 380 ?", ["Théodose", "Constantin", "Julien", "Valens"], 0,
     "L'édit de Thessalonique va au-delà de la tolérance accordée par Constantin en 313."],
    ["Que se passe-t-il en 476 dans l'Empire romain d'Occident ?", ["Le dernier empereur est déposé par un chef germanique", "Rome est incendiée", "L'Empire est divisé", "Les Vandales prennent Carthage"], 0,
     "Odoacre dépose Romulus Augustule. La date est une commodité d'historien plus qu'une rupture ressentie sur le moment."],
    ["Quelles causes les historiens retiennent-ils pour la chute de l'Empire d'Occident ?", ["Un faisceau de causes économiques, militaires et politiques", "Les seules invasions barbares", "La conversion au christianisme", "L'épuisement des mines d'argent uniquement"], 0,
     "Plus de deux cents explications ont été proposées depuis Gibbon ; aucune ne suffit isolément.", 3],
  ]),

  notion("hm2-chine-imperiale", S, "La Chine impériale",
    "Deux mille ans de dynasties, du premier empereur à la dernière impératrice.",
    "La Chine impériale a inventé le concours administratif bien avant l'Europe.",
    2, [
    ["Quel souverain unifie la Chine en 221 avant notre ère ?", ["Qin Shi Huang", "Wudi", "Taizong", "Kubilai Khan"], 0,
     "Il unifie aussi l'écriture, les poids et les mesures, et fait relier des murailles existantes."],
    ["Quelle découverte archéologique de 1974 est liée au premier empereur ?", ["L'armée de terre cuite", "Les manuscrits de Dunhuang", "Le tombeau de Mawangdui", "Les bronzes de Sanxingdui"], 0,
     "Plus de huit mille statues, chacune au visage différent, gardant l'entrée de son mausolée."],
    ["Quelle dynastie succède aux Qin et donne son nom à l'ethnie majoritaire chinoise ?", ["Les Han", "Les Tang", "Les Song", "Les Ming"], 0,
     "Plus de quatre siècles de règne. Les Chinois se désignent encore aujourd'hui comme Han."],
    ["Quelle route commerciale relie la Chine à la Méditerranée dès l'Antiquité ?", ["La route de la soie", "La route des épices", "La route de l'ambre", "La route du thé"], 0,
     "L'expression date du XIXe siècle. Il s'agissait en fait d'un réseau de relais, non d'une route unique."],
    ["Quelle dynastie marque un âge d'or culturel entre le VIIe et le Xe siècle ?", ["Les Tang", "Les Han", "Les Yuan", "Les Qing"], 0,
     "Chang'an, leur capitale, était alors la plus grande ville du monde, ouverte aux marchands et aux religions étrangères."],
    ["Quel système de recrutement des fonctionnaires la Chine impériale développe-t-elle ?", ["Les concours impériaux fondés sur les classiques confucéens", "L'hérédité des charges", "La vente des offices", "La désignation par les gouverneurs"], 0,
     "Ouverts en théorie à tous, ils exigeaient des années d'étude que seules certaines familles pouvaient financer."],
    ["Quelle dynastie mongole règne sur la Chine au XIIIe siècle ?", ["Les Yuan", "Les Ming", "Les Song", "Les Jin"], 0,
     "Fondée par Kubilai Khan, petit-fils de Gengis Khan. Marco Polo situe son voyage sous ce règne."],
    ["Quel amiral chinois mène sept grandes expéditions maritimes au XVe siècle ?", ["Zheng He", "Li Zicheng", "Yongle", "Zhu Yuanzhang"], 0,
     "Ses flottes atteignirent l'Afrique de l'Est. Les expéditions furent interrompues par décision impériale."],
    ["Quelle dynastie règne sur la Chine de 1644 à 1912 ?", ["Les Qing", "Les Ming", "Les Yuan", "Les Han"], 0,
     "D'origine mandchoue, elle impose la natte aux hommes chinois comme signe de soumission."],
    ["Quel événement met fin à l'Empire chinois en 1912 ?", ["La révolution républicaine et l'abdication de Puyi", "L'invasion japonaise", "La révolte des Taiping", "La guerre de l'opium"], 0,
     "L'empereur avait six ans. Il régnera brièvement sur un État fantoche japonais dans les années 1930.", 3],
  ]),

  notion("hm2-inde-histoire", S, "L'histoire de l'Inde",
    "De la civilisation de l'Indus à l'indépendance : quelques jalons d'un sous-continent.",
    "L'Inde britannique comprenait aussi les actuels Pakistan, Bangladesh et Birmanie.",
    2, [
    ["Quelle civilisation urbaine se développe dans la vallée de l'Indus vers 2600 avant notre ère ?", ["La civilisation harappéenne", "La civilisation védique", "La civilisation maurya", "La civilisation dravidienne du Deccan"], 0,
     "Mohenjo-daro et Harappa disposaient d'un urbanisme planifié et de systèmes d'évacuation des eaux."],
    ["Quel empereur maurya se convertit au bouddhisme après une guerre meurtrière ?", ["Ashoka", "Chandragupta", "Bindusara", "Kanishka"], 0,
     "La guerre du Kalinga, vers 261 avant notre ère. Il fit graver des édits de non-violence sur des piliers de pierre."],
    ["Quelle dynastie marque un âge d'or classique indien du IVe au VIe siècle ?", ["Les Gupta", "Les Maurya", "Les Chola", "Les Moghols"], 0,
     "Mathématiques, astronomie et littérature sanskrite y connaissent un essor durable."],
    ["Quel mathématicien indien du Ve siècle calcule une valeur précise de pi ?", ["Aryabhata", "Brahmagupta", "Bhaskara", "Madhava"], 0,
     "Brahmagupta, au VIIe siècle, sera le premier à traiter le zéro comme un nombre à part entière."],
    ["Quel empire musulman domine l'Inde du XVIe au XVIIIe siècle ?", ["L'Empire moghol", "Le sultanat de Delhi", "L'Empire marathe", "Le sultanat du Bengale"], 0,
     "Fondé par Babur en 1526, il atteint son apogée sous Akbar puis Shah Jahan."],
    ["Quel empereur moghol fait construire le Taj Mahal ?", ["Shah Jahan", "Akbar", "Aurangzeb", "Babur"], 0,
     "Mausolée élevé pour son épouse Mumtaz Mahal, achevé vers 1653 à Agra."],
    ["Quelle compagnie commerciale prend le contrôle de larges parties de l'Inde au XVIIIe siècle ?", ["La Compagnie anglaise des Indes orientales", "La Compagnie française des Indes", "La Compagnie néerlandaise", "La Compagnie portugaise"], 0,
     "Une entreprise privée dotée d'une armée. La Couronne britannique reprend le contrôle direct en 1858."],
    ["Quelle révolte de 1857 conduit à la dissolution de la Compagnie des Indes ?", ["La révolte des cipayes", "La révolte du Bengale", "La rébellion marathe", "La révolte du sel"], 0,
     "Partie de soldats indiens de l'armée coloniale, elle fut réprimée avec une extrême violence."],
    ["Quelle méthode Gandhi promeut-il dans la lutte pour l'indépendance ?", ["La non-violence et la désobéissance civile", "La grève générale armée", "La négociation parlementaire seule", "Le boycott électoral"], 0,
     "La marche du sel de 1930 en est l'exemple le plus célèbre."],
    ["Que se passe-t-il en Inde en août 1947 ?", ["L'indépendance et la partition entre Inde et Pakistan", "La fin de la Compagnie des Indes", "La proclamation de la République", "L'entrée dans le Commonwealth"], 0,
     "La partition provoqua le déplacement de plus de dix millions de personnes et des violences massives.", 3],
  ]),

  notion("hm2-islam-conquetes", S, "L'expansion de l'islam",
    "En un siècle, un empire de l'Atlantique à l'Indus, puis sa fragmentation.",
    "L'expansion arabe du VIIe siècle est l'une des plus rapides de l'histoire militaire.",
    2, [
    ["Quelle bataille de 636 ouvre la Syrie aux armées arabes ?", ["Le Yarmouk", "Qadisiyya", "Nahavend", "Poitiers"], 0,
     "L'Empire byzantin y perd définitivement ses provinces orientales."],
    ["Quelle bataille de 636 marque l'effondrement de l'Empire perse sassanide ?", ["Qadisiyya", "Le Yarmouk", "Talas", "Siffin"], 0,
     "L'Empire perse, épuisé par des décennies de guerre contre Byzance, disparaît en quelques années."],
    ["Quelle dynastie établit sa capitale à Damas au VIIe siècle ?", ["Les Omeyyades", "Les Abbassides", "Les Fatimides", "Les Ayyoubides"], 0,
     "Renversés en 750, un rescapé fonde un émirat indépendant en Espagne."],
    ["En quelle année les armées musulmanes franchissent-elles le détroit de Gibraltar ?", ["711", "622", "800", "756"], 0,
     "Le royaume wisigoth d'Espagne s'effondre en quelques années."],
    ["Quelle bataille de 732 arrête une incursion arabe en Gaule ?", ["Poitiers", "Tours seule", "Narbonne", "Toulouse"], 0,
     "Charles Martel y commande les Francs. La portée de la bataille a été fortement amplifiée par l'historiographie ultérieure."],
    ["Quelle bataille de 751 fixe la frontière entre mondes chinois et musulman en Asie centrale ?", ["Talas", "Qadisiyya", "Manzikert", "Ankara"], 0,
     "Selon la tradition, des prisonniers chinois y auraient transmis le secret du papier au monde musulman."],
    ["Quel califat s'établit à Cordoue en Espagne au Xe siècle ?", ["Le califat omeyyade de Cordoue", "Le califat fatimide", "Le califat abbasside d'Occident", "Le califat almohade"], 0,
     "Cordoue fut alors l'une des plus grandes villes d'Europe, avec une vie intellectuelle intense."],
    ["Quel savant andalou du XIIe siècle commente Aristote et influence l'Occident latin ?", ["Averroès", "Avicenne", "Al-Ghazali", "Al-Fârâbî"], 0,
     "Ses commentaires, traduits en latin, nourrissent la scolastique européenne au XIIIe siècle."],
    ["Quel médecin persan écrit un canon de la médecine utilisé en Europe jusqu'au XVIIe siècle ?", ["Avicenne", "Averroès", "Rhazès", "Al-Zahrawi"], 0,
     "Son Canon fut enseigné dans les facultés européennes pendant plus de cinq siècles."],
    ["Quel événement met fin au califat abbasside de Bagdad en 1258 ?", ["La prise de la ville par les Mongols", "La conquête ottomane", "La révolte des Seldjoukides", "La croisade de Saint Louis"], 0,
     "Le sac de Bagdad détruisit bibliothèques et systèmes d'irrigation, avec des effets durables sur la région.", 3],
  ]),

  notion("hm2-byzance", S, "L'Empire byzantin",
    "Mille ans d'Empire romain d'Orient, de Constantin à la chute de Constantinople.",
    "Les Byzantins ne se disaient pas byzantins mais romains : le mot est une invention d'érudits modernes.",
    2, [
    ["Comment les habitants de l'Empire byzantin se désignaient-ils ?", ["Comme des Romains", "Comme des Byzantins", "Comme des Grecs", "Comme des Hellènes"], 0,
     "Le terme byzantin apparaît chez des érudits allemands du XVIe siècle."],
    ["Quel empereur du VIe siècle reconquiert une partie de l'Occident ?", ["Justinien", "Héraclius", "Basile II", "Constantin V"], 0,
     "Italie, Afrique du Nord et sud de l'Espagne. Les conquêtes ne survivront pas longtemps à son règne."],
    ["Quel recueil juridique Justinien fait-il compiler ?", ["Le Corpus juris civilis", "Le Code théodosien", "Les Basiliques", "Le Digeste seul"], 0,
     "Redécouvert en Occident au XIe siècle, il fonde la tradition du droit civil européen."],
    ["Quelle église Justinien fait-il construire à Constantinople ?", ["Sainte-Sophie", "Saint-Sauveur-in-Chora", "Les Saints-Apôtres seule", "Sainte-Irène"], 0,
     "Sa coupole de trente et un mètres resta longtemps un record technique."],
    ["Qu'est-ce que le feu grégeois ?", ["Une arme incendiaire byzantine dont la composition reste inconnue", "Un signal de guerre par tours", "Un explosif à base de soufre", "Une flèche enflammée"], 0,
     "Il brûlait sur l'eau et fut décisif dans plusieurs sièges navals de Constantinople."],
    ["Qu'est-ce que la querelle iconoclaste des VIIIe et IXe siècles ?", ["Un conflit sur la légitimité du culte des images", "Une dispute sur la nature du Christ", "Un schisme avec Rome", "Une révolte fiscale"], 0,
     "Elle se solde par le rétablissement des images, célébré comme le triomphe de l'orthodoxie."],
    ["Quelle bataille de 1071 ouvre l'Anatolie aux Turcs seldjoukides ?", ["Manzikert", "Myriokephalon", "Andrinople", "Dorylée"], 0,
     "La défaite conduit l'empereur à demander une aide occidentale, à l'origine indirecte des croisades."],
    ["Que se passe-t-il à Constantinople en 1204 ?", ["Les croisés prennent et pillent la ville", "Les Turcs s'en emparent", "Un tremblement de terre la détruit", "Elle est reprise aux Bulgares"], 0,
     "La quatrième croisade, détournée de son but, installe un empire latin qui durera cinquante-sept ans."],
    ["Quelle innovation permet à Mehmed II de forcer les murailles de Constantinople en 1453 ?", ["Des canons d'un calibre inédit", "Des tours de siège mobiles", "Un tunnel sous les remparts", "Une flotte de galères lourdes"], 0,
     "Les murailles théodosiennes avaient résisté à une vingtaine de sièges pendant mille ans."],
    ["Quelle conséquence culturelle la chute de Constantinople a-t-elle en Occident ?", ["L'arrivée de savants grecs et de manuscrits en Italie", "La fermeture des routes commerciales seule", "L'interdiction du grec en Europe", "La perte de tous les textes antiques"], 0,
     "Le mouvement avait commencé avant 1453, mais s'accélère alors et nourrit l'humanisme de la Renaissance.", 3],
  ]),

  notion("hm2-croisades", S, "Les croisades",
    "Deux siècles d'expéditions vers l'Orient, leurs motifs et leurs conséquences.",
    "Les croisades ne visaient pas seulement l'Orient : la notion s'est étendue à l'Espagne et au nord de l'Europe.",
    2, [
    ["Qui appelle à la première croisade en 1095 ?", ["Le pape Urbain II", "Le pape Grégoire VII", "L'empereur Alexis Comnène", "Saint Bernard"], 0,
     "Au concile de Clermont. La formule Dieu le veut aurait été reprise par la foule."],
    ["Combien de temps dure la première croisade, du départ à la prise de Jérusalem ?", ["Environ trois ans", "Six mois", "Dix ans", "Un an"], 0,
     "Partie en 1096, elle atteint son but en juillet 1099 après les sièges d'Antioche et de Maarat."],
    ["Quels États latins sont fondés en Orient après la première croisade ?", ["Quatre, dont le royaume de Jérusalem", "Un seul", "Deux", "Six"], 0,
     "Royaume de Jérusalem, principauté d'Antioche, comtés d'Édesse et de Tripoli."],
    ["Quel sultan reprend Jérusalem aux croisés en 1187 ?", ["Saladin", "Baybars", "Nur ad-Din", "Al-Kamil"], 0,
     "Après la bataille de Hattin. Sa clémence lors de la reddition a nourri sa réputation en Occident même."],
    ["Quels ordres militaires naissent des croisades ?", ["Les Templiers, les Hospitaliers et les Teutoniques", "Les Bénédictins et les Cisterciens", "Les Franciscains et les Dominicains", "Les Chartreux"], 0,
     "Moines et soldats à la fois, ils développent aussi des réseaux financiers considérables."],
    ["Quel roi de France meurt lors de la huitième croisade en 1270 ?", ["Louis IX", "Philippe Auguste", "Philippe le Bel", "Louis VII"], 0,
     "Devant Tunis, probablement de dysenterie. Il avait déjà été fait prisonnier en Égypte en 1250."],
    ["Quelle ville marque en 1291 la fin des États latins d'Orient ?", ["Saint-Jean-d'Acre", "Jérusalem", "Antioche", "Tripoli"], 0,
     "Sa chute face aux Mamelouks met un terme à deux siècles de présence latine."],
    ["Qu'est-ce que la Reconquista ?", ["La reconquête chrétienne progressive de la péninsule Ibérique", "La reprise de Constantinople", "La croisade contre les Albigeois", "La conquête de la Sicile"], 0,
     "Elle s'achève en 1492 avec la prise de Grenade, près de huit siècles après 711."],
    ["Contre quels peuples les croisades baltes sont-elles menées aux XIIe et XIIIe siècles ?", ["Les peuples païens de la Baltique", "Les orthodoxes russes seuls", "Les musulmans de Crimée", "Les Mongols"], 0,
     "L'ordre Teutonique y taille un État qui subsistera jusqu'au XVIe siècle."],
    ["Quelle conséquence économique durable les croisades ont-elles en Europe ?", ["L'essor du commerce méditerranéen des cités italiennes", "La ruine des ports européens", "L'abandon des routes terrestres", "La fin des foires de Champagne"], 0,
     "Venise et Gênes en tirent un profit considérable, notamment par le transport et le crédit.", 3],
  ]),

  notion("hm2-mongols", S, "Les conquêtes mongoles",
    "Le plus vaste empire terrestre continu de l'histoire, constitué en moins d'un siècle.",
    "L'Empire mongol a rendu possible une circulation continentale sans précédent avant sa fragmentation.",
    2, [
    ["Qui unifie les tribus mongoles en 1206 ?", ["Gengis Khan", "Kubilai Khan", "Tamerlan", "Batu"], 0,
     "Le titre signifie souverain universel. Son nom personnel était Temüjin."],
    ["Quelle innovation militaire fait la force des armées mongoles ?", ["La cavalerie d'archers très mobile", "L'infanterie lourde", "Les machines de siège seules", "Les chars de guerre"], 0,
     "Chaque cavalier disposait de plusieurs montures, ce qui permettait des déplacements très rapides."],
    ["Quel petit-fils de Gengis Khan fonde la dynastie Yuan en Chine ?", ["Kubilai Khan", "Batu", "Hulagu", "Möngke"], 0,
     "Il achève la conquête des Song du Sud en 1279."],
    ["Quel khanat mongol domine la Russie pendant plus de deux siècles ?", ["La Horde d'Or", "L'Ilkhanat", "Le khanat de Djaghataï", "L'Empire des steppes occidentales"], 0,
     "Les principautés russes payaient tribut. Moscou s'est renforcée en servant d'intermédiaire fiscal."],
    ["Que désigne la Pax Mongolica ?", ["Une période de sécurité des routes commerciales sous domination mongole", "Un traité entre khanats", "La paix conclue avec la Chine", "L'accord entre Mongols et papauté"], 0,
     "Marco Polo voyagea dans ce contexte. La peste noire emprunta probablement les mêmes routes."],
    ["Quelle bataille de 1260 arrête l'expansion mongole vers l'Égypte ?", ["Aïn Djalout", "Manzikert", "Kosovo", "Ankara"], 0,
     "Les Mamelouks y remportent l'une des premières défaites infligées aux Mongols."],
    ["Pourquoi les Mongols renoncent-ils à envahir l'Europe centrale en 1242 ?", ["La mort du grand khan impose le retour des chefs pour l'élection", "Une défaite militaire", "Un hiver trop rude", "Un traité de paix"], 0,
     "Les armées mongoles avaient écrasé les forces hongroises et polonaises quelques mois plus tôt."],
    ["Quel conquérant turco-mongol ravage l'Asie centrale à la fin du XIVe siècle ?", ["Tamerlan", "Babur", "Ouzbek Khan", "Toqtamich"], 0,
     "Il se réclamait de l'héritage de Gengis Khan sans en descendre directement."],
    ["Quelle innovation administrative les Mongols généralisent-ils sur leurs routes ?", ["Un réseau de relais de poste", "Un cadastre impérial", "Une monnaie unique", "Un impôt foncier uniforme"], 0,
     "Le yam permettait de transmettre un message sur des milliers de kilomètres en quelques jours."],
    ["Quelle religion l'Empire mongol imposait-il aux peuples conquis ?", ["Aucune : la tolérance religieuse était la règle", "Le bouddhisme tibétain", "L'islam", "Le christianisme nestorien"], 0,
     "Les différents khanats adoptèrent ensuite des religions différentes selon leurs zones d'influence.", 3],
  ]),

  notion("hm2-decouvertes", S, "Les grandes découvertes",
    "Un siècle de navigation qui met en contact des mondes jusque-là séparés.",
    "Les Européens ne découvrent pas des terres vides : ils entrent en contact avec des sociétés existantes.",
    2, [
    ["Quel prince portugais organise l'exploration de la côte africaine au XVe siècle ?", ["Henri le Navigateur", "Jean II", "Manuel Ier", "Alphonse V"], 0,
     "Il ne navigua lui-même presque jamais, mais finança et coordonna les expéditions."],
    ["Que bouleverse l'ouverture de la route maritime vers l'Inde en 1498 ?", ["Le commerce des épices, jusque-là aux mains d'intermédiaires", "Le commerce de l'or africain", "Le trafic de la soie chinoise", "Le commerce du sel saharien"], 0,
     "Venise et les marchands du Levant perdent leur position dominante en quelques décennies."],
    ["Quelle expédition réalise le premier tour du monde entre 1519 et 1522 ?", ["Celle de Magellan, achevée par Elcano", "Celle de Colomb", "Celle de Drake", "Celle de Cabral"], 0,
     "Magellan fut tué aux Philippines ; dix-huit hommes sur environ deux cent cinquante rentrèrent."],
    ["Qui donne son nom au continent américain ?", ["Amerigo Vespucci", "Christophe Colomb", "Juan de la Cosa", "Martin Waldseemüller"], 0,
     "Le cartographe Waldseemüller le baptisa ainsi en 1507, Vespucci ayant compris qu'il s'agissait d'un continent nouveau."],
    ["Qu'appelle-t-on l'échange colombien ?", ["Le transfert de plantes, animaux et maladies entre l'Ancien et le Nouveau Monde", "Le commerce de l'argent américain", "Le troc avec les peuples amérindiens", "Le partage des colonies entre puissances"], 0,
     "Maïs, pomme de terre et tomate vers l'Europe ; blé, chevaux et surtout maladies vers l'Amérique."],
    ["Quelle fut la principale cause de l'effondrement démographique amérindien ?", ["Les maladies importées, contre lesquelles les populations n'étaient pas immunisées", "Les guerres de conquête", "Le travail forcé", "Les famines"], 0,
     "Variole, rougeole et typhus ont tué une majorité de la population en quelques décennies."],
    ["Quel conquistador détruit l'Empire inca à partir de 1532 ?", ["Francisco Pizarro", "Hernán Cortés", "Vasco Núñez de Balboa", "Gonzalo Jiménez de Quesada"], 0,
     "Il profita d'une guerre civile qui venait de déchirer l'empire entre deux prétendants.", 3],
  ]),

  notion("hm2-reforme-guerres-religion", S, "La Réforme et les guerres de religion",
    "Un siècle et demi de rupture religieuse et de conflits en Europe.",
    "La paix d'Augsbourg règle le conflit par un principe simple et brutal, qui ne laisse aucun choix aux sujets.",
    2, [
    ["Quel principe la paix d'Augsbourg établit-elle en 1555 ?", ["La religion du prince détermine celle de ses sujets", "La liberté de conscience individuelle", "L'égalité des cultes", "La séparation des Églises et de l'État"], 0,
     "Formulé plus tard sous l'expression cujus regio, ejus religio. Le calvinisme n'y était pas inclus."],
    ["Quel invention favorise la diffusion rapide des idées de la Réforme ?", ["L'imprimerie", "Le papier", "Le courrier régulier", "La gravure sur bois seule"], 0,
     "Les écrits de Luther se diffusèrent à des centaines de milliers d'exemplaires en quelques années."],
    ["Quel roi d'Angleterre rompt avec Rome en 1534 ?", ["Henri VIII", "Édouard VI", "Jacques Ier", "Richard III"], 0,
     "Le refus d'annuler son mariage déclenche la rupture ; l'Acte de Suprématie le fait chef de l'Église d'Angleterre."],
    ["Quelle nuit de 1572 marque le massacre de protestants en France ?", ["La Saint-Barthélemy", "La nuit de Nantes", "La Saint-Michel", "La nuit de Vassy"], 0,
     "Commencée à Paris le 24 août, elle s'étend à plusieurs villes de province dans les semaines suivantes."],
    ["Quel édit de 1598 accorde des droits aux protestants français ?", ["L'édit de Nantes", "L'édit de Saint-Germain", "L'édit d'Amboise", "L'édit de Fontainebleau"], 0,
     "Signé par Henri IV, ancien protestant converti au catholicisme pour accéder au trône."],
    ["Quel roi révoque l'édit de Nantes en 1685 ?", ["Louis XIV", "Louis XIII", "Louis XV", "Henri IV"], 0,
     "Des centaines de milliers de protestants quittent la France, au bénéfice économique de leurs pays d'accueil."],
    ["Quelle guerre européenne se déroule de 1618 à 1648 ?", ["La guerre de Trente Ans", "La guerre de Quatre-Vingts Ans", "La guerre de Succession d'Espagne", "La guerre de Sept Ans"], 0,
     "Née d'un conflit religieux en Bohême, elle devient un affrontement politique européen."],
    ["Quel ordre religieux est fondé en 1540 pour porter la Contre-Réforme ?", ["La Compagnie de Jésus", "L'ordre des Capucins", "L'Oratoire", "Les Théatins"], 0,
     "Fondée par Ignace de Loyola, elle joue un rôle majeur dans l'enseignement et les missions."],
    ["Quelle proportion de la population du Saint-Empire la guerre de Trente Ans aurait-elle emportée ?", ["Entre un cinquième et un tiers selon les régions", "Environ cinq pour cent", "Environ la moitié partout", "Moins d'un dixième"], 0,
     "Les famines et les épidémies liées aux passages de troupes firent bien plus de morts que les combats.", 3],
  ]),

  notion("hm2-revolution-industrielle", S, "La révolution industrielle",
    "Charbon, machines et usines : la transformation la plus rapide des conditions de vie humaines.",
    "La révolution industrielle commence en Angleterre au XVIIIe siècle, pas partout en même temps.",
    2, [
    ["Dans quel pays la révolution industrielle commence-t-elle ?", ["En Angleterre", "En France", "En Allemagne", "Aux Pays-Bas"], 0,
     "Charbon abondant, capitaux disponibles, main-d'œuvre libérée des campagnes et marchés coloniaux s'y combinent."],
    ["Quelle source d'énergie domine la première révolution industrielle ?", ["Le charbon", "Le pétrole", "L'électricité", "La force hydraulique seule"], 0,
     "Le pétrole et l'électricité caractérisent la seconde révolution industrielle, à partir des années 1870."],
    ["Quelle industrie est la première mécanisée en Angleterre ?", ["Le textile", "La sidérurgie", "La chimie", "La construction navale"], 0,
     "Filature puis tissage : la navette volante et la mule-jenny multiplient la productivité."],
    ["Qui met au point la locomotive à vapeur exploitée commercialement ?", ["George Stephenson", "James Watt", "Richard Trevithick", "Isambard Brunel"], 0,
     "Trevithick avait construit la première locomotive à vapeur ; Stephenson en fit un système de transport viable."],
    ["Qu'est-ce que le mouvement luddite ?", ["Une révolte d'ouvriers détruisant des machines au début du XIXe siècle", "Un syndicat de mineurs", "Un mouvement d'inventeurs", "Une coopérative ouvrière"], 0,
     "Ils ne s'opposaient pas aux machines en soi mais à leur usage pour déqualifier et sous-payer le travail."],
    ["Quelle loi anglaise de 1833 limite le travail des enfants en usine ?", ["Le Factory Act", "Le Poor Law Act", "Le Reform Act", "Le Combination Act"], 0,
     "Il interdit l'emploi des moins de neuf ans dans le textile et instaure des inspecteurs."],
    ["Quelle invention de 1856 permet la production massive d'acier ?", ["Le convertisseur Bessemer", "Le haut-fourneau à coke", "Le four Martin seul", "L'électrolyse"], 0,
     "Le prix de l'acier s'effondre, rendant possibles rails, ponts et gratte-ciel."],
    ["Quel phénomène démographique accompagne l'industrialisation ?", ["Un exode rural massif vers les villes", "Une baisse de la population totale", "Un retour aux campagnes", "Une stagnation urbaine"], 0,
     "Manchester passe de vingt-cinq mille à plus de trois cent mille habitants en un siècle."],
    ["Quelle organisation ouvrière se développe en réaction aux conditions de travail ?", ["Le syndicalisme", "Le mutualisme agricole", "Les corporations de métiers", "Les guildes marchandes"], 0,
     "Longtemps interdits, les syndicats sont légalisés en Grande-Bretagne en 1824 et en France en 1884."],
    ["Quelle conséquence environnementale de long terme la révolution industrielle amorce-t-elle ?", ["La hausse des émissions de gaz à effet de serre", "La déforestation tropicale", "L'acidification des sols", "La désertification"], 0,
     "Les carottes glaciaires montrent une inflexion de la concentration de CO2 à partir de cette période.", 3],
  ]),

  notion("hm2-colonisation", S, "Colonisation et décolonisation",
    "Le partage du monde par quelques puissances européennes, et son démantèlement en trente ans.",
    "L'essentiel des empires coloniaux européens s'est constitué et dissous en moins d'un siècle.",
    2, [
    ["Quelle conférence de 1884-1885 organise le partage de l'Afrique ?", ["La conférence de Berlin", "Le congrès de Vienne", "La conférence d'Algésiras", "Le congrès de Berlin de 1878"], 0,
     "Aucun Africain n'y était représenté. Elle fixe la règle de l'occupation effective."],
    ["Quel pays africain reste indépendant lors du partage colonial ?", ["l'Éthiopie", "Le Maroc", "Le Liberia seul", "Le Soudan"], 0,
     "Elle repousse l'invasion italienne à Adoua en 1896. Le Liberia conserve aussi une indépendance formelle."],
    ["Quelle bataille de 1896 voit une armée africaine battre une puissance européenne ?", ["Adoua", "Isandhlwana", "Omdurman", "Rorke's Drift"], 0,
     "L'Éthiopie de Ménélik II y écrase l'armée italienne, ce qui eut un retentissement mondial."],
    ["Quel incident de 1898 oppose la France et le Royaume-Uni au Soudan ?", ["Fachoda", "Agadir", "Tanger", "Ouadi Halfa"], 0,
     "La France recule. L'épisode marque un tournant vers le rapprochement franco-britannique."],
    ["Quel pays devient la propriété personnelle d'un roi européen en 1885 ?", ["l'État indépendant du Congo, propriété de Léopold II", "Le Kenya", "l'Angola", "Le Mozambique"], 0,
     "L'exploitation du caoutchouc y provoqua des atrocités massives, dénoncées internationalement dès 1900."],
    ["Quelle conférence de 1955 réunit des pays d'Asie et d'Afrique nouvellement indépendants ?", ["La conférence de Bandung", "La conférence de Belgrade", "La conférence du Caire", "La conférence de Colombo"], 0,
     "Elle affirme le refus de l'alignement sur les deux blocs et le soutien aux luttes anticoloniales."],
    ["Quelle année est appelée l'année de l'Afrique ?", ["1960", "1957", "1962", "1975"], 0,
     "Dix-sept pays africains accèdent à l'indépendance cette année-là."],
    ["Quel pays d'Afrique subsaharienne accède le premier à l'indépendance en 1957 ?", ["Le Ghana", "Le Sénégal", "La Guinée", "Le Nigeria"], 0,
     "Sous la conduite de Kwame Nkrumah, promoteur du panafricanisme."],
    ["Quelle guerre d'indépendance se déroule en Algérie de 1954 à 1962 ?", ["La guerre d'Algérie", "La guerre du Rif", "La guerre de Kabylie", "La révolution du Constantinois"], 0,
     "Elle s'achève par les accords d'Évian. La France ne la reconnaît officiellement comme guerre qu'en 1999."],
    ["Qu'appelle-t-on la théorie de la dépendance ?", ["L'idée que le sous-développement résulte de la place occupée dans l'économie mondiale", "La dépendance politique aux anciennes métropoles", "Le poids de la dette extérieure", "La dépendance alimentaire des pays du Sud"], 0,
     "Développée en Amérique latine dans les années 1960, elle conteste l'idée d'un simple retard à rattraper.", 3],
  ]),

  notion("hm2-guerre-froide", S, "La guerre froide",
    "Quarante-cinq ans d'affrontement indirect entre deux blocs armés de l'arme nucléaire.",
    "La guerre froide n'a jamais opposé directement les deux superpuissances : elle s'est jouée par procuration.",
    2, [
    ["Quel discours de 1946 popularise l'expression rideau de fer ?", ["Celui de Churchill à Fulton", "Celui de Truman au Congrès", "Celui de Staline à Moscou", "Celui de Marshall à Harvard"], 0,
     "Il décrit la coupure de l'Europe alors que l'alliance de guerre vient à peine de s'achever."],
    ["Qu'est-ce que le plan Marshall ?", ["Un programme américain d'aide à la reconstruction européenne", "Un plan militaire de défense de l'Europe", "Un accord monétaire international", "Un plan d'aide à l'Allemagne seule"], 0,
     "Proposé en 1947, il fut refusé par l'URSS et ses satellites."],
    ["Quelle crise de 1948 oppose les Alliés à l'URSS autour de Berlin ?", ["Le blocus de Berlin", "La construction du Mur", "L'ultimatum de Khrouchtchev", "L'insurrection de Berlin-Est"], 0,
     "Un pont aérien ravitailla la ville pendant près d'un an."],
    ["Pourquoi la RDA fait-elle édifier le mur de Berlin en 1961 ?", ["Pour arrêter le départ massif de sa population vers l'Ouest", "Pour se protéger d'une invasion", "Pour délimiter les zones d'occupation", "Pour contrôler le commerce entre les deux villes"], 0,
     "Près de trois millions de personnes avaient déjà quitté le pays, souvent des travailleurs qualifiés."],
    ["Quelle crise de 1962 amène le monde au bord d'une guerre nucléaire ?", ["La crise des missiles de Cuba", "La crise de Suez", "La crise de Berlin", "La crise du Vietnam"], 0,
     "Elle aboutit à l'installation d'une ligne de communication directe entre Washington et Moscou."],
    ["Quel conflit oppose les États-Unis au Nord-Vietnam de 1964 à 1973 ?", ["La guerre du Vietnam", "La guerre de Corée", "La guerre du Cambodge", "La guerre d'Indochine"], 0,
     "La guerre d'Indochine, antérieure, opposait la France au Viêt-minh jusqu'en 1954."],
    ["Quelle intervention soviétique de 1968 met fin au Printemps de Prague ?", ["L'invasion de la Tchécoslovaquie par le pacte de Varsovie", "L'invasion de la Hongrie", "L'écrasement de la Pologne", "L'intervention en Roumanie"], 0,
     "Elle est justifiée par la doctrine Brejnev de souveraineté limitée."],
    ["Qu'est-ce que la détente des années 1970 ?", ["Une phase d'apaisement et d'accords de limitation des armements", "La fin de la guerre froide", "Un traité de désarmement complet", "Un rapprochement militaire des deux blocs"], 0,
     "Les accords SALT et l'Acte final d'Helsinki en 1975 en sont les principaux résultats."],
    ["Quelle politique Mikhaïl Gorbatchev engage-t-il à partir de 1985 ?", ["La perestroïka et la glasnost", "La collectivisation", "La déstalinisation", "Le rideau de fer sélectif"], 0,
     "Restructuration économique et transparence politique, qui échappent rapidement au contrôle du pouvoir."],
    ["Quel événement de décembre 1991 met fin à l'URSS ?", ["Sa dissolution officielle et la démission de Gorbatchev", "La chute du mur de Berlin", "Le putsch d'août", "La réunification allemande"], 0,
     "Quinze États indépendants lui succèdent. La Russie hérite du siège au Conseil de sécurité.", 3],
  ]),

  notion("hm2-etats-unis", S, "L'histoire des États-Unis",
    "De treize colonies à la première puissance mondiale : les étapes.",
    "La Constitution américaine de 1787 est la plus ancienne constitution écrite encore en vigueur.",
    2, [
    ["En quelle année les colonies américaines déclarent-elles leur indépendance ?", ["1776", "1783", "1787", "1765"], 0,
     "Le 4 juillet. La guerre se poursuit jusqu'au traité de Paris de 1783."],
    ["Quel slogan résume la contestation fiscale des colons américains ?", ["Pas de taxation sans représentation", "La liberté ou la mort", "Un pays, une loi", "Le pouvoir au peuple"], 0,
     "Les colonies n'avaient pas de députés au Parlement britannique qui votait leurs impôts."],
    ["Quelle bataille de 1781 décide de l'issue de la guerre d'indépendance américaine ?", ["Yorktown", "Saratoga", "Bunker Hill", "Trenton"], 0,
     "La flotte française y bloqua les Britanniques par la mer, rendant la reddition inévitable."],
    ["En quelle année la Constitution des États-Unis est-elle adoptée ?", ["1787", "1776", "1791", "1800"], 0,
     "Les dix premiers amendements, la Déclaration des droits, sont ratifiés en 1791."],
    ["Quel achat de 1803 double la superficie des États-Unis ?", ["L'achat de la Louisiane à la France", "L'achat de l'Alaska", "L'annexion du Texas", "La cession de la Floride"], 0,
     "Napoléon vendit le territoire pour financer ses guerres européennes."],
    ["Quelle doctrine de 1823 s'oppose à toute intervention européenne dans les Amériques ?", ["La doctrine Monroe", "La destinée manifeste", "La doctrine Truman", "La politique de la porte ouverte"], 0,
     "Elle servira aussi à justifier des interventions américaines dans le continent."],
    ["Quelle guerre déchire les États-Unis de 1861 à 1865 ?", ["La guerre de Sécession", "La guerre d'indépendance", "La guerre hispano-américaine", "Les guerres indiennes"], 0,
     "Environ six cent mille morts, plus que dans tous les autres conflits américains réunis jusqu'au XXe siècle."],
    ["Qu'est-ce que la ségrégation légale dans le Sud américain ?", ["Un système de séparation raciale imposé par les lois d'État", "Une pratique sociale non écrite", "Une règle fédérale", "Un régime propre aux écoles"], 0,
     "Les lois Jim Crow, validées en 1896 par l'arrêt Plessy, ne seront démantelées qu'à partir de 1954."],
    ["Quelle loi de 1964 interdit la discrimination raciale aux États-Unis ?", ["Le Civil Rights Act", "Le Voting Rights Act", "Le Fair Housing Act", "Le Brown Act"], 0,
     "Le Voting Rights Act de 1965 s'attaque spécifiquement aux obstacles au droit de vote.", 3],
  ]),

  notion("hm2-amerique-latine", S, "L'Amérique latine",
    "Civilisations précolombiennes, indépendances, XXe siècle politique.",
    "Les indépendances latino-américaines sont presque toutes acquises entre 1810 et 1825.",
    2, [
    ["Quelle civilisation précolombienne développe une écriture complète en Mésoamérique ?", ["Les Mayas", "Les Aztèques", "Les Incas", "Les Olmèques"], 0,
     "Leur système glyphique n'a été largement déchiffré qu'à partir des années 1950."],
    ["Quel système les Incas utilisaient-ils pour enregistrer des informations ?", ["Le quipu, un jeu de cordelettes nouées", "Un alphabet gravé", "Des tablettes d'argile", "Des pictogrammes peints"], 0,
     "Il notait au moins des données numériques ; l'hypothèse d'un contenu narratif reste débattue."],
    ["Quelle cité inca perchée dans les Andes est redécouverte en 1911 ?", ["Machu Picchu", "Cusco", "Ollantaytambo", "Tiwanaku"], 0,
     "Hiram Bingham la fit connaître ; le site n'avait jamais été totalement oublié des populations locales."],
    ["Quelle était la capitale de l'Empire aztèque ?", ["Tenochtitlan", "Teotihuacan", "Cholula", "Tlaxcala"], 0,
     "Bâtie sur un lac, elle comptait peut-être deux cent mille habitants. Mexico est édifiée sur ses ruines."],
    ["Qui est surnommé le Libertador en Amérique du Sud ?", ["Simón Bolívar", "José de San Martín", "Bernardo O'Higgins", "Antonio José de Sucre"], 0,
     "Il rêvait d'une grande fédération sud-américaine, projet qui échoua rapidement."],
    ["Quelle particularité l'indépendance du Brésil présente-t-elle en 1822 ?", ["Elle donne naissance à un empire dirigé par un prince portugais", "Elle est obtenue sans rupture avec Lisbonne", "Elle est proclamée par une assemblée élue", "Elle suit une guerre de dix ans"], 0,
     "Le Brésil reste une monarchie jusqu'en 1889, et n'abolit l'esclavage qu'en 1888."],
    ["Jusqu'à quelle année les États-Unis ont-ils contrôlé le canal de Panama ?", ["1999", "1945", "1977", "2015"], 0,
     "Les traités Torrijos-Carter de 1977 avaient programmé cette rétrocession sur vingt-deux ans."],
    ["Quelle révolution éclate au Mexique en 1910 ?", ["La révolution mexicaine", "La guerre des Cristeros", "La révolution d'Ayutla", "La guerre de Réforme"], 0,
     "Emiliano Zapata et Pancho Villa en sont les figures les plus connues."],
    ["Quel régime s'installe à Cuba après 1959 ?", ["Un régime communiste dirigé par Fidel Castro", "Une démocratie parlementaire", "Une junte militaire", "Un protectorat américain"], 0,
     "Le rapprochement avec l'URSS conduit à l'embargo américain, maintenu pendant des décennies."],
    ["Qu'est-ce que l'opération Condor ?", ["Une coordination des dictatures sud-américaines contre leurs opposants", "Un plan de développement régional", "Une opération militaire américaine", "Un accord commercial andin"], 0,
     "Mise en place dans les années 1970, elle organisait la traque et l'élimination transfrontalière d'opposants.", 3],
  ]),

  notion("hm2-japon-histoire", S, "L'histoire du Japon",
    "Shoguns, fermeture, modernisation accélérée : les tournants d'une histoire insulaire.",
    "Le Japon est passé d'une société féodale fermée à une puissance industrielle en une cinquantaine d'années.",
    2, [
    ["Quel titre porte le chef militaire qui gouverne le Japon à la place de l'empereur ?", ["Le shogun", "Le daimyo", "Le samouraï", "Le régent kampaku"], 0,
     "L'empereur conservait une autorité religieuse et symbolique sans pouvoir effectif."],
    ["Quelle période de fermeture le Japon connaît-il à partir des années 1630 ?", ["Le sakoku", "L'ère Meiji", "L'époque de Kamakura", "L'ère Taisho"], 0,
     "Seuls des marchands néerlandais et chinois étaient tolérés, dans un comptoir isolé à Nagasaki."],
    ["Quel événement de 1853 force le Japon à s'ouvrir ?", ["L'arrivée des navires du commodore Perry", "Une révolte paysanne", "Un traité avec la Chine", "Une invasion russe"], 0,
     "La démonstration de force navale américaine aboutit à des traités jugés inégaux."],
    ["Quelle restauration transforme le Japon à partir de 1868 ?", ["La restauration Meiji", "La restauration Kenmu", "La réforme de Taika", "L'ère Showa"], 0,
     "Abolition des privilèges des samouraïs, conscription, industrialisation et constitution en trente ans."],
    ["Quelle guerre de 1904-1905 voit le Japon battre une puissance européenne ?", ["La guerre russo-japonaise", "La première guerre sino-japonaise", "La guerre de Corée", "La guerre des Boxers"], 0,
     "La victoire de Tsushima eut un retentissement mondial et nourrit les mouvements anticoloniaux."],
    ["Quel territoire le Japon annexe-t-il en 1910 ?", ["La Corée", "Taïwan", "La Mandchourie", "Les Philippines"], 0,
     "Taïwan avait été cédé en 1895 ; la Mandchourie devient un État fantoche en 1932."],
    ["Quelle bataille navale de 1942 marque le tournant du Pacifique ?", ["Midway", "La mer de Corail", "Leyte", "Okinawa"], 0,
     "Le Japon y perd quatre porte-avions et l'initiative stratégique."],
    ["Sur quelles villes des bombes atomiques sont-elles larguées en 1945 ?", ["Hiroshima et Nagasaki", "Tokyo et Osaka", "Kyoto et Kobe", "Nagoya et Yokohama"], 0,
     "Les 6 et 9 août. La capitulation est annoncée le 15 août."],
    ["Que prévoit l'article 9 de la Constitution japonaise de 1947 ?", ["Le renoncement à la guerre comme droit souverain", "L'interdiction de toute police armée", "La neutralité permanente", "L'interdiction du service militaire"], 0,
     "Son interprétation a évolué pour permettre des forces d'autodéfense, sujet de débat constant depuis.", 3],
  ]),

  notion("hm2-afrique-precoloniale", S, "L'Afrique avant la colonisation",
    "Empires, réseaux commerciaux, savoirs : une histoire longtemps ignorée des manuels européens.",
    "L'Afrique précoloniale comptait de vastes États organisés, dotés d'universités et de monnaies.",
    2, [
    ["Quel empire ouest-africain contrôle le commerce de l'or au XIVe siècle ?", ["L'Empire du Mali", "L'Empire du Ghana", "L'Empire songhaï", "Le royaume du Bénin"], 0,
     "Son souverain Mansa Moussa est réputé pour son pèlerinage à La Mecque en 1324."],
    ["Quelle ville du Mali fut un grand centre intellectuel médiéval ?", ["Tombouctou", "Gao", "Djenné", "Ouagadougou"], 0,
     "Ses bibliothèques conservent des dizaines de milliers de manuscrits, en partie sauvés lors des conflits récents."],
    ["Quel empire succède au Mali dans la vallée du Niger au XVe siècle ?", ["L'Empire songhaï", "L'Empire du Ghana", "L'Empire du Kanem-Bornou", "Le royaume ashanti"], 0,
     "Il est détruit par une expédition marocaine en 1591, équipée d'armes à feu."],
    ["Quel commerce transsaharien reliait l'Afrique de l'Ouest à la Méditerranée ?", ["Le commerce de l'or et du sel", "Le commerce des épices", "Le commerce du bois", "Le commerce du cuivre seul"], 0,
     "L'or venait du sud, le sel des mines sahariennes. Les esclaves étaient aussi une marchandise de ces routes."],
    ["Quel royaume d'Afrique australe est associé à un vaste site de pierres sèches ?", ["Le Grand Zimbabwe", "Le royaume du Kongo", "Le royaume du Monomotapa seul", "Le royaume zoulou"], 0,
     "Ses murailles ont longtemps été attribuées à tort à des bâtisseurs étrangers par les archéologues coloniaux."],
    ["Quel royaume chrétien se maintient en Afrique de l'Est depuis l'Antiquité ?", ["l'Éthiopie", "La Nubie", "Le Kongo", "Le Buganda"], 0,
     "Le royaume d'Aksoum se convertit au IVe siècle. Les églises de Lalibela datent du XIIIe siècle."],
    ["Quelle cité-État swahilie prospérait sur la côte est-africaine ?", ["Kilwa", "Tombouctou", "Ifé", "Loango"], 0,
     "Le commerce de l'océan Indien y reliait l'Afrique, l'Arabie, l'Inde et la Chine."],
    ["Quel royaume africain est célèbre pour ses bronzes du XVIe siècle ?", ["Le royaume du Bénin", "Le royaume ashanti", "Le royaume du Dahomey", "Le royaume du Kongo"], 0,
     "Ces plaques, pillées lors de l'expédition britannique de 1897, font l'objet de demandes de restitution."],
    ["Quel royaume africain envoie des ambassadeurs au Vatican dès le XVIe siècle ?", ["Le royaume du Kongo", "Le royaume du Mali", "L'Éthiopie seule", "Le royaume du Bénin"], 0,
     "Son souverain se convertit au christianisme et entretint une correspondance directe avec le Portugal et Rome."],
    ["Combien de personnes la traite atlantique a-t-elle déportées selon les estimations ?", ["Environ douze millions", "Environ deux millions", "Environ trente millions", "Environ cinq cent mille"], 0,
     "Environ un déporté sur huit mourut pendant la traversée, soit 12 à 13 %. Les traites transsaharienne et orientale s'y ajoutent.", 3],
  ]),
];
