/**
 * Histoire de France, troisième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Histoire de France";

export const CG_HISTOIRE_FRANCE_3: SeedSkill[] = [
  notion("hf3-societe-ancien-regime", S, "La société d'Ancien Régime",
    "Ordres, privilèges, hiérarchies : comment était organisée la société avant 1789.",
    "La société d'ordres reposait sur des statuts juridiques, non sur la richesse.",
    2, [
    ["Quels sont les trois ordres de la société d'Ancien Régime ?", ["Le clergé, la noblesse et le tiers état", "La cour, la ville et la campagne", "Les nobles, les bourgeois et les paysans", "Le roi, les seigneurs et les serfs"], 0,
     "Le tiers état représentait environ quatre-vingt-dix-sept pour cent de la population."],
    ["Qu'est-ce qu'un privilège sous l'Ancien Régime ?", ["Un droit particulier attaché à un statut ou à un territoire", "Une faveur royale", "Un titre de noblesse", "Une exemption fiscale seulement"], 0,
     "Le mot signifie littéralement loi privée : provinces, villes et corporations en avaient aussi."],
    ["Qu'est-ce que la taille ?", ["Un impôt direct dont les privilégiés étaient largement exemptés", "Une taxe sur le sel", "Un droit seigneurial", "Une redevance ecclésiastique"], 0,
     "Son inégalité était l'un des principaux griefs des cahiers de doléances."],
    ["Qu'est-ce que la gabelle ?", ["Un impôt sur le sel très inégalement réparti selon les provinces", "Un impôt foncier", "Une taxe sur le vin", "Un droit de péage"], 0,
     "Certaines provinces en étaient exemptées, ce qui alimentait une contrebande massive."],
    ["Qu'est-ce que la dîme ?", ["Une redevance en nature versée à l'Église", "Un impôt royal", "Un droit seigneurial sur les moulins", "Une taxe de marché"], 0,
     "Son taux réel était généralement inférieur au dixième que son nom suggère."],
    ["Qu'est-ce qu'une corvée seigneuriale ?", ["Un travail gratuit dû au seigneur", "Un impôt en argent", "Une prestation militaire", "Une redevance sur les récoltes"], 0,
     "La corvée royale, distincte, servait à l'entretien des routes."],
    ["Qu'est-ce qu'une corporation de métier ?", ["Une organisation encadrant l'exercice d'un métier et l'accès à la maîtrise", "Un syndicat de travailleurs", "Une association de commerçants", "Une confrérie religieuse"], 0,
     "Supprimées en 1791 par la loi Le Chapelier, qui interdit aussi toute coalition ouvrière."],
    ["Qu'est-ce que la noblesse de robe ?", ["Une noblesse acquise par l'exercice de charges judiciaires ou administratives", "Une noblesse d'Église", "Une noblesse militaire", "Une noblesse de cour"], 0,
     "Elle s'opposait à la noblesse d'épée, plus ancienne et souvent méprisante à son égard."],
    ["Qu'est-ce que la vénalité des offices ?", ["L'achat de charges publiques, transmissibles par hérédité", "La corruption des officiers royaux", "La vente de titres de noblesse", "L'affermage des impôts"], 0,
     "Elle procurait des revenus immédiats à la monarchie au prix d'une administration difficile à réformer."],
    ["Qu'est-ce qu'un parlement sous l'Ancien Régime ?", ["Une cour de justice souveraine disposant d'un droit de remontrance", "Une assemblée représentative", "Un conseil du roi", "Une chambre législative"], 0,
     "Leur opposition aux réformes fiscales a contribué à la crise finale de la monarchie.", 3],
  ]),

  notion("hf3-marine-empire-colonial", S, "La France maritime et coloniale",
    "Compagnies, comptoirs, empires successifs.",
    "La France a perdu son premier empire colonial en 1763, avant d'en constituer un second au XIXe siècle.",
    2, [
    ["Quel explorateur français fonde Québec en 1608 ?", ["Samuel de Champlain", "Jacques Cartier", "Cavelier de La Salle", "Jean Ribault"], 0,
     "Jacques Cartier avait exploré le Saint-Laurent dès 1534."],
    ["Quel territoire nord-américain porte le nom de Nouvelle-France ?", ["Les possessions françaises d'Amérique du Nord", "La Louisiane seule", "Le Canada actuel", "Terre-Neuve"], 0,
     "Elle s'étendait du Saint-Laurent au golfe du Mexique à son apogée."],
    ["Quel traité de 1763 fait perdre à la France l'essentiel de son empire américain ?", ["Le traité de Paris", "Le traité d'Utrecht", "Le traité de Versailles", "Le traité d'Aix-la-Chapelle"], 0,
     "Il met fin à la guerre de Sept Ans. Voltaire parlait de quelques arpents de neige."],
    ["Quelle île antillaise fut la colonie française la plus riche au XVIIIe siècle ?", ["Saint-Domingue", "La Martinique", "La Guadeloupe", "La Réunion"], 0,
     "Elle produisait une part majeure du sucre et du café consommés en Europe."],
    ["Quelle compagnie française commerçait avec l'Asie au XVIIe siècle ?", ["La Compagnie française des Indes orientales", "La Compagnie du Sénégal", "La Compagnie du Mississippi", "La Compagnie des Cent-Associés"], 0,
     "Fondée par Colbert en 1664, sur le modèle néerlandais."],
    ["Quels comptoirs français ont subsisté en Inde jusqu'en 1954 ?", ["Pondichéry, Chandernagor, Karikal, Mahé et Yanaon", "Goa et Bombay", "Calcutta et Madras", "Surat et Cochin"], 0,
     "Leur rattachement à l'Inde s'est fait sans conflit armé."],
    ["Quand la France s'empare-t-elle d'Alger ?", ["En 1830", "En 1848", "En 1870", "En 1815"], 0,
     "Le prétexte fut un différend diplomatique sur une dette impayée."],
    ["Quel protectorat français est établi en Tunisie en 1881 ?", ["Le protectorat instauré par le traité du Bardo", "Une colonie de peuplement", "Un mandat international", "Un condominium franco-italien"], 0,
     "Le Maroc suivra en 1912 par le traité de Fès."],
    ["Quelle exposition parisienne de 1931 célèbre l'empire colonial ?", ["l'Exposition coloniale internationale", "l'Exposition universelle", "l'Exposition des arts décoratifs", "l'Exposition de 1937"], 0,
     "Plus de trente millions de visites. Une contre-exposition fut organisée par les surréalistes."],
    ["Combien de personnes vivaient dans l'empire colonial français en 1939 ?", ["Environ cent millions", "Environ vingt millions", "Environ trois cents millions", "Environ cinquante millions"], 0,
     "Sur plus de douze millions de kilomètres carrés, second empire mondial après le britannique.", 3],
  ]),

  notion("hf3-industrialisation-france", S, "L'industrialisation de la France",
    "Un rythme plus lent et plus régulier que celui de ses voisins.",
    "L'industrialisation française a été plus tardive et plus progressive qu'en Angleterre.",
    2, [
    ["Quel bassin houiller a été le plus important de France ?", ["Le bassin du Nord-Pas-de-Calais", "Le bassin de la Loire", "Le bassin de Lorraine", "Le bassin d'Alès"], 0,
     "Son exploitation a cessé en 1990 après plus de deux siècles d'activité."],
    ["Quelle région française s'est spécialisée dans la sidérurgie grâce au minerai de fer ?", ["La Lorraine", "La Bretagne", "L'Auvergne", "La Normandie"], 0,
     "Le procédé Thomas, en 1878, a permis d'exploiter la minette lorraine, riche en phosphore."],
    ["Quelle industrie textile domine dans le Nord au XIXe siècle ?", ["Le textile de coton et de laine autour de Roubaix-Tourcoing", "La soie", "Le lin exclusivement", "La bonneterie"], 0,
     "Lyon restait la capitale de la soie, avec une organisation du travail très différente."],
    ["Quelle catastrophe minière frappe Courrières en 1906 ?", ["Un coup de poussier faisant plus de mille morts", "Un effondrement de galerie", "Une inondation de puits", "Un incendie de carreau"], 0,
     "La plus grande catastrophe minière européenne. Elle a provoqué une grève massive."],
    ["Quand la journée de huit heures est-elle instaurée en France ?", ["En 1919", "En 1936", "En 1906", "En 1945"], 0,
     "La loi de 1906 avait instauré le repos hebdomadaire obligatoire."],
    ["Qu'est-ce que le taylorisme introduit en France dans les années 1910 ?", ["Une organisation scientifique du travail décomposant les tâches", "Une automatisation des chaînes", "Un système de primes au rendement", "Un mode de gestion des stocks"], 0,
     "Renault l'expérimente dès 1912, provoquant des grèves importantes."],
    ["Quelle entreprise française symbolise l'automobile de masse dans l'entre-deux-guerres ?", ["Citroën", "Peugeot", "Panhard", "Delage"], 0,
     "André Citroën applique le premier la production en série à la française."],
    ["Qu'est-ce que la sidérurgie sur l'eau des années 1960 ?", ["L'implantation de complexes sidérurgiques dans les ports", "Une production hydraulique d'acier", "Une sidérurgie fluviale", "Un procédé de refroidissement"], 0,
     "Dunkerque et Fos-sur-Mer illustrent ce choix, lié à l'importation du minerai."],
    ["Qu'est-ce que la désindustrialisation française depuis les années 1970 ?", ["Un recul massif de l'emploi industriel", "Une baisse de la production absolue", "Une délocalisation totale", "Un abandon de l'industrie lourde seule"], 0,
     "La part de l'industrie dans l'emploi est passée d'environ un tiers à moins de dix pour cent."],
    ["Quel bassin industriel a été le plus touché par la crise sidérurgique ?", ["La Lorraine", "L'Alsace", "La Bourgogne", "Le Limousin"], 0,
     "Les fermetures des années 1970 et 1980 y ont provoqué de longs conflits sociaux.", 3],
  ]),

  notion("hf3-mouvement-ouvrier", S, "Le mouvement ouvrier français",
    "Syndicats, grèves, conquêtes sociales.",
    "Les syndicats ont été interdits en France pendant près d'un siècle.",
    2, [
    ["Quelle loi de 1791 interdit les coalitions ouvrières ?", ["La loi Le Chapelier", "La loi Waldeck-Rousseau", "La loi Ollivier", "La loi Guizot"], 0,
     "Elle supprime les corporations mais interdit aussi toute association professionnelle."],
    ["Quel délit la loi Ollivier de 1864 supprime-t-elle ?", ["Le délit de coalition", "Le délit d'attroupement", "Le délit d'association", "Le délit de réunion"], 0,
     "La grève cesse d'être une infraction pénale, sans être encore reconnue comme un droit."],
    ["Quelle loi de 1884 autorise les syndicats professionnels ?", ["La loi Waldeck-Rousseau", "La loi Le Chapelier", "La loi Ferry", "La loi Millerand"], 0,
     "Elle met fin à près d'un siècle d'interdiction."],
    ["Quelle centrale syndicale française est fondée en 1895 ?", ["La CGT", "La CFDT", "FO", "La CFTC"], 0,
     "La CFTC naît en 1919, FO en 1948, la CFDT en 1964."],
    ["Qu'est-ce que la charte d'Amiens de 1906 ?", ["Un texte affirmant l'indépendance du syndicalisme vis-à-vis des partis", "Un accord salarial", "Une convention collective", "Une déclaration de grève générale"], 0,
     "Elle reste une référence dans les débats sur le rôle du syndicalisme français."],
    ["Que gagnent les ouvriers lors des accords Matignon de 1936 ?", ["Hausses de salaires, conventions collectives et délégués du personnel", "Les congés payés seuls", "La semaine de quarante heures seule", "La retraite à soixante ans"], 0,
     "Congés payés et semaine de quarante heures sont votés dans les jours suivants."],
    ["Combien de jours de congés payés la loi de 1936 accorde-t-elle ?", ["Douze jours, soit deux semaines", "Une semaine", "Trois semaines", "Un mois"], 0,
     "Une troisième semaine est accordée en 1956, une quatrième en 1969, une cinquième en 1982."],
    ["Qu'est-ce que le Conseil national de la Résistance a prévu en matière sociale ?", ["Sécurité sociale, retraites et droit au travail", "La nationalisation de toutes les entreprises", "Le salaire minimum", "La cogestion des entreprises"], 0,
     "Son programme de mars 1944 a largement structuré les réformes de la Libération."],
    ["Qu'est-ce que le comité d'entreprise créé en 1945 ?", ["Une instance de représentation du personnel consultée sur la marche de l'entreprise", "Un syndicat d'entreprise", "Un conseil d'administration ouvrier", "Une caisse sociale"], 0,
     "Il a fusionné avec d'autres instances dans le comité social et économique en 2017."],
    ["Quel mouvement social a mobilisé le plus de grévistes de l'histoire française ?", ["Mai 1968", "Les grèves de 1936", "Les grèves de 1995", "Les grèves de 1947"], 0,
     "Entre sept et neuf millions de grévistes, contre environ deux millions en 1936.", 3],
  ]),

  notion("hf3-ecole-republique", S, "L'école de la République",
    "Construction du système scolaire français.",
    "L'école obligatoire ne signifiait pas l'école pour tous jusqu'au baccalauréat.",
    2, [
    ["Que prévoit la loi Guizot de 1833 ?", ["Une école primaire de garçons par commune", "La gratuité de l'école", "L'obligation scolaire", "La laïcité de l'enseignement"], 0,
     "Elle organise aussi une formation des instituteurs dans des écoles normales."],
    ["Que prévoit la loi Falloux de 1850 ?", ["Un renforcement du rôle de l'Église dans l'enseignement", "La laïcisation des programmes", "La gratuité du secondaire", "La création des lycées de filles"], 0,
     "Elle favorise le développement de l'enseignement privé confessionnel."],
    ["Quelle loi de 1867 encourage l'ouverture d'écoles de filles ?", ["La loi Duruy", "La loi Guizot", "La loi Falloux", "La loi Ferry"], 0,
     "Victor Duruy développe aussi des cours secondaires pour jeunes filles, très critiqués à l'époque."],
    ["Quand les lycées de jeunes filles sont-ils créés ?", ["En 1880, par la loi Camille Sée", "En 1850", "En 1902", "En 1924"], 0,
     "Leur programme n'est aligné sur celui des garçons qu'en 1924."],
    ["Que devient l'école primaire avec les lois Ferry ?", ["Gratuite en 1881, obligatoire et laïque en 1882", "Obligatoire en 1881", "Laïque dès 1879", "Gratuite en 1882"], 0,
     "La laïcisation du personnel enseignant n'interviendra qu'en 1886, avec la loi Goblet."],
    ["Qu'est-ce que le certificat d'études primaires ?", ["Un diplôme sanctionnant la fin de la scolarité élémentaire", "Un examen d'entrée en sixième", "Un brevet professionnel", "Un diplôme d'instituteur"], 0,
     "Créé en 1866, il a été supprimé en 1989 et reste un symbole de l'école républicaine."],
    ["Quand la scolarité obligatoire est-elle prolongée jusqu'à quatorze ans ?", ["En 1936", "En 1882", "En 1959", "En 1945"], 0,
     "Elle passe à seize ans avec la réforme Berthoin de 1959, applicable à partir de 1967."],
    ["Qu'est-ce que le collège unique instauré en 1975 ?", ["Un collège commun à tous les élèves après le primaire", "Un collège d'enseignement général", "Un collège technique unifié", "Un cycle d'orientation"], 0,
     "La réforme Haby supprime les filières séparées après le primaire."],
    ["Quel objectif est fixé en 1985 pour le baccalauréat ?", ["Amener quatre-vingts pour cent d'une classe d'âge au niveau du baccalauréat", "Rendre le baccalauréat obligatoire", "Supprimer les filières", "Créer le baccalauréat professionnel seul"], 0,
     "Le baccalauréat professionnel est créé la même année pour y contribuer."],
    ["Quelle part d'une génération obtient aujourd'hui le baccalauréat en France ?", ["Environ huit sur dix", "Environ la moitié", "Environ trois sur dix", "La quasi-totalité"], 0,
     "Contre environ cinq pour cent au début des années 1950.", 3],
  ]),

  notion("hf3-sante-france", S, "Santé publique et médecine en France",
    "Hôpitaux, épidémies, protection sanitaire.",
    "L'hôpital français est passé d'un lieu d'accueil des pauvres à un lieu de soin technique.",
    2, [
    ["Qu'était l'hôtel-Dieu médiéval ?", ["Un lieu d'accueil des pauvres, des malades et des voyageurs", "Un hôpital de soins", "Une léproserie", "Une maternité"], 0,
     "La fonction charitable y primait sur la fonction médicale."],
    ["Quelle institution est créée en 1656 pour enfermer les pauvres à Paris ?", ["l'Hôpital général", "L'Hôtel-Dieu", "La Salpêtrière seule", "Les Invalides"], 0,
     "Le grand renfermement a concerné plusieurs milliers de personnes."],
    ["Qui crée l'Institut Pasteur en 1888 ?", ["Louis Pasteur, grâce à une souscription internationale", "l'État français", "L'Académie de médecine", "La ville de Paris"], 0,
     "Le succès du vaccin contre la rage avait suscité des dons du monde entier."],
    ["Quelle maladie a été combattue par le BCG mis au point en France ?", ["La tuberculose", "La variole", "La diphtérie", "La poliomyélite"], 0,
     "Calmette et Guérin le mettent au point à l'Institut Pasteur de Lille en 1921."],
    ["Qu'est-ce que la loi Veil de 1975 ?", ["La légalisation de l'interruption volontaire de grossesse", "La légalisation de la contraception", "La création de la Sécurité sociale", "La réforme hospitalière"], 0,
     "La contraception avait été légalisée par la loi Neuwirth en 1967."],
    ["Quel scandale sanitaire des années 1980 concerne les transfusions ?", ["L'affaire du sang contaminé", "L'affaire du Mediator", "L'affaire de l'amiante", "L'affaire de l'hormone de croissance"], 0,
     "Des hémophiles ont été contaminés par le VIH après des retards dans les mesures de sécurité."],
    ["Quelle agence a été créée en 1993 après les crises sanitaires ?", ["l'Agence du médicament, ancêtre de l'ANSM", "La Haute Autorité de santé", "l'ANSES", "Santé publique France"], 0,
     "La séparation entre évaluation et gestion du risque a alors été renforcée."],
    ["Qu'est-ce que la canicule de 2003 a révélé en France ?", ["Une vulnérabilité des personnes âgées isolées et un défaut d'alerte", "Une faiblesse du système hospitalier seul", "Un manque de climatisation", "Une insuffisance des services d'urgence"], 0,
     "Environ quinze mille décès en excès. Un plan national canicule a été créé ensuite."],
    ["Quelle particularité le système de santé français présente-t-il ?", ["Une médecine libérale associée à un financement socialisé", "Un système entièrement public", "Un système d'assurance privée", "Un système géré par les régions"], 0,
     "Cette combinaison est relativement rare parmi les pays comparables.", 3],
  ]),

  notion("hf3-agriculture-france", S, "L'agriculture française",
    "Du monde paysan à l'agriculture moderne.",
    "La France comptait plus de six millions d'agriculteurs en 1950 ; ils sont moins de quatre cent mille aujourd'hui.",
    2, [
    ["Quelle part de la population active française travaillait dans l'agriculture en 1900 ?", ["Environ quatre sur dix", "Environ deux sur dix", "Environ six sur dix", "Environ une sur dix"], 0,
     "Contre moins de deux pour cent aujourd'hui."],
    ["Qu'est-ce que le remembrement agricole ?", ["Le regroupement de parcelles morcelées en unités plus grandes", "L'agrandissement des exploitations", "La redistribution des terres", "La mise en commun des cultures"], 0,
     "Il a facilité la mécanisation mais détruit des centaines de milliers de kilomètres de haies."],
    ["Quel événement de 1907 mobilise les viticulteurs du Languedoc ?", ["La révolte des vignerons contre la surproduction et la fraude", "Une grève des ouvriers agricoles", "Une révolte fiscale", "Une manifestation contre le phylloxéra"], 0,
     "Des centaines de milliers de manifestants et une mutinerie de soldats du dix-septième régiment."],
    ["Qu'est-ce que le Crédit agricole à l'origine ?", ["Un réseau de caisses mutualistes pour financer les agriculteurs", "Une banque publique agricole", "Un organisme de subventions", "Une coopérative d'achat"], 0,
     "Créé à la fin du XIXe siècle, il est devenu l'une des premières banques mondiales."],
    ["Qu'est-ce qu'une coopérative agricole ?", ["Une structure détenue par des agriculteurs pour mutualiser des activités", "Une entreprise d'agrofourniture", "Un groupement d'achat", "Un syndicat agricole"], 0,
     "Elles collectent et transforment aujourd'hui une part majeure de la production française."],
    ["Quel syndicat agricole a longtemps été majoritaire en France ?", ["La FNSEA", "La Confédération paysanne", "La Coordination rurale", "Le MODEF"], 0,
     "Elle a joué un rôle central dans la cogestion de la politique agricole avec l'État."],
    ["Qu'est-ce que la politique des structures agricoles des années 1960 ?", ["Une politique favorisant l'agrandissement et la modernisation des exploitations", "Une réforme foncière", "Une politique de prix garantis", "Un soutien aux petites exploitations"], 0,
     "Les lois Pisani ont notamment créé les SAFER et les indemnités de départ."],
    ["Qu'est-ce qu'une SAFER ?", ["Une société pouvant préempter des terres agricoles pour orienter leur usage", "Une coopérative foncière", "Un organisme de crédit rural", "Une chambre d'agriculture"], 0,
     "Elle vise notamment à faciliter l'installation de nouveaux agriculteurs."],
    ["Quel est le rang de la France dans la production agricole européenne ?", ["Premier producteur de l'Union européenne", "Deuxième", "Troisième", "Cinquième"], 0,
     "Sa balance commerciale agroalimentaire s'est cependant nettement dégradée depuis les années 2000."],
    ["Quel enjeu majeur l'agriculture française affronte-t-elle aujourd'hui ?", ["Le renouvellement des générations d'exploitants", "Le manque de terres", "L'absence de débouchés", "Le manque de main-d'œuvre saisonnière seul"], 0,
     "Près de la moitié des exploitants doivent partir à la retraite dans la décennie à venir.", 3],
  ]),

  notion("hf3-immigration-france", S, "L'immigration en France",
    "Vagues, politiques, intégration.",
    "La France est le plus ancien pays d'immigration d'Europe continentale.",
    2, [
    ["Pourquoi la France a-t-elle recouru à l'immigration dès le XIXe siècle ?", ["Sa transition démographique précoce limitait la main-d'œuvre disponible", "Elle manquait de terres", "Elle voulait peupler ses colonies", "Elle appliquait une politique volontariste d'accueil"], 0,
     "Sa natalité a baissé bien plus tôt que celle de ses voisins européens."],
    ["Quelles nationalités dominent l'immigration en France dans l'entre-deux-guerres ?", ["Italienne, polonaise et espagnole", "Algérienne et marocaine", "Portugaise et turque", "Belge et allemande"], 0,
     "Les Polonais ont notamment été recrutés collectivement pour les mines du Nord."],
    ["Quel afflux de réfugiés la France connaît-elle en 1939 ?", ["La Retirada des républicains espagnols", "L'arrivée de réfugiés allemands", "L'exode belge", "L'arrivée d'Arméniens"], 0,
     "Environ quatre cent cinquante mille personnes en quelques semaines, souvent internées dans des camps."],
    ["Quel organisme recrute la main-d'œuvre étrangère après 1945 ?", ["l'Office national d'immigration", "Le ministère du Travail seul", "Les préfectures", "Les entreprises directement"], 0,
     "Le recrutement direct par les employeurs, ensuite régularisé, est resté très courant."],
    ["Quelle nationalité domine l'immigration de travail dans les années 1960 ?", ["La nationalité portugaise puis maghrébine", "L'italienne", "La turque", "La polonaise"], 0,
     "Les Portugais fuyaient aussi la dictature et la guerre coloniale."],
    ["Qu'est-ce que le regroupement familial en France ?", ["Le droit pour un résident étranger de faire venir sa famille proche", "Une régularisation collective", "Un droit d'asile familial", "Un statut de résident permanent"], 0,
     "Il devient la principale voie d'entrée légale après la suspension de l'immigration de travail en 1974."],
    ["Qu'est-ce que la Marche pour l'égalité de 1983 ?", ["Une marche contre le racisme partie de Marseille vers Paris", "Une manifestation syndicale", "Une marche pour les droits des femmes", "Une marche de sans-papiers"], 0,
     "Surnommée Marche des beurs par la presse, elle a rassemblé cent mille personnes à l'arrivée."],
    ["Qu'est-ce que le droit du sol en France ?", ["L'acquisition de la nationalité liée à la naissance et à la résidence sur le territoire", "L'acquisition automatique à la naissance", "Un droit réservé aux enfants de résidents", "Un droit de propriété foncière"], 0,
     "Il est en France conditionné à une résidence prolongée pendant la minorité."],
    ["Qu'est-ce que la Cité nationale de l'histoire de l'immigration ?", ["Un musée consacré à l'histoire de l'immigration en France", "Un centre d'accueil", "Un observatoire statistique", "Un centre d'archives"], 0,
     "Installée au palais de la Porte Dorée, ancien musée des colonies, elle a ouvert en 2007."],
    ["Quelle part de la population française a au moins un grand-parent immigré ?", ["Environ un quart", "Environ un dixième", "Environ la moitié", "Environ un vingtième"], 0,
     "Ce chiffre illustre l'ancienneté et la profondeur du fait migratoire français.", 3],
  ]),

  notion("hf3-decentralisation-territoires", S, "Aménagement du territoire",
    "Politiques d'équilibre, métropoles, ruralités.",
    "Le déséquilibre entre la capitale et le reste du pays a été nommé dès 1947 par un géographe, dans un titre resté célèbre.",
    2, [
    ["Quel ouvrage de 1947 dénonce le déséquilibre entre Paris et la province ?", ["Paris et le désert français", "La France déchirée", "Le Territoire de l'aménagement", "La Métropole et ses marges"], 0,
     "Jean-François Gravier y plaide pour une politique d'aménagement volontariste."],
    ["Quel organisme d'aménagement du territoire est créé en 1963 ?", ["La DATAR", "Le Commissariat général au Plan", "L'Agence nationale de l'urbanisme", "Le CNAT"], 0,
     "Elle a piloté les politiques de métropoles d'équilibre et de villes nouvelles."],
    ["Qu'est-ce qu'une métropole d'équilibre ?", ["Une grande ville de province soutenue pour contrebalancer Paris", "Une capitale régionale administrative", "Une ville nouvelle", "Une agglomération transfrontalière"], 0,
     "Huit ont été désignées dans les années 1960, dont Lyon, Marseille et Lille."],
    ["Combien de villes nouvelles ont été créées en région parisienne ?", ["Cinq", "Trois", "Sept", "Deux"], 0,
     "Cergy-Pontoise, Évry, Marne-la-Vallée, Melun-Sénart et Saint-Quentin-en-Yvelines."],
    ["Qu'est-ce que la politique de la ville ?", ["Une action publique ciblée sur les quartiers en difficulté", "Une politique d'urbanisme général", "Une politique du logement", "Une politique des transports urbains"], 0,
     "Elle combine rénovation urbaine, action sociale et développement économique local."],
    ["Qu'est-ce que le zonage en quartiers prioritaires ?", ["Un découpage identifiant les territoires à faible revenu pour concentrer les moyens", "Un classement urbanistique", "Un périmètre de rénovation", "Une zone franche fiscale"], 0,
     "Le critère principal retenu depuis 2014 est le revenu des habitants."],
    ["Qu'est-ce que la diagonale du vide ?", ["Une bande de faible densité traversant la France du nord-est au sud-ouest", "Une zone désindustrialisée", "Un couloir de transit", "Une zone montagneuse"], 0,
     "Le terme est aujourd'hui critiqué car il gomme la diversité de ces territoires."],
    ["Qu'est-ce qu'une zone de revitalisation rurale ?", ["Un dispositif d'exonérations pour soutenir les territoires ruraux fragiles", "Une aire protégée", "Un parc naturel régional", "Un périmètre agricole prioritaire"], 0,
     "Son efficacité fait l'objet d'évaluations contrastées."],
    ["Qu'est-ce qu'un parc naturel régional ?", ["Un territoire habité à patrimoine remarquable géré par une charte", "Une réserve naturelle intégrale", "Un parc national", "Une zone Natura 2000"], 0,
     "Contrairement au parc national, il repose sur l'adhésion volontaire des communes."],
    ["Qu'est-ce que la fracture territoriale ?", ["Un écart croissant d'accès aux services et aux emplois entre territoires", "Une division administrative", "Une rupture géologique", "Une inégalité entre régions riches et pauvres seulement"], 0,
     "Elle recoupe partiellement mais pas totalement l'opposition entre métropoles et périphéries.", 3],
  ]),

  notion("hf3-culture-france-xxe", S, "La vie culturelle française au XXe siècle",
    "Politiques publiques, institutions, mouvements.",
    "La France a fait de la culture une politique publique bien avant la plupart de ses voisins.",
    2, [
    ["Quelle institution culturelle est créée en 1959 ?", ["Le ministère des Affaires culturelles", "Le CNC", "La Cinémathèque", "Le Centre Pompidou"], 0,
     "André Malraux en est le premier titulaire, avec une mission de démocratisation."],
    ["Qu'est-ce que le Théâtre national populaire de Jean Vilar ?", ["Un théâtre visant un public large avec un répertoire exigeant", "Un théâtre de rue", "Un théâtre amateur national", "Un théâtre subventionné régional"], 0,
     "Prix bas, horaires adaptés et suppression des pourboires en faisaient partie."],
    ["Quel centre culturel parisien ouvre en 1977 ?", ["Le Centre Pompidou", "La Cité des sciences", "l'Opéra Bastille", "La Grande Bibliothèque"], 0,
     "Il réunit un musée d'art moderne, une bibliothèque publique et un centre de création."],
    ["Quels grands travaux marquent les années 1980 et 1990 à Paris ?", ["La pyramide du Louvre, l'Opéra Bastille et la Grande Bibliothèque", "Le Centre Pompidou et la Défense", "Le musée d'Orsay seul", "La tour Montparnasse"], 0,
     "L'Arche de la Défense et la Cité des sciences en font également partie."],
    ["Quelle fête populaire est créée en 1982 par le ministère de la Culture ?", ["La Fête de la musique", "Les Journées du patrimoine", "La Nuit des musées", "Le Printemps des poètes"], 0,
     "Elle se tient le 21 juin et a été reprise dans plus de cent pays."],
    ["Quand les Journées du patrimoine sont-elles créées ?", ["En 1984", "En 1959", "En 1995", "En 1977"], 0,
     "Elles ouvrent au public des bâtiments habituellement fermés, dont des lieux de pouvoir."],
    ["Qu'est-ce que la Bibliothèque nationale de France site François-Mitterrand ?", ["Un ensemble de quatre tours ouvert en 1996", "Le site historique de la rue de Richelieu", "Une bibliothèque universitaire", "Un centre d'archives"], 0,
     "Le projet a suscité de vives critiques sur la conservation des livres dans des tours vitrées."],
    ["Qu'est-ce que le musée du quai Branly ?", ["Un musée consacré aux arts d'Afrique, d'Asie, d'Océanie et des Amériques", "Un musée d'art contemporain", "Un musée d'ethnographie française", "Un musée colonial"], 0,
     "Ouvert en 2006, il a hérité de collections du musée de l'Homme et du musée des Arts africains."],
    ["Qu'est-ce que la décentralisation théâtrale d'après-guerre ?", ["La création de centres dramatiques en province", "La suppression des théâtres parisiens", "Le transfert des tournées en région", "La régionalisation du financement"], 0,
     "Le premier centre dramatique national ouvre à Colmar en 1946."],
    ["Quel constat les enquêtes sur les pratiques culturelles établissent-elles depuis 1973 ?", ["Une forte corrélation entre diplôme et fréquentation culturelle", "Une égalisation progressive des pratiques", "Une baisse générale des pratiques", "Une indépendance vis-à-vis du milieu social"], 0,
     "Le numérique a modifié les pratiques sans effacer ces écarts.", 3],
  ]),

  notion("hf3-justice-france-histoire", S, "L'histoire de la justice française",
    "De la justice seigneuriale à l'État de droit.",
    "La torture judiciaire a été abolie en France en 1788, un an avant la Révolution.",
    2, [
    ["Qu'est-ce que la question judiciaire sous l'Ancien Régime ?", ["La torture employée pour obtenir des aveux", "Un interrogatoire contradictoire", "Une procédure d'appel", "Une enquête préliminaire"], 0,
     "Elle est abolie en deux temps, en 1780 et 1788."],
    ["Quel philosophe italien influence la réforme pénale au XVIIIe siècle ?", ["Cesare Beccaria", "Montesquieu seul", "Voltaire", "Filangieri"], 0,
     "Son traité Des délits et des peines, en 1764, plaide contre la torture et la peine de mort."],
    ["Quel code pénal est promulgué en 1810 ?", ["Le Code pénal napoléonien", "Le Code criminel révolutionnaire", "Le Code d'instruction criminelle seul", "Le Code Louis"], 0,
     "Il est resté en vigueur, très modifié, jusqu'à l'entrée en application du nouveau code en 1994."],
    ["Qu'est-ce que le bagne en France ?", ["Un lieu de détention avec travaux forcés, notamment aux colonies", "Une prison militaire", "Un camp de travail temporaire", "Une prison d'État"], 0,
     "Le bagne de Guyane a fonctionné jusqu'en 1938, les derniers bagnards revenant après 1945."],
    ["Qu'est-ce que la relégation instaurée en 1885 ?", ["Une déportation à vie des multirécidivistes", "Une peine de bannissement", "Une assignation à résidence", "Une déchéance civique"], 0,
     "Elle frappait des délinquants mineurs répétés, souvent pour de petits vols."],
    ["Quand la justice des mineurs est-elle spécialisée en France ?", ["Par l'ordonnance de 1945", "En 1912", "En 1958", "En 1970"], 0,
     "Une première loi de 1912 avait créé des tribunaux pour enfants ; 1945 pose la primauté de l'éducatif."],
    ["Qu'est-ce que la guillotine ?", ["Un instrument d'exécution adopté en 1792 par souci d'égalité et de rapidité", "Un instrument de torture", "Une machine de guerre", "Un dispositif de contention"], 0,
     "Elle devait rendre la mort identique pour tous, nobles comme roturiers."],
    ["Quand la dernière exécution capitale a-t-elle lieu en France ?", ["En 1977", "En 1972", "En 1981", "En 1969"], 0,
     "À Marseille. L'abolition intervient quatre ans plus tard."],
    ["Qu'est-ce que la présomption d'innocence renforcée par la loi de 2000 ?", ["Un ensemble de garanties procédurales pour les personnes mises en cause", "Une nouvelle définition du doute", "Une réforme de la détention provisoire seule", "Une limitation de la publicité des procès"], 0,
     "Elle crée notamment le juge des libertés et de la détention."],
    ["Qu'est-ce que le Conseil supérieur de la magistrature ?", ["Une institution veillant à l'indépendance de l'autorité judiciaire", "Une juridiction d'appel", "Un conseil de discipline des avocats", "Une instance de nomination des préfets"], 0,
     "Sa composition et ses pouvoirs ont été plusieurs fois réformés pour renforcer son indépendance.", 3],
  ]),

  notion("hf3-vie-quotidienne", S, "La vie quotidienne des Français",
    "Logement, consommation, loisirs à travers les décennies.",
    "L'équipement des logements français a changé plus vite entre 1950 et 1975 qu'en un siècle auparavant.",
    2, [
    ["Quelle part des logements français avait l'eau courante en 1954 ?", ["Environ six sur dix", "La quasi-totalité", "Environ trois sur dix", "Environ neuf sur dix"], 0,
     "Moins d'un logement sur dix disposait alors d'une baignoire ou d'une douche."],
    ["Quel équipement se généralise dans les foyers français dans les années 1960 ?", ["Le réfrigérateur et la télévision", "Le lave-vaisselle", "Le téléphone", "Le micro-ondes"], 0,
     "Le taux d'équipement en réfrigérateur passe d'environ un foyer sur dix à la quasi-totalité en quinze ans."],
    ["Quand la télévision devient-elle majoritaire dans les foyers français ?", ["Au milieu des années 1960", "En 1950", "En 1975", "En 1980"], 0,
     "La deuxième chaîne apparaît en 1964, la couleur en 1967."],
    ["Qu'est-ce que le grand ensemble des années 1950 et 1960 ?", ["Un ensemble de logements collectifs construits rapidement en périphérie", "Un quartier résidentiel pavillonnaire", "Une cité ouvrière", "Un lotissement social"], 0,
     "Ils apportaient un confort inédit à des familles souvent mal logées auparavant."],
    ["Qu'est-ce que le baby-boom français ?", ["Une forte hausse de la natalité de 1945 aux années 1960", "Une hausse de l'immigration", "Une baisse de la mortalité infantile", "Un rattrapage des naissances de guerre seul"], 0,
     "Il a duré plus longtemps en France que dans la plupart des pays européens."],
    ["Quand le premier hypermarché ouvre-t-il en France ?", ["En 1963, à Sainte-Geneviève-des-Bois", "En 1950", "En 1972", "En 1958"], 0,
     "Le modèle s'est ensuite exporté dans le monde entier."],
    ["Qu'est-ce que le Minitel ?", ["Un terminal télématique français diffusé à partir de 1980", "Un ordinateur personnel", "Un téléphone à écran", "Un service de télévision interactive"], 0,
     "Neuf millions de terminaux distribués gratuitement, avec des usages qui préfiguraient internet."],
    ["Quand le téléphone se généralise-t-il dans les foyers français ?", ["Dans les années 1970 et 1980", "Dans les années 1950", "Dans les années 1990", "Dès 1945"], 0,
     "Le plan de rattrapage téléphonique de 1974 a fait passer la France du dernier au premier rang européen."],
    ["Qu'est-ce que la semaine de trente-neuf heures instaurée en 1982 ?", ["Une réduction du temps de travail légal", "Une durée maximale de travail", "Un horaire de référence conventionnel", "Un plafond hebdomadaire"], 0,
     "La cinquième semaine de congés payés est accordée la même année."],
    ["Quand les trente-cinq heures sont-elles instaurées en France ?", ["En 1998 et 2000, par les lois Aubry", "En 1982", "En 2005", "En 1993"], 0,
     "Leur effet sur l'emploi reste discuté parmi les économistes.", 3],
  ]),

  notion("hf3-france-europe", S, "La France et la construction européenne",
    "Rôle, engagements, débats.",
    "La France a proposé la première étape de la construction européenne en 1950.",
    2, [
    ["Quelle déclaration de 1950 propose une communauté du charbon et de l'acier ?", ["La déclaration Schuman", "Le plan Monnet", "La déclaration de Messine", "Le plan Marshall"], 0,
     "Rédigée par Jean Monnet, elle vise à rendre la guerre franco-allemande matériellement impossible."],
    ["Quel projet européen la France rejette-t-elle en 1954 ?", ["La Communauté européenne de défense", "La CECA", "Le traité de Rome", "L'Union de l'Europe occidentale"], 0,
     "L'Assemblée nationale française refuse de ratifier un traité que la France avait proposé."],
    ["Qu'est-ce que la politique de la chaise vide en 1965 ?", ["Le refus français de siéger dans les instances européennes", "Un boycott du Parlement européen", "Un retrait de la CEE", "Une abstention systématique"], 0,
     "De Gaulle s'opposait à l'extension du vote à la majorité qualifiée."],
    ["Quel compromis met fin à la crise de la chaise vide ?", ["Le compromis de Luxembourg de 1966", "Le traité de Rome", "L'Acte unique", "Le compromis de Bruxelles"], 0,
     "Il permet à un État d'invoquer un intérêt vital pour bloquer une décision."],
    ["Quand les Français élisent-ils pour la première fois des députés européens ?", ["En 1979", "En 1957", "En 1986", "En 1992"], 0,
     "Simone Veil est élue première présidente du Parlement européen élu."],
    ["Quel traité les Français ratifient-ils de justesse par référendum en 1992 ?", ["Le traité de Maastricht", "Le traité de Rome", "L'Acte unique", "Le traité d'Amsterdam"], 0,
     "Cinquante et un pour cent de oui, après une campagne particulièrement clivante."],
    ["Que rejettent les Français par référendum en 2005 ?", ["Le traité établissant une Constitution pour l'Europe", "Le traité de Lisbonne", "L'élargissement à l'Est", "Le passage à l'euro"], 0,
     "Le traité de Lisbonne, en 2007, en reprendra l'essentiel par voie parlementaire."],
    ["Quand l'euro entre-t-il en circulation sous forme de pièces et billets ?", ["En janvier 2002", "En 1999", "En 2000", "En 2004"], 0,
     "Il existait comme monnaie scripturale depuis 1999."],
    ["Quelle institution européenne siège à Strasbourg ?", ["Le Parlement européen pour ses sessions plénières", "La Commission", "La Banque centrale européenne", "La Cour de justice"], 0,
     "Le Conseil de l'Europe, institution distincte, y siège également."],
    ["Quel rôle la France joue-t-elle dans le budget européen ?", ["Elle est contributrice nette mais première bénéficiaire des aides agricoles", "Elle est bénéficiaire nette", "Elle ne contribue pas", "Elle est le premier contributeur"], 0,
     "L'Allemagne est le premier contributeur net en volume.", 3],
  ]),

  notion("hf3-personnages-france", S, "Figures de l'histoire de France",
    "Femmes et hommes qui ont marqué le pays.",
    "L'histoire nationale a longtemps réduit la place des femmes à quelques figures exceptionnelles.",
    2, [
    ["Quelle reine de France fut aussi reine d'Angleterre au XIIe siècle ?", ["Aliénor d'Aquitaine", "Blanche de Castille", "Catherine de Médicis", "Anne de Bretagne"], 0,
     "Épouse de Louis VII puis d'Henri Plantagenêt, elle apporta l'Aquitaine à la couronne anglaise."],
    ["Quelle régente gouverne la France pendant la minorité de Louis IX ?", ["Blanche de Castille", "Anne de France", "Catherine de Médicis", "Marie de Médicis"], 0,
     "Elle assure aussi la régence pendant la croisade de son fils."],
    ["Quelle duchesse épouse successivement deux rois de France ?", ["Anne de Bretagne", "Claude de France", "Louise de Savoie", "Marguerite d'Autriche"], 0,
     "Charles VIII puis Louis XII, ce qui prépare le rattachement de la Bretagne."],
    ["Quelle femme dirige la France de fait pendant les guerres de religion ?", ["Catherine de Médicis", "Marguerite de Valois", "Diane de Poitiers", "Louise de Lorraine"], 0,
     "Régente puis conseillère de trois de ses fils successivement rois."],
    ["Quelle femme de lettres tient un salon influent au XVIIIe siècle ?", ["Madame Geoffrin", "Madame de Sévigné", "Madame de Staël seule", "Madame Roland"], 0,
     "Son salon accueillait encyclopédistes, artistes et voyageurs étrangers."],
    ["Quelle militante rédige en 1791 une Déclaration des droits de la femme ?", ["Olympe de Gouges", "Théroigne de Méricourt", "Madame Roland", "Charlotte Corday"], 0,
     "Elle sera guillotinée en 1793."],
    ["Quelle femme est la première à recevoir deux prix Nobel ?", ["Marie Curie", "Irène Joliot-Curie", "Bertha von Suttner", "Gerty Cori"], 0,
     "Physique en 1903 et chimie en 1911, une performance jamais renouvelée par une femme."],
    ["Quelle résistante est entrée au Panthéon en 2015 ?", ["Germaine Tillion", "Lucie Aubrac", "Danielle Casanova", "Berty Albrecht"], 0,
     "Elle y est entrée avec Geneviève de Gaulle-Anthonioz, Jean Zay et Pierre Brossolette."],
    ["Quelle artiste et résistante est entrée au Panthéon en 2021 ?", ["Joséphine Baker", "Édith Piaf", "Colette", "Simone Signoret"], 0,
     "Née américaine, elle avait été agent de renseignement pour la France libre."],
    ["Quelle femme politique française est entrée au Panthéon en 2018 ?", ["Simone Veil", "Louise Weiss", "Marie-Claude Vaillant-Couturier", "Yvette Roudy"], 0,
     "Rescapée d'Auschwitz, ministre de la Santé et présidente du Parlement européen.", 3],
  ]),

  notion("hf3-langue-etat-france", S, "L'État et la langue française",
    "Politique linguistique, unification, débats.",
    "L'unification linguistique de la France s'est achevée bien plus tard qu'on ne le croit souvent.",
    2, [
    ["Quelle part de la population française parlait français en 1789 selon l'enquête Grégoire ?", ["Une minorité, peut-être un quart", "La quasi-totalité", "Environ la moitié", "Environ trois quarts"], 0,
     "L'enquête, méthodologiquement fragile, reste la principale source sur cette question."],
    ["Qu'est-ce que le rapport Grégoire de 1794 ?", ["Un rapport préconisant l'éradication des patois", "Une défense des langues régionales", "Un inventaire linguistique neutre", "Un projet d'enseignement bilingue"], 0,
     "Son titre parle d'anéantir les patois et d'universaliser l'usage de la langue française."],
    ["Quel rôle l'école a-t-elle joué dans l'unification linguistique ?", ["Elle a imposé le français comme unique langue d'enseignement", "Elle a enseigné les langues régionales", "Elle a été neutre", "Elle a suivi l'usage local"], 0,
     "Le symbole, objet de honte transmis aux élèves surpris à parler patois, en fut un instrument."],
    ["Qu'est-ce que le service militaire a apporté à la diffusion du français ?", ["Un brassage national imposant une langue commune", "Une alphabétisation obligatoire", "Un enseignement des langues régionales", "Aucun effet"], 0,
     "La Première Guerre mondiale a accéléré ce brassage de façon décisive."],
    ["Quelle loi de 1994 encadre l'usage du français en France ?", ["La loi Toubon", "La loi Deixonne", "La loi Bas-Lauriol", "La loi Fioraso"], 0,
     "Elle vise la publicité, l'étiquetage, le travail et l'enseignement, avec des exceptions."],
    ["Pourquoi la France n'a-t-elle pas ratifié la Charte européenne des langues régionales ?", ["Un obstacle constitutionnel tiré de l'unicité de la langue de la République", "Un refus politique de principe", "Un désaccord sur le contenu", "Une opposition des régions"], 0,
     "Le Conseil constitutionnel a jugé certaines dispositions contraires à la Constitution en 1999."],
    ["Que dit la Constitution française sur les langues régionales depuis 2008 ?", ["Elles appartiennent au patrimoine de la France", "Elles sont langues officielles", "Elles peuvent être enseignées obligatoirement", "Elles ont valeur juridique"], 0,
     "L'article 75-1 leur donne une reconnaissance symbolique sans créer de droit opposable."],
    ["Qu'est-ce que la loi Molac de 2021 ?", ["Une loi sur la protection et la promotion des langues régionales", "Une loi sur l'enseignement bilingue seul", "Une loi sur la signalétique", "Une loi sur l'audiovisuel régional"], 0,
     "Le Conseil constitutionnel en a censuré la disposition sur l'enseignement immersif dans le public."],
    ["Qu'est-ce que la francophonie institutionnelle pour la France ?", ["Un instrument de politique culturelle et diplomatique", "Une organisation purement linguistique", "Une politique intérieure", "Un dispositif d'aide au développement"], 0,
     "Elle mêle coopération culturelle, éducative et enjeux d'influence."],
    ["Quel est aujourd'hui le rapport entre langue française et diversité linguistique en France ?", ["Une reconnaissance croissante mais un statut juridique limité pour les autres langues", "Une politique de bilinguisme généralisé", "Une interdiction des autres langues", "Une égalité juridique de toutes les langues"], 0,
     "Environ soixante-quinze langues sont parlées sur le territoire français selon un rapport de 1999.", 3],
  ]),

  notion("hf3-sciences-france", S, "Les sciences en France",
    "Institutions, découvertes, organisation de la recherche.",
    "La France a longtemps organisé sa recherche autour de grandes institutions publiques.",
    2, [
    ["Quelle académie scientifique est fondée en 1666 ?", ["l'Académie des sciences", "l'Académie française", "l'Académie de médecine", "l'Institut de France"], 0,
     "Colbert la crée pour organiser la recherche au service de l'État."],
    ["Quel organisme public de recherche est créé en 1939 ?", ["Le CNRS", "L'INSERM", "L'INRA", "Le CEA"], 0,
     "Il emploie aujourd'hui plus de trente mille personnes dans toutes les disciplines."],
    ["Quel organisme français est chargé de la recherche médicale ?", ["l'INSERM", "Le CNRS", "l'INRAE", "l'Institut Pasteur"], 0,
     "Créé en 1964, il succède à un institut national d'hygiène fondé en 1941."],
    ["Quel organisme est créé en 1945 pour l'énergie atomique ?", ["Le CEA", "l'IRSN", "l'ASN", "Le CNRS"], 0,
     "Frédéric Joliot-Curie en fut le premier haut-commissaire."],
    ["Quel institut français est spécialisé dans la recherche agronomique ?", ["l'INRAE", "Le CIRAD seul", "l'IRD", "Le CNRS"], 0,
     "Il est issu de la fusion de l'INRA et de l'IRSTEA en 2020."],
    ["Quel mathématicien français a donné son nom à un espace en analyse ?", ["Henri Lebesgue", "Évariste Galois", "Henri Poincaré", "Sophie Germain"], 0,
     "Son intégrale a refondé l'analyse au début du XXe siècle."],
    ["Quel mathématicien français meurt en duel à vingt ans en 1832 ?", ["Évariste Galois", "Niels Abel", "Augustin Cauchy", "Joseph Liouville"], 0,
     "Ses travaux sur la résolution des équations ont fondé la théorie des groupes."],
    ["Quel groupe de mathématiciens français publie sous un pseudonyme collectif ?", ["Nicolas Bourbaki", "Le groupe de Nancy", "Le collectif Poincaré", "L'école de Paris"], 0,
     "Fondé en 1935, il a entrepris une refondation axiomatique des mathématiques."],
    ["Quel prix scientifique français a récompensé de nombreux mathématiciens ?", ["La médaille Fields, souvent attribuée à des Français", "Le prix Nobel de mathématiques", "Le prix Abel français", "La médaille du CNRS seule"], 0,
     "La France est le deuxième pays par le nombre de médailles Fields, derrière les États-Unis."],
    ["Quel constat les rapports récents font-ils sur la recherche française ?", ["Un investissement inférieur à l'objectif européen de trois pour cent du PIB", "Un investissement supérieur à la moyenne", "Une absence de publications", "Une prédominance de la recherche privée"], 0,
     "L'écart concerne surtout la recherche privée, plus faible qu'en Allemagne ou en Corée du Sud.", 3],
  ]),

  notion("hf3-france-monde", S, "La France dans le monde",
    "Diplomatie, francophonie, présence internationale.",
    "La France dispose du troisième réseau diplomatique mondial.",
    2, [
    ["Quel rang la France occupe-t-elle par la taille de son réseau diplomatique ?", ["Troisième mondial", "Premier", "Dixième", "Cinquième"], 0,
     "Derrière la Chine et les États-Unis, avec environ cent soixante ambassades."],
    ["Quel siège permanent la France occupe-t-elle à l'ONU ?", ["Un siège permanent au Conseil de sécurité", "La présidence de l'Assemblée générale", "Un siège au Conseil économique et social", "Un siège tournant"], 0,
     "Elle y dispose d'un droit de veto, comme les quatre autres membres permanents."],
    ["Quand la France quitte-t-elle le commandement intégré de l'OTAN ?", ["En 1966", "En 1949", "En 1958", "En 1974"], 0,
     "Elle y est revenue en 2009, tout en restant hors du groupe des plans nucléaires."],
    ["Qu'est-ce que la force de dissuasion française ?", ["Un arsenal nucléaire autonome créé à partir des années 1960", "Une force conventionnelle d'intervention", "Une capacité de projection navale", "Un système de défense antimissile"], 0,
     "Le premier essai nucléaire français a lieu en 1960 au Sahara."],
    ["Quel discours français de 2003 s'oppose à l'intervention en Irak ?", ["Le discours de Dominique de Villepin à l'ONU", "Le discours de Chirac à Bruxelles", "Le discours de Mitterrand à New York", "Le discours de Juppé au Sénat"], 0,
     "Il a marqué une rupture publique avec la position américaine."],
    ["Qu'est-ce que le couple franco-allemand ?", ["Une coopération politique structurante pour l'Union européenne", "Une alliance militaire bilatérale", "Une union douanière", "Un accord culturel"], 0,
     "Le traité de l'Élysée, en 1963, en a posé les bases institutionnelles."],
    ["Quelle institution culturelle française est présente dans le monde entier ?", ["l'Institut français et le réseau des alliances", "Le CNRS", "Le Louvre uniquement", "La Bibliothèque nationale"], 0,
     "Les Alliances françaises sont des associations de droit local, distinctes du réseau d'État."],
    ["Quel réseau scolaire français existe à l'étranger ?", ["Le réseau de l'AEFE", "Les lycées internationaux", "Les écoles européennes", "Les instituts français"], 0,
     "Plus de cinq cents établissements dans plus de cent trente pays."],
    ["Quelle particularité la présence française outre-mer confère-t-elle ?", ["Une présence sur tous les océans et une zone maritime immense", "Un accès aux marchés asiatiques", "Une réserve de matières premières", "Une population supplémentaire importante"], 0,
     "La France est présente dans les trois grands océans, ce qui structure sa stratégie maritime."],
    ["Qu'est-ce que la Françafrique ?", ["Un ensemble de relations politiques et économiques étroites avec d'anciennes colonies africaines", "Une organisation officielle", "Un traité de coopération", "Une zone monétaire seule"], 0,
     "Le terme, souvent critique, désigne des réseaux d'influence longtemps informels.", 3],
  ]),

  notion("hf3-medias-france", S, "Les médias français dans l'histoire",
    "Presse, radio, télévision : contrôle et libération.",
    "L'information audiovisuelle française a été sous contrôle direct de l'État jusqu'aux années 1970.",
    2, [
    ["Quelle est la première quotidienne française à grand tirage au XIXe siècle ?", ["Le Petit Journal", "Le Figaro", "Le Temps", "La Presse"], 0,
     "Vendu un sou, il atteint le million d'exemplaires dans les années 1890."],
    ["Qu'est-ce que le bourrage de crâne pendant la Première Guerre mondiale ?", ["Une propagande de presse minimisant les difficultés du front", "Une censure militaire", "Un contrôle des correspondances", "Une interdiction de publication"], 0,
     "Le décalage avec la réalité vécue a durablement affaibli la confiance dans la presse."],
    ["Quelle radio émet depuis Londres pendant l'Occupation ?", ["La BBC, avec les émissions françaises", "Radio Paris", "Radio Vichy", "Radio Luxembourg"], 0,
     "Radio Paris était sous contrôle allemand, d'où le slogan des résistants sur ses mensonges."],
    ["Quel journal clandestin est diffusé sous l'Occupation ?", ["Combat, parmi de nombreux autres", "Le Figaro", "Le Temps", "Paris-Soir"], 0,
     "Des centaines de titres clandestins ont circulé, imprimés dans des conditions périlleuses."],
    ["Que se passe-t-il pour la presse française à la Libération ?", ["De nombreux titres sont interdits pour collaboration et remplacés", "Elle reprend inchangée", "Elle est nationalisée", "Elle est entièrement libéralisée"], 0,
     "Les ordonnances de 1944 réorganisent le secteur et créent l'Agence France-Presse."],
    ["Quand la publicité de marque est-elle autorisée à la télévision française ?", ["En 1968", "En 1959", "En 1974", "En 1982"], 0,
     "Son introduction fut très débattue, par crainte d'une influence des annonceurs."],
    ["Que se passe-t-il en 1981 pour la radio en France ?", ["La fin du monopole d'État et l'autorisation des radios locales", "La création de France Inter", "Le passage à la FM", "La privatisation d'Europe 1"], 0,
     "Des centaines de radios libres, jusque-là clandestines, sortent alors de l'illégalité."],
    ["Quelle première chaîne privée payante est créée en 1984 ?", ["Canal Plus", "La Cinq", "M6", "TF1"], 0,
     "Son modèle par abonnement et son financement du cinéma en ont fait un acteur singulier."],
    ["Qu'est-ce que la loi de 1986 sur l'audiovisuel ?", ["Un texte instaurant la liberté de communication et créant une autorité de régulation", "Une loi de privatisation", "Une loi sur la publicité", "Une loi sur les quotas de diffusion"], 0,
     "Elle crée la CNCL, remplacée par le CSA en 1989, puis par l'Arcom en 2022."],
    ["Quel constat les études font-elles sur la confiance des Français dans les médias ?", ["Un niveau de confiance durablement bas", "Une confiance en hausse continue", "Une confiance stable et élevée", "Une confiance identique à la moyenne européenne"], 0,
     "Le baromètre annuel publié depuis 1987 permet de suivre cette évolution.", 3],
  ]),

  notion("hf3-catastrophes-france", S, "Catastrophes et crises en France",
    "Événements majeurs et transformations qu'ils ont provoquées.",
    "Chaque grande catastrophe française a produit une réforme de la prévention.",
    2, [
    ["Quelle catastrophe minière survient à Courrières en 1906 ?", ["Une explosion faisant plus de mille morts", "Un effondrement de galerie", "Une inondation", "Un coup de grisou limité"], 0,
     "Elle a accéléré la création des services de secours miniers et la législation du travail."],
    ["Quelle rupture de barrage frappe le Var en 1959 ?", ["La rupture du barrage de Malpasset", "La rupture du barrage de Vouglans", "La rupture du barrage de Bort", "La rupture du barrage de Serre-Ponçon"], 0,
     "Plus de quatre cents morts. La catastrophe a transformé la réglementation des grands ouvrages."],
    ["Quelle marée noire touche la Bretagne en 1978 ?", ["Celle de l'Amoco Cadiz", "Celle du Torrey Canyon", "Celle de l'Erika", "Celle du Prestige"], 0,
     "Plus de deux cent mille tonnes de pétrole déversées, la plus grave marée noire française."],
    ["Quel naufrage pollue le littoral atlantique français en 1999 ?", ["Celui de l'Erika", "Celui de l'Amoco Cadiz", "Celui du Prestige", "Celui du Tanio"], 0,
     "Il a donné lieu à une jurisprudence importante sur le préjudice écologique."],
    ["Quelle explosion industrielle frappe Toulouse en 2001 ?", ["L'explosion de l'usine AZF", "Une explosion de raffinerie", "Un accident chimique à Blagnac", "Une explosion de dépôt de gaz"], 0,
     "Trente et un morts. Elle a conduit à réformer la prévention des risques technologiques."],
    ["Quelle tempête frappe la France en décembre 1999 ?", ["Les tempêtes Lothar et Martin", "La tempête Xynthia", "La tempête Klaus", "La tempête Ciara"], 0,
     "Environ quatre-vingt-dix morts et des dégâts forestiers considérables."],
    ["Quelle tempête provoque des submersions meurtrières en 2010 ?", ["Xynthia", "Klaus", "Lothar", "Ciara"], 0,
     "Elle a révélé l'urbanisation de zones basses littorales et conduit à revoir les plans de prévention."],
    ["Quelle catastrophe sanitaire frappe la France en 2003 ?", ["La canicule", "Une épidémie de grippe", "Une pollution atmosphérique majeure", "Une contamination alimentaire"], 0,
     "Environ quinze mille décès en excès, majoritairement des personnes âgées isolées."],
    ["Quel incendie ravage un monument parisien en avril 2019 ?", ["L'incendie de Notre-Dame de Paris", "L'incendie du Palais-Royal", "L'incendie de la Sorbonne", "L'incendie du Grand Palais"], 0,
     "La flèche de Viollet-le-Duc et la charpente médiévale ont été détruites."],
    ["Qu'est-ce que le régime français de catastrophe naturelle ?", ["Un mécanisme d'indemnisation reposant sur une garantie obligatoire et l'État", "Un fonds d'urgence public", "Une aide d'État exceptionnelle", "Un dispositif d'assurance volontaire"], 0,
     "Créé en 1982, il repose sur une surprime sur les contrats d'assurance dommages.", 3],
  ]),
];
