/**
 * Histoire de France, deuxième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Histoire de France";

export const CG_HISTOIRE_FRANCE_2: SeedSkill[] = [
  notion("hf2-gaule-romaine", S, "La Gaule romaine",
    "Cinq siècles de romanisation, des villes, des routes et une langue qui deviendra le français.",
    "La Gaule n'a pas été romanisée par la force mais par l'intérêt des élites locales à l'être.",
    2, [
    ["Quel chef gaulois affronte César à Alésia en 52 avant notre ère ?", ["Vercingétorix", "Ambiorix", "Brennus", "Dumnorix"], 0,
     "César décrit lui-même le siège dans La Guerre des Gaules, seule source détaillée de l'épisode."],
    ["Quelle ville devient la capitale des Gaules sous Auguste ?", ["Lugdunum, l'actuelle Lyon", "Lutèce", "Narbonne", "Reims"], 0,
     "Elle abritait le sanctuaire fédéral des Trois Gaules et un atelier monétaire impérial."],
    ["Quelle province romaine couvrait le sud de la Gaule dès le IIe siècle avant notre ère ?", ["La Narbonnaise", "L'Aquitaine", "La Lyonnaise", "La Belgique"], 0,
     "Conquise bien avant les campagnes de César, elle a donné son nom à la Provence."],
    ["Quel aqueduc romain enjambe le Gardon dans le sud de la France ?", ["Le pont du Gard", "Le pont d'Avignon", "L'aqueduc de Fréjus", "L'aqueduc de Lyon"], 0,
     "Quarante-neuf mètres de haut, sans mortier. Il alimentait Nîmes en eau depuis Uzès."],
    ["Quel amphithéâtre romain accueille encore aujourd'hui courses camarguaises et concerts, à Arles ?", ["Les arènes d'Arles", "Le cirque de Vienne", "La tour Magne de Nîmes", "Le mausolée de Glanum"], 0,
     "Vieilles de deux mille ans, elles ont aussi servi de village fortifié au Moyen Âge."],
    ["Quelle langue latine parlée en Gaule donne naissance au français ?", ["Le latin populaire", "Le latin classique", "Le gaulois latinisé", "Le francique"], 0,
     "Le gaulois s'est éteint entre le IIIe et le VIe siècle, laissant environ cent cinquante mots."],
    ["Quel empereur romain est né à Lugdunum ?", ["Claude", "Trajan", "Hadrien", "Auguste"], 0,
     "Il plaida au Sénat pour que les notables gaulois puissent y siéger, discours conservé sur une table de bronze."],
    ["Quelle crise frappe la Gaule au IIIe siècle ?", ["Invasions, insécurité et repli des villes derrière des murailles", "Une famine générale", "Une révolte des légions", "Une épidémie de peste"], 0,
     "Les villes se rétractent souvent à une fraction de leur surface antérieure."],
    ["Qui est le premier évêque de Paris selon la tradition ?", ["Saint Denis", "Saint Martin", "Saint Irénée", "Saint Rémi"], 0,
     "Martyrisé au IIIe siècle. La basilique de Saint-Denis s'élève sur le lieu supposé de sa sépulture."],
    ["Quel évêque de Tours devient une figure majeure de la christianisation des campagnes ?", ["Saint Martin", "Saint Denis", "Saint Hilaire", "Saint Germain"], 0,
     "Des milliers de communes françaises portent son nom, signe de la densité de son culte.", 3],
  ]),

  notion("hf2-carolingiens", S, "L'Empire carolingien",
    "De Pépin le Bref au partage de Verdun : un siècle d'unité impériale.",
    "Le partage de Verdun de 843 dessine les contours lointains de la France et de l'Allemagne.",
    2, [
    ["Qui dépose le dernier roi mérovingien en 751 ?", ["Pépin le Bref", "Charles Martel", "Charlemagne", "Carloman"], 0,
     "Il se fait sacrer, inaugurant un rituel qui légitime la dynastie par l'onction religieuse."],
    ["Quelle capitale Charlemagne se donne-t-il ?", ["Aix-la-Chapelle", "Paris", "Reims", "Metz"], 0,
     "Il y fit bâtir une chapelle palatine inspirée des modèles byzantins et ravennates."],
    ["Que sont les missi dominici ?", ["Des envoyés royaux chargés de contrôler les comtes", "Des officiers militaires commandant les troupes de l'empire", "Des collecteurs d'impôts levant le cens dans les comtés", "Des juges itinérants nommés par les évêques du royaume"], 0,
     "Ils allaient par deux, un laïc et un clerc, pour se surveiller mutuellement."],
    ["Qu'appelle-t-on la renaissance carolingienne ?", ["Un renouveau des écoles, des copies de manuscrits et de l'écriture", "La reconstruction des villes romaines abandonnées depuis le Ve siècle", "Le retour des arts antiques dans la peinture et la sculpture de cour", "Un renouveau du droit romain enseigné dans les écoles épiscopales"], 0,
     "La minuscule caroline, écriture claire mise au point alors, est l'ancêtre de nos caractères d'imprimerie."],
    ["Quelle bataille légendaire de 778 inspire la Chanson de Roland ?", ["Roncevaux", "Tolbiac, en 496", "Poitiers, en 732", "Fontenoy, en 841"], 0,
     "L'arrière-garde franque y fut détruite par des Basques, non par des Sarrasins comme le dit le poème."],
    ["Quel serment de 842 est le plus ancien texte en langue romane ?", ["Les Serments de Strasbourg", "Le capitulaire de Quierzy, en 877", "Le serment de Compiègne, en 833", "Le traité de Verdun, en 843"], 0,
     "Deux petits-fils de Charlemagne y jurent alliance contre leur frère, chacun dans la langue des troupes de l'autre."],
    ["Que décide le traité de Verdun en 843 ?", ["Le partage de l'Empire entre les trois fils de Louis le Pieux", "L'élection d'un empereur unique par l'assemblée des grands", "La cession de l'Italie au pape et à l'Église de Rome", "L'alliance de l'empire franc avec Byzance contre les Arabes"], 0,
     "Francie occidentale, Francie orientale et Lotharingie centrale, celle-ci sans cohérence durable."],
    ["Quel capitulaire de 877 rend les charges comtales héréditaires en pratique ?", ["Le capitulaire de Quierzy", "Le capitulaire de Villis", "Le capitulaire de Herstal", "L'ordonnance de Compiègne"], 0,
     "Il marque une étape vers la féodalité en affaiblissant durablement le contrôle royal."],
    ["Quelle menace extérieure déstabilise l'Empire carolingien au IXe siècle ?", ["Les incursions vikings, sarrasines et hongroises", "L'Empire byzantin et sa flotte de Méditerranée", "Les Slaves de l'Est établis au-delà de l'Elbe", "Les Bulgares du Danube et leurs cavaliers"], 0,
     "L'incapacité du pouvoir central à protéger les populations renforce les seigneurs locaux.", 3],
  ]),

  notion("hf2-capetiens", S, "Les premiers Capétiens",
    "De Hugues Capet à Philippe le Bel : la lente construction du domaine royal et de l'État.",
    "Les premiers Capétiens ne contrôlaient qu'un petit territoire autour de Paris et Orléans.",
    2, [
    ["Quelle pratique assure la continuité de la dynastie capétienne ?", ["Le sacre du fils aîné du vivant du père", "L'élection du roi par les grands à chaque décès", "Le partage du royaume entre tous les fils", "La désignation du successeur par le pape"], 0,
     "Abandonnée quand l'hérédité fut devenue une évidence, sous Philippe Auguste."],
    ["Où les rois de France étaient-ils sacrés ?", ["À Reims", "À Paris", "À Saint-Denis", "À Chartres"], 0,
     "La tradition remonte au baptême de Clovis, situé dans cette ville par la légende."],
    ["Quel roi capétien allonge considérablement le domaine royal au XIIe siècle ?", ["Philippe Auguste", "Louis VI le Gros", "Louis VII le Jeune", "Robert le Pieux"], 0,
     "Il quadruple le domaine, notamment en confisquant les fiefs continentaux du roi d'Angleterre."],
    ["Quelle bataille de 1214 consolide le pouvoir de Philippe Auguste ?", ["Bouvines", "Azincourt", "Crécy", "Poitiers"], 0,
     "La victoire sur une coalition impériale et anglaise a été célébrée comme un succès national avant l'heure."],
    ["Quelle institution Philippe Auguste met-il en place pour administrer le royaume ?", ["Les baillis et sénéchaux", "Les intendants", "Les gouverneurs de province", "Les états généraux"], 0,
     "Fonctionnaires rémunérés et révocables, ils échappent à l'hérédité féodale."],
    ["Quel roi de France est canonisé en 1297 ?", ["Louis IX", "Philippe Auguste", "Robert le Pieux", "Louis VII"], 0,
     "Il rendait la justice sous un chêne selon la tradition, et acquit la couronne d'épines pour la Sainte-Chapelle."],
    ["Quel édifice Louis IX fait-il construire pour abriter des reliques ?", ["La Sainte-Chapelle", "Notre-Dame de Paris", "L'abbaye de Saint-Denis", "La cathédrale de Chartres"], 0,
     "Les reliques coûtèrent plus cher que le bâtiment lui-même."],
    ["Quel conflit oppose Philippe le Bel au pape Boniface VIII ?", ["Un conflit sur la taxation du clergé et la primauté du pouvoir", "Une querelle sur la nomination des évêques du royaume de France", "Un désaccord sur le financement d'une nouvelle croisade en Orient", "Un litige territorial portant sur les possessions pontificales d'Italie"], 0,
     "Il aboutit à l'installation de la papauté à Avignon en 1309."],
    ["Quel ordre Philippe le Bel fait-il supprimer en 1312 ?", ["L'ordre du Temple", "L'ordre de Saint-Jean", "L'ordre de Cluny", "L'ordre teutonique"], 0,
     "Les Templiers étaient ses créanciers. Le grand maître Jacques de Molay est brûlé en 1314.", 3],
  ]),

  notion("hf2-guerre-cent-ans", S, "La guerre de Cent Ans",
    "Cent seize ans de conflit intermittent entre deux dynasties pour la couronne de France.",
    "La guerre de Cent Ans est une succession de campagnes séparées par de longues trêves.",
    2, [
    ["Quelle question déclenche la guerre de Cent Ans en 1337 ?", ["La succession au trône de France", "Le contrôle de la Flandre seul", "Un litige commercial sur la laine", "Une querelle religieuse"], 0,
     "Édouard III d'Angleterre, petit-fils de Philippe le Bel par sa mère, revendique la couronne."],
    ["Quelle règle écarte les femmes de la succession au trône de France ?", ["L'invocation de la loi salique", "La coutume de Paris", "L'ordonnance de Moulins", "Le droit d'aînesse"], 0,
     "Ce texte franc, sans rapport initial avec la royauté, fut exhumé pour justifier l'exclusion."],
    ["Quelle bataille de 1346 révèle la supériorité de l'archerie anglaise ?", ["Crécy", "Azincourt", "Poitiers", "Formigny"], 0,
     "L'arc long anglais y décime la chevalerie française avant tout corps à corps."],
    ["Quel roi de France est fait prisonnier à Poitiers en 1356 ?", ["Jean II le Bon", "Philippe VI", "Charles V", "Charles VI"], 0,
     "Sa rançon, énorme, pesa lourd sur les finances du royaume."],
    ["Quelle révolte paysanne éclate en 1358 ?", ["La Jacquerie", "La révolte des Maillotins", "La Grande Jacquerie de Bourgogne", "La révolte des Tuchins"], 0,
     "Le mot vient de Jacques Bonhomme, sobriquet donné aux paysans."],
    ["Quel roi français surnommé le Sage redresse la situation dans les années 1360 ?", ["Charles V", "Charles VI", "Jean II", "Philippe VI"], 0,
     "Avec du Guesclin, il évite les batailles rangées et reprend les places une à une."],
    ["Quelle bataille de 1415 est un désastre pour la chevalerie française ?", ["Azincourt", "Crécy", "Patay", "Castillon"], 0,
     "Un terrain boueux et des lignes trop serrées y annulèrent l'avantage numérique français."],
    ["Quel traité de 1420 déshérite le dauphin au profit du roi d'Angleterre ?", ["Le traité de Troyes", "Le traité de Brétigny", "Le traité d'Arras", "Le traité de Picquigny"], 0,
     "Signé par Isabeau de Bavière au nom d'un Charles VI atteint de crises de démence."],
  ]),

  notion("hf2-renaissance-francaise", S, "La Renaissance française",
    "Guerres d'Italie, châteaux de la Loire, humanisme : la France du XVIe siècle.",
    "Les guerres d'Italie ont surtout servi à importer en France un art et un mode de vie.",
    2, [
    ["Quel roi engage les guerres d'Italie en 1494 ?", ["Charles VIII", "Louis XII", "François Ier", "Henri II"], 0,
     "Il revendiquait le royaume de Naples au titre d'un héritage angevin."],
    ["Quelle bataille de 1525 se solde par la capture de François Ier ?", ["Pavie", "Marignan", "Saint-Quentin", "Cérisoles"], 0,
     "Il aurait écrit que tout était perdu fors l'honneur, formule apocryphe mais tenace."],
    ["Quel artiste italien meurt en France en 1519 sous la protection de François Ier ?", ["Léonard de Vinci", "Michel-Ange", "Raphaël", "Le Primatice"], 0,
     "Il avait apporté avec lui plusieurs tableaux, dont la Joconde, d'où sa présence au Louvre."],
    ["Quel château de la Loire est associé à François Ier et à son escalier à double révolution ?", ["Chambord", "Chenonceau", "Amboise", "Blois"], 0,
     "Quatre cent vingt-six pièces. Le roi n'y séjourna que quelques semaines au total."],
    ["Quelle ordonnance de 1539 impose le français dans les actes officiels ?", ["L'ordonnance de Villers-Cotterêts", "L'édit de Fontainebleau", "L'ordonnance de Blois", "L'édit de Moulins"], 0,
     "Elle impose aussi la tenue des registres de baptême, ancêtre de l'état civil."],
    ["Quel collège François Ier fonde-t-il en 1530 pour enseigner hors de l'université ?", ["Le Collège royal, futur Collège de France", "La Sorbonne", "Le collège de Navarre", "L'Académie française"], 0,
     "Il y fait enseigner l'hébreu et le grec, disciplines négligées par la Sorbonne ; le latin et les mathématiques s'y ajoutent peu après."],
    ["Quel médecin et écrivain publie Gargantua et Pantagruel ?", ["François Rabelais", "Michel de Montaigne", "Clément Marot", "Étienne Dolet"], 0,
     "Ses livres furent condamnés par la Sorbonne, ce qui ne les empêcha pas de circuler largement."],
    ["Quel penseur invente la forme de l'essai en 1580 ?", ["Michel de Montaigne", "François Rabelais", "Étienne de La Boétie", "Jean Bodin"], 0,
     "Son ami La Boétie avait écrit le Discours de la servitude volontaire, publié après sa mort."],
    ["Quel imprimeur humaniste est brûlé à Paris en 1546 pour hérésie ?", ["Étienne Dolet", "Robert Estienne", "Antoine Vérard", "Josse Bade"], 0,
     "L'imprimerie était sous étroite surveillance : diffuser une idée valait alors autant que la soutenir.", 3],
  ]),

  notion("hf2-henri-iv-richelieu", S, "Henri IV et Richelieu",
    "Sortie des guerres de religion et construction de l'État moderne.",
    "Richelieu ne combat pas le protestantisme comme religion mais comme puissance politique armée.",
    2, [
    ["Quelle formule est attribuée à Henri IV lors de sa conversion ?", ["Paris vaut bien une messe", "L'État c'est moi", "Le roi règne et ne gouverne pas", "Un roi, une foi, une loi"], 0,
     "La phrase n'est attestée que bien après sa mort, mais résume fidèlement son calcul politique."],
    ["Quel ministre d'Henri IV redresse les finances du royaume ?", ["Sully", "Colbert", "Richelieu", "Mazarin"], 0,
     "Il aurait dit que labourage et pâturage étaient les deux mamelles de la France."],
    ["Comment Henri IV meurt-il en 1610 ?", ["Assassiné par Ravaillac", "De maladie", "À la guerre", "Empoisonné"], 0,
     "Rue de la Ferronnerie à Paris, alors qu'il préparait une intervention militaire en Europe."],
    ["Quel siège Richelieu conduit-il contre les protestants en 1627-1628 ?", ["La Rochelle", "Montauban", "Nîmes", "Privas"], 0,
     "Une digue coupa la ville de la mer. Les protestants gardent leur culte mais perdent leurs places fortes."],
    ["Quel édit de 1629 retire aux protestants leurs places de sûreté ?", ["La paix d'Alès", "L'édit de Nantes", "L'édit de Fontainebleau", "L'édit de Grâce de Montpellier"], 0,
     "La liberté de culte est maintenue : c'est le pouvoir militaire protestant qui est visé."],
    ["Quel journal Richelieu fait-il créer en 1631 pour orienter l'opinion ?", ["La Gazette", "Le Mercure galant", "Le Journal des savants", "Les Nouvelles ordinaires"], 0,
     "Théophraste Renaudot en est le rédacteur ; le cardinal et le roi y écrivaient parfois eux-mêmes."],
    ["Quelle politique extérieure Richelieu mène-t-il pendant la guerre de Trente Ans ?", ["Il soutient les princes protestants contre les Habsbourg", "Il défend l'unité catholique", "Il reste neutre", "Il s'allie à l'Espagne"], 0,
     "La raison d'État prime sur la solidarité religieuse : affaiblir les Habsbourg passe avant tout."],
    ["Que sont les intendants mis en place au XVIIe siècle ?", ["Des commissaires royaux administrant les provinces", "Des gouverneurs héréditaires", "Des juges d'appel", "Des receveurs d'impôts locaux"], 0,
     "Révocables et étrangers à la province qu'ils administrent, ils contournent les pouvoirs locaux."],
    ["Quelle révolte secoue la France entre 1648 et 1653 ?", ["La Fronde", "La révolte des Croquants", "La guerre des Camisards", "La révolte du papier timbré"], 0,
     "Parlementaire puis nobiliaire, elle marqua durablement Louis XIV, alors enfant."],
    ["Quel cardinal gouverne la France pendant la minorité de Louis XIV ?", ["Mazarin", "Richelieu", "Fleury", "Dubois"], 0,
     "D'origine italienne, il forma le jeune roi et négocia le traité des Pyrénées en 1659.", 3],
  ]),

  notion("hf2-louis-xiv", S, "Le règne de Louis XIV",
    "Soixante-douze ans de règne, la monarchie absolue à son apogée et ses limites.",
    "Le règne personnel de Louis XIV commence en 1661, à la mort de Mazarin.",
    2, [
    ["En quelle année Louis XIV commence-t-il son règne personnel ?", ["1661", "1643", "1682", "1715"], 0,
     "Il avait vingt-deux ans et décida de ne pas nommer de premier ministre."],
    ["Quel ministre organise le mercantilisme français sous Louis XIV ?", ["Colbert", "Louvois", "Vauban", "Le Tellier"], 0,
     "Manufactures royales, compagnies de commerce et protectionnisme douanier en sont les instruments."],
    ["Quel ingénieur fortifie les frontières du royaume sous Louis XIV ?", ["Vauban", "Colbert", "Louvois", "Turenne"], 0,
     "Une douzaine de ses places fortes sont inscrites au patrimoine mondial."],
    ["En quelle année la cour s'installe-t-elle définitivement à Versailles ?", ["1682", "1661", "1715", "1670"], 0,
     "Le château devient à la fois résidence, siège du gouvernement et instrument de contrôle de la noblesse."],
    ["Quelle affaire empoisonne la cour dans les années 1670 ?", ["L'affaire des Poisons", "L'affaire du collier", "L'affaire Fouquet", "L'affaire des placards"], 0,
     "Elle mit en cause plusieurs proches du roi, dont Madame de Montespan."],
    ["Quel surintendant est arrêté en 1661 après une fête trop somptueuse ?", ["Nicolas Fouquet", "Jean-Baptiste Colbert", "Michel Le Tellier", "Hugues de Lionne"], 0,
     "Vaux-le-Vicomte, sa demeure, servit de modèle à Versailles ; ses artistes furent repris par le roi."],
    ["Quelle guerre européenne occupe la fin du règne de Louis XIV ?", ["La guerre de Succession d'Espagne", "La guerre de Hollande", "La guerre de Dévolution", "La guerre de Sept Ans"], 0,
     "Elle s'achève par les traités d'Utrecht en 1713, au prix d'une France épuisée."],
    ["Quelle révolte protestante éclate dans les Cévennes après 1685 ?", ["La guerre des Camisards", "La Fronde", "La révolte des Croquants", "La révolte du papier timbré"], 0,
     "Une guérilla de paysans protestants tint tête aux troupes royales pendant plusieurs années."],
    ["Quel dramaturge est protégé par Louis XIV malgré les attaques des dévots ?", ["Molière", "Racine", "Corneille", "Boileau"], 0,
     "Tartuffe fut interdit cinq ans avant d'être autorisé sous une forme remaniée."],
    ["Quelle conséquence financière le règne de Louis XIV laisse-t-il ?", ["Une dette considérable et un système fiscal inéquitable", "Un budget en excédent", "Une monnaie stable et forte", "Une administration sans dette"], 0,
     "Les privilégiés échappaient à l'essentiel de l'impôt, question qui restera irrésolue jusqu'en 1789.", 3],
  ]),

  notion("hf2-lumieres-france", S, "La France des Lumières",
    "Un siècle de critique, de sciences et de sociabilité intellectuelle avant la Révolution.",
    "L'Encyclopédie fut un projet commercial autant qu'intellectuel, vendu par souscription.",
    2, [
    ["Quel procédé Montesquieu emploie-t-il dans les Lettres persanes en 1721 ?", ["Le regard d'étrangers fictifs sur la société française", "Le dialogue philosophique entre un maître et son élève", "La fable animalière à la manière de La Fontaine", "Le récit d'un voyage authentique en Orient"], 0,
     "Le décentrement du regard permet de critiquer les mœurs françaises en feignant l'étonnement naïf."],
    ["Quel conte philosophique de Voltaire paraît en 1759 ?", ["Candide", "Zadig", "Micromégas", "L'Ingénu"], 0,
     "Il y raille l'optimisme leibnizien après le tremblement de terre de Lisbonne."],
    ["Quelle affaire judiciaire Voltaire fait-il réviser en 1765 ?", ["L'affaire Calas", "L'affaire du chevalier de La Barre", "L'affaire Sirven", "L'affaire Lally"], 0,
     "Un protestant exécuté sur des présomptions ; sa réhabilitation posthume marqua l'opinion européenne."],
    ["Quel auteur dramatique fait jouer Le Mariage de Figaro en 1784, après des années de censure ?", ["Beaumarchais", "Marivaux", "Diderot", "Voltaire"], 0,
     "La pièce met en scène un valet plus rusé que son maître ; Louis XVI lui-même en redoutait la portée subversive."],
    ["Que sont les salons au XVIIIe siècle ?", ["Des réunions régulières chez des particuliers, souvent tenues par des femmes", "Des académies officielles fondées par lettres patentes du roi de France", "Des cafés littéraires ouverts au public dans les quartiers de Paris", "Des sociétés savantes provinciales réunissant notables et érudits locaux"], 0,
     "Madame Geoffrin, Madame du Deffand et Julie de Lespinasse comptent parmi les plus influentes."],
    ["Quel chimiste français fonde la chimie moderne avant d'être guillotiné en 1794 ?", ["Antoine Lavoisier", "Claude Berthollet", "Guyton de Morveau", "Fourcroy"], 0,
     "Fermier général, il fut exécuté pour cette fonction fiscale et non pour ses travaux."],
    ["Quel naturaliste dirige le Jardin du roi et écrit une Histoire naturelle monumentale ?", ["Buffon", "Lamarck", "Jussieu", "Daubenton"], 0,
     "Trente-six volumes parus de son vivant, lus dans toute l'Europe."],
    ["Quelle invention des frères Montgolfier marque l'année 1783 ?", ["Le ballon à air chaud", "Le paratonnerre", "La machine à vapeur", "Le télégraphe optique"], 0,
     "Le premier vol habité eut lieu quelques mois plus tard au-dessus de Paris."],
    ["Quel système de télégraphe optique est mis en service en France en 1794 ?", ["Le télégraphe de Chappe", "Le sémaphore de Popham", "Le télégraphe électrique", "Le code des tours"], 0,
     "Un réseau de tours à bras articulés transmettait un message de Paris à Lille en une heure.", 3],
  ]),

  notion("hf2-revolution-1789", S, "1789 et la fin de l'Ancien Régime",
    "Les états généraux, la nuit du 4 août, la Déclaration : six mois qui changent tout.",
    "La Révolution commence par une crise financière que la monarchie ne parvient pas à résoudre.",
    2, [
    ["Pourquoi Louis XVI convoque-t-il les états généraux en 1789 ?", ["Pour résoudre une crise financière", "Pour réformer l'armée", "Pour répondre à une révolte paysanne", "Pour préparer une guerre"], 0,
     "Ils n'avaient plus été réunis depuis 1614."],
    ["Que sont les cahiers de doléances ?", ["Des recueils de plaintes et de vœux rédigés dans tout le royaume", "Des registres fiscaux tenus par les intendants des généralités du royaume", "Des pétitions rédigées par les seuls districts parisiens", "Des rapports d'intendants adressés au contrôleur général"], 0,
     "Des dizaines de milliers ont été conservés : ils forment une source unique sur la société d'alors."],
    ["Que se passe-t-il le 20 juin 1789 dans une salle de jeu de paume ?", ["Les députés jurent de ne pas se séparer avant d'avoir donné une constitution", "Le roi dissout l'assemblée des états généraux et fait fermer la salle", "La Bastille est prise par la foule des faubourgs parisiens en armes", "Les privilèges de la noblesse et du clergé sont abolis dans la nuit"], 0,
     "Trouvant leur salle fermée, les députés du tiers état se replient dans une salle voisine."],
    ["Que symbolise la prise de la Bastille le 14 juillet 1789 ?", ["La chute de l'arbitraire royal", "La fin de la monarchie", "La victoire militaire du peuple", "La libération de nombreux prisonniers"], 0,
     "Sept prisonniers seulement s'y trouvaient. La forteresse valait comme symbole, non comme prison."],
    ["Que décide l'Assemblée dans la nuit du 4 août 1789 ?", ["L'abolition des privilèges", "La condamnation du roi", "La création des départements", "La vente des biens du clergé"], 0,
     "Le rachat de certains droits fut d'abord prévu, avant leur suppression pure et simple en 1793."],
    ["Quel texte est adopté le 26 août 1789 ?", ["La Déclaration des droits de l'homme et du citoyen", "La Constitution civile du clergé, votée en juillet", "La Constitution de 1791, instaurant la monarchie", "Le décret sur la vente des biens nationaux"], 0,
     "Dix-sept articles, placés en préambule de la Constitution de 1791."],
    ["Que sont les biens nationaux ?", ["Les biens du clergé puis des émigrés, vendus par l'État", "Les propriétés personnelles de la famille royale à Versailles", "Les terres communales des villages, partagées entre habitants", "Les biens des corporations de métiers supprimées en 1791"], 0,
     "Leur vente servit à gager les assignats et créa une nouvelle catégorie de propriétaires attachés au nouvel ordre."],
    ["Qu'est-ce que l'assignat ?", ["Un papier-monnaie gagé sur les biens nationaux", "Un emprunt d'État lancé auprès des banquiers", "Une obligation royale émise avant 1789", "Une monnaie métallique frappée par la Convention"], 0,
     "Émis en quantité croissante, il s'effondra, provoquant une inflation majeure."],
    ["Quelle réorganisation territoriale intervient en 1790 ?", ["La création des départements", "La création des régions administratives", "La suppression pure et simple des communes", "La refonte des paroisses en cantons"], 0,
     "Quatre-vingt-trois départements, dessinés pour qu'on puisse atteindre le chef-lieu en une journée de cheval."],
    ["Que provoque la Constitution civile du clergé en 1790 ?", ["Une division durable entre prêtres jureurs et réfractaires", "La suppression complète du culte catholique dans tout le royaume", "L'expulsion de tous les évêques hors du royaume", "La nationalisation des églises paroissiales de campagne"], 0,
     "Elle est l'une des principales causes de la contre-révolution, notamment en Vendée.", 3],
  ]),

  notion("hf2-terreur-directoire", S, "De la Terreur au Directoire",
    "1792-1799 : république, guerre, Terreur et recherche d'un ordre stable.",
    "La Terreur est un régime d'exception assumé comme tel, pas un simple débordement.",
    2, [
    ["Quand la République est-elle proclamée en France ?", ["Le 22 septembre 1792", "Le 14 juillet 1789, à la Bastille", "Le 10 août 1792, aux Tuileries", "Le 21 janvier 1793, place de la Révolution"], 0,
     "Au lendemain de la victoire de Valmy, qui rassure sur la capacité militaire du nouveau régime."],
    ["Quelle bataille de septembre 1792 arrête l'invasion prussienne ?", ["Valmy", "Jemappes", "Fleurus", "Wattignies"], 0,
     "Une canonnade plus qu'une bataille rangée, mais l'armée révolutionnaire tient et l'ennemi recule."],
    ["Quand Louis XVI est-il exécuté ?", ["Le 21 janvier 1793", "Le 10 août 1792", "Le 22 septembre 1792", "Le 2 juin 1793"], 0,
     "Condamné par la Convention à une courte majorité sur la question de la peine."],
    ["Quel comité dirige la France pendant la Terreur ?", ["Le Comité de salut public", "Le Comité de sûreté générale seul", "Le Directoire", "Le Conseil des Cinq-Cents"], 0,
     "Composé de douze membres renouvelés mensuellement, il concentre l'essentiel du pouvoir exécutif."],
    ["Quelle région se soulève contre la Convention en 1793 ?", ["La Vendée", "La Bretagne seule", "La Provence", "L'Alsace"], 0,
     "Conscription, question religieuse et rejet du pouvoir parisien s'y combinent."],
    ["Que sont les colonnes infernales de 1794 ?", ["Des colonnes militaires menant une répression systématique en Vendée", "Des unités d'artillerie de siège employées devant Toulon", "Des convois de ravitaillement escortés vers les armées du Nord", "Des tribunaux itinérants jugeant les suspects de province en province"], 0,
     "La qualification de leurs opérations reste l'objet de débats historiographiques vifs."],
    ["Quel calendrier est adopté en 1793 ?", ["Le calendrier républicain", "Le calendrier grégorien réformé", "Le calendrier décimal romain", "Le calendrier civil de l'an I"], 0,
     "Douze mois de trente jours aux noms saisonniers, semaines de dix jours. Abandonné en 1806."],
    ["Quel événement met fin à la Terreur en juillet 1794 ?", ["La chute de Robespierre au 9 thermidor", "La mort de Danton, guillotiné en germinal", "La prise des Tuileries par les sections", "Le coup d'État du 18 brumaire an VIII"], 0,
     "Il est exécuté le lendemain avec une vingtaine de ses partisans."],
    ["Quel régime gouverne la France de 1795 à 1799 ?", ["Le Directoire", "Le Consulat", "La Convention", "Le Comité de salut public"], 0,
     "Cinq directeurs et deux conseils, un système instable ponctué de coups d'État successifs."],
    ["Quelle innovation militaire la Révolution introduit-elle durablement ?", ["La conscription de masse", "L'artillerie à cheval", "Le fusil à percussion", "La ligne de bataille en colonnes"], 0,
     "La levée en masse de 1793 met sur pied des armées d'une taille inédite en Europe.", 3],
  ]),

  notion("hf2-napoleon", S, "Napoléon Bonaparte",
    "Du Consulat à Waterloo : quinze ans qui refondent l'État français et bouleversent l'Europe.",
    "L'essentiel des institutions administratives françaises actuelles date du Consulat.",
    2, [
    ["Quel coup d'État porte Bonaparte au pouvoir en 1799 ?", ["Le 18 brumaire", "Le 9 thermidor", "Le 13 vendémiaire", "Le 18 fructidor"], 0,
     "Il met fin au Directoire et instaure le Consulat, avec Bonaparte comme premier consul."],
    ["Quel code civil est promulgué en 1804 ?", ["Le Code civil des Français", "Le Code pénal", "Le Code de commerce", "Le Code de procédure civile"], 0,
     "Il a servi de modèle à des dizaines de pays et reste en vigueur, largement modifié."],
    ["Quelle institution financière est créée en 1800 ?", ["La Banque de France", "La Caisse des dépôts", "Le Crédit foncier", "La Caisse d'amortissement"], 0,
     "Elle reçoit le monopole d'émission des billets à Paris en 1803."],
    ["Quelle distinction Napoléon crée-t-il en 1802 ?", ["La Légion d'honneur", "L'ordre du Mérite", "La médaille militaire", "L'ordre de la Réunion"], 0,
     "Première décoration ouverte à tous, militaires comme civils, sans condition de naissance."],
    ["Quel accord de 1801 régit les rapports entre la France et l'Église catholique ?", ["Le Concordat", "L'édit de tolérance", "La Constitution civile du clergé", "Les articles organiques seuls"], 0,
     "Il reste en vigueur en Alsace-Moselle, alors allemande lors de la loi de séparation de 1905."],
    ["Quelle bataille de 1805 est considérée comme le chef-d'œuvre tactique de Napoléon ?", ["Austerlitz", "Iéna", "Wagram", "Friedland"], 0,
     "Il y attire l'ennemi sur une aile volontairement affaiblie avant de percer le centre."],
    ["Quelle défaite navale de 1805 ruine les projets d'invasion de l'Angleterre ?", ["Trafalgar", "Aboukir", "Copenhague", "La Hougue"], 0,
     "Nelson y meurt, mais la maîtrise britannique des mers est acquise pour un siècle."],
    ["Qu'est-ce que le blocus continental ?", ["L'interdiction du commerce avec la Grande-Bretagne imposée à l'Europe", "Le blocus des ports français", "Un embargo sur les grains", "Une union douanière européenne"], 0,
     "Il désorganisa aussi les économies continentales et poussa la Russie à s'en affranchir."],
    ["Quelle campagne de 1812 marque le tournant de l'Empire ?", ["La campagne de Russie", "La campagne d'Espagne", "La campagne d'Allemagne", "La campagne d'Autriche"], 0,
     "Sur environ six cent mille hommes engagés, une faible fraction revint."],
    ["Où Napoléon meurt-il en 1821 ?", ["À Sainte-Hélène", "À l'île d'Elbe", "En Corse", "À Vienne"], 0,
     "Après six ans d'exil sous surveillance britannique. Ses cendres sont ramenées à Paris en 1840.", 3],
  ]),

  notion("hf2-restauration-monarchie-juillet", S, "Restauration et monarchie de Juillet",
    "1815-1848 : deux monarchies constitutionnelles et une société qui se transforme.",
    "La Restauration ne rétablit pas l'Ancien Régime : elle instaure un régime parlementaire censitaire.",
    2, [
    ["Quel texte fonde le régime de la Restauration en 1814 ?", ["La Charte constitutionnelle", "La Constitution de l'an VIII", "La Charte de 1830", "Le Sénatus-consulte"], 0,
     "Octroyée par le roi, elle maintient nombre d'acquis révolutionnaires, dont l'égalité devant la loi."],
    ["Qu'est-ce que le suffrage censitaire ?", ["Un droit de vote réservé à ceux qui paient un certain montant d'impôts", "Un vote réservé aux nobles", "Un vote par corporations", "Un vote indirect par collèges"], 0,
     "Sous la Restauration, environ cent mille électeurs sur trente millions d'habitants."],
    ["Quelle révolution de juillet 1830 renverse Charles X ?", ["Les Trois Glorieuses", "La révolution de Février", "Les journées de Juin", "La révolte des Canuts"], 0,
     "Trois journées d'insurrection parisienne à la suite d'ordonnances restreignant la presse et le suffrage."],
    ["Quel roi accède au trône en 1830 ?", ["Louis-Philippe", "Charles X", "Louis XVIII", "Napoléon III"], 0,
     "Duc d'Orléans, il devient roi des Français et non roi de France, formule qui marque l'origine du pouvoir."],
    ["Quelle révolte ouvrière éclate à Lyon en 1831 ?", ["La révolte des Canuts", "La révolte des Camisards", "La grève des mineurs", "L'insurrection des Ateliers"], 0,
     "Les ouvriers de la soie réclamaient un tarif minimum garanti. Leur devise : vivre en travaillant ou mourir en combattant."],
    ["Quelle loi de 1833 organise l'enseignement primaire en France ?", ["La loi Guizot", "La loi Falloux", "Les lois Ferry", "La loi Duruy"], 0,
     "Elle impose une école de garçons par commune, sans gratuité ni obligation."],
    ["Quelle conquête coloniale commence en 1830 ?", ["Celle de l'Algérie", "Celle du Sénégal", "Celle de l'Indochine", "Celle de la Tunisie"], 0,
     "Elle durera des décennies et sera marquée par des campagnes de destruction systématique."],
    ["Quel roman de Victor Hugo, publié en 1831, s'inspire de la cathédrale médiévale de Paris ?", ["Notre-Dame de Paris", "Les Misérables", "Le Dernier Jour d'un condamné", "Les Contemplations"], 0,
     "Son succès contribue à relancer l'intérêt pour le patrimoine gothique, alors menacé par l'abandon et les démolitions."],
    ["Quelle crise économique et politique précipite la chute de Louis-Philippe ?", ["La crise de 1846-1847 et l'interdiction des banquets réformistes", "Une défaite militaire", "Une révolte coloniale", "Un conflit avec l'Église"], 0,
     "L'interdiction du banquet du 22 février 1848 déclenche l'insurrection."],
    ["Quel ouvrage d'Alexis de Tocqueville paraît en 1835 ?", ["De la démocratie en Amérique", "L'Ancien Régime et la Révolution", "Souvenirs", "Le Rapport sur l'Algérie"], 0,
     "Il y analyse l'égalisation des conditions comme un mouvement irrésistible et ambigu.", 3],
  ]),

  notion("hf2-second-empire", S, "La Deuxième République et le Second Empire",
    "1848-1870 : suffrage universel masculin, coup d'État, modernisation et défaite.",
    "Une conquête de 1848 n'a plus jamais été reprise, pas même par les régimes autoritaires qui ont suivi.",
    2, [
    ["Quelle avancée majeure la Deuxième République instaure-t-elle en 1848 ?", ["Le suffrage universel masculin", "Le vote des femmes aux élections", "Le droit de grève pour les ouvriers", "La liberté syndicale et d'association"], 0,
     "Le corps électoral passe de deux cent cinquante mille à plus de neuf millions d'électeurs."],
    ["Quel décret de 1848 abolit définitivement l'esclavage dans les colonies françaises ?", ["Le décret porté par Victor Schœlcher", "Le décret voté par la Convention en 1794", "L'édit signé par Louis-Philippe en 1840", "La loi Mackau sur le sort des esclaves"], 0,
     "L'abolition de 1794 avait été annulée par Bonaparte en 1802."],
    ["Que se passe-t-il le 2 décembre 1851 ?", ["Le coup d'État de Louis-Napoléon Bonaparte", "La proclamation de l'Empire au Sénat", "L'élection présidentielle au suffrage universel", "La révolution de Février contre Louis-Philippe"], 0,
     "L'Empire est proclamé un an jour pour jour plus tard, date anniversaire d'Austerlitz."],
    ["Quel préfet transforme Paris sous le Second Empire ?", ["Haussmann", "Rambuteau", "Poubelle", "Belgrand"], 0,
     "Percées, égouts, parcs et immeubles normés : la ville actuelle est largement son œuvre."],
    ["Quel type d'établissement financier se développe sous le Second Empire ?", ["Les grandes banques de dépôt", "Les caisses d'épargne uniquement", "Les monts-de-piété", "Les banques régionales d'émission"], 0,
     "Crédit lyonnais et Société générale naissent alors, dans un contexte d'essor du chemin de fer."],
    ["Quel traité de commerce de 1860 ouvre la France à la concurrence britannique ?", ["Le traité Cobden-Chevalier", "Le traité de Francfort, en 1871", "Le traité de Paris, en 1856", "Le traité de Turin, en 1860"], 0,
     "Il marque un tournant libre-échangiste très mal accueilli par les industriels français."],
    ["Quel territoire la France annexe-t-elle en 1860 ?", ["La Savoie et le comté de Nice", "L'Alsace, prise à l'Autriche", "La Corse, achetée à Gênes", "Le Roussillon, cédé par l'Espagne"], 0,
     "En contrepartie du soutien apporté à l'unité italienne, et après plébiscites."],
    ["Quelle guerre provoque la chute du Second Empire ?", ["La guerre franco-prussienne de 1870", "La guerre de Crimée contre la Russie", "L'expédition du Mexique, de 1861 à 1867", "La campagne d'Italie contre l'Autriche"], 0,
     "La capitulation de Sedan entraîne la proclamation de la République le 4 septembre 1870."],
    ["Quelle expédition coloniale se solde par un échec en 1867 ?", ["L'expédition du Mexique", "La conquête de la Cochinchine", "L'expédition de Chine", "La campagne du Sénégal"], 0,
     "L'empereur Maximilien, installé par la France, est fusillé après le retrait des troupes françaises."],
    ["Quel canal est inauguré en 1869 sous l'impulsion d'un ingénieur français ?", ["Le canal de Suez", "Le canal de Panama", "Le canal de Corinthe", "Le canal de Kiel"], 0,
     "Ferdinand de Lesseps en dirigea la construction ; son échec ultérieur à Panama sera retentissant.", 3],
  ]),

  notion("hf2-troisieme-republique", S, "La Troisième République",
    "De 1870 à 1940 : le régime le plus durable de l'histoire française depuis 1789.",
    "La Troisième République a été instaurée par des monarchistes incapables de s'entendre sur un roi.",
    2, [
    ["Quel amendement de 1875 instaure la République à une voix de majorité ?", ["L'amendement Wallon", "L'amendement Grévy", "L'amendement Thiers", "L'amendement Ferry"], 0,
     "Il institue un président de la République élu, ce qui inscrit le mot dans la loi constitutionnelle."],
    ["Quel événement parisien de 1871 se solde par une répression sanglante ?", ["La Commune de Paris", "Les journées de Juin", "Le 4 septembre", "L'insurrection de Belleville"], 0,
     "La Semaine sanglante fit plusieurs milliers de morts en mai 1871."],
    ["Quel traité de 1871 cède l'Alsace et une partie de la Lorraine à l'Allemagne ?", ["Le traité de Francfort", "Le traité de Versailles", "Le traité de Prague", "Le traité de Vienne"], 0,
     "Il impose aussi une indemnité de cinq milliards de francs-or."],
    ["Quelle crise de 1889 menace le régime républicain ?", ["La crise boulangiste", "L'affaire Dreyfus", "Le scandale de Panama", "L'affaire des fiches"], 0,
     "Un général populaire faillit renverser le régime avant de renoncer et de s'exiler."],
    ["Quelle affaire divise la France à partir de 1894 ?", ["L'affaire Dreyfus", "L'affaire Stavisky", "L'affaire Caillaux", "L'affaire Landru"], 0,
     "Un officier juif condamné à tort pour trahison ; sa réhabilitation n'interviendra qu'en 1906."],
    ["Quel écrivain publie J'accuse en 1898 ?", ["Émile Zola", "Anatole France", "Georges Clemenceau", "Jean Jaurès"], 0,
     "Le titre est de Clemenceau, alors directeur politique de L'Aurore, journal fondé par Ernest Vaughan."],
    ["Quelle loi de 1901 encadre la liberté d'association ?", ["La loi sur les associations", "La loi sur les syndicats", "La loi sur la presse", "La loi sur les congrégations"], 0,
     "Elle reste le cadre de la vie associative française aujourd'hui."],
    ["Quelle loi de 1905 sépare les Églises et l'État ?", ["La loi de séparation", "La loi Ferry", "La loi Combes", "La loi Waldeck-Rousseau"], 0,
     "La République ne reconnaît, ne salarie ni ne subventionne aucun culte, tout en garantissant leur libre exercice."],
    ["Quel homme politique socialiste est assassiné en juillet 1914 ?", ["Jean Jaurès", "Léon Blum", "Jules Guesde", "Paul Lafargue"], 0,
     "Il militait pour éviter la guerre. Son meurtrier sera acquitté en 1919."],
    ["Quelle réforme sociale majeure intervient en 1936 ?", ["Congés payés, semaine de quarante heures et conventions collectives", "La Sécurité sociale et les allocations familiales pour tous", "Le salaire minimum garanti dans toutes les branches", "La retraite à soixante ans pour l'ensemble des salariés"], 0,
     "Les accords Matignon sont signés en juin 1936 sous le gouvernement de Front populaire.", 3],
  ]),

  notion("hf2-france-1914-1918", S, "La France dans la Première Guerre mondiale",
    "Quatre ans de guerre sur le sol national, et une société transformée.",
    "La France a perdu proportionnellement plus d'hommes que tout autre grand belligérant occidental.",
    2, [
    ["Quelle bataille de septembre 1914 arrête l'avance allemande ?", ["La bataille de la Marne", "Verdun, en 1916", "La Somme, en 1916", "Le Chemin des Dames, en 1917"], 0,
     "Les taxis de la Marne, souvent cités, n'y transportèrent qu'un contingent limité de soldats."],
    ["Quelle bataille de 1916 dure près de dix mois autour d'une place forte ?", ["Verdun", "La Somme", "Ypres", "Arras"], 0,
     "Le système de rotation des unités a fait passer par ce front une majorité de l'armée française."],
    ["Quelle route ravitaille Verdun pendant la bataille ?", ["La Voie sacrée", "La route de Bar-le-Duc-Metz", "Le chemin des Dames", "La route de Reims"], 0,
     "Un camion y passait toutes les quatorze secondes au plus fort de l'effort."],
    ["Quelle offensive de 1917 provoque des mutineries dans l'armée française ?", ["Le Chemin des Dames", "Verdun", "La Somme", "L'offensive d'Artois"], 0,
     "Les mutineries furent surtout des refus de monter à l'assaut, non des rébellions politiques."],
    ["Qui est surnommé le Tigre et dirige le gouvernement à partir de 1917 ?", ["Georges Clemenceau", "Raymond Poincaré, président", "Aristide Briand, ministre", "Paul Painlevé, mathématicien"], 0,
     "Il avait soixante-seize ans et s'était fait connaître comme défenseur de Dreyfus."],
    ["Quelle innovation apparaît sur le champ de bataille en 1916 ?", ["Le char d'assaut", "L'avion de chasse", "Le sous-marin", "La mitrailleuse"], 0,
     "Les Britanniques les engagent d'abord dans la Somme ; les chars français Renault suivront en 1918."],
    ["Combien de soldats français sont morts pendant la Première Guerre mondiale ?", ["Environ un million quatre cent mille", "Environ trois cent mille hommes seulement", "Environ trois millions d'hommes", "Environ sept cent mille hommes"], 0,
     "Auxquels s'ajoutent environ trois millions de blessés, pour plus de quatre millions de blessures, dont de nombreux mutilés."],
    ["Que désigne le terme gueules cassées ?", ["Les soldats défigurés par leurs blessures", "Les prisonniers de guerre rapatriés en 1918", "Les déserteurs fusillés pour l'exemple", "Les soldats gazés à l'ypérite en 1917"], 0,
     "Certains participèrent à la signature du traité de Versailles, placés au premier rang."],
    ["Quel rôle nouveau les femmes jouent-elles pendant la guerre ?", ["Elles occupent massivement des emplois industriels et agricoles", "Elles obtiennent le droit de vote dès la fin du conflit", "Elles servent dans les unités combattantes du front", "Elles dirigent les municipalités laissées sans hommes"], 0,
     "Le droit de vote ne leur sera accordé qu'en 1944, contrairement à plusieurs pays voisins."],
    ["Quel traité met fin à la guerre avec l'Allemagne en 1919 ?", ["Le traité de Versailles", "Le traité de Trianon", "Le traité de Saint-Germain", "Le traité de Sèvres"], 0,
     "Signé dans la galerie des Glaces, là où l'Empire allemand avait été proclamé en 1871.", 3],
  ]),

  notion("hf2-france-1940-1944", S, "La France de 1940 à 1944",
    "Défaite, occupation, collaboration et Résistance.",
    "Le régime de Vichy n'a pas seulement subi les demandes allemandes : il a aussi devancé certaines.",
    2, [
    ["Quelle stratégie allemande perce le front français en mai 1940 ?", ["La percée blindée par les Ardennes", "Une offensive frontale sur la ligne Maginot", "Un débarquement en Normandie", "Une attaque par la Suisse"], 0,
     "Le secteur était jugé impraticable aux blindés par le commandement français."],
    ["Quel régime s'installe en France en juillet 1940 ?", ["L'État français, dirigé par Pétain", "La Troisième République maintenue", "Un protectorat allemand direct", "Un gouvernement militaire"], 0,
     "Les pleins pouvoirs constitutionnels lui sont votés par l'Assemblée nationale réunie à Vichy."],
    ["Quelle devise remplace celle de la République sous Vichy ?", ["Travail, Famille, Patrie", "Ordre, Travail, Nation", "Honneur et Patrie", "Unité, Discipline, Travail"], 0,
     "Elle figure sur les pièces de monnaie et les bâtiments publics de la période."],
    ["Quel statut Vichy promulgue-t-il dès octobre 1940 ?", ["Le statut des Juifs", "Le statut des étrangers", "Le statut du travail", "Le statut des fonctionnaires"], 0,
     "Adopté sans demande allemande, il exclut les Juifs de nombreuses professions."],
    ["Quelle rafle a lieu à Paris en juillet 1942 ?", ["La rafle du Vélodrome d'Hiver", "La rafle de la rue des Rosiers", "La rafle du billet vert", "La rafle de Drancy"], 0,
     "Plus de treize mille personnes arrêtées par la police française, dont plus de quatre mille enfants."],
    ["Quel camp d'internement sert de principal lieu de transit vers Auschwitz ?", ["Drancy", "Gurs", "Rivesaltes", "Le Vernet"], 0,
     "Environ soixante-trois mille personnes en sont déportées entre 1942 et 1944."],
    ["Quel service oblige les jeunes Français à travailler en Allemagne à partir de 1943 ?", ["Le Service du travail obligatoire", "La Relève volontaire seule", "Le service civique", "La conscription industrielle"], 0,
     "Il pousse de nombreux réfractaires à rejoindre les maquis."],
    ["Qui unifie les mouvements de résistance en 1943 ?", ["Jean Moulin", "Pierre Brossolette", "Henri Frenay", "Jacques Bingen"], 0,
     "Le Conseil national de la Résistance se réunit pour la première fois en mai 1943, rue du Four à Paris."],
    ["Quel programme le Conseil national de la Résistance adopte-t-il en mars 1944 ?", ["Un programme de réformes sociales et économiques d'après-guerre", "Un plan militaire d'insurrection", "Une constitution provisoire", "Un accord avec les Alliés"], 0,
     "Sécurité sociale, nationalisations et droit au travail y figurent, et seront largement appliqués."],
    ["Quel village est détruit et sa population massacrée en juin 1944 ?", ["Oradour-sur-Glane", "Tulle", "Vassieux-en-Vercors", "Maillé"], 0,
     "Six cent quarante-trois victimes. Les ruines ont été conservées en l'état comme lieu de mémoire.", 3],
  ]),

  notion("hf2-quatrieme-republique", S, "La Quatrième République",
    "1946-1958 : reconstruction, croissance, instabilité gouvernementale et guerres coloniales.",
    "La Quatrième République a connu vingt-deux gouvernements en douze ans, soit une durée moyenne de six mois.",
    2, [
    ["Quand les femmes votent-elles pour la première fois en France ?", ["En 1945", "En 1936", "En 1919", "En 1958"], 0,
     "Le droit leur a été accordé par ordonnance en avril 1944, appliqué aux municipales d'avril 1945."],
    ["Quelle institution est créée en 1945 pour couvrir les risques sociaux ?", ["La Sécurité sociale", "Les allocations familiales seules", "L'assurance chômage", "Les caisses de retraite complémentaires"], 0,
     "Elle applique un point central du programme du Conseil national de la Résistance."],
    ["Quel plan organise la modernisation économique française à partir de 1946 ?", ["Le plan Monnet", "Le plan Marshall", "Le plan Pinay", "Le plan Rueff"], 0,
     "Une planification indicative, non contraignante, centrée sur les secteurs de base."],
    ["Quelles entreprises sont nationalisées à la Libération ?", ["Les banques de dépôt, l'électricité, le gaz et le charbon", "L'agriculture et le commerce de gros dans tout le pays", "Les seules compagnies d'assurances et leurs filiales", "Les chemins de fer uniquement, réunis dans la SNCF"], 0,
     "Renault est nationalisé à titre de sanction pour la collaboration de son propriétaire."],
    ["Qu'appelle-t-on les Trente Glorieuses ?", ["Les trois décennies de forte croissance de 1945 à 1975", "Les trente premières années de la Cinquième République", "Les trente ans de reconstruction industrielle d'après-guerre", "La période allant de 1958 à 1988, sous la Ve République"], 0,
     "L'expression est due à l'économiste Jean Fourastié en 1979."],
    ["Quelle guerre coloniale se termine par la défaite de Diên Biên Phu en 1954 ?", ["La guerre d'Indochine", "La guerre d'Algérie", "La guerre du Maroc", "La guerre de Madagascar"], 0,
     "Les accords de Genève suivent quelques semaines plus tard et divisent le Vietnam."],
    ["Quels protectorats deviennent indépendants en 1956 ?", ["Le Maroc et la Tunisie", "L'Algérie et le Maroc", "Le Sénégal et le Mali", "Madagascar et le Cameroun"], 0,
     "Le statut de protectorat facilitait juridiquement une émancipation que l'Algérie, département français, n'avait pas."],
    ["Quel traité de 1957 fonde la Communauté économique européenne ?", ["Le traité de Rome", "Le traité de Paris", "Le traité de Maastricht", "Le traité de Bruxelles"], 0,
     "Six pays fondateurs : France, Allemagne, Italie et Benelux."],
    ["Quelle crise de 1958 met fin à la Quatrième République ?", ["La crise algérienne du 13 mai", "La crise de Suez", "La crise monétaire", "La crise ministérielle de Paris"], 0,
     "De Gaulle est investi président du Conseil et chargé de préparer une nouvelle constitution."],
    ["Quelle faiblesse institutionnelle caractérise la Quatrième République ?", ["Un exécutif faible face à une Assemblée toute-puissante", "Un président trop puissant, élu au suffrage universel", "L'absence de tout contrôle parlementaire sur le gouvernement", "Un mode de scrutin majoritaire à deux tours par circonscription"], 0,
     "L'absence de majorité stable et la facilité de renversement expliquent l'instabilité chronique.", 3],
  ]),

  notion("hf2-cinquieme-republique", S, "La Cinquième République",
    "Institutions, alternances, cohabitations : le régime en place depuis 1958.",
    "L'élection du président au suffrage universel direct date de 1962, pas de 1958.",
    2, [
    ["Quelle réforme de 1962 modifie l'élection du président ?", ["Son élection au suffrage universel direct", "L'allongement du mandat présidentiel à sept ans", "La limitation à deux mandats consécutifs", "La suppression du Sénat, rejetée par référendum"], 0,
     "Adoptée par référendum, la procédure employée fut contestée juridiquement."],
    ["Quelle réforme de 2001 fait précéder l'élection présidentielle des élections législatives ?", ["L'inversion du calendrier électoral", "Le passage au quinquennat", "La limitation des mandats", "La réforme du mode de scrutin législatif"], 0,
     "Combinée au quinquennat voté l'année précédente, elle vise à aligner le tempo des deux scrutins et à renforcer le fait majoritaire."],
    ["Qu'est-ce que l'article 49 alinéa 3 de la Constitution ?", ["L'adoption d'un texte sans vote, sauf motion de censure", "La dissolution de l'Assemblée nationale par le président", "Les pouvoirs exceptionnels du président en cas de crise", "Le vote bloqué sur un texte, sans amendement"], 0,
     "Son usage a été limité en 2008 à un texte par session, hors budgets."],
    ["Qu'est-ce que l'article 16 de la Constitution ?", ["Les pouvoirs exceptionnels du président en cas de crise grave", "Le droit de dissolution de l'Assemblée nationale", "La procédure de révision de la Constitution par le Congrès de Versailles", "Le référendum d'initiative partagée introduit en 2008"], 0,
     "Il n'a été appliqué qu'une fois, en 1961, lors du putsch des généraux à Alger."],
    ["Quel mouvement social secoue la France en mai 1968 ?", ["Une contestation étudiante puis une grève générale", "Une révolte paysanne contre l'effondrement des prix agricoles", "Une grève des transports contre la SNCF", "Une insurrection ouvrière armée dans les banlieues"], 0,
     "Environ sept à neuf millions de grévistes, le plus vaste mouvement social de l'histoire française."],
    ["Qu'est-ce qu'une cohabitation ?", ["Un président et un gouvernement de bords politiques opposés", "Un gouvernement d'union nationale réunissant tous les partis", "Une coalition parlementaire majoritaire à l'Assemblée", "Un partage du pouvoir entre les deux chambres du Parlement"], 0,
     "Trois cohabitations ont eu lieu depuis 1986. Le quinquennat en a réduit la probabilité."],
    ["Quelle réforme de 1974 élargit la saisine du Conseil constitutionnel ?", ["L'ouverture aux parlementaires par groupes de soixante", "La saisine directe par les citoyens ordinaires, sans filtre", "La saisine par le seul Premier ministre du gouvernement", "La saisine automatique de toutes les lois votées"], 0,
     "Le nombre de saisines a explosé, transformant le rôle de l'institution."],
    ["Quelle révision constitutionnelle de 2008 limite le nombre de mandats présidentiels ?", ["Deux mandats consécutifs au maximum", "Trois mandats consécutifs au maximum", "Aucune limite, la règle ancienne étant maintenue", "Un seul mandat, non renouvelable"], 0,
     "Elle a aussi renforcé les pouvoirs du Parlement sur l'ordre du jour et les nominations.", 3],
  ]),

  notion("hf2-france-outre-mer", S, "La France d'outre-mer",
    "Départements, collectivités, territoires : une France présente sur tous les océans.",
    "Grâce à ses outre-mer, la France dispose de la deuxième zone économique exclusive du monde.",
    2, [
    ["Combien de départements d'outre-mer la France compte-t-elle ?", ["Cinq", "Trois", "Quatre", "Sept"], 0,
     "Guadeloupe, Martinique, Guyane, La Réunion et Mayotte, ce dernier depuis 2011."],
    ["En quelle année les vieilles colonies deviennent-elles des départements ?", ["1946", "1848", "1958", "1962"], 0,
     "Guadeloupe, Martinique, Guyane et La Réunion, sous l'impulsion notamment d'Aimé Césaire."],
    ["Quelle collectivité française est la plus vaste en superficie ?", ["La Guyane", "La Nouvelle-Calédonie", "La Polynésie française", "Les Terres australes"], 0,
     "Environ quatre-vingt-quatre mille kilomètres carrés, couverts en grande partie de forêt amazonienne."],
    ["Quel accord de 1998 organise l'avenir institutionnel de la Nouvelle-Calédonie ?", ["L'accord de Nouméa", "Les accords de Matignon seuls", "L'accord de Papeete", "Le statut de 1988"], 0,
     "Il prévoyait un transfert progressif de compétences et des consultations sur l'indépendance."],
    ["Quelle collectivité française se trouve dans l'Atlantique nord, près du Canada ?", ["Saint-Pierre-et-Miquelon", "Saint-Martin", "Saint-Barthélemy", "La Guadeloupe"], 0,
     "Dernier vestige de la Nouvelle-France, à quelques kilomètres de Terre-Neuve."],
    ["Quel territoire français abrite le centre spatial de Kourou ?", ["La Guyane", "La Réunion", "La Nouvelle-Calédonie", "La Polynésie française"], 0,
     "Sa proximité de l'équateur offre un gain d'énergie appréciable au lancement."],
    ["Quel rang la France occupe-t-elle pour la taille de sa zone économique exclusive ?", ["Le deuxième mondial", "Le premier", "Le cinquième", "Le dixième"], 0,
     "Plus de dix millions de kilomètres carrés, dont l'essentiel grâce aux outre-mer du Pacifique."],
    ["Quelle loi de 2001 qualifie la traite et l'esclavage de crime contre l'humanité ?", ["La loi Taubira", "La loi Gayssot", "La loi Mékachéra", "La loi Perben"], 0,
     "Elle prévoit aussi que ces sujets trouvent une place dans les programmes scolaires.", 3],
  ]),

  notion("hf2-symboles-republique", S, "Emblèmes et devise de la République",
    "Drapeau, hymne, devise, Marianne : d'où viennent-ils et que disent les textes.",
    "La Marseillaise n'est devenue hymne national définitif qu'en 1879.",
    2, [
    ["D'où vient le drapeau tricolore français ?", ["De l'association des couleurs de Paris et du blanc royal", "Des trois ordres de l'Ancien Régime réunis en 1789", "Des couleurs de la Révolution américaine de 1776", "Des armoiries des Bourbons, reprises en 1790"], 0,
     "Le bleu et le rouge sont les couleurs de la ville de Paris, encadrant le blanc du roi."],
    ["Dans quelle ville la Marseillaise est-elle composée en 1792 ?", ["Strasbourg", "Marseille, au sud", "Paris, à la Convention", "Valmy, en Champagne"], 0,
     "Rouget de Lisle y était officier du génie. Le titre initial était Chant de guerre pour l'armée du Rhin."],
    ["Pourquoi ce chant s'appelle-t-il la Marseillaise ?", ["Des fédérés marseillais l'ont chanté en arrivant à Paris", "Il a été composé à Marseille par un officier du Midi", "Il célèbre une bataille livrée non loin de Marseille", "Il fut adopté par la municipalité de Marseille en 1792"], 0,
     "Adopté par les volontaires marseillais montés à Paris en juillet 1792, il devient officiellement hymne national par le décret du 14 juillet 1795."],
    ["Sous quels régimes la Marseillaise a-t-elle été écartée au XIXe siècle ?", ["Sous l'Empire et la Restauration", "Sous la Deuxième République", "Sous le Directoire", "Sous la monarchie de Juillet seule"], 0,
     "Jugée trop révolutionnaire, elle est rétablie définitivement en 1879 par la Troisième République."],
    ["Quelle est la devise de la République française ?", ["Liberté, Égalité, Fraternité", "Liberté, Égalité, Solidarité", "Unité, Liberté, Justice", "Honneur et Patrie"], 0,
     "La fraternité n'a été durablement associée aux deux autres termes qu'en 1848."],
    ["Que symbolise le bonnet phrygien porté par Marianne ?", ["L'affranchissement, par référence aux esclaves libérés de Rome", "La coiffe que portaient les paysans révolutionnaires du Midi de la France", "Le couvre-chef réglementaire des soldats de l'an II", "Un emblème repris de la ville antique de Phrygie"], 0,
     "Le rouge de ce bonnet est devenu par extension la couleur des révolutions."],
    ["Quel jour est la fête nationale française ?", ["Le 14 juillet", "Le 4 septembre", "Le 21 janvier", "Le 26 août"], 0,
     "La loi de 1880 ne précise pas si elle commémore 1789 ou la Fête de la Fédération de 1790."],
    ["Quel est le sceau de la République française ?", ["Une figure de la Liberté assise", "Un faisceau de licteur entouré de lauriers", "Un coq gaulois sur fond tricolore", "Une fleur de lys stylisée en or"], 0,
     "Gravé en 1848, il n'est plus utilisé que pour les actes constitutionnels."],
    ["Que dit l'article premier de la Constitution de 1958 sur la République ?", ["Elle est indivisible, laïque, démocratique et sociale", "Elle est fédérale, démocratique et largement décentralisée", "Elle est parlementaire, laïque et représentative", "Elle est souveraine, indépendante et neutre"], 0,
     "Le caractère décentralisé y a été ajouté en 2003 ; l'égal accès aux mandats, inscrit en 1999 aux articles 3 et 4, y a été transféré en 2008.", 3],
  ]),
];
