/**
 * Histoire du monde — treize notions.
 *
 * Le cahier couvre les grandes civilisations et les grands conflits. Ces
 * notions descendent d'un cran : un empire précis, une révolution, une
 * décennie, une institution.
 */
import { notion, type Q } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Histoire du monde";

export const CG_HISTOIRE_MONDE: SeedSkill[] = [
  notion("hm-alexandre", S, "Alexandre le Grand et le monde hellénistique",
    "Douze ans de conquête, un empire de la Grèce à l'Indus, et trois siècles de royaumes grecs en Orient après sa mort.",
    "Trois batailles suffisent à tenir toute la conquête, dans l'ordre où l'armée avance vers l'est. Le plus difficile à retenir vient après sa mort, quand ses généraux se partagent l'empire.",
    2, [
    ["De quel royaume Alexandre hérite-t-il en 336 av. J.-C. ?", ["La Macédoine", "Athènes", "Sparte", "L'Épire"], 0,
     "Il succède à son père Philippe II, assassiné, qui avait déjà soumis les cités grecques à Chéronée en 338."],
    ["Quel philosophe fut le précepteur d'Alexandre ?", ["Aristote", "Platon", "Diogène", "Isocrate"], 0,
     "Aristote lui enseigne quelques années à Mieza. Alexandre emportera, dit-on, une édition de l'Iliade annotée par son maître."],
    ["Quelle bataille de 331 av. J.-C. brise l'Empire perse ?", ["Gaugamèles", "Issos", "Le Granique", "L'Hydaspe"], 0,
     "Darius III y est mis en fuite. Babylone, Suse et Persépolis tombent dans les mois qui suivent."],
    ["Quelle ville fondée en Égypte porte le nom d'Alexandre ?", ["Alexandrie", "Antioche", "Séleucie", "Pergame"], 0,
     "Fondée en 331 av. J.-C., elle devient le grand foyer intellectuel du monde hellénistique avec sa bibliothèque et son phare."],
    ["Jusqu'où Alexandre pousse-t-il sa conquête vers l'est ?", ["Jusqu'à l'Indus", "Jusqu'au Gange", "Jusqu'à la mer Caspienne", "Jusqu'à la Chine"], 0,
     "Après la victoire de l'Hydaspe en 326, ses troupes refusent d'aller plus loin. Il doit rebrousser chemin."],
    ["Où meurt Alexandre en 323 av. J.-C. ?", ["À Babylone", "À Alexandrie", "À Pella", "À Suse"], 0,
     "Il meurt à trente-deux ans, sans successeur désigné. Les causes exactes — fièvre, empoisonnement — restent discutées."],
    ["Comment nomme-t-on les généraux qui se partagent son empire ?", ["Les diadoques", "Les satrapes", "Les stratèges", "Les éphores"], 0,
     "Le mot signifie successeurs. Leurs guerres durent plus de quarante ans et aboutissent à trois grands royaumes."],
    ["Quelle dynastie règne sur l'Égypte hellénistique ?", ["Les Lagides", "Les Séleucides", "Les Antigonides", "Les Attalides"], 0,
     "Fondée par Ptolémée, elle règne jusqu'à Cléopâtre VII, morte en 30 av. J.-C."],
    ["Qu'appelle-t-on hellénisation ?", ["La diffusion de la langue et de la culture grecques en Orient", "Le retour des Grecs en Europe", "L'unification religieuse de l'Empire", "La colonisation grecque archaïque"], 0,
     "Le grec devient la langue commune de l'Orient, la koinè, dans laquelle sera plus tard écrit le Nouveau Testament."],
    ["Quel royaume grec subsiste le plus longtemps en Asie centrale ?", ["Le royaume gréco-bactrien", "Le royaume du Pont", "Le royaume de Pergame", "Le royaume de Commagène"], 0,
     "Installé dans l'actuel Afghanistan, il produit un art gréco-bouddhique dont témoignent les statues du Gandhara.", 3],
  ]),

  notion("hm-carthage-rome", S, "Carthage et les guerres puniques",
    "Trois guerres, cent dix-huit ans, et la disparition d'une des grandes puissances de la Méditerranée. Rome y gagne son premier empire.",
    "Première guerre : la Sicile et la mer. Deuxième : Hannibal et l'Italie. Troisième : la destruction.",
    2, [
    ["Où Carthage a-t-elle été fondée ?", ["Sur le site de l'actuelle Tunis", "En Sicile, à Palerme", "En Espagne, à Carthagène", "En Libye orientale"], 0,
     "Fondée par des Phéniciens de Tyr vers 814 av. J.-C. selon la tradition, elle devient la première puissance maritime de l'Ouest méditerranéen."],
    ["Quel enjeu déclenche la première guerre punique en 264 av. J.-C. ?", ["Le contrôle de la Sicile", "La possession de l'Espagne", "Le commerce de l'étain", "La domination de la Corse"], 0,
     "L'intervention romaine à Messine met fin à un équilibre ancien. Rome construit alors sa première flotte de guerre."],
    ["Quelle invention permet aux Romains de compenser leur infériorité navale ?", ["Le corbeau, une passerelle d'abordage", "La trirème à trois rangs de rameurs", "Le feu grégeois, mélange incendiaire", "La catapulte de marine"], 0,
     "Ce pont mobile à crochet transforme un combat naval en combat d'infanterie, où Rome excelle."],
    ["Par où Hannibal entre-t-il en Italie en 218 av. J.-C. ?", ["Par les Alpes", "Par la Sicile", "Par l'Adriatique", "Par la vallée du Rhin"], 0,
     "Parti d'Espagne, il traverse les Pyrénées, la Gaule et les Alpes avec des éléphants. La traversée lui coûte la moitié de son armée."],
    ["Quelle bataille de 216 av. J.-C. est le pire désastre romain ?", ["Cannes", "Trasimène", "La Trébie", "Zama"], 0,
     "Hannibal y enveloppe une armée bien supérieure en nombre. La manœuvre est encore étudiée dans les écoles militaires."],
    ["Quel général romain finit par battre Hannibal en 202 av. J.-C. ?", ["Scipion l'Africain", "Fabius Cunctator, avant lui", "Marcellus, vainqueur de Syracuse", "Caton l'Ancien, plus tard"], 0,
     "La bataille de Zama, en Afrique, met fin à la deuxième guerre punique. Carthage perd sa flotte et ses possessions."],
    ["Quelle tactique Fabius Maximus emploie-t-il contre Hannibal ?", ["Éviter la bataille rangée et harceler", "Attaquer frontalement l'ennemi", "Assiéger Carthage sans attendre", "Négocier une paix séparée en Espagne"], 0,
     "Son surnom, Cunctator, signifie le Temporisateur. La stratégie fut d'abord jugée lâche, puis reconnue efficace."],
    ["Quelle formule Caton l'Ancien répétait-il au Sénat ?", ["Il faut détruire Carthage", "Rome ne négocie pas", "Malheur aux vaincus", "La guerre nourrit la guerre"], 0,
     "Delenda est Carthago : il aurait conclu ainsi chacune de ses interventions, quel qu'en fût le sujet."],
    ["Que devient Carthage en 146 av. J.-C. ?", ["Elle est rasée et son territoire annexé", "Elle devient une alliée fidèle de Rome", "Elle est reconstruite aussitôt par Scipion Émilien", "Elle passe sous le contrôle du royaume numide"], 0,
     "La ville est détruite après un siège de trois ans. Rome y fondera une colonie un siècle plus tard."],
    ["Quel autre événement majeur a lieu la même année 146 av. J.-C. ?", ["La destruction de Corinthe", "La conquête de l'Égypte par Rome", "La mort de Scipion l'Africain", "La révolte de Spartacus, bien plus tard"], 0,
     "Rome achève la même année la soumission de la Grèce. Deux capitales sont détruites en quelques mois.", 3],
  ]),

  notion("hm-empire-mongol", S, "L'Empire mongol",
    "En un siècle, le plus vaste empire continu de l'histoire : de la Corée à la Hongrie, une administration nomade et des routes rouvertes.",
    "Distinguez le fondateur de ses successeurs, qui divisent l'empire en quatre khanats.",
    2, [
    ["Quel nom prend Temüjin en 1206 ?", ["Gengis Khan", "Kubilai Khan", "Tamerlan", "Batu Khan"], 0,
     "Le titre signifie souverain universel. Il l'obtient après avoir unifié les tribus de la steppe."],
    ["Quel code de lois Gengis Khan promulgue-t-il ?", ["La Yassa", "Le Yasak", "Le Kanun", "Le Sharia"], 0,
     "Ce code oral règle la discipline militaire, la chasse et la succession. Aucun exemplaire complet ne nous est parvenu."],
    ["Quel empire chinois Kubilai Khan fonde-t-il en 1271 ?", ["La dynastie Yuan", "La dynastie Ming", "La dynastie Song", "La dynastie Qing"], 0,
     "Il achève la conquête de la Chine du Sud en 1279. Sa capitale, Khanbalik, deviendra Pékin."],
    ["Quel voyageur vénitien séjourne à la cour de Kubilai ?", ["Marco Polo", "Jean de Plan Carpin", "Guillaume de Rubrouck", "Ibn Battuta"], 0,
     "Son récit, dicté en prison à Gênes, fera longtemps référence en Europe sur l'Asie."],
    ["Qu'est-ce que le yam mongol ?", ["Un réseau de relais de poste", "Un impôt sur les troupeaux", "Une assemblée des chefs", "Une unité militaire"], 0,
     "Des relais espacés d'une journée de cheval permettent de traverser l'empire en quelques semaines."],
    ["Quelle bataille arrête l'expansion mongole en 1260 ?", ["Aïn Djalout", "Kôsedag", "Legnica", "Mohi"], 0,
     "Les Mamelouks d'Égypte y battent l'armée mongole en Palestine. C'est le premier coup d'arrêt sérieux."],
    ["Que devient l'empire après 1260 ?", ["Il se divise en quatre khanats", "Il se convertit entièrement à l'islam", "Il est conquis par la Chine", "Il se replie en Mongolie"], 0,
     "Horde d'Or, Ilkhanat, khanat de Djaghataï et empire Yuan cessent progressivement de reconnaître un khan suprême."],
    ["Quel khanat mongol domine la Russie jusqu'au XVe siècle ?", ["La Horde d'Or", "L'Ilkhanat", "Le khanat de Djaghataï", "Le khanat de Sibir"], 0,
     "Les principautés russes lui versent tribut. Moscou s'en émancipe progressivement à partir de 1480."],
    ["Quel conquérant se réclame de l'héritage mongol à la fin du XIVe siècle ?", ["Tamerlan", "Babur", "Ivan III", "Bayezid Ier"], 0,
     "Turco-mongol de Samarcande, il ravage l'Asie centrale, la Perse et l'Inde du Nord. Son descendant Babur fondera l'empire moghol."],
    ["Quel effet indirect l'unification mongole a-t-elle sur l'Europe ?", ["Elle facilite les échanges et la diffusion de la peste noire", "Elle interrompt tout commerce avec l'Asie", "Elle provoque les croisades", "Elle isole la Chine"], 0,
     "La pax mongolica rouvre les routes de la soie. Le bacille de la peste suit les mêmes routes vers 1347.", 3],
  ]),

  notion("hm-espagne-or", S, "L'Espagne du Siècle d'or et son empire",
    "De la prise de Grenade en 1492 à la paix des Pyrénées en 1659 : la première puissance mondiale, son argent américain et son déclin.",
    "L'argent du Potosí explique à la fois la puissance espagnole et l'inflation qui ruine le royaume.",
    2, [
    ["Que se passe-t-il à Grenade en 1492 ?", ["La chute du dernier royaume musulman d'Espagne", "La découverte de l'Amérique par Colomb", "Le couronnement de Charles Quint à Aix", "L'expulsion des Morisques d'Andalousie"], 0,
     "La Reconquista s'achève après près de huit siècles. La même année, les Juifs sont expulsés et Colomb part vers l'ouest."],
    ["Qui sont les Rois Catholiques ?", ["Isabelle de Castille et Ferdinand d'Aragon", "Charles Quint et son fils Philippe II d'Espagne", "Jeanne la Folle et Philippe le Beau, leurs enfants", "Ferdinand VII et Marie-Louise de Parme"], 0,
     "Leur mariage en 1469 unit les deux couronnes sans les fondre. Le titre leur est accordé par le pape en 1496."],
    ["Quel conquistador abat l'Empire aztèque ?", ["Hernán Cortés", "Francisco Pizarro", "Vasco de Balboa", "Pedro de Alvarado"], 0,
     "Il prend Tenochtitlan en 1521, aidé par des alliés indigènes et par les épidémies apportées d'Europe."],
    ["Quel conquistador abat l'Empire inca ?", ["Francisco Pizarro", "Hernán Cortés, au Mexique", "Diego de Almagro, son associé", "Gonzalo Jiménez de Quesada"], 0,
     "Il capture Atahualpa à Cajamarca en 1532 et l'exécute malgré le versement d'une rançon."],
    ["Quelle mine d'argent enrichit l'Espagne à partir de 1545 ?", ["Le Potosí, dans l'actuelle Bolivie", "Zacatecas, au Mexique", "Les mines de Guanajuato, au Mexique", "Les gisements de Colombie"], 0,
     "Le cerro rico fournit pendant deux siècles l'essentiel de l'argent mondial, extrait au prix d'une mortalité effroyable."],
    ["Quel empereur règne sur l'Espagne, les Pays-Bas, l'Autriche et les Amériques ?", ["Charles Quint", "Philippe II", "Ferdinand Ier", "Philippe III"], 0,
     "Il abdique en 1556 et partage ses possessions entre son fils Philippe II et son frère Ferdinand."],
    ["Quel désastre naval l'Espagne subit-elle en 1588 ?", ["La défaite de l'Invincible Armada", "La bataille de Lépante, en 1571", "La perte de la flotte des Indes", "Le siège de Cadix"], 0,
     "La flotte envoyée contre l'Angleterre est dispersée par le combat puis par les tempêtes. Le mythe de l'invincibilité espagnole s'effondre."],
    ["Quelle victoire chrétienne l'Espagne remporte-t-elle en 1571 ?", ["Lépante", "Otrante", "Malte", "Preveza"], 0,
     "La Sainte Ligue y détruit la flotte ottomane. Cervantès y perd l'usage de la main gauche."],
    ["Quel roman de Cervantès paraît en 1605 ?", ["Don Quichotte", "La Célestine", "Le Lazarillo de Tormes", "Les Nouvelles exemplaires"], 0,
     "Souvent tenu pour le premier roman moderne, il parodie les romans de chevalerie tout en inventant un personnage inoubliable."],
    ["Quel peintre est le maître du Siècle d'or espagnol à la cour de Philippe IV ?", ["Vélasquez", "Le Greco, à Tolède", "Murillo, à Séville", "Zurbarán"], 0,
     "Les Ménines, peint en 1656, joue du regard et du miroir d'une façon restée sans équivalent.", 3],
  ]),

  notion("hm-independances-amerique-latine", S, "Les indépendances latino-américaines",
    "Entre 1810 et 1825, l'Amérique espagnole se libère. Deux libérateurs, des projets d'union avortés, et des républiques fragiles.",
    "Bolívar libère le nord, San Martín le sud. Ils se rencontrent à Guayaquil en 1822, et l'un se retire.",
    2, [
    ["Quel événement européen déclenche les indépendances américaines ?", ["L'invasion de l'Espagne par Napoléon en 1808", "La Révolution française", "Le congrès de Vienne", "La guerre de Sept Ans"], 0,
     "La déposition du roi d'Espagne prive les colonies de leur souverain légitime et ouvre la question du pouvoir."],
    ["Quel libérateur est surnommé le Libertador ?", ["Simón Bolívar", "José de San Martín", "Bernardo O'Higgins", "Miguel Hidalgo"], 0,
     "Né à Caracas, il libère le Venezuela, la Colombie, l'Équateur, le Pérou et la Bolivie, qui porte son nom."],
    ["Quel exploit militaire San Martín accomplit-il en 1817 ?", ["La traversée des Andes", "La prise de Lima par mer", "Le siège de Montevideo", "La bataille de Boyacá"], 0,
     "Il fait franchir la cordillère à son armée pour surprendre les royalistes au Chili, à Chacabuco."],
    ["Quelle république éphémère Bolívar fonde-t-il en 1819 ?", ["La Grande Colombie", "La Confédération péruvienne", "Les Provinces-Unies", "La République de Quito"], 0,
     "Elle réunit les actuels Venezuela, Colombie, Équateur et Panama. Elle éclate en 1831, peu après la mort de Bolívar."],
    ["Quel prêtre lance le soulèvement mexicain en 1810 ?", ["Miguel Hidalgo", "José Morelos", "Agustín de Iturbide", "Benito Juárez"], 0,
     "Le cri de Dolores, le 16 septembre 1810, est resté la fête nationale mexicaine. Hidalgo est fusillé l'année suivante."],
    ["Comment le Brésil accède-t-il à l'indépendance en 1822 ?", ["Le fils du roi du Portugal se proclame empereur", "Par une guerre de dix ans", "Par un traité avec l'Angleterre", "Par une révolution républicaine"], 0,
     "Pierre Ier refuse de rentrer à Lisbonne et prend la tête du mouvement. Le Brésil reste un empire jusqu'en 1889."],
    ["Quelle bataille de 1824 achève la guerre d'indépendance sud-américaine ?", ["Ayacucho", "Boyacá", "Carabobo", "Maipú"], 0,
     "La victoire de Sucre au Pérou met fin à la présence militaire espagnole sur le continent."],
    ["Quelles colonies espagnoles restent aux mains de Madrid après 1825 ?", ["Cuba et Porto Rico", "Le Panama et le Honduras", "Les Philippines seules", "Aucune"], 0,
     "Elles ne seront perdues qu'en 1898, à l'issue de la guerre contre les États-Unis."],
    ["Que prévoit la doctrine Monroe de 1823 ?", ["L'Europe ne doit plus intervenir dans les Amériques", "Les États-Unis annexent le Mexique", "Le libre-échange dans l'hémisphère", "L'abolition de l'esclavage"], 0,
     "Formulée par le président James Monroe, elle sera invoquée pendant plus d'un siècle pour justifier l'influence américaine."],
    ["Pourquoi le projet d'union continentale de Bolívar échoue-t-il ?", ["Rivalités régionales et distances", "Une intervention espagnole", "L'opposition du Brésil", "Un refus britannique"], 0,
     "Le congrès de Panama de 1826 ne réunit que quatre États. Bolívar meurt en 1830 en jugeant avoir labouré la mer.", 3],
  ]),

  notion("hm-meiji-japon", S, "Le Japon de Meiji à 1945",
    "En cinquante ans, un pays fermé devient une puissance industrielle et coloniale, puis s'engage dans une guerre qui le détruit.",
    "Trois guerres marquent l'ascension : la Chine en 1894, la Russie en 1904, puis l'expansion des années 1930.",
    2, [
    ["Quel événement force l'ouverture du Japon en 1853 ?", ["L'arrivée des navires du commodore Perry", "Une révolte paysanne", "Un traité imposé par la Russie", "L'intervention de la flotte britannique"], 0,
     "Les navires noirs américains obligent le shogunat à signer des traités inégaux, ce qui précipite sa chute."],
    ["Que désigne l'ère Meiji, commencée en 1868 ?", ["La restauration du pouvoir impérial et la modernisation", "Le retour du shogunat Tokugawa au pouvoir", "Une période de guerre civile entre clans", "L'isolement volontaire du pays"], 0,
     "Le mot signifie gouvernement éclairé. La capitale est transférée d'Edo, rebaptisée Tokyo."],
    ["Quelle classe sociale perd ses privilèges sous Meiji ?", ["Les samouraïs", "Les marchands", "Les paysans", "Les moines"], 0,
     "Leur pension est supprimée et le port du sabre interdit en 1876. La révolte de Satsuma est écrasée l'année suivante."],
    ["Contre quel pays le Japon gagne-t-il la guerre de 1894-1895 ?", ["La Chine", "La Russie", "La Corée", "Les États-Unis"], 0,
     "Il obtient Taïwan et une influence sur la Corée. La rapidité de sa victoire surprend les puissances européennes."],
    ["Quelle guerre le Japon gagne-t-il en 1905 ?", ["La guerre russo-japonaise", "La première guerre sino-japonaise", "La guerre du Pacifique, bien plus tard", "La guerre de Corée, au XXe siècle"], 0,
     "La victoire de Tsushima est la première d'une puissance asiatique sur une puissance européenne à l'époque moderne."],
    ["Quand le Japon annexe-t-il la Corée ?", ["En 1910", "En 1895", "En 1931", "En 1937"], 0,
     "La colonisation dure jusqu'en 1945 et laisse un contentieux mémoriel toujours vif."],
    ["Quelle région le Japon envahit-il en 1931 ?", ["La Mandchourie", "La Corée, déjà annexée", "Taïwan, cédé en 1895", "L'Indochine française"], 0,
     "L'incident de Moukden sert de prétexte. Le Japon y installe l'État fantoche du Mandchoukouo et quitte la SDN."],
    ["Quel massacre marque la guerre en Chine en 1937 ?", ["Le massacre de Nankin", "Le siège de Shanghai", "La bataille de Wuhan", "L'incident de Xi'an"], 0,
     "Les estimations les plus courantes vont de cent mille à trois cent mille victimes civiles."],
    ["Quelle attaque fait entrer les États-Unis en guerre en décembre 1941 ?", ["Pearl Harbor", "Midway", "Guadalcanal", "Les Philippines"], 0,
     "L'attaque de la base hawaïenne détruit une partie de la flotte américaine mais épargne les porte-avions, absents ce jour-là."],
    ["Quelle bataille marque le tournant du Pacifique en juin 1942 ?", ["Midway", "La mer de Corail", "Iwo Jima", "Okinawa"], 0,
     "Le Japon y perd quatre porte-avions en une journée. Il ne reprendra plus l'initiative stratégique.", 3],
  ]),

  notion("hm-etats-unis-19e", S, "Les États-Unis au XIXe siècle",
    "De l'achat de la Louisiane à la conquête de l'Ouest, de la guerre de Sécession à l'entrée dans le club des puissances.",
    "La question de l'esclavage traverse tout le siècle : chaque nouvel État admis relance l'équilibre entre Nord et Sud.",
    2, [
    ["À qui les États-Unis achètent-ils la Louisiane en 1803 ?", ["À la France de Napoléon", "À l'Espagne, qui l'avait cédée", "Au Mexique, alors espagnol", "À la Grande-Bretagne, après 1783"], 0,
     "Quinze millions de dollars pour un territoire qui double la superficie du pays. Napoléon y renonce faute de pouvoir le défendre."],
    ["Que désigne la Destinée manifeste ?", ["L'idée que les États-Unis doivent s'étendre jusqu'au Pacifique", "Le droit de vote universel des hommes blancs", "L'abolition progressive de l'esclavage dans les États du Nord", "La doctrine d'isolement vis-à-vis de l'Europe"], 0,
     "Formulée en 1845, elle sert à justifier l'expansion vers l'ouest et la guerre contre le Mexique."],
    ["Que perd le Mexique en 1848 ?", ["La Californie, le Nouveau-Mexique et les territoires alentour", "Le Texas seulement, annexé trois ans plus tôt", "La Floride, vendue aux États-Unis", "La Basse-Californie et la péninsule du Yucatán"], 0,
     "Le traité de Guadalupe Hidalgo ampute le Mexique de près de la moitié de son territoire."],
    ["Quel événement déclenche la ruée vers l'or de 1849 ?", ["La découverte d'or en Californie", "La découverte d'or dans le Klondike", "L'ouverture du Nevada", "La découverte d'argent au Colorado"], 0,
     "La population de la Californie passe de quelques milliers à plus de cent mille personnes en un an."],
    ["Quel est le motif immédiat de la sécession des États du Sud en 1860 ?", ["L'élection d'Abraham Lincoln", "L'abolition immédiate de l'esclavage", "Une crise économique", "Un conflit douanier avec l'Angleterre"], 0,
     "Lincoln s'opposait à l'extension de l'esclavage aux nouveaux territoires, non à son maintien là où il existait déjà."],
    ["Quelle bataille marque le tournant de la guerre de Sécession en 1863 ?", ["Gettysburg", "Bull Run, deux ans plus tôt", "Antietam, en 1862", "Shiloh"], 0,
     "La défaite de Lee met fin à l'offensive sudiste au Nord. Vicksburg tombe le lendemain, coupant la Confédération en deux."],
    ["Quel amendement abolit l'esclavage aux États-Unis ?", ["Le treizième", "Le quatorzième", "Le quinzième", "Le dixième"], 0,
     "Ratifié en décembre 1865, il est complété par le quatorzième sur la citoyenneté et le quinzième sur le droit de vote."],
    ["Que désignent les lois Jim Crow ?", ["La ségrégation raciale légale dans le Sud", "Les lois sur l'immigration chinoise", "La réforme agraire du Homestead Act", "Les lois antitrust contre les grands trusts"], 0,
     "Adoptées à partir des années 1870, elles organisent la séparation et durent jusqu'aux années 1960."],
    ["Qu'achèvent les États-Unis en 1869 ?", ["Le premier chemin de fer transcontinental", "Le canal de Panama, ouvert en 1914", "Le télégraphe transatlantique, posé en 1866", "Le pont de Brooklyn, inauguré en 1883"], 0,
     "La jonction se fait à Promontory Summit, dans l'Utah. Le voyage d'une côte à l'autre passe de six mois à une semaine."],
    ["Que gagnent les États-Unis à la guerre de 1898 contre l'Espagne ?", ["Cuba, Porto Rico, Guam et les Philippines", "Le Mexique et Cuba, arrachés à l'Espagne", "Hawaï seulement, annexé la même année", "Le Panama et sa zone de canal"], 0,
     "Le pays devient une puissance coloniale. Cuba obtient une indépendance étroitement encadrée.", 3],
  ]),

  notion("hm-genocide-crimes", S, "Les génocides du XXe siècle",
    "Un mot forgé en 1944, une convention de 1948, et des crimes qui ont changé le droit international.",
    "Le mot est plus récent qu'on ne croit : il naît en 1944, sous la plume d'un juriste polonais, et la convention de l'ONU le définit quatre ans plus tard.",
    3, [
    ["Qui forge le mot génocide en 1944 ?", ["Raphael Lemkin", "Hersch Lauterpacht", "Hannah Arendt", "Robert Jackson"], 0,
     "Juriste polonais réfugié aux États-Unis, il compose le mot du grec genos, la race, et du latin caedere, tuer."],
    ["Quand l'ONU adopte-t-elle la convention sur le génocide ?", ["En 1948", "En 1945", "En 1951", "En 1968"], 0,
     "Adoptée la veille de la Déclaration universelle des droits de l'homme, elle définit le génocide comme l'intention de détruire un groupe."],
    ["Quel génocide frappe les Arméniens de l'Empire ottoman ?", ["Celui de 1915-1916", "Celui de 1894-1896", "Celui de 1922", "Celui de 1909"], 0,
     "Déportations et massacres font entre huit cent mille et un million et demi de morts. La France l'a reconnu par une loi en 2001."],
    ["Quel procès juge les principaux responsables nazis en 1945-1946 ?", ["Le procès de Nuremberg", "Le procès de Tokyo", "Le procès Eichmann", "Le procès de Francfort"], 0,
     "Il crée les notions de crime contre la paix, crime de guerre et crime contre l'humanité, jugées par un tribunal international."],
    ["Où Adolf Eichmann est-il jugé en 1961 ?", ["À Jérusalem", "À Nuremberg", "À La Haye", "À Bonn"], 0,
     "Enlevé en Argentine par le Mossad, il est jugé et exécuté. Hannah Arendt tire de ce procès sa réflexion sur la banalité du mal."],
    ["Quel régime commet un génocide au Cambodge de 1975 à 1979 ?", ["Les Khmers rouges", "Le régime de Lon Nol", "L'armée vietnamienne", "Le Viêt-cong"], 0,
     "Environ un quart de la population meurt d'exécutions, de famine et de travail forcé sous Pol Pot."],
    ["Quel génocide a lieu au Rwanda en 1994 ?", ["Celui des Tutsi", "Celui des Hutu", "Celui des Twa", "Celui des Banyamulenge"], 0,
     "Environ huit cent mille personnes sont tuées en cent jours. Un tribunal international est créé à Arusha la même année."],
    ["Quel massacre européen de 1995 est qualifié de génocide par la justice internationale ?", ["Srebrenica", "Vukovar", "Sarajevo", "Mostar"], 0,
     "Plus de huit mille hommes et adolescents bosniaques y sont tués, dans une zone pourtant déclarée protégée par l'ONU."],
    ["Quelle juridiction permanente est créée en 1998 ?", ["La Cour pénale internationale", "La Cour internationale de justice", "Le Tribunal pour l'ex-Yougoslavie", "La Cour européenne des droits de l'homme"], 0,
     "Le statut de Rome la fonde ; elle siège à La Haye depuis 2002 et juge des individus, non des États."],
    ["Quelle est la différence entre crime contre l'humanité et génocide ?", ["Le génocide suppose l'intention de détruire un groupe comme tel", "Le génocide vise des civils, l'autre des militaires", "Le génocide est jugé en temps de guerre seulement", "Il n'y en a aucune en droit"], 0,
     "C'est l'intention destructrice visant un groupe national, ethnique, racial ou religieux qui distingue le génocide.", 3],
  ]),

  notion("hm-decolonisation-afrique", S, "Les indépendances africaines",
    "1960, l'année de l'Afrique : dix-sept États accèdent à l'indépendance. Avant et après, des chemins très différents.",
    "Distinguez les indépendances négociées, comme au Ghana, et celles arrachées par la guerre, comme en Algérie ou en Angola.",
    2, [
    ["Quel pays d'Afrique subsaharienne devient indépendant le premier, en 1957 ?", ["Le Ghana", "Le Nigeria", "Le Sénégal", "La Guinée"], 0,
     "Ancienne Côte-de-l'Or britannique, il prend le nom d'un empire médiéval. Kwame Nkrumah en est le premier dirigeant."],
    ["Quel pays refuse la Communauté française en 1958 ?", ["La Guinée", "Le Mali", "Le Sénégal", "Le Niger"], 0,
     "Sékou Touré déclare préférer la pauvreté dans la liberté à la richesse dans l'esclavage. L'aide française est brutalement retirée."],
    ["Combien d'États africains accèdent à l'indépendance en 1960 ?", ["Dix-sept", "Sept", "Vingt-cinq", "Douze"], 0,
     "D'où le nom d'année de l'Afrique. La majorité sont d'anciennes colonies françaises."],
    ["Quelle guerre d'indépendance oppose l'Algérie à la France de 1954 à 1962 ?", ["La guerre d'Algérie", "La guerre du Rif", "La révolte de Sétif", "La guerre de Kabylie"], 0,
     "Elle s'achève par les accords d'Évian. Elle a provoqué en France la chute de la IVe République."],
    ["Quelle crise secoue le Congo dès son indépendance en 1960 ?", ["La sécession du Katanga", "La guerre du Biafra", "La révolte des Mau Mau", "La crise du Shaba"], 0,
     "Patrice Lumumba, premier Premier ministre, est assassiné en 1961. L'ONU intervient militairement."],
    ["Quelle guerre civile déchire le Nigeria de 1967 à 1970 ?", ["La guerre du Biafra", "La guerre du Darfour", "La guerre des Grands Lacs", "La guerre du Tigré"], 0,
     "La sécession du Sud-Est, riche en pétrole, se solde par une famine qui bouleverse l'opinion mondiale et fait naître l'action humanitaire moderne."],
    ["Quel mouvement insurrectionnel kényan est réprimé par les Britanniques dans les années 1950 ?", ["La révolte des Mau Mau", "La révolte de Maji Maji", "La révolte des Zoulous", "La guerre des Ashanti"], 0,
     "La répression britannique fait des dizaines de milliers de morts. Le Kenya devient indépendant en 1963."],
    ["Quand les colonies portugaises d'Afrique deviennent-elles indépendantes ?", ["En 1975, après la révolution des Œillets", "En 1960", "En 1968", "En 1980"], 0,
     "La chute de la dictature à Lisbonne en 1974 précipite l'indépendance de l'Angola, du Mozambique, de la Guinée-Bissau et du Cap-Vert."],
    ["Quel régime sud-africain s'éteint avec les élections de 1994 ?", ["L'apartheid", "Le protectorat britannique", "Le régime boer", "La ségrégation du Natal"], 0,
     "Nelson Mandela, libéré en 1990 après vingt-sept ans de prison, devient président lors des premières élections multiraciales."],
    ["Quelle organisation continentale succède à l'OUA en 2002 ?", ["L'Union africaine", "La CEDEAO", "Le NEPAD", "La SADC"], 0,
     "L'Organisation de l'unité africaine, fondée en 1963, laisse place à une union dotée de plus larges compétences.", 3],
  ]),

  notion("hm-chute-urss", S, "La chute du bloc soviétique",
    "De l'arrivée de Gorbatchev en 1985 à la disparition de l'URSS en décembre 1991 : six ans qui redessinent l'Europe.",
    "Deux mots russes résument la tentative de réforme : l'un désigne la transparence, l'autre la refonte de l'économie. Ne les intervertis pas.",
    2, [
    ["Qui arrive au pouvoir en URSS en 1985 ?", ["Mikhaïl Gorbatchev", "Iouri Andropov", "Constantin Tchernenko", "Boris Eltsine"], 0,
     "À cinquante-quatre ans, il est le plus jeune dirigeant soviétique depuis Staline."],
    ["Que signifie perestroïka ?", ["Restructuration", "Transparence", "Ouverture", "Renouveau"], 0,
     "Elle désigne la réforme économique. La glasnost, elle, est la liberté d'expression et d'information."],
    ["Quelle catastrophe de 1986 ébranle la confiance dans le régime ?", ["Tchernobyl", "L'accident de Kychtym", "Le naufrage du Koursk", "L'explosion de Baïkonour"], 0,
     "Le silence initial des autorités, puis l'ampleur du désastre, nourrissent la demande de transparence."],
    ["Quel pays d'Europe de l'Est voit naître le syndicat Solidarność ?", ["La Pologne", "La Hongrie", "La Tchécoslovaquie", "La Roumanie"], 0,
     "Né aux chantiers de Gdansk en 1980, il est interdit sous la loi martiale avant de gagner les élections de 1989."],
    ["Quand le mur de Berlin tombe-t-il ?", ["Le 9 novembre 1989", "Le 3 octobre 1990", "Le 12 juin 1987", "Le 25 décembre 1991"], 0,
     "L'ouverture des postes-frontières résulte d'une annonce confuse d'un responsable est-allemand, suivie d'un afflux immédiat."],
    ["Comment appelle-t-on la transition tchécoslovaque de 1989 ?", ["La révolution de Velours", "La révolution des Œillets", "Le Printemps de Prague", "La révolution orange"], 0,
     "Sans violence, elle porte le dramaturge Václav Havel à la présidence en quelques semaines."],
    ["Quel dirigeant est renversé et exécuté en Roumanie en décembre 1989 ?", ["Nicolae Ceaușescu", "Todor Jivkov", "Erich Honecker", "Gustáv Husák"], 0,
     "C'est la seule transition violente d'Europe de l'Est cette année-là."],
    ["Quand les deux Allemagnes sont-elles réunifiées ?", ["Le 3 octobre 1990", "Le 9 novembre 1989", "Le 1er juillet 1990", "Le 31 décembre 1991"], 0,
     "La RDA adhère à la RFA selon l'article 23 de la Loi fondamentale. Le traité quatre plus deux règle les questions internationales."],
    ["Que se passe-t-il en août 1991 à Moscou ?", ["Un putsch conservateur échoue", "Gorbatchev démissionne", "L'URSS est dissoute", "Eltsine est élu président"], 0,
     "Boris Eltsine, debout sur un char, incarne la résistance. Le putsch accélère l'effondrement qu'il voulait empêcher."],
    ["Quand l'URSS cesse-t-elle officiellement d'exister ?", ["Le 26 décembre 1991", "Le 3 octobre 1990", "Le 12 juin 1990", "Le 1er janvier 1992"], 0,
     "Après la démission de Gorbatchev la veille, le Soviet suprême acte la dissolution. Quinze États indépendants lui succèdent.", 3],
  ]),

  notion("hm-inde-independance", S, "L'Inde de Gandhi à la partition",
    "Une indépendance obtenue sans guerre contre l'occupant, et payée par une partition qui déplace plus de dix millions de personnes.",
    "L'indépendance et la partition sont deux histoires parallèles, pas une seule : la méthode de Gandhi n'a pas empêché la seconde.",
    2, [
    ["Quel parti mène le mouvement pour l'indépendance indienne ?", ["Le Congrès national indien", "La Ligue musulmane", "Le Parti communiste indien", "Le Swaraj Party"], 0,
     "Fondé en 1885, il devient sous Gandhi un mouvement de masse et non plus un cercle de notables."],
    ["Quel principe Gandhi met-il au centre de son action ?", ["La non-violence", "La grève générale", "La lutte armée", "Le boycott parlementaire"], 0,
     "Ahimsa, la non-violence, et satyagraha, la force de la vérité, structurent sa stratégie politique."],
    ["Que fait Gandhi lors de la marche du sel en 1930 ?", ["Il défie le monopole britannique en récoltant du sel", "Il occupe le parlement de Delhi", "Il organise une grève générale des cheminots indiens", "Il brûle publiquement des étoffes anglaises"], 0,
     "Après 385 kilomètres à pied, il ramasse une poignée de sel sur la plage de Dandi. Le geste, illégal, est repris dans tout le pays."],
    ["Quel massacre de 1919 marque une rupture avec les Britanniques ?", ["Amritsar", "Calcutta", "Chauri Chaura", "Lahore"], 0,
     "Le général Dyer fait tirer sur une foule désarmée dans un jardin clos : au moins trois cent soixante-dix-neuf morts."],
    ["Qui dirige la Ligue musulmane et réclame un État séparé ?", ["Muhammad Ali Jinnah", "Jawaharlal Nehru, son rival", "Sardar Patel, du Congrès", "Maulana Azad, resté au Congrès"], 0,
     "Longtemps partisan de l'unité, il se convertit à l'idée du Pakistan dans les années 1940."],
    ["Quand l'Inde et le Pakistan deviennent-ils indépendants ?", ["En août 1947", "En 1945, à la fin de la guerre", "En 1950, à la Constitution", "En 1935"], 0,
     "La partition est décidée en quelques semaines, sur des frontières tracées par un juriste britannique arrivé sur place cinq semaines plus tôt."],
    ["Quel est le bilan humain de la partition ?", ["Des centaines de milliers de morts et plus de dix millions de déplacés", "Quelques milliers de morts seulement", "Aucune violence notable de part et d'autre", "Deux millions de déplacés, surtout au Pendjab"], 0,
     "Les violences intercommunautaires accompagnent des échanges de population d'une ampleur sans précédent."],
    ["Qui devient le premier Premier ministre de l'Inde ?", ["Jawaharlal Nehru", "Sardar Patel, son ministre", "Rajendra Prasad, premier président", "Indira Gandhi, sa fille"], 0,
     "Il reste au pouvoir jusqu'à sa mort en 1964 et oriente l'Inde vers le non-alignement et la planification."],
    ["Quand Gandhi est-il assassiné ?", ["En janvier 1948", "En août 1947", "En 1950", "En 1946"], 0,
     "Il est tué par un nationaliste hindou qui lui reprochait sa conciliation envers les musulmans."],
    ["Quel territoire reste disputé entre l'Inde et le Pakistan depuis 1947 ?", ["Le Cachemire", "Le Pendjab, déjà partagé", "Le Bengale, divisé lui aussi", "Le Gujarat, à l'ouest"], 0,
     "Le maharajah hindou d'un État à majorité musulmane choisit l'Inde. Trois guerres en ont découlé.", 3],
  ]),

  notion("hm-organisations-internationales", S, "Les organisations internationales et leur histoire",
    "De la Société des Nations à l'OMC, un siècle d'institutions inventées pour éviter la guerre, réguler le commerce ou soigner.",
    "La SDN échoue faute de moyens et d'adhésion américaine ; l'ONU est conçue pour corriger ces deux défauts.",
    2, [
    ["Quelle organisation naît du traité de Versailles en 1919 ?", ["La Société des Nations", "L'Organisation des Nations unies", "La Croix-Rouge internationale", "Le Bureau international du travail seul"], 0,
     "Voulue par le président Wilson, elle ne sera jamais rejointe par les États-Unis, dont le Sénat refuse de ratifier le traité."],
    ["Quand l'ONU est-elle fondée ?", ["En 1945", "En 1919", "En 1948", "En 1950"], 0,
     "La charte est signée à San Francisco en juin 1945 par cinquante et un États."],
    ["Quelle agence de l'ONU s'occupe de la santé ?", ["L'OMS", "L'UNICEF", "Le PNUD", "La FAO"], 0,
     "Créée en 1948, elle a coordonné l'éradication de la variole, déclarée en 1980."],
    ["Quelle organisation régit le commerce mondial depuis 1995 ?", ["L'OMC", "Le GATT", "La CNUCED", "L'OCDE"], 0,
     "Elle succède au GATT de 1947 et dispose d'un organe de règlement des différends, ce qui la distingue de son prédécesseur."],
    ["Quelle institution est créée à Bretton Woods en 1944 avec la Banque mondiale ?", ["Le Fonds monétaire international", "La Banque des règlements internationaux", "L'OCDE, créée à Paris en 1961", "La BCE, bien plus tard"], 0,
     "Les accords organisent un système de changes fixes adossé au dollar, abandonné en 1971."],
    ["Quelle alliance militaire est fondée en 1949 ?", ["L'OTAN", "Le pacte de Varsovie", "L'UEO", "Le pacte de Bagdad"], 0,
     "Son article 5 pose qu'une attaque contre l'un est une attaque contre tous. Il n'a été invoqué qu'une fois, après le 11 septembre 2001."],
    ["Quelle organisation regroupe les pays exportateurs de pétrole depuis 1960 ?", ["L'OPEP", "L'AIE", "L'OCDE", "Le G20"], 0,
     "Son embargo de 1973 provoque le premier choc pétrolier et fait quadrupler les prix."],
    ["Que crée la conférence de Rio en 1992 ?", ["La convention-cadre sur les changements climatiques", "Le protocole de Kyoto", "L'accord de Paris", "Le GIEC"], 0,
     "La convention adoptée à Rio rend possibles les conférences annuelles, dites COP, dont sont issus Kyoto puis Paris.", 3],
  ]),

  notion("hm-routes-echanges", S, "Les grandes routes commerciales de l'histoire",
    "Soie, sel, épices, esclaves : les routes ont fait circuler des marchandises, mais aussi des religions, des techniques et des maladies.",
    "Une route commerciale transporte toujours plus que des marchandises : idées, épidémies et alphabets suivent les caravanes.",
    2, [
    ["Que transportait principalement la route de la soie ?", ["De la soie, mais aussi des idées et des techniques", "Uniquement de la soie", "Des esclaves", "De l'or africain"], 0,
     "Le bouddhisme, le papier et la poudre à canon ont voyagé sur ces mêmes pistes, du Ier siècle av. J.-C. au XVe siècle."],
    ["Quel produit les caravanes transsahariennes échangeaient-elles contre l'or ?", ["Le sel", "Le fer", "Le blé", "Le cuivre"], 0,
     "Extrait à Taghaza, le sel valait presque son poids en or dans les régions sahéliennes qui en manquaient."],
    ["Quelle cité italienne domine le commerce avec l'Orient au Moyen Âge ?", ["Venise", "Florence", "Naples", "Milan"], 0,
     "Sa position et ses privilèges à Byzance en font la plaque tournante des épices. Gênes lui dispute cette place."],
    ["Quelle ligue commerciale domine la mer du Nord et la Baltique ?", ["La Hanse", "La ligue de Cambrai", "L'union de Kalmar", "La ligue lombarde"], 0,
     "Réseau de villes marchandes du XIIe au XVIIe siècle, elle avait ses comptoirs de Novgorod à Londres."],
    ["Quel produit motive les grandes découvertes portugaises ?", ["Les épices d'Asie", "Le coton indien", "L'or d'Amérique", "La porcelaine chinoise"], 0,
     "Poivre, girofle et muscade valaient des fortunes en Europe et transitaient par des intermédiaires nombreux."],
    ["Quel navigateur atteint l'Inde par la mer en 1498 ?", ["Vasco de Gama", "Christophe Colomb", "Bartolomeu Dias", "Fernand de Magellan"], 0,
     "Il contourne l'Afrique et ouvre la route maritime des épices, qui ruine progressivement le commerce vénitien."],
    ["Qu'appelle-t-on commerce triangulaire ?", ["Le trafic entre Europe, Afrique et Amérique fondé sur la traite", "Le commerce entre trois ports européens", "Les échanges entre Asie, Afrique et Europe", "Le troc entre colonies"], 0,
     "Marchandises vers l'Afrique, captifs vers l'Amérique, denrées coloniales vers l'Europe : plus de douze millions de personnes déportées."],
    ["Quel canal ouvert en 1869 raccourcit la route vers l'Asie ?", ["Le canal de Suez", "Le canal de Panama", "Le canal de Kiel", "Le canal de Corinthe"], 0,
     "Il évite le contournement de l'Afrique et réduit de moitié la distance entre Londres et Bombay."],
    ["Quel canal ouvert en 1914 relie l'Atlantique au Pacifique ?", ["Le canal de Panama", "Le canal de Suez", "Le canal de Nicaragua", "Le détroit de Magellan"], 0,
     "Un premier chantier français échoue dans les années 1880 ; les États-Unis achèvent l'ouvrage après avoir soutenu l'indépendance du Panama."],
    ["Quelle innovation du XXe siècle transforme le transport maritime ?", ["Le conteneur", "Le moteur diesel", "Le radar", "Le pavillon de complaisance"], 0,
     "Normalisé dans les années 1960, il réduit les coûts de manutention dans des proportions telles qu'il rend possible la mondialisation industrielle.", 3],
  ]),
];
