/**
 * Institutions & Économie — treize notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Institutions & Économie";

export const CG_INSTITUTIONS_ECONOMIE: SeedSkill[] = [
  notion("ie-collectivites", S, "Les collectivités territoriales françaises",
    "Communes, départements, régions : qui décide de quoi, et depuis quand.",
    "La clause de compétence générale n'existe plus que pour les communes depuis 2015.",
    2, [
    ["Combien la France compte-t-elle environ de communes ?", ["Environ trente-cinq mille", "Environ dix mille", "Environ cent mille", "Environ cinq mille"], 0,
     "Un record en Europe, hérité des paroisses d'Ancien Régime. Les fusions récentes ont réduit ce nombre à la marge."],
    ["Qui élit le maire d'une commune ?", ["Le conseil municipal", "Les habitants directement", "Le préfet", "Le conseil départemental"], 0,
     "Les habitants élisent les conseillers municipaux, qui désignent ensuite le maire parmi eux."],
    ["Quelle collectivité gère les collèges ?", ["Le département", "La région", "La commune", "L'État seul, par le rectorat"], 0,
     "La région gère les lycées, la commune les écoles primaires."],
    ["Quelle collectivité est chargée des lycées et des transports régionaux ?", ["La région", "Le département", "La commune", "l'intercommunalité"], 0,
     "Elle a aussi la compétence du développement économique et de la formation professionnelle."],
    ["Quelle est la principale compétence sociale du département ?", ["l'action sociale, dont le revenu de solidarité active", "Le logement social et son attribution", "L'assurance maladie et le remboursement de tous les soins", "Les retraites et les pensions de réversion"], 0,
     "Il gère aussi l'aide sociale à l'enfance et l'allocation personnalisée d'autonomie."],
    ["Combien de régions métropolitaines la France compte-t-elle depuis 2016 ?", ["Treize", "Vingt-deux", "Dix-huit", "Seize"], 0,
     "La loi de 2015 a fusionné les vingt-deux régions métropolitaines antérieures. S'y ajoutent cinq régions d'outre-mer."],
    ["Que représente le préfet dans un département ?", ["l'État", "Le conseil départemental", "La région", "Le gouvernement local élu"], 0,
     "Nommé en conseil des ministres, il contrôle la légalité des actes des collectivités."],
    ["Quelle est la forme la plus intégrée de coopération entre communes ?", ["La métropole", "La communauté de communes", "Le syndicat intercommunal", "Le pays"], 0,
     "Communauté de communes, communauté d'agglomération, communauté urbaine puis métropole : les compétences transférées augmentent à chaque échelon."],
    ["En quelle année la première grande loi de décentralisation a-t-elle été votée ?", ["1982", "1958", "1972", "1992"], 0,
     "La loi Defferre supprime la tutelle a priori du préfet et transfère l'exécutif départemental au président du conseil général."],
    ["Que dit la Constitution française de l'organisation de la République depuis 2003 ?", ["Elle est décentralisée", "Elle est fédérale", "Elle est régionalisée", "Elle est unitaire et centralisée"], 0,
     "La révision de 2003 a inscrit le caractère décentralisé à l'article premier, sans rompre avec le caractère unitaire.", 3],
  ]),

  notion("ie-justice-france", S, "L'organisation de la justice en France",
    "Deux ordres, plusieurs degrés, et une distinction entre juger l'administration et juger les personnes.",
    "L'ordre judiciaire juge les litiges entre personnes, l'ordre administratif les litiges avec l'administration.",
    2, [
    ["Quelles sont les deux grandes branches de la justice française ?", ["l'ordre judiciaire et l'ordre administratif", "Le contentieux civil et le contentieux pénal des tribunaux", "Le droit privé et le droit constitutionnel écrit", "Les juridictions ordinaires et celles d'exception"], 0,
     "La séparation remonte à la Révolution, qui interdit aux juges de connaître des actes de l'administration."],
    ["Quelle est la plus haute juridiction de l'ordre administratif ?", ["Le Conseil d'État", "La Cour de cassation", "Le tribunal administratif", "La Cour des comptes"], 0,
     "Il est à la fois juge suprême de l'administration et conseiller du gouvernement pour la rédaction des textes."],
    ["Quelle juridiction juge les crimes en France ?", ["La cour d'assises", "Le tribunal correctionnel", "Le tribunal de police", "La cour d'appel"], 0,
     "Les délits relèvent du tribunal correctionnel, les contraventions du tribunal de police."],
    ["Qu'est-ce que le principe du double degré de juridiction ?", ["La possibilité de faire rejuger une affaire en appel", "Le droit d'être assisté par deux avocats au procès", "La présence obligatoire de deux juges à l'audience", "Le recours successif devant les deux ordres de juridiction"], 0,
     "Il ne vaut pas pour toutes les affaires : les très petits litiges civils y échappent."],
    ["Que signifie la présomption d'innocence ?", ["Toute personne est réputée innocente tant qu'elle n'a pas été jugée coupable", "Le doute profite toujours à l'accusé au cours du procès", "L'accusé n'a jamais à se défendre lui-même devant le juge", "La charge de la preuve appartient entièrement à la défense et non au parquet"], 0,
     "Elle figure dans la Déclaration de 1789 et implique que la charge de la preuve pèse sur l'accusation."],
    ["Quel magistrat représente la société et requiert une peine ?", ["Le procureur de la République", "Le juge d'instruction du tribunal", "Le juge des libertés et de la détention", "Le président du tribunal correctionnel"], 0,
     "Il appartient au parquet, ou ministère public, par opposition aux magistrats du siège qui jugent."],
    ["Quel juge enquête sur les affaires les plus complexes ?", ["Le juge d'instruction", "Le procureur", "Le juge des enfants", "Le juge d'application des peines"], 0,
     "Il instruit à charge et à décharge. Le nombre d'affaires qui lui sont confiées a fortement diminué."],
    ["Qu'est-ce que la question prioritaire de constitutionnalité ?", ["La possibilité de contester la constitutionnalité d'une loi déjà en vigueur", "Le contrôle d'une loi avant sa promulgation par le président", "Un recours ouvert devant la Cour européenne des droits de l'homme à Strasbourg", "Une saisine du Conseil constitutionnel réservée au seul Président"], 0,
     "Introduite en 2008 et entrée en vigueur en 2010, elle a ouvert le contrôle de constitutionnalité aux justiciables."],
    ["Quelle juridiction tranche les conflits de compétence entre les deux ordres ?", ["Le Tribunal des conflits", "Le Conseil constitutionnel", "La Cour de cassation", "Le Conseil d'État"], 0,
     "Composé à parité de membres des deux ordres, il désigne la juridiction compétente sans juger le fond.", 3],
  ]),

  notion("ie-securite-sociale", S, "La protection sociale française",
    "Quatre branches, un financement par cotisations et impôts, et un modèle né en 1945.",
    "La Sécurité sociale n'est pas l'État : elle est gérée par des caisses, sous tutelle publique.",
    2, [
    ["En quelle année la Sécurité sociale française est-elle créée ?", ["1945", "1936", "1958", "1968"], 0,
     "Les ordonnances d'octobre 1945 s'inspirent du programme du Conseil national de la Résistance."],
    ["Quel ministre communiste porte la création de la Sécurité sociale ?", ["Ambroise Croizat", "Maurice Thorez, secrétaire général", "Pierre Laroque, haut fonctionnaire", "Jacques Duclos, dirigeant communiste"], 0,
     "Pierre Laroque, haut fonctionnaire, en est l'architecte technique."],
    ["Quelles sont les branches historiques de la Sécurité sociale ?", ["Maladie, famille, retraite, accidents du travail", "Maladie, chômage, retraite et logement social", "Santé, éducation, retraite et politique familiale", "Maladie, famille, chômage et dépendance des âgés"], 0,
     "Une cinquième branche, l'autonomie, a été créée en 2020. Le chômage relève d'un régime distinct."],
    ["Qu'est-ce que la CSG ?", ["Un impôt affecté au financement de la protection sociale", "Une cotisation patronale assise sur l'ensemble des salaires versés", "Une taxe prélevée sur les contrats des mutuelles santé", "Une contribution volontaire versée par les seuls assurés"], 0,
     "Créée en 1991, elle a progressivement remplacé une partie des cotisations salariales."],
    ["Qui gère l'assurance chômage en France ?", ["Un régime paritaire distinct de la Sécurité sociale", "La branche maladie", "L'État directement, par le ministère du Travail et ses services", "Les régions, depuis la décentralisation"], 0,
     "Il est piloté par les partenaires sociaux, sous un encadrement croissant de l'État depuis 2018."],
    ["Qu'est-ce que le ticket modérateur ?", ["La part des frais de santé qui reste à la charge de l'assuré", "Une avance de frais que l'assuré doit régler au médecin", "Un forfait hospitalier dû pour chaque journée passée à l'hôpital", "La part des frais que la mutuelle rembourse à l'assuré"], 0,
     "Il est souvent pris en charge par une complémentaire santé."],
    ["Qu'est-ce que le RSA ?", ["Un revenu minimum versé sous conditions de ressources", "Une allocation chômage versée après la perte d'un emploi salarié", "Une pension d'invalidité versée après un accident", "Une aide au logement versée par la caisse d'allocations familiales"], 0,
     "Créé en 2009, il a remplacé le revenu minimum d'insertion instauré en 1988."],
    ["Quelle réforme de 1999 étend la couverture maladie aux plus démunis ?", ["La couverture maladie universelle", "L'aide médicale d'État", "La complémentaire santé solidaire", "Le tiers payant généralisé"], 0,
     "Elle a été remplacée en 2016 par la protection universelle maladie, qui automatise l'affiliation."],
    ["Que représente environ la protection sociale dans le PIB français ?", ["Environ trente pour cent", "Environ dix pour cent", "Environ cinquante pour cent", "Environ vingt pour cent"], 0,
     "C'est l'un des niveaux les plus élevés de l'OCDE, retraites et santé en constituant l'essentiel.", 3],
  ]),

  notion("ie-monnaie-banques", S, "La monnaie et les banques",
    "Qui crée la monnaie, à quoi sert une banque centrale, et pourquoi l'inflation se pilote par les taux.",
    "Ce sont les banques commerciales qui créent l'essentiel de la monnaie, en accordant des crédits.",
    2, [
    ["Qui crée l'essentiel de la monnaie en circulation ?", ["Les banques commerciales, par le crédit", "La banque centrale, et elle seule", "L'État, par l'intermédiaire du Trésor public", "L'imprimerie qui fabrique les billets"], 0,
     "Les billets ne représentent qu'une faible part de la masse monétaire."],
    ["Quel est le principal objectif de la Banque centrale européenne ?", ["La stabilité des prix", "Le plein-emploi", "La croissance", "L'équilibre budgétaire des États"], 0,
     "Elle vise une inflation proche de deux pour cent à moyen terme. La Réserve fédérale américaine a un double mandat."],
    ["Que se passe-t-il quand une banque centrale relève ses taux directeurs ?", ["Le crédit devient plus cher, ce qui freine la demande", "La monnaie se déprécie mécaniquement", "L'épargne devient moins rémunératrice", "L'inflation augmente"], 0,
     "C'est l'outil principal de lutte contre l'inflation, au prix d'un ralentissement de l'activité."],
    ["Comment mesure-t-on concrètement la hausse générale des prix ?", ["Par un indice des prix à la consommation calculé sur un panier de biens", "Par la moyenne des prix de gros relevés chaque mois chez les producteurs", "Par la variation du salaire moyen d'une année sur l'autre", "Par le volume de monnaie en circulation dans l'économie"], 0,
     "Le panier est pondéré selon les dépenses réelles des ménages et révisé chaque année."],
    ["Qu'est-ce que la déflation ?", ["Une baisse générale et durable des prix", "Un simple ralentissement du rythme de l'inflation", "Une réduction de la dette publique de l'État", "Une baisse de la masse monétaire en circulation"], 0,
     "Elle est redoutée car elle incite à repousser les achats, ce qui entretient la baisse de l'activité."],
    ["Combien de pays utilisent l'euro comme monnaie officielle dans la zone euro ?", ["Vingt et un", "Vingt-sept, comme l'Union européenne", "Dix-neuf seulement", "Quinze au total"], 0,
     "La Croatie l'a adopté en 2023 et la Bulgarie en 2026, portant la zone euro à vingt et un États membres de l'Union."],
    ["Qu'est-ce que le taux de change ?", ["Le prix d'une monnaie exprimé dans une autre", "Le taux d'intérêt pratiqué à l'étranger", "La commission prélevée par un bureau de change", "Le taux d'inflation comparé entre deux pays"], 0,
     "Un change flottant varie librement sur les marchés ; un change fixe est maintenu par la banque centrale."],
    ["Qu'est-ce que l'assouplissement quantitatif ?", ["l'achat massif de titres par une banque centrale pour injecter des liquidités", "Une baisse des réserves obligatoires que les banques déposent à la banque centrale", "Un allégement des règles prudentielles imposées aux banques", "Une réduction des taux directeurs jusqu'au niveau zéro"], 0,
     "Employé massivement après 2008 et pendant la pandémie, il gonfle le bilan de la banque centrale."],
    ["Qu'est-ce qu'une crise de liquidité bancaire ?", ["Une banque solvable ne parvient plus à se financer à court terme", "Une banque n'a plus assez de fonds propres pour couvrir ses pertes", "Les clients de la banque cessent de rembourser leurs crédits", "La banque centrale refuse de lui accorder le moindre prêt"], 0,
     "C'est le mécanisme des paniques bancaires : la banque possède des actifs, mais ne peut les vendre assez vite.", 3],
  ]),

  notion("ie-entreprise-travail", S, "L'entreprise et le monde du travail",
    "Formes juridiques, contrat de travail, représentation du personnel : le cadre dans lequel on travaille.",
    "La différence entre salarié et indépendant tient au lien de subordination, pas au mode de rémunération.",
    2, [
    ["Qu'est-ce qui caractérise juridiquement un contrat de travail ?", ["Le lien de subordination", "Le versement d'un salaire", "L'existence d'un écrit", "La durée déterminée"], 0,
     "C'est ce critère qui permet de requalifier certaines prestations indépendantes en contrat de travail."],
    ["Quelle est la forme de contrat de droit commun en France ?", ["Le contrat à durée indéterminée", "Le contrat à durée déterminée renouvelable", "L'intérim par agence", "Le contrat de mission d'intérim"], 0,
     "Le contrat à durée déterminée est l'exception et doit reposer sur un motif prévu par la loi."],
    ["Quelle est la durée légale du travail hebdomadaire en France ?", ["Trente-cinq heures", "Trente-neuf heures", "Quarante heures", "Trente-sept heures"], 0,
     "C'est un seuil de déclenchement des heures supplémentaires, pas un plafond de travail."],
    ["Qu'est-ce qu'une convention collective ?", ["Un accord de branche qui complète le code du travail", "Un contrat conclu entre l'entreprise et l'État employeur", "Un règlement intérieur négocié avec les représentants du personnel", "Un accord européen fixant les règles communes du travail"], 0,
     "Elle ne peut être moins favorable que la loi sur les matières d'ordre public, mais peut l'être davantage."],
    ["Quelle instance représente les salariés dans les entreprises d'au moins onze salariés ?", ["Le comité social et économique", "Le comité d'entreprise", "Les délégués du personnel", "Le conseil de prud'hommes"], 0,
     "Créé en 2017, il a fusionné les trois anciennes instances de représentation."],
    ["Quelle juridiction tranche les litiges entre employeur et salarié ?", ["Le conseil de prud'hommes", "Le tribunal de commerce", "Le tribunal judiciaire", "Le tribunal administratif"], 0,
     "Il est paritaire : ses juges sont élus, moitié employeurs, moitié salariés, et ne sont pas des magistrats professionnels."],
    ["Quelle est la différence entre une SARL et une SA ?", ["La SA est conçue pour de grandes structures et un actionnariat large", "La SARL est réservée aux seules activités de commerce", "La SA peut être créée sans aucun capital minimum", "La SARL ne peut jamais compter plus d'un seul associé, contrairement à la SA"], 0,
     "La SA impose un capital minimum de trente-sept mille euros et un conseil d'administration."],
    ["Qu'est-ce qu'une entreprise individuelle ?", ["Une activité exercée par une personne physique sans société", "Une société commerciale ne comptant qu'un seul et unique associé", "Une entreprise employant moins de dix salariés au total", "Une jeune entreprise innovante en cours de création"], 0,
     "Depuis 2022, le patrimoine personnel de l'entrepreneur est protégé de plein droit."],
    ["Qu'est-ce que le chômage partiel, ou activité partielle ?", ["Une réduction d'activité indemnisée par l'État pour éviter les licenciements", "Un temps partiel imposé au salarié par son employeur", "Une rupture progressive du contrat de travail étalée sur plusieurs mois de préavis", "Un congé sans solde accordé à la demande du salarié"], 0,
     "Massivement utilisé en 2020, il a limité la hausse du chômage pendant la crise sanitaire."],
    ["Qu'est-ce que la rupture conventionnelle ?", ["Une rupture du contrat d'un commun accord ouvrant droit au chômage", "Un licenciement négocié qui n'ouvre droit à aucune indemnité de départ", "Une démission ouvrant malgré tout droit à une indemnité", "Une fin de période d'essai décidée par l'une des deux parties"], 0,
     "Créée en 2008, elle représente aujourd'hui une part importante des fins de contrat à durée indéterminée.", 3],
  ]),

  notion("ie-commerce-mondial", S, "Le commerce international",
    "Avantages comparatifs, balance commerciale, accords multilatéraux : ce qui circule et pourquoi.",
    "Un déficit commercial n'est pas une dette : c'est un solde de flux sur une période.",
    2, [
    ["Quelle organisation régule le commerce mondial depuis 1995 ?", ["l'Organisation mondiale du commerce", "Le Fonds monétaire international, à Washington", "La Banque mondiale, à Washington", "L'OCDE, organisation des pays développés"], 0,
     "Elle succède au GATT, un accord signé en 1947 mais dépourvu de personnalité juridique."],
    ["Qu'est-ce que la balance commerciale ?", ["La différence entre exportations et importations de biens", "L'ensemble des flux financiers entrant et sortant d'un pays", "La dette extérieure nette contractée par le pays", "Le solde budgétaire annuel de l'État"], 0,
     "La balance des paiements est plus large : elle inclut services, revenus et mouvements de capitaux."],
    ["Qui formule la théorie des avantages comparatifs ?", ["David Ricardo", "Adam Smith", "John Maynard Keynes", "Friedrich List"], 0,
     "En 1817 : même un pays moins productif partout a intérêt à se spécialiser là où son désavantage est le plus faible."],
    ["Qu'est-ce qu'un droit de douane ?", ["Une taxe sur les produits importés", "Un quota d'importation", "Une norme technique", "Une taxe à l'exportation uniquement"], 0,
     "C'est l'instrument protectionniste le plus ancien. Il renchérit le produit étranger pour protéger le producteur local."],
    ["Qu'est-ce qu'une barrière non tarifaire ?", ["Une norme ou une procédure qui entrave l'importation sans taxe", "Un droit de douane particulièrement élevé à l'entrée du territoire", "Un embargo total décrété contre un pays exportateur", "Une subvention versée aux entreprises exportatrices"], 0,
     "Normes sanitaires, quotas et formalités administratives en sont des exemples fréquents."],
    ["Quel accord commercial lie les États-Unis, le Mexique et le Canada depuis 2020 ?", ["l'ACEUM", "l'ALENA", "Le Mercosur", "Le CETA"], 0,
     "Il remplace l'ALENA, en vigueur depuis 1994, avec des règles renforcées sur l'automobile et le travail."],
    ["Quel accord commercial lie l'Union européenne et le Canada ?", ["Le CETA", "Le Mercosur", "Le TAFTA", "l'accord de Cotonou"], 0,
     "Signé en 2016 et appliqué provisoirement depuis 2017, il n'est pas ratifié par tous les États membres."],
    ["Quel pays est le premier exportateur mondial de marchandises ?", ["La Chine", "Les États-Unis", "l'Allemagne", "Le Japon"], 0,
     "Elle a dépassé l'Allemagne en 2009. Les États-Unis restent premiers pour les services."],
    ["Qu'appelle-t-on chaîne de valeur mondiale ?", ["La répartition des étapes de production d'un bien entre plusieurs pays", "Le circuit de distribution d'un produit jusqu'au consommateur", "La hiérarchie des fournisseurs d'une grande entreprise", "L'ensemble des marges commerciales prélevées tout au long du circuit de vente"], 0,
     "Un téléphone conçu, fabriqué et assemblé dans plusieurs pays traverse plusieurs fois les frontières avant sa vente."],
    ["Qu'est-ce que le dumping commercial ?", ["Vendre à l'étranger en dessous du prix pratiqué sur le marché intérieur", "Subventionner les exportations d'un secteur pour gagner des parts de marché", "Fermer complètement son marché intérieur aux importations", "Dévaluer sa monnaie pour rendre ses produits moins chers"], 0,
     "L'OMC autorise des droits antidumping en riposte, à condition de prouver le préjudice.", 3],
  ]),

  notion("ie-croissance-inegalites", S, "Croissance, richesse et inégalités",
    "Ce que le PIB mesure, ce qu'il ignore, et comment on décrit la répartition d'un revenu national.",
    "Le PIB mesure une production marchande, pas un bien-être : il compte les dégâts réparés comme de la richesse.",
    2, [
    ["Que mesure le produit intérieur brut ?", ["La valeur des biens et services produits sur un territoire en un an", "La richesse totale accumulée par un pays depuis le début de son histoire", "Le revenu moyen des habitants du territoire considéré", "Les dépenses de l'État et des administrations publiques"], 0,
     "Il compte la production marchande et la production non marchande évaluée à son coût."],
    ["Quelle grande critique adresse-t-on au PIB ?", ["Il ignore le bénévolat, le travail domestique et les dégâts environnementaux", "Il surestime la contribution des services marchands à la production", "Il ne tient aucun compte de la hausse générale des prix d'une année sur l'autre", "Il ne s'applique qu'aux pays riches déjà industrialisés"], 0,
     "Une marée noire augmente le PIB par les dépenses de dépollution. Le PIB par habitant corrige seulement la taille de la population."],
    ["Que vaut l'indice de Gini dans une société d'égalité parfaite ?", ["Zéro", "Un", "Cinquante", "Cent"], 0,
     "Il vaut un — ou cent, exprimé en pourcentage — quand une seule personne détient tout."],
    ["Qu'est-ce que l'indice de développement humain ?", ["Un indicateur combinant santé, éducation et revenu", "Le PIB d'un pays corrigé de l'inflation annuelle", "Un indice de bonheur déclaré par les habitants eux-mêmes", "Une mesure de la seule espérance de vie à la naissance"], 0,
     "Créé par le PNUD en 1990 sous l'impulsion d'Amartya Sen et Mahbub ul Haq, pour dépasser le seul PIB."],
    ["Comment définit-on le seuil de pauvreté monétaire en France ?", ["Soixante pour cent du niveau de vie médian", "Le montant du revenu de solidarité active", "Le SMIC calculé pour un mi-temps", "Un revenu fixe réévalué chaque année sur l'inflation"], 0,
     "C'est une définition relative : elle mesure l'écart à la société, pas la survie matérielle."],
    ["Qu'est-ce que le pouvoir d'achat ?", ["La quantité de biens qu'un revenu permet d'acheter", "Le revenu disponible brut du ménage une fois les impôts payés", "Le salaire net perçu chaque mois", "Le montant de l'épargne mise de côté"], 0,
     "Il progresse si le revenu augmente plus vite que les prix. C'est un rapport, pas un montant."],
    ["Qu'est-ce que la productivité du travail ?", ["La production rapportée à la quantité de travail employée", "Le nombre total d'heures travaillées dans l'ensemble de l'économie", "Le taux d'emploi de la population active", "Le rendement du capital investi par les entreprises"], 0,
     "Elle est le principal moteur de long terme de la hausse du niveau de vie."],
    ["Quel économiste a popularisé l'étude des inégalités par les données fiscales dans les années 2010 ?", ["Thomas Piketty", "Joseph Stiglitz", "Paul Krugman", "Amartya Sen"], 0,
     "Le Capital au XXIe siècle, paru en 2013, exploite des séries historiques de déclarations d'impôts."],
    ["Qu'appelle-t-on la courbe de Kuznets ?", ["l'hypothèse que les inégalités croissent puis décroissent avec le développement", "La relation entre le niveau du chômage et celui de l'inflation dans une économie", "Le lien entre la croissance et le niveau de la dette publique", "La répartition des revenus par décile au sein de la population"], 0,
     "Formulée en 1955, elle est très discutée : la remontée des inégalités depuis 1980 la contredit largement."],
    ["Que décrit la courbe de Phillips ?", ["Une relation inverse entre chômage et inflation", "Le lien entre la croissance et la création d'emplois", "L'évolution des salaires réels au cours du cycle", "Le rapport entre l'épargne et l'investissement"], 0,
     "Observée en 1958, elle s'est démentie lors de la stagflation des années 1970, où chômage et inflation ont monté ensemble.", 3],
  ]),

  notion("ie-budget-etat", S, "Le budget de l'État et la dette publique",
    "Recettes, dépenses, déficit, dette : quatre notions souvent confondues.",
    "Le déficit est un flux annuel, la dette un stock accumulé : combler le déficit ne rembourse pas la dette.",
    2, [
    ["Quel texte fixe chaque année les recettes et dépenses de l'État ?", ["La loi de finances", "La loi de programmation", "Le projet de loi de règlement seul", "La loi organique"], 0,
     "Elle est votée à l'automne pour l'année suivante et peut être corrigée par des lois de finances rectificatives."],
    ["Quel est le premier impôt en recettes pour l'État français ?", ["La taxe sur la valeur ajoutée", "L'impôt sur le revenu des personnes", "L'impôt sur les sociétés", "La taxe foncière sur le bâti"], 0,
     "La TVA rapporte plus que l'impôt sur le revenu. C'est un impôt sur la consommation, donc peu progressif."],
    ["Quelle différence y a-t-il entre déficit et dette ?", ["Le déficit est un flux annuel, la dette un stock cumulé", "Le déficit concerne l'État et la dette les seules collectivités", "La dette est simplement un déficit déjà remboursé", "Il n'existe aucune différence comptable entre les deux"], 0,
     "Un déficit réduit mais toujours positif fait encore croître la dette."],
    ["Quel plafond de déficit public le traité de Maastricht fixe-t-il ?", ["Trois pour cent du PIB", "Un pour cent du PIB annuel", "Cinq pour cent du PIB", "Zéro, l'équilibre strict"], 0,
     "Il fixe aussi un plafond de dette à soixante pour cent du PIB. Les règles ont été suspendues puis réformées après 2020."],
    ["Qu'est-ce qu'un impôt progressif ?", ["Son taux augmente avec le montant imposé", "Son montant augmente automatiquement chaque année", "Il est prélevé par tranches de montant égal", "Son taux reste proportionnel au revenu"], 0,
     "L'impôt sur le revenu français est progressif par tranches : seule la fraction dans la tranche est taxée à son taux."],
    ["Qu'est-ce que la TVA ?", ["Un impôt indirect sur la consommation", "Un impôt assis sur les bénéfices des sociétés", "Une cotisation sociale prélevée sur le salaire", "Une taxe sur le patrimoine des ménages"], 0,
     "Inventée en France par Maurice Lauré en 1954, elle a été adoptée dans plus de cent cinquante pays."],
    ["Que finance principalement la dépense publique française ?", ["La protection sociale", "La défense nationale", "L'éducation et la recherche", "Les infrastructures de transport"], 0,
     "Retraites et santé en constituent la part dominante, loin devant les autres postes."],
    ["Quelle institution contrôle l'emploi des fonds publics en France ?", ["La Cour des comptes", "Le Conseil d'État", "l'Inspection générale des finances seule", "Le Conseil constitutionnel"], 0,
     "Elle publie chaque année un rapport public et assiste le Parlement dans le contrôle du budget."],
    ["À qui la dette publique française est-elle due ?", ["À des investisseurs français et étrangers détenant des titres d'État", "À la seule Banque centrale européenne, qui rachète tous les titres émis", "Aux autres États européens, dans le cadre de la solidarité", "Au Fonds monétaire international, prêteur en dernier ressort"], 0,
     "Elle prend la forme d'obligations négociables, émises par l'Agence France Trésor."],
    ["Que mesure une note souveraine attribuée par une agence de notation ?", ["Le risque estimé qu'un État ne rembourse pas sa dette", "La santé économique globale du pays et de ses entreprises", "Le niveau absolu de la dette publique rapporté au PIB", "La qualité de la gestion budgétaire du gouvernement"], 0,
     "Une dégradation renchérit théoriquement les emprunts, mais les marchés anticipent souvent les décisions des agences.", 3],
  ]),

  notion("ie-onu-organisations", S, "L'ONU et les organisations internationales",
    "Une charte de 1945, six organes principaux, et une galaxie d'agences spécialisées.",
    "Seuls cinq membres permanents du Conseil de sécurité disposent du droit de veto.",
    2, [
    ["Dans quelle ville la charte des Nations unies est-elle signée ?", ["San Francisco", "New York, en 1945", "Yalta, en Crimée", "Genève, en Suisse"], 0,
     "En juin 1945, par cinquante et un États fondateurs, quelques semaines après la capitulation allemande."],
    ["Combien d'États membres compte l'ONU ?", ["Cent quatre-vingt-treize", "Cent cinquante États", "Deux cents États exactement", "Cent quatre-vingts"], 0,
     "Le Soudan du Sud est le dernier admis, en 2011."],
    ["Quels pays sont membres permanents du Conseil de sécurité ?", ["Chine, États-Unis, France, Royaume-Uni, Russie", "États-Unis, Russie, Chine, Allemagne, Japon", "France, Royaume-Uni, Allemagne, Italie, Espagne", "Les cinq plus grandes économies"], 0,
     "Ce sont les vainqueurs de 1945. Leur droit de veto bloque toute résolution contraire à leurs intérêts."],
    ["Où se situe le siège de l'ONU ?", ["À New York", "À Genève, en Suisse", "À La Haye", "À Vienne"], 0,
     "Genève abrite le second siège européen et de nombreuses agences spécialisées."],
    ["Quelle juridiction internationale siège à La Haye et juge les différends entre États ?", ["La Cour internationale de justice", "La Cour pénale internationale", "La Cour européenne des droits de l'homme", "Le Tribunal du droit de la mer"], 0,
     "La Cour pénale internationale, également à La Haye, juge des individus et non des États."],
    ["Que fait l'UNESCO ?", ["Elle œuvre pour l'éducation, la science et la culture", "Elle gère l'aide alimentaire d'urgence dans le monde entier", "Elle coordonne la santé publique à l'échelle mondiale", "Elle protège les réfugiés et les personnes déplacées"], 0,
     "Elle tient la liste du patrimoine mondial, créée par la convention de 1972."],
    ["Que peut déclarer l'Organisation mondiale de la santé face à une épidémie ?", ["Une urgence de santé publique de portée internationale", "Un état d'exception sanitaire applicable au monde entier", "Une quarantaine obligatoire dans les pays touchés", "Une interdiction de circuler entre les États membres"], 0,
     "Prévue par le règlement sanitaire international de 2005, cette déclaration déclenche des recommandations aux États, sans les contraindre."],
    ["Quelle organisation protège les réfugiés ?", ["Le HCR", "l'OIM seule", "l'UNICEF", "Le PAM"], 0,
     "Créé en 1950, le Haut-Commissariat pour les réfugiés applique la convention de Genève de 1951."],
    ["Que prévoit l'article 5 du traité de l'Atlantique Nord ?", ["Une attaque contre un membre est considérée comme une attaque contre tous", "L'interdiction pour un membre d'en attaquer un autre", "Le commandement unifié des forces alliées, dès le temps de paix, à Bruxelles", "La consultation obligatoire des alliés avant l'entrée en conflit"], 0,
     "Il n'a été invoqué qu'une fois, par les États-Unis, après les attentats du 11 septembre 2001."],
    ["Que sont les objectifs de développement durable ?", ["Dix-sept objectifs mondiaux fixés en 2015 à l'horizon 2030", "Les engagements climatiques pris lors de l'accord de Paris de 2015", "Les cibles chiffrées adoptées par le G20", "Les priorités de financement de la Banque mondiale"], 0,
     "Ils succèdent aux objectifs du Millénaire pour le développement, en vigueur de 2000 à 2015.", 3],
  ]),

  notion("ie-medias-information", S, "Les médias, l'information et sa régulation",
    "Qui garantit la liberté de la presse, qui la régule, et comment se finance l'information.",
    "La loi de 1881 encadre encore aujourd'hui la liberté de la presse en France.",
    2, [
    ["Quelle loi fonde la liberté de la presse en France ?", ["La loi du 29 juillet 1881", "La loi du 26 août 1789", "L'ordonnance du 26 août 1944", "La loi constitutionnelle de 1958"], 0,
     "Elle pose le principe de liberté et définit limitativement les abus punissables, dont la diffamation."],
    ["Quelle autorité régule l'audiovisuel et le numérique en France ?", ["l'Arcom", "Le CSA seul", "l'Arcep", "La CNIL"], 0,
     "Née en 2022 de la fusion du CSA et de la Hadopi, elle veille au pluralisme et à la protection des mineurs."],
    ["Quelle autorité protège les données personnelles en France ?", ["La CNIL", "l'Arcom", "l'Arcep", "La DGCCRF"], 0,
     "Créée en 1978, bien avant l'internet grand public, par la loi Informatique et libertés."],
    ["Que signifie le sigle RGPD ?", ["Règlement général sur la protection des données", "Régulation générale des plateformes numériques", "Registre général des personnes et données", "Règlement de gestion des publications numériques"], 0,
     "Applicable depuis mai 2018 dans toute l'Union européenne, il impose consentement et droit à l'effacement."],
    ["Qu'est-ce que le secret des sources d'un journaliste ?", ["Le droit de ne pas révéler l'identité de ses informateurs", "L'interdiction de citer une source restée anonyme", "Le droit de publier une information sans la vérifier", "L'obligation de protéger tous les documents reçus d'un tiers"], 0,
     "Protégé par la loi de 2010, il connaît des exceptions justifiées par un impératif prépondérant d'intérêt public."],
    ["Qu'est-ce que le droit de réponse ?", ["Le droit pour une personne citée d'obtenir la publication de sa réponse", "Le droit de poursuivre un journal devant le tribunal", "Le droit d'exiger la publication d'un rectificatif du journal", "Le droit d'accéder aux sources et aux documents utilisés par le journaliste"], 0,
     "Il s'exerce sans avoir à prouver un préjudice, et le refus de publication est punissable."],
    ["Comment se finance principalement la presse en ligne aujourd'hui ?", ["Par la publicité et les abonnements", "Par les subventions publiques seules", "Par la vente au numéro", "Par le mécénat"], 0,
     "La part des abonnements numériques progresse à mesure que les recettes publicitaires migrent vers les plateformes."],
    ["Qu'est-ce que la charte de Munich de 1971 ?", ["Une déclaration des devoirs et droits des journalistes", "Un traité international sur la liberté de la presse", "Une loi allemande encadrant l'ensemble des médias", "Un code européen encadrant la publicité dans la presse écrite"], 0,
     "Dix devoirs et cinq droits, dont l'obligation de rectifier une information inexacte."],
    ["Qu'appelle-t-on bulle de filtre ?", ["l'enfermement d'un internaute dans des contenus conformes à ses opinions", "Un blocage géographique qui empêche l'accès à certains contenus mis en ligne", "La modération automatique des contenus par algorithme", "Un abonnement donnant accès à des contenus réservés"], 0,
     "L'expression est due à Eli Pariser en 2011. L'ampleur réelle du phénomène fait débat chez les chercheurs."],
    ["Que prévoit le règlement européen sur les services numériques adopté en 2022 ?", ["Des obligations de modération et de transparence pour les grandes plateformes", "Une taxe européenne prélevée sur les revenus publicitaires des grandes plateformes", "L'interdiction pure et simple de l'anonymat sur internet", "La création d'un opérateur européen de réseaux sociaux publics"], 0,
     "Le DSA impose des audits, l'accès des chercheurs aux données et des mécanismes de recours pour les utilisateurs.", 3],
  ]),

  notion("ie-democratie-regimes", S, "Démocraties et régimes politiques",
    "Séparation des pouvoirs, types de régimes, modes de scrutin : la grammaire du politique.",
    "Un régime parlementaire n'est pas un régime sans président : ce qui le définit est le lien de responsabilité entre l'exécutif et les chambres.",
    2, [
    ["Qui théorise la séparation des pouvoirs en 1748 ?", ["Montesquieu", "Jean-Jacques Rousseau", "John Locke", "Voltaire"], 0,
     "Dans L'Esprit des lois. John Locke avait esquissé l'idée dès 1690."],
    ["Qu'est-ce qu'un régime présidentiel ?", ["Le gouvernement n'est pas responsable devant le Parlement", "Le président est élu au suffrage universel direct par les citoyens", "Le président nomme seul le Premier ministre et les ministres", "Le président peut dissoudre le Parlement quand il le souhaite"], 0,
     "Les États-Unis en sont l'exemple : ni renversement du gouvernement, ni dissolution du Congrès."],
    ["Qu'est-ce qu'un régime parlementaire ?", ["Le gouvernement est responsable devant le Parlement", "Le Parlement gouverne directement, sans gouvernement distinct", "Le chef de l'État n'existe pas dans ce type de régime", "Le Parlement élit le chef de l'État, qui gouverne ensuite seul"], 0,
     "L'Allemagne et le Royaume-Uni en sont des exemples. La contrepartie est le droit de dissolution."],
    ["Comment qualifie-t-on le régime de la Ve République française ?", ["Semi-présidentiel", "Présidentiel", "Parlementaire pur", "Directorial"], 0,
     "Un président élu au suffrage universel direct depuis 1962, mais un gouvernement responsable devant l'Assemblée nationale."],
    ["Qu'est-ce qu'un scrutin majoritaire à deux tours ?", ["Le candidat en tête au second tour l'emporte, après élimination des autres", "Les sièges sont répartis à la proportionnelle des voix obtenues au premier tour", "Deux élus sont désignés dans chaque circonscription, un par tour", "Le vote se fait par liste bloquée, sans possibilité de rature"], 0,
     "Il favorise les grandes formations et la constitution de majorités stables, au prix de la représentativité."],
    ["Qu'est-ce que la représentation proportionnelle ?", ["Les sièges sont répartis selon le pourcentage de voix", "Chaque région élit un nombre égal d'élus, quel que soit son poids", "Le vainqueur emporte la totalité des sièges en jeu", "Les élus sont désignés par tirage au sort parmi les candidats"], 0,
     "Elle représente mieux la diversité des opinions, mais rend souvent nécessaires des coalitions."],
    ["Qu'est-ce qu'une motion de censure ?", ["Un vote du Parlement qui renverse le gouvernement", "Un blâme officiel adressé à un ministre par les députés", "Un refus de voter le budget présenté par le gouvernement", "Une saisine du Conseil constitutionnel par soixante députés"], 0,
     "Sous la Ve République, elle exige la majorité absolue des membres de l'Assemblée, seuls les votes favorables étant comptés."],
    ["Qu'est-ce qu'un référendum ?", ["Une consultation directe des citoyens sur un texte ou une question", "Une élection anticipée organisée après une dissolution", "Un sondage officiel commandé par le gouvernement sur un projet", "Un vote du Parlement réuni en Congrès afin de réviser la Constitution"], 0,
     "En France, il peut porter sur l'organisation des pouvoirs publics ou la ratification d'un traité."],
    ["Qu'est-ce que l'État de droit ?", ["Un ordre où les pouvoirs publics sont soumis au droit et contrôlés par un juge", "Un État qui applique strictement ses lois, quelles qu'elles soient", "Un régime doté d'une constitution écrite et d'une déclaration des droits solennelle", "Un État où la seule justice judiciaire est indépendante du gouvernement"], 0,
     "La hiérarchie des normes et l'existence d'un recours juridictionnel effectif en sont les piliers."],
    ["Qu'appelle-t-on démocratie illibérale ?", ["Un régime issu des urnes qui affaiblit les contre-pouvoirs", "Une démocratie sans partis politiques organisés", "Un régime autoritaire qui a supprimé toute élection libre", "Une démocratie directe où le peuple vote lui-même toutes les lois"], 0,
     "L'expression, popularisée par Fareed Zakaria en 1997, désigne des pouvoirs élus qui rognent presse, justice et opposition.", 3],
  ]),

  notion("ie-energie-transition", S, "Énergie et transition écologique",
    "Ce que consomme un pays, d'où vient l'électricité, et ce que veut dire décarboner.",
    "Énergie et électricité ne sont pas la même chose : l'électricité ne représente qu'un quart de l'énergie consommée en France.",
    2, [
    ["Quelle source produit la majorité de l'électricité française ?", ["Le nucléaire", "l'hydraulique", "Le gaz", "l'éolien"], 0,
     "Autour de deux tiers de la production selon les années. L'hydraulique est la première source renouvelable du pays."],
    ["Quelle est la principale source d'énergie primaire dans le monde ?", ["Le pétrole", "Le charbon", "Le gaz naturel", "l'hydraulique"], 0,
     "Les énergies fossiles représentent encore environ quatre cinquièmes du mix mondial."],
    ["Qu'est-ce qu'une énergie renouvelable ?", ["Une source dont le stock se reconstitue à l'échelle humaine", "Une énergie dont la production n'émet aucun CO2", "Une énergie produite localement, au plus près du consommateur", "Une énergie qu'il est impossible de stocker"], 0,
     "Le nucléaire est bas carbone mais non renouvelable ; la biomasse est renouvelable mais émet du CO2 à la combustion."],
    ["Qu'appelle-t-on énergie intermittente ?", ["Une production qui dépend du vent ou du soleil", "Une énergie produite par à-coups pour des raisons techniques", "Une énergie stockée puis relâchée par intervalles", "Une centrale mise à l'arrêt à intervalles réguliers"], 0,
     "Elle impose des moyens de flexibilité : stockage, effacement de la demande ou centrales pilotables."],
    ["Quel secteur émet le plus de gaz à effet de serre en France ?", ["Les transports", "L'industrie manufacturière", "L'agriculture", "Le logement"], 0,
     "Environ un tiers des émissions, dont la majeure partie due à la voiture individuelle."],
    ["Qu'est-ce que le mix énergétique d'un pays ?", ["La répartition des sources d'énergie qu'il consomme", "Le rendement moyen de l'ensemble de ses centrales", "Sa dépendance aux importations d'énergie étrangère", "Sa production totale d'électricité au cours de l'année"], 0,
     "Il diffère du mix électrique, qui ne concerne que la production d'électricité."],
    ["Qu'est-ce que la neutralité carbone ?", ["Un équilibre entre émissions et absorptions de gaz à effet de serre", "L'arrêt total de toute émission de gaz à effet de serre dans l'ensemble du pays", "La compensation intégrale par l'achat de crédits carbone", "La réduction de moitié des émissions par rapport à 1990"], 0,
     "L'Union européenne la vise pour 2050. Elle suppose de réduire fortement les émissions avant de compenser le reste."],
    ["Qu'est-ce que le mécanisme européen d'échange de quotas d'émission ?", ["Un marché où les industriels achètent des droits à émettre du CO2", "Une taxe carbone européenne prélevée sur les industriels", "Un plafond d'émissions fixé pays par pays par la Commission", "Un système de subventions vertes versées aux industriels les plus propres"], 0,
     "Lancé en 2005, il couvre l'industrie lourde et l'électricité. Le plafond de quotas décroît chaque année."],
    ["Qu'est-ce que la sobriété énergétique ?", ["La réduction de la consommation par les usages et l'organisation", "L'amélioration du seul rendement technique des appareils", "Le remplacement des énergies fossiles par les seules renouvelables", "La limitation autoritaire de la production industrielle"], 0,
     "Elle se distingue de l'efficacité, qui vise à consommer moins pour un même service sans changer l'usage."],
    ["Qu'appelle-t-on effet rebond ?", ["Les gains d'efficacité sont partiellement annulés par une hausse de l'usage", "Le retour du prix de l'énergie à son niveau d'avant la baisse", "La reprise de la consommation d'énergie au sortir d'une crise", "L'augmentation des émissions constatée aussitôt après une période de réduction"], 0,
     "Décrit dès 1865 par William Stanley Jevons à propos du charbon : des machines plus efficaces en ont fait consommer davantage.", 3],
  ]),

  notion("ie-consommation-droit", S, "Le droit de la consommation",
    "Garanties, rétractation, démarchage : ce que la loi protège quand on achète.",
    "La garantie légale de conformité est gratuite et de durée fixée par la loi : elle ne se confond pas avec la garantie commerciale, qui se vend.",
    2, [
    ["Quelle est la durée de la garantie légale de conformité pour un bien neuf en France ?", ["Deux ans", "Un an", "Six mois", "Cinq ans"], 0,
     "Elle est gratuite et obligatoire. La garantie commerciale, payante ou offerte, s'y ajoute sans la remplacer."],
    ["Quel est le délai de rétractation pour un achat à distance ?", ["Quatorze jours", "Sept jours", "Trente jours", "Quarante-huit heures"], 0,
     "Il court à compter de la réception du bien et n'a pas à être justifié. Certains produits en sont exclus."],
    ["Le délai de rétractation s'applique-t-il à un achat en magasin ?", ["Non, il ne concerne pas les achats en boutique", "Oui, dans les mêmes conditions", "Oui, mais sous sept jours", "Seulement pour les biens de plus de cent euros"], 0,
     "Le retour en magasin relève d'un geste commercial, pas d'un droit. Le démarchage à domicile, lui, ouvre bien ce droit."],
    ["Qu'est-ce qu'un vice caché ?", ["Un défaut non apparent qui rend le bien impropre à son usage", "Un défaut visible dès la livraison du bien acheté", "Une usure normale liée à l'usage du bien", "Une panne survenant après l'expiration de la garantie légale de conformité"], 0,
     "L'action se prescrit par deux ans à compter de la découverte du vice, y compris entre particuliers."],
    ["Qu'est-ce qu'une clause abusive ?", ["Une clause créant un déséquilibre significatif au détriment du consommateur", "Une clause écrite en très petits caractères au bas du contrat d'adhésion signé", "Une clause que le consommateur n'a pas signée lui-même", "Une clause imposant un délai de rétractation plus court"], 0,
     "Elle est réputée non écrite : le contrat subsiste sans elle."],
    ["Quelle administration contrôle la loyauté des pratiques commerciales en France ?", ["La DGCCRF", "La CNIL", "l'Arcom", "l'Autorité de la concurrence seule"], 0,
     "Elle vérifie l'information des consommateurs, la sécurité des produits et les pratiques trompeuses."],
    ["Qu'est-ce que l'obsolescence programmée ?", ["Le fait de réduire délibérément la durée de vie d'un produit", "L'usure naturelle d'un appareil au fil des années", "L'arrêt des mises à jour logicielles par le fabricant", "Le renouvellement rapide des modèles proposés à la vente en magasin"], 0,
     "Elle est un délit en France depuis 2015, mais la preuve de l'intention reste difficile à établir."],
    ["Qu'est-ce que l'indice de réparabilité ?", ["Une note affichée indiquant la facilité de réparer un produit", "La durée de disponibilité des pièces détachées d'un produit vendu", "Le coût moyen d'une réparation chez un professionnel", "La garantie du constructeur, étendue au-delà de deux ans"], 0,
     "Obligatoire en France depuis 2021 sur plusieurs catégories d'appareils, il évolue vers un indice de durabilité."],
    ["Qu'est-ce qu'une action de groupe ?", ["Une action en justice engagée pour un ensemble de consommateurs lésés", "Une plainte collective déposée auprès d'une administration de contrôle", "Une médiation organisée entre plusieurs associations", "Une pétition dotée d'une valeur juridique contraignante"], 0,
     "Introduite en France en 2014, elle est ouverte aux associations agréées."],
    ["Qu'est-ce que le taux annuel effectif global d'un crédit ?", ["Le coût total du crédit exprimé en pourcentage annuel", "Le seul taux d'intérêt nominal du prêt", "Le taux plafond légal fixé chaque trimestre par la Banque de France", "La marge que la banque prélève sur l'opération"], 0,
     "Il inclut intérêts, frais de dossier et assurance obligatoire : c'est le seul chiffre comparable d'une offre à l'autre.", 3],
  ]),
];
