/**
 * Institutions & Économie, deuxième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Institutions & Économie";

export const CG_INSTITUTIONS_ECONOMIE_2: SeedSkill[] = [
  notion("ie2-union-europeenne", S, "L'Union européenne",
    "Institutions, compétences, décisions : comment fonctionne l'Union.",
    "La Commission propose, le Conseil et le Parlement décident : c'est le triangle institutionnel.",
    2, [
    ["Quelle institution européenne détient l'initiative des textes législatifs ?", ["La Commission européenne", "Le Parlement européen", "Le Conseil de l'Union", "Le Conseil européen"], 0,
     "Le Parlement peut lui demander de proposer un texte, mais ne peut pas le faire lui-même."],
    ["Que réunit le Conseil européen ?", ["Les chefs d'État et de gouvernement des États membres", "Les ministres compétents par domaine", "Les députés élus", "Les commissaires européens"], 0,
     "À ne pas confondre avec le Conseil de l'Union européenne, qui réunit les ministres."],
    ["Comment les députés européens sont-ils désignés ?", ["Élus au suffrage universel direct dans chaque État", "Désignés par les parlements nationaux", "Nommés par les gouvernements", "Élus par les partis européens"], 0,
     "Depuis 1979. Le mandat est de cinq ans."],
    ["Combien d'États membres l'Union européenne compte-t-elle ?", ["Vingt-sept", "Vingt-huit", "Vingt-cinq", "Trente"], 0,
     "Depuis le retrait du Royaume-Uni, effectif en 2020."],
    ["Quel traité crée l'Union européenne et la citoyenneté européenne ?", ["Le traité de Maastricht", "Le traité de Rome", "Le traité d'Amsterdam", "Le traité de Lisbonne"], 0,
     "Signé en 1992, il pose aussi les critères de la monnaie unique."],
    ["Quel traité de 2007 réforme le fonctionnement des institutions européennes ?", ["Le traité de Lisbonne", "Le traité de Nice", "Le traité d'Amsterdam", "Le traité de Maastricht"], 0,
     "Il reprend une partie du contenu du projet de constitution rejeté par référendum en 2005."],
    ["Qu'est-ce que le principe de subsidiarité ?", ["L'Union n'intervient que si l'action est plus efficace à son niveau", "L'Union est subordonnée aux États", "Les États appliquent le droit européen", "Les décisions se prennent à l'unanimité"], 0,
     "Les parlements nationaux peuvent contester un texte au nom de ce principe."],
    ["Quelle juridiction assure l'interprétation uniforme du droit européen ?", ["La Cour de justice de l'Union européenne", "La Cour européenne des droits de l'homme", "La Cour des comptes européenne", "Le Tribunal de première instance seul"], 0,
     "La Cour européenne des droits de l'homme relève du Conseil de l'Europe, institution distincte."],
    ["Qu'est-ce qu'un règlement européen, par rapport à une directive ?", ["Le règlement s'applique directement, la directive doit être transposée", "Le règlement est facultatif", "La directive prime sur le règlement", "Les deux exigent une loi nationale"], 0,
     "La directive fixe un objectif et laisse aux États le choix des moyens."],
    ["Qu'est-ce que le marché unique européen ?", ["La libre circulation des biens, services, capitaux et personnes", "Une union douanière seule", "Une zone de libre-échange", "Une monnaie commune"], 0,
     "Ces quatre libertés sont indissociables dans la construction juridique de l'Union.", 3],
  ]),

  notion("ie2-parlement-francais", S, "Le Parlement français",
    "Deux chambres, une procédure législative, des pouvoirs de contrôle.",
    "L'Assemblée nationale a le dernier mot en cas de désaccord persistant avec le Sénat.",
    2, [
    ["Combien de députés l'Assemblée nationale compte-t-elle ?", ["Cinq cent soixante-dix-sept", "Trois cent quarante-huit", "Six cents", "Cinq cents"], 0,
     "Élus pour cinq ans au scrutin majoritaire à deux tours dans des circonscriptions."],
    ["De qui le collège électoral sénatorial est-il très majoritairement composé ?", ["De délégués des conseils municipaux", "De conseillers régionaux", "De députés", "De maires uniquement"], 0,
     "Environ quatre-vingt-quinze pour cent, ce qui explique la surreprésentation des communes rurales au Sénat."],
    ["Quelle chambre a le dernier mot en cas de désaccord législatif persistant ?", ["L'Assemblée nationale", "Le Sénat", "Aucune, le texte est abandonné", "Le Conseil constitutionnel tranche"], 0,
     "Le gouvernement doit toutefois le demander explicitement."],
    ["Qu'est-ce qu'une commission mixte paritaire ?", ["Une réunion de députés et de sénateurs cherchant un texte de compromis", "Une commission d'enquête", "Une commission permanente", "Une commission de contrôle budgétaire"], 0,
     "Sept députés et sept sénateurs, convoqués après plusieurs lectures infructueuses."],
    ["Qu'est-ce que la navette parlementaire ?", ["L'examen successif d'un texte par les deux chambres", "Le transport des textes entre chambres", "Le vote simultané des deux assemblées", "L'échange de rapporteurs"], 0,
     "Elle se poursuit jusqu'à adoption d'un texte identique ou intervention du gouvernement."],
    ["Qu'est-ce qu'une question au gouvernement ?", ["Une séance hebdomadaire d'interpellation des ministres", "Une saisine écrite d'un ministère", "Une audition en commission", "Une demande d'explication budgétaire"], 0,
     "Elles sont télévisées et constituent le moment le plus visible du contrôle parlementaire."],
    ["Qu'est-ce qu'une commission d'enquête parlementaire ?", ["Une commission temporaire dotée de pouvoirs d'investigation", "Une commission permanente d'un domaine", "Un groupe de travail informel", "Une mission d'information ordinaire"], 0,
     "Elle peut convoquer des témoins sous serment et dispose de six mois maximum."],
    ["Qu'est-ce que l'immunité parlementaire ?", ["Une protection contre les poursuites pour les actes liés au mandat", "Une impunité totale", "Une protection contre les impôts", "Une immunité diplomatique"], 0,
     "L'irresponsabilité couvre les propos tenus dans l'exercice du mandat ; l'inviolabilité peut être levée."],
    ["Qu'est-ce que le cumul des mandats en France depuis 2017 ?", ["Un mandat parlementaire est incompatible avec un exécutif local", "Le cumul reste autorisé sans limite", "Deux mandats locaux sont interdits", "Le cumul est limité à trois mandats"], 0,
     "La réforme a considérablement modifié le profil et le travail des parlementaires."],
    ["Qu'est-ce qu'une loi organique ?", ["Une loi précisant l'organisation des pouvoirs publics, adoptée selon une procédure renforcée", "Une loi de finances", "Une loi cadre non contraignante", "Une loi de ratification"], 0,
     "Elle est obligatoirement soumise au Conseil constitutionnel avant promulgation.", 3],
  ]),

  notion("ie2-fonction-publique", S, "La fonction publique",
    "Statut, concours, missions : qui travaille pour l'État et les collectivités.",
    "La fonction publique française compte trois versants distincts.",
    2, [
    ["Quels sont les trois versants de la fonction publique française ?", ["l'État, la territoriale et l'hospitalière", "l'État, les collectivités et les entreprises publiques", "La civile, la militaire et la judiciaire", "La nationale, la régionale et la locale"], 0,
     "Ensemble, ils emploient environ cinq millions et demi de personnes."],
    ["Quel principe régit l'accès à la fonction publique française ?", ["L'égal accès par concours", "La nomination discrétionnaire", "La cooptation professionnelle", "Le recrutement sur titres uniquement"], 0,
     "Le principe découle de la Déclaration de 1789, qui écarte toute distinction autre que les talents."],
    ["Qu'est-ce qu'un fonctionnaire titulaire ?", ["Un agent nommé dans un grade et dont l'emploi est statutaire", "Un agent en contrat à durée indéterminée", "Un agent en poste depuis dix ans", "Un cadre de la fonction publique"], 0,
     "Il est dans une situation réglementaire, non contractuelle : son statut peut être modifié par la loi."],
    ["Qu'est-ce que le devoir de réserve d'un fonctionnaire ?", ["Une obligation de modération dans l'expression publique liée à ses fonctions", "L'interdiction de toute opinion politique", "Le secret professionnel", "L'interdiction de se syndiquer"], 0,
     "Son intensité varie selon le rang et la nature des fonctions exercées."],
    ["Qu'est-ce que le principe de continuité du service public ?", ["Le service doit fonctionner sans interruption injustifiée", "Le service doit être identique partout", "Le service doit être gratuit", "Les agents ne peuvent pas faire grève"], 0,
     "Il justifie l'encadrement du droit de grève et les services minimums, sans le supprimer."],
    ["Qu'est-ce que le principe d'égalité devant le service public ?", ["Tous les usagers placés dans la même situation sont traités identiquement", "Tous les services sont gratuits", "Tous les territoires sont couverts identiquement", "Tous les agents ont le même statut"], 0,
     "Il n'interdit pas de traiter différemment des situations différentes, comme les tarifs selon le revenu."],
    ["Qu'est-ce que le principe de mutabilité du service public ?", ["Le service doit s'adapter à l'évolution des besoins", "Les agents doivent être mobiles", "Le service peut être privatisé", "Les usagers peuvent changer de prestataire"], 0,
     "Il explique qu'aucun usager n'a de droit acquis au maintien d'un service en l'état."],
    ["Quelle école a formé les hauts fonctionnaires français de 1945 à 2021 ?", ["l'ENA", "Sciences Po seule", "l'École polytechnique", "l'ENS"], 0,
     "Elle a été remplacée par l'Institut national du service public."],
    ["Qu'est-ce qu'un agent contractuel de la fonction publique ?", ["Un agent recruté par contrat, sans être titulaire d'un grade", "Un fonctionnaire stagiaire", "Un vacataire ponctuel", "Un agent détaché du privé"], 0,
     "Ils représentent aujourd'hui une part significative des effectifs, notamment dans la territoriale."],
    ["Qu'est-ce que le pantouflage ?", ["Le passage d'un haut fonctionnaire vers le secteur privé", "Le retour d'un cadre privé dans l'administration", "Une mise en disponibilité", "Un détachement à l'étranger"], 0,
     "Une commission de déontologie examine les risques de conflit d'intérêts avant d'autoriser le départ.", 3],
  ]),

  notion("ie2-droits-libertes", S, "Droits fondamentaux et libertés publiques",
    "Textes de référence, garanties, limites.",
    "Aucune liberté n'est absolue : toutes se concilient avec d'autres droits et l'ordre public.",
    2, [
    ["Quel texte de 1948 énonce des droits reconnus à tous les êtres humains ?", ["La Déclaration universelle des droits de l'homme", "La Convention européenne des droits de l'homme", "La Charte des Nations unies", "Le Pacte de New York"], 0,
     "Adoptée par l'Assemblée générale des Nations unies, elle n'a pas en elle-même de force contraignante."],
    ["Quelle juridiction fait appliquer la Convention européenne des droits de l'homme ?", ["La Cour européenne des droits de l'homme, à Strasbourg", "La Cour de justice de l'Union européenne", "La Cour internationale de justice", "La Cour pénale internationale"], 0,
     "Elle peut être saisie par un particulier après épuisement des recours internes."],
    ["Qu'est-ce que le bloc de constitutionnalité en France ?", ["L'ensemble des normes de valeur constitutionnelle, Constitution et textes annexés", "La seule Constitution de 1958", "Les lois organiques", "Les traités ratifiés"], 0,
     "Il inclut la Déclaration de 1789, le préambule de 1946 et la Charte de l'environnement."],
    ["Quelle liberté la loi de 1881 protège-t-elle en France ?", ["La liberté de la presse", "La liberté d'association", "La liberté de réunion", "La liberté syndicale"], 0,
     "Elle définit limitativement les abus punissables, ce qui protège la liberté par défaut."],
    ["Que garantit le droit au respect de la vie privée ?", ["La protection contre l'immixtion dans la sphère personnelle", "Le droit à l'anonymat", "Le secret de toute correspondance sans exception", "L'interdiction de toute surveillance"], 0,
     "Il figure à l'article 9 du Code civil français et à l'article 8 de la Convention européenne."],
    ["Qu'est-ce que la présomption d'innocence ?", ["Toute personne est réputée innocente jusqu'à condamnation définitive", "Le doute profite au prévenu au procès", "L'accusation doit être prouvée à l'audience", "Le prévenu n'a pas à témoigner"], 0,
     "Elle s'impose aussi aux autorités publiques et aux médias, pas seulement au juge."],
    ["Qu'est-ce que le Défenseur des droits en France ?", ["Une autorité indépendante protégeant les droits des usagers et luttant contre les discriminations", "Un tribunal administratif", "Un service du ministère de la Justice", "Un médiateur d'entreprise"], 0,
     "Créé en 2011, il a repris les missions du Médiateur de la République et de plusieurs autorités."],
    ["Qu'est-ce que la liberté de conscience ?", ["Le droit de croire, de ne pas croire et de changer de conviction", "Le droit d'exprimer toute opinion", "Le droit de pratiquer un culte", "Le droit à l'objection de conscience"], 0,
     "Elle est plus large que la liberté de culte, qui n'en est qu'une manifestation."],
    ["Qu'est-ce que l'état d'urgence en France ?", ["Un régime d'exception élargissant les pouvoirs administratifs", "Une suspension de la Constitution", "Une loi martiale", "Un transfert de pouvoirs à l'armée"], 0,
     "Créé en 1955 pendant la guerre d'Algérie, il a été appliqué plusieurs fois depuis."],
    ["Qu'est-ce que le contrôle de proportionnalité d'une mesure restreignant une liberté ?", ["Vérifier qu'elle est adaptée, nécessaire et non excessive", "Vérifier qu'elle est prévue par la loi", "Comparer les libertés en présence", "Mesurer son coût pour l'État"], 0,
     "Ce raisonnement en trois temps est devenu central dans la jurisprudence française et européenne.", 3],
  ]),

  notion("ie2-mondialisation", S, "La mondialisation économique",
    "Flux, acteurs, débats : ce que recouvre l'intégration des économies.",
    "La mondialisation n'est pas un phénomène nouveau, mais son intensité et sa vitesse le sont.",
    2, [
    ["Qu'est-ce que la mondialisation économique ?", ["L'intégration croissante des économies par les échanges et les investissements", "L'uniformisation des cultures", "La domination des pays riches", "La suppression des frontières"], 0,
     "Elle comporte aussi des dimensions culturelle, politique et migratoire."],
    ["Qu'est-ce qu'une firme multinationale ?", ["Une entreprise implantée et produisant dans plusieurs pays", "Une entreprise exportatrice", "Une entreprise cotée à l'étranger", "Un groupe à capitaux étrangers"], 0,
     "Les plus grandes réalisent des chiffres d'affaires supérieurs au PIB de nombreux États."],
    ["Qu'est-ce qu'un investissement direct à l'étranger ?", ["Une prise de participation durable dans une entreprise étrangère", "Un placement financier temporaire", "Une exportation de biens", "Un prêt international"], 0,
     "Il se distingue de l'investissement de portefeuille, purement financier et volatil."],
    ["Qu'est-ce qu'une délocalisation ?", ["Le transfert d'une activité vers un pays à coûts plus faibles", "L'ouverture d'un marché étranger", "L'externalisation d'une fonction", "La fermeture d'un site industriel"], 0,
     "Elle se distingue de la simple externalisation, qui peut rester nationale."],
    ["Qu'est-ce qu'un paradis fiscal ?", ["Un territoire à fiscalité très faible et à opacité élevée", "Un pays sans impôt sur le revenu", "Un centre financier international", "Une zone franche industrielle"], 0,
     "Les listes officielles varient selon les critères retenus et les rapports de force diplomatiques."],
    ["Qu'est-ce que l'optimisation fiscale ?", ["L'usage légal des règles fiscales pour réduire l'impôt dû", "La fraude fiscale organisée", "Le report d'imposition", "L'exonération accordée par un État"], 0,
     "Elle se distingue juridiquement de la fraude, même si la frontière est parfois discutée."],
    ["Qu'est-ce que le prix de transfert ?", ["Le prix des échanges internes à un groupe multinational", "Le coût du transport international", "Le prix de cession d'une filiale", "Le tarif douanier interne"], 0,
     "Sa manipulation permet de localiser artificiellement les bénéfices dans les pays à faible fiscalité."],
    ["Qu'est-ce que l'impôt minimum mondial adopté en 2021 ?", ["Un taux plancher de quinze pour cent sur les bénéfices des grandes multinationales", "Un impôt européen sur les entreprises", "Une taxe sur les transactions financières", "Un droit de douane harmonisé"], 0,
     "Négocié à l'OCDE et approuvé par plus de cent trente pays, son application reste inégale."],
    ["Qu'est-ce que la démondialisation ?", ["Un ralentissement ou un recul de l'intégration économique mondiale", "Une fermeture totale des frontières", "Le retour au protectionnisme généralisé", "La fin des multinationales"], 0,
     "Le débat porte sur son ampleur réelle : les flux se réorganisent plus qu'ils ne disparaissent."],
    ["Qu'est-ce que la relocalisation ?", ["Le retour d'une production sur le territoire national", "Le déplacement d'un site dans un même pays", "L'implantation dans un pays voisin", "La diversification des fournisseurs"], 0,
     "Les crises récentes ont relancé le débat sur la souveraineté économique, notamment sanitaire.", 3],
  ]),

  notion("ie2-marche-concurrence", S, "Marchés et concurrence",
    "Offre, demande, monopoles, régulation : comment fonctionnent les marchés.",
    "Un marché concurrentiel suppose des conditions rarement toutes réunies dans la réalité.",
    2, [
    ["Qu'est-ce qu'un marché en économie ?", ["Un lieu réel ou abstrait de rencontre de l'offre et de la demande", "Un lieu physique de vente", "Un secteur économique", "Un ensemble de consommateurs"], 0,
     "Le marché du travail ou celui des capitaux n'ont pas d'existence physique."],
    ["Qu'est-ce que la loi de l'offre et de la demande ?", ["Le prix tend à équilibrer les quantités offertes et demandées", "Le prix est fixé par le producteur", "La demande détermine seule le prix", "L'offre suit toujours la demande"], 0,
     "Ce mécanisme suppose que les acteurs soient nombreux et informés, ce qui est souvent inexact."],
    ["Qu'est-ce qu'un monopole ?", ["Une situation où un seul offreur est présent sur un marché", "Une entente entre producteurs", "Une position dominante", "Un marché à barrières d'entrée"], 0,
     "Le monopsone en est le symétrique du côté de la demande : un seul acheteur."],
    ["Qu'est-ce qu'un oligopole ?", ["Un marché dominé par un petit nombre d'offreurs", "Un marché à un seul vendeur", "Un marché protégé par l'État", "Un marché à forte concurrence"], 0,
     "L'interdépendance entre acteurs y rend les comportements stratégiques déterminants."],
    ["Qu'est-ce qu'une entente illicite ?", ["Un accord entre concurrents pour fausser la concurrence", "Une fusion d'entreprises", "Un accord de distribution exclusive", "Un partenariat industriel"], 0,
     "Les cartels de prix sont sanctionnés par des amendes pouvant atteindre dix pour cent du chiffre d'affaires mondial."],
    ["Qu'est-ce qu'un abus de position dominante ?", ["L'exploitation abusive d'une puissance de marché", "Le fait d'être en situation de monopole", "Une fusion non autorisée", "Une politique de prix bas"], 0,
     "Être dominant n'est pas illicite ; c'est l'abus qui l'est."],
    ["Quelle autorité française sanctionne les pratiques anticoncurrentielles ?", ["L'Autorité de la concurrence", "La DGCCRF seule", "l'AMF", "L'Arcom"], 0,
     "Elle contrôle aussi les concentrations d'entreprises au-delà de certains seuils."],
    ["Qu'est-ce qu'une externalité négative ?", ["Un coût imposé à des tiers sans compensation par le marché", "Une perte pour l'entreprise", "Un coût de production imprévu", "Une taxe sur la production"], 0,
     "La pollution en est l'exemple type : son coût n'apparaît pas dans le prix du produit."],
    ["Qu'est-ce qu'un bien public au sens économique ?", ["Un bien non rival et non excluable", "Un bien produit par l'État", "Un bien gratuit", "Un bien d'intérêt général"], 0,
     "L'éclairage public ou la défense nationale en sont des exemples : nul ne peut en être exclu."],
    ["Qu'est-ce que l'asymétrie d'information ?", ["Une situation où une partie en sait plus que l'autre", "Un défaut de publicité", "Une inégalité de moyens", "Une différence de compétence technique"], 0,
     "Akerlof l'a illustrée avec le marché des voitures d'occasion, ce qui lui a valu un prix Nobel.", 3],
  ]),

  notion("ie2-emploi-chomage", S, "Emploi et chômage",
    "Mesure, formes, politiques : comprendre les chiffres du travail.",
    "Le chômage se mesure selon des définitions précises : tous les sans-emploi n'y entrent pas.",
    2, [
    ["Qu'est-ce qu'un chômeur au sens du Bureau international du travail ?", ["Une personne sans emploi, disponible et en recherche active", "Toute personne inscrite à France Travail", "Toute personne sans revenu d'activité", "Toute personne ayant perdu son emploi"], 0,
     "Cette définition explique l'écart entre les chiffres du chômage et ceux des inscrits."],
    ["Qu'est-ce que la population active ?", ["Les personnes en emploi et les chômeurs", "Les personnes en âge de travailler", "Les salariés uniquement", "Les personnes ayant un emploi"], 0,
     "Le taux de chômage rapporte les chômeurs à cette population, non à la population totale."],
    ["Qu'est-ce que le taux d'emploi ?", ["La part des personnes en emploi dans la population en âge de travailler", "La part des actifs occupés parmi les actifs", "Le nombre d'emplois créés", "Le taux de remplissage des postes"], 0,
     "Il donne une image souvent plus parlante que le taux de chômage seul."],
    ["Qu'est-ce que le chômage frictionnel ?", ["Le chômage de courte durée lié aux transitions entre emplois", "Le chômage dû à un manque de qualification", "Le chômage lié à la conjoncture", "Le chômage de longue durée"], 0,
     "Il est incompressible : il correspond au temps nécessaire pour trouver un emploi adapté."],
    ["Qu'est-ce que le chômage structurel ?", ["Un chômage lié à l'inadéquation durable entre offres et compétences", "Un chômage lié à la récession", "Un chômage saisonnier", "Un chômage volontaire"], 0,
     "Il ne se résorbe pas par la seule reprise de l'activité."],
    ["Qu'est-ce que le halo autour du chômage ?", ["Les personnes souhaitant travailler mais non comptées comme chômeurs", "Les chômeurs découragés uniquement", "Les travailleurs à temps partiel subi", "Les personnes en formation"], 0,
     "Elles ne remplissent pas tous les critères de disponibilité ou de recherche active."],
    ["Qu'est-ce que le sous-emploi ?", ["Une situation de travail à temps partiel subi ou de chômage technique", "Un emploi sous-qualifié", "Un emploi mal rémunéré", "Un emploi précaire"], 0,
     "Il révèle une sous-utilisation de la main-d'œuvre invisible dans le taux de chômage."],
    ["Qu'est-ce que le SMIC ?", ["Le salaire minimum légal en France", "Le salaire moyen des débutants", "Un plancher conventionnel de branche", "Le minimum garanti pour les temps partiels"], 0,
     "Créé en 1970, il succède au SMIG et est revalorisé automatiquement selon l'inflation."],
    ["Qu'est-ce que la formation professionnelle continue ?", ["Un droit à se former tout au long de la vie active", "La formation initiale prolongée", "L'apprentissage en alternance", "Le tutorat en entreprise"], 0,
     "Le compte personnel de formation en est le principal instrument depuis 2015."],
    ["Qu'est-ce que le taux d'activité des seniors ?", ["La part des cinquante-cinq à soixante-quatre ans en emploi ou au chômage", "Le taux d'emploi des retraités", "La proportion de préretraités", "Le taux de départ à la retraite"], 0,
     "Il est en France inférieur à la moyenne européenne, ce qui pèse sur le financement des retraites.", 3],
  ]),

  notion("ie2-finance", S, "La finance et les marchés",
    "Actions, obligations, bourses, crises : comment circule l'épargne.",
    "Une action est une part de propriété, une obligation une créance : la différence est essentielle.",
    2, [
    ["Quelle différence sépare une action d'une obligation ?", ["L'action est une part du capital, l'obligation une créance", "L'action est plus sûre", "L'obligation donne un droit de vote", "L'action rapporte un intérêt fixe"], 0,
     "L'actionnaire est propriétaire et supporte le risque ; l'obligataire est créancier et passe avant lui."],
    ["Qu'est-ce qu'un dividende ?", ["La part du bénéfice versée aux actionnaires", "L'intérêt d'une obligation", "La plus-value à la revente", "Une commission de courtage"], 0,
     "Son versement n'est pas obligatoire : il dépend des résultats et de la décision de l'assemblée générale."],
    ["Qu'est-ce que le CAC 40 ?", ["Un indice des quarante principales capitalisations de la Bourse de Paris", "L'ensemble des sociétés cotées à Paris", "Un indice européen", "Un classement des entreprises françaises"], 0,
     "Sa composition est révisée régulièrement selon la liquidité et la capitalisation."],
    ["Qu'est-ce qu'une introduction en Bourse ?", ["La première mise sur le marché des actions d'une société", "Une augmentation de capital", "Le rachat d'une société cotée", "Un transfert entre places boursières"], 0,
     "Elle permet de lever des fonds mais impose des obligations d'information permanente."],
    ["Qu'est-ce qu'un produit dérivé ?", ["Un contrat dont la valeur dépend d'un actif sous-jacent", "Une action de filiale", "Une obligation convertible", "Un fonds indiciel"], 0,
     "Options, contrats à terme et swaps permettent de se couvrir ou de spéculer."],
    ["Qu'est-ce qu'une bulle spéculative ?", ["Une hausse des prix déconnectée de la valeur fondamentale", "Une forte volatilité", "Une correction de marché", "Un krach boursier"], 0,
     "Elle se reconnaît surtout après son éclatement, ce qui rend sa détection difficile en temps réel."],
    ["Quelle crise financière débute en 2007 avec les crédits immobiliers américains ?", ["La crise des subprimes", "La crise de la dette souveraine", "Le krach de 1987", "La crise asiatique"], 0,
     "La faillite de Lehman Brothers en septembre 2008 en marque le point culminant."],
    ["Qu'est-ce que le risque systémique ?", ["Le risque qu'une défaillance se propage à tout le système financier", "Le risque propre à un titre", "Le risque de change", "Le risque de liquidité d'une banque"], 0,
     "Il justifie une régulation spécifique des établissements jugés trop grands pour faire faillite."],
    ["Quelle autorité régule les marchés financiers en France ?", ["l'AMF", "l'ACPR seule", "La Banque de France", "l'Autorité de la concurrence"], 0,
     "L'Autorité des marchés financiers veille à l'information des investisseurs et sanctionne les abus."],
    ["Qu'est-ce que le trading à haute fréquence ?", ["Des transactions automatisées exécutées en fractions de seconde", "Un trading intensif manuel", "Un arbitrage entre places boursières", "Une spéculation à court terme classique"], 0,
     "Il représente une part importante des volumes échangés et fait débat quant à son utilité économique.", 3],
  ]),

  notion("ie2-logement", S, "Le logement",
    "Marché, politiques publiques, précarité : se loger comme enjeu économique et social.",
    "Le logement est le premier poste de dépense des ménages français.",
    2, [
    ["Quel est le premier poste de dépense des ménages français ?", ["Le logement et les charges associées", "L'alimentation", "Les transports", "Les loisirs"], 0,
     "Il représente environ un quart du budget, davantage pour les ménages modestes."],
    ["Qu'est-ce que le taux d'effort d'un ménage pour le logement ?", ["La part de son revenu consacrée à se loger", "Le montant de son loyer", "Son endettement immobilier", "Sa capacité d'emprunt"], 0,
     "Un taux supérieur à un tiers est généralement considéré comme excessif."],
    ["Qu'est-ce qu'un logement social en France ?", ["Un logement à loyer plafonné attribué sous conditions de ressources", "Un logement subventionné pour tous", "Un logement propriété de l'État", "Un logement d'urgence"], 0,
     "Plusieurs catégories existent selon le niveau de ressources visé."],
    ["Que prévoit la loi SRU de 2000 ?", ["Un quota de logements sociaux dans certaines communes", "L'encadrement des loyers", "La construction de villes nouvelles", "La rénovation des quartiers anciens"], 0,
     "Le seuil est de vingt ou vingt-cinq pour cent selon les zones, avec des pénalités pour les communes déficitaires."],
    ["Qu'est-ce que l'encadrement des loyers ?", ["Un plafonnement du loyer au mètre carré dans les zones tendues", "Un blocage général des loyers", "Une aide au paiement du loyer", "Une révision annuelle obligatoire"], 0,
     "Expérimenté à Paris puis étendu à d'autres agglomérations, il fait l'objet d'évaluations contrastées."],
    ["Qu'est-ce que la trêve hivernale ?", ["Une période où les expulsions locatives sont suspendues", "Une suspension des loyers", "Un gel des charges de chauffage", "Une aide d'urgence saisonnière"], 0,
     "Du 1er novembre au 31 mars en France, avec des exceptions limitées."],
    ["Qu'est-ce que le droit au logement opposable ?", ["Un droit permettant un recours contre l'État en cas de non-relogement", "Un droit à un logement gratuit", "Une priorité d'attribution automatique", "Un droit de préemption des locataires"], 0,
     "Institué en 2007, son application se heurte à la pénurie de logements disponibles."],
    ["Qu'est-ce qu'une passoire thermique ?", ["Un logement très mal isolé, classé F ou G au diagnostic énergétique", "Un logement sans chauffage", "Un logement humide", "Un logement ancien non rénové"], 0,
     "Leur mise en location est progressivement interdite en France depuis 2023."],
    ["Qu'est-ce que le diagnostic de performance énergétique ?", ["Une évaluation obligatoire de la consommation d'un logement", "Un audit facultatif de chauffage", "Un contrôle des installations", "Une estimation de la facture annuelle"], 0,
     "Il classe le logement de A à G et doit figurer dans toute annonce de vente ou de location."],
    ["Qu'est-ce que l'artificialisation des sols liée à l'habitat ?", ["La transformation de terres naturelles ou agricoles en surfaces construites", "L'imperméabilisation des toitures", "La densification urbaine", "La construction en hauteur"], 0,
     "La loi française vise une réduction progressive jusqu'à l'absence d'artificialisation nette en 2050.", 3],
  ]),

  notion("ie2-education-systeme", S, "Le système éducatif français",
    "Organisation, diplômes, débats : comment l'école est structurée.",
    "L'instruction est obligatoire de trois à seize ans, la scolarisation ne l'est pas.",
    2, [
    ["De quel âge à quel âge l'instruction est-elle obligatoire en France ?", ["De trois à seize ans", "De six à seize ans", "De trois à dix-huit ans", "De six à dix-huit ans"], 0,
     "L'abaissement à trois ans date de 2019. Une obligation de formation s'étend jusqu'à dix-huit ans."],
    ["Quels sont les trois cycles de l'école élémentaire et de la maternelle ?", ["Apprentissages premiers, fondamentaux et consolidation", "Petite, moyenne et grande section", "Cours préparatoire, élémentaire et moyen", "Éveil, apprentissage et approfondissement"], 0,
     "Le cycle de consolidation associe les deux dernières années d'élémentaire et la sixième."],
    ["Quel diplôme sanctionne la fin du collège ?", ["Le diplôme national du brevet", "Le certificat d'études", "Le CAP", "Le baccalauréat"], 0,
     "Il n'est pas nécessaire pour entrer au lycée, l'orientation reposant sur le conseil de classe."],
    ["Quelles sont les trois voies du lycée en France ?", ["Générale, technologique et professionnelle", "Scientifique, littéraire et économique", "Classique, moderne et technique", "Générale, technique et agricole"], 0,
     "La réforme de 2019 a remplacé les séries générales par un système de spécialités."],
    ["Quand le baccalauréat a-t-il été créé sous sa forme moderne ?", ["En 1808, sous Napoléon", "En 1880", "En 1902", "En 1968"], 0,
     "Il reste le premier grade universitaire, ce qui explique qu'il ouvre l'accès à l'enseignement supérieur."],
    ["Qu'est-ce que la carte scolaire ?", ["Un dispositif d'affectation des élèves selon leur lieu de résidence", "Le calendrier scolaire", "La répartition des enseignants", "La carte des académies"], 0,
     "Son assouplissement depuis 2007 a fait l'objet d'évaluations mitigées sur la mixité sociale."],
    ["Qu'est-ce qu'une académie dans le système français ?", ["Une circonscription administrative de l'éducation nationale", "Une université", "Un conseil de discipline", "Une société savante"], 0,
     "Chacune est dirigée par un recteur, représentant du ministre."],
    ["Qu'est-ce que l'enseignement privé sous contrat ?", ["Un enseignement privé financé en partie par l'État en échange d'obligations", "Un enseignement entièrement privé", "Un enseignement confessionnel non financé", "Une école hors contrat subventionnée"], 0,
     "La loi Debré de 1959 en fixe le cadre : programmes nationaux et accueil sans distinction."],
    ["Qu'est-ce que Parcoursup ?", ["La plateforme d'affectation dans l'enseignement supérieur français", "Un dispositif d'orientation au collège", "Un service d'inscription universitaire", "Un portail de bourses étudiantes"], 0,
     "Mise en place en 2018, elle a remplacé Admission Post-Bac."],
    ["Qu'est-ce que l'éducation prioritaire ?", ["Un dispositif renforçant les moyens dans les territoires défavorisés", "Un enseignement pour élèves en difficulté", "Un programme pour élèves précoces", "Un dispositif d'orientation renforcée"], 0,
     "Les réseaux REP et REP+ bénéficient d'effectifs réduits et de moyens supplémentaires.", 3],
  ]),

  notion("ie2-sante-systeme", S, "L'organisation de la santé en France",
    "Financement, acteurs, accès aux soins.",
    "La France combine une offre libérale et un financement largement socialisé.",
    2, [
    ["Comment les soins sont-ils principalement financés en France ?", ["Par l'assurance maladie obligatoire, complétée par les mutuelles", "Par l'impôt seul", "Par les assurances privées", "Par les patients directement"], 0,
     "Le reste à charge des ménages est parmi les plus faibles des pays comparables."],
    ["Qu'est-ce que le parcours de soins coordonné ?", ["Un dispositif où le médecin traitant oriente vers les spécialistes", "Un plan de soins hospitalier", "Un protocole pour affections longues", "Un circuit d'urgence"], 0,
     "Le non-respect du parcours entraîne un remboursement réduit."],
    ["Qu'est-ce qu'une affection de longue durée ?", ["Une maladie chronique ouvrant droit à une prise en charge à cent pour cent", "Une hospitalisation de plus d'un mois", "Une maladie professionnelle", "Un arrêt de travail prolongé"], 0,
     "Une trentaine d'affections sont concernées, dont le diabète et les cancers."],
    ["Qu'est-ce qu'un désert médical ?", ["Un territoire où l'offre de soins est très insuffisante", "Une zone sans hôpital", "Une commune sans pharmacie", "Une région rurale isolée"], 0,
     "Le phénomène touche aussi des zones périurbaines, contrairement à une idée répandue."],
    ["Qu'est-ce que le numerus clausus en médecine ?", ["Une limitation du nombre d'étudiants admis en deuxième année", "Un quota de médecins par département", "Une limite d'installation des praticiens", "Un plafond de remboursements"], 0,
     "Instauré en 1971 et supprimé en 2020, il explique en partie la pénurie actuelle de médecins."],
    ["Qu'est-ce que le tiers payant ?", ["La dispense d'avance de frais pour le patient", "Le paiement par un tiers assureur", "Une prise en charge partielle", "Un règlement différé"], 0,
     "Il est obligatoire pour certaines situations, comme les bénéficiaires de la complémentaire santé solidaire."],
    ["Qu'est-ce que le secteur 2 pour un médecin ?", ["Un secteur autorisant des dépassements d'honoraires", "Un secteur hospitalier public", "Un exercice salarié", "Un secteur non conventionné"], 0,
     "Les dépassements doivent rester mesurés et sont partiellement encadrés par des contrats."],
    ["Qu'est-ce qu'un générique de médicament ?", ["Une copie d'un médicament dont le brevet a expiré", "Un médicament sans marque", "Un médicament vendu sans ordonnance", "Un médicament moins dosé"], 0,
     "Il doit démontrer une bioéquivalence avec le médicament d'origine."],
    ["Qu'est-ce que la Haute Autorité de santé ?", ["Une autorité indépendante évaluant les produits et pratiques de santé", "Un service du ministère de la Santé", "L'organisme gérant l'assurance maladie", "L'agence du médicament"], 0,
     "Ses avis conditionnent notamment le remboursement des médicaments."],
    ["Qu'est-ce que la pharmacovigilance ?", ["La surveillance des effets indésirables des médicaments après commercialisation", "Le contrôle des officines", "La vérification des ordonnances", "Le suivi des stocks pharmaceutiques"], 0,
     "Les essais cliniques ne détectent pas les effets rares : seule l'utilisation à grande échelle les révèle.", 3],
  ]),

  notion("ie2-defense-securite", S, "Défense et sécurité",
    "Forces, doctrine, institutions : comment un État se défend.",
    "La dissuasion nucléaire française repose sur le principe de stricte suffisance.",
    2, [
    ["Qui est le chef des armées en France ?", ["Le président de la République", "Le Premier ministre", "Le ministre des Armées", "Le chef d'état-major des armées"], 0,
     "L'article 15 de la Constitution le prévoit ; il préside les conseils de défense."],
    ["Quand le service militaire obligatoire a-t-il été suspendu en France ?", ["En 1997", "En 1990", "En 2001", "En 2005"], 0,
     "La suspension, décidée par Jacques Chirac, a pris effet progressivement jusqu'en 2001."],
    ["Qu'est-ce que la journée défense et citoyenneté ?", ["Une journée obligatoire de sensibilisation pour les jeunes Français", "Un rappel des réservistes", "Une commémoration nationale", "Une formation militaire volontaire"], 0,
     "Elle a succédé aux trois jours du service national et conditionne l'inscription aux examens."],
    ["Sur quel principe repose la dissuasion nucléaire française ?", ["La stricte suffisance : disposer du minimum nécessaire pour dissuader", "La supériorité numérique", "La frappe préventive", "La parité avec les autres puissances"], 0,
     "La doctrine française insiste sur l'autonomie de décision et le caractère strictement défensif."],
    ["Quelles sont les deux composantes de la dissuasion nucléaire française ?", ["Océanique et aéroportée", "Terrestre et aérienne", "Océanique et terrestre", "Aérienne et spatiale"], 0,
     "La composante terrestre du plateau d'Albion a été démantelée en 1996."],
    ["Qu'est-ce que la gendarmerie nationale ?", ["Une force armée exerçant des missions de police", "Un service de police civile", "Une unité de l'armée de terre", "Une police municipale nationale"], 0,
     "Rattachée au ministère de l'Intérieur depuis 2009, elle conserve son statut militaire."],
    ["Qu'est-ce que le renseignement extérieur français ?", ["La DGSE", "La DGSI", "La DRM seule", "Le SGDSN"], 0,
     "La DGSI est chargée du renseignement intérieur, sous l'autorité du ministère de l'Intérieur."],
    ["Qu'est-ce que le plan Vigipirate ?", ["Un dispositif national de vigilance et de protection contre le terrorisme", "Un plan d'évacuation", "Un plan de secours sanitaire", "Un dispositif de cybersécurité"], 0,
     "Créé en 1978, il comporte plusieurs niveaux d'activation."],
    ["Qu'est-ce que la loi de programmation militaire ?", ["Une loi fixant les moyens des armées sur plusieurs années", "Une loi organisant le service national", "Un budget annuel de la défense", "Un plan d'équipement européen"], 0,
     "Elle donne une visibilité pluriannuelle indispensable aux programmes d'armement, longs à réaliser."],
    ["Qu'est-ce que la cyberdéfense ?", ["La protection des systèmes d'information contre les attaques", "La surveillance d'internet", "La lutte contre la désinformation", "Le renseignement électronique"], 0,
     "Un commandement dédié a été créé en France en 2017, avec des effectifs en forte croissance.", 3],
  ]),

  notion("ie2-histoire-economique", S, "Grandes crises et pensées économiques",
    "Ce que les crises ont changé dans la façon de penser l'économie.",
    "Chaque grande crise a produit une remise en cause des idées dominantes de son époque.",
    2, [
    ["Que se passe-t-il en octobre 1929 à New York ?", ["Un krach boursier majeur", "Une faillite bancaire isolée", "Une dévaluation du dollar", "Une grève générale"], 0,
     "Le jeudi noir marque le début d'une dépression qui durera une décennie."],
    ["Qu'est-ce que le New Deal ?", ["Un programme américain de relance et de réformes dans les années 1930", "Un accord commercial international", "Un plan de reconstruction européen", "Une réforme monétaire américaine"], 0,
     "Grands travaux, régulation bancaire et protection sociale en sont les axes principaux."],
    ["Quel économiste défend en 1936 l'intervention de l'État pour soutenir la demande ?", ["John Maynard Keynes", "Milton Friedman", "Friedrich Hayek", "Joseph Schumpeter"], 0,
     "Sa Théorie générale renverse l'idée que le marché s'autorégule toujours vers le plein emploi."],
    ["Quel économiste défend au contraire le rôle de la monnaie et critique l'interventionnisme ?", ["Milton Friedman", "John Maynard Keynes", "Paul Samuelson", "John Kenneth Galbraith"], 0,
     "Chef de file du monétarisme, il influence les politiques économiques à partir des années 1970."],
    ["Quel économiste autrichien voit dans le marché un système de traitement de l'information ?", ["Friedrich Hayek", "Ludwig von Mises", "Joseph Schumpeter", "Carl Menger"], 0,
     "Il soutient qu'aucun planificateur ne peut réunir l'information dispersée entre les acteurs."],
    ["Quel économiste décrit l'innovation comme une destruction créatrice ?", ["Joseph Schumpeter", "Karl Marx", "David Ricardo", "Alfred Marshall"], 0,
     "Les nouvelles combinaisons détruisent les anciennes activités tout en créant la croissance."],
    ["Qu'est-ce que le système de Bretton Woods ?", ["Un ordre monétaire international fondé sur des changes fixes et le dollar", "Un accord commercial d'après-guerre", "Une union douanière européenne", "Un traité sur les dettes de guerre"], 0,
     "Établi en 1944, il prend fin en 1971 avec la suspension de la convertibilité du dollar en or."],
    ["Qu'est-ce que les chocs pétroliers des années 1970 ?", ["De brusques hausses du prix du pétrole aux effets économiques majeurs", "Des pénuries d'approvisionnement locales", "Des faillites de compagnies pétrolières", "Des découvertes de nouveaux gisements"], 0,
     "Ils provoquent la stagflation, combinaison de chômage et d'inflation que les modèles d'alors n'expliquaient pas."],
    ["Qu'est-ce que la crise de la dette souveraine européenne de 2010 ?", ["Une crise de confiance sur la dette de plusieurs États de la zone euro", "Un défaut de paiement de la France", "Une crise bancaire allemande", "Un effondrement de l'euro"], 0,
     "La Grèce en fut l'épicentre ; elle a conduit à créer des mécanismes de stabilité européens."],
    ["Quelle particularité économique la crise de 2020 présente-t-elle ?", ["Un arrêt volontaire de l'activité pour raisons sanitaires", "Une crise financière classique", "Une crise de surproduction", "Une crise énergétique"], 0,
     "Les soutiens publics massifs ont limité les faillites mais fortement accru l'endettement.", 3],
  ]),

  notion("ie2-numerique-economie", S, "L'économie numérique",
    "Plateformes, données, régulation : ce que le numérique change à l'économie.",
    "Une plateforme ne vend pas un produit : elle organise la rencontre entre plusieurs groupes d'utilisateurs.",
    2, [
    ["Qu'est-ce qu'un marché biface ?", ["Un marché où une plateforme met en relation deux groupes distincts", "Un marché à deux produits", "Un marché à double régulation", "Un marché international"], 0,
     "La plateforme peut subventionner un côté pour attirer l'autre, ce qui déroute l'analyse classique."],
    ["Qu'est-ce qu'un effet de réseau ?", ["La valeur d'un service augmente avec le nombre d'utilisateurs", "L'interconnexion des serveurs", "La vitesse de diffusion d'un service", "Le partage des infrastructures"], 0,
     "Il favorise la concentration : le premier arrivé devient très difficile à déloger."],
    ["Qu'est-ce que l'économie de l'attention ?", ["Un modèle où le temps et l'attention des utilisateurs sont la ressource vendue", "Une économie du service client", "Un marché de la publicité classique", "Une économie fondée sur la qualité"], 0,
     "Elle explique la conception d'interfaces visant à maximiser le temps passé."],
    ["Qu'est-ce que le RGPD encadre ?", ["Le traitement des données personnelles", "Le commerce en ligne", "La fiscalité numérique", "La cybersécurité des entreprises"], 0,
     "Il impose une base légale pour tout traitement et confère des droits aux personnes concernées."],
    ["Que vise le règlement européen sur les marchés numériques ?", ["Encadrer les pratiques des très grandes plateformes contrôlant l'accès aux marchés", "Taxer les revenus numériques", "Réguler les contenus illicites", "Harmoniser le commerce électronique"], 0,
     "Il impose des obligations aux contrôleurs d'accès, comme l'interopérabilité ou l'interdiction de l'auto-préférence."],
    ["Qu'est-ce que l'obsolescence des compétences numériques ?", ["Le vieillissement rapide des savoir-faire techniques", "L'obsolescence des équipements", "La fin de vie des logiciels", "L'abandon d'un standard technique"], 0,
     "Elle rend la formation continue particulièrement critique dans ces métiers."],
    ["Qu'est-ce que le travail de plateforme ?", ["Une activité indépendante organisée par une application", "Un télétravail salarié", "Un travail intérimaire numérique", "Un emploi en centre d'appel"], 0,
     "Son statut juridique fait l'objet de contentieux nombreux sur la requalification en salariat."],
    ["Qu'est-ce que la fracture numérique ?", ["Les inégalités d'accès et d'usage des outils numériques", "La panne d'un réseau", "La séparation entre logiciels libres et propriétaires", "La différence entre générations"], 0,
     "Elle combine accès aux équipements, qualité du réseau et compétences d'usage."],
    ["Qu'est-ce que l'empreinte environnementale du numérique ?", ["L'ensemble des impacts liés aux équipements, réseaux et centres de données", "La consommation électrique des serveurs seule", "Les déchets électroniques uniquement", "Les émissions liées au streaming"], 0,
     "La fabrication des terminaux en représente la part la plus importante, avant leur usage."],
    ["Qu'est-ce qu'un logiciel libre ?", ["Un logiciel dont la licence garantit l'usage, l'étude, la modification et le partage", "Un logiciel gratuit", "Un logiciel sans licence", "Un logiciel open source commercial"], 0,
     "Gratuit et libre sont deux notions distinctes : un logiciel libre peut être vendu.", 3],
  ]),

  notion("ie2-inegalites-mondiales", S, "Développement et inégalités mondiales",
    "Mesures, mécanismes, politiques : les écarts entre pays et en leur sein.",
    "L'écart entre pays s'est réduit tandis que les inégalités internes augmentaient dans de nombreux États.",
    2, [
    ["Qu'est-ce que l'extrême pauvreté selon la Banque mondiale ?", ["Vivre sous un seuil international de revenu quotidien", "N'avoir aucun revenu", "Vivre sous le seuil de pauvreté national", "Être sans logement"], 0,
     "Le seuil est réévalué régulièrement en parité de pouvoir d'achat."],
    ["Quelle évolution l'extrême pauvreté mondiale a-t-elle connue depuis 1990 ?", ["Une forte baisse, portée surtout par l'Asie", "Une hausse continue", "Une stabilité", "Une baisse uniquement en Afrique"], 0,
     "La Chine y a contribué de façon décisive. La tendance a marqué le pas depuis 2020."],
    ["Qu'est-ce que l'aide publique au développement ?", ["Des transferts publics des pays riches vers les pays en développement", "Les investissements privés à l'étranger", "Les envois de fonds des migrants", "Les prêts commerciaux internationaux"], 0,
     "L'objectif de zéro virgule sept pour cent du revenu national brut est rarement atteint."],
    ["Que représentent les transferts de fonds des migrants pour de nombreux pays ?", ["Une ressource souvent supérieure à l'aide publique au développement", "Une ressource marginale", "Un flux équivalent aux exportations", "Une source d'endettement"], 0,
     "Ces envois sont plus stables que les investissements étrangers en période de crise."],
    ["Qu'est-ce que le microcrédit ?", ["Un prêt de faible montant à des personnes exclues du système bancaire", "Un crédit à taux réduit", "Un prêt d'honneur d'État", "Un crédit à la consommation encadré"], 0,
     "Muhammad Yunus a reçu le prix Nobel de la paix en 2006 pour son développement au Bangladesh."],
    ["Qu'est-ce que le commerce équitable ?", ["Un système garantissant un prix minimum et des conditions au producteur", "Un commerce sans intermédiaire", "Un commerce sans droits de douane", "Un échange de biens de valeur égale"], 0,
     "Son impact réel fait l'objet d'évaluations nuancées selon les filières."],
    ["Qu'est-ce que la dette des pays en développement ?", ["Un endettement dont le service peut absorber une part majeure des recettes publiques", "Une dette systématiquement annulée", "Un endettement privé uniquement", "Une dette envers le seul FMI"], 0,
     "Les initiatives d'allègement des années 2000 ont été suivies d'un réendettement rapide."],
    ["Que mesure le coefficient de Gini au sein d'un pays ?", ["La concentration des revenus ou des patrimoines", "Le niveau de pauvreté", "La croissance économique", "Le niveau de vie médian"], 0,
     "Le Gini des patrimoines est presque toujours bien plus élevé que celui des revenus."],
    ["Qu'est-ce que la mobilité sociale intergénérationnelle ?", ["La capacité à occuper une position différente de celle de ses parents", "Le changement d'emploi au cours d'une carrière", "La migration géographique", "L'ascension professionnelle interne"], 0,
     "Elle varie fortement d'un pays à l'autre et est plus faible là où les inégalités sont fortes."],
    ["Qu'est-ce que la courbe de Gatsby le Magnifique ?", ["Une relation entre inégalités et faible mobilité sociale", "Une courbe de croissance des patrimoines", "Un indicateur de richesse relative", "Une mesure du ruissellement"], 0,
     "Elle illustre que plus un pays est inégalitaire, moins la position des enfants s'écarte de celle des parents.", 3],
  ]),

  notion("ie2-justice-penale", S, "La justice pénale",
    "Infractions, procédure, peines : comment la société sanctionne.",
    "La procédure pénale française est mixte : inquisitoire à l'instruction, accusatoire au procès.",
    2, [
    ["Quelles sont les trois catégories d'infractions en droit français ?", ["Contraventions, délits et crimes", "Fautes, délits et crimes", "Infractions légères, moyennes et graves", "Contraventions, fautes et crimes"], 0,
     "La distinction commande la juridiction compétente, la procédure et les peines encourues."],
    ["Qu'est-ce que la garde à vue ?", ["Une mesure privative de liberté pendant une enquête", "Une détention avant jugement", "Une peine de courte durée", "Une mesure de sûreté après condamnation"], 0,
     "Sa durée de droit commun est de vingt-quatre heures, renouvelable une fois."],
    ["Qu'est-ce que la détention provisoire ?", ["L'incarcération d'une personne présumée innocente avant son jugement", "Une peine ferme immédiate", "Une garde à vue prolongée", "Un placement sous surveillance électronique"], 0,
     "Elle est décidée par le juge des libertés et de la détention, non par le juge d'instruction."],
    ["Qu'est-ce que le principe de légalité des délits et des peines ?", ["Nul ne peut être puni pour un fait non prévu par la loi", "Toute infraction doit être poursuivie", "La peine doit être proportionnée", "La loi pénale s'applique à tous"], 0,
     "Il implique aussi la non-rétroactivité de la loi pénale plus sévère."],
    ["Qu'est-ce que la prescription pénale ?", ["Le délai au-delà duquel une infraction ne peut plus être poursuivie", "L'extinction de la peine par le temps", "La durée d'inscription au casier", "Le délai de recours"], 0,
     "Certains crimes, comme les crimes contre l'humanité, sont imprescriptibles."],
    ["Qu'est-ce qu'une partie civile ?", ["La victime qui se joint à l'action publique pour demander réparation", "Le représentant de la société", "Le témoin principal", "L'avocat de la défense"], 0,
     "Sa constitution permet d'accéder au dossier et de participer à l'audience."],
    ["Qu'est-ce que le sursis ?", ["Une dispense d'exécution de tout ou partie d'une peine sous conditions", "Une réduction de peine automatique", "Un report du procès", "Une libération conditionnelle"], 0,
     "Le sursis probatoire impose des obligations dont le non-respect entraîne la révocation."],
    ["Qu'est-ce que la libération conditionnelle ?", ["Une sortie anticipée sous conditions avant la fin de la peine", "Une remise de peine automatique", "Une grâce présidentielle", "Une suspension de peine médicale"], 0,
     "Elle est accordée par le juge d'application des peines et vise à préparer la réinsertion."],
    ["Quand la peine de mort a-t-elle été abolie en France ?", ["En 1981", "En 1968", "En 1975", "En 1990"], 0,
     "Sur proposition de Robert Badinter, alors garde des Sceaux. L'abolition est inscrite dans la Constitution depuis 2007."],
    ["Qu'est-ce que la justice restaurative ?", ["Un processus de dialogue entre auteur et victime en complément de la justice pénale", "Une réparation financière imposée", "Une peine alternative à la prison", "Une médiation obligatoire"], 0,
     "Introduite en droit français en 2014, elle repose sur le volontariat des deux parties.", 3],
  ]),

  notion("ie2-agriculture-politique", S, "Les politiques agricoles et alimentaires",
    "Soutiens, régulation, souveraineté : comment les États encadrent l'alimentation.",
    "La politique agricole commune a d'abord été conçue pour assurer l'autosuffisance alimentaire européenne.",
    2, [
    ["Quel était l'objectif initial de la politique agricole commune en 1962 ?", ["Assurer l'autosuffisance alimentaire de l'Europe", "Protéger l'environnement", "Soutenir les revenus agricoles seuls", "Ouvrir les marchés agricoles"], 0,
     "L'Europe sortait de décennies de pénuries et de dépendance aux importations."],
    ["Qu'est-ce qu'un paiement direct dans la politique agricole commune ?", ["Une aide au revenu versée à l'hectare", "Une subvention à la production", "Un prix garanti", "Une aide à l'exportation"], 0,
     "Le découplage des aides et de la production a été introduit dans les années 2000."],
    ["Qu'est-ce que l'écoconditionnalité des aides agricoles ?", ["Le versement des aides est soumis au respect de règles environnementales", "Une aide réservée à l'agriculture biologique", "Un bonus écologique volontaire", "Une taxe sur les pratiques polluantes"], 0,
     "Elle vise à orienter les pratiques sans imposer un modèle unique."],
    ["Qu'est-ce que la souveraineté alimentaire ?", ["La capacité d'un pays à définir sa politique agricole et à nourrir sa population", "L'autosuffisance totale", "L'interdiction des importations", "La production nationale de toutes les denrées"], 0,
     "Le concept a été formulé par des organisations paysannes, en réponse à la libéralisation des échanges."],
    ["Qu'est-ce que la loi EGalim en France ?", ["Une loi visant à rééquilibrer les relations commerciales agricoles", "Une loi sur l'agriculture biologique", "Une loi sur l'étiquetage alimentaire", "Une loi sur les circuits courts"], 0,
     "Adoptée en 2018 puis complétée, elle vise notamment la construction du prix à partir des coûts de production."],
    ["Qu'est-ce que le seuil de revente à perte ?", ["Un prix plancher en dessous duquel un distributeur ne peut vendre", "Le seuil de rentabilité d'un produit", "Le prix minimum payé au producteur", "Un plafond de marge"], 0,
     "Son relèvement visait à limiter l'usage de produits alimentaires comme produits d'appel."],
    ["Qu'est-ce qu'une interprofession agricole ?", ["Une organisation réunissant les acteurs d'une filière", "Un syndicat agricole", "Une coopérative de producteurs", "Un organisme de certification"], 0,
     "Elle peut négocier des accords étendus à toute la filière par arrêté."],
    ["Qu'est-ce que le plan Écophyto ?", ["Un plan de réduction de l'usage des produits phytosanitaires", "Un programme de protection des sols", "Un plan d'aide à l'agriculture biologique", "Un dispositif de traçabilité"], 0,
     "Lancé en 2008, ses objectifs de réduction ont été plusieurs fois reportés."],
    ["Qu'est-ce que le foncier agricole ?", ["Les terres agricoles et les règles régissant leur accès", "Le patrimoine bâti des exploitations", "Le capital d'exploitation", "Les droits à produire"], 0,
     "Les SAFER peuvent préempter des ventes pour favoriser l'installation d'agriculteurs."],
    ["Qu'est-ce que le renouvellement des générations en agriculture ?", ["L'enjeu du remplacement des agriculteurs partant à la retraite", "La rotation des cultures", "Le renouvellement du cheptel", "La transmission familiale des terres"], 0,
     "Une part importante des exploitants français a plus de cinquante ans, ce qui pose la question de la reprise.", 3],
  ]),

  notion("ie2-transports-politiques", S, "Les politiques de transport",
    "Réseaux, financement, arbitrages : organiser la mobilité.",
    "Le transport est le premier secteur émetteur de gaz à effet de serre en France.",
    2, [
    ["Quelle entreprise gère le réseau ferré français ?", ["SNCF Réseau", "La RATP", "Réseau ferré de France, aujourd'hui intégré", "L'ARAFER"], 0,
     "La séparation entre gestionnaire d'infrastructure et exploitant découle des directives européennes."],
    ["Qu'est-ce que l'ouverture à la concurrence ferroviaire ?", ["La possibilité pour plusieurs opérateurs d'exploiter des lignes", "La privatisation du réseau", "La fin des trains régionaux", "La suppression des monopoles régionaux"], 0,
     "Elle se déploie progressivement en France depuis 2020 pour les liaisons longue distance."],
    ["Qu'est-ce qu'une autorité organisatrice de mobilité ?", ["Une collectivité chargée d'organiser les transports sur son territoire", "Une entreprise de transport public", "Un régulateur national", "Un syndicat de transporteurs"], 0,
     "Régions, intercommunalités et métropoles en exercent la compétence selon les échelles."],
    ["Qu'est-ce que le versement mobilité ?", ["Une contribution des employeurs finançant les transports publics", "Une taxe sur les carburants", "Un péage urbain", "Une redevance des usagers"], 0,
     "Il constitue une ressource majeure des réseaux urbains français."],
    ["Qu'est-ce qu'une zone à faibles émissions ?", ["Un périmètre où la circulation des véhicules polluants est restreinte", "Une zone piétonne", "Un quartier sans voiture", "Une zone limitée à trente kilomètres par heure"], 0,
     "Le classement Crit'Air en détermine l'accès en France."],
    ["Qu'est-ce que le report modal ?", ["Le transfert de trafic d'un mode de transport vers un autre", "Le changement d'itinéraire", "Le décalage horaire des trajets", "La substitution d'un véhicule par un autre"], 0,
     "Faire passer du fret de la route au rail en est l'exemple le plus recherché."],
    ["Qu'est-ce que le fret ferroviaire ?", ["Le transport de marchandises par le train", "Le transport de voyageurs longue distance", "Le transport combiné rail-route", "Le transport de conteneurs maritimes"], 0,
     "Sa part modale a fortement reculé en France depuis les années 1980, à rebours d'autres pays européens."],
    ["Qu'est-ce que le transport combiné ?", ["L'acheminement d'une même unité de charge par plusieurs modes", "Le transport de passagers et de fret ensemble", "Un service intégrant plusieurs opérateurs", "Un trajet à correspondances multiples"], 0,
     "Le conteneur en est l'unité de base, transférée sans rupture de charge entre navire, train et camion."],
    ["Qu'est-ce qu'une infrastructure de recharge pour véhicules électriques ?", ["Un réseau de bornes conditionnant l'usage de ces véhicules", "Un parking équipé", "Une station-service adaptée", "Un dispositif domestique de charge"], 0,
     "Son déploiement inégal sur le territoire est l'un des principaux freins à l'adoption."],
    ["Quel mode de transport domine les émissions du secteur en France ?", ["La voiture individuelle", "Le transport aérien intérieur", "Le fret ferroviaire", "Le transport maritime"], 0,
     "Elle en représente à elle seule plus de la moitié, loin devant les poids lourds et l'aérien.", 3],
  ]),

  notion("ie2-culture-politiques", S, "Les politiques culturelles",
    "Financement, démocratisation, exception culturelle.",
    "La France a créé le premier ministère de la Culture au monde en 1959.",
    2, [
    ["Qui est le premier ministre français de la Culture en 1959 ?", ["André Malraux", "Jack Lang", "Jacques Duhamel", "Michel Guy"], 0,
     "Sa mission était de rendre accessibles les œuvres capitales de l'humanité au plus grand nombre."],
    ["Qu'est-ce qu'une maison de la culture ?", ["Un équipement culturel de proximité créé sous Malraux", "Un musée régional", "Une bibliothèque municipale", "Un centre de formation artistique"], 0,
     "Elles visaient à décentraliser l'accès à la création, hors de Paris."],
    ["Qu'est-ce que l'exception culturelle française ?", ["Le refus de traiter les biens culturels comme des marchandises ordinaires", "Une subvention réservée aux artistes français", "Un quota de production nationale", "Une exonération fiscale du secteur culturel"], 0,
     "Elle a permis d'exclure l'audiovisuel des négociations commerciales internationales dans les années 1990."],
    ["Comment le cinéma français est-il principalement soutenu ?", ["Par une taxe sur les billets et les diffuseurs redistribuée par le CNC", "Par des subventions directes de l'État", "Par un crédit d'impôt seul", "Par des fonds régionaux"], 0,
     "Le mécanisme est largement automatique et redistributif, ce qui le distingue d'une subvention discrétionnaire."],
    ["Qu'est-ce que la chronologie des médias ?", ["Les délais entre la sortie en salle et les autres modes de diffusion", "Le calendrier des sorties de films", "L'ordre de diffusion à la télévision", "Le classement des œuvres par date"], 0,
     "Elle protège l'exploitation en salle et a été renégociée avec l'arrivée des plateformes."],
    ["Qu'est-ce que le pass Culture ?", ["Une aide financière pour l'accès des jeunes aux biens culturels", "Un abonnement aux musées nationaux", "Une carte de réduction étudiante", "Un dispositif scolaire d'éducation artistique"], 0,
     "Il comporte une part individuelle et une part collective mobilisée par les établissements scolaires."],
    ["Qu'est-ce que la gratuité des musées nationaux pour les moins de vingt-six ans ?", ["Une mesure applicable aux résidents de l'Union européenne", "Une gratuité universelle", "Une réduction de moitié", "Une gratuité réservée aux étudiants"], 0,
     "Elle s'applique aux collections permanentes, non systématiquement aux expositions temporaires."],
    ["Qu'est-ce que le mécénat culturel en France ?", ["Un soutien privé ouvrant droit à une réduction d'impôt", "Un financement public délégué", "Un partenariat commercial", "Un don sans contrepartie fiscale"], 0,
     "La loi Aillagon de 2003 a fortement développé cette pratique."],
    ["Qu'est-ce qu'une scène nationale ?", ["Un label attribué à des établissements de spectacle vivant sur le territoire", "Une salle parisienne subventionnée", "Un théâtre national", "Un festival labellisé"], 0,
     "Une soixantaine de structures forment ce réseau, financé conjointement par l'État et les collectivités."],
    ["Qu'est-ce que la démocratisation culturelle ?", ["L'objectif d'élargir l'accès aux œuvres à tous les publics", "La gestion démocratique des institutions", "La production culturelle participative", "La diffusion de la culture populaire"], 0,
     "Les enquêtes montrent que la fréquentation reste fortement corrélée au niveau de diplôme, malgré les politiques menées.", 3],
  ]),

  notion("ie2-associations-economie-sociale", S, "Économie sociale et solidaire",
    "Associations, coopératives, mutuelles, fondations : une autre façon d'entreprendre.",
    "Dans une coopérative, chaque associé dispose d'une voix, quel que soit son apport.",
    2, [
    ["Quelle règle distingue une coopérative d'une société classique ?", ["Une personne, une voix", "L'absence de bénéfices", "L'interdiction de salarier", "La propriété publique"], 0,
     "Le pouvoir n'est pas proportionnel au capital détenu."],
    ["Qu'est-ce qu'une SCOP ?", ["Une société coopérative dont les salariés sont associés majoritaires", "Une société civile de production", "Une coopérative de consommateurs", "Une association employeuse"], 0,
     "Les salariés y détiennent au moins cinquante et un pour cent du capital et la majorité des droits de vote."],
    ["Qu'est-ce qu'une mutuelle ?", ["Une organisation à but non lucratif couvrant des risques pour ses adhérents", "Une compagnie d'assurance privée", "Un organisme de sécurité sociale", "Une caisse de retraite complémentaire"], 0,
     "Elle appartient à ses adhérents et ne verse pas de dividendes à des actionnaires."],
    ["Qu'est-ce qu'une association loi 1901 ?", ["Un groupement à but non lucratif fondé sur la liberté d'association", "Une entreprise à but social", "Une fondation reconnue d'utilité publique", "Une coopérative de services"], 0,
     "Le partage des bénéfices entre membres y est interdit, mais elle peut exercer une activité économique."],
    ["Qu'est-ce qu'une fondation ?", ["L'affectation irrévocable de biens à une œuvre d'intérêt général", "Une association durable", "Une entreprise philanthropique", "Un fonds de dotation public"], 0,
     "À la différence de l'association, elle repose sur un patrimoine plutôt que sur des membres."],
    ["Qu'est-ce que l'insertion par l'activité économique ?", ["Un dispositif employant des personnes éloignées de l'emploi avec un accompagnement", "Un stage en entreprise", "Une formation professionnelle", "Un contrat aidé classique"], 0,
     "Chantiers, ateliers et entreprises d'insertion en sont les principales formes."],
    ["Qu'est-ce qu'une entreprise à mission ?", ["Une société inscrivant une raison d'être sociale ou environnementale dans ses statuts", "Une entreprise sans but lucratif", "Une entreprise publique déléguée", "Une association employeuse"], 0,
     "Créée par la loi Pacte de 2019, cette qualité s'accompagne d'un contrôle par un organisme tiers."],
    ["Qu'est-ce que le bénévolat ?", ["Une activité librement consentie et non rémunérée", "Un travail faiblement rémunéré", "Un service civique", "Un volontariat indemnisé"], 0,
     "Sa contribution économique, difficile à chiffrer, représente l'équivalent de centaines de milliers d'emplois."],
    ["Qu'est-ce que le service civique en France ?", ["Un engagement volontaire indemnisé de six à douze mois", "Un service militaire alternatif", "Un stage obligatoire", "Un contrat de travail aidé"], 0,
     "Créé en 2010, il est ouvert aux seize-vingt-cinq ans sans condition de diplôme."],
    ["Quelle part de l'emploi salarié français l'économie sociale et solidaire représente-t-elle ?", ["Environ un dixième", "Environ un tiers", "Environ un pour cent", "Environ un quart"], 0,
     "Elle est particulièrement présente dans l'action sociale, la santé, le sport et la culture.", 3],
  ]),
];
