/**
 * Institutions & Économie, troisième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Institutions & Économie";

export const CG_INSTITUTIONS_ECONOMIE_3: SeedSkill[] = [
  notion("ie3-elections-france", S, "Les élections en France",
    "Modes de scrutin, calendrier, participation.",
    "Chaque élection française obéit à un mode de scrutin différent.",
    2, [
    ["Comment le président de la République est-il élu ?", ["Au scrutin uninominal majoritaire à deux tours", "À la proportionnelle", "Par le Parlement", "Au scrutin de liste"], 0,
     "Seuls les deux candidats arrivés en tête peuvent se maintenir au second tour."],
    ["Quel mode de scrutin s'applique aux élections législatives ?", ["Le scrutin uninominal majoritaire à deux tours par circonscription", "La proportionnelle nationale", "Le scrutin de liste régional", "Le scrutin à un tour"], 0,
     "Il faut réunir au moins douze virgule cinq pour cent des inscrits pour se maintenir au second tour."],
    ["Quel mode de scrutin s'applique aux élections européennes en France ?", ["La proportionnelle sur une circonscription nationale", "Le scrutin majoritaire", "La proportionnelle régionale", "Le scrutin de liste départemental"], 0,
     "Un seuil de cinq pour cent est nécessaire pour obtenir des sièges."],
    ["Comment sont élus les conseillers municipaux dans les communes de plus de mille habitants ?", ["Au scrutin de liste avec prime majoritaire", "Au scrutin uninominal", "À la proportionnelle intégrale", "Au scrutin plurinominal"], 0,
     "La liste arrivée en tête obtient d'emblée la moitié des sièges."],
    ["Qu'est-ce que la prime majoritaire ?", ["Une attribution automatique de sièges à la liste arrivée en tête", "Un bonus de voix", "Un seuil de représentation", "Une répartition proportionnelle corrigée"], 0,
     "Elle vise à dégager une majorité stable de gestion."],
    ["Qu'est-ce que la parité aux élections françaises ?", ["Une obligation d'alternance des sexes sur les listes", "Une recommandation", "Une obligation de résultat", "Une règle réservée aux européennes"], 0,
     "Elle s'applique à tous les scrutins de liste depuis 2000, avec des pénalités financières pour les législatives."],
    ["Qu'est-ce que le vote par procuration ?", ["La délégation de son vote à un autre électeur", "Un vote par correspondance", "Un vote anticipé", "Un vote électronique"], 0,
     "Depuis 2022, le mandataire peut être inscrit dans une autre commune."],
    ["Qu'est-ce que l'abstention ?", ["Le fait de ne pas participer à un scrutin auquel on est inscrit", "Le vote blanc", "Le vote nul", "La non-inscription"], 0,
     "Elle atteint des niveaux records aux élections locales et européennes depuis vingt ans."],
    ["Qu'est-ce que le vote blanc en France ?", ["Un bulletin vierge décompté séparément mais non intégré aux suffrages exprimés", "Un vote nul", "Une abstention enregistrée", "Un suffrage exprimé"], 0,
     "Depuis 2014, il est décompté à part sans influer sur les pourcentages des candidats."],
    ["Qu'est-ce que le mal-inscrit sur les listes électorales ?", ["Un électeur inscrit dans une commune où il ne réside plus", "Un électeur non inscrit", "Un électeur radié", "Un électeur inscrit deux fois"], 0,
     "Le phénomène concerne plusieurs millions de personnes et alimente l'abstention.", 3],
  ]),

  notion("ie3-partis-politiques", S, "Les partis politiques",
    "Rôle, financement, organisation.",
    "Les partis politiques français sont financés en grande partie sur fonds publics.",
    2, [
    ["Que dit la Constitution française des partis politiques ?", ["Ils concourent à l'expression du suffrage et se forment librement", "Ils sont agréés par l'État", "Ils sont réglementés par le Parlement", "Ils doivent être déclarés en préfecture uniquement"], 0,
     "L'article 4 leur impose de respecter les principes de la souveraineté nationale et de la démocratie."],
    ["Comment les partis politiques français sont-ils financés publiquement ?", ["Selon les résultats aux législatives et le nombre de parlementaires", "Par une dotation forfaitaire égale", "Par des subventions ministérielles", "Par les collectivités locales"], 0,
     "La loi de 1988 a instauré ce financement pour limiter la dépendance aux dons privés."],
    ["Quel plafond s'applique aux dons de particuliers à un parti en France ?", ["Sept mille cinq cents euros par an et par personne", "Sans plafond", "Mille euros", "Cent mille euros"], 0,
     "Les dons d'entreprises sont interdits depuis 1995."],
    ["Qu'est-ce que la Commission nationale des comptes de campagne ?", ["Une autorité contrôlant les comptes des candidats et des partis", "Une juridiction électorale", "Un service du ministère de l'Intérieur", "Une commission parlementaire"], 0,
     "Elle peut rejeter un compte, ce qui entraîne la perte du remboursement et une possible inéligibilité."],
    ["Qu'est-ce que le plafonnement des dépenses de campagne ?", ["Une limite légale au montant dépensé par candidat", "Un plafond de dons", "Un plafond de remboursement", "Une limite de durée de campagne"], 0,
     "Il varie selon le type d'élection et le nombre d'habitants concernés."],
    ["Qu'est-ce qu'une primaire politique ?", ["Une élection interne désignant le candidat d'un parti ou d'un camp", "Un premier tour d'élection", "Une consultation militante non contraignante", "Une désignation par les instances"], 0,
     "Ouverte ou fermée selon qu'elle est réservée aux adhérents ou étendue aux sympathisants."],
    ["Qu'est-ce qu'un groupe parlementaire ?", ["Un regroupement de parlementaires partageant des orientations communes", "Un parti politique", "Une commission permanente", "Une intergroupe thématique"], 0,
     "Il faut au moins quinze députés pour en constituer un à l'Assemblée nationale."],
    ["Qu'est-ce qu'un député non inscrit ?", ["Un parlementaire n'appartenant à aucun groupe", "Un député sans étiquette", "Un député démissionnaire", "Un député suppléant"], 0,
     "Il dispose de bien moins de temps de parole et de moyens que ses collègues."],
    ["Qu'est-ce que le clivage gauche-droite ?", ["Une structuration politique héritée du placement dans l'assemblée de 1789", "Une opposition idéologique récente", "Un découpage électoral", "Une distinction constitutionnelle"], 0,
     "Les partisans du veto royal siégeaient à droite du président de séance."],
    ["Qu'est-ce que la démocratie interne d'un parti ?", ["Les procédures permettant aux adhérents de participer aux décisions", "L'élection des dirigeants seule", "Le vote des militants sur les candidatures", "Le respect des statuts"], 0,
     "Elle est très variable d'un parti à l'autre, sans obligation légale précise en France.", 3],
  ]),

  notion("ie3-fiscalite", S, "La fiscalité française",
    "Impôts, taux, redistribution.",
    "Un impôt progressif prélève une part croissante du revenu à mesure qu'il augmente.",
    2, [
    ["Comment fonctionne l'impôt sur le revenu français ?", ["Par tranches, chaque fraction du revenu étant taxée à son propre taux", "Par un taux unique appliqué au revenu total", "Par un forfait selon la catégorie", "Par un prélèvement proportionnel"], 0,
     "Franchir une tranche n'augmente jamais l'impôt total au-delà du gain obtenu."],
    ["Qu'est-ce que le quotient familial ?", ["Un mécanisme divisant le revenu par un nombre de parts selon la composition du foyer", "Une réduction d'impôt par enfant", "Un abattement forfaitaire", "Un crédit d'impôt familial"], 0,
     "Son avantage est plafonné, ce qui limite son effet pour les hauts revenus."],
    ["Qu'est-ce que le prélèvement à la source ?", ["Une collecte de l'impôt directement sur le revenu versé", "Un acompte trimestriel", "Un paiement mensuel automatique", "Une déclaration simplifiée"], 0,
     "Instauré en France en 2019, bien après la plupart des pays comparables."],
    ["Quelle est la part des ménages payant l'impôt sur le revenu en France ?", ["Un peu moins de la moitié", "La quasi-totalité", "Un quart", "Trois quarts"], 0,
     "Le nombre de tranches et les seuils expliquent cette proportion."],
    ["Qu'est-ce que la TVA à taux réduit ?", ["Un taux inférieur applicable à certains biens et services", "Une exonération partielle", "Un taux régional", "Un taux réservé aux entreprises"], 0,
     "Alimentation, livres et travaux de rénovation en bénéficient selon des taux différenciés."],
    ["Qu'est-ce qu'un impôt proportionnel ?", ["Un impôt dont le taux est identique quel que soit le montant imposé", "Un impôt à taux croissant", "Un impôt forfaitaire", "Un impôt à taux décroissant"], 0,
     "La TVA est proportionnelle, mais son effet est régressif rapporté au revenu."],
    ["Pourquoi la TVA est-elle jugée régressive ?", ["Elle pèse davantage sur les ménages modestes rapportée à leur revenu", "Son taux augmente avec le revenu", "Elle exonère les hauts revenus", "Elle ne s'applique qu'aux biens de base"], 0,
     "Les ménages modestes consomment une plus grande part de leur revenu."],
    ["Qu'est-ce que la taxe foncière ?", ["Un impôt local dû par les propriétaires de biens immobiliers", "Un impôt sur les revenus locatifs", "Une taxe sur les transactions", "Un impôt sur le patrimoine"], 0,
     "Elle finance principalement les communes et leurs groupements."],
    ["Qu'est-ce que l'impôt sur la fortune immobilière ?", ["Un impôt sur le patrimoine immobilier au-delà d'un seuil", "Un impôt sur tous les actifs", "Une taxe sur les plus-values", "Un impôt sur les successions"], 0,
     "Il a remplacé en 2018 l'impôt de solidarité sur la fortune, dont l'assiette était plus large."],
    ["Qu'est-ce que la niche fiscale ?", ["Un dispositif dérogatoire réduisant l'impôt dû", "Une exonération générale", "Un abattement de droit commun", "Un crédit d'impôt universel"], 0,
     "Leur coût total pour les finances publiques se chiffre en dizaines de milliards d'euros.", 3],
  ]),

  notion("ie3-protection-consommateur", S, "Protection du consommateur",
    "Contrats, garanties, litiges.",
    "Le droit de la consommation protège la partie présumée la plus faible au contrat.",
    2, [
    ["Qu'est-ce qu'un contrat d'adhésion ?", ["Un contrat dont les clauses ne sont pas négociables", "Un contrat conclu à distance", "Un contrat oral", "Un contrat entre professionnels"], 0,
     "Le droit y renforce la protection de la partie qui n'a pas rédigé le contrat."],
    ["Qu'est-ce que l'obligation d'information précontractuelle ?", ["Le devoir d'informer le consommateur des caractéristiques essentielles avant l'achat", "Une publicité obligatoire", "Un devoir de conseil après-vente", "Une notice technique"], 0,
     "Son manquement peut entraîner la nullité du contrat ou des sanctions administratives."],
    ["Qu'est-ce qu'un délai de réflexion, par rapport à un délai de rétractation ?", ["Le délai de réflexion précède la signature, la rétractation la suit", "Ce sont deux termes équivalents", "Le délai de réflexion suit la livraison", "La rétractation précède l'engagement"], 0,
     "Le crédit immobilier impose ainsi un délai de réflexion de dix jours."],
    ["Qu'est-ce que le démarchage téléphonique en France ?", ["Une pratique encadrée par des horaires et un registre d'opposition", "Une pratique interdite", "Une pratique libre", "Une pratique réservée à certains secteurs"], 0,
     "Le dispositif Bloctel permet de s'y opposer, avec une efficacité inégale."],
    ["Qu'est-ce que la garantie légale des vices cachés ?", ["Une protection contre un défaut non apparent rendant le bien impropre", "La garantie de conformité", "La garantie commerciale", "Une assurance du vendeur"], 0,
     "Elle s'applique aussi entre particuliers, contrairement à la garantie de conformité."],
    ["Qu'est-ce qu'un service après-vente ?", ["Un service assurant réparation, entretien ou assistance après l'achat", "Une garantie légale", "Un contrat d'extension de garantie", "Une assistance téléphonique"], 0,
     "Il ne se confond pas avec les garanties légales, qui s'appliquent indépendamment de lui."],
    ["Qu'est-ce que la médiation de la consommation ?", ["Un dispositif gratuit de résolution amiable des litiges", "Une procédure judiciaire simplifiée", "Un arbitrage payant", "Une conciliation en justice"], 0,
     "Tout professionnel doit désigner un médiateur et en informer ses clients."],
    ["Qu'est-ce que le surendettement ?", ["Une impossibilité manifeste de faire face à ses dettes non professionnelles", "Un endettement élevé", "Un incident de paiement", "Un fichage bancaire"], 0,
     "Une commission départementale peut décider d'un plan ou d'un effacement partiel."],
    ["Qu'est-ce que le fichier des incidents de remboursement des crédits ?", ["Un fichier recensant les défauts de paiement de crédits aux particuliers", "Un fichier des interdits bancaires", "Un registre des surendettés", "Un fichier de solvabilité"], 0,
     "Il est géré par la Banque de France et consulté avant l'octroi d'un crédit."],
    ["Qu'est-ce que le droit au compte bancaire ?", ["Le droit de faire désigner une banque pour ouvrir un compte de base", "Un droit à des services gratuits", "Un droit au crédit", "Un droit à la mobilité bancaire"], 0,
     "La Banque de France désigne un établissement en cas de refus généralisé.", 3],
  ]),

  notion("ie3-monde-travail", S, "Le monde du travail contemporain",
    "Formes d'emploi, organisation, santé au travail.",
    "Les formes d'emploi se sont fortement diversifiées depuis les années 1980.",
    2, [
    ["Qu'est-ce qu'un contrat à durée déterminée ?", ["Un contrat conclu pour une durée limitée et un motif prévu par la loi", "Un contrat renouvelable librement", "Un contrat sans terme précis", "Un contrat saisonnier uniquement"], 0,
     "Remplacement, accroissement temporaire d'activité et emploi saisonnier en sont les motifs principaux."],
    ["Qu'est-ce que l'intérim ?", ["Une mise à disposition d'un salarié par une agence auprès d'une entreprise", "Un contrat court direct", "Un emploi saisonnier", "Un contrat de mission indépendant"], 0,
     "La relation est triangulaire : l'agence est l'employeur, l'entreprise l'utilisateur."],
    ["Qu'est-ce que le travail à temps partiel subi ?", ["Un temps partiel imposé faute d'emploi à temps plein", "Un temps partiel choisi", "Un temps partiel thérapeutique", "Un temps partiel de fin de carrière"], 0,
     "Il touche particulièrement les femmes et certains secteurs comme la propreté ou le commerce."],
    ["Qu'est-ce que le télétravail ?", ["Un travail effectué hors des locaux de l'employeur grâce aux outils numériques", "Un travail à domicile artisanal", "Un travail indépendant", "Un travail nomade"], 0,
     "Sa généralisation partielle après 2020 a modifié durablement l'organisation de nombreuses entreprises."],
    ["Qu'est-ce que le droit à la déconnexion ?", ["Le droit de ne pas être joignable en dehors du temps de travail", "Le droit de refuser le télétravail", "Le droit de couper les outils numériques au bureau", "Une pause obligatoire"], 0,
     "Inscrit dans le code du travail français en 2017, il doit faire l'objet d'une négociation."],
    ["Qu'est-ce qu'un risque psychosocial au travail ?", ["Un risque pour la santé mentale lié à l'organisation du travail", "Un conflit interpersonnel", "Un stress individuel", "Un risque d'accident"], 0,
     "Charge de travail, autonomie, reconnaissance et rapports sociaux en sont des déterminants."],
    ["Qu'est-ce que l'épuisement professionnel ?", ["Un état d'épuisement lié à une exposition prolongée au stress professionnel", "Une dépression", "Une fatigue passagère", "Un désengagement volontaire"], 0,
     "Il n'est pas reconnu comme maladie professionnelle en tant que telle en France."],
    ["Qu'est-ce que le document unique d'évaluation des risques ?", ["Un document obligatoire recensant les risques professionnels de l'entreprise", "Un règlement intérieur", "Un registre d'accidents", "Un plan de prévention"], 0,
     "Il est obligatoire dès le premier salarié et doit être mis à jour régulièrement."],
    ["Qu'est-ce que la médecine du travail ?", ["Un service de prévention chargé de la santé des salariés", "Un service de soins en entreprise", "Un contrôle d'aptitude uniquement", "Un service d'urgence"], 0,
     "Sa mission est exclusivement préventive : elle ne délivre pas de soins."],
    ["Qu'est-ce que l'obligation de sécurité de l'employeur ?", ["Une obligation de prendre les mesures nécessaires pour protéger la santé des salariés", "Une obligation d'assurance", "Une obligation de formation seule", "Une obligation d'équipement"], 0,
     "Elle est de moyens renforcés : l'employeur doit démontrer avoir pris toutes les mesures nécessaires.", 3],
  ]),

  notion("ie3-retraites", S, "Les retraites",
    "Systèmes, financement, débats.",
    "Le système français combine plusieurs régimes obligatoires superposés.",
    2, [
    ["Sur quel principe le système de retraite français repose-t-il ?", ["La répartition, les actifs finançant les pensions des retraités", "La capitalisation individuelle", "Un fonds de réserve", "Un système mixte obligatoire"], 0,
     "La capitalisation n'existe qu'à titre complémentaire et facultatif."],
    ["Qu'est-ce qu'un régime complémentaire de retraite ?", ["Un régime obligatoire s'ajoutant au régime de base", "Une épargne facultative", "Une assurance privée", "Un fonds de pension"], 0,
     "L'AGIRC-ARRCO couvre les salariés du privé et fonctionne par points."],
    ["Qu'est-ce que le taux de remplacement d'une retraite ?", ["Le rapport entre la pension et le dernier salaire", "Le taux de cotisation", "Le taux de liquidation", "Le rapport actifs-retraités"], 0,
     "Il varie fortement selon les carrières et le niveau de revenu."],
    ["Qu'est-ce que la durée d'assurance requise ?", ["Le nombre de trimestres nécessaires pour une retraite à taux plein", "L'âge légal de départ", "La durée de cotisation minimale", "La durée de service effectif"], 0,
     "Elle a été progressivement allongée par les réformes successives."],
    ["Qu'est-ce que la décote dans le calcul d'une pension ?", ["Une réduction appliquée en cas de trimestres manquants", "Une revalorisation", "Un abattement fiscal", "Une pénalité de départ anticipé fiscale"], 0,
     "La surcote, à l'inverse, majore la pension en cas de trimestres supplémentaires."],
    ["Qu'est-ce que le minimum vieillesse ?", ["Une allocation garantissant un revenu minimal aux personnes âgées modestes", "Une pension minimale de retraite", "Un complément de retraite", "Une aide au logement"], 0,
     "L'allocation de solidarité aux personnes âgées est récupérable sur la succession au-delà d'un seuil."],
    ["Qu'est-ce que le rapport démographique d'un système par répartition ?", ["Le rapport entre le nombre de cotisants et celui de retraités", "Le taux de natalité", "L'espérance de vie moyenne", "Le taux d'emploi des seniors"], 0,
     "Il est passé d'environ quatre cotisants par retraité en 1960 à moins de deux aujourd'hui."],
    ["Qu'est-ce que la pénibilité au travail dans le système de retraite ?", ["Un dispositif ouvrant des droits liés à l'exposition à certains facteurs", "Une reconnaissance d'invalidité", "Un départ anticipé général", "Une majoration de pension"], 0,
     "Le compte professionnel de prévention permet d'acquérir des points convertibles en trimestres."],
    ["Qu'est-ce que le cumul emploi-retraite ?", ["La possibilité de travailler tout en percevant sa pension", "Un report de départ", "Une retraite progressive", "Un temps partiel de fin de carrière"], 0,
     "Depuis 2023, il peut sous conditions générer de nouveaux droits à retraite."],
    ["Qu'est-ce que la retraite progressive ?", ["Un dispositif permettant de réduire son activité en percevant une partie de sa pension", "Un départ échelonné", "Un cumul emploi-retraite", "Une préretraite"], 0,
     "Elle permet de continuer à cotiser sur l'activité maintenue.", 3],
  ]),

  notion("ie3-banque-credit", S, "Banque et crédit",
    "Métiers bancaires, crédit, régulation.",
    "Une banque commerciale crée de la monnaie en accordant un crédit.",
    2, [
    ["Que signifie la formule les crédits font les dépôts ?", ["La monnaie est créée par l'octroi du crédit, non par la collecte préalable d'épargne", "Les dépôts permettent de prêter", "Les crédits sont garantis par les dépôts", "Les deux montants sont toujours égaux"], 0,
     "Le remboursement du crédit détruit symétriquement cette monnaie."],
    ["Qu'est-ce que le taux directeur d'une banque centrale ?", ["Le taux auquel les banques se refinancent auprès d'elle", "Le taux des crédits aux particuliers", "Le taux d'inflation cible", "Le taux d'épargne réglementé"], 0,
     "Il se répercute progressivement sur l'ensemble des taux de l'économie."],
    ["Qu'est-ce que le taux d'usure en France ?", ["Un taux maximal légal au-delà duquel un prêt est illégal", "Le taux moyen du marché", "Le taux plafond de la banque centrale", "Le taux des crédits à la consommation"], 0,
     "Il est calculé trimestriellement à partir des taux effectivement pratiqués."],
    ["Qu'est-ce qu'un crédit immobilier à taux fixe ?", ["Un prêt dont le taux ne varie pas pendant toute sa durée", "Un prêt à mensualité constante", "Un prêt indexé", "Un prêt à taux plafonné"], 0,
     "La France est l'un des pays où le taux fixe domine largement, ce qui protège les emprunteurs."],
    ["Qu'est-ce que le taux d'endettement d'un emprunteur ?", ["La part de ses revenus consacrée au remboursement de ses crédits", "Le montant total de sa dette", "Le rapport dette-patrimoine", "Le coût total du crédit"], 0,
     "Il est en principe limité à trente-cinq pour cent des revenus, assurance comprise."],
    ["Qu'est-ce que l'assurance emprunteur ?", ["Une assurance couvrant le remboursement en cas de décès ou d'invalidité", "Une garantie bancaire", "Une caution mutuelle", "Une assurance du bien financé"], 0,
     "La loi Lemoine de 2022 permet d'en changer à tout moment."],
    ["Qu'est-ce que le livret A ?", ["Un compte d'épargne réglementé défiscalisé", "Un compte courant rémunéré", "Un placement financier", "Un plan d'épargne logement"], 0,
     "Une part de sa collecte finance le logement social via la Caisse des dépôts."],
    ["Qu'est-ce que la garantie des dépôts bancaires en France ?", ["Une protection des dépôts jusqu'à cent mille euros par déposant et par banque", "Une garantie illimitée", "Une garantie de l'État sur tous les comptes", "Une assurance facultative"], 0,
     "Le Fonds de garantie des dépôts et de résolution la met en œuvre."],
    ["Qu'est-ce que la supervision bancaire européenne ?", ["Un contrôle des grandes banques par la Banque centrale européenne", "Un contrôle national exclusif", "Une auto-régulation du secteur", "Une supervision par la Commission"], 0,
     "Le mécanisme de surveillance unique est en place depuis 2014."],
    ["Qu'est-ce que le ratio de solvabilité d'une banque ?", ["Le rapport entre ses fonds propres et ses engagements pondérés par le risque", "Le rapport dépôts-crédits", "Sa liquidité disponible", "Son niveau de réserves obligatoires"], 0,
     "Les accords de Bâle en fixent les exigences minimales au niveau international.", 3],
  ]),

  notion("ie3-entreprises-formes", S, "Créer et gérer une entreprise",
    "Statuts, gestion, transmission.",
    "Le choix du statut juridique conditionne fiscalité, responsabilité et protection sociale.",
    2, [
    ["Qu'est-ce qu'une micro-entreprise ?", ["Un régime simplifié pour entrepreneur individuel sous seuils de chiffre d'affaires", "Une petite société", "Une entreprise unipersonnelle à responsabilité limitée", "Une association employeuse"], 0,
     "Les charges y sont calculées en pourcentage du chiffre d'affaires encaissé."],
    ["Qu'est-ce qu'une SAS ?", ["Une société par actions simplifiée, à statuts très libres", "Une société anonyme réduite", "Une société à responsabilité limitée", "Une société civile"], 0,
     "Sa souplesse statutaire en a fait la forme la plus choisie pour les créations récentes."],
    ["Qu'est-ce que la responsabilité limitée dans une société ?", ["Les associés ne risquent que leurs apports", "Une limitation des dettes de la société", "Une garantie de l'État", "Une assurance obligatoire"], 0,
     "Une caution personnelle du dirigeant peut cependant annuler cette protection en pratique."],
    ["Qu'est-ce qu'un business plan ?", ["Un document présentant le projet, son marché et ses prévisions financières", "Un plan comptable", "Un budget prévisionnel seul", "Une étude de marché"], 0,
     "Il sert autant à convaincre des financeurs qu'à structurer la réflexion du créateur."],
    ["Qu'est-ce que le besoin en fonds de roulement ?", ["Le besoin de financement lié au décalage entre encaissements et décaissements", "Le capital de départ", "La trésorerie disponible", "Le montant des immobilisations"], 0,
     "Une entreprise rentable peut faire faillite faute de trésorerie."],
    ["Qu'est-ce que le compte de résultat ?", ["Un document retraçant produits et charges d'un exercice", "Un état du patrimoine", "Un plan de trésorerie", "Un budget prévisionnel"], 0,
     "Le bilan, lui, décrit la situation patrimoniale à une date donnée."],
    ["Qu'est-ce que le bilan comptable ?", ["Une photographie du patrimoine de l'entreprise à une date donnée", "Un résumé de l'activité annuelle", "Un état de trésorerie", "Un tableau de bord de gestion"], 0,
     "Actif et passif y sont toujours équilibrés par construction."],
    ["Qu'est-ce que l'amortissement comptable ?", ["La constatation de la perte de valeur d'un bien sur sa durée d'usage", "Le remboursement d'un emprunt", "Une provision pour risque", "Une charge exceptionnelle"], 0,
     "Il étale une dépense d'investissement sur plusieurs exercices."],
    ["Qu'est-ce qu'une procédure de sauvegarde ?", ["Une procédure préventive pour une entreprise en difficulté mais non en cessation de paiements", "Un redressement judiciaire", "Une liquidation", "Une conciliation amiable"], 0,
     "Elle permet de geler les dettes le temps d'élaborer un plan."],
    ["Qu'est-ce que la transmission d'entreprise ?", ["Le transfert de propriété à un repreneur ou à un héritier", "Une cession d'actifs", "Une fusion", "Un changement de forme juridique"], 0,
     "Des dizaines de milliers d'entreprises françaises sont concernées chaque année par le départ à la retraite de leur dirigeant.", 3],
  ]),

  notion("ie3-services-publics", S, "Les services publics",
    "Missions, modes de gestion, évolutions.",
    "Un service public peut être géré directement ou délégué à un opérateur privé.",
    2, [
    ["Qu'est-ce qu'un service public ?", ["Une activité d'intérêt général assurée sous le contrôle d'une personne publique", "Une activité gérée par l'État", "Un service gratuit", "Une administration"], 0,
     "Il peut être exploité par une entreprise privée sous délégation."],
    ["Qu'est-ce qu'une délégation de service public ?", ["Un contrat confiant la gestion d'un service à un tiers rémunéré sur les résultats", "Un marché public", "Une privatisation", "Une concession de travaux"], 0,
     "La distribution d'eau en est l'exemple le plus répandu en France."],
    ["Qu'est-ce qu'une régie municipale ?", ["Une gestion directe d'un service par la collectivité", "Une société d'économie mixte", "Une délégation à une entreprise", "Un établissement public national"], 0,
     "Plusieurs grandes villes sont revenues à ce mode de gestion pour l'eau."],
    ["Qu'est-ce qu'un service d'intérêt économique général au sens européen ?", ["Une activité économique soumise à des obligations de service public", "Un service public administratif", "Un service marchand ordinaire", "Un monopole d'État"], 0,
     "Le droit européen encadre les compensations financières qui peuvent lui être versées."],
    ["Qu'est-ce que l'ouverture à la concurrence d'un service public en réseau ?", ["La séparation entre l'infrastructure et les services exploités", "Une privatisation totale", "Une fin des obligations de service public", "Un transfert aux collectivités"], 0,
     "Énergie, télécommunications et transports ferroviaires ont suivi ce schéma en Europe."],
    ["Qu'est-ce que le service universel des télécommunications ?", ["Une obligation d'assurer un service de base à tous, à un prix abordable", "Une couverture réseau complète", "Une tarification unique", "Un accès gratuit"], 0,
     "Il garantit notamment un raccordement téléphonique fixe sur tout le territoire."],
    ["Qu'est-ce qu'un opérateur de service public postal ?", ["Un opérateur soumis à des obligations de distribution sur tout le territoire", "Une entreprise publique de courrier", "Un monopole postal", "Un service d'État"], 0,
     "La Poste conserve en France des missions de service public malgré son ouverture à la concurrence."],
    ["Qu'est-ce que la continuité territoriale ?", ["Un principe garantissant l'accès aux services depuis les territoires éloignés", "Une desserte routière continue", "Un aménagement du territoire", "Une égalité tarifaire nationale"], 0,
     "Elle justifie des aides au transport vers la Corse et les outre-mer."],
    ["Qu'est-ce que la dématérialisation des services publics ?", ["Le passage des démarches administratives au format numérique", "La suppression des guichets", "L'automatisation des décisions", "La numérisation des archives"], 0,
     "Elle pose la question de l'accès pour les personnes éloignées du numérique."],
    ["Qu'est-ce que l'accessibilité numérique des sites publics ?", ["Une obligation d'adapter les sites aux personnes en situation de handicap", "Une obligation de couverture réseau", "Une gratuité d'accès", "Une simplicité d'usage"], 0,
     "Le référentiel général d'amélioration de l'accessibilité en fixe les critères techniques.", 3],
  ]),

  notion("ie3-securite-sociale-branches", S, "Les branches de la protection sociale",
    "Maladie, famille, retraite, accidents, autonomie.",
    "La cinquième branche de la Sécurité sociale, l'autonomie, a été créée en 2020.",
    2, [
    ["Que couvre la branche maladie de la Sécurité sociale ?", ["Les soins, l'invalidité, la maternité et le décès", "Les seuls soins médicaux", "Les hospitalisations uniquement", "Les accidents du travail"], 0,
     "Elle représente le poste de dépenses le plus important."],
    ["Que couvre la branche famille ?", ["Les prestations familiales et certaines aides au logement", "Les allocations familiales seules", "Les congés parentaux", "Les crèches uniquement"], 0,
     "Elle est gérée par les caisses d'allocations familiales."],
    ["Que couvre la branche accidents du travail et maladies professionnelles ?", ["Les risques liés à l'exercice professionnel, financés par les employeurs", "Tous les accidents de la vie", "Les arrêts maladie ordinaires", "L'invalidité en général"], 0,
     "Le taux de cotisation varie selon la sinistralité de l'entreprise."],
    ["Qu'est-ce que la branche autonomie créée en 2020 ?", ["Une branche consacrée au grand âge et au handicap", "Une branche santé mentale", "Une branche dépendance privée", "Une branche d'aide sociale"], 0,
     "Elle est gérée par la Caisse nationale de solidarité pour l'autonomie."],
    ["Qu'est-ce que l'allocation personnalisée d'autonomie ?", ["Une aide aux personnes âgées en perte d'autonomie, gérée par les départements", "Une pension d'invalidité", "Une aide au logement", "Une prestation de la branche maladie"], 0,
     "Son montant dépend du degré de dépendance et des ressources."],
    ["Qu'est-ce que la prestation de compensation du handicap ?", ["Une aide finançant les besoins liés au handicap", "Une allocation de ressources", "Une pension d'invalidité", "Une aide à l'emploi"], 0,
     "Elle est attribuée par la maison départementale des personnes handicapées."],
    ["Qu'est-ce que l'objectif national de dépenses d'assurance maladie ?", ["Un plafond indicatif voté chaque année par le Parlement", "Un budget contraignant", "Un objectif de recettes", "Une prévision de dépenses hospitalières"], 0,
     "Il structure les négociations tarifaires avec les professionnels de santé."],
    ["Qu'est-ce que la loi de financement de la Sécurité sociale ?", ["Un texte annuel fixant recettes et objectifs de dépenses sociales", "Une loi de finances", "Un décret budgétaire", "Une convention d'objectifs"], 0,
     "Créée en 1996, elle donne au Parlement un droit de regard sur les comptes sociaux."],
    ["Qu'est-ce que le déficit de la Sécurité sociale ?", ["L'écart entre recettes et dépenses des régimes obligatoires", "La dette hospitalière", "Le déficit de l'État en santé", "Le solde des complémentaires"], 0,
     "La Caisse d'amortissement de la dette sociale est chargée de le résorber."],
    ["Qu'est-ce que la CSG dans le financement social ?", ["Un impôt affecté portant sur l'ensemble des revenus", "Une cotisation salariale", "Une taxe sur les entreprises", "Une contribution volontaire"], 0,
     "Elle a progressivement remplacé une partie des cotisations, élargissant l'assiette du financement.", 3],
  ]),

  notion("ie3-economie-comportementale", S, "Économie comportementale",
    "Biais, décisions, politiques publiques.",
    "Les individus ne se comportent pas comme l'homo economicus des manuels.",
    2, [
    ["Qu'est-ce que l'économie comportementale ?", ["Un champ intégrant psychologie et économie pour expliquer les décisions réelles", "Une économie expérimentale", "Une psychologie du consommateur", "Une sociologie économique"], 0,
     "Kahneman et Tversky en sont les fondateurs, avec un Nobel d'économie en 2002."],
    ["Qu'est-ce que l'aversion à la perte ?", ["La tendance à ressentir plus fortement une perte qu'un gain équivalent", "Le refus du risque", "La prudence financière", "L'évitement de l'incertitude"], 0,
     "Une perte pèse environ deux fois plus qu'un gain de même montant."],
    ["Qu'est-ce que l'effet de dotation ?", ["La tendance à surévaluer ce que l'on possède déjà", "Un effet de richesse", "Un biais d'achat", "Un attachement affectif"], 0,
     "Une expérience classique montre que le prix demandé pour céder un objet excède le prix qu'on aurait payé pour l'acquérir."],
    ["Qu'est-ce que le biais du statu quo ?", ["Une préférence pour l'état actuel des choses", "Une résistance au changement organisationnel", "Une aversion au risque", "Un conservatisme politique"], 0,
     "Il explique l'efficacité redoutable des options par défaut."],
    ["Qu'est-ce qu'un nudge ?", ["Un aménagement du contexte de choix orientant les décisions sans contraindre", "Une incitation financière", "Une obligation légère", "Une campagne d'information"], 0,
     "L'inscription par défaut au don d'organes en est un exemple discuté."],
    ["Qu'est-ce que le biais de disponibilité ?", ["Une surestimation des événements facilement remémorés", "Une préférence pour l'information accessible", "Un biais de sélection", "Un excès de confiance"], 0,
     "Il explique la surestimation des risques médiatisés par rapport aux risques courants."],
    ["Qu'est-ce que la comptabilité mentale ?", ["Le fait de traiter l'argent différemment selon son origine ou sa destination", "Un calcul approximatif", "Une gestion budgétaire personnelle", "Une estimation des coûts"], 0,
     "Un même euro n'est pas dépensé de la même façon selon qu'il vient d'un salaire ou d'un gain inattendu."],
    ["Qu'est-ce que l'escalade d'engagement ?", ["La poursuite d'une action en raison des investissements déjà consentis", "Une prise de risque croissante", "Un engagement contractuel", "Une fidélité à une décision"], 0,
     "Les coûts irrécupérables ne devraient logiquement pas influencer une décision future."],
    ["Qu'est-ce que la procrastination du point de vue économique ?", ["Un décalage entre préférences présentes et futures", "Une paresse individuelle", "Un manque d'information", "Une contrainte de temps"], 0,
     "Elle explique l'écart entre l'intention d'épargner et le comportement effectif."],
    ["Comment les politiques publiques utilisent-elles ces travaux ?", ["En modifiant les options par défaut et la présentation des choix", "En augmentant les sanctions", "En multipliant l'information", "En imposant des obligations"], 0,
     "L'adhésion automatique à un plan d'épargne retraite a fortement augmenté les taux d'épargne dans plusieurs pays.", 3],
  ]),

  notion("ie3-collectivites-finances", S, "Les finances locales",
    "Ressources, dépenses, autonomie.",
    "Les collectivités locales réalisent la majorité de l'investissement public civil en France.",
    2, [
    ["Quelle part de l'investissement public civil les collectivités réalisent-elles ?", ["Environ deux tiers", "Environ un quart", "Environ un dixième", "La quasi-totalité"], 0,
     "Écoles, voirie, équipements sportifs et culturels en constituent l'essentiel."],
    ["Quelles sont les principales ressources fiscales des communes ?", ["La taxe foncière et diverses taxes locales", "La taxe d'habitation seule", "L'impôt sur le revenu local", "La TVA locale"], 0,
     "La suppression de la taxe d'habitation sur les résidences principales a modifié cet équilibre."],
    ["Qu'est-il advenu du montant global de la dotation de l'État aux collectivités dans les années 2010 ?", ["Il a été fortement réduit", "Il a doublé", "Il est resté stable", "Il a été supprimé"], 0,
     "Cette baisse a contraint les collectivités à réduire leurs dépenses ou à augmenter leur fiscalité."],
    ["Qu'est-ce que l'autonomie financière des collectivités ?", ["Un principe constitutionnel garantissant une part déterminante de ressources propres", "Une liberté de fixer tous les impôts", "Un droit d'emprunt illimité", "Une indépendance budgétaire totale"], 0,
     "Sa mesure fait l'objet de contestations récurrentes des associations d'élus."],
    ["Qu'est-ce que la règle d'or budgétaire des collectivités ?", ["L'obligation de voter un budget en équilibre réel", "Un plafond de dette", "Une interdiction d'emprunter", "Un objectif de désendettement"], 0,
     "L'emprunt ne peut financer que l'investissement, jamais le fonctionnement courant."],
    ["Qu'est-ce que la capacité d'autofinancement d'une collectivité ?", ["L'excédent de fonctionnement disponible pour financer l'investissement", "Sa trésorerie", "Sa capacité d'emprunt", "Son épargne de précaution"], 0,
     "Elle conditionne largement la capacité à investir sans s'endetter."],
    ["Qu'est-ce que la péréquation horizontale ?", ["Un transfert de ressources entre collectivités riches et pauvres", "Une dotation de l'État", "Une compensation fiscale", "Un fonds européen"], 0,
     "Le fonds national de péréquation des ressources intercommunales en est le principal instrument."],
    ["Qu'est-ce qu'un emprunt toxique de collectivité ?", ["Un prêt structuré dont les taux ont explosé selon des indices imprévus", "Un emprunt à taux élevé", "Un emprunt non autorisé", "Un emprunt étranger"], 0,
     "Plusieurs centaines de collectivités françaises en ont contracté avant 2008."],
    ["Qu'est-ce que le contrôle de légalité des actes locaux ?", ["Un contrôle a posteriori exercé par le préfet", "Une autorisation préalable", "Un contrôle budgétaire", "Un audit de la Cour des comptes"], 0,
     "Le préfet peut déférer un acte au tribunal administratif s'il l'estime illégal."],
    ["Qu'est-ce que la chambre régionale des comptes ?", ["Une juridiction contrôlant la gestion des collectivités", "Une commission budgétaire", "Un service préfectoral", "Un organe consultatif"], 0,
     "Ses rapports d'observations définitives sont publics et souvent commentés localement.", 3],
  ]),

  notion("ie3-europe-politiques", S, "Les politiques européennes",
    "Agriculture, concurrence, environnement, recherche.",
    "L'Union européenne agit surtout par la réglementation et le budget, non par l'impôt.",
    2, [
    ["Quelle part du budget européen la politique agricole représente-t-elle ?", ["Environ un tiers", "Environ dix pour cent", "Plus de la moitié", "Environ soixante-dix pour cent"], 0,
     "Sa part a fortement diminué depuis les années 1980, où elle dépassait deux tiers."],
    ["Qu'est-ce que la politique européenne de concurrence ?", ["Un ensemble de règles contrôlant ententes, abus et aides d'État", "Une politique commerciale", "Une politique industrielle", "Une régulation des prix"], 0,
     "La Commission peut infliger des amendes de plusieurs milliards d'euros."],
    ["Qu'est-ce qu'une aide d'État au sens européen ?", ["Un avantage public sélectif faussant potentiellement la concurrence", "Une subvention publique quelconque", "Une aide sociale", "Un investissement public"], 0,
     "Elle doit en principe être notifiée à la Commission avant d'être versée."],
    ["Qu'est-ce que le programme Erasmus ?", ["Un programme de mobilité étudiante et de formation en Europe", "Un programme de recherche", "Un fonds d'aide aux universités", "Un programme d'échange scolaire seul"], 0,
     "Lancé en 1987, il a concerné plus de dix millions de personnes."],
    ["Qu'est-ce que le programme-cadre européen de recherche ?", ["Le principal instrument de financement de la recherche européenne", "Un fonds structurel", "Un programme national coordonné", "Une agence de recherche"], 0,
     "Horizon Europe en est la version en cours, dotée de plusieurs dizaines de milliards d'euros."],
    ["Qu'est-ce que le pacte vert européen ?", ["Une stratégie visant la neutralité climatique de l'Union en 2050", "Un accord climatique international", "Un fonds environnemental", "Une directive sur les émissions"], 0,
     "Il se décline en une série de textes législatifs sectoriels."],
    ["Qu'est-ce que le mécanisme d'ajustement carbone aux frontières ?", ["Une taxation carbone des importations de certains produits", "Un droit de douane environnemental général", "Une norme d'émission", "Une compensation carbone"], 0,
     "Il vise à éviter que la production ne se déplace vers des pays moins contraints."],
    ["Qu'est-ce que la politique commerciale commune ?", ["Une compétence exclusive de l'Union pour négocier les accords commerciaux", "Une coordination des politiques nationales", "Une politique douanière partagée", "Un cadre de négociation facultatif"], 0,
     "Les États membres ne peuvent pas négocier seuls d'accord commercial."],
    ["Qu'est-ce que le plan de relance européen de 2020 ?", ["Un emprunt commun finançant la relance après la pandémie", "Un fonds structurel renforcé", "Une aide directe aux États", "Un mécanisme de stabilité"], 0,
     "C'est la première fois que l'Union emprunte massivement en commun sur les marchés."],
    ["Qu'est-ce que le semestre européen ?", ["Un cycle annuel de coordination des politiques économiques des États membres", "Un budget semestriel", "Une session parlementaire", "Un cycle de négociations commerciales"], 0,
     "Il permet à la Commission d'émettre des recommandations sur les budgets nationaux.", 3],
  ]),

  notion("ie3-organisation-internationale-economie", S, "Les institutions économiques internationales",
    "FMI, Banque mondiale, OCDE, G7 et G20.",
    "Le FMI prête aux États en difficulté, la Banque mondiale finance le développement.",
    2, [
    ["Quelle est la mission principale du Fonds monétaire international ?", ["Assurer la stabilité du système monétaire et prêter aux États en crise", "Financer le développement", "Réguler le commerce", "Coordonner les politiques budgétaires"], 0,
     "Ses prêts sont assortis de conditions de politique économique, souvent critiquées."],
    ["Quelle est la mission de la Banque mondiale ?", ["Financer des projets de développement dans les pays à faible revenu", "Stabiliser les monnaies", "Réguler les banques", "Gérer la dette internationale"], 0,
     "Elle regroupe plusieurs institutions, dont la BIRD et l'Association internationale de développement."],
    ["Qu'est-ce que l'OCDE ?", ["Une organisation d'analyse et de coordination réunissant des économies développées", "Une banque de développement", "Un organisme de régulation commerciale", "Une agence de l'ONU"], 0,
     "Elle produit des statistiques et des comparaisons internationales très utilisées."],
    ["Qu'est-ce que le G7 ?", ["Un forum informel réunissant sept grandes économies avancées", "Une organisation internationale", "Un conseil de sécurité économique", "Un groupe de négociation commerciale"], 0,
     "Il n'a aucun pouvoir contraignant mais une forte capacité d'orientation."],
    ["Qu'est-ce que le G20 ?", ["Un forum réunissant vingt économies majeures, avancées et émergentes", "Une organisation permanente", "Un groupe de pays du Sud", "Un conseil monétaire"], 0,
     "Son rôle s'est renforcé après la crise financière de 2008."],
    ["Qu'est-ce qu'un plan d'ajustement structurel ?", ["Un ensemble de réformes exigées en contrepartie d'un prêt du FMI", "Un plan de relance", "Un programme d'aide au développement", "Un rééchelonnement de dette"], 0,
     "Appliqués massivement dans les années 1980 et 1990, ils ont fait l'objet de vives critiques."],
    ["Qu'est-ce que le Club de Paris ?", ["Un groupe informel de créanciers publics renégociant des dettes souveraines", "Une organisation bancaire", "Un fonds d'aide au développement", "Un forum de politique monétaire"], 0,
     "Le Club de Londres réunit, lui, les créanciers privés."],
    ["Qu'est-ce que le droit de tirage spécial du FMI ?", ["Un actif de réserve international créé par le Fonds", "Une monnaie internationale", "Un droit d'emprunt automatique", "Une garantie de change"], 0,
     "Sa valeur est calculée à partir d'un panier de grandes devises."],
    ["Comment les droits de vote sont-ils répartis au FMI ?", ["Selon des quotes-parts liées au poids économique des États", "Un pays une voix", "Selon la population", "Par région"], 0,
     "Cette répartition, favorable aux économies avancées, est contestée par les pays émergents."],
    ["Qu'est-ce que l'aide liée dans la coopération internationale ?", ["Une aide conditionnée à l'achat de biens du pays donateur", "Une aide conditionnée à des réformes", "Une aide remboursable", "Une aide sectorielle"], 0,
     "L'OCDE encourage son déliement, car elle réduit l'efficacité de l'aide.", 3],
  ]),

  notion("ie3-droit-numerique", S, "Le droit du numérique",
    "Données, plateformes, responsabilités.",
    "Le droit du numérique repose largement sur des règlements européens directement applicables.",
    2, [
    ["Qu'est-ce qu'une donnée à caractère personnel ?", ["Toute information se rapportant à une personne identifiée ou identifiable", "Une donnée sensible", "Une donnée nominative seule", "Une donnée privée"], 0,
     "Une adresse IP ou un identifiant de terminal peut en constituer une."],
    ["Qu'est-ce qu'une donnée sensible au sens du RGPD ?", ["Une donnée révélant santé, opinions, origine ou orientation sexuelle", "Une donnée confidentielle", "Une donnée bancaire", "Une donnée d'identification"], 0,
     "Leur traitement est en principe interdit, sauf exceptions strictement encadrées."],
    ["Qu'est-ce que le consentement au sens du RGPD ?", ["Une manifestation de volonté libre, spécifique, éclairée et univoque", "Une acceptation des conditions générales", "Une absence d'opposition", "Une case précochée"], 0,
     "Le silence ou l'inaction ne valent jamais consentement."],
    ["Qu'est-ce que le droit à la portabilité des données ?", ["Le droit de récupérer ses données dans un format réutilisable", "Le droit de les effacer", "Le droit d'y accéder", "Le droit de les corriger"], 0,
     "Il vise à faciliter le changement de service sans perdre son historique."],
    ["Qu'est-ce que la responsabilité d'un hébergeur ?", ["Une responsabilité limitée tant qu'il n'a pas connaissance d'un contenu illicite", "Une responsabilité identique à celle d'un éditeur", "Une irresponsabilité totale", "Une responsabilité pénale automatique"], 0,
     "Il doit agir promptement pour retirer un contenu manifestement illicite qui lui est signalé."],
    ["Qu'est-ce que le règlement européen sur les services numériques ?", ["Un texte imposant transparence et modération aux plateformes", "Une taxe numérique", "Une régulation des télécommunications", "Un cadre sur le commerce électronique"], 0,
     "Les très grandes plateformes y sont soumises à des obligations renforcées et à des audits."],
    ["Qu'est-ce que le règlement sur les marchés numériques ?", ["Un texte encadrant les pratiques des contrôleurs d'accès", "Un règlement sur le commerce en ligne", "Une régulation des données", "Un cadre fiscal numérique"], 0,
     "Il interdit notamment l'auto-préférence et impose l'interopérabilité de certains services."],
    ["Qu'est-ce que la contrefaçon numérique ?", ["La reproduction non autorisée d'une œuvre protégée", "Un piratage informatique", "Une usurpation d'identité", "Une fraude en ligne"], 0,
     "Elle relève du droit d'auteur, distinct des infractions informatiques."],
    ["Qu'est-ce que le droit d'auteur appliqué aux logiciels ?", ["Une protection du code source comme œuvre de l'esprit", "Une protection par brevet", "Une protection par secret d'affaires", "Une absence de protection"], 0,
     "En Europe, le logiciel relève du droit d'auteur, non du brevet, contrairement aux États-Unis."],
    ["Qu'est-ce que le règlement européen sur l'intelligence artificielle ?", ["Un cadre imposant des obligations proportionnées au niveau de risque", "Une interdiction générale", "Un cadre volontaire", "Une régulation des données d'entraînement seule"], 0,
     "Certains usages, comme la notation sociale généralisée, y sont purement interdits.", 3],
  ]),

  notion("ie3-inegalites-france", S, "Les inégalités en France",
    "Revenus, patrimoine, mobilité.",
    "Les inégalités de patrimoine sont bien plus fortes que les inégalités de revenu.",
    2, [
    ["Quelles inégalités sont les plus marquées en France ?", ["Les inégalités de patrimoine", "Les inégalités de revenu", "Les inégalités de consommation", "Les inégalités salariales"], 0,
     "Les dix pour cent les plus riches détiennent environ la moitié du patrimoine total."],
    ["Qu'est-ce que le niveau de vie médian ?", ["Le niveau séparant la population en deux moitiés égales", "Le revenu moyen", "Le salaire médian", "Le revenu disponible moyen"], 0,
     "Il est nettement inférieur au revenu moyen, tiré vers le haut par les hauts revenus."],
    ["Qu'est-ce que le taux de pauvreté en France ?", ["La part de la population sous soixante pour cent du niveau de vie médian", "La part sans emploi", "La part sous le SMIC", "La part au RSA"], 0,
     "Il concerne environ quatorze pour cent de la population."],
    ["Quel groupe est le plus touché par la pauvreté en France ?", ["Les familles monoparentales et les jeunes", "Les retraités", "Les salariés à temps plein", "Les indépendants"], 0,
     "Le taux de pauvreté des familles monoparentales dépasse largement la moyenne nationale."],
    ["Qu'est-ce que la redistribution en France ?", ["L'effet combiné des prélèvements et des prestations sur les inégalités", "Les seules aides sociales", "Le système fiscal seul", "Les transferts entre ménages"], 0,
     "Elle réduit fortement les écarts de revenu, davantage par les prestations que par l'impôt."],
    ["Qu'est-ce que la mobilité sociale en France ?", ["La capacité à changer de position sociale par rapport à ses parents", "La mobilité géographique", "Le changement d'emploi", "L'ascension professionnelle"], 0,
     "Elle est réelle mais reste inférieure à celle des pays nordiques."],
    ["Qu'est-ce que la reproduction sociale selon Bourdieu ?", ["La transmission des positions sociales par l'école et la famille", "L'hérédité biologique", "La transmission du patrimoine", "L'endogamie sociale"], 0,
     "Le capital culturel y joue un rôle aussi déterminant que le capital économique."],
    ["Qu'est-ce que l'écart salarial entre femmes et hommes en France ?", ["Un écart d'environ quinze pour cent à temps de travail comparable", "Un écart inexistant", "Un écart de plus de quarante pour cent", "Un écart uniquement lié au temps partiel"], 0,
     "Une partie s'explique par la ségrégation des métiers, une autre reste inexpliquée."],
    ["Qu'est-ce que le plafond de verre ?", ["Un obstacle invisible limitant l'accès des femmes aux postes de direction", "Une limite salariale", "Une barrière de diplôme", "Un seuil de promotion"], 0,
     "Des quotas ont été instaurés en France pour les conseils d'administration des grandes entreprises."],
    ["Qu'est-ce que l'index de l'égalité professionnelle ?", ["Une note obligatoire mesurant les écarts entre femmes et hommes en entreprise", "Un label facultatif", "Un indicateur statistique national", "Un classement des employeurs"], 0,
     "Il est obligatoire pour les entreprises d'au moins cinquante salariés depuis 2019.", 3],
  ]),

  notion("ie3-transition-economie", S, "Économie et transition écologique",
    "Coûts, instruments, arbitrages.",
    "La transition écologique est autant un problème d'investissement que de contrainte.",
    2, [
    ["Qu'est-ce qu'une externalité environnementale négative ?", ["Un coût environnemental non pris en compte dans le prix", "Une pollution industrielle", "Une taxe environnementale", "Un dommage écologique réparé"], 0,
     "La tarification carbone vise précisément à l'internaliser."],
    ["Qu'est-ce qu'une taxe carbone ?", ["Un prix mis sur les émissions de gaz à effet de serre", "Une taxe sur les carburants", "Une taxe sur les entreprises polluantes", "Un droit de douane environnemental"], 0,
     "Son acceptabilité dépend fortement de l'usage fait des recettes."],
    ["Qu'est-ce qu'un marché de quotas d'émission ?", ["Un système plafonnant les émissions et permettant d'échanger des droits", "Une taxe négociable", "Un système de compensation", "Un marché volontaire"], 0,
     "Il fixe la quantité et laisse le marché déterminer le prix, à l'inverse de la taxe."],
    ["Qu'est-ce que le coût de l'inaction climatique ?", ["Les dommages futurs évités par une action présente", "Le coût des politiques climatiques", "Le manque à gagner économique", "Le coût des catastrophes passées"], 0,
     "Le rapport Stern de 2006 l'a estimé bien supérieur au coût de l'action."],
    ["Qu'est-ce qu'un actif échoué ?", ["Un investissement devenu sans valeur avant la fin de sa durée de vie prévue", "Un actif financier risqué", "Un investissement non rentable", "Un actif immobilisé"], 0,
     "Les réserves fossiles non exploitables constituent le principal risque de ce type."],
    ["Qu'est-ce que la finance verte ?", ["Un ensemble de financements orientés vers des activités favorables à l'environnement", "Une finance éthique", "Un investissement socialement responsable", "Un fonds environnemental public"], 0,
     "La taxonomie européenne vise à définir ce qui peut être qualifié de durable."],
    ["Qu'est-ce que la taxonomie européenne ?", ["Une classification des activités économiques selon leur durabilité", "Un système fiscal environnemental", "Une norme comptable", "Un label financier"], 0,
     "L'inclusion du gaz et du nucléaire y a fait l'objet de vifs débats."],
    ["Qu'est-ce que la sobriété énergétique du point de vue économique ?", ["Une réduction de la demande par les usages et l'organisation", "Une hausse de l'efficacité", "Une baisse de la production", "Une restriction réglementaire"], 0,
     "Elle se distingue de l'efficacité, qui vise le même service avec moins d'énergie."],
    ["Qu'est-ce que la transition juste ?", ["Un principe visant à répartir équitablement les coûts de la transition", "Une transition rapide", "Une transition planifiée", "Une transition financée par l'État"], 0,
     "Il concerne notamment les travailleurs et territoires dépendant d'activités appelées à disparaître."],
    ["Qu'est-ce que le découplage entre croissance et émissions ?", ["Une baisse des émissions malgré une croissance du PIB", "Une croissance sans consommation d'énergie", "Une stagnation économique", "Une réduction de la production"], 0,
     "Un découplage absolu est observé dans plusieurs pays, mais son rythme reste insuffisant.", 3],
  ]),

  notion("ie3-associations-democratie", S, "Vie associative et participation",
    "Engagement, démocratie participative, contre-pouvoirs.",
    "La France compte plus d'un million et demi d'associations actives.",
    2, [
    ["Combien d'associations actives compte-t-on en France ?", ["Plus d'un million et demi", "Environ cent mille", "Environ cinq cent mille", "Environ cinq millions"], 0,
     "Environ un cinquième d'entre elles emploient des salariés."],
    ["Combien de bénévoles la France compte-t-elle environ ?", ["Plus de vingt millions", "Environ deux millions", "Environ cinquante millions", "Environ cinq millions"], 0,
     "L'engagement bénévole ponctuel progresse au détriment de l'engagement régulier."],
    ["Qu'est-ce qu'une association reconnue d'utilité publique ?", ["Une association bénéficiant d'un statut accordé par décret après examen", "Une association agréée", "Une association subventionnée", "Une fondation"], 0,
     "Environ deux mille associations en bénéficient, ce qui facilite les dons et legs."],
    ["Qu'est-ce qu'un budget participatif ?", ["Un dispositif où les habitants décident de l'affectation d'une part du budget local", "Une consultation budgétaire", "Un vote sur les impôts locaux", "Un contrôle citoyen des comptes"], 0,
     "Des centaines de collectivités françaises en pratiquent aujourd'hui."],
    ["Qu'est-ce qu'une convention citoyenne ?", ["Une assemblée de citoyens tirés au sort formulant des propositions", "Une consultation publique", "Un référendum local", "Un conseil consultatif d'élus"], 0,
     "La Convention citoyenne pour le climat, en 2019 et 2020, en fut la première application nationale française."],
    ["Qu'est-ce que le tirage au sort en démocratie ?", ["Une méthode de désignation ancienne, aujourd'hui utilisée pour des assemblées consultatives", "Une loterie électorale", "Un mode de scrutin", "Une désignation aléatoire des élus"], 0,
     "Athènes y recourait largement pour désigner ses magistrats."],
    ["Qu'est-ce qu'une pétition citoyenne européenne ?", ["Un dispositif permettant de demander à la Commission de proposer un texte", "Une pétition parlementaire", "Un référendum européen", "Une consultation publique"], 0,
     "Elle exige un million de signatures dans au moins sept États membres."],
    ["Qu'est-ce que le référendum d'initiative partagée en France ?", ["Une procédure exigeant l'appui de parlementaires et de millions d'électeurs", "Un référendum d'initiative populaire", "Un référendum local", "Une consultation nationale"], 0,
     "Ses conditions sont si strictes qu'aucune n'a jamais abouti à un vote."],
    ["Qu'est-ce qu'un lanceur d'alerte ?", ["Une personne signalant de bonne foi une menace ou une atteinte à l'intérêt général", "Un dénonciateur anonyme", "Un témoin dans une procédure", "Un journaliste d'investigation"], 0,
     "La loi française de 2022 a renforcé sa protection contre les représailles."],
    ["Qu'est-ce que le débat public en France ?", ["Une procédure organisée pour les grands projets d'aménagement", "Une consultation informelle", "Une enquête publique", "Un référendum local"], 0,
     "La Commission nationale du débat public en est l'autorité indépendante organisatrice.", 3],
  ]),

  notion("ie3-crises-contemporaines", S, "Les crises de 2008 à aujourd'hui",
    "2008, 2020, inflation : mécanismes et réponses.",
    "Chaque crise récente a modifié le rôle attendu des banques centrales et des États.",
    2, [
    ["Qu'est-ce qu'un crédit subprime ?", ["Un crédit immobilier accordé à des emprunteurs à faible solvabilité", "Un crédit à taux réduit", "Un crédit hypothécaire classique", "Un crédit à la consommation"], 0,
     "Leur titrisation a diffusé le risque dans tout le système financier mondial."],
    ["Qu'est-ce que la titrisation ?", ["La transformation de créances en titres négociables", "Un transfert de propriété", "Une garantie bancaire", "Une couverture de risque"], 0,
     "Elle permet de sortir des risques du bilan, ce qui peut réduire la vigilance sur leur qualité."],
    ["Que s'est-il passé en septembre 2008 ?", ["La faillite de Lehman Brothers a provoqué une panique financière mondiale", "Le krach boursier de Wall Street", "La crise de la dette grecque", "L'effondrement de l'euro"], 0,
     "Le refus de la sauver a rompu l'anticipation d'un soutien public systématique."],
    ["Qu'est-ce que la crise de la dette souveraine européenne ?", ["Une crise de confiance sur la dette de plusieurs États de la zone euro à partir de 2010", "Une crise bancaire", "Une crise de change", "Une crise budgétaire française"], 0,
     "Elle a conduit à créer le Mécanisme européen de stabilité."],
    ["Qu'est-ce que la formule prononcée par Mario Draghi en 2012 ?", ["Faire tout ce qu'il faudra pour préserver l'euro", "Sauver les banques à tout prix", "Réduire les déficits publics", "Racheter la dette grecque"], 0,
     "Cette seule déclaration a suffi à calmer durablement les marchés."],
    ["Quelle particularité la crise de 2020 présente-t-elle ?", ["Un arrêt volontaire de l'activité pour raisons sanitaires", "Une crise financière", "Une crise énergétique", "Une crise de la dette"], 0,
     "Les soutiens publics massifs ont limité les faillites au prix d'un fort endettement."],
    ["Qu'est-ce que le chômage partiel massif de 2020 ?", ["Un dispositif prenant en charge les salaires pour éviter les licenciements", "Une allocation chômage renforcée", "Un congé forcé", "Une suspension des contrats"], 0,
     "Il a concerné plusieurs millions de salariés simultanément en France."],
    ["Quelle cause principale explique la poussée d'inflation de 2021 et 2022 ?", ["Des tensions d'approvisionnement et une flambée des prix de l'énergie", "Une hausse des salaires", "Une création monétaire excessive seule", "Une baisse de la production agricole"], 0,
     "La guerre en Ukraine a fortement accentué le choc énergétique et alimentaire."],
    ["Comment les banques centrales ont-elles réagi à cette inflation ?", ["Par une hausse rapide des taux directeurs", "Par une baisse des taux", "Par des rachats d'actifs", "Par des contrôles de prix"], 0,
     "Le rythme de hausse a été le plus rapide depuis quarante ans."],
    ["Qu'est-ce que le bouclier tarifaire mis en place en France ?", ["Un dispositif limitant la hausse des prix de l'énergie pour les consommateurs", "Une aide directe aux ménages", "Une baisse de TVA", "Un plafonnement des salaires"], 0,
     "Son coût s'est chiffré en dizaines de milliards d'euros pour les finances publiques.", 3],
  ]),
];
