/**
 * Langue française, deuxième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Langue française";

export const CG_LANGUE_FRANCAISE_2: SeedSkill[] = [
  notion("lf2-familles-langues", S, "Les familles de langues",
    "Comment les linguistes classent les langues du monde.",
    "Deux langues appartiennent à la même famille si elles descendent d'une langue commune.",
    2, [
    ["À quelle famille le français appartient-il ?", ["Aux langues indo-européennes", "Aux langues afro-asiatiques", "Aux langues ouraliennes", "Aux langues altaïques"], 0,
     "La branche romane en est issue par l'intermédiaire du latin."],
    ["Quelles langues forment la branche romane ?", ["Français, italien, espagnol, portugais, roumain et autres", "Français, anglais et allemand", "Espagnol, basque et catalan", "Italien, grec et latin"], 0,
     "Le catalan, l'occitan, le sarde et le romanche en font également partie."],
    ["À quelle famille l'anglais appartient-il ?", ["Aux langues germaniques", "Aux langues romanes", "Aux langues celtiques", "Aux langues slaves"], 0,
     "Malgré un vocabulaire massivement emprunté au français, sa grammaire reste germanique."],
    ["Quelle langue européenne n'appartient à aucune famille connue ?", ["Le basque", "Le finnois", "Le hongrois", "l'estonien"], 0,
     "Finnois, hongrois et estonien forment la famille finno-ougrienne, distincte de l'indo-européen."],
    ["À quelle famille l'arabe et l'hébreu appartiennent-ils ?", ["Aux langues sémitiques", "Aux langues indo-européennes", "Aux langues turciques", "Aux langues chamito-berbères seules"], 0,
     "La famille afro-asiatique inclut aussi les langues berbères et l'égyptien ancien."],
    ["Combien de langues parle-t-on environ dans le monde ?", ["Environ sept mille", "Environ mille", "Environ vingt mille", "Environ trois cents"], 0,
     "Une grande partie est menacée : plusieurs disparaissent chaque année."],
    ["Quelle langue compte le plus de locuteurs natifs ?", ["Le mandarin", "l'anglais", "l'espagnol", "l'hindi"], 0,
     "L'anglais domine en revanche largement le nombre total de locuteurs, langue seconde comprise."],
    ["Qu'est-ce qu'une langue isolante comme le chinois ?", ["Une langue où les mots ne se déclinent ni ne se conjuguent", "Une langue sans parenté connue", "Une langue à écriture idéographique", "Une langue à tons"], 0,
     "Le sens y dépend fortement de l'ordre des mots et de particules séparées."],
    ["Qu'est-ce qu'une langue agglutinante comme le turc ?", ["Une langue empilant des suffixes porteurs chacun d'un sens", "Une langue à mots très longs", "Une langue sans articles", "Une langue à conjugaison irrégulière"], 0,
     "Un seul mot peut y correspondre à une phrase entière en français."],
    ["Qu'est-ce qu'une langue à tons ?", ["Une langue où la hauteur de la voix distingue le sens des mots", "Une langue chantée", "Une langue à accent tonique variable", "Une langue à voyelles longues"], 0,
     "Le mandarin en compte quatre, le cantonais six à neuf selon les analyses.", 3],
  ]),

  notion("lf2-anglicismes", S, "Emprunts et anglicismes",
    "Comment le français emprunte, adapte ou remplace les mots étrangers.",
    "Le français a emprunté à des dizaines de langues, l'anglais n'étant que la plus récente.",
    2, [
    ["Quel terme officiel est recommandé pour remplacer l'anglais email ?", ["Courriel", "Courrier-e", "Mél", "Message électronique seul"], 0,
     "Mél sert d'abréviation devant une adresse, comme Tél. devant un numéro."],
    ["Quel terme officiel remplace le mot anglais hashtag ?", ["Mot-dièse", "Étiquette", "Mot-clic", "Balise"], 0,
     "Mot-clic est le terme recommandé au Québec, qui a précédé la France sur ce point."],
    ["Quel terme officiel français remplace smartphone ?", ["Ordiphone", "Téléphone intelligent", "Mobile évolué", "Téléphone connecté"], 0,
     "La recommandation est peu suivie en France ; le Québec emploie téléphone intelligent."],
    ["D'où vient le mot français bistrot selon l'étymologie la plus probable ?", ["D'un mot dialectal français, non du russe", "Du russe signifiant vite", "De l'italien", "De l'allemand"], 0,
     "La légende des cosaques réclamant à boire est séduisante mais chronologiquement invraisemblable."],
    ["Quel mot français a été emprunté par l'anglais puis réemprunté par le français ?", ["Tennis, issu du français tenez", "Sport", "Budget", "Rosbif"], 0,
     "Budget vient également du français bougette, la petite bourse, réemprunté ensuite à l'anglais."],
    ["Quelle langue a fourni au français des mots comme algèbre, alcool et amiral ?", ["l'arabe", "Le persan", "Le turc", "L'hébreu"], 0,
     "Plusieurs centaines de mots français en sont issus, souvent par l'intermédiaire de l'espagnol ou de l'italien."],
    ["Quel mot français vient du néerlandais par la marine ?", ["Bâbord", "Marin", "Voile", "Ancre"], 0,
     "Bâbord, tribord, matelot et cabillaud proviennent tous du néerlandais ou du bas-allemand."],
    ["Qu'est-ce qu'un faux anglicisme ?", ["Un mot d'apparence anglaise inconnu ou différent en anglais", "Un anglicisme mal orthographié", "Un mot anglais francisé", "Un emprunt refusé par l'Académie"], 0,
     "Un pressing, un footing ou un baby-foot ne se disent pas ainsi en anglais."],
    ["Pourquoi certains emprunts sont-ils préférés aux équivalents français ?", ["Ils sont plus brefs ou déjà connus dans un milieu professionnel", "Ils sont plus corrects", "Ils sont imposés par la loi", "Ils n'ont pas d'équivalent possible"], 0,
     "L'usage tranche : les recommandations officielles ne s'imposent qu'à l'administration."],
    ["Qu'est-ce qu'un emprunt intégré ?", ["Un mot étranger adapté à la prononciation et à l'orthographe françaises", "Un mot conservé tel quel", "Un mot traduit littéralement", "Un mot repris avec son sens d'origine"], 0,
     "Redingote vient de riding coat, paquebot de packet boat : l'origine s'y est effacée.", 3],
  ]),

  notion("lf2-conjugaison-systeme", S, "Le système verbal français",
    "Modes, temps, groupes : l'architecture de la conjugaison.",
    "Le français distingue le temps, le mode et l'aspect : trois notions souvent confondues.",
    2, [
    ["Combien de groupes de verbes la grammaire scolaire française distingue-t-elle ?", ["Trois", "Deux", "Quatre", "Cinq"], 0,
     "Le troisième groupe est en réalité un ensemble hétérogène de verbes irréguliers."],
    ["Combien de modes personnels le français compte-t-il ?", ["Quatre : indicatif, subjonctif, conditionnel et impératif", "Trois", "Cinq", "Deux"], 0,
     "Infinitif, participe et gérondif sont des modes impersonnels."],
    ["Que traduit l'aspect d'un verbe ?", ["Le déroulement de l'action, achevée ou en cours", "Le moment de l'action", "L'attitude du locuteur", "La personne qui agit"], 0,
     "L'imparfait et le passé simple situent tous deux dans le passé mais diffèrent par l'aspect."],
    ["Quelle est la valeur principale de l'imparfait ?", ["Présenter une action en cours ou répétée dans le passé", "Situer une action ponctuelle passée", "Exprimer une hypothèse", "Marquer l'antériorité"], 0,
     "Le passé simple, lui, présente l'action comme un fait achevé et ponctuel."],
    ["Dans quel registre le passé simple s'emploie-t-il aujourd'hui ?", ["Surtout à l'écrit littéraire et historique", "Dans la langue parlée courante", "Uniquement au subjonctif", "Dans la langue administrative"], 0,
     "Le passé composé l'a remplacé à l'oral dans presque toutes ses valeurs."],
    ["Qu'exprime le conditionnel présent ?", ["Une hypothèse, une atténuation ou un futur dans le passé", "Uniquement une condition", "Une obligation", "Une action achevée"], 0,
     "Sa valeur de futur du passé explique qu'il soit parfois analysé comme un temps de l'indicatif."],
    ["Après quelles conjonctions le subjonctif est-il généralement requis ?", ["Bien que, quoique, avant que, pour que", "Parce que, puisque, comme", "Alors que, tandis que", "Depuis que, après que"], 0,
     "Après que appelle en principe l'indicatif, même si l'usage hésite fortement."],
    ["Qu'est-ce qu'un verbe pronominal ?", ["Un verbe employé avec un pronom réfléchi de même personne que le sujet", "Un verbe sans complément", "Un verbe à sens passif", "Un verbe impersonnel"], 0,
     "Leur accord au passé composé dépend de la fonction du pronom, ce qui explique sa difficulté."],
    ["Qu'est-ce qu'un verbe défectif ?", ["Un verbe dont certaines formes n'existent pas dans l'usage", "Un verbe irrégulier", "Un verbe archaïque", "Un verbe transitif indirect"], 0,
     "Le verbe frire ou le verbe choir ne se conjuguent qu'à certaines personnes et à certains temps."],
    ["Pourquoi la voix passive est-elle parfois ambiguë en français ?", ["Sa forme se confond avec celle d'un attribut du sujet", "Elle supprime toujours l'agent", "Elle change le temps du verbe", "Elle inverse l'ordre des mots"], 0,
     "La porte est fermée peut décrire une action subie ou un état constaté.", 3],
  ]),

  notion("lf2-orthographe-histoire", S, "L'histoire de l'orthographe française",
    "Pourquoi le français s'écrit-il ainsi.",
    "L'orthographe française conserve des lettres qui ne se prononcent plus depuis des siècles.",
    2, [
    ["Pourquoi l'orthographe française est-elle si éloignée de la prononciation ?", ["Elle a conservé des graphies anciennes après l'évolution des sons", "Elle a été fixée arbitrairement", "Elle imite le latin classique seul", "Elle suit une logique étymologique stricte"], 0,
     "Beaucoup de consonnes finales muettes se prononçaient encore au Moyen Âge."],
    ["Pourquoi certains mots comportent-ils des lettres étymologiques inutiles ?", ["Des humanistes de la Renaissance les ont ajoutées pour rappeler le latin", "Elles ont toujours existé", "Elles marquent la prononciation ancienne", "Elles distinguent les homonymes"], 0,
     "Le b de doubter, aujourd'hui douter, ou le p de temps en sont des exemples."],
    ["Que remplace souvent l'accent circonflexe en français ?", ["Un s disparu de l'ancien français", "Une voyelle longue", "Un accent tonique", "Une consonne double"], 0,
     "Forêt vient de forest, hôpital de hospital, comme le montrent les mots de la même famille."],
    ["Quand l'Académie française publie-t-elle la première édition de son dictionnaire ?", ["En 1694", "En 1635", "En 1762", "En 1798"], 0,
     "Elle avait été chargée de cette mission dès sa fondation, cinquante-neuf ans plus tôt."],
    ["Quelle réforme orthographique de 1835 modifie de nombreux pluriels ?", ["Le passage de -ois à -ais dans certains mots et le pluriel en -ants", "La suppression des accents circonflexes", "L'introduction du tréma", "La simplification des consonnes doubles"], 0,
     "Elle a notamment fait passer françois à français."],
    ["Qu'est-ce que la dictée de Mérimée ?", ["Une dictée réputée difficile écrite pour la cour de Napoléon III", "Un exercice scolaire du XIXe siècle", "Une épreuve du certificat d'études", "Un concours orthographique national"], 0,
     "Elle circule encore comme exercice de virtuosité orthographique."],
    ["Qu'est-ce que les rectifications de 1990 modifient principalement ?", ["Trait d'union, pluriel des composés, accent circonflexe et anomalies", "L'ensemble de l'orthographe", "La conjugaison", "L'accord du participe passé"], 0,
     "Elles concernent environ deux mille mots et restent facultatives."],
    ["Quel statut les rectifications de 1990 ont-elles en France ?", ["Elles sont recommandées, les deux graphies étant admises", "Elles sont obligatoires depuis 2016", "Elles ont été abandonnées", "Elles ne valent que pour l'administration"], 0,
     "Les manuels scolaires les appliquent depuis 2016, sans que l'ancienne graphie soit fautive."],
    ["Pourquoi l'accord du participe passé avec avoir est-il souvent jugé complexe ?", ["Il dépend de la place du complément d'objet direct", "Il varie selon le temps employé", "Il dépend du sujet", "Il change selon le registre"], 0,
     "La règle est attribuée à Clément Marot, qui l'aurait empruntée à l'italien au XVIe siècle."],
    ["Quel projet de simplification orthographique a été proposé sans aboutir en France ?", ["Plusieurs, dont ceux des années 1890 et 1970", "Un seul, en 1990", "Aucun avant le XXe siècle", "Un projet européen dans les années 1950"], 0,
     "L'attachement culturel à l'orthographe a fait échouer la plupart des tentatives.", 3],
  ]),

  notion("lf2-lexicographie", S, "Faire un dictionnaire",
    "Comment on décide qu'un mot existe et ce qu'il signifie.",
    "Un dictionnaire ne crée pas les mots : il enregistre un usage déjà établi.",
    2, [
    ["Sur quoi les lexicographes s'appuient-ils pour retenir un mot ?", ["Un usage attesté, durable et suffisamment répandu", "Une décision de l'Académie", "Une demande du public", "Une création littéraire remarquée"], 0,
     "Les corpus de presse et de textes numériques permettent aujourd'hui de mesurer cette diffusion."],
    ["Qu'est-ce qu'un corpus en lexicographie ?", ["Un vaste ensemble de textes servant à observer les usages", "Un dictionnaire de référence", "Un fichier de citations littéraires", "Une base d'exemples inventés"], 0,
     "Il permet de fonder les définitions sur des emplois réels plutôt que sur l'intuition."],
    ["Qu'est-ce qu'une entrée de dictionnaire ?", ["L'unité constituée d'un mot vedette et de son traitement", "La première définition d'un mot", "Un renvoi entre deux mots", "Un exemple d'emploi"], 0,
     "Une entrée peut comporter plusieurs sens, numérotés et hiérarchisés."],
    ["Comment les sens d'un mot sont-ils ordonnés dans un dictionnaire ?", ["Par ordre historique ou par fréquence selon les ouvrages", "Toujours par ordre alphabétique", "Du plus rare au plus courant", "Selon l'importance grammaticale"], 0,
     "Le Robert privilégie l'ordre historique, d'autres dictionnaires la fréquence d'usage."],
    ["Qu'est-ce qu'une marque d'usage dans un dictionnaire ?", ["Une indication de registre, de domaine ou de région", "Une marque déposée citée", "Un signe de prononciation", "Une note étymologique"], 0,
     "Familier, vieilli, technique ou régional orientent l'emploi du mot."],
    ["Qu'est-ce que le Trésor de la langue française ?", ["Un vaste dictionnaire du français des XIXe et XXe siècles", "Un dictionnaire de l'ancien français", "Le dictionnaire de l'Académie", "Un dictionnaire étymologique"], 0,
     "Seize volumes, consultables gratuitement en ligne, avec une richesse de citations considérable."],
    ["Qu'est-ce qu'un dictionnaire étymologique ?", ["Un ouvrage retraçant l'origine et l'évolution des mots", "Un dictionnaire des mots anciens", "Un dictionnaire bilingue latin-français", "Un dictionnaire des racines grecques"], 0,
     "Il distingue attestation la plus ancienne, langue d'origine et évolutions de sens."],
    ["Qu'est-ce qu'un dictionnaire de synonymes ?", ["Un ouvrage groupant des mots de sens voisins avec leurs nuances", "Une liste d'équivalents interchangeables", "Un dictionnaire analogique", "Un thésaurus alphabétique"], 0,
     "Les synonymes parfaits sont rares : c'est justement l'objet de ces ouvrages de le montrer."],
    ["Qu'est-ce qu'un dictionnaire analogique ?", ["Un ouvrage permettant de retrouver un mot à partir d'une idée", "Un dictionnaire de comparaisons", "Un dictionnaire par thèmes illustré", "Un dictionnaire de métaphores"], 0,
     "Il répond à la question inverse d'un dictionnaire ordinaire : partir du sens pour trouver le mot."],
    ["Combien de mots un dictionnaire général de langue française contient-il environ ?", ["Entre soixante mille et cent mille", "Environ dix mille", "Environ cinq cent mille", "Environ un million"], 0,
     "Le lexique total du français, termes techniques compris, dépasse largement ce nombre.", 3],
  ]),

  notion("lf2-oral-ecrit", S, "L'oral et l'écrit",
    "Deux systèmes distincts, non une simple transcription l'un de l'autre.",
    "L'écrit n'est pas de l'oral transcrit : chacun a ses règles propres.",
    2, [
    ["Quelle différence fondamentale sépare l'oral et l'écrit ?", ["Ils obéissent à des règles et à des contraintes différentes", "L'écrit est plus correct", "L'oral est plus simple", "L'écrit reproduit l'oral"], 0,
     "L'oral dispose de l'intonation, du geste et du contexte ; l'écrit doit tout expliciter."],
    ["Qu'est-ce qu'une liaison en français ?", ["La prononciation d'une consonne finale devant une voyelle", "Un enchaînement de deux mots", "Une élision de voyelle", "Un accent d'insistance"], 0,
     "Certaines sont obligatoires, d'autres facultatives, d'autres interdites."],
    ["Qu'est-ce qu'une élision ?", ["La suppression d'une voyelle finale devant une voyelle initiale", "Une liaison non prononcée", "Un raccourcissement de mot", "Une chute de consonne"], 0,
     "L'apostrophe la note à l'écrit : l'ami, s'il, jusqu'à."],
    ["Où se place l'accent tonique en français ?", ["Sur la dernière syllabe prononcée du groupe", "Sur la première syllabe du mot", "Sur l'avant-dernière syllabe", "Il n'existe pas en français"], 0,
     "C'est une particularité qui distingue nettement le français de l'espagnol ou de l'italien."],
    ["Qu'est-ce qu'un phonème disparu du français standard contemporain ?", ["La distinction entre brin et brun chez de nombreux locuteurs", "Le son ou", "Le son é", "La consonne r"], 0,
     "Les voyelles nasales se sont progressivement réduites de quatre à trois pour beaucoup de francophones."],
    ["Qu'est-ce que le e caduc ?", ["Un e qui peut être prononcé ou non selon le contexte", "Un e muet toujours silencieux", "Un e final de féminin", "Un e d'appui grammatical"], 0,
     "Sa prononciation varie fortement selon les régions et les registres."],
    ["Qu'est-ce que la négation à deux éléments en français ?", ["La construction ne… pas, dont le ne s'efface souvent à l'oral", "Une double négation fautive", "L'emploi de ni… ni", "Une négation renforcée"], 0,
     "L'oral courant emploie très majoritairement la négation sans ne, ce qui n'est pas une faute mais un registre."],
    ["Qu'est-ce qu'une phrase segmentée à l'oral ?", ["Une construction détachant un élément repris par un pronom", "Une phrase interrompue", "Une phrase sans verbe", "Une phrase juxtaposée"], 0,
     "Moi, je pense que… est une segmentation très courante et parfaitement grammaticale à l'oral."],
    ["Comment l'interrogation se forme-t-elle le plus souvent à l'oral ?", ["Par la seule intonation ou par est-ce que", "Par l'inversion du sujet", "Par l'ajout d'un mot interrogatif final", "Par un auxiliaire spécifique"], 0,
     "L'inversion est surtout écrite ou soutenue : tu viens ? est la forme la plus fréquente."],
    ["Pourquoi l'oral spontané paraît-il incorrect à l'écrit ?", ["Ses procédés propres sont jugés à l'aune de normes écrites", "Il est réellement fautif", "Il manque de vocabulaire", "Il ignore la grammaire"], 0,
     "Une transcription brute d'oral, même d'un locuteur très cultivé, paraît toujours désorganisée.", 3],
  ]),

  notion("lf2-noms-communs-origines", S, "L'origine des mots du quotidien",
    "Des histoires de mots qu'on emploie sans y penser.",
    "L'histoire d'un mot révèle souvent une réalité matérielle disparue.",
    2, [
    ["D'où vient le mot travail ?", ["D'un instrument de contention pour les animaux", "Du latin signifiant effort", "D'un mot germanique désignant la peine", "Du grec signifiant fatigue"], 0,
     "Le tripalium était un appareil à trois pieux ; l'évolution de sens vers la peine puis l'activité est ancienne."],
    ["D'où vient le mot candidat ?", ["Du latin candidus, blanc, couleur de la toge des postulants", "D'un mot signifiant choisir", "D'un terme grec pour élection", "D'un mot désignant la promesse"], 0,
     "À Rome, les candidats blanchissaient leur toge à la craie pour être reconnaissables."],
    ["D'où vient le mot bureau ?", ["D'une étoffe de laine recouvrant la table", "Du latin signifiant bois", "D'un mot désignant un meuble à tiroirs", "D'un terme d'architecture"], 0,
     "La bure recouvrait le meuble ; le nom du tissu a désigné le meuble puis la pièce puis l'institution."],
    ["D'où vient le mot fenêtre ?", ["Du latin fenestra", "Du germanique", "Du gaulois", "Du grec"], 0,
     "L'anglais window vient au contraire du vieux norrois, littéralement l'œil du vent."],
    ["D'où vient le mot dimanche ?", ["Du latin dies dominicus, le jour du Seigneur", "D'un mot désignant le repos", "Du nom d'une divinité", "D'un terme germanique"], 0,
     "Les autres jours de la semaine portent des noms de divinités romaines associées aux planètes."],
    ["D'où vient le mot salade ?", ["De l'italien insalata, mets salé", "D'un mot latin désignant l'herbe", "D'un terme provençal", "Du grec"], 0,
     "Le sel servait à assaisonner les herbes crues, d'où le nom du plat entier."],
    ["Qu'imposa Eugène Poubelle aux propriétaires parisiens en 1884 ?", ["Des récipients couverts pour les ordures ménagères", "Un ramassage quotidien payant", "Le tri des déchets", "L'interdiction de jeter dans la rue"], 0,
     "La mesure fut d'abord très mal accueillie ; son nom est resté attaché à l'objet."],
    ["D'où vient le mot silhouette ?", ["Du nom d'un contrôleur général des finances", "D'un terme de dessin italien", "D'un mot flamand", "Du grec"], 0,
     "Étienne de Silhouette, ministre en 1759, était réputé pour son avarice et ses portraits découpés à peu de frais."],
    ["D'où vient le mot boycott ?", ["Du nom d'un régisseur irlandais mis à l'écart", "D'un verbe anglais ancien", "D'un mot néerlandais", "D'un terme de commerce maritime"], 0,
     "Charles Boycott fut ostracisé par les fermiers irlandais en 1880."],
    ["D'où vient le mot sandwich ?", ["Du nom d'un comte anglais", "D'un mot néerlandais", "D'un terme de marine", "D'une ville anglaise seulement"], 0,
     "Le comte de Sandwich aurait demandé qu'on lui serve de la viande entre deux tranches pour ne pas quitter sa table de jeu.", 3],
  ]),

  notion("lf2-argot-francais", S, "L'argot et les parlers familiers",
    "Des langues dans la langue, leurs procédés et leur histoire.",
    "L'argot se renouvelle sans cesse : dès qu'il est compris de tous, il cesse de remplir sa fonction.",
    2, [
    ["Quel est le rôle historique de l'argot ?", ["Rendre le discours incompréhensible aux non-initiés", "Simplifier la langue", "Enrichir le vocabulaire courant", "Marquer une origine régionale"], 0,
     "Il crée aussi une identité de groupe, fonction qui subsiste même quand le secret n'est plus nécessaire."],
    ["Quel procédé consiste à insérer des syllabes parasites dans les mots ?", ["Le largonji ou le javanais", "Le verlan", "Le loucherbem seul", "L'apocope"], 0,
     "En javanais, Paris devient Pavaravis. Le procédé était très en vogue au XIXe siècle."],
    ["Qu'est-ce que le loucherbem ?", ["Un argot de bouchers déplaçant l'initiale et ajoutant un suffixe", "Un argot de typographes", "Un parler de forains", "Un jargon de marins"], 0,
     "Boucher devient loucherbem, fou devient loufoque : ce dernier est passé dans la langue courante."],
    ["Qu'est-ce qu'une apocope ?", ["La suppression de la fin d'un mot", "La suppression du début", "L'inversion des syllabes", "L'ajout d'un suffixe"], 0,
     "Ciné, prof, resto, appart : le procédé est très productif en français familier."],
    ["Qu'est-ce qu'une aphérèse ?", ["La suppression du début d'un mot", "La suppression de la fin", "La chute d'une syllabe médiane", "Le redoublement d'une syllabe"], 0,
     "Bus pour autobus, blème pour problème : elle est moins fréquente que l'apocope en français."],
    ["Quel écrivain a introduit massivement l'argot en littérature au XXe siècle ?", ["Louis-Ferdinand Céline", "Marcel Proust", "André Gide", "Paul Valéry"], 0,
     "Voyage au bout de la nuit, en 1932, a fait scandale par sa langue autant que par son propos."],
    ["Quel auteur de romans policiers a créé un argot largement inventé ?", ["Frédéric Dard, sous le nom de San-Antonio", "Georges Simenon", "Léo Malet", "Albert Simonin"], 0,
     "Albert Simonin, lui, s'appuyait sur un argot réellement pratiqué, qu'il a documenté."],
    ["Qu'est-ce que le parler des cités contemporain ?", ["Un ensemble de variétés mêlant emprunts, verlan et innovations", "Un argot unique et codifié", "Un dialecte régional", "Un français simplifié"], 0,
     "Il emprunte à l'arabe, aux langues africaines, au romani et à l'anglais."],
    ["Que deviennent les mots d'argot avec le temps ?", ["Beaucoup passent dans la langue courante et perdent leur marque", "Ils disparaissent tous", "Ils restent confinés à un milieu", "Ils sont interdits par l'Académie"], 0,
     "Bagnole, boulot, mec ou flic ont suivi ce chemin sur plusieurs générations."],
    ["Pourquoi l'argot se renouvelle-t-il constamment ?", ["Il perd sa fonction dès qu'il est compris de tous", "Ses locuteurs changent de génération", "Il suit la mode", "Il est réprimé par les institutions"], 0,
     "C'est une course permanente entre le groupe et ceux qui décodent son vocabulaire.", 3],
  ]),

  notion("lf2-genres-noms", S, "Le genre des noms",
    "Masculin, féminin, hésitations : d'où vient le genre grammatical.",
    "Le genre grammatical est très largement arbitraire et varie d'une langue à l'autre.",
    2, [
    ["Le genre grammatical est-il lié au sens du mot ?", ["Non, il est très largement arbitraire", "Oui, il reflète une propriété du référent", "Oui, pour les objets uniquement", "Oui, sauf exceptions rares"], 0,
     "Le soleil est masculin en français, féminin en allemand ; la lune fait l'inverse."],
    ["Combien de genres le latin comptait-il ?", ["Trois : masculin, féminin et neutre", "Deux", "Quatre", "Un seul"], 0,
     "Le neutre a disparu en français, ses mots se répartissant entre masculin et féminin."],
    ["Quel mot français change de sens selon son genre ?", ["Un livre et une livre", "Une table", "Un chemin", "Une porte"], 0,
     "Un mode et une mode, un poêle et une poêle, un voile et une voile fonctionnent de même."],
    ["Quel est le genre du mot après-midi ?", ["Les deux genres sont admis", "Masculin uniquement", "Féminin uniquement", "Neutre"], 0,
     "L'usage masculin est aujourd'hui nettement majoritaire."],
    ["Quel est le genre du mot amour au pluriel dans l'usage soutenu ?", ["Féminin", "Masculin", "Les deux indifféremment", "Neutre"], 0,
     "Délice et orgue suivent la même particularité : masculins au singulier, féminins au pluriel dans l'usage classique."],
    ["Quel mot est souvent employé au mauvais genre en français ?", ["Autoroute, qui est féminin", "Avion", "Wagon", "Bureau"], 0,
     "Antidote, astérisque, pétale et haltère sont masculins ; oasis et échappatoire sont féminins."],
    ["Comment le féminin des noms de métiers se forme-t-il généralement ?", ["Par ajout d'un e ou d'un suffixe spécifique", "Par l'article seul", "Par un mot entièrement différent", "Il ne se forme pas"], 0,
     "Auteure, autrice, écrivaine : plusieurs formations coexistent, avec des préférences régionales."],
    ["Quelle position l'Académie française a-t-elle adoptée en 2019 sur la féminisation des métiers ?", ["Elle n'y voit plus d'obstacle de principe", "Elle l'a interdite", "Elle l'a rendue obligatoire", "Elle ne s'est pas prononcée"], 0,
     "Elle s'y était longtemps opposée, alors que le Québec et la Belgique l'avaient adoptée bien plus tôt."],
    ["Qu'est-ce que l'accord de proximité ?", ["L'accord de l'adjectif avec le nom le plus proche", "L'accord avec le sujet le plus important", "L'accord au masculin par défaut", "L'accord avec le premier nom cité"], 0,
     "Pratiqué en ancien français et jusqu'au XVIIe siècle, il a été écarté au profit du masculin générique."],
    ["Qu'est-ce que l'écriture inclusive au sens large ?", ["Un ensemble de procédés visant à rendre les femmes visibles dans la langue", "L'usage du point médian uniquement", "Une réforme orthographique", "Une norme administrative"], 0,
     "Doublets, noms épicènes et féminisation des titres en font partie ; le point médian n'en est qu'un procédé parmi d'autres.", 3],
  ]),

  notion("lf2-syntaxe-phrase", S, "La phrase française",
    "Ordre des mots, subordination, ponctuation logique.",
    "L'ordre sujet-verbe-complément est la règle en français, mais il souffre de nombreuses exceptions.",
    2, [
    ["Quel est l'ordre canonique des mots en français ?", ["Sujet, verbe, complément", "Verbe, sujet, complément", "Sujet, complément, verbe", "Complément, verbe, sujet"], 0,
     "Cet ordre rigide compense la disparition des déclinaisons latines."],
    ["Qu'est-ce qu'une proposition subordonnée complétive ?", ["Une proposition introduite par que, complément du verbe", "Une proposition relative", "Une proposition circonstancielle", "Une proposition participiale"], 0,
     "Je pense qu'il viendra : la subordonnée y occupe la place d'un complément d'objet."],
    ["Qu'est-ce qu'une proposition subordonnée circonstancielle ?", ["Une proposition exprimant le temps, la cause, le but ou la condition", "Une proposition complément du nom", "Une proposition sujet", "Une proposition d'attribution"], 0,
     "Elle peut souvent être déplacée dans la phrase, contrairement à la complétive."],
    ["Qu'est-ce qu'une apposition ?", ["Un élément détaché qui caractérise un nom sans mot de liaison", "Un complément du nom", "Un attribut du sujet", "Une épithète liée"], 0,
     "Paris, capitale de la France, … : l'apposition est isolée par des virgules."],
    ["Qu'est-ce qu'un complément d'objet indirect ?", ["Un complément relié au verbe par une préposition", "Un complément circonstanciel", "Un complément d'agent", "Un attribut du complément"], 0,
     "Parler à quelqu'un, penser à quelque chose : la préposition fait partie de la construction du verbe."],
    ["Qu'est-ce qu'un complément d'agent ?", ["Celui qui accomplit l'action dans une phrase passive", "Le sujet d'un verbe actif", "Un complément de moyen", "Un complément d'attribution"], 0,
     "Il est introduit par par ou de : la lettre a été écrite par Marie."],
    ["Qu'est-ce qu'une phrase nominale ?", ["Une phrase sans verbe conjugué", "Une phrase à sujet nominal", "Une phrase sans sujet", "Une phrase déclarative simple"], 0,
     "Fréquente dans les titres de presse et les slogans, elle est parfaitement correcte."],
    ["Qu'est-ce que la mise en relief ?", ["Un procédé détachant un élément pour l'accentuer", "Une répétition emphatique", "Un déplacement du verbe", "Une inversion du sujet"], 0,
     "C'est Marie qui a écrit la lettre : la construction met le sujet en avant sans changer l'ordre canonique."],
    ["Qu'est-ce que la virgule sépare obligatoirement ?", ["Les éléments d'une énumération et les propositions détachées", "Le sujet et le verbe", "Le verbe et son complément d'objet", "L'article et le nom"], 0,
     "Séparer le sujet du verbe par une seule virgule est une faute classique."],
    ["Qu'est-ce qu'un anacoluthe ?", ["Une rupture de construction syntaxique dans la phrase", "Une phrase trop longue", "Une répétition maladroite", "Un pléonasme"], 0,
     "Volontaire, elle est une figure de style ; involontaire, elle rend la phrase bancale.", 3],
  ]),

  notion("lf2-litterature-langue", S, "La langue des écrivains",
    "Comment les écrivains ont modelé le français.",
    "De nombreux mots français courants ont été forgés ou popularisés par des écrivains.",
    2, [
    ["Quel écrivain du XVIe siècle a créé de nombreux mots savants en français ?", ["Rabelais", "Montaigne", "Marot", "Du Bellay"], 0,
     "Il a introduit ou popularisé des centaines de termes tirés du grec et du latin."],
    ["Quel grammairien du XVIIe siècle codifie le bon usage ?", ["Vaugelas", "Malherbe", "Ménage", "Bouhours"], 0,
     "Ses Remarques sur la langue française, en 1647, prennent pour norme l'usage de la cour."],
    ["Quel poète du XVIIe siècle prône l'épuration de la langue poétique ?", ["Malherbe", "Ronsard", "Théophile de Viau", "Saint-Amant"], 0,
     "Enfin Malherbe vint, écrira Boileau, saluant cette clarté nouvelle."],
    ["Qu'est-ce que la préciosité au XVIIe siècle ?", ["Une recherche raffinée du langage dans certains salons", "Un mouvement littéraire baroque", "Une école de poésie religieuse", "Un style théâtral"], 0,
     "Molière l'a raillée dans Les Précieuses ridicules, ce qui a durablement noirci sa réputation."],
    ["Quel écrivain revendique une langue proche de l'oral populaire au XXe siècle ?", ["Céline", "Gide", "Valéry", "Mauriac"], 0,
     "Il parlait de rendre l'émotion du langage parlé dans l'écrit, par une syntaxe travaillée."],
    ["Quel écrivain français a écrit un même récit en quatre-vingt-dix-neuf variations stylistiques ?", ["Raymond Queneau", "Georges Perec", "Boris Vian", "Jacques Prévert"], 0,
     "Les Exercices de style, en 1947, sont devenus un classique de l'enseignement du français."],
    ["Quel écrivain a inventé le mot pataphysique ?", ["Alfred Jarry", "Raymond Roussel", "Boris Vian", "Antonin Artaud"], 0,
     "Science des solutions imaginaires, elle a donné lieu à un collège toujours actif."],
    ["Quel mot Rabelais a-t-il popularisé pour désigner un géant vorace ?", ["Gargantuesque, formé sur Gargantua", "Pantagruélique seul", "Titanesque", "Colossal"], 0,
     "Pantagruélique, formé sur son fils Pantagruel, désigne plus précisément un appétit démesuré."],
    ["Quel écrivain a créé le mot surréalisme ?", ["Guillaume Apollinaire", "André Breton", "Tristan Tzara", "Paul Éluard"], 0,
     "Il l'emploie en 1917 ; Breton s'en empare pour nommer le mouvement en 1924."],
    ["Pourquoi les écrivains influencent-ils la langue ?", ["Leurs créations et leurs tours se diffusent par la lecture et l'école", "Ils décident des règles", "Ils siègent à l'Académie", "Ils rédigent les dictionnaires"], 0,
     "Les dictionnaires les citent abondamment, ce qui consacre certains emplois.", 3],
  ]),

  notion("lf2-apprentissage-langues", S, "Apprendre et enseigner les langues",
    "Méthodes, cadres de référence, bilinguisme.",
    "Le Cadre européen commun définit six niveaux de maîtrise, de A1 à C2.",
    2, [
    ["Que définit le Cadre européen commun de référence pour les langues ?", ["Six niveaux de compétence de A1 à C2", "Un programme d'enseignement unique", "Une méthode d'apprentissage", "Un examen européen"], 0,
     "Il décrit ce qu'un apprenant sait faire, non ce qu'il a appris."],
    ["Que signifie le niveau B2 dans ce cadre ?", ["Un utilisateur indépendant capable de comprendre un discours complexe", "Un débutant avancé", "Un niveau proche du natif", "Un niveau élémentaire"], 0,
     "Il est souvent exigé pour l'accès aux études supérieures dans une langue étrangère."],
    ["Qu'est-ce que l'approche actionnelle en didactique des langues ?", ["Un enseignement fondé sur la réalisation de tâches concrètes", "Un apprentissage par la grammaire", "Une méthode par répétition", "Un enseignement par immersion totale"], 0,
     "Elle considère l'apprenant comme un acteur social accomplissant des actions, non un simple récepteur."],
    ["Qu'est-ce que la méthode audio-orale ?", ["Une méthode fondée sur la répétition de structures orales", "Une méthode d'écoute passive", "Une méthode de traduction", "Un enseignement par la chanson"], 0,
     "Développée pour l'armée américaine pendant la guerre, elle a dominé les années 1950 et 1960."],
    ["Qu'est-ce que l'immersion linguistique ?", ["Un enseignement de matières dans la langue cible", "Un séjour à l'étranger", "Un bain de langue par les médias", "Un enseignement intensif"], 0,
     "Les modèles canadiens d'immersion en français ont été très étudiés."],
    ["Qu'est-ce que l'interlangue d'un apprenant ?", ["Un système intermédiaire cohérent entre sa langue et la langue cible", "Un mélange fautif de deux langues", "Une traduction mentale", "Un vocabulaire limité"], 0,
     "Les erreurs y sont souvent systématiques, donc informatives sur l'état de l'apprentissage."],
    ["Qu'est-ce qu'un faux débutant ?", ["Un apprenant ayant déjà des connaissances passives inégales", "Un apprenant ayant échoué", "Un apprenant autodidacte", "Un apprenant en reprise d'études"], 0,
     "C'est le profil le plus répandu chez les adultes reprenant une langue apprise à l'école."],
    ["Le bilinguisme précoce retarde-t-il l'apprentissage du langage ?", ["Non, il ne cause pas de retard durable", "Oui, systématiquement", "Oui, chez les garçons", "Oui, pour le vocabulaire seulement"], 0,
     "Le vocabulaire peut être réparti entre les deux langues, mais le total est comparable."],
    ["Qu'est-ce que l'alternance codique ?", ["Le passage d'une langue à l'autre au sein d'un même échange", "Une confusion entre deux langues", "Une traduction simultanée", "Un emprunt lexical"], 0,
     "Loin d'être une déficience, elle obéit à des règles précises chez les bilingues compétents."],
    ["Quel âge est réputé favorable à l'acquisition d'un accent proche du natif ?", ["L'enfance, avec une décroissance progressive ensuite", "L'adolescence", "L'âge adulte avec un bon entraînement", "Il n'y a aucun effet de l'âge"], 0,
     "L'hypothèse d'une période critique stricte est discutée : le déclin semble progressif plutôt que brutal.", 3],
  ]),

  notion("lf2-textes-officiels", S, "Le français administratif et juridique",
    "Une langue de spécialité, ses conventions et ses critiques.",
    "Le langage administratif obéit à des exigences de précision qui expliquent une partie de sa lourdeur.",
    2, [
    ["Pourquoi le langage juridique emploie-t-il des formules figées ?", ["Leur sens a été précisé par la jurisprudence", "Par tradition uniquement", "Pour impressionner le lecteur", "Par imitation du latin"], 0,
     "Changer un mot peut modifier la portée d'un texte, d'où la prudence des rédacteurs."],
    ["Qu'est-ce que le considérant dans une décision de justice ?", ["Un paragraphe exposant un motif du raisonnement", "L'énoncé de la décision", "La citation d'un texte de loi", "Le résumé des faits"], 0,
     "Le Conseil d'État a modernisé sa rédaction en 2019 pour la rendre plus lisible."],
    ["Qu'est-ce que le dispositif d'un jugement ?", ["La partie énonçant la décision proprement dite", "L'exposé des motifs", "Le rappel des faits", "La liste des pièces"], 0,
     "C'est la seule partie revêtue de l'autorité de la chose jugée."],
    ["Qu'est-ce que le langage clair en administration ?", ["Une démarche visant à rendre les textes compréhensibles par leurs destinataires", "Une simplification du vocabulaire", "Une traduction en langage courant", "Un résumé des textes officiels"], 0,
     "Plusieurs pays en ont fait une politique publique, avec des tests auprès d'usagers."],
    ["Qu'est-ce qu'un formulaire Cerfa ?", ["Un formulaire administratif français normalisé", "Un certificat officiel", "Un registre d'état civil", "Une attestation sur l'honneur"], 0,
     "Le sigle vient d'un ancien centre d'enregistrement et de révision des formulaires administratifs."],
    ["Qu'est-ce que le Journal officiel de la République française ?", ["La publication qui rend les textes opposables", "Un recueil de jurisprudence", "Le bulletin du gouvernement", "Un registre des décisions administratives"], 0,
     "Un texte non publié ne peut en principe être opposé aux citoyens."],
    ["Qu'est-ce qu'une circulaire administrative ?", ["Une instruction adressée par un ministre à ses services", "Un décret d'application", "Un arrêté préfectoral", "Une note d'information sans portée"], 0,
     "Elle ne peut légalement ajouter à la loi, ce qui n'empêche pas les contentieux sur ce point."],
    ["Qu'est-ce qu'un décret d'application ?", ["Un texte précisant les modalités d'application d'une loi", "Un texte modifiant une loi", "Une loi d'urgence", "Un règlement européen transposé"], 0,
     "Son absence peut rendre une loi votée inapplicable pendant des années."],
    ["Qu'est-ce que la légistique ?", ["L'art et la technique de rédiger les textes normatifs", "L'étude de la légitimité des lois", "La science du droit comparé", "La codification du droit"], 0,
     "Des guides officiels en fixent les règles pour améliorer la qualité et la cohérence des textes."],
    ["Que critique-t-on principalement dans la langue administrative ?", ["Son opacité pour les usagers non spécialistes", "Son manque de vocabulaire", "Ses fautes de grammaire", "Sa longueur excessive uniquement"], 0,
     "L'enjeu est aussi un enjeu de droits : un texte incompréhensible entrave l'accès aux prestations.", 3],
  ]),

  notion("lf2-traduction-litteraire", S, "Traduire et interpréter",
    "Métiers, techniques, difficultés.",
    "La traduction écrite et l'interprétation orale sont deux métiers distincts.",
    2, [
    ["Quelle différence sépare traduction et interprétation ?", ["La première est écrite, la seconde orale", "La première est littéraire", "La seconde est plus fidèle", "Elles sont équivalentes"], 0,
     "Les compétences et les formations diffèrent nettement."],
    ["Qu'est-ce que l'interprétation simultanée ?", ["Une traduction orale en temps réel depuis une cabine", "Une traduction après chaque phrase", "Une traduction résumée", "Une lecture d'un texte préparé"], 0,
     "Elle a été mise en œuvre à grande échelle au procès de Nuremberg."],
    ["Qu'est-ce que l'interprétation consécutive ?", ["L'interprète parle après l'orateur, en s'appuyant sur des notes", "L'interprète parle en même temps", "L'interprète résume à la fin", "L'interprète traduit par écrit"], 0,
     "Elle repose sur une technique de prise de notes symbolique très spécifique."],
    ["Qu'est-ce qu'un traducteur assermenté ?", ["Un traducteur habilité par une cour d'appel pour les documents officiels", "Un traducteur diplômé", "Un traducteur juridique spécialisé", "Un traducteur agréé par un ministère"], 0,
     "Sa signature confère une valeur officielle à la traduction."],
    ["Qu'est-ce que la localisation d'un logiciel ?", ["Son adaptation linguistique et culturelle à un marché", "Sa traduction littérale", "Son adaptation technique", "Sa géolocalisation"], 0,
     "Formats de date, monnaies, sens de lecture et références culturelles y sont adaptés."],
    ["Qu'est-ce qu'une mémoire de traduction ?", ["Une base enregistrant les segments déjà traduits pour les réutiliser", "Un dictionnaire personnel", "Un glossaire terminologique", "Un logiciel de traduction automatique"], 0,
     "Elle assure la cohérence sur de grands volumes et accélère le travail."],
    ["Qu'est-ce que la post-édition ?", ["La révision humaine d'une traduction produite par une machine", "La relecture d'un texte traduit", "La mise en page finale", "La correction d'épreuves"], 0,
     "Elle est devenue une part importante du travail des traducteurs professionnels."],
    ["Quelle difficulté pose la traduction de l'humour ?", ["Il repose souvent sur la langue et des références partagées", "Il est trop familier", "Il varie selon les époques", "Il manque de vocabulaire équivalent"], 0,
     "Le traducteur doit parfois inventer un autre jeu de mots pour produire un effet équivalent."],
    ["Qu'est-ce que le sous-titrage, comme contrainte de traduction ?", ["Une traduction contrainte par la vitesse de lecture et l'espace", "Une traduction littérale des dialogues", "Une transcription du dialogue", "Une adaptation libre"], 0,
     "Il faut souvent condenser de trente à quarante pour cent du texte parlé."],
    ["Qu'est-ce que l'adaptation en doublage ?", ["Une réécriture tenant compte du mouvement des lèvres", "Une traduction fidèle des dialogues", "Un résumé des répliques", "Une transposition culturelle"], 0,
     "La synchronisation labiale impose des choix parfois éloignés du texte source.", 3],
  ]),

  notion("lf2-poesie-langue", S, "Sonorités et jeux de langue",
    "Rimes, homophonies, contrepèteries : ce que la langue permet de faire.",
    "Le français est particulièrement propice aux jeux d'homophonie en raison de ses nombreuses finales muettes.",
    2, [
    ["Qu'est-ce qu'une contrepèterie ?", ["L'interversion de sons produisant un autre sens, souvent grivois", "Un jeu de mots par homophonie", "Une inversion de lettres", "Un calembour approximatif"], 0,
     "La tradition veut qu'on ne l'explique jamais, laissant au lecteur le plaisir de la trouver."],
    ["Qu'est-ce qu'un calembour ?", ["Un jeu de mots fondé sur une ressemblance sonore", "Une inversion de syllabes", "Une phrase à double lecture", "Une figure de répétition"], 0,
     "Victor Hugo le qualifiait de fiente de l'esprit qui vole, sans s'en priver pour autant."],
    ["Qu'est-ce qu'un palindrome ?", ["Un mot ou une phrase se lisant identiquement dans les deux sens", "Un mot inversé", "Un anagramme parfait", "Un mot symétrique visuellement"], 0,
     "Kayak, ressasser, ou la phrase Ésope reste ici et se repose."],
    ["Qu'est-ce qu'une anagramme ?", ["Un mot formé en réarrangeant les lettres d'un autre", "Un mot lu à l'envers", "Un mot de même sonorité", "Un mot de même longueur"], 0,
     "Marcel Duchamp signait Rrose Sélavy, anagramme approximative d'Éros c'est la vie."],
    ["Qu'est-ce qu'un pangramme ?", ["Une phrase contenant toutes les lettres de l'alphabet", "Une phrase sans répétition de lettres", "Un texte à contrainte alphabétique", "Une phrase de longueur maximale"], 0,
     "Portez ce vieux whisky au juge blond qui fume en est le plus connu en français."],
    ["Quelle figure sonore correspond à la répétition d'une même voyelle ?", ["L'assonance", "L'allitération", "La paronomase", "L'anaphore"], 0,
     "L'allitération, elle, porte sur les consonnes. Les deux structurent le vers autant que la rime."],
    ["Qu'est-ce qu'une onomatopée ?", ["Un mot imitant un son", "Un cri animal", "Une interjection", "Un mot expressif inventé"], 0,
     "Le français en compte des centaines, dont beaucoup ne figurent pas dans les dictionnaires."],
    ["Qu'est-ce qu'un acrostiche ?", ["Un texte dont les initiales de chaque vers forment un mot", "Un poème à rimes croisées", "Un poème sans ponctuation", "Un texte lu verticalement"], 0,
     "Le procédé a servi à dissimuler des messages ou des dédicaces."],
    ["Qu'est-ce qu'une charade ?", ["Une devinette décomposant un mot en syllabes définies séparément", "Un mot croisé oral", "Une énigme logique", "Un rébus parlé"], 0,
     "Mon premier, mon second, mon tout : la structure est fixe depuis le XVIIIe siècle."],
    ["Qu'est-ce qu'un rébus ?", ["Une devinette où des images représentent des sons", "Une charade illustrée", "Un mot-croisé imagé", "Un anagramme visuel"], 0,
     "Le mot vient du latin signifiant par les choses : les objets figurent des sons, non des idées.", 3],
  ]),

  notion("lf2-communication-orale", S, "Parler en public",
    "Voix, structure, rapport à l'auditoire.",
    "Parler en public s'apprend : ce n'est ni un don ni une question de confiance seule.",
    2, [
    ["Qu'est-ce que le trac avant une prise de parole ?", ["Une réaction physiologique de stress, normale et gérable", "Un manque de préparation", "Un défaut de personnalité", "Un signe d'incompétence"], 0,
     "Les orateurs expérimentés le ressentent aussi ; ils apprennent à l'utiliser plutôt qu'à le supprimer."],
    ["Que faut-il travailler en priorité pour une prise de parole ?", ["La structure du propos et son fil conducteur", "L'apprentissage par cœur", "Les effets de voix", "Le vocabulaire soutenu"], 0,
     "Un auditoire pardonne des hésitations, jamais un propos dont il ne saisit pas la logique."],
    ["Qu'est-ce que le débit dans l'expression orale ?", ["La vitesse d'élocution", "Le volume de la voix", "L'articulation des mots", "La hauteur de la voix"], 0,
     "Un débit trop rapide est le défaut le plus fréquent des orateurs anxieux."],
    ["Quel rôle le silence joue-t-il dans un discours ?", ["Il souligne, laisse respirer et marque les articulations", "Il trahit une hésitation", "Il doit être évité", "Il ralentit inutilement le propos"], 0,
     "Les pauses maîtrisées sont l'un des marqueurs les plus nets d'un orateur expérimenté."],
    ["Qu'est-ce que le contact visuel avec l'auditoire ?", ["Un regard distribué qui maintient l'attention et l'échange", "Un regard fixe sur une personne", "Un balayage rapide de la salle", "Un regard vers le fond de la salle"], 0,
     "Fixer ses notes ou l'écran rompt le lien plus sûrement que n'importe quelle maladresse."],
    ["Qu'est-ce qu'une accroche dans une prise de parole ?", ["Une entrée en matière captant immédiatement l'attention", "Le titre de l'exposé", "La présentation de l'orateur", "L'annonce du plan"], 0,
     "Question, anecdote ou chiffre frappant : elle précède utilement l'annonce du plan."],
    ["Comment faut-il utiliser un support de projection ?", ["En appui, sans y transcrire l'intégralité du discours", "En y écrivant tout le propos", "En le lisant à voix haute", "En multipliant les animations"], 0,
     "Un auditoire ne peut lire et écouter simultanément : il fera l'un ou l'autre."],
    ["Qu'est-ce que l'adaptation à l'auditoire ?", ["L'ajustement du vocabulaire et des exemples au public visé", "La modification du contenu selon les réactions", "Le choix d'un ton familier", "La simplification systématique"], 0,
     "Le même contenu se présente différemment devant des spécialistes et devant des néophytes."],
    ["Qu'est-ce qu'une reformulation dans un échange ?", ["La reprise de ce qui a été dit pour vérifier la compréhension", "Une répétition du propos", "Une correction du propos d'autrui", "Un résumé final"], 0,
     "Elle est particulièrement utile pour désamorcer un désaccord fondé sur un malentendu."],
    ["Qu'est-ce que l'écoute active ?", ["Une attention manifestée par des signaux verbaux et non verbaux", "Une écoute silencieuse", "Une prise de notes systématique", "Une reformulation permanente"], 0,
     "Elle facilite l'échange et améliore la mémorisation de ce qui est dit.", 3],
  ]),

  notion("lf2-numerique-langue", S, "La langue et le numérique",
    "Écriture en ligne, correcteurs, traitement automatique.",
    "Les usages écrits en ligne ont créé des formes hybrides entre oral et écrit.",
    2, [
    ["Qu'est-ce qu'un correcteur orthographique automatique ?", ["Un outil comparant les mots à un dictionnaire et à des règles", "Un logiciel de traduction", "Un analyseur grammatical complet", "Un outil de reformulation"], 0,
     "Il ne détecte pas les erreurs produisant un mot existant, comme un homophone mal choisi."],
    ["Pourquoi les correcteurs ne détectent-ils pas toutes les fautes ?", ["Ils analysent mal le sens et le contexte", "Ils sont mal programmés", "Leur dictionnaire est trop petit", "Ils ignorent la grammaire"], 0,
     "La distinction entre ces, ses, c'est et s'est exige une compréhension du sens de la phrase."],
    ["Qu'est-ce que le traitement automatique du langage ?", ["Un domaine visant à faire analyser et produire du texte par des machines", "La correction automatique", "La traduction assistée", "L'indexation de documents"], 0,
     "Il combine linguistique, statistique et apprentissage automatique."],
    ["Qu'est-ce qu'une écriture SMS ?", ["Un ensemble d'abréviations nées de contraintes de saisie et de coût", "Une langue nouvelle", "Une orthographe fautive", "Un argot de jeunes"], 0,
     "Les études montrent qu'elle n'altère pas la maîtrise orthographique de ceux qui la pratiquent."],
    ["Qu'est-ce qu'un émoji du point de vue linguistique ?", ["Un signe qui apporte un ton ou une intention à un message", "Une ponctuation graphique", "Un mot pictural", "Un substitut de vocabulaire"], 0,
     "Il compense l'absence d'intonation et de gestes propre à l'écrit."],
    ["Qu'est-ce que la synthèse vocale ?", ["La production automatique de parole à partir d'un texte", "La reconnaissance de la parole", "L'enregistrement d'une voix", "La modification d'une voix"], 0,
     "Elle est essentielle à l'accessibilité pour les personnes déficientes visuelles."],
    ["Qu'est-ce que la reconnaissance automatique de la parole ?", ["La transcription automatique d'un signal sonore en texte", "La synthèse vocale", "L'identification d'un locuteur", "La traduction orale"], 0,
     "Ses performances chutent fortement en présence de bruit, d'accents ou de plusieurs locuteurs."],
    ["Qu'est-ce qu'un modèle de langue ?", ["Un système statistique prédisant la suite probable d'un texte", "Un modèle grammatical formel", "Un dictionnaire structuré", "Une norme linguistique"], 0,
     "Les grands modèles récents reposent sur ce principe, appliqué à des corpus immenses."],
    ["Pourquoi la qualité des données linguistiques compte-t-elle pour ces systèmes ?", ["Ils reproduisent les biais et les lacunes de leurs corpus d'entraînement", "Elles déterminent leur vitesse", "Elles fixent leur vocabulaire maximal", "Elles limitent leur taille"], 0,
     "Les langues peu dotées en données numériques sont nettement moins bien traitées."],
    ["Qu'est-ce qu'une langue peu dotée numériquement ?", ["Une langue disposant de peu de ressources écrites exploitables", "Une langue à peu de locuteurs", "Une langue sans écriture", "Une langue non officielle"], 0,
     "La majorité des sept mille langues du monde sont dans ce cas, ce qui accroît les inégalités d'accès aux outils.", 3],
  ]),

  notion("lf2-noms-lieux-france", S, "La toponymie française",
    "Ce que les noms de lieux racontent de l'histoire du peuplement.",
    "La carte des noms de lieux est une archive de deux mille ans de peuplement.",
    2, [
    ["Que signifient les noms de lieux en -ville ?", ["Un domaine rural, du latin villa", "Une ville fortifiée", "Un bourg marchand", "Une agglomération romaine"], 0,
     "Le sens de cité est bien plus tardif ; à l'origine il désigne une exploitation agricole."],
    ["Que signifient les noms en -court ?", ["Un domaine rural, souvent d'origine franque", "Une cour de justice", "Une résidence seigneuriale", "Un enclos fortifié"], 0,
     "Ils sont concentrés dans le nord-est de la France, zone de peuplement franc."],
    ["Que signale le préfixe Saint- dans un nom de commune ?", ["Une fondation ou une dédicace religieuse", "Un lieu de pèlerinage", "Un ancien monastère", "Une donation ecclésiastique"], 0,
     "Plusieurs milliers de communes françaises en portent, avec des variantes régionales."],
    ["Que désigne le suffixe -ing dans les noms de Moselle ?", ["Un domaine appartenant à un chef germanique", "Une prairie", "Un cours d'eau", "Un défrichement"], 0,
     "Il correspond au -ange francisé et marque la limite du peuplement germanique."],
    ["Que signifie le terme mont dans les toponymes ?", ["Une hauteur, même modeste", "Une montagne au sens strict", "Un sommet enneigé", "Un col"], 0,
     "Une colline de quelques dizaines de mètres suffit à justifier le nom dans les plaines."],
    ["Que désignent les noms de lieux en -ac dans le sud-ouest ?", ["Un domaine gallo-romain", "Une source", "Une clairière", "Un gué"], 0,
     "Ils correspondent aux -y et -é du nord, issus du même suffixe latin -acum."],
    ["Que signifie le préfixe Plou- en Bretagne ?", ["Une paroisse primitive", "Un village", "Une colline", "Une rivière"], 0,
     "Il vient du latin plebem, le peuple, désignant la communauté paroissiale."],
    ["Que signale un toponyme en -sart ou -essart ?", ["Un défrichement médiéval", "Un marécage asséché", "Un pâturage", "Une clairière naturelle"], 0,
     "Il témoigne de la grande vague de défrichement des XIe et XIIe siècles."],
    ["Que désignent les noms en Val- ou -val ?", ["Une vallée", "Une hauteur", "Un cours d'eau", "Un chemin encaissé"], 0,
     "Combe, comble et coumbe désignent également des vallons dans différentes régions."],
    ["Pourquoi de nombreuses communes ont-elles changé de nom au XIXe siècle ?", ["Pour éviter les homonymies dans l'administration postale", "Par décision révolutionnaire", "Pour franciser des noms régionaux", "Par volonté des habitants"], 0,
     "D'où les nombreux noms composés, ajoutant une rivière ou une caractéristique locale.", 3],
  ]),

  notion("lf2-langue-medias", S, "La langue des médias",
    "Titres, angles, formules : comment l'information est mise en mots.",
    "Le choix des mots dans un titre oriente la lecture avant même l'article.",
    2, [
    ["Qu'est-ce qu'un titre incitatif dans la presse ?", ["Un titre suscitant la curiosité sans livrer l'information", "Un titre résumant l'article", "Un titre polémique", "Un titre publicitaire"], 0,
     "Le titre informatif, à l'inverse, délivre l'essentiel dès la lecture."],
    ["Qu'est-ce qu'un chapô ?", ["Un court texte introductif placé sous le titre", "Le premier paragraphe de l'article", "Le résumé de fin d'article", "Le titre secondaire"], 0,
     "Il résume l'information et donne envie de lire la suite."],
    ["Qu'est-ce qu'une accroche journalistique ?", ["La première phrase de l'article, destinée à retenir le lecteur", "Le titre principal", "L'intertitre", "La légende de photo"], 0,
     "On l'appelle aussi attaque : elle conditionne largement la poursuite de la lecture."],
    ["Qu'est-ce qu'un angle en journalisme ?", ["Le point de vue choisi pour traiter un sujet", "L'orientation politique du média", "La longueur de l'article", "Le format retenu"], 0,
     "Un même sujet peut donner lieu à des dizaines d'angles différents, tous légitimes."],
    ["Qu'est-ce qu'une brève ?", ["Un article très court donnant l'essentiel d'une information", "Un résumé d'article", "Une dépêche d'agence", "Un encadré explicatif"], 0,
     "Quelques lignes qui doivent contenir l'essentiel des réponses aux questions de base."],
    ["Qu'est-ce qu'un encadré dans un article ?", ["Un texte complémentaire séparé du corps de l'article", "Une citation mise en valeur", "Un intertitre", "Une légende développée"], 0,
     "Il permet de traiter un aspect technique sans alourdir le récit principal."],
    ["Qu'est-ce qu'une accroche visuelle en une ?", ["Un élément graphique attirant l'œil sur un sujet", "La photographie principale", "Le titre principal", "Le bandeau publicitaire"], 0,
     "La hiérarchie de la une traduit la hiérarchie éditoriale de l'information."],
    ["Qu'est-ce que le langage euphémisé dans l'information ?", ["Des formules atténuant la réalité décrite", "Un vocabulaire technique", "Un style neutre", "Un registre soutenu"], 0,
     "Plan social pour licenciements collectifs en est un exemple souvent commenté."],
    ["Qu'est-ce qu'un élément de langage ?", ["Une formule préparée et répétée par les communicants", "Une expression courante", "Un terme technique", "Une citation officielle"], 0,
     "Leur repérage est un exercice classique d'analyse critique du discours médiatique."],
    ["Pourquoi les journalistes emploient-ils le conditionnel dans certains cas ?", ["Pour signaler une information non confirmée", "Pour atténuer une critique", "Pour marquer une hypothèse personnelle", "Par convention stylistique"], 0,
     "Son usage engage néanmoins la responsabilité du média : il ne dispense pas de vérifier.", 3],
  ]),

  notion("lf2-litteracie", S, "Lire, comprendre, résumer",
    "Compétences de lecture et de compréhension écrite.",
    "Comprendre un texte suppose de mobiliser des connaissances qui n'y figurent pas.",
    2, [
    ["Qu'est-ce que la compréhension en lecture ?", ["La construction d'une représentation mentale du contenu", "Le déchiffrage des mots", "La mémorisation du texte", "La reconnaissance du vocabulaire"], 0,
     "Elle mobilise des connaissances préalables que le texte suppose sans les énoncer."],
    ["Qu'est-ce qu'une inférence en lecture ?", ["Une information déduite sans être écrite explicitement", "Une interprétation subjective", "Un résumé mental", "Une hypothèse de lecture"], 0,
     "Les textes littéraires en exigent souvent davantage que les textes documentaires."],
    ["Qu'est-ce que la fluence en lecture ?", ["La capacité à lire avec exactitude, vitesse et expression", "La vitesse de lecture seule", "La lecture à voix haute", "La compréhension immédiate"], 0,
     "Une fluence insuffisante mobilise toute l'attention sur le décodage, au détriment du sens."],
    ["Qu'est-ce qu'un connecteur logique ?", ["Un mot reliant des idées en indiquant leur relation", "Une conjonction de coordination", "Un mot de liaison stylistique", "Une transition de paragraphe"], 0,
     "Donc, cependant, en effet, or : leur repérage est essentiel à la compréhension d'un raisonnement."],
    ["Qu'est-ce qu'un texte argumentatif ?", ["Un texte visant à convaincre par des raisons", "Un texte polémique", "Un essai", "Un texte d'opinion"], 0,
     "Il se caractérise par une thèse, des arguments et souvent la réfutation d'objections."],
    ["Qu'est-ce qu'un plan de texte ?", ["L'organisation logique de ses parties", "La table des matières", "Le résumé des paragraphes", "La structure typographique"], 0,
     "Le repérer facilite considérablement la mémorisation et la restitution."],
    ["Qu'est-ce qu'un résumé ?", ["Une réduction du texte respectant son organisation et son point de vue", "Une sélection des passages importants", "Une reformulation libre", "Un commentaire abrégé"], 0,
     "Il ne doit pas introduire de jugement ni modifier l'ordre du raisonnement."],
    ["Qu'est-ce qu'une synthèse de documents ?", ["Une confrontation organisée de plusieurs textes sur un même sujet", "Un résumé de chaque document", "Un commentaire comparatif", "Une compilation de citations"], 0,
     "Elle exige de dégager des axes transversaux plutôt que de traiter les documents l'un après l'autre."],
    ["Qu'est-ce que la lecture sélective ?", ["Une lecture ciblée cherchant une information précise", "Une lecture rapide", "Une lecture partielle", "Une lecture en diagonale"], 0,
     "Elle est différente de la lecture intégrale et suppose de savoir où chercher."],
    ["Pourquoi la lecture sur écran diffère-t-elle de la lecture sur papier ?", ["Elle favorise le survol et fragmente davantage l'attention", "Elle est plus rapide", "Elle améliore la mémorisation", "Elle n'a aucun effet mesuré"], 0,
     "Les résultats varient selon la longueur et la difficulté du texte, mais l'écart existe pour les textes longs.", 3],
  ]),
];
