/**
 * Littérature, deuxième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Littérature";

export const CG_LITTERATURE_2: SeedSkill[] = [
  notion("li2-litterature-medievale", S, "La littérature du Moyen Âge",
    "Chansons de geste, romans courtois, fabliaux : mille ans de textes en langue vulgaire.",
    "La littérature médiévale française commence en langue d'oïl bien avant que le français ne soit fixé.",
    2, [
    ["Quelle est la plus ancienne chanson de geste française conservée ?", ["La Chanson de Roland", "Le Roman de Renart", "Le Couronnement de Louis", "Raoul de Cambrai"], 0,
     "Composée vers 1100, elle transfigure un épisode militaire de 778 en combat contre les Sarrasins."],
    ["Qu'est-ce qu'une chanson de geste ?", ["Un poème épique chanté racontant les exploits de héros guerriers", "Un poème d'amour courtois", "Un récit satirique", "Une pièce de théâtre religieuse"], 0,
     "Elles se regroupent en cycles autour de Charlemagne, de Guillaume d'Orange ou de Doon de Mayence."],
    ["Quel auteur du XIIe siècle écrit plusieurs romans arthuriens ?", ["Chrétien de Troyes", "Marie de France", "Béroul", "Wace"], 0,
     "Lancelot, Yvain, Perceval : il fixe pour des siècles la matière de Bretagne."],
    ["Quelle poétesse du XIIe siècle écrit des Lais ?", ["Marie de France", "Christine de Pizan", "Louise Labé", "Béatrice de Die"], 0,
     "Première femme de lettres connue en langue française, elle composa aussi des fables."],
    ["Qu'est-ce que l'amour courtois ?", ["Un code amoureux plaçant la dame en position de suzeraine", "Un mariage arrangé entre nobles", "Un amour réservé à la cour royale", "Une forme de poésie religieuse"], 0,
     "Le service d'amour reprend le vocabulaire de la vassalité féodale."],
    ["Quel long poème allégorique du XIIIe siècle connut un immense succès ?", ["Le Roman de la Rose", "Le Roman de Renart", "Le Roman de Thèbes", "Le Roman d'Alexandre"], 0,
     "Commencé par Guillaume de Lorris, poursuivi par Jean de Meung dans un esprit tout différent."],
    ["Qu'est-ce qu'un fabliau ?", ["Un récit bref, comique et souvent grivois", "Une fable animalière morale", "Un poème lyrique", "Un conte merveilleux"], 0,
     "Ils mettent volontiers en scène des marchands, des clercs et des paysans rusés."],
    ["Quelle femme de lettres du XIVe siècle vécut de sa plume ?", ["Christine de Pizan", "Marie de France", "Louise Labé", "Marguerite de Navarre"], 0,
     "Veuve à vingt-cinq ans, elle écrivit pour subvenir aux besoins de sa famille et défendit les femmes contre la misogynie savante."],
    ["Quel poète du XVe siècle passa vingt-cinq ans en captivité en Angleterre ?", ["Charles d'Orléans", "François Villon", "Alain Chartier", "Eustache Deschamps"], 0,
     "Il y composa une œuvre lyrique raffinée, dans une langue d'une remarquable clarté."],
    ["Qu'est-ce qu'un mystère au théâtre médiéval ?", ["Une vaste pièce religieuse jouée en plein air sur plusieurs jours", "Une farce courte", "Un débat allégorique", "Un office liturgique chanté"], 0,
     "Le Mystère de la Passion pouvait mobiliser des centaines d'acteurs devant des milliers de spectateurs.", 3],
  ]),

  notion("li2-moliere", S, "Molière",
    "Trente ans de théâtre, du tréteau de province à la cour, et une comédie devenue critique sociale.",
    "Molière est mort en jouant, mais pas sur scène : quelques heures après la représentation.",
    2, [
    ["Quelle charge Molière abandonne-t-il pour se consacrer au théâtre ?", ["Celle de tapissier du roi, héritée de son père", "Une charge de magistrat", "Une charge de médecin", "Une charge de percepteur"], 0,
     "Il fonde l'Illustre-Théâtre à vingt et un ans ; la troupe fait faillite en deux ans et il est emprisonné pour dettes."],
    ["Quelle pièce de Molière fut interdite pendant cinq ans ?", ["Tartuffe", "Dom Juan", "Le Misanthrope", "L'Avare"], 0,
     "Le parti dévot obtint son interdiction dès 1664 ; elle ne fut jouée librement qu'en 1669."],
    ["Quel personnage de Molière est un séducteur impie puni par une statue ?", ["Dom Juan", "Tartuffe", "Alceste", "Harpagon"], 0,
     "La pièce fut retirée de l'affiche après quinze représentations en 1665."],
    ["Quel personnage de Molière est un misanthrope amoureux d'une coquette ?", ["Alceste", "Orgon", "Argan", "Sganarelle"], 0,
     "Le Misanthrope, en 1666, est souvent tenu pour sa comédie la plus grave."],
    ["Quel personnage de Molière est un avare obsédé par sa cassette ?", ["Harpagon", "Argan", "Orgon", "Jourdain"], 0,
     "La pièce est en prose, ce qui fut jugé étrange pour une grande comédie à sa création."],
    ["Quel bourgeois de Molière veut devenir gentilhomme ?", ["Monsieur Jourdain", "Harpagon", "Argan", "Chrysale"], 0,
     "Il découvre avec émerveillement qu'il fait de la prose sans le savoir."],
    ["Quelle pièce Molière jouait-il le soir de sa mort en 1673 ?", ["Le Malade imaginaire", "Les Femmes savantes", "Tartuffe", "Le Misanthrope"], 0,
     "Il tenait le rôle d'Argan, hypocondriaque. Il mourut quelques heures après la représentation."],
    ["Qu'est-ce qu'une comédie-ballet ?", ["Une pièce mêlant texte parlé, musique et danse", "Un ballet sans paroles", "Une comédie musicale moderne", "Une pièce chantée intégralement"], 0,
     "Molière en écrivit plusieurs avec Lully, dont Le Bourgeois gentilhomme."],
    ["Quelle est la règle des trois unités que Molière respecte inégalement ?", ["Unité de temps, de lieu et d'action", "Unité de ton, de style et de genre", "Unité de personnages, de décor et de langue", "Unité de rythme, de vers et de rime"], 0,
     "Il s'en écarte plus librement que les auteurs de tragédie, notamment dans Dom Juan."],
    ["Qui composa la musique de plusieurs pièces de Molière avant de se brouiller avec lui ?", ["Jean-Baptiste Lully", "Marc-Antoine Charpentier", "Robert Cambert", "Michel Lambert"], 0,
     "Charpentier prit le relais après leur rupture, notamment pour Le Malade imaginaire.", 3],
  ]),

  notion("li2-racine-corneille", S, "Racine et Corneille",
    "Deux conceptions de la tragédie, une génération d'écart, une rivalité fondatrice.",
    "Chez Corneille le héros choisit son destin ; chez Racine la passion le détruit.",
    2, [
    ["Quelle pièce de Corneille déclenche une querelle littéraire en 1637 ?", ["Le Cid", "Horace", "Cinna", "Polyeucte"], 0,
     "L'Académie française fut saisie et reprocha à la pièce d'enfreindre les règles et la vraisemblance."],
    ["Quel dilemme structure Le Cid de Corneille ?", ["Choisir entre l'amour et l'honneur familial", "Choisir entre le pouvoir et la religion", "Choisir entre deux femmes", "Choisir entre la vie et la mort"], 0,
     "Rodrigue doit venger son père en tuant celui de Chimène, qu'il aime."],
    ["Quelle tragédie de Corneille met en scène trois frères contre trois frères ?", ["Horace", "Cinna", "Le Cid", "Nicomède"], 0,
     "Le combat des Horaces et des Curiaces, emprunté à l'histoire romaine légendaire."],
    ["Quel thème domine Cinna de Corneille ?", ["La clémence du souverain", "La vengeance familiale", "Le martyre religieux", "L'amour impossible"], 0,
     "Auguste pardonne à un conspirateur, geste qui fonde sa légitimité mieux que la répression."],
    ["Quelle tragédie de Racine met en scène une reine amoureuse du fiancé de sa fille ?", ["Phèdre", "Andromaque", "Bérénice", "Britannicus"], 0,
     "Phèdre aime son beau-fils Hippolyte. La pièce de 1677 est souvent tenue pour son chef-d'œuvre."],
    ["Quelle tragédie de Racine repose sur une chaîne d'amours non réciproques ?", ["Andromaque", "Phèdre", "Athalie", "Esther"], 0,
     "Oreste aime Hermione qui aime Pyrrhus qui aime Andromaque, fidèle à un mort."],
    ["Quelle pièce de Racine se résume à une séparation sans mort ?", ["Bérénice", "Phèdre", "Andromaque", "Mithridate"], 0,
     "Racine revendique dans sa préface qu'une tragédie n'a pas besoin de sang pour être tragique."],
    ["Quel dramaturge écrit deux tragédies bibliques pour Saint-Cyr après s'être retiré ?", ["Racine", "Corneille", "Quinault", "Rotrou"], 0,
     "Esther et Athalie, écrites à la demande de Madame de Maintenon pour ses pensionnaires."],
    ["Quelle différence essentielle sépare le héros cornélien du héros racinien ?", ["Le premier maîtrise sa volonté, le second est emporté par la passion", "Le premier est noble, le second bourgeois", "Le premier meurt toujours, le second survit", "Le premier parle en prose, le second en vers"], 0,
     "Cette opposition, forgée par la critique du XIXe siècle, simplifie des œuvres plus nuancées."],
    ["Quel courant religieux marqua la formation de Racine ?", ["Le jansénisme, à Port-Royal", "Le jésuitisme", "Le quiétisme", "Le protestantisme"], 0,
     "L'idée d'une nature humaine impuissante face à ses penchants traverse son théâtre.", 3],
  ]),

  notion("li2-conte-philosophique", S, "Le conte philosophique",
    "Un genre du XVIIIe siècle : une fiction brève au service d'une démonstration.",
    "Le conte philosophique déguise l'argumentation en récit pour échapper à la censure.",
    2, [
    ["Quelle est la caractéristique du conte philosophique ?", ["Un récit bref mettant une thèse à l'épreuve d'une fiction", "Un conte merveilleux moralisé", "Une fable en vers", "Un essai déguisé en dialogue"], 0,
     "Le détour par la fiction permettait aussi de contourner la censure royale."],
    ["Contre quelle doctrine Candide est-il dirigé ?", ["L'optimisme selon lequel tout est pour le mieux", "Le matérialisme", "Le scepticisme", "Le jansénisme"], 0,
     "Voltaire vise la formule leibnizienne du meilleur des mondes possibles, incarnée par Pangloss."],
    ["Sur quelle formule Candide s'achève-t-il ?", ["Il faut cultiver notre jardin", "Tout est pour le mieux", "Écrasons l'infâme", "Le mieux est l'ennemi du bien"], 0,
     "Interprétée soit comme un repli, soit comme un appel à l'action concrète et modeste."],
    ["Quel conte de Voltaire met en scène des géants venus de Sirius ?", ["Micromégas", "Zadig", "L'Ingénu", "Jeannot et Colin"], 0,
     "Le changement d'échelle sert à relativiser l'importance que l'homme s'accorde."],
    ["Quel conte de Voltaire suit les épreuves d'un sage babylonien ?", ["Zadig", "Candide", "Micromégas", "La Princesse de Babylone"], 0,
     "Sous-titré La Destinée, il interroge la providence et le hasard."],
    ["Quel conte de Voltaire met en scène un Huron arrivant en France ?", ["L'Ingénu", "Zadig", "Candide", "Micromégas"], 0,
     "Le regard extérieur du personnage sert à dénoncer les absurdités des institutions françaises."],
    ["Quel roman épistolaire de Montesquieu utilise un procédé comparable ?", ["Les Lettres persanes", "Le Temple de Gnide", "Les Considérations", "Le Dialogue de Sylla"], 0,
     "Deux Persans découvrant Paris en 1721 permettent une satire décapante de la société française."],
    ["Quel dialogue de Diderot met en scène un neveu cynique face à un philosophe ?", ["Le Neveu de Rameau", "Jacques le Fataliste", "La Religieuse", "Le Rêve de d'Alembert"], 0,
     "Écrit sur des années, il ne fut publié en français qu'au XIXe siècle."],
    ["Quel roman de Diderot joue avec les conventions du récit ?", ["Jacques le Fataliste", "La Religieuse", "Le Neveu de Rameau", "Les Bijoux indiscrets"], 0,
     "Le narrateur interrompt sans cesse son histoire pour discuter avec le lecteur."],
    ["Quel roman de Diderot dénonce les vocations religieuses forcées ?", ["La Religieuse", "Jacques le Fataliste", "Le Neveu de Rameau", "Le Rêve de d'Alembert"], 0,
     "Né d'une mystification épistolaire entre amis, il devint un réquisitoire contre l'enfermement conventuel.", 3],
  ]),

  notion("li2-hugo", S, "Victor Hugo",
    "Poète, dramaturge, romancier et figure politique : soixante ans de production.",
    "Hugo a passé près de vingt ans en exil, période où il écrit certaines de ses œuvres majeures.",
    2, [
    ["Dans quelle préface Hugo formule-t-il le programme du drame romantique ?", ["La préface de Cromwell", "La préface d'Hernani", "La préface des Contemplations", "La préface de Ruy Blas"], 0,
     "Publiée en 1827, elle appelle à mêler le sublime et le grotesque contre les règles classiques."],
    ["Quel roman de Hugo se déroule autour d'une cathédrale parisienne ?", ["Notre-Dame de Paris", "Les Misérables", "Les Travailleurs de la mer", "L'Homme qui rit"], 0,
     "Publié en 1831, il contribua à sauver l'édifice, alors en état de délabrement avancé."],
    ["Quel personnage des Misérables est un ancien bagnard poursuivi par un policier ?", ["Jean Valjean", "Marius", "Gavroche", "Thénardier"], 0,
     "Javert incarne une conception de la loi incapable d'admettre la rédemption."],
    ["Quel recueil poétique Hugo publie-t-il en 1856 autour du deuil de sa fille ?", ["Les Contemplations", "Les Châtiments", "La Légende des siècles", "Les Orientales"], 0,
     "Il le divise en deux parties, Autrefois et Aujourd'hui, séparées par la mort de Léopoldine."],
    ["Contre qui Les Châtiments sont-ils dirigés en 1853 ?", ["Napoléon III", "Charles X", "Louis-Philippe", "Thiers"], 0,
     "Écrit en exil, le recueil circulait clandestinement en France."],
    ["Où Hugo passe-t-il l'essentiel de son exil ?", ["À Jersey puis Guernesey", "En Belgique", "En Angleterre continentale", "En Suisse"], 0,
     "Il refusa l'amnistie de 1859 : il ne rentra qu'après la chute de l'Empire en 1870."],
    ["Quel combat politique Hugo mène-t-il toute sa vie ?", ["L'abolition de la peine de mort", "Le suffrage censitaire", "Le protectionnisme", "La restauration monarchique"], 0,
     "Le Dernier Jour d'un condamné, publié en 1829, en est le manifeste romanesque."],
    ["Quelle vaste fresque poétique Hugo consacre-t-il à l'humanité ?", ["La Légende des siècles", "Les Contemplations", "Les Rayons et les Ombres", "Les Voix intérieures"], 0,
     "Une succession de tableaux censés retracer la marche du genre humain de la Genèse à l'avenir."],
    ["Quel drame de Hugo met en scène un valet amoureux d'une reine ?", ["Ruy Blas", "Hernani", "Lucrèce Borgia", "Marion Delorme"], 0,
     "Créé en 1838, il illustre le mélange des conditions cher au drame romantique."],
    ["Combien de personnes suivirent les funérailles de Hugo en 1885 ?", ["Environ deux millions", "Environ cinquante mille", "Environ cinq cent mille", "Environ dix mille"], 0,
     "Funérailles nationales, avec transfert au Panthéon. La foule fut sans précédent pour un écrivain.", 3],
  ]),

  notion("li2-balzac-realisme", S, "Balzac et le roman réaliste",
    "Décrire une société entière : le projet romanesque du XIXe siècle.",
    "Balzac a inventé le retour des personnages d'un roman à l'autre, procédé repris par tout le roman moderne.",
    2, [
    ["Quel procédé Balzac invente-t-il pour relier ses romans ?", ["Le retour des mêmes personnages d'un livre à l'autre", "La narration à plusieurs voix", "Le récit enchâssé", "Le monologue intérieur"], 0,
     "Plus de deux mille personnages circulent ainsi dans La Comédie humaine."],
    ["Quel roman de Balzac met en scène un père sacrifié par ses filles ?", ["Le Père Goriot", "Eugénie Grandet", "Illusions perdues", "La Peau de chagrin"], 0,
     "Publié en 1835, il introduit aussi le personnage de Rastignac, arriviste devenu emblématique."],
    ["Quel personnage de Balzac lance un défi à Paris depuis le Père-Lachaise ?", ["Rastignac", "Lucien de Rubempré", "Vautrin", "Raphaël de Valentin"], 0,
     "La formule exacte, souvent citée de mémoire, est « À nous deux maintenant ! »."],
    ["Quel roman de Balzac raconte l'échec d'un jeune provincial monté à Paris ?", ["Illusions perdues", "Le Père Goriot", "Le Lys dans la vallée", "César Birotteau"], 0,
     "Le monde du journalisme et de l'édition y est décrit avec une précision documentaire."],
    ["Quel roman de Balzac met en scène une héritière de province et son père avare ?", ["Eugénie Grandet", "Le Père Goriot", "La Cousine Bette", "Ursule Mirouët"], 0,
     "L'argent y est le véritable moteur des relations familiales."],
    ["Quel roman fantastique de Balzac associe désir et durée de vie ?", ["La Peau de chagrin", "Séraphîta", "Louis Lambert", "L'Élixir de longue vie"], 0,
     "Chaque souhait exaucé rétrécit la peau et raccourcit l'existence de son possesseur."],
    ["Quel roman de Flaubert met en scène une femme lassée de la vie provinciale ?", ["Madame Bovary", "L'Éducation sentimentale", "Salammbô", "Trois Contes"], 0,
     "Le bovarysme désigne depuis l'insatisfaction née de l'écart entre les rêves et la réalité."],
    ["Quel principe d'écriture Flaubert défendait-il ?", ["L'impersonnalité et le travail acharné du style", "L'inspiration spontanée", "L'engagement politique du romancier", "La primauté de l'intrigue"], 0,
     "Il écrivait parfois moins d'une page par jour, cherchant le mot juste."],
    ["Quel écrivain publie Boule de Suif en 1880 ?", ["Guy de Maupassant", "Émile Zola", "Alphonse Daudet", "Joris-Karl Huysmans"], 0,
     "La nouvelle parut dans un recueil collectif rassemblé par Zola sur la guerre de 1870."],
    ["Quel roman de Stendhal suit l'ascension d'un fils de charpentier ?", ["Le Rouge et le Noir", "La Chartreuse de Parme", "Armance", "Lucien Leuwen"], 0,
     "Sous-titré Chronique de 1830, il analyse l'hypocrisie sociale de la Restauration.", 3],
  ]),

  notion("li2-zola-naturalisme", S, "Zola et le naturalisme",
    "Un projet scientifique appliqué au roman, et vingt volumes pour l'éprouver.",
    "Zola menait de véritables enquêtes de terrain avant d'écrire chaque roman.",
    2, [
    ["Combien de romans compte le cycle des Rougon-Macquart ?", ["Vingt", "Dix", "Trente", "Quinze"], 0,
     "Publiés de 1871 à 1893, ils suivent cinq générations d'une même famille."],
    ["Quel roman de Zola est consacré au monde de la mine ?", ["Germinal", "L'Assommoir", "La Bête humaine", "La Terre"], 0,
     "Zola descendit lui-même dans une fosse d'Anzin pour le documenter."],
    ["Quel roman de Zola décrit la déchéance d'une blanchisseuse par l'alcool ?", ["L'Assommoir", "Nana", "Germinal", "Pot-Bouille"], 0,
     "Son succès en 1877 fit la fortune de Zola et provoqua un scandale par sa langue populaire."],
    ["Quel roman de Zola met en scène l'essor des grands magasins ?", ["Au Bonheur des Dames", "Pot-Bouille", "L'Argent", "La Curée"], 0,
     "Il y analyse la naissance de la consommation moderne et la ruine du petit commerce."],
    ["Quel roman de Zola se déroule dans le monde des chemins de fer ?", ["La Bête humaine", "Germinal", "L'Œuvre", "Le Ventre de Paris"], 0,
     "La locomotive y devient un personnage à part entière."],
    ["Quel roman de Zola décrit les Halles de Paris ?", ["Le Ventre de Paris", "Au Bonheur des Dames", "La Curée", "Pot-Bouille"], 0,
     "Il oppose les Gras et les Maigres dans une allégorie sociale de la société impériale."],
    ["Quel essai de Zola théorise le naturalisme en 1880 ?", ["Le Roman expérimental", "Mes haines", "Documents littéraires", "Une campagne"], 0,
     "Il s'appuie sur la méthode expérimentale de Claude Bernard, transposée à la fiction."],
    ["Quelle place l'hérédité tient-elle dans le projet des Rougon-Macquart ?", ["Elle explique en partie les destins des personnages", "Elle est écartée au profit du milieu", "Elle est purement métaphorique", "Elle n'apparaît que dans le dernier tome"], 0,
     "Zola s'appuyait sur des théories médicales de son temps, aujourd'hui largement obsolètes."],
    ["Quel recueil de nouvelles collectif marque l'acte de naissance du groupe naturaliste ?", ["Les Soirées de Médan", "Les Six Contes", "Le Manifeste des Cinq", "Les Nuits de Paris"], 0,
     "Publié en 1880, il réunit Zola, Maupassant, Huysmans et trois autres auteurs."],
    ["Quel roman de Huysmans marque une rupture avec le naturalisme en 1884 ?", ["À rebours", "Là-bas", "En route", "Marthe"], 0,
     "Son esthète reclus incarne la fin de non-recevoir opposée à la description du réel ordinaire.", 3],
  ]),

  notion("li2-proust", S, "Proust et la Recherche",
    "Sept volumes, une théorie de la mémoire et une refonte de la forme romanesque.",
    "La Recherche n'est pas un récit chronologique : elle suit le mouvement de la mémoire.",
    2, [
    ["Combien de volumes compte À la recherche du temps perdu ?", ["Sept", "Cinq", "Dix", "Trois"], 0,
     "Les trois derniers ont été publiés après la mort de Proust, à partir de manuscrits inachevés."],
    ["Quel est le premier volume de la Recherche ?", ["Du côté de chez Swann", "À l'ombre des jeunes filles en fleurs", "Le Côté de Guermantes", "Le Temps retrouvé"], 0,
     "Publié à compte d'auteur en 1913 après plusieurs refus d'éditeurs."],
    ["Quel volume de la Recherche obtient le prix Goncourt en 1919 ?", ["À l'ombre des jeunes filles en fleurs", "Du côté de chez Swann", "Sodome et Gomorrhe", "La Prisonnière"], 0,
     "Le choix fut contesté : on lui reprochait d'écrire un livre de riche pour les riches."],
    ["Quel épisode célèbre déclenche la mémoire involontaire ?", ["La madeleine trempée dans le thé", "La sonate de Vinteuil", "Les pavés inégaux", "La serviette empesée"], 0,
     "D'autres réminiscences du même type reviennent dans le dernier volume et fondent la vocation du narrateur."],
    ["Qu'est-ce que la mémoire involontaire chez Proust ?", ["Un souvenir ressuscité par une sensation, hors de tout effort", "Un souvenir travaillé par la réflexion", "L'oubli progressif du passé", "Un souvenir transmis par autrui"], 0,
     "Elle s'oppose à la mémoire volontaire, qui ne restitue selon lui qu'un savoir sec sur le passé."],
    ["Quelle œuvre musicale fictive traverse la Recherche ?", ["La sonate de Vinteuil", "Le quatuor de Berma", "La symphonie d'Elstir", "La cantate de Bergotte"], 0,
     "Sa petite phrase devient l'hymne de l'amour de Swann pour Odette."],
    ["Quel peintre fictif de la Recherche incarne l'art de voir autrement ?", ["Elstir", "Bergotte", "Vinteuil", "Berma"], 0,
     "Bergotte est l'écrivain, Berma l'actrice, Vinteuil le compositeur."],
    ["Quelle affaire politique traverse la Recherche ?", ["L'affaire Dreyfus", "L'affaire Panama", "L'affaire Stavisky", "L'affaire Boulanger"], 0,
     "Elle sert de révélateur des positions sociales et des reniements dans les salons."],
    ["Comment Proust travaillait-il ses manuscrits ?", ["En ajoutant sans cesse des feuillets collés, les paperoles", "En dictant à un secrétaire", "En réécrivant chaque version intégralement", "En composant directement à la machine"], 0,
     "Certaines pages atteignent plusieurs mètres une fois dépliées."],
    ["Sur quelle idée le dernier volume de la Recherche s'achève-t-il ?", ["La décision d'écrire l'œuvre que le lecteur vient de lire", "Le renoncement du narrateur", "La mort du narrateur", "Le départ pour un voyage"], 0,
     "La boucle ainsi refermée fait du livre le récit de sa propre genèse.", 3],
  ]),

  notion("li2-existentialisme", S, "Existentialisme et littérature engagée",
    "Sartre, Beauvoir, Camus : la littérature comme prise de position.",
    "Camus a toujours refusé l'étiquette d'existentialiste que la presse lui accolait.",
    2, [
    ["Quelle formule résume l'existentialisme sartrien ?", ["L'existence précède l'essence", "Je pense donc je suis", "L'homme est un loup pour l'homme", "Tout est pour le mieux"], 0,
     "L'homme n'a pas de nature donnée : il se définit par ses actes."],
    ["Quel roman de Sartre paraît en 1938 ?", ["La Nausée", "Les Chemins de la liberté", "Le Mur", "Les Mots"], 0,
     "Le personnage y éprouve la contingence brute de l'existence face à une racine de marronnier."],
    ["Quelle pièce de Sartre contient la formule sur l'enfer et les autres ?", ["Huis clos", "Les Mouches", "Les Mains sales", "Le Diable et le Bon Dieu"], 0,
     "Trois personnages enfermés ensemble découvrent qu'aucun bourreau n'est nécessaire."],
    ["Quel essai de Simone de Beauvoir paraît en 1949 ?", ["Le Deuxième Sexe", "Les Mandarins", "Mémoires d'une jeune fille rangée", "La Force de l'âge"], 0,
     "On ne naît pas femme, on le devient : la formule fonde une part de la pensée féministe contemporaine."],
    ["Quel roman de Simone de Beauvoir obtient le Goncourt en 1954 ?", ["Les Mandarins", "L'Invitée", "Le Sang des autres", "Une mort très douce"], 0,
     "Il met en scène le milieu intellectuel français de l'après-guerre."],
    ["Quel essai de Camus paraît en 1942 sur l'absurde ?", ["Le Mythe de Sisyphe", "L'Homme révolté", "Noces", "L'Été"], 0,
     "Il s'ouvre sur la question du suicide, tenue pour le seul problème philosophique vraiment sérieux."],
    ["Quel roman de Camus décrit une ville frappée par une épidémie ?", ["La Peste", "L'Étranger", "La Chute", "Le Premier Homme"], 0,
     "Publié en 1947, il fut aussi lu comme une allégorie de l'occupation nazie."],
    ["Quel essai de Camus provoque sa rupture avec Sartre en 1951 ?", ["L'Homme révolté", "Le Mythe de Sisyphe", "Les Justes", "Noces"], 0,
     "Sa critique de la violence révolutionnaire fut jugée inacceptable par la revue de Sartre."],
    ["Quel prix Camus reçoit-il en 1957 ?", ["Le prix Nobel de littérature", "Le prix Goncourt", "Le prix Renaudot", "Le grand prix de l'Académie"], 0,
     "À quarante-quatre ans, il fut l'un des plus jeunes lauréats. Il mourut trois ans plus tard dans un accident."],
    ["Qu'est-ce que la littérature engagée selon Sartre ?", ["Une écriture qui assume sa responsabilité politique", "Une littérature militante de parti", "Un art didactique", "Un genre réservé à l'essai"], 0,
     "Qu'est-ce que la littérature ?, publié en 1948, en développe la théorie.", 3],
  ]),

  notion("li2-science-fiction", S, "La science-fiction",
    "Un genre né au XIXe siècle, ses grands auteurs et ses questions.",
    "La science-fiction parle moins de l'avenir que du présent de ceux qui l'écrivent.",
    2, [
    ["Quel écrivain français du XIXe siècle est un précurseur de la science-fiction ?", ["Jules Verne", "Victor Hugo", "Alexandre Dumas", "Théophile Gautier"], 0,
     "Ses Voyages extraordinaires mêlaient vulgarisation scientifique et aventure."],
    ["Quel écrivain britannique publie La Machine à explorer le temps en 1895 ?", ["H. G. Wells", "Jules Verne", "Arthur Conan Doyle", "Rider Haggard"], 0,
     "Il publie aussi La Guerre des mondes et L'Homme invisible en quelques années."],
    ["Quelles sont les trois lois de la robotique énoncées par Asimov ?", ["Des règles hiérarchisées protégeant l'humain puis le robot", "Trois principes de conception mécanique", "Des lois de la physique des automates", "Des règles de programmation informatique"], 0,
     "Formulées en 1942, elles servent surtout à explorer leurs failles logiques dans ses nouvelles."],
    ["Quel roman de Frank Herbert se déroule sur une planète désertique ?", ["Dune", "Fondation", "Hypérion", "Les Robots"], 0,
     "Écologie, religion et politique y sont étroitement mêlées autour d'une ressource unique."],
    ["Quel roman de Ray Bradbury décrit une société où l'on brûle les livres ?", ["Fahrenheit 451", "Chroniques martiennes", "L'Homme illustré", "La Foire des ténèbres"], 0,
     "Le titre désigne la température supposée d'inflammation du papier."],
    ["Quel roman d'Aldous Huxley décrit une dystopie fondée sur le conditionnement ?", ["Le Meilleur des mondes", "1984", "Nous autres", "La Ferme des animaux"], 0,
     "Publié en 1932, il oppose au régime par la terreur un régime par le plaisir organisé."],
    ["Quel roman russe de 1920 a inspiré les grandes dystopies ultérieures ?", ["Nous autres, de Zamiatine", "Le Maître et Marguerite", "Le Docteur Jivago", "Moscou-sur-Vodka"], 0,
     "Interdit en URSS, il circula à l'étranger et influença Orwell et Huxley."],
    ["Quel écrivain américain explore la réalité et l'identité dans Ubik et Blade Runner ?", ["Philip K. Dick", "Robert Heinlein", "Ursula Le Guin", "Alfred Bester"], 0,
     "Le film Blade Runner adapte son roman Les androïdes rêvent-ils de moutons électriques ?"],
    ["Quelle écrivaine explore le genre et l'anthropologie dans La Main gauche de la nuit ?", ["Ursula Le Guin", "Octavia Butler", "Joanna Russ", "Connie Willis"], 0,
     "Son peuple imaginaire est androgyne, ce qui permet d'interroger nos catégories de genre."],
    ["Qu'est-ce que le cyberpunk ?", ["Un courant mêlant haute technologie et déliquescence sociale", "Une science-fiction spatiale classique", "Un genre postapocalyptique", "Une science-fiction humoristique"], 0,
     "Neuromancien, de William Gibson, publié en 1984, en est le texte fondateur.", 3],
  ]),

  notion("li2-policier", S, "Le roman policier",
    "Énigme, roman noir, thriller : un genre populaire aux formes multiples.",
    "Le roman policier naît avec une nouvelle d'Edgar Poe en 1841.",
    2, [
    ["Quelle nouvelle de 1841 est considérée comme le premier récit policier ?", ["Double assassinat dans la rue Morgue", "Le Chien des Baskerville", "Le Mystère de la chambre jaune", "L'Affaire Lerouge"], 0,
     "Edgar Allan Poe y crée le détective Dupin, modèle de tous les enquêteurs déductifs."],
    ["Qui crée le personnage de Sherlock Holmes ?", ["Arthur Conan Doyle", "Edgar Allan Poe", "Wilkie Collins", "G. K. Chesterton"], 0,
     "Il tenta de le faire mourir en 1893, mais dut le ressusciter sous la pression des lecteurs."],
    ["Quelle romancière britannique crée Hercule Poirot et Miss Marple ?", ["Agatha Christie", "Dorothy Sayers", "P. D. James", "Ruth Rendell"], 0,
     "Elle est l'autrice de fiction la plus vendue de tous les temps."],
    ["Quel roman d'Agatha Christie repose sur un narrateur inattendu ?", ["Le Meurtre de Roger Ackroyd", "Dix Petits Nègres", "Le Crime de l'Orient-Express", "Mort sur le Nil"], 0,
     "Sa parution en 1926 fit scandale : certains l'accusèrent de tricher avec le lecteur."],
    ["Qu'est-ce que le roman à énigme ?", ["Un récit centré sur la résolution intellectuelle d'un crime", "Un récit d'ambiance criminelle", "Un roman d'espionnage", "Un thriller psychologique"], 0,
     "Le lecteur est censé disposer des mêmes indices que l'enquêteur."],
    ["Qu'est-ce que le roman noir américain ?", ["Un genre décrivant la corruption sociale à travers le crime", "Un roman policier historique", "Un roman d'horreur", "Un récit d'espionnage"], 0,
     "Hammett et Chandler en sont les fondateurs dans les années 1920 et 1930."],
    ["Quel personnage de détective Raymond Chandler crée-t-il ?", ["Philip Marlowe", "Sam Spade", "Nero Wolfe", "Lew Archer"], 0,
     "Sam Spade est le personnage de Dashiell Hammett dans Le Faucon maltais."],
    ["Quel commissaire Georges Simenon crée-t-il ?", ["Maigret", "Lecoq", "Rouletabille", "San-Antonio"], 0,
     "Il lui consacre soixante-quinze romans, centrés sur la psychologie plus que sur la déduction."],
    ["Quelle collection française lancée en 1945 popularise le roman noir ?", ["La Série noire", "Le Masque", "Le Fleuve noir", "Le Poulpe"], 0,
     "Son nom, dû à Marcel Duhamel, a donné son adjectif au genre en français."],
    ["Qu'est-ce que le polar nordique ?", ["Un courant scandinave mêlant enquête et critique sociale", "Un roman policier historique du Nord", "Un genre policier finlandais", "Un thriller polaire"], 0,
     "Sjöwall et Wahlöö en posent les bases dès les années 1960, bien avant son succès international.", 3],
  ]),

  notion("li2-bande-dessinee", S, "La bande dessinée",
    "Un art narratif à part entière, ses écoles et son vocabulaire.",
    "La bande dessinée est parfois appelée le neuvième art depuis les années 1960.",
    2, [
    ["Comment appelle-t-on l'espace entre deux cases de bande dessinée ?", ["Le gouttière", "Le cadre", "La marge", "Le blanc tournant"], 0,
     "C'est là que le lecteur opère mentalement le passage d'une image à l'autre."],
    ["Qu'est-ce qu'une planche en bande dessinée ?", ["Une page complète composée de plusieurs cases", "Une case unique", "Une bande horizontale", "Une couverture illustrée"], 0,
     "Une bande, ou strip, désigne une rangée de cases à l'intérieur de la planche."],
    ["Quel auteur belge crée Tintin en 1929 ?", ["Hergé", "Franquin", "Peyo", "Jacobs"], 0,
     "La ligne claire, son style, se caractérise par un trait d'épaisseur constante et des aplats de couleur."],
    ["Quel auteur crée Gaston Lagaffe ?", ["Franquin", "Hergé", "Morris", "Uderzo"], 0,
     "Il reprit aussi Spirou et créa le Marsupilami."],
    ["Qui sont les créateurs d'Astérix ?", ["Goscinny et Uderzo", "Charlier et Giraud", "Peyo et Delporte", "Morris et Goscinny"], 0,
     "René Goscinny au scénario, Albert Uderzo au dessin, à partir de 1959."],
    ["Quel magazine français a révolutionné la bande dessinée adulte en 1975 ?", ["Métal hurlant", "Pilote", "Spirou", "Tintin"], 0,
     "Fondé par Moebius, Druillet et Dionnet, il influença durablement la science-fiction visuelle mondiale."],
    ["Qu'est-ce qu'un manga ?", ["Une bande dessinée japonaise, lue de droite à gauche", "Un dessin animé japonais", "Un roman graphique asiatique", "Un genre de bande dessinée d'action"], 0,
     "L'anime désigne l'animation. Les mangas se déclinent en catégories selon le public visé."],
    ["Quel auteur japonais est surnommé le dieu du manga ?", ["Osamu Tezuka", "Akira Toriyama", "Katsuhiro Ōtomo", "Naoki Urasawa"], 0,
     "Créateur d'Astro Boy, il a fixé de nombreux codes narratifs du manga d'après-guerre."],
    ["Quelle bande dessinée d'Art Spiegelman a reçu un prix Pulitzer ?", ["Maus", "Persepolis", "Watchmen", "Sandman"], 0,
     "Elle raconte la Shoah en représentant les Juifs en souris et les nazis en chats."],
    ["Quel festival français est le plus important rendez-vous de la bande dessinée ?", ["Le festival d'Angoulême", "Le festival de Blois", "Quai des Bulles", "Le Lyon BD Festival"], 0,
     "Créé en 1974, il décerne notamment le Fauve d'or du meilleur album.", 3],
  ]),

  notion("li2-litterature-antique", S, "La littérature antique",
    "Épopées, tragédies, philosophie : les textes fondateurs de la tradition occidentale.",
    "Les épopées homériques ont d'abord été transmises oralement pendant des siècles.",
    2, [
    ["Quelle épopée raconte la colère d'Achille ?", ["L'Iliade", "L'Odyssée", "L'Énéide", "Les Argonautiques"], 0,
     "Elle ne couvre que quelques semaines de la dixième année du siège de Troie."],
    ["Quelle épopée raconte le retour d'Ulysse ?", ["L'Odyssée", "L'Iliade", "L'Énéide", "La Théogonie"], 0,
     "Dix ans de retour après dix ans de guerre. Le récit commence in medias res, au milieu de l'action."],
    ["Quel poète latin écrit l'Énéide ?", ["Virgile", "Ovide", "Horace", "Lucrèce"], 0,
     "Inachevée à sa mort, il aurait demandé qu'elle soit brûlée. Auguste s'y opposa."],
    ["Quelle œuvre d'Ovide rassemble des récits de transformations ?", ["Les Métamorphoses", "L'Art d'aimer", "Les Tristes", "Les Fastes"], 0,
     "Elle est la principale source de la mythologie gréco-romaine pour les artistes occidentaux."],
    ["Quels sont les trois grands tragiques grecs ?", ["Eschyle, Sophocle et Euripide", "Homère, Hésiode et Pindare", "Aristophane, Ménandre et Plaute", "Platon, Aristote et Socrate"], 0,
     "Sur des centaines de pièces écrites, une trentaine seulement nous sont parvenues."],
    ["Quelle tragédie de Sophocle met en scène un roi enquêtant sur son propre crime ?", ["Œdipe roi", "Antigone", "Électre", "Ajax"], 0,
     "Aristote la donne en exemple de l'enchaînement parfait des péripéties."],
    ["Quelle héroïne de Sophocle défie la loi de la cité au nom de la loi divine ?", ["Antigone", "Électre", "Médée", "Iphigénie"], 0,
     "La pièce a été réécrite et rejouée dans presque tous les contextes de résistance politique."],
    ["Quel auteur grec est le maître de la comédie ancienne ?", ["Aristophane", "Ménandre", "Sophocle", "Euripide"], 0,
     "Ses pièces attaquent nommément des contemporains, dont Socrate dans Les Nuées."],
    ["Quel philosophe grec écrit sous forme de dialogues ?", ["Platon", "Aristote", "Épicure", "Zénon"], 0,
     "Socrate, qui n'a rien écrit, y tient presque toujours le rôle principal."],
    ["Quel traité d'Aristote fonde la réflexion occidentale sur le théâtre ?", ["La Poétique", "La Rhétorique", "L'Éthique à Nicomaque", "La Métaphysique"], 0,
     "La notion de catharsis en est issue, même si son sens exact reste discuté.", 3],
  ]),

  notion("li2-litterature-hispanique", S, "Les littératures de langue espagnole",
    "Siècle d'or, roman moderne, boom latino-américain.",
    "Le premier roman moderne européen est espagnol, et son héros a trop lu de romans de chevalerie.",
    2, [
    ["Quel roman de Cervantès paraît en deux parties en 1605 et 1615 ?", ["Don Quichotte", "Les Nouvelles exemplaires", "La Galatée", "Persilès"], 0,
     "La deuxième partie répond à une suite apocryphe publiée par un rival."],
    ["Qu'est-ce que le Siècle d'or espagnol ?", ["Une période de floraison littéraire et artistique aux XVIe et XVIIe siècles", "Le siècle de la conquête américaine", "L'époque des rois catholiques", "Le règne de Philippe II seul"], 0,
     "Cervantès, Lope de Vega, Calderón, Góngora et Quevedo y appartiennent."],
    ["Quel dramaturge espagnol aurait écrit plusieurs centaines de pièces ?", ["Lope de Vega", "Calderón", "Tirso de Molina", "Cervantès"], 0,
     "Les estimations vont de quatre cents à plus de mille cinq cents œuvres."],
    ["Quelle pièce de Calderón médite sur l'illusion de l'existence ?", ["La vie est un songe", "Le Grand Théâtre du monde", "L'Alcade de Zalamea", "Le Médecin de son honneur"], 0,
     "Un prince enfermé dès sa naissance ne sait plus distinguer le rêve de la réalité."],
    ["Qu'est-ce que le roman picaresque ?", ["Un récit à la première personne suivant un marginal de maître en maître", "Un roman de chevalerie parodique", "Un récit sentimental", "Une chronique historique"], 0,
     "Lazarillo de Tormes, publié en 1554, en est le premier grand exemple."],
    ["Quel poète espagnol est assassiné en 1936 au début de la guerre civile ?", ["Federico García Lorca", "Antonio Machado", "Miguel Hernández", "Rafael Alberti"], 0,
     "Poète et dramaturge, auteur de Noces de sang et de La Maison de Bernarda Alba."],
    ["Quel poète chilien reçoit le Nobel de littérature en 1971 ?", ["Pablo Neruda", "Nicanor Parra", "Vicente Huidobro", "Gonzalo Rojas"], 0,
     "Gabriela Mistral, également chilienne, l'avait reçu en 1945."],
    ["Qu'appelle-t-on le boom latino-américain ?", ["L'essor international du roman latino-américain dans les années 1960", "L'industrialisation du continent", "La croissance de l'édition espagnole", "L'apparition du réalisme magique seul"], 0,
     "García Márquez, Vargas Llosa, Cortázar et Fuentes en sont les principales figures."],
    ["Quel roman de Julio Cortázar propose plusieurs ordres de lecture ?", ["Marelle", "Les Armes secrètes", "Le Livre de Manuel", "Bestiaire"], 0,
     "L'auteur propose au lecteur un parcours linéaire ou un cheminement par sauts entre chapitres."],
    ["Quel écrivain péruvien reçoit le Nobel de littérature en 2010 ?", ["Mario Vargas Llosa", "César Vallejo", "Alfredo Bryce Echenique", "José María Arguedas"], 0,
     "Il fut aussi candidat à la présidence de son pays en 1990.", 3],
  ]),

  notion("li2-litterature-germanique", S, "Les littératures de langue allemande",
    "Goethe, romantisme allemand, littérature du XXe siècle.",
    "Faust a occupé Goethe pendant près de soixante ans.",
    2, [
    ["Quel drame Goethe a-t-il écrit sur près de soixante ans ?", ["Faust", "Les Souffrances du jeune Werther", "Wilhelm Meister", "Iphigénie en Tauride"], 0,
     "La seconde partie fut publiée après sa mort en 1832."],
    ["Quel roman de Goethe déclenche une vague d'imitations en Europe en 1774 ?", ["Les Souffrances du jeune Werther", "Faust", "Les Affinités électives", "Hermann et Dorothée"], 0,
     "Son succès fut tel qu'on lui attribua une vague de suicides, réalité difficile à établir."],
    ["Quel mouvement littéraire allemand précède le romantisme ?", ["Le Sturm und Drang", "Le Biedermeier", "Le Vormärz", "Le Jeune Allemagne"], 0,
     "Tempête et élan : il exalte la passion et le génie contre les règles classiques."],
    ["Quel poète allemand est aussi l'auteur du Chant des Allemands ?", ["Hoffmann von Fallersleben", "Friedrich Schiller", "Heinrich Heine", "Novalis"], 0,
     "Sa troisième strophe seule constitue l'hymne allemand actuel."],
    ["Quel écrivain allemand publie La Montagne magique en 1924 ?", ["Thomas Mann", "Hermann Hesse", "Robert Musil", "Alfred Döblin"], 0,
     "Un sanatorium suisse y devient le microcosme de l'Europe d'avant 1914."],
    ["Quel roman de Thomas Mann suit le déclin d'une famille de négociants ?", ["Les Buddenbrook", "La Mort à Venise", "Docteur Faustus", "Le Docteur Mann"], 0,
     "Publié à vingt-six ans, il lui vaudra le Nobel en 1929."],
    ["Quel écrivain de langue allemande né à Prague écrit Le Procès ?", ["Franz Kafka", "Rainer Maria Rilke", "Stefan Zweig", "Joseph Roth"], 0,
     "Il demanda à son ami Max Brod de brûler ses manuscrits ; celui-ci les publia."],
    ["Quelle nouvelle de Kafka s'ouvre sur un homme changé en insecte ?", ["La Métamorphose", "Le Verdict", "Un artiste de la faim", "La Colonie pénitentiaire"], 0,
     "Le terme allemand employé désigne une vermine indéterminée, que Kafka refusait de faire illustrer."],
    ["Quel écrivain autrichien écrit Le Monde d'hier avant son suicide en 1942 ?", ["Stefan Zweig", "Joseph Roth", "Robert Musil", "Arthur Schnitzler"], 0,
     "Ce récit d'une Europe disparue fut achevé en exil au Brésil."],
    ["Quel écrivain allemand reçoit le Nobel en 1999 pour Le Tambour ?", ["Günter Grass", "Heinrich Böll", "Siegfried Lenz", "Uwe Johnson"], 0,
     "Heinrich Böll l'avait reçu en 1972. Le Tambour est le premier volet de la Trilogie de Dantzig.", 3],
  ]),

  notion("li2-litterature-francophone", S, "Les littératures francophones",
    "Écrire en français hors de France : Antilles, Afrique, Maghreb, Québec, Belgique.",
    "Écrire en français peut être un choix, un héritage colonial ou les deux à la fois.",
    2, [
    ["Quel écrivain martiniquais publie le Cahier d'un retour au pays natal en 1939 ?", ["Aimé Césaire", "Édouard Glissant", "Patrick Chamoiseau", "Frantz Fanon"], 0,
     "Le mot négritude y apparaît pour la première fois sous sa plume."],
    ["Quel écrivain martiniquais développe la notion de créolité ?", ["Patrick Chamoiseau", "Aimé Césaire", "Léon-Gontran Damas", "Joseph Zobel"], 0,
     "Avec Raphaël Confiant et Jean Bernabé, dans l'Éloge de la créolité de 1989."],
    ["Quel écrivain martiniquais théorise la relation et le Tout-monde ?", ["Édouard Glissant", "Aimé Césaire", "Frantz Fanon", "René Depestre"], 0,
     "Il oppose à l'identité racine une identité rhizome, ouverte et relationnelle."],
    ["Quel essai de Frantz Fanon paraît en 1961 ?", ["Les Damnés de la terre", "Peau noire, masques blancs", "L'An V de la révolution algérienne", "Pour la révolution africaine"], 0,
     "Préfacé par Sartre, il devint une référence des mouvements de libération."],
    ["Quel écrivain sénégalais publie Une si longue lettre ?", ["Mariama Bâ", "Ousmane Sembène", "Cheikh Hamidou Kane", "Aminata Sow Fall"], 0,
     "Roman épistolaire de 1979 sur la condition des femmes après un veuvage."],
    ["Quel roman de Cheikh Hamidou Kane oppose deux cultures ?", ["L'Aventure ambiguë", "Une si longue lettre", "Les Bouts de bois de Dieu", "Le Docker noir"], 0,
     "Un jeune Peul partagé entre l'école coranique et l'école française."],
    ["Quel écrivain algérien publie Nedjma en 1956 ?", ["Kateb Yacine", "Mohammed Dib", "Mouloud Feraoun", "Assia Djebar"], 0,
     "Il disait du français qu'il était son butin de guerre."],
    ["Quelle écrivaine algérienne entre à l'Académie française en 2005 ?", ["Assia Djebar", "Maïssa Bey", "Leïla Sebbar", "Malika Mokeddem"], 0,
     "Première femme du Maghreb à y siéger, romancière et cinéaste."],
    ["Quel écrivain québécois publie Bonheur d'occasion en 1945 ?", ["Gabrielle Roy", "Michel Tremblay", "Anne Hébert", "Réjean Ducharme"], 0,
     "Le roman décrit un quartier ouvrier de Montréal pendant la guerre."],
    ["Quel dramaturge québécois fait entrer le joual sur scène en 1968 ?", ["Michel Tremblay", "Gratien Gélinas", "Marcel Dubé", "Robert Lepage"], 0,
     "Les Belles-Sœurs provoqua un débat national sur la langue et la représentation du peuple.", 3],
  ]),

  notion("li2-autobiographie", S, "Écrire sa vie",
    "Confessions, mémoires, journaux, correspondances : les formes du récit de soi.",
    "Rousseau inaugure l'idée de tout dire sur soi, y compris le déshonorant. Avant lui, on écrivait ses mémoires, pas ses fautes.",
    2, [
    ["Quel ouvrage de Rousseau inaugure l'autobiographie moderne ?", ["Les Confessions", "Les Rêveries du promeneur solitaire", "Émile", "Les Dialogues"], 0,
     "Publié après sa mort, il annonce vouloir montrer un homme dans toute la vérité de sa nature."],
    ["Quel titre saint Augustin donne-t-il à son récit de conversion ?", ["Les Confessions", "La Cité de Dieu", "Les Soliloques", "Les Rétractations"], 0,
     "Écrit vers 397, il constitue le premier grand récit d'introspection de la tradition occidentale."],
    ["Quels mémoires Chateaubriand fait-il publier après sa mort ?", ["Les Mémoires d'outre-tombe", "Le Génie du christianisme", "René", "Atala"], 0,
     "Il en avait vendu les droits de son vivant pour financer sa vieillesse."],
    ["Quel duc laisse des mémoires sur la cour de Louis XIV ?", ["Saint-Simon", "Retz", "La Rochefoucauld", "Sully"], 0,
     "Ils ne furent publiés intégralement qu'au XIXe siècle, un siècle après sa mort."],
    ["Quel journal d'une adolescente cachée pendant la guerre est devenu un classique ?", ["Le Journal d'Anne Frank", "Le Journal d'Hélène Berr", "Le Journal de Mihail Sebastian", "Le Journal d'Etty Hillesum"], 0,
     "Publié par son père en 1947, seul survivant de la famille."],
    ["Quel récit de Primo Levi témoigne de sa déportation ?", ["Si c'est un homme", "La Trêve", "Les Naufragés et les Rescapés", "Le Système périodique"], 0,
     "Refusé par plusieurs éditeurs en 1947, il ne connut le succès que dix ans plus tard."],
    ["Quel écrivain publie Les Mots en 1964, récit de son enfance ?", ["Jean-Paul Sartre", "Albert Camus", "André Gide", "Michel Leiris"], 0,
     "Il y raconte sa découverte de la lecture et de l'écriture comme d'une imposture fondatrice."],
    ["Quelle écrivaine française fait de sa vie une enquête sociologique ?", ["Annie Ernaux", "Marguerite Duras", "Nathalie Sarraute", "Colette"], 0,
     "Elle parle d'auto-socio-biographie : le je y sert à examiner un milieu, pas seulement une personne."],
    ["Quel écrivain français forge le terme d'autofiction en 1977 ?", ["Serge Doubrovsky", "Philippe Lejeune", "Michel Leiris", "Georges Perec"], 0,
     "Philippe Lejeune, lui, a théorisé le pacte autobiographique dans un essai de 1975."],
    ["Quel livre de Georges Perec alterne récit d'enfance et fiction ?", ["W ou le Souvenir d'enfance", "La Vie mode d'emploi", "Les Choses", "Un homme qui dort"], 0,
     "Deux textes alternés, en italique et en romain, disent l'impossibilité de raconter directement la disparition de ses parents.", 3],
  ]),

  notion("li2-oulipo-experiences", S, "Contraintes et expérimentations littéraires",
    "L'Oulipo, le lettrisme, le Nouveau Roman : la forme comme sujet.",
    "L'Oulipo n'est pas un mouvement littéraire mais un atelier de recherche de contraintes.",
    2, [
    ["Que signifie l'acronyme Oulipo ?", ["Ouvroir de littérature potentielle", "Organisation universelle de littérature poétique", "Ouvrage libre de poésie", "Office de littérature populaire"], 0,
     "Fondé en 1960 par Raymond Queneau et François Le Lionnais."],
    ["Quel roman de Georges Perec est écrit sans la lettre e ?", ["La Disparition", "Les Revenentes", "La Vie mode d'emploi", "Un homme qui dort"], 0,
     "Trois cents pages sans la voyelle la plus fréquente du français. Les Revenentes emploie e comme seule voyelle."],
    ["Qu'est-ce qu'un lipogramme ?", ["Un texte écrit en s'interdisant une ou plusieurs lettres", "Un poème sans ponctuation", "Un texte à mots imposés", "Une phrase palindrome"], 0,
     "La contrainte est très ancienne : on en trouve des exemples dès l'Antiquité grecque."],
    ["Quel livre de Raymond Queneau raconte cent mille milliards de poèmes ?", ["Cent mille milliards de poèmes", "Exercices de style", "Zazie dans le métro", "Le Chiendent"], 0,
     "Dix sonnets aux vers découpés en bandes, combinables ligne à ligne."],
    ["Quel livre de Queneau raconte quatre-vingt-dix-neuf fois la même scène ?", ["Exercices de style", "Zazie dans le métro", "Les Fleurs bleues", "Loin de Rueil"], 0,
     "Une scène banale d'autobus, racontée dans quatre-vingt-dix-neuf registres différents."],
    ["Quel roman de Perec est construit sur le plan d'un immeuble parisien ?", ["La Vie mode d'emploi", "La Disparition", "Les Choses", "W ou le Souvenir d'enfance"], 0,
     "Le parcours des chapitres suit celui d'un cavalier sur un échiquier de dix cases sur dix."],
    ["Quel écrivain italien membre de l'Oulipo écrit Si par une nuit d'hiver un voyageur ?", ["Italo Calvino", "Umberto Eco", "Primo Levi", "Dino Buzzati"], 0,
     "Le roman enchaîne dix débuts de romans que le lecteur ne peut jamais finir."],
    ["Dans quel essai Alain Robbe-Grillet formule-t-il le programme du Nouveau Roman ?", ["Pour un nouveau roman", "L'Ère du soupçon", "Le Degré zéro de l'écriture", "Essais critiques"], 0,
     "Publié en 1963. L'Ère du soupçon, de Nathalie Sarraute, l'avait précédé de huit ans."],
    ["Quelle écrivaine du Nouveau Roman explore les mouvements infimes de la conscience ?", ["Nathalie Sarraute", "Marguerite Duras", "Claude Simon", "Monique Wittig"], 0,
     "Elle appelle tropismes ces réactions intérieures fugitives, antérieures à la parole."],
    ["Quel écrivain du Nouveau Roman reçoit le Nobel en 1985 ?", ["Claude Simon", "Alain Robbe-Grillet", "Michel Butor", "Robert Pinget"], 0,
     "Son écriture accumule les images de la mémoire dans des phrases d'une grande longueur.", 3],
  ]),

  notion("li2-lecture-publique", S, "Bibliothèques et vie littéraire",
    "Où circulent les livres, qui les prescrit, comment se fait une réputation.",
    "La Bibliothèque nationale de France conserve un exemplaire de tout ce qui paraît en France.",
    2, [
    ["Que conserve la Bibliothèque nationale de France au titre du dépôt légal ?", ["Un exemplaire de chaque document publié en France", "Les seuls livres primés", "Les manuscrits d'auteurs", "Les ouvrages du domaine public"], 0,
     "Le dépôt légal s'étend aujourd'hui aux sites web français."],
    ["Quelle bibliothèque antique est la plus célèbre du monde méditerranéen ?", ["Celle d'Alexandrie", "Celle de Pergame", "Celle d'Éphèse", "Celle d'Athènes"], 0,
     "Sa disparition fut progressive : incendies, réductions de budget et abandon, sur plusieurs siècles."],
    ["Qu'est-ce qu'une bibliothèque municipale classée ?", ["Une bibliothèque conservant des fonds patrimoniaux sous contrôle de l'État", "La plus grande bibliothèque d'une ville", "Une bibliothèque universitaire", "Une bibliothèque payante"], 0,
     "Elles détiennent souvent des fonds issus des confiscations révolutionnaires."],
    ["Combien d'éditions incunables sont recensées dans le monde ?", ["Environ trente mille", "Environ mille", "Environ trois cent mille", "Environ cent"], 0,
     "Ces livres imprimés avant 1501 font l'objet de catalogues collectifs internationaux depuis un siècle."],
    ["Que fait un critique littéraire ?", ["Il analyse et évalue publiquement des œuvres", "Il corrige les manuscrits", "Il choisit les livres d'un éditeur", "Il attribue les prix"], 0,
     "Son influence sur les ventes est réelle mais très inégale selon les genres."],
    ["Qu'est-ce qu'un club de lecture ?", ["Un groupe se réunissant pour discuter d'ouvrages lus en commun", "Une association d'éditeurs", "Un service d'abonnement à des livres", "Un jury littéraire"], 0,
     "Leur diffusion, ancienne, a été relancée par les réseaux sociaux et les plateformes vidéo."],
    ["Quelle émission télévisée française a longtemps fait vendre les livres qu'elle présentait ?", ["Apostrophes", "Le Masque et la Plume", "Lectures pour tous", "Bouillon de culture"], 0,
     "Animée par Bernard Pivot de 1975 à 1990, elle pouvait multiplier les ventes d'un ouvrage."],
    ["Qu'est-ce que la rentrée littéraire en France ?", ["La publication concentrée de centaines de romans à la fin de l'été", "L'ouverture des salons du livre", "La reprise des cours de littérature", "La remise des prix d'automne"], 0,
     "Environ cinq cents romans y paraissent en quelques semaines, dont l'immense majorité passe inaperçue."],
    ["Qu'est-ce que le prêt numérique en bibliothèque ?", ["Un accès temporaire à un livre numérique via la bibliothèque", "L'achat groupé de livres numériques", "La numérisation des fonds anciens", "Le téléchargement libre d'ouvrages"], 0,
     "Les conditions sont fixées par les éditeurs : nombre de prêts simultanés, durée, nombre total d'emprunts."],
    ["Qu'est-ce que le domaine public en édition ?", ["L'ensemble des œuvres dont les droits patrimoniaux ont expiré", "Les livres financés par l'État", "Les ouvrages libres de droits par choix de l'auteur", "Les publications officielles"], 0,
     "En France, soixante-dix ans après la mort de l'auteur, avec des prorogations pour les guerres.", 3],
  ]),

  notion("li2-prix-litteraires", S, "Prix et reconnaissance littéraire",
    "Qui décerne quoi, sur quels critères, et avec quels effets.",
    "Le prix Goncourt ne rapporte que dix euros à son lauréat, mais des centaines de milliers de ventes.",
    2, [
    ["Quel prix littéraire international est décerné à Stockholm ?", ["Le prix Nobel de littérature", "Le prix Cervantes", "Le Booker Prize", "Le prix Kafka"], 0,
     "Décerné par l'Académie suédoise depuis 1901, il récompense une œuvre et non un livre."],
    ["Quel écrivain français a reçu le premier prix Nobel de littérature en 1901 ?", ["Sully Prudhomme", "Émile Zola", "Anatole France", "Frédéric Mistral"], 0,
     "Le choix fut critiqué : beaucoup attendaient Tolstoï."],
    ["Combien de membres compte le jury du prix Goncourt ?", ["Dix", "Douze", "Sept", "Quinze"], 0,
     "Ils se réunissent chez Drouant, à Paris, où ils déjeunent une fois par mois."],
    ["Quel prix français est décerné le même jour que le Goncourt, en réaction à celui-ci ?", ["Le prix Renaudot", "Le prix Femina", "Le prix Médicis", "Le prix Interallié"], 0,
     "Créé en 1926 par des journalistes attendant la décision du Goncourt."],
    ["Quel prix français est décerné par un jury exclusivement féminin ?", ["Le prix Femina", "Le prix Goncourt", "Le prix Médicis", "Le prix Décembre"], 0,
     "Créé en 1904 par des collaboratrices d'une revue, en réponse à un Goncourt jugé trop masculin."],
    ["Quel prix français récompense un auteur dont la notoriété ne correspond pas au talent ?", ["Le prix Médicis", "Le prix Renaudot", "Le prix Interallié", "Le prix des Deux Magots"], 0,
     "Créé en 1958, il a souvent distingué des écritures exigeantes."],
    ["Quel prix britannique récompense un roman de langue anglaise ?", ["Le Booker Prize", "Le prix Nobel", "Le prix Pulitzer", "Le prix Cervantes"], 0,
     "Ouvert depuis 2014 à tous les romans écrits en anglais et publiés au Royaume-Uni."],
    ["Quel prix américain récompense notamment le journalisme et la littérature ?", ["Le prix Pulitzer", "Le National Book Award", "Le prix PEN/Faulkner", "Le prix Hugo"], 0,
     "Décerné depuis 1917 par l'université Columbia, il comporte une vingtaine de catégories."],
    ["Quel prix récompense les meilleures œuvres de science-fiction, voté par les lecteurs ?", ["Le prix Hugo", "Le prix Nebula", "Le prix Locus", "Le prix Philip K. Dick"], 0,
     "Le Nebula, lui, est décerné par les auteurs professionnels du genre."],
    ["Quel effet un grand prix littéraire a-t-il sur les ventes en France ?", ["Il les multiplie souvent par dix ou davantage", "Il les modifie peu", "Il ne joue que sur la presse", "Il agit surtout sur les traductions"], 0,
     "Un Goncourt dépasse fréquemment les trois cent mille exemplaires, contre quelques milliers pour un roman moyen.", 3],
  ]),
];
