/**
 * Littérature — treize notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Littérature";

export const CG_LITTERATURE: SeedSkill[] = [
  notion("li-genres-litteraires", S, "Les genres littéraires",
    "Roman, théâtre, poésie, essai : des formes aux règles anciennes, et des frontières poreuses.",
    "Un genre se définit par sa forme et son mode d'énonciation, pas par son sujet.",
    2, [
    ["Qu'est-ce qu'un roman épistolaire ?", ["Un roman composé de lettres échangées", "Un roman écrit à la première personne", "Un roman historique", "Un roman en vers"], 0,
     "Les Liaisons dangereuses de Laclos en est le sommet français."],
    ["Qu'est-ce qu'une nouvelle, par rapport au roman ?", ["Un récit bref, à intrigue resserrée", "Un roman inachevé", "Un récit d'actualité", "Un roman à plusieurs voix"], 0,
     "La chute finale y joue souvent un rôle décisif, comme chez Maupassant."],
    ["Qu'est-ce qu'une fable ?", ["Un court récit à visée morale mettant souvent en scène des animaux", "Un conte merveilleux", "Un poème lyrique", "Un récit fondateur d'un peuple"], 0,
     "Ésope en Grèce, Phèdre à Rome, La Fontaine en France en sont les grands noms."],
    ["Qu'est-ce qu'un essai ?", ["Un texte de réflexion personnelle sur un sujet", "Un traité savant exhaustif", "Un récit autobiographique", "Un manifeste politique"], 0,
     "Montaigne invente le mot et la forme en 1580 : essayer sa pensée plutôt que conclure."],
    ["Qu'est-ce qu'une autobiographie ?", ["Le récit de sa propre vie par son auteur", "Un roman inspiré de faits réels", "Un journal intime publié", "Une biographie autorisée"], 0,
     "Philippe Lejeune parle de pacte autobiographique : identité entre auteur, narrateur et personnage."],
    ["Qu'est-ce que l'autofiction ?", ["Un récit de soi assumant une part de fiction", "Une autobiographie romancée sans le dire", "Un roman à clés", "Un témoignage journalistique"], 0,
     "Le terme est forgé par Serge Doubrovsky en 1977 pour son roman Fils."],
    ["Qu'est-ce qu'une tragédie classique ?", ["Une pièce en cinq actes, en vers, où un héros noble court à sa perte", "Une pièce à fin malheureuse", "Un drame historique", "Une pièce sans dénouement"], 0,
     "Elle obéit aux règles des trois unités : action, lieu, temps."],
    ["Qu'est-ce qu'un drame romantique ?", ["Une pièce qui rejette les unités et mêle registres et milieux sociaux", "Une tragédie moderne", "Une pièce sur la vie privée", "Un mélodrame populaire"], 0,
     "Hugo en fixe le programme dans la préface de Cromwell en 1827 et l'illustre avec Hernani."],
    ["Qu'est-ce qu'un sonnet ?", ["Un poème de quatorze vers en deux quatrains et deux tercets", "Un poème de douze vers", "Un poème sans rimes", "Un poème chanté"], 0,
     "Venu d'Italie, il est introduit en France au XVIe siècle par Marot et la Pléiade."],
    ["Qu'est-ce qu'un poème en prose ?", ["Un texte poétique sans vers ni rimes", "Un roman très travaillé", "Une prose rythmée en alexandrins cachés", "Un récit lyrique versifié"], 0,
     "Aloysius Bertrand en pose les bases ; Baudelaire l'installe avec Le Spleen de Paris.", 3],
  ]),

  notion("li-versification", S, "La versification française",
    "Compter les syllabes, placer la césure, entendre les rimes : la mécanique du vers.",
    "Le e muet compte devant une consonne et s'élide devant une voyelle ou en fin de vers.",
    2, [
    ["D'où le vers de douze syllabes tire-t-il le nom d'alexandrin ?", ["Du Roman d'Alexandre, écrit dans ce mètre au XIIe siècle", "D'Alexandre le Grand, qui l'aurait aimé", "De la ville d'Alexandrie", "D'un poète nommé Alexandre de Ronsard"], 0,
     "Le mètre s'impose ensuite au XVIe siècle et domine la poésie française jusqu'au XIXe."],
    ["Comment appelle-t-on un vers de dix syllabes ?", ["Un décasyllabe", "Un octosyllabe", "Un alexandrin", "Un hendécasyllabe"], 0,
     "C'est le mètre de la Chanson de Roland, avant que l'alexandrin ne domine."],
    ["Qu'est-ce que la césure d'un alexandrin classique ?", ["Une coupe après la sixième syllabe", "La pause en fin de vers", "L'accent sur la dernière syllabe", "Le silence entre deux strophes"], 0,
     "Elle partage le vers en deux hémistiches. Les romantiques la déplaceront pour assouplir le rythme."],
    ["Qu'est-ce qu'un enjambement ?", ["Une phrase qui se poursuit au vers suivant", "Une rime déplacée", "Une syllabe supplémentaire", "Une pause au milieu du vers"], 0,
     "Le rejet est le cas particulier où seul un mot bref déborde sur le vers suivant."],
    ["Qu'est-ce qu'une diérèse ?", ["Prononcer en deux syllabes ce qui s'en dit une", "Supprimer une syllabe", "Répéter une consonne", "Élider un e muet"], 0,
     "Dans « pas-si-on » compté en trois syllabes plutôt que deux. La synérèse fait l'inverse."],
    ["Que sont des rimes embrassées ?", ["Une disposition ABBA", "Une disposition ABAB", "Une disposition AABB", "Des rimes sans ordre fixe"], 0,
     "ABAB sont des rimes croisées, AABB des rimes plates ou suivies."],
    ["Qu'est-ce qu'une rime riche ?", ["Une rime partageant au moins trois sons communs", "Une rime rare", "Une rime sur un mot long", "Une rime entre deux mots de même sens"], 0,
     "Une rime pauvre n'en partage qu'un, une rime suffisante deux."],
    ["Qu'est-ce que l'alternance des rimes en poésie classique ?", ["L'alternance obligatoire entre rimes féminines et masculines", "L'alternance des mètres", "Le changement de rime à chaque strophe", "L'alternance entre vers et prose"], 0,
     "Une rime féminine se termine par un e muet ; une rime masculine non."],
    ["Qu'est-ce qu'un vers libre ?", ["Un vers sans mètre ni rime réguliers", "Un vers sans ponctuation", "Un vers de longueur impaire", "Un vers non rimé mais mesuré"], 0,
     "Il s'impose à la fin du XIXe siècle, notamment avec Rimbaud, Laforgue et les symbolistes."],
    ["Qu'est-ce qu'un calligramme ?", ["Un poème dont la disposition dessine une figure", "Un poème écrit à la main", "Un poème sans verbe", "Un acrostiche"], 0,
     "Apollinaire en fait un recueil en 1918, mais la forme remonte à l'Antiquité grecque.", 3],
  ]),

  notion("li-figures-style", S, "Les figures de style en littérature",
    "Comparaison, métaphore, métonymie, ironie : nommer précisément ce que fait une phrase.",
    "La comparaison montre l'outil de comparaison ; la métaphore le supprime.",
    2, [
    ["Qu'est-ce qu'une métaphore ?", ["Une comparaison sans outil de comparaison", "Une exagération volontaire", "Une opposition de termes", "Un remplacement par un mot voisin"], 0,
     "« Cet homme est un lion » est une métaphore ; « fort comme un lion » une comparaison."],
    ["Qu'est-ce qu'une métonymie ?", ["Désigner une chose par un terme qui lui est logiquement lié", "Exagérer une qualité", "Adoucir une réalité", "Répéter un mot en tête de phrase"], 0,
     "« Boire un verre », « lire un Zola » : le contenant pour le contenu, l'auteur pour l'œuvre."],
    ["Qu'est-ce qu'une synecdoque ?", ["Désigner le tout par la partie ou l'inverse", "Comparer deux réalités", "Inverser l'ordre des mots", "Employer un mot pour son contraire"], 0,
     "« Une voile à l'horizon » pour un navire. C'est un cas particulier de métonymie."],
    ["Qu'est-ce qu'un oxymore ?", ["L'association de deux termes contradictoires", "Une gradation ascendante", "Une répétition sonore", "Une comparaison implicite"], 0,
     "« Cette obscure clarté », chez Corneille, en est l'exemple le plus cité."],
    ["Qu'est-ce qu'une hyperbole ?", ["Une exagération volontaire", "Une atténuation", "Une opposition", "Une répétition"], 0,
     "« Je meurs de faim ». Son contraire, la litote, dit moins pour suggérer plus."],
    ["Qu'est-ce qu'une litote ?", ["Dire moins pour faire entendre plus", "Exagérer un trait", "Adoucir un mot déplaisant", "Répéter une structure"], 0,
     "« Va, je ne te hais point » chez Corneille signifie exactement l'inverse."],
    ["Qu'est-ce qu'un euphémisme ?", ["Une formule qui atténue une réalité désagréable", "Une exagération ironique", "Une figure de répétition", "Une contradiction apparente"], 0,
     "« Il nous a quittés » pour « il est mort ». À ne pas confondre avec la litote, qui vise l'intensification."],
    ["Qu'est-ce qu'une anaphore ?", ["La répétition d'un mot en tête de plusieurs propositions", "La répétition en fin de phrase", "L'inversion du sujet", "Le retour d'un même son"], 0,
     "« Moi, président de la République… » : un usage rhétorique célèbre de la figure."],
    ["Qu'est-ce qu'une allitération ?", ["La répétition d'un même son consonantique", "La répétition d'une voyelle", "La répétition d'un mot", "L'imitation d'un bruit"], 0,
     "L'assonance est son équivalent pour les voyelles. « Pour qui sont ces serpents… » chez Racine."],
    ["Qu'est-ce qu'une prétérition ?", ["Annoncer qu'on ne dira pas ce qu'on dit malgré tout", "Répéter une négation", "Suggérer par l'absence", "Interrompre volontairement une phrase"], 0,
     "« Je ne vous parlerai pas de son passé… » : la figure dit en feignant de taire.", 3],
  ]),

  notion("li-mouvements-litteraires", S, "Les mouvements littéraires",
    "Humanisme, classicisme, Lumières, romantisme, réalisme, surréalisme : sept siècles en quelques programmes.",
    "Un mouvement se reconnaît à un manifeste, une revue ou une préface qui fixe son programme.",
    2, [
    ["Qu'est-ce que l'humanisme au XVIe siècle ?", ["Un mouvement qui replace l'homme et les textes antiques au centre du savoir", "Une doctrine de charité chrétienne", "Un courant politique républicain", "Une école de peinture italienne"], 0,
     "Érasme, Rabelais et Montaigne en sont les figures majeures. L'imprimerie en démultiplie la portée."],
    ["Quel groupe de poètes du XVIe siècle veut illustrer la langue française ?", ["La Pléiade", "Les Grands Rhétoriqueurs", "Le Parnasse", "Les Félibres"], 0,
     "Du Bellay publie en 1549 la Défense et illustration de la langue française, son manifeste."],
    ["Quelle règle domine le théâtre classique du XVIIe siècle ?", ["La règle des trois unités", "L'interdiction du vers", "L'absence de chœur", "L'unité de ton"], 0,
     "Unité d'action, de lieu et de temps, au nom de la vraisemblance et de la bienséance."],
    ["Qu'est-ce que le siècle des Lumières ?", ["Un mouvement du XVIIIe siècle plaçant la raison et l'esprit critique au premier plan", "Un courant mystique", "Une école poétique", "Une période d'expansion coloniale"], 0,
     "L'Encyclopédie de Diderot et d'Alembert en est le grand chantier collectif."],
    ["Quel sentiment le romantisme place-t-il au centre ?", ["Le moi et ses émotions", "La raison", "L'objectivité scientifique", "La satire sociale"], 0,
     "Mélancolie, nature, passion et révolte contre les règles en sont les traits communs."],
    ["Quel mouvement veut peindre la société telle qu'elle est, au XIXe siècle ?", ["Le réalisme", "Le romantisme", "Le symbolisme", "Le classicisme"], 0,
     "Balzac, Flaubert et Maupassant en sont les grands noms. Le naturalisme y ajoute une méthode scientifique."],
    ["Quel écrivain théorise le naturalisme ?", ["Émile Zola", "Gustave Flaubert", "Honoré de Balzac", "Guy de Maupassant"], 0,
     "Dans Le Roman expérimental en 1880 : le romancier observe et expérimente comme un médecin."],
    ["Quelle formule résume la doctrine du Parnasse ?", ["L'art pour l'art", "L'art engagé", "L'art populaire", "L'art total"], 0,
     "Contre l'épanchement romantique, les parnassiens visent la perfection formelle et l'impassibilité."],
    ["Qui publie le Manifeste du surréalisme en 1924 ?", ["André Breton", "Louis Aragon", "Paul Éluard", "Tristan Tzara"], 0,
     "Le mouvement explore le rêve, l'écriture automatique et l'inconscient, dans le sillage de Freud."],
    ["Qu'est-ce que le Nouveau Roman ?", ["Un courant des années 1950 qui rompt avec l'intrigue et le personnage traditionnels", "Un retour au roman réaliste", "Un genre policier littéraire", "Le roman de la Libération"], 0,
     "Robbe-Grillet, Sarraute et Butor, réunis autour des Éditions de Minuit, en sont les principaux auteurs.", 3],
  ]),

  notion("li-theatre-francais", S, "Le théâtre français",
    "Du tréteau médiéval à la scène contemporaine : auteurs, formes et institutions.",
    "La Comédie-Française naît en 1680 de la fusion de troupes voulue par Louis XIV.",
    2, [
    ["En quelle année la Comédie-Française est-elle fondée ?", ["1680", "1643", "1715", "1789"], 0,
     "Louis XIV fusionne la troupe de Molière avec celle de l'Hôtel de Bourgogne. C'est la plus ancienne troupe permanente du monde."],
    ["Quel surnom la Comédie-Française porte-t-elle ?", ["La Maison de Molière", "Le Théâtre du Roi", "La Grande Salle", "Le Palais des Comédiens"], 0,
     "Molière était mort sept ans avant sa fondation, mais sa troupe en constitue le noyau."],
    ["Quelle pièce de Beaumarchais fut longtemps interdite avant sa création en 1784 ?", ["Le Mariage de Figaro", "Le Barbier de Séville", "La Mère coupable", "Eugénie"], 0,
     "Le monologue de Figaro attaque les privilèges de naissance. Louis XVI la jugea détestable avant de céder."],
    ["Quelle pièce de Victor Hugo provoque une bataille en 1830 ?", ["Hernani", "Ruy Blas", "Les Burgraves", "Lucrèce Borgia"], 0,
     "Partisans du drame romantique et défenseurs du classicisme s'affrontent dans la salle dès la première."],
    ["Qui écrit En attendant Godot, créée en 1953 ?", ["Samuel Beckett", "Eugène Ionesco", "Jean Genet", "Arthur Adamov"], 0,
     "Pièce fondatrice du théâtre de l'absurde : deux personnages attendent quelqu'un qui ne vient jamais."],
    ["Quelle pièce d'Eugène Ionesco est jouée sans interruption dans le même théâtre parisien depuis 1957 ?", ["La Cantatrice chauve", "Rhinocéros", "Les Chaises", "Le Roi se meurt"], 0,
     "Au Théâtre de la Huchette, c'est l'un des plus longs records de représentation continue au monde."],
    ["Qui fonde le Théâtre national populaire dans sa forme d'après-guerre ?", ["Jean Vilar", "Louis Jouvet", "Antonin Artaud", "Jacques Copeau"], 0,
     "Il en prend la direction en 1951 avec l'ambition d'un théâtre exigeant pour un public large."],
    ["Quel festival de théâtre Jean Vilar crée-t-il en 1947 ?", ["Le Festival d'Avignon", "Le Festival d'Aix", "Le Printemps des comédiens", "Les Nuits de Fourvière"], 0,
     "La cour d'honneur du Palais des papes en est le lieu emblématique."],
    ["Qui écrit Le Théâtre et son double, qui appelle à un théâtre de la cruauté ?", ["Antonin Artaud", "Bertolt Brecht", "Konstantin Stanislavski", "Jacques Copeau"], 0,
     "Publié en 1938, il influence durablement la mise en scène du XXe siècle."],
    ["Qu'est-ce que la distanciation au théâtre ?", ["Un procédé empêchant le spectateur de s'identifier pour le faire réfléchir", "L'éloignement de la scène", "Le refus du décor", "Le jeu sans émotion"], 0,
     "Théorisée par Bertolt Brecht, elle rompt l'illusion par des adresses au public ou des pancartes.", 3],
  ]),

  notion("li-roman-francais", S, "Le roman français",
    "Du roman de chevalerie au roman contemporain : quelques jalons et leurs auteurs.",
    "La Princesse de Clèves, en 1678, est souvent tenue pour le premier roman d'analyse psychologique.",
    2, [
    ["Quel roman de 1678 est souvent tenu pour le premier roman d'analyse psychologique français ?", ["La Princesse de Clèves", "Manon Lescaut", "La Nouvelle Héloïse", "Gil Blas"], 0,
     "Publié anonymement par Madame de La Fayette, il fait de l'intériorité le vrai sujet du récit."],
    ["Quel ensemble romanesque Balzac construit-il à partir de 1830 ?", ["La Comédie humaine", "Les Rougon-Macquart", "Les Thibault", "Les Hommes de bonne volonté"], 0,
     "Près de quatre-vingt-dix romans reliés par le retour des personnages, pour peindre toute une société."],
    ["Quelle fresque romanesque Zola consacre-t-il à une famille sous le Second Empire ?", ["Les Rougon-Macquart", "La Comédie humaine", "Les Misérables", "Le Cycle de Pardaillan"], 0,
     "Vingt romans, sous-titrés Histoire naturelle et sociale d'une famille sous le Second Empire."],
    ["Quel roman de Flaubert vaut à son auteur un procès en 1857 ?", ["Madame Bovary", "L'Éducation sentimentale", "Salammbô", "Bouvard et Pécuchet"], 0,
     "Poursuivi pour outrage à la morale publique, il est acquitté. Baudelaire, la même année, sera condamné."],
    ["Quelle œuvre Marcel Proust publie-t-il à partir de 1913 ?", ["À la recherche du temps perdu", "Les Faux-Monnayeurs", "Le Grand Meaulnes", "Le Rivage des Syrtes"], 0,
     "Sept volumes, achevés après sa mort. Le premier fut refusé par plusieurs éditeurs, dont Gide chez Gallimard."],
    ["Quel roman d'Albert Camus s'ouvre sur la mort d'une mère et l'indifférence du narrateur ?", ["L'Étranger", "La Peste", "La Chute", "Le Premier Homme"], 0,
     "Publié en 1942, il illustre la notion d'absurde développée dans Le Mythe de Sisyphe."],
    ["Quel écrivain refuse le prix Nobel de littérature en 1964 ?", ["Jean-Paul Sartre", "Albert Camus", "André Malraux", "Louis-Ferdinand Céline"], 0,
     "Il refusait toute distinction officielle, estimant qu'un écrivain ne doit pas se laisser transformer en institution."],
    ["Quel roman de Marguerite Duras obtient le Goncourt en 1984 ?", ["L'Amant", "Un barrage contre le Pacifique", "Moderato cantabile", "Le Ravissement de Lol V. Stein"], 0,
     "Récit largement autobiographique de sa jeunesse en Indochine, il connaît un immense succès."],
    ["Quelle écrivaine obtient le prix Nobel de littérature en 2022 ?", ["Annie Ernaux", "Marguerite Duras", "Nathalie Sarraute", "Marie NDiaye"], 0,
     "L'Académie salue une écriture qui met à nu les racines et les contraintes de la mémoire personnelle."],
    ["Quel prix littéraire français est décerné chez Drouant depuis 1903 ?", ["Le prix Goncourt", "Le prix Renaudot", "Le prix Femina", "Le prix Médicis"], 0,
     "Il récompense le meilleur ouvrage d'imagination en prose de l'année et ne rapporte que dix euros à son lauréat.", 3],
  ]),

  notion("li-poesie-francaise", S, "La poésie française",
    "De Villon à Bonnefoy : quelques voix et les recueils qui ont fait date.",
    "Les Fleurs du mal ont été condamnées en 1857, la même année que Madame Bovary fut acquittée.",
    2, [
    ["Quel poète du XVe siècle écrit la Ballade des pendus ?", ["François Villon", "Charles d'Orléans", "Clément Marot", "Rutebeuf"], 0,
     "Écrite alors qu'il attendait, dit-on, une exécution qui fut finalement commuée en bannissement."],
    ["Quel recueil de Baudelaire est condamné en 1857 ?", ["Les Fleurs du mal", "Le Spleen de Paris", "Les Paradis artificiels", "Les Épaves"], 0,
     "Six pièces sont censurées pour outrage à la morale publique. Elles ne seront réhabilitées qu'en 1949."],
    ["Quel très jeune poète écrit Le Bateau ivre puis cesse d'écrire avant vingt et un ans ?", ["Arthur Rimbaud", "Paul Verlaine", "Stéphane Mallarmé", "Lautréamont"], 0,
     "Il part ensuite pour l'Afrique où il devient négociant. Son œuvre tient en quelques années."],
    ["Quel poème de Verlaine commence par « Il pleure dans mon cœur » ?", ["Ariettes oubliées", "Chanson d'automne", "Mon rêve familier", "Green"], 0,
     "Tiré des Romances sans paroles, il illustre la musicalité que Verlaine réclamait avant toute chose."],
    ["Quel recueil de Mallarmé s'achève sur un poème disposé librement sur la page ?", ["Un coup de dés jamais n'abolira le hasard", "Hérodiade", "L'Après-midi d'un faune", "Poésies"], 0,
     "Publié en 1897, il fait de la page blanche et de la typographie des éléments du poème."],
    ["Quel poème d'Apollinaire évoque la Seine et le temps qui passe ?", ["Le Pont Mirabeau", "Zone", "La Chanson du mal-aimé", "Les Colchiques"], 0,
     "Tiré d'Alcools, publié en 1913, recueil dont Apollinaire a supprimé toute ponctuation."],
    ["Quel poème de Paul Éluard, écrit sous l'Occupation, s'achève sur le mot Liberté ?", ["Liberté", "Capitale de la douleur", "Le Temps déborde", "Poésie et vérité"], 0,
     "Parachuté par la Royal Air Force au-dessus de la France occupée, il devient un texte de résistance."],
    ["Quel poète martiniquais est l'un des fondateurs de la négritude ?", ["Aimé Césaire", "Léon-Gontran Damas", "Édouard Glissant", "Frantz Fanon"], 0,
     "Avec Léopold Sédar Senghor et Léon-Gontran Damas, dans les années 1930 à Paris."],
    ["Quel poète sénégalais devient président de son pays en 1960 ?", ["Léopold Sédar Senghor", "Aimé Césaire", "Birago Diop", "Cheikh Anta Diop"], 0,
     "Il fut aussi le premier Africain élu à l'Académie française, en 1983."],
    ["Quel poète français du XXe siècle consacre un recueil aux choses ordinaires dans Le Parti pris des choses ?", ["Francis Ponge", "René Char", "Yves Bonnefoy", "Philippe Jaccottet"], 0,
     "Publié en 1942, il décrit le cageot, l'huître ou le pain avec une minutie qui les transfigure.", 3],
  ]),

  notion("li-litterature-anglaise", S, "La littérature de langue anglaise",
    "Shakespeare, le roman victorien, le modernisme, la littérature américaine : quelques repères.",
    "Shakespeare a écrit environ trente-sept pièces et cent cinquante-quatre sonnets.",
    2, [
    ["Combien de sonnets Shakespeare a-t-il écrits ?", ["Cent cinquante-quatre", "Cent", "Deux cents", "Cinquante"], 0,
     "Publiés en 1609, ils sont adressés pour la plupart à un jeune homme, puis à une dame brune."],
    ["Quelle pièce de Shakespeare se déroule au Danemark ?", ["Hamlet", "Macbeth", "Le Roi Lear", "Othello"], 0,
     "Macbeth se situe en Écosse, Othello à Venise et Chypre, Le Roi Lear dans une Bretagne légendaire."],
    ["Quel roman de Jane Austen s'ouvre sur une vérité universellement reconnue à propos d'un homme fortuné ?", ["Orgueil et Préjugés", "Raison et Sentiments", "Emma", "Persuasion"], 0,
     "Publié en 1813, il est devenu l'un des romans les plus lus de la langue anglaise."],
    ["Quel roman de Mary Shelley naît d'un défi littéraire au bord du lac Léman en 1816 ?", ["Frankenstein", "Dracula", "Le Moine", "Les Hauts de Hurlevent"], 0,
     "L'été sans été, dû à l'éruption du Tambora, retint le groupe à l'intérieur. Elle avait dix-huit ans."],
    ["Quel roman de Charles Dickens s'ouvre sur un orphelin réclamant du rab de gruau ?", ["Oliver Twist", "David Copperfield", "Les Grandes Espérances", "Un chant de Noël"], 0,
     "Publié en feuilleton à partir de 1837, il dénonce le sort réservé aux enfants pauvres."],
    ["Quelle sœur Brontë écrit Les Hauts de Hurlevent ?", ["Emily", "Charlotte", "Anne", "Elizabeth"], 0,
     "Charlotte écrit Jane Eyre, Anne La Recluse de Wildfell Hall. Toutes trois publièrent d'abord sous pseudonymes masculins."],
    ["Quel roman de James Joyce raconte une seule journée à Dublin ?", ["Ulysse", "Gens de Dublin", "Portrait de l'artiste en jeune homme", "Finnegans Wake"], 0,
     "Le 16 juin 1904, désormais célébré comme le Bloomsday. Le roman parut à Paris en 1922."],
    ["Quelle romancière britannique écrit Mrs Dalloway et Les Vagues ?", ["Virginia Woolf", "Katherine Mansfield", "Iris Murdoch", "Doris Lessing"], 0,
     "Figure du groupe de Bloomsbury, elle est l'une des grandes voix du monologue intérieur."],
    ["Quel roman de George Orwell paru en 1949 décrit une société de surveillance totale ?", ["1984", "La Ferme des animaux", "Le Meilleur des mondes", "Fahrenheit 451"], 0,
     "Le Meilleur des mondes est d'Aldous Huxley, Fahrenheit 451 de Ray Bradbury."],
    ["Quel romancier américain écrit Le Vieil Homme et la Mer ?", ["Ernest Hemingway", "William Faulkner", "John Steinbeck", "Francis Scott Fitzgerald"], 0,
     "Publié en 1952, il contribue à lui valoir le prix Nobel deux ans plus tard.", 3],
  ]),

  notion("li-litteratures-monde", S, "Les littératures du monde",
    "Russie, Amérique latine, Japon, Afrique : des œuvres majeures hors des aires française et anglaise.",
    "Le Dit du Genji, écrit vers l'an mille par une femme de la cour japonaise, est souvent tenu pour le premier roman du monde.",
    2, [
    ["Quel roman de Tolstoï se déroule pendant les guerres napoléoniennes ?", ["Guerre et Paix", "Anna Karénine", "Résurrection", "La Sonate à Kreutzer"], 0,
     "Publié entre 1865 et 1869, il mêle destins privés et fresque historique sur près de deux mille pages."],
    ["Quel roman de Dostoïevski raconte le meurtre d'une usurière par un étudiant ?", ["Crime et Châtiment", "Les Frères Karamazov", "L'Idiot", "Les Démons"], 0,
     "Publié en 1866, il explore la culpabilité davantage que le crime lui-même."],
    ["Quel écrivain colombien écrit Cent Ans de solitude ?", ["Gabriel García Márquez", "Mario Vargas Llosa", "Julio Cortázar", "Carlos Fuentes"], 0,
     "Paru en 1967, il est le roman emblématique du réalisme magique et de la famille Buendía."],
    ["Quel écrivain argentin est connu pour ses nouvelles labyrinthiques réunies dans Fictions ?", ["Jorge Luis Borges", "Julio Cortázar", "Ernesto Sabato", "Adolfo Bioy Casares"], 0,
     "Bibliothèques infinies, livres impossibles et miroirs y composent une œuvre brève et vertigineuse."],
    ["Quelle œuvre japonaise du XIe siècle est souvent tenue pour le premier roman du monde ?", ["Le Dit du Genji", "Le Livre de l'oreiller", "Les Contes d'Ise", "Le Dit des Heiké"], 0,
     "Écrit par Murasaki Shikibu, dame de la cour impériale de Heian."],
    ["Quel écrivain japonais obtient le Nobel de littérature en 1968 ?", ["Yasunari Kawabata", "Yukio Mishima", "Kenzaburō Ōe", "Jun'ichirō Tanizaki"], 0,
     "Kenzaburō Ōe l'obtiendra en 1994. Mishima, souvent pressenti, ne l'a jamais reçu."],
    ["Quel écrivain nigérian publie Le Monde s'effondre en 1958 ?", ["Chinua Achebe", "Wole Soyinka", "Ben Okri", "Ngũgĩ wa Thiong'o"], 0,
     "Le roman raconte l'arrivée des colons vue depuis un village igbo. Il a été traduit dans plus de cinquante langues."],
    ["Quel écrivain africain reçoit le premier prix Nobel de littérature du continent, en 1986 ?", ["Wole Soyinka", "Naguib Mahfouz", "Nadine Gordimer", "Chinua Achebe"], 0,
     "Dramaturge et poète nigérian. Naguib Mahfouz, égyptien, l'obtiendra en 1988."],
    ["Quel poème épique mésopotamien est l'un des plus anciens textes littéraires connus ?", ["L'Épopée de Gilgamesh", "Le Livre des morts", "L'Énuma Elish", "Le Code de Hammurabi"], 0,
     "Gravé sur tablettes d'argile, il contient un récit du déluge antérieur au texte biblique."],
    ["Quelle romancière chilienne écrit La Maison aux esprits ?", ["Isabel Allende", "Gabriela Mistral", "Marcela Serrano", "Diamela Eltit"], 0,
     "Publié en 1982, il transpose l'histoire du Chili dans une saga familiale sur quatre générations.", 3],
  ]),

  notion("li-contes-jeunesse", S, "Contes et littérature de jeunesse",
    "Des recueils du XVIIe siècle aux classiques modernes : ce que lisent les enfants et d'où ça vient.",
    "Perrault fixe par écrit des contes populaires bien plus anciens, souvent adoucis pour la cour.",
    2, [
    ["Qui publie en 1697 les Histoires ou contes du temps passé ?", ["Charles Perrault", "Jean de La Fontaine", "Madame d'Aulnoy", "Antoine Galland"], 0,
     "Le Petit Chaperon rouge, Cendrillon et Le Chat botté y figurent, avec une moralité en vers."],
    ["Qui recueille en Allemagne les contes de Blanche-Neige et Hansel et Gretel ?", ["Les frères Grimm", "Hans Christian Andersen", "E.T.A. Hoffmann", "Ludwig Bechstein"], 0,
     "Jacob et Wilhelm Grimm, philologues, publient leur recueil à partir de 1812."],
    ["Quel auteur danois écrit La Petite Sirène et Le Vilain Petit Canard ?", ["Hans Christian Andersen", "Selma Lagerlöf", "Karen Blixen", "Astrid Lindgren"], 0,
     "Contrairement aux Grimm, il compose des contes originaux plutôt que de collecter la tradition orale."],
    ["Quel recueil oriental est traduit en français par Antoine Galland au XVIIIe siècle ?", ["Les Mille et Une Nuits", "Le Livre des rois", "Kalila et Dimna", "Le Panchatantra"], 0,
     "Sa traduction, parue à partir de 1704, a durablement façonné l'image européenne de l'Orient."],
    ["Qui écrit Le Petit Prince, publié en 1943 ?", ["Antoine de Saint-Exupéry", "Jean Giono", "Marcel Pagnol", "Romain Gary"], 0,
     "Paru d'abord à New York, il est l'un des livres les plus traduits au monde."],
    ["Quel personnage italien créé en 1881 voit son nez s'allonger quand il ment ?", ["Pinocchio", "Arlequin", "Polichinelle", "Gepetto"], 0,
     "Carlo Collodi le publie d'abord en feuilleton dans un journal pour enfants."],
    ["Qui écrit Le Livre de la jungle ?", ["Rudyard Kipling", "Robert Louis Stevenson", "Lewis Carroll", "Jack London"], 0,
     "Publié en 1894, il vaudra à son auteur le prix Nobel de littérature en 1907."],
    ["Quelle série de romans de Lewis Carroll met en scène une fillette et un lapin pressé ?", ["Alice au pays des merveilles", "Peter Pan", "Le Magicien d'Oz", "Les Voyages de Gulliver"], 0,
     "Publié en 1865, il est né d'une histoire improvisée lors d'une promenade en barque."],
    ["Quelle autrice suédoise crée le personnage de Fifi Brindacier ?", ["Astrid Lindgren", "Selma Lagerlöf", "Tove Jansson", "Maria Gripe"], 0,
     "Publié en 1945, ce personnage d'enfant libre et forte a bousculé la littérature jeunesse de son temps."],
    ["Quel album de Maurice Sendak, paru en 1963, met en scène un enfant chez les monstres ?", ["Max et les Maximonstres", "Le Petit Prince", "Le Vent dans les saules", "Blaise et le château"], 0,
     "Longtemps jugé effrayant par des bibliothécaires, il est devenu un classique de l'album illustré.", 3],
  ]),

  notion("li-edition-livre", S, "Le livre et l'édition",
    "De l'imprimerie au format de poche : comment un texte devient un objet, et qui en détient les droits.",
    "L'auteur ne vend pas son œuvre : il cède des droits d'exploitation, pour une durée et un territoire donnés.",
    2, [
    ["Qui met au point l'imprimerie à caractères mobiles en Europe vers 1450 ?", ["Johannes Gutenberg", "Aldo Manuzio", "William Caxton", "Nicolas Jenson"], 0,
     "Le procédé existait en Chine et en Corée bien avant, mais son adaptation à l'alphabet latin change l'échelle."],
    ["Qu'est-ce qu'un incunable ?", ["Un livre imprimé avant 1501", "Un manuscrit enluminé", "Un livre à tirage unique", "Un ouvrage sans nom d'auteur"], 0,
     "Du latin incunabula, le berceau : les tout premiers pas de l'imprimerie."],
    ["Qu'est-ce que le dépôt légal ?", ["L'obligation de déposer un exemplaire de tout ouvrage publié", "L'enregistrement du droit d'auteur", "Le dépôt d'un manuscrit chez un notaire", "Une taxe sur l'édition"], 0,
     "Institué par François Ier en 1537, il alimente aujourd'hui les collections de la Bibliothèque nationale de France."],
    ["Combien de temps le droit d'auteur dure-t-il après la mort de l'auteur en France ?", ["Soixante-dix ans", "Cinquante ans", "Trente ans", "Cent ans"], 0,
     "Passé ce délai, l'œuvre entre dans le domaine public et peut être librement reproduite."],
    ["Que garantit la loi Lang de 1981 en France ?", ["Le prix unique du livre", "La gratuité des bibliothèques", "La TVA réduite sur le livre", "Le soutien aux librairies indépendantes"], 0,
     "L'éditeur fixe le prix ; le détaillant ne peut s'en écarter que de cinq pour cent."],
    ["Qu'est-ce que le droit moral d'un auteur ?", ["Un droit perpétuel et incessible sur la paternité et l'intégrité de l'œuvre", "Le droit d'être rémunéré", "Le droit de refuser une traduction", "Le droit de retirer son livre de la vente"], 0,
     "Il subsiste après l'entrée dans le domaine public et se transmet aux héritiers."],
    ["Qu'est-ce qu'un à-valoir dans un contrat d'édition ?", ["Une avance sur les droits d'auteur à venir", "Une prime de signature non remboursable", "Le prix d'achat du manuscrit", "Une garantie de tirage"], 0,
     "Il se déduit ensuite des droits générés par les ventes. Il n'est en général pas remboursable si le livre se vend mal."],
    ["Qu'est-ce que l'ISBN ?", ["Un numéro international identifiant une édition d'un livre", "Un code de classement en bibliothèque", "Un identifiant d'auteur", "Un numéro de dépôt légal"], 0,
     "Il change à chaque nouvelle édition ou format, ce qui permet de distinguer broché, poche et numérique."],
    ["Qu'est-ce que le format de poche ?", ["Une réédition à bas prix d'un titre déjà paru", "Un genre littéraire court", "Un livre de moins de deux cents pages", "Un livre publié sans éditeur"], 0,
     "Le Livre de Poche, lancé en 1953, a démocratisé l'accès aux classiques comme aux succès récents."],
    ["Qu'est-ce que le domaine public volontaire ?", ["Le choix d'un auteur de renoncer à ses droits patrimoniaux", "L'expiration anticipée du droit d'auteur", "La publication sans éditeur", "L'autorisation de photocopier une œuvre"], 0,
     "Les licences libres permettent de l'organiser juridiquement, sans que le droit moral puisse être abandonné.", 3],
  ]),

  notion("li-critique-lecture", S, "Lire, analyser, critiquer",
    "Narrateur, point de vue, registre : les outils qui permettent de parler précisément d'un texte.",
    "Le narrateur n'est pas l'auteur : c'est une voix construite à l'intérieur du récit.",
    2, [
    ["Qu'est-ce qu'un narrateur interne ?", ["Un narrateur qui raconte depuis le point de vue d'un personnage", "Un narrateur qui sait tout", "Un narrateur qui commente le récit", "L'auteur lui-même"], 0,
     "Le lecteur ne sait que ce que le personnage perçoit, ce qui permet de ménager le suspense."],
    ["Qu'est-ce qu'un narrateur omniscient ?", ["Un narrateur qui connaît les pensées de tous les personnages", "Un narrateur extérieur mais limité", "Un personnage secondaire", "Un narrateur non fiable"], 0,
     "Fréquent dans le roman du XIXe siècle, il s'efface largement au XXe."],
    ["Qu'est-ce que la focalisation externe ?", ["Le récit ne rapporte que ce qui est visible, sans accès aux pensées", "Le récit suit un seul personnage", "Le narrateur commente de l'extérieur", "Le récit alterne les points de vue"], 0,
     "Effet de caméra objective, souvent employé dans le roman policier ou le Nouveau Roman."],
    ["Qu'est-ce que le registre pathétique ?", ["Un registre qui cherche à émouvoir, à susciter la compassion", "Un registre comique", "Un registre solennel", "Un registre ironique"], 0,
     "Il se distingue du tragique, qui suppose une fatalité contre laquelle le héros ne peut rien."],
    ["Qu'est-ce que le registre épique ?", ["Un registre d'amplification qui grandit l'action et les personnages", "Un registre du récit historique", "Un registre guerrier", "Un registre solennel et funèbre"], 0,
     "Hyperboles, pluriels et forces surnaturelles en sont les marques. Zola l'emploie hors de tout contexte guerrier."],
    ["Qu'est-ce que l'ironie ?", ["Faire entendre le contraire de ce que l'on dit", "Se moquer ouvertement", "Exagérer un trait", "Employer un langage familier"], 0,
     "Elle suppose un accord tacite avec le lecteur, qui doit percevoir le décalage."],
    ["Qu'est-ce qu'une mise en abyme ?", ["Une œuvre contenant une reproduction d'elle-même", "Un récit sans fin", "Un retour en arrière", "Une digression"], 0,
     "Le théâtre dans le théâtre chez Shakespeare, ou le roman que le personnage écrit chez Gide."],
    ["Qu'est-ce qu'une analepse ?", ["Un retour en arrière dans le récit", "Une anticipation", "Une ellipse temporelle", "Une répétition d'un épisode"], 0,
     "La prolepse fait l'inverse : elle annonce un événement à venir."],
    ["Qu'est-ce qu'une ellipse narrative ?", ["Le récit passe sous silence une période de l'histoire", "Une phrase sans verbe", "Un résumé accéléré", "Un changement de narrateur"], 0,
     "Le sommaire, lui, résume rapidement une longue durée sans la supprimer."],
    ["Qu'est-ce que l'intertextualité ?", ["La présence d'un texte dans un autre, par citation ou allusion", "La comparaison de deux traductions", "La lecture croisée de deux auteurs", "Le dialogue entre un auteur et son lecteur"], 0,
     "La notion est forgée par Julia Kristeva en 1967, dans le sillage des travaux de Bakhtine.", 3],
  ]),

  notion("li-langues-traduction", S, "Traduire la littérature",
    "Ce qu'on gagne et ce qu'on perd à passer d'une langue à l'autre, et le statut du traducteur.",
    "Le traducteur est légalement un auteur : sa traduction est une œuvre protégée à part entière.",
    2, [
    ["Quel statut juridique la loi française reconnaît-elle au traducteur littéraire ?", ["Celui d'auteur d'une œuvre dérivée protégée", "Celui de prestataire technique", "Celui de coauteur de l'original", "Celui de salarié de l'éditeur"], 0,
     "Sa traduction est protégée par le droit d'auteur, indépendamment des droits sur le texte source."],
    ["Que désigne l'expression « les belles infidèles » ?", ["Des traductions élégantes mais éloignées de l'original", "Des traductions littérales", "Des traductions anonymes", "Des retraductions successives"], 0,
     "Formule du XVIIe siècle, appliquée aux traductions françaises qui adaptaient les Anciens au goût de la cour."],
    ["Qu'est-ce qu'un faux ami en traduction ?", ["Un mot ressemblant à un autre dans une autre langue mais de sens différent", "Un mot intraduisible", "Un emprunt mal orthographié", "Un archaïsme"], 0,
     "L'anglais actually signifie en réalité, non actuellement ; library est une bibliothèque, non une librairie."],
    ["Qu'est-ce qu'une traduction cibliste ?", ["Une traduction privilégiant la fluidité dans la langue d'arrivée", "Une traduction mot à mot", "Une traduction annotée", "Une traduction depuis une langue tierce"], 0,
     "La traduction sourcière, à l'inverse, garde les aspérités de la langue de départ."],
    ["Qu'est-ce qu'une retraduction ?", ["Une nouvelle traduction d'une œuvre déjà traduite", "Une traduction depuis une traduction", "Une révision par l'auteur", "Une traduction inversée"], 0,
     "Les classiques sont régulièrement retraduits, la langue et la lecture des œuvres évoluant."],
    ["Quel texte antique traduit en grec porte le nom de Septante ?", ["La Bible hébraïque", "L'Iliade", "Le Code de Hammurabi", "Les Dialogues de Platon"], 0,
     "Selon la légende, soixante-douze traducteurs y auraient travaillé séparément en aboutissant au même texte."],
    ["Quel érudit traduit la Bible en latin au IVe siècle ?", ["Saint Jérôme", "Saint Augustin", "Origène", "Érasme"], 0,
     "Sa Vulgate est restée la référence de l'Église latine pendant plus d'un millénaire. Il est le patron des traducteurs."],
    ["Quelle traduction de la Bible contribue à fixer l'allemand moderne ?", ["Celle de Martin Luther", "Celle d'Érasme", "Celle de Zwingli", "Celle de Melanchthon"], 0,
     "Publiée intégralement en 1534, elle choisit une langue accessible et unifie des usages régionaux disparates."],
    ["Qu'est-ce que la traduction automatique neuronale ?", ["Une traduction produite par un modèle statistique entraîné sur de grands corpus", "Une traduction assistée par dictionnaire", "Une traduction mot à mot automatisée", "Une relecture automatique"], 0,
     "Elle a nettement amélioré la fluidité depuis 2016, sans supprimer les erreurs de sens ou de registre."],
    ["Qu'appelle-t-on l'intraduisible en théorie de la traduction ?", ["Ce qui résiste au passage d'une langue à l'autre et oblige à choisir", "Un mot absent de la langue cible", "Un texte trop technique", "Un jeu de mots impossible à rendre"], 0,
     "Barbara Cassin en a fait le sujet d'un dictionnaire : l'intraduisible n'est pas ce qu'on ne traduit pas, mais ce qu'on ne cesse pas de traduire.", 3],
  ]),
];
