/**
 * Littérature, troisième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Littérature";

export const CG_LITTERATURE_3: SeedSkill[] = [
  notion("li3-montaigne-moralistes", S, "Montaigne et les moralistes",
    "Observer l'homme sans système : une tradition française.",
    "Les moralistes ne prêchent pas la morale : ils décrivent les mœurs.",
    2, [
    ["Que signifie le mot essai chez Montaigne ?", ["Une mise à l'épreuve de sa propre pensée", "Un exercice scolaire", "Une tentative littéraire ratée", "Un traité méthodique"], 0,
     "Il se peint lui-même comme sujet d'étude, ce qui était inédit."],
    ["Quelle devise Montaigne fait-il graver dans sa librairie ?", ["Que sais-je ?", "Connais-toi toi-même", "Rien de trop", "Vis caché"], 0,
     "Elle résume son scepticisme méthodique, hérité des philosophies antiques."],
    ["Quel ami de Montaigne écrit le Discours de la servitude volontaire ?", ["Étienne de La Boétie", "Pierre Charron", "Justus Lipsius", "Guillaume Du Vair"], 0,
     "Il y analyse pourquoi les peuples consentent à leur propre soumission."],
    ["Que sont les Pensées de Pascal ?", ["Des fragments d'une apologie du christianisme restée inachevée", "Un traité de physique", "Un journal personnel", "Un recueil de maximes mondaines"], 0,
     "Publiés après sa mort, leur ordre reste discuté par les éditeurs."],
    ["Qu'est-ce que le roseau pensant chez Pascal ?", ["Une image de la fragilité et de la grandeur de l'homme", "Une figure de la nature", "Une critique de la raison", "Un symbole religieux"], 0,
     "L'homme est le plus faible de la nature, mais il sait qu'il meurt : c'est là sa dignité."],
    ["Qu'est-ce qu'une maxime chez La Rochefoucauld ?", ["Une formule brève dévoilant l'amour-propre derrière les vertus", "Un proverbe populaire", "Un conseil de conduite", "Un précepte religieux"], 0,
     "Nos vertus ne sont le plus souvent que des vices déguisés, écrit-il en épigraphe."],
    ["Quel moraliste peint des types sociaux dans Les Caractères ?", ["La Bruyère", "La Rochefoucauld", "Vauvenargues", "Chamfort"], 0,
     "Ses portraits, souvent reconnaissables, lui valurent de solides inimitiés à la cour."],
    ["Quelle forme brève Chamfort pratique-t-il à la fin du XVIIIe siècle ?", ["La maxime et l'anecdote", "Le sonnet", "L'épître", "La fable"], 0,
     "Ses Maximes et pensées ont été publiées après sa mort pendant la Révolution."],
    ["Qu'est-ce que l'honnête homme au XVIIe siècle ?", ["Un idéal de sociabilité cultivée sans pédanterie", "Un homme vertueux", "Un homme de loi", "Un homme de cour"], 0,
     "Il doit savoir parler de tout sans jamais se poser en spécialiste."],
    ["Pourquoi parle-t-on de moralistes plutôt que de philosophes ?", ["Ils décrivent les mœurs sans construire de système", "Ils enseignent la morale", "Ils écrivent des sermons", "Ils sont hostiles à la philosophie"], 0,
     "Leur méthode est l'observation et la formule, non la démonstration.", 3],
  ]),

  notion("li3-fables-lafontaine", S, "La Fontaine et la fable",
    "Un genre ancien porté à sa perfection en français.",
    "La Fontaine emprunte presque toutes ses intrigues : son invention est dans la forme.",
    2, [
    ["Combien de fables La Fontaine a-t-il publiées ?", ["Environ deux cent quarante", "Une centaine", "Une cinquantaine", "Plus de cinq cents"], 0,
     "Réparties en douze livres publiés entre 1668 et 1694."],
    ["À qui La Fontaine emprunte-t-il l'essentiel de ses sujets ?", ["À Ésope, Phèdre et à des sources orientales", "À la tradition orale française", "À Homère", "À Virgile"], 0,
     "Le Pañchatantra indien lui a fourni plusieurs récits par des traductions successives."],
    ["Quelle fable oppose la prévoyance et l'insouciance ?", ["La Cigale et la Fourmi", "Le Corbeau et le Renard", "Le Loup et l'Agneau", "Le Lièvre et la Tortue"], 0,
     "La fourmi n'y est pas présentée comme un modèle : elle est décrite comme peu prêteuse."],
    ["Quelle fable illustre les effets de la flatterie ?", ["Le Corbeau et le Renard", "Le Loup et l'Agneau", "Le Chêne et le Roseau", "La Grenouille et le Bœuf"], 0,
     "Tout flatteur vit aux dépens de celui qui l'écoute."],
    ["Quelle fable s'ouvre sur la raison du plus fort ?", ["Le Loup et l'Agneau", "Le Renard et les Raisins", "Le Lion et le Rat", "Les Animaux malades de la peste"], 0,
     "La raison du plus fort est toujours la meilleure : la morale précède ici le récit."],
    ["Quelle fable montre la souplesse l'emporter sur la rigidité ?", ["Le Chêne et le Roseau", "Le Lièvre et la Tortue", "Le Rat de ville et le Rat des champs", "Le Chat et le Renard"], 0,
     "Je plie et ne romps pas, dit le roseau. Le chêne, lui, est déraciné."],
    ["Quelle fable dénonce l'injustice judiciaire selon le rang ?", ["Les Animaux malades de la peste", "Le Loup et le Chien", "La Cour du Lion", "Le Meunier, son fils et l'âne"], 0,
     "Selon que vous serez puissant ou misérable, les jugements de cour vous rendront blanc ou noir."],
    ["À qui le premier recueil des Fables est-il dédié ?", ["Au Dauphin, fils de Louis XIV", "À Louis XIV", "À Colbert", "À Fouquet"], 0,
     "La visée éducative affichée n'exclut pas une lecture politique pour les adultes."],
    ["Quel protecteur de La Fontaine tombe en disgrâce en 1661 ?", ["Nicolas Fouquet", "Colbert", "Le Grand Condé", "Mazarin"], 0,
     "Le poète lui resta fidèle, ce qui lui valut la défaveur durable du roi."],
    ["Pourquoi les fables mettent-elles en scène des animaux ?", ["Le détour animalier permet de critiquer sans nommer", "Elles s'adressent aux enfants", "La tradition l'impose", "Les animaux sont plus expressifs"], 0,
     "Ce voile de fiction rend dicibles des critiques du pouvoir et de la cour.", 3],
  ]),

  notion("li3-rousseau-lumieres", S, "Rousseau",
    "Une œuvre à contre-courant des Lumières dont elle procède.",
    "Rousseau est un homme des Lumières qui en conteste plusieurs présupposés.",
    2, [
    ["Que soutient Rousseau dans son premier discours de 1750 ?", ["Que le progrès des sciences et des arts a corrompu les mœurs", "Que la science améliore l'homme", "Que l'art doit être encouragé", "Que l'éducation est inutile"], 0,
     "Le paradoxe le rendit célèbre du jour au lendemain."],
    ["Qu'est-ce que l'état de nature chez Rousseau ?", ["Une hypothèse méthodologique sur l'homme avant la société", "Une période historique attestée", "Un idéal à retrouver", "Un état de guerre permanent"], 0,
     "Il précise lui-même qu'il s'agit d'un état qui n'a peut-être jamais existé."],
    ["Que dit Rousseau de l'origine de l'inégalité ?", ["Elle naît avec la propriété et la vie sociale", "Elle est naturelle", "Elle vient des différences de talent", "Elle est voulue par Dieu"], 0,
     "Le premier qui enclot un terrain et dit ceci est à moi, fondateur de la société civile."],
    ["Quelle est la thèse centrale du Contrat social ?", ["La souveraineté appartient au peuple et est inaliénable", "Le roi tient son pouvoir de Dieu", "Le pouvoir doit être partagé entre trois branches", "L'État doit être minimal"], 0,
     "L'homme est né libre et partout il est dans les fers, écrit-il en ouverture."],
    ["Qu'est-ce que la volonté générale chez Rousseau ?", ["La volonté du corps politique orientée vers l'intérêt commun", "La somme des volontés individuelles", "La volonté de la majorité", "La volonté du gouvernement"], 0,
     "Il la distingue expressément de la volonté de tous, simple addition d'intérêts particuliers."],
    ["Quel projet éducatif Rousseau expose-t-il dans Émile ?", ["Une éducation respectant les étapes du développement de l'enfant", "Une instruction encyclopédique précoce", "Une éducation religieuse", "Une formation professionnelle"], 0,
     "L'ouvrage fut condamné et brûlé, notamment pour sa profession de foi religieuse."],
    ["Quel roman épistolaire de Rousseau connaît un immense succès en 1761 ?", ["Julie ou la Nouvelle Héloïse", "Émile", "Les Confessions", "Les Rêveries"], 0,
     "L'un des plus grands succès de librairie du siècle, lu et pleuré dans toute l'Europe."],
    ["Quelle œuvre autobiographique Rousseau laisse-t-il inachevée ?", ["Les Rêveries du promeneur solitaire", "Les Confessions", "Les Dialogues", "L'Émile"], 0,
     "Il travaillait à la dixième promenade au moment de sa mort en 1778."],
    ["Quelle relation Rousseau entretient-il avec les philosophes des Lumières ?", ["Une rupture progressive et douloureuse", "Une collaboration constante", "Une indifférence mutuelle", "Une hostilité de principe dès l'origine"], 0,
     "Sa brouille avec Diderot puis avec Hume l'a laissé très isolé."],
    ["Quelle influence Rousseau a-t-il eue sur la Révolution française ?", ["Une influence considérable, revendiquée par les révolutionnaires", "Aucune", "Une influence tardive", "Une influence limitée à l'éducation"], 0,
     "Ses cendres ont été transférées au Panthéon en 1794.", 3],
  ]),

  notion("li3-romantisme-francais", S, "Le romantisme français",
    "Sensibilité, engagement, renouvellement des formes.",
    "Le romantisme français arrive plus tard qu'en Allemagne et en Angleterre.",
    2, [
    ["Quel écrivain publie René en 1802 ?", ["Chateaubriand", "Senancour", "Constant", "Nodier"], 0,
     "Il y définit le mal du siècle, cette mélancolie sans objet des jeunes gens de son temps."],
    ["Quel roman de Benjamin Constant analyse une passion sans issue ?", ["Adolphe", "René", "Obermann", "Corinne"], 0,
     "Publié en 1816, il est d'une sécheresse d'analyse remarquable pour l'époque."],
    ["Quelle femme de lettres introduit le romantisme allemand en France ?", ["Madame de Staël", "Madame de Genlis", "Madame de Duras", "George Sand"], 0,
     "Son ouvrage De l'Allemagne, publié en 1813, fut d'abord détruit sur ordre de Napoléon."],
    ["Quel recueil de Lamartine paraît en 1820 ?", ["Les Méditations poétiques", "Les Harmonies", "Jocelyn", "Les Recueillements"], 0,
     "Son succès immédiat marque l'entrée du lyrisme romantique dans la poésie française."],
    ["Quel poème de Lamartine évoque un lac et le temps qui fuit ?", ["Le Lac", "L'Isolement", "Le Vallon", "L'Automne"], 0,
     "Ô temps, suspends ton vol : l'un des vers les plus cités de la poésie française."],
    ["Quel poète romantique meurt jeune après une œuvre marquée par la douleur ?", ["Alfred de Musset", "Alfred de Vigny", "Gérard de Nerval", "Théophile Gautier"], 0,
     "Ses Nuits, écrites après sa rupture avec George Sand, sont son œuvre la plus connue."],
    ["Quelle romancière signe Indiana et La Mare au diable ?", ["George Sand", "Madame de Staël", "Marceline Desbordes-Valmore", "Delphine de Girardin"], 0,
     "Elle a écrit plus de soixante-dix romans et défendu l'émancipation des femmes."],
    ["Quelle poétesse romantique est saluée par Baudelaire et Verlaine ?", ["Marceline Desbordes-Valmore", "Delphine de Girardin", "Louise Colet", "Anaïs Ségalas"], 0,
     "Verlaine l'a incluse dans ses Poètes maudits, seule femme de la série."],
    ["Quel poète romantique sombre dans la folie et écrit Les Chimères ?", ["Gérard de Nerval", "Alfred de Vigny", "Alfred de Musset", "Théophile Gautier"], 0,
     "Ses sonnets hermétiques ont profondément marqué les surréalistes."],
    ["Quel poète romantique développe une méditation stoïcienne sur la solitude ?", ["Alfred de Vigny", "Lamartine", "Musset", "Nerval"], 0,
     "Seul le silence est grand, tout le reste est faiblesse, écrit-il dans La Mort du loup.", 3],
  ]),

  notion("li3-symbolisme-decadence", S, "Symbolisme et fin de siècle",
    "Suggérer plutôt que nommer : une révolution poétique.",
    "Le symbolisme cherche à suggérer l'idée par l'image plutôt qu'à la décrire.",
    2, [
    ["Quel poème de Baudelaire théorise les correspondances entre les sens ?", ["Correspondances", "L'Albatros", "Spleen", "Élévation"], 0,
     "Les parfums, les couleurs et les sons se répondent : le vers a fondé toute une esthétique."],
    ["Qui publie le Manifeste du symbolisme en 1886 ?", ["Jean Moréas", "Stéphane Mallarmé", "Paul Verlaine", "Gustave Kahn"], 0,
     "Publié dans Le Figaro, il donne son nom au mouvement."],
    ["Quel principe Verlaine énonce dans son Art poétique ?", ["De la musique avant toute chose", "De la clarté avant tout", "De la rime avant tout", "De la vérité avant tout"], 0,
     "Il y prône aussi l'impair et la nuance contre la couleur franche."],
    ["Quel recueil de Rimbaud est composé de poèmes en prose ?", ["Les Illuminations", "Le Bateau ivre", "Poésies", "Une saison en enfer"], 0,
     "Une saison en enfer mêle prose et vers dans une forme plus narrative."],
    ["Que réclame Rimbaud dans ses lettres dites du voyant ?", ["Un dérèglement de tous les sens pour atteindre l'inconnu", "Un retour à la clarté classique", "Une poésie engagée", "Une poésie savante"], 0,
     "Je est un autre : la formule a été indéfiniment commentée depuis."],
    ["Quel poète refuse la description et veut céder l'initiative aux mots ?", ["Stéphane Mallarmé", "Paul Verlaine", "Arthur Rimbaud", "Jules Laforgue"], 0,
     "Peindre non la chose mais l'effet qu'elle produit, écrivait-il."],
    ["Quel roman de Huysmans est le bréviaire de la décadence ?", ["À rebours", "Là-bas", "En rade", "Marthe"], 0,
     "Son héros vit reclus dans un univers entièrement artificiel."],
    ["Quel dramaturge belge écrit Pelléas et Mélisande ?", ["Maurice Maeterlinck", "Émile Verhaeren", "Georges Rodenbach", "Charles Van Lerberghe"], 0,
     "Prix Nobel en 1911, il est l'un des rares dramaturges symbolistes joués durablement."],
    ["Quel roman de Villiers de L'Isle-Adam met en scène une créature artificielle ?", ["L'Ève future", "Axël", "Les Contes cruels", "Tribulat Bonhomet"], 0,
     "Le mot andréide, qu'il y emploie, a donné notre androïde."],
    ["Qu'est-ce que la synesthésie en poésie symboliste ?", ["L'association de sensations relevant de sens différents", "Une figure de répétition", "Une rime intérieure", "Un vers libre"], 0,
     "Le sonnet des Voyelles de Rimbaud en est l'exemple le plus commenté.", 3],
  ]),

  notion("li3-theatre-xxe", S, "Le théâtre du XXe siècle",
    "Ruptures, mises en scène, écritures contemporaines.",
    "Le XXe siècle voit le metteur en scène devenir l'auteur du spectacle.",
    2, [
    ["Quelle pièce d'Alfred Jarry fait scandale en 1896 ?", ["Ubu roi", "Ubu enchaîné", "Les Minutes de sable mémorial", "César-Antéchrist"], 0,
     "Son premier mot, une grossièreté déformée, provoqua un tumulte dans la salle."],
    ["Quel dramaturge italien met en scène des personnages en quête d'auteur ?", ["Luigi Pirandello", "Gabriele D'Annunzio", "Eduardo De Filippo", "Dario Fo"], 0,
     "Six personnages en quête d'auteur, en 1921, met en crise la représentation elle-même."],
    ["Quelle pièce de Jean Giraudoux évoque un conflit annoncé en 1935 ?", ["La guerre de Troie n'aura pas lieu", "Ondine", "Électre", "Amphitryon 38"], 0,
     "Créée quatre ans avant la Seconde Guerre mondiale, elle prend une résonance particulière."],
    ["Quelle pièce d'Anouilh reprend un mythe grec sous l'Occupation ?", ["Antigone", "Le Bal des voleurs", "Becket", "L'Alouette"], 0,
     "Créée en 1944, elle a été lue à la fois comme un texte de résistance et de compromis."],
    ["Quel dramaturge écrit La Cantatrice chauve et Rhinocéros ?", ["Eugène Ionesco", "Samuel Beckett", "Arthur Adamov", "Jean Genet"], 0,
     "Rhinocéros, en 1959, met en scène la contagion des idéologies totalitaires."],
    ["Quelle pièce de Jean Genet met en scène deux domestiques ?", ["Les Bonnes", "Le Balcon", "Les Nègres", "Les Paravents"], 0,
     "Créée en 1947, elle repose sur un jeu de rôles vertigineux entre maîtresse et servantes."],
    ["Quel metteur en scène allemand théorise le théâtre épique ?", ["Bertolt Brecht", "Max Reinhardt", "Erwin Piscator seul", "Peter Stein"], 0,
     "Il veut un spectateur critique plutôt qu'un spectateur ému."],
    ["Quelle troupe française fondée en 1964 pratique la création collective ?", ["Le Théâtre du Soleil", "La Comédie-Française", "Le Théâtre de la Ville", "Le Théâtre de l'Odéon"], 0,
     "Ariane Mnouchkine y a développé un fonctionnement coopératif durable."],
    ["Quelle dramaturge française contemporaine est l'une des plus jouées dans le monde ?", ["Yasmina Reza", "Marguerite Duras", "Nathalie Sarraute", "Hélène Cixous"], 0,
     "Art, créée en 1994, a été traduite dans plus de trente langues."],
    ["Qu'est-ce que le théâtre documentaire contemporain ?", ["Un théâtre construit à partir de matériaux réels, enquêtes et témoignages", "Un théâtre historique", "Un théâtre de reconstitution", "Un théâtre filmé"], 0,
     "Il pose la question du statut de la parole rapportée sur scène.", 3],
  ]),

  notion("li3-roman-contemporain", S, "Le roman contemporain",
    "Formes, thèmes, auteurs depuis les années 1980.",
    "Le roman contemporain français mêle volontiers enquête, récit de soi et histoire collective.",
    2, [
    ["Quel écrivain français reçoit le prix Nobel de littérature en 2014 ?", ["Patrick Modiano", "Jean-Marie Gustave Le Clézio", "Michel Houellebecq", "Pierre Michon"], 0,
     "Le Clézio l'avait reçu en 2008."],
    ["Quel thème traverse l'œuvre de Patrick Modiano ?", ["La mémoire trouée de l'Occupation et l'identité incertaine", "La vie provinciale", "L'aventure coloniale", "La satire sociale"], 0,
     "Ses romans mêlent enquête sur le passé et déambulation dans Paris."],
    ["Quel écrivain a écrit Les Bienveillantes en 2006 ?", ["Jonathan Littell", "Laurent Binet", "Yannick Haenel", "Pierre Assouline"], 0,
     "Le roman, écrit en français par un auteur américain, adopte le point de vue d'un officier SS."],
    ["Quel roman de Laurent Binet raconte l'attentat contre Heydrich ?", ["HHhH", "La Septième Fonction du langage", "Civilizations", "Perspectives"], 0,
     "Il y interroge en permanence la légitimité de romancer des faits historiques."],
    ["Quelle écrivaine française explore la mémoire familiale et sociale ?", ["Annie Ernaux", "Marie Darrieussecq", "Christine Angot", "Delphine de Vigan"], 0,
     "Les Années, publié en 2008, mêle mémoire personnelle et histoire collective."],
    ["Quel écrivain français est connu pour ses romans sur la solitude contemporaine ?", ["Michel Houellebecq", "Emmanuel Carrère", "Philippe Djian", "Jean Echenoz"], 0,
     "Ses livres suscitent des débats aussi vifs sur leur contenu que sur leur forme."],
    ["Quel écrivain brouille les frontières entre enquête, biographie et récit de soi ?", ["Emmanuel Carrère", "Patrick Deville", "Éric Vuillard", "Jean Rolin"], 0,
     "L'Adversaire, en 2000, part d'un fait divers criminel réel."],
    ["Quel prix Goncourt de 2017 raconte une réunion d'industriels allemands en 1933 ?", ["L'Ordre du jour", "Leurs enfants après eux", "Au revoir là-haut", "L'Anomalie"], 0,
     "Éric Vuillard y pratique un récit historique très resserré, à la lisière de l'essai."],
    ["Quel roman de 2020 mêle thriller, science-fiction et réflexion sur le double ?", ["L'Anomalie", "Le Lambeau", "Chanson douce", "Leurs enfants après eux"], 0,
     "Hervé Le Tellier, membre de l'Oulipo, y multiplie les pastiches de genres."],
    ["Quelle tendance marque le roman français contemporain ?", ["Un fort retour du récit du réel et de l'enquête", "Un abandon de la narration", "Un retour au roman historique classique", "Un rejet de l'autobiographie"], 0,
     "Le succès des non-fictions littéraires en témoigne depuis une vingtaine d'années.", 3],
  ]),

  notion("li3-poesie-contemporaine", S, "La poésie depuis 1945",
    "Voix, formes, circuits de diffusion.",
    "La poésie contemporaine se lit peu mais s'écoute et se performe davantage.",
    2, [
    ["Quel poète français publie Fureur et Mystère en 1948 ?", ["René Char", "Francis Ponge", "Henri Michaux", "Pierre Reverdy"], 0,
     "Ancien chef de maquis, il y mêle aphorismes et poèmes issus de la Résistance."],
    ["Quel poète belge d'expression française explore les états intérieurs ?", ["Henri Michaux", "Jean Follain", "Guillevic", "André Frénaud"], 0,
     "Il a aussi mené des expériences sur les effets des hallucinogènes sur la création."],
    ["Que cherche Francis Ponge en décrivant un cageot ou un galet ?", ["Donner la parole aux objets en évitant le lyrisme du moi", "Faire l'éloge du travail manuel", "Renouveler l'alexandrin par la prose", "Décrire la nature pour elle-même"], 0,
     "Le poème imite alors la chose : Le Cageot tient en trois paragraphes, comme la caissette qu'il décrit."],
    ["Quel poète suisse de langue française cherche une écriture de la retenue ?", ["Philippe Jaccottet", "Yves Bonnefoy", "Jacques Dupin", "André du Bouchet"], 0,
     "Son œuvre est entrée dans la Pléiade de son vivant, cas rare."],
    ["Quel poète français a beaucoup traduit Shakespeare ?", ["Yves Bonnefoy", "Francis Ponge", "Michel Deguy", "Jacques Roubaud"], 0,
     "Il tenait la traduction pour une part entière de son travail poétique."],
    ["Quel mathématicien et poète français est membre de l'Oulipo ?", ["Jacques Roubaud", "Michel Deguy", "Bernard Noël", "Claude Royet-Journoud"], 0,
     "Il a notamment travaillé la forme du sonnet selon des contraintes formelles strictes."],
    ["Qu'est-ce que la poésie sonore ?", ["Une poésie conçue pour la voix et l'enregistrement", "Une poésie chantée", "Une poésie musicale", "Une poésie déclamée classiquement"], 0,
     "Bernard Heidsieck et Henri Chopin en sont des figures françaises majeures."],
    ["Qu'est-ce que le slam ?", ["Une poésie orale déclamée en public, souvent en tournoi", "Une chanson à texte", "Un rap poétique", "Une lecture publique de poèmes"], 0,
     "Né à Chicago en 1984, il repose sur une règle simple : trois minutes, sans accessoire."],
    ["Comment la poésie contemporaine se diffuse-t-elle principalement ?", ["Par de petites maisons d'édition, des revues et des lectures publiques", "Par les grandes maisons d'édition", "Par la presse quotidienne", "Par les librairies généralistes"], 0,
     "Les tirages dépassent rarement quelques centaines d'exemplaires."],
    ["Qu'est-ce que le Printemps des poètes ?", ["Une manifestation nationale annuelle de promotion de la poésie", "Un prix littéraire", "Un festival international", "Une revue de poésie"], 0,
     "Créé en 1999, il propose chaque année un thème fédérateur.", 3],
  ]),

  notion("li3-litterature-jeunesse-2", S, "La littérature de jeunesse contemporaine",
    "Albums, romans, questions éditoriales.",
    "La littérature de jeunesse est l'un des secteurs les plus dynamiques de l'édition française.",
    2, [
    ["Quelle part du marché du livre la littérature de jeunesse représente-t-elle en France ?", ["Une part importante, autour d'un cinquième", "Une part marginale", "La moitié", "Environ cinq pour cent"], 0,
     "C'est l'un des rares segments dont les ventes résistent bien."],
    ["Qu'est-ce qu'un album jeunesse ?", ["Un livre où texte et image forment un récit indissociable", "Un livre illustré", "Un livre cartonné pour tout-petits", "Un recueil de contes"], 0,
     "L'image n'y illustre pas le texte : elle raconte avec lui, parfois contre lui."],
    ["Quel album de Tomi Ungerer met en scène des brigands ?", ["Les Trois Brigands", "Jean de la Lune", "Otto", "Flix"], 0,
     "Son œuvre, longtemps controversée, refuse l'édulcoration des sujets difficiles."],
    ["Quelle maison d'édition française a marqué l'album jeunesse depuis 1965 ?", ["L'École des loisirs", "Gallimard Jeunesse", "Bayard", "Nathan"], 0,
     "Elle a fait connaître en France de nombreux auteurs étrangers exigeants."],
    ["Quelle série britannique de sept romans a relancé la lecture chez les jeunes ?", ["Harry Potter", "À la croisée des mondes", "Le Seigneur des anneaux", "Les Chroniques de Narnia"], 0,
     "Plus de cinq cents millions d'exemplaires vendus dans le monde."],
    ["Qu'est-ce que la littérature pour jeunes adultes ?", ["Un segment éditorial visant les adolescents et jeunes adultes", "Un genre littéraire précis", "Une littérature scolaire", "Un rayon de bibliothèque"], 0,
     "Il s'est structuré comme catégorie commerciale dans les années 2000."],
    ["Qu'est-ce que la loi de 1949 sur les publications destinées à la jeunesse ?", ["Un texte encadrant le contenu des publications pour mineurs", "Une loi sur l'édition scolaire", "Une loi sur les bibliothèques", "Une loi sur le prix du livre jeunesse"], 0,
     "Longtemps utilisée pour censurer certaines publications, elle reste en vigueur sous une forme révisée."],
    ["Qu'est-ce qu'un livre-jeu dont vous êtes le héros ?", ["Un récit à embranchements où le lecteur choisit la suite", "Un livre avec des jeux", "Un livre interactif numérique", "Un roman illustré"], 0,
     "Le format, popularisé dans les années 1980, a connu un net regain récent."],
    ["Qu'est-ce que le prix des Incorruptibles ?", ["Un prix littéraire jeunesse décerné par les jeunes lecteurs eux-mêmes", "Un prix de la critique", "Un prix d'illustration", "Un prix des libraires"], 0,
     "Des centaines de milliers d'élèves y participent chaque année."],
    ["Pourquoi la lecture recule-t-elle chez les adolescents ?", ["La concurrence des écrans et des autres loisirs mobilise leur temps libre", "Les livres sont trop chers", "L'offre est insuffisante", "L'école décourage la lecture"], 0,
     "Les enquêtes montrent un recul du temps consacré à la lecture, non une disparition de la pratique.", 3],
  ]),

  notion("li3-romans-graphiques", S, "Roman graphique et récits illustrés",
    "Un format qui a élargi le public de la bande dessinée.",
    "Le roman graphique a permis à la bande dessinée d'aborder des sujets réservés au livre.",
    2, [
    ["Qu'est-ce qu'un roman graphique ?", ["Un récit long en bande dessinée, souvent destiné à un lectorat adulte", "Une bande dessinée illustrée", "Un roman avec des images", "Une adaptation de roman en bande dessinée"], 0,
     "Le terme désigne plus un format éditorial et un public qu'un genre précis."],
    ["Quelle autrice iranienne raconte son enfance à Téhéran en bande dessinée ?", ["Marjane Satrapi", "Zeina Abirached", "Riad Sattouf", "Rutu Modan"], 0,
     "Persepolis, publié à partir de 2000, a été adapté au cinéma en 2007."],
    ["Quelle série de Riad Sattouf raconte une enfance entre France et Syrie ?", ["L'Arabe du futur", "Les Cahiers d'Esther", "La Vie secrète des jeunes", "Pascal Brutal"], 0,
     "Six tomes, traduits dans une vingtaine de langues."],
    ["Quel auteur américain a reçu le Pulitzer pour un récit sur la Shoah ?", ["Art Spiegelman", "Chris Ware", "Will Eisner", "Joe Sacco"], 0,
     "Maus, achevé en 1991, a obtenu un prix spécial en 1992."],
    ["Quel auteur est considéré comme un pionnier du roman graphique américain ?", ["Will Eisner", "Jack Kirby", "Robert Crumb", "Harvey Kurtzman"], 0,
     "Un pacte avec Dieu, en 1978, popularise l'expression graphic novel."],
    ["Quel auteur pratique le reportage en bande dessinée ?", ["Joe Sacco", "Art Spiegelman", "Chris Ware", "Daniel Clowes"], 0,
     "Palestine et Gorazde reposent sur un travail d'enquête de terrain de plusieurs mois."],
    ["Quelle collection française a contribué à légitimer la bande dessinée d'auteur ?", ["L'Association", "Casterman jeunesse", "Delcourt", "Soleil"], 0,
     "Fondée en 1990, elle a publié Persepolis et de nombreux récits en noir et blanc."],
    ["Qu'est-ce que la bande dessinée documentaire ?", ["Un récit dessiné fondé sur une enquête ou des faits vérifiés", "Une bande dessinée historique", "Une adaptation de documentaire", "Une bande dessinée pédagogique"], 0,
     "Elle pose les mêmes questions déontologiques que le journalisme écrit."],
    ["Qu'est-ce que la bande dessinée de vulgarisation scientifique ?", ["Un récit dessiné expliquant des savoirs scientifiques", "Une bande dessinée de science-fiction", "Un manuel illustré", "Une bande dessinée éducative pour enfants"], 0,
     "Le genre connaît un fort développement en France depuis les années 2010."],
    ["Quel effet le roman graphique a-t-il eu sur le statut de la bande dessinée ?", ["Il a favorisé sa reconnaissance en librairie générale et en bibliothèque", "Il l'a coupée de son public", "Il a réduit sa diffusion", "Il n'a rien changé"], 0,
     "Les rayons de librairie et les prix littéraires généralistes s'y sont progressivement ouverts.", 3],
  ]),

  notion("li3-litterature-russe", S, "La littérature russe",
    "Un siècle d'or et ses prolongements.",
    "La littérature russe du XIXe siècle a été écrite pour l'essentiel en une soixantaine d'années.",
    2, [
    ["Quel poète est considéré comme le fondateur de la littérature russe moderne ?", ["Alexandre Pouchkine", "Mikhaïl Lermontov", "Nicolas Gogol", "Ivan Krylov"], 0,
     "Eugène Onéguine, roman en vers, est son œuvre la plus célèbre."],
    ["Quel roman de Gogol met en scène un escroc achetant des serfs décédés ?", ["Les Âmes mortes", "Le Manteau", "Le Revizor", "Tarass Boulba"], 0,
     "Il a brûlé la seconde partie de son roman peu avant sa mort."],
    ["Quelle nouvelle de Gogol a marqué toute la littérature russe ultérieure ?", ["Le Manteau", "Le Nez", "Le Journal d'un fou", "La Perspective Nevski"], 0,
     "Nous sommes tous sortis du Manteau de Gogol, aurait dit Dostoïevski."],
    ["Quel roman de Tourgueniev met en scène un nihiliste ?", ["Pères et Fils", "Premier Amour", "Récits d'un chasseur", "Terres vierges"], 0,
     "Le mot nihiliste s'est diffusé dans toute l'Europe à partir de ce roman de 1862."],
    ["Quel roman de Tolstoï met en scène une femme adultère dans la haute société ?", ["Anna Karénine", "Guerre et Paix", "Résurrection", "La Sonate à Kreutzer"], 0,
     "Sa première phrase sur les familles heureuses est l'une des plus citées de la littérature."],
    ["Quel roman de Dostoïevski met en scène un parricide et un procès ?", ["Les Frères Karamazov", "Crime et Châtiment", "L'Idiot", "Les Démons"], 0,
     "Son chapitre du Grand Inquisiteur est étudié comme un texte philosophique à part entière."],
    ["Quel dramaturge russe écrit La Cerisaie et La Mouette ?", ["Anton Tchekhov", "Alexandre Ostrovski", "Maxime Gorki", "Nikolaï Erdman"], 0,
     "Médecin de formation, il est aussi l'auteur de centaines de nouvelles."],
    ["Quel roman soviétique n'a pu être publié qu'à l'étranger en 1957 ?", ["Le Docteur Jivago", "Le Maître et Marguerite", "Une journée d'Ivan Denissovitch", "Vie et Destin"], 0,
     "Pasternak dut refuser le prix Nobel sous la pression des autorités soviétiques."],
    ["Quel roman de Boulgakov mêle satire soviétique et fantastique ?", ["Le Maître et Marguerite", "Cœur de chien", "La Garde blanche", "Les Œufs fatidiques"], 0,
     "Écrit dans les années 1930, il n'a été publié intégralement qu'en 1973."],
    ["Quel écrivain russe publie L'Archipel du Goulag, enquête d'ensemble sur le système concentrationnaire ?", ["Alexandre Soljenitsyne", "Varlam Chalamov", "Vassili Grossman", "Evguénia Guinzbourg"], 0,
     "Publié à l'Ouest en 1973, il vaut à son auteur l'expulsion d'URSS l'année suivante. Chalamov, Grossman et Guinzbourg ont témoigné du même monde sous d'autres formes.", 3],
  ]),

  notion("li3-litterature-orientale", S, "Littératures d'Asie et du monde arabe",
    "Traditions poétiques et récits classiques.",
    "La poésie arabe classique repose sur des formes fixées dès l'époque préislamique.",
    2, [
    ["Qu'est-ce qu'une qasida dans la poésie arabe ?", ["Un long poème monorime à structure codifiée", "Un poème d'amour bref", "Un chant religieux", "Une épopée guerrière"], 0,
     "Elle comporte traditionnellement une ouverture élégiaque devant un campement abandonné."],
    ["Quel poète persan du XIIIe siècle est un maître du soufisme ?", ["Rûmî", "Hafez", "Saadi", "Omar Khayyam"], 0,
     "Son Masnavi est parfois appelé le Coran persan par ses lecteurs."],
    ["Quel poète persan est célèbre pour ses quatrains ?", ["Omar Khayyam", "Rûmî", "Ferdowsi", "Nizami"], 0,
     "Également mathématicien et astronome, il a réformé le calendrier persan."],
    ["Quelle épopée persane raconte l'histoire des rois d'Iran ?", ["Le Livre des rois de Ferdowsi", "Le Masnavi", "Le Divan de Hafez", "Le Golestan"], 0,
     "Environ soixante mille distiques, composés sur trente ans autour de l'an mille."],
    ["Quelle forme poétique japonaise compte dix-sept syllabes ?", ["Le haïku", "Le tanka", "Le renga", "Le waka"], 0,
     "Le tanka en compte trente et une, réparties en cinq segments."],
    ["Quel poète japonais du XVIIe siècle a porté le haïku à sa maturité ?", ["Matsuo Bashō", "Yosa Buson", "Kobayashi Issa", "Masaoka Shiki"], 0,
     "Son journal de voyage La Sente étroite du Bout-du-Monde mêle prose et haïkus."],
    ["Quel roman chinois du XVIIIe siècle décrit le déclin d'une grande famille ?", ["Le Rêve dans le pavillon rouge", "Au bord de l'eau", "Les Trois Royaumes", "La Pérégrination vers l'Ouest"], 0,
     "Il est l'objet d'un champ d'études universitaire à part entière en Chine."],
    ["Quel roman chinois raconte les exploits de cent huit hors-la-loi ?", ["Au bord de l'eau", "Les Trois Royaumes", "Le Rêve dans le pavillon rouge", "Jin Ping Mei"], 0,
     "Il a inspiré d'innombrables adaptations théâtrales, cinématographiques et vidéoludiques."],
    ["Quel écrivain égyptien reçoit le prix Nobel de littérature en 1988 ?", ["Naguib Mahfouz", "Taha Hussein", "Tawfiq al-Hakim", "Youssef Idris"], 0,
     "Premier écrivain de langue arabe distingué. Sa Trilogie du Caire est son œuvre majeure."],
    ["Quel poète palestinien est l'une des grandes voix arabes du XXe siècle ?", ["Mahmoud Darwich", "Adonis", "Nizar Kabbani", "Badr Chaker es-Sayyab"], 0,
     "Son œuvre mêle exil, terre et amour, avec un immense écho dans le monde arabe.", 3],
  ]),

  notion("li3-litterature-italienne", S, "La littérature italienne",
    "Dante, Renaissance, modernité.",
    "Dante a largement fixé la langue italienne écrite en choisissant le toscan.",
    2, [
    ["De combien de parties la Divine Comédie est-elle composée ?", ["Trois", "Deux", "Quatre", "Cinq"], 0,
     "Enfer, Purgatoire, Paradis, chacune de trente-trois chants plus un prologue."],
    ["Qui guide Dante dans l'Enfer et le Purgatoire ?", ["Virgile", "Béatrice", "Saint Bernard", "Homère"], 0,
     "Béatrice le guide au Paradis, où Virgile, païen, ne peut le suivre."],
    ["Quel poète italien du XIVe siècle a donné son nom à une forme de sonnet ?", ["Pétrarque", "Dante", "Boccace", "Politien"], 0,
     "Son Canzoniere a fixé un modèle amoureux imité dans toute l'Europe."],
    ["Quel recueil de Boccace met en scène des conteurs fuyant la peste ?", ["Le Décaméron", "Le Canzoniere", "La Vita nuova", "Le Roland furieux"], 0,
     "Cent nouvelles racontées en dix jours par dix jeunes gens réfugiés à la campagne."],
    ["Quel traité politique Machiavel écrit-il en 1513 ?", ["Le Prince", "Les Discours", "L'Art de la guerre", "La Mandragore"], 0,
     "Son nom a donné un adjectif qui trahit largement la complexité de sa pensée."],
    ["Quel poème épique de l'Arioste met en scène un chevalier devenu fou ?", ["Le Roland furieux", "La Jérusalem délivrée", "Le Morgant", "L'Orlando innamorato"], 0,
     "Publié en 1516, il mêle chevalerie, magie et ironie constante."],
    ["Quel roman italien du XIXe siècle est un classique scolaire national ?", ["Les Fiancés de Manzoni", "Le Guépard", "Le Journal de Pinocchio", "Les Malavoglia"], 0,
     "Sa langue a servi de modèle pour l'unification linguistique italienne."],
    ["Quel roman de Lampedusa décrit la fin de l'aristocratie sicilienne ?", ["Le Guépard", "Les Fiancés", "Les Malavoglia", "Le Désert des Tartares"], 0,
     "Publié après la mort de son auteur en 1958, il fut d'abord refusé par les éditeurs."],
    ["Quel écrivain italien a écrit Le Nom de la rose ?", ["Umberto Eco", "Italo Calvino", "Dino Buzzati", "Leonardo Sciascia"], 0,
     "Sémiologue de formation, il a écrit ce roman à quarante-huit ans."],
    ["Quelle écrivaine italienne contemporaine publie sous pseudonyme la saga L'Amie prodigieuse ?", ["Elena Ferrante", "Natalia Ginzburg", "Dacia Maraini", "Elsa Morante"], 0,
     "Son identité réelle n'a jamais été confirmée malgré plusieurs enquêtes journalistiques.", 3],
  ]),

  notion("li3-essais-idees", S, "Essais et littérature d'idées",
    "Penser par écrit hors du traité philosophique.",
    "L'essai occupe en France une place que peu de littératures accordent au même degré.",
    2, [
    ["Quel essai de Sartre paraît en 1943 ?", ["L'Être et le Néant", "La Nausée", "Les Mots", "Critique de la raison dialectique"], 0,
     "Il y développe une ontologie phénoménologique de la conscience et de la liberté."],
    ["Quel essai de Roland Barthes analyse les mythologies contemporaines ?", ["Mythologies", "Le Degré zéro de l'écriture", "S/Z", "La Chambre claire"], 0,
     "Publié en 1957, il décrypte publicité, catch, automobile et faits divers."],
    ["Quel essai de Michel Foucault porte sur la prison ?", ["Surveiller et punir", "Histoire de la folie", "Les Mots et les Choses", "L'Archéologie du savoir"], 0,
     "Publié en 1975, il analyse la naissance d'une société disciplinaire."],
    ["Quel ouvrage de Pierre Bourdieu analyse les goûts comme marqueurs sociaux ?", ["La Distinction", "Les Héritiers", "La Misère du monde", "Le Sens pratique"], 0,
     "Publié en 1979, il montre que les préférences esthétiques sont socialement structurées."],
    ["Quel essai de Claude Lévi-Strauss mêle récit de voyage et anthropologie ?", ["Tristes Tropiques", "La Pensée sauvage", "Les Structures élémentaires de la parenté", "Anthropologie structurale"], 0,
     "Il s'ouvre sur une phrase célèbre : Je hais les voyages et les explorateurs."],
    ["Quel essai de Simone Weil porte sur la condition ouvrière ?", ["La Condition ouvrière", "L'Enracinement", "La Pesanteur et la Grâce", "Oppression et Liberté"], 0,
     "Elle avait travaillé en usine pour éprouver ce dont elle voulait parler."],
    ["Quel essai d'Hannah Arendt analyse les régimes totalitaires ?", ["Les Origines du totalitarisme", "La Condition de l'homme moderne", "Eichmann à Jérusalem", "La Crise de la culture"], 0,
     "Publié en 1951, il rapproche nazisme et stalinisme par leur structure plus que par leur idéologie."],
    ["Quelle notion Hannah Arendt forge-t-elle à propos d'Eichmann ?", ["La banalité du mal", "La raison d'État", "L'obéissance aveugle", "L'homme de masse"], 0,
     "L'expression a été très discutée, y compris sur la lecture qu'elle fait du personnage."],
    ["Quel essai d'Edward Said analyse la représentation occidentale de l'Orient ?", ["L'Orientalisme", "Culture et Impérialisme", "Réflexions sur l'exil", "Des intellectuels et du pouvoir"], 0,
     "Publié en 1978, il a fondé un champ d'études entier."],
    ["Quel essai de Simone de Beauvoir analyse la construction du féminin ?", ["Le Deuxième Sexe", "Pour une morale de l'ambiguïté", "La Vieillesse", "Les Mandarins"], 0,
     "Il fut mis à l'index par le Vatican et vivement attaqué à sa parution en 1949.", 3],
  ]),

  notion("li3-correspondances-journaux", S, "Correspondances et journaux",
    "Écrire sans destinataire public.",
    "Une correspondance n'est pas écrite pour être publiée : c'est ce qui en fait le prix et la difficulté.",
    2, [
    ["Quelle épistolière du XVIIe siècle écrit à sa fille pendant vingt-cinq ans ?", ["Madame de Sévigné", "Madame de La Fayette", "Madame de Maintenon", "Madame de Sablé"], 0,
     "Plus de mille lettres conservées, publiées après sa mort."],
    ["Quel écrivain entretient une correspondance abondante avec George Sand ?", ["Gustave Flaubert", "Victor Hugo", "Honoré de Balzac", "Alfred de Musset"], 0,
     "Leurs échanges portent autant sur l'écriture que sur la politique."],
    ["Quel peintre a laissé une correspondance devenue un classique littéraire ?", ["Vincent van Gogh", "Paul Cézanne", "Claude Monet", "Edgar Degas"], 0,
     "Ses lettres à son frère Théo forment un document exceptionnel sur la création."],
    ["Quel journal d'écrivain couvre plus de cinquante ans au XXe siècle ?", ["Le Journal d'André Gide", "Le Journal de Jules Renard", "Les Cahiers de Paul Valéry", "Le Journal de Kafka"], 0,
     "Publié partiellement de son vivant, ce qui pose la question de son statut."],
    ["Quel journal d'un écrivain du XIXe siècle est célèbre pour son ironie ?", ["Le Journal de Jules Renard", "Le Journal des Goncourt", "Le Journal d'Amiel", "Le Journal de Delacroix"], 0,
     "Le Journal des Goncourt documente en revanche minutieusement la vie littéraire parisienne."],
    ["Qu'est-ce qu'un journal de deuil ?", ["Un carnet tenu après la perte d'un proche", "Un journal de guerre", "Un registre funéraire", "Un recueil d'hommages"], 0,
     "Roland Barthes en a laissé un, écrit après la mort de sa mère et publié en 2009."],
    ["Quelle question éthique la publication d'une correspondance pose-t-elle ?", ["Le respect de l'intimité de l'auteur et de ses correspondants", "Le droit d'auteur seul", "L'authenticité des lettres", "La qualité littéraire"], 0,
     "Les tiers cités n'ont jamais consenti à cette publication, contrairement à l'auteur."],
    ["Qu'est-ce qu'un carnet d'écrivain ?", ["Un support de notes préparatoires et de fragments", "Un journal intime", "Un cahier de brouillons", "Un agenda de travail"], 0,
     "Leur étude relève de la génétique littéraire, qui reconstitue le travail de création."],
    ["Qu'est-ce que la critique génétique ?", ["L'étude des manuscrits pour reconstituer la genèse d'une œuvre", "L'analyse des sources d'un auteur", "L'étude des influences", "Une analyse biographique"], 0,
     "Elle s'est développée en France à partir des années 1970 autour de fonds de manuscrits."],
    ["Que devient une correspondance à la mort de son auteur ?", ["Elle relève des héritiers et du droit moral", "Elle tombe dans le domaine public", "Elle appartient aux destinataires", "Elle devient publiable librement"], 0,
     "Les lettres appartiennent matériellement au destinataire, mais leur contenu reste protégé.", 3],
  ]),

  notion("li3-litterature-engagement", S, "Littérature et engagement",
    "Écrire dans la cité : formes et débats.",
    "L'engagement littéraire ne se réduit pas au contenu politique d'un texte.",
    2, [
    ["Quel genre Sartre exclut-il de la littérature engagée ?", ["La poésie", "Le théâtre", "L'essai", "Le roman"], 0,
     "Il estime que le poète traite les mots comme des choses et non comme des signes. De nombreux poètes ont contesté cette exclusion."],
    ["Quel poème d'Aragon devient un chant de résistance ?", ["La Rose et le Réséda", "Les Yeux d'Elsa", "Le Crève-cœur", "Le Musée Grévin"], 0,
     "Celui qui croyait au ciel, celui qui n'y croyait pas : il unit résistants chrétiens et communistes."],
    ["Quel recueil clandestin réunit des textes de résistance en 1943 ?", ["L'Honneur des poètes", "Les Éditions de Minuit clandestines seules", "Le Silence de la mer", "Le Cahier noir"], 0,
     "Publié aux Éditions de Minuit clandestines, il rassemblait des poèmes sous pseudonymes."],
    ["Quel récit de Vercors paraît clandestinement en 1942 ?", ["Le Silence de la mer", "La Marche à l'étoile", "Les Armes de la nuit", "Le Sable du temps"], 0,
     "Il met en scène la résistance passive d'une famille face à un officier allemand cultivé."],
    ["Quel écrivain antillais a lié son œuvre à la lutte anticoloniale ?", ["Aimé Césaire", "Léopold Sédar Senghor", "Ousmane Sembène", "Mongo Beti"], 0,
     "Son Discours sur le colonialisme, en 1950, est un texte de combat majeur."],
    ["Quel manifeste français de 1960 soutient l'insoumission pendant la guerre d'Algérie ?", ["Le Manifeste des 121", "L'Appel de Stockholm", "La Déclaration des intellectuels", "Le Manifeste de Bandung"], 0,
     "Ses signataires ont fait l'objet de poursuites et de sanctions professionnelles."],
    ["Quel manifeste de 1971 revendique la pratique de l'avortement ?", ["Le Manifeste des 343", "Le Manifeste des 121", "L'Appel des femmes", "La Déclaration de Bobigny"], 0,
     "Signé par de nombreuses écrivaines et artistes, il a contribué au vote de la loi de 1975."],
    ["Qu'est-ce que la littérature de témoignage ?", ["Un récit rendant compte d'une expérience historique vécue", "Un reportage littéraire", "Une autobiographie", "Un essai historique"], 0,
     "Les récits de déportation en constituent le corpus le plus discuté sur le plan de la forme."],
    ["Quel prix Nobel de littérature a été décerné à une autrice de récits de témoignage en 2015 ?", ["Svetlana Alexievitch", "Herta Müller", "Elfriede Jelinek", "Olga Tokarczuk"], 0,
     "Elle construit ses livres à partir de centaines d'entretiens montés en polyphonie."],
    ["Quelle critique adresse-t-on parfois à la littérature engagée ?", ["Le risque de subordonner l'écriture à un message", "Son manque de public", "Sa difficulté de lecture", "Son caractère daté"], 0,
     "Barthes, Blanchot et d'autres ont défendu une conception de l'engagement propre à la langue elle-même.", 3],
  ]),

  notion("li3-lecture-numerique", S, "Le livre à l'ère numérique",
    "Formats, usages, économie.",
    "Le livre numérique n'a pas remplacé le papier, contrairement aux prédictions des années 2000.",
    2, [
    ["Quelle part du marché du livre le numérique représente-t-il en France ?", ["Une part minoritaire, autour de dix pour cent", "La moitié", "Un quart", "Moins d'un pour cent"], 0,
     "La part est bien plus élevée aux États-Unis et pour certains genres, comme la romance."],
    ["Qu'est-ce que le format EPUB ?", ["Un format ouvert de livre numérique à mise en page adaptable", "Un format propriétaire", "Un fichier image de page", "Un format audio"], 0,
     "Contrairement au PDF, il adapte le texte à la taille de l'écran."],
    ["Qu'est-ce qu'un verrou numérique sur un livre électronique ?", ["Un dispositif limitant la copie et l'usage du fichier", "Un mot de passe d'accès", "Un chiffrement de sauvegarde", "Une signature d'authenticité"], 0,
     "Il peut rendre le livre illisible si le service qui le gère disparaît."],
    ["Qu'est-ce qu'un livre audio ?", ["Un enregistrement de la lecture d'un texte", "Une adaptation radiophonique", "Un résumé sonore", "Une lecture par synthèse vocale uniquement"], 0,
     "Le segment connaît la croissance la plus rapide de l'édition depuis quelques années."],
    ["Qu'est-ce que l'autoédition ?", ["La publication d'un ouvrage par son auteur sans éditeur", "Une publication à compte d'auteur", "Une édition indépendante", "Une publication en ligne gratuite"], 0,
     "Les plateformes numériques l'ont rendue accessible et parfois rémunératrice."],
    ["Qu'est-ce que l'édition à compte d'auteur ?", ["Une publication où l'auteur finance la fabrication de son livre", "Une autoédition numérique", "Une édition associative", "Une édition sans avance"], 0,
     "Elle se distingue de l'édition traditionnelle, où l'éditeur prend le risque financier."],
    ["Qu'est-ce que le prix unique du livre numérique en France ?", ["Une extension au numérique du principe du prix fixé par l'éditeur", "Un tarif unique pour tous les livres", "Un plafond de prix", "Une TVA unique"], 0,
     "La loi de 2011 l'a instauré, sur le modèle de la loi Lang de 1981."],
    ["Qu'est-ce qu'une plateforme de lecture par abonnement ?", ["Un service donnant accès à un catalogue contre une redevance mensuelle", "Une bibliothèque numérique publique", "Une librairie en ligne", "Un service de prêt entre lecteurs"], 0,
     "La rémunération des auteurs y est calculée sur les pages lues, ce qui suscite des critiques."],
    ["Qu'est-ce que le domaine public numérisé ?", ["Des œuvres libres de droits mises en ligne par des institutions", "Des livres gratuits", "Des ouvrages en libre accès", "Des textes sans auteur identifié"], 0,
     "Gallica, portail de la Bibliothèque nationale de France, en propose plusieurs millions de documents."],
    ["Qu'est-ce que la lecture numérique change à la compréhension d'un texte long ?", ["Elle tend à favoriser le survol et fragmenter l'attention", "Elle améliore la mémorisation", "Elle n'a aucun effet", "Elle accélère la compréhension"], 0,
     "L'effet est surtout marqué pour les textes longs et difficiles, moins pour les textes brefs.", 3],
  ]),

  notion("li3-metiers-livre", S, "Les métiers du livre",
    "De l'auteur au libraire : qui fait le livre.",
    "Un livre passe entre les mains d'une dizaine de métiers avant d'atteindre le lecteur.",
    2, [
    ["Que fait un éditeur au sens éditorial ?", ["Il choisit les textes et accompagne leur mise au point", "Il imprime les livres", "Il vend les livres", "Il finance seulement la production"], 0,
     "Le travail éditorial peut demander plusieurs mois d'échanges avec l'auteur."],
    ["Que fait un correcteur ?", ["Il vérifie orthographe, grammaire, typographie et cohérence", "Il réécrit le texte", "Il choisit les manuscrits", "Il met en page"], 0,
     "La préparation de copie précède la correction sur épreuves."],
    ["Que fait un maquettiste dans l'édition ?", ["Il conçoit la mise en page et la présentation du livre", "Il dessine la couverture", "Il choisit les caractères seuls", "Il imprime les épreuves"], 0,
     "Grille, marges, choix typographiques et hiérarchie visuelle relèvent de son travail."],
    ["Que fait un attaché de presse dans l'édition ?", ["Il fait connaître le livre aux journalistes et aux prescripteurs", "Il rédige les communiqués seuls", "Il organise les ventes", "Il négocie les droits"], 0,
     "Son travail conditionne largement la visibilité d'un livre à sa sortie."],
    ["Que fait un agent littéraire ?", ["Il représente l'auteur et négocie ses contrats", "Il corrige les manuscrits", "Il publie les livres", "Il vend les livres en librairie"], 0,
     "La pratique, dominante dans le monde anglo-saxon, reste minoritaire en France."],
    ["Qu'est-ce qu'un diffuseur dans la chaîne du livre ?", ["L'acteur qui présente les titres aux libraires", "L'imprimeur", "Le transporteur", "Le grossiste"], 0,
     "Le distributeur, lui, gère la logistique physique et les flux financiers."],
    ["Que fait un libraire au-delà de la vente ?", ["Il sélectionne, conseille et met en valeur les titres", "Il commande automatiquement les nouveautés", "Il fixe les prix", "Il édite des ouvrages"], 0,
     "Une librairie moyenne doit choisir parmi plus de cinq cent mille titres disponibles."],
    ["Qu'est-ce que l'office en librairie ?", ["Un envoi régulier de nouveautés par le distributeur", "Une commande spéciale", "Un retour d'invendus", "Une remise commerciale"], 0,
     "Le libraire peut le refuser ou l'ajuster, mais le volume des nouveautés le contraint fortement."],
    ["Qu'est-ce que le droit de retour dans le commerce du livre ?", ["La possibilité pour le libraire de renvoyer les invendus", "Un droit de rétractation du client", "Une garantie de qualité", "Un droit de reprise de l'auteur"], 0,
     "Il limite le risque du libraire mais génère un flux logistique considérable."],
    ["Qu'est-ce que le label Librairie indépendante de référence ?", ["Une reconnaissance publique accordée à des librairies de qualité", "Un label commercial", "Une certification professionnelle", "Un classement des ventes"], 0,
     "Il ouvre droit à des avantages fiscaux et à des aides publiques.", 3],
  ]),

  notion("li3-litterature-scolaire", S, "Enseigner la littérature",
    "Programmes, corpus, débats.",
    "Le corpus scolaire n'est pas figé : il change à chaque génération.",
    2, [
    ["Qu'est-ce qu'un classique littéraire ?", ["Une œuvre dont la valeur est reconnue durablement par une tradition de lecture", "Une œuvre ancienne", "Une œuvre du XVIIe siècle", "Une œuvre au programme scolaire"], 0,
     "Le statut de classique se construit et peut se défaire."],
    ["Qu'est-ce que le canon littéraire ?", ["L'ensemble des œuvres tenues pour essentielles par une culture", "Le programme officiel", "La liste des prix littéraires", "Le catalogue d'un éditeur"], 0,
     "Sa composition, longtemps très masculine et occidentale, fait l'objet de révisions."],
    ["Qu'est-ce qu'une explication de texte ?", ["Une analyse linéaire mettant au jour le fonctionnement d'un extrait", "Un résumé commenté", "Une biographie de l'auteur", "Une paraphrase du passage"], 0,
     "L'exercice est spécifiquement français dans sa forme scolaire actuelle."],
    ["Qu'est-ce qu'un commentaire composé ?", ["Une analyse organisée autour d'axes de lecture", "Une analyse linéaire", "Une dissertation sur l'œuvre", "Un résumé argumenté"], 0,
     "Il exige de construire un plan à partir du texte, non d'appliquer une grille préétablie."],
    ["Qu'est-ce qu'une dissertation littéraire ?", ["Une réflexion argumentée sur une question de littérature", "Un commentaire d'œuvre", "Une synthèse de cours", "Une analyse comparée"], 0,
     "Elle suppose de discuter un énoncé plutôt que de l'illustrer."],
    ["Qu'est-ce qu'une œuvre intégrale au programme ?", ["Une œuvre étudiée dans sa totalité et non par extraits", "Une œuvre non abrégée", "Une édition complète", "Une œuvre imposée nationalement"], 0,
     "L'étude d'extraits, ou groupement de textes, en constitue le complément."],
    ["Pourquoi le corpus scolaire évolue-t-il ?", ["Il reflète des choix culturels et pédagogiques qui se discutent", "Les œuvres anciennes se perdent", "Les programmes changent chaque année", "Les éditeurs imposent leurs titres"], 0,
     "L'entrée d'autrices et d'auteurs francophones en est une évolution récente et débattue."],
    ["Qu'est-ce que la lecture cursive ?", ["Une lecture personnelle et suivie d'une œuvre, hors étude détaillée", "Une lecture rapide", "Une lecture à voix haute", "Une lecture partielle"], 0,
     "Elle vise à construire une culture littéraire et le goût de lire."],
    ["Qu'est-ce qu'un carnet de lecture ?", ["Un support où l'élève consigne ses réactions et ses observations", "Un cahier de résumés", "Un carnet de citations", "Un journal de bord scolaire"], 0,
     "Il valorise le rapport personnel à l'œuvre plutôt que la restitution d'un savoir."],
    ["Quel débat traverse l'enseignement de la littérature ?", ["L'équilibre entre analyse technique et plaisir de lire", "Le choix des éditions", "Le nombre d'œuvres à étudier", "La place de la grammaire"], 0,
     "Les deux objectifs ne s'opposent pas nécessairement, mais leur articulation reste discutée.", 3],
  ]),
];
