/**
 * Littérature — treize notions, dont la plupart ont désormais un cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Littérature";

export const CG_LITTERATURE: SeedSkill[] = [
  notion("li-genres-litteraires", S, "Les genres littéraires",
    "Roman, théâtre, poésie, essai : des formes aux règles anciennes, et des frontières poreuses.",
    "Un genre se définit par sa forme et son mode d'énonciation, pas par son sujet.",
    2, [
    ["Qu'est-ce qu'un roman épistolaire ?", ["Un roman composé de lettres échangées", "Un roman écrit à la première personne", "Un roman historique situé sous l'Ancien Régime", "Un roman en vers, comme au Moyen Âge"], 0,
     "Les Liaisons dangereuses de Laclos en est le sommet français."],
    ["Qu'est-ce qu'une nouvelle, par rapport au roman ?", ["Un récit bref, à intrigue resserrée", "Un roman resté inachevé à la mort de l'auteur", "Un récit inspiré d'un fait d'actualité", "Un roman court à plusieurs narrateurs"], 0,
     "La chute finale y joue souvent un rôle décisif, comme chez Maupassant."],
    ["Qu'est-ce qu'une fable ?", ["Un court récit à visée morale mettant souvent en scène des animaux", "Un conte merveilleux transmis oralement avant d'être recueilli par un écrivain", "Un poème lyrique chanté par un trouvère", "Un récit fondateur expliquant l'origine d'un peuple"], 0,
     "Ésope en Grèce, Phèdre à Rome, La Fontaine en France en sont les grands noms."],
    ["Qu'est-ce qu'un essai ?", ["Un texte de réflexion personnelle sur un sujet", "Un traité savant qui épuise méthodiquement son sujet", "Un récit autobiographique centré sur l'enfance", "Un manifeste défendant une position politique"], 0,
     "Montaigne invente le mot et la forme en 1580 : essayer sa pensée plutôt que conclure."],
    ["Qu'est-ce qu'une autobiographie ?", ["Le récit de sa propre vie par son auteur", "Un roman librement inspiré de faits réels", "Un journal intime publié du vivant de l'auteur", "Une biographie écrite avec l'accord du modèle"], 0,
     "Philippe Lejeune parle de pacte autobiographique : identité entre auteur, narrateur et personnage."],
    ["Qu'est-ce que l'autofiction ?", ["Un récit de soi assumant une part de fiction", "Une autobiographie romancée qui ne s'avoue pas", "Un roman à clés où chacun reconnaît des proches", "Un témoignage recueilli par un journaliste"], 0,
     "Le terme est forgé par Serge Doubrovsky en 1977 pour son roman Fils."],
    ["Qu'est-ce qu'une tragédie classique ?", ["Une pièce en cinq actes, en vers, où un héros noble court à sa perte", "Une pièce à fin malheureuse tirée de l'histoire romaine", "Un drame historique en trois actes et en prose", "Une pièce dont le dénouement reste suspendu"], 0,
     "Elle obéit aux règles des trois unités : action, lieu, temps."],
    ["Qu'est-ce qu'un drame romantique ?", ["Une pièce qui rejette les unités et mêle registres et milieux sociaux", "Une tragédie moderne située à l'époque contemporaine", "Une pièce centrée sur la vie privée d'une famille", "Un mélodrame populaire joué sur les boulevards"], 0,
     "Hugo en fixe le programme dans la préface de Cromwell en 1827 et l'illustre avec Hernani."],
    ["Qu'est-ce qu'un sonnet ?", ["Un poème de quatorze vers en deux quatrains et deux tercets", "Un poème de douze vers répartis en trois quatrains à rimes croisées", "Un poème sans rimes de longueur libre", "Un poème chanté accompagné au luth à la Renaissance"], 0,
     "Venu d'Italie, il est introduit en France au XVIe siècle par Marot et la Pléiade."],
    ["Qu'est-ce qu'un poème en prose ?", ["Un texte poétique sans vers ni rimes", "Un roman dont la prose est très travaillée", "Une prose rythmée en alexandrins cachés", "Un récit lyrique versifié en strophes régulières"], 0,
     "Aloysius Bertrand en pose les bases ; Baudelaire l'installe avec Le Spleen de Paris.", 3],
  ]),

  notion("li-versification", S, "La versification française",
    "Compter les syllabes, placer la césure, entendre les rimes : la mécanique du vers.",
    "Le e muet compte devant une consonne et s'élide devant une voyelle ou en fin de vers.",
    2, [
    ["D'où le vers de douze syllabes tire-t-il le nom d'alexandrin ?", ["Du Roman d'Alexandre, écrit dans ce mètre au XIIe siècle", "D'Alexandre le Grand, dont les exploits auraient été chantés ainsi", "De la ville d'Alexandrie, où le vers serait né", "D'un poète de la Pléiade nommé Alexandre de Ronsard"], 0,
     "Le mètre s'impose ensuite au XVIe siècle et domine la poésie française jusqu'au XIXe."],
    ["Comment appelle-t-on un vers de dix syllabes ?", ["Un décasyllabe", "Un octosyllabe", "Un alexandrin", "Un hendécasyllabe"], 0,
     "C'est le mètre de la Chanson de Roland, avant que l'alexandrin ne domine."],
    ["Qu'est-ce que la césure d'un alexandrin classique ?", ["Une coupe après la sixième syllabe", "La pause marquée à la fin de chaque vers", "L'accent porté sur la dernière syllabe du vers", "Le silence ménagé entre deux strophes"], 0,
     "Elle partage le vers en deux hémistiches. Les romantiques la déplaceront pour assouplir le rythme."],
    ["Qu'est-ce qu'un enjambement ?", ["Une phrase qui se poursuit au vers suivant", "Une rime déplacée d'un vers à l'autre", "Une syllabe supplémentaire tolérée dans le vers", "Une pause marquée au milieu du vers"], 0,
     "Le rejet est le cas particulier où seul un mot bref déborde sur le vers suivant."],
    ["Qu'est-ce qu'une diérèse ?", ["Prononcer en deux syllabes ce qui s'en dit une", "Supprimer une syllabe du vers pour respecter le compte", "Répéter une consonne d'un vers à l'autre", "Élider un e muet devant une voyelle initiale"], 0,
     "Dans « pas-si-on » compté en trois syllabes plutôt que deux. La synérèse fait l'inverse."],
    ["Que sont des rimes embrassées ?", ["Une disposition ABBA", "Une disposition ABAB", "Une disposition AABB", "Des rimes sans ordre fixe"], 0,
     "ABAB sont des rimes croisées, AABB des rimes plates ou suivies."],
    ["Qu'est-ce qu'une rime riche ?", ["Une rime partageant au moins trois sons communs", "Une rime rare dans la langue française", "Une rime portant sur un mot de plusieurs syllabes", "Une rime entre deux mots de sens très proche"], 0,
     "Une rime pauvre n'en partage qu'un, une rime suffisante deux."],
    ["Qu'est-ce que l'alternance des rimes en poésie classique ?", ["L'alternance obligatoire entre rimes féminines et masculines", "L'alternance régulière entre deux mètres différents", "Le changement de rime à chaque nouvelle strophe", "L'alternance entre passages en vers et en prose"], 0,
     "Une rime féminine se termine par un e muet ; une rime masculine non."],
    ["Qu'est-ce qu'un vers libre ?", ["Un vers sans mètre ni rime réguliers", "Un vers écrit sans aucune ponctuation", "Un vers d'un nombre impair de syllabes", "Un vers non rimé mais régulièrement mesuré"], 0,
     "Il s'impose à la fin du XIXe siècle, notamment avec Rimbaud, Laforgue et les symbolistes."],
    ["Qu'est-ce qu'un calligramme ?", ["Un poème dont la disposition dessine une figure", "Un poème calligraphié à la main par son auteur", "Un poème construit sans aucun verbe", "Un acrostiche dont les initiales forment un nom"], 0,
     "Apollinaire en fait un recueil en 1918, mais la forme remonte à l'Antiquité grecque.", 3],
  ]),

  notion("li-figures-style", S, "Les figures de style en littérature",
    "Comparaison, métaphore, métonymie, ironie : nommer précisément ce que fait une phrase.",
    "La comparaison montre l'outil de comparaison ; la métaphore le supprime.",
    2, [
    ["Qu'est-ce qu'une métaphore ?", ["Une comparaison sans outil de comparaison", "Une exagération volontaire destinée à frapper l'esprit", "Le rapprochement de deux termes de sens opposé", "Le remplacement d'un mot par un autre qui lui est lié"], 0,
     "« Cet homme est un lion » est une métaphore ; « fort comme un lion » une comparaison."],
    ["Qu'est-ce qu'une métonymie ?", ["Désigner une chose par un terme qui lui est logiquement lié", "Exagérer une qualité pour la rendre plus frappante", "Adoucir une réalité pénible en la nommant autrement", "Répéter un même mot en tête de plusieurs phrases successives"], 0,
     "« Boire un verre », « lire un Zola » : le contenant pour le contenu, l'auteur pour l'œuvre."],
    ["Qu'est-ce qu'une synecdoque ?", ["Désigner le tout par la partie ou l'inverse", "Rapprocher deux réalités au moyen d'un outil de comparaison", "Inverser l'ordre attendu des mots dans la phrase", "Employer un mot pour dire exactement le contraire"], 0,
     "« Une voile à l'horizon » pour un navire. C'est un cas particulier de métonymie."],
    ["Qu'est-ce qu'un oxymore ?", ["L'association de deux termes contradictoires", "Une suite de termes d'intensité croissante", "La répétition d'un même son dans une suite de mots", "Une comparaison faite sans outil de comparaison"], 0,
     "« Cette obscure clarté », chez Corneille, en est l'exemple le plus cité."],
    ["Qu'est-ce qu'une hyperbole ?", ["Une exagération volontaire", "Une atténuation volontaire de ce que l'on veut dire", "Le rapprochement de deux idées qui s'opposent", "La reprise d'un même mot à plusieurs reprises"], 0,
     "« Je meurs de faim ». Son contraire, la litote, dit moins pour suggérer plus."],
    ["Qu'est-ce qu'une litote ?", ["Dire moins pour faire entendre plus", "Exagérer un trait au point de le rendre invraisemblable", "Remplacer un mot déplaisant par une formule plus douce", "Reprendre une même structure de phrase plusieurs fois"], 0,
     "« Va, je ne te hais point » chez Corneille signifie exactement l'inverse."],
    ["Qu'est-ce qu'un euphémisme ?", ["Une formule qui atténue une réalité désagréable", "Une exagération employée sur un ton ironique", "Une figure de répétition", "Le rapprochement de deux mots qui se contredisent"], 0,
     "« Il nous a quittés » pour « il est mort ». À ne pas confondre avec la litote, qui vise l'intensification."],
    ["Qu'est-ce qu'une anaphore ?", ["La répétition d'un mot en tête de plusieurs propositions", "La reprise d'un même mot à la fin de plusieurs phrases", "L'inversion du sujet et du verbe dans la phrase", "Le retour d'un même son d'un vers à l'autre"], 0,
     "« Moi, président de la République… » : un usage rhétorique célèbre de la figure."],
    ["Qu'est-ce qu'une allitération ?", ["La répétition d'un même son consonantique", "La répétition d'une même voyelle dans une suite de mots", "La reprise du même mot à plusieurs endroits du texte", "L'imitation par les mots d'un bruit de la réalité"], 0,
     "L'assonance est son équivalent pour les voyelles. « Pour qui sont ces serpents… » chez Racine."],
    ["Qu'est-ce qu'une prétérition ?", ["Annoncer qu'on ne dira pas ce qu'on dit malgré tout", "Répéter une négation pour insister sur le refus", "Suggérer une idée en la laissant entièrement de côté", "Interrompre volontairement une phrase avant sa fin"], 0,
     "« Je ne vous parlerai pas de son passé… » : la figure dit en feignant de taire.", 3],
  ]),

  notion("li-mouvements-litteraires", S, "Les mouvements littéraires",
    "Humanisme, classicisme, Lumières, romantisme, réalisme, surréalisme : sept siècles en quelques programmes.",
    "Un mouvement se reconnaît à un manifeste, une revue ou une préface qui fixe son programme.",
    2, [
    ["Qu'est-ce que l'humanisme au XVIe siècle ?", ["Un mouvement qui replace l'homme et les textes antiques au centre du savoir", "Une doctrine de charité chrétienne prêchée par les ordres mendiants du Moyen Âge", "Un courant politique républicain né dans les cités italiennes", "Une école de peinture italienne née à Florence"], 0,
     "Érasme, Rabelais et Montaigne en sont les figures majeures. L'imprimerie en démultiplie la portée."],
    ["Quel groupe de poètes du XVIe siècle veut illustrer la langue française ?", ["La Pléiade", "Les Grands Rhétoriqueurs", "Le Parnasse", "Les Félibres"], 0,
     "Du Bellay publie en 1549 la Défense et illustration de la langue française, son manifeste."],
    ["Quelle règle domine le théâtre classique du XVIIe siècle ?", ["La règle des trois unités", "L'interdiction du vers", "L'absence de chœur", "L'unité de ton"], 0,
     "Unité d'action, de lieu et de temps, au nom de la vraisemblance et de la bienséance."],
    ["Qu'est-ce que le siècle des Lumières ?", ["Un mouvement du XVIIIe siècle plaçant la raison et l'esprit critique au premier plan", "Un courant mystique venu d'Allemagne", "Une école poétique attachée à la forme fixe", "Une période d'expansion coloniale et commerciale des puissances européennes vers les Amériques"], 0,
     "L'Encyclopédie de Diderot et d'Alembert en est le grand chantier collectif."],
    ["Quel sentiment le romantisme place-t-il au centre ?", ["Le moi et ses émotions", "La raison", "L'objectivité scientifique", "La satire sociale"], 0,
     "Mélancolie, nature, passion et révolte contre les règles en sont les traits communs."],
    ["Quel mouvement veut peindre la société telle qu'elle est, au XIXe siècle ?", ["Le réalisme", "Le romantisme", "Le symbolisme", "Le classicisme"], 0,
     "Balzac, Flaubert et Maupassant en sont les grands noms. Le naturalisme y ajoute une méthode scientifique."],
    ["Quel écrivain théorise le naturalisme ?", ["Émile Zola", "Gustave Flaubert", "Honoré de Balzac", "Guy de Maupassant"], 0,
     "Dans Le Roman expérimental en 1880 : le romancier observe et expérimente comme un médecin."],
    ["Quelle formule résume la doctrine du Parnasse ?", ["L'art pour l'art", "L'art au service du peuple", "L'art populaire", "L'art total, réunissant tous les genres"], 0,
     "Contre l'épanchement romantique, les parnassiens visent la perfection formelle et l'impassibilité."],
    ["Qui publie le Manifeste du surréalisme en 1924 ?", ["André Breton", "Louis Aragon", "Paul Éluard", "Tristan Tzara"], 0,
     "Le mouvement explore le rêve, l'écriture automatique et l'inconscient, dans le sillage de Freud."],
    ["Qu'est-ce que le Nouveau Roman ?", ["Un courant des années 1950 qui rompt avec l'intrigue et le personnage traditionnels", "Un retour au roman réaliste du XIXe siècle et à ses personnages fortement caractérisés", "Un genre policier littéraire né dans les années 1950", "Le roman né au lendemain de la Libération"], 0,
     "Robbe-Grillet, Sarraute et Butor, réunis autour des Éditions de Minuit, en sont les principaux auteurs.", 3],
  ]),

  notion("li-theatre-francais", S, "Le théâtre français",
    "Du tréteau médiéval à la scène contemporaine : auteurs, formes et institutions.",
    "La Comédie-Française naît en 1680 de la fusion de troupes voulue par Louis XIV.",
    2, [
    ["En quelle année la Comédie-Française est-elle fondée ?", ["1680", "1643", "1715", "1789"], 0,
     "Louis XIV fusionne la troupe de Molière avec celle de l'Hôtel de Bourgogne. C'est la plus ancienne troupe permanente du monde."],
    ["Quel surnom la Comédie-Française porte-t-elle ?", ["La Maison de Molière", "Le Théâtre du Roi", "La Grande Salle", "Le Palais des Comédiens"], 0,
     "Molière était mort sept ans avant sa fondation, mais sa troupe en constitue le noyau."],
    ["Quelle pièce de Beaumarchais fut longtemps interdite avant sa création en 1784 ?", ["Le Mariage de Figaro", "Le Barbier de Séville", "La Mère coupable", "Eugénie"], 0,
     "Le monologue de Figaro attaque les privilèges de naissance. Louis XVI la jugea détestable avant de céder."],
    ["Quelle pièce de Victor Hugo provoque une bataille en 1830 ?", ["Hernani", "Ruy Blas", "Les Burgraves", "Lucrèce Borgia"], 0,
     "Partisans du drame romantique et défenseurs du classicisme s'affrontent dans la salle dès la première."],
    ["Qui écrit En attendant Godot, créée en 1953 ?", ["Samuel Beckett", "Eugène Ionesco", "Jean Genet", "Arthur Adamov"], 0,
     "Pièce fondatrice du théâtre de l'absurde : deux personnages attendent quelqu'un qui ne vient jamais."],
    ["Quelle pièce d'Eugène Ionesco est jouée sans interruption dans le même théâtre parisien depuis 1957 ?", ["La Cantatrice chauve", "Rhinocéros", "Les Chaises", "Le Roi se meurt"], 0,
     "Au Théâtre de la Huchette, c'est l'un des plus longs records de représentation continue au monde."],
    ["Qui fonde le Festival d'Avignon en 1947 ?", ["Jean Vilar", "Louis Jouvet", "Antonin Artaud", "Jacques Copeau"], 0,
     "La cour d'honneur du Palais des papes en est le lieu emblématique."],
    ["Quelle institution théâtrale populaire le même homme dirige-t-il à partir de 1951 ?", ["Le Théâtre national populaire", "La Comédie-Française", "L'Odéon", "Le Théâtre du Soleil"], 0,
     "Il en prend la direction avec l'ambition d'un théâtre exigeant pour un public large."],
    ["Qui écrit Le Théâtre et son double, qui appelle à un théâtre de la cruauté ?", ["Antonin Artaud", "Bertolt Brecht", "Konstantin Stanislavski", "Jacques Copeau"], 0,
     "Publié en 1938, il influence durablement la mise en scène du XXe siècle."],
    ["Qu'est-ce que la distanciation au théâtre ?", ["Un procédé empêchant le spectateur de s'identifier pour le faire réfléchir", "L'éloignement de la scène", "Le refus du décor", "Le jeu sans émotion"], 0,
     "Théorisée par Bertolt Brecht, elle rompt l'illusion par des adresses au public ou des pancartes.", 3],
  ]),

  notion("li-roman-francais", S, "Le roman français",
    "Du roman de chevalerie au roman contemporain : quelques jalons et leurs auteurs.",
    "La Princesse de Clèves, en 1678, est souvent tenue pour le premier roman d'analyse psychologique.",
    2, [
    ["Quel roman de 1678 est souvent tenu pour le premier roman d'analyse psychologique français ?", ["La Princesse de Clèves", "Manon Lescaut", "La Nouvelle Héloïse", "Gil Blas"], 0,
     "Publié anonymement par Madame de La Fayette, il fait de l'intériorité le vrai sujet du récit."],
    ["Quel ensemble romanesque Balzac construit-il à partir de 1830 ?", ["La Comédie humaine", "Les Rougon-Macquart", "Les Thibault", "Les Hommes de bonne volonté"], 0,
     "Près de quatre-vingt-dix romans achevés, organisés en études de mœurs, études philosophiques et études analytiques, pour peindre toute une société."],
    ["Quelle fresque romanesque Zola consacre-t-il à une famille sous le Second Empire ?", ["Les Rougon-Macquart", "La Comédie humaine", "Les Misérables", "Le Cycle de Pardaillan"], 0,
     "Vingt romans, sous-titrés Histoire naturelle et sociale d'une famille sous le Second Empire."],
    ["Quel roman de Flaubert vaut à son auteur un procès en 1857 ?", ["Madame Bovary", "L'Éducation sentimentale", "Salammbô", "Bouvard et Pécuchet"], 0,
     "Poursuivi pour outrage à la morale publique, il est acquitté. Baudelaire, la même année, sera condamné."],
    ["Quelle œuvre Marcel Proust publie-t-il à partir de 1913 ?", ["À la recherche du temps perdu", "Les Faux-Monnayeurs", "Le Grand Meaulnes", "Le Rivage des Syrtes"], 0,
     "Sept volumes, achevés après sa mort. Le premier fut refusé par plusieurs éditeurs, dont Gide chez Gallimard."],
    ["Quel roman d'Albert Camus s'ouvre sur la mort d'une mère et l'indifférence du narrateur ?", ["L'Étranger", "La Peste", "La Chute", "Le Premier Homme"], 0,
     "Publié en 1942, il illustre la notion d'absurde développée dans Le Mythe de Sisyphe."],
    ["Quel écrivain refuse le prix Nobel de littérature en 1964 ?", ["Jean-Paul Sartre", "Albert Camus", "André Malraux", "Louis-Ferdinand Céline"], 0,
     "Il refusait toute distinction officielle, estimant qu'un écrivain ne doit pas se laisser transformer en institution."],
    ["Quel roman de Marguerite Duras obtient le Goncourt en 1984 ?", ["L'Amant", "Un barrage contre le Pacifique", "Moderato cantabile", "Le Ravissement de Lol V. Stein"], 0,
     "Récit largement autobiographique de sa jeunesse en Indochine, il connaît un immense succès."],
    ["Quelle écrivaine obtient le prix Nobel de littérature en 2022 ?", ["Annie Ernaux", "Marguerite Duras", "Nathalie Sarraute", "Marie NDiaye"], 0,
     "L'Académie salue une écriture qui met à nu les racines et les contraintes de la mémoire personnelle."],
    ["Quel prix littéraire français est décerné chez Drouant depuis 1914 ?", ["Le prix Goncourt", "Le prix Renaudot", "Le prix Femina", "Le prix Médicis"], 0,
     "Il récompense le meilleur ouvrage d'imagination en prose de l'année et ne rapporte que dix euros à son lauréat.", 3],
  ]),

  notion("li-poesie-francaise", S, "La poésie française",
    "De Villon à Bonnefoy : quelques voix et les recueils qui ont fait date.",
    "Les Fleurs du mal ont été condamnées en 1857, la même année que Madame Bovary fut acquittée.",
    2, [
    ["Quel poète du XVe siècle écrit la Ballade des pendus ?", ["François Villon", "Charles d'Orléans", "Clément Marot", "Rutebeuf"], 0,
     "Écrite alors qu'il attendait, dit-on, une exécution qui fut finalement commuée en bannissement."],
    ["Quel recueil de Baudelaire est condamné en 1857 ?", ["Les Fleurs du mal", "Le Spleen de Paris", "Les Paradis artificiels", "Les Épaves"], 0,
     "Six pièces sont censurées pour outrage à la morale publique. Elles ne seront réhabilitées qu'en 1949."],
    ["Quel très jeune poète écrit Le Bateau ivre puis cesse d'écrire avant vingt et un ans ?", ["Arthur Rimbaud", "Paul Verlaine", "Stéphane Mallarmé", "Lautréamont"], 0,
     "Il part ensuite pour l'Afrique où il devient négociant. Son œuvre tient en quelques années."],
    ["De quelle suite de Romances sans paroles « Il pleure dans mon cœur » est-il tiré ?", ["Les Ariettes oubliées", "Chanson d'automne", "Mon rêve familier", "Green"], 0,
     "Tiré des Romances sans paroles, il illustre la musicalité que Verlaine réclamait avant toute chose."],
    ["Quel poème de Mallarmé, publié en 1897, disperse librement les mots sur la double page ?", ["Un coup de dés jamais n'abolira le hasard", "Hérodiade", "L'Après-midi d'un faune", "Poésies"], 0,
     "Publié en 1897, il fait de la page blanche et de la typographie des éléments du poème."],
    ["Quel poème d'Apollinaire évoque la Seine et le temps qui passe ?", ["Le Pont Mirabeau", "Zone", "La Chanson du mal-aimé", "Les Colchiques"], 0,
     "Tiré d'Alcools, publié en 1913, recueil dont Apollinaire a supprimé toute ponctuation."],
    ["Quel poème de Paul Éluard, écrit sous l'Occupation, s'achève sur le mot Liberté ?", ["Liberté", "La Courbe de tes yeux", "Notre vie", "Couvre-feu"], 0,
     "Parachuté par la Royal Air Force au-dessus de la France occupée, il devient un texte de résistance."],
    ["Quel poète martiniquais est l'un des fondateurs de la négritude ?", ["Aimé Césaire", "Léon-Gontran Damas", "Édouard Glissant", "Frantz Fanon"], 0,
     "Avec Léopold Sédar Senghor et Léon-Gontran Damas, dans les années 1930 à Paris."],
    ["Quel poète sénégalais devient président de son pays en 1960 ?", ["Léopold Sédar Senghor", "Aimé Césaire", "Birago Diop", "Cheikh Anta Diop"], 0,
     "Il fut aussi le premier Africain élu à l'Académie française, en 1983."],
    ["Quel poète français du XXe siècle consacre un recueil aux choses ordinaires dans Le Parti pris des choses ?", ["Francis Ponge", "René Char", "Yves Bonnefoy", "Philippe Jaccottet"], 0,
     "Publié en 1942, il décrit le cageot, l'huître ou le pain avec une minutie qui les transfigure.", 3],
  ]),

  notion("li-litterature-anglaise", S, "La littérature de langue anglaise",
    "Shakespeare, le roman victorien, le modernisme, la littérature américaine : quelques repères.",
    "Shakespeare a écrit une trentaine de pièces et un recueil de sonnets dont le nombre exact tombe souvent en question.",
    2, [
    ["Combien de sonnets Shakespeare a-t-il écrits ?", ["Cent cinquante-quatre", "Cent", "Deux cents", "Cinquante"], 0,
     "Publiés en 1609, ils sont adressés pour la plupart à un jeune homme, puis à une dame brune."],
    ["Quelle pièce de Shakespeare se déroule au Danemark ?", ["Hamlet", "Macbeth", "Le Roi Lear", "Othello"], 0,
     "Macbeth se situe en Écosse, Othello à Venise et Chypre, Le Roi Lear dans une Bretagne légendaire."],
    ["Quel roman de Jane Austen s'ouvre sur une vérité universellement reconnue à propos d'un homme fortuné ?", ["Orgueil et Préjugés", "Raison et Sentiments", "Emma", "Persuasion"], 0,
     "Publié en 1813, il est devenu l'un des romans les plus lus de la langue anglaise."],
    ["Quel roman de Mary Shelley naît d'un défi littéraire au bord du lac Léman en 1816 ?", ["Frankenstein", "Dracula", "Le Moine", "Les Hauts de Hurlevent"], 0,
     "L'été sans été, dû à l'éruption du Tambora, retint le groupe à l'intérieur. Elle avait dix-huit ans."],
    ["Quel roman de Charles Dickens s'ouvre sur un orphelin réclamant du rab de gruau ?", ["Oliver Twist", "David Copperfield", "Les Grandes Espérances", "Un chant de Noël"], 0,
     "Publié en feuilleton à partir de 1837, il dénonce le sort réservé aux enfants pauvres."],
    ["Quelle sœur Brontë écrit Les Hauts de Hurlevent ?", ["Emily", "Charlotte", "Anne", "Elizabeth"], 0,
     "Charlotte écrit Jane Eyre, Anne La Recluse de Wildfell Hall. Toutes trois publièrent d'abord sous pseudonymes masculins."],
    ["Quel roman de James Joyce raconte une seule journée à Dublin ?", ["Ulysse", "Gens de Dublin", "Portrait de l'artiste en jeune homme", "Finnegans Wake"], 0,
     "Le 16 juin 1904, désormais célébré comme le Bloomsday. Le roman parut à Paris en 1922."],
    ["Quelle romancière britannique écrit Mrs Dalloway et Les Vagues ?", ["Virginia Woolf", "Katherine Mansfield", "Iris Murdoch", "Doris Lessing"], 0,
     "Figure du groupe de Bloomsbury, elle est l'une des grandes voix du monologue intérieur."],
    ["Quel roman de George Orwell paru en 1949 décrit une société de surveillance totale ?", ["1984", "La Ferme des animaux", "Le Meilleur des mondes", "Fahrenheit 451"], 0,
     "Le Meilleur des mondes est d'Aldous Huxley, Fahrenheit 451 de Ray Bradbury."],
    ["Quel romancier américain écrit Le Vieil Homme et la Mer ?", ["Ernest Hemingway", "William Faulkner", "John Steinbeck", "Francis Scott Fitzgerald"], 0,
     "Publié en 1952, il contribue à lui valoir le prix Nobel deux ans plus tard.", 3],
  ]),

  notion("li-litteratures-monde", S, "Les littératures du monde",
    "Russie, Amérique latine, Japon, Afrique : des œuvres majeures hors des aires française et anglaise.",
    "Le premier roman du monde n'est ni européen ni moderne : il a été écrit vers l'an mille par une femme de la cour japonaise.",
    2, [
    ["Quel roman de Tolstoï se déroule pendant les guerres napoléoniennes ?", ["Guerre et Paix", "Anna Karénine", "Résurrection", "La Sonate à Kreutzer"], 0,
     "Publié entre 1865 et 1869, il mêle destins privés et fresque historique sur près de deux mille pages."],
    ["Quel roman de Dostoïevski raconte le meurtre d'une usurière par un étudiant ?", ["Crime et Châtiment", "Les Frères Karamazov", "L'Idiot", "Les Démons"], 0,
     "Publié en 1866, il explore la culpabilité davantage que le crime lui-même."],
    ["Quel écrivain colombien écrit Cent Ans de solitude ?", ["Gabriel García Márquez", "Mario Vargas Llosa", "Julio Cortázar", "Carlos Fuentes"], 0,
     "Paru en 1967, il est le roman emblématique du réalisme magique et de la famille Buendía."],
    ["Quel écrivain argentin est connu pour ses nouvelles labyrinthiques réunies dans Fictions ?", ["Jorge Luis Borges", "Julio Cortázar", "Ernesto Sabato", "Adolfo Bioy Casares"], 0,
     "Bibliothèques infinies, livres impossibles et miroirs y composent une œuvre brève et vertigineuse."],
    ["Quelle œuvre japonaise du XIe siècle est souvent tenue pour le premier roman du monde ?", ["Le Dit du Genji", "Le Livre de l'oreiller", "Les Contes d'Ise", "Le Dit des Heiké"], 0,
     "Écrit par Murasaki Shikibu, dame de la cour impériale de Heian."],
    ["Quel écrivain japonais obtient le Nobel de littérature en 1968 ?", ["Yasunari Kawabata", "Yukio Mishima", "Kenzaburō Ōe", "Jun'ichirō Tanizaki"], 0,
     "Kenzaburō Ōe l'obtiendra en 1994. Mishima, souvent pressenti, ne l'a jamais reçu."],
    ["Quel écrivain nigérian publie Le Monde s'effondre en 1958 ?", ["Chinua Achebe", "Wole Soyinka", "Ben Okri", "Ngũgĩ wa Thiong'o"], 0,
     "Le roman raconte l'arrivée des colons vue depuis un village igbo. Il a été traduit dans plus de cinquante langues."],
    ["Quel écrivain africain reçoit le premier prix Nobel de littérature du continent, en 1986 ?", ["Wole Soyinka", "Naguib Mahfouz", "Nadine Gordimer", "Chinua Achebe"], 0,
     "Dramaturge et poète nigérian, il passa vingt-deux mois à l'isolement pendant la guerre du Biafra et y écrivit sur du papier de fortune."],
    ["Quel poème épique mésopotamien est l'un des plus anciens textes littéraires connus ?", ["L'Épopée de Gilgamesh", "Le Livre des morts", "L'Énuma Elish", "Le Code de Hammurabi"], 0,
     "Gravé sur tablettes d'argile, il contient un récit du déluge antérieur au texte biblique."],
    ["Quelle romancière chilienne écrit La Maison aux esprits ?", ["Isabel Allende", "Gabriela Mistral", "Marcela Serrano", "Diamela Eltit"], 0,
     "Publié en 1982, il transpose l'histoire du Chili dans une saga familiale sur quatre générations.", 3],
  ]),

  notion("li-contes-jeunesse", S, "Contes et littérature de jeunesse",
    "Des recueils du XVIIe siècle aux classiques modernes : ce que lisent les enfants et d'où ça vient.",
    "Perrault fixe par écrit des contes populaires bien plus anciens, souvent adoucis pour la cour.",
    2, [
    ["Qui publie en 1697 les Histoires ou contes du temps passé ?", ["Charles Perrault", "Jean de La Fontaine", "Madame d'Aulnoy", "Antoine Galland"], 0,
     "Le Petit Chaperon rouge, Cendrillon et Le Chat botté y figurent, avec une moralité en vers."],
    ["Quel auteur danois écrit La Petite Sirène et Le Vilain Petit Canard ?", ["Hans Christian Andersen", "Selma Ottilia Lovisa Lagerlöf", "Karen Blixen", "Astrid Lindgren"], 0,
     "Contrairement aux Grimm, il compose des contes originaux plutôt que de collecter la tradition orale."],
    ["Quel recueil oriental est traduit en français par Antoine Galland au XVIIIe siècle ?", ["Les Mille et Une Nuits", "Le Livre des rois de Ferdowsi", "Kalila et Dimna", "Le Panchatantra"], 0,
     "Sa traduction, parue à partir de 1704, a durablement façonné l'image européenne de l'Orient."],
    ["Qui écrit Le Petit Prince, publié en 1943 ?", ["Antoine de Saint-Exupéry", "Jean Giono", "Marcel Pagnol", "Romain Gary"], 0,
     "Paru d'abord à New York, il est l'un des livres les plus traduits au monde."],
    ["Quel personnage italien créé en 1881 voit son nez s'allonger quand il ment ?", ["Pinocchio", "Arlequin", "Polichinelle", "Gepetto"], 0,
     "Carlo Collodi le publie d'abord en feuilleton dans un journal pour enfants."],
    ["Qui écrit Le Livre de la jungle ?", ["Rudyard Kipling", "Robert Louis Stevenson", "Lewis Carroll", "Jack London"], 0,
     "Publié en 1894, il vaudra à son auteur le prix Nobel de littérature en 1907."],
    ["Quel roman de Lewis Carroll met en scène une fillette et un lapin pressé ?", ["Alice au pays des merveilles", "Peter Pan dans les jardins de Kensington", "Le Magicien d'Oz", "Les Voyages de Gulliver"], 0,
     "Publié en 1865, il est né d'une histoire improvisée lors d'une promenade en barque."],
    ["Quelle autrice suédoise crée le personnage de Fifi Brindacier ?", ["Astrid Lindgren", "Selma Ottilia Lovisa Lagerlöf", "Tove Jansson", "Maria Gripe"], 0,
     "Publié en 1945, ce personnage d'enfant libre et forte a bousculé la littérature jeunesse de son temps."],
    ["Quel album de Maurice Sendak, paru en 1963, met en scène un enfant chez les monstres ?", ["Max et les Maximonstres", "Le Petit Prince", "Le Vent dans les saules", "Blaise et le château"], 0,
     "Longtemps jugé effrayant par des bibliothécaires, il est devenu un classique de l'album illustré.", 3],
  ]),

  notion("li-edition-livre", S, "Le livre et l'édition",
    "De l'imprimerie au format de poche : comment un texte devient un objet, et qui en détient les droits.",
    "L'auteur ne vend pas son œuvre : il cède des droits d'exploitation, pour une durée et un territoire donnés.",
    2, [
    ["Qu'est-ce qu'un incunable ?", ["Un livre imprimé avant 1501", "Un manuscrit enluminé", "Un livre à tirage unique", "Un ouvrage sans nom d'auteur"], 0,
     "Du latin incunabula, le berceau : les tout premiers pas de l'imprimerie."],
    ["Qu'est-ce que le dépôt légal ?", ["L'obligation de déposer un exemplaire de tout ouvrage publié", "L'enregistrement officiel du droit d'auteur", "Le dépôt d'un exemplaire du manuscrit chez un notaire", "Une taxe prélevée sur chaque ouvrage édité"], 0,
     "Institué par François Ier en 1537, il alimente aujourd'hui les collections de la Bibliothèque nationale de France."],
    ["Combien de temps le droit d'auteur dure-t-il après la mort de l'auteur en France ?", ["Soixante-dix ans", "Cinquante ans, comme dans plusieurs pays voisins", "Trente ans", "Cent ans"], 0,
     "Passé ce délai, l'œuvre entre dans le domaine public et peut être librement reproduite."],
    ["Que garantit la loi Lang de 1981 en France ?", ["Le prix unique du livre", "La gratuité des bibliothèques", "La TVA réduite sur le livre", "Le soutien aux librairies indépendantes"], 0,
     "L'éditeur fixe le prix ; le détaillant ne peut s'en écarter que de cinq pour cent."],
    ["Qu'est-ce que le droit moral d'un auteur ?", ["Un droit perpétuel et incessible sur la paternité et l'intégrité de l'œuvre", "Le droit d'être rémunéré pour chaque exemplaire vendu", "Le droit de refuser toute traduction de son œuvre", "Le droit de retirer son livre de la vente à tout moment"], 0,
     "Il subsiste après l'entrée dans le domaine public et se transmet aux héritiers."],
    ["Qu'est-ce qu'un à-valoir dans un contrat d'édition ?", ["Une avance sur les droits d'auteur à venir", "Une prime de signature non remboursable versée à la signature", "Le prix d'achat définitif du manuscrit", "Une garantie sur le tirage minimum"], 0,
     "Il se déduit ensuite des droits générés par les ventes. Il n'est en général pas remboursable si le livre se vend mal."],
    ["Qu'est-ce que l'ISBN ?", ["Un numéro international identifiant une édition d'un livre", "Un code de classement des ouvrages en bibliothèque", "Un identifiant unique attribué à chaque auteur", "Un numéro attribué lors du dépôt légal"], 0,
     "Il change à chaque nouvelle édition ou format, ce qui permet de distinguer broché, poche et numérique."],
    ["Qu'est-ce que le format de poche ?", ["Une réédition à bas prix d'un titre déjà paru", "Un genre littéraire court et populaire", "Un livre de moins de deux cents pages, quel que soit l'éditeur", "Un livre publié directement sans éditeur"], 0,
     "Le Livre de Poche, lancé en 1953, a démocratisé l'accès aux classiques comme aux succès récents."],
    ["Qu'est-ce que le domaine public volontaire ?", ["Le choix d'un auteur de renoncer à ses droits patrimoniaux", "L'expiration anticipée du droit d'auteur prononcée par le juge", "La publication d'une œuvre sans passer par un éditeur", "L'autorisation donnée de photocopier une œuvre entière"], 0,
     "Les licences libres permettent de l'organiser juridiquement, sans que le droit moral puisse être abandonné.", 3],
  ]),

  notion("li-critique-lecture", S, "Lire, analyser, critiquer",
    "Narrateur, point de vue, registre : les outils qui permettent de parler précisément d'un texte.",
    "Le narrateur n'est pas l'auteur : c'est une voix construite à l'intérieur du récit.",
    2, [
    ["Qu'est-ce qu'un narrateur interne ?", ["Un narrateur qui raconte depuis le point de vue d'un personnage", "Un narrateur qui sait tout des personnages et de leurs pensées", "Un narrateur extérieur qui commente le récit qu'il rapporte", "L'auteur du livre, parlant en son nom propre"], 0,
     "Le lecteur ne sait que ce que le personnage perçoit, ce qui permet de ménager le suspense."],
    ["Qu'est-ce qu'un narrateur omniscient ?", ["Un narrateur qui connaît les pensées de tous les personnages", "Un narrateur extérieur, mais dont le savoir reste limité", "Un personnage secondaire qui rapporte ce qu'il a vu", "Un narrateur dont le lecteur ne peut pas croire le récit"], 0,
     "Fréquent dans le roman du XIXe siècle, il s'efface largement au XXe."],
    ["Qu'est-ce que la focalisation externe ?", ["Le récit ne rapporte que ce qui est visible, sans accès aux pensées", "Le récit suit un seul personnage et ne sait que ce qu'il sait", "Le narrateur commente les événements depuis l'extérieur", "Le récit alterne les points de vue de plusieurs personnages"], 0,
     "Effet de caméra objective, souvent employé dans le roman policier ou le Nouveau Roman."],
    ["Qu'est-ce que le registre pathétique ?", ["Un registre qui cherche à émouvoir, à susciter la compassion", "Un registre qui cherche à faire rire le lecteur", "Un registre solennel, propre aux discours officiels", "Un registre ironique, qui dit le contraire de ce qu'il pense"], 0,
     "Il se distingue du tragique, qui suppose une fatalité contre laquelle le héros ne peut rien."],
    ["Qu'est-ce que le registre épique ?", ["Un registre d'amplification qui grandit l'action et les personnages", "Un registre propre au récit des événements historiques", "Un registre qui décrit les combats et la vie militaire", "Un registre solennel et funèbre, celui de l'éloge des morts"], 0,
     "Hyperboles, pluriels et forces surnaturelles en sont les marques. Zola l'emploie hors de tout contexte guerrier."],
    ["Qu'est-ce que l'ironie ?", ["Faire entendre le contraire de ce que l'on dit", "Se moquer ouvertement de quelqu'un ou de quelque chose", "Exagérer un trait jusqu'à le rendre invraisemblable", "Employer un langage familier, proche de la conversation"], 0,
     "Elle suppose un accord tacite avec le lecteur, qui doit percevoir le décalage."],
    ["Qu'est-ce qu'une mise en abyme ?", ["Une œuvre contenant une reproduction d'elle-même", "Un récit qui se poursuit sans jamais trouver sa fin", "Un retour en arrière sur un épisode déjà passé", "Une digression qui s'écarte un moment du fil du récit"], 0,
     "Le théâtre dans le théâtre chez Shakespeare, ou le roman que le personnage écrit chez Gide."],
    ["Qu'est-ce qu'une analepse ?", ["Un retour en arrière dans le récit", "Une anticipation sur un événement qui n'a pas eu lieu", "Un passage de temps que le récit laisse de côté", "La répétition d'un épisode déjà raconté plus tôt"], 0,
     "La prolepse fait l'inverse : elle annonce un événement à venir."],
    ["Qu'est-ce qu'une ellipse narrative ?", ["Le récit passe sous silence une période de l'histoire", "Une phrase construite sans verbe conjugué", "Un résumé accéléré de plusieurs mois en quelques lignes", "Un changement de narrateur au milieu du récit"], 0,
     "Le sommaire, lui, résume rapidement une longue durée sans la supprimer."],
    ["Qu'est-ce que l'intertextualité ?", ["La présence d'un texte dans un autre, par citation ou allusion", "La comparaison de deux traductions d'une même œuvre", "La lecture croisée de deux auteurs d'une même époque", "Le dialogue qu'un auteur engage avec son propre lecteur"], 0,
     "La notion est forgée par Julia Kristeva en 1967, dans le sillage des travaux de Bakhtine.", 3],
  ]),

  notion("li-langues-traduction", S, "Traduire la littérature",
    "Ce qu'on gagne et ce qu'on perd à passer d'une langue à l'autre, et le statut du traducteur.",
    "Le traducteur est légalement un auteur : sa traduction est une œuvre protégée à part entière.",
    2, [
    ["Quel statut juridique la loi française reconnaît-elle au traducteur littéraire ?", ["Celui d'auteur d'une œuvre dérivée protégée", "Celui de prestataire technique payé à la page", "Celui de coauteur à parts égales avec l'original", "Celui de salarié de la maison d'édition"], 0,
     "Sa traduction est protégée par le droit d'auteur, indépendamment des droits sur le texte source."],
    ["Que désigne l'expression « les belles infidèles » ?", ["Des traductions élégantes mais éloignées de l'original", "Des traductions littérales fidèles jusqu'à la maladresse", "Des traductions publiées sans nom de traducteur", "Des retraductions successives d'un même classique"], 0,
     "Formule du XVIIe siècle, appliquée aux traductions françaises qui adaptaient les Anciens au goût de la cour."],
    ["Qu'est-ce qu'un faux ami en traduction ?", ["Un mot ressemblant à un autre dans une autre langue mais de sens différent", "Un mot intraduisible dans la langue d'arrivée", "Un emprunt mal orthographié par le traducteur", "Un archaïsme que la langue moderne a abandonné"], 0,
     "L'anglais actually signifie en réalité, non actuellement ; library est une bibliothèque, non une librairie."],
    ["Qu'est-ce qu'une traduction cibliste ?", ["Une traduction privilégiant la fluidité dans la langue d'arrivée", "Une traduction mot à mot qui conserve l'ordre des mots de la langue de départ", "Une traduction annotée par un spécialiste de l'auteur", "Une traduction faite depuis une langue tierce, dite relais"], 0,
     "La traduction sourcière, à l'inverse, garde les aspérités de la langue de départ."],
    ["Qu'est-ce qu'une retraduction ?", ["Une nouvelle traduction d'une œuvre déjà traduite", "Une traduction faite depuis une autre traduction", "Une révision de la traduction par l'auteur lui-même", "Une traduction inversée vers la langue d'origine"], 0,
     "Les classiques sont régulièrement retraduits, la langue et la lecture des œuvres évoluant."],
    ["Quel texte antique traduit en grec porte le nom de Septante ?", ["La Bible hébraïque", "L'Iliade", "Le Code de Hammurabi", "Les Dialogues de Platon"], 0,
     "Selon la légende, soixante-douze traducteurs y auraient travaillé séparément en aboutissant au même texte."],
    ["Quel érudit traduit la Bible en latin au IVe siècle ?", ["Saint Jérôme", "Saint Augustin", "Origène", "Érasme"], 0,
     "Sa Vulgate est restée la référence de l'Église latine pendant plus d'un millénaire. Il est le patron des traducteurs."],
    ["Quelle traduction de la Bible contribue à fixer l'allemand moderne ?", ["Celle de Martin Luther", "Celle de Didier Érasme", "Celle d'Ulrich Zwingli", "Celle de Philippe Melanchthon"], 0,
     "Publiée intégralement en 1534, elle choisit une langue accessible et unifie des usages régionaux disparates."],
    ["Qu'est-ce que la traduction automatique neuronale ?", ["Une traduction produite par un réseau de neurones entraîné sur de grands corpus bilingues", "Une traduction assistée par un dictionnaire électronique", "Une traduction mot à mot automatisée par un logiciel", "Une relecture automatique corrigeant la grammaire"], 0,
     "Elle a remplacé vers 2016 la traduction statistique, qui procédait par alignement de segments, et a nettement amélioré la fluidité, sans supprimer les erreurs de sens ou de registre."],
    ["Qu'appelle-t-on l'intraduisible en théorie de la traduction ?", ["Ce qui résiste au passage d'une langue à l'autre et oblige à choisir", "Un mot qui n'a aucun équivalent dans la langue cible", "Un texte trop technique pour un traducteur littéraire", "Un jeu de mots que la langue d'arrivée ne peut rendre"], 0,
     "Barbara Cassin en a fait le sujet d'un dictionnaire : l'intraduisible n'est pas ce qu'on ne traduit pas, mais ce qu'on ne cesse pas de traduire.", 3],
  ]),
];
