/**
 * Mythologie & Religions — treize notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Mythologie & Religions";

export const CG_MYTHOLOGIE_RELIGIONS: SeedSkill[] = [
  notion("mr-mythologie-nordique", S, "La mythologie nordique",
    "Ases et Vanes, neuf mondes, et une fin du monde annoncée dès l'origine.",
    "Contrairement aux mythes grecs, la mythologie nordique programme la destruction de ses propres dieux.",
    2, [
    ["Qui est le père des dieux dans la mythologie nordique ?", ["Odin", "Thor", "Loki", "Baldr"], 0,
     "Il a sacrifié un œil pour boire à la source de la sagesse."],
    ["Quel est l'attribut de Thor ?", ["Le marteau Mjöllnir", "La lance Gungnir", "L'épée Gram", "L'anneau Draupnir"], 0,
     "Gungnir est la lance d'Odin, Draupnir son anneau. Le marteau revient toujours dans la main de Thor."],
    ["Comment s'appelle l'arbre-monde de la mythologie nordique ?", ["Yggdrasil", "Bifröst", "Asgard", "Midgard"], 0,
     "Un frêne dont les racines et les branches relient les neuf mondes. Bifröst est le pont arc-en-ciel."],
    ["Comment s'appelle le domaine des dieux Ases ?", ["Asgard", "Midgard", "Helheim", "Vanaheim"], 0,
     "Midgard est le monde des humains, Vanaheim celui des dieux Vanes."],
    ["Où vont les guerriers morts au combat selon la mythologie nordique ?", ["Au Valhalla", "Au Helheim", "À Vanaheim", "À Niflheim"], 0,
     "Les Valkyries les y conduisent pour combattre chaque jour jusqu'au crépuscule des dieux."],
    ["Qui est Loki ?", ["Un dieu rusé et changeant, à l'origine du destin des dieux", "Le dieu de la guerre", "Le gardien du pont Bifröst", "Le dieu de la mer"], 0,
     "Ni entièrement Ase ni géant, il aide les dieux autant qu'il précipite leur perte."],
    ["Quel hiver terrible précède le Ragnarök ?", ["Le Fimbulvetr", "Le Niflheim", "Le Gjallarhorn", "Le Naglfar"], 0,
     "Trois hivers sans été consécutifs. La plupart des dieux périssent ensuite, mais un monde nouveau surgit de la mer."],
    ["Quel loup géant doit dévorer Odin lors du Ragnarök ?", ["Fenrir", "Sköll", "Hati", "Garm"], 0,
     "Fils de Loki, il est enchaîné par une entrave magique au prix de la main du dieu Tyr."],
    ["Quel texte islandais du XIIIe siècle est la principale source de la mythologie nordique ?", ["L'Edda de Snorri Sturluson", "Le Kalevala", "La Chanson des Nibelungen", "Le Beowulf"], 0,
     "Rédigé par un chrétien plus de deux siècles après la christianisation, il transmet une tradition déjà réinterprétée."],
    ["Quel jour de la semaine anglaise tire son nom de Thor ?", ["Thursday", "Tuesday", "Wednesday", "Friday"], 0,
     "Tuesday vient de Tyr, Wednesday d'Odin sous sa forme Woden, Friday de la déesse Frigg ou Freyja.", 3],
  ]),

  notion("mr-mythologie-egyptienne", S, "La mythologie égyptienne",
    "Des dieux à tête d'animal, un jugement des morts, et trois mille ans de continuité.",
    "L'Égypte a maintenu ses cultes pendant plus de trois millénaires, un record dans l'histoire des religions.",
    2, [
    ["Qui est le dieu solaire principal de l'Égypte antique ?", ["Rê", "Osiris", "Ptah", "Amon seul"], 0,
     "Il fusionne à Thèbes avec Amon pour devenir Amon-Rê, dieu dynastique du Nouvel Empire."],
    ["Quel dieu égyptien est assassiné par son frère puis ressuscité ?", ["Osiris", "Horus", "Seth", "Anubis"], 0,
     "Seth le démembre ; Isis rassemble son corps. Osiris devient alors le souverain du royaume des morts."],
    ["Quelle déesse égyptienne est l'épouse d'Osiris ?", ["Isis", "Nephtys", "Hathor", "Sekhmet"], 0,
     "Son culte s'est répandu dans tout le monde romain, jusqu'en Gaule et en Bretagne."],
    ["Quel dieu à tête de faucon venge son père Osiris ?", ["Horus", "Thot", "Khonsou", "Montou"], 0,
     "Le pharaon vivant est identifié à Horus, et à Osiris une fois mort."],
    ["Quel dieu à tête de chacal préside à l'embaumement ?", ["Anubis", "Osiris", "Sobek", "Khnoum"], 0,
     "Il conduit aussi le défunt à la salle du jugement et surveille la balance."],
    ["Contre quoi le cœur du défunt est-il pesé lors du jugement des morts ?", ["Contre la plume de Maât", "Contre une pierre sacrée", "Contre un scarabée d'or", "Contre le cœur d'un dieu"], 0,
     "Maât est l'ordre, la justice et la vérité. Un cœur trop lourd était dévoré par la Grande Dévoreuse."],
    ["Quel dieu à tête d'ibis est le scribe des dieux ?", ["Thot", "Ptah", "Bès", "Khepri"], 0,
     "Inventeur de l'écriture, il note le résultat de la pesée du cœur."],
    ["Quel pharaon impose un culte quasi exclusif au disque solaire Aton ?", ["Akhenaton", "Toutânkhamon", "Ramsès II", "Thoutmôsis III"], 0,
     "Son règne, au XIVe siècle avant notre ère, fut suivi d'un retour rapide aux cultes traditionnels."],
    ["Qu'est-ce que le Livre des morts égyptien ?", ["Un recueil de formules destinées à guider le défunt dans l'au-delà", "Un registre des sépultures", "Un traité d'embaumement", "Une chronique des pharaons"], 0,
     "Placé dans la tombe, il varie d'un exemplaire à l'autre selon les moyens du défunt."],
    ["Que représente le scarabée dans la symbolique égyptienne ?", ["Le renouvellement et la renaissance du soleil", "La protection contre les voleurs", "Le pouvoir royal", "La fertilité des terres"], 0,
     "Le bousier roulant sa boule évoquait le dieu Khepri poussant le soleil à l'horizon.", 3],
  ]),

  notion("mr-judaisme", S, "Le judaïsme",
    "Textes, fêtes, pratiques : les repères d'une des plus anciennes religions monothéistes.",
    "Le Talmud n'est pas un livre de lois mais l'enregistrement d'un débat, avec ses désaccords conservés.",
    2, [
    ["Comment appelle-t-on les cinq premiers livres de la Bible hébraïque ?", ["La Torah", "Les Prophètes", "Les Écrits", "Le Talmud"], 0,
     "La Bible hébraïque comprend aussi les Prophètes et les Écrits, d'où l'acronyme Tanakh."],
    ["Qu'est-ce que le Talmud ?", ["Un vaste recueil de commentaires et de débats rabbiniques", "Un livre de prières", "Le récit de l'Exode", "Un code de lois civil"], 0,
     "Il comprend la Mishna et sa discussion, la Guemara, compilées entre le IIe et le VIe siècle."],
    ["Quel jour est le shabbat ?", ["Du vendredi soir au samedi soir", "Le dimanche", "Le samedi matin seulement", "Le vendredi"], 0,
     "Il commence au coucher du soleil : dans le calendrier juif, le jour débute le soir."],
    ["Que commémore la fête de Pessah ?", ["La sortie d'Égypte", "Le don de la Torah", "La dédicace du Temple", "La création du monde"], 0,
     "Le repas du séder en rejoue le récit, avec des aliments symboliques et le pain sans levain."],
    ["Que commémore Hanouka ?", ["La rededicace du Temple de Jérusalem au IIe siècle avant notre ère", "La sortie d'Égypte", "La création du monde", "Le retour de l'exil de Babylone"], 0,
     "On y allume une lampe à neuf branches, une bougie de plus chaque soir pendant huit jours."],
    ["Qu'est-ce que Yom Kippour ?", ["Le jour du Grand Pardon, marqué par le jeûne", "Le nouvel an juif", "La fête des cabanes", "La fête des sorts"], 0,
     "C'est le jour le plus solennel du calendrier, consacré au repentir et à la réconciliation."],
    ["Qu'est-ce que la cacherout ?", ["L'ensemble des règles alimentaires du judaïsme", "Le rituel du mariage", "Le calendrier des fêtes", "L'étude quotidienne des textes"], 0,
     "Elle interdit notamment le porc, les fruits de mer et le mélange de la viande et du lait."],
    ["Qu'est-ce qu'une synagogue ?", ["Un lieu de prière, d'étude et de rassemblement communautaire", "Un lieu de sacrifice", "La résidence du rabbin", "Un tribunal religieux"], 0,
     "Elle s'est développée après la destruction du Second Temple en 70, qui a mis fin au culte sacrificiel."],
    ["Qu'est-ce que la bar-mitsva ?", ["Le passage à la majorité religieuse d'un garçon à treize ans", "Un rite de naissance", "La cérémonie du mariage", "L'ordination d'un rabbin"], 0,
     "La bat-mitsva en est l'équivalent pour les filles, généralisé au XXe siècle."],
    ["Quel mouvement mystique juif naît en Europe orientale au XVIIIe siècle ?", ["Le hassidisme", "Le karaïsme", "Le sabbatéisme", "Le judaïsme réformé"], 0,
     "Fondé par le Baal Shem Tov, il met l'accent sur la ferveur et la joie plus que sur la seule érudition.", 3],
  ]),

  notion("mr-christianisme", S, "Le christianisme",
    "Une religion née dans le judaïsme, ses conciles, ses divisions et ses grandes confessions.",
    "Les trois grandes branches viennent de deux ruptures : 1054 pour l'orthodoxie, le XVIe siècle pour la Réforme.",
    2, [
    ["Combien de Évangiles sont reconnus canoniques ?", ["Quatre", "Trois", "Sept", "Douze"], 0,
     "Matthieu, Marc, Luc et Jean. Les trois premiers, dits synoptiques, présentent de nombreux récits communs."],
    ["Quel empereur romain autorise le christianisme en 313 ?", ["Constantin", "Théodose", "Dioclétien", "Julien"], 0,
     "L'édit de Milan proclame la liberté de culte. Théodose en fera la religion officielle en 380."],
    ["Quel concile de 325 formule un credo commun ?", ["Le concile de Nicée", "Le concile de Chalcédoine", "Le concile d'Éphèse", "Le concile de Trente"], 0,
     "Il tranche la question de la nature du Christ contre l'arianisme."],
    ["Quel événement marque en 1054 la séparation entre Rome et Constantinople ?", ["Le Grand Schisme d'Orient", "La prise de Constantinople", "Le concile de Latran", "La querelle des Investitures"], 0,
     "Les excommunications réciproques n'ont été levées qu'en 1965."],
    ["Qui affiche en 1517 des thèses contre les indulgences ?", ["Martin Luther", "Jean Calvin", "Ulrich Zwingli", "Thomas Müntzer"], 0,
     "Le geste est traditionnellement situé à Wittenberg. Il ouvre la Réforme protestante."],
    ["Quel réformateur s'installe à Genève et y organise une Église réformée ?", ["Jean Calvin", "Martin Luther", "Philippe Melanchthon", "Théodore de Bèze"], 0,
     "Son Institution de la religion chrétienne, publiée en français en 1541, marque aussi l'histoire de la langue."],
    ["Quel concile catholique répond à la Réforme au XVIe siècle ?", ["Le concile de Trente", "Le concile de Nicée II", "Le concile de Constance", "Le concile de Bâle"], 0,
     "Réuni de 1545 à 1563, il définit la doctrine catholique et réforme la discipline du clergé."],
    ["Quel concile catholique du XXe siècle réforme la liturgie et les rapports au monde moderne ?", ["Vatican II", "Vatican I", "Le concile de Trente", "Le concile de Latran V"], 0,
     "Réuni de 1962 à 1965, il autorise notamment la messe en langue vernaculaire."],
    ["Quel est le chef de l'Église catholique ?", ["Le pape, évêque de Rome", "Le patriarche de Constantinople", "L'archevêque de Canterbury", "Le collège des cardinaux"], 0,
     "Les orthodoxes reconnaissent au patriarche de Constantinople une primauté d'honneur, non de juridiction."],
    ["Qu'est-ce que l'anglicanisme ?", ["Une Église née de la rupture d'Henri VIII avec Rome en 1534", "Une branche du luthéranisme", "Une Église orthodoxe occidentale", "Un courant calviniste anglais"], 0,
     "Elle conserve une organisation épiscopale tout en adoptant des éléments doctrinaux de la Réforme.", 3],
  ]),

  notion("mr-islam", S, "L'islam",
    "Piliers, textes, courants et grandes étapes d'une religion suivie par près d'un quart de l'humanité.",
    "La distinction entre sunnites et chiites naît d'une question de succession politique, non de doctrine initiale.",
    2, [
    ["Combien de piliers l'islam sunnite compte-t-il ?", ["Cinq", "Six", "Quatre", "Trois"], 0,
     "Profession de foi, prière, aumône, jeûne du ramadan et pèlerinage à La Mecque."],
    ["Que rapportent les hadiths ?", ["Les paroles et les actes attribués au Prophète", "Les révélations coraniques", "Les décisions des califes", "Les récits de la conquête"], 0,
     "Réunis dans la Sunna, ils complètent le Coran. Leur authenticité est classée selon la solidité de la chaîne de transmission."],
    ["En combien de chapitres le Coran est-il divisé ?", ["Cent quatorze sourates", "Cent", "Cinquante", "Deux cents"], 0,
     "Elles sont classées de la plus longue à la plus courte, non par ordre chronologique de révélation."],
    ["Quel événement marque le début du calendrier musulman ?", ["L'hégire, le départ de La Mecque vers Médine", "La naissance du Prophète", "La première révélation", "La prise de La Mecque"], 0,
     "En 622 de l'ère commune. Le calendrier est lunaire, d'où le décalage annuel des fêtes."],
    ["Que commémore l'Aïd el-Fitr ?", ["La fin du mois de ramadan", "Le pèlerinage", "Le sacrifice d'Abraham", "La naissance du Prophète"], 0,
     "L'Aïd el-Adha, la grande fête, commémore le sacrifice interrompu d'Abraham."],
    ["Comment s'appelle le pèlerinage à La Mecque ?", ["Le hajj", "La omra", "La zakat", "Le sawm"], 0,
     "Il a lieu à une date précise et s'impose une fois dans la vie à qui en a les moyens. La omra peut se faire à tout moment."],
    ["Quelle est l'origine de la division entre sunnites et chiites ?", ["Un désaccord sur la succession du Prophète", "Une divergence sur le texte du Coran", "Un conflit sur les rites de prière", "Une querelle sur le calendrier"], 0,
     "Les chiites soutenaient qu'elle devait revenir à Ali, cousin et gendre du Prophète, et à sa descendance."],
    ["Qu'est-ce que le soufisme ?", ["Une voie mystique de l'islam", "Une école juridique", "Un courant réformiste moderne", "Une branche du chiisme"], 0,
     "Il traverse sunnisme et chiisme et a produit une immense littérature poétique, dont l'œuvre de Rûmî."],
    ["Qu'est-ce que la charia ?", ["Un ensemble de normes tirées du Coran et de la Sunna, diversement interprétées", "Un code pénal unique", "La constitution des États musulmans", "Un recueil de fatwas"], 0,
     "Quatre grandes écoles juridiques sunnites en proposent des lectures différentes, sans autorité centrale pour trancher."],
    ["Quelle dynastie établit Bagdad comme capitale au VIIIe siècle ?", ["Les Abbassides", "Les Omeyyades", "Les Fatimides", "Les Seldjoukides"], 0,
     "La ville devint un foyer intellectuel majeur, où furent traduits et prolongés les savoirs grecs, persans et indiens.", 3],
  ]),

  notion("mr-hindouisme-bouddhisme", S, "L'hindouisme et le bouddhisme",
    "Deux traditions nées en Inde, leurs textes, leurs notions clés et leur diffusion.",
    "Le bouddhisme est né en réaction à certains aspects de la tradition védique, dont il partage le vocabulaire.",
    2, [
    ["Quels sont les textes les plus anciens de la tradition hindoue ?", ["Les Védas", "Les Upanishads", "La Bhagavad-Gîtâ", "Le Ramayana"], 0,
     "Composés entre 1500 et 500 avant notre ère, ils ont été transmis oralement avec une extrême précision."],
    ["Qu'est-ce que le karma ?", ["La loi selon laquelle les actes déterminent les existences futures", "Le destin fixé à la naissance", "L'âme individuelle", "Le cycle des saisons"], 0,
     "Il n'implique ni jugement ni juge : c'est une causalité, comparable à une loi naturelle."],
    ["Qu'est-ce que le samsara ?", ["Le cycle des renaissances", "La libération finale", "La méditation", "Le devoir propre à chacun"], 0,
     "La sortie de ce cycle s'appelle moksha dans l'hindouisme, nirvana dans le bouddhisme."],
    ["Quels dieux forment la trimurti hindoue ?", ["Brahma, Vishnou et Shiva", "Indra, Agni et Varuna", "Krishna, Rama et Ganesh", "Vishnou, Lakshmi et Shiva"], 0,
     "Créateur, conservateur et destructeur. Krishna et Rama sont des avatars de Vishnou."],
    ["Quelle épopée indienne contient la Bhagavad-Gîtâ ?", ["Le Mahabharata", "Le Ramayana", "Les Puranas", "Le Rig-Véda"], 0,
     "Le dialogue entre Arjuna et Krishna, avant la bataille, est devenu un texte spirituel autonome."],
    ["Qui est le fondateur historique du bouddhisme ?", ["Siddhartha Gautama", "Ashoka", "Nagarjuna", "Bodhidharma"], 0,
     "Prince du nord de l'Inde au Ve siècle avant notre ère, il devient le Bouddha, l'Éveillé."],
    ["Quelles sont les quatre nobles vérités du bouddhisme ?", ["Le constat de la souffrance, son origine, sa cessation et la voie qui y mène", "Les quatre étapes de la méditation", "Les quatre castes", "Les quatre âges du monde"], 0,
     "La voie est dite octuple : elle décrit huit aspects de la conduite, de l'attention et de la compréhension."],
    ["Quel empereur indien du IIIe siècle avant notre ère favorise la diffusion du bouddhisme ?", ["Ashoka", "Chandragupta", "Kanishka", "Harsha"], 0,
     "Après une guerre particulièrement meurtrière, il fit graver des édits prônant la non-violence sur des piliers de pierre."],
    ["Quelle grande branche du bouddhisme est majoritaire au Tibet et en Mongolie ?", ["Le bouddhisme vajrayana", "Le theravada", "Le zen", "L'amidisme"], 0,
     "Le theravada domine en Asie du Sud-Est, le mahayana en Chine, en Corée et au Japon."],
    ["Qu'est-ce que le nirvana ?", ["l'extinction de la soif et la sortie du cycle des renaissances", "Un paradis céleste", "Un état de transe", "La fusion avec une divinité"], 0,
     "Le mot signifie littéralement extinction, comme celle d'une flamme privée de combustible.", 3],
  ]),

  notion("mr-religions-monde", S, "Autres religions et croyances",
    "Sikhisme, jaïnisme, shintoïsme, animismes : au-delà des grandes traditions les plus connues.",
    "La religion la plus pratiquée d'un pays ne dit rien de la diversité réelle de ses croyances.",
    2, [
    ["Où le sikhisme est-il né au XVe siècle ?", ["Au Pendjab, en Inde", "Au Bengale", "Au Tibet", "En Perse"], 0,
     "Fondé par Guru Nanak, il affirme un Dieu unique et rejette le système des castes."],
    ["Quel principe est au cœur du jaïnisme ?", ["La non-violence envers tout être vivant", "Le renoncement à la parole", "Le culte des ancêtres", "L'égalité de tous les dieux"], 0,
     "L'ahimsa y est poussé à l'extrême : certains moines balaient le sol devant eux pour ne pas écraser d'insecte."],
    ["Quelle religion traditionnelle du Japon vénère des esprits appelés kami ?", ["Le shintoïsme", "Le bouddhisme zen", "Le taoïsme", "Le confucianisme"], 0,
     "Les kami habitent les lieux, les phénomènes naturels et les ancêtres. Shinto et bouddhisme coexistent au Japon."],
    ["Le confucianisme est-il d'abord une religion ?", ["Non, c'est avant tout une doctrine morale et politique", "Oui, avec un panthéon organisé", "Oui, il repose sur un livre révélé", "Non, c'est une école de méditation"], 0,
     "Il porte sur l'ordre social, le rite et le devoir. Sa dimension cultuelle s'est développée plus tard."],
    ["Quel principe est au cœur du taoïsme ?", ["Le tao, voie naturelle qu'il s'agit de suivre sans forcer", "Le culte de l'empereur", "La discipline monastique", "Le sacrifice rituel"], 0,
     "Le non-agir n'est pas la passivité mais l'action conforme au cours naturel des choses."],
    ["Quelle religion fondée en Perse au VIe siècle avant notre ère oppose un principe bon à un principe mauvais ?", ["Le zoroastrisme", "Le manichéisme", "Le mithraïsme", "Le mazdéisme sassanide seul"], 0,
     "Elle a influencé les représentations du bien et du mal dans les monothéismes ultérieurs."],
    ["Qu'est-ce que l'animisme ?", ["La croyance en une force ou un esprit animant les êtres et les éléments", "Le culte des animaux", "La croyance en la réincarnation animale", "Le culte des ancêtres uniquement"], 0,
     "Le terme, forgé au XIXe siècle par les ethnologues, recouvre des traditions très diverses."],
    ["Qu'est-ce que le vaudou ?", ["Un ensemble de cultes ouest-africains et de leurs prolongements américains", "Une pratique de sorcellerie individuelle", "Un culte des morts haïtien uniquement", "Une branche du christianisme populaire"], 0,
     "Religion officiellement reconnue au Bénin, il a été profondément déformé par sa représentation dans le cinéma."],
    ["Qu'est-ce que la laïcité en France ?", ["Un principe de neutralité de l'État garantissant la liberté de conscience", "l'interdiction des religions dans l'espace public", "L'athéisme d'État", "La reconnaissance de toutes les religions par l'État"], 0,
     "La loi de 1905 sépare les Églises et l'État : elle ne reconnaît ni ne subventionne aucun culte."],
    ["Quelle est approximativement la part de personnes sans affiliation religieuse dans le monde ?", ["Environ un sixième de la population", "Environ la moitié", "Moins de cinq pour cent", "Environ un tiers"], 0,
     "Ce groupe est très hétérogène : athées, agnostiques et personnes croyantes sans appartenance déclarée.", 3],
  ]),

  notion("mr-symboles-rites", S, "Symboles et rites",
    "Ce que font les rites, comment ils marquent le temps et les étapes de la vie.",
    "Un rite de passage se déroule en trois temps : séparation, marge, agrégation.",
    2, [
    ["Quel ethnologue français décrit les rites de passage en trois étapes ?", ["Arnold Van Gennep", "Marcel Mauss", "Claude Lévi-Strauss", "Émile Durkheim"], 0,
     "Séparation, marge et agrégation : le schéma s'applique aux funérailles comme aux mariages ou aux initiations."],
    ["Qu'est-ce qu'un rite de passage ?", ["Un rituel marquant un changement de statut social", "Une cérémonie saisonnière", "Un pèlerinage obligatoire", "Un rite de purification"], 0,
     "Naissance, majorité, mariage, funérailles en sont les occasions les plus universelles."],
    ["Que désigne le sacré selon Émile Durkheim ?", ["Ce qui est séparé du profane par la société elle-même", "Ce qui vient de la divinité", "Ce qui est interdit", "Ce qui relève du surnaturel"], 0,
     "Pour lui, la religion est d'abord un fait social : la société se célèbre elle-même à travers ses dieux."],
    ["Qu'est-ce qu'un tabou ?", ["Une interdiction dont la transgression est perçue comme dangereuse", "Un objet sacré", "Un rite secret", "Une croyance ancienne"], 0,
     "Le mot vient du polynésien tapu et a été introduit en Europe par les récits de voyage du XVIIIe siècle."],
    ["Qu'est-ce qu'un totem ?", ["Un être ou un objet servant d'emblème à un groupe", "Une statue divine", "Un objet de sorcellerie", "Un lieu sacré"], 0,
     "Il fonde souvent une parenté symbolique et un ensemble d'interdits partagés."],
    ["Que signifie l'expression « le don et le contre-don » chez Marcel Mauss ?", ["Le don crée une obligation de rendre qui lie les groupes", "Le don doit rester anonyme", "Le don est toujours désintéressé", "Le don est une transaction déguisée"], 0,
     "Son Essai sur le don, publié en 1925, montre que donner, recevoir et rendre structurent des sociétés entières."],
    ["Que représente le symbole du yin et du yang ?", ["Deux principes complémentaires présents l'un dans l'autre", "L'opposition du bien et du mal", "La séparation du ciel et de la terre", "Le cycle des saisons"], 0,
     "Chaque moitié contient un point de l'autre : rien n'est purement l'un ou purement l'autre."],
    ["Que signifie le mot pèlerinage ?", ["Un voyage vers un lieu tenu pour sacré", "Une procession locale", "Une retraite spirituelle", "Une marche de pénitence"], 0,
     "Compostelle, La Mecque, Bénarès et Lourdes en sont parmi les plus fréquentés au monde."],
    ["Qu'est-ce qu'une relique ?", ["Un reste corporel ou un objet lié à un personnage sacré", "Un objet de culte ancien", "Une offrande déposée dans un sanctuaire", "Un manuscrit sacré"], 0,
     "Le commerce des reliques, très actif au Moyen Âge, a nourri l'économie de nombreux sanctuaires."],
    ["Qu'est-ce que le syncrétisme religieux ?", ["La fusion d'éléments issus de traditions différentes", "La coexistence de plusieurs religions", "L'abandon d'une religion pour une autre", "La traduction d'un texte sacré"], 0,
     "Les religions afro-brésiliennes en offrent un exemple : des divinités africaines y sont associées à des saints catholiques.", 3],
  ]),

  notion("mr-mythes-fondateurs", S, "Les grands récits fondateurs",
    "Déluges, créations, héros civilisateurs : des motifs qui reviennent d'une culture à l'autre.",
    "Le récit du déluge est attesté en Mésopotamie plus de mille ans avant sa version biblique.",
    2, [
    ["Dans quelle œuvre mésopotamienne trouve-t-on un récit de déluge antérieur à la Bible ?", ["L'Épopée de Gilgamesh", "Le Code de Hammurabi", "Les Annales assyriennes", "Le Livre des morts"], 0,
     "Sa découverte au XIXe siècle a profondément modifié la lecture historique des textes bibliques."],
    ["Que raconte le mythe de Prométhée ?", ["Le vol du feu aux dieux pour le donner aux hommes", "La création du monde", "La chute des Titans", "La naissance d'Athéna"], 0,
     "Zeus le punit en l'enchaînant, un aigle lui dévorant le foie chaque jour."],
    ["Que raconte le mythe de la boîte de Pandore ?", ["L'ouverture d'une jarre libérant les maux sur le monde", "La création de la première femme seulement", "La punition d'un roi avare", "Le vol d'un trésor divin"], 0,
     "Le texte grec parle d'une jarre ; la traduction en boîte est une erreur du XVIe siècle devenue courante."],
    ["Que symbolise la tour de Babel dans le récit biblique ?", ["L'origine de la diversité des langues", "La chute d'un empire", "La naissance des villes", "Le premier temple"], 0,
     "Le récit lie l'orgueil humain à la confusion des langues et à la dispersion des peuples."],
    ["Quel héros grec accomplit douze travaux ?", ["Héraclès", "Thésée", "Persée", "Jason"], 0,
     "Imposés en expiation d'un meurtre commis dans une crise de folie envoyée par Héra."],
    ["Quel héros grec doit affronter le Minotaure dans un labyrinthe ?", ["Thésée", "Héraclès", "Persée", "Bellérophon"], 0,
     "Ariane lui donne un fil pour retrouver la sortie. Dédale avait conçu le labyrinthe."],
    ["Que raconte le mythe d'Icare ?", ["Un vol trop proche du soleil qui fait fondre la cire des ailes", "Une chute dans un labyrinthe", "Une traversée de la mer à la nage", "Un enlèvement par un aigle"], 0,
     "Fils de Dédale, il ignore l'avertissement de son père. Le mythe sert d'emblème à la démesure."],
    ["Que raconte le mythe de Sisyphe ?", ["Un homme condamné à rouler éternellement un rocher", "Un roi transformé en pierre", "Un géant portant le ciel", "Un homme changé en fleuve"], 0,
     "Albert Camus en a tiré en 1942 une image de la condition humaine face à l'absurde."],
    ["Que raconte la légende du roi Arthur ?", ["Un roi breton entouré de chevaliers en quête du Graal", "La fondation de Rome", "La conquête de l'Angleterre par les Normands", "Le siège d'une cité par des géants"], 0,
     "Le cycle s'est enrichi du XIIe au XVe siècle, notamment sous la plume de Chrétien de Troyes."],
    ["Que désigne l'expression « mythe fondateur » ?", ["Un récit qui explique l'origine d'un peuple ou d'une institution", "Une légende sans fondement", "Un texte sacré", "Un récit héroïque ancien"], 0,
     "Romulus et Rémus pour Rome, le serment du Grütli pour la Suisse : leur véracité historique importe moins que leur fonction.", 3],
  ]),

  notion("mr-philosophie-religion", S, "Philosophie et questions religieuses",
    "Les grandes positions sur l'existence de Dieu, le mal et le sens, telles que la philosophie les a formulées.",
    "L'agnosticisme n'est pas une position intermédiaire entre foi et athéisme : il porte sur ce qu'on peut savoir.",
    2, [
    ["Qu'est-ce que l'agnosticisme ?", ["La position selon laquelle on ne peut savoir si Dieu existe", "La croyance en un dieu impersonnel", "Le refus de toute religion", "L'indifférence aux questions religieuses"], 0,
     "Le terme est forgé par Thomas Huxley en 1869. Il porte sur la connaissance, non sur la croyance."],
    ["Qu'est-ce que le déisme ?", ["La croyance en un Dieu créateur sans religion révélée", "L'athéisme modéré", "Le culte de la nature", "La croyance en plusieurs dieux"], 0,
     "Voltaire et de nombreux penseurs des Lumières s'en réclamaient, contre les Églises institutionnelles."],
    ["Qu'est-ce que le panthéisme ?", ["L'identification de Dieu et de la nature", "Le culte de tous les dieux", "La croyance en un dieu personnel", "Le rejet du sacré"], 0,
     "Spinoza en est la figure majeure, ce qui lui valut d'être excommunié et longtemps tenu pour athée."],
    ["Qu'appelle-t-on le problème du mal en philosophie ?", ["La difficulté de concilier l'existence du mal avec un Dieu bon et tout-puissant", "La question de l'origine du péché", "La définition du bien", "Le débat sur la liberté humaine"], 0,
     "Épicure en aurait formulé la première version. Leibniz y répond en 1710 par sa théodicée."],
    ["Qu'est-ce que le pari de Pascal ?", ["Un argument selon lequel il est rationnel de parier sur l'existence de Dieu", "Une preuve de l'existence de Dieu", "Une critique de la superstition", "Un raisonnement sur l'infini mathématique"], 0,
     "Il ne prétend pas prouver, mais raisonner en termes de gains et de pertes en situation d'incertitude."],
    ["Quelle preuve de l'existence de Dieu Anselme de Cantorbéry propose-t-il ?", ["L'argument ontologique", "L'argument cosmologique", "L'argument du dessein", "L'argument moral"], 0,
     "Il tire l'existence de Dieu de la seule définition de son concept. Kant en montrera la faiblesse."],
    ["Quel philosophe déclare que Dieu est mort ?", ["Friedrich Nietzsche", "Ludwig Feuerbach", "Karl Marx", "Arthur Schopenhauer"], 0,
     "Ce n'est pas un constat théologique mais culturel : les valeurs fondées sur Dieu ont perdu leur évidence."],
    ["Que dit Marx de la religion ?", ["Qu'elle est l'opium du peuple, à la fois consolation et illusion", "Qu'elle doit être interdite", "Qu'elle est indifférente à l'économie", "Qu'elle précède toute société"], 0,
     "La formule complète parle du soupir de la créature opprimée : elle est moins uniquement accusatrice qu'on ne le cite."],
    ["Qu'est-ce que la sécularisation ?", ["Le recul de l'emprise du religieux sur les institutions et les mœurs", "L'interdiction du culte public", "La nationalisation des biens du clergé", "La conversion massive à l'athéisme"], 0,
     "Elle ne se confond pas avec la disparition des croyances, qui se recomposent plutôt qu'elles ne s'effacent."],
    ["Que soutient le fidéisme ?", ["Que la foi ne peut être fondée par la raison", "Que la raison prouve la foi", "Que la foi est une illusion", "Que la religion est d'abord sociale"], 0,
     "Tertullien en offre une formule extrême, souvent citée sous une forme apocryphe : je crois parce que c'est absurde.", 3],
  ]),

  notion("mr-calendriers-fetes", S, "Calendriers et fêtes",
    "Comment les religions ont découpé le temps, et pourquoi les dates se déplacent.",
    "Un calendrier lunaire dérive d'environ onze jours par an par rapport au calendrier solaire.",
    2, [
    ["Pourquoi les fêtes musulmanes se décalent-elles chaque année ?", ["Le calendrier musulman est purement lunaire", "Les dates sont fixées chaque année par les autorités", "Il suit un cycle de sept ans", "Il compte trois cent soixante jours"], 0,
     "Douze mois lunaires font environ trois cent cinquante-quatre jours, d'où un décalage d'une dizaine de jours."],
    ["Sur quoi le calendrier juif est-il fondé ?", ["Un calendrier luni-solaire avec mois intercalaire", "Un calendrier lunaire pur", "Un calendrier solaire", "Un calendrier de trois cent soixante jours"], 0,
     "Un treizième mois est ajouté sept fois par cycle de dix-neuf ans, ce qui maintient Pessah au printemps."],
    ["Comment la date de Pâques chrétienne est-elle calculée ?", ["Le premier dimanche après la pleine lune suivant l'équinoxe de printemps", "Une date fixe en avril", "Le premier dimanche d'avril", "Quarante jours après le carême"], 0,
     "D'où sa mobilité entre le 22 mars et le 25 avril dans le calendrier grégorien."],
    ["Quel pape réforme le calendrier en 1582 ?", ["Grégoire XIII", "Jules II", "Léon X", "Pie V"], 0,
     "Dix jours furent supprimés pour rattraper la dérive du calendrier julien. Certains pays attendirent le XXe siècle pour l'adopter."],
    ["Pourquoi les Églises orthodoxes fêtent-elles parfois Noël le 7 janvier ?", ["Elles suivent le calendrier julien pour les fêtes", "Elles célèbrent une autre naissance", "Elles ajoutent une période de jeûne", "Elles suivent un calendrier lunaire"], 0,
     "Le décalage entre calendriers julien et grégorien est aujourd'hui de treize jours."],
    ["Quelle est l'origine de la fête de Halloween ?", ["Une fête celtique de fin des récoltes, reprise par la veille de la Toussaint", "Une fête romaine des morts", "Une invention commerciale américaine", "Une tradition scandinave"], 0,
     "Samain marquait le passage à la saison sombre. Son nom actuel vient de All Hallows' Eve."],
    ["Que célèbre le nouvel an chinois ?", ["Le début de l'année du calendrier luni-solaire chinois", "Le solstice d'hiver", "L'équinoxe de printemps", "La fin des moissons"], 0,
     "Il tombe entre le 21 janvier et le 20 février, à la deuxième nouvelle lune après le solstice d'hiver."],
    ["Qu'est-ce que Diwali ?", ["La fête des lumières célébrée notamment dans l'hindouisme", "Le nouvel an hindou uniquement", "Une fête des moissons", "Une fête bouddhiste"], 0,
     "Elle est aussi célébrée par des sikhs et des jaïns, avec des significations propres à chaque tradition."],
    ["Que commémore le Nouvel An perse Nowrouz ?", ["L'équinoxe de printemps", "La fondation d'un empire", "Une victoire militaire", "La naissance de Zoroastre"], 0,
     "Célébré dans une dizaine de pays, il est inscrit au patrimoine culturel immatériel de l'humanité."],
    ["Pourquoi la semaine compte-t-elle sept jours ?", ["Un héritage babylonien lié aux astres visibles à l'œil nu", "Une décision de l'Église", "Un découpage du mois lunaire romain", "Une convention agricole médiévale"], 0,
     "Sept astres mobiles connus des anciens : le Soleil, la Lune et cinq planètes. Les noms des jours en gardent la trace.", 3],
  ]),

  notion("mr-lieux-sacres", S, "Les grands lieux sacrés",
    "Jérusalem, La Mecque, Bénarès, Compostelle : des lieux, leur histoire et ce qui s'y pratique.",
    "Jérusalem est un lieu saint pour les trois monothéismes, ce qui explique la complexité de son statut.",
    2, [
    ["Quel édifice de La Mecque les musulmans du monde entier orientent-ils leur prière vers lui ?", ["La Kaaba", "La mosquée du Prophète", "Le dôme du Rocher", "La mosquée al-Aqsa"], 0,
     "Cette direction s'appelle la qibla. La mosquée du Prophète se trouve à Médine."],
    ["Quel mur de Jérusalem est un lieu de prière majeur du judaïsme ?", ["Le mur occidental", "Le mur du dôme", "Le mur de la Vieille Ville", "Le mur de Sion"], 0,
     "Dernier vestige du soubassement de l'esplanade du Second Temple, détruit en 70."],
    ["Quelle basilique du Vatican est le plus grand édifice religieux catholique ?", ["La basilique Saint-Pierre", "La basilique Saint-Jean-de-Latran", "La basilique Sainte-Marie-Majeure", "La basilique Saint-Paul-hors-les-Murs"], 0,
     "Saint-Jean-de-Latran est pourtant la cathédrale de Rome et le siège officiel de l'évêque."],
    ["Quelle ville indienne au bord du Gange est un lieu de pèlerinage hindou majeur ?", ["Bénarès", "Bombay", "Calcutta", "Amritsar"], 0,
     "Y mourir et y être incinéré est censé libérer du cycle des renaissances. Amritsar est le grand lieu saint sikh."],
    ["Quel sanctuaire d'Espagne est l'aboutissement d'un pèlerinage médiéval majeur ?", ["Saint-Jacques-de-Compostelle", "Montserrat", "Le Pilar de Saragosse", "Covadonga"], 0,
     "Les chemins qui y mènent traversent la France et sont inscrits au patrimoine mondial."],
    ["Quel temple bouddhiste indonésien est le plus grand du monde ?", ["Borobudur", "Angkor Vat", "Le Wat Pho", "Le Shwedagon"], 0,
     "Construit au IXe siècle à Java, il fut longtemps recouvert par la végétation et les cendres volcaniques."],
    ["Quel ensemble monumental du Cambodge fut d'abord un temple hindou ?", ["Angkor Vat", "Borobudur", "Bagan", "Prambanan"], 0,
     "Dédié à Vishnou au XIIe siècle, il devint bouddhique par la suite et figure sur le drapeau national."],
    ["Quel lieu de pèlerinage marial français attire des millions de visiteurs chaque année ?", ["Lourdes", "Lisieux", "Le Puy-en-Velay", "La Salette"], 0,
     "Le pèlerinage est né des apparitions rapportées par Bernadette Soubirous en 1858."],
    ["Quelle est la plus ancienne mosquée encore en fonction du monde musulman occidental ?", ["La mosquée de Kairouan, en Tunisie", "La mosquée de Cordoue", "La mosquée al-Azhar", "La Koutoubia"], 0,
     "Fondée au VIIe siècle, elle a servi de modèle architectural dans tout le Maghreb."],
    ["Quel mont grec abrite une république monastique orthodoxe autonome ?", ["Le mont Athos", "Le mont Olympe", "Le mont Parnasse", "Le mont Pélion"], 0,
     "Vingt monastères y forment un État autonome au sein de la Grèce, dont l'accès est interdit aux femmes depuis des siècles.", 3],
  ]),

  notion("mr-textes-sacres", S, "Canon, exégèse et interprétation",
    "Comment un texte devient canonique, comment il se transmet et comment on l'étudie.",
    "Un canon est le résultat d'un processus historique de sélection, souvent long et disputé.",
    2, [
    ["Qu'est-ce qu'un canon dans le domaine religieux ?", ["La liste des textes reconnus comme faisant autorité", "Le commentaire officiel d'un texte", "Une règle liturgique", "L'ensemble des lois religieuses"], 0,
     "Le canon chrétien s'est fixé progressivement entre le IIe et le IVe siècle."],
    ["Qu'est-ce qu'un texte apocryphe ?", ["Un texte écarté du canon", "Un texte anonyme", "Un texte falsifié", "Un texte perdu"], 0,
     "Les évangiles apocryphes sont nombreux et renseignent sur la diversité du christianisme ancien."],
    ["Quels manuscrits découverts en 1947 près de la mer Morte éclairent le judaïsme ancien ?", ["Les manuscrits de Qumrân", "Les papyrus d'Oxyrhynque", "Les codex de Nag Hammadi", "Les tablettes d'Ougarit"], 0,
     "Ils contiennent les plus anciennes copies connues de textes bibliques, antérieures de mille ans aux copies disponibles."],
    ["Quels manuscrits découverts en Égypte en 1945 contiennent des textes gnostiques ?", ["Les codex de Nag Hammadi", "Les manuscrits de la mer Morte", "Les papyrus d'Éléphantine", "Les ostraca de Deir el-Médineh"], 0,
     "Ils incluent l'Évangile selon Thomas, recueil de paroles attribuées à Jésus."],
    ["Qu'est-ce que l'exégèse ?", ["L'étude critique et l'interprétation d'un texte", "La récitation rituelle", "La traduction liturgique", "La copie manuscrite"], 0,
     "L'exégèse historico-critique replace le texte dans son contexte de production."],
    ["Qu'est-ce qu'une herméneutique ?", ["Une théorie de l'interprétation", "Une méthode de datation", "Un commentaire littéral", "Une science des manuscrits"], 0,
     "Elle s'est étendue au-delà des textes sacrés, jusqu'à la philosophie et aux sciences humaines."],
    ["Comment se transmettaient les Védas avant leur mise par écrit ?", ["Oralement, par des techniques de mémorisation très codifiées", "Sur des tablettes d'argile", "Par des inscriptions sur pierre", "Sur des feuilles de palmier dès l'origine"], 0,
     "Plusieurs récitations parallèles servaient de contrôle mutuel, garantissant une fidélité remarquable."],
    ["Qu'est-ce que la massore dans la tradition juive ?", ["Un appareil de notes garantissant l'exactitude du texte biblique", "Un commentaire mystique", "Un recueil de lois", "Une traduction en araméen"], 0,
     "Les massorètes comptaient les lettres et les mots pour prévenir toute altération lors des copies."],
    ["Comment le texte du Coran a-t-il été fixé ?", ["Par une recension écrite ordonnée sous le calife Othman", "Par un concile de savants", "Par une révélation unique consignée immédiatement", "Par une compilation médiévale tardive"], 0,
     "Les variantes de lecture reconnues portent sur la vocalisation, non sur la structure du texte."],
    ["Qu'est-ce qu'un colophon dans un manuscrit ancien ?", ["Une note finale indiquant le copiste, le lieu ou la date", "L'enluminure de la première page", "La reliure d'origine", "Une marque de propriété"], 0,
     "C'est souvent la seule source d'information sur les conditions de production d'un manuscrit.", 3],
  ]),
];
