/**
 * Mythologie & Religions, deuxième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Mythologie & Religions";

export const CG_MYTHOLOGIE_RELIGIONS_2: SeedSkill[] = [
  notion("mr2-mythologie-grecque-dieux", S, "Les dieux de l'Olympe",
    "Douze grandes divinités, leurs attributs et leurs domaines.",
    "Chaque dieu grec a un attribut qui permet de l'identifier dans les représentations.",
    2, [
    ["Quel dieu grec règne sur l'Olympe ?", ["Zeus", "Poséidon", "Hadès", "Apollon"], 0,
     "Son attribut est la foudre. Son équivalent romain est Jupiter."],
    ["Quelle épithète Poséidon porte-t-il en raison de son pouvoir sur les séismes ?", ["L'ébranleur de la terre", "Le maître des flots", "Le porteur du trident", "Le dompteur des chevaux"], 0,
     "Les Grecs attribuaient les tremblements de terre à des coups de son trident sur le sol."],
    ["Quel dieu grec règne sur le monde des morts ?", ["Hadès", "Thanatos", "Charon", "Hermès"], 0,
     "Thanatos personnifie la mort, Charon passe les âmes. Hadès désigne aussi le lieu lui-même."],
    ["Quelle déesse grecque est celle de la sagesse et de la guerre stratégique ?", ["Athéna", "Héra", "Artémis", "Aphrodite"], 0,
     "Née tout armée de la tête de Zeus. La chouette et l'olivier sont ses attributs."],
    ["Quelle déesse grecque est celle de l'amour et de la beauté ?", ["Aphrodite", "Héra", "Perséphone", "Hestia"], 0,
     "Née de l'écume selon une version, fille de Zeus selon une autre. Vénus chez les Romains."],
    ["Quel dieu grec est celui de la forge et du feu ?", ["Héphaïstos", "Arès", "Apollon", "Hélios"], 0,
     "Seul dieu difforme et boiteux de l'Olympe, il fabrique les armes des dieux."],
    ["Quel dieu grec est le messager des dieux ?", ["Hermès", "Apollon", "Iris seule", "Éros"], 0,
     "Il conduit aussi les âmes aux Enfers et protège les voyageurs, les marchands et les voleurs."],
    ["Quelle déesse grecque protège les moissons et les récoltes ?", ["Déméter", "Héra", "Hestia", "Artémis"], 0,
     "L'enlèvement de sa fille Perséphone explique mythologiquement le cycle des saisons."],
    ["Quel dieu grec est associé au vin et à l'extase ?", ["Dionysos", "Apollon", "Pan", "Silène"], 0,
     "Son culte comportait des rites de transe, très différents de la mesure apollinienne."],
  ]),

  notion("mr2-mythologie-grecque-recits", S, "Les grands récits grecs",
    "Théogonie, guerre de Troie, cycles héroïques.",
    "Les mythes grecs ne forment pas un système cohérent : les versions se contredisent souvent.",
    2, [
    ["Quel poète grec raconte la naissance des dieux dans la Théogonie ?", ["Hésiode", "Homère", "Pindare", "Eschyle"], 0,
     "Il y décrit une succession de générations divines s'achevant par le règne de Zeus."],
    ["Qui sont les Titans ?", ["Les divinités de la génération précédant les Olympiens", "Des géants ennemis des hommes", "Les enfants de Zeus", "Les gardiens des Enfers"], 0,
     "Zeus les renverse au terme d'un conflit appelé Titanomachie."],
    ["Quel événement déclenche la guerre de Troie selon le mythe ?", ["L'enlèvement d'Hélène par Pâris", "Le vol de l'or troyen", "Le meurtre d'un ambassadeur", "Une querelle entre rois grecs"], 0,
     "En amont, le jugement de Pâris entre trois déesses avait scellé les alliances divines."],
    ["Quelle ruse permet la prise de Troie ?", ["Le cheval de bois", "L'incendie du port", "L'empoisonnement des puits", "La trahison d'un prêtre"], 0,
     "Attribuée à Ulysse. L'épisode est raconté dans l'Odyssée et l'Énéide, non dans l'Iliade."],
    ["Quel héros grec est invulnérable sauf au talon ?", ["Achille", "Ajax", "Hector", "Patrocle"], 0,
     "Sa mère l'aurait plongé dans le Styx en le tenant par le talon."],
    ["Qui est le principal héros troyen tué par Achille ?", ["Hector", "Pâris", "Énée", "Priam"], 0,
     "Achille traîne son corps autour des murs de la ville, épisode central de l'Iliade."],
    ["Quel héros troyen fuit la ville en flammes et fonde la lignée de Rome ?", ["Énée", "Hector", "Pâris", "Priam"], 0,
     "Virgile en fait le sujet de l'Énéide, à la gloire de la Rome d'Auguste."],
    ["Quelle magicienne aide Jason à conquérir la Toison d'or ?", ["Médée", "Circé", "Calypso", "Ariane"], 0,
     "Elle tuera ensuite ses propres enfants pour se venger de sa trahison, selon Euripide."],
    ["Quel poète grec charme les Enfers pour ramener son épouse ?", ["Orphée", "Amphion", "Linos", "Arion"], 0,
     "Il perd Eurydice pour s'être retourné avant d'avoir regagné la surface."],
    ["Qu'est-ce que la boîte de Pandore selon le mythe grec ?", ["Une jarre dont l'ouverture libère les maux sur l'humanité", "Un coffre contenant les dons des dieux", "Un cadeau des Titans", "Une urne funéraire divine"], 0,
     "Seule l'espérance reste au fond, détail dont le sens est discuté depuis l'Antiquité.", 3],
  ]),

  notion("mr2-mythologie-romaine", S, "La mythologie romaine",
    "Panthéon, fondation, cultes civiques : une religion d'abord politique.",
    "La religion romaine est avant tout un ensemble de rites publics, non une affaire de croyance individuelle.",
    2, [
    ["Quel dieu romain correspond au Zeus grec ?", ["Jupiter", "Mars", "Mercure", "Saturne"], 0,
     "Il forme avec Junon et Minerve la triade capitoline, au cœur du culte de l'État romain."],
    ["Quelle déesse romaine correspond à Aphrodite ?", ["Vénus", "Junon", "Diane", "Cérès"], 0,
     "La gens Julia, celle de César, prétendait descendre d'elle par Énée."],
    ["Qui sont les fondateurs mythiques de Rome ?", ["Romulus et Rémus", "Énée et Ascagne", "Numa et Tullus", "Évandre et Faunus"], 0,
     "Allaités par une louve, ils se querellent lors du tracé des murs ; Romulus tue Rémus."],
    ["Qu'est-ce que le culte des Lares dans la religion romaine ?", ["Un culte domestique rendu aux esprits protecteurs du foyer", "Un culte impérial", "Un culte funéraire public", "Un culte agraire saisonnier"], 0,
     "Chaque maison disposait d'un autel domestique où l'on rendait ces hommages quotidiens."],
    ["Que sont les Vestales ?", ["Des prêtresses chargées d'entretenir le feu sacré de Vesta", "Des devineresses officielles", "Des prêtresses de Junon", "Des servantes du temple de Jupiter"], 0,
     "Elles devaient rester vierges trente ans ; le manquement était puni de mort."],
    ["Qu'est-ce qu'un augure à Rome ?", ["Un prêtre interprétant les signes divins avant une décision publique", "Un prophète itinérant", "Un prêtre sacrificateur", "Un devin privé"], 0,
     "Aucune décision politique importante n'était prise sans consultation préalable."],
    ["Qu'est-ce que le culte impérial romain ?", ["La divinisation de l'empereur ou de son génie", "Le culte rendu par l'empereur", "Le culte des ancêtres impériaux seul", "La religion officielle de l'armée"], 0,
     "Le refus d'y participer explique en grande partie les persécutions contre les chrétiens."],
    ["Quelles fêtes romaines de décembre inversaient les rôles sociaux ?", ["Les Saturnales", "Les Lupercales", "Les Bacchanales", "Les Vestalia"], 0,
     "Maîtres et esclaves y échangeaient symboliquement leurs places, le temps de la fête."],
    ["Quel culte oriental s'est répandu dans l'armée romaine ?", ["Le mithraïsme", "Le culte d'Isis seul", "Le culte de Cybèle", "Le manichéisme"], 0,
     "Réservé aux hommes, il se pratiquait dans des sanctuaires souterrains appelés mithraea.", 3],
  ]),

  notion("mr2-mythologie-celte", S, "Les mythologies celtiques",
    "Druides, panthéon, cycles irlandais : ce qu'on en sait et par qui.",
    "Les Celtes n'écrivaient pas leurs traditions religieuses : nos sources sont extérieures ou tardives.",
    2, [
    ["Pourquoi la mythologie celtique continentale est-elle mal connue ?", ["Les druides interdisaient de mettre par écrit leur savoir", "Les textes ont été détruits", "Elle n'existait pas sous forme organisée", "Les Romains l'ont interdite dès la conquête"], 0,
     "César rapporte cette interdiction. L'essentiel de nos sources est romain ou médiéval irlandais."],
    ["Quel rôle jouaient les druides dans la société celtique ?", ["Prêtres, juges et dépositaires du savoir", "Chefs militaires", "Guérisseurs uniquement", "Conseillers des seuls rois"], 0,
     "Leur formation aurait duré jusqu'à vingt ans, entièrement par mémorisation orale."],
    ["Quel arbre était particulièrement vénéré par les druides selon Pline ?", ["Le chêne", "Le frêne", "Le hêtre", "L'if"], 0,
     "Le gui poussant sur le chêne était cueilli lors d'un rite décrit par Pline l'Ancien."],
    ["Quel recueil médiéval irlandais raconte les invasions mythiques de l'Irlande ?", ["Le Livre des conquêtes", "Le Livre de Kells", "Les Annales d'Ulster", "Le Cycle de Finn seul"], 0,
     "Il présente une succession de peuples mythiques précédant les Gaëls."],
    ["Quel héros irlandais est le personnage central du cycle d'Ulster ?", ["Cúchulainn", "Finn mac Cumaill", "Conaire Mor", "Lug"], 0,
     "La Razzia des vaches de Cooley en est le récit principal."],
    ["Quel dieu celtique est associé à la lumière et à de multiples talents ?", ["Lug", "Dagda", "Ogme", "Manannan"], 0,
     "Son nom se retrouve dans de nombreux toponymes, dont Lyon, l'antique Lugdunum."],
    ["Quelle fête celtique marque le début de la saison sombre ?", ["Samain", "Beltaine", "Imbolc", "Lugnasad"], 0,
     "Beltaine ouvre la saison claire. Samain a laissé sa trace dans Halloween."],
    ["Qu'est-ce que l'Autre Monde dans les traditions celtiques ?", ["Un monde parallèle accessible en certains lieux et à certaines dates", "Le royaume des morts uniquement", "Un paradis céleste", "Le monde souterrain des dieux"], 0,
     "Il est souvent situé sous les collines, sous les eaux ou sur des îles occidentales."],
    ["Quel personnage arthurien est présenté comme un enchanteur d'origine celtique ?", ["Merlin", "Lancelot", "Perceval", "Gauvain"], 0,
     "Il combine des traditions galloises anciennes et des inventions médiévales."],
    ["Que sait-on avec certitude des sacrifices humains celtiques ?", ["Des indices archéologiques existent, mais les récits romains sont sujets à caution", "Ils étaient systématiques", "Ils n'ont jamais existé", "Ils étaient réservés aux prisonniers de guerre"], 0,
     "Les sources antiques servaient aussi à justifier la conquête en présentant les Gaulois comme barbares.", 3],
  ]),

  notion("mr2-mythologies-asiatiques", S, "Mythologies d'Asie",
    "Chine, Japon, Inde : récits de création et figures majeures.",
    "En Chine comme au Japon, mythologie et légitimité politique sont étroitement liées.",
    2, [
    ["Quel personnage mythique chinois sépare le ciel et la terre ?", ["Pangu", "Fuxi", "Nüwa", "Huangdi"], 0,
     "Son corps, à sa mort, aurait formé les éléments du monde."],
    ["Quelle divinité chinoise crée les humains avec de l'argile jaune ?", ["Nüwa", "Pangu", "Xiwangmu", "Shennong"], 0,
     "Elle répare aussi le ciel après une catastrophe cosmique, selon la tradition."],
    ["Quelle déesse est l'ancêtre mythique de la famille impériale japonaise ?", ["Amaterasu", "Izanami", "Inari", "Benzaiten"], 0,
     "Déesse du soleil, elle légitime la dynastie impériale, ce qui fut réaffirmé jusqu'en 1946."],
    ["Quel couple divin japonais crée l'archipel selon le mythe ?", ["Izanagi et Izanami", "Amaterasu et Susanoo", "Ninigi et Konohana", "Ebisu et Daikoku"], 0,
     "Les gouttes tombées de leur lance auraient formé les premières îles."],
    ["Quel roi des singes est le héros d'un roman chinois célèbre ?", ["Sun Wukong", "Zhu Bajie", "Nezha", "Erlang Shen"], 0,
     "La Pérégrination vers l'Ouest, du XVIe siècle, l'a rendu populaire dans toute l'Asie."],
    ["Que représente le dragon dans la culture chinoise ?", ["Une figure bénéfique associée à l'eau et au pouvoir impérial", "Un monstre destructeur", "Un esprit des montagnes", "Un symbole funéraire"], 0,
     "Il s'oppose en cela au dragon européen, presque toujours malfaisant."],
    ["Quel texte hindou raconte les exploits de Rama ?", ["Le Ramayana", "Le Mahabharata", "Les Puranas", "Les Upanishads"], 0,
     "Il est encore joué chaque année dans de nombreux villages d'Inde et d'Asie du Sud-Est."],
    ["Quel dieu hindou à tête d'éléphant écarte les obstacles ?", ["Ganesh", "Hanuman", "Kartikeya", "Indra"], 0,
     "On l'invoque au début de toute entreprise nouvelle."],
    ["Quel dieu singe aide Rama dans le Ramayana ?", ["Hanuman", "Ganesh", "Garuda", "Nandi"], 0,
     "Il est vénéré pour sa force et sa dévotion sans faille."],
    ["Qu'est-ce qu'un avatar dans l'hindouisme ?", ["Une descente d'une divinité sous une forme terrestre", "Une réincarnation humaine ordinaire", "Une statue de culte", "Un esprit protecteur"], 0,
     "Vishnou en compte traditionnellement dix, dont Rama et Krishna.", 3],
  ]),

  notion("mr2-mythologies-ameriques", S, "Mythologies des Amériques",
    "Mésoamérique, Andes, peuples d'Amérique du Nord.",
    "La mythologie maya ne nous est parvenue que par une poignée de sources écrites : les autodafés coloniaux ont fait le reste.",
    2, [
    ["Quel texte maya raconte la création du monde ?", ["Le Popol Vuh", "Le Codex de Dresde", "Les Livres du Chilam Balam", "Le Codex Borgia"], 0,
     "Transcrit en alphabet latin au XVIe siècle à partir d'une tradition antérieure."],
    ["Quel dieu mésoaméricain est représenté en serpent à plumes ?", ["Quetzalcóatl", "Tlaloc", "Huitzilopochtli", "Tezcatlipoca"], 0,
     "Appelé Kukulkan chez les Mayas, il est associé au vent, au savoir et à la civilisation."],
    ["Quel dieu aztèque est celui de la pluie ?", ["Tlaloc", "Quetzalcóatl", "Xipe Totec", "Mictlantecuhtli"], 0,
     "Son temple partageait le sommet du Templo Mayor avec celui de Huitzilopochtli."],
    ["Quel dieu tutélaire des Aztèques est associé au soleil et à la guerre ?", ["Huitzilopochtli", "Tlaloc", "Quetzalcóatl", "Coatlicue"], 0,
     "C'est lui qui aurait guidé le peuple mexica jusqu'au site de Tenochtitlan."],
    ["Quel signe devait indiquer aux Aztèques le lieu de fondation de leur capitale ?", ["Un aigle sur un cactus dévorant un serpent", "Une source jaillissant du rocher", "Un jaguar endormi", "Un arbre foudroyé"], 0,
     "Le motif figure aujourd'hui au centre du drapeau mexicain."],
    ["Quel dieu créateur andin est vénéré avant et pendant l'Empire inca ?", ["Viracocha", "Inti", "Pachamama", "Illapa"], 0,
     "Inti, le soleil, était le dieu dynastique des Incas, dont l'empereur se disait le fils."],
    ["Qui est Pachamama dans les Andes ?", ["La divinité de la terre nourricière", "La déesse de la lune", "L'esprit des montagnes", "La divinité des eaux"], 0,
     "Son culte reste vivant, souvent mêlé à des pratiques catholiques."],
    ["Qu'est-ce qu'un totem chez certains peuples d'Amérique du Nord ?", ["Un emblème animal lié à un clan et à ses récits", "Une idole religieuse", "Un objet de sorcellerie", "Un poteau funéraire"], 0,
     "Les mâts sculptés de la côte nord-ouest racontent des lignées et des droits, plus qu'ils ne servent au culte."],
    ["Quelle figure revient dans de nombreux récits amérindiens sous les traits d'un farceur ?", ["Le trickster, souvent coyote ou corbeau", "Le chaman ancestral", "Le grand esprit", "L'homme-médecine"], 0,
     "Il transgresse les règles, crée et détruit, dans des récits souvent comiques et instructifs."],
    ["Qu'est-ce qu'une quête de vision dans certaines traditions des Plaines ?", ["Une retraite solitaire visant à recevoir une révélation personnelle", "Un rite de guérison collectif", "Un pèlerinage saisonnier", "Une danse rituelle de groupe"], 0,
     "Jeûne, isolement et privation de sommeil en constituent souvent le cadre.", 3],
  ]),

  notion("mr2-bible-textes", S, "La Bible et ses récits",
    "Structure, personnages, épisodes fondateurs.",
    "La Bible est une bibliothèque : des dizaines de livres écrits sur près d'un millénaire.",
    2, [
    ["Quel est le premier livre de la Bible ?", ["La Genèse", "l'Exode", "Le Lévitique", "Les Nombres"], 0,
     "Il contient les récits de création, du déluge et des patriarches."],
    ["Que raconte le livre de l'Exode ?", ["La sortie d'Égypte et le don de la Loi", "La création du monde", "La conquête de Canaan", "L'exil à Babylone"], 0,
     "Moïse y reçoit les Dix Commandements sur le mont Sinaï."],
    ["Combien de commandements Moïse reçoit-il selon la tradition ?", ["Dix", "Sept", "Douze", "Vingt"], 0,
     "Leur numérotation varie légèrement selon les traditions juive, catholique et protestante."],
    ["Qui est le premier roi d'Israël selon la Bible ?", ["Saül", "David", "Salomon", "Samuel"], 0,
     "Oint par le prophète Samuel, il est ensuite écarté au profit de David."],
    ["Quel roi biblique est réputé pour sa sagesse et son jugement célèbre ?", ["Salomon", "David", "Ézéchias", "Josias"], 0,
     "Le jugement entre deux femmes revendiquant le même enfant est devenu proverbial."],
    ["Quel prophète biblique est avalé par un grand poisson ?", ["Jonas", "Élie", "Jérémie", "Ézéchiel"], 0,
     "Le récit sert à illustrer l'impossibilité de fuir une mission reçue."],
    ["Quel personnage biblique voit sa foi éprouvée par des malheurs successifs ?", ["Job", "Abraham", "Isaac", "Jacob"], 0,
     "Le livre qui porte son nom pose frontalement la question de la souffrance de l'innocent."],
    ["Quel livre biblique est un recueil de chants attribués à David ?", ["Les Psaumes", "Les Proverbes", "L'Ecclésiaste", "Le Cantique des cantiques"], 0,
     "Cent cinquante poèmes, employés dans la liturgie juive comme chrétienne."],
    ["Quel livre biblique est un poème d'amour entre deux amants ?", ["Le Cantique des cantiques", "Les Psaumes", "Le livre de Ruth", "Les Lamentations"], 0,
     "Son inclusion dans le canon a été justifiée par une lecture allégorique."],
    ["Quel est le dernier livre du Nouveau Testament ?", ["l'Apocalypse", "Les Actes des Apôtres", "l'Épître aux Hébreux", "l'Évangile de Jean"], 0,
     "Le mot signifie révélation, non catastrophe : ce sens est venu du contenu du texte.", 3],
  ]),

  notion("mr2-christianisme-histoire", S, "Le christianisme dans l'histoire",
    "Monachisme, papauté, missions, ordres religieux.",
    "Le monachisme occidental s'organise autour de la règle de saint Benoît.",
    2, [
    ["Quelle règle organise le monachisme occidental à partir du VIe siècle ?", ["La règle de saint Benoît", "La règle de saint Augustin", "La règle de saint Basile", "La règle de saint Colomban"], 0,
     "Prière et travail y sont équilibrés, avec une insistance sur la stabilité dans un même monastère."],
    ["Quel ordre monastique réforme le monachisme au Xe siècle depuis la Bourgogne ?", ["Cluny", "Cîteaux", "La Grande Chartreuse", "Prémontré"], 0,
     "Son abbatiale fut la plus grande église de la chrétienté avant la reconstruction de Saint-Pierre."],
    ["Quel ordre naît en 1098 en réaction au faste clunisien ?", ["Cîteaux", "Cluny", "Les Prémontrés", "Les Camaldules"], 0,
     "Bernard de Clairvaux en devient la figure dominante au XIIe siècle."],
    ["Quel ordre mendiant est fondé par un marchand italien au XIIIe siècle ?", ["Les Franciscains", "Les Dominicains", "Les Carmes", "Les Augustins"], 0,
     "François d'Assise fait de la pauvreté volontaire le cœur de sa règle."],
    ["Quel ordre fondé au XIIIe siècle est voué à la prédication ?", ["Les Dominicains", "Les Franciscains", "Les Bénédictins", "Les Cisterciens"], 0,
     "Ils ont joué un rôle important dans les universités médiévales et dans l'Inquisition."],
    ["Qu'est-ce que la querelle des Investitures ?", ["Un conflit entre papauté et empereur sur la nomination des évêques", "Une dispute théologique", "Un conflit sur les biens d'Église", "Une querelle entre ordres monastiques"], 0,
     "Le concordat de Worms de 1122 en marque le compromis final."],
    ["Qu'est-ce que le grand schisme d'Occident ?", ["Une période de 1378 à 1417 avec plusieurs papes concurrents", "La rupture avec Constantinople", "La naissance du protestantisme", "La séparation de l'Église anglicane"], 0,
     "Le concile de Constance y met fin en imposant l'élection d'un pape unique."],
    ["Qu'est-ce que l'Inquisition médiévale ?", ["Une procédure judiciaire ecclésiastique contre l'hérésie", "Une police religieuse permanente", "Un tribunal d'État", "Une institution espagnole uniquement"], 0,
     "L'Inquisition espagnole, créée en 1478, relevait de la Couronne et non directement du pape."],
    ["Quel ordre missionnaire s'implante massivement en Amérique et en Asie au XVIe siècle ?", ["Les Jésuites", "Les Bénédictins", "Les Chartreux", "Les Trappistes"], 0,
     "François Xavier atteint le Japon dès 1549."],
    ["Qu'est-ce que la théologie de la libération ?", ["Un courant latino-américain liant foi chrétienne et justice sociale", "Une théologie protestante libérale", "Un mouvement œcuménique", "Une théologie de la décolonisation africaine"], 0,
     "Née dans les années 1960, elle a été critiquée par Rome pour ses emprunts au marxisme.", 3],
  ]),

  notion("mr2-islam-histoire", S, "L'islam dans l'histoire",
    "Sciences, art, empires : mille ans de civilisation.",
    "L'âge d'or islamique a transmis et prolongé une grande part de l'héritage scientifique antique.",
    2, [
    ["Quelle institution de Bagdad favorise la traduction des savoirs antiques ?", ["La Maison de la sagesse", "La mosquée al-Azhar", "L'université de Cordoue", "La bibliothèque de Damas"], 0,
     "Textes grecs, persans et indiens y furent traduits en arabe à partir du IXe siècle."],
    ["Quel savant persan donne son nom à l'algorithme ?", ["Al-Khwarizmi", "Al-Biruni", "Ibn Sina", "Al-Kindi"], 0,
     "Son traité sur le calcul indien a introduit en Occident les chiffres dits arabes."],
    ["Quel savant du XIe siècle pose les bases de l'optique moderne ?", ["Ibn al-Haytham", "Al-Razi", "Ibn Rushd", "Al-Farabi"], 0,
     "Il démontre que la vision résulte de la lumière entrant dans l'œil, non l'inverse."],
    ["Quelle institution du Caire est l'une des plus anciennes universités du monde ?", ["Al-Azhar", "La Zitouna", "La Qarawiyyin", "La Nizamiyya"], 0,
     "La Qarawiyyin de Fès, fondée en 859 par une femme, est souvent citée comme la plus ancienne."],
    ["Quelle dynastie règne sur l'Égypte et fonde Le Caire au Xe siècle ?", ["Les Fatimides", "Les Abbassides", "Les Ayyoubides", "Les Mamelouks"], 0,
     "Ils étaient chiites ismaéliens, à la différence de la majorité de la population."],
    ["Quel sultan reprend Jérusalem en 1187 et fonde une dynastie ?", ["Saladin", "Baybars", "Al-Kamil", "Nur ad-Din"], 0,
     "Il fonde la dynastie ayyoubide, d'origine kurde."],
    ["Quel régime militaire domine l'Égypte du XIIIe au XVIe siècle ?", ["Les Mamelouks", "Les Ayyoubides", "Les Fatimides", "Les Ottomans"], 0,
     "Anciens esclaves-soldats, ils arrêtent l'avancée mongole en 1260."],
    ["Quel empire musulman prend Constantinople en 1453 ?", ["l'Empire ottoman", "L'Empire seldjoukide", "L'Empire timouride", "Le sultanat mamelouk"], 0,
     "Il dominera ensuite le monde musulman méditerranéen pendant plus de quatre siècles."],
    ["Quel élément architectural caractérise la mosquée ?", ["Le mihrab indiquant la direction de La Mecque", "Le clocher", "L'autel central", "La nef à trois vaisseaux"], 0,
     "Le minbar sert à la prédication, le minaret à l'appel à la prière."],
    ["Pourquoi l'art islamique développe-t-il l'ornement géométrique et la calligraphie ?", ["Une réticence à la représentation figurée dans le contexte religieux", "Une interdiction absolue de toute image", "Un manque de tradition figurative", "Une préférence esthétique sans raison religieuse"], 0,
     "La peinture figurative existe abondamment dans les contextes profanes, notamment persan et moghol.", 3],
  ]),

  notion("mr2-bouddhisme-pratiques", S, "Le bouddhisme en pratique",
    "Méditation, monachisme, diffusion contemporaine.",
    "Le bouddhisme s'est adapté à chaque culture qu'il a rencontrée.",
    2, [
    ["Qu'est-ce que la méditation de pleine conscience ?", ["Une attention soutenue au moment présent sans jugement", "Une concentration sur un objet unique", "Une visualisation guidée", "Une répétition de formules"], 0,
     "Sa version laïcisée en Occident est issue de pratiques bouddhistes, dépouillées de leur cadre religieux."],
    ["Qu'est-ce que la sangha ?", ["La communauté des pratiquants, notamment monastique", "L'enseignement du Bouddha", "L'ensemble des textes sacrés", "Le lieu de méditation"], 0,
     "Elle forme avec le Bouddha et le dharma les trois joyaux du bouddhisme."],
    ["Qu'est-ce que le dharma dans le bouddhisme ?", ["L'enseignement du Bouddha et l'ordre des choses", "Le destin individuel", "Le cycle des renaissances", "La discipline monastique"], 0,
     "Le mot a des sens différents dans l'hindouisme, où il désigne aussi le devoir propre à chacun."],
    ["Qu'est-ce qu'un stupa ?", ["Un monument reliquaire de forme hémisphérique", "Un temple à étages", "Une statue monumentale", "Un monastère fortifié"], 0,
     "Il symbolise l'esprit éveillé et abrite parfois des reliques."],
    ["Qu'est-ce qu'un mantra ?", ["Une formule répétée servant de support à la méditation", "Un texte canonique", "Une prière collective", "Un chant liturgique"], 0,
     "Om mani padme hum est l'un des plus répandus dans le bouddhisme tibétain."],
    ["Qu'est-ce qu'un mandala ?", ["Une représentation symbolique de l'univers servant de support spirituel", "Un temple circulaire", "Un texte illustré", "Un objet de divination"], 0,
     "Les mandalas de sable tibétains sont détruits après leur achèvement, pour illustrer l'impermanence."],
    ["Qu'est-ce que le zen ?", ["Une école du bouddhisme mahayana centrée sur la méditation assise", "Une philosophie japonaise non religieuse", "Une école du bouddhisme theravada", "Une pratique de purification rituelle"], 0,
     "Chan en Chine, zen au Japon : le mot dérive du sanskrit dhyana, la méditation."],
    ["Qu'est-ce qu'un kōan ?", ["Une énigme paradoxale servant à déjouer la pensée discursive", "Un texte canonique zen", "Une posture de méditation", "Une règle monastique"], 0,
     "Le bruit d'une seule main en est l'exemple le plus connu en Occident."],
    ["Qui est le dalaï-lama ?", ["Une figure spirituelle majeure du bouddhisme tibétain", "Le chef de tous les bouddhistes", "Le fondateur du bouddhisme tibétain", "Le supérieur de tous les monastères"], 0,
     "Il dirige l'une des écoles du bouddhisme tibétain, non l'ensemble du bouddhisme."],
    ["Comment le bouddhisme s'est-il diffusé en Occident ?", ["Par les traductions savantes puis par les diasporas et les mouvements des années 1960", "Par les missions bouddhistes médiévales", "Par la colonisation", "Par les échanges commerciaux du XIXe siècle"], 0,
     "L'exil tibétain après 1959 a joué un rôle déterminant dans sa visibilité contemporaine.", 3],
  ]),

  notion("mr2-religions-france", S, "Les religions en France",
    "Histoire, statistiques, cadre juridique.",
    "La loi de 1905 ne s'applique pas de la même façon sur tout le territoire français.",
    2, [
    ["Où le régime concordataire s'applique-t-il encore en France ?", ["En Alsace et en Moselle", "En Corse", "Dans les outre-mer", "Dans les anciennes provinces catholiques"], 0,
     "Ces territoires étaient allemands en 1905 ; le Concordat de 1801 y est resté en vigueur."],
    ["Que prévoit l'article 2 de la loi de 1905 ?", ["La République ne reconnaît, ne salarie ni ne subventionne aucun culte", "La séparation des Églises et de l'État", "La liberté de conscience", "La neutralité des agents publics"], 0,
     "Des exceptions existent, notamment pour l'entretien des édifices antérieurs à 1905."],
    ["À qui appartiennent les églises françaises construites avant 1905 ?", ["Aux communes ou à l'État", "Au diocèse", "Au Vatican", "Aux associations cultuelles"], 0,
     "Elles sont mises gratuitement à disposition du culte, la commune assurant leur entretien."],
    ["Qu'est-ce qu'une association cultuelle en France ?", ["Une association ayant pour objet exclusif l'exercice d'un culte", "Une association religieuse caritative", "Une congrégation reconnue", "Une fondation religieuse"], 0,
     "Ce statut, défini par la loi de 1905, ouvre certains avantages fiscaux avec des contreparties."],
    ["Que prévoit la loi de 2004 sur les signes religieux à l'école ?", ["L'interdiction des signes religieux ostensibles dans les écoles publiques", "L'interdiction des signes religieux dans tout l'espace public", "L'interdiction de l'enseignement religieux", "L'interdiction des aumôneries"], 0,
     "Elle concerne les élèves des établissements publics du premier et du second degré."],
    ["Quel est le principe de neutralité applicable aux agents publics ?", ["Ils ne doivent manifester aucune conviction religieuse dans l'exercice de leurs fonctions", "Ils doivent être athées", "Ils ne peuvent pratiquer aucun culte", "Ils doivent déclarer leur religion"], 0,
     "L'obligation porte sur l'exercice des fonctions, non sur la vie privée."],
    ["Quelle religion est historiquement majoritaire en France ?", ["Le catholicisme", "Le protestantisme", "L'islam", "Le judaïsme"], 0,
     "La part de personnes se déclarant sans religion a fortement augmenté depuis les années 1980."],
    ["Quelle communauté protestante est historiquement implantée dans les Cévennes ?", ["Les huguenots réformés", "Les luthériens", "Les anabaptistes", "Les méthodistes"], 0,
     "La révocation de l'édit de Nantes y a provoqué la guerre des Camisards."],
    ["Quand les Juifs obtiennent-ils la pleine citoyenneté en France ?", ["En 1791, pendant la Révolution", "En 1789", "En 1848", "En 1808"], 0,
     "La France est le premier pays européen à leur accorder l'égalité des droits."],
    ["Qu'est-ce que l'Observatoire de la laïcité, devenu comité interministériel ?", ["Une instance d'analyse et de conseil sur l'application du principe de laïcité", "Un tribunal des cultes", "Un organe de contrôle des associations religieuses", "Une autorité de sanction"], 0,
     "Sa mission est consultative : il ne dispose d'aucun pouvoir de sanction.", 3],
  ]),

  notion("mr2-ethique-religions", S, "Religions et questions de société",
    "Bioéthique, environnement, égalité : ce que disent et débattent les traditions.",
    "Les positions religieuses ne sont pas homogènes : chaque tradition connaît des courants divergents.",
    2, [
    ["Qu'est-ce que la bioéthique ?", ["La réflexion sur les questions morales soulevées par les sciences du vivant", "Une branche de la biologie", "Le droit médical", "L'éthique environnementale"], 0,
     "En France, les lois de bioéthique sont révisées périodiquement après un débat public."],
    ["Quelle encyclique de 2015 traite de l'écologie ?", ["Laudato si'", "Rerum novarum", "Pacem in terris", "Humanae vitae"], 0,
     "Le pape François y lie crise écologique et justice sociale."],
    ["Quelle encyclique de 1891 fonde la doctrine sociale de l'Église catholique ?", ["Rerum novarum", "Quadragesimo anno", "Laudato si'", "Populorum progressio"], 0,
     "Léon XIII y prend position sur la condition ouvrière face au libéralisme et au socialisme."],
    ["Quelle question divise les traditions religieuses sur la fin de vie ?", ["L'admissibilité de l'euthanasie et du suicide assisté", "La définition de la mort clinique", "Le don d'organes", "Les soins palliatifs"], 0,
     "La plupart des traditions distinguent laisser mourir et provoquer la mort."],
    ["Quelle est la position dominante des grandes traditions sur le don d'organes ?", ["Il est généralement encouragé comme acte de solidarité", "Il est unanimement interdit", "Il n'est jamais évoqué", "Il est réservé aux proches"], 0,
     "Des débats subsistent sur les critères de constat du décès."],
    ["Qu'est-ce que le dialogue interreligieux ?", ["Des échanges organisés entre représentants de traditions différentes", "La fusion de plusieurs religions", "Une théologie comparée", "Un œcuménisme intrachrétien"], 0,
     "L'œcuménisme, plus étroit, concerne les rapports entre confessions chrétiennes."],
    ["Qu'est-ce que le concile Vatican II change dans le rapport aux autres religions ?", ["Il reconnaît des éléments de vérité dans les autres traditions", "Il condamne toute autre religion", "Il proclame l'unité des religions", "Il supprime la mission"], 0,
     "La déclaration Nostra aetate, en 1965, marque notamment un tournant dans le rapport au judaïsme."],
    ["Quelle question traverse aujourd'hui plusieurs traditions religieuses ?", ["La place des femmes dans les fonctions religieuses", "L'existence de Dieu", "La validité des textes sacrés", "L'usage de la langue liturgique"], 0,
     "Les positions vont de l'ordination pleine et entière au refus de tout ministère féminin."],
    ["Qu'est-ce que le fondamentalisme religieux ?", ["Une lecture littérale des textes érigée en norme exclusive", "Une pratique religieuse rigoureuse", "Un conservatisme social", "Un retour aux origines historiques d'une religion"], 0,
     "Le terme est né aux États-Unis au début du XXe siècle dans un contexte protestant."],
    ["Qu'est-ce qu'une dérive sectaire selon le droit français ?", ["Une atteinte aux libertés et à la santé par une pression psychologique organisée", "L'appartenance à une religion minoritaire", "Une croyance non reconnue", "Un groupe religieux non déclaré"], 0,
     "Le droit français ne définit pas les sectes mais sanctionne les abus de faiblesse et les atteintes aux personnes.", 3],
  ]),

  notion("mr2-art-sacre", S, "L'art et le sacré",
    "Architecture, images, musique religieuse.",
    "L'orientation des églises vers l'est n'est pas un hasard architectural mais un choix symbolique.",
    2, [
    ["Pourquoi les églises chrétiennes sont-elles traditionnellement orientées ?", ["Le chœur est tourné vers l'est, direction du soleil levant", "Vers Jérusalem", "Vers Rome", "Vers l'entrée principale du bourg"], 0,
     "Le mot orientation vient précisément de cette pratique."],
    ["Qu'est-ce qu'une iconostase ?", ["Une cloison couverte d'icônes séparant le sanctuaire de la nef", "Un support de statues", "Un retable orthodoxe", "Un pupitre de lecture"], 0,
     "Elle caractérise les églises de tradition byzantine."],
    ["Qu'est-ce qu'une icône dans la tradition orthodoxe ?", ["Une image sacrée peinte selon des règles précises", "Une statue de dévotion", "Une fresque d'église", "Une enluminure liturgique"], 0,
     "Elle n'est pas considérée comme une œuvre d'art personnelle mais comme une fenêtre vers le divin."],
    ["Qu'est-ce qu'un minaret ?", ["Une tour depuis laquelle est lancé l'appel à la prière", "Un clocher de mosquée", "Un poste de guet religieux", "Une tour funéraire"], 0,
     "Sa forme varie considérablement selon les régions et les époques."],
    ["Qu'est-ce qu'une synagogue contient obligatoirement ?", ["Une arche abritant les rouleaux de la Torah", "Un autel de sacrifice", "Une chaire surélevée", "Un baptistère"], 0,
     "L'orientation se fait vers Jérusalem, comme la prière."],
    ["Qu'est-ce que la calligraphie arabe dans l'art religieux islamique ?", ["Un art majeur, support privilégié du texte coranique", "Un ornement secondaire", "Une pratique réservée aux manuscrits", "Une technique décorative profane"], 0,
     "Elle a donné naissance à de nombreux styles, du coufique anguleux au naskhi cursif."],
    ["Qu'est-ce qu'un chant liturgique ?", ["Un chant intégré au déroulement d'un office religieux", "Un chant religieux populaire", "Un cantique de dévotion privée", "Un chant de pèlerinage"], 0,
     "Sa fonction rituelle le distingue du chant religieux de concert."],
    ["Qu'est-ce qu'un requiem ?", ["Une messe pour les défunts, souvent mise en musique", "Un chant de louange", "Une prière du soir", "Un office de la semaine sainte"], 0,
     "Ceux de Mozart, Verdi, Fauré et Brahms comptent parmi les plus joués."],
    ["Qu'est-ce qu'un oratorio ?", ["Une œuvre vocale religieuse sans mise en scène", "Un opéra sacré joué", "Une cantate profane", "Une messe polyphonique"], 0,
     "Le Messie de Haendel en est l'exemple le plus célèbre."],
    ["Qu'est-ce qu'un ex-voto ?", ["Un objet offert en remerciement d'un vœu exaucé", "Une offrande sacrificielle", "Un objet de culte domestique", "Un reliquaire portatif"], 0,
     "Plaques, tableaux naïfs ou maquettes de bateaux tapissent certaines chapelles de pèlerinage.", 3],
  ]),

  notion("mr2-superstitions", S, "Croyances populaires et superstitions",
    "Origines, transmission, persistance de pratiques hors des religions instituées.",
    "Beaucoup de superstitions ont une origine pratique ou religieuse oubliée.",
    2, [
    ["D'où vient la crainte du chiffre treize à table ?", ["Du souvenir de la Cène et de ses treize convives", "D'une superstition romaine", "D'un décompte des mois lunaires", "D'une légende nordique"], 0,
     "Une tradition nordique évoque aussi un banquet de douze dieux troublé par un treizième."],
    ["D'où vient la superstition du miroir brisé ?", ["De la croyance antique que le reflet contenait une part de l'âme", "D'une interdiction religieuse", "Du coût élevé des miroirs", "D'un présage médiéval de guerre"], 0,
     "Les sept ans de malheur renverraient à une croyance romaine sur le renouvellement du corps."],
    ["Pourquoi touche-t-on du bois pour conjurer le sort ?", ["Probablement d'anciennes croyances liées aux esprits des arbres", "D'un rite chrétien de la croix uniquement", "D'une pratique de charpentier", "D'une coutume germanique de serment"], 0,
     "Les explications divergent ; l'origine précise n'est pas établie."],
    ["Que symbolise traditionnellement le trèfle à quatre feuilles ?", ["La chance, en raison de sa rareté", "La protection contre les maladies", "La prospérité agricole", "La fidélité en amour"], 0,
     "Sa fréquence naturelle est estimée à environ un sur dix mille."],
    ["Pourquoi le chat noir est-il associé au malheur en Europe ?", ["À cause de son assimilation médiévale à la sorcellerie", "D'une superstition égyptienne", "D'un présage antique de peste", "D'une légende scandinave"], 0,
     "Dans d'autres cultures, notamment au Japon, il est au contraire de bon augure."],
    ["Qu'est-ce qu'un porte-bonheur ?", ["Un objet censé attirer la chance ou écarter le malheur", "Une amulette religieuse", "Un talisman magique actif", "Un objet béni"], 0,
     "L'amulette protège, le talisman est censé agir : les distinctions varient selon les auteurs."],
    ["Qu'est-ce que l'astrologie ?", ["Une pratique attribuant une influence aux astres sur les destinées", "L'étude scientifique des astres", "Une branche ancienne de l'astronomie encore valide", "Un calendrier religieux"], 0,
     "Ses prédictions n'ont jamais résisté aux tests statistiques contrôlés."],
    ["Quelle différence sépare astronomie et astrologie ?", ["L'astronomie est une science, l'astrologie une croyance", "L'astrologie est plus ancienne uniquement", "L'astronomie étudie les planètes, l'astrologie les étoiles", "Elles utilisent les mêmes méthodes"], 0,
     "Elles ont été longtemps confondues : Kepler tirait une partie de ses revenus d'horoscopes."],
    ["Qu'est-ce que l'effet Barnum ?", ["La tendance à reconnaître une description vague comme personnellement exacte", "Un effet de mémoire sélective", "Un biais de confirmation", "Une suggestion collective"], 0,
     "Il explique une grande part du succès des horoscopes et des tests de personnalité douteux."],
    ["Pourquoi de nombreux immeubles américains n'ont-ils pas de treizième étage ?", ["Par superstition commerciale", "Par une règle d'urbanisme", "Pour des raisons de sécurité incendie", "Par une tradition architecturale"], 0,
     "L'étage existe physiquement : seule sa numérotation est escamotée.", 3],
  ]),

  notion("mr2-athées-libres-penseurs", S, "Incroyance et libre pensée",
    "Histoire d'une position minoritaire devenue courante.",
    "L'athéisme explicite est resté longtemps impensable ou dangereux à exprimer publiquement.",
    2, [
    ["Qu'est-ce que la libre pensée ?", ["Un courant revendiquant l'autonomie de la raison face aux dogmes", "Une doctrine athée organisée", "Un mouvement anticlérical politique", "Une philosophie sceptique antique"], 0,
     "Elle s'est structurée en associations au XIXe siècle, notamment en France."],
    ["Quel philosophe grec antique fonde une école matérialiste ?", ["Épicure", "Platon", "Aristote", "Zénon"], 0,
     "Sa physique atomiste ne nie pas les dieux mais leur refuse toute intervention dans le monde."],
    ["Quel poète latin expose la philosophie épicurienne en vers ?", ["Lucrèce", "Virgile", "Horace", "Ovide"], 0,
     "De la nature des choses fut redécouvert en 1417 et influença profondément la pensée moderne."],
    ["Quel philosophe du XVIIe siècle est excommunié pour ses idées sur Dieu et la nature ?", ["Spinoza", "Descartes", "Leibniz", "Pascal"], 0,
     "Son identification de Dieu et de la nature lui valut d'être longtemps tenu pour athée."],
    ["Quel curé français laisse à sa mort un testament athée au XVIIIe siècle ?", ["Jean Meslier", "Étienne Dolet", "Abbé Prévost", "Abbé Raynal"], 0,
     "Découvert après sa mort en 1729, son texte circula clandestinement, notamment par Voltaire."],
    ["Quel philosophe allemand du XIXe siècle voit dans Dieu une projection humaine ?", ["Ludwig Feuerbach", "Friedrich Nietzsche", "Karl Marx", "Arthur Schopenhauer"], 0,
     "L'homme aurait créé Dieu à son image, en projetant hors de lui ses propres qualités idéalisées."],
    ["Quelle est la différence entre athéisme et agnosticisme ?", ["L'athéisme porte sur la croyance, l'agnosticisme sur la connaissance", "L'agnosticisme est un athéisme modéré", "L'athéisme nie toute spiritualité", "L'agnosticisme suppose une foi incertaine"], 0,
     "On peut être athée et agnostique : ne pas croire tout en jugeant la question indécidable."],
    ["Qu'est-ce que le scepticisme scientifique ?", ["Une démarche exigeant des preuves proportionnées aux affirmations", "Un doute systématique sur la science", "Un refus de toute croyance", "Un relativisme des connaissances"], 0,
     "Il s'applique aussi bien aux allégations paranormales qu'aux résultats scientifiques mal établis."],
    ["Que garantit la liberté de conscience aux non-croyants ?", ["Le droit de ne pas croire et de ne pas subir de contrainte religieuse", "Un droit à la critique des religions sans limite", "Une exemption d'obligations civiles", "Une reconnaissance officielle de l'athéisme"], 0,
     "Elle protège symétriquement les croyants et les non-croyants."],
    ["Quelle évolution les enquêtes montrent-elles en Europe occidentale depuis 1970 ?", ["Une hausse continue des personnes sans affiliation religieuse", "Un retour massif à la pratique", "Une stabilité des appartenances", "Une progression uniforme de toutes les religions"], 0,
     "Le phénomène est très inégal selon les pays et coexiste avec des recompositions du croire.", 3],
  ]),

  notion("mr2-mythes-modernes", S, "Mythes et récits contemporains",
    "Comment des récits nouveaux occupent la fonction des anciens mythes.",
    "Les récits de super-héros reprennent des structures narratives très anciennes.",
    2, [
    ["Qu'est-ce que le monomythe décrit par Joseph Campbell ?", ["Une structure de récit héroïque commune à de nombreuses cultures", "Un mythe unique originel", "Un récit fondateur universel", "Une théorie de l'origine des religions"], 0,
     "Départ, initiation, retour : le schéma a été massivement repris par les scénaristes hollywoodiens."],
    ["Quel cinéaste a explicitement utilisé les travaux de Campbell ?", ["George Lucas", "Steven Spielberg", "Francis Ford Coppola", "Ridley Scott"], 0,
     "Il l'a revendiqué pour la construction du premier film de la saga Star Wars."],
    ["Qu'est-ce qu'une légende urbaine ?", ["Un récit contemporain présenté comme vrai et circulant de bouche à oreille", "Une histoire ancienne d'une ville", "Un fait divers célèbre", "Une rumeur politique"], 0,
     "Elles comportent souvent une morale implicite et un témoin toujours situé à un degré de distance."],
    ["Qu'est-ce que le complotisme ?", ["Une explication systématique des événements par un dessein caché", "Une critique des institutions", "Un scepticisme envers les médias", "Une théorie politique minoritaire"], 0,
     "Sa structure narrative est proche du récit mythique : rien n'y est laissé au hasard."],
    ["Qu'est-ce qu'une figure d'apocalypse dans la culture contemporaine ?", ["Un récit de fin du monde et de ce qui vient après", "Une prophétie religieuse", "Un scénario catastrophe réaliste", "Une critique écologique"], 0,
     "Le genre postapocalyptique en explore surtout les recommencements possibles."],
    ["Quel récit fondateur les nations modernes se donnent-elles souvent ?", ["Un mythe de fondation légitimant leur existence", "Une chronologie strictement historique", "Un texte constitutionnel", "Un récit religieux"], 0,
     "Les historiens en montrent la construction, parfois tardive et délibérée."],
    ["Qu'est-ce qu'un héros culturel ?", ["Une figure qui apporte un savoir ou un bien fondateur à l'humanité", "Un personnage populaire", "Un fondateur de religion", "Un personnage historique glorifié"], 0,
     "Prométhée en est l'exemple grec : il apporte le feu, donc la technique."],
    ["Qu'est-ce que la sacralisation d'objets profanes ?", ["L'attribution d'une valeur quasi sacrée à des objets ordinaires", "La bénédiction religieuse d'objets", "La conservation muséale", "La fétichisation commerciale"], 0,
     "Reliques sportives, manuscrits d'écrivains ou lieux de mémoire en font l'objet."],
    ["Qu'est-ce qu'un rite civil contemporain ?", ["Une cérémonie non religieuse marquant une étape de vie", "Une fête nationale", "Une commémoration officielle", "Un usage administratif"], 0,
     "Mariage civil, parrainage républicain ou funérailles laïques en sont des exemples."],
    ["Pourquoi les sciences sociales étudient-elles les mythes contemporains ?", ["Ils révèlent les valeurs et les angoisses d'une société", "Ils remplacent les religions", "Ils sont historiquement fondés", "Ils préparent les changements politiques"], 0,
     "Roland Barthes en a donné une analyse célèbre dans ses Mythologies, en 1957.", 3],
  ]),

  notion("mr2-eschatologie", S, "Fins dernières et au-delà",
    "Ce que les traditions disent de la mort et de ce qui suit.",
    "Les représentations de l'au-delà varient profondément d'une tradition à l'autre.",
    2, [
    ["Qu'est-ce que l'eschatologie ?", ["Le discours sur les fins dernières et le destin ultime", "L'étude des rites funéraires", "La théologie de la création", "La doctrine du salut individuel"], 0,
     "Elle peut être individuelle, sur le sort de chacun, ou collective, sur la fin du monde."],
    ["Qu'est-ce que le shéol dans la Bible hébraïque ancienne ?", ["Un séjour indistinct des morts, sans rétribution marquée", "Un paradis céleste", "Un lieu de châtiment", "Un état de sommeil temporaire"], 0,
     "L'idée d'une rétribution différenciée après la mort se développe tardivement dans le judaïsme."],
    ["Qu'est-ce que le purgatoire dans la doctrine catholique ?", ["Un état de purification avant l'accès au ciel", "Un lieu de châtiment éternel", "Une antichambre du jugement", "Un séjour des non-baptisés"], 0,
     "Sa formulation doctrinale se précise au Moyen Âge et fut un point de rupture avec la Réforme."],
    ["Qu'est-ce que la résurrection des morts dans les traditions abrahamiques ?", ["Le retour à la vie corporelle lors du jugement final", "La survie de l'âme seule", "La réincarnation dans un autre corps", "L'ascension immédiate au ciel"], 0,
     "Elle se distingue nettement de l'immortalité de l'âme d'origine grecque."],
    ["Qu'est-ce que le samsara dans les traditions indiennes ?", ["Le cycle des morts et des renaissances", "Le monde des morts", "L'état de libération", "La loi morale universelle"], 0,
     "En sortir, non y prospérer, constitue l'objectif spirituel."],
    ["Qu'est-ce que le jugement dernier dans l'iconographie chrétienne ?", ["La scène du tri final entre les élus et les damnés", "La pesée de l'âme individuelle", "La fin du monde matériel", "La seconde venue du Christ seule"], 0,
     "Il orne fréquemment les tympans des églises, à l'entrée du bâtiment."],
    ["Qu'est-ce que la pesée de l'âme dans l'Égypte antique ?", ["La comparaison du cœur du défunt à la plume de Maât", "Le jugement par un tribunal divin", "La sélection des momies", "L'évaluation des offrandes"], 0,
     "Un cœur trop lourd, chargé de fautes, était dévoré par la Grande Dévoreuse."],
    ["Qu'est-ce que le Valhalla dans la mythologie nordique ?", ["La demeure des guerriers morts au combat", "Le royaume des dieux", "Le séjour des morts ordinaires", "Le lieu du jugement"], 0,
     "Ceux qui meurent autrement rejoignent le Helheim, gouverné par la déesse Hel."],
    ["Qu'est-ce que le culte des ancêtres ?", ["Des pratiques rituelles maintenant un lien avec les défunts de la lignée", "Une croyance en la réincarnation familiale", "Une religion sans dieu", "Un rite funéraire unique"], 0,
     "Très répandu en Asie et en Afrique, il structure souvent l'organisation familiale et sociale."],
    ["Que révèlent les pratiques funéraires pour les archéologues ?", ["Des indices sur l'organisation sociale et les croyances d'une société", "L'espérance de vie uniquement", "La religion officielle d'un État", "Le niveau technique d'une civilisation"], 0,
     "La présence d'offrandes, la position du corps et la richesse des tombes sont particulièrement instructives.", 3],
  ]),

  notion("mr2-pelerinages", S, "Pèlerinages et lieux de dévotion",
    "Marcher vers un lieu saint : histoire et pratiques.",
    "Le pèlerinage combine presque toujours un déplacement physique et une transformation intérieure attendue.",
    2, [
    ["Combien de personnes accomplissent chaque année le hajj à La Mecque ?", ["Environ deux millions", "Environ cent mille", "Environ dix millions", "Environ cinq cent mille"], 0,
     "Le nombre est contingenté par quotas nationaux pour des raisons de sécurité."],
    ["Quel pèlerinage hindou rassemble des dizaines de millions de personnes ?", ["La Kumbh Mela", "La Ratha Yatra", "Le Thaipusam", "La Durga Puja"], 0,
     "Il se tient par rotation dans quatre villes, à des intervalles fixés par l'astrologie."],
    ["Quels chemins de pèlerinage médiévaux traversent la France vers l'Espagne ?", ["Les chemins de Saint-Jacques", "Les chemins de Rome", "Les voies romaines de Compostelle seules", "Les routes de Jérusalem"], 0,
     "Quatre grandes voies françaises convergeaient vers les Pyrénées."],
    ["Qu'est-ce que la coquille Saint-Jacques symbolise pour le pèlerin ?", ["La preuve d'être parvenu jusqu'à l'océan, devenue emblème du chemin", "Un ustensile de repas", "Un symbole de baptême", "Une monnaie de pèlerinage"], 0,
     "Elle servait aussi d'écuelle et d'objet de reconnaissance entre pèlerins."],
    ["Qu'est-ce que la Compostela ?", ["Un certificat délivré au pèlerin arrivé à Saint-Jacques", "Un passeport de pèlerinage", "Une médaille commémorative", "Un billet d'accès à la cathédrale"], 0,
     "Il faut avoir parcouru au moins cent kilomètres à pied ou deux cents à vélo pour l'obtenir."],
    ["Quel pèlerinage juif était prescrit trois fois par an dans l'Antiquité ?", ["La montée au Temple de Jérusalem", "La visite du mont Sinaï", "Le pèlerinage à Hébron", "Le voyage à Safed"], 0,
     "Pessah, Chavouot et Souccot étaient les trois fêtes de pèlerinage."],
    ["Qu'est-ce que le pardon en Bretagne ?", ["Un pèlerinage local avec procession en l'honneur d'un saint", "Une absolution collective", "Une fête patronale civile", "Un rite de réconciliation"], 0,
     "La grande Troménie de Locronan est l'un des plus connus, célébré tous les six ans."],
    ["Quel pèlerinage japonais fait le tour d'une île avec quatre-vingt-huit temples ?", ["Le pèlerinage de Shikoku", "Le chemin de Kumano", "Le circuit du mont Fuji", "La route de Nikko"], 0,
     "Environ mille deux cents kilomètres, traditionnellement parcourus à pied en un à deux mois."],
    ["Quelle fonction sociale les pèlerinages ont-ils historiquement remplie ?", ["Ils créaient des réseaux d'échange, d'hospitalité et de circulation", "Ils servaient uniquement à la dévotion", "Ils remplaçaient les foires commerciales", "Ils permettaient d'éviter l'impôt"], 0,
     "Hôpitaux, ponts et routes se sont développés le long des grands itinéraires."],
    ["Pourquoi certains pèlerinages connaissent-ils un regain contemporain ?", ["Des motivations spirituelles, sportives et personnelles se combinent", "Une réaffirmation religieuse générale", "Un effet purement touristique", "Une politique de valorisation patrimoniale"], 0,
     "Les enquêtes sur les chemins de Compostelle montrent une majorité de marcheurs aux motivations mixtes.", 3],
  ]),

  notion("mr2-conciles-doctrines", S, "Débats doctrinaux et conciles",
    "Comment se fixent les dogmes et pourquoi ils divisent.",
    "La plupart des grands schismes chrétiens sont nés de débats sur la nature du Christ.",
    2, [
    ["Que tranche le concile de Nicée en 325 ?", ["La nature divine du Christ contre l'arianisme", "Le canon des Écritures", "La date de Pâques uniquement", "Le célibat des prêtres"], 0,
     "Il fixe aussi une règle de calcul de la date de Pâques."],
    ["Que soutenait l'arianisme ?", ["Que le Fils est une créature, inférieure au Père", "Que le Christ n'était qu'un homme", "Que le Christ n'avait qu'une nature divine", "Que l'Esprit n'est pas divin"], 0,
     "Longtemps majoritaire chez les peuples germaniques convertis, il fut condamné dès 325."],
    ["Que tranche le concile de Chalcédoine en 451 ?", ["Le Christ a deux natures, divine et humaine, en une personne", "Le Christ n'a qu'une nature", "La divinité de l'Esprit saint", "L'autorité du pape"], 0,
     "Plusieurs Églises orientales n'ont pas accepté cette formulation et s'en sont séparées."],
    ["Qu'est-ce que la querelle du Filioque ?", ["Un désaccord sur la procession de l'Esprit saint dans le Credo", "Un débat sur la nature du Christ", "Une dispute sur les images", "Un conflit sur le calendrier"], 0,
     "L'ajout latin d'un mot au Credo est l'un des motifs doctrinaux du schisme de 1054."],
    ["Qu'est-ce que la querelle des indulgences ?", ["Un conflit sur la remise des peines contre des dons", "Un débat sur la confession", "Une dispute sur les reliques", "Une querelle sur le purgatoire seul"], 0,
     "Elle déclenche la Réforme en 1517, la vente servant alors à financer la basilique Saint-Pierre."],
    ["Qu'est-ce que la doctrine de la prédestination chez Calvin ?", ["Dieu a décidé de toute éternité du salut de chacun", "Le salut dépend des œuvres", "Le salut est offert à tous également", "Le libre arbitre détermine le salut"], 0,
     "Elle a nourri d'intenses débats, y compris à l'intérieur du protestantisme."],
    ["Qu'est-ce que le jansénisme ?", ["Un courant catholique rigoriste sur la grâce, condamné au XVIIe siècle", "Une branche du protestantisme français", "Une doctrine mystique espagnole", "Un mouvement gallican"], 0,
     "Port-Royal en fut le foyer ; Pascal et Racine y furent liés."],
    ["Qu'est-ce que le dogme de l'infaillibilité pontificale ?", ["Le pape ne peut errer quand il définit solennellement une doctrine de foi", "Le pape ne se trompe jamais", "Les décisions papales sont sans appel", "Le pape est au-dessus des conciles"], 0,
     "Proclamé en 1870 au concile Vatican I, il a été invoqué explicitement de façon très rare."],
    ["Que change Vatican II pour la liturgie catholique ?", ["Il autorise la célébration en langue vernaculaire", "Il supprime la messe latine", "Il abolit les sacrements", "Il transfère la liturgie aux laïcs"], 0,
     "Le latin reste autorisé ; c'est son caractère exclusif qui prend fin."],
    ["Qu'est-ce que l'œcuménisme ?", ["La recherche de l'unité entre confessions chrétiennes", "Le dialogue entre toutes les religions", "L'unification des rites", "La reconnaissance mutuelle des baptêmes seule"], 0,
     "Le Conseil œcuménique des Églises, fondé en 1948, en est la principale instance.", 3],
  ]),

  notion("mr2-religions-chiffres", S, "Les religions dans le monde aujourd'hui",
    "Répartition, dynamiques, mesures.",
    "Compter les fidèles d'une religion suppose des conventions discutables : appartenance déclarée, pratique ou héritage.",
    2, [
    ["Quelle est la religion la plus répandue dans le monde ?", ["Le christianisme", "L'islam", "L'hindouisme", "Le bouddhisme"], 0,
     "Environ un tiers de la population mondiale, toutes confessions chrétiennes confondues."],
    ["Quelle religion connaît la croissance démographique la plus rapide ?", ["L'islam", "Le christianisme", "l'hindouisme", "Le bouddhisme"], 0,
     "Cette croissance tient surtout à la structure par âge et à la fécondité des populations concernées."],
    ["Dans quel pays vit la plus grande population musulmane ?", ["l'Indonésie", "l'Arabie saoudite", "Le Pakistan", "l'Égypte"], 0,
     "Plus de deux cents millions de musulmans, loin devant les pays arabes."],
    ["Où se trouve aujourd'hui la majorité des chrétiens du monde ?", ["Hors d'Europe, notamment en Afrique et en Amérique", "En Europe", "En Amérique du Nord", "Au Proche-Orient"], 0,
     "Le centre de gravité du christianisme s'est déplacé vers le sud au cours du XXe siècle."],
    ["Quelle religion compte le plus de fidèles en Inde ?", ["l'hindouisme", "l'islam", "Le sikhisme", "Le bouddhisme"], 0,
     "L'Inde abrite néanmoins l'une des plus grandes populations musulmanes du monde."],
    ["Quel est le pays comptant la plus forte proportion de personnes sans religion ?", ["La Chine", "La Suède", "Le Japon", "La République tchèque"], 0,
     "Les enquêtes y sont délicates : appartenance déclarée et pratiques effectives divergent fortement."],
    ["Pourquoi les statistiques religieuses sont-elles difficiles à établir ?", ["Les critères d'appartenance et les méthodes varient d'un pays à l'autre", "Les données sont secrètes", "Les religions refusent de les fournir", "Les recensements sont trop rares"], 0,
     "La France interdit d'ailleurs les statistiques publiques sur l'appartenance religieuse."],
    ["Qu'est-ce que la sécularisation observée en Europe occidentale ?", ["Un recul de la pratique et de l'affiliation institutionnelles", "La disparition des croyances", "L'interdiction des cultes", "La baisse du nombre de lieux de culte seule"], 0,
     "Les croyances ne disparaissent pas mais se recomposent hors des cadres institutionnels."],
    ["Qu'est-ce que la liberté religieuse au sens des textes internationaux ?", ["Le droit de croire, de pratiquer, de changer de religion ou de n'en avoir aucune", "Le droit de pratiquer un culte reconnu", "La protection des minorités religieuses", "L'égalité des religions devant la loi"], 0,
     "Le droit de changer de religion reste contesté ou pénalisé dans plusieurs pays."],
    ["Que mesure un indice de restriction gouvernementale sur la religion ?", ["Le degré de contrainte légale et administrative exercée sur les pratiques religieuses", "La proportion de croyants", "Le budget public des cultes", "Le nombre de lieux de culte par habitant"], 0,
     "Ces indices, publiés par des centres de recherche, montrent une hausse des restrictions depuis vingt ans.", 3],
  ]),
];
