/**
 * Mythologie & Religions, troisième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Mythologie & Religions";

export const CG_MYTHOLOGIE_RELIGIONS_3: SeedSkill[] = [
  notion("mr3-mythologie-mesopotamienne", S, "Les mythes mésopotamiens",
    "Les plus anciens récits écrits de l'humanité.",
    "Les mythes mésopotamiens nous sont parvenus sur des tablettes d'argile.",
    2, [
    ["Quel dieu mésopotamien règne sur le ciel dans les panthéons anciens ?", ["An", "Enlil", "Enki", "Marduk"], 0,
     "Enlil, dieu du vent, exerce en pratique l'autorité effective dans de nombreux récits."],
    ["Quel dieu mésopotamien est associé à l'eau douce et à la sagesse ?", ["Enki", "Enlil", "An", "Nergal"], 0,
     "Il apparaît souvent comme protecteur de l'humanité face aux autres dieux."],
    ["Quel dieu devient la divinité principale de Babylone ?", ["Marduk", "Enlil", "Sîn", "Assur"], 0,
     "L'Enuma Elish raconte comment il accède à la royauté divine après avoir vaincu Tiamat."],
    ["Qu'est-ce que l'Enuma Elish ?", ["Un poème babylonien de la création du monde", "Un code de lois", "Une épopée héroïque", "Un rituel funéraire"], 0,
     "Le monde y est façonné à partir du corps de la déesse primordiale vaincue."],
    ["Qui est Ishtar dans la mythologie mésopotamienne ?", ["Une déesse de l'amour et de la guerre", "Une déesse de la terre", "Une déesse des morts", "Une déesse du foyer"], 0,
     "Sa descente aux Enfers est l'un des récits les plus complets qui nous soient parvenus."],
    ["Qui accompagne Gilgamesh dans ses aventures ?", ["Enkidu", "Utnapishtim", "Humbaba", "Ninsun"], 0,
     "Sa mort déclenche la quête d'immortalité du héros."],
    ["Qui est Utnapishtim dans l'Épopée de Gilgamesh ?", ["Le survivant du déluge ayant reçu l'immortalité", "Un roi rival", "Un dieu des Enfers", "Le père de Gilgamesh"], 0,
     "Son récit présente d'étroites parallèles avec celui de Noé."],
    ["Que cherche Gilgamesh après la mort de son ami ?", ["Le secret de l'immortalité", "La vengeance", "Un trésor", "La reconquête de son royaume"], 0,
     "Il échoue, et le poème s'achève sur l'acceptation de la condition mortelle."],
    ["Pourquoi les tablettes mésopotamiennes se sont-elles si bien conservées ?", ["L'argile cuite résiste au temps, au feu et à l'humidité", "Elles étaient enterrées volontairement", "Le climat désertique les a protégées seul", "Elles étaient gravées dans la pierre"], 0,
     "Paradoxalement, les incendies de palais ont cuit et donc préservé de nombreuses tablettes."],
    ["Qu'est-ce que la bibliothèque d'Assurbanipal ?", ["Une collection de tablettes retrouvée à Ninive", "Un temple-bibliothèque babylonien", "Une école de scribes", "Des archives royales sumériennes"], 0,
     "Elle a livré la version la plus complète de l'Épopée de Gilgamesh.", 3],
  ]),

  notion("mr3-cultes-antiques", S, "Cultes et mystères antiques",
    "Rites initiatiques et religions à mystères.",
    "Les religions à mystères promettaient un salut individuel, à la différence des cultes civiques.",
    2, [
    ["Qu'est-ce qu'une religion à mystères ?", ["Un culte à initiation promettant un sort meilleur après la mort", "Un culte secret interdit", "Une religion sans temple", "Un culte réservé aux prêtres"], 0,
     "Le secret sur les rites était strictement gardé, ce qui limite ce que nous en savons."],
    ["Quels mystères se célébraient à Éleusis, près d'Athènes ?", ["Les mystères de Déméter et Perséphone", "Les mystères d'Orphée", "Les mystères de Dionysos", "Les mystères d'Isis"], 0,
     "Ils ont été célébrés pendant près de deux mille ans."],
    ["Qu'est-ce que l'orphisme ?", ["Un courant religieux grec centré sur la purification et la survie de l'âme", "Un culte de la nature", "Un mouvement philosophique", "Une secte pythagoricienne"], 0,
     "Il attribuait à Orphée des textes révélés sur l'origine de l'âme."],
    ["Quelle déesse égyptienne connaît un culte à mystères dans le monde romain ?", ["Isis", "Bastet", "Hathor", "Sekhmet"], 0,
     "Son culte s'est répandu de l'Égypte à la Bretagne romaine."],
    ["Qu'est-ce que le mithraïsme ?", ["Un culte à mystères d'origine iranienne répandu dans l'armée romaine", "Un culte solaire officiel", "Une religion perse d'État", "Un culte impérial"], 0,
     "Ses sanctuaires souterrains, les mithraea, sont retrouvés dans tout l'Empire."],
    ["Qu'est-ce qu'un oracle dans le monde grec ?", ["Un lieu où une divinité rendait des réponses aux consultants", "Un devin itinérant", "Un prêtre interprète", "Un présage naturel"], 0,
     "Delphes fut le plus prestigieux, consulté par les cités comme par les particuliers."],
    ["Qui rendait les oracles à Delphes ?", ["La Pythie, prêtresse d'Apollon", "Un collège de prêtres", "Le grand prêtre du temple", "Un devin choisi par tirage"], 0,
     "Ses paroles étaient interprétées et mises en vers par les prêtres du sanctuaire."],
    ["Qu'est-ce qu'un sacrifice dans les religions antiques ?", ["Une offrande rituelle partagée entre les dieux et les hommes", "Une destruction totale de l'offrande", "Un don symbolique", "Une immolation humaine"], 0,
     "Dans le sacrifice grec, l'essentiel de la viande était consommé par les participants."],
    ["Qu'est-ce qu'un temple antique abritait principalement ?", ["La statue de la divinité", "L'assemblée des fidèles", "Les rites publics", "Les offrandes sacrificielles"], 0,
     "Les cérémonies se déroulaient devant le temple, autour de l'autel extérieur."],
    ["Pourquoi les cultes antiques ne demandaient-ils pas de croyance au sens moderne ?", ["Ils reposaient sur l'accomplissement correct des rites", "Ils ignoraient les dieux", "Ils étaient purement politiques", "Ils étaient réservés aux élites"], 0,
     "L'orthopraxie, la pratique correcte, y importait plus que l'orthodoxie.", 3],
  ]),

  notion("mr3-judaisme-histoire", S, "Le judaïsme dans l'histoire",
    "Exil, diaspora, émancipation.",
    "L'histoire juive s'est largement construite en diaspora depuis l'Antiquité.",
    2, [
    ["Que se passe-t-il en 70 de notre ère à Jérusalem ?", ["La destruction du Second Temple par les Romains", "La reconstruction du Temple", "L'exil à Babylone", "La révolte des Maccabées"], 0,
     "Le culte sacrificiel prend fin ; la synagogue et l'étude prennent le relais."],
    ["Qu'est-ce que la diaspora juive ?", ["La dispersion des communautés juives hors de la terre d'Israël", "Un exil temporaire", "Une migration organisée", "Une déportation unique"], 0,
     "Elle commence bien avant 70 et concerne le pourtour méditerranéen entier."],
    ["Qui sont les Ashkénazes ?", ["Les Juifs d'Europe centrale et orientale", "Les Juifs d'Espagne", "Les Juifs d'Afrique du Nord", "Les Juifs du Proche-Orient"], 0,
     "Le yiddish, langue germanique écrite en caractères hébreux, en est la langue vernaculaire historique."],
    ["Qui sont les Séfarades ?", ["Les Juifs originaires de la péninsule Ibérique et leurs descendants", "Les Juifs d'Europe centrale", "Les Juifs d'Éthiopie", "Les Juifs de Perse"], 0,
     "Le judéo-espagnol, ou ladino, en fut la langue après l'expulsion de 1492."],
    ["Que se passe-t-il pour les Juifs d'Espagne en 1492 ?", ["Ils sont expulsés du royaume", "Ils obtiennent la citoyenneté", "Ils sont convertis de force uniquement", "Ils sont regroupés en quartiers"], 0,
     "Beaucoup se réfugient dans l'Empire ottoman, qui les accueille."],
    ["Qu'est-ce qu'un ghetto au sens historique ?", ["Un quartier d'assignation forcée des Juifs dans certaines villes", "Un quartier pauvre", "Un quartier commerçant", "Une communauté volontaire"], 0,
     "Le mot vient du quartier vénitien où les Juifs furent assignés à partir de 1516."],
    ["Qu'est-ce que la Haskala ?", ["Un mouvement des Lumières juives prônant l'ouverture au monde moderne", "Un courant mystique", "Une école talmudique", "Un mouvement sioniste"], 0,
     "Elle se développe en Europe centrale à partir de la fin du XVIIIe siècle."],
    ["Qu'est-ce que le sionisme politique ?", ["Un mouvement visant la création d'un État juif", "Un courant religieux messianique", "Une organisation communautaire", "Un mouvement culturel"], 0,
     "Theodor Herzl en formule le programme en 1896 après l'affaire Dreyfus."],
    ["Qu'est-ce que la Shoah ?", ["L'extermination systématique des Juifs d'Europe par le régime nazi", "Une persécution religieuse", "Une déportation de masse", "Une politique d'exclusion"], 0,
     "Environ six millions de personnes assassinées entre 1941 et 1945.", 3],
  ]),

  notion("mr3-islam-pratiques", S, "L'islam en pratique",
    "Rites, calendrier, diversité des usages.",
    "Les pratiques islamiques varient considérablement selon les régions et les écoles.",
    2, [
    ["Combien de prières quotidiennes l'islam sunnite prescrit-il ?", ["Cinq", "Trois", "Sept", "Deux"], 0,
     "Le chiisme duodécimain permet d'en regrouper certaines, réduisant à trois moments de prière."],
    ["Qu'est-ce que la zakat ?", ["Une aumône obligatoire calculée sur le patrimoine", "Un don volontaire", "Un impôt religieux d'État", "Une offrande de fête"], 0,
     "Elle constitue l'un des cinq piliers et vise la redistribution vers les plus démunis."],
    ["Qu'est-ce que le ramadan ?", ["Un mois de jeûne du lever au coucher du soleil", "Une fête de trois jours", "Une période de pèlerinage", "Un mois de prière renforcée"], 0,
     "Enfants, malades, voyageurs et femmes enceintes en sont dispensés."],
    ["Qu'est-ce que la nuit du Destin ?", ["La nuit commémorant la première révélation du Coran", "La nuit de fin du ramadan", "La nuit du pèlerinage", "La nuit de l'hégire"], 0,
     "Elle est située dans les dix derniers jours du ramadan, sans date fixe certaine."],
    ["Qu'est-ce que la qibla ?", ["La direction de La Mecque vers laquelle on prie", "Le lieu de prière", "L'appel à la prière", "La niche du mihrab"], 0,
     "Elle fut d'abord orientée vers Jérusalem avant d'être changée."],
    ["Qu'est-ce que le halal ?", ["Ce qui est licite selon la loi islamique", "Un mode d'abattage seulement", "Un régime alimentaire", "Une certification commerciale"], 0,
     "Le terme s'applique bien au-delà de l'alimentation, à tous les actes de la vie."],
    ["Qu'est-ce qu'une madrasa ?", ["Un établissement d'enseignement religieux", "Une mosquée de quartier", "Un tribunal islamique", "Une confrérie soufie"], 0,
     "Elles se sont développées à partir du XIe siècle et ont formé les élites savantes."],
    ["Qu'est-ce qu'un imam dans l'islam sunnite ?", ["Celui qui dirige la prière, sans statut sacerdotal", "Un prêtre ordonné", "Un chef religieux national", "Un juriste religieux"], 0,
     "Dans le chiisme, le terme désigne au contraire des figures d'autorité spirituelle majeures."],
    ["Qu'est-ce qu'une fatwa ?", ["Un avis juridique donné par un savant qualifié", "Une condamnation à mort", "Une loi religieuse", "Un décret officiel"], 0,
     "Elle n'a de portée que pour celui qui la sollicite et l'accepte."],
    ["Combien d'écoles juridiques sunnites principales existe-t-il ?", ["Quatre", "Deux", "Six", "Une seule"], 0,
     "Hanafite, malikite, chaféite et hanbalite, aux méthodes et aux aires géographiques distinctes.", 3],
  ]),

  notion("mr3-christianisme-pratiques", S, "Le christianisme en pratique",
    "Sacrements, calendrier, liturgie.",
    "Les Églises chrétiennes ne reconnaissent pas le même nombre de sacrements.",
    2, [
    ["Combien de sacrements l'Église catholique reconnaît-elle ?", ["Sept", "Deux", "Trois", "Cinq"], 0,
     "Les Églises protestantes n'en reconnaissent généralement que deux : baptême et cène."],
    ["Qu'est-ce que l'eucharistie ?", ["Le sacrement du pain et du vin commémorant la Cène", "Une prière collective", "Un rite de bénédiction", "Une confession publique"], 0,
     "Sa compréhension théologique est l'un des points de divergence majeurs entre confessions."],
    ["Qu'est-ce que le baptême ?", ["Un rite d'entrée dans la communauté chrétienne par l'eau", "Une consécration religieuse", "Une bénédiction d'enfant", "Un rite de majorité"], 0,
     "Certaines Églises le réservent aux adultes conscients de leur engagement."],
    ["Qu'est-ce que le carême ?", ["Une période de quarante jours de préparation à Pâques", "Un jeûne de l'Avent", "Une retraite monastique", "Une semaine de pénitence"], 0,
     "Il commence le mercredi des Cendres et rappelle les quarante jours du Christ au désert."],
    ["Que commémore la Pentecôte ?", ["La descente de l'Esprit saint sur les apôtres", "La résurrection", "L'ascension du Christ", "La naissance de l'Église de Rome"], 0,
     "Elle est célébrée cinquante jours après Pâques."],
    ["Que commémore l'Ascension ?", ["L'élévation du Christ au ciel quarante jours après Pâques", "Sa résurrection", "Sa naissance", "Sa transfiguration"], 0,
     "Elle tombe toujours un jeudi dans le calendrier chrétien occidental."],
    ["Qu'est-ce que le Credo ?", ["Une profession de foi énonçant les articles essentiels", "Une prière quotidienne", "Un chant liturgique", "Un texte évangélique"], 0,
     "Le symbole de Nicée-Constantinople en est la version la plus universellement reçue."],
    ["Qu'est-ce qu'une liturgie ?", ["L'organisation réglée du culte public", "Une prière individuelle", "Un sermon", "Un chant sacré"], 0,
     "Le mot vient du grec désignant un service rendu au peuple."],
    ["Qu'est-ce qu'un ordre monastique contemplatif ?", ["Un ordre voué à la prière et au retrait du monde", "Un ordre enseignant", "Un ordre hospitalier", "Un ordre missionnaire"], 0,
     "Chartreux et carmes déchaux en sont des exemples ; les ordres actifs ont d'autres missions."],
    ["Qu'est-ce que le célibat ecclésiastique dans l'Église catholique latine ?", ["Une discipline imposée aux prêtres, non un dogme", "Un dogme intangible", "Une règle universelle chrétienne", "Une tradition sans base juridique"], 0,
     "Les Églises orientales catholiques et orthodoxes ordonnent des hommes mariés.", 3],
  ]),

  notion("mr3-orthodoxie", S, "Les Églises orthodoxes",
    "Organisation, liturgie, aire géographique.",
    "L'orthodoxie est composée d'Églises autocéphales, sans autorité centrale unique.",
    2, [
    ["Qu'est-ce qu'une Église autocéphale ?", ["Une Église indépendante dirigée par son propre primat", "Une Église nationale sans clergé", "Une Église sans hiérarchie", "Une Église rattachée à Constantinople"], 0,
     "Une quinzaine d'Églises orthodoxes autocéphales sont reconnues."],
    ["Quel patriarche détient une primauté d'honneur dans l'orthodoxie ?", ["Le patriarche œcuménique de Constantinople", "Le patriarche de Moscou", "Le patriarche d'Antioche", "Le patriarche de Jérusalem"], 0,
     "Cette primauté est d'honneur et non de juridiction, ce qui la distingue du rôle du pape."],
    ["Quelle Église orthodoxe compte le plus de fidèles ?", ["l'Église orthodoxe russe", "l'Église de Grèce", "l'Église de Roumanie", "l'Église de Serbie"], 0,
     "Plus de cent millions de fidèles selon les estimations."],
    ["Qu'est-ce que la Divine Liturgie orthodoxe ?", ["La célébration eucharistique principale", "Une prière du soir", "Un office monastique", "Une bénédiction dominicale"], 0,
     "La liturgie de saint Jean Chrysostome en est la forme la plus employée."],
    ["Que sont les portes royales d'une iconostase ?", ["Les portes centrales ouvertes seulement à certains moments de la liturgie", "L'entrée principale de l'église", "Les portes réservées à l'évêque", "Les portes latérales du sanctuaire"], 0,
     "Leur ouverture et leur fermeture rythment le déroulement de la Divine Liturgie."],
    ["Qu'est-ce que l'hésychasme ?", ["Une tradition mystique orthodoxe centrée sur la prière du cœur", "Un courant monastique réformateur", "Une école théologique", "Un mouvement de réforme liturgique"], 0,
     "La répétition de la prière de Jésus en constitue la pratique centrale."],
    ["Quel mont grec est le centre monastique de l'orthodoxie ?", ["Le mont Athos", "Le mont Sinaï", "Le mont Olympe", "Le mont Carmel"], 0,
     "Vingt monastères y forment une république monastique autonome."],
    ["Pourquoi certaines Églises orthodoxes fêtent-elles Noël le 7 janvier ?", ["Elles suivent le calendrier julien pour les fêtes fixes", "Elles célèbrent une autre date de naissance", "Elles suivent un calendrier lunaire", "Elles décalent la fête de treize jours volontairement"], 0,
     "L'écart entre calendriers julien et grégorien est aujourd'hui de treize jours."],
    ["Qu'est-ce que la théologie apophatique ?", ["Une approche définissant Dieu par ce qu'il n'est pas", "Une théologie négative du mal", "Une théologie sans dogme", "Une théologie mystique"], 0,
     "Elle est particulièrement développée dans la tradition orthodoxe."],
    ["Quelle crise récente divise le monde orthodoxe ?", ["La reconnaissance d'une Église autocéphale ukrainienne", "Une réforme liturgique", "Un désaccord sur le calendrier", "Une question doctrinale"], 0,
     "Le patriarcat de Moscou a rompu la communion avec Constantinople en 2018.", 3],
  ]),

  notion("mr3-protestantismes", S, "Les protestantismes",
    "Diversité des confessions issues de la Réforme.",
    "Le protestantisme n'est pas une Église mais une famille de confessions très diverses.",
    2, [
    ["Quels sont les grands principes de la Réforme ?", ["L'Écriture seule, la foi seule, la grâce seule", "L'autorité du concile", "La tradition et l'Écriture", "L'autorité épiscopale"], 0,
     "Ces formules latines résument l'opposition aux médiations institutionnelles."],
    ["Qu'est-ce que le luthéranisme ?", ["Une confession issue de Luther, majoritaire en Europe du Nord", "Un courant calviniste", "Une Église anglicane", "Un mouvement anabaptiste"], 0,
     "Il conserve une liturgie proche du rite catholique dans plusieurs de ses formes."],
    ["Qu'est-ce que le calvinisme ?", ["Une tradition réformée insistant sur la souveraineté de Dieu", "Un courant luthérien", "Une Église épiscopale", "Un mouvement piétiste"], 0,
     "Il s'est diffusé en Suisse, en France, aux Pays-Bas et en Écosse."],
    ["Qu'est-ce que l'anabaptisme ?", ["Un courant refusant le baptême des enfants au profit du baptême d'adultes", "Un courant réformé", "Une branche luthérienne", "Un mouvement anglican"], 0,
     "Violemment persécuté au XVIe siècle, il a donné naissance aux mennonites et aux amish."],
    ["Qu'est-ce que le méthodisme ?", ["Un mouvement né au XVIIIe siècle dans l'anglicanisme, centré sur la conversion personnelle", "Une branche luthérienne", "Un courant calviniste", "Un mouvement anabaptiste"], 0,
     "John Wesley en est le fondateur ; il s'est fortement développé aux États-Unis."],
    ["Qu'est-ce que le pentecôtisme ?", ["Un courant insistant sur les dons de l'Esprit et l'expérience personnelle", "Une branche méthodiste", "Un courant réformé", "Un mouvement baptiste"], 0,
     "Né au début du XXe siècle, il est aujourd'hui le courant chrétien à la croissance la plus rapide."],
    ["Qu'est-ce qu'une Église évangélique ?", ["Une Église protestante insistant sur la conversion et l'autorité de la Bible", "Une Église luthérienne", "Une Église orthodoxe réformée", "Une Église anglicane basse"], 0,
     "Le terme recouvre une grande diversité de sensibilités et d'organisations."],
    ["Comment un pasteur protestant est-il désigné ?", ["Il est appelé par une communauté après une formation théologique", "Il est ordonné par un évêque", "Il est nommé par une hiérarchie", "Il se déclare lui-même"], 0,
     "L'absence de sacerdoce distinct découle du principe du sacerdoce universel des croyants."],
    ["Qu'est-ce que le sacerdoce universel des croyants ?", ["L'idée que tout croyant a un accès direct à Dieu sans médiateur", "Le droit d'exercer le ministère", "L'égalité entre pasteurs", "L'élection des responsables"], 0,
     "Il fonde l'organisation généralement plus horizontale des Églises protestantes."],
    ["Quelle est la place des femmes dans le ministère protestant ?", ["Beaucoup d'Églises ordonnent des femmes pasteures depuis le XXe siècle", "Elles en sont exclues", "Elles n'exercent qu'un rôle laïc", "Cela dépend uniquement des pays"], 0,
     "En France, les Églises réformées ordonnent des femmes depuis les années 1960.", 3],
  ]),

  notion("mr3-hindouisme-pratiques", S, "L'hindouisme en pratique",
    "Rites, temples, pèlerinages.",
    "L'hindouisme n'a ni fondateur, ni credo unique, ni autorité centrale.",
    2, [
    ["Qu'est-ce qu'une puja ?", ["Un rite d'offrande et de vénération à une divinité", "Une prière collective", "Un sacrifice védique", "Un pèlerinage"], 0,
     "Elle peut se pratiquer au temple comme à la maison, devant un autel domestique."],
    ["Qu'est-ce qu'un darshan ?", ["Le fait de voir la divinité et d'en être vu", "Une méditation", "Une offrande de fleurs", "Une bénédiction du prêtre"], 0,
     "Cette vision réciproque est au cœur de l'expérience du temple hindou."],
    ["Qu'est-ce qu'un ashram ?", ["Un lieu de retraite spirituelle autour d'un maître", "Un temple hindou", "Un monastère bouddhiste", "Une école védique"], 0,
     "Le mot désigne aussi les quatre étapes idéales de la vie dans la tradition brahmanique."],
    ["Quels sont les quatre buts de la vie dans la tradition hindoue ?", ["Le devoir, la prospérité, le désir et la libération", "La naissance, la vie, la mort et la renaissance", "L'étude, le mariage, la retraite et le renoncement", "La prière, le travail, le don et l'ascèse"], 0,
     "Dharma, artha, kama et moksha, hiérarchisés mais tous légitimes."],
    ["Qu'est-ce que le système des varnas ?", ["Une division idéale de la société en quatre catégories", "Le système des castes actuel", "Une hiérarchie sacerdotale", "Une division régionale"], 0,
     "Il ne se confond pas avec les milliers de jatis, les groupes sociaux réels."],
    ["Qu'est-ce que le Gange dans l'hindouisme ?", ["Un fleuve sacré dont les eaux purifient", "Un simple fleuve nourricier", "Un lieu de pèlerinage secondaire", "Une frontière religieuse"], 0,
     "Sa pollution constitue un problème sanitaire et religieux majeur."],
    ["Qu'est-ce que la crémation dans les rites hindous ?", ["Le mode de traitement du corps permettant la libération de l'âme", "Un rite réservé aux brahmanes", "Une pratique récente", "Un rite optionnel"], 0,
     "Varanasi, sur le Gange, en est le lieu le plus recherché."],
    ["Qu'est-ce que la vache dans l'hindouisme ?", ["Un animal vénéré et protégé", "Un animal sacrifié rituellement", "Un animal impur", "Un animal sans statut particulier"], 0,
     "Son abattage est interdit dans plusieurs États indiens, ce qui a des effets politiques importants."],
    ["Qu'est-ce que le yoga dans son sens traditionnel ?", ["Une discipline spirituelle visant la libération, dont les postures ne sont qu'un aspect", "Une gymnastique", "Une technique de relaxation", "Une méditation assise"], 0,
     "Les Yoga-sutra de Patanjali en décrivent huit membres, dont la posture n'est que le troisième."],
    ["Pourquoi Diwali n'a-t-elle pas la même signification partout en Inde ?", ["Chaque région y rattache un récit et une divinité différents", "La date varie selon les États", "Elle est récente dans certaines régions", "Elle n'est pas célébrée partout"], 0,
     "Retour de Rama au nord, culte de Lakshmi à l'ouest, hommage à Kali au Bengale.", 3],
  ]),

  notion("mr3-taoisme-confucianisme", S, "Traditions chinoises",
    "Taoïsme, confucianisme, religion populaire.",
    "Un Chinois pouvait traditionnellement relever de plusieurs traditions à la fois.",
    2, [
    ["Quel texte fondateur est attribué à Laozi ?", ["Le Tao-tö king", "Les Entretiens", "Le Livre des mutations", "Le Zhuangzi"], 0,
     "Environ cinq mille caractères, d'une concision extrême et d'une interprétation ouverte."],
    ["Qu'est-ce que le wu wei dans le taoïsme ?", ["Le non-agir, l'action conforme au cours naturel des choses", "L'inaction totale", "Le renoncement au monde", "La méditation assise"], 0,
     "Il ne s'agit pas de passivité mais d'une action sans forçage."],
    ["Quel philosophe taoïste est connu pour ses paraboles ?", ["Zhuangzi", "Laozi", "Confucius", "Mozi"], 0,
     "Le rêve du papillon, où il ne sait plus s'il est homme ou papillon, en est la plus célèbre."],
    ["Quel recueil rassemble les propos de Confucius ?", ["Les Entretiens", "Le Livre des rites", "Le Livre des odes", "Le Mencius"], 0,
     "Compilé par ses disciples après sa mort, il a structuré la culture lettrée chinoise."],
    ["Qu'est-ce que le ren dans le confucianisme ?", ["La vertu d'humanité et de bienveillance envers autrui", "Le respect des rites", "La piété filiale", "La loyauté au souverain"], 0,
     "C'est la vertu cardinale, dont découlent les autres."],
    ["Qu'est-ce que la piété filiale ?", ["Le respect dû aux parents et aux ancêtres", "Une obligation religieuse", "Un devoir civique", "Une pratique funéraire"], 0,
     "Elle structure l'ensemble des relations sociales dans la pensée confucéenne."],
    ["Qu'est-ce que le Yi Jing ?", ["Le Livre des mutations, ouvrage divinatoire et philosophique", "Un traité de rites", "Un recueil de poèmes", "Un manuel militaire"], 0,
     "Ses soixante-quatre hexagrammes ont été commentés pendant plus de deux millénaires."],
    ["Qu'est-ce que le culte des ancêtres en Chine ?", ["Un ensemble de rites entretenant le lien avec les défunts de la lignée", "Une religion organisée", "Un culte impérial", "Une pratique taoïste"], 0,
     "Il traverse toutes les traditions chinoises et structure la vie familiale."],
    ["Qu'est-ce que le feng shui ?", ["Un art d'harmoniser l'implantation des constructions avec leur environnement", "Une pratique divinatoire", "Une médecine traditionnelle", "Une méditation"], 0,
     "Il concernait d'abord l'emplacement des tombes avant de s'étendre à l'habitat."],
    ["Comment les traditions chinoises coexistent-elles historiquement ?", ["Un individu pouvait relever simultanément de plusieurs d'entre elles", "Elles s'excluaient mutuellement", "Une seule était autorisée", "Elles étaient hiérarchisées par l'État"], 0,
     "L'expression des trois enseignements traduit cette coexistence du confucianisme, du taoïsme et du bouddhisme.", 3],
  ]),

  notion("mr3-textes-sacres-2", S, "Transmettre les textes sacrés",
    "Copie, traduction, diffusion.",
    "La transmission des textes sacrés a mobilisé des institutions entières pendant des siècles.",
    2, [
    ["Qu'est-ce qu'un scriptorium ?", ["Un atelier monastique de copie de manuscrits", "Une bibliothèque", "Une école de scribes antique", "Un atelier d'enluminure"], 0,
     "Le travail y était réparti entre copistes, rubricateurs et enlumineurs."],
    ["Combien de temps fallait-il pour copier une Bible à la main ?", ["Environ un an de travail pour un copiste", "Quelques semaines", "Une dizaine d'années", "Quelques jours"], 0,
     "Le coût en parchemin, tiré de centaines de peaux, s'y ajoutait."],
    ["Qu'est-ce qu'un codex ?", ["Un livre à pages reliées, remplaçant le rouleau", "Un manuscrit enluminé", "Un rouleau de parchemin", "Un recueil de lois"], 0,
     "Son adoption par les chrétiens dès les premiers siècles a facilité la consultation des textes."],
    ["Qu'est-ce qu'un palimpseste ?", ["Un parchemin gratté et réutilisé pour un nouveau texte", "Un manuscrit illustré", "Une copie tardive", "Un texte apocryphe"], 0,
     "Les techniques modernes permettent parfois de relire le texte effacé."],
    ["Qu'est-ce que la Vulgate ?", ["La traduction latine de la Bible par saint Jérôme", "La traduction grecque", "Une version syriaque", "Une paraphrase médiévale"], 0,
     "Elle a été la référence de l'Église latine pendant plus de mille ans."],
    ["Quelle traduction anglaise de la Bible a marqué la langue anglaise ?", ["La version du roi Jacques, en 1611", "La Bible de Wycliffe", "La Bible de Genève", "La Bible de Tyndale seule"], 0,
     "Elle a exercé sur l'anglais une influence comparable à celle de Luther sur l'allemand."],
    ["Pourquoi la traduction des textes sacrés a-t-elle souvent été interdite ?", ["Elle échappait au contrôle de l'institution religieuse", "Elle était techniquement impossible", "Les langues manquaient de vocabulaire", "Elle était jugée inutile"], 0,
     "Tyndale fut exécuté en 1536 pour avoir traduit la Bible en anglais."],
    ["Qu'est-ce que la récitation dans la transmission du Coran ?", ["Un mode de transmission orale codifié, transmis de maître à disciple", "Une lecture publique", "Une psalmodie libre", "Un chant liturgique"], 0,
     "Les chaînes de transmission des lectures sont documentées sur plus de mille ans."],
    ["Qu'est-ce qu'un hafiz ?", ["Une personne ayant mémorisé intégralement le Coran", "Un récitant professionnel", "Un savant en droit islamique", "Un copiste de manuscrits"], 0,
     "Des millions de personnes dans le monde ont accompli cette mémorisation."],
    ["Qu'est-ce que la numérisation des manuscrits religieux a changé ?", ["Elle a rendu accessibles des fonds jusque-là réservés à quelques chercheurs", "Elle a remplacé les originaux", "Elle a réduit leur valeur", "Elle a supprimé les copies papier"], 0,
     "La comparaison de témoins dispersés dans le monde est devenue possible en quelques clics.", 3],
  ]),

  notion("mr3-monachisme", S, "Le monachisme",
    "Formes, règles, fonctions sociales.",
    "Le retrait du monde existe dans presque toutes les grandes traditions religieuses.",
    2, [
    ["Qu'est-ce qu'un ermite ?", ["Un religieux vivant en solitaire", "Un moine cloîtré", "Un prêtre isolé", "Un pèlerin permanent"], 0,
     "Le cénobitisme désigne au contraire la vie monastique en communauté."],
    ["Qui sont les Pères du désert ?", ["Des ascètes chrétiens retirés dans les déserts d'Égypte aux premiers siècles", "Des théologiens orientaux", "Des évêques du concile de Nicée", "Des missionnaires nomades"], 0,
     "Antoine le Grand en est la figure la plus célèbre."],
    ["Qu'est-ce que la règle de saint Benoît prescrit ?", ["Un équilibre entre prière, travail et lecture", "Une ascèse extrême", "Un silence permanent", "Une itinérance perpétuelle"], 0,
     "La stabilité dans un même monastère en est un principe fondamental."],
    ["Qu'est-ce que la stabilité monastique ?", ["L'engagement à demeurer dans le même monastère à vie", "Une régularité de la prière", "Une constance dans la règle", "Une permanence des offices"], 0,
     "Elle distingue la tradition bénédictine des ordres mendiants itinérants."],
    ["Qu'est-ce qu'un moine bouddhiste theravada ?", ["Un religieux vivant de la mendicité et suivant des centaines de règles", "Un moine sédentaire propriétaire", "Un prêtre officiant", "Un ermite permanent"], 0,
     "Le vinaya, code monastique, comprend plus de deux cents règles."],
    ["Qu'est-ce que l'ordination temporaire dans certains pays bouddhistes ?", ["Une période de vie monastique limitée dans le temps", "Une ordination d'essai", "Un noviciat", "Une retraite spirituelle"], 0,
     "En Thaïlande, de nombreux hommes passent quelques semaines ou mois au monastère."],
    ["Qu'est-ce qu'un monastère cistercien ?", ["Un monastère prônant la simplicité et le travail manuel", "Un monastère urbain", "Un monastère mendiant", "Un monastère enseignant"], 0,
     "L'architecture cistercienne se caractérise par son dépouillement ornemental."],
    ["Quel rôle économique les monastères médiévaux ont-ils joué ?", ["Ils ont défriché, innové et structuré l'économie rurale", "Un rôle marginal", "Un rôle purement spirituel", "Un rôle commercial urbain"], 0,
     "Moulins, forges, vignobles et systèmes hydrauliques leur doivent beaucoup."],
    ["Qu'est-ce qu'un vœu monastique ?", ["Un engagement solennel encadrant la vie religieuse", "Une promesse temporaire", "Un serment liturgique", "Une profession de foi"], 0,
     "Pauvreté, chasteté et obéissance en constituent le socle dans le christianisme."],
    ["Qu'est-ce que la vie monastique féminine ?", ["Une tradition ancienne et importante dans plusieurs religions", "Une pratique récente", "Une exception rare", "Une forme secondaire"], 0,
     "Les abbesses médiévales exerçaient parfois une autorité temporelle considérable.", 3],
  ]),

  notion("mr3-religion-politique", S, "Religion et pouvoir politique",
    "Théocratie, laïcité, régimes de séparation.",
    "Les rapports entre religion et État varient de la fusion complète à la séparation stricte.",
    2, [
    ["Qu'est-ce qu'une théocratie ?", ["Un régime où l'autorité politique se fonde sur une autorité religieuse", "Un régime religieux tolérant", "Une monarchie de droit divin", "Un État confessionnel"], 0,
     "L'Iran depuis 1979 en constitue un exemple contemporain."],
    ["Qu'est-ce qu'un État confessionnel ?", ["Un État reconnaissant une religion officielle", "Un État théocratique", "Un État laïque", "Un État interdisant les cultes"], 0,
     "Le Royaume-Uni et le Danemark en sont des exemples européens, avec des libertés religieuses garanties."],
    ["Qu'est-ce que le césaropapisme ?", ["Un régime où le pouvoir politique contrôle l'institution religieuse", "Un pouvoir religieux sur l'État", "Une séparation stricte", "Une alliance égale"], 0,
     "Le terme est employé notamment à propos de l'Empire byzantin."],
    ["Qu'est-ce que la doctrine des deux glaives ?", ["Une conception médiévale distinguant pouvoirs spirituel et temporel", "Une théorie de la guerre sainte", "Une doctrine militaire", "Un principe de succession"], 0,
     "Leur articulation a nourri des siècles de conflits entre papauté et empereurs."],
    ["Qu'est-ce que le gallicanisme ?", ["Une doctrine limitant l'autorité du pape sur l'Église de France", "Un courant protestant français", "Une théologie janséniste", "Un mouvement anticlérical"], 0,
     "Il a marqué la monarchie française du XVe au XVIIIe siècle."],
    ["Qu'est-ce que l'ultramontanisme ?", ["Une doctrine affirmant l'autorité pleine du pape", "Un courant gallican", "Un mouvement conciliaire", "Une réforme épiscopale"], 0,
     "Il s'oppose au gallicanisme et triomphe au concile Vatican I en 1870."],
    ["Qu'est-ce que la séparation des Églises et de l'État en France ?", ["Un régime où l'État ne reconnaît ni ne subventionne aucun culte", "Une interdiction des religions", "Une neutralité des citoyens", "Une tutelle de l'État sur les cultes"], 0,
     "La loi de 1905 garantit simultanément la liberté de conscience et le libre exercice des cultes."],
    ["Comment les États-Unis organisent-ils les rapports entre religion et État ?", ["Par un premier amendement interdisant l'établissement d'une religion", "Par une religion officielle", "Par une laïcité à la française", "Par un concordat"], 0,
     "La religiosité y reste néanmoins très présente dans la vie publique."],
    ["Qu'est-ce qu'un concordat ?", ["Un accord entre un État et le Saint-Siège organisant les rapports avec l'Église", "Un traité entre religions", "Une charte de tolérance", "Un accord œcuménique"], 0,
     "Celui de 1801 s'applique encore en Alsace-Moselle."],
    ["En quoi la liberté de conscience est-elle plus large que la liberté de culte ?", ["Elle protège aussi ceux qui ne pratiquent aucun culte", "Elle autorise tous les cultes", "Elle concerne l'expression publique", "Elle protège les lieux de culte"], 0,
     "L'article premier de la loi de 1905 la garantit avant même de mentionner l'exercice des cultes.", 3],
  ]),

  notion("mr3-fetes-religieuses", S, "Les grandes fêtes religieuses",
    "Calendriers, significations, pratiques.",
    "De nombreuses fêtes religieuses recouvrent des célébrations saisonnières plus anciennes.",
    2, [
    ["Que commémore Pâques dans le christianisme ?", ["La résurrection du Christ", "Sa naissance", "Sa crucifixion seule", "Son entrée à Jérusalem"], 0,
     "C'est la fête chrétienne la plus importante, dont dépendent plusieurs autres dates."],
    ["Que commémore Yom Kippour dans le judaïsme ?", ["Le Grand Pardon, jour de jeûne et de repentir", "La sortie d'Égypte", "Le don de la Torah", "La création du monde"], 0,
     "Le jeûne y dure environ vingt-cinq heures."],
    ["Que commémore Roch Hachana ?", ["Le nouvel an juif", "Le Grand Pardon", "La fête des cabanes", "La dédicace du Temple"], 0,
     "La sonnerie du chofar, corne de bélier, en est le rite le plus caractéristique."],
    ["Qu'est-ce que Souccot ?", ["La fête des cabanes, rappelant la traversée du désert", "La fête des sorts", "Le nouvel an", "La fête des lumières"], 0,
     "On y construit une cabane végétale où l'on prend ses repas pendant une semaine."],
    ["Qu'est-ce que Pourim ?", ["Une fête joyeuse commémorant le salut des Juifs de Perse", "Une fête de pénitence", "Une fête des moissons", "Une fête des lumières"], 0,
     "Déguisements et lecture du livre d'Esther en sont les traits marquants."],
    ["Que commémore l'Aïd el-Adha ?", ["Le sacrifice interrompu d'Abraham", "La fin du ramadan", "L'hégire", "La naissance du Prophète"], 0,
     "Il coïncide avec la fin du pèlerinage à La Mecque."],
    ["Qu'est-ce que Vesak dans le bouddhisme ?", ["Une fête commémorant naissance, éveil et mort du Bouddha", "Le nouvel an bouddhiste", "Une fête des moines", "Une fête des offrandes"], 0,
     "Elle est célébrée à la pleine lune du mois de mai dans la plupart des pays."],
    ["Qu'est-ce que Holi en Inde ?", ["Une fête printanière marquée par des lancers de poudres colorées", "Une fête des lumières", "Un pèlerinage", "Une fête des moissons d'automne"], 0,
     "Elle célèbre notamment la victoire du bien sur le mal et l'arrivée du printemps."],
    ["Qu'est-ce que la Toussaint ?", ["Une fête catholique honorant tous les saints", "Une fête des morts", "Une fête de la Vierge", "Une commémoration nationale"], 0,
     "La commémoration des défunts a lieu le lendemain, le 2 novembre."],
    ["Pourquoi certaines fêtes religieuses tombent-elles à date fixe et d'autres non ?", ["Les calendriers religieux ne suivent pas tous le calendrier solaire", "Les autorités les fixent chaque année", "Elles suivent les saisons", "Elles dépendent des pays"], 0,
     "Une fête calée sur un calendrier lunaire se décale nécessairement par rapport au calendrier civil.", 3],
  ]),

  notion("mr3-croyances-populaires", S, "Croyances et religiosité populaire",
    "Saints locaux, ex-voto, dévotions.",
    "La religiosité populaire déborde souvent le cadre fixé par les institutions.",
    2, [
    ["Qu'est-ce que la dévotion populaire ?", ["Un ensemble de pratiques religieuses locales souvent extérieures à la liturgie officielle", "Une pratique liturgique", "Un culte officiel", "Une prière collective"], 0,
     "Les institutions l'ont tour à tour encouragée et cherché à l'encadrer."],
    ["Qu'est-ce qu'un saint patron ?", ["Un saint protecteur d'un métier, d'un lieu ou d'un groupe", "Un fondateur d'ordre", "Un saint canonisé récemment", "Un martyr local"], 0,
     "Sainte Barbe pour les mineurs, saint Éloi pour les forgerons, saint Yves pour les juristes."],
    ["Quel effet économique la possession de reliques avait-elle au Moyen Âge ?", ["Elle attirait pèlerins et donations, enrichissant le sanctuaire", "Elle coûtait cher à entretenir", "Elle n'avait aucun effet", "Elle était fiscalement taxée"], 0,
     "Cette rente explique les vols de reliques, parfois racontés comme des exploits pieux."],
    ["Qu'est-ce qu'un reliquaire ?", ["Un contenant précieux abritant une relique", "Une châsse funéraire", "Un autel portatif", "Un coffre liturgique"], 0,
     "Certains reproduisent la forme du membre qu'ils contiennent."],
    ["Que trouve-t-on fréquemment comme ex-voto dans les chapelles littorales ?", ["Des maquettes de navires", "Des filets de pêche", "Des ancres miniatures", "Des cartes marines"], 0,
     "Elles remercient d'un naufrage évité et documentent l'histoire maritime locale."],
    ["Qu'est-ce qu'une procession ?", ["Un déplacement rituel collectif", "Une prière collective statique", "Un pèlerinage individuel", "Une bénédiction publique"], 0,
     "Elle inscrit le sacré dans l'espace du village ou de la ville."],
    ["Qu'est-ce qu'un pardon breton ?", ["Une fête religieuse locale avec procession et pèlerinage", "Une absolution collective", "Une fête patronale civile", "Une bénédiction des bateaux"], 0,
     "Certains rassemblent plusieurs milliers de participants."],
    ["Qu'est-ce qu'une apparition mariale ?", ["Une manifestation de la Vierge rapportée par des témoins", "Une vision collective validée", "Un miracle reconnu", "Une révélation prophétique"], 0,
     "Très peu sont officiellement reconnues par l'Église, après de longues enquêtes."],
    ["Qu'est-ce qu'un guérisseur dans les campagnes françaises ?", ["Une personne exerçant des pratiques traditionnelles de soin", "Un médecin traditionnel reconnu", "Un prêtre exorciste", "Un rebouteux diplômé"], 0,
     "Ces pratiques ont longtemps coexisté avec la médecine officielle et n'ont pas disparu."],
    ["Comment les Églises ont-elles réagi à la religiosité populaire ?", ["Par une alternance d'encadrement, de tolérance et de condamnation", "Par une acceptation constante", "Par une interdiction générale", "Par une indifférence"], 0,
     "Le concile de Trente a notamment cherché à encadrer strictement le culte des saints et des images.", 3],
  ]),

  notion("mr3-nouvelles-spiritualites", S, "Spiritualités contemporaines",
    "Recompositions du croire.",
    "La baisse de la pratique institutionnelle ne signifie pas la disparition du croire.",
    2, [
    ["Qu'est-ce que le croire sans appartenir ?", ["Une religiosité individuelle détachée des institutions", "Une pratique clandestine", "Un athéisme partiel", "Une appartenance sans pratique"], 0,
     "L'expression est due au sociologue britannique Grace Davie."],
    ["Qu'est-ce que le bricolage religieux ?", ["Une composition individuelle d'éléments issus de traditions diverses", "Une conversion successive", "Un syncrétisme institutionnel", "Une pratique œcuménique"], 0,
     "Il caractérise une part importante des spiritualités contemporaines occidentales."],
    ["Qu'est-ce que le mouvement New Age ?", ["Un ensemble diffus de croyances mêlant spiritualité, ésotérisme et développement personnel", "Une religion organisée", "Un courant philosophique", "Une secte structurée"], 0,
     "Il s'est diffusé à partir des années 1970 sans organisation centrale."],
    ["Qu'est-ce que la méditation laïque ?", ["Une pratique détachée de son cadre religieux d'origine", "Une prière silencieuse", "Une relaxation médicale", "Une technique de concentration récente"], 0,
     "Son efficacité sur le stress est documentée, avec des effets souvent surestimés dans les médias."],
    ["Qu'est-ce que le pèlerinage laïcisé ?", ["Une marche accomplie pour des motifs personnels non religieux", "Un tourisme culturel", "Une randonnée sportive", "Une visite patrimoniale"], 0,
     "Une majorité des marcheurs de Compostelle déclarent des motivations mixtes ou non religieuses."],
    ["Qu'est-ce que la spiritualité en entreprise ?", ["Un ensemble de pratiques de bien-être parfois issues de traditions religieuses", "Une pratique religieuse au travail", "Une aumônerie d'entreprise", "Une politique de tolérance religieuse"], 0,
     "Leur usage managérial fait l'objet de critiques sur l'instrumentalisation de ces techniques."],
    ["Qu'est-ce qu'une célébration laïque de mariage ou de funérailles ?", ["Une cérémonie sans référence religieuse marquant une étape de vie", "Un acte administratif", "Un rite civil obligatoire", "Une cérémonie œcuménique"], 0,
     "Leur développement traduit un besoin de rituel indépendant de l'adhésion religieuse."],
    ["Qu'est-ce que la croyance aux médecines alternatives ?", ["Un ensemble de pratiques dont l'efficacité n'est pas démontrée scientifiquement", "Une médecine traditionnelle reconnue", "Une pratique complémentaire validée", "Une médecine douce encadrée"], 0,
     "Le recours à ces pratiques est fréquent et coexiste souvent avec la médecine conventionnelle."],
    ["Qu'est-ce que le rapport des jeunes générations à la religion en Europe ?", ["Une baisse de l'affiliation accompagnée de recompositions", "Un retour massif à la pratique", "Une indifférence totale", "Une stabilité des pratiques"], 0,
     "Les enquêtes montrent des situations très contrastées selon les pays et les milieux."],
    ["Pourquoi parle-t-on de recomposition plutôt que de disparition du religieux ?", ["Les croyances persistent en dehors des cadres institutionnels", "Les religions se réforment", "Les institutions se renforcent", "Les pratiques restent stables"], 0,
     "Les sociologues observent un déplacement plutôt qu'un effacement du croire.", 3],
  ]),

  notion("mr3-symboles-religieux", S, "Symboles et signes religieux",
    "Formes, sens, usages.",
    "Un même symbole peut avoir des significations opposées selon les traditions.",
    2, [
    ["Que représente la croix chrétienne ?", ["L'instrument du supplice du Christ devenu signe de salut", "Un symbole solaire ancien", "Une marque d'appartenance", "Un signe de bénédiction"], 0,
     "Elle n'est devenue le symbole chrétien dominant qu'à partir du IVe siècle."],
    ["Que représente le poisson dans le christianisme primitif ?", ["Un signe de reconnaissance discret entre chrétiens", "Un symbole de baptême", "Un attribut des apôtres", "Un signe eucharistique"], 0,
     "Le mot grec pour poisson forme un acronyme de Jésus-Christ, Fils de Dieu, Sauveur."],
    ["Que représente l'étoile de David ?", ["Un symbole identitaire juif adopté tardivement", "Un symbole biblique ancien", "Un signe liturgique", "Un emblème royal antique"], 0,
     "Son usage comme emblème juif ne se généralise qu'à partir du XIXe siècle."],
    ["Que représente le croissant dans l'islam ?", ["Un symbole d'origine ottomane devenu emblème répandu", "Un symbole coranique", "Un signe liturgique", "Une figure du calendrier lunaire seule"], 0,
     "Il n'a aucune base scripturaire et n'est pas universellement accepté."],
    ["Que représente la roue dans le bouddhisme ?", ["La roue de la loi, symbole de l'enseignement du Bouddha", "Le cycle des saisons", "Le temps cyclique", "La méditation"], 0,
     "Ses huit rayons évoquent le noble sentier octuple."],
    ["Que représente le lotus dans les traditions indiennes ?", ["La pureté naissant de la boue", "La fertilité", "L'immortalité", "La sagesse divine"], 0,
     "La fleur s'élève au-dessus de l'eau sans être souillée, d'où sa valeur symbolique."],
    ["Que représente le om dans l'hindouisme ?", ["Une syllabe sacrée considérée comme le son originel", "Un mot de prière", "Un nom divin", "Un signe d'écriture rituelle"], 0,
     "Elle ouvre et clôt de nombreuses récitations et prières."],
    ["Que représente le yin et le yang ?", ["Deux principes complémentaires et interdépendants", "Le bien et le mal", "L'homme et la femme", "Le jour et la nuit"], 0,
     "Chaque moitié contient un germe de l'autre, ce qui exclut toute opposition absolue."],
    ["Que représente la svastika avant son détournement au XXe siècle ?", ["Un symbole de bon augure présent dans plusieurs traditions asiatiques", "Un symbole guerrier", "Un signe funéraire", "Un emblème politique"], 0,
     "Il reste largement utilisé dans l'hindouisme, le bouddhisme et le jaïnisme."],
    ["Pourquoi l'interprétation d'un symbole religieux exige-t-elle du contexte ?", ["Son sens dépend de la tradition, de l'époque et de l'usage", "Les symboles sont universels", "Les significations sont fixées", "Le sens est toujours littéral"], 0,
     "Un même signe peut signaler une appartenance, une protection ou une doctrine selon les cas.", 3],
  ]),

  notion("mr3-religions-afrique", S, "Religions africaines",
    "Traditions locales, christianismes et islams africains.",
    "L'Afrique est aujourd'hui l'un des principaux foyers de croissance du christianisme et de l'islam.",
    2, [
    ["Qu'est-ce qu'une religion traditionnelle africaine ?", ["Un ensemble de traditions locales diverses, souvent orales", "Une religion unifiée du continent", "Un culte animiste unique", "Une religion sans divinités"], 0,
     "Le pluriel s'impose : les traditions varient d'un peuple à l'autre."],
    ["Qu'est-ce qu'un culte des ancêtres en Afrique ?", ["Des pratiques maintenant un lien entre vivants et défunts de la lignée", "Un culte des esprits de la nature", "Une religion sans divinité", "Un culte funéraire ponctuel"], 0,
     "Les ancêtres y sont souvent perçus comme des intermédiaires actifs."],
    ["Qu'est-ce qu'un féticheur ?", ["Un spécialiste rituel manipulant des objets chargés de puissance", "Un sorcier malfaisant", "Un prêtre traditionnel", "Un guérisseur uniquement"], 0,
     "Le mot vient du portugais feitiço et charrie une connotation coloniale péjorative."],
    ["Qu'est-ce que le vodun au Bénin ?", ["Une religion structurée reconnue officiellement", "Une pratique de sorcellerie", "Un culte funéraire", "Une confrérie initiatique seule"], 0,
     "Le Bénin lui consacre une fête nationale chaque 10 janvier."],
    ["Qu'est-ce que le candomblé au Brésil ?", ["Une religion afro-brésilienne héritée des traditions yoruba", "Une danse rituelle", "Un culte syncrétique catholique", "Une confrérie de quartier"], 0,
     "Ses divinités, les orishas, ont souvent été associées à des saints catholiques sous la contrainte."],
    ["Qu'est-ce que la santeria à Cuba ?", ["Une religion afro-cubaine mêlant traditions yoruba et catholicisme", "Un culte de guérison", "Une pratique divinatoire", "Une confrérie initiatique"], 0,
     "Elle illustre les stratégies de survie religieuse sous l'esclavage."],
    ["Quelle religion connaît la plus forte croissance en Afrique subsaharienne ?", ["Le christianisme, notamment évangélique et pentecôtiste", "L'islam soufi", "Les religions traditionnelles", "Le catholicisme seul"], 0,
     "Les Églises indépendantes africaines y jouent un rôle majeur."],
    ["Qu'est-ce qu'une Église indépendante africaine ?", ["Une Église fondée par des Africains hors des missions occidentales", "Une Église nationale d'État", "Une mission protestante locale", "Une congrégation catholique africaine"], 0,
     "Elles se comptent par milliers et intègrent souvent des éléments culturels locaux."],
    ["Qu'est-ce qu'une confrérie soufie en Afrique de l'Ouest ?", ["Une organisation religieuse structurant la vie sociale et économique", "Un ordre monastique", "Une école coranique", "Une association caritative"], 0,
     "La Mouridiya au Sénégal en est un exemple aux ramifications économiques importantes."],
    ["Comment traditions locales et religions monothéistes coexistent-elles souvent en Afrique ?", ["Par des articulations et des emprunts plutôt que par exclusion", "Par une substitution complète", "Par une séparation stricte", "Par un conflit permanent"], 0,
     "Les pratiques observées relèvent souvent de plusieurs registres selon les circonstances.", 3],
  ]),

  notion("mr3-religions-ameriques", S, "Religions des Amériques",
    "Traditions autochtones et christianismes américains.",
    "L'évangélisation des Amériques a produit des formes religieuses inédites.",
    2, [
    ["Qu'est-ce que le syncrétisme religieux en Amérique latine ?", ["Une combinaison de traditions autochtones ou africaines et du catholicisme", "Une conversion complète", "Une coexistence séparée", "Un abandon des traditions locales"], 0,
     "La Vierge de Guadalupe en est un exemple emblématique au Mexique."],
    ["Qu'est-ce que la Vierge de Guadalupe ?", ["Une apparition mariale devenue symbole national mexicain", "Une sainte locale", "Une figure préhispanique", "Une statue miraculeuse espagnole"], 0,
     "Le lieu de son apparition correspondait à un ancien sanctuaire préhispanique."],
    ["Qu'est-ce que la fête des morts au Mexique ?", ["Une célébration mêlant traditions préhispaniques et catholiques", "Une fête catholique importée", "Une fête préhispanique intacte", "Une commémoration civile"], 0,
     "Elle est inscrite au patrimoine culturel immatériel de l'humanité."],
    ["Qu'est-ce qu'une réduction jésuite ?", ["Un village organisé par les jésuites pour regrouper des populations autochtones", "Une mission itinérante", "Un monastère colonial", "Un comptoir commercial"], 0,
     "Celles du Paraguay ont fonctionné plus d'un siècle avant l'expulsion des jésuites."],
    ["Quel archevêque salvadorien proche des pauvres est assassiné en 1980 ?", ["Oscar Romero", "Hélder Câmara", "Gustavo Gutiérrez", "Leonardo Boff"], 0,
     "Abattu pendant une messe, il a été canonisé en 2018."],
    ["Quel courant chrétien progresse rapidement en Amérique latine ?", ["Le pentecôtisme évangélique", "Le catholicisme traditionnel", "L'orthodoxie", "L'anglicanisme"], 0,
     "Le Brésil et le Guatemala comptent parmi les pays les plus concernés."],
    ["Qu'est-ce qu'un potlatch chez certains peuples de la côte nord-ouest américaine ?", ["Une cérémonie de don ostentatoire affirmant le rang social", "Un rite funéraire", "Une danse rituelle", "Un conseil tribal"], 0,
     "Il fut interdit au Canada de 1885 à 1951, précisément en raison de son importance sociale."],
    ["Qu'est-ce qu'une hutte à sudation ?", ["Un rite de purification par la chaleur pratiqué par plusieurs peuples autochtones", "Un abri temporaire", "Une salle de conseil", "Un lieu de guérison médicale"], 0,
     "Sa reprise commerciale hors contexte a causé des accidents et suscité de vives critiques."],
    ["Qu'est-ce que le peyotl dans certaines traditions amérindiennes ?", ["Un cactus utilisé rituellement dans un cadre religieux encadré", "Une plante médicinale ordinaire", "Un aliment cérémoniel", "Un colorant rituel"], 0,
     "La Native American Church en fait un usage protégé aux États-Unis."],
    ["Qu'est-ce que l'appropriation culturelle de rites autochtones ?", ["La reprise de pratiques hors de leur contexte, souvent à des fins commerciales", "Un échange culturel", "Une transmission autorisée", "Un syncrétisme religieux"], 0,
     "Les communautés concernées dénoncent régulièrement ces usages non autorisés.", 3],
  ]),

  notion("mr3-dialogue-conflits", S, "Religions, conflits et dialogue",
    "Guerres de religion, coexistence, médiation.",
    "Les conflits dits religieux mêlent presque toujours des enjeux politiques et économiques.",
    2, [
    ["Pourquoi parle-t-on rarement de conflits purement religieux ?", ["Des enjeux politiques, territoriaux et économiques y sont toujours mêlés", "La religion n'y joue aucun rôle", "Les croyances sont secondaires", "Les acteurs sont laïques"], 0,
     "La religion peut fournir un langage et une mobilisation sans être la cause unique."],
    ["Qu'est-ce que la coexistence confessionnelle au Liban ?", ["Un système politique répartissant les fonctions entre communautés", "Une séparation territoriale", "Une neutralité de l'État", "Une religion officielle unique"], 0,
     "Ce confessionnalisme institutionnel est à la fois un équilibre et une source de blocages."],
    ["Qu'est-ce que le conflit nord-irlandais ?", ["Un conflit politique et identitaire recoupant une division confessionnelle", "Une guerre de religion", "Un conflit purement territorial", "Un conflit linguistique"], 0,
     "L'accord du Vendredi saint, en 1998, y a mis largement fin."],
    ["Qu'est-ce que le dialogue islamo-chrétien ?", ["Des échanges organisés entre représentants des deux traditions", "Une fusion doctrinale", "Une négociation politique", "Un accord théologique"], 0,
     "Le document sur la fraternité humaine signé à Abou Dhabi en 2019 en est un jalon récent."],
    ["Qu'est-ce que la déclaration Nostra aetate ?", ["Un texte de Vatican II sur les relations avec les religions non chrétiennes", "Une encyclique sociale", "Un texte œcuménique", "Une constitution liturgique"], 0,
     "Elle a notamment transformé le rapport de l'Église catholique au judaïsme."],
    ["Qu'est-ce que l'antisémitisme ?", ["Une hostilité systématique envers les Juifs", "Une critique du judaïsme", "Une opposition politique", "Un rejet religieux ancien seul"], 0,
     "Le terme, forgé au XIXe siècle, désigne une idéologie de nature raciale et non seulement religieuse."],
    ["Qu'est-ce que l'islamophobie selon les organisations internationales ?", ["Une hostilité visant les musulmans en tant que tels", "Une critique de l'islam", "Un débat sur la laïcité", "Une opposition doctrinale"], 0,
     "Le terme lui-même fait l'objet de débats sur sa définition et son usage."],
    ["Qu'est-ce que la liberté de critiquer une religion en France ?", ["Un droit protégé, distinct de l'injure envers les personnes", "Un droit sans limite", "Un délit de blasphème", "Une liberté encadrée par les cultes"], 0,
     "Le délit de blasphème n'existe pas en droit français depuis 1881."],
    ["Qu'est-ce qu'un lieu de culte partagé ?", ["Un espace fréquenté par plusieurs communautés religieuses", "Un lieu œcuménique construit à cet effet", "Un lieu abandonné réaffecté", "Un lieu multiconfessionnel officiel"], 0,
     "Plusieurs sanctuaires du pourtour méditerranéen sont fréquentés par des fidèles de traditions différentes."],
    ["Qu'est-ce que la médiation interreligieuse dans les conflits ?", ["L'implication de responsables religieux dans des processus de paix", "Une négociation théologique", "Un arbitrage international", "Une réconciliation doctrinale"], 0,
     "Des acteurs religieux ont joué ce rôle en Afrique du Sud, au Mozambique et ailleurs.", 3],
  ]),
];
