/**
 * Physique & chimie — treize notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Physique & Chimie";

export const CG_PHYSIQUE_CHIMIE: SeedSkill[] = [
  notion("pc-tableau-periodique", S, "Le tableau périodique des éléments",
    "Cent dix-huit cases rangées par numéro atomique, où la place d'un élément annonce son comportement.",
    "Une colonne réunit des éléments aux propriétés voisines : c'est le nombre d'électrons externes qui les rapproche.",
    2, [
    ["Qui publie en 1869 le tableau périodique laissant des cases vides pour des éléments inconnus ?", ["Dmitri Mendeleïev", "Antoine Lavoisier", "John Dalton", "Marie Curie"], 0,
     "Il prédit les propriétés du gallium et du germanium avant leur découverte, ce qui valide sa classification."],
    ["Qu'est-ce que le numéro atomique d'un élément ?", ["Son nombre de protons", "Son nombre de neutrons", "Sa masse en unités atomiques", "Son nombre d'électrons de valence"], 0,
     "Il définit l'élément : changer le nombre de protons, c'est changer d'élément."],
    ["Qu'appelle-t-on gaz nobles ?", ["Les éléments de la dernière colonne, chimiquement très peu réactifs", "Les métaux précieux", "Les gaz de l'atmosphère", "Les éléments radioactifs légers"], 0,
     "Hélium, néon, argon, krypton, xénon, radon : leur couche externe est saturée, ils ne cherchent pas à réagir."],
    ["Que sont deux isotopes d'un même élément ?", ["Des atomes de même nombre de protons mais de nombre de neutrons différent", "Des atomes de charge différente", "Deux formes cristallines", "Deux états d'oxydation"], 0,
     "Le carbone 12 et le carbone 14 ont les mêmes propriétés chimiques mais des masses et des stabilités différentes."],
    ["Quel élément porte le symbole Fe ?", ["Le fer", "Le fluor", "Le francium", "Le fermium"], 0,
     "Le symbole vient du latin ferrum. Beaucoup de métaux connus dès l'Antiquité gardent leur nom latin."],
    ["Quel élément porte le symbole Au ?", ["L'or", "L'argent", "L'aluminium", "L'argon"], 0,
     "Du latin aurum. L'argent est Ag, pour argentum."],
    ["Quel élément la fusion produit-elle au cœur du Soleil ?", ["De l'hélium à partir d'hydrogène", "De l'hydrogène à partir d'hélium", "Du carbone à partir d'oxygène", "Du fer à partir de silicium"], 0,
     "Quatre noyaux d'hydrogène donnent un noyau d'hélium ; la légère perte de masse devient énergie."],
    ["Quelle est l'origine des éléments plus lourds que le fer ?", ["Les supernovae et les fusions d'étoiles à neutrons", "Le Big Bang", "La fusion ordinaire des étoiles", "La radioactivité terrestre"], 0,
     "La fusion cesse d'être rentable au fer : au-delà, il faut des événements bien plus violents.", 3],
  ]),

  notion("pc-etats-matiere", S, "Les états de la matière et leurs changements",
    "Solide, liquide, gaz, plasma : la même matière, des arrangements différents, et des transitions à températures fixes.",
    "Pendant un changement d'état, la température ne bouge pas : toute l'énergie sert à casser les liaisons.",
    2, [
    ["Comment appelle-t-on le passage du liquide au gaz ?", ["La vaporisation", "La condensation", "La sublimation", "La fusion"], 0,
     "Elle prend le nom d'ébullition quand elle se produit dans toute la masse du liquide, et non seulement en surface."],
    ["Comment appelle-t-on le passage du gaz au solide directement ?", ["La condensation solide", "La sublimation", "La fusion", "La solidification"], 0,
     "Le givre en est un exemple : la vapeur d'eau se dépose en cristaux sans passer par l'état liquide."],
    ["Que se passe-t-il pour la température pendant un changement d'état pur ?", ["Elle reste constante", "Elle augmente régulièrement", "Elle chute brusquement", "Elle oscille"], 0,
     "L'énergie fournie sert à rompre les liaisons entre molécules, pas à les agiter davantage."],
    ["À quelle température l'eau bout-elle au niveau de la mer ?", ["Cent degrés Celsius", "Quatre-vingt-dix degrés", "Cent dix degrés", "Quatre-vingt-dix-huit degrés"], 0,
     "En altitude, la pression plus faible abaisse ce point : environ quatre-vingt-cinq degrés à trois mille mètres."],
    ["Qu'est-ce que le plasma ?", ["Un gaz ionisé, où électrons et noyaux sont séparés", "Un liquide très visqueux", "Un solide amorphe", "Un gaz sous très haute pression"], 0,
     "C'est l'état le plus répandu de la matière visible de l'univers : les étoiles en sont faites."],
    ["Qu'est-ce que le zéro absolu ?", ["La température la plus basse possible, soit moins 273,15 degrés Celsius", "Le point de congélation de l'eau", "La température de l'espace intersidéral", "La température de fusion de l'hélium"], 0,
     "C'est le zéro de l'échelle Kelvin. Il est inatteignable, seulement approchable."],
    ["Pourquoi une cocotte-minute cuit-elle plus vite ?", ["La pression élevée fait bouillir l'eau au-dessus de cent degrés", "Elle chauffe plus fort", "Elle conserve mieux la vapeur", "Elle réduit l'évaporation"], 0,
     "L'eau y atteint environ cent vingt degrés, ce qui accélère considérablement les réactions de cuisson."],
    ["Qu'est-ce qu'un état supercritique ?", ["Un état où liquide et gaz ne se distinguent plus", "Un solide instable", "Un plasma froid", "Un liquide surfondu"], 0,
     "Le CO2 supercritique sert notamment à décaféiner le café sans solvant chimique."],
    ["Pourquoi le sel fait-il fondre la glace ?", ["Il abaisse la température de fusion de l'eau", "Il produit de la chaleur", "Il absorbe l'humidité", "Il augmente la pression sur la glace"], 0,
     "L'efficacité chute nettement en dessous de moins dix degrés environ."],
    ["Qu'est-ce qu'un superfluide ?", ["Un liquide sans viscosité, qui s'écoule sans frottement", "Un liquide très dense", "Un gaz liquéfié", "Un liquide magnétique"], 0,
     "L'hélium liquide en devient un sous environ deux kelvins : il remonte les parois de son récipient.", 3],
  ]),

  notion("pc-electricite", S, "L'électricité et le magnétisme",
    "Tension, intensité, résistance : trois grandeurs liées par une loi simple, et un lien profond avec le magnétisme.",
    "La tension pousse, l'intensité circule, la résistance freine. U = R × I résume tout le reste.",
    2, [
    ["Quelle unité mesure la tension électrique ?", ["Le volt", "l'ampère", "l'ohm", "le watt"], 0,
     "Nommée d'après Alessandro Volta, inventeur de la première pile en 1800."],
    ["Quelle unité mesure l'intensité du courant ?", ["l'ampère", "le volt", "le coulomb", "le watt"], 0,
     "Elle mesure la quantité de charges qui passe par seconde. C'est l'intensité qui est dangereuse pour le corps, pas la tension seule."],
    ["Que dit la loi d'Ohm ?", ["La tension égale la résistance multipliée par l'intensité", "La puissance égale la tension au carré", "Le courant est proportionnel à la puissance", "La résistance dépend de la tension"], 0,
     "Formulée par Georg Ohm en 1827, elle vaut pour les conducteurs dits ohmiques."],
    ["Comment calcule-t-on la puissance électrique en courant continu ?", ["En multipliant la tension par l'intensité", "En divisant la tension par l'intensité", "En multipliant la résistance par l'intensité", "En ajoutant tension et intensité"], 0,
     "Un appareil de deux cent trente volts qui tire dix ampères consomme deux mille trois cents watts."],
    ["Quelle est la tension du réseau domestique en France ?", ["Deux cent trente volts", "Cent dix volts", "Quatre cents volts", "Cent vingt volts"], 0,
     "L'Amérique du Nord utilise environ cent vingt volts, ce qui impose des intensités plus fortes à puissance égale."],
    ["Qui découvre en 1820 qu'un courant dévie une aiguille aimantée ?", ["Hans Christian Ørsted", "Michael Faraday", "André-Marie Ampère", "James Clerk Maxwell"], 0,
     "L'observation, faite pendant un cours, fonde l'électromagnétisme."],
    ["Quel principe permet de produire du courant avec un aimant en mouvement ?", ["L'induction électromagnétique", "L'effet Joule", "L'effet photoélectrique", "La conduction"], 0,
     "Découverte par Faraday en 1831, elle est le fondement de tous les alternateurs et transformateurs."],
    ["Qu'est-ce que l'effet Joule ?", ["La production de chaleur par le passage du courant dans un conducteur", "La production de lumière par un filament", "La perte de tension dans un câble", "La création d'un champ magnétique"], 0,
     "Utile dans un radiateur, c'est une perte pure dans une ligne à haute tension."],
    ["Pourquoi transporte-t-on l'électricité à très haute tension ?", ["Pour réduire l'intensité et donc les pertes en ligne", "Parce que les câbles le supportent mieux", "Pour aller plus vite", "Pour éviter les orages"], 0,
     "Les pertes croissent avec le carré de l'intensité : à puissance égale, plus la tension est haute, moins on perd."],
    ["Qu'est-ce qu'un supraconducteur ?", ["Un matériau dont la résistance devient nulle en dessous d'une température critique", "Un conducteur très épais", "Un matériau qui amplifie le courant", "Un isolant devenu conducteur sous tension"], 0,
     "Découverte en 1911 par Kamerlingh Onnes. Les supraconducteurs à haute température restent un objectif de recherche.", 3],
  ]),

  notion("pc-lumiere-ondes", S, "La lumière et les ondes",
    "Une onde et une particule à la fois, un spectre bien plus large que le visible, et des lois de propagation simples.",
    "Le visible n'est qu'une mince tranche du spectre électromagnétique, entre l'infrarouge et l'ultraviolet.",
    2, [
    ["Que définit aujourd'hui la valeur exacte de 299 792 458 mètres par seconde ?", ["Le mètre", "La seconde", "Le joule", "Le kelvin"], 0,
     "Depuis 1983, la vitesse de la lumière est figée par convention et c'est le mètre qui en découle."],
    ["Quelles couleurs bornent le spectre visible ?", ["Le violet et le rouge", "Le bleu et le jaune", "L'ultraviolet et l'infrarouge", "Le vert et l'orange"], 0,
     "Le violet a la plus courte longueur d'onde, le rouge la plus longue. Au-delà commencent ultraviolet et infrarouge."],
    ["Pourquoi le ciel est-il bleu ?", ["Les molécules de l'air diffusent davantage les courtes longueurs d'onde", "L'océan se reflète dans l'atmosphère", "L'ozone est bleu", "La lumière du Soleil est bleue"], 0,
     "C'est la diffusion Rayleigh. Au couchant, la lumière traverse plus d'atmosphère et le rouge domine."],
    ["Qu'est-ce que la réfraction ?", ["Le changement de direction de la lumière en changeant de milieu", "Le renvoi de la lumière par un miroir", "L'absorption de la lumière", "La décomposition de la lumière en couleurs"], 0,
     "C'est elle qui fait paraître brisé un bâton plongé dans l'eau."],
    ["Qui décompose la lumière blanche avec un prisme au XVIIe siècle ?", ["Isaac Newton", "Christiaan Huygens", "René Descartes", "Galilée"], 0,
     "Il montre que le prisme ne colore pas la lumière mais sépare des couleurs déjà présentes."],
    ["Comment se forme un arc-en-ciel ?", ["Par réfraction et réflexion de la lumière dans les gouttes de pluie", "Par diffusion dans les nuages", "Par diffraction sur la glace", "Par polarisation de la lumière solaire"], 0,
     "Il apparaît toujours à l'opposé du Soleil, et son centre se trouve sous l'horizon quand le Soleil est haut."],
    ["Qu'est-ce que l'effet photoélectrique ?", ["L'éjection d'électrons par la lumière frappant un métal", "La production de lumière par un courant", "L'échauffement d'un métal exposé au soleil", "La réflexion sur une surface métallique"], 0,
     "Son explication par Einstein en 1905, qui suppose des grains de lumière, lui vaudra le Nobel."],
    ["Que signifie le mot laser ?", ["Amplification de lumière par émission stimulée de rayonnement", "Lumière artificielle à spectre étroit", "Rayon d'énergie concentrée", "Source lumineuse à électrons"], 0,
     "L'acronyme anglais décrit le mécanisme : les photons émis sont tous en phase et de même longueur d'onde."],
    ["Quelle onde électromagnétique a la plus courte longueur d'onde ?", ["Les rayons gamma", "Les rayons X", "Les ultraviolets", "Les micro-ondes"], 0,
     "L'ordre décroissant est : ondes radio, micro-ondes, infrarouge, visible, ultraviolet, rayons X, rayons gamma."],
    ["Qu'est-ce que la dualité onde-corpuscule ?", ["La lumière et la matière se comportent tantôt comme des ondes, tantôt comme des particules", "La lumière change de nature selon la couleur", "Toute onde possède une masse", "Une particule émet toujours une onde"], 0,
     "Louis de Broglie l'étend à la matière en 1924 : un électron aussi peut diffracter.", 3],
  ]),

  notion("pc-forces-mouvement", S, "Forces, mouvement et gravitation",
    "Trois lois formulées en 1687, une force universelle, et de quoi décrire aussi bien une pomme qu'une planète.",
    "Un corps sans force ne s'arrête pas : il continue tout droit. C'est le frottement qui nous trompe.",
    2, [
    ["Que dit le principe d'inertie ?", ["Un corps sans force extérieure garde une vitesse constante", "Tout corps finit par s'arrêter", "Un corps tombe à vitesse constante", "Toute force produit une accélération constante"], 0,
     "Formulé par Galilée puis Newton, il contredit l'intuition héritée d'Aristote."],
    ["Que relie la deuxième loi de Newton ?", ["La force, la masse et l'accélération", "La vitesse et le temps", "L'énergie et la masse", "La force et la distance"], 0,
     "F = m × a. Une même force accélère deux fois moins un corps deux fois plus lourd."],
    ["Que dit le principe des actions réciproques ?", ["Toute action s'accompagne d'une réaction égale et opposée", "Toute force finit par s'annuler", "Deux forces égales s'annulent toujours", "L'action précède la réaction"], 0,
     "Les deux forces s'exercent sur des corps différents : c'est pourquoi elles ne s'annulent pas."],
    ["Quelle est la valeur approximative de l'accélération de la pesanteur sur Terre ?", ["Environ 9,81 mètres par seconde carrée", "Environ 1,6 mètre par seconde carrée", "Environ 20 mètres par seconde carrée", "Environ 3 mètres par seconde carrée"], 0,
     "Elle varie légèrement avec la latitude et l'altitude. Sur la Lune, elle vaut environ 1,6."],
    ["Dans le vide, une plume et un marteau lâchés ensemble tombent-ils à la même vitesse ?", ["Oui, la chute ne dépend pas de la masse", "Non, le marteau tombe plus vite", "Non, la plume tombe plus vite", "Cela dépend de la hauteur"], 0,
     "L'expérience a été refaite sur la Lune par David Scott en 1971, pendant Apollo 15."],
    ["Qu'est-ce que le poids d'un corps ?", ["La force d'attraction gravitationnelle qu'il subit", "Sa quantité de matière", "Sa masse multipliée par son volume", "Une grandeur indépendante du lieu"], 0,
     "La masse reste identique partout, le poids change avec la gravité locale. Il se mesure en newtons."],
    ["Pourquoi les astronautes flottent-ils dans la Station spatiale ?", ["Ils sont en chute libre permanente autour de la Terre", "Il n'y a pas de gravité à cette altitude", "Ils sont trop loin de la Terre", "La rotation annule la gravité"], 0,
     "À quatre cents kilomètres, la gravité vaut encore environ quatre-vingt-dix pour cent de sa valeur au sol."],
    ["Que décrit la loi de la gravitation universelle ?", ["Deux masses s'attirent proportionnellement au produit de leurs masses et à l'inverse du carré de leur distance", "Toute masse attire proportionnellement à son volume", "L'attraction décroît proportionnellement à la distance", "Seules les grandes masses s'attirent"], 0,
     "Newton l'énonce en 1687 dans les Principia et unifie ainsi la chute des corps et le mouvement des astres."],
    ["Qu'apporte la relativité générale d'Einstein en 1915 ?", ["La gravitation devient une déformation de l'espace-temps", "La lumière devient plus rapide près des masses", "La gravité disparaît à grande échelle", "Les lois de Newton sont réfutées à toute échelle"], 0,
     "Les lois de Newton restent une excellente approximation à faible vitesse et faible champ."],
    ["Qu'est-ce qu'une onde gravitationnelle ?", ["Une ondulation de l'espace-temps provoquée par des masses accélérées", "Une variation de la pesanteur terrestre", "Une onde de choc dans le vide", "Un rayonnement émis par les trous noirs"], 0,
     "Prédite en 1916, la première détection directe date de 2015, lors de la fusion de deux trous noirs.", 3],
  ]),

  notion("pc-energie", S, "L'énergie et ses transformations",
    "Elle ne se crée ni ne se perd, mais se dégrade : le principe qui gouverne toutes les machines.",
    "Le rendement d'une machine thermique est plafonné par la physique, pas par la qualité de la fabrication.",
    2, [
    ["Que dit le premier principe de la thermodynamique ?", ["L'énergie se conserve, elle ne fait que changer de forme", "L'énergie se dégrade toujours", "Toute machine perd de l'énergie", "L'énergie augmente avec le désordre"], 0,
     "Il interdit le mouvement perpétuel de première espèce, qui produirait de l'énergie à partir de rien."],
    ["Que dit le second principe de la thermodynamique ?", ["L'entropie d'un système isolé ne peut que croître", "L'énergie totale diminue", "La chaleur va du froid vers le chaud", "Tout système tend vers l'équilibre mécanique"], 0,
     "C'est lui qui donne une flèche au temps et interdit de convertir intégralement la chaleur en travail."],
    ["Quelle unité mesure l'énergie dans le Système international ?", ["Le joule", "Le watt", "La calorie", "Le kilowattheure"], 0,
     "Le watt mesure une puissance, soit une énergie par seconde. Un watt vaut un joule par seconde."],
    ["Qu'est-ce que l'énergie cinétique ?", ["L'énergie liée au mouvement d'un corps", "L'énergie liée à sa position", "L'énergie de sa masse au repos", "L'énergie stockée sous forme de chaleur"], 0,
     "Elle croît avec le carré de la vitesse : rouler deux fois plus vite quadruple l'énergie à dissiper au freinage."],
    ["Qu'est-ce que l'énergie potentielle de pesanteur ?", ["L'énergie liée à la position d'un corps dans un champ de pesanteur", "L'énergie du mouvement vertical", "L'énergie stockée dans les liaisons chimiques", "L'énergie dissipée par frottement"], 0,
     "C'est elle qu'exploitent les barrages hydroélectriques et les stations de pompage-turbinage."],
    ["Que signifie la relation E = mc² ?", ["Masse et énergie sont deux formes d'une même grandeur", "L'énergie croît avec la vitesse de la lumière", "La masse détruit l'énergie", "Toute énergie possède une vitesse"], 0,
     "Une très faible perte de masse libère une énergie considérable : c'est le principe des réactions nucléaires."],
    ["Quel est l'ordre de grandeur du rendement d'un moteur thermique de voiture ?", ["Autour de trente à quarante pour cent", "Autour de dix pour cent", "Autour de quatre-vingts pour cent", "Autour de soixante pour cent"], 0,
     "Le reste part en chaleur. Un moteur électrique dépasse quatre-vingt-dix pour cent."],
    ["Qu'est-ce qu'une pompe à chaleur ?", ["Un dispositif qui transfère la chaleur d'un milieu froid vers un milieu chaud", "Un chauffage électrique amélioré", "Un système qui crée de la chaleur", "Un échangeur passif"], 0,
     "Elle ne crée pas d'énergie : elle en déplace, ce qui lui permet de restituer plus de chaleur qu'elle ne consomme d'électricité."],
    ["Quelle différence y a-t-il entre fission et fusion nucléaires ?", ["La fission casse un noyau lourd, la fusion assemble des noyaux légers", "La fission assemble, la fusion casse", "La fission concerne l'hydrogène", "La fusion produit des déchets radioactifs à vie longue"], 0,
     "Les centrales actuelles utilisent la fission de l'uranium. La fusion contrôlée reste au stade expérimental."],
    ["Qu'est-ce que l'exergie, ou énergie utile ?", ["La part d'une énergie réellement convertible en travail", "L'énergie totale d'un système", "L'énergie dissipée en chaleur", "L'énergie stockée dans un réservoir"], 0,
     "Un kilojoule d'électricité et un kilojoule d'eau tiède n'ont pas la même valeur d'usage : c'est ce que mesure l'exergie.", 3],
  ]),

  notion("pc-reactions-chimiques", S, "Les réactions chimiques",
    "Des atomes qui se réorganisent sans jamais disparaître : conservation de la matière, équilibres et catalyse.",
    "Rien ne se perd, rien ne se crée : une équation chimique doit être équilibrée des deux côtés.",
    2, [
    ["Qui énonce que rien ne se perd et rien ne se crée dans une réaction chimique ?", ["Antoine Lavoisier", "Joseph Priestley", "Robert Boyle", "John Dalton"], 0,
     "Il fonde la chimie moderne en pesant systématiquement réactifs et produits."],
    ["Qu'est-ce qu'un catalyseur ?", ["Une substance qui accélère une réaction sans être consommée", "Un réactif en excès", "Un produit secondaire", "Un solvant réactif"], 0,
     "Il abaisse l'énergie d'activation. Les enzymes sont les catalyseurs du vivant."],
    ["Qu'est-ce qu'une oxydation ?", ["Une perte d'électrons", "Un gain d'électrons", "Une réaction avec l'eau", "Une combustion incomplète"], 0,
     "Elle s'accompagne toujours d'une réduction ailleurs : les électrons perdus par l'un sont gagnés par l'autre."],
    ["Que mesure le pH ?", ["L'acidité d'une solution", "La concentration en sel", "La conductivité électrique", "La température de réaction"], 0,
     "Un pH inférieur à sept est acide, supérieur à sept basique. L'échelle est logarithmique : chaque unité vaut un facteur dix."],
    ["Quel est le pH approximatif de l'eau pure à vingt-cinq degrés ?", ["Sept", "Cinq", "Neuf", "Zéro"], 0,
     "C'est la neutralité. L'eau de pluie ordinaire, chargée en CO2 dissous, est légèrement acide, autour de cinq et demi."],
    ["Qu'est-ce qu'une réaction exothermique ?", ["Une réaction qui libère de la chaleur", "Une réaction qui absorbe de la chaleur", "Une réaction qui produit un gaz", "Une réaction très rapide"], 0,
     "Les combustions en sont l'exemple type. Une réaction endothermique, à l'inverse, refroidit son milieu."],
    ["Quelle est la formule chimique du sel de table ?", ["NaCl", "KCl", "CaCO3", "NaHCO3"], 0,
     "Chlorure de sodium. Le bicarbonate de soude est NaHCO3, le calcaire CaCO3."],
    ["Qu'est-ce qu'une liaison covalente ?", ["Un partage d'électrons entre deux atomes", "Un transfert complet d'électrons", "Une attraction entre molécules", "Une liaison entre métaux"], 0,
     "La liaison ionique, elle, résulte d'un transfert : un atome cède, l'autre capte."],
    ["Lequel de ces polymères est d'origine naturelle ?", ["La cellulose", "Le polyéthylène", "Le polystyrène", "Le PVC"], 0,
     "Protéines et ADN sont également des polymères naturels : le motif s'y répète des milliers de fois."],
    ["Que décrit le principe de Le Chatelier ?", ["Un système à l'équilibre réagit de façon à s'opposer à la perturbation qu'on lui impose", "Une réaction va toujours vers le produit le plus stable", "Une réaction s'accélère avec la pression", "L'équilibre est atteint quand les concentrations sont égales"], 0,
     "Augmenter la pression déplace l'équilibre du côté où il y a le moins de molécules de gaz.", 3],
  ]),

  notion("pc-astronomie-systeme", S, "Le système solaire",
    "Une étoile, huit planètes, une ceinture d'astéroïdes et des objets glacés : l'inventaire de notre voisinage.",
    "Une planète doit avoir nettoyé son orbite : c'est ce critère de 2006 qui a exclu Pluton.",
    2, [
    ["Combien de planètes compte le système solaire depuis 2006 ?", ["Huit", "Neuf", "Sept", "Dix"], 0,
     "Pluton a été reclassée en planète naine, une catégorie créée la même année."],
    ["Quelle est la plus grosse planète du système solaire ?", ["Jupiter", "Saturne", "Neptune", "Uranus"], 0,
     "Sa masse dépasse deux fois celle de toutes les autres planètes réunies."],
    ["Quelle planète est la plus chaude du système solaire ?", ["Vénus", "Mercure", "Mars", "Jupiter"], 0,
     "Son atmosphère de CO2 produit un effet de serre extrême : environ quatre cent soixante degrés en surface, malgré sa distance."],
    ["Où se situe la ceinture d'astéroïdes principale ?", ["Entre Mars et Jupiter", "Entre la Terre et Mars", "Au-delà de Neptune", "Entre Jupiter et Saturne"], 0,
     "Sa masse totale reste inférieure à celle de la Lune : ce n'est pas une planète avortée dense."],
    ["Qu'est-ce que la ceinture de Kuiper ?", ["Une région d'objets glacés au-delà de Neptune", "Un anneau de poussière autour du Soleil", "Une zone d'astéroïdes métalliques", "Un nuage de comètes très lointain"], 0,
     "Pluton en fait partie. Le nuage d'Oort, bien plus lointain, est la réserve supposée des comètes à longue période."],
    ["Qu'est-ce qui distingue une comète d'un astéroïde ?", ["La comète est riche en glaces et développe une queue près du Soleil", "La comète est plus grosse", "L'astéroïde tourne plus vite", "La comète est métallique"], 0,
     "La queue pointe toujours à l'opposé du Soleil, poussée par le vent solaire, quel que soit le sens du mouvement."],
    ["Quelle est la durée approximative du trajet de la lumière du Soleil à la Terre ?", ["Environ huit minutes", "Environ une seconde", "Environ une heure", "Environ trente secondes"], 0,
     "Cent cinquante millions de kilomètres, soit une unité astronomique."],
    ["Quelle sonde a survolé Pluton en 2015 ?", ["New Horizons", "Voyager 2", "Cassini", "Juno"], 0,
     "Elle a révélé une géologie active, avec des plaines d'azote gelé et des montagnes de glace d'eau."],
    ["Comment s'est probablement formée la Lune ?", ["Par la collision de la Terre primitive avec un corps de la taille de Mars", "Par capture d'un astéroïde", "Par accrétion simultanée avec la Terre", "Par éjection due à la rotation terrestre"], 0,
     "L'hypothèse de l'impact géant explique la composition de la Lune, très proche du manteau terrestre.", 3],
  ]),

  notion("pc-univers-cosmologie", S, "L'univers et son histoire",
    "Treize milliards huit cents millions d'années, une expansion mesurée, et quatre-vingt-quinze pour cent de contenu inconnu.",
    "L'expansion n'est pas une fuite dans l'espace : c'est l'espace lui-même qui s'étire.",
    2, [
    ["Quel âge attribue-t-on à l'univers ?", ["Environ 13,8 milliards d'années", "Environ 4,5 milliards d'années", "Environ 100 milliards d'années", "Environ 1 milliard d'années"], 0,
     "L'estimation vient surtout de l'analyse du fond diffus cosmologique."],
    ["Qu'est-ce que le fond diffus cosmologique ?", ["Le rayonnement fossile émis environ 380 000 ans après le Big Bang", "La lumière des premières étoiles", "Le rayonnement des trous noirs", "La lumière diffusée par les poussières galactiques"], 0,
     "Découvert par hasard en 1964 par Penzias et Wilson, il constitue la preuve la plus forte du modèle du Big Bang."],
    ["Qui observe en 1929 que les galaxies s'éloignent d'autant plus vite qu'elles sont lointaines ?", ["Edwin Hubble", "Albert Einstein", "Fred Hoyle", "Arthur Eddington"], 0,
     "Georges Lemaître avait proposé l'expansion deux ans plus tôt sur des bases théoriques."],
    ["Quel prêtre et physicien belge propose l'idée d'un univers en expansion issu d'un atome primitif ?", ["Georges Lemaître", "Arthur Eddington", "Willem de Sitter", "Fred Hoyle"], 0,
     "L'expression Big Bang est due à Fred Hoyle, qui l'employait par dérision : il défendait un univers stationnaire."],
    ["Qu'est-ce que la matière noire ?", ["Une matière invisible détectée par ses effets gravitationnels", "De la matière très froide", "Les trous noirs de la galaxie", "Un nuage de poussière interstellaire"], 0,
     "Elle explique la vitesse de rotation des galaxies, trop rapide pour la seule matière visible."],
    ["Qu'est-ce que l'énergie noire ?", ["Une composante qui accélère l'expansion de l'univers", "L'énergie des trous noirs", "L'énergie du vide intergalactique connue et mesurée", "Un rayonnement invisible"], 0,
     "Son existence a été déduite en 1998 de l'observation de supernovae lointaines. Sa nature reste inconnue."],
    ["Dans quelle galaxie se trouve le système solaire ?", ["La Voie lactée", "Andromède", "Le Grand Nuage de Magellan", "Le Triangle"], 0,
     "Une galaxie spirale barrée d'environ cent mille années-lumière de diamètre."],
    ["Quelle galaxie majeure est la plus proche de la nôtre ?", ["Andromède", "Le Triangle", "Le Sombrero", "Le Tourbillon"], 0,
     "Située à environ 2,5 millions d'années-lumière, elle se rapproche et fusionnera avec la Voie lactée dans quelques milliards d'années."],
    ["Qu'est-ce qu'un trou noir ?", ["Une région dont rien ne peut s'échapper, pas même la lumière", "Une étoile éteinte", "Un vide dans l'espace", "Un tunnel vers une autre région de l'univers"], 0,
     "La première image d'un environnement de trou noir a été publiée en 2019 par l'Event Horizon Telescope."],
    ["Qu'appelle-t-on horizon des événements ?", ["La frontière au-delà de laquelle rien ne peut revenir", "La limite visible de l'univers", "Le bord d'une galaxie", "La surface d'une étoile à neutrons"], 0,
     "Pour un observateur extérieur, un objet qui la franchit semble ralentir indéfiniment sans jamais la traverser.", 3],
  ]),

  notion("pc-mesures-unites", S, "Mesures, unités et ordres de grandeur",
    "Sept unités de base redéfinies en 2019 par des constantes de la nature, et l'art d'estimer sans calculer.",
    "Depuis 2019, plus aucune unité du Système international ne repose sur un objet matériel.",
    2, [
    ["Combien d'unités de base compte le Système international ?", ["Sept", "Cinq", "Neuf", "Six"], 0,
     "Mètre, kilogramme, seconde, ampère, kelvin, mole et candela."],
    ["Sur quoi le mètre est-il défini aujourd'hui ?", ["Sur la distance parcourue par la lumière en une fraction de seconde", "Sur une barre de platine iridié", "Sur une fraction du méridien terrestre", "Sur la longueur d'onde d'un laser à hélium"], 0,
     "La définition de 1983 fige la vitesse de la lumière et fait du mètre une conséquence de la seconde."],
    ["Quel objet servait de référence au kilogramme jusqu'en 2019 ?", ["Un cylindre de platine iridié conservé à Sèvres", "Un litre d'eau pure", "Un bloc de silicium", "Une sphère de quartz"], 0,
     "Sa masse dérivait légèrement au fil des décennies, ce qui a motivé la redéfinition par la constante de Planck."],
    ["Sur quoi la seconde est-elle définie ?", ["Sur une transition de l'atome de césium 133", "Sur la rotation de la Terre", "Sur la révolution terrestre autour du Soleil", "Sur un pendule étalon"], 0,
     "Neuf milliards cent quatre-vingt-douze millions six cent trente et un mille sept cent soixante-dix périodes de ce rayonnement."],
    ["Que mesure la mole ?", ["Une quantité de matière", "Une masse", "Une concentration", "Un volume de gaz"], 0,
     "Une mole contient exactement 6,022 × 10²³ entités, le nombre d'Avogadro, fixé par définition depuis 2019."],
    ["Que mesure le kelvin ?", ["Une température absolue", "Une quantité de chaleur", "Une différence de température seulement", "Une capacité thermique"], 0,
     "Zéro kelvin est le zéro absolu. Un écart d'un kelvin égale un écart d'un degré Celsius."],
    ["Quel préfixe multiplie une unité par un milliard ?", ["Giga", "Méga", "Téra", "Kilo"], 0,
     "Kilo pour mille, méga pour un million, giga pour un milliard, téra pour mille milliards."],
    ["Que vaut un nanomètre ?", ["Un milliardième de mètre", "Un millionième de mètre", "Un millième de millimètre", "Un dixième de micron"], 0,
     "L'échelle des molécules et des virus. Un cheveu humain fait environ quatre-vingt mille nanomètres d'épaisseur."],
    ["Qu'est-ce qu'une année-lumière ?", ["Une distance", "Une durée", "Une vitesse", "Une unité de temps astronomique"], 0,
     "Environ neuf mille cinq cents milliards de kilomètres : la distance parcourue par la lumière en un an."],
    ["Quelle sonde a été perdue en 1999 à cause d'une confusion d'unités ?", ["Mars Climate Orbiter", "Mars Polar Lander", "Beagle 2", "Phobos 1"], 0,
     "Un logiciel fournissait des livres-force par seconde, l'autre attendait des newtons-seconde. La sonde s'est désintégrée dans l'atmosphère martienne.", 3],
  ]),

  notion("pc-materiaux", S, "Les matériaux et leurs propriétés",
    "Métaux, céramiques, polymères, composites : ce qui rend un matériau dur, souple, conducteur ou léger.",
    "Dur n'est pas résistant : le diamant raye tout mais se brise d'un coup de marteau.",
    2, [
    ["Quel est le matériau naturel le plus dur connu ?", ["Le diamant", "Le corindon", "Le quartz", "Le carbure de tungstène"], 0,
     "Il occupe le rang dix de l'échelle de Mohs. Dur ne signifie pas incassable : il est fragile au choc."],
    ["Qu'est-ce qu'un alliage ?", ["Un mélange d'un métal avec un ou plusieurs autres éléments", "Un métal purifié", "Un métal recouvert d'un autre", "Un composé chimique entre deux métaux uniquement"], 0,
     "Le bronze mêle cuivre et étain, le laiton cuivre et zinc, l'acier fer et carbone."],
    ["Que contient l'acier inoxydable pour résister à la corrosion ?", ["Du chrome", "Du zinc", "De l'étain", "Du nickel seul"], 0,
     "Au moins dix et demi pour cent de chrome, qui forme une couche protectrice invisible d'oxyde."],
    ["Qu'est-ce qu'un matériau composite ?", ["L'association de plusieurs matériaux aux propriétés complémentaires", "Un alliage à trois métaux", "Un plastique renforcé uniquement", "Un matériau recyclé"], 0,
     "Le béton armé associe la résistance en compression du béton et celle en traction de l'acier."],
    ["Pourquoi le verre est-il transparent ?", ["Sa structure désordonnée n'absorbe pas la lumière visible", "Il est très fin", "Il est parfaitement lisse", "Il réfléchit toute la lumière"], 0,
     "Ses électrons ne peuvent absorber les photons visibles, faute de niveaux d'énergie disponibles."],
    ["Qu'est-ce qu'un semi-conducteur ?", ["Un matériau dont la conductivité se situe entre celle des métaux et celle des isolants", "Un métal partiellement oxydé", "Un isolant chauffé", "Un conducteur à basse température"], 0,
     "Le silicium dopé est à la base de tous les transistors et donc de toute l'électronique moderne."],
    ["Qu'est-ce que le graphène ?", ["Un feuillet de carbone d'un seul atome d'épaisseur", "Une forme dense du graphite", "Un polymère de carbone", "Un alliage carbone-silicium"], 0,
     "Isolé en 2004, il est extrêmement résistant et bon conducteur. Geim et Novoselov ont reçu le Nobel en 2010."],
    ["Quel matériau est utilisé pour les gilets pare-balles ?", ["Le kevlar", "Le nylon", "Le téflon", "Le polyéthylène ordinaire"], 0,
     "Fibre aramide inventée en 1965 par Stephanie Kwolek, cinq fois plus résistante que l'acier à masse égale."],
    ["Qu'est-ce qu'un matériau à mémoire de forme ?", ["Un alliage qui retrouve sa forme initiale après chauffage", "Un plastique qui garde la forme donnée", "Un métal très élastique", "Un composite auto-réparant"], 0,
     "Le nitinol, alliage de nickel et de titane, est utilisé en médecine pour les stents."],
    ["Pourquoi le béton doit-il être armé pour porter une poutre ?", ["Il résiste mal à la traction", "Il résiste mal à la compression", "Il se dilate trop", "Il absorbe l'humidité"], 0,
     "Excellent en compression, il se fissure en traction : l'acier reprend cet effort dans la zone tendue.", 3],
  ]),

  notion("pc-nucleaire-radioactivite", S, "Le nucléaire et la radioactivité",
    "Des noyaux instables, trois types de rayonnements, et des applications qui vont de la datation à la médecine.",
    "La radioactivité est un phénomène naturel : le corps humain lui-même est légèrement radioactif.",
    2, [
    ["Qui découvre la radioactivité en 1896 ?", ["Henri Becquerel", "Marie Curie", "Pierre Curie", "Ernest Rutherford"], 0,
     "Une plaque photographique voilée par un sel d'uranium, alors qu'il cherchait un effet de la lumière solaire."],
    ["Quels éléments Marie et Pierre Curie isolent-ils en 1898 ?", ["Le polonium et le radium", "L'uranium et le thorium", "Le radon et l'actinium", "Le plutonium et le neptunium"], 0,
     "Le polonium est nommé en hommage à la Pologne, patrie de Marie Curie."],
    ["Qu'est-ce qu'une période radioactive ou demi-vie ?", ["La durée au bout de laquelle la moitié des noyaux se sont désintégrés", "La durée de vie totale d'un échantillon", "Le temps avant qu'un élément devienne stable", "La durée d'émission d'un rayonnement"], 0,
     "Elle va de fractions de seconde à des milliards d'années selon l'isotope."],
    ["Quel rayonnement est arrêté par une simple feuille de papier ?", ["Le rayonnement alpha", "Le rayonnement bêta", "Le rayonnement gamma", "Les neutrons"], 0,
     "Il est cependant très dangereux en cas d'inhalation ou d'ingestion, car il dépose toute son énergie localement."],
    ["Quel rayonnement exige un blindage de plomb ou de béton épais ?", ["Le rayonnement gamma", "Le rayonnement alpha", "Le rayonnement bêta", "Les rayons cathodiques"], 0,
     "C'est un rayonnement électromagnétique de très haute énergie, très pénétrant."],
    ["Quel gaz radioactif naturel s'accumule dans certaines caves ?", ["Le radon", "Le radium", "Le krypton", "Le tritium"], 0,
     "Issu de la désintégration de l'uranium des roches granitiques, il est la deuxième cause de cancer du poumon après le tabac."],
    ["Quelle unité mesure la dose de rayonnement reçue par un organisme ?", ["Le sievert", "Le becquerel", "Le gray seul", "Le curie"], 0,
     "Le becquerel mesure l'activité d'une source, le gray l'énergie déposée, le sievert son effet biologique."],
    ["Quel combustible les centrales nucléaires françaises utilisent-elles principalement ?", ["L'uranium enrichi", "Le plutonium pur", "Le thorium", "L'uranium naturel"], 0,
     "Enrichi à environ quatre pour cent en uranium 235, contre 0,7 pour cent à l'état naturel."],
    ["En quelle année a eu lieu l'accident de Tchernobyl ?", ["1986", "1979", "1991", "1996"], 0,
     "Le 26 avril, lors d'un essai de sûreté sur le réacteur numéro quatre, en Ukraine soviétique."],
    ["Quel accident nucléaire majeur suit un séisme et un tsunami en 2011 ?", ["Fukushima", "Three Mile Island", "Kychtym", "Windscale"], 0,
     "La perte du refroidissement a entraîné la fusion de trois cœurs. L'accident a conduit plusieurs pays à revoir leur politique énergétique.", 3],
  ]),

  notion("pc-chimie-quotidien", S, "La chimie du quotidien",
    "Savons, plastiques, médicaments, additifs : les réactions qui traversent une journée ordinaire.",
    "Un savon fonctionne parce que sa molécule a une tête qui aime l'eau et une queue qui aime le gras.",
    2, [
    ["Pourquoi le savon lave-t-il ?", ["Ses molécules ont une partie qui aime l'eau et une autre qui aime le gras", "Il dissout les graisses par acidité", "Il désinfecte en tuant les bactéries", "Il abrase les salissures"], 0,
     "Les graisses sont emprisonnées dans des micelles, entraînées par le rinçage."],
    ["Quelle réaction produit le savon à partir d'un corps gras ?", ["La saponification", "L'estérification", "L'hydrolyse acide", "La fermentation"], 0,
     "Un corps gras chauffé avec une base forte donne du savon et de la glycérine."],
    ["Pourquoi le bicarbonate fait-il mousser le vinaigre ?", ["Il libère du dioxyde de carbone en milieu acide", "Il produit de l'oxygène", "Il dissout l'acide en chauffant", "Il forme un savon"], 0,
     "Réaction acide-base classique, utilisée aussi comme levure chimique dans les gâteaux."],
    ["Qu'est-ce qu'un antioxydant alimentaire ?", ["Une substance qui ralentit l'oxydation des aliments", "Un conservateur antibactérien", "Un colorant stabilisé", "Un exhausteur de goût"], 0,
     "L'acide ascorbique, ou vitamine C, est l'un des plus employés. Il empêche notamment le brunissement."],
    ["Pourquoi une pomme coupée brunit-elle ?", ["Une enzyme oxyde ses composés phénoliques au contact de l'air", "Elle perd son eau", "Elle fermente", "Elle absorbe la lumière"], 0,
     "Le jus de citron freine la réaction par son acidité et sa vitamine C."],
    ["Quel gaz gonfle une pâte à pain ?", ["Le dioxyde de carbone", "L'oxygène", "L'azote", "La vapeur d'eau seule"], 0,
     "Produit par la levure qui fermente les sucres de la farine. La vapeur contribue ensuite à la levée au four."],
    ["Quel principe actif se cache derrière l'aspirine ?", ["L'acide acétylsalicylique", "Le paracétamol", "L'ibuprofène", "L'acide ascorbique"], 0,
     "Synthétisé industriellement par Bayer en 1897, il dérive d'une substance de l'écorce de saule connue depuis l'Antiquité."],
    ["Pourquoi ne faut-il jamais mélanger eau de Javel et produit acide ?", ["Le mélange dégage du chlore gazeux toxique", "Il devient inefficace", "Il provoque une explosion", "Il attaque les canalisations"], 0,
     "Le mélange avec l'ammoniaque est également dangereux : il libère des chloramines irritantes."],
    ["Qu'est-ce qu'un plastique thermoplastique ?", ["Un plastique qui ramollit à la chaleur et peut être refondu", "Un plastique résistant à la chaleur", "Un plastique biodégradable", "Un plastique renforcé de fibres"], 0,
     "Il est donc recyclable par fusion, contrairement aux thermodurcissables, qui durcissent définitivement."],
    ["Qu'est-ce qu'un tensioactif ?", ["Une molécule qui abaisse la tension superficielle entre deux liquides", "Un agent qui augmente la viscosité", "Un catalyseur de nettoyage", "Un colorant dispersé"], 0,
     "On en trouve dans les savons, les lessives, les cosmétiques et jusque dans les poumons, où il empêche les alvéoles de se coller.", 3],
  ]),
];
