/**
 * Inventions & Technologie — treize notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Inventions & Technologie";

export const CG_SCIENCES_TECH: SeedSkill[] = [
  notion("st-informatique-fondements", S, "Les fondements de l'informatique",
    "Binaire, algorithmes, machines : d'où vient l'ordinateur et sur quoi il repose.",
    "Un ordinateur ne calcule qu'avec deux états ; toute l'informatique en découle.",
    2, [
    ["Sur quel système de numération l'informatique repose-t-elle ?", ["Le binaire", "Le décimal", "L'hexadécimal", "L'octal"], 0,
     "Deux états électriques suffisent, ce qui rend les circuits fiables. L'hexadécimal n'est qu'une écriture abrégée du binaire."],
    ["Que vaut un octet ?", ["Huit bits", "Huit octets", "Mille bits", "Deux bits"], 0,
     "Un octet peut coder deux cent cinquante-six valeurs différentes."],
    ["Quelle mathématicienne du XIXe siècle écrit ce qui est tenu pour le premier programme ?", ["Ada Lovelace", "Emmy Noether", "Sophie Germain", "Grace Hopper"], 0,
     "Pour la machine analytique de Charles Babbage, jamais construite de son vivant."],
    ["Quel mathématicien britannique formalise en 1936 un modèle théorique de calcul ?", ["Alan Turing", "John von Neumann", "Claude Shannon", "Alonzo Church"], 0,
     "La machine de Turing sert encore à définir ce qui est calculable et ce qui ne l'est pas."],
    ["Quelle architecture d'ordinateur, décrite en 1945, stocke programme et données dans la même mémoire ?", ["L'architecture de von Neumann", "L'architecture Harvard", "L'architecture RISC", "L'architecture client-serveur"], 0,
     "Elle reste le modèle de la quasi-totalité des ordinateurs actuels."],
    ["Qui fonde la théorie de l'information en 1948 ?", ["Claude Shannon", "Norbert Wiener", "Alan Turing", "John Tukey"], 0,
     "Il y définit le bit comme unité de mesure de l'information et fixe les limites de la compression et de la transmission."],
    ["Qu'observe Gordon Moore en 1965, dans ce qu'on appellera la loi de Moore ?", ["Le nombre de transistors d'une puce double environ chaque année", "La vitesse des processeurs double chaque année", "Le coût des composants diminue de moitié tous les ans", "La mémoire double tous les six mois"], 0,
     "Il révisa lui-même le rythme à un doublement tous les deux ans en 1975. Observation empirique devenue objectif industriel, elle est aujourd'hui en fin de course physique."],
    ["Qu'est-ce qu'un compilateur ?", ["Un programme qui traduit un code source en langage machine", "Un éditeur de texte", "Un système d'exploitation", "Un programme de débogage"], 0,
     "Grace Hopper a développé le premier compilateur au début des années 1950."],
    ["Qu'est-ce qu'un système d'exploitation ?", ["Un logiciel qui gère le matériel et fait fonctionner les autres programmes", "Un ensemble de pilotes", "Une interface graphique", "Un langage de programmation"], 0,
     "Il alloue mémoire, processeur et accès aux fichiers entre les programmes en cours."],
    ["Qu'est-ce que la complexité algorithmique ?", ["La mesure des ressources consommées par un algorithme selon la taille des données", "La difficulté à lire un programme", "Le nombre de lignes de code", "Le nombre de fonctions imbriquées"], 0,
     "Elle explique pourquoi certains problèmes restent hors de portée même avec des machines mille fois plus rapides.", 3],
  ]),

  notion("st-internet-reseaux", S, "Internet et les réseaux",
    "Ce qui distingue Internet du Web, comment circulent les données, et qui gouverne le réseau.",
    "Internet est le réseau ; le Web n'est qu'un des services qui circulent dessus.",
    2, [
    ["Quelle différence y a-t-il entre Internet et le Web ?", ["Internet est le réseau, le Web un service qui l'utilise", "Ce sont deux mots pour la même chose", "Le Web est plus ancien", "Internet désigne les sites, le Web les serveurs"], 0,
     "Le courrier électronique et le transfert de fichiers utilisent Internet sans passer par le Web."],
    ["Quel réseau militaire américain est l'ancêtre d'Internet ?", ["ARPANET", "MILNET", "NSFNET", "CYCLADES"], 0,
     "Premiers échanges en 1969 entre quatre universités américaines."],
    ["Qui invente le World Wide Web en 1989 ?", ["Tim Berners-Lee", "Vinton Cerf", "Robert Kahn", "Marc Andreessen"], 0,
     "Au CERN, pour partager la documentation entre chercheurs. Il a renoncé à tout brevet sur son invention."],
    ["Que fait le protocole IP ?", ["Il achemine les paquets de données entre machines identifiées par une adresse", "Il chiffre les communications", "Il compresse les données", "Il gère l'affichage des pages"], 0,
     "TCP se charge de la fiabilité : réassemblage, ordre et retransmission des paquets perdus."],
    ["À quoi sert le système DNS ?", ["À traduire un nom de domaine en adresse IP", "À chiffrer les échanges", "À répartir la charge des serveurs", "À stocker les pages web"], 0,
     "Sans lui, il faudrait retenir des suites de chiffres pour atteindre chaque site."],
    ["Que signifie le s de https ?", ["Que la connexion est chiffrée", "Que le site est sécurisé et vérifié par l'État", "Que le serveur est en France", "Que les données ne sont pas conservées"], 0,
     "Il garantit la confidentialité du transport, pas l'honnêteté du site."],
    ["Qu'est-ce qu'une adresse IP ?", ["Un identifiant numérique attribué à une machine sur le réseau", "Le nom du fournisseur d'accès", "Un identifiant de compte", "Un code de localisation postale"], 0,
     "L'épuisement des adresses IPv4 a conduit au déploiement d'IPv6, qui en offre un nombre pratiquement inépuisable."],
    ["Qu'est-ce que la neutralité du net ?", ["Le principe selon lequel les opérateurs ne doivent pas discriminer les flux", "L'anonymat des utilisateurs", "L'absence de censure d'État", "La gratuité de l'accès"], 0,
     "Elle est inscrite dans le droit européen depuis 2015, et a été abrogée puis discutée aux États-Unis."],
    ["Qu'est-ce qu'un VPN ?", ["Un tunnel chiffré entre un appareil et un serveur distant", "Un antivirus réseau", "Un pare-feu matériel", "Un moteur de recherche anonyme"], 0,
     "Il masque l'adresse IP au site visité mais déplace la confiance vers le fournisseur du service."],
    ["Qu'est-ce que le chiffrement de bout en bout ?", ["Seuls l'expéditeur et le destinataire peuvent lire le message", "Le message est chiffré sur les serveurs", "Le message est effacé après lecture", "Le message est signé numériquement"], 0,
     "Le fournisseur du service lui-même ne peut pas lire le contenu, ce qui alimente un débat récurrent sur l'accès judiciaire.", 3],
  ]),

  notion("st-intelligence-artificielle", S, "L'intelligence artificielle",
    "Ce que recouvre le terme, comment ces systèmes apprennent, et quelles limites ils rencontrent.",
    "Un modèle d'apprentissage n'est pas programmé pour une tâche : il ajuste des paramètres à partir d'exemples.",
    2, [
    ["Quand le terme intelligence artificielle apparaît-il ?", ["En 1956, lors d'une conférence à Dartmouth", "En 1943", "En 1972", "En 1997"], 0,
     "John McCarthy le propose pour désigner le champ de recherche naissant."],
    ["Qu'est-ce que l'apprentissage supervisé ?", ["Un apprentissage à partir d'exemples étiquetés", "Un apprentissage sans données", "Un apprentissage par essais et récompenses", "Un apprentissage contrôlé par un humain en temps réel"], 0,
     "Le modèle ajuste ses paramètres pour réduire l'écart entre sa prédiction et l'étiquette attendue."],
    ["Qu'est-ce que l'apprentissage par renforcement ?", ["Un apprentissage guidé par des récompenses et des pénalités", "Un apprentissage sur données massives", "Un apprentissage par imitation", "Un apprentissage sans modèle"], 0,
     "C'est la méthode employée pour les programmes de jeu, où chaque partie fournit un signal de succès ou d'échec."],
    ["Qu'est-ce qu'un réseau de neurones artificiels ?", ["Un modèle de calcul organisé en couches de fonctions pondérées", "Une simulation biologique du cerveau", "Un circuit électronique dédié", "Un algorithme de recherche"], 0,
     "L'analogie avec le neurone biologique est lointaine : il s'agit d'une somme pondérée suivie d'une fonction non linéaire."],
    ["Quel programme bat le champion du monde d'échecs en 1997 ?", ["Deep Blue", "AlphaZero", "Watson", "Stockfish"], 0,
     "Il reposait sur la force de calcul et des règles écrites par des experts, non sur l'apprentissage."],
    ["Quel programme bat un champion de go en 2016 ?", ["AlphaGo", "Deep Blue", "Watson", "Libratus"], 0,
     "Le go était réputé hors de portée en raison du nombre de configurations possibles."],
    ["Qu'est-ce que le test de Turing ?", ["Une épreuve où une machine tente de se faire passer pour un humain dans une conversation", "Un test de calcul", "Une mesure de la vitesse d'un processeur", "Un test de reconnaissance d'images"], 0,
     "Proposé en 1950, il déplace la question de la pensée vers celle du comportement observable."],
    ["Qu'est-ce qu'un biais algorithmique ?", ["Une discrimination systématique héritée des données ou de la conception", "Une erreur de calcul", "Un défaut matériel", "Un réglage manuel du modèle"], 0,
     "Un système entraîné sur des décisions passées reproduit les inégalités qu'elles contenaient."],
    ["Qu'appelle-t-on hallucination d'un modèle de langage ?", ["La production d'une affirmation plausible mais fausse", "Un plantage du modèle", "Une réponse hors sujet", "Un refus de répondre"], 0,
     "Le modèle optimise la vraisemblance du texte, non sa vérité : rien dans son fonctionnement ne garantit l'exactitude."],
    ["Que prévoit le règlement européen sur l'intelligence artificielle adopté en 2024 ?", ["Un encadrement gradué selon le niveau de risque des usages", "Une interdiction générale des modèles génératifs", "Une taxe sur les systèmes automatisés", "Une obligation de code source ouvert"], 0,
     "Certains usages, comme la notation sociale généralisée, sont interdits ; d'autres sont soumis à des obligations strictes.", 3],
  ]),

  notion("st-transports", S, "Les transports",
    "Machine à vapeur, automobile, aviation, spatial : deux siècles de vitesse.",
    "Le chemin de fer a imposé l'heure unifiée : avant lui, chaque ville vivait à son heure solaire.",
    2, [
    ["Qui met au point une machine à vapeur efficace au XVIIIe siècle ?", ["James Watt", "Denis Papin", "Thomas Newcomen", "Richard Trevithick"], 0,
     "Il perfectionne la machine de Newcomen en séparant le condenseur, ce qui divise la consommation de charbon."],
    ["Quelle innovation le chemin de fer impose-t-il à la mesure du temps ?", ["Une heure unifiée sur un même réseau", "Le passage à l'heure d'été", "Le calendrier grégorien", "Les fuseaux de quinze degrés"], 0,
     "Avant lui, chaque ville réglait ses horloges sur le soleil local, ce qui rendait les horaires impraticables."],
    ["Qui construit le premier véhicule automobile à vapeur en 1769 ?", ["Nicolas-Joseph Cugnot", "Karl Benz", "Gottlieb Daimler", "Étienne Lenoir"], 0,
     "Son fardier à vapeur, conçu pour tracter des canons, est conservé au Musée des arts et métiers."],
    ["Qui dépose en 1886 le brevet de la première automobile à moteur à essence ?", ["Karl Benz", "Henry Ford", "Rudolf Diesel", "Armand Peugeot"], 0,
     "Sa femme Bertha Benz réalisa en 1888 le premier long trajet, de Mannheim à Pforzheim, prouvant la viabilité du véhicule."],
    ["Quelle innovation industrielle Henry Ford généralise-t-il en 1913 ?", ["La chaîne de montage mobile", "La soudure automatique", "L'emboutissage à froid", "Le moteur en ligne"], 0,
     "Le temps d'assemblage d'une voiture passa de douze heures à environ une heure et demie."],
    ["Qui réalise en 1903 le premier vol motorisé contrôlé ?", ["Les frères Wright", "Clément Ader", "Louis Blériot", "Alberto Santos-Dumont"], 0,
     "Clément Ader avait décollé en 1890 mais sans contrôle du vol. Blériot traverse la Manche en 1909."],
    ["Quel avion de ligne supersonique a été exploité de 1976 à 2003 ?", ["Le Concorde", "Le Tupolev Tu-144", "Le Boeing 2707", "Le Caravelle"], 0,
     "Franco-britannique, il reliait Paris à New York en environ trois heures et demie."],
    ["Quel est le premier satellite artificiel mis en orbite ?", ["Spoutnik 1, en 1957", "Explorer 1", "Vanguard 1", "Luna 1"], 0,
     "Son lancement par l'URSS déclenche la course à l'espace et la création de la NASA l'année suivante."],
    ["Qui est le premier homme dans l'espace ?", ["Iouri Gagarine, en 1961", "Alan Shepard", "Neil Armstrong", "Guerman Titov"], 0,
     "Un seul tour de Terre, en cent huit minutes. Valentina Terechkova sera la première femme en 1963."],
    ["Quelle innovation a le plus réduit le coût du transport maritime au XXe siècle ?", ["Le conteneur normalisé", "Le moteur diesel marin", "L'élargissement du canal de Suez", "Le porte-conteneurs à double coque"], 0,
     "Introduit en 1956 par Malcom McLean, il a supprimé la manutention pièce par pièce et transformé le commerce mondial.", 3],
  ]),

  notion("st-energie-technologies", S, "Les technologies de l'énergie",
    "Produire, stocker, transporter : les objets techniques derrière le mot énergie.",
    "Le vrai verrou des renouvelables n'est pas la production mais le stockage.",
    2, [
    ["Comment un alternateur produit-il de l'électricité ?", ["Par induction, un aimant tournant devant des bobines", "Par réaction chimique", "Par effet thermoélectrique", "Par frottement"], 0,
     "La quasi-totalité de l'électricité mondiale est produite ainsi, quelle que soit la source d'énergie qui fait tourner la turbine."],
    ["Comment fonctionne un panneau photovoltaïque ?", ["La lumière libère des électrons dans un semi-conducteur", "La chaleur du soleil dilate un fluide", "Les rayons chauffent une plaque conductrice", "La lumière fait vibrer un cristal"], 0,
     "Le rendement des panneaux commerciaux se situe généralement entre dix-huit et vingt-deux pour cent."],
    ["Quelle différence y a-t-il entre solaire thermique et photovoltaïque ?", ["Le thermique produit de la chaleur, le photovoltaïque de l'électricité", "Le thermique est plus récent", "Le photovoltaïque utilise des miroirs", "Le thermique fonctionne la nuit"], 0,
     "Le solaire à concentration utilise des miroirs pour produire de la vapeur, puis de l'électricité."],
    ["Qu'est-ce qu'une centrale de pompage-turbinage ?", ["Une station qui remonte l'eau pour la turbiner plus tard", "Une centrale au fil de l'eau", "Une centrale marémotrice", "Un barrage de retenue classique"], 0,
     "C'est le principal moyen de stockage d'électricité à grande échelle en service aujourd'hui."],
    ["Comment une batterie lithium-ion stocke-t-elle l'énergie ?", ["Par déplacement d'ions entre deux électrodes", "Par compression d'un gaz", "Par échauffement d'un métal", "Par réaction irréversible"], 0,
     "Le prix Nobel de chimie 2019 a récompensé Goodenough, Whittingham et Yoshino pour son développement."],
    ["Qu'est-ce qu'une pile à combustible ?", ["Un dispositif produisant de l'électricité à partir d'hydrogène et d'oxygène", "Une batterie rechargeable", "Un générateur thermique", "Un condensateur de forte capacité"], 0,
     "Elle ne rejette que de l'eau, mais l'hydrogène doit être produit, ce qui déplace la question de l'origine de l'énergie."],
    ["Comment une éolienne convertit-elle le vent en électricité ?", ["Les pales entraînent un rotor relié à un alternateur", "Le vent comprime un fluide", "Les pales produisent une charge statique", "Le vent chauffe un échangeur"], 0,
     "La puissance récupérable croît avec le cube de la vitesse du vent, d'où l'importance du site."],
    ["Qu'est-ce qu'un réseau électrique intelligent ?", ["Un réseau qui ajuste production et consommation grâce à des échanges d'information", "Un réseau entièrement souterrain", "Un réseau à courant continu", "Un réseau doté de batteries"], 0,
     "Il permet notamment d'effacer temporairement des consommations plutôt que d'augmenter la production."],
    ["Qu'est-ce qu'un compteur communicant ?", ["Un compteur transmettant à distance les données de consommation", "Un compteur à double tarif", "Un compteur mécanique amélioré", "Un compteur individuel de chauffage"], 0,
     "Son déploiement a soulevé des questions de protection des données, la courbe de charge révélant des habitudes de vie."],
    ["Qu'est-ce que l'analyse du cycle de vie d'une technologie énergétique ?", ["Un bilan des impacts de l'extraction au recyclage", "Le calcul de sa durée de fonctionnement", "L'estimation de sa rentabilité", "La mesure de ses émissions en fonctionnement"], 0,
     "Elle seule permet de comparer honnêtement des filières dont les impacts se situent à des étapes différentes.", 3],
  ]),

  notion("st-medecine-technologies", S, "Les technologies médicales",
    "Imagerie, prothèses, biotechnologies : comment la technique a transformé le soin.",
    "L'imagerie a rendu visible l'intérieur du corps sans l'ouvrir : c'est la rupture du XXe siècle en médecine.",
    2, [
    ["Qui découvre les rayons X en 1895 ?", ["Wilhelm Röntgen", "Antoine Becquerel", "Marie Curie", "Paul Langevin"], 0,
     "Il reçoit le premier prix Nobel de physique en 1901. Il refusa de breveter sa découverte."],
    ["Sur quel principe repose l'imagerie par résonance magnétique ?", ["L'alignement des noyaux d'hydrogène dans un champ magnétique intense", "L'absorption de rayons X", "L'émission de positons", "La réflexion d'ultrasons"], 0,
     "Elle n'utilise aucun rayonnement ionisant, ce qui la rend répétable sans dose cumulée."],
    ["Sur quoi repose l'échographie ?", ["La réflexion d'ultrasons par les tissus", "Un champ magnétique", "Des rayons X de faible intensité", "Un traceur radioactif"], 0,
     "Sans danger connu, elle est l'examen de référence pour le suivi de grossesse."],
    ["Qu'est-ce qu'un scanner, ou tomodensitométrie ?", ["Une reconstruction en coupes à partir de multiples radiographies", "Une IRM rapide", "Une échographie tridimensionnelle", "Une imagerie par positons"], 0,
     "Son inventeur Godfrey Hounsfield a reçu le Nobel de médecine en 1979."],
    ["Qu'est-ce qu'un stimulateur cardiaque ?", ["Un appareil implanté qui régule le rythme du cœur par impulsions électriques", "Un défibrillateur externe", "Une valve artificielle", "Une pompe d'assistance"], 0,
     "Le premier modèle implantable date de 1958 ; le patient a survécu plus de quarante ans avec des appareils successifs."],
    ["En quelle année a lieu la première greffe de cœur humain ?", ["1967", "1954", "1975", "1982"], 0,
     "Réalisée par Christiaan Barnard en Afrique du Sud. Le patient survécut dix-huit jours."],
    ["Qu'est-ce que la PCR ?", ["Une technique d'amplification de fragments d'ADN", "Un test immunologique", "Une méthode de séquençage", "Un procédé de culture cellulaire"], 0,
     "Mise au point par Kary Mullis en 1983, elle permet de détecter des quantités infimes de matériel génétique."],
    ["Qu'est-ce qu'un vaccin à ARN messager ?", ["Un vaccin fournissant aux cellules l'instruction de produire un antigène", "Un vaccin à virus atténué", "Un vaccin à protéine recombinante", "Un vaccin à ADN intégré au génome"], 0,
     "L'ARN ne pénètre pas dans le noyau et se dégrade rapidement. Les recherches sur cette technologie ont commencé dans les années 1990."],
    ["Qu'est-ce que la chirurgie assistée par robot ?", ["Une chirurgie où le geste du praticien est transmis à des instruments articulés", "Une opération autonome sans chirurgien", "Une opération programmée à l'avance", "Une chirurgie à distance uniquement"], 0,
     "Elle apporte stabilité et précision dans des espaces réduits, le chirurgien restant l'auteur de chaque mouvement."],
    ["Qu'est-ce que la médecine personnalisée ?", ["Une approche adaptant le traitement aux caractéristiques biologiques du patient", "Un suivi médical individualisé", "La médecine de ville", "Un accompagnement psychologique du soin"], 0,
     "Elle repose largement sur l'analyse génomique des tumeurs pour choisir la thérapie ciblée adaptée.", 3],
  ]),

  notion("st-materiaux-fabrication", S, "Fabriquer : de l'artisanat à l'industrie",
    "Outils, machines-outils, robots, impression 3D : comment on produit des objets.",
    "L'interchangeabilité des pièces, plus que la machine à vapeur, a rendu possible l'industrie moderne.",
    2, [
    ["Qu'est-ce que l'interchangeabilité des pièces ?", ["La possibilité de remplacer une pièce par une autre identique sans ajustement", "La standardisation des matériaux", "L'usage de pièces multifonctions", "L'assemblage sans vis"], 0,
     "Développée pour l'armement au XVIIIe siècle, elle rend possible la réparation et la production en série."],
    ["Qu'est-ce qu'une machine-outil à commande numérique ?", ["Une machine dont les mouvements sont pilotés par un programme", "Une machine électrique automatisée", "Une machine à réglage mécanique", "Un robot d'assemblage"], 0,
     "Elle permet de reproduire une pièce complexe à l'identique, en série ou à l'unité."],
    ["Qu'est-ce que l'impression tridimensionnelle par dépôt de matière ?", ["Une fabrication couche par couche à partir d'un modèle numérique", "Un moulage assisté par ordinateur", "Une gravure au laser", "Un usinage par retrait de matière"], 0,
     "On parle de fabrication additive, par opposition à l'usinage, qui est soustractif."],
    ["Qu'est-ce qu'un robot industriel ?", ["Un manipulateur programmable multi-axes", "Une machine automatique à cycle fixe", "Un véhicule autoguidé", "Un système de contrôle qualité"], 0,
     "La reprogrammabilité le distingue d'un automate dédié à une seule tâche."],
    ["Qu'est-ce que le lean manufacturing ?", ["Une organisation visant à éliminer les gaspillages de production", "Une production à flux poussé", "Une automatisation intégrale", "Une méthode de contrôle qualité statistique"], 0,
     "Issu du système de production Toyota, il repose notamment sur le juste-à-temps et l'amélioration continue."],
    ["Qu'est-ce que le juste-à-temps ?", ["Approvisionner au moment précis du besoin, sans stock tampon", "Livrer les clients dans les délais", "Produire en continu", "Anticiper la demande par des stocks"], 0,
     "Très efficace en régime normal, il rend les chaînes vulnérables à la moindre rupture, comme l'ont montré les crises récentes."],
    ["Qu'est-ce que la norme ISO 9001 ?", ["Une norme de système de management de la qualité", "Une norme de sécurité des produits", "Une norme environnementale", "Une norme de tolérance dimensionnelle"], 0,
     "Elle certifie des processus, non la qualité intrinsèque d'un produit."],
    ["Qu'est-ce que l'obsolescence logicielle d'un appareil ?", ["L'arrêt des mises à jour rendant l'appareil inutilisable ou vulnérable", "L'usure des composants", "La sortie d'un modèle plus performant", "La panne d'une pièce non remplaçable"], 0,
     "La législation européenne impose désormais des durées minimales de disponibilité des mises à jour pour certains produits."],
    ["Qu'est-ce que l'éco-conception ?", ["Concevoir un produit en intégrant ses impacts sur tout son cycle de vie", "Utiliser des matériaux recyclés", "Réduire l'emballage", "Fabriquer localement"], 0,
     "L'essentiel des impacts d'un produit est déterminé dès la conception, avant toute production."],
    ["Qu'est-ce que l'économie circulaire ?", ["Un modèle visant à maintenir les matières en usage le plus longtemps possible", "Le recyclage systématique", "La production locale", "La location plutôt que la vente"], 0,
     "Réemploi, réparation et reconditionnement y priment sur le recyclage, qui reste une perte de valeur.", 3],
  ]),

  notion("st-mathematiques", S, "Les mathématiques",
    "Nombres, démonstrations, grands problèmes : ce que font les mathématiciens.",
    "Une conjecture n'est pas un théorème : elle attend une démonstration, parfois pendant des siècles.",
    2, [
    ["Qu'est-ce qu'un nombre premier ?", ["Un entier supérieur à un divisible seulement par un et par lui-même", "Un nombre impair", "Un nombre sans diviseur", "Le plus petit nombre d'un ensemble"], 0,
     "Euclide a démontré il y a plus de deux mille ans qu'il en existe une infinité."],
    ["Qu'est-ce qu'un nombre irrationnel ?", ["Un nombre qui ne peut s'écrire comme quotient de deux entiers", "Un nombre négatif", "Un nombre imaginaire", "Un nombre infini"], 0,
     "La racine de deux en est le premier exemple découvert, ce qui aurait bouleversé les pythagoriciens."],
    ["Que dit le théorème de Pythagore ?", ["Dans un triangle rectangle, le carré de l'hypoténuse égale la somme des carrés des deux autres côtés", "Les angles d'un triangle font cent quatre-vingts degrés", "Deux triangles semblables ont des côtés proportionnels", "La médiane d'un triangle rectangle vaut la moitié de l'hypoténuse"], 0,
     "Connu des Babyloniens bien avant Pythagore, il doit son nom à l'école qui en aurait donné une démonstration."],
    ["Qu'est-ce que le nombre pi ?", ["Le rapport entre la circonférence d'un cercle et son diamètre", "L'aire d'un cercle de rayon un", "Le rapport entre le rayon et la circonférence", "Un nombre rationnel proche de 3,14"], 0,
     "Il est irrationnel et transcendant, ce qui a été démontré en 1882 par Ferdinand von Lindemann."],
    ["Qu'est-ce que le nombre d'or ?", ["Un rapport égal à environ 1,618, solution d'une équation simple", "Le rapport entre diamètre et circonférence", "Une constante physique", "Le rapport entre deux nombres premiers consécutifs"], 0,
     "Il apparaît dans la suite de Fibonacci, dont le rapport de deux termes consécutifs s'en approche."],
    ["Quel théorème énoncé en 1637 n'a été démontré qu'en 1994 ?", ["Le dernier théorème de Fermat", "La conjecture de Poincaré", "Le théorème des quatre couleurs", "L'hypothèse de Riemann"], 0,
     "Andrew Wiles y consacra sept ans de travail solitaire. Fermat prétendait en détenir une démonstration."],
    ["Quelle conjecture démontrée en 2003 portait sur la topologie de l'espace en trois dimensions ?", ["La conjecture de Poincaré", "La conjecture de Goldbach", "L'hypothèse de Riemann", "La conjecture des nombres premiers jumeaux"], 0,
     "Grigori Perelman l'a démontrée puis a refusé la médaille Fields et le prix d'un million de dollars."],
    ["Qu'est-ce que la médaille Fields ?", ["La plus haute distinction en mathématiques, remise à des chercheurs de moins de quarante ans", "Le Nobel de mathématiques", "Un prix décerné chaque année", "Un prix réservé aux mathématiques appliquées"], 0,
     "Elle est décernée tous les quatre ans, à deux à quatre lauréats."],
    ["Que sont les problèmes du prix du millénaire ?", ["Sept problèmes majeurs dotés chacun d'un million de dollars", "Les questions ouvertes de la géométrie", "Les conjectures de Hilbert", "Les problèmes de calcul non résolus"], 0,
     "Énoncés en 2000 par l'institut Clay. Un seul a été résolu à ce jour, la conjecture de Poincaré."],
    ["Que montrent les théorèmes d'incomplétude de Gödel ?", ["Tout système formel assez riche contient des énoncés vrais indémontrables en son sein", "Toute théorie mathématique est contradictoire", "Aucune démonstration n'est certaine", "Les mathématiques ne peuvent être formalisées"], 0,
     "Publiés en 1931, ils ont mis fin au programme de Hilbert visant à fonder toutes les mathématiques sur un système complet.", 3],
  ]),

  notion("st-statistiques-donnees", S, "Statistiques et données",
    "Moyenne, médiane, sondage, corrélation : lire un chiffre sans se faire abuser.",
    "Une corrélation n'établit jamais une causalité : c'est l'erreur d'interprétation la plus répandue.",
    2, [
    ["Quelle différence y a-t-il entre moyenne et médiane ?", ["La médiane partage la population en deux moitiés, la moyenne dépend des valeurs extrêmes", "La médiane est toujours plus élevée", "La moyenne s'applique aux petits échantillons", "Il n'y a pas de différence pour de grandes populations"], 0,
     "Sur les revenus, la médiane est nettement inférieure à la moyenne, tirée vers le haut par les hauts revenus."],
    ["Qu'est-ce qu'un échantillon représentatif ?", ["Un échantillon dont la structure reflète celle de la population étudiée", "Un échantillon de grande taille", "Un échantillon tiré au hasard uniquement", "Un échantillon volontaire"], 0,
     "La taille compte moins que la méthode : un million de réponses volontaires vaut moins que mille personnes bien tirées."],
    ["Qu'est-ce que la marge d'erreur d'un sondage ?", ["l'intervalle dans lequel se situe probablement la valeur réelle", "L'erreur commise par l'institut", "Le taux de non-réponse", "L'écart entre deux sondages"], 0,
     "Pour mille personnes, elle avoisine trois points : un écart de deux points entre deux candidats n'est pas significatif."],
    ["Pourquoi une corrélation ne prouve-t-elle pas une causalité ?", ["Un facteur tiers peut expliquer les deux variables", "Une corrélation est toujours fortuite", "Les corrélations ne sont pas mesurables", "La causalité est toujours inverse"], 0,
     "Les ventes de glaces et les noyades augmentent ensemble : la chaleur explique les deux."],
    ["Qu'est-ce que l'écart type ?", ["Une mesure de la dispersion des valeurs autour de la moyenne", "La différence entre deux moyennes", "L'écart entre le maximum et le minimum", "La marge d'erreur d'un calcul"], 0,
     "Deux séries de même moyenne peuvent avoir des écarts types très différents, donc des réalités très différentes."],
    ["Qu'est-ce qu'un biais de sélection ?", ["Un biais dû à la façon dont l'échantillon a été constitué", "Une erreur de mesure", "Un biais du chercheur", "Un biais de mémoire des répondants"], 0,
     "Interroger les passants d'une rue commerçante sur leurs achats en donne un exemple immédiat."],
    ["Qu'est-ce que le biais du survivant ?", ["N'observer que les cas ayant subsisté, ce qui fausse les conclusions", "Privilégier les données récentes", "Ignorer les valeurs extrêmes", "Surestimer les cas rares"], 0,
     "Étudier les entreprises qui ont réussi sans regarder celles qui ont échoué conduit à des recettes illusoires."],
    ["Qu'est-ce qu'un indice, en statistique économique ?", ["Une valeur rapportée à une base de référence, souvent cent", "Un pourcentage de variation", "Un classement", "Une moyenne pondérée"], 0,
     "Il permet de comparer des évolutions, non des niveaux absolus."],
    ["Que signifie l'expression « toutes choses égales par ailleurs » ?", ["On isole l'effet d'une variable en neutralisant les autres", "On compare des groupes identiques", "On raisonne sur des moyennes", "On suppose la stabilité du contexte"], 0,
     "C'est une opération statistique, pas une hypothèse sur le monde : les autres variables ne sont pas vraiment constantes."],
    ["Qu'est-ce que l'anonymisation d'un jeu de données ?", ["Un traitement rendant impossible la réidentification des personnes", "La suppression des noms", "Le chiffrement des données", "L'accès restreint aux chercheurs"], 0,
     "Le simple retrait des noms ne suffit pas : le croisement de quelques attributs suffit souvent à réidentifier quelqu'un.", 3],
  ]),

  notion("st-inventions-quotidien", S, "Les inventions du quotidien",
    "Des objets si familiers qu'on oublie qu'ils ont été inventés.",
    "Beaucoup d'inventions quotidiennes ont d'abord servi à autre chose que leur usage actuel.",
    2, [
    ["Qui invente le stylo à bille moderne dans les années 1930 ?", ["László Bíró", "Marcel Bich", "Lewis Waterman", "John Loud"], 0,
     "Journaliste hongrois, il cherchait une encre à séchage rapide. Marcel Bich en fit un objet jetable à bas coût."],
    ["Qui invente le velcro après avoir observé des fruits accrochés au poil de son chien ?", ["Georges de Mestral", "Whitcomb Judson", "Gideon Sundback", "Jacob Rabinow"], 0,
     "L'ingénieur suisse dépose son brevet en 1951. Le nom vient de velours et crochet."],
    ["À quoi le four à micro-ondes doit-il sa découverte en 1945 ?", ["Une barre chocolatée fondue près d'un magnétron de radar", "Un essai de séchage industriel", "Une recherche sur la conservation", "Un accident de laboratoire chimique"], 0,
     "Percy Spencer, ingénieur chez Raytheon, comprit que les micro-ondes chauffaient les aliments."],
    ["Qui met au point à la fin du XIXe siècle le stylo-plume à réservoir fiable ?", ["Lewis Waterman", "László Bíró", "Marcel Bich", "Petrache Poenaru"], 0,
     "Un système de capillarité empêche l'encre de couler d'un coup. Il déposa son brevet en 1884."],
    ["Quelle invention de 1928 est due à une observation de moisissure sur une boîte de Petri ?", ["La pénicilline", "L'aspirine", "L'insuline", "Le vaccin antigrippal"], 0,
     "Alexander Fleming remarqua que les bactéries ne poussaient pas autour de la moisissure."],
    ["Qui invente le braille, système de lecture tactile ?", ["Louis Braille", "Valentin Haüy", "Charles Barbier", "Helen Keller"], 0,
     "Il avait quinze ans et était lui-même aveugle depuis l'âge de trois ans."],
    ["Quelle invention de 1888 permet la photographie amateur de masse ?", ["L'appareil Kodak à pellicule souple", "La plaque au gélatino-bromure", "L'appareil reflex", "Le flash au magnésium"], 0,
     "George Eastman vendait l'appareil chargé : le client renvoyait le tout pour développement."],
    ["Quel objet Chester Carlson met-il au point en 1938 ?", ["La photocopie électrostatique", "L'imprimante matricielle", "Le télécopieur", "Le duplicateur à alcool"], 0,
     "Il lui fallut plus de dix ans pour convaincre un industriel ; le procédé donna naissance à Xerox."],
    ["Quelle invention de 1958 est à l'origine de toute l'électronique moderne ?", ["Le circuit intégré", "Le transistor", "Le microprocesseur", "La diode"], 0,
     "Jack Kilby et Robert Noyce y parviennent indépendamment. Le transistor date de 1947, le microprocesseur de 1971."],
    ["Quelle invention accidentelle de 1968 est à l'origine des notes repositionnables ?", ["Une colle trop faible mise au point chez 3M", "Un papier mal encollé", "Un adhésif thermique raté", "Un vernis de reliure"], 0,
     "Spencer Silver cherchait une colle très résistante. Il fallut six ans pour qu'un collègue trouve un usage à son échec.", 3],
  ]),

  notion("st-espace-exploration", S, "L'exploration spatiale",
    "Des premiers satellites aux sondes interstellaires : ce qui a été fait et par qui.",
    "Aucune sonde n'a quitté le système solaire au sens gravitationnel : la plus lointaine n'est sortie que de l'héliosphère.",
    2, [
    ["Quelle mission dépose les premiers hommes sur la Lune en 1969 ?", ["Apollo 11", "Apollo 8", "Apollo 13", "Gemini 12"], 0,
     "Neil Armstrong et Buzz Aldrin y marchèrent ; Michael Collins resta en orbite."],
    ["Combien de missions Apollo ont posé des hommes sur la Lune ?", ["Six", "Trois", "Neuf", "Une"], 0,
     "Apollo 11, 12, 14, 15, 16 et 17. Apollo 13 dut renoncer après une explosion à bord."],
    ["Quelle station spatiale internationale est occupée en continu depuis 2000 ?", ["l'ISS", "Mir", "Skylab", "Tiangong"], 0,
     "Elle orbite à environ quatre cents kilomètres et fait le tour de la Terre en quatre-vingt-dix minutes."],
    ["Quelle sonde lancée en 1977 est l'objet humain le plus éloigné de la Terre ?", ["Voyager 1", "Pioneer 10", "New Horizons", "Voyager 2"], 0,
     "Elle a franchi l'héliopause en 2012 et transmet encore des données plus de quarante ans après son lancement."],
    ["Quel télescope spatial lancé en 1990 a transformé l'astronomie ?", ["Hubble", "James Webb", "Kepler", "Spitzer"], 0,
     "Un défaut de son miroir principal a dû être corrigé lors d'une mission de maintenance en 1993."],
    ["Quel télescope spatial lancé en 2021 observe principalement dans l'infrarouge ?", ["James Webb", "Hubble", "Gaia", "Planck"], 0,
     "Placé à un million et demi de kilomètres de la Terre, il est trop loin pour toute réparation humaine."],
    ["Quelle agence spatiale européenne coordonne les programmes du continent ?", ["l'ESA", "le CNES seul", "Eumetsat", "Arianespace"], 0,
     "Fondée en 1975, elle réunit vingt-deux États membres. Le CNES est l'agence française."],
    ["Quel lanceur européen décolle depuis Kourou, en Guyane ?", ["Ariane", "Soyouz seul", "Vega seul", "Falcon"], 0,
     "La proximité de l'équateur permet de profiter au maximum de la vitesse de rotation terrestre."],
    ["Quelle mission a posé un atterrisseur sur une comète en 2014 ?", ["Rosetta, avec le module Philae", "Cassini-Huygens", "Deep Impact", "Stardust"], 0,
     "Après dix ans de voyage. Philae rebondit et se posa dans une zone mal éclairée, écourtant sa mission."],
    ["Qu'est-ce que le syndrome de Kessler ?", ["Une réaction en chaîne de collisions de débris en orbite", "L'usure des satellites par les rayonnements", "La saturation des fréquences radio", "La perte de contrôle des satellites"], 0,
     "Décrit en 1978, il décrirait un scénario où certaines orbites deviendraient inutilisables pour des générations.", 3],
  ]),

  notion("st-securite-numerique", S, "La sécurité informatique",
    "Menaces, mots de passe, chiffrement : ce qui protège et ce qui expose.",
    "La faille la plus fréquente n'est pas technique : c'est l'humain qu'on trompe.",
    2, [
    ["Qu'est-ce que l'hameçonnage ?", ["Une tentative d'obtenir des informations en se faisant passer pour un tiers de confiance", "Une infection par pièce jointe", "Un vol de mot de passe par force brute", "Une interception de connexion"], 0,
     "Il exploite la confiance et l'urgence plutôt qu'une faille logicielle."],
    ["Qu'est-ce qu'un rançongiciel ?", ["Un logiciel qui chiffre les données et exige un paiement", "Un logiciel espion", "Un virus destructeur", "Un cheval de Troie bancaire"], 0,
     "Payer ne garantit pas la restitution des données et alimente l'activité criminelle."],
    ["Qu'est-ce que l'authentification à deux facteurs ?", ["Une vérification combinant deux éléments de nature différente", "Deux mots de passe successifs", "Une double connexion", "Un mot de passe et une question secrète"], 0,
     "Quelque chose que l'on sait, que l'on possède ou que l'on est : c'est la combinaison qui fait la sécurité."],
    ["Qu'est-ce qui rend un mot de passe robuste ?", ["Sa longueur et son imprévisibilité", "La présence de caractères spéciaux uniquement", "Son renouvellement fréquent", "Sa complexité visuelle"], 0,
     "Une longue phrase de passe résiste mieux qu'un mot court truffé de symboles."],
    ["Qu'est-ce qu'un gestionnaire de mots de passe ?", ["Un coffre chiffré qui stocke et génère des mots de passe uniques", "Un service de récupération de comptes", "Un navigateur sécurisé", "Un outil de vérification de fuites"], 0,
     "Il résout le vrai problème : réutiliser un même mot de passe expose tous les comptes à la fuite d'un seul site."],
    ["Qu'est-ce qu'une faille dite zero-day ?", ["Une vulnérabilité exploitée avant qu'un correctif n'existe", "Une faille non corrigée depuis un an", "Une faille dans un logiciel obsolète", "Une erreur de configuration"], 0,
     "Le nom vient du délai laissé à l'éditeur pour réagir : zéro jour."],
    ["Qu'est-ce qu'une attaque par déni de service ?", ["Une saturation volontaire d'un service pour le rendre indisponible", "Un vol de données massif", "Un blocage de compte utilisateur", "Une suppression de fichiers"], 0,
     "Distribuée, elle mobilise des milliers de machines compromises, souvent des objets connectés mal protégés."],
    ["Qu'est-ce que le chiffrement asymétrique ?", ["Un système à deux clés, l'une publique, l'autre privée", "Un chiffrement à clé unique", "Un chiffrement à longueur variable", "Un chiffrement par blocs"], 0,
     "Il permet de chiffrer sans avoir échangé de secret au préalable, et fonde la signature électronique."],
    ["Qu'est-ce qu'une signature électronique ?", ["Un procédé cryptographique garantissant l'origine et l'intégrité d'un document", "Une image de signature manuscrite", "Un code d'identification", "Un horodatage"], 0,
     "Le règlement européen eIDAS lui donne, sous conditions, la même valeur juridique qu'une signature manuscrite."],
    ["Quelle autorité française accompagne la sécurité des systèmes d'information de l'État ?", ["l'ANSSI", "La CNIL", "l'Arcom", "La DGSI"], 0,
     "Créée en 2009, elle publie des recommandations, qualifie des produits et intervient sur les incidents majeurs.", 3],
  ]),

  notion("st-histoire-sciences", S, "Grandes figures et méthode scientifique",
    "Comment se construit un savoir scientifique, et qui l'a fait avancer.",
    "Une théorie scientifique doit pouvoir être réfutée : c'est ce qui la distingue d'une croyance.",
    2, [
    ["Qu'est-ce que la réfutabilité selon Karl Popper ?", ["Le fait qu'une théorie puisse être contredite par une observation", "La possibilité de démontrer une théorie", "La capacité à convaincre les pairs", "La reproductibilité d'une expérience"], 0,
     "Une théorie compatible avec toute observation possible n'apprend rien : elle n'est pas scientifique en ce sens."],
    ["Qu'est-ce que la relecture par les pairs ?", ["l'examen d'un article par des chercheurs du domaine avant publication", "La validation par un comité éthique", "La reproduction d'une expérience", "La citation par d'autres chercheurs"], 0,
     "Elle filtre sans garantir : des articles erronés passent, d'autres valables sont rejetés."],
    ["Qu'est-ce que la crise de la reproductibilité ?", ["Le constat qu'une part importante d'études publiées ne se reproduit pas", "Le manque de financements pour répéter les expériences", "L'impossibilité de publier des réplications", "La perte des données de recherche"], 0,
     "Elle a été particulièrement documentée en psychologie et en biomédecine depuis les années 2010."],
    ["Qu'est-ce qu'un essai clinique en double aveugle ?", ["Ni le patient ni le soignant ne savent qui reçoit le traitement", "Le patient ignore le traitement reçu", "Deux groupes sont comparés", "Les résultats sont analysés à l'aveugle"], 0,
     "Il élimine les attentes des deux côtés, qui influencent les résultats mesurés."],
    ["Qu'est-ce que l'effet placebo ?", ["Une amélioration due à l'attente du patient plutôt qu'au traitement", "Une absence d'effet", "Un effet secondaire imprévu", "Une réaction allergique psychosomatique"], 0,
     "Il est réel et mesurable, ce qui oblige tout essai sérieux à s'en prémunir par un groupe témoin."],
    ["Qui formule la méthode expérimentale en médecine dans un ouvrage de 1865 ?", ["Claude Bernard", "Louis Pasteur", "Xavier Bichat", "Rudolf Virchow"], 0,
     "Son Introduction à l'étude de la médecine expérimentale reste un texte de référence sur la démarche scientifique."],
    ["Quel astronome est condamné en 1633 pour avoir défendu l'héliocentrisme ?", ["Galilée", "Copernic", "Kepler", "Giordano Bruno"], 0,
     "Copernic était mort en 1543 l'année de la publication de son livre. Bruno fut brûlé en 1600 pour d'autres motifs également."],
    ["Quelle femme reçoit deux prix Nobel dans deux disciplines différentes ?", ["Marie Curie", "Dorothy Hodgkin", "Irène Joliot-Curie", "Lise Meitner"], 0,
     "Physique en 1903 et chimie en 1911. Elle reste la seule femme dans ce cas."],
    ["Qui découvre la structure de l'ADN grâce à des clichés de diffraction dont la contribution fut longtemps minorée ?", ["Rosalind Franklin", "Barbara McClintock", "Lise Meitner", "Jocelyn Bell"], 0,
     "Son cliché 51 fut montré à Watson sans son accord. Morte en 1958, elle ne pouvait plus recevoir le Nobel de 1962."],
    ["Qu'est-ce que le principe de précaution en droit français ?", ["Prendre des mesures proportionnées face à un risque incertain mais grave", "Interdire toute activité risquée", "Attendre la certitude scientifique avant d'agir", "Appliquer la mesure la plus stricte possible"], 0,
     "Inscrit dans la Charte de l'environnement de 2004, il impose d'agir malgré l'incertitude, non de s'abstenir.", 3],
  ]),
];
