/**
 * Sciences de la vie & Terre, troisième lot — vingt notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Sciences de la vie & Terre";

export const CG_SCIENCES_VIE_3: SeedSkill[] = [
  notion("sv3-insectes", S, "Les insectes",
    "Le groupe animal le plus divers de la planète.",
    "Un insecte adulte se reconnaît à ses six pattes et à son corps en trois parties.",
    2, [
    ["Combien de pattes un insecte adulte possède-t-il ?", ["Six", "Huit", "Quatre", "Dix"], 0,
     "Les araignées, avec huit pattes, ne sont pas des insectes mais des arachnides."],
    ["En combien de parties le corps d'un insecte se divise-t-il ?", ["Trois : tête, thorax et abdomen", "Deux", "Quatre", "Une seule"], 0,
     "Les arachnides n'en ont que deux, tête et thorax étant fusionnés."],
    ["Qu'est-ce que la métamorphose complète chez un insecte ?", ["Un développement passant par un stade nymphal", "Une croissance continue", "Une succession de mues sans changement de forme", "Un changement de couleur"], 0,
     "Œuf, larve, nymphe, adulte : le papillon en est l'exemple type."],
    ["Comment respirent les insectes ?", ["Par un réseau de trachées débouchant sur des orifices", "Par des poumons", "Par la peau", "Par des branchies"], 0,
     "Ce système limite leur taille : il ne fonctionne pas efficacement à grande échelle."],
    ["Quel groupe d'insectes est le plus riche en espèces ?", ["Les coléoptères", "Les papillons", "Les hyménoptères", "Les diptères"], 0,
     "Environ quatre cent mille espèces décrites, soit près d'un quart de toutes les espèces animales connues."],
    ["Qu'est-ce qu'une société d'insectes eusociaux ?", ["Une colonie avec division du travail et castes reproductrices", "Un groupe d'insectes vivant ensemble", "Une colonie saisonnière", "Un essaim temporaire"], 0,
     "Fourmis, termites et certaines abeilles et guêpes présentent cette organisation."],
    ["Comment une abeille indique-t-elle la position d'une source de nourriture ?", ["Par une danse codant direction et distance", "Par des phéromones seules", "Par un vol de guidage", "Par des sons"], 0,
     "L'angle de la danse par rapport à la verticale code l'angle par rapport au soleil."],
    ["Qu'est-ce que le syndrome d'effondrement des colonies d'abeilles ?", ["Une disparition massive d'ouvrières aux causes multiples", "Une maladie virale unique", "Un empoisonnement direct", "Un phénomène migratoire"], 0,
     "Pesticides, parasites, monoculture et pathogènes y jouent un rôle combiné."],
    ["Quel parasite affaiblit gravement les colonies d'abeilles ?", ["Le varroa", "Le frelon asiatique", "La teigne de la cire", "La nosémose seule"], 0,
     "Cet acarien affaiblit les abeilles et transmet des virus."],
    ["Quelle tendance les études documentent-elles sur les populations d'insectes ?", ["Un déclin marqué de la biomasse dans plusieurs régions", "Une stabilité générale", "Une augmentation", "Une évolution inconnue"], 0,
     "Une étude allemande de 2017 a mesuré une baisse de plus de soixante-quinze pour cent en trente ans sur des sites protégés.", 3],
  ]),

  notion("sv3-oiseaux", S, "Le monde des oiseaux",
    "Vol, migration, chant, diversité.",
    "Les oiseaux sont les seuls dinosaures encore vivants.",
    2, [
    ["Quelle adaptation permet le vol chez les oiseaux ?", ["Des os creux, des plumes et un métabolisme élevé", "Des ailes membraneuses", "Une musculature légère seule", "Un système respiratoire simple"], 0,
     "Leur système respiratoire à sacs aériens est bien plus efficace que celui des mammifères."],
    ["Combien d'espèces d'oiseaux compte-t-on environ dans le monde ?", ["Environ onze mille", "Environ deux mille", "Environ cinquante mille", "Environ cinq cents"], 0,
     "Le nombre évolue avec la révision de la classification par la génétique."],
    ["Quel est le plus grand oiseau vivant ?", ["l'autruche", "L'albatros", "Le condor", "L'émeu"], 0,
     "L'albatros hurleur détient en revanche le record d'envergure, plus de trois mètres."],
    ["Quel oiseau effectue la plus longue migration connue ?", ["La sterne arctique", "L'hirondelle", "La cigogne", "Le martinet"], 0,
     "Un aller-retour annuel entre les deux pôles, soit des dizaines de milliers de kilomètres."],
    ["Comment les oiseaux migrateurs s'orientent-ils la nuit ?", ["Notamment grâce aux étoiles et au champ magnétique", "Par la seule mémoire", "Par l'odorat", "En suivant les reliefs"], 0,
     "Des expériences en planétarium ont démontré leur usage des constellations."],
    ["Qu'est-ce que le chant chez les oiseaux ?", ["Un signal complexe servant à défendre un territoire et attirer un partenaire", "Un simple cri de communication", "Un signal d'alarme", "Un comportement de jeu"], 0,
     "Il est souvent appris, avec des dialectes locaux dans certaines espèces."],
    ["Quel organe permet aux oiseaux de chanter ?", ["Le syrinx", "Le larynx", "La trachée seule", "Le bec"], 0,
     "Situé à la base de la trachée, il permet parfois d'émettre deux sons simultanément."],
    ["Qu'est-ce qu'un oiseau nidifuge ?", ["Un oisillon capable de quitter le nid peu après l'éclosion", "Un oiseau qui ne fait pas de nid", "Un oiseau migrateur", "Un oiseau abandonnant sa couvée"], 0,
     "Les canetons en sont un exemple ; les passereaux sont au contraire nidicoles."],
    ["Quelle est la principale cause de déclin des oiseaux communs en Europe ?", ["La transformation des milieux agricoles", "La chasse", "Le changement climatique seul", "Les prédateurs domestiques"], 0,
     "Les oiseaux des milieux agricoles ont perdu environ un tiers de leurs effectifs en trente ans."],
    ["Qu'est-ce que le suivi temporel des oiseaux communs ?", ["Un programme de sciences participatives mesurant l'évolution des populations", "Un recensement des espèces rares", "Un comptage des migrateurs", "Un suivi des oiseaux bagués"], 0,
     "Il repose sur des milliers d'observateurs bénévoles formés, coordonnés par le Muséum.", 3],
  ]),

  notion("sv3-mammiferes", S, "Les mammifères",
    "Caractéristiques, groupes, adaptations.",
    "Le trait commun à tous les mammifères est l'allaitement des jeunes.",
    2, [
    ["Quel caractère définit les mammifères ?", ["Les glandes mammaires produisant du lait", "Les poils seuls", "La respiration pulmonaire", "La chaleur corporelle constante"], 0,
     "Poils, oreille moyenne à trois osselets et néocortex développé s'y ajoutent."],
    ["Quels mammifères pondent des œufs ?", ["Les monotrèmes, comme l'ornithorynque", "Les marsupiaux", "Les insectivores", "Aucun"], 0,
     "L'ornithorynque et les échidnés sont les seuls survivants de ce groupe très ancien."],
    ["Qu'est-ce qu'un marsupial ?", ["Un mammifère dont le jeune achève son développement dans une poche", "Un mammifère australien", "Un mammifère sans placenta du tout", "Un mammifère nocturne"], 0,
     "Kangourous, koalas et opossums en font partie."],
    ["Quel est le plus grand mammifère terrestre ?", ["l'éléphant d'Afrique", "Le rhinocéros blanc", "l'hippopotame", "La girafe"], 0,
     "Jusqu'à six ou sept tonnes pour les plus grands mâles."],
    ["Comment les chauves-souris se repèrent-elles dans l'obscurité ?", ["Par écholocalisation", "Par vision infrarouge", "Par l'odorat", "Par magnétoréception"], 0,
     "Elles émettent des ultrasons et analysent leur écho pour cartographier leur environnement."],
    ["Qu'est-ce que l'hibernation ?", ["Un ralentissement profond du métabolisme pendant l'hiver", "Un sommeil prolongé", "Une réduction d'activité saisonnière", "Une migration hivernale"], 0,
     "La marmotte peut y réduire son rythme cardiaque à quelques battements par minute."],
    ["Quel groupe de mammifères est retourné vivre entièrement dans l'eau ?", ["Les cétacés", "Les pinnipèdes", "Les siréniens seuls", "Les loutres"], 0,
     "Baleines et dauphins descendent d'ancêtres terrestres, proches des hippopotames actuels."],
    ["Qu'est-ce qu'un primate ?", ["Un mammifère à mains préhensiles et vision binoculaire développée", "Un singe uniquement", "Un mammifère arboricole", "Un mammifère à gros cerveau"], 0,
     "L'ordre inclut lémuriens, singes et humains."],
    ["Quel mammifère est le plus menacé en France métropolitaine ?", ["Le vison d'Europe, parmi les plus critiques", "Le loup", "Le lynx", "L'ours brun"], 0,
     "L'ours des Pyrénées et le vison d'Europe figurent parmi les populations les plus réduites.", 3],
  ]),

  notion("sv3-adn-technologies", S, "Les technologies de l'ADN",
    "Séquencer, modifier, identifier.",
    "L'analyse génétique a transformé la médecine, la justice et l'histoire.",
    2, [
    ["Qu'est-ce que l'empreinte génétique ?", ["Un profil individuel établi à partir de régions variables de l'ADN", "Une séquence complète du génome", "Un test de paternité seul", "Une analyse chromosomique"], 0,
     "Mise au point en 1984, elle a révolutionné l'enquête criminelle."],
    ["Qu'est-ce qu'un test génétique de filiation ?", ["Une comparaison de marqueurs entre individus", "Un séquençage complet", "Une analyse sanguine", "Un test immunologique"], 0,
     "En France, il n'est légal que sur décision judiciaire."],
    ["Qu'est-ce que l'ADN mitochondrial ?", ["Un ADN transmis uniquement par la mère", "Un ADN nucléaire", "Un ADN du père", "Un ADN bactérien"], 0,
     "Il permet de retracer des lignées maternelles sur des milliers de générations."],
    ["Qu'est-ce que le chromosome Y en généalogie génétique ?", ["Un marqueur de lignée paternelle", "Un marqueur maternel", "Un chromosome mixte", "Un chromosome sans information généalogique"], 0,
     "Il se transmet de père en fils avec peu de recombinaison."],
    ["Qu'est-ce que l'ADN ancien ?", ["De l'ADN extrait de restes archéologiques ou fossiles", "Un ADN dégradé de laboratoire", "Un ADN de référence", "Un ADN de populations anciennes vivantes"], 0,
     "Svante Pääbo a reçu le Nobel de médecine 2022 pour ses travaux sur les génomes d'hominidés éteints."],
    ["Qu'est-ce que l'ADN environnemental ?", ["De l'ADN prélevé dans l'eau ou le sol pour détecter des espèces", "Un ADN modifié par l'environnement", "Un ADN de plantes", "Un ADN altéré par la pollution"], 0,
     "Un échantillon d'eau permet de recenser les poissons d'une rivière sans en capturer un seul."],
    ["Qu'est-ce que le génie génétique ?", ["La modification ciblée du matériel génétique d'un organisme", "La sélection de variétés", "L'hybridation contrôlée", "L'analyse du génome"], 0,
     "Il se distingue de la sélection classique par l'intervention directe sur l'ADN."],
    ["Qu'est-ce que la thérapie génique somatique ?", ["Une modification génétique limitée aux cellules du patient, non transmissible", "Une modification héréditaire", "Une greffe de cellules souches", "Un traitement hormonal ciblé"], 0,
     "La modification germinale, transmissible aux descendants, est interdite dans la plupart des pays."],
    ["Qu'est-ce qu'un organisme génétiquement modifié ?", ["Un organisme dont le génome a été modifié par génie génétique", "Un hybride", "Une variété sélectionnée", "Un organisme irradié"], 0,
     "Le statut juridique des organismes issus des nouvelles techniques d'édition reste débattu."],
    ["Quelle question éthique l'édition du génome humain soulève-t-elle ?", ["La modification transmissible aux générations futures", "Le coût des traitements seul", "La disponibilité des techniques", "La brevetabilité des gènes uniquement"], 0,
     "L'annonce en 2018 de bébés modifiés en Chine a provoqué une condamnation internationale.", 3],
  ]),

  notion("sv3-immunologie-avancee", S, "Vaccins et immunité",
    "Types de vaccins, couverture, controverses.",
    "Il existe plusieurs technologies vaccinales, qui ne protègent pas de la même manière.",
    2, [
    ["Qu'est-ce qu'un vaccin vivant atténué ?", ["Un vaccin utilisant un agent affaibli mais vivant", "Un vaccin à agent tué", "Un vaccin à fragment", "Un vaccin à ARN"], 0,
     "Le vaccin contre la rougeole en est un exemple. Il est déconseillé aux personnes immunodéprimées."],
    ["Qu'est-ce qu'un vaccin inactivé ?", ["Un vaccin contenant un agent tué", "Un vaccin à agent vivant affaibli", "Un vaccin à protéine recombinante", "Un vaccin à vecteur viral"], 0,
     "Souvent moins immunogène, il nécessite fréquemment des rappels."],
    ["Qu'est-ce qu'un adjuvant vaccinal ?", ["Une substance renforçant la réponse immunitaire au vaccin", "Un conservateur", "Un stabilisant", "Un solvant"], 0,
     "Les sels d'aluminium en sont les plus utilisés, et les plus discutés dans le débat public."],
    ["Qu'est-ce qu'un vaccin à vecteur viral ?", ["Un vaccin utilisant un virus modifié pour transporter une information génétique", "Un vaccin à virus complet", "Un vaccin à ARN nu", "Un vaccin à protéine"], 0,
     "Le virus vecteur est rendu incapable de se répliquer."],
    ["Combien de vaccins sont obligatoires pour les nourrissons en France depuis 2018 ?", ["Onze", "Trois", "Huit", "Quinze"], 0,
     "Trois étaient obligatoires auparavant, huit autres recommandés ont été rendus obligatoires."],
    ["Pourquoi le seuil d'immunité collective varie-t-il d'une maladie à l'autre ?", ["Il dépend de la contagiosité de l'agent infectieux", "Il dépend de la gravité de la maladie", "Il dépend du type de vaccin", "Il est fixé par les autorités sanitaires"], 0,
     "Environ quatre-vingt-quinze pour cent pour la rougeole, très contagieuse ; nettement moins pour d'autres maladies."],
    ["Qu'est-ce que la pharmacovigilance vaccinale ?", ["Le suivi des effets indésirables après commercialisation", "Le contrôle qualité des lots", "Les essais cliniques", "La surveillance des stocks"], 0,
     "Elle permet de détecter des effets rares invisibles lors des essais."],
    ["Qu'est-ce que la balance bénéfice-risque d'un vaccin ?", ["La comparaison entre les risques évités et les effets indésirables encourus", "Le rapport coût-efficacité", "Le taux d'efficacité", "Le nombre de doses nécessaires"], 0,
     "Elle varie selon l'âge, l'état de santé et la situation épidémiologique."],
    ["Qu'est-ce que l'hésitation vaccinale ?", ["Un retard ou un refus de vaccination malgré la disponibilité des vaccins", "Un refus total de la médecine", "Une contre-indication médicale", "Une méconnaissance des vaccins"], 0,
     "L'OMS l'a classée parmi les dix principales menaces pour la santé mondiale en 2019."],
    ["Quelle maladie a été presque éradiquée par la vaccination ?", ["La poliomyélite", "La grippe", "La tuberculose", "Le paludisme"], 0,
     "Le nombre de cas a chuté de plus de quatre-vingt-dix-neuf pour cent depuis 1988.", 3],
  ]),

  notion("sv3-cerveau-troubles", S, "Le cerveau et ses troubles",
    "Maladies neurologiques et psychiatriques.",
    "Les troubles psychiatriques et neurologiques relèvent d'approches et de spécialités distinctes.",
    2, [
    ["Qu'est-ce que la maladie d'Alzheimer ?", ["Une maladie neurodégénérative provoquant une perte progressive de mémoire et d'autonomie", "Un vieillissement normal", "Une maladie psychiatrique", "Une maladie vasculaire cérébrale"], 0,
     "Plaques amyloïdes et dégénérescence neurofibrillaire en sont les marqueurs caractéristiques."],
    ["Qu'est-ce que la maladie de Parkinson ?", ["Une dégénérescence de neurones producteurs de dopamine", "Un trouble musculaire", "Une maladie auto-immune", "Un trouble vasculaire"], 0,
     "Tremblement de repos, lenteur et rigidité en sont les signes principaux."],
    ["Qu'est-ce que l'épilepsie ?", ["Une décharge électrique anormale et synchronisée de neurones", "Une maladie psychiatrique", "Un trouble musculaire", "Une carence métabolique"], 0,
     "Toutes les crises ne se traduisent pas par des convulsions."],
    ["Qu'est-ce que la sclérose en plaques ?", ["Une maladie auto-immune détruisant la gaine de myéline", "Une dégénérescence neuronale", "Une maladie vasculaire", "Une infection du système nerveux"], 0,
     "Elle évolue souvent par poussées, avec des symptômes très variables selon la localisation des lésions."],
    ["Qu'est-ce que la dépression au sens clinique ?", ["Un trouble caractérisé par une humeur basse durable et une perte d'élan", "Une tristesse passagère", "Un épuisement physique", "Un trouble de la personnalité"], 0,
     "Elle touche plusieurs centaines de millions de personnes dans le monde."],
    ["Qu'est-ce qu'un trouble bipolaire ?", ["Une alternance d'épisodes dépressifs et d'épisodes maniaques", "Une double personnalité", "Un trouble anxieux", "Une instabilité émotionnelle passagère"], 0,
     "Le diagnostic est souvent posé avec plusieurs années de retard."],
    ["Qu'est-ce que la schizophrénie ?", ["Un trouble psychotique affectant la perception et la pensée", "Un dédoublement de personnalité", "Un trouble de l'humeur", "Une déficience intellectuelle"], 0,
     "La confusion courante avec le trouble dissociatif de l'identité est un contresens fréquent."],
    ["Qu'est-ce qu'un trouble du spectre de l'autisme ?", ["Un trouble du neurodéveloppement affectant communication et interactions", "Une maladie psychiatrique acquise", "Un trouble de l'attachement", "Une déficience intellectuelle"], 0,
     "Le terme spectre traduit une très grande variabilité des situations."],
    ["Qu'est-ce que la neuroplasticité en rééducation ?", ["La capacité du cerveau à réorganiser ses connexions après une lésion", "La régénération des neurones détruits", "La compensation par un autre organe", "Un processus limité à l'enfance"], 0,
     "Elle fonde les protocoles de rééducation après un accident vasculaire cérébral."],
    ["Qu'est-ce que la stimulation cérébrale profonde ?", ["Une technique implantant des électrodes pour moduler une activité cérébrale", "Une stimulation magnétique externe", "Un traitement médicamenteux ciblé", "Une chirurgie de destruction"], 0,
     "Elle a transformé la prise en charge de certaines formes de la maladie de Parkinson.", 3],
  ]),

  notion("sv3-hormones-reproduction", S, "Endocrinologie et développement",
    "Puberté, croissance, régulations hormonales.",
    "Les hormones agissent à des concentrations extrêmement faibles.",
    2, [
    ["Quelle hormone déclenche la croissance pendant l'enfance ?", ["l'hormone de croissance sécrétée par l'hypophyse", "La testostérone seule", "La thyroxine", "L'insuline"], 0,
     "Son déficit provoque un retard statural, traité par injections depuis les années 1950."],
    ["Qu'est-ce que la puberté sur le plan hormonal ?", ["Une réactivation de l'axe hypothalamo-hypophysaire commandant les gonades", "Une production soudaine d'hormones nouvelles", "Un effet de la croissance osseuse", "Une maturation cérébrale seule"], 0,
     "L'âge de son déclenchement a nettement avancé au cours du dernier siècle."],
    ["Quelle hormone régule le métabolisme de base ?", ["La thyroxine", "L'insuline", "Le cortisol", "L'adrénaline"], 0,
     "Un excès provoque une hyperthyroïdie, un déficit une hypothyroïdie."],
    ["Qu'est-ce que le diabète de type 1 ?", ["Une destruction auto-immune des cellules produisant l'insuline", "Une résistance à l'insuline", "Un excès de sucre alimentaire", "Une maladie hépatique"], 0,
     "Il apparaît souvent dans l'enfance et impose un apport externe d'insuline à vie."],
    ["Qu'est-ce que le diabète de type 2 ?", ["Une résistance progressive des cellules à l'insuline", "Une absence totale d'insuline", "Une maladie auto-immune", "Un trouble héréditaire pur"], 0,
     "Il représente environ neuf cas de diabète sur dix et se développe souvent après quarante ans."],
    ["Pourquoi les perturbateurs endocriniens échappent-ils au raisonnement toxicologique classique ?", ["Certains agissent à très faibles doses, sans relation dose-effet simple", "Ils sont indétectables", "Ils s'accumulent dans les os", "Ils n'ont d'effet qu'à forte dose"], 0,
     "La période d'exposition, notamment pendant le développement, compte souvent autant que la dose."],
    ["Qu'est-ce que le cortisol ?", ["Une hormone du stress régulant aussi le métabolisme", "Une hormone sexuelle", "Une hormone digestive", "Une hormone du sommeil"], 0,
     "Sa sécrétion suit un rythme circadien marqué, maximale au réveil."],
    ["Qu'est-ce que l'hormone parathyroïdienne régule ?", ["Le calcium sanguin", "Le sodium", "Le glucose", "Le potassium"], 0,
     "Elle agit sur l'os, le rein et l'intestin pour maintenir la calcémie."],
    ["Qu'est-ce que le rétrocontrôle hormonal ?", ["Un mécanisme où l'hormone produite freine sa propre commande", "Une amplification hormonale", "Une action retardée", "Un couplage entre deux hormones"], 0,
     "C'est ce qui rend dangereux l'arrêt brutal d'un traitement hormonal prolongé."],
    ["Qu'est-ce que l'exploration hormonale en médecine ?", ["Un ensemble de dosages sanguins interprétés selon le contexte et l'heure", "Une imagerie des glandes", "Un test génétique", "Une biopsie glandulaire"], 0,
     "Une seule mesure isolée est souvent ininterprétable en raison des variations circadiennes.", 3],
  ]),

  notion("sv3-eau-milieux", S, "Les milieux aquatiques continentaux",
    "Rivières, lacs, zones humides.",
    "Les zones humides ont perdu une part considérable de leur surface en un siècle.",
    2, [
    ["Qu'est-ce qu'un cours d'eau de première catégorie en France ?", ["Un cours d'eau où domine la truite et les salmonidés", "Un cours d'eau navigable", "Un cours d'eau protégé", "Un cours d'eau de grande taille"], 0,
     "La classification détermine les règles de pêche applicables."],
    ["Qu'est-ce qu'une continuité écologique d'un cours d'eau ?", ["La libre circulation des espèces et des sédiments", "La continuité du débit", "L'absence de pollution", "La stabilité des berges"], 0,
     "Barrages et seuils la rompent, ce qui explique les programmes d'effacement d'ouvrages."],
    ["Qu'est-ce qu'une passe à poissons ?", ["Un aménagement permettant de franchir un obstacle sur un cours d'eau", "Un filet de capture", "Un bassin d'élevage", "Un canal de dérivation"], 0,
     "Son efficacité varie fortement selon les espèces et la conception de l'ouvrage."],
    ["Qu'est-ce qu'un poisson migrateur amphihalin ?", ["Un poisson passant d'eau douce en eau salée au cours de sa vie", "Un poisson migrant en rivière", "Un poisson de mer côtier", "Un poisson d'estuaire"], 0,
     "Le saumon et l'anguille en sont les exemples les plus connus, tous deux en fort déclin."],
    ["Qu'est-ce qu'une ripisylve ?", ["La végétation boisée des berges d'un cours d'eau", "Une forêt inondable", "Une haie agricole", "Un boisement de fond de vallée"], 0,
     "Elle limite l'érosion, filtre les polluants et ombrage l'eau."],
    ["Qu'est-ce qu'une tourbière ?", ["Une zone humide accumulant de la matière organique non décomposée", "Un marais salant", "Un étang forestier", "Une prairie inondable"], 0,
     "Elle stocke des quantités considérables de carbone et conserve des archives polliniques."],
    ["Qu'est-ce que la convention de Ramsar ?", ["Un traité international sur les zones humides d'importance internationale", "Un accord sur les fleuves transfrontaliers", "Une convention sur la pêche", "Un traité sur la qualité de l'eau"], 0,
     "Signée en 1971 en Iran, elle protège plus de deux mille cinq cents sites dans le monde."],
    ["Qu'est-ce qu'un indice biologique de qualité de l'eau ?", ["Une évaluation fondée sur les organismes présents dans le milieu", "Une mesure chimique", "Un dosage bactériologique", "Une mesure de turbidité"], 0,
     "Les invertébrés benthiques renseignent sur la qualité moyenne sur plusieurs mois."],
    ["Qu'est-ce que l'eutrophisation d'un lac ?", ["Un enrichissement en nutriments provoquant proliférations d'algues et asphyxie", "Un assèchement progressif", "Une acidification", "Un réchauffement de l'eau"], 0,
     "Les nitrates et phosphates d'origine agricole et domestique en sont les principaux moteurs."],
    ["Qu'est-ce qu'une espèce aquatique invasive en France ?", ["Une espèce introduite qui déséquilibre les milieux, comme l'écrevisse de Louisiane", "Une espèce migratrice", "Une espèce protégée", "Une espèce d'élevage"], 0,
     "Elle transmet une maladie mortelle pour les écrevisses autochtones.", 3],
  ]),

  notion("sv3-agriculture-biologie", S, "Biologie appliquée à l'agriculture",
    "Protection des cultures, sélection, biotechnologies.",
    "La lutte biologique utilise des organismes vivants contre les ravageurs.",
    2, [
    ["Qu'est-ce que la lutte biologique ?", ["L'usage d'organismes vivants pour contrôler des ravageurs", "L'usage de produits naturels", "Une agriculture sans traitement", "Un contrôle mécanique"], 0,
     "Coccinelles contre pucerons ou trichogrammes contre pyrale du maïs en sont des exemples."],
    ["Qu'est-ce qu'un auxiliaire de culture ?", ["Un organisme utile luttant naturellement contre les ravageurs", "Un engrais organique", "Un outil agricole", "Un stimulant de croissance"], 0,
     "Haies et bandes fleuries favorisent leur présence dans les parcelles."],
    ["Qu'est-ce que la résistance aux pesticides ?", ["L'apparition de populations de ravageurs insensibles au traitement", "Une tolérance de la plante", "Une dégradation du produit", "Une immunité acquise du sol"], 0,
     "Elle résulte de la sélection des individus les moins sensibles, génération après génération."],
    ["Qu'est-ce qu'un fongicide ?", ["Un produit destiné à lutter contre les champignons parasites", "Un produit contre les insectes", "Un désherbant", "Un stimulant racinaire"], 0,
     "Le mildiou et l'oïdium comptent parmi les maladies les plus traitées en viticulture."],
    ["Qu'est-ce que la bouillie bordelaise ?", ["Un fongicide à base de cuivre utilisé notamment en agriculture biologique", "Un engrais liquide", "Un insecticide naturel", "Un désherbant"], 0,
     "Son usage répété entraîne une accumulation de cuivre dans les sols."],
    ["Qu'est-ce que la sélection variétale classique ?", ["Le croisement et le tri de générations successives selon des critères observés", "Une modification génétique", "Une culture in vitro", "Un clonage de plantes"], 0,
     "Elle demande souvent une dizaine d'années pour obtenir une variété stable."],
    ["Qu'est-ce que la sélection assistée par marqueurs ?", ["Une sélection utilisant des repères génétiques pour accélérer le tri", "Une modification du génome", "Un clonage sélectif", "Une hybridation forcée"], 0,
     "Elle accélère la sélection classique sans modifier directement le génome."],
    ["Qu'est-ce que la culture in vitro de plantes ?", ["La multiplication de plantes à partir de fragments en milieu stérile", "Une culture hors-sol", "Une culture sous serre", "Une culture hydroponique"], 0,
     "Elle permet de produire des plants sains et identiques en très grand nombre."],
    ["Qu'est-ce qu'un biostimulant agricole ?", ["Un produit favorisant les processus naturels de la plante", "Un engrais concentré", "Un pesticide naturel", "Un régulateur de croissance chimique"], 0,
     "La réglementation européenne encadre leurs allégations depuis 2019."],
    ["Qu'est-ce que la biodiversité fonctionnelle en agriculture ?", ["La diversité d'organismes rendant des services utiles à la culture", "La variété des plantes cultivées", "Le nombre d'espèces présentes", "La richesse du sol"], 0,
     "Pollinisation, régulation des ravageurs et fertilité du sol en sont les principales fonctions.", 3],
  ]),

  notion("sv3-cancer", S, "Le cancer",
    "Mécanismes, facteurs de risque, traitements.",
    "Le cancer n'est pas une maladie mais une famille de maladies.",
    2, [
    ["Qu'est-ce qu'un cancer sur le plan biologique ?", ["Une prolifération incontrôlée de cellules capables d'envahir d'autres tissus", "Une tumeur bénigne", "Une inflammation chronique", "Une infection cellulaire"], 0,
     "La capacité d'invasion et de métastase distingue le cancer d'une tumeur bénigne."],
    ["Qu'est-ce qu'une métastase ?", ["Une colonisation à distance par des cellules issues de la tumeur d'origine", "Une récidive locale", "Une tumeur secondaire indépendante", "Une extension du volume tumoral"], 0,
     "C'est la principale cause de mortalité par cancer."],
    ["Quel est le premier facteur de risque évitable de cancer ?", ["Le tabac", "L'alcool", "L'alimentation", "La pollution"], 0,
     "Il est responsable d'environ un cancer sur cinq en France."],
    ["Quel cancer est le plus fréquent chez la femme en France ?", ["Le cancer du sein", "Le cancer du poumon", "Le cancer colorectal", "Le cancer de l'utérus"], 0,
     "Le cancer du poumon en est en revanche devenu une cause majeure de décès."],
    ["Quel cancer est le plus fréquent chez l'homme en France ?", ["Le cancer de la prostate", "Le cancer du poumon", "Le cancer colorectal", "Le cancer de la vessie"], 0,
     "Son dépistage systématique fait l'objet de débats en raison des surdiagnostics."],
    ["Qu'est-ce qu'un dépistage organisé du cancer ?", ["Un programme systématique proposé à une population cible", "Un examen sur prescription", "Un test pour personnes à risque", "Un bilan de santé complet"], 0,
     "En France, il concerne les cancers du sein, colorectal et du col de l'utérus."],
    ["Qu'est-ce que le surdiagnostic ?", ["La détection de lésions qui n'auraient jamais causé de symptômes", "Une erreur de diagnostic", "Un diagnostic tardif", "Un diagnostic répété"], 0,
     "Il conduit à des traitements inutiles, avec leurs effets indésirables propres."],
    ["Qu'est-ce que la chimiothérapie ?", ["Un traitement par médicaments visant les cellules à division rapide", "Un traitement par rayonnement", "Une chirurgie ciblée", "Une immunothérapie"], 0,
     "Ses effets indésirables s'expliquent par l'atteinte des cellules saines à renouvellement rapide."],
    ["Qu'est-ce que la radiothérapie ?", ["Un traitement utilisant des rayonnements pour détruire les cellules tumorales", "Une imagerie de contrôle", "Une chimiothérapie locale", "Un traitement hormonal"], 0,
     "Les techniques modernes permettent de concentrer la dose sur la tumeur en épargnant les tissus voisins."],
    ["Qu'est-ce que le taux de survie à cinq ans ?", ["La proportion de patients vivants cinq ans après le diagnostic", "Le taux de guérison", "L'espérance de vie après traitement", "Le taux de rémission complète"], 0,
     "Il varie considérablement selon la localisation et le stade au diagnostic.", 3],
  ]),

  notion("sv3-microbiote-sante", S, "Microbiote et santé",
    "Recherches récentes et prudence nécessaire.",
    "Les recherches sur le microbiote sont prometteuses mais souvent surinterprétées.",
    2, [
    ["Qu'est-ce que la transplantation de microbiote fécal ?", ["Le transfert de flore intestinale d'un donneur à un patient", "Une greffe d'intestin", "Un traitement probiotique concentré", "Une injection de bactéries de laboratoire"], 0,
     "Elle est validée pour les infections récidivantes à Clostridioides difficile."],
    ["Comment le microbiote d'un nouveau-né se constitue-t-il ?", ["Par contact avec la mère et l'environnement dès la naissance", "Il est présent avant la naissance", "Il vient uniquement de l'allaitement", "Il se forme après un an"], 0,
     "Le mode d'accouchement influence sa composition initiale."],
    ["Qu'est-ce qu'un prébiotique ?", ["Une fibre nourrissant les bactéries bénéfiques déjà présentes", "Un micro-organisme vivant ingéré", "Un antibiotique doux", "Un complément vitaminé"], 0,
     "Le probiotique, lui, apporte des micro-organismes vivants."],
    ["Que produisent les bactéries intestinales à partir des fibres ?", ["Des acides gras à chaîne courte", "Des protéines", "Des vitamines liposolubles", "Du glucose"], 0,
     "Le butyrate ainsi produit nourrit directement les cellules du côlon."],
    ["Quel effet un régime pauvre en fibres a-t-il sur le microbiote ?", ["Il appauvrit sa diversité", "Il l'enrichit", "Il n'a pas d'effet", "Il le stabilise"], 0,
     "Les études comparant populations occidentales et rurales montrent des écarts marqués de diversité."],
    ["Qu'est-ce que la dysbiose ?", ["Un déséquilibre du microbiote associé à divers troubles", "Une infection intestinale", "Une allergie alimentaire", "Une inflammation chronique"], 0,
     "Le lien de causalité avec les maladies observées reste souvent difficile à établir."],
    ["Que sait-on du lien entre microbiote et obésité ?", ["Une association est établie, la causalité reste discutée", "Le microbiote cause l'obésité", "Il n'y a aucun lien", "Le lien est prouvé chez l'humain"], 0,
     "Les expériences sur souris sont plus concluantes que les études humaines."],
    ["Qu'est-ce que l'axe intestin-cerveau ?", ["Un ensemble de communications entre le système digestif et le système nerveux", "Un nerf unique", "Une hypothèse non vérifiée", "Une voie hormonale seule"], 0,
     "Le nerf vague, les métabolites bactériens et le système immunitaire y participent."],
    ["Quel effet les antibiotiques répétés dans l'enfance pourraient-ils avoir ?", ["Une modification durable du microbiote, aux conséquences encore étudiées", "Aucun effet", "Une immunité renforcée", "Une amélioration digestive"], 0,
     "Les études observationnelles doivent être interprétées avec prudence, les enfants traités étant aussi plus souvent malades."],
    ["Pourquoi faut-il rester prudent sur les allégations liées au microbiote ?", ["Beaucoup de résultats viennent d'études animales ou observationnelles", "Les recherches sont fausses", "Le microbiote n'est pas mesurable", "Les données manquent totalement"], 0,
     "Le marché des compléments a largement devancé les preuves cliniques disponibles.", 3],
  ]),

  notion("sv3-geologie-france", S, "La géologie de la France",
    "Formations, ressources, paysages.",
    "Le sous-sol français conserve la trace de plusieurs chaînes de montagnes disparues.",
    2, [
    ["Quelle chaîne de montagnes ancienne a laissé le Massif central et l'Armorique ?", ["La chaîne hercynienne", "La chaîne alpine", "La chaîne calédonienne", "La chaîne pyrénéenne"], 0,
     "Formée il y a environ trois cents millions d'années, elle a été presque entièrement arasée."],
    ["Quand les Alpes ont-elles commencé à se former ?", ["Il y a environ soixante millions d'années", "Il y a trois cents millions d'années", "Il y a dix millions d'années", "Il y a un milliard d'années"], 0,
     "La collision entre plaques africaine et eurasiatique se poursuit aujourd'hui."],
    ["Qu'est-ce que le Bassin parisien sur le plan géologique ?", ["Un empilement de couches sédimentaires en cuvette", "Un socle ancien affleurant", "Un bassin volcanique", "Une plaine alluviale"], 0,
     "Ses couches empilées expliquent les reliefs de cuesta et les nappes aquifères étagées."],
    ["Qu'est-ce que le calcaire lutétien ?", ["Une pierre de construction extraite dans la région parisienne", "Un calcaire alpin", "Un marbre du Massif central", "Un grès des Vosges"], 0,
     "Une grande partie des immeubles haussmanniens en est bâtie."],
    ["Qu'est-ce que la chaîne des Puys ?", ["Un alignement de volcans récents en Auvergne", "Une chaîne calcaire", "Un massif granitique", "Un plateau basaltique ancien"], 0,
     "Inscrite au patrimoine mondial en 2018, elle compte plus de quatre-vingts édifices."],
    ["Quand la chaîne des Puys a-t-elle été active pour la dernière fois ?", ["Il y a environ sept mille ans", "Il y a un million d'années", "Il y a cent mille ans", "Au Moyen Âge"], 0,
     "Elle est considérée comme endormie et non éteinte."],
    ["Qu'est-ce que le karst ?", ["Un relief creusé par la dissolution des roches calcaires", "Un relief volcanique", "Un relief glaciaire", "Un relief granitique"], 0,
     "Grottes, gouffres et résurgences en sont les formes caractéristiques."],
    ["Quelle région française est célèbre pour ses gorges karstiques ?", ["Les Causses et les gorges du Tarn", "La Bretagne", "Les Landes", "L'Alsace"], 0,
     "Le plateau du Vercors et le Jura présentent également des reliefs karstiques marqués."],
    ["Qu'est-ce que la houille dans le sous-sol français ?", ["Un charbon formé au Carbonifère, exploité jusqu'en 2004", "Un gaz naturel", "Un minerai de fer", "Une roche volcanique"], 0,
     "La dernière mine française a fermé à Creutzwald, en Moselle."],
    ["Quel risque sismique concerne la France métropolitaine ?", ["Un risque modéré, surtout dans les Alpes, les Pyrénées et l'Alsace", "Un risque nul", "Un risque majeur sur tout le territoire", "Un risque limité à la Corse"], 0,
     "Le séisme de Bâle en 1356 et celui de Lambesc en 1909 rappellent que ce risque n'est pas théorique.", 3],
  ]),

  notion("sv3-mesures-biologie", S, "Mesurer le vivant",
    "Instruments, protocoles, statistiques.",
    "Une observation biologique n'a de sens qu'associée à un protocole explicite.",
    2, [
    ["Qu'est-ce qu'un témoin dans une expérience biologique ?", ["Un groupe non soumis au traitement testé", "Un observateur extérieur", "Un échantillon de référence", "Un instrument étalonné"], 0,
     "Sans lui, aucune variation ne peut être attribuée au traitement."],
    ["Qu'est-ce qu'une expérience en double aveugle ?", ["Ni le sujet ni l'expérimentateur ne connaissent l'attribution", "Le sujet seul est en aveugle", "Deux groupes sont comparés", "Les données sont analysées sans identifiants"], 0,
     "Elle élimine les biais d'attente des deux côtés."],
    ["Qu'est-ce qu'une randomisation ?", ["Une attribution aléatoire des sujets aux groupes", "Un tirage au sort des mesures", "Un échantillonnage représentatif", "Une variation aléatoire des doses"], 0,
     "Elle équilibre en moyenne les facteurs connus et inconnus entre les groupes."],
    ["Qu'est-ce qu'une étude observationnelle ?", ["Une étude sans intervention de l'expérimentateur sur l'exposition", "Une étude de laboratoire", "Une expérience contrôlée", "Une observation de terrain seule"], 0,
     "Elle permet d'établir des associations mais rarement des causalités."],
    ["Qu'est-ce qu'un facteur de confusion ?", ["Une variable liée à la fois à l'exposition et au résultat", "Une erreur de mesure", "Un biais de sélection", "Une variable aléatoire"], 0,
     "Il peut créer une association trompeuse entre deux phénomènes sans lien causal."],
    ["Qu'est-ce qu'une méta-analyse ?", ["Une synthèse statistique de plusieurs études sur une même question", "Une revue de littérature", "Une étude de grande taille", "Une réanalyse de données brutes"], 0,
     "Sa qualité dépend entièrement de celle des études incluses."],
    ["Qu'est-ce qu'un intervalle de confiance dans une étude ?", ["Une plage de valeurs compatibles avec les données observées", "Une marge d'erreur instrumentale", "Un seuil de significativité", "Un écart type"], 0,
     "Un intervalle large signale une incertitude importante, même avec un résultat significatif."],
    ["Qu'est-ce que la puissance statistique d'une étude ?", ["Sa capacité à détecter un effet réel s'il existe", "Sa taille d'échantillon", "Sa précision de mesure", "Sa significativité"], 0,
     "Une étude sous-dimensionnée peut ne rien détecter alors qu'un effet existe."],
    ["Qu'est-ce que le biais de publication ?", ["La tendance à publier davantage les résultats positifs", "Une erreur de relecture", "Un biais de sélection des sujets", "Une falsification de données"], 0,
     "Il fausse les méta-analyses et l'appréciation générale d'un effet."],
    ["Qu'est-ce que le préenregistrement d'une étude ?", ["Le dépôt public du protocole avant la collecte des données", "L'inscription à un registre d'essais", "Une déclaration éthique", "Un dépôt de brevet"], 0,
     "Il limite les analyses opportunistes menées jusqu'à obtenir un résultat significatif.", 3],
  ]),

  notion("sv3-especes-france", S, "La faune et la flore de France",
    "Espèces emblématiques, protections, retours.",
    "La France métropolitaine abrite une biodiversité plus riche que la moyenne européenne.",
    2, [
    ["Quel grand prédateur est revenu naturellement en France en 1992 ?", ["Le loup", "Le lynx", "L'ours", "Le chacal doré"], 0,
     "Depuis l'Italie, dans le parc du Mercantour. La population dépasse aujourd'hui plusieurs centaines d'individus."],
    ["Quel grand mammifère a été réintroduit dans les Pyrénées ?", ["L'ours brun", "Le loup", "Le bouquetin", "Le lynx"], 0,
     "Des individus slovènes ont été relâchés à partir de 1996, dans un contexte très conflictuel."],
    ["Quel rapace a été réintroduit avec succès dans plusieurs massifs français ?", ["Le vautour fauve", "L'aigle royal", "Le faucon pèlerin", "Le milan royal"], 0,
     "Les Grands Causses ont accueilli le premier programme, à partir de 1981."],
    ["Quel oiseau a failli disparaître de France à cause d'un pesticide ?", ["Le faucon pèlerin", "La cigogne blanche", "Le héron cendré", "Le busard cendré"], 0,
     "Le DDT fragilisait la coquille de ses œufs. Son interdiction a permis sa recolonisation."],
    ["Quel mammifère marin fréquente régulièrement les côtes françaises ?", ["Le grand dauphin", "L'orque", "Le cachalot en Manche", "Le morse"], 0,
     "Le sanctuaire Pelagos, en Méditerranée, protège plusieurs espèces de cétacés."],
    ["Qu'est-ce qu'une espèce protégée en France ?", ["Une espèce dont la destruction et la perturbation sont interdites", "Une espèce rare", "Une espèce chassable réglementée", "Une espèce inscrite à la liste rouge"], 0,
     "La protection porte aussi sur les habitats nécessaires à leur cycle de vie."],
    ["Qu'est-ce que le réseau Natura 2000 ?", ["Un réseau européen de sites protégeant habitats et espèces", "Un parc national européen", "Une liste d'espèces protégées", "Un programme de recherche"], 0,
     "Il couvre environ treize pour cent du territoire terrestre français."],
    ["Qu'est-ce qu'un parc national français ?", ["Un espace protégé à cœur réglementé et aire d'adhésion", "Une réserve naturelle intégrale", "Un parc naturel régional", "Une forêt domaniale protégée"], 0,
     "La France en compte onze, dont trois en outre-mer."],
    ["Qu'est-ce que la liste rouge des espèces menacées en France ?", ["Un état des lieux du risque de disparition des espèces du territoire", "Une liste d'espèces protégées", "Un inventaire des espèces rares", "Un classement réglementaire"], 0,
     "Elle est établie selon la méthodologie de l'UICN par un comité national."],
    ["Quelle particularité les outre-mer français présentent-ils pour la biodiversité ?", ["Ils concentrent l'essentiel des espèces endémiques françaises", "Ils ont une faune identique à la métropole", "Ils abritent peu d'espèces", "Ils ne sont pas protégés"], 0,
     "Plus de quatre-vingts pour cent de la biodiversité française s'y trouve.", 3],
  ]),

  notion("sv3-alimentation-sante", S, "Épidémiologie de l'alimentation",
    "Recommandations, épidémiologie nutritionnelle, limites.",
    "L'épidémiologie nutritionnelle est difficile car on ne peut isoler un aliment de son contexte.",
    2, [
    ["Pourquoi les études nutritionnelles sont-elles difficiles à interpréter ?", ["Les régimes sont liés à de nombreux autres facteurs de mode de vie", "Les aliments sont mal identifiés", "Les mesures sont impossibles", "Les échantillons sont trop petits"], 0,
     "Un mangeur de légumes diffère aussi par son activité physique, son revenu et son tabagisme."],
    ["Qu'est-ce qu'un questionnaire de fréquence alimentaire ?", ["Un outil déclaratif estimant la consommation habituelle", "Une pesée des aliments", "Un carnet alimentaire", "Un dosage sanguin"], 0,
     "Sa fiabilité est limitée par les biais de mémoire et de déclaration."],
    ["Que recommande le Programme national nutrition santé sur les fruits et légumes ?", ["Au moins cinq portions par jour", "Trois portions", "Dix portions", "Deux portions"], 0,
     "La recommandation vise environ quatre cents grammes par jour."],
    ["Que recommande-t-on sur la consommation de sel ?", ["De la limiter à environ cinq grammes par jour", "De l'augmenter", "De la supprimer totalement", "De la limiter à quinze grammes"], 0,
     "La consommation moyenne française reste nettement supérieure à cette recommandation."],
    ["Quel lien est établi entre viande transformée et cancer ?", ["Le Centre international de recherche sur le cancer la classe comme cancérogène", "Aucun lien", "Un lien uniquement chez l'animal", "Un lien réfuté"], 0,
     "Le classement porte sur le niveau de preuve du danger, non sur l'ampleur du risque."],
    ["Qu'est-ce que l'alimentation ultra-transformée ?", ["Des produits industriels contenant des ingrédients d'usage non domestique", "Des plats préparés en général", "Des conserves", "Des aliments surgelés"], 0,
     "Additifs, arômes et protéines isolées en sont des marqueurs typiques."],
    ["Quel lien les études suggèrent-elles entre ultra-transformé et santé ?", ["Une association avec plusieurs pathologies chroniques", "Aucun lien", "Un effet protecteur", "Un lien limité à l'obésité"], 0,
     "Les mécanismes précis restent discutés : composition, additifs, matrice ou densité énergétique."],
    ["Qu'est-ce que l'index glycémique d'un aliment ?", ["La vitesse à laquelle il élève la glycémie", "Sa teneur en sucre", "Sa densité calorique", "Sa charge en glucides"], 0,
     "La charge glycémique tient compte en plus de la quantité consommée."],
    ["Que recommande-t-on sur l'alcool en santé publique ?", ["De ne pas dépasser dix verres par semaine et d'avoir des jours sans", "Deux verres par jour sans limite hebdomadaire", "Un verre de vin est bénéfique", "Aucune limite pour le vin"], 0,
     "L'idée d'un effet protecteur cardiovasculaire du vin a été largement remise en cause."],
    ["Qu'est-ce qu'une carence en fer ?", ["Un déficit fréquent pouvant entraîner une anémie", "Un excès de fer", "Une maladie génétique", "Un trouble digestif"], 0,
     "C'est la carence nutritionnelle la plus répandue au monde, touchant surtout les femmes et les enfants.", 3],
  ]),

  notion("sv3-vieillissement", S, "Le vieillissement",
    "Mécanismes biologiques et enjeux sociaux.",
    "Le vieillissement n'est pas une maladie mais un ensemble de processus.",
    2, [
    ["Qu'est-ce que la sénescence cellulaire ?", ["Un arrêt définitif de division d'une cellule encore vivante", "La mort cellulaire", "Une division ralentie", "Une mutation du génome"], 0,
     "Ces cellules s'accumulent avec l'âge et sécrètent des facteurs inflammatoires."],
    ["Qu'est-ce que la limite de Hayflick ?", ["Le nombre maximal de divisions d'une cellule humaine en culture", "La durée de vie maximale", "Le seuil de mutation", "La limite de régénération d'un organe"], 0,
     "Environ cinquante divisions, découverte en 1961, liée au raccourcissement des télomères."],
    ["Qu'est-ce qu'un télomère ?", ["Une extrémité protectrice de chromosome qui se raccourcit à chaque division", "Un gène du vieillissement", "Une protéine réparatrice", "Un fragment d'ADN mitochondrial"], 0,
     "La télomérase, qui les reconstitue, est active dans les cellules souches et cancéreuses."],
    ["Pourquoi l'écart entre espérance de vie et espérance de vie en bonne santé se creuse-t-il ?", ["Les années gagnées le sont souvent avec des incapacités", "Les mesures ont changé", "L'espérance de vie stagne", "Les maladies chroniques ont disparu"], 0,
     "En France, l'écart approche une dizaine d'années, ce qui pèse sur les politiques du grand âge."],
    ["Quelle est l'espérance de vie à la naissance en France ?", ["Environ quatre-vingt-cinq ans pour les femmes et soixante-dix-neuf pour les hommes", "Soixante-quinze ans pour tous", "Quatre-vingt-quinze ans", "Soixante-dix ans"], 0,
     "L'écart entre les sexes se réduit lentement depuis les années 1990."],
    ["Qu'est-ce que la fragilité chez la personne âgée ?", ["Un état de vulnérabilité accrue face aux agressions", "Une maladie chronique", "Une perte d'autonomie constituée", "Un trouble cognitif"], 0,
     "Elle est réversible si elle est repérée tôt, notamment par l'activité physique."],
    ["Qu'est-ce que la perte d'autonomie ?", ["Une incapacité à réaliser seul les actes de la vie quotidienne", "Un isolement social", "Un vieillissement normal", "Une maladie neurologique"], 0,
     "La grille AGGIR permet de l'évaluer pour l'attribution de l'allocation personnalisée d'autonomie."],
    ["Qu'est-ce que la réserve cognitive ?", ["Une capacité du cerveau à compenser les lésions liées à l'âge", "Une mémoire de secours", "Un stock de neurones inutilisés", "Une plasticité de l'enfance"], 0,
     "Niveau d'études, activités intellectuelles et vie sociale semblent y contribuer."],
    ["Qu'est-ce que la polymédication chez les personnes âgées ?", ["La prise simultanée de nombreux médicaments, source d'interactions", "Un traitement multiple justifié", "Une automédication", "Une prescription hospitalière"], 0,
     "Elle est une cause fréquente d'hospitalisations évitables."],
    ["Que sait-on des interventions ralentissant le vieillissement ?", ["L'activité physique reste la mieux documentée", "Plusieurs traitements sont validés", "Aucun facteur n'a d'effet", "Seule la génétique compte"], 0,
     "Les allégations sur les compléments antivieillissement ne reposent sur aucune preuve solide chez l'humain.", 3],
  ]),

  notion("sv3-eau-corps", S, "L'eau et les équilibres du corps",
    "Hydratation, reins, équilibres internes.",
    "L'eau fait la majeure partie du corps humain, mais la proportion varie avec l'âge et la masse grasse.",
    2, [
    ["Quelle proportion du corps humain adulte est constituée d'eau ?", ["Environ soixante pour cent", "Environ trente pour cent", "Environ quatre-vingt-dix pour cent", "Environ quarante pour cent"], 0,
     "La proportion est plus élevée chez le nourrisson et plus faible chez la personne âgée."],
    ["Quel organe régule principalement l'équilibre hydrique ?", ["Le rein", "Le foie", "Le cœur", "L'intestin"], 0,
     "Il filtre environ cent quatre-vingts litres de plasma par jour pour n'éliminer qu'un à deux litres d'urine."],
    ["Qu'est-ce que l'hormone antidiurétique ?", ["Une hormone limitant la perte d'eau par les reins", "Une hormone augmentant la diurèse", "Une hormone digestive", "Une hormone du stress"], 0,
     "Elle explique pourquoi l'alcool, qui en inhibe la sécrétion, augmente la production d'urine."],
    ["Qu'est-ce que l'homéostasie ?", ["Le maintien de conditions internes stables malgré les variations externes", "Un équilibre chimique", "Une régulation hormonale", "Un état de repos métabolique"], 0,
     "Température, pH, glycémie et volémie en sont les principaux paramètres régulés."],
    ["Quelle est la température interne normale du corps humain ?", ["Environ trente-sept degrés", "Environ trente-cinq degrés", "Environ trente-neuf degrés", "Environ trente-six degrés"], 0,
     "Elle varie légèrement selon l'heure, l'activité et le point de mesure."],
    ["Comment le corps se refroidit-il principalement ?", ["Par l'évaporation de la sueur", "Par la respiration", "Par le rayonnement seul", "Par la circulation sanguine profonde"], 0,
     "Une humidité élevée réduit fortement l'efficacité de ce mécanisme, ce qui rend les canicules humides dangereuses."],
    ["Qu'est-ce qu'un coup de chaleur ?", ["Une défaillance de la thermorégulation avec température corporelle très élevée", "Une déshydratation", "Une insolation bénigne", "Un malaise vagal"], 0,
     "C'est une urgence vitale : le refroidissement doit être immédiat."],
    ["Combien d'eau un adulte perd-il en moyenne par jour ?", ["Environ deux litres et demi", "Environ un demi-litre", "Environ cinq litres", "Environ dix litres"], 0,
     "Urine, respiration, transpiration et pertes digestives s'y combinent."],
    ["D'où vient l'eau apportée quotidiennement au corps ?", ["Des boissons, des aliments et du métabolisme", "Des boissons uniquement", "Des aliments uniquement", "De la respiration"], 0,
     "Les aliments fournissent environ un litre par jour dans un régime ordinaire."],
    ["Qu'est-ce que la soif comme signal physiologique ?", ["Un signal tardif traduisant déjà un déficit hydrique", "Un signal précoce", "Un réflexe conditionné", "Un signal indépendant de l'hydratation"], 0,
     "Chez la personne âgée, ce signal s'émousse, ce qui accroît le risque de déshydratation.", 3],
  ]),

  notion("sv3-symbioses", S, "Symbioses et interactions",
    "Coopérations et parasitismes dans le vivant.",
    "La coopération entre espèces est aussi répandue que la compétition.",
    2, [
    ["Qu'est-ce qu'une symbiose ?", ["Une association durable entre deux espèces", "Une association bénéfique uniquement", "Une coopération temporaire", "Un parasitisme atténué"], 0,
     "Le mutualisme, le commensalisme et le parasitisme en sont des formes."],
    ["Qu'est-ce que le mutualisme ?", ["Une association bénéfique aux deux partenaires", "Une association neutre", "Un parasitisme réciproque", "Une compétition régulée"], 0,
     "La pollinisation entre fleurs et insectes en est l'exemple le plus répandu."],
    ["Qu'est-ce que le commensalisme ?", ["Une association bénéfique à l'un sans effet sur l'autre", "Une association mutuellement bénéfique", "Un parasitisme léger", "Une compétition indirecte"], 0,
     "Le rémora fixé au requin en est un exemple classique."],
    ["Qu'est-ce que le parasitisme ?", ["Une association bénéfique à l'un au détriment de l'autre", "Une prédation", "Une compétition directe", "Une association neutre"], 0,
     "Un parasite trop virulent risque de tuer son hôte, donc de disparaître avec lui."],
    ["Qu'est-ce qu'un parasitoïde ?", ["Un organisme dont le développement tue son hôte", "Un parasite bénin", "Un prédateur spécialisé", "Un symbiote temporaire"], 0,
     "De nombreuses guêpes pondent dans des chenilles, ce qui est exploité en lutte biologique."],
    ["Qu'est-ce que la nodosité des légumineuses ?", ["Une structure racinaire abritant des bactéries fixatrices d'azote", "Une tumeur végétale", "Un organe de réserve", "Une infection fongique"], 0,
     "Les rhizobiums y transforment l'azote de l'air en composés assimilables."],
    ["Qu'est-ce que la mycorhize arbusculaire ?", ["Une association entre racines et champignons pénétrant les cellules racinaires", "Une infection fongique", "Un champignon de surface", "Une symbiose avec des bactéries"], 0,
     "Elle concerne la grande majorité des plantes terrestres et existe depuis plus de quatre cents millions d'années."],
    ["Qu'est-ce que le corail sur le plan symbiotique ?", ["Un animal vivant en symbiose avec des algues photosynthétiques", "Une algue calcaire", "Un végétal marin", "Un minéral d'origine biologique"], 0,
     "Le blanchissement correspond à l'expulsion de ces algues sous l'effet du stress thermique."],
    ["Qu'est-ce que le microbiote d'un termite lui permet de faire ?", ["Digérer la cellulose du bois", "Fabriquer sa carapace", "Réguler sa température", "Se reproduire"], 0,
     "Sans ses micro-organismes intestinaux, il ne pourrait tirer aucune énergie du bois."],
    ["Qu'est-ce que la coévolution dans une symbiose ?", ["Une évolution réciproque des partenaires au fil des générations", "Une évolution parallèle indépendante", "Une convergence de formes", "Une spéciation simultanée"], 0,
     "Certaines orchidées et leurs pollinisateurs présentent des correspondances morphologiques extrêmement précises.", 3],
  ]),

  notion("sv3-terre-atmosphere-histoire", S, "L'histoire de l'atmosphère terrestre",
    "Des origines à l'oxygène : quatre milliards d'années de transformation.",
    "L'oxygène atmosphérique est un produit du vivant, non une condition initiale.",
    2, [
    ["De quoi l'atmosphère primitive de la Terre était-elle composée ?", ["Principalement de dioxyde de carbone, d'azote et de vapeur d'eau", "D'oxygène et d'azote", "D'hydrogène et d'hélium seulement", "De méthane pur"], 0,
     "Elle était issue du dégazage volcanique intense de la Terre jeune."],
    ["Qu'est-ce que la grande oxydation ?", ["L'accumulation d'oxygène atmosphérique il y a environ 2,4 milliards d'années", "Une oxydation des océans", "Une phase de rouille des roches", "Un épisode volcanique"], 0,
     "Elle résulte de la photosynthèse des cyanobactéries et fut une catastrophe pour la vie anaérobie."],
    ["Quels organismes ont produit les premiers l'oxygène atmosphérique ?", ["Les cyanobactéries", "Les algues vertes", "Les plantes terrestres", "Les archées"], 0,
     "Les stromatolithes en conservent la trace fossile depuis plus de trois milliards d'années."],
    ["Quand la couche d'ozone s'est-elle formée ?", ["Après l'accumulation d'oxygène dans l'atmosphère", "Dès la formation de la Terre", "Il y a un million d'années", "Avec l'apparition des plantes terrestres"], 0,
     "Elle a permis la colonisation des continents en filtrant les ultraviolets."],
    ["Quand les plantes ont-elles colonisé les continents ?", ["Il y a environ quatre cent cinquante millions d'années", "Il y a un milliard d'années", "Il y a cent millions d'années", "Il y a deux milliards d'années"], 0,
     "Cette colonisation a fortement modifié le climat et l'érosion des roches."],
    ["Qu'est-ce que le charbon révèle sur le Carbonifère ?", ["Une accumulation massive de matière végétale non décomposée", "Un climat aride", "Une activité volcanique intense", "Un niveau marin bas"], 0,
     "Les champignons capables de dégrader la lignine n'étaient alors pas encore répandus."],
    ["Comment mesure-t-on les climats du passé lointain ?", ["Par les isotopes des roches, des glaces et des fossiles", "Par les archives historiques", "Par les mesures instrumentales", "Par les cernes d'arbres uniquement"], 0,
     "Chaque archive couvre une échelle de temps différente."],
    ["Qu'est-ce qu'une carotte de glace ?", ["Un cylindre prélevé dans une calotte, contenant des bulles d'air fossiles", "Un échantillon de banquise", "Un forage sous-marin", "Une carotte sédimentaire"], 0,
     "Les carottes antarctiques les plus profondes, comme celle d'EPICA Dome C, remontent à plus de huit cent mille ans."],
    ["Que montrent les carottes de glace sur le CO2 atmosphérique ?", ["Sa concentration actuelle dépasse tout niveau des huit cent mille dernières années", "Une stabilité complète", "Des variations comparables à aujourd'hui", "Une baisse continue"], 0,
     "Les cycles glaciaires-interglaciaires y sont parfaitement lisibles."],
    ["Quelle est la principale cause de l'augmentation actuelle du CO2 ?", ["La combustion des énergies fossiles", "Le volcanisme", "La respiration des êtres vivants", "Le dégazage des océans"], 0,
     "La signature isotopique du carbone atmosphérique permet d'identifier son origine fossile.", 3],
  ]),
];
