/**
 * Sciences de la vie & Terre, deuxième lot — vingt notions.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Sciences de la vie & Terre";

export const CG_SCIENCES_VIE_2: SeedSkill[] = [
  notion("sv2-cellule", S, "La cellule",
    "L'unité de base du vivant, ses organites et ses fonctions.",
    "Toute cellule provient d'une autre cellule : c'est le troisième principe de la théorie cellulaire.",
    2, [
    ["Qui observe et nomme les cellules pour la première fois en 1665 ?", ["Robert Hooke", "Antonie van Leeuwenhoek", "Theodor Schwann", "Rudolf Virchow"], 0,
     "Il observait du liège au microscope ; les cavités lui rappelaient des cellules de moine."],
    ["Que dit la théorie cellulaire ?", ["Tout être vivant est fait de cellules issues d'autres cellules", "Toute cellule contient obligatoirement un noyau", "Les cellules se forment spontanément à partir de matière inerte", "Toute cellule est identique à toutes les autres"], 0,
     "Formulée par Schleiden et Schwann, complétée par Virchow avec l'idée de filiation cellulaire."],
    ["Quel organite produit l'essentiel de l'énergie de la cellule ?", ["La mitochondrie", "Le ribosome", "Le noyau", "L'appareil de Golgi"], 0,
     "Elle possède son propre ADN, vestige de son origine bactérienne."],
    ["Quelle théorie explique l'origine des mitochondries et des chloroplastes ?", ["L'endosymbiose", "La génération spontanée", "La sélection cellulaire", "La différenciation progressive"], 0,
     "Défendue par Lynn Margulis dans les années 1960, elle fut longtemps rejetée avant d'être admise."],
    ["Que fait un ribosome ?", ["Il assemble les protéines à partir de l'ARN messager", "Il stocke l'énergie sous forme de sucres", "Il duplique l'ADN avant chaque division", "Il digère les déchets qui s'accumulent à l'intérieur de la cellule"], 0,
     "Une cellule peut en contenir plusieurs millions."],
    ["Quel organite trie et expédie les protéines dans la cellule ?", ["L'appareil de Golgi", "Le lysosome digestif", "Le réticulum endoplasmique lisse", "Le centrosome cellulaire"], 0,
     "Il modifie chimiquement les protéines et les emballe dans des vésicules."],
    ["Quel organite contient des enzymes digestives ?", ["Le lysosome", "La mitochondrie", "Le ribosome", "Le peroxysome seul"], 0,
     "Il recycle les composants usés de la cellule, processus appelé autophagie."],
    ["Quelle est la différence entre mitose et méiose ?", ["La mitose donne deux cellules identiques, la méiose quatre cellules à moitié moins de chromosomes", "La mitose ne concerne que la formation des gamètes sexuels", "La méiose se déroule beaucoup plus rapidement que la mitose", "La mitose donne quatre cellules différentes, la méiose deux cellules porteuses de tous les chromosomes"], 0,
     "La méiose produit les gamètes et brasse le matériel génétique par recombinaison."],
    ["Qu'est-ce que l'apoptose ?", ["Une mort cellulaire programmée et contrôlée", "Une mort cellulaire accidentelle et désordonnée", "La division d'une cellule déjà vieillie", "L'arrêt complet du métabolisme cellulaire"], 0,
     "Elle sculpte les organes pendant le développement et élimine les cellules endommagées."],
    ["Qu'est-ce qu'une cellule souche ?", ["Une cellule capable de se diviser et de se différencier en plusieurs types", "Une cellule embryonnaire, et elle seule dans l'organisme", "Une cellule immortelle, qui ne meurt jamais et se divise sans fin ni limite d'âge", "Une cellule dépourvue de noyau, comme le globule rouge"], 0,
     "Les cellules souches induites, obtenues en 2006 à partir de cellules adultes, ont valu un Nobel à Shinya Yamanaka.", 3],
  ]),

  notion("sv2-nutrition-digestion", S, "La digestion et la nutrition",
    "Comment les aliments deviennent des nutriments utilisables par les cellules.",
    "La digestion commence dans la bouche et se poursuit sur environ neuf mètres de tube digestif.",
    2, [
    ["Où commence la digestion des amidons ?", ["Dans la bouche, par l'amylase salivaire", "Dans l'estomac, sous l'action de l'acide", "Dans l'intestin grêle, après le passage gastrique", "Dans le côlon, grâce aux bactéries"], 0,
     "C'est pourquoi un morceau de pain longuement mâché prend un goût sucré."],
    ["Quel est le pH approximatif de l'estomac ?", ["Entre un et trois", "Autour de sept", "Autour de neuf", "Autour de cinq et demi"], 0,
     "Cette acidité active la pepsine et détruit une grande partie des micro-organismes ingérés."],
    ["Où se fait l'essentiel de l'absorption des nutriments ?", ["Dans l'intestin grêle", "Dans l'estomac, avant le duodénum", "Dans le côlon, en fin de parcours", "Dans l'œsophage, dès la déglutition"], 0,
     "Ses villosités et microvillosités portent sa surface d'échange à plusieurs dizaines de mètres carrés."],
    ["Quel rôle la bile joue-t-elle dans la digestion ?", ["Elle émulsionne les graisses pour faciliter leur digestion", "Elle digère les protéines des aliments", "Elle neutralise les sucres avant l'intestin", "Elle absorbe directement les vitamines liposolubles au passage"], 0,
     "Produite par le foie, elle est stockée dans la vésicule biliaire."],
    ["Quel organe produit les enzymes digestives déversées dans l'intestin ?", ["Le pancréas", "Le foie", "La rate", "L'estomac seul"], 0,
     "Il sécrète aussi du bicarbonate pour neutraliser l'acidité venue de l'estomac."],
    ["Quelle est la principale fonction du côlon ?", ["Réabsorber l'eau et abriter le microbiote", "Absorber les protéines apportées par les aliments", "Produire les enzymes de la digestion", "Digérer les graisses grâce à la bile"], 0,
     "Il récupère environ un litre et demi d'eau par jour."],
    ["Qu'est-ce que le métabolisme de base ?", ["L'énergie dépensée au repos pour maintenir les fonctions vitales", "L'énergie dépensée au cours d'une activité physique", "La quantité totale d'aliments nécessaire chaque jour à l'organisme", "Le rendement de la digestion des aliments"], 0,
     "Il représente environ soixante à soixante-dix pour cent de la dépense énergétique quotidienne."],
    ["Qu'est-ce que le glycogène ?", ["Une forme de stockage du glucose dans le foie et les muscles", "Un sucre alimentaire présent dans les céréales", "Une hormone qui règle le taux de sucre du sang", "Une graisse de réserve stockée dans le tissu adipeux du ventre"], 0,
     "Les réserves hépatiques permettent de tenir environ vingt-quatre heures de jeûne."],
    ["Qu'est-ce que l'intolérance au lactose ?", ["Un déficit en lactase empêchant de digérer le sucre du lait", "Une allergie aux protéines contenues dans le lait de vache frais", "Une réaction immunitaire dirigée contre le lait", "Une carence en calcium due à un manque de lait"], 0,
     "La persistance de la lactase à l'âge adulte est une mutation relativement récente, très inégalement répartie."],
    ["Qu'est-ce que la maladie cœliaque ?", ["Une réaction immunitaire au gluten endommageant l'intestin", "Une intolérance digestive bénigne, passagère et sans conséquence", "Une allergie au blé et à ses dérivés", "Un trouble du microbiote intestinal du côlon"], 0,
     "Elle impose un régime strict à vie et n'a rien à voir avec une simple sensibilité au gluten.", 3],
  ]),

  notion("sv2-respiration-circulation", S, "Respiration et circulation",
    "Comment l'oxygène atteint les cellules et le dioxyde de carbone en repart.",
    "Le sang effectue deux circuits : un vers les poumons, un vers le reste du corps.",
    2, [
    ["Que transporte l'hémoglobine ?", ["L'oxygène", "Le glucose", "Les lipides", "Les hormones"], 0,
     "Chaque molécule peut fixer quatre molécules de dioxygène grâce à ses atomes de fer."],
    ["Où ont lieu les échanges gazeux dans les poumons ?", ["Dans les alvéoles", "Dans les bronches", "Dans la trachée", "Dans la plèvre"], 0,
     "Environ trois cents millions d'alvéoles offrent une surface d'échange d'environ soixante-dix mètres carrés, celle d'un grand appartement."],
    ["Qu'est-ce que la petite circulation ?", ["Le circuit entre le cœur et les poumons", "La circulation du sang dans les capillaires", "Le circuit emprunté par le sang veineux", "La circulation cérébrale du sang"], 0,
     "La grande circulation dessert tout le reste de l'organisme."],
    ["Qu'est-ce qu'une artère ?", ["Un vaisseau qui part du cœur", "Un vaisseau qui transporte du sang oxygéné", "Un vaisseau qui ramène le sang au cœur", "Un vaisseau du système lymphatique"], 0,
     "L'artère pulmonaire transporte du sang pauvre en oxygène : la définition tient au sens du flux, non à sa composition."],
    ["Qu'est-ce que la tension artérielle ?", ["La pression exercée par le sang sur la paroi des artères", "La vitesse à laquelle le sang circule dans les grosses artères", "Le débit de sang éjecté par le cœur en une minute", "La résistance opposée par la paroi des vaisseaux"], 0,
     "Elle se mesure en deux valeurs : systolique lors de la contraction, diastolique au repos du cœur."],
    ["Qu'est-ce qu'un infarctus du myocarde ?", ["La destruction d'une partie du muscle cardiaque privée de sang", "Un arrêt brutal et complet du cœur", "Un trouble du rythme cardiaque irrégulier", "Une inflammation du péricarde, cette membrane qui entoure le cœur"], 0,
     "Il résulte le plus souvent de l'obstruction d'une artère coronaire."],
    ["Qu'est-ce qu'un accident vasculaire cérébral ?", ["Une interruption ou une rupture de l'irrigation d'une zone du cerveau", "Une crise d'épilepsie avec perte de connaissance", "Une chute de tension brutale accompagnée d'un malaise et d'une perte de vue", "Une migraine sévère avec troubles de la vision"], 0,
     "Chaque minute compte : la prise en charge rapide conditionne largement les séquelles."],
    ["Quels sont les groupes sanguins du système ABO ?", ["A, B, AB et O", "A, B et C", "O positif et négatif seulement", "I, II, III et IV"], 0,
     "Le facteur Rhésus s'y ajoute. Le groupe O négatif est donneur universel pour les globules rouges."],
    ["Qu'est-ce que l'apnée du sommeil ?", ["Des arrêts respiratoires répétés pendant le sommeil", "Un ronflement particulièrement sonore", "Un sommeil trop léger et entrecoupé de réveils", "Une respiration anormalement rapide pendant la nuit"], 0,
     "Souvent sous-diagnostiquée, elle augmente le risque cardiovasculaire et la somnolence diurne.", 3],
  ]),

  notion("sv2-squelette-muscles", S, "Le squelette et les muscles",
    "Os, articulations, contraction : comment le corps tient debout et se déplace.",
    "L'os est un tissu vivant, sans cesse détruit et reconstruit.",
    2, [
    ["Combien d'os compte un squelette humain adulte ?", ["Environ deux cent six", "Environ trois cents", "Environ cent cinquante", "Environ deux cent cinquante"], 0,
     "Un nouveau-né en compte davantage : certains fusionnent au cours de la croissance."],
    ["Quel est le plus petit os du corps humain ?", ["L'étrier, dans l'oreille moyenne", "Le pisiforme, un petit os du poignet", "La dernière phalange du petit orteil", "L'os hyoïde, à la base de la langue"], 0,
     "Il transmet les vibrations du tympan à l'oreille interne avec les deux autres osselets."],
    ["Qu'est-ce que le cartilage articulaire ?", ["Un tissu lisse recouvrant les extrémités osseuses", "Un ligament renforcé entourant l'articulation", "Une membrane synoviale sécrétant le liquide articulaire", "Un tissu osseux encore jeune et non calcifié"], 0,
     "Dépourvu de vaisseaux, il se répare très mal, d'où la gravité de son usure."],
    ["Qu'est-ce qu'un ligament ?", ["Un tissu reliant deux os entre eux", "Un tissu reliant un muscle à un os", "Une gaine musculaire", "Une membrane articulaire"], 0,
     "Un tendon, lui, relie le muscle à l'os."],
    ["Combien de muscles le corps humain compte-t-il environ ?", ["Plus de six cents muscles squelettiques", "Environ deux cents muscles au total", "Environ mille cinq cents muscles au total", "Environ cent muscles seulement"], 0,
     "S'y ajoutent les muscles lisses des organes et le muscle cardiaque."],
    ["Qu'est-ce qu'un muscle antagoniste ?", ["Un muscle produisant le mouvement inverse d'un autre", "Un muscle inactif, resté sans usage", "Un muscle profond situé sous les muscles visibles", "Un muscle stabilisateur qui maintient l'articulation en place"], 0,
     "Le biceps fléchit le coude, le triceps l'étend : ils fonctionnent par paires."],
    ["Qu'est-ce que l'ostéoporose ?", ["Une fragilisation osseuse par perte de densité", "Une inflammation douloureuse du tissu osseux", "Une infection osseuse d'origine bactérienne", "Une déformation progressive de la colonne vertébrale"], 0,
     "Elle touche davantage les femmes après la ménopause, la baisse d'œstrogènes accélérant la perte osseuse."],
    ["Qu'est-ce qu'une courbature ?", ["Une douleur musculaire due à des microlésions après l'effort", "Une accumulation d'acide lactique persistant dans le muscle fatigué", "Une déshydratation musculaire survenant pendant l'effort", "Une contraction involontaire et douloureuse du muscle"], 0,
     "L'explication par l'acide lactique est un mythe tenace : il est éliminé en moins d'une heure."],
    ["Qu'est-ce que la sarcopénie ?", ["La perte progressive de masse musculaire avec l'âge", "Une maladie génétique rare du tissu musculaire", "Une inflammation musculaire d'origine auto-immune", "Une atrophie liée à une immobilisation prolongée au lit"], 0,
     "L'activité physique en freine nettement la progression, à tout âge.", 3],
  ]),

  notion("sv2-reproduction", S, "La reproduction humaine",
    "Gamètes, fécondation, développement : les bases biologiques.",
    "La fécondation a lieu dans la trompe, pas dans l'utérus.",
    2, [
    ["Où a lieu la fécondation chez l'humain ?", ["Dans la trompe utérine", "Dans l'utérus", "Dans l'ovaire", "Dans le col de l'utérus"], 0,
     "L'œuf fécondé migre ensuite plusieurs jours avant de s'implanter dans l'utérus."],
    ["Combien de chromosomes un gamète humain porte-t-il ?", ["Vingt-trois", "Quarante-six", "Vingt-deux", "Quarante-huit"], 0,
     "La méiose divise par deux le nombre de chromosomes, rétabli à la fécondation."],
    ["Qu'est-ce que la nidation ?", ["L'implantation de l'embryon dans la paroi utérine", "La formation progressive du placenta", "La première division du zygote fécondé", "La rupture du follicule ovarien au moment de l'ovulation"], 0,
     "Elle survient environ une semaine après la fécondation."],
    ["Quelle est la durée moyenne d'une grossesse humaine ?", ["Environ quarante semaines d'aménorrhée", "Environ trente-six semaines d'aménorrhée", "Environ quarante-quatre semaines", "Environ trente semaines pleines"], 0,
     "Soit environ trente-huit semaines depuis la fécondation, le décompte usuel partant des dernières règles."],
    ["Quel rôle joue le placenta ?", ["Il assure les échanges entre la mère et le fœtus", "Il protège mécaniquement le fœtus, et rien de plus", "Il produit à lui seul le liquide amniotique", "Il filtre absolument toutes les substances nocives"], 0,
     "Il laisse passer de nombreuses substances, dont l'alcool et certains médicaments."],
    ["Qu'est-ce que l'ovulation ?", ["La libération d'un ovocyte par l'ovaire", "La formation d'un ovule dans l'ovaire", "La fécondation d'un ovocyte par un spermatozoïde", "La maturation de l'endomètre avant les règles"], 0,
     "Elle survient environ quatorze jours avant les règles suivantes, non au quatorzième jour du cycle."],
    ["Combien d'ovocytes une femme possède-t-elle à la naissance ?", ["Environ un à deux millions", "Environ quatre cents", "Environ dix mille", "Ils se forment après la puberté"], 0,
     "Leur nombre décroît continuellement ; quelques centaines seulement seront ovulés."],
    ["Qu'est-ce que la fécondation in vitro ?", ["Une fécondation réalisée en laboratoire avant transfert dans l'utérus", "Une insémination artificielle pratiquée directement dans l'utérus maternel", "Un don d'embryon congelé par un autre couple", "Une stimulation ovarienne par traitement hormonal"], 0,
     "Le premier bébé né par cette technique, Louise Brown, est né en 1978."],
    ["Qu'est-ce que le diagnostic prénatal ?", ["La recherche d'anomalies chez le fœtus pendant la grossesse", "Un test de grossesse précoce réalisé à la maison", "Un dépistage génétique pratiqué sur les deux parents avant conception", "Un examen complet du nouveau-né à la maternité"], 0,
     "Échographies, marqueurs sériques et analyse d'ADN fœtal circulant en sont les principaux outils."],
    ["Qu'est-ce que la ménopause ?", ["L'arrêt définitif des cycles ovulatoires", "Une baisse temporaire de fertilité", "Une chute des œstrogènes réversible", "Un arrêt des règles de plus de trois mois"], 0,
     "Elle est constatée rétrospectivement après douze mois consécutifs sans règles, en moyenne vers cinquante et un ans.", 3],
  ]),

  notion("sv2-genetique-maladies", S, "Génétique et maladies héréditaires",
    "Dominance, récessivité, chromosomes sexuels : comment se transmettent les maladies.",
    "Une maladie récessive peut sauter des générations sans jamais disparaître.",
    2, [
    ["Qu'est-ce qu'une maladie autosomique récessive ?", ["Elle ne s'exprime que si les deux allèles sont atteints", "Elle se transmet par le père et par lui seul", "Elle apparaît sans aucune exception à chacune des générations suivantes", "Elle touche uniquement les garçons nés dans la famille"], 0,
     "Les parents porteurs sains ont un risque sur quatre d'avoir un enfant atteint à chaque grossesse."],
    ["Quelle maladie génétique fréquente en Europe touche les poumons et le pancréas ?", ["La mucoviscidose", "La drépanocytose", "L'hémophilie", "La myopathie de Duchenne"], 0,
     "Environ une naissance sur quatre mille en France. L'espérance de vie a beaucoup progressé depuis les années 1980."],
    ["Quelle maladie génétique déforme les globules rouges en faucille ?", ["La drépanocytose", "La thalassémie", "L'hémophilie", "La maladie de Fabry"], 0,
     "La forme hétérozygote confère une protection partielle contre le paludisme, ce qui explique sa fréquence."],
    ["Pourquoi l'hémophilie touche-t-elle surtout les garçons ?", ["Le gène est porté par le chromosome X", "Le gène est porté par le chromosome Y", "Elle est liée aux hormones masculines", "Elle est transmise par le père"], 0,
     "Les filles, qui ont deux X, sont généralement porteuses sans être atteintes."],
    ["Qu'est-ce que la trisomie 21 ?", ["La présence de trois exemplaires du chromosome 21", "Une mutation ponctuelle touchant le gène numéro 21", "Une délétion d'un fragment de chromosome", "Une anomalie du nombre des chromosomes sexuels X et Y"], 0,
     "Mise en évidence en 1959 dans l'équipe de Raymond Turpin, à partir des cultures cellulaires de Marthe Gautier, et publiée avec Jérôme Lejeune. Le risque augmente avec l'âge maternel."],
    ["Qu'est-ce qu'une mutation ?", ["Une modification de la séquence de l'ADN", "Une maladie génétique héritée des parents", "Un changement dans l'expression d'un gène", "Une recombinaison entre deux chromosomes"], 0,
     "La plupart sont neutres ; certaines sont délétères, d'autres avantageuses."],
    ["Qu'est-ce qu'un conseil génétique ?", ["Une consultation évaluant le risque de transmission d'une maladie", "Un test ADN destiné à établir une filiation", "Une thérapie génique destinée à corriger un gène défectueux du patient", "Un dépistage néonatal réalisé sur le nouveau-né à la maternité"], 0,
     "Il combine analyse de l'arbre généalogique, examens et information des personnes concernées."],
    ["Qu'est-ce que la thérapie génique ?", ["L'introduction d'un gène fonctionnel pour corriger une maladie", "La modification du génome transmise ensuite à tous les descendants", "Un traitement hormonal ciblé sur une glande malade", "Une greffe de cellules souches prélevées chez un donneur compatible"], 0,
     "Les premiers succès durables concernent des déficits immunitaires et certaines maladies du sang."],
    ["Qu'est-ce que le dépistage néonatal en France ?", ["Un test systématique de plusieurs maladies à la naissance", "Un examen clinique complet du nouveau-né réalisé à la maternité", "Un test génétique pratiqué sur les deux parents", "Une échographie de contrôle pratiquée au dernier trimestre"], 0,
     "Réalisé par une goutte de sang au talon, il porte aujourd'hui sur plus d'une dizaine de maladies."],
    ["Qu'est-ce que la pénétrance d'un gène ?", ["La proportion de porteurs qui développent effectivement le caractère", "La force avec laquelle un gène s'exprime chez chacun de ses porteurs sains", "Le nombre de copies du gène présentes dans le génome", "La vitesse de transmission du gène dans l'ensemble d'une population"], 0,
     "Une pénétrance incomplète explique qu'un porteur d'une mutation puisse rester indemne toute sa vie.", 3],
  ]),

  notion("sv2-ecosystemes", S, "Les écosystèmes",
    "Chaînes alimentaires, cycles, équilibres : comment fonctionne un milieu.",
    "L'énergie se perd à chaque niveau d'une chaîne alimentaire, ce qui limite le nombre de maillons.",
    2, [
    ["Qu'est-ce qu'un écosystème ?", ["L'ensemble d'un milieu et des êtres vivants qui l'occupent, avec leurs interactions", "Une communauté d'espèces animales et végétales vivant côte à côte dans une même région", "Un milieu physique donné, avec son sol, son climat et son relief", "Une chaîne alimentaire complète, du producteur au grand prédateur"], 0,
     "Le terme est forgé en 1935 par le botaniste Arthur Tansley."],
    ["Qu'est-ce qu'un producteur primaire ?", ["Un organisme fabriquant sa matière organique à partir de minéraux", "Un herbivore consommant directement les végétaux qui poussent dans le milieu", "Un décomposeur recyclant les débris organiques du sol", "Un prédateur de premier niveau chassant les petits herbivores du milieu"], 0,
     "Plantes, algues et certaines bactéries. Ils sont à la base de presque toutes les chaînes alimentaires."],
    ["Quelle proportion d'énergie passe environ d'un niveau trophique au suivant ?", ["Environ dix pour cent", "Environ cinquante pour cent", "Environ quatre-vingts pour cent", "La totalité"], 0,
     "C'est pourquoi les chaînes dépassent rarement quatre ou cinq maillons."],
    ["Quel rôle jouent les décomposeurs ?", ["Ils recyclent la matière organique morte en minéraux", "Ils consomment les végétaux vivants du milieu", "Ils fixent l'azote de l'air et l'incorporent au sol cultivé", "Ils produisent l'oxygène dissous dans les eaux de surface"], 0,
     "Bactéries, champignons et petits invertébrés du sol assurent cette fonction essentielle."],
    ["Qu'est-ce qu'une espèce clé de voûte ?", ["Une espèce dont la disparition bouleverse tout l'écosystème", "L'espèce la plus abondante en nombre d'individus dans le milieu", "Le prédateur situé au sommet de la chaîne alimentaire", "L'espèce la plus anciennement installée dans le milieu naturel"], 0,
     "La réintroduction du loup à Yellowstone a fourni un cas d'école, quoique parfois surinterprété."],
    ["Qu'est-ce que la bioaccumulation ?", ["La concentration croissante d'un polluant le long d'une chaîne alimentaire", "L'accumulation de biomasse végétale au fil des saisons", "La croissance d'une population animale jusqu'à la saturation complète du milieu", "Le stockage durable du carbone par les sols et par les grandes forêts du globe"], 0,
     "Le DDT et le mercure en fournissent des exemples classiques chez les prédateurs supérieurs."],
    ["Qu'est-ce qu'une succession écologique ?", ["L'évolution progressive d'un milieu vers un état plus stable", "Le remplacement d'une espèce par une autre au même endroit", "La migration saisonnière des espèces d'un milieu à l'autre", "L'alternance régulière des saisons dans un même milieu naturel"], 0,
     "Une friche devient lande, puis fourré, puis forêt, si rien ne l'interrompt."],
    ["Qu'est-ce qu'une niche écologique ?", ["L'ensemble des conditions et ressources qu'une espèce exploite", "L'habitat physique dans lequel vit habituellement une espèce donnée", "Le territoire défendu par un individu contre ses rivaux", "L'abri creusé ou construit par un animal pour se protéger du froid"], 0,
     "Deux espèces ne peuvent occuper durablement exactement la même niche au même endroit."],
    ["Qu'est-ce que l'eutrophisation ?", ["Un enrichissement excessif d'un milieu aquatique en nutriments", "Un appauvrissement naturel du milieu aquatique en oxygène dissous", "Un réchauffement des eaux de surface dû au climat", "Une acidification des lacs provoquée par les pluies chargées de soufre"], 0,
     "Nitrates et phosphates provoquent une prolifération d'algues, dont la décomposition asphyxie le milieu."],
    ["Qu'est-ce qu'un service écosystémique ?", ["Un bénéfice que les humains tirent du fonctionnement d'un écosystème", "Un aménagement écologique réalisé pour restaurer un milieu", "Un dispositif réglementaire de protection des espèces les plus menacées", "Une compensation environnementale exigée après la destruction d'un milieu"], 0,
     "Pollinisation, épuration de l'eau, régulation du climat : leur évaluation monétaire reste discutée.", 3],
  ]),

  notion("sv2-comportement-animal", S, "Le comportement animal",
    "Instinct, apprentissage, communication : ce que font les animaux et pourquoi.",
    "Attribuer des intentions humaines aux animaux est un biais, mais leur en refuser toutes en est un autre.",
    2, [
    ["Qu'est-ce que l'éthologie ?", ["L'étude scientifique du comportement animal", "L'étude et la classification des espèces animales", "L'étude des écosystèmes et des relations entre espèces", "L'étude de la domestication des animaux par l'homme"], 0,
     "Konrad Lorenz, Nikolaas Tinbergen et Karl von Frisch ont reçu le Nobel pour cette discipline en 1973."],
    ["Qu'est-ce que l'empreinte étudiée par Konrad Lorenz ?", ["L'attachement précoce d'un jeune au premier objet mobile qu'il perçoit", "Une marque odorante laissée pour délimiter un territoire", "Une mémoire olfactive du lieu de naissance de l'animal", "Une trace que l'animal laisse derrière lui en se déplaçant"], 0,
     "Ses oies cendrées le suivaient comme leur mère, ce qui rendit l'expérience célèbre."],
    ["Que découvre Karl von Frisch sur les abeilles ?", ["Elles communiquent la position des fleurs par une danse", "Elles reconnaissent leur reine à son odeur particulière", "Elles mémorisent des repères visuels sur le trajet du retour", "Elles suivent les lignes du champ magnétique terrestre"], 0,
     "La direction et la durée de la danse codent l'angle par rapport au soleil et la distance."],
    ["Qu'est-ce qu'un réflexe conditionné ?", ["Une réponse apprise par association répétée entre deux stimuli", "Un réflexe inné, présent dès la naissance de l'animal", "Une réaction de fuite déclenchée par un danger soudain", "Une habitude motrice acquise par la seule répétition du geste"], 0,
     "Pavlov l'a mis en évidence chez le chien à la fin du XIXe siècle."],
    ["Qu'est-ce que le conditionnement opérant ?", ["Un apprentissage par les conséquences de ses propres actions", "Un apprentissage par imitation", "Une association apprise entre deux stimuli présentés ensemble", "Un réflexe inné que la répétition vient renforcer"], 0,
     "Décrit par Skinner : le comportement suivi d'une récompense se répète, celui suivi d'une punition s'éteint."],
    ["Qu'est-ce que le test du miroir ?", ["Une épreuve mesurant la reconnaissance de soi", "Un test mesurant l'acuité visuelle de l'animal", "Un test mesurant la mémoire des lieux chez l'animal", "Une évaluation du degré de sociabilité de l'animal"], 0,
     "Grands singes, dauphins, éléphants et pies l'ont passé, avec des débats sur l'interprétation."],
    ["Qu'est-ce que l'altruisme de parentèle ?", ["Un comportement coûteux favorisant des individus apparentés", "Un altruisme exercé indifféremment envers tous ses congénères", "Une coopération durable entre deux espèces différentes", "Un partage du territoire entre plusieurs individus"], 0,
     "Il s'explique par le partage de gènes : aider un frère revient en partie à propager ses propres gènes."],
    ["Qu'est-ce que la migration animale ?", ["Un déplacement saisonnier régulier entre deux zones", "Une dispersion aléatoire des individus dans toutes les directions", "Un changement définitif d'habitat, sans retour possible", "Un déplacement provoqué par l'apparition soudaine d'un danger"], 0,
     "La sterne arctique effectue chaque année un aller-retour entre les deux pôles."],
    ["Comment les oiseaux migrateurs s'orientent-ils ?", ["Par une combinaison de repères solaires, stellaires et magnétiques", "Par la seule mémoire du trajet parcouru à l'aller", "En suivant exclusivement le tracé des côtes maritimes", "Par le seul odorat, en suivant les odeurs du parcours"], 0,
     "La perception du champ magnétique impliquerait des protéines photosensibles de la rétine."],
    ["Qu'est-ce que l'anthropomorphisme en éthologie ?", ["L'attribution abusive de traits humains aux animaux", "L'étude comparée des comportements de l'homme et de l'animal", "La domestication progressive d'espèces restées sauvages", "L'observation des animaux dans leur milieu naturel"], 0,
     "Le biais inverse, refuser toute continuité entre humains et animaux, s'appelle l'anthropodéni.", 3],
  ]),

  notion("sv2-vegetaux-cultures", S, "Les plantes cultivées",
    "Domestication, sélection, diversité : d'où viennent nos aliments végétaux.",
    "Presque toutes nos plantes cultivées ont été profondément transformées par des millénaires de sélection.",
    2, [
    ["De quelle plante sauvage le maïs descend-il ?", ["La téosinte", "Le sorgho sauvage", "Le millet", "Le blé sauvage"], 0,
     "Ses épis mesuraient quelques centimètres. La domestication au Mexique remonte à environ neuf mille ans."],
    ["Quelle plante a donné le chou, le brocoli, le chou-fleur et le chou de Bruxelles ?", ["Le chou sauvage", "La moutarde des champs", "Le navet cultivé", "Le colza d'hiver"], 0,
     "Une même espèce, sélectionnée sur des organes différents : bourgeon, fleur, tige ou feuille."],
    ["D'où la pomme de terre est-elle originaire ?", ["Des Andes", "D'Irlande", "D'Europe centrale", "D'Asie centrale"], 0,
     "Des milliers de variétés y sont encore cultivées. L'Europe n'en a longtemps utilisé que quelques-unes."],
    ["Quelle catastrophe frappe l'Irlande à partir de 1845 ?", ["La grande famine due au mildiou de la pomme de terre", "Une invasion de criquets venus d'Afrique du Nord", "Une sécheresse prolongée de plusieurs étés de suite", "Une épidémie de peste bovine décimant tous les troupeaux du pays"], 0,
     "La dépendance à une seule variété a rendu la population extrêmement vulnérable."],
    ["Qu'est-ce qu'une variété hybride F1 ?", ["Le croisement de deux lignées pures, très homogène mais non reproductible", "Une variété génétiquement modifiée en laboratoire par une transgenèse ciblée", "Une variété ancienne sélectionnée par les paysans au fil du temps", "Un croisement entre deux espèces différentes du même genre"], 0,
     "Les graines récoltées sur une F1 ne redonnent pas la même plante, ce qui oblige à en racheter chaque année."],
    ["Qu'est-ce qu'une variété population ?", ["Une variété génétiquement diverse, reproductible par le cultivateur", "Une variété cultivée à très grande échelle dans plusieurs pays", "Une variété de terroir protégée par une appellation d'origine contrôlée", "Une variété inscrite au catalogue officiel des semences"], 0,
     "Sa diversité interne lui donne une meilleure capacité d'adaptation, au prix d'une moindre homogénéité."],
    ["Qu'est-ce que le catalogue officiel des espèces et variétés ?", ["Un registre conditionnant la commercialisation des semences", "Un inventaire scientifique des variétés cultivées en France", "Une liste des variétés protégées par un certificat d'obtention", "Un catalogue commercial édité par les semenciers"], 0,
     "Ses critères d'homogénéité et de stabilité ont longtemps exclu les variétés paysannes."],
    ["Qu'est-ce que la banque de semences du Svalbard ?", ["Un dépôt mondial de graines conservé dans le permafrost arctique", "Une collection botanique norvégienne ouverte aux visiteurs", "Une réserve nationale de semences gérée par l'État norvégien", "Un laboratoire de sélection variétale installé au-delà du cercle polaire"], 0,
     "Ouverte en 2008, elle conserve des duplicatas de collections du monde entier en cas de catastrophe."],
    ["Qu'est-ce que la pollinisation par les insectes rapporte à l'agriculture ?", ["Une part importante des rendements de nombreuses cultures", "Un effet négligeable sur les rendements des grandes cultures", "Un rôle limité aux seuls fruits exotiques importés", "Un effet limité aux fleurs ornementales des jardins"], 0,
     "Environ trois quarts des espèces cultivées en dépendent au moins partiellement."],
    ["Pourquoi les populations d'insectes pollinisateurs déclinent-elles ?", ["Pesticides, perte d'habitat, parasites et changement climatique combinés", "Les seuls pesticides employés en agriculture intensive", "Le seul réchauffement du climat au cours des dernières décennies", "La seule concurrence des abeilles domestiques élevées dans les ruchers voisins"], 0,
     "Aucun facteur unique n'explique le phénomène ; leur combinaison est aujourd'hui bien documentée.", 3],
  ]),

  notion("sv2-champignons", S, "Les champignons",
    "Ni plantes ni animaux : un règne à part, essentiel aux écosystèmes.",
    "Les champignons sont plus proches des animaux que des plantes.",
    2, [
    ["À quel règne les champignons appartiennent-ils ?", ["Un règne distinct des plantes et des animaux", "Au règne végétal, au même titre que les plantes vertes", "Au règne animal, comme les invertébrés", "Aux protistes unicellulaires des eaux douces"], 0,
     "Ils sont phylogénétiquement plus proches des animaux que des plantes."],
    ["Pourquoi les champignons ne font-ils pas de photosynthèse ?", ["Ils ne possèdent pas de chlorophylle", "Ils vivent entièrement sous terre", "Ils manquent de feuilles pour capter la lumière", "Ils absorbent le dioxyde de carbone autrement"], 0,
     "Ils se nourrissent en absorbant des molécules organiques, comme les animaux, mais par digestion externe."],
    ["Qu'est-ce que le mycélium ?", ["Le réseau de filaments qui constitue le corps du champignon", "Le chapeau visible du champignon, au-dessus du sol", "Les spores en cours de germination dans le sol", "La racine par laquelle le champignon puise l'eau et les sels du sol"], 0,
     "Ce que l'on ramasse n'est que l'organe reproducteur d'un organisme souvent bien plus vaste."],
    ["De quoi est faite la paroi des cellules de champignons ?", ["De chitine", "De cellulose", "De lignine", "De peptidoglycane"], 0,
     "La chitine constitue aussi la carapace des insectes, indice de leur parenté avec les animaux."],
    ["Pourquoi les lichens servent-ils d'indicateurs de la qualité de l'air ?", ["Ils absorbent directement les polluants atmosphériques faute de racines", "Ils changent nettement de couleur selon le niveau de pollution de l'air ambiant", "Ils ne poussent qu'en ville, sur les murs et les toits", "Ils fixent tout le dioxyde de carbone présent en excès dans l'air"], 0,
     "Sans système racinaire ni cuticule protectrice, ils accumulent ce que l'air transporte. Certaines espèces disparaissent au premier signe de pollution soufrée."],
    ["Quel champignon microscopique permet la fabrication du pain et du vin ?", ["La levure de boulanger", "Le pénicillium des fromages", "L'aspergillus des greniers", "Le botrytis de la vigne"], 0,
     "Saccharomyces cerevisiae, l'un des organismes les plus étudiés en biologie."],
    ["Quel champignon confère au roquefort ses veines bleues ?", ["Penicillium roqueforti", "Aspergillus niger, moisissure noire", "Botrytis cinerea, moisissure grise", "Rhizopus, moisissure du pain"], 0,
     "Le camembert doit sa croûte à Penicillium camemberti, une espèce voisine."],
    ["Quel champignon est responsable de la pourriture noble du raisin ?", ["Botrytis cinerea", "Penicillium expansum", "Aspergillus flavus", "Fusarium"], 0,
     "Dans certaines conditions climatiques, il concentre les sucres et permet les vins liquoreux."],
    ["Qu'est-ce qu'une mycotoxine ?", ["Une substance toxique produite par certains champignons", "Un venin injecté par un champignon vénéneux", "Un antibiotique produit par un champignon du sol", "Un allergène contenu dans les spores en suspension dans l'air"], 0,
     "L'aflatoxine, produite sur les arachides et les céréales mal conservées, est un puissant cancérogène."],
    ["Quel champignon vénéneux est responsable de la majorité des intoxications mortelles ?", ["L'amanite phalloïde", "L'amanite tue-mouches", "Le bolet de Satan", "L'entolome livide"], 0,
     "Les symptômes n'apparaissent qu'après six à douze heures, quand les toxines ont déjà atteint le foie.", 3],
  ]),

  notion("sv2-oceans-vie", S, "La vie marine",
    "Plancton, poissons, mammifères marins : la biodiversité des océans.",
    "Le plancton produit environ la moitié de l'oxygène que nous respirons.",
    2, [
    ["Qu'est-ce que le phytoplancton ?", ["Des organismes végétaux microscopiques en suspension dans l'eau", "Des larves de poissons dérivant au gré des courants marins de surface", "Des algues fixées au fond, près du rivage", "Des bactéries marines vivant en pleine eau"], 0,
     "Il produit une part considérable de l'oxygène atmosphérique et est à la base des chaînes alimentaires marines."],
    ["De quoi la baleine bleue se nourrit-elle ?", ["De krill, de minuscules crustacés", "De gros poissons de pleine eau", "De calmars géants des abysses", "De plancton végétal filtré en surface"], 0,
     "Elle en filtre plusieurs tonnes par jour à travers ses fanons. Le plus grand animal du monde vit des plus petits."],
    ["Qu'est-ce que le krill ?", ["De petits crustacés formant d'immenses bancs", "Un plancton végétal des eaux froides", "Une larve de poisson des mers australes", "Un mollusque des grands fonds, dépourvu de coquille"], 0,
     "Il constitue une biomasse considérable et la base du régime de nombreuses baleines."],
    ["Quel est le plus grand poisson du monde ?", ["Le requin baleine", "Le grand requin blanc", "La raie manta", "Le poisson-lune"], 0,
     "Jusqu'à dix-huit mètres. Comme la baleine bleue, il est planctonophage et inoffensif."],
    ["Qu'est-ce que la zone abyssale ?", ["Les profondeurs océaniques au-delà de deux mille mètres", "Le fond du plateau continental, près des côtes", "La zone de pénombre où la lumière s'éteint", "Les seules fosses océaniques les plus profondes de tout le globe"], 0,
     "Sans lumière, sous une pression énorme, elle abrite pourtant une faune abondante."],
    ["Qu'est-ce qu'une source hydrothermale ?", ["Une émission d'eau chaude minéralisée au fond des océans", "Un geyser sous-marin projetant du gaz", "Une remontée d'eau douce au fond de la mer", "Une faille volcanique émergée qui domine largement les flots"], 0,
     "Les écosystèmes qui s'y développent reposent sur la chimiosynthèse, non sur la lumière."],
    ["Qu'est-ce que la bioluminescence ?", ["La production de lumière par un organisme vivant", "La réflexion de la lumière du jour par les écailles", "La fluorescence des tissus sous un ultraviolet", "L'éclat des minéraux marins dans l'obscurité"], 0,
     "Elle est très répandue en profondeur : une majorité d'organismes des grands fonds en sont capables."],
    ["Qu'est-ce que la surpêche ?", ["Un prélèvement supérieur à la capacité de renouvellement des stocks", "Une pêche pratiquée en dehors de toute légalité", "Une pêche industrielle menée à très grande échelle par des chalutiers", "Une pêche pratiquée hors de la saison autorisée"], 0,
     "Une part importante des stocks mondiaux évalués est exploitée à la limite ou au-delà."],
    ["Qu'est-ce que le chalutage de fond ?", ["Une technique traînant un filet sur le fond marin", "Une pêche à la ligne pratiquée dans les eaux profondes", "Un filet dérivant librement en surface", "Une pêche au casier posé sur le fond"], 0,
     "Il est très critiqué pour la destruction des habitats et l'importance des captures accessoires."],
    ["Qu'est-ce que l'acidification des océans ?", ["Une baisse du pH due à l'absorption du CO2 atmosphérique", "Une pollution provoquée par les rejets industriels côtiers", "Un effet direct des pluies acides sur la mer", "Une conséquence directe des grandes marées noires"], 0,
     "Elle fragilise les organismes à squelette calcaire : coraux, mollusques et certains planctons.", 3],
  ]),

  notion("sv2-paleontologie", S, "Les fossiles et la vie passée",
    "Comment on lit l'histoire de la vie dans les roches.",
    "Seule une fraction infime des êtres vivants a été fossilisée.",
    2, [
    ["Qu'est-ce qu'un fossile ?", ["Un reste ou une trace d'un organisme conservé dans les roches", "Un os très ancien retrouvé lors d'une fouille", "Une empreinte fraîche laissée dans le sol meuble", "Un minéral d'origine biologique cristallisé au cœur d'une roche"], 0,
     "Empreintes de pas, terriers et coprolithes sont aussi des fossiles, dits de trace."],
    ["Pourquoi la fossilisation est-elle rare ?", ["Elle exige un enfouissement rapide dans des conditions particulières", "Les os des animaux se minéralisent très difficilement", "Les roches finissent toujours par détruire les restes", "Les organismes sont presque toujours trop petits pour pouvoir se conserver"], 0,
     "Les milieux aquatiques sédimentaires y sont bien plus favorables que les milieux terrestres."],
    ["Qu'est-ce qu'un fossile stratigraphique ?", ["Une espèce très répandue et de courte durée, utile pour dater les couches", "Le fossile le plus ancien que renferme une couche sédimentaire, tout en bas", "Un fossile trouvé en position verticale dans la strate", "Un fossile de très grande taille, visible à l'œil nu dans la roche"], 0,
     "Ammonites et foraminifères en sont des exemples classiques."],
    ["Quel animal marin en spirale est un fossile guide du Mésozoïque ?", ["L'ammonite", "Le trilobite", "Le brachiopode", "Le crinoïde"], 0,
     "Le trilobite caractérise plutôt le Paléozoïque."],
    ["Quand les dinosaures non aviens disparaissent-ils ?", ["Il y a environ soixante-six millions d'années", "Il y a environ dix millions d'années", "Il y a environ deux cent cinquante millions d'années", "Il y a un peu plus d'un million d'années"], 0,
     "La limite Crétacé-Paléogène, marquée par une couche riche en iridium sur toute la planète."],
    ["Quelle est la cause principale retenue de l'extinction des dinosaures ?", ["L'impact d'un astéroïde au Yucatán", "Une glaciation généralisée", "Une épidémie", "Une baisse du niveau des mers seule"], 0,
     "Le volcanisme massif du Deccan, contemporain, aurait aggravé la crise."],
    ["Qu'est-ce que l'explosion cambrienne ?", ["Une diversification rapide des formes animales il y a environ 540 millions d'années", "Une extinction massive des premières formes de vie marine", "Une éruption volcanique majeure ayant obscurci le ciel pendant des millions d'années", "L'apparition des toutes premières cellules vivantes sur la Terre"], 0,
     "La plupart des grands plans d'organisation animale actuels y apparaissent dans un intervalle géologiquement bref."],
    ["Quel gisement canadien est célèbre pour ses fossiles cambriens à corps mou ?", ["Les schistes de Burgess", "La formation de Morrison", "Le bassin de Karoo", "Le gisement de Solnhofen"], 0,
     "Découvert en 1909, il conserve des organismes dépourvus de squelette, exceptionnellement préservés."],
    ["Quel fossile allemand présente à la fois des plumes et des dents ?", ["L'Archaeopteryx", "Le Ptérodactyle", "Le Compsognathus", "L'Iguanodon"], 0,
     "Découvert en 1861, deux ans après L'Origine des espèces, il fut aussitôt utilisé comme preuve de l'évolution."],
    ["Comment date-t-on les roches très anciennes ?", ["Par la désintégration d'isotopes radioactifs à longue période", "Par le carbone 14 contenu dans la roche", "Par la seule épaisseur des couches empilées", "Par la seule comparaison des fossiles que ces roches anciennes renferment"], 0,
     "Uranium-plomb ou potassium-argon permettent de remonter à des milliards d'années.", 3],
  ]),

  notion("sv2-neurosciences", S, "Le système nerveux",
    "Neurones, sens, réflexes : comment l'information circule dans le corps.",
    "Le système nerveux autonome fonctionne sans intervention de la volonté.",
    2, [
    ["Quelles sont les deux grandes divisions du système nerveux ?", ["Le système nerveux central et le système nerveux périphérique", "Le cerveau, le cervelet et la moelle épinière", "Le système volontaire d'un côté, le système involontaire de l'autre", "Les nerfs, les ganglions et les plexus nerveux"], 0,
     "Le central comprend l'encéphale et la moelle épinière, le périphérique les nerfs et ganglions."],
    ["Que fait le système nerveux sympathique ?", ["Il prépare l'organisme à l'action et au stress", "Il favorise la digestion et le repos de l'organisme", "Il contrôle tous les mouvements volontaires du corps", "Il transmet les sensations vers le cerveau"], 0,
     "Le parasympathique agit en sens inverse : ralentissement du cœur, stimulation digestive."],
    ["Qu'est-ce qu'un arc réflexe ?", ["Un circuit court passant par la moelle sans décision du cerveau", "Un réflexe appris à force de répétitions", "Une réaction émotionnelle rapide et incontrôlée", "Un mouvement rendu entièrement automatique par un long entraînement"], 0,
     "C'est ce qui permet de retirer la main d'une source brûlante avant même d'avoir senti la douleur."],
    ["À quelle vitesse l'influx nerveux se propage-t-il au maximum ?", ["Environ cent vingt mètres par seconde", "Environ dix mètres par seconde au plus", "À la vitesse du son dans l'air", "À la vitesse de la lumière dans le vide"], 0,
     "La gaine de myéline accélère considérablement la conduction en la rendant saltatoire."],
    ["Quel est le rôle de la myéline ?", ["Isoler l'axone et accélérer la conduction nerveuse", "Nourrir le neurone et lui fournir toute l'énergie nécessaire", "Produire les neurotransmetteurs de la synapse", "Relier deux neurones voisins l'un à l'autre"], 0,
     "La sclérose en plaques résulte de sa destruction par le système immunitaire."],
    ["Combien de sens l'être humain possède-t-il ?", ["Plus que les cinq traditionnels, dont l'équilibre et la proprioception", "Exactement cinq, ni plus ni moins, comme on l'apprend à l'école primaire", "Six, en comptant l'intuition parmi les sens", "Quatre seulement, l'odorat n'en étant pas un"], 0,
     "La proprioception, sens de la position du corps, est essentielle et pourtant rarement citée."],
    ["Qu'est-ce que la proprioception ?", ["La perception de la position et du mouvement de son propre corps", "La perception de la douleur par les terminaisons nerveuses de la peau", "Le sens de l'équilibre logé dans l'oreille interne", "La perception de la température par la peau"], 0,
     "Elle permet de toucher son nez les yeux fermés."],
    ["Où se situe l'organe de l'équilibre ?", ["Dans l'oreille interne", "Dans le cervelet", "Dans l'oreille moyenne", "Dans le tronc cérébral"], 0,
     "Le système vestibulaire, fait de canaux semi-circulaires remplis de liquide."],
    ["Qu'est-ce qu'un neurotransmetteur ?", ["Une molécule qui transmet le signal d'un neurone à un autre", "Un canal ionique percé dans la membrane du neurone qui reçoit", "Une protéine constitutive de la gaine de myéline", "Une hormone cérébrale déversée dans le sang"], 0,
     "Dopamine, sérotonine, acétylcholine et GABA comptent parmi les plus connus."],
    ["Quel neurotransmetteur est particulièrement associé à la récompense et à la motivation ?", ["La dopamine", "La sérotonine", "L'acétylcholine", "Le GABA"], 0,
     "La maladie de Parkinson résulte de la dégénérescence de neurones dopaminergiques.", 3],
  ]),

  notion("sv2-sommeil-rythmes", S, "Sommeil et horloge biologique",
    "Horloge interne, cycles, effets de la privation.",
    "L'horloge biologique tourne sur un cycle légèrement supérieur à vingt-quatre heures, recalé chaque jour par la lumière.",
    2, [
    ["Qu'est-ce qu'un rythme circadien ?", ["Un cycle biologique d'environ vingt-quatre heures", "Un cycle mensuel calé sur les phases de la lune", "Un cycle saisonnier suivant la longueur des jours", "Un cycle de quatre-vingt-dix minutes répété toute la nuit"], 0,
     "Le mot vient du latin circa diem, environ un jour."],
    ["Où se situe l'horloge biologique principale du corps humain ?", ["Dans l'hypothalamus", "Dans l'épiphyse", "Dans le tronc cérébral", "Dans l'hypophyse"], 0,
     "Le noyau suprachiasmatique reçoit directement l'information lumineuse depuis la rétine."],
    ["Quelle est la durée approximative d'un cycle de sommeil ?", ["Environ quatre-vingt-dix minutes", "Environ trente minutes, quatre fois par nuit", "Environ trois heures pleines", "Environ soixante minutes en moyenne"], 0,
     "Une nuit compte quatre à six cycles enchaînés."],
    ["Que caractérise le sommeil paradoxal ?", ["Une activité cérébrale intense avec atonie musculaire", "Un sommeil très profond dont on se réveille difficilement", "Un endormissement léger juste après le coucher", "Un réveil partiel accompagné de mouvements du corps"], 0,
     "C'est la phase où les rêves sont les plus élaborés et les plus facilement mémorisés."],
    ["Quelle phase du sommeil est la plus réparatrice physiquement ?", ["Le sommeil lent profond", "Le sommeil paradoxal des fins de nuit", "Le sommeil léger du début de nuit", "La phase d'endormissement"], 0,
     "Elle domine en début de nuit et diminue au fil des cycles."],
    ["Quel effet la lumière bleue des écrans a-t-elle le soir ?", ["Elle retarde la sécrétion de mélatonine", "Elle fatigue seulement les yeux, sans toucher le sommeil", "Elle stimule le sommeil lent profond de début de nuit", "Elle n'a aucun effet démontré sur l'organisme"], 0,
     "L'effet mesuré est réel mais son ampleur varie beaucoup selon l'intensité et la durée d'exposition."],
    ["Combien d'heures de sommeil un adulte a-t-il besoin en moyenne ?", ["Entre sept et neuf heures", "Environ cinq heures par nuit", "Environ dix heures par nuit", "Environ six heures par nuit"], 0,
     "Les besoins varient d'une personne à l'autre, mais très peu d'adultes fonctionnent bien sous six heures."],
    ["Quel est l'effet d'une dette de sommeil chronique ?", ["Une dégradation de l'attention, de la mémoire et de la santé métabolique", "Une simple somnolence passagère qui se dissipe dans la journée", "Un effet limité aux seules performances physiques et sportives", "Aucun effet dès lors que l'on récupère le week-end et pendant les congés"], 0,
     "La récupération de fin de semaine ne compense que partiellement les déficits accumulés."],
    ["Qu'est-ce que le décalage horaire social ?", ["L'écart entre les horaires imposés en semaine et le rythme naturel du corps", "Le décalage ressenti après un vol entre deux fuseaux horaires", "Le travail de nuit régulier imposé par certains métiers", "Un trouble pathologique du rythme circadien diagnostiqué par un médecin du sommeil"], 0,
     "Il concerne particulièrement les adolescents, dont l'horloge se décale naturellement vers le tard."],
    ["Qu'est-ce que le travail posté fait au risque sanitaire ?", ["Il augmente les risques cardiovasculaires et métaboliques", "Il n'a aucun effet mesuré sur la santé des travailleurs", "Il n'affecte que la vigilance pendant les heures de travail", "Il agit uniquement sur l'humeur et le moral des salariés"], 0,
     "Le travail de nuit a été classé cancérogène probable par le Centre international de recherche sur le cancer.", 3],
  ]),

  notion("sv2-agriculture-sols", S, "Les sols",
    "Formation, fertilité, dégradation : une ressource lente à se former et rapide à perdre.",
    "Il faut plusieurs siècles pour former un centimètre de sol fertile.",
    2, [
    ["De quoi un sol est-il composé ?", ["De minéraux, de matière organique, d'eau, d'air et d'organismes vivants", "De roche broyée uniquement, sans aucun apport vivant", "De matière organique et d'eau, à l'exclusion des minéraux", "D'argile et de sable mélangés en proportions variables selon les terrains"], 0,
     "La fraction vivante, souvent oubliée, conditionne largement la fertilité."],
    ["Combien de temps faut-il pour former un centimètre de sol fertile ?", ["Plusieurs centaines d'années", "Environ dix ans", "Environ un an", "Plusieurs millénaires systématiquement"], 0,
     "La perte par érosion peut être des dizaines de fois plus rapide que la formation."],
    ["Qu'est-ce que l'humus ?", ["La matière organique décomposée et stabilisée d'un sol", "La couche superficielle de feuilles mortes non décomposées", "L'argile la plus fine contenue dans un sol", "Un engrais organique répandu sur les cultures"], 0,
     "Il retient l'eau, les nutriments et joue un rôle majeur dans le stockage du carbone."],
    ["Qu'est-ce que le complexe argilo-humique ?", ["L'association d'argile et d'humus qui retient les éléments nutritifs", "Un simple mélange de sable et d'argile, dépourvu de toute matière organique", "Une couche imperméable du sol arrêtant l'eau d'infiltration", "Un dépôt de racines décomposées au fond du profil du sol"], 0,
     "Il agit comme un garde-manger chimique en fixant les ions nutritifs et en les libérant progressivement."],
    ["Qu'est-ce que l'érosion des sols ?", ["L'entraînement des particules par l'eau ou le vent", "L'appauvrissement chimique du sol en éléments nutritifs", "Le tassement du sol par le passage des engins", "L'acidification progressive de la terre cultivée"], 0,
     "Un sol nu est bien plus vulnérable qu'un sol couvert par la végétation ou un paillage."],
    ["Qu'est-ce que le tassement du sol ?", ["Une compaction réduisant la porosité et la circulation de l'eau et de l'air", "Une érosion en profondeur emportant peu à peu les horizons inférieurs du sol", "Un dépôt de sédiments fins apporté par les crues successives", "Une baisse de la teneur en matière organique du sol cultivé"], 0,
     "Le poids croissant des engins agricoles en est une cause majeure, avec des effets durables."],
    ["Quel animal du sol est un indicateur de sa qualité biologique ?", ["Le ver de terre", "La fourmi", "Le cloporte", "Le mille-pattes"], 0,
     "Il brasse la terre, crée des galeries et enfouit la matière organique. Darwin lui a consacré son dernier livre."],
    ["Qu'est-ce que la salinisation des sols ?", ["Une accumulation de sels rendant la terre stérile", "Un apport volontaire d'engrais riches en sels minéraux", "Une acidification du sol par les pluies répétées", "Un dépôt d'embruns marins sur les terres côtières"], 0,
     "Elle résulte souvent d'une irrigation mal drainée en climat sec, et a ruiné des civilisations entières."],
    ["Qu'est-ce que la désertification ?", ["La dégradation des terres en zones sèches, souvent d'origine humaine", "L'avancée naturelle des déserts sous le seul effet du climat, sans l'homme", "Une sécheresse prolongée sur plusieurs années consécutives", "L'abandon des terres agricoles par les populations rurales"], 0,
     "Une convention des Nations unies lui est spécifiquement consacrée depuis 1994."],
    ["Quelle quantité de carbone les sols stockent-ils par rapport à l'atmosphère ?", ["Environ deux à trois fois plus", "Environ autant que l'atmosphère", "Environ dix fois moins qu'elle", "Une quantité tout à fait négligeable"], 0,
     "D'où l'intérêt des pratiques agricoles qui augmentent le stock de matière organique des sols.", 3],
  ]),

  notion("sv2-virus", S, "Les virus",
    "À la frontière du vivant : structure, réplication, épidémies.",
    "Un virus n'est pas une cellule et ne se reproduit qu'en détournant la machinerie d'une cellule hôte.",
    2, [
    ["De quoi un virus est-il constitué au minimum ?", ["D'un matériel génétique entouré d'une capside protéique", "D'une cellule dépourvue de noyau, comme une bactérie", "D'une membrane entourant un cytoplasme et ses organites", "D'une bactérie réduite à sa plus simple expression"], 0,
     "Certains possèdent en plus une enveloppe lipidique prise à la cellule hôte."],
    ["Pourquoi les antibiotiques sont-ils inefficaces contre les virus ?", ["Ils ciblent des structures que les virus ne possèdent pas", "Les virus sont trop petits pour être atteints par la molécule", "Les virus mutent trop vite pour qu'un traitement reste efficace", "Les virus sont protégés par une enveloppe que rien ne traverse"], 0,
     "Paroi bactérienne, ribosomes bactériens : rien de tout cela n'existe chez un virus."],
    ["Qu'est-ce qu'un virus à ARN ?", ["Un virus dont le génome est fait d'ARN et non d'ADN", "Un virus qui fabrique de l'ARN messager dans la cellule", "Un virus dépourvu de capside protéique protectrice", "Un virus qui n'infecte que les bactéries, et jamais les cellules"], 0,
     "Ils mutent généralement plus vite, faute de mécanisme de correction efficace."],
    ["Qu'est-ce qu'un variant viral ?", ["Une version du virus portant des mutations distinctives", "Un virus appartenant à une tout autre espèce virale", "Un virus atténué en laboratoire pour servir de vaccin", "Un virus recombiné artificiellement à partir de deux souches"], 0,
     "La plupart des mutations n'ont pas d'effet ; seules quelques-unes modifient transmissibilité ou virulence."],
    ["Qu'est-ce qu'une zoonose ?", ["Une maladie transmissible de l'animal à l'humain", "Une maladie des animaux d'élevage", "Une infection contractée au contact des animaux d'un zoo", "Une maladie transmise à l'homme par la piqûre d'un insecte"], 0,
     "La majorité des maladies infectieuses humaines émergentes sont d'origine animale."],
    ["Que mesure le taux de reproduction de base d'une épidémie ?", ["Le nombre moyen de personnes infectées par un malade dans une population non immunisée", "La vitesse à laquelle l'épidémie gagne du terrain", "La proportion de malades développant une forme grave", "Le temps au bout duquel le nombre de cas a doublé"], 0,
     "En dessous de un, l'épidémie régresse ; au-dessus, elle progresse."],
    ["Qu'est-ce que la période d'incubation ?", ["Le délai entre l'infection et l'apparition des symptômes", "La durée pendant laquelle un malade reste contagieux", "Le temps pendant lequel le virus survit hors de l'organisme", "Le délai au bout duquel l'organisme devient immunisé"], 0,
     "Elle conditionne l'efficacité des quarantaines et le traçage des contacts."],
    ["Qu'est-ce qu'un porteur asymptomatique ?", ["Une personne infectée et parfois contagieuse sans présenter de symptômes", "Une personne immunisée qui ne peut plus être infectée", "Une personne guérie et qui ne transmet plus le virus", "Une personne vaccinée contre la maladie en question"], 0,
     "Il complique considérablement le contrôle d'une épidémie."],
    ["Quel virus est responsable de la grippe saisonnière ?", ["Le virus influenza", "Le coronavirus, responsable de la Covid-19", "L'adénovirus, responsable de rhumes et de conjonctivites", "Le rhinovirus, principal responsable du rhume banal"], 0,
     "Sa capacité à muter impose une reformulation annuelle du vaccin."],
    ["Qu'est-ce qu'un réservoir viral ?", ["Une espèce hébergeant durablement un virus sans en être gravement affectée", "Un stock de souches virales conservé en laboratoire", "Une zone géographique où la maladie est endémique", "Un organe dans lequel le virus persiste après la guérison"], 0,
     "Les chauves-souris hébergent de nombreux virus qui les affectent peu, ce qui intrigue les chercheurs.", 3],
  ]),

  notion("sv2-eau-potable", S, "L'eau potable et l'assainissement",
    "Traiter, distribuer, épurer : la chaîne qui a le plus fait pour la santé publique.",
    "L'accès à l'eau potable a sauvé plus de vies que n'importe quel médicament.",
    2, [
    ["Quelle est la première étape du traitement de l'eau potable ?", ["Le dégrillage et la clarification", "La chloration de l'eau brute", "La filtration sur charbon actif en grains", "L'ozonation en bassin fermé"], 0,
     "Elle élimine les matières grossières avant les traitements plus fins."],
    ["À quoi sert la coagulation-floculation ?", ["À agglomérer les particules fines pour les décanter", "À désinfecter l'eau avant sa mise en réseau", "À enlever le calcaire dissous dans l'eau brute", "À éliminer les nitrates d'origine agricole présents dans l'eau"], 0,
     "Des sels de fer ou d'aluminium neutralisent les charges qui maintenaient les particules en suspension."],
    ["Pourquoi l'eau du robinet contient-elle du chlore ?", ["Pour maintenir une désinfection tout au long du réseau", "Pour améliorer son goût et masquer les odeurs", "Pour éliminer le calcaire qui se dépose dans les canalisations", "Pour ajuster son pH avant la mise en distribution"], 0,
     "Le chlore résiduel protège contre une contamination survenant après le traitement."],
    ["Qu'est-ce qu'une station d'épuration ?", ["Une installation traitant les eaux usées avant rejet dans le milieu", "Une usine de potabilisation traitant l'eau du fleuve avant distribution", "Un bassin de rétention des eaux de pluie en cas d'orage", "Un dispositif de dessalement de l'eau de mer par membranes"], 0,
     "Le traitement combine des procédés physiques, biologiques et parfois chimiques."],
    ["Quel rôle jouent les bactéries dans une station d'épuration ?", ["Elles dégradent la matière organique dissoute", "Elles filtrent les particules en suspension", "Elles désinfectent l'eau avant son rejet", "Elles éliminent les métaux lourds dissous dans l'eau"], 0,
     "Les boues activées sont un écosystème bactérien entretenu et aéré artificiellement."],
    ["Qu'est-ce que le dessalement de l'eau de mer ?", ["Un procédé retirant le sel pour produire de l'eau douce", "Une dilution de l'eau salée avec de l'eau de rivière", "Une filtration des sédiments marins en suspension", "Un traitement des saumures rejetées par les usines côtières"], 0,
     "L'osmose inverse domine aujourd'hui, mais reste énergivore et produit des saumures concentrées."],
    ["Qu'est-ce que l'osmose inverse ?", ["Un procédé forçant l'eau à travers une membrane retenant les sels", "Une filtration par gravité à travers un lit de sable et de graviers", "Une distillation sous vide à basse température", "Un échange d'ions sur une résine qui capte les sels"], 0,
     "Elle nécessite une pression élevée, d'où sa consommation d'énergie importante."],
    ["Qu'est-ce qu'un périmètre de protection de captage ?", ["Une zone où les activités sont réglementées autour d'un point de prélèvement", "Une clôture grillagée posée autour d'un réservoir d'eau potable", "Une zone de surveillance sanitaire où l'eau est analysée chaque semaine par l'agence", "Un secteur de distribution desservi en priorité en cas de pénurie"], 0,
     "Il vise à prévenir la contamination plutôt qu'à la traiter après coup."],
    ["Quelle part de la population mondiale n'a pas accès à un assainissement géré en toute sécurité ?", ["Environ deux personnes sur cinq", "Environ cinq pour cent", "Environ soixante-dix pour cent", "Environ dix pour cent"], 0,
     "Soit 3,4 milliards de personnes (suivi OMS/UNICEF). Les maladies diarrhéiques restent l'une des premières causes de mortalité infantile dans le monde."],
    ["Qu'est-ce qu'un polluant émergent dans l'eau ?", ["Une substance récemment détectée dont les effets sont mal connus", "Un polluant industriel classique, déjà réglementé depuis fort longtemps", "Un contaminant bactérien apparu dans le réseau de distribution", "Un métal lourd relargué par les canalisations anciennes"], 0,
     "Résidus médicamenteux, perturbateurs endocriniens et composés perfluorés en font partie.", 3],
  ]),

  notion("sv2-toxicologie", S, "Toxicologie et santé environnementale",
    "Dose, exposition, effet : comment on évalue la dangerosité d'une substance.",
    "C'est la dose qui fait le poison, mais certains effets ne suivent pas une relation dose-réponse simple.",
    2, [
    ["Quel principe fondateur de la toxicologie est attribué à Paracelse ?", ["Toute substance est un poison selon la dose", "Toute substance naturelle est sans danger", "L'effet dépend de la voie d'exposition seule", "Le poison agit indépendamment de la dose"], 0,
     "Formulé au XVIe siècle, il reste la base de l'évaluation des risques chimiques."],
    ["Qu'est-ce que la dose journalière admissible ?", ["Une quantité pouvant être ingérée quotidiennement sans risque appréciable", "La dose létale mesurée chez l'animal, divisée par cent", "La dose maximale tolérée par l'organisme en une seule prise", "Le seuil au-dessous duquel une substance n'est plus détectable par l'analyse"], 0,
     "Elle est calculée à partir d'études animales avec de larges facteurs de sécurité."],
    ["Qu'est-ce qu'un perturbateur endocrinien ?", ["Une substance interférant avec le système hormonal", "Un toxique agissant sur le système nerveux central", "Un cancérogène agissant directement sur l'ADN", "Un allergène puissant provoquant des crises d'asthme"], 0,
     "Certains agissent à très faibles doses, ce qui complique l'application du raisonnement classique par seuil."],
    ["Qu'est-ce que l'effet cocktail ?", ["L'interaction entre plusieurs substances modifiant leurs effets", "L'accumulation d'un même toxique au fil des expositions", "Un effet différé apparaissant des années plus tard", "Une réaction allergique croisée entre deux substances chimiques voisines"], 0,
     "L'évaluation réglementaire, faite substance par substance, le prend encore mal en compte."],
    ["Que classe le Centre international de recherche sur le cancer ?", ["Le niveau de preuve du caractère cancérogène d'agents", "Le niveau de risque réellement encouru par la population", "La toxicité aiguë des produits en cas d'ingestion", "Le nombre de cancers attribuables à chaque agent"], 0,
     "Une classification en groupe 1 signale une certitude sur le danger, non l'ampleur du risque."],
    ["Qu'est-ce que le principe ALARA en radioprotection ?", ["Réduire l'exposition au niveau le plus bas raisonnablement possible", "Respecter strictement la dose maximale annuelle fixée par la réglementation", "Éviter absolument toute exposition, quelle qu'elle soit", "Compenser l'exposition reçue par des périodes de repos"], 0,
     "Il reconnaît qu'aucun seuil d'innocuité absolue n'est établi pour les faibles doses."],
    ["Qu'est-ce que le saturnisme ?", ["Une intoxication au plomb", "Une intoxication au mercure", "Une intoxication à l'arsenic", "Une intoxication au cadmium"], 0,
     "Les peintures anciennes et les canalisations en sont les sources principales chez l'enfant."],
    ["Quelle catastrophe a révélé la toxicité du mercure au Japon ?", ["La maladie de Minamata", "L'accident de Bhopal", "L'affaire de Seveso", "La catastrophe de Toyama"], 0,
     "Des rejets industriels dans la baie ont contaminé les poissons et intoxiqué des milliers de personnes."],
    ["Qu'est-ce que l'amiante ?", ["Un minéral fibreux dont l'inhalation provoque des cancers", "Un isolant synthétique fabriqué à partir de pétrole", "Un composé chimique industriel obtenu par une synthèse récente", "Un dérivé du plomb utilisé dans les peintures"], 0,
     "Interdite en France en 1997, elle continue de causer des décès en raison du long délai de latence."],
    ["Qu'est-ce qu'un polluant persistant ?", ["Une substance qui se dégrade très lentement dans l'environnement", "Un polluant présent en très forte concentration dans le milieu naturel", "Un polluant émis en continu par une installation", "Un polluant toxique dès les plus faibles doses reçues"], 0,
     "Les composés perfluorés, surnommés polluants éternels, en sont l'exemple le plus discuté aujourd'hui.", 3],
  ]),

  notion("sv2-domestication", S, "La domestication des animaux",
    "Quand, où et comment les humains se sont associés à d'autres espèces.",
    "La première espèce domestiquée l'a été bien avant l'agriculture, par des chasseurs-cueilleurs.",
    2, [
    ["Quelle est la première espèce animale domestiquée ?", ["Le chien", "Le mouton", "La chèvre", "Le bœuf"], 0,
     "Il y a probablement plus de quinze mille ans, avant même le Néolithique."],
    ["De quel animal sauvage le chien descend-il ?", ["Du loup gris", "Du chacal", "Du renard", "Du coyote"], 0,
     "La divergence est ancienne et les études génétiques débattent encore du lieu et du nombre de domestications."],
    ["Où le mouton et la chèvre ont-ils été domestiqués ?", ["Au Proche-Orient", "En Asie centrale", "En Afrique du Nord", "En Europe méridionale"], 0,
     "Dans le Croissant fertile, il y a environ dix mille ans, avec les premières cultures céréalières."],
    ["Quel animal sauvage est l'ancêtre du bœuf domestique ?", ["L'aurochs", "Le bison", "Le buffle", "Le yak"], 0,
     "Le dernier aurochs est mort en Pologne en 1627."],
    ["Où le cheval a-t-il probablement été domestiqué ?", ["Dans les steppes d'Eurasie occidentale", "En Arabie", "En Mongolie orientale", "En Europe centrale"], 0,
     "Les études génétiques récentes situent l'origine des chevaux modernes dans la steppe pontique."],
    ["Quelle espèce a été domestiquée en Amérique du Sud avant l'arrivée des Européens ?", ["Le lama", "Le cheval", "Le bœuf", "Le mouton"], 0,
     "Le lama et l'alpaga, avec le cochon d'Inde et le dindon plus au nord."],
    ["Qu'est-ce que le syndrome de domestication ?", ["Un ensemble de traits communs aux espèces domestiquées", "Une maladie des animaux d'élevage", "Une dépendance comportementale à l'humain", "Une perte de fertilité"], 0,
     "Oreilles tombantes, robe tachetée, museau raccourci : ces traits apparaissent ensemble sans avoir été sélectionnés."],
    ["Quelle expérience russe a reproduit la domestication chez le renard ?", ["L'expérience de Beliaev sur les renards argentés", "L'expérience de Pavlov", "L'expérience de Lyssenko", "L'élevage de Novossibirsk sur les visons"], 0,
     "En sélectionnant uniquement la docilité, les chercheurs ont vu apparaître les traits morphologiques associés."],
    ["Quel animal a été domestiqué en Égypte et vénéré dans certains cultes ?", ["Le chat", "Le chien", "L'ibis", "Le faucon"], 0,
     "Les études génétiques suggèrent une domestication d'abord au Proche-Orient, développée ensuite en Égypte."],
    ["Quelle est la principale conséquence écologique de l'élevage mondial ?", ["Une occupation massive des terres et des émissions importantes", "Une amélioration des sols", "Une baisse de la déforestation", "Un effet neutre sur le climat"], 0,
     "L'élevage occupe la majorité des terres agricoles mondiales, pâturages et cultures fourragères comprises.", 3],
  ]),

  notion("sv2-evolution-mecanismes", S, "Les mécanismes de l'évolution",
    "Sélection, dérive, spéciation : comment les espèces changent.",
    "L'évolution n'a pas de but : elle trie ce qui existe, elle ne crée pas ce qui serait utile.",
    2, [
    ["Qui publie L'Origine des espèces en 1859 ?", ["Charles Darwin", "Alfred Russel Wallace", "Jean-Baptiste Lamarck", "Thomas Huxley"], 0,
     "Wallace était parvenu indépendamment à des conclusions voisines, ce qui précipita la publication."],
    ["Que propose Lamarck avant Darwin ?", ["La transmission des caractères acquis", "La sélection naturelle des plus aptes", "La dérive génétique des populations", "La spéciation par isolement géographique"], 0,
     "Sa théorie est fausse dans son mécanisme, mais il fut l'un des premiers à défendre le transformisme."],
    ["Qu'est-ce que la dérive génétique ?", ["Une variation aléatoire des fréquences d'allèles, forte dans les petites populations", "Une mutation progressive du génome au fil des générations", "Un flux de gènes entre populations voisines qui se croisent", "Une sélection agissant sur un caractère qui n'a aucun effet sur la survie des individus"], 0,
     "Elle peut fixer un allèle sans aucun avantage adaptatif, par simple hasard d'échantillonnage."],
    ["Qu'est-ce qu'un effet de fondation ?", ["La perte de diversité quand une petite population colonise un nouveau milieu", "L'apparition d'une nouvelle espèce dans un milieu déjà occupé", "Le retour spontané d'une population localement disparue", "L'établissement durable d'une espèce invasive au détriment des espèces locales"], 0,
     "Il explique la fréquence élevée de certaines maladies génétiques dans des populations isolées."],
    ["Qu'est-ce que la spéciation allopatrique ?", ["L'apparition d'espèces séparées par une barrière géographique", "Une spéciation sans le moindre isolement des populations", "Une spéciation par hybridation entre deux espèces proches voisines", "Une spéciation par doublement du nombre de chromosomes"], 0,
     "C'est le mode le mieux documenté ; la spéciation sympatrique, sans barrière, reste plus discutée."],
    ["Qu'est-ce que la sélection sexuelle ?", ["Une sélection portant sur l'accès aux partenaires plutôt que sur la survie", "La sélection des gamètes les plus vigoureux lors de la fécondation", "Le choix du moment le plus favorable de l'année pour se reproduire", "La sélection favorisant les espèces sexuées au détriment des espèces asexuées"], 0,
     "Elle explique des traits coûteux comme la queue du paon, désavantageux pour la survie."],
    ["Qu'est-ce qu'un organe vestigial ?", ["Une structure héritée ayant perdu sa fonction d'origine", "Un organe en cours de formation chez l'embryon", "Un organe atrophié à la suite d'une maladie", "Un organe apparu récemment au cours de l'évolution de l'espèce"], 0,
     "Le coccyx humain et les os pelviens des baleines en sont des exemples classiques."],
    ["Qu'est-ce que la coévolution ?", ["L'évolution réciproque de deux espèces en interaction", "L'évolution simultanée de deux populations isolées l'une de l'autre", "L'évolution convergente vers des formes semblables", "L'évolution d'un écosystème entier au fil des siècles"], 0,
     "Fleurs et pollinisateurs, prédateurs et proies en offrent de nombreux exemples."],
    ["Qu'est-ce que la théorie synthétique de l'évolution ?", ["La réunion du darwinisme et de la génétique au XXe siècle", "La théorie de Darwin prise isolément, sans l'apport de la génétique", "L'hypothèse des équilibres ponctués défendue par Gould", "La théorie neutraliste des mutations, formulée par Kimura"], 0,
     "Formulée dans les années 1930 et 1940, elle explique la variation par les mutations et le tri par la sélection."],
    ["Qu'est-ce que l'hypothèse des équilibres ponctués ?", ["L'idée que l'évolution alterne longues stases et changements rapides", "L'idée d'une évolution parfaitement constante et graduelle", "L'idée que les extinctions de masse reviennent à intervalles réguliers", "L'idée d'une évolution dirigée vers un but déterminé"], 0,
     "Proposée en 1972 par Eldredge et Gould à partir de la lecture du registre fossile.", 3],
  ]),
];
