/**
 * Sport, deuxième lot — dix-neuf notions sans cours.
 */
import { notion } from "./commun";
import type { SeedSkill } from "../../../src/modules/types";

const S = "Sport";

export const CG_SPORT_2: SeedSkill[] = [
  notion("sp2-histoire-sport", S, "L'histoire du sport moderne",
    "Naissance des règles, des clubs et des fédérations au XIXe siècle.",
    "Le sport moderne naît en Grande-Bretagne avec la codification écrite des règles.",
    2, [
    ["Dans quel pays le sport moderne se codifie-t-il au XIXe siècle ?", ["Au Royaume-Uni", "En France, sous le Second Empire", "En Allemagne, avec le mouvement du Turnen", "Aux États-Unis, dans les universités"], 0,
     "Les public schools britanniques y ont joué un rôle déterminant."],
    ["Qu'est-ce qui distingue le sport moderne des jeux traditionnels ?", ["Des règles écrites, des fédérations et la mesure des performances", "La seule recherche de la victoire", "L'effort physique intense qui est exigé de l'ensemble des participants", "La présence de spectateurs nombreux tout autour des aires de compétition"], 0,
     "La comparabilité des performances suppose des règles identiques partout."],
    ["Quel jeu populaire français est un ancêtre de plusieurs sports de balle ?", ["La soule", "La pelote", "Le jeu de paume", "La longue paume"], 0,
     "Jeu violent et peu réglementé, il opposait des villages entiers."],
    ["Quel sport pratiqué à la cour de France est un ancêtre du tennis ?", ["Le jeu de paume", "La soule", "Le mail", "Le ballon au poing"], 0,
     "Le serment du Jeu de paume, en 1789, s'est tenu dans une salle destinée à ce sport."],
    ["Quand la première fédération sportive internationale est-elle créée ?", ["En 1881, pour la gymnastique", "En 1904, pour le football", "En 1894, pour l'olympisme", "En 1912, pour l'athlétisme"], 0,
     "La Fédération internationale de gymnastique est la plus ancienne encore en activité."],
    ["Quel rôle les public schools britanniques ont-elles joué ?", ["Elles ont codifié et diffusé les règles de nombreux sports", "Elles ont créé de toutes pièces les premiers Jeux olympiques modernes", "Elles ont formé les premiers professionnels", "Elles ont interdit les jeux populaires"], 0,
     "Le sport y était conçu comme un instrument d'éducation morale et de discipline."],
    ["Qu'est-ce que l'amateurisme dans le sport du XIXe siècle ?", ["Un principe excluant les sportifs rémunérés, souvent socialement discriminant", "Une pratique de loisir réservée aux membres des clubs les plus fermés de Londres", "Un niveau de compétition inférieur, réservé aux débutants et aux jeunes sportifs", "Un statut fiscal avantageux accordé aux clubs qui ne versaient aucune rémunération"], 0,
     "Il écartait de fait les ouvriers, qui ne pouvaient s'entraîner sans compensation."],
    ["Quand le professionnalisme est-il admis aux Jeux olympiques ?", ["Progressivement à partir des années 1980", "Dès 1896", "En 1936", "En 1960"], 0,
     "Les basketteurs professionnels américains y participent pour la première fois en 1992."],
    ["Quel sport est le premier à autoriser officiellement le professionnalisme en Angleterre ?", ["Le football, en 1885", "Le rugby", "Le cricket", "L'athlétisme"], 0,
     "Le refus du professionnalisme au rugby provoquera la scission de 1895."],
    ["Quelle innovation du XIXe siècle a favorisé la diffusion du sport ?", ["Le chemin de fer et la presse", "L'électricité et l'éclairage des stades", "La photographie de presse", "Le télégraphe, à lui seul"], 0,
     "Les compétitions régulières entre villes supposaient des déplacements rapides et une couverture médiatique.", 3],
  ]),

  notion("sp2-gymnastique", S, "La gymnastique",
    "Agrès, disciplines, notation.",
    "La gymnastique artistique ne comporte pas les mêmes agrès pour les hommes et pour les femmes.",
    2, [
    ["Combien d'agrès la gymnastique artistique masculine compte-t-elle ?", ["Six", "Quatre", "Cinq", "Huit"], 0,
     "Sol, cheval d'arçons, anneaux, saut, barres parallèles et barre fixe."],
    ["Combien d'agrès la gymnastique artistique féminine compte-t-elle ?", ["Quatre", "Six", "Cinq", "Trois"], 0,
     "Saut, barres asymétriques, poutre et sol."],
    ["Quelle largeur fait une poutre de gymnastique ?", ["Dix centimètres", "Vingt centimètres", "Cinq centimètres", "Quinze centimètres"], 0,
     "Elle est placée à cent vingt-cinq centimètres du sol."],
    ["Qu'est-ce que la gymnastique rythmique ?", ["Une discipline associant mouvements et engins comme le ruban ou le cerceau", "Une gymnastique exécutée en musique sur un praticable de douze mètres de côté", "Une danse sportive jugée sur la synchronisation et sur l'expression du couple", "Une gymnastique acrobatique pratiquée à deux ou à plusieurs"], 0,
     "Quatre engins sont au programme senior : cerceau, ballon, massues et ruban. La corde en a été retirée."],
    ["Qu'est-ce que le trampoline en compétition ?", ["Une discipline olympique de sauts acrobatiques", "Un exercice d'échauffement utilisé par les gymnastes", "Une épreuve de gymnastique artistique", "Une discipline de démonstration"], 0,
     "Il est devenu olympique aux Jeux de Sydney en 2000."],
    ["Comment une performance de gymnastique est-elle notée ?", ["Par une note de difficulté et une note d'exécution", "Par une note unique sur dix attribuée par un jury de six juges", "Par un classement comparatif entre les gymnastes du plateau", "Par un vote à main levée des juges présents à l'agrès"], 0,
     "Le fameux dix parfait a disparu du code de pointage en 2006."],
    ["Quelle gymnaste roumaine obtient le premier dix parfait olympique en 1976 ?", ["Nadia Comăneci", "Olga Korbut", "Ludmilla Tourischeva", "Věra Čáslavská"], 0,
     "L'affichage électronique ne prévoyait pas cette note et indiqua un virgule zéro zéro."],
    ["Qu'est-ce qu'un élément nommé en gymnastique ?", ["Une figure portant le nom du gymnaste qui l'a réalisée le premier en compétition", "Un mouvement obligatoire que chaque gymnaste doit présenter à l'un des agrès imposés", "Une figure imposée par le code de pointage à toutes les gymnastes d'une catégorie", "Un enchaînement de référence filmé par la fédération"], 0,
     "Il faut la réussir lors d'une compétition officielle majeure pour qu'elle soit inscrite au code."],
    ["Quel est le risque principal de la gymnastique de haut niveau ?", ["Les blessures liées aux impacts répétés et à la spécialisation précoce", "L'épuisement cardiovasculaire", "Les blessures musculaires seules", "Les troubles respiratoires"], 0,
     "Les enquêtes récentes ont aussi mis en lumière des situations de maltraitance dans plusieurs pays."],
    ["Qu'est-ce que la gymnastique aux agrès à l'école ?", ["Une activité éducative visant la maîtrise du corps, non la performance", "Une préparation à la compétition", "Une discipline optionnelle", "Un test d'évaluation physique"], 0,
     "Elle vise le repérage dans l'espace, l'appui et la confiance dans le mouvement.", 3],
  ]),

  notion("sp2-basket-nba", S, "Le basket-ball",
    "Règles, compétitions, grandes figures.",
    "Le basket est l'un des rares sports majeurs dont on connaît l'inventeur et la date exacte.",
    2, [
    ["Quelle est la hauteur d'un panier de basket ?", ["Trois mètres cinq", "Trois mètres", "Trois mètres cinquante", "Deux mètres quatre-vingts"], 0,
     "Dix pieds, hauteur inchangée depuis l'invention du jeu en 1891."],
    ["Combien de temps une équipe a-t-elle pour tirer en NBA ?", ["Vingt-quatre secondes", "Trente secondes", "Trente-cinq secondes", "Vingt secondes"], 0,
     "La règle, introduite en 1954, a transformé le rythme du jeu."],
    ["Que vaut un lancer franc ?", ["Un point", "Deux points", "Trois points", "Un demi-point"], 0,
     "Il est accordé après certaines fautes et se tire sans opposition."],
    ["Qu'est-ce qu'un marcher au basket ?", ["Un déplacement irrégulier sans dribble", "Un dribble interrompu", "Un contact avec l'adversaire", "Un retour en zone"], 0,
     "Deux appuis sont autorisés après l'arrêt du dribble."],
    ["Qu'est-ce qu'un rebond au basket ?", ["La récupération du ballon après un tir manqué", "Un tir raté", "Un rattrapage après passe", "Une remise en jeu"], 0,
     "Il est offensif ou défensif selon l'équipe qui le prend."],
    ["Quelle ligue professionnelle américaine est la plus réputée en basket ?", ["La NBA", "La NCAA", "La WNBA", "La ABA"], 0,
     "La NCAA est le championnat universitaire, principal vivier de la NBA."],
    ["Quel joueur américain est souvent considéré comme le plus grand de l'histoire ?", ["Michael Jordan", "Kareem Abdul-Jabbar", "Bill Russell", "Wilt Chamberlain"], 0,
     "Le débat reste ouvert, notamment avec LeBron James."],
    ["Qu'est-ce que la Dream Team de 1992 ?", ["La sélection américaine composée pour la première fois de professionnels NBA", "L'équipe championne NBA de 1992", "Une sélection universitaire d'élite", "L'équipe américaine de 1996"], 0,
     "Elle remporte l'or à Barcelone avec une marge moyenne considérable."],
    ["Quelle compétition européenne de clubs est la plus prestigieuse en basket ?", ["L'EuroLigue", "La Coupe Korać", "L'EuroCoupe", "La Ligue des champions"], 0,
     "Les clubs espagnols, grecs, turcs et israéliens y dominent régulièrement."],
    ["Quelle particularité le basket à trois contre trois présente-t-il ?", ["Un demi-terrain, un seul panier et un format court", "Un terrain complet réduit", "Deux paniers et trois joueurs", "Un jeu sans dribble"], 0,
     "Il est devenu discipline olympique aux Jeux de Tokyo en 2021.", 3],
  ]),

  notion("sp2-rugby", S, "Le rugby",
    "Règles, compétitions, culture du jeu.",
    "Le rugby à quinze et le rugby à treize sont deux sports distincts issus d'une scission.",
    2, [
    ["Pourquoi le rugby à treize s'est-il séparé du rugby à quinze ?", ["Un conflit sur l'indemnisation des joueurs ouvriers", "Un désaccord sur le nombre de joueurs et les règles du jeu", "Une querelle entre clubs anglais et gallois", "Un conflit sur le calendrier des compétitions"], 0,
     "La scission de 1895 oppose le nord industriel de l'Angleterre au sud amateur."],
    ["Qu'est-ce qu'une mêlée au rugby ?", ["Une phase de reprise du jeu où les avants s'opposent en poussée", "Un regroupement de joueurs debout autour du ballon après un plaquage", "Une touche jouée au sol après une sortie de ballon", "Une phase de conquête aérienne disputée après un coup de pied haut"], 0,
     "Elle sanctionne notamment une passe en avant ou un ballon injouable."],
    ["Qu'est-ce qu'une touche au rugby ?", ["Une remise en jeu après sortie du ballon en dehors du terrain", "Un plaquage effectué au-delà de la ligne de touche, hors du terrain", "Un contact fautif commis sur un adversaire qui n'a pas le ballon", "Une pénalité accordée à l'équipe qui sort le ballon du terrain"], 0,
     "Les alignements et les levées en font une phase très codifiée."],
    ["Qu'est-ce qu'un ruck ?", ["Un regroupement au sol autour du ballon après plaquage", "Une mêlée ouverte ordonnée par l'arbitre après un en-avant", "Une phase de touche disputée en alignement", "Un maul de pénétration"], 0,
     "Le maul se distingue du ruck par le fait que le porteur du ballon reste debout."],
    ["Que se passe-t-il en cas de plaquage haut ?", ["Une pénalité, avec un risque de carton", "Un simple coup franc", "Une mêlée", "Une remise en jeu"], 0,
     "Les règles se sont durcies dans les années récentes pour limiter les commotions cérébrales."],
    ["Quel tournoi annuel oppose six nations européennes ?", ["Le Tournoi des Six Nations", "La Coupe d'Europe", "Le Championnat européen", "La Coupe des nations"], 0,
     "L'Italie l'a rejoint en 2000, transformant le Tournoi des Cinq Nations."],
    ["Qu'est-ce que le Grand Chelem dans le Tournoi ?", ["Une victoire contre toutes les autres équipes", "Un titre remporté sans défaite", "Une victoire à l'extérieur partout", "Un record de points marqués"], 0,
     "La Triple Couronne concerne uniquement les quatre nations britanniques."],
    ["Quand la Coupe du monde de rugby a-t-elle été créée ?", ["En 1987", "En 1954", "En 1995", "En 1975"], 0,
     "Elle se dispute tous les quatre ans. La Nouvelle-Zélande a remporté la première édition."],
    ["Qu'est-ce que le haka ?", ["Une danse rituelle maorie exécutée avant les matchs néo-zélandais", "Un chant repris par les supporters néo-zélandais dans les tribunes", "Un salut protocolaire adressé à l'équipe adverse avant le coup d'envoi", "Un échauffement collectif exécuté sur la pelouse"], 0,
     "Plusieurs versions existent ; le Ka Mate est la plus connue."],
    ["Qu'est-ce que la troisième mi-temps au rugby ?", ["Le moment de convivialité entre équipes après le match", "Une prolongation disputée en cas d'égalité à la fin du match", "Une période supplémentaire de dix minutes prévue par le règlement", "Un entraînement de récupération organisé le lendemain du match"], 0,
     "Cette tradition est constitutive de la culture du rugby, même si elle évolue avec le professionnalisme.", 3],
  ]),

  notion("sp2-natation-eau", S, "La natation et les sports aquatiques",
    "Techniques, épreuves, disciplines associées.",
    "En brasse comme en papillon, les mouvements des deux bras doivent être simultanés et symétriques.",
    2, [
    ["Quelle nage est la plus rapide ?", ["Le crawl", "Le dos", "La brasse", "Le papillon"], 0,
     "Le papillon est le deuxième plus rapide, mais bien plus coûteux en énergie."],
    ["Dans quel ordre les nages s'enchaînent-elles en quatre nages individuel ?", ["Papillon, dos, brasse, nage libre", "Crawl, dos, brasse, papillon", "Dos, brasse, papillon, crawl", "Brasse, papillon, dos, crawl"], 0,
     "L'ordre diffère en relais quatre nages, qui commence par le dos."],
    ["Quelle est la longueur d'un bassin olympique ?", ["Cinquante mètres", "Vingt-cinq mètres", "Cent mètres", "Trente-trois mètres"], 0,
     "Les compétitions en petit bassin se disputent sur vingt-cinq mètres."],
    ["Qu'est-ce que la coulée en natation ?", ["La phase immergée après le départ ou le virage", "Une glissade en surface juste après le plongeon de départ", "Un mouvement de jambes ondulatoire", "Un enchaînement de deux nages différentes"], 0,
     "Elle est limitée à quinze mètres par le règlement, car plus rapide que la nage."],
    ["Qu'est-ce que la natation synchronisée, aujourd'hui appelée natation artistique ?", ["Une discipline associant nage, figures et musique", "Un ballet nautique présenté en démonstration lors des galas", "Une nage exécutée en formation par une équipe entière", "Une discipline de plongeon collectif jugée sur la synchronisation"], 0,
     "Les épreuves sont ouvertes aux hommes aux Jeux olympiques depuis 2024."],
    ["Qu'est-ce que le water-polo ?", ["Un sport collectif en eau profonde à sept joueurs par équipe", "Un jeu de ballon pratiqué en piscine, les pieds touchant le fond", "Une variante aquatique du handball qui se joue à onze contre onze", "Un sport de plage qui se dispute dans les vagues, tout près du rivage"], 0,
     "Les joueurs n'ont pas le droit de toucher le fond, ce qui en fait un sport extrêmement exigeant."],
    ["Qu'est-ce que la nage en eau libre ?", ["Une compétition en milieu naturel sur de longues distances", "Une nage sans style imposé", "Une nage sans ligne d'eau", "Une nage de sauvetage"], 0,
     "L'épreuve olympique se dispute sur dix kilomètres."],
    ["Qu'est-ce que le plongeon de haut vol ?", ["Un plongeon depuis vingt à vingt-sept mètres", "Un plongeon depuis dix mètres", "Un plongeon depuis un tremplin", "Un plongeon en apnée"], 0,
     "La vitesse d'entrée dans l'eau approche les quatre-vingt-dix kilomètres par heure."],
    ["Qu'est-ce que l'apnée statique ?", ["Une discipline où l'on retient sa respiration immobile le plus longtemps possible", "Une plongée au cours de laquelle on cherche à descendre aussi bas que possible en mer", "Une nage en apnée sur une distance donnée", "Une descente à poids constant le long d'un câble"], 0,
     "Les records dépassent onze minutes, avec une préparation spécifique et des risques importants.", 3],
  ]),

  notion("sp2-sports-mecaniques", S, "Les sports mécaniques",
    "Formule 1, rallye, moto : règles et sécurité.",
    "La sécurité en sport automobile a progressé au point de rendre les accidents mortels exceptionnels.",
    2, [
    ["Quand le championnat du monde de Formule 1 est-il créé ?", ["En 1950", "En 1946", "En 1958", "En 1966"], 0,
     "La première course s'est tenue à Silverstone, en Angleterre."],
    ["Qu'est-ce que le halo en Formule 1 ?", ["Un arceau de protection de la tête du pilote", "Un système de freinage récupérant l'énergie au freinage", "Un dispositif aérodynamique placé au-dessus du cockpit", "Un capteur de choc placé dans le baquet"], 0,
     "Introduit en 2018 malgré des critiques esthétiques, il a déjà sauvé plusieurs vies."],
    ["Qu'est-ce que la voiture de sécurité en course ?", ["Un véhicule neutralisant la course en la ralentissant", "Une voiture d'intervention médicale qui suit le peloton au départ", "Un véhicule d'ouverture qui inspecte la piste", "Une voiture chargée de remorquer les monoplaces"], 0,
     "Elle permet de sécuriser la piste sans interrompre totalement l'épreuve."],
    ["Qu'est-ce que le drapeau rouge en course automobile ?", ["L'interruption immédiate de la course", "Un avertissement de danger", "Une pénalité", "Un dernier tour signalé"], 0,
     "Le drapeau à damier signale l'arrivée, le drapeau jaune un danger."],
    ["Qu'est-ce que le rallye Dakar ?", ["Un rallye-raid tout-terrain sur plusieurs milliers de kilomètres", "Un rallye couru sur asphalte à travers plusieurs pays d'Afrique de l'Ouest", "Une course de côte disputée en plusieurs manches chronométrées successives", "Un raid réservé aux seules motos, interdit aux automobiles et aux camions"], 0,
     "Parti de Paris jusqu'en 2001, puis d'autres villes européennes jusqu'en 2007, il s'est couru en Amérique du Sud de 2009 à 2019, et en Arabie saoudite depuis 2020."],
    ["Quelle est la particularité du rallye automobile ?", ["Les concurrents partent en décalé sur des spéciales chronométrées", "Le départ groupé sur circuit", "La course en peloton", "Le classement au nombre de tours"], 0,
     "Le copilote lit les notes décrivant le parcours, invisible à l'avance depuis le volant."],
    ["Qu'est-ce que le MotoGP ?", ["La catégorie reine du championnat du monde de vitesse moto", "Un championnat de motocross disputé sur des circuits en terre", "Une épreuve d'endurance courue sur vingt-quatre heures en équipage", "Un championnat de rallye réservé aux motos"], 0,
     "Les prototypes y atteignent plus de trois cent cinquante kilomètres par heure."],
    ["Qu'est-ce que la Formule E ?", ["Un championnat de monoplaces électriques", "Une catégorie junior servant d'antichambre à la Formule 1", "Un championnat d'endurance électrique", "Une série de démonstration"], 0,
     "Créée en 2014, elle se court principalement sur des circuits urbains temporaires."],
    ["Quel effet le sport automobile a-t-il sur l'industrie ?", ["Il sert de laboratoire technologique pour la série", "Il n'a aucun effet mesurable sur les voitures de série", "Il ralentit l'innovation en mobilisant les ingénieurs", "Il ne concerne que la compétition, jamais la production"], 0,
     "Freins, pneumatiques, aérodynamique et systèmes hybrides en ont directement bénéficié.", 3],
  ]),

  notion("sp2-sports-glisse", S, "Sports de glisse et de plein air",
    "Surf, escalade, alpinisme, sports urbains.",
    "L'escalade sportive est devenue olympique en 2021.",
    2, [
    ["D'où le surf moderne est-il originaire ?", ["De Polynésie, notamment d'Hawaï", "De Californie", "D'Australie", "Du Brésil"], 0,
     "Pratique ancienne et rituelle, il a été réintroduit dans le monde occidental au début du XXe siècle."],
    ["Qu'est-ce que le shortboard, par rapport au longboard ?", ["Une planche courte plus maniable et radicale", "Une planche plus stable, réservée aux petites vagues", "Une planche destinée aux débutants", "Une planche de compétition uniquement"], 0,
     "La révolution du shortboard, à la fin des années 1960, a transformé le style de surf."],
    ["Quelles disciplines composaient l'escalade olympique en 2021 ?", ["Vitesse, bloc et difficulté", "Bloc et difficulté seuls", "Vitesse et bloc", "Escalade libre et artificielle"], 0,
     "Le combiné imposé a été critiqué : les trois disciplines demandent des qualités très différentes."],
    ["Qu'est-ce que le bloc en escalade ?", ["Une escalade sans corde à faible hauteur sur tapis", "Une escalade pratiquée uniquement sur des blocs de rocher naturels", "Une escalade de vitesse sur une voie entièrement standardisée", "Une escalade pratiquée en salle"], 0,
     "Les passages sont courts mais très intenses, appelés problèmes."],
    ["Qu'est-ce que l'escalade en libre ?", ["Une escalade où le matériel ne sert qu'à la sécurité", "Une escalade menée sans le moindre matériel d'assurage", "Une escalade dans laquelle la corde n'est jamais utilisée", "Une escalade menée sans aucune assurance, au-dessus du vide"], 0,
     "Le solo intégral, lui, se pratique sans aucune assurance."],
    ["Qu'est-ce que la cotation en escalade ?", ["Un système évaluant la difficulté d'une voie", "Un classement des grimpeurs établi en compétition", "Une évaluation du risque encouru par le grimpeur", "Une notation de l'engagement physique et mental"], 0,
     "Les systèmes diffèrent selon les pays, ce qui rend les comparaisons délicates."],
    ["Quel sommet a été gravi pour la première fois en 1953 ?", ["L'Everest", "Le K2", "L'Annapurna", "Le Kangchenjunga"], 0,
     "Par Edmund Hillary et Tenzing Norgay. L'Annapurna avait été gravi en 1950 par une expédition française."],
    ["Qu'est-ce que la zone de la mort en haute altitude ?", ["Au-delà d'environ huit mille mètres, où l'organisme ne peut plus s'acclimater", "La zone des crevasses", "La face nord des sommets", "La zone d'avalanches"], 0,
     "L'organisme s'y dégrade continuellement, quelle que soit l'acclimatation préalable."],
    ["Qu'est-ce que le skateboard en compétition olympique ?", ["Une discipline comportant les épreuves de street et de park", "Une épreuve de vitesse chronométrée sur une longue piste descendante", "Une discipline de figures libres notée par un jury international", "Une épreuve de slalom entre des plots"], 0,
     "Il est devenu olympique à Tokyo en 2021, avec des athlètes très jeunes sur les podiums."],
    ["Qu'est-ce que le parkour ?", ["Une pratique de déplacement urbain fondée sur le franchissement d'obstacles", "Une course d'obstacles chronométrée disputée sur un parcours artificiel balisé", "Une discipline acrobatique de rue jugée par un jury lors de compétitions internationales", "Un sport de compétition codifié par une fédération internationale depuis les années 1990"], 0,
     "Né en banlieue parisienne dans les années 1990, il revendique souvent son caractère non compétitif.", 3],
  ]),

  notion("sp2-handisport", S, "Handisport et sport adapté",
    "Classifications, disciplines, histoire.",
    "La classification vise à faire concourir ensemble des athlètes aux limitations comparables.",
    2, [
    ["Où les premiers jeux pour athlètes handicapés sont-ils organisés en 1948 ?", ["À Stoke Mandeville, en Angleterre", "À Rome, capitale de l'Italie", "À Londres, dans le sud de l'Angleterre", "À Heidelberg, en Allemagne de l'Ouest"], 0,
     "Sur l'initiative du neurologue Ludwig Guttmann, pour des vétérans blessés médullaires."],
    ["En quelle année les premiers Jeux paralympiques d'été ont-ils lieu ?", ["1960, à Rome", "1948, à Londres", "1976, à Toronto", "1988, à Séoul"], 0,
     "Depuis 1988, ils se tiennent dans la même ville que les Jeux olympiques."],
    ["Qu'est-ce que la classification en para-sport ?", ["Un système regroupant les athlètes selon l'impact de leur handicap sur la performance", "Un classement par type de handicap, identique dans l'ensemble des disciplines sportives", "Un classement établi par un médecin agréé", "Un classement fondé sur le niveau sportif atteint"], 0,
     "Elle est spécifique à chaque discipline, un même athlète pouvant être classé différemment selon le sport."],
    ["Quelle différence sépare handisport et sport adapté en France ?", ["Le handisport concerne les handicaps physiques et sensoriels, le sport adapté le handicap mental", "Ce sont deux termes équivalents, employés indifféremment par les fédérations françaises et internationales", "Le sport adapté ne concerne que les activités de loisir pratiquées en dehors de toute compétition officielle", "Le handisport ne concerne que la compétition de haut niveau, le sport adapté la seule pratique scolaire"], 0,
     "Deux fédérations distinctes les organisent en France."],
    ["Qu'est-ce que le cécifoot ?", ["Un football pour déficients visuels avec un ballon sonore", "Un football en salle adapté aux joueurs en fauteuil roulant", "Un football pour sourds et malentendants, arbitré au drapeau", "Un football pratiqué assis sur le sol"], 0,
     "Les joueurs de champ portent un bandeau ; le gardien est voyant."],
    ["Qu'est-ce que le goalball ?", ["Un sport collectif pour déficients visuels avec un ballon sonore", "Un handball adapté", "Un football à cinq", "Un jeu de précision"], 0,
     "Créé après la Seconde Guerre mondiale pour la rééducation de vétérans, il est paralympique depuis 1976."],
    ["Qu'est-ce que la boccia ?", ["Un sport de précision paralympique proche de la pétanque", "Un jeu de quilles adapté aux athlètes se déplaçant en fauteuil", "Un tir à l'arc pratiqué assis", "Un sport de lancer pratiqué en fauteuil"], 0,
     "Il est ouvert aux athlètes présentant des handicaps très lourds, avec parfois une rampe et un assistant."],
    ["Qu'est-ce que le rugby-fauteuil ?", ["Un sport de contact en fauteuil, mixte, pour tétraplégiques", "Un rugby à treize adapté", "Un basket-fauteuil de contact", "Un handball en fauteuil"], 0,
     "Il fut d'abord surnommé murderball en raison de la violence des chocs entre fauteuils."],
    ["Qu'est-ce que le sport pour sourds ?", ["Une compétition distincte, les Deaflympics, organisée séparément", "Une catégorie paralympique", "Une discipline handisport", "Un championnat national uniquement"], 0,
     "Les Deaflympics existent depuis 1924 et ne font pas partie du mouvement paralympique."],
    ["Qu'est-ce que la sportification du handicap interroge ?", ["Le rapport entre performance, spectacle et représentation du handicap", "Le coût des équipements adaptés, hors de portée de la plupart des clubs", "La médicalisation excessive de la pratique sportive des personnes handicapées", "L'accès aux clubs ordinaires, encore difficile dans beaucoup de communes"], 0,
     "Les athlètes eux-mêmes contestent souvent le récit héroïsant qui leur est appliqué.", 3],
  ]),

  notion("sp2-sport-education", S, "Le sport à l'école et en club",
    "EPS, associations, encadrement.",
    "Ne confonds pas ce qui s'enseigne, avec ses programmes et ses évaluations, et ce qui se pratique librement.",
    2, [
    ["Qu'est-ce que l'EPS en France ?", ["Une discipline d'enseignement obligatoire avec ses programmes", "Une activité de loisir scolaire laissée à l'initiative des établissements", "Une option facultative choisie au lycée", "Un temps de récréation encadré par un surveillant"], 0,
     "Elle est évaluée au brevet comme au baccalauréat."],
    ["Qu'est-ce que l'UNSS ?", ["La fédération du sport scolaire du second degré", "Une association regroupant les clubs sportifs universitaires", "Un syndicat national des enseignants d'éducation physique", "Un office national des sports de nature"], 0,
     "Elle organise des compétitions scolaires du district au niveau national."],
    ["Qu'est-ce que l'USEP ?", ["La fédération du sport scolaire dans le premier degré", "Une union sportive regroupant les universités françaises", "Une fédération du sport pratiqué en entreprise et en comité", "Un office municipal chargé des équipements sportifs de proximité"], 0,
     "Elle est liée à la Ligue de l'enseignement et travaille sur le temps scolaire et périscolaire."],
    ["Que faut-il pour encadrer une activité sportive contre rémunération en France ?", ["Un diplôme d'État, aujourd'hui le BPJEPS ou ses équivalents", "Un diplôme de bénévole autorisant l'encadrement gratuit dans un club affilié", "Un titre fédéral délivré par la fédération nationale de la discipline concernée", "Une attestation de secourisme exigée des encadrants"], 0,
     "Encadrer contre rémunération sans diplôme est un délit en France ; le brevet d'État d'éducateur sportif, ancien nom du diplôme, n'est plus délivré."],
    ["Qu'est-ce qu'un club sportif amateur en France ?", ["Une association affiliée à une fédération", "Une société commerciale", "Un service municipal", "Un groupement d'intérêt public"], 0,
     "La France compte plus de cent cinquante mille clubs affiliés."],
    ["Qu'est-ce qu'une licence sportive ?", ["Un titre d'adhésion à une fédération incluant une assurance", "Une autorisation de participer aux seules compétitions officielles", "Un certificat médical établi en début de saison", "Une carte remise par le club à ses adhérents"], 0,
     "Elle conditionne la participation aux compétitions officielles."],
    ["Qu'est-ce que le certificat médical de non-contre-indication ?", ["Un document longtemps exigé pour la pratique en club, aujourd'hui allégé", "Un examen médical annuel obligatoire pour tous les licenciés sans exception", "Un bilan sportif complet réalisé dans un laboratoire d'effort chaque saison", "Un document réservé aux seuls licenciés engagés en compétition officielle"], 0,
     "Depuis 2021, il est remplacé pour les mineurs par un questionnaire de santé dans la plupart des cas."],
    ["Qu'est-ce que le sport-études ?", ["Un aménagement de scolarité permettant de concilier études et entraînement intensif", "Une filière sportive du baccalauréat", "Un internat sportif", "Un centre de formation professionnel"], 0,
     "Les sections sportives scolaires et les pôles espoirs en constituent les principaux dispositifs."],
    ["Qu'est-ce que le savoir nager en France ?", ["Une attestation validant des compétences aquatiques de sécurité", "Un diplôme de natation sportive délivré par la fédération française", "Un test de vitesse chronométré sur vingt-cinq mètres en bassin couvert", "Une évaluation de la technique des quatre nages"], 0,
     "La noyade reste l'une des premières causes de mortalité accidentelle chez les enfants."],
    ["Pourquoi la pratique sportive baisse-t-elle à l'adolescence ?", ["Des facteurs sociaux, scolaires et de rapport au corps se combinent", "Par manque d'équipements", "Par désintérêt général", "Par contrainte scolaire seule"], 0,
     "La baisse est plus marquée chez les filles, ce qui fait l'objet de politiques publiques ciblées.", 3],
  ]),

  notion("sp2-records-performance", S, "Records et progression des performances",
    "Ce qui explique l'amélioration des performances au fil du temps.",
    "Un ralentissement n'est pas une stagnation : les records tombent encore, juste plus rarement.",
    2, [
    ["Qu'est-ce qui a le plus contribué à l'amélioration des records au XXe siècle ?", ["L'élargissement du bassin de pratiquants et la professionnalisation", "Le seul progrès des techniques d'entraînement depuis le début du siècle", "La seule amélioration des matériaux et des surfaces de compétition modernes", "Le dopage généralisé"], 0,
     "L'accès des femmes et de nouvelles nations à la compétition a fortement élargi le vivier."],
    ["Que constate-t-on sur la progression des records depuis les années 1990 ?", ["Un net ralentissement dans la plupart des disciplines", "Une accélération continue de la progression des records", "Une stagnation totale depuis trente ans", "Une régression des performances"], 0,
     "Plusieurs travaux suggèrent que l'on approche de limites physiologiques dans certaines épreuves."],
    ["Quel rôle le matériel joue-t-il dans les records ?", ["Un rôle déterminant dans certaines disciplines, ce qui impose des règles d'homologation", "Un rôle négligeable, les fédérations imposant depuis toujours un matériel strictement identique", "Un rôle limité aux seuls sports mécaniques, où la machine compte davantage que le pilote", "Un rôle uniquement esthétique, puisque la réglementation interdit tout avantage technique"], 0,
     "Perches, combinaisons de natation et chaussures d'athlétisme ont chacune provoqué des débats."],
    ["Pourquoi les combinaisons de natation en polyuréthane ont-elles été interdites ?", ["Elles amélioraient artificiellement la flottabilité et les temps", "Elles étaient dangereuses pour la peau et la circulation sanguine", "Elles coûtaient beaucoup trop cher pour les fédérations les moins riches", "Elles gênaient les mouvements des épaules"], 0,
     "Une vague de records en 2008 et 2009 a conduit à leur interdiction en 2010."],
    ["Qu'est-ce qu'un record homologué ?", ["Une performance validée selon des conditions réglementaires strictes", "La meilleure performance connue", "Un record national reconnu", "Une performance enregistrée officiellement"], 0,
     "Vent, altitude, homologation du parcours et contrôle antidopage en conditionnent la validité."],
    ["Pourquoi certains records d'athlétisme des années 1980 tiennent-ils toujours ?", ["Le contexte de contrôle antidopage de l'époque est mis en cause", "Les athlètes de cette génération étaient naturellement plus doués", "Les conditions de piste étaient meilleures", "Les règles d'homologation ont changé depuis"], 0,
     "Une réforme des records a été discutée à ce sujet, sans être appliquée."],
    ["Quel effet l'altitude a-t-elle sur les performances de sprint ?", ["Elle les améliore par une résistance de l'air réduite", "Elle les dégrade", "Elle n'a aucun effet", "Elle les améliore par un meilleur apport en oxygène"], 0,
     "Les records établis au-dessus de mille mètres portent une mention spécifique."],
    ["Quel effet l'altitude a-t-elle sur les épreuves d'endurance ?", ["Elle les dégrade par la moindre disponibilité en oxygène", "Elle les améliore", "Elle n'a aucun effet", "Elle les améliore après acclimatation seulement"], 0,
     "Les Jeux de Mexico en 1968 ont illustré ce double effet de façon spectaculaire."],
    ["Qu'est-ce qu'un lièvre en course de fond ?", ["Un coureur chargé d'imposer un rythme avant d'abandonner", "Un coureur favori que le peloton surveille tout au long de la course", "Un coureur qui prend la tête de la course au dernier tour", "Un remplaçant engagé à la toute dernière minute par son équipe"], 0,
     "Les records mondiaux sont presque toujours établis dans des courses organisées avec des lièvres."],
    ["Qu'est-ce que la performance humaine maximale théorique ?", ["Une estimation débattue des limites physiologiques dans une discipline", "Le record du monde actuellement homologué par la fédération internationale", "Le meilleur temps possible calculé à partir des seuls modèles biomécaniques", "La limite officiellement fixée par les fédérations"], 0,
     "Les modèles varient beaucoup ; les prédictions passées ont souvent été dépassées.", 3],
  ]),

  notion("sp2-sport-medias", S, "Sport et médias",
    "Retransmission, droits, récits.",
    "La retransmission télévisée a transformé les règles de plusieurs sports.",
    2, [
    ["Comment la télévision a-t-elle modifié certains sports ?", ["En imposant des temps morts, des horaires et parfois des règles", "En améliorant la qualité du jeu grâce aux revenus qu'elle a apportés", "En augmentant la fréquentation des stades", "Sans aucun effet sur le déroulement des rencontres"], 0,
     "Les temps morts publicitaires structurent le déroulement de nombreux sports américains."],
    ["Qu'est-ce qu'un droit de retransmission sportive ?", ["L'autorisation payante de diffuser une compétition", "Un droit d'accès des journalistes aux tribunes de presse", "Un droit à l'image que chaque athlète cède à son club", "Une licence de reportage délivrée par la ligue"], 0,
     "Ils constituent la première ressource des grandes ligues professionnelles."],
    ["Qu'est-ce que le décret français sur les événements d'importance majeure ?", ["Une liste d'événements devant rester accessibles en clair", "Une obligation de diffusion publique", "Un encadrement des prix des droits", "Une régulation des paris"], 0,
     "Il empêche que certains grands rendez-vous ne soient réservés aux seules chaînes payantes."],
    ["Qu'est-ce que le commentaire sportif ?", ["Un récit en direct construisant la dramaturgie de l'événement", "Une description strictement neutre de l'action, sans effet de récit", "Une analyse technique détaillée des choix tactiques des deux équipes", "Un compte rendu entièrement rédigé après la fin de la rencontre"], 0,
     "Il fabrique des personnages, des enjeux et des retournements autant qu'il décrit."],
    ["Qu'est-ce que le ralenti dans la retransmission sportive ?", ["Un outil de spectacle devenu aussi un instrument d'arbitrage", "Une simple répétition de l'image destinée à faire patienter le public", "Un effet visuel purement décoratif", "Une contrainte technique de la diffusion"], 0,
     "Sa généralisation a rendu visibles des erreurs d'arbitrage autrefois invisibles."],
    ["Qu'est-ce que le sport-spectacle ?", ["Une pratique organisée d'abord en fonction de son audience", "Un sport de démonstration", "Un spectacle sans compétition", "Un sport professionnel"], 0,
     "Le catch en est un cas extrême, où l'issue est scénarisée."],
    ["Qu'est-ce que la vidéo à la demande a changé pour le sport ?", ["Elle a fragmenté l'offre entre de nombreux diffuseurs payants", "Elle a réduit le prix des abonnements en multipliant les diffuseurs", "Elle a supprimé toutes les diffusions en clair des compétitions", "Elle n'a rien changé aux habitudes"], 0,
     "L'usager doit souvent cumuler plusieurs abonnements pour suivre une seule compétition."],
    ["Qu'est-ce que le journalisme sportif d'investigation ?", ["Une enquête sur les aspects économiques, sanitaires ou politiques du sport", "Un long reportage d'avant-match consacré à la préparation de chacune des équipes", "Une analyse tactique approfondie publiée le lendemain de chacune des rencontres", "Un portrait d'athlète retraçant l'ensemble de sa carrière sportive et personnelle"], 0,
     "Les grandes affaires de dopage et de corruption ont souvent été révélées par la presse."],
    ["Qu'est-ce que la couverture médiatique du sport féminin ?", ["Un espace en progression mais encore très minoritaire", "Une couverture équivalente au sport masculin", "Une couverture inexistante", "Une couverture réservée aux Jeux olympiques"], 0,
     "Les études l'évaluent autour de vingt pour cent du temps d'antenne sportif en France."],
    ["Qu'est-ce que le récit de la revanche dans le sport ?", ["Un schéma narratif récurrent construit par les médias", "Un règlement de compétition prévoyant systématiquement un match retour", "Une statistique des confrontations passées entre deux équipes", "Un format de tournoi à double affrontement"], 0,
     "Ces schémas facilitent l'accès du public à un événement sans en modifier le contenu sportif.", 3],
  ]),

  notion("sp2-sport-sante", S, "Activité physique et santé",
    "Recommandations, sédentarité, bénéfices.",
    "L'inactivité physique est l'un des principaux facteurs de risque de mortalité évitable.",
    2, [
    ["Quelle durée d'activité physique modérée l'OMS recommande-t-elle par semaine à l'adulte ?", ["Cent cinquante à trois cents minutes", "Soixante minutes chaque jour de la semaine", "Six cents minutes réparties sur le mois", "Trente minutes par jour"], 0,
     "Avec un renforcement musculaire au moins deux fois par semaine."],
    ["Quelle différence sépare inactivité physique et sédentarité ?", ["L'inactivité est un manque d'activité, la sédentarité un temps passé assis", "Ce sont deux synonymes que les études épidémiologiques emploient indifféremment", "La sédentarité ne concerne que le temps de travail", "L'inactivité concerne le sport uniquement"], 0,
     "On peut être actif sportivement et très sédentaire le reste de la journée."],
    ["Quels bénéfices l'activité physique régulière apporte-t-elle ?", ["Une réduction du risque cardiovasculaire, métabolique et de certains cancers", "Une amélioration esthétique de la silhouette, sans effet démontré sur la santé", "Un effet uniquement musculaire, sans aucune conséquence sur les autres organes", "Un effet limité au cœur et aux vaisseaux, sans aucune influence sur le métabolisme"], 0,
     "Les bénéfices sur la santé mentale et le sommeil sont également bien documentés."],
    ["Qu'est-ce que l'activité physique adaptée ?", ["Une pratique encadrée conçue pour des personnes atteintes de pathologies", "Un sport de loisir proposé aux adhérents des clubs et des associations sportives", "Une rééducation médicale conduite par un kinésithérapeute après une opération", "Une gymnastique douce pratiquée en groupe"], 0,
     "Elle peut être prescrite par un médecin depuis la loi de 2016."],
    ["Quel effet l'activité physique a-t-elle sur le diabète de type 2 ?", ["Elle améliore la sensibilité à l'insuline", "Elle n'a pas d'effet démontré", "Elle augmente la glycémie", "Elle agit uniquement par la perte de poids"], 0,
     "L'effet est direct et indépendant de la variation de poids."],
    ["À partir de quel âge l'activité physique reste-t-elle bénéfique ?", ["À tout âge, y compris très avancé", "Jusqu'à soixante-cinq ans, âge de la retraite", "Jusqu'à quarante ans environ, puis les risques l'emportent", "Uniquement chez les enfants et les adolescents"], 0,
     "Chez la personne âgée, elle réduit notamment le risque de chute et la perte d'autonomie."],
    ["Qu'est-ce que la sarcopénie liée au vieillissement ?", ["Une perte de masse et de force musculaires", "Une fragilité osseuse", "Une perte d'équilibre", "Une raideur articulaire"], 0,
     "Le renforcement musculaire est le principal moyen de la ralentir."],
    ["Qu'est-ce que le risque de mort subite du sportif ?", ["Un événement rare, souvent lié à une anomalie cardiaque préexistante", "Un risque courant de tout effort intense, quel que soit l'état de santé du sportif", "Un accident lié à la déshydratation à l'effort", "Une conséquence directe du surentraînement"], 0,
     "Le dépistage cardiaque des sportifs de haut niveau vise précisément ces anomalies."],
    ["Qu'est-ce que le syndrome de surentraînement ?", ["Un état de fatigue durable avec baisse de performance", "Une blessure musculaire", "Une déshydratation chronique", "Une carence alimentaire"], 0,
     "Il impose souvent plusieurs semaines à plusieurs mois d'arrêt complet."],
    ["Qu'est-ce que le sport sur ordonnance ?", ["La prescription d'activité physique adaptée par un médecin", "Une obligation de pratique", "Un remboursement du sport en club", "Un certificat d'aptitude"], 0,
     "Prévu par la loi française, son remboursement reste très inégal selon les territoires.", 3],
  ]),

  notion("sp2-sport-feminin", S, "Le sport féminin",
    "Accès, reconnaissance, inégalités persistantes.",
    "Les femmes ont été exclues de nombreux sports par des arguments médicaux longtemps tenus pour scientifiques.",
    2, [
    ["Pourquoi les femmes ont-elles longtemps été exclues du marathon ?", ["On prétendait que l'effort leur était physiologiquement nuisible", "Les règlements des fédérations ne prévoyaient tout simplement pas leur cas", "Elles ne s'intéressaient pas aux épreuves de course de longue distance", "Les distances imposées étaient jugées trop longues"], 0,
     "Le marathon féminin n'est devenu olympique qu'en 1984, à Los Angeles."],
    ["Quelle coureuse s'inscrit officieusement au marathon de Boston en 1967 ?", ["Kathrine Switzer", "Bobbi Gibb", "Joan Benoit", "Grete Waitz"], 0,
     "Un officiel tenta de l'expulser en pleine course ; les photographies firent le tour du monde."],
    ["Quand le football féminin a-t-il été interdit en Angleterre ?", ["De 1921 à 1971 par la fédération", "Il ne l'a jamais été", "Pendant la Seconde Guerre mondiale", "Dans les années 1950"], 0,
     "Il attirait alors des dizaines de milliers de spectateurs, ce qui inquiétait la fédération masculine."],
    ["Quand la première Coupe du monde féminine de football a-t-elle lieu ?", ["En 1991", "En 1971", "En 1999", "En 1983"], 0,
     "L'édition de 2019, organisée en France, a marqué un tournant en termes d'audience."],
    ["Quelle inégalité persiste dans de nombreux sports professionnels ?", ["Les écarts de rémunération et de dotations", "L'accès aux compétitions internationales majeures", "Les règles du jeu, différentes", "La durée réglementaire des matchs"], 0,
     "Plusieurs fédérations ont égalisé les primes internationales, mais pas les salaires en club."],
    ["Qu'est-ce que le test de féminité dans l'histoire du sport ?", ["Un contrôle imposé aux athlètes femmes, aujourd'hui abandonné sous cette forme", "Un test médical de routine imposé à tous les athlètes avant chaque grande compétition", "Un contrôle antidopage spécifique aux hormones féminines, encore pratiqué aujourd'hui", "Une évaluation servant à répartir les concurrentes entre les différentes catégories"], 0,
     "Ces contrôles ont causé de graves atteintes à la dignité de nombreuses athlètes."],
    ["Qu'est-ce que le débat sur l'hyperandrogénie dans le sport ?", ["Une controverse sur les seuils hormonaux imposés aux athlètes femmes", "Un débat sur le dopage hormonal organisé par certaines fédérations nationales", "Une question portant sur la répartition des concurrentes par catégories d'âge", "Un débat sur la fiabilité des tests génétiques"], 0,
     "Il oppose équité sportive, science incertaine et droits des personnes concernées."],
    ["Quelle proportion de licenciés sportifs les femmes représentent-elles en France ?", ["Environ quatre sur dix", "Environ la moitié", "Environ deux sur dix", "Environ six sur dix"], 0,
     "La proportion varie fortement selon les disciplines et diminue avec le niveau de responsabilité."],
    ["Quelle est la place des femmes dans la direction des fédérations sportives ?", ["Encore très minoritaire malgré des obligations de parité", "Paritaire depuis 2000", "Majoritaire dans les sports féminins", "Sans réglementation"], 0,
     "La loi française impose des proportions minimales dans les instances dirigeantes."],
    ["Quel effet la médiatisation a-t-elle sur le sport féminin ?", ["Elle conditionne largement les ressources et la professionnalisation", "Elle n'a aucun effet économique sur les clubs comme sur les fédérations", "Elle dépend seulement des résultats", "Elle est indépendante des audiences"], 0,
     "Les audiences records des dernières compétitions ont montré l'existence d'un public jusque-là supposé absent.", 3],
  ]),

  notion("sp2-sport-collectif-tactique", S, "Tactique et jeu collectif",
    "Systèmes, principes, analyse.",
    "Un système de jeu n'est qu'un point de départ : c'est le mouvement qui compte.",
    2, [
    ["Que désigne un système de jeu au football ?", ["La répartition initiale des joueurs sur le terrain", "La stratégie de match définie par l'entraîneur avant la rencontre", "Le style de jeu propre à une équipe", "La seule organisation défensive de l'équipe"], 0,
     "Le 4-4-2 ou le 4-3-3 décrivent une disposition, non un comportement."],
    ["Qu'est-ce que le pressing au football ?", ["Une pression collective sur le porteur du ballon pour le récupérer haut", "Un marquage individuel de chaque adversaire sur toute la surface du terrain", "Un repli défensif rapide de toute l'équipe derrière la ligne médiane du terrain", "Une accélération offensive menée par les seuls attaquants"], 0,
     "Il exige une coordination fine : un joueur mal placé le rend inefficace."],
    ["Qu'est-ce que la défense de zone ?", ["Chaque joueur défend un espace plutôt qu'un adversaire", "Une défense alignée sur une même ligne à hauteur du milieu de terrain", "Un marquage individuel strict de chaque adversaire désigné à l'avance", "Une défense organisée en infériorité numérique après une exclusion"], 0,
     "Elle s'oppose au marquage individuel, où chacun suit un adversaire désigné."],
    ["Qu'est-ce que le hors-jeu de position au handball ?", ["Une notion inexistante : il n'y a pas de hors-jeu au handball", "Un placement irrégulier en attaque", "Une entrée fautive dans la zone", "Un dépassement de la ligne médiane"], 0,
     "Seule la zone de six mètres est interdite aux joueurs de champ."],
    ["Qu'est-ce qu'une contre-attaque en sport collectif ?", ["Une attaque rapide lancée après récupération du ballon", "Une attaque placée face à une défense entièrement replacée", "Une relance longue du gardien vers l'avant", "Une transition défensive après une perte de balle"], 0,
     "Elle exploite le déséquilibre momentané de l'adversaire encore en position offensive."],
    ["Qu'est-ce que la possession de balle comme indicateur ?", ["Une statistique dont la corrélation avec la victoire est faible", "Un indicateur fiable de la domination exercée par une équipe sur l'autre", "Un critère réglementaire pris en compte en cas d'égalité au score", "Un déterminant direct du score final"], 0,
     "Certaines équipes ont bâti leur succès sur une possession volontairement faible."],
    ["Qu'est-ce que l'analyse vidéo dans le sport collectif ?", ["Un outil d'étude des comportements et des adversaires", "Un dispositif d'arbitrage permettant de revoir les actions litigieuses", "Un support de communication destiné aux partenaires du club", "Un moyen de recrutement réservé aux jeunes joueurs en formation"], 0,
     "Les clubs professionnels emploient aujourd'hui des équipes d'analystes à temps plein."],
    ["Qu'est-ce que les données de suivi des joueurs ?", ["Des mesures de position, de vitesse et de charge par capteurs", "Des statistiques de match publiées à la fin de chaque rencontre", "Des relevés d'entraînement tenus à la main par le préparateur physique", "Des données médicales couvertes par le secret"], 0,
     "Elles servent à ajuster la charge d'entraînement autant qu'à analyser le jeu."],
    ["Qu'est-ce que la charge d'entraînement ?", ["La quantité et l'intensité du travail imposé à l'athlète", "Le poids soulevé", "Le volume horaire seul", "La difficulté perçue"], 0,
     "Son suivi vise à concilier progression et prévention des blessures."],
    ["Pourquoi le sport collectif résiste-t-il à la modélisation statistique ?", ["Les interactions entre joueurs y sont trop nombreuses et contextuelles", "Les données sont insuffisantes", "Les règles changent trop souvent", "Les échantillons sont trop petits"], 0,
     "Les modèles fonctionnent mieux dans les sports à actions discrètes, comme le baseball.", 3],
  ]),

  notion("sp2-jeux-traditionnels", S, "Jeux et sports traditionnels",
    "Pratiques régionales et populaires, souvent antérieures au sport moderne.",
    "De nombreux jeux traditionnels ont survécu à la standardisation sportive.",
    2, [
    ["Qu'est-ce que la pétanque ?", ["Un jeu de boules né en Provence au début du XXe siècle", "Un jeu de boules médiéval pratiqué dans toute l'Europe du Nord", "Une variante du jeu provençal en mouvement", "Un jeu de quilles provençal"], 0,
     "Le nom vient de l'occitan pès tancats, les pieds joints, qui la distingue du jeu provençal."],
    ["Qu'est-ce que la pelote basque ?", ["Une famille de jeux de balle contre un mur ou un fronton", "Un jeu de balle au filet opposant deux équipes de trois joueurs", "Un jeu de crosse pratiqué sur les places des villages basques", "Une variante basque du squash"], 0,
     "Plusieurs spécialités existent, à main nue, à la chistera ou à la pala."],
    ["Qu'est-ce que la lutte bretonne ?", ["Le gouren, une lutte traditionnelle sans mise au sol brutale", "Une lutte celte de force", "Un combat de gaulois reconstitué", "Une variante du judo"], 0,
     "Elle interdit de faire chuter l'adversaire sur le dos sans l'accompagner."],
    ["Qu'est-ce que le tir à la corde ?", ["Un sport d'équipe autrefois olympique", "Un jeu de kermesse sans fédération ni règlement", "Un exercice militaire d'entraînement collectif", "Un sport de démonstration présenté à Paris en 1924"], 0,
     "Il figurait au programme olympique de 1900 à 1920."],
    ["Qu'est-ce que le jeu de quilles au maillet ?", ["Un jeu traditionnel du Sud-Ouest de la France", "Un jeu de boules normand joué sur une piste de terre", "Un jeu de palets pratiqué dans les fêtes bretonnes", "Un jeu picard de lancer"], 0,
     "De nombreuses variantes régionales existent, avec des règles et des matériels distincts."],
    ["Qu'est-ce que le palet breton ?", ["Un jeu d'adresse consistant à lancer des disques sur une planche", "Un jeu de boules de fonte que l'on lance sur un terrain de terre battue", "Une variante bretonne de la pétanque", "Un jeu de quilles de bois"], 0,
     "Il se joue sur planche en bois ou sur terre selon les régions."],
    ["Qu'est-ce que la course landaise ?", ["Un spectacle taurin sans mise à mort où l'homme évite la vache", "Une course de taureaux", "Un rodéo régional", "Une corrida sans épée"], 0,
     "Écarteurs et sauteurs y démontrent une maîtrise du placement et du timing."],
    ["Qu'est-ce que le hurling irlandais ?", ["Un sport de crosse rapide d'origine gaélique", "Un jeu de balle au mur pratiqué dans les villages irlandais", "Un sport de lancer de poids pratiqué en Écosse", "Une variante irlandaise du hockey sur gazon moderne"], 0,
     "Il est resté amateur, organisé par une association fondée en 1884 pour défendre les sports gaéliques."],
    ["Qu'est-ce que le sumo ?", ["Une lutte japonaise à forte dimension rituelle", "Un art martial de percussion pratiqué pieds et poings nus", "Une lutte de force pure sans aucune règle rituelle", "Un sport de démonstration réservé aux fêtes"], 0,
     "Sel purificateur, gestes codifiés et hiérarchie stricte encadrent chaque combat."],
    ["Pourquoi les jeux traditionnels ont-ils souvent reculé ?", ["La standardisation des sports modernes et l'exode rural les ont marginalisés", "Ils étaient trop dangereux", "Ils ont été interdits", "Ils manquaient de règles"], 0,
     "Plusieurs connaissent aujourd'hui un regain, porté par des politiques patrimoniales locales.", 3],
  ]),

  notion("sp2-organisation-competitions", S, "Organiser une compétition",
    "Formats, calendriers, logistique.",
    "Le format d'une compétition détermine largement les chances des participants.",
    2, [
    ["Qu'est-ce qu'un tournoi à élimination directe ?", ["Une compétition où une défaite élimine", "Un championnat disputé en matchs aller et retour", "Un tournoi organisé en poules de quatre équipes", "Un système suisse à rondes fixes"], 0,
     "Il produit un vainqueur rapidement mais dépend fortement du tirage."],
    ["Qu'est-ce qu'un championnat en poules ?", ["Une phase où chaque équipe rencontre toutes les autres du groupe", "Une phase finale disputée par les équipes les mieux classées du tournoi", "Un tournoi de qualification préalable", "Un classement établi sur les points cumulés"], 0,
     "Il réduit l'effet du hasard mais allonge la durée de la compétition."],
    ["Qu'est-ce que le système suisse ?", ["Un format appariant les concurrents de niveau proche à chaque ronde", "Un tournoi à élimination organisé sur deux tableaux parallèles indépendants", "Un championnat complet réparti sur l'ensemble de la saison sportive annuelle", "Un tournoi à handicap dont les points sont pondérés selon le classement"], 0,
     "Très utilisé aux échecs, il permet de classer de nombreux participants en peu de rondes."],
    ["Qu'est-ce qu'une tête de série ?", ["Un concurrent placé dans le tableau pour éviter les affrontements précoces entre favoris", "Le premier inscrit", "Le tenant du titre", "Le meilleur classé mondial"], 0,
     "Le nombre de têtes de série varie selon la taille du tableau."],
    ["Qu'est-ce qu'une wild card ?", ["Une invitation accordée à un concurrent non qualifié", "Un joker de repêchage accordé au meilleur éliminé des qualifications", "Une qualification automatique réservée au tenant du titre", "Un droit de participation acheté au tournoi"], 0,
     "Elle sert à inviter des locaux, des revenants de blessure ou de jeunes espoirs."],
    ["Qu'est-ce qu'un calendrier sportif international ?", ["Une coordination des dates entre fédérations et ligues", "Le programme détaillé de toutes les rencontres d'une compétition", "Un classement annuel des nations", "Un règlement propre à chaque saison"], 0,
     "Les conflits entre clubs et sélections nationales y sont récurrents."],
    ["Qu'est-ce que le fair-play sportif ?", ["Un ensemble de comportements respectant l'adversaire et l'esprit du jeu", "Une règle écrite", "Une sanction disciplinaire", "Un classement de discipline"], 0,
     "Le classement du fair-play peut départager des équipes à égalité dans certaines compétitions."],
    ["Qu'est-ce que la billetterie nominative ?", ["Un billet associé à l'identité de son détenteur", "Un billet numéroté attribué à une place précise du stade", "Un abonnement de saison donnant accès à toutes les rencontres", "Un billet électronique présenté sur téléphone à l'entrée"], 0,
     "Elle vise à lutter contre la revente illégale et à sécuriser les enceintes."],
    ["Qu'est-ce qu'un héritage olympique ?", ["Les effets durables d'un événement sur la ville hôte", "Le patrimoine sportif d'un pays", "Les infrastructures construites", "Les médailles remportées"], 0,
     "Les évaluations montrent des résultats très inégaux selon la planification préalable."],
    ["Pourquoi les candidatures olympiques se sont-elles raréfiées ?", ["Le coût et les dépassements budgétaires ont dissuadé de nombreuses villes", "Le CIO a lui-même limité le nombre de candidatures recevables pour chaque édition", "Les règles de candidature sont devenues bien trop strictes pour les grandes villes", "L'intérêt du public pour les Jeux a nettement baissé"], 0,
     "Plusieurs référendums locaux ont abouti au retrait de candidatures dans les années 2010.", 3],
  ]),

  notion("sp2-nutrition-sportive", S, "Nutrition et sport",
    "Apports, hydratation, compléments.",
    "L'alimentation du sportif diffère surtout par les quantités, non par la nature des aliments.",
    2, [
    ["Quel est le principal carburant de l'effort intense ?", ["Le glycogène musculaire", "Les lipides", "Les protéines", "Le glucose sanguin seul"], 0,
     "À forte intensité, l'organisme puise principalement dans ses réserves de glucides."],
    ["Qu'est-ce que la recharge glucidique avant une épreuve d'endurance ?", ["Une augmentation des apports en glucides pour saturer les réserves", "Un jeûne préalable de vingt-quatre heures destiné à vider les réserves", "Un apport en protéines renforcé les jours précédents", "Une hydratation accrue la veille de l'épreuve"], 0,
     "Elle se pratique dans les jours précédant une épreuve longue, avec une réduction de l'entraînement."],
    ["Quel besoin en protéines un sportif d'endurance a-t-il ?", ["Un besoin accru mais couvert par une alimentation variée", "Un besoin identique au sédentaire", "Un besoin nécessitant des compléments", "Un besoin triple"], 0,
     "Les besoins augmentent, mais la consommation spontanée les couvre le plus souvent."],
    ["Quel est le principal risque d'une déshydratation à l'effort ?", ["Une baisse de performance et un risque de coup de chaleur", "Une carence minérale entraînant des troubles du rythme cardiaque", "Une crampe musculaire isolée, sans autre conséquence sur l'effort", "Une hypoglycémie brutale en fin d'épreuve"], 0,
     "Une perte de deux pour cent du poids corporel suffit à dégrader nettement la performance."],
    ["Qu'est-ce que l'hyponatrémie d'effort ?", ["Une chute du sodium sanguin liée à une consommation excessive d'eau pure", "Une déshydratation sévère provoquée par une transpiration abondante et prolongée", "Une carence en potassium liée à un apport alimentaire nettement insuffisant", "Une perte de sel par la sueur que les boissons ne parviennent pas à compenser"], 0,
     "Rare mais potentiellement mortelle, elle a été observée sur des marathons et des ultras."],
    ["Qu'est-ce qu'une boisson de l'effort ?", ["Une boisson apportant eau, glucides et sodium en proportions adaptées", "Une boisson énergisante à base de caféine et de taurine, prise avant l'effort", "Une boisson protéinée destinée à reconstituer la masse musculaire après l'effort", "Une eau fortement minéralisée"], 0,
     "Les boissons énergisantes, à base de caféine, n'ont pas la même fonction."],
    ["Que sait-on de l'efficacité des compléments alimentaires pour le sport ?", ["Très peu ont une efficacité démontrée", "La plupart sont efficaces", "Ils sont tous inefficaces", "Leur efficacité dépend du niveau sportif"], 0,
     "Caféine, créatine, nitrates et bicarbonate figurent parmi les rares aux effets établis."],
    ["Quel risque les compléments alimentaires présentent-ils pour un sportif contrôlé ?", ["Une contamination par des substances interdites", "Un surdosage vitaminique seul", "Une allergie", "Une interaction médicamenteuse"], 0,
     "Le principe de responsabilité stricte s'applique : l'athlète répond de ce qu'il ingère."],
    ["Qu'est-ce que la fenêtre métabolique après l'effort ?", ["Une période supposée optimale pour la récupération nutritionnelle", "Le temps de digestion nécessaire avant de reprendre un entraînement", "La durée de reconstitution des réserves", "Le délai à respecter avant le repas"], 0,
     "Son importance a été largement révisée à la baisse par les travaux récents."],
    ["Quelle est la base d'une alimentation de sportif ?", ["Une alimentation variée et suffisante, adaptée en quantité", "Un régime hyperprotéiné", "Une alimentation sans graisse", "Un régime standardisé"], 0,
     "Les besoins spécifiques concernent surtout le volume, le timing et l'hydratation.", 3],
  ]),

  notion("sp2-violence-sport", S, "Violence et supporterisme",
    "Tribunes, régulation, prévention.",
    "Le supporterisme n'est pas réductible à la violence : il constitue une culture organisée.",
    2, [
    ["Qu'est-ce qu'un groupe ultra ?", ["Un groupe de supporters organisé, actif dans l'animation des tribunes", "Un groupe de hooligans qui vient au stade dans le seul but d'en découdre", "Une association de supporters officiellement reconnue et financée par le club", "Un club de fans réuni autour d'un joueur"], 0,
     "Le mouvement est né en Italie dans les années 1960 et repose sur une organisation structurée."],
    ["Quelle catastrophe survient au stade du Heysel en 1985 ?", ["Un mouvement de foule mortel avant une finale européenne", "L'effondrement d'une tribune entière sous le poids des supporters", "Un incendie parti d'une tribune en bois", "Une bousculade à la sortie du stade après le match"], 0,
     "Trente-neuf morts, majoritairement des supporters italiens. Les clubs anglais furent exclus des coupes d'Europe."],
    ["Que s'est-il passé à Hillsborough en 1989 ?", ["Une bousculade mortelle due à une mauvaise gestion des accès", "Un affrontement entre supporters des deux clubs sur la pelouse", "L'effondrement des gradins d'une tribune surchargée de spectateurs", "L'incendie d'une tribune en bois déclaré pendant la rencontre"], 0,
     "Quatre-vingt-dix-sept morts. Il a fallu près de trente ans pour établir les responsabilités officielles."],
    ["Quelle conséquence le drame de Hillsborough a-t-il eue sur les stades anglais ?", ["La suppression des places debout dans l'élite", "L'interdiction de tout déplacement de supporters à l'extérieur", "La fermeture définitive de plusieurs stades vétustes", "L'interdiction des groupes de supporters"], 0,
     "Le rapport Taylor a imposé des stades entièrement assis dans les divisions supérieures."],
    ["Qu'est-ce qu'une interdiction administrative de stade ?", ["Une mesure préfectorale interdisant l'accès à un individu", "Une sanction judiciaire prononcée par un tribunal correctionnel", "Une exclusion décidée par le club recevant", "Une sanction prononcée par la fédération"], 0,
     "Elle est prononcée sans jugement, ce qui fait l'objet de critiques sur le plan des libertés."],
    ["Qu'est-ce que le tifo dans les tribunes ?", ["Une animation visuelle collective préparée par les supporters", "Un chant repris en chœur par l'ensemble des supporters d'une tribune", "Un déplacement organisé en autocar vers le stade de l'adversaire", "Le drapeau du club remis au capitaine de l'équipe avant le coup d'envoi"], 0,
     "Certains mobilisent des centaines de personnes et plusieurs semaines de préparation."],
    ["Qu'est-ce que la lutte contre le racisme dans les stades ?", ["Un ensemble de dispositifs de prévention et de sanction encore jugés insuffisants", "Une compétence exclusive des clubs, que les fédérations laissent à leur libre appréciation", "Une action limitée aux seules compétitions internationales organisées par la FIFA et l'UEFA", "Un dispositif purement symbolique sans effet juridique"], 0,
     "Les protocoles d'interruption de match sont désormais prévus par les règlements internationaux."],
    ["Qu'est-ce que le dialogue avec les supporters ?", ["Une approche privilégiant la médiation plutôt que la seule répression", "Une consultation formelle des associations", "Une négociation commerciale", "Un dispositif de sécurité"], 0,
     "Plusieurs pays européens ont réduit les incidents en développant cette approche."],
    ["Qu'est-ce que la violence dans le sport amateur ?", ["Un phénomène concernant surtout les rapports avec les arbitres et entre joueurs", "Un phénomène inexistant", "Un problème limité aux tribunes", "Une question réservée au football"], 0,
     "Les fédérations recensent chaque année plusieurs milliers d'incidents en France."],
    ["Pourquoi l'arbitrage amateur connaît-il une crise de recrutement ?", ["Les incivilités et agressions découragent les vocations", "Le niveau d'exigence a augmenté", "Les formations sont trop longues", "La rémunération a baissé"], 0,
     "Plusieurs fédérations ont mis en place des journées d'arrêt des compétitions pour alerter sur ce point.", 3],
  ]),

  notion("sp2-sport-environnement", S, "Sport et environnement",
    "Empreinte des événements, adaptation, sports de nature.",
    "Le réchauffement climatique remet en cause la tenue de certaines compétitions historiques.",
    2, [
    ["Quel poste domine l'empreinte carbone d'un grand événement sportif ?", ["Le déplacement des spectateurs", "La construction des infrastructures", "La consommation d'énergie des stades", "L'organisation logistique"], 0,
     "Le transport aérien international en constitue la part la plus lourde."],
    ["Quel effet le réchauffement a-t-il sur les sports d'hiver ?", ["Il réduit l'enneigement naturel et menace des stations de basse altitude", "Il allonge la saison de ski en repoussant la fonte des neiges au printemps", "Il n'a pas encore d'effet mesuré sur l'enneigement", "Il déplace les compétitions vers le cœur de l'été"], 0,
     "De nombreuses épreuves de Coupe du monde ont été annulées ou déplacées ces dernières années."],
    ["Qu'est-ce que la neige de culture ?", ["De la neige produite artificiellement à partir d'eau et d'air", "De la neige transportée par camion depuis les glaciers d'altitude", "De la neige naturelle compactée par le passage des engins de damage", "De la neige conservée d'une saison sur l'autre sous des bâches isolantes"], 0,
     "Sa production exige des températures suffisamment basses et une grande quantité d'eau."],
    ["Qu'est-ce qui menace certaines épreuves d'endurance estivales ?", ["Les vagues de chaleur et le risque sanitaire", "Le manque de participants sur les épreuves les plus longues", "La sécheresse qui rend les parcours impraticables", "Les restrictions de circulation en ville"], 0,
     "Plusieurs marathons ont été déplacés dans le calendrier ou dans la journée."],
    ["Qu'est-ce que l'érosion des sentiers par la fréquentation sportive ?", ["Une dégradation des sols par le passage répété", "Un effet des intempéries seules", "Un phénomène naturel", "Un problème limité aux zones humides"], 0,
     "Certains sites de montagne ou de bord de mer imposent désormais des quotas de fréquentation."],
    ["Qu'est-ce que le dérangement de la faune par les sports de nature ?", ["Une perturbation du repos et de la reproduction des animaux sauvages", "Une pollution sonore produite par les engins motorisés en pleine nature", "Une destruction directe des habitats naturels", "Un risque de collision avec les animaux"], 0,
     "Les périodes de reproduction et d'hivernage sont les plus sensibles."],
    ["Qu'est-ce qu'une zone de quiétude en montagne ?", ["Un secteur où la fréquentation est limitée pour protéger la faune", "Une zone interdite aux remontées mécaniques", "Une réserve naturelle intégrale", "Un secteur hors-piste sécurisé"], 0,
     "Le tétras-lyre, très sensible au dérangement hivernal, en est souvent le motif."],
    ["Qu'est-ce que la sobriété appliquée aux événements sportifs ?", ["Une réduction de la taille, des déplacements et des constructions", "Une baisse volontaire du nombre de spectateurs admis dans les enceintes", "Une réduction des dépenses d'organisation et du budget de communication", "Une limitation de la publicité dans les stades"], 0,
     "Elle suppose notamment de privilégier les équipements existants."],
    ["Qu'est-ce que la compensation carbone d'un événement ?", ["Le financement de projets censés compenser les émissions produites", "Une réduction directe des émissions produites par l'organisation de l'épreuve", "Une taxe environnementale prélevée sur chacun des billets vendus au public", "Un bilan carbone détaillé publié par l'organisateur après l'événement"], 0,
     "Son efficacité réelle est très discutée, notamment pour les projets forestiers."],
    ["Pourquoi le sport est-il un enjeu de sensibilisation environnementale ?", ["Sa visibilité et sa dépendance aux conditions naturelles en font un porte-voix", "Il émet peu de carbone", "Il concerne peu de personnes", "Il est indépendant du climat"], 0,
     "Les athlètes de sports de nature sont parmi les premiers témoins des changements en cours.", 3],
  ]),
];
