/**
 * Lot 013 — Ponctuation (13 règles) et Typographie (12 règles).
 *
 * Deuxième vague. Comme au lot 001, aucune règle ne demande de RETIRER un signe :
 * seules les omissions et les substitutions sont exprimables.
 */
import type { ContentBatch } from "../../../src/lib/content";

export const BATCH_013: ContentBatch = {
  id: "batch-013",
  rules: [
    /* ─────────────── ponctuation ─────────────── */
    {
      slug: "virgule-cest-a-dire",
      category: "Ponctuation",
      title: "Virgule devant « c'est-à-dire »",
      statement: "<b>c'est-à-dire</b> introduit une reformulation : une virgule le précède.",
      tip: "La reformulation est une incise : elle se détache de ce qui précède.",
      difficulty: 2,
      sentences: [
        { marked: "Il travaille en [alternance] c'est-à-dire trois jours par semaine.", fix: "alternance," },
        { marked: "La séance dure deux [heures] c'est-à-dire jusqu'à midi.", fix: "heures," },
        { marked: "Elle est [pigiste] c'est-à-dire payée à l'article.", fix: "pigiste," },
        { marked: "Le délai court jusqu'au [30] c'est-à-dire dans huit jours.", fix: "30," },
        { marked: "Il est arrivé tard, c'est-à-dire après la fermeture.", fix: null },
      ],
    },
    {
      slug: "virgule-par-exemple",
      category: "Ponctuation",
      title: "Virgules autour de « par exemple »",
      statement: "Glissé au milieu d'une phrase, <b>par exemple</b> s'entoure de virgules.",
      tip: "Retire-le : si la phrase tient, il était intercalé, donc encadré.",
      difficulty: 2,
      sentences: [
        { marked: "Certains [fruits] par exemple, se conservent tout l'hiver.", fix: "fruits," },
        { marked: "Une langue [ancienne] par exemple, demande de la patience.", fix: "ancienne," },
        { marked: "Ce [matériau] par exemple, résiste très mal au gel.", fix: "matériau," },
        { marked: "Un [détail] par exemple, peut changer tout le sens.", fix: "détail," },
        { marked: "Certaines pièces, par exemple, ont été refaites entièrement.", fix: null },
      ],
    },
    {
      slug: "virgule-notamment",
      category: "Ponctuation",
      title: "Virgule devant « notamment »",
      statement: "<b>notamment</b> introduit un exemple détaché : il est précédé d'une virgule.",
      tip: "Notamment ouvre une parenthèse d'exemples : elle commence par une virgule.",
      difficulty: 2,
      sentences: [
        { marked: "Plusieurs services sont [concernés] notamment la comptabilité.", fix: "concernés," },
        { marked: "Il connaît bien la [région] notamment la vallée du nord.", fix: "région," },
        { marked: "Ces mesures touchent les plus [jeunes] notamment les apprentis.", fix: "jeunes," },
        { marked: "Le rapport pointe des [manques] notamment en personnel.", fix: "manques," },
        { marked: "Le texte a été revu, notamment dans sa conclusion.", fix: null },
      ],
    },
    {
      slug: "deux-points-explication",
      category: "Ponctuation",
      title: "Deux-points d'explication",
      statement: "Les <b>deux-points</b> annoncent aussi une cause ou une conséquence, sans qu'il soit besoin de « car » (l'un des emplois déjà cités pour les deux-points en général).",
      tip: "Remplace-les par « en effet » : si ça marche, les deux-points conviennent.",
      difficulty: 2,
      sentences: [
        { marked: "Il n'est pas [venu] il avait complètement oublié la date.", fix: "venu :" },
        { marked: "La séance a été [écourtée] la salle devait être libérée.", fix: "écourtée :" },
        { marked: "Nous partirons [tôt] la route est longue jusqu'à la côte.", fix: "tôt :" },
        { marked: "Le dossier est [incomplet] deux pièces manquent encore.", fix: "incomplet :" },
        { marked: "Elle a refusé : les conditions ne lui convenaient pas.", fix: null },
      ],
    },
    {
      slug: "guillemets-imbriques",
      category: "Ponctuation",
      title: "Guillemets à l'intérieur de guillemets",
      statement: "Une citation dans une citation prend des <b>guillemets anglais</b> à l'intérieur des chevrons français.",
      tip: "Les chevrons restent à l'extérieur : les guillemets anglais “ ” se glissent dedans.",
      difficulty: 3,
      sentences: [
        { marked: "Il a dit : « elle a répondu [«non»] sans hésiter ».", fix: "“non”" },
        { marked: "« Le mot [«urgent»] revenait sans cesse », a-t-il précisé.", fix: "“urgent”" },
        { marked: "Elle écrit : « il a crié [«assez»] et il est parti ».", fix: "“assez”" },
        { marked: "« Le panneau indiquait [«fermé»] », a rapporté le témoin.", fix: "“fermé”" },
        { marked: "Il a dit : « elle a murmuré “merci” avant de sortir ».", fix: null },
      ],
    },
    {
      slug: "virgule-avant-etc",
      category: "Ponctuation",
      title: "Virgule devant « etc. »",
      statement: "<b>etc.</b> clôt une énumération et se sépare du dernier terme par une <b>virgule</b>.",
      tip: "Etc. est un élément de la liste : il se sépare comme les autres.",
      difficulty: 2,
      sentences: [
        { marked: "Il faut des vis, des clous, des [chevilles] etc.", fix: "chevilles," },
        { marked: "Elle collectionne timbres, pièces, [cartes] etc.", fix: "cartes," },
        { marked: "Prends du pain, du fromage, des [fruits] etc.", fix: "fruits," },
        { marked: "On y trouve romans, essais, [manuels] etc.", fix: "manuels," },
        { marked: "Le carton contenait des vis, des clous, des chevilles, etc.", fix: null },
      ],
    },
    {
      slug: "espace-apres-virgule",
      category: "Ponctuation",
      title: "Espace après la virgule, jamais avant",
      statement: "La virgule se colle au mot qui la précède et se sépare du suivant par une <b>espace</b>.",
      tip: "La virgule ferme, elle n'ouvre pas : elle s'appuie sur le mot d'avant.",
      difficulty: 1,
      sentences: [
        { marked: "Il est [arrivé] , puis reparti sans dire un mot.", fix: "arrivé," },
        { marked: "Elle a tout [rangé] , nettoyé, puis fermé la porte.", fix: "rangé," },
        { marked: "Le train part à huit [heures] , pas une minute plus tard.", fix: "heures," },
        { marked: "Prends ton [manteau] , il fait vraiment froid dehors.", fix: "manteau," },
        { marked: "Il est venu, il a vu, il est reparti aussitôt.", fix: null },
      ],
    },
    {
      slug: "apostrophe-typographique",
      category: "Ponctuation",
      title: "L'apostrophe courbe",
      statement: "En typographie d'édition soignée, l'apostrophe est <b>courbe</b> ’ — l'apostrophe droite ' est un signe de machine à écrire, très répandu à l'écrit courant (y compris ailleurs dans ce module).",
      tip: "Le traitement de texte la corrige souvent automatiquement dans les documents destinés à l'impression.",
      difficulty: 3,
      sentences: [
        { marked: "Il n'a rien dit de [l'affaire] depuis hier soir.", fix: "l’affaire" },
        { marked: "Il attend [l'ouverture] de la mairie depuis huit heures.", fix: "l’ouverture" },
        { marked: "Le prix de [l'essence] a encore augmenté ce mois-ci.", fix: "l’essence" },
        { marked: "Personne ne connaît [l'auteur] de ce message anonyme.", fix: "l’auteur" },
        { marked: "L’ouverture de l’enquête a été annoncée ce matin.", fix: null },
      ],
    },
    {
      slug: "trait-union-inversion",
      category: "Ponctuation",
      title: "Trait d'union dans l'inversion",
      statement: "Dans une inversion, un <b>trait d'union</b> relie le verbe et le pronom, et un <b>t</b> s'intercale quand le verbe finit par une voyelle : dit-il, viendra-t-elle.",
      tip: "Le t de liaison ne s'ajoute qu'après une voyelle, et jamais avec une apostrophe.",
      difficulty: 2,
      sentences: [
        { marked: "« Rien n'a changé », [dit-t-il] en refermant le dossier.", fix: "dit-il" },
        { marked: "[Viendra-elle] finalement à la réunion de mardi ?", fix: "Viendra-t-elle" },
        { marked: "« C'est faux », [répondit-t-elle] sans hausser la voix.", fix: "répondit-elle" },
        { marked: "[Va-t'il] pleuvoir avant la fin de la journée ?", fix: "Va-t-il" },
        { marked: "« J'arrive », dit-il en attrapant son manteau.", fix: null },
      ],
    },
    {
      slug: "point-interrogation-indirecte",
      category: "Ponctuation",
      title: "Pas de point d'interrogation après une interrogative indirecte",
      statement: "Une question rapportée n'est plus une question : elle se termine par un <b>point</b>.",
      tip: "S'il y a « il demande si », la phrase affirme : point final.",
      difficulty: 3,
      sentences: [
        { marked: "Il se demande si le train partira bien à l'heure [?]", fix: "." },
        { marked: "Je ne sais vraiment pas où il a rangé les clés [?]", fix: "." },
        { marked: "Elle voudrait savoir quand la réunion du conseil commence [?]", fix: "." },
        { marked: "Personne ici ne comprend pourquoi il a soudain refusé [?]", fix: "." },
        { marked: "Elle demande si tout est prêt pour le départ.", fix: null },
      ],
    },
    {
      slug: "virgule-adverbe-phrase",
      category: "Ponctuation",
      title: "Virgule après un adverbe qui porte sur la phrase",
      statement: "<b>heureusement</b>, <b>curieusement</b>, <b>évidemment</b> placés en tête portent sur toute la phrase : une virgule les détache.",
      tip: "L'adverbe commente la phrase entière, il ne modifie pas le verbe : il se détache.",
      difficulty: 2,
      sentences: [
        { marked: "[Heureusement] personne n'a été blessé dans l'accident.", fix: "Heureusement," },
        { marked: "[Curieusement] aucun témoin ne se souvient de rien.", fix: "Curieusement," },
        { marked: "[Évidemment] tout le monde a fait semblant de comprendre.", fix: "Évidemment," },
        { marked: "[Naturellement] il est arrivé dernier, comme toujours.", fix: "Naturellement," },
        { marked: "Malheureusement, la séance a été annulée au dernier moment.", fix: null },
      ],
    },
    {
      slug: "virgule-adjectifs-coordonnes",
      category: "Ponctuation",
      title: "Virgule entre deux adjectifs",
      statement: "Deux adjectifs qui qualifient le même nom sans être reliés par « et » se séparent par une <b>virgule</b>.",
      tip: "Si tu peux glisser « et » entre les deux, mets une virgule à la place.",
      difficulty: 2,
      sentences: [
        { marked: "Ce fut une nuit [froide] humide et interminable.", fix: "froide," },
        { marked: "Il a rendu un travail [soigné] complet et parfaitement lisible.", fix: "soigné," },
        { marked: "Elle porte une robe bleue, [légère] parfaitement coupée.", fix: "légère," },
        { marked: "Un homme [grand] mince et légèrement voûté nous attendait.", fix: "grand," },
        { marked: "C'était une pièce sombre, étroite, mal ventilée.", fix: null },
      ],
    },

    /* ─────────────── typographie ─────────────── */
    {
      slug: "typo-souverains-romains",
      category: "Typographie",
      title: "Les souverains en chiffres romains",
      statement: "Le rang d'un souverain s'écrit en <b>chiffres romains</b>, sans exposant : Louis XIV, François Ier.",
      tip: "Seul « premier » prend un exposant : François Ier, mais Louis XIV.",
      difficulty: 3,
      sentences: [
        { marked: "Louis [14] a régné pendant soixante-douze ans.", fix: "XIV" },
        { marked: "Le roi de la Renaissance française fut François [1er].", fix: "Ier" },
        { marked: "Napoléon [3] a transformé Paris avec Haussmann.", fix: "III" },
        { marked: "L'édit de Nantes fut signé en 1598 par Henri [4ème].", fix: "IV" },
        { marked: "Louis XVI succéda à Louis XV en 1774.", fix: null },
      ],
    },
    {
      slug: "typo-italique-mots-etrangers",
      category: "Typographie",
      title: "Les mots étrangers en italique",
      statement: "Un mot étranger non francisé se met en <b>italique</b> (ce que cet exercice ne peut pas afficher) et garde sa graphie d'origine : a priori, curriculum vitae, in extremis — sans trait d'union ni accent ajoutés.",
      tip: "Une fois le mot entré dans l'usage, il perd son italique : week-end n'en prend plus. Ici, c'est la graphie du mot qu'on corrige, pas sa mise en forme.",
      difficulty: 3,
      sentences: [
        { marked: "Il a joint son [curriculum-vitae] à sa candidature.", fix: "curriculum vitae" },
        { marked: "Rien ne s'y opposait [à] priori au moment de la signature.", fix: "a" },
        { marked: "Le but a été marqué [in-extremis] à la dernière seconde.", fix: "in extremis" },
        { marked: "Il a réagi a [postériori] en relisant tout le dossier.", fix: "posteriori" },
        { marked: "Son curriculum vitae mentionne trois langues étrangères.", fix: null },
      ],
    },
    {
      slug: "typo-majuscule-apres-point",
      category: "Typographie",
      title: "Majuscule après un point, sauf abréviation",
      statement: "Un point final impose une <b>majuscule</b> au mot suivant. Le point abréviatif, lui, n'en impose aucune.",
      tip: "Demande-toi si la phrase est finie : le point de « M. » ne finit rien.",
      difficulty: 2,
      sentences: [
        { marked: "Il est parti sans un mot. [il] reviendra sans doute demain.", fix: "Il" },
        { marked: "La séance est levée. [la] prochaine aura lieu en mars.", fix: "La" },
        { marked: "Une réponse est arrivée. [elle] ne change rien au dossier.", fix: "Elle" },
        { marked: "Le dossier est clos. [rien] ne sera rouvert avant l'automne.", fix: "Rien" },
        { marked: "M. Dupont est passé ce matin. Il repassera demain.", fix: null },
      ],
    },
    {
      slug: "typo-temperature",
      category: "Typographie",
      title: "Écrire une température",
      statement: "Une espace sépare le nombre du symbole de degré, et l'unité se colle juste après : <b>20 °C</b>.",
      tip: "Le degré est un symbole d'unité : il prend une espace comme kg ou %.",
      difficulty: 3,
      sentences: [
        { marked: "La température atteindra [25°C] en début d'après-midi.", fix: "25 °C" },
        { marked: "Le thermostat est réglé sur [19°] toute la journée.", fix: "19 °C" },
        { marked: "Il a fait [-5°C] cette nuit dans la vallée.", fix: "−5 °C" },
        { marked: "L'eau bout à [100°c] au niveau de la mer.", fix: "100 °C" },
        { marked: "Le thermomètre indiquait 22 °C à l'ombre.", fix: null },
      ],
    },
    {
      slug: "typo-majuscule-journaux",
      category: "Typographie",
      title: "Majuscule aux titres de journaux",
      statement: "Comme pour les titres d'œuvres, un journal dont le nom commence par un article prend la majuscule sur cet article et sur le nom qui le suit : Le Monde, La Croix, L'Équipe (et sur le premier mot seul quand il n'y a pas d'article : Libération).",
      tip: "L'article fait partie du titre : il prend la majuscule et ne se contracte pas.",
      difficulty: 3,
      sentences: [
        { marked: "Il lit Le [monde] tous les matins dans le train.", fix: "Monde" },
        { marked: "Un article paru dans [libération] a relancé le débat.", fix: "Libération" },
        { marked: "Elle est abonnée à La [croix] depuis maintenant vingt ans.", fix: "Croix" },
        { marked: "Selon [l'équipe], le transfert serait déjà conclu.", fix: "L'Équipe" },
        { marked: "Le Monde et Libération ont publié le même jour.", fix: null },
      ],
    },
    {
      slug: "typo-abrev-pages",
      category: "Typographie",
      title: "Les abréviations de renvoi",
      statement: "Le Lexique de l'Imprimerie nationale préconise <b>p.</b> pour page (au singulier comme au pluriel), <b>vol.</b> pour volume, <b>chap.</b> pour chapitre ; <b>pp.</b> reste courant en bibliographie, mais pas <b>pg.</b>, qui n'est pas une forme reçue.",
      tip: "Une seule lettre suivie d'un point suffit : p. 12-15 couvre plusieurs pages.",
      difficulty: 3,
      sentences: [
        { marked: "Voir le développement, [pg.] 45 à 52 du rapport.", fix: "p." },
        { marked: "Ce passage figure au [chapitre] 3, en fin de volume.", fix: "chap." },
        { marked: "Consultez le [vol] 2 pour les annexes techniques.", fix: "vol." },
        { marked: "La citation se trouve pp. 118-120 de l'édition originale.", fix: null },
        { marked: "Voir p. 45 et chap. 3 pour le détail des calculs.", fix: null },
      ],
    },
    {
      slug: "typo-majuscule-saints",
      category: "Typographie",
      title: "saint, Saint et Saint-",
      statement: "<b>saint</b> reste en minuscule devant le nom d'un personnage, prend la majuscule dans un nom de lieu, avec trait d'union : la Saint-Jean, Saint-Étienne.",
      tip: "La personne garde la minuscule, le lieu et la fête prennent la majuscule.",
      difficulty: 3,
      sentences: [
        { marked: "Il a lu la vie de [Saint] François d'Assise.", fix: "saint" },
        { marked: "Nous passons par [saint-Malo] avant de rejoindre la côte.", fix: "Saint-Malo" },
        { marked: "La fête de la [saint-Jean] tombe le 24 juin.", fix: "Saint-Jean" },
        { marked: "L'église [saint-Sulpice] domine toute la place.", fix: "Saint-Sulpice" },
        { marked: "À Saint-Étienne, on fête la Saint-Jean chaque année.", fix: null },
      ],
    },
    {
      slug: "typo-majuscule-mots-composes",
      category: "Typographie",
      title: "Majuscules dans un nom composé de lieu",
      statement: "Dans un nom de lieu composé, <b>chaque élément significatif</b> prend une majuscule et un trait d'union : Villeneuve-sur-Lot.",
      tip: "Les prépositions et les articles restent en minuscule à l'intérieur du nom.",
      difficulty: 3,
      sentences: [
        { marked: "Ils habitent à Villeneuve-sur-[lot] depuis trois ans.", fix: "Lot" },
        { marked: "Le train s'arrête à Chalon-[Sur]-Saône pendant dix minutes.", fix: "sur" },
        { marked: "Elle vient de Bourg-en-[bresse], préfecture de l'Ain.", fix: "Bresse" },
        { marked: "L'usine se trouve à Nogent-[Le]-Rotrou depuis 1950.", fix: "le" },
        { marked: "Il travaille à Boulogne-sur-Mer depuis janvier.", fix: null },
      ],
    },
    {
      slug: "typo-espace-tiret-intervalle",
      category: "Typographie",
      title: "Le tiret d'intervalle",
      statement: "Entre deux nombres, on emploie un <b>trait d'union</b> sans espace : p. 12-15, 1939-1945 — ni tiret cadratin, ni espaces.",
      tip: "Le trait d'union relie deux bornes : rien ne le sépare des chiffres.",
      difficulty: 3,
      sentences: [
        { marked: "La guerre de [1939–1945] a marqué deux générations.", fix: "1939-1945" },
        { marked: "Consultez les pages [45—52] du rapport annuel.", fix: "45-52" },
        { marked: "L'exposition présente les œuvres de [1900—1950] au musée municipal.", fix: "1900-1950" },
        { marked: "La période [2010–2020] a vu tripler les inscriptions.", fix: "2010-2020" },
        { marked: "Le règne de Louis XIV couvre les années 1643-1715.", fix: null },
      ],
    },
    {
      slug: "typo-abrev-etats",
      category: "Typographie",
      title: "Abréger un nom de pays",
      statement: "Dans un texte français, on évite les sigles anglais <b>USA</b> ou <b>UK</b> : on écrit <b>États-Unis</b>/<b>Royaume-Uni</b> en toutes lettres, ou, en abrégé, <b>É.-U.</b> et <b>R.-U.</b>, avec points et trait d'union.",
      tip: "L'abréviation française reprend les initiales françaises, pas celles de l'anglais — mais la forme en toutes lettres reste la plus courante en France.",
      difficulty: 3,
      sentences: [
        { marked: "Les [USA] ont ratifié l'accord la semaine dernière.", fix: "É.-U." },
        { marked: "Le [UK] a quitté l'Union européenne en 2020.", fix: "R.-U." },
        { marked: "Un accord entre la France et les [US] est en discussion.", fix: "É.-U." },
        { marked: "L'ambassade du [UK] se trouve dans le huitième arrondissement.", fix: "R.-U." },
        { marked: "Les É.-U. et le R.-U. ont signé le même jour.", fix: null },
      ],
    },
    {
      slug: "typo-marques-minuscule",
      category: "Typographie",
      title: "Une marque devenue nom commun",
      statement: "Passée dans l'usage courant, une marque perd sa <b>majuscule</b> : un frigidaire, un kleenex, du scotch.",
      tip: "Si le mot désigne l'objet et non le fabricant, il s'écrit en minuscule.",
      difficulty: 3,
      sentences: [
        { marked: "Passe-moi un [Kleenex], j'ai renversé mon café.", fix: "kleenex" },
        { marked: "Le [Frigidaire] fait un bruit inquiétant depuis hier.", fix: "frigidaire" },
        { marked: "Il a recollé la poignée avec du [Scotch].", fix: "scotch" },
        { marked: "Elle range le linge dans un vieux [Formica] jauni.", fix: "formica" },
        { marked: "Le frigidaire est plein et il ne reste plus de kleenex.", fix: null },
      ],
    },
    {
      slug: "typo-numero-telephone",
      category: "Typographie",
      title: "Écrire un numéro de téléphone",
      statement: "Un numéro français s'écrit par <b>groupes de deux chiffres</b> séparés par une espace : 01 23 45 67 89.",
      tip: "Ni points ni tirets : l'espace suffit, et rend le numéro lisible.",
      difficulty: 2,
      sentences: [
        { marked: "Appelez-moi au [01.23.45.67.89] avant midi.", fix: "01 23 45 67 89" },
        { marked: "Son portable est le [06-12-34-56-78], si besoin.", fix: "06 12 34 56 78" },
        { marked: "Le standard répond au [0123456789] toute la journée.", fix: "01 23 45 67 89" },
        { marked: "Notez le [04/56/78/90/12] pour les urgences.", fix: "04 56 78 90 12" },
        { marked: "Le secrétariat répond au 01 45 67 89 10.", fix: null },
      ],
    },
  ],
};
