/**
 * Lot 014 — Registre et style (13 règles) et Écrits professionnels (12 règles).
 */
import type { ContentBatch } from "../../../src/lib/content";

export const BATCH_014: ContentBatch = {
  id: "batch-014",
  rules: [
    /* ─────────────── registre et style ─────────────── */
    {
      slug: "anglicisme-staff",
      category: "Registre et style",
      title: "staff ou personnel",
      statement: "Le français dit <b>personnel</b>, <b>équipe</b> ou <b>effectifs</b>.",
      tip: "Trois mots français, trois nuances : le staff n'en a qu'une.",
      difficulty: 1,
      sentences: [
        { marked: "Tout le [staff] a été convoqué pour huit heures.", fix: "personnel" },
        { marked: "Le [staff] médical assure une permanence de nuit.", fix: "personnel" },
        { marked: "Elle dirige un [staff] de quinze personnes depuis trois ans.", fix: "équipe" },
        { marked: "Le [staff] technique intervient dès la première alerte.", fix: "personnel" },
        { marked: "Le personnel administratif travaille au troisième étage.", fix: null },
      ],
    },
    {
      slug: "anglicisme-job",
      category: "Registre et style",
      title: "job ou emploi",
      statement: "On dit <b>emploi</b>, <b>poste</b>, <b>travail</b> ou <b>métier</b> selon le cas.",
      tip: "Le mot précis vaut mieux que le mot passe-partout.",
      difficulty: 1,
      sentences: [
        { marked: "Il a trouvé un [job] dans une agence de communication.", fix: "emploi" },
        { marked: "Ce [job] demande beaucoup de rigueur et de patience.", fix: "poste" },
        { marked: "Elle cherche un petit [job] pour financer ses études.", fix: "travail" },
        { marked: "Son [job] consiste à vérifier chaque dossier reçu.", fix: "travail" },
        { marked: "Elle occupe ce poste depuis maintenant quatre ans.", fix: null },
      ],
    },
    {
      slug: "anglicisme-business",
      category: "Registre et style",
      title: "business ou activité",
      statement: "Selon le contexte : <b>activité</b>, <b>affaires</b>, <b>commerce</b> ou <b>entreprise</b>.",
      tip: "Business recouvre quatre notions distinctes : choisis celle qui convient.",
      difficulty: 1,
      sentences: [
        { marked: "Son [business] marche bien depuis l'ouverture du magasin.", fix: "commerce" },
        { marked: "Nous développons ce [business] depuis deux ans à peine.", fix: "activité" },
        { marked: "Le [business] a repris après une année difficile.", fix: "chiffre d'affaires" },
        { marked: "Il a monté son propre [business] à vingt-cinq ans.", fix: "entreprise" },
        { marked: "Son commerce prospère malgré la concurrence du centre-ville.", fix: null },
      ],
    },
    {
      slug: "anglicisme-briefer",
      category: "Registre et style",
      title: "briefer ou informer",
      statement: "On <b>informe</b>, on <b>renseigne</b>, on <b>met au courant</b> — le verbe briefer n'ajoute rien.",
      tip: "Un briefing est une réunion d'information : le mot français existe déjà.",
      difficulty: 2,
      sentences: [
        { marked: "Peux-tu [briefer] l'équipe avant la réunion de dix heures ?", fix: "informer" },
        { marked: "Il a été [briefé] sur le dossier hier après-midi.", fix: "informé" },
        { marked: "Un [briefing] complet est prévu chaque lundi matin.", fix: "point" },
        { marked: "Elle [briefe] les nouveaux venus dès leur arrivée.", fix: "renseigne" },
        { marked: "Le point du lundi permet d'informer toute l'équipe.", fix: null },
      ],
    },
    {
      slug: "anglicisme-manager",
      category: "Registre et style",
      title: "manager ou encadrer",
      statement: "Selon le cas : <b>diriger</b>, <b>encadrer</b>, <b>gérer</b> ou <b>animer</b>.",
      tip: "On dirige une entreprise, on encadre une équipe, on gère un budget.",
      difficulty: 2,
      sentences: [
        { marked: "Elle [manage] une équipe de douze techniciens.", fix: "encadre" },
        { marked: "Il faut [manager] ce projet avec beaucoup de méthode.", fix: "piloter" },
        { marked: "Le [manager] du service part à la retraite en juin.", fix: "responsable" },
        { marked: "Il a [managé] trois filiales avant de venir ici.", fix: "dirigé" },
        { marked: "Elle encadre une équipe de douze techniciens depuis un an.", fix: null },
      ],
    },
    {
      slug: "anglicisme-implementer",
      category: "Registre et style",
      title: "implémenter ou mettre en œuvre",
      statement: "Le français dit <b>mettre en œuvre</b>, <b>appliquer</b>, <b>installer</b> ou <b>déployer</b>.",
      tip: "Implémenter n'existe qu'en informatique, et encore : déployer y suffit.",
      difficulty: 2,
      sentences: [
        { marked: "Il faudra [implémenter] cette réforme dès septembre.", fix: "appliquer" },
        { marked: "La procédure a été [implémentée] sans aucune formation.", fix: "mise en place" },
        { marked: "Nous allons [implémenter] le nouveau logiciel cet été.", fix: "déployer" },
        { marked: "Ces mesures seront [implémentées] progressivement.", fix: "appliquées" },
        { marked: "La réforme sera mise en œuvre dès le mois de septembre.", fix: null },
      ],
    },
    {
      slug: "anglicisme-updater",
      category: "Registre et style",
      title: "updater ou mettre à jour",
      statement: "On <b>met à jour</b>, on <b>actualise</b>, on <b>réactualise</b>.",
      tip: "Trois syllabes de plus, mais un français qui se lit à voix haute.",
      difficulty: 1,
      sentences: [
        { marked: "Peux-tu [updater] le tableau avant la réunion ?", fix: "actualiser" },
        { marked: "Le fichier n'a pas été [updaté] depuis janvier.", fix: "mis à jour" },
        { marked: "Il faudrait [updater] les coordonnées des adhérents.", fix: "actualiser" },
        { marked: "Cette [update] corrige plusieurs défauts signalés.", fix: "mise à jour" },
        { marked: "Le tableau a été mis à jour hier en fin de journée.", fix: null },
      ],
    },
    {
      slug: "anglicisme-canceller",
      category: "Registre et style",
      title: "canceller ou annuler",
      statement: "Le verbe français est <b>annuler</b> ; canceller est un calque de l'anglais.",
      tip: "Annuler existe depuis le XIVe siècle : il n'a besoin d'aucun remplaçant.",
      difficulty: 1,
      sentences: [
        { marked: "Il a fallu [canceller] la réunion de dernière minute.", fix: "annuler" },
        { marked: "Le vol a été [cancellé] pour cause de brouillard.", fix: "annulé" },
        { marked: "Peux-tu [canceller] ma réservation de mardi soir ?", fix: "annuler" },
        { marked: "Toutes les commandes ont été [cancellées] ce matin.", fix: "annulées" },
        { marked: "La réunion a été annulée faute de participants.", fix: null },
      ],
    },
    {
      slug: "anglicisme-partager-information",
      category: "Registre et style",
      title: "partager une information",
      statement: "On <b>transmet</b>, on <b>communique</b>, on <b>fait part de</b> — partager suppose de diviser en parts.",
      tip: "Une information transmise n'est pas divisée : elle est donnée entière.",
      difficulty: 2,
      sentences: [
        { marked: "Merci de [partager] cette note à toute l'équipe.", fix: "transmettre" },
        { marked: "Je vous [partage] le compte rendu de la séance.", fix: "transmets" },
        { marked: "Elle a [partagé] ses conclusions avec la direction.", fix: "communiqué" },
        { marked: "Ces documents seront [partagés] dès demain matin.", fix: "diffusés" },
        { marked: "Je vous transmets le compte rendu de la séance de mardi.", fix: null },
      ],
    },
    {
      slug: "registre-omission-ne",
      category: "Registre et style",
      title: "La négation garde son « ne »",
      statement: "À l'écrit, la négation s'écrit toujours <b>ne… pas</b> : l'omission du ne relève de l'oral familier.",
      tip: "Lis la phrase à voix haute dans un contexte officiel : le ne s'impose.",
      difficulty: 1,
      sentences: [
        { marked: "Je [sais] pas encore ce que je vais répondre.", fix: "ne sais" },
        { marked: "Depuis, elle [veut] plus entendre parler de cette histoire.", fix: "ne veut" },
        { marked: "Ils [ont] rien compris à la consigne du départ.", fix: "n'ont" },
        { marked: "À ce jour, nous [avons] pas reçu la confirmation attendue.", fix: "n'avons" },
        { marked: "Je ne sais pas encore quelle décision prendre.", fix: null },
      ],
    },
    {
      slug: "impropriete-cloturer",
      category: "Registre et style",
      title: "clore ou clôturer",
      statement: "On <b>clôt</b> un débat, une séance, un compte ; <b>clôturer</b> signifie entourer d'une clôture.",
      tip: "Clôturer se fait avec du grillage : pour le reste, clore suffit.",
      difficulty: 3,
      sentences: [
        { marked: "Le président a [clôturé] la séance à midi précise.", fix: "clos" },
        { marked: "Il faudra [clôturer] ce débat avant la pause.", fix: "clore" },
        { marked: "L'incident est [clôturé], n'y revenons plus.", fix: "clos" },
        { marked: "Nous allons [clôturer] ce compte bancaire inutilisé.", fix: "clore" },
        { marked: "Le propriétaire va clôturer son terrain au printemps.", fix: null },
      ],
    },
    {
      slug: "impropriete-instaurer",
      category: "Registre et style",
      title: "instaurer ou instituer",
      statement: "<b>instaurer</b>, c'est établir pour la première fois ; <b>instituer</b>, c'est créer par un acte officiel.",
      tip: "On instaure un climat, on institue une commission.",
      difficulty: 3,
      sentences: [
        { marked: "La loi a [instauré] une commission d'enquête permanente.", fix: "institué" },
        { marked: "Il a [institué] un climat de confiance en quelques mois.", fix: "instauré" },
        { marked: "Ce décret [instaure] un nouvel organisme de contrôle.", fix: "institue" },
        { marked: "Cette pratique s'est [instituée] peu à peu dans le service.", fix: "instaurée" },
        { marked: "Le climat instauré a permis d'instituer un vrai dialogue.", fix: null },
      ],
    },
    {
      slug: "registre-ca-cela",
      category: "Registre et style",
      title: "cela plutôt que ça à l'écrit",
      statement: "<b>ça</b> appartient à l'oral ; à l'écrit soigné, on écrit <b>cela</b>.",
      tip: "Dans une lettre ou un rapport, « ça » détonne toujours.",
      difficulty: 2,
      sentences: [
        { marked: "Cela dit, [ça] ne change rien à l'affaire.", fix: "cela" },
        { marked: "Tout [ça] mérite une explication devant le conseil.", fix: "cela" },
        { marked: "Il faudra tenir compte de tout [ça] dans le rapport.", fix: "cela" },
        { marked: "[Ça] ne saurait tarder, d'après le secrétariat.", fix: "Cela" },
        { marked: "Rien de tout [ça] ne figure au procès-verbal.", fix: "cela" },
        { marked: "Nous verrons [ça] lors de la prochaine séance.", fix: "cela" },
        { marked: "Cela ne changera rien à la décision du conseil.", fix: null },
      ],
    },

    /* ─────────────── écrits professionnels ─────────────── */
    {
      slug: "pro-en-esperant",
      category: "Écrits professionnels",
      title: "En espérant une réponse favorable",
      statement: "La formule d'espoir se construit avec un <b>nom</b> ou une <b>subordonnée à l'indicatif</b> : en espérant une réponse favorable, en espérant que vous accepterez.",
      tip: "« Espérer que » est suivi de l'indicatif, jamais du subjonctif.",
      difficulty: 3,
      sentences: [
        { marked: "En espérant que vous [acceptiez] ma candidature, je vous salue.", fix: "accepterez" },
        { marked: "En espérant qu'il [soit] possible de se rencontrer bientôt.", fix: "sera" },
        { marked: "En espérant que cette réponse vous [convienne] pleinement.", fix: "conviendra" },
        { marked: "En espérant que vous [puissiez] donner suite à ma demande.", fix: "pourrez" },
        { marked: "En espérant que ma candidature retiendra votre attention.", fix: null },
      ],
    },
    {
      slug: "pro-remercier-avance",
      category: "Écrits professionnels",
      title: "Vous en remerciant par avance",
      statement: "On écrit <b>par avance</b> ou <b>d'avance</b> ; « en avance » signifie « avant l'heure prévue ».",
      tip: "Être en avance, c'est arriver tôt ; remercier par avance, c'est anticiper.",
      difficulty: 2,
      sentences: [
        { marked: "Je vous remercie [en] avance de votre compréhension.", fix: "par" },
        { marked: "Vous en remerciant [en] avance, je reste à votre disposition.", fix: "par" },
        { marked: "Merci [en] avance pour votre réponse rapide.", fix: "d'" },
        { marked: "Nous vous remercions [en] avance de votre diligence.", fix: "par" },
        { marked: "Je vous remercie par avance de votre attention.", fix: null },
      ],
    },
    {
      slug: "pro-nous-vous-informons",
      category: "Écrits professionnels",
      title: "Nous vous informons que",
      statement: "On <b>informe quelqu'un de</b> quelque chose ou <b>que</b> suivi d'une proposition ; jamais « informer sur ».",
      tip: "Informer de, informer que : la préposition « sur » appartient à « renseigner ».",
      difficulty: 3,
      sentences: [
        { marked: "Nous vous informons [sur] la fermeture annuelle du service.", fix: "de" },
        { marked: "Je vous informe [sur] le report de la réunion de mardi.", fix: "du" },
        { marked: "Le service vous informera [sur] la suite donnée à votre dossier.", fix: "de" },
        { marked: "Ils nous ont informés [sur] leur décision par courriel.", fix: "de" },
        { marked: "Nous vous informons de la fermeture du service en août.", fix: null },
      ],
    },
    {
      slug: "pro-restant-disposition",
      category: "Écrits professionnels",
      title: "Restant à votre disposition : le participe suit le signataire",
      statement: "Le participe qui ouvre la formule finale se rapporte au <b>signataire</b> et s'accorde avec lui : restant, restants, restante.",
      tip: "Demande-toi qui reste disponible : c'est avec cette personne que le participe s'accorde.",
      difficulty: 3,
      sentences: [
        { marked: "[Restants] à votre disposition, je vous prie d'agréer mes salutations.", fix: "Restant" },
        { marked: "[Restant] à votre disposition, nous vous prions d'agréer nos salutations.", fix: "Restants" },
        { marked: "Nous restons joignables tout l'été, [demeurants] à votre écoute.", fix: "demeurant" },
        { marked: "Nous vous adressons nos salutations, [restante] à votre disposition.", fix: "restants" },
        { marked: "Je vous prie de recevoir mes salutations, [restants] dans l'attente.", fix: "restant" },
        { marked: "[Demeurant] à votre service, nous vous adressons nos respectueuses salutations.", fix: "Demeurants" },
        { marked: "Restant à votre disposition, je vous prie d'agréer mes salutations distinguées.", fix: null },
      ],
    },
    {
      slug: "pro-signature-prenom-nom",
      category: "Écrits professionnels",
      title: "Le nom ne s'écrit pas tout en capitales",
      statement: "Une signature s'écrit <b>prénom puis nom</b>, en capitale initiale seulement. Le nom en majuscules appartient aux formulaires.",
      tip: "Les capitales servent à remplir une case, pas à signer une lettre.",
      difficulty: 2,
      sentences: [
        { marked: "Cordialement, Camille [DUPONT], chargée de mission.", fix: "Dupont" },
        { marked: "Bien à vous, Paul [MARTIN], responsable du service.", fix: "Martin" },
        { marked: "Signé : Marie [LEROY], directrice adjointe du site.", fix: "Leroy" },
        { marked: "Cordialement, Julie [BERNARD], assistante de direction.", fix: "Bernard" },
        { marked: "Bien à vous, Claire [MOREAU], responsable des achats.", fix: "Moreau" },
        { marked: "Cordialement, Antoine [ROUX], chef de projet.", fix: "Roux" },
        { marked: "Cordialement, Camille Dupont, chargée de mission au service technique.", fix: null },
      ],
    },
    {
      slug: "pro-objet-reference",
      category: "Écrits professionnels",
      title: "Objet et référence",
      statement: "L'objet est un <b>groupe nominal</b>, la référence un <b>identifiant</b> : Objet : demande de devis. Réf. : 2024-118.",
      tip: "L'objet dit quoi, la référence dit lequel : ne les mélange pas.",
      difficulty: 2,
      sentences: [
        { marked: "Objet : [dossier] 2024-118 concernant votre demande.", fix: "demande" },
        { marked: "Réf. du dossier : [demande] de devis pour le toit.", fix: "2024-118" },
        { marked: "Objet : [n°] 4521, relance de la facture impayée.", fix: "relance" },
        { marked: "Voir la réf. suivante : [relance] de facture impayée.", fix: "2024-092" },
        { marked: "Objet : demande de devis. Réf. : 2024-118.", fix: null },
      ],
    },
    {
      slug: "pro-lettre-recommandee",
      category: "Écrits professionnels",
      title: "Lettre recommandée avec accusé de réception",
      statement: "La mention exacte est <b>lettre recommandée avec accusé de réception</b>, abrégée LRAR — jamais « avec avis de réception » dans l'usage courant.",
      tip: "L'accusé de réception prouve la remise : c'est lui qu'on demande.",
      difficulty: 3,
      sentences: [
        { marked: "Envoyée en recommandé avec [avis] de réception, la mise en demeure.", fix: "accusé" },
        { marked: "Ce courrier part en lettre [recommandé] avec accusé de réception.", fix: "recommandée" },
        { marked: "La résiliation doit être envoyée en [LRRA] avant le 31 mars.", fix: "LRAR" },
        { marked: "Un [recommandée] avec accusé de réception vous sera adressé.", fix: "recommandé" },
        { marked: "La mise en demeure part en lettre recommandée avec accusé de réception.", fix: null },
      ],
    },
    {
      slug: "pro-tutoiement",
      category: "Écrits professionnels",
      title: "Ne pas mélanger tutoiement et vouvoiement",
      statement: "Un même message garde un seul registre : ou bien <b>tu</b> partout, ou bien <b>vous</b> partout.",
      tip: "Relis ton message d'un bout à l'autre : un seul pronom doit y régner.",
      difficulty: 2,
      sentences: [
        { marked: "Bonjour Paul, peux-tu me confirmer que [vous] serez présent ?", fix: "tu" },
        { marked: "Madame, pourriez-vous me dire si [tu] as reçu le dossier ?", fix: "vous avez" },
        { marked: "Salut Marie, je [vous] envoie le fichier dès ce soir.", fix: "t'" },
        { marked: "Cher collègue, je vous remercie de [ton] retour rapide.", fix: "votre" },
        { marked: "Bonjour Paul, peux-tu me confirmer ta présence mardi ?", fix: null },
      ],
    },
    {
      slug: "pro-abreviations-interdites",
      category: "Écrits professionnels",
      title: "Ni RDV ni K€ dans un courrier",
      statement: "Un écrit professionnel écrit <b>rendez-vous</b>, <b>information</b> et les sommes en toutes lettres ou en chiffres complets.",
      tip: "Les abréviations de note interne n'ont pas leur place dans un courrier.",
      difficulty: 2,
      sentences: [
        { marked: "Je souhaiterais convenir d'un [RDV] la semaine prochaine.", fix: "rendez-vous" },
        { marked: "Le budget s'élève à [50K€] pour l'ensemble du projet.", fix: "50 000 euros" },
        { marked: "Merci de me transmettre cette [info] avant vendredi.", fix: "information" },
        { marked: "Un [pb] technique retarde la livraison de deux jours.", fix: "problème" },
        { marked: "Je souhaiterais convenir d'un rendez-vous la semaine prochaine.", fix: null },
      ],
    },
    {
      slug: "pro-formule-refus",
      category: "Écrits professionnels",
      title: "Formuler un refus",
      statement: "Un refus poli emploie <b>ne pas être en mesure de</b> ou <b>ne pas pouvoir donner suite</b>, jamais un simple « non ».",
      tip: "Le refus s'explique avant de se prononcer : la formule ménage le destinataire.",
      difficulty: 2,
      sentences: [
        { marked: "Nous [refusons] votre demande pour des raisons budgétaires.", fix: "ne sommes pas en mesure d'accepter" },
        { marked: "Je [refuse] de donner suite à votre proposition.", fix: "ne peux pas" },
        { marked: "Le service [refuse] votre dossier, incomplet à ce jour.", fix: "ne peut retenir" },
        { marked: "Nous [refusons] votre candidature pour cette session.", fix: "ne pouvons retenir" },
        { marked: "Nous ne sommes pas en mesure de donner suite à votre demande.", fix: null },
      ],
    },
    {
      slug: "pro-demande-devis",
      category: "Écrits professionnels",
      title: "Établir ou faire un devis",
      statement: "On <b>établit</b>, on <b>adresse</b> ou on <b>transmet</b> un devis ; « faire un devis » relève de l'oral.",
      tip: "Le verbe précis fait sérieux : établir, adresser, transmettre.",
      difficulty: 2,
      sentences: [
        { marked: "Pourriez-vous me [faire] un devis avant la fin du mois ?", fix: "établir" },
        { marked: "Le devis sera [fait] dans les huit jours ouvrés.", fix: "établi" },
        { marked: "Le devis a été [fait] par le bureau d'études hier.", fix: "établi" },
        { marked: "Nous vous [ferons] un devis dès réception des plans.", fix: "adresserons" },
        { marked: "Pourriez-vous établir un devis avant la fin du mois ?", fix: null },
      ],
    },
    {
      slug: "pro-relance-facture",
      category: "Écrits professionnels",
      title: "Relancer une facture impayée",
      statement: "On parle de facture <b>impayée</b> ou <b>échue</b>, et l'on <b>invite à régulariser</b> avant toute mise en demeure.",
      tip: "La relance constate un fait ; elle n'accuse pas encore.",
      difficulty: 3,
      sentences: [
        { marked: "Votre facture [non-payée] date du 12 mars dernier.", fix: "impayée" },
        { marked: "Nous vous [demandons] de régulariser sous huitaine.", fix: "invitons" },
        { marked: "Cette facture non [payée] fera l'objet d'une mise en demeure.", fix: "réglée" },
        { marked: "Merci de [payer] cette somme dans les meilleurs délais.", fix: "régler" },
        { marked: "Nous vous invitons à régler cette facture impayée sous huitaine.", fix: null },
      ],
    },
    {
      slug: "pro-copie-destinataires",
      category: "Écrits professionnels",
      title: "En copie, et non en cc",
      statement: "En français, on met quelqu'un <b>en copie</b> ; la copie cachée se dit <b>copie invisible</b>.",
      tip: "Cc et Cci sont des étiquettes de logiciel, pas des mots de phrase.",
      difficulty: 2,
      sentences: [
        { marked: "Je mets le service comptable en [cc] de ce message.", fix: "copie" },
        { marked: "Vous trouverez la direction en [cci] pour simple information.", fix: "copie invisible" },
        { marked: "Merci de me mettre en [cc] lors du prochain envoi.", fix: "copie" },
        { marked: "Le responsable du site était en [cc] du courriel initial.", fix: "copie" },
        { marked: "Je mets le service comptable en copie de ce message.", fix: null },
      ],
    },
  ],
};
