/**
 * Lot 015 — Vocabulaire : expressions figées (25 règles).
 *
 * Des locutions qu'on entend souvent et qu'on écrit mal. Le mot marqué est
 * toujours celui, unique, qui change dans la locution.
 */
import type { ContentBatch } from "../../../src/lib/content";

export const BATCH_015: ContentBatch = {
  id: "batch-015",
  rules: [
    {
      slug: "expr-battre-son-plein",
      category: "Vocabulaire",
      title: "battre son plein",
      statement: "Dans <b>battre son plein</b>, « plein » est un nom singulier : il ne prend jamais de s.",
      tip: "Le plein est la marée haute : il n'y en a qu'un à la fois.",
      difficulty: 3,
      sentences: [
        { marked: "Les festivités battaient leur [pleins] depuis trois jours.", fix: "plein" },
        { marked: "La fête bat son [pleins] jusqu'au bout de la nuit.", fix: "plein" },
        { marked: "En ce moment, les travaux battent leur [pleins].", fix: "plein" },
        { marked: "Hier encore, les négociations battaient leur [pleins].", fix: "plein" },
        { marked: "La saison bat son plein depuis le mois de juin.", fix: null },
      ],
    },
    {
      slug: "expr-maille-a-partir",
      category: "Vocabulaire",
      title: "avoir maille à partir",
      statement: "<b>avoir maille à partir avec</b> signifie avoir un différend. La maille était une monnaie, et « partir » voulait dire partager.",
      tip: "Rien à voir avec le tricot ni avec un départ : c'est du vieux français.",
      difficulty: 3,
      sentences: [
        { marked: "Il a eu maille à [repartir] avec son ancien associé.", fix: "partir" },
        { marked: "Elle a eu [mailles] à partir avec l'administration fiscale.", fix: "maille" },
        { marked: "Nous avons eu maille à [départir] avec ce fournisseur.", fix: "partir" },
        { marked: "Il aura [mailles] à partir avec le syndic de copropriété.", fix: "maille" },
        { marked: "Elle a eu maille à partir avec son ancien propriétaire.", fix: null },
      ],
    },
    {
      slug: "expr-sans-coup-ferir",
      category: "Vocabulaire",
      title: "sans coup férir",
      statement: "<b>sans coup férir</b> signifie sans rencontrer de résistance. « Férir » est un vieux verbe qui veut dire frapper.",
      tip: "Le mot ne s'écrit ni « ferrir » ni « faillir » : férir, comme dans « sans coup férir ».",
      difficulty: 3,
      sentences: [
        { marked: "La ville fut prise sans coup [ferrir] au petit matin.", fix: "férir" },
        { marked: "Il a emporté la décision sans coup [faillir].", fix: "férir" },
        { marked: "Le projet est passé sans coup [ferrir] devant le conseil.", fix: "férir" },
        { marked: "Elle a obtenu gain de cause sans coup [férire].", fix: "férir" },
        { marked: "L'amendement est passé sans coup férir en fin de séance.", fix: null },
      ],
    },
    {
      slug: "expr-de-guerre-lasse",
      category: "Vocabulaire",
      title: "de guerre lasse",
      statement: "<b>de guerre lasse</b> signifie « fatigué de lutter ». L'adjectif s'accorde avec « guerre », donc toujours au féminin.",
      tip: "C'est la guerre qui est lasse, pas celui qui parle : lasse ne bouge jamais.",
      difficulty: 3,
      sentences: [
        { marked: "De guerre [las], il a fini par accepter leurs conditions.", fix: "lasse" },
        { marked: "Elle a cédé de guerre [lassée] au bout de six mois.", fix: "lasse" },
        { marked: "De guerre [lassé], le voisin a retiré sa plainte.", fix: "lasse" },
        { marked: "Ils ont abandonné de guerre [las] après deux ans de procédure.", fix: "lasse" },
        { marked: "De guerre lasse, ils ont accepté un arrangement à l'amiable.", fix: null },
      ],
    },
    {
      slug: "expr-faire-long-feu",
      category: "Vocabulaire",
      title: "faire long feu",
      statement: "<b>faire long feu</b>, c'est échouer ; <b>ne pas faire long feu</b>, c'est ne pas durer. Les deux sens s'opposent.",
      tip: "L'expression vient de l'arme qui tarde à partir : le coup rate.",
      difficulty: 3,
      sentences: [
        { marked: "Ce projet a fait long [feux] dès la première réunion.", fix: "feu" },
        { marked: "Sa carrière n'a pas fait long [feux] dans cette maison.", fix: "feu" },
        { marked: "Leur association n'aura pas fait long [feux].", fix: "feu" },
        { marked: "L'initiative a fait [longue] feu faute de financement.", fix: "long" },
        { marked: "Cette mode n'a pas fait long feu dans la région.", fix: null },
      ],
    },
    {
      slug: "expr-nen-avoir-cure",
      category: "Vocabulaire",
      title: "n'en avoir cure",
      statement: "<b>n'en avoir cure</b> signifie ne pas s'en soucier. « Cure » y garde son sens ancien de souci.",
      tip: "Rien à voir avec une cure thermale : le mot vient du latin cura, le souci.",
      difficulty: 3,
      sentences: [
        { marked: "Il n'en a [cures] et poursuit son chemin sans se retourner.", fix: "cure" },
        { marked: "Elle n'en avait [cur] malgré les avertissements répétés.", fix: "cure" },
        { marked: "Ils n'en ont [cures], la décision est déjà prise.", fix: "cure" },
        { marked: "Le conseil n'en a [cures] et maintient son calendrier.", fix: "cure" },
        { marked: "Il n'en a cure et continue comme si de rien n'était.", fix: null },
      ],
    },
    {
      slug: "expr-a-linstar",
      category: "Vocabulaire",
      title: "à l'instar de",
      statement: "<b>à l'instar de</b> signifie « à la manière de », et non « contrairement à ».",
      tip: "Instar vient du latin « à la ressemblance » : c'est une comparaison, pas une opposition.",
      difficulty: 3,
      sentences: [
        { marked: "À l'[instant] de ses voisins, il a repeint sa façade.", fix: "l'instar" },
        { marked: "À l'[instars] de Paris, la ville a piétonnisé son centre.", fix: "l'instar" },
        { marked: "À l'[instand] de sa sœur, elle a choisi le droit.", fix: "l'instar" },
        { marked: "Il a réagi à l'[instant] de tous les autres élus.", fix: "l'instar" },
        { marked: "À l'instar de ses voisins, il a rénové sa toiture.", fix: null },
      ],
    },
    {
      slug: "expr-pierre-achoppement",
      category: "Vocabulaire",
      title: "pierre d'achoppement",
      statement: "Une <b>pierre d'achoppement</b> est un obstacle. Le mot vient d'« achopper », buter contre.",
      tip: "Un seul p à achoppement, comme dans achopper.",
      difficulty: 3,
      sentences: [
        { marked: "Le financement reste la pierre d'[achopement] du projet.", fix: "d'achoppement" },
        { marked: "Cette clause fut la pierre d'[achoppemant] des négociations.", fix: "d'achoppement" },
        { marked: "La date est devenue la pierre d'[achopement] du dossier.", fix: "d'achoppement" },
        { marked: "Le prix demeure la principale pierre d'[achopement].", fix: "d'achoppement" },
        { marked: "Le calendrier reste la pierre d'achoppement de l'accord.", fix: null },
      ],
    },
    {
      slug: "expr-couper-court",
      category: "Vocabulaire",
      title: "couper court à",
      statement: "<b>couper court à</b> signifie interrompre net. « Court » y est un adverbe : il reste invariable.",
      tip: "Un adverbe ne s'accorde jamais : couper court, quoi qu'il coupe.",
      difficulty: 3,
      sentences: [
        { marked: "Elle a coupé [courte] à toutes les spéculations.", fix: "court" },
        { marked: "Il faut couper [courts] à ces rumeurs sans fondement.", fix: "court" },
        { marked: "Le président a coupé [courte] à la discussion.", fix: "court" },
        { marked: "Ils ont coupé [courts] aux questions du public.", fix: "court" },
        { marked: "Le maire a coupé court à toutes les rumeurs.", fix: null },
      ],
    },
    {
      slug: "expr-donner-le-change",
      category: "Vocabulaire",
      title: "donner le change",
      statement: "<b>donner le change</b>, c'est tromper sur ses intentions. L'expression vient de la chasse, où le gibier détourne les chiens.",
      tip: "Ni « donner le changement » ni « donner les changes » : la locution est figée.",
      difficulty: 3,
      sentences: [
        { marked: "Il a donné le [changement] pendant plusieurs semaines.", fix: "change" },
        { marked: "Pendant des mois, elle a donné les [changes] à tous.", fix: "change" },
        { marked: "Impossible de donner le [changement] plus longtemps.", fix: "change" },
        { marked: "À leurs concurrents directs, ils ont donné le [changer].", fix: "change" },
        { marked: "Il a donné le change jusqu'à la dernière minute.", fix: null },
      ],
    },
    {
      slug: "expr-en-butte-a",
      category: "Vocabulaire",
      title: "en butte à",
      statement: "<b>en butte à</b> signifie exposé à, en proie à. Rien à voir avec le but ni avec un obstacle.",
      tip: "La butte était la cible des archers : on y est exposé aux tirs.",
      difficulty: 3,
      sentences: [
        { marked: "Il est en [but] à des critiques de toutes parts.", fix: "butte" },
        { marked: "Elle fut en [buts] aux moqueries de ses collègues.", fix: "butte" },
        { marked: "Le maire est en [but] à une forte opposition locale.", fix: "butte" },
        { marked: "Ils sont en [buttes] à des difficultés financières.", fix: "butte" },
        { marked: "Le projet est en butte à de vives critiques du voisinage.", fix: null },
      ],
    },
    {
      slug: "expr-etre-de-mise",
      category: "Vocabulaire",
      title: "être de mise",
      statement: "<b>être de mise</b> signifie être convenable, approprié. La locution est invariable.",
      tip: "Ni « de mises » ni « de mie » : la mise est ce qu'on met sur la table.",
      difficulty: 3,
      sentences: [
        { marked: "La discrétion est de [mises] dans ce genre d'affaire.", fix: "mise" },
        { marked: "Les félicitations ne sont pas de [mises] aujourd'hui.", fix: "mise" },
        { marked: "La prudence reste de [mises] jusqu'à nouvel ordre.", fix: "mise" },
        { marked: "Ce ton familier n'est pas de [mises] en réunion.", fix: "mise" },
        { marked: "La plus grande prudence est de mise en cette saison.", fix: null },
      ],
    },
    {
      slug: "expr-faire-fi",
      category: "Vocabulaire",
      title: "faire fi de",
      statement: "<b>faire fi de</b> signifie mépriser, dédaigner. « Fi » est une interjection de dégoût, invariable.",
      tip: "Fi ! est un cri de dédain : il ne prend jamais de s.",
      difficulty: 3,
      sentences: [
        { marked: "Il fait [fis] de toutes les recommandations du médecin.", fix: "fi" },
        { marked: "Elle a fait [fit] des conseils de son entourage.", fix: "fi" },
        { marked: "Ils font [fis] du règlement intérieur depuis des mois.", fix: "fi" },
        { marked: "Le conseil a fait [fit] de l'avis des riverains.", fix: "fi" },
        { marked: "Il fait fi des consignes de sécurité les plus élémentaires.", fix: null },
      ],
    },
    {
      slug: "expr-mettre-a-mal",
      category: "Vocabulaire",
      title: "mettre à mal",
      statement: "<b>mettre à mal</b> signifie endommager, ébranler. « Mal » y est un nom singulier invariable.",
      tip: "On met à mal, jamais « à maux » : le singulier est figé.",
      difficulty: 3,
      sentences: [
        { marked: "Cette affaire a mis à [maux] la réputation du service.", fix: "mal" },
        { marked: "La crise a mis à [mals] toute l'économie locale.", fix: "mal" },
        { marked: "Ces révélations mettent à [maux] sa crédibilité.", fix: "mal" },
        { marked: "L'incident a mis à [male] la confiance des habitants.", fix: "mal" },
        { marked: "La tempête a mis à mal toute la toiture du hangar.", fix: null },
      ],
    },
    {
      slug: "expr-prendre-a-partie",
      category: "Vocabulaire",
      title: "prendre à partie",
      statement: "<b>prendre à partie</b>, c'est s'en prendre à quelqu'un. Il s'écrit avec « partie » au féminin, sans s.",
      tip: "On prend quelqu'un à partie comme on prend un adversaire en justice.",
      difficulty: 3,
      sentences: [
        { marked: "Il a été pris à [parti] par plusieurs spectateurs.", fix: "partie" },
        { marked: "Elle a pris à [parti] le responsable du service.", fix: "partie" },
        { marked: "L'arbitre fut pris à [parties] par les deux équipes.", fix: "partie" },
        { marked: "Ils ont pris à [parti] le conférencier après son exposé.", fix: "partie" },
        { marked: "Le ministre a été pris à partie par la salle entière.", fix: null },
      ],
    },
    {
      slug: "expr-sous-legide",
      category: "Vocabulaire",
      title: "sous l'égide de",
      statement: "<b>sous l'égide de</b> signifie sous la protection de. L'égide était le bouclier d'Athéna.",
      tip: "Le mot est féminin et prend un accent aigu : l'égide.",
      difficulty: 3,
      sentences: [
        { marked: "Le colloque se tient sous l'[egide] du ministère.", fix: "l'égide" },
        { marked: "Ce programme fonctionne sous l'[égyde] des Nations unies.", fix: "l'égide" },
        { marked: "L'exposition est organisée sous l'[aegide] de la région.", fix: "l'égide" },
        { marked: "La collecte a lieu sous l'[égides] de la mairie.", fix: "l'égide" },
        { marked: "Le festival se déroule sous l'égide du conseil régional.", fix: null },
      ],
    },
    {
      slug: "expr-vaille-que-vaille",
      category: "Vocabulaire",
      title: "vaille que vaille",
      statement: "<b>vaille que vaille</b> signifie tant bien que mal. Les deux formes sont au subjonctif du verbe valoir.",
      tip: "Ni « vaillle » ni « vaille que veuille » : la formule se répète à l'identique.",
      difficulty: 3,
      sentences: [
        { marked: "Il a terminé le chantier [vaillle] que vaille.", fix: "vaille" },
        { marked: "Elle avance [veuille] que vaille malgré les obstacles.", fix: "vaille" },
        { marked: "Nous tiendrons vaille que [veuille] jusqu'à la fin.", fix: "vaille" },
        { marked: "Le service fonctionne vaille que [vaillent] depuis janvier.", fix: "vaille" },
        { marked: "Le projet avance vaille que vaille depuis le printemps.", fix: null },
      ],
    },
    {
      slug: "expr-a-bon-escient",
      category: "Vocabulaire",
      title: "à bon escient",
      statement: "<b>à bon escient</b> signifie à propos, en connaissance de cause. Le mot vient du latin scire, savoir.",
      tip: "Escient garde son s muet, comme science dont il est cousin.",
      difficulty: 3,
      sentences: [
        { marked: "Il emploie ce terme à bon [essient] dans son rapport.", fix: "escient" },
        { marked: "Elle a agi à bon [éscient] compte tenu des circonstances.", fix: "escient" },
        { marked: "Ces crédits ont été dépensés à bon [ecient].", fix: "escient" },
        { marked: "Le mot est utilisé à bon [essciant] dans ce contexte.", fix: "escient" },
        { marked: "Cette dépense a été engagée à bon escient.", fix: null },
      ],
    },
    {
      slug: "expr-au-demeurant",
      category: "Vocabulaire",
      title: "au demeurant",
      statement: "<b>au demeurant</b> signifie « du reste, par ailleurs ». C'est une transition, pas une conclusion.",
      tip: "Remplace par « du reste » : si ça marche, la locution convient.",
      difficulty: 3,
      sentences: [
        { marked: "Au [demeurent], rien ne s'oppose à cette solution.", fix: "demeurant" },
        { marked: "Ce texte, au [demeurance] très clair, mérite d'être lu.", fix: "demeurant" },
        { marked: "Au [demeurand], la question reste entièrement ouverte.", fix: "demeurant" },
        { marked: "Sa remarque, au [demeurents] fondée, a été ignorée.", fix: "demeurant" },
        { marked: "Au demeurant, ce choix n'était pas le plus mauvais.", fix: null },
      ],
    },
    {
      slug: "expr-nonobstant",
      category: "Vocabulaire",
      title: "nonobstant",
      statement: "<b>nonobstant</b> signifie « malgré ». Il s'écrit en un seul mot et reste invariable.",
      tip: "Le mot contient « obstant », qui fait obstacle : nonobstant, l'obstacle ne compte pas.",
      difficulty: 3,
      sentences: [
        { marked: "[Non-obstant] ces réserves, le contrat a été signé.", fix: "Nonobstant" },
        { marked: "[Nonobstants] les délais, la livraison a eu lieu.", fix: "Nonobstant" },
        { marked: "Il a poursuivi, [nonobstan] l'avis du conseil municipal.", fix: "nonobstant" },
        { marked: "[Nonobstantes] les difficultés, ils ont tenu le calendrier.", fix: "Nonobstant" },
        { marked: "Nonobstant ces réserves, la commission a rendu un avis favorable.", fix: null },
      ],
    },
    {
      slug: "expr-a-lencontre",
      category: "Vocabulaire",
      title: "à l'encontre de",
      statement: "<b>à l'encontre de</b> signifie « contre ». La locution ne s'emploie pas au sens de « à la rencontre de ».",
      tip: "Encontre contient « contre » : le sens est toujours l'opposition.",
      difficulty: 3,
      sentences: [
        { marked: "Cette décision va à l'encontre du règlement en vigueur.", fix: null },
        { marked: "Il est allé à l'[encontre] de son ami à la gare.", fix: "la rencontre" },
        { marked: "Aucune poursuite n'a été engagée à son [rencontre].", fix: "encontre" },
        { marked: "Elle est partie à l'[encontre] du facteur ce matin.", fix: "la rencontre" },
        { marked: "Ce choix va à l'encontre de tout ce qui a été décidé.", fix: null },
      ],
    },
    {
      slug: "expr-de-concert",
      category: "Vocabulaire",
      title: "de concert ou de conserve",
      statement: "<b>de concert</b> signifie en accord ; <b>de conserve</b> signifie ensemble, côte à côte. Le second vient de la marine.",
      tip: "Deux navires naviguent de conserve ; deux personnes agissent de concert.",
      difficulty: 3,
      sentences: [
        { marked: "Les deux ministres ont agi de [conserve] sur ce dossier.", fix: "concert" },
        { marked: "Les bateaux ont navigué de [concert] jusqu'au détroit.", fix: "conserve" },
        { marked: "Ils ont préparé cette réforme de [conserve] pendant un an.", fix: "concert" },
        { marked: "Les deux voitures roulaient de [concert] sur la départementale.", fix: "conserve" },
        { marked: "Les deux services ont travaillé de concert tout l'hiver.", fix: null },
      ],
    },
    {
      slug: "expr-sen-falloir",
      category: "Vocabulaire",
      title: "il s'en faut de peu",
      statement: "<b>il s'en faut de peu</b> et <b>tant s'en faut</b> expriment l'écart. Le verbe reste impersonnel et invariable.",
      tip: "S'en falloir ne se conjugue qu'avec « il » : aucune autre personne n'existe.",
      difficulty: 3,
      sentences: [
        { marked: "Il s'en est [fallut] de peu qu'il rate son train.", fix: "fallu" },
        { marked: "Ce n'est pas terminé, tant s'en [fallent].", fix: "faut" },
        { marked: "Il s'en [fallaient] de peu que tout s'écroule.", fix: "fallait" },
        { marked: "Elle n'a pas renoncé, tant s'en [fallut].", fix: "faut" },
        { marked: "Il s'en est fallu de peu que le pont ne cède.", fix: null },
      ],
    },
    {
      slug: "expr-en-lespece",
      category: "Vocabulaire",
      title: "en l'espèce",
      statement: "<b>en l'espèce</b> signifie « dans ce cas précis ». C'est une formule juridique, toujours au singulier.",
      tip: "L'espèce est le cas particulier soumis au juge : il n'y en a qu'un.",
      difficulty: 3,
      sentences: [
        { marked: "En l'[espèces], la responsabilité ne fait aucun doute.", fix: "l'espèce" },
        { marked: "Le texte ne s'applique pas en l'[espece] présente.", fix: "l'espèce" },
        { marked: "En l'[espéce], la juridiction s'est déclarée incompétente.", fix: "l'espèce" },
        { marked: "Rien, en l'[espèces], ne justifie une telle décision.", fix: "l'espèce" },
        { marked: "En l'espèce, le tribunal a suivi les conclusions du rapport.", fix: null },
      ],
    },
    {
      slug: "expr-tenir-tete",
      category: "Vocabulaire",
      title: "tenir tête à",
      statement: "<b>tenir tête à</b> signifie résister. « Tête » y reste au singulier, sans article.",
      tip: "La locution est figée : ni « tenir la tête » ni « tenir têtes ».",
      difficulty: 2,
      sentences: [
        { marked: "Il a tenu [têtes] à toute la direction pendant des mois.", fix: "tête" },
        { marked: "Elle sait tenir [têtes] à ses interlocuteurs les plus durs.", fix: "tête" },
        { marked: "Ils ont tenu [têtes] aux pressions les plus fortes.", fix: "tête" },
        { marked: "Personne n'osait lui tenir [têtes] pendant les réunions.", fix: "tête" },
        { marked: "Il a tenu tête à son supérieur sans jamais hausser le ton.", fix: null },
      ],
    },
  ],
};
