/**
 * Lot de dictées — 76 textes, pour porter le total à 100.
 *
 * Une dictée ne porte AUCUNE faute : elle est lue à voix haute et recopiée.
 * Chaque texte est donc écrit pour être irréprochable, et rattaché aux règles
 * qu'il fait effectivement travailler.
 *
 * Niveaux : 1 abordable, 2 intermédiaire, 3 coriace.
 */
import type { ContentBatch } from "../../../src/lib/content";

export const DICTATIONS: ContentBatch = {
  id: "dictations-001",
  rules: [],
  dictations: [
    /* ─────────────── niveau 1 ─────────────── */
    { text: "On a compris ce qu'ils ont voulu dire dès le début.", theme: "Discussion", difficulty: 1, ruleSlugs: ["on-ont"] },
    { text: "Ses affaires sont rangées dans ces cartons depuis le déménagement.", theme: "Maison", difficulty: 1, ruleSlugs: ["ces-ses", "pp-être"] },
    { text: "Il a promis à sa sœur de passer la voir dimanche.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["a-à", "ça-sa"] },
    { text: "Je ne sais pas où il range les clés de la cave.", theme: "Maison", difficulty: 1, ruleSlugs: ["ou-où", "discute-cle-clef"] },
    { text: "Ce livre est passionnant, mais il se lit très lentement.", theme: "Vie scolaire", difficulty: 1, ruleSlugs: ["ce-se", "mais-mes"] },
    { text: "Son frère et sa sœur sont déjà partis à la gare.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["son-sont", "et-est"] },
    { text: "Tous les invités sont arrivés avant le début du repas.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["tout-tous", "pp-être"] },
    { text: "Le professeur leur a rendu les copies ce matin.", theme: "Vie scolaire", difficulty: 1, ruleSlugs: ["leur", "pp-avoir"] },
    { text: "Elle peut venir un peu plus tard si cela t'arrange.", theme: "Discussion", difficulty: 1, ruleSlugs: ["peu-peut"] },
    { text: "Nous commençons à ranger la cuisine avant l'arrivée des invités.", theme: "Cuisine", difficulty: 1, ruleSlugs: ["verbes-cer", "cedille"] },
    { text: "Regarde bien avant de traverser cette avenue très passante.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["impératif"] },
    { text: "Il est prêt à partir, tout près de la porte.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["pres-pret"] },
    { text: "Le cours d'histoire commence à dix heures dans la salle voisine.", theme: "Vie scolaire", difficulty: 1, ruleSlugs: ["cour-cours", "heures-format"] },
    { text: "Mes amis sont venus, mais personne ne m'avait prévenu.", theme: "Discussion", difficulty: 1, ruleSlugs: ["mais-mes"] },
    { text: "La fin du repas approche et je n'ai plus faim.", theme: "Cuisine", difficulty: 1, ruleSlugs: ["faim-fin"] },
    { text: "Il a reçu le colis avec deux jours de retard.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["cedille", "pp-avoir"] },
    { text: "Aujourd'hui, la réunion commence une heure plus tôt que prévu.", theme: "Travail", difficulty: 1, ruleSlugs: ["aujourdhui", "plutot"] },
    { text: "Vous parlez trop fort pour une salle aussi petite.", theme: "Travail", difficulty: 1, ruleSlugs: ["ez-er"] },
    { text: "Chacun range ses affaires avant de quitter la classe.", theme: "Vie scolaire", difficulty: 1, ruleSlugs: ["ces-ses", "accord-chaque-chacun"] },
    { text: "Le train arrive voie numéro trois dans quelques minutes.", theme: "Voyage", difficulty: 1, ruleSlugs: ["voie-voix"] },
    { text: "Elle a mangé une amande grillée avant de payer son amende.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["amande-amende"] },
    { text: "Il faut marcher plus vite si nous voulons arriver à l'heure.", theme: "Voyage", difficulty: 1, ruleSlugs: ["é-er"] },
    { text: "Demain, je passerai te chercher vers huit heures du matin.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["futur-cond", "heures-format"] },
    { text: "Le dessert du jour est une tarte aux abricots du verger.", theme: "Cuisine", difficulty: 1, ruleSlugs: ["desert-dessert"] },
    { text: "Tous les matins, il part courir avant le lever du soleil.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["tout-tous"] },
    { text: "Bonjour, madame, votre dossier est prêt depuis hier soir.", theme: "Bureau", difficulty: 1, ruleSlugs: ["virgule-vocatif", "pres-pret"] },

    /* ─────────────── niveau 2 ─────────────── */
    { text: "Quant à lui, il partira quand il aura tout terminé.", theme: "Discussion", difficulty: 2, ruleSlugs: ["quand-quant", "conj-futur-anterieur"] },
    { text: "Bien qu'il soit tard, il a tenu à relire le dossier.", theme: "Travail", difficulty: 2, ruleSlugs: ["subj-bienque", "a-à"] },
    { text: "La plupart des spectateurs sont restés malgré la pluie battante.", theme: "Vie scolaire", difficulty: 2, ruleSlugs: ["la-plupart", "parmi-malgré"] },
    { text: "Il faut que tu partes avant la fermeture des portes.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["subj-falloir"] },
    { text: "Si nous avions su, nous aurions pris le train de sept heures.", theme: "Voyage", difficulty: 2, ruleSlugs: ["si-conditionnel", "conj-plus-que-parfait"] },
    { text: "Les fleurs qu'il lui a offertes ont fané en trois jours.", theme: "Maison", difficulty: 2, ruleSlugs: ["pp-avoir"] },
    { text: "Nous avancions doucement dans les travaux du grenier.", theme: "Maison", difficulty: 2, ruleSlugs: ["verbes-cer", "pluriel-ail"] },
    { text: "Elle nettoie les vitres dès le premier rayon de soleil.", theme: "Maison", difficulty: 2, ruleSlugs: ["verbes-yer"] },
    { text: "Quelles que soient les difficultés, nous irons jusqu'au bout.", theme: "Travail", difficulty: 2, ruleSlugs: ["quel-que"] },
    { text: "Le panier de fruits mûrs attend sur la table de la cuisine.", theme: "Cuisine", difficulty: 2, ruleSlugs: ["sujet-éloigné", "mur-mur-accent"] },
    { text: "Il agit prudemment dans toutes les situations délicates.", theme: "Travail", difficulty: 2, ruleSlugs: ["amment-emment"] },
    { text: "Nous voyagions beaucoup avant la naissance des enfants.", theme: "Voyage", difficulty: 2, ruleSlugs: ["verbes-ger", "imparfait-ions"] },
    { text: "Ce chien n'est pas le nôtre, il vient du village voisin.", theme: "Nature", difficulty: 2, ruleSlugs: ["notre-notre"] },
    { text: "Elle sait parfaitement où se trouve le dossier manquant.", theme: "Bureau", difficulty: 2, ruleSlugs: ["sais-sait", "ou-où"] },
    { text: "Vingt pour cent des dossiers ont été rejetés cette année.", theme: "Bureau", difficulty: 2, ruleSlugs: ["accord-pourcentage-verbe", "pourcentage-espace"] },
    { text: "Il a payé quatre-vingts euros pour cette réparation.", theme: "Nombres et mesures", difficulty: 2, ruleSlugs: ["vingt-cent", "hyphen-nombres"] },
    { text: "Le règlement intérieur sera affiché dans le hall dès lundi.", theme: "Travail", difficulty: 2, ruleSlugs: ["accent-grave", "h-aspire"] },
    { text: "Ils ont apporté le dossier et amené leur fille à l'école.", theme: "Vie scolaire", difficulty: 2, ruleSlugs: ["amener"] },
    { text: "Nous partirons avant qu'il ne pleuve sur toute la région.", theme: "Nature", difficulty: 2, ruleSlugs: ["conj-subjonctif-avant-que"] },
    { text: "La liste des candidats retenus sera affichée demain matin.", theme: "Vie scolaire", difficulty: 2, ruleSlugs: ["sujet-éloigné"] },
    { text: "Personne n'est censé ignorer la loi, même un homme sensé.", theme: "Discussion", difficulty: 2, ruleSlugs: ["censé"] },
    { text: "Elle porte des chaussures marron achetées en solde l'hiver dernier.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["couleurs"] },
    { text: "Il faudra deux jours, voire trois, pour terminer ce chantier.", theme: "Travail", difficulty: 2, ruleSlugs: ["voire", "voire-meme"] },
    { text: "Le magasin ferme à dix-neuf heures tous les jours sauf le dimanche.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["heures-format", "jours-mois"] },
    { text: "Dès que j'aurai reçu le courrier, je te préviendrai aussitôt.", theme: "Écrits professionnels", difficulty: 2, ruleSlugs: ["conj-futur-anterieur", "aussitot"] },
    { text: "Nous vous saurions gré de bien vouloir nous répondre rapidement.", theme: "Écrits professionnels", difficulty: 2, ruleSlugs: ["savoir-gré"] },

    /* ─────────────── niveau 3 ─────────────── */
    { text: "Elles se sont rendu compte de l'erreur bien trop tard.", theme: "Bureau", difficulty: 3, ruleSlugs: ["rendu-compte", "essentiellement-pronominaux"] },
    { text: "Les enfants que j'ai entendus chanter avaient tous dix ans.", theme: "Vie scolaire", difficulty: 3, ruleSlugs: ["pp-infinitif"] },
    { text: "La chanson que j'ai entendu chanter m'a beaucoup émue.", theme: "Récit", difficulty: 3, ruleSlugs: ["pp-infinitif", "pp-avoir"] },
    { text: "Veuillez trouver ci-joint les trois attestations que vous réclamiez.", theme: "Écrits professionnels", difficulty: 3, ruleSlugs: ["ci-joint", "pro-veuillez-trouver"] },
    { text: "Elles se sont fait construire une maison au bord de la rivière.", theme: "Maison", difficulty: 3, ruleSlugs: ["fait-infinitif"] },
    { text: "Elle s'est lavé les mains avant de passer à table.", theme: "Cuisine", difficulty: 3, ruleSlugs: ["conj-participe-passe-pronominaux-cod"] },
    { text: "Des erreurs, j'en ai commis plus que je ne veux l'avouer.", theme: "Récit", difficulty: 3, ruleSlugs: ["pp-en"] },
    { text: "Excepté les deux dernières pages, tout le manuscrit est relu.", theme: "Bureau", difficulty: 3, ruleSlugs: ["excepté-vu"] },
    { text: "Les trois heures que ce trajet m'a coûté furent pénibles.", theme: "Voyage", difficulty: 3, ruleSlugs: ["pp-couté"] },
    { text: "Plus d'un participant s'est plaint de l'organisation du colloque.", theme: "Travail", difficulty: 3, ruleSlugs: ["plus-dun"] },
    { text: "Moins de deux mois séparent les deux événements annoncés.", theme: "Nombres et mesures", difficulty: 3, ruleSlugs: ["accord-moins-de-deux"] },
    { text: "C'est un des rares livres qui méritent d'être relus chaque année.", theme: "Vie scolaire", difficulty: 3, ruleSlugs: ["un-des-qui"] },
    { text: "Ce sont les voisins qui ont prévenu les pompiers cette nuit.", theme: "Maison", difficulty: 3, ruleSlugs: ["cest-ce-sont"] },
    { text: "Il aurait dû prévenir avant de partir aussi précipitamment.", theme: "Récit", difficulty: 3, ruleSlugs: ["conj-conditionnel-passe-2", "du-du-accent"] },
    { text: "Si tu avais prévenu, nous serions venus te chercher à la gare.", theme: "Voyage", difficulty: 3, ruleSlugs: ["conj-plus-que-parfait"] },
    { text: "Je doute qu'il puisse terminer ce travail avant la fin du mois.", theme: "Travail", difficulty: 3, ruleSlugs: ["conj-subjonctif-doute", "subj-pouvoir"] },
    { text: "Nous croyions alors que tout allait rentrer dans l'ordre.", theme: "Récit", difficulty: 3, ruleSlugs: ["conj-verbes-croire-voir-imparfait", "imparfait-ions"] },
    { text: "Il faudrait qu'ils aillent voir par eux-mêmes ce qui s'est passé.", theme: "Discussion", difficulty: 3, ruleSlugs: ["conj-verbes-aller-subjonctif", "meme"] },
    { text: "Elle a monté les valises jusqu'au troisième étage sans aide.", theme: "Maison", difficulty: 3, ruleSlugs: ["conj-passe-compose-etre-avoir", "auxiliaire"] },
    { text: "Il connaît la région comme sa poche depuis son enfance.", theme: "Voyage", difficulty: 3, ruleSlugs: ["conj-verbes-aitre"] },
    { text: "Nous peignons la cuisine ce week-end si le temps le permet.", theme: "Maison", difficulty: 3, ruleSlugs: ["conj-verbes-eindre-oindre", "week-end"] },
    { text: "Ils finirent leur repas sans échanger le moindre mot.", theme: "Récit", difficulty: 3, ruleSlugs: ["passé-simple-pluriel"] },
    { text: "Le personnel navigant est convoqué à sept heures précises.", theme: "Travail", difficulty: 3, ruleSlugs: ["fatigant", "participe-présent"] },
    { text: "Il a acquis une solide expérience en moins de trois ans.", theme: "Travail", difficulty: 3, ruleSlugs: ["acquerir"] },
    { text: "De vieilles gens attendaient devant la mairie encore fermée.", theme: "Récit", difficulty: 3, ruleSlugs: ["accord-gens"] },
    { text: "Une foule de curieux s'étaient massés devant la vitrine.", theme: "Récit", difficulty: 3, ruleSlugs: ["accord-collectif-groupe"] },
    { text: "Les Misérables restent son roman préféré depuis l'adolescence.", theme: "Vie scolaire", difficulty: 3, ruleSlugs: ["accord-titre-oeuvre", "nombreux-sujet"] },
    { text: "Quelques-unes de ces photographies datent d'avant la guerre.", theme: "Récit", difficulty: 3, ruleSlugs: ["accord-quelques-uns", "orthographe"] },
    { text: "Elle a rendu la copie telle quelle, sans même la relire.", theme: "Vie scolaire", difficulty: 3, ruleSlugs: ["accord-tel-quel", "meme"] },
    { text: "Tout autre candidat aurait renoncé depuis bien longtemps.", theme: "Travail", difficulty: 3, ruleSlugs: ["accord-tout-autre"] },
    { text: "Nul obstacle ne l'a jamais découragé, nulle remarque non plus.", theme: "Récit", difficulty: 3, ruleSlugs: ["accord-nul-nulle", "aucun"] },
    { text: "Les archéologues ont mis au jour une villa romaine intacte.", theme: "Récit", difficulty: 3, ruleSlugs: ["mettre-au-jour"] },
    { text: "Il a vérifié par acquit de conscience, sans y croire vraiment.", theme: "Bureau", difficulty: 3, ruleSlugs: ["acquit"] },
    { text: "D'ores et déjà, nous pouvons annoncer une baisse des tarifs.", theme: "Écrits professionnels", difficulty: 3, ruleSlugs: ["dores-deja"] },
    { text: "Nous corrigerons au fur et à mesure des retours du client.", theme: "Travail", difficulty: 3, ruleSlugs: ["au-fur"] },
    { text: "En son for intérieur, il savait la vérité depuis longtemps.", theme: "Récit", difficulty: 3, ruleSlugs: ["for-interieur"] },
    { text: "La maison est de plain-pied, sans la moindre marche à monter.", theme: "Maison", difficulty: 3, ruleSlugs: ["plain-pied"] },
    { text: "Les orateurs se citaient à l'envi les uns les autres.", theme: "Discussion", difficulty: 3, ruleSlugs: ["a-lenvi"] },
    { text: "Ce champignon est vénéneux et cette vipère est venimeuse.", theme: "Nature", difficulty: 3, ruleSlugs: ["veneneux"] },
    { text: "Le médecin a prescrit trois semaines de repos complet.", theme: "Vie quotidienne", difficulty: 3, ruleSlugs: ["prescrire"] },
    { text: "Une inclinaison trop forte du toit compliquerait la couverture.", theme: "Maison", difficulty: 3, ruleSlugs: ["inclinaison"] },
    { text: "Il est entré par effraction, ce qui constitue une infraction grave.", theme: "Récit", difficulty: 3, ruleSlugs: ["effraction"] },
    { text: "Ses grands-parents ont émigré d'Italie au début du siècle dernier.", theme: "Récit", difficulty: 3, ruleSlugs: ["emigrer", "grand-mere"] },
    { text: "Veuillez agréer, Madame la Directrice, mes salutations distinguées.", theme: "Écrits professionnels", difficulty: 3, ruleSlugs: ["pro-agreer-salutations", "pro-monsieur-le-maire"] },
    { text: "Je fais suite à notre entretien téléphonique de mardi dernier.", theme: "Écrits professionnels", difficulty: 3, ruleSlugs: ["discute-suite-a"] },
    { text: "Nous accusons réception de votre demande et l'étudions actuellement.", theme: "Écrits professionnels", difficulty: 3, ruleSlugs: ["pro-accuser-reception"] },
    { text: "Madame, vous êtes priée de confirmer votre venue avant vendredi.", theme: "Écrits professionnels", difficulty: 3, ruleSlugs: ["pro-vous-de-politesse"] },
    { text: "Je me permets de revenir sur mon message du trois mars.", theme: "Écrits professionnels", difficulty: 3, ruleSlugs: ["pro-je-me-permets", "pro-relance-polie"] },
    { text: "Cette épicerie est bien fournie en produits de la région.", theme: "Vie quotidienne", difficulty: 3, ruleSlugs: ["impropriete-achalande"] },
    { text: "Dans la conjoncture actuelle, aucune conjecture ne tient longtemps.", theme: "Discussion", difficulty: 3, ruleSlugs: ["conjoncture", "impropriete-conjecture"] },
  ],
};
