/**
 * Second lot de dictées — 74 textes, pour porter le total à 200.
 *
 * Ils s'appuient surtout sur les règles des lots 008 à 015 : homophones
 * lexicaux, paronymes, conjugaisons irrégulières, expressions figées.
 */
import type { ContentBatch } from "../../../src/lib/content";

export const DICTATIONS_2: ContentBatch = {
  id: "dictations-002",
  rules: [],
  dictations: [
    /* ─────────────── niveau 1 ─────────────── */
    { text: "Ses bottes pleines de boue traînaient au bout du couloir.", theme: "Nature", difficulty: 1, ruleSlugs: ["boue-bout"] },
    { text: "La dent de lait est tombée dans le lavabo ce matin.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["dans-dent"] },
    { text: "Sous la tente, ma tante racontait des histoires de guerre.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["tante-tente", "week-end"] },
    { text: "Le laitier livrait ce lait laid et tiède chaque matin.", theme: "Cuisine", difficulty: 1, ruleSlugs: ["laid-lait"] },
    { text: "Sur ce ton, tu n'auras pas une seule part de thon.", theme: "Cuisine", difficulty: 1, ruleSlugs: ["thon-ton"] },
    { text: "Il a tiré l'eau du puits, puis rempli les deux seaux.", theme: "Nature", difficulty: 1, ruleSlugs: ["puits-puis", "seau-sceau"] },
    { text: "La chaîne du portail grinçait sous les branches du chêne.", theme: "Nature", difficulty: 1, ruleSlugs: ["chaine-chene"] },
    { text: "Contrôle la date inscrite sous le pot avant de l'ouvrir.", theme: "Cuisine", difficulty: 1, ruleSlugs: ["anglicisme-checker", "date-datte"] },
    { text: "En communiquant mieux, nous fabriquerions plus vite ces pièces.", theme: "Travail", difficulty: 1, ruleSlugs: ["conj-verbes-quer"] },
    { text: "Je reçois peu de courrier, mais j'ai bien reçu le tien.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["conj-verbe-recevoir", "cedille"] },
    { text: "Nous buvons peu de café, mais ils en boivent beaucoup.", theme: "Bureau", difficulty: 1, ruleSlugs: ["conj-verbe-boire"] },
    { text: "La dernière rangée reste libre pour les premiers arrivés.", theme: "Vie quotidienne", difficulty: 1, ruleSlugs: ["accord-ordinal"] },
    { text: "Ils sont restés debout et ont chanté tous ensemble.", theme: "Récit", difficulty: 1, ruleSlugs: ["accord-adverbe-invariable"] },
    { text: "Cette rencontre hasardeuse a changé le cours de sa vie.", theme: "Discussion", difficulty: 1, ruleSlugs: ["ortho-hasard-h"] },
    { text: "Toutes les commandes de la semaine ont été annulées hier.", theme: "Travail", difficulty: 1, ruleSlugs: ["anglicisme-canceller"] },
    { text: "Je ne sais pas encore quelle décision je vais prendre.", theme: "Discussion", difficulty: 1, ruleSlugs: ["registre-omission-ne", "accord-quel-attribut"] },
    { text: "L'équipe soignante assure une permanence toute la nuit.", theme: "Bureau", difficulty: 1, ruleSlugs: ["anglicisme-staff", "abrev-ordinaux"] },
    { text: "Le fichier des adhérents sera actualisé avant lundi matin.", theme: "Bureau", difficulty: 1, ruleSlugs: ["anglicisme-updater", "mettre-au-jour"] },
    { text: "Il est venu, il a vu, il est reparti presque aussitôt.", theme: "Récit", difficulty: 1, ruleSlugs: ["espace-apres-virgule", "aussitot"] },
    { text: "Il cherche un emploi stable depuis la fermeture de l'usine.", theme: "Travail", difficulty: 1, ruleSlugs: ["anglicisme-job"] },
    { text: "Le secrétariat répond au 01 45 67 89 10 jusqu'à midi.", theme: "Bureau", difficulty: 1, ruleSlugs: ["typo-numero-telephone"] },
    { text: "Il a recollé la poignée avec un morceau de scotch.", theme: "Maison", difficulty: 1, ruleSlugs: ["typo-marques-minuscule"] },
    { text: "Le mur du jardin est couvert de mûres jusqu'en septembre.", theme: "Nature", difficulty: 1, ruleSlugs: ["mur-mur-accent"] },
    { text: "Il est sûr de lui, mais il compte beaucoup sur nous.", theme: "Discussion", difficulty: 1, ruleSlugs: ["sur-sur-accent"] },

    /* ─────────────── niveau 2 ─────────────── */
    { text: "Les rennes du troupeau suivaient la reine des neiges.", theme: "Récit", difficulty: 2, ruleSlugs: ["reine-renne"] },
    { text: "Il pense à panser sa plaie avant de repartir travailler.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["panser-penser"] },
    { text: "Après la pose des fenêtres, ils ont fait une longue pause.", theme: "Maison", difficulty: 2, ruleSlugs: ["pause-pose"] },
    { text: "Le poids des petits pois n'atteint même pas un kilo.", theme: "Cuisine", difficulty: 2, ruleSlugs: ["poids-pois", "unites-espace"] },
    { text: "Un inconnu rôdait près du hangar mal rodé de la ferme.", theme: "Nature", difficulty: 2, ruleSlugs: ["roder-roder-accent"] },
    { text: "Il a cherché en vain le vin que vingt convives attendaient.", theme: "Récit", difficulty: 2, ruleSlugs: ["vain-vin-vingt", "vingt-cent"] },
    { text: "Ma chère amie, cette viande coûte vraiment trop cher.", theme: "Cuisine", difficulty: 2, ruleSlugs: ["chair-chere-cher"] },
    { text: "Sans une goutte de sang, cent analyses restaient impossibles.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["sang-cent-sans"] },
    { text: "La grêle a cabossé toute la tôle ondulée du garage.", theme: "Maison", difficulty: 2, ruleSlugs: ["taule-tole"] },
    { text: "Le plongeur immerge la caméra avant que le rocher n'émerge.", theme: "Nature", difficulty: 2, ruleSlugs: ["emerger-immerger"] },
    { text: "L'évasion a suivi de très peu l'invasion du bâtiment.", theme: "Récit", difficulty: 2, ruleSlugs: ["evasion-invasion"] },
    { text: "Il a esquissé un geste, puis esquivé la réponse attendue.", theme: "Discussion", difficulty: 2, ruleSlugs: ["esquisser-esquiver"] },
    { text: "Il admire la justesse de ce calcul et la justice du verdict.", theme: "Discussion", difficulty: 2, ruleSlugs: ["justesse-justice"] },
    { text: "Nous finissons tôt le vendredi, mais nous partons tard.", theme: "Travail", difficulty: 2, ruleSlugs: ["conj-verbes-ir-groupes"] },
    { text: "Sans arrosage, ces jeunes plants mourront avant l'été.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["conj-verbe-mourir"] },
    { text: "Ils courront le marathon si la pluie cesse d'ici demain.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["conj-verbe-courir"] },
    { text: "Sache que rien ne sera décidé avant la fin du mois.", theme: "Écrits professionnels", difficulty: 2, ruleSlugs: ["conj-verbe-savoir-imperatif"] },
    { text: "Il faut que nous soyons prêts avant l'ouverture des portes.", theme: "Travail", difficulty: 2, ruleSlugs: ["conj-verbe-etre-subjonctif", "conj-subjonctif-avant-que"] },
    { text: "Ce film me plaît, même s'il déplaît à toute la critique.", theme: "Discussion", difficulty: 2, ruleSlugs: ["conj-verbe-plaire"] },
    { text: "Ils écrivaient chaque semaine des lettres interminables.", theme: "Bureau", difficulty: 2, ruleSlugs: ["conj-verbe-ecrire"] },
    { text: "En naviguant de nuit, on distingue mal les feux du port.", theme: "Voyage", difficulty: 2, ruleSlugs: ["conj-verbes-guer", "cote-cote-cotte"] },
    { text: "Vas-y sans moi, et rapportes-en deux si tu en trouves.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["conj-imperatif-s-euphonique"] },
    { text: "Il est né en juin, et elle naquit deux ans plus tard.", theme: "Récit", difficulty: 2, ruleSlugs: ["conj-verbe-naitre"] },
    { text: "Vous souriiez beaucoup plus à cette époque de votre vie.", theme: "Discussion", difficulty: 2, ruleSlugs: ["conj-verbe-rire-sourire", "davantage"] },
    { text: "Deux basses-cours et trois grands-messes animent le village.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["pluriel-composes-nom-adjectif"] },
    { text: "Ces chefs-d'œuvre et ces pots-de-vin appartiennent au passé.", theme: "Nature", difficulty: 2, ruleSlugs: ["pluriel-composes-preposition"] },
    { text: "Les porte-parole ont lu un communiqué commun ce matin.", theme: "Travail", difficulty: 2, ruleSlugs: ["pluriel-composes-invariables"] },
    { text: "Elle portait une écharpe bleu clair et des gants gris souris.", theme: "Maison", difficulty: 2, ruleSlugs: ["accord-couleur-composee"] },
    { text: "C'est vous qui décidez de la date, pas le secrétariat.", theme: "Travail", difficulty: 2, ruleSlugs: ["accord-cest-nous-qui"] },
    { text: "Une trentaine de personnes se sont inscrites en un jour.", theme: "Vie scolaire", difficulty: 2, ruleSlugs: ["accord-dizaine"] },
    { text: "Un tiers des candidats ont renoncé avant même l'oral.", theme: "Vie scolaire", difficulty: 2, ruleSlugs: ["accord-fraction"] },
    { text: "Le thermomètre indiquait vingt-deux degrés à l'ombre.", theme: "Nature", difficulty: 2, ruleSlugs: ["typo-temperature", "hyphen-nombres"] },
    { text: "L'abbé refusa d'abattre le vieux tilleul de l'abbaye.", theme: "Récit", difficulty: 2, ruleSlugs: ["ortho-abattre-abbaye"] },
    { text: "Rien ne parvenait à l'apaiser avant que le calme n'apparaisse.", theme: "Maison", difficulty: 2, ruleSlugs: ["ortho-apercevoir-apparaitre"] },
    { text: "Le ballon a crevé pendant la balade du dimanche matin.", theme: "Récit", difficulty: 2, ruleSlugs: ["ortho-balade-ballon", "balade"] },
    { text: "Le parallélisme des roues sera vérifié au prochain contrôle.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["ortho-parallele"] },
    { text: "Ce personnage secondaire révèle une personnalité complexe.", theme: "Travail", difficulty: 2, ruleSlugs: ["ortho-personnel-personnage"] },
    { text: "Laisse-la tranquille : elle cherche un peu de tranquillité.", theme: "Nature", difficulty: 2, ruleSlugs: ["ortho-tranquille"] },
    { text: "Pendant les vacances, il s'est enfin fait vacciner.", theme: "Vie quotidienne", difficulty: 2, ruleSlugs: ["ortho-vaccin-vacance"] },
    { text: "Une poignée de spectateurs assistait à la montée du col.", theme: "Vie scolaire", difficulty: 2, ruleSlugs: ["ortho-noms-en-ee"] },
    { text: "La santé et la liberté valent mieux que toutes les richesses.", theme: "Discussion", difficulty: 2, ruleSlugs: ["ortho-noms-en-te"] },
    { text: "Le réalisme de ce roman rappelle beaucoup celui de Balzac.", theme: "Vie scolaire", difficulty: 2, ruleSlugs: ["ortho-mots-en-isme"] },
    { text: "Le candidat marchait sur le tapis d'un pas très lourd.", theme: "Récit", difficulty: 2, ruleSlugs: ["ortho-consonnes-finales-muettes"] },
    { text: "Le miroir du couloir reflète toute la baignoire.", theme: "Maison", difficulty: 2, ruleSlugs: ["ortho-mots-en-oire-oir"] },
    { text: "Il faudra renseigner les nouveaux venus dès leur arrivée.", theme: "Travail", difficulty: 2, ruleSlugs: ["anglicisme-briefer"] },
    { text: "Le décret institue un organisme que la loi avait instauré.", theme: "Travail", difficulty: 2, ruleSlugs: ["impropriete-instaurer"] },

    /* ─────────────── niveau 3 ─────────────── */
    { text: "Le niveau du fleuve a crû sans que personne l'ait cru possible.", theme: "Nature", difficulty: 3, ruleSlugs: ["cru-cru-accent"] },
    { text: "Le notaire scelle l'acte pendant qu'il ajuste sa selle.", theme: "Récit", difficulty: 3, ruleSlugs: ["selle-celle-scelle"] },
    { text: "Ce mets délicat ne se sert qu'au mois de mai, mais rarement.", theme: "Cuisine", difficulty: 3, ruleSlugs: ["mets-mai-mais", "jours-mois"] },
    { text: "Le maire et sa mère se promènent au bord de la mer.", theme: "Récit", difficulty: 3, ruleSlugs: ["mer-mere-maire"] },
    { text: "Il a trouvé les mots justes pour apaiser tous ses maux.", theme: "Discussion", difficulty: 3, ruleSlugs: ["mot-maux"] },
    { text: "Sa main a effleuré la pierre qui affleure sous la mousse.", theme: "Nature", difficulty: 3, ruleSlugs: ["affleurer-effleurer"] },
    { text: "Ce procédé immoral révolte ceux qu'on croyait amoraux.", theme: "Discussion", difficulty: 3, ruleSlugs: ["amoral-immoral"] },
    { text: "Anobli par le roi, il fut ennobli par ses propres actes.", theme: "Récit", difficulty: 3, ruleSlugs: ["anoblir-ennoblir"] },
    { text: "L'avènement du roi fut l'événement du siècle entier.", theme: "Récit", difficulty: 3, ruleSlugs: ["avenement-evenement"] },
    { text: "Le mur décrépi abritait un vieillard décrépit et muet.", theme: "Récit", difficulty: 3, ruleSlugs: ["decrepit-decrepi"] },
    { text: "Le maçon a enduit la façade sans induire personne en erreur.", theme: "Maison", difficulty: 3, ruleSlugs: ["enduire-induire"] },
    { text: "Le public exultait pendant que l'orateur exaltait leur courage.", theme: "Vie scolaire", difficulty: 3, ruleSlugs: ["exalter-exulter"] },
    { text: "Les naufragés mouraient d'inanition, conscients de leur inanité.", theme: "Discussion", difficulty: 3, ruleSlugs: ["inanition-inanite"] },
    { text: "Infliger une amende n'a nullement infléchi son comportement.", theme: "Discussion", difficulty: 3, ruleSlugs: ["infliger-inflechir", "amande-amende"] },
    { text: "La magnificence du palais rappelle la munificence de son bâtisseur.", theme: "Récit", difficulty: 3, ruleSlugs: ["munificence-magnificence"] },
    { text: "Un homme oisif tient parfois des propos bien oiseux.", theme: "Discussion", difficulty: 3, ruleSlugs: ["oiseux-oisif"] },
    { text: "Cette jument ombrageuse refuse le chemin pourtant bien ombragé.", theme: "Nature", difficulty: 3, ruleSlugs: ["ombrageux-ombrage"] },
    { text: "Une angoisse sourde l'oppressait dans ce pays opprimé.", theme: "Récit", difficulty: 3, ruleSlugs: ["opprimer-oppresser"] },
    { text: "Les pêcheurs réparaient leurs filets, indifférents aux pécheurs.", theme: "Récit", difficulty: 3, ruleSlugs: ["pecheur-pecheur-accent"] },
    { text: "Le percepteur a écrit au précepteur des jeunes princes.", theme: "Récit", difficulty: 3, ruleSlugs: ["percepteur-precepteur"] },
    { text: "Stupéfaite par l'annonce, elle fut stupéfiée une seconde fois.", theme: "Récit", difficulty: 3, ruleSlugs: ["stupefait-stupefie", "deux-points-explication"] },
    { text: "Cette sujétion horaire rend toute suggestion difficile à tenir.", theme: "Bureau", difficulty: 3, ruleSlugs: ["suggestion-sujetion"] },
    { text: "Quand elle fut sortie, un long silence envahit la pièce.", theme: "Récit", difficulty: 3, ruleSlugs: ["conj-passe-anterieur"] },
    { text: "Il fallait qu'il fût là bien avant l'ouverture des portes.", theme: "Récit", difficulty: 3, ruleSlugs: ["conj-imparfait-subjonctif"] },
    { text: "Le blé croît vite, mais nul n'a cru qu'il pousserait tant.", theme: "Nature", difficulty: 3, ruleSlugs: ["conj-verbe-croitre"] },
    { text: "Nous fuyons le bruit de la ville, mais le temps nous fuit.", theme: "Récit", difficulty: 3, ruleSlugs: ["conj-verbe-fuir"] },
    { text: "Mû par la colère, il a claqué la porte sans un mot.", theme: "Récit", difficulty: 3, ruleSlugs: ["conj-verbe-mouvoir"] },
    { text: "Le rapport conclut à une négligence, comme l'accord conclu jadis.", theme: "Travail", difficulty: 3, ruleSlugs: ["conj-verbe-conclure"] },
    { text: "Le service est inclus, mais le pourboire en reste exclu.", theme: "Vie quotidienne", difficulty: 3, ruleSlugs: ["conj-verbe-exclure-inclure"] },
    { text: "Ils vinrent très tôt et tinrent parole jusqu'au bout.", theme: "Récit", difficulty: 3, ruleSlugs: ["conj-verbe-tenir-venir"] },
    { text: "Nous prévoirons deux jours de marge et nous verrons bien.", theme: "Travail", difficulty: 3, ruleSlugs: ["conj-verbe-prevoir-futur"] },
    { text: "Ni la pluie ni le vent n'ont découragé les marcheurs.", theme: "Discussion", difficulty: 3, ruleSlugs: ["accord-verbe-ni-ni"] },
    { text: "Je les crois honnêtes et je les juge parfaitement compétents.", theme: "Discussion", difficulty: 3, ruleSlugs: ["accord-attribut-cod"] },
    { text: "La mère, aussi bien que le père, est responsable des enfants.", theme: "Travail", difficulty: 3, ruleSlugs: ["accord-de-meme-que", "majuscule-fonctions"] },
    { text: "Les premiers-nés héritaient autrefois de toute la ferme.", theme: "Vie quotidienne", difficulty: 3, ruleSlugs: ["pluriel-adjectifs-composes"] },
    { text: "Les familles ayant droit à cette aide seront prévenues.", theme: "Vie scolaire", difficulty: 3, ruleSlugs: ["accord-participe-ayant"] },
    { text: "Sa feue tante lui a légué la maison de famille.", theme: "Récit", difficulty: 3, ruleSlugs: ["accord-feu-defunt"] },
    { text: "Le vent, la pluie, le froid, tout semblait contre eux.", theme: "Récit", difficulty: 3, ruleSlugs: ["accord-tout-resume"] },
    { text: "Elle s'est fait couper les cheveux très court hier.", theme: "Vie quotidienne", difficulty: 3, ruleSlugs: ["accord-se-faire-participe"] },
    { text: "Les pièces qu'elle a crues utiles figurent toutes en annexe.", theme: "Bureau", difficulty: 3, ruleSlugs: ["accord-participe-que-attribut"] },
    { text: "Monsieur le préfet a signé l'arrêté en fin de matinée.", theme: "Travail", difficulty: 3, ruleSlugs: ["accord-madame-le-titre"] },
    { text: "Il a rapporté de belles photos de son voyage en Grèce.", theme: "Voyage", difficulty: 3, ruleSlugs: ["accord-nom-apres-des"] },
    { text: "La saison bat son plein depuis le début du mois de juin.", theme: "Récit", difficulty: 3, ruleSlugs: ["expr-battre-son-plein"] },
    { text: "De guerre lasse, le voisin a fini par retirer sa plainte.", theme: "Discussion", difficulty: 3, ruleSlugs: ["expr-de-guerre-lasse"] },
    { text: "Le financement demeure la principale pierre d'achoppement.", theme: "Travail", difficulty: 3, ruleSlugs: ["expr-pierre-achoppement"] },
    { text: "Le maire a coupé court à toutes les rumeurs du village.", theme: "Discussion", difficulty: 3, ruleSlugs: ["expr-couper-court"] },
    { text: "Le maire est en butte à une opposition de plus en plus vive.", theme: "Travail", difficulty: 3, ruleSlugs: ["expr-en-butte-a"] },
    { text: "Ce ton familier n'est pas de mise dans une réunion publique.", theme: "Nature", difficulty: 3, ruleSlugs: ["expr-etre-de-mise"] },
    { text: "Le conseil a fait fi de l'avis pourtant unanime des riverains.", theme: "Travail", difficulty: 3, ruleSlugs: ["expr-faire-fi"] },
    { text: "Ce programme fonctionne sous l'égide des Nations unies.", theme: "Récit", difficulty: 3, ruleSlugs: ["expr-sous-legide"] },
    { text: "Cette dépense a été engagée à bon escient, sans excès.", theme: "Bureau", difficulty: 3, ruleSlugs: ["expr-a-bon-escient"] },
    { text: "Nonobstant les délais, la livraison a bien eu lieu mardi.", theme: "Travail", difficulty: 3, ruleSlugs: ["expr-nonobstant"] },
    { text: "Les deux navires ont longtemps navigué de conserve.", theme: "Travail", difficulty: 3, ruleSlugs: ["expr-de-concert"] },
    { text: "Il s'en est fallu de peu que le vieux pont ne cède.", theme: "Récit", difficulty: 3, ruleSlugs: ["expr-sen-falloir"] },
  ],
};
