/** Littérature, premier lot — les cours. */
import type { LotCours } from "../commun";

export const COURS_LITTERATURE: LotCours = {
  "li-genres-litteraires": [
    ["Les formes du récit", `Un genre se définit par sa forme et son mode d'énonciation, non par son sujet : un même sujet peut donner un roman, une pièce ou un poème. Le roman est le genre le plus souple, et se décline en sous-formes selon son dispositif. Le roman épistolaire est composé de lettres échangées, ce qui supprime le narrateur extérieur et multiplie les points de vue — Les Liaisons dangereuses en est le sommet français.

La nouvelle se distingue du roman par la brièveté et par le resserrement : une intrigue unique, peu de personnages, une chute souvent. La fable est un court récit à visée morale, mettant fréquemment en scène des animaux, dont l'origine remonte à Ésope et que La Fontaine a porté à sa perfection française.`],
    ["Écrire sur soi", `L'essai est un texte de réflexion personnelle sur un sujet, sans prétention à l'exhaustivité ni à la démonstration systématique. Montaigne invente le mot et la chose au XVIe siècle : essayer, c'est mettre à l'épreuve sa propre pensée.

L'autobiographie est le récit de sa propre vie par son auteur, avec un pacte implicite : ce qui est raconté est présenté comme vrai. L'autofiction, terme forgé en 1977 par Serge Doubrovsky, rompt ce pacte en assumant une part de fiction dans un récit de soi : l'auteur porte son nom, mais ne garantit plus l'exactitude. La distinction n'est pas seulement théorique, elle a donné lieu à des procès.`],
    ["Théâtre et poésie", `La tragédie classique obéit à des contraintes strictes : cinq actes, en vers, un héros de rang noble qui court à sa perte, et le respect des unités de temps, de lieu et d'action. Le drame romantique, deux siècles plus tard, rejette ces règles et revendique le mélange des registres et des milieux sociaux, sur le modèle revendiqué de Shakespeare.

En poésie, le sonnet est une forme fixe importée d'Italie : quatorze vers répartis en deux quatrains et deux tercets, avec un jeu de rimes contraint. Le poème en prose, apparu au XIXe siècle avec Aloysius Bertrand puis Baudelaire, abandonne vers et rimes tout en revendiquant la densité et le rythme de la poésie : c'est une définition par la tension plutôt que par la forme.`],
  ],

  "li-versification": [
    ["Compter les syllabes", `Le vers français se mesure en syllabes, non en accents. L'alexandrin, vers de douze syllabes, tire son nom du Roman d'Alexandre, poème du XIIe siècle écrit dans ce mètre. Le décasyllabe en compte dix, l'octosyllabe huit.

La difficulté du décompte tient au e muet : il compte comme une syllabe devant une consonne, s'élide devant une voyelle, et ne compte jamais en fin de vers. Une diérèse ajoute encore une possibilité : prononcer en deux syllabes ce qui s'en dit une dans la langue courante, comme dans un vers où le mot lion est compté pour deux. La synérèse fait l'inverse.`],
    ["Couper et enjamber", `L'alexandrin classique porte une césure après la sixième syllabe, qui le divise en deux hémistiches équilibrés. Le romantisme brisera cet équilibre en déplaçant la coupe, ce qui suffisait à faire scandale.

L'enjambement fait déborder une phrase sur le vers suivant : le sens et le mètre cessent de coïncider, ce qui crée une tension expressive. Le rejet et le contre-rejet en sont des variantes plus précises, selon que l'élément déborde en début ou en fin de vers. Ces procédés font partie de la ressource ordinaire du poète depuis le XIXe siècle ; ils étaient bannis par la doctrine classique.`],
    ["Les rimes, et leur abandon", `Les rimes se disposent selon trois schémas principaux : plates ou suivies en AABB, croisées en ABAB, embrassées en ABBA. Leur qualité se mesure au nombre de sons communs : une rime pauvre en partage un, une rime suffisante deux, une rime riche au moins trois.

La poésie classique impose en outre l'alternance des rimes féminines, terminées par un e muet, et des rimes masculines. Tout cet édifice est démonté à la fin du XIXe siècle : le vers libre abandonne mètre et rime réguliers, gardant du vers la seule disposition en lignes. Apollinaire ira plus loin avec le calligramme, poème dont la disposition sur la page dessine une figure — la forme visible devenant elle-même porteuse de sens.`],
  ],

  "li-figures-style": [
    ["Rapprocher", `La comparaison et la métaphore font le même geste, rapprocher deux réalités, mais pas de la même façon : la comparaison montre l'outil de comparaison — comme, tel, semblable à — quand la métaphore le supprime et pose l'identité. Cette suppression est ce qui fait sa force : elle n'illustre pas, elle affirme.

Deux autres figures procèdent par contiguïté et non par ressemblance. La métonymie désigne une chose par un terme qui lui est logiquement lié : boire un verre, lire un Zola. La synecdoque, cas particulier, désigne le tout par la partie ou l'inverse : une voile pour un navire, cent têtes pour cent bêtes.`],
    ["Amplifier, atténuer", `L'hyperbole exagère volontairement : mourir de faim, des siècles d'attente. Elle est si répandue dans la langue courante qu'on ne la perçoit plus comme figure.

À l'opposé, la litote dit moins pour faire entendre plus — l'exemple canonique étant le va, je ne te hais point de Chimène, qui signifie exactement le contraire de sa lettre. L'euphémisme atténue lui aussi, mais dans une autre intention : adoucir une réalité désagréable plutôt que renforcer par la retenue. L'oxymore, enfin, associe deux termes contradictoires — obscure clarté, silence assourdissant — et produit du sens par le heurt même.`],
    ["Répéter, feindre", `L'anaphore répète un mot en tête de plusieurs propositions successives : c'est la figure du discours politique par excellence, parce qu'elle martèle et structure à la fois. L'allitération répète un même son consonantique à l'intérieur d'un vers ou d'une phrase, l'assonance faisant de même avec les voyelles.

La prétérition relève d'une autre logique, celle de la feinte : annoncer qu'on ne dira pas ce qu'on dit malgré tout — je ne mentionnerai pas ses échecs répétés. Elle permet de formuler une accusation tout en affichant la délicatesse de s'en abstenir, ce qui la rend redoutable en rhétorique judiciaire et politique.`],
  ],

  "li-theatre-francais": [
    ["Une institution", `La Comédie-Française est fondée en 1680 par une décision de Louis XIV, qui fusionne les troupes parisiennes existantes en une seule compagnie dotée d'un monopole. Elle est aujourd'hui la plus ancienne troupe de théâtre permanente au monde encore en activité.

Son surnom, la Maison de Molière, tient à ce que la troupe issue de celle de Molière, mort sept ans plus tôt, en constituait le noyau. Son organisation en société d'acteurs — sociétaires et pensionnaires — remonte à cette origine et n'a pas d'équivalent.`],
    ["Les scandales", `Le théâtre français a ses batailles. Le Mariage de Figaro, de Beaumarchais, est écrit en 1778 mais interdit pendant six ans par la censure royale, qui y voit avec raison une charge contre les privilèges : sa création en 1784 est un triomphe et un présage.

En 1830, la première d'Hernani, de Victor Hugo, tourne à l'affrontement organisé entre partisans du romantisme et défenseurs des règles classiques : ce que la salle défendait, ce n'était pas une pièce, c'était une conception de la littérature. La bataille dure plusieurs représentations et devient le symbole du basculement romantique.`],
    ["Le XXe siècle", `Après-guerre, le théâtre se réinvente sur deux fronts. Samuel Beckett écrit En attendant Godot, créée en 1953 : deux vagabonds attendent quelqu'un qui ne viendra pas, l'intrigue est abolie et l'attente devient le sujet. Eugène Ionesco pousse l'absurde vers la mécanique du langage ; sa Cantatrice chauve, créée en 1950, est jouée sans interruption depuis 1957 dans le même petit théâtre parisien.

Sur le plan des idées, Antonin Artaud avait appelé dès 1938, dans Le Théâtre et son double, à un théâtre de la cruauté agissant physiquement sur le spectateur. Bertolt Brecht propose une voie inverse avec la distanciation : empêcher l'identification, rappeler au spectateur qu'il est au théâtre, pour qu'il juge au lieu de s'émouvoir. Côté institutions, Jean Vilar donne au Théâtre national populaire sa forme d'après-guerre et crée en 1947 le Festival d'Avignon, avec l'ambition d'un théâtre exigeant pour un public large.`],
  ],

  "li-litterature-anglaise": [
    ["Shakespeare", `Shakespeare a écrit environ trente-sept pièces et cent cinquante-quatre sonnets, sur une carrière d'une vingtaine d'années. L'ampleur de son influence sur l'anglais est telle qu'on lui attribue l'introduction de milliers de mots et d'expressions dans la langue courante.

Hamlet, sa pièce la plus longue, se déroule au Danemark : un prince apprend par un spectre que son père a été assassiné par son oncle, et diffère indéfiniment sa vengeance. L'hésitation y devient un caractère, ce qui était inédit au théâtre.`],
    ["Le roman britannique", `Jane Austen ouvre Orgueil et Préjugés sur une phrase devenue proverbiale, à propos de la vérité universellement reconnue qu'un homme fortuné doit chercher une épouse : l'ironie du narrateur y est un instrument d'analyse sociale. En 1816, au bord du lac Léman, un défi littéraire entre amis conduit Mary Shelley, âgée de dix-huit ans, à écrire Frankenstein — souvent tenu pour le premier roman de science-fiction.

Charles Dickens fait du roman une machine à décrire la misère industrielle : Oliver Twist s'ouvre sur un orphelin réclamant du rab de gruau, scène devenue emblématique. Emily Brontë, l'une des trois sœurs écrivaines, publie Les Hauts de Hurlevent, roman d'une violence passionnelle qui déconcerta ses contemporains.`],
    ["Modernisme et après", `Le XXe siècle apporte la rupture formelle. James Joyce raconte dans Ulysse une seule journée à Dublin, le 16 juin 1904, en épousant le flux de conscience de ses personnages et en pastichant tous les styles de la prose anglaise. Virginia Woolf explore la même voie dans Mrs Dalloway et Les Vagues, en dissolvant l'intrigue dans la perception.

George Orwell, en 1949, publie 1984 : une société de surveillance totale où le langage lui-même est réduit pour rendre la dissidence impensable. De l'autre côté de l'Atlantique, Ernest Hemingway impose une prose dépouillée, dont Le Vieil Homme et la Mer est l'aboutissement — un récit de quelques dizaines de pages qui lui vaut le Pulitzer puis le Nobel.`],
  ],

  "li-litteratures-monde": [
    ["Le roman russe", `Le XIXe siècle russe produit deux monuments. Guerre et Paix, de Tolstoï, se déroule pendant les guerres napoléoniennes et mêle des centaines de personnages à une réflexion sur les causes de l'histoire : l'auteur y conteste que les grands hommes la fassent.

Dostoïevski travaille à l'échelle inverse, celle de la conscience. Crime et Châtiment raconte le meurtre d'une vieille usurière par un étudiant persuadé d'être au-dessus de la loi commune, et les six cents pages qui suivent examinent ce que cet acte fait à celui qui l'a commis.`],
    ["L'Amérique latine", `Gabriel García Márquez publie en 1967 Cent Ans de solitude, histoire d'une famille et d'un village imaginaire sur plusieurs générations, où le prodige est raconté du même ton que le quotidien : c'est le réalisme magique, qui donnera son identité au boom latino-américain.

Jorge Luis Borges, Argentin, travaille au format court : les nouvelles réunies dans Fictions construisent des labyrinthes, des bibliothèques infinies et des livres qui se réécrivent, avec une économie de moyens qui a influencé toute la littérature contemporaine. Isabel Allende, Chilienne, prolonge la veine familiale et politique avec La Maison aux esprits.`],
    ["L'Asie, l'Afrique, et les origines", `Le Dit du Genji, écrit vers l'an mille par Murasaki Shikibu, femme de la cour japonaise, est souvent tenu pour le premier roman du monde : plus de mille pages, une psychologie fine, une construction qui n'a pas d'équivalent à cette date. Yasunari Kawabata obtient en 1968 le premier prix Nobel de littérature japonais.

En Afrique, Chinua Achebe publie en 1958 Le Monde s'effondre, qui raconte l'arrivée des colons britanniques du point de vue d'un village igbo : le roman inaugure une littérature africaine de langue anglaise écrite depuis l'intérieur. Wole Soyinka, Nigérian lui aussi, reçoit en 1986 le premier prix Nobel de littérature décerné à un écrivain africain. Bien avant tout cela, L'Épopée de Gilgamesh, écrite en Mésopotamie, reste l'un des plus anciens textes littéraires connus.`],
  ],

  "li-critique-lecture": [
    ["Qui raconte", `Le narrateur n'est pas l'auteur : c'est une voix construite à l'intérieur du récit, dont l'auteur peut se distinguer entièrement. Confondre les deux est l'erreur d'analyse la plus fréquente.

Cette voix peut adopter différentes positions. Un narrateur interne raconte depuis le point de vue d'un personnage, avec les limites de sa connaissance. Un narrateur omniscient connaît les pensées de tous les personnages et peut anticiper les événements. La focalisation externe fait l'inverse : le récit ne rapporte que ce qui est visible, comme une caméra, sans accès à aucune intériorité — technique du roman behavioriste et du polar américain.`],
    ["Sur quel ton", `Le registre qualifie l'effet visé par un texte. Le registre pathétique cherche à émouvoir et à susciter la compassion, en insistant sur la souffrance. Le registre épique amplifie : il grandit l'action et les personnages, multiplie les hyperboles et les pluriels, et transforme un combat individuel en affrontement de forces.

L'ironie relève d'un autre mécanisme : faire entendre le contraire de ce que l'on dit, en comptant sur la complicité du lecteur pour rétablir le sens. Elle échoue dès que cette complicité manque — d'où les malentendus fréquents lorsqu'un texte ironique est cité hors contexte.`],
    ["Comment c'est construit", `Le récit organise librement le temps. Une analepse est un retour en arrière ; une prolepse, une anticipation ; une ellipse narrative passe une période sous silence, laissant au lecteur le soin de combler. Ces écarts entre le temps de l'histoire et celui du récit sont l'un des principaux moyens d'expression du romancier.

Deux autres notions servent à décrire les emboîtements. La mise en abyme est le procédé par lequel une œuvre contient une reproduction d'elle-même — une pièce jouée dans la pièce, un tableau représentant le tableau. L'intertextualité désigne la présence d'un texte dans un autre, par citation, allusion, pastiche ou parodie : aucun texte n'est écrit dans le vide, et repérer ses dettes fait partie de la lecture.`],
  ],

  "li-langues-traduction": [
    ["Le traducteur est un auteur", `La loi française reconnaît au traducteur littéraire le statut d'auteur : sa traduction est une œuvre dérivée, protégée à part entière, et il perçoit des droits sur les ventes. Ce n'est pas une subtilité juridique — cela signifie qu'une traduction est une création, avec ses choix, son style et sa date, et non un décalque neutre.

C'est ce qui justifie les retraductions : traduire à nouveau une œuvre déjà traduite n'est pas corriger une erreur, c'est proposer une autre lecture, dans une langue d'arrivée qui a elle-même changé. Les grands textes sont retraduits toutes les deux ou trois générations.`],
    ["Deux fidélités", `L'histoire de la traduction oscille entre deux exigences contradictoires. Au XVIIe siècle, on appelait les belles infidèles ces traductions élégantes mais éloignées de l'original, qui adaptaient les Anciens au goût du temps quitte à les réécrire.

La tension subsiste sous d'autres noms. Une traduction cibliste privilégie la fluidité dans la langue d'arrivée : le lecteur ne doit pas sentir qu'il lit une traduction. Une traduction sourcière conserve au contraire les aspérités de l'original, quitte à malmener le français. Aucune des deux positions n'est absurde, et le choix engage tout le texte. Le piège technique le plus banal reste le faux ami : un mot qui ressemble à un autre dans une autre langue mais n'en a pas le sens.`],
    ["Les traductions qui ont fait des langues", `Certaines traductions ont eu plus d'effet que des œuvres originales. La Septante est la traduction en grec de la Bible hébraïque, réalisée à Alexandrie à partir du IIIe siècle avant notre ère : elle rend le texte accessible au monde hellénistique et servira de base aux premiers chrétiens. Au IVe siècle, saint Jérôme traduit la Bible en latin — la Vulgate — qui restera la référence occidentale pendant mille ans.

La traduction de la Bible par Martin Luther, au XVIe siècle, a contribué à fixer l'allemand moderne en imposant une norme écrite commune. Aujourd'hui, la traduction automatique neuronale produit des résultats convaincants à partir de modèles statistiques entraînés sur d'immenses corpus, mais bute précisément sur ce que la théorie appelle l'intraduisible : ce qui résiste au passage d'une langue à l'autre et oblige à choisir plutôt qu'à rendre.`],
  ],

  "li2-moliere": [
    ["Un fils de tapissier", `Jean-Baptiste Poquelin naît en 1622 dans une famille de tapissiers aisés. Son père détient la charge de tapissier ordinaire du roi, transmissible, qui lui assure une position confortable et un avenir tracé. Il l'abandonne à vingt et un ans pour fonder une troupe de théâtre — l'Illustre Théâtre — qui fait faillite en deux ans et le conduit brièvement en prison pour dettes.

Suivent treize années de tournées en province, où il apprend le métier, écrit ses premières farces et constitue une troupe soudée. Quand il revient à Paris en 1658, il a trente-six ans et une expérience de la scène que peu d'auteurs de son temps possèdent : il joue lui-même presque tous ses rôles principaux. C'est cette double position d'auteur et de comédien qui explique la théâtralité de son écriture.`,
      { image: "lit-moliere", legende: "Molière en costume de scène. Auteur, directeur de troupe et comédien, il jouait lui-même la plupart de ses grands rôles — Harpagon, Argan, Alceste." }],
    ["Le scandale et la censure", `Tartuffe est interdite pendant cinq ans. La pièce met en scène un faux dévot qui s'introduit dans une famille et manque de la ruiner ; le parti dévot y voit une attaque contre la religion elle-même, et obtient l'interdiction dès la première représentation en 1664. Molière remanie, plaide, écrit des placets au roi, et n'obtient l'autorisation définitive qu'en 1669.

Dom Juan, écrit dans l'intervalle pour compenser le manque à gagner, aggrave la situation : le séducteur impie y raisonne avec une force que sa punition finale — foudroyé par la statue du Commandeur — n'annule pas vraiment. La pièce est retirée après quelques semaines et ne sera plus jouée dans son texte intégral avant le XIXe siècle.`],
    ["Une galerie de caractères", `Molière ne peint pas des individus mais des travers, poussés jusqu'à l'obsession. Alceste, dans Le Misanthrope, exige une sincérité absolue de ses contemporains tout en aimant Célimène, la plus coquette et la plus mondaine des femmes : le comique naît de cette contradiction, et la pièce touche à autre chose que le rire.

Harpagon, dans L'Avare, est obsédé par sa cassette au point de préférer son argent à ses enfants — et de s'adresser au public pour lui demander s'il n'a pas vu son voleur. Monsieur Jourdain, dans Le Bourgeois gentilhomme, veut acquérir les manières de la noblesse et découvre avec ravissement qu'il fait de la prose depuis quarante ans sans le savoir. Chaque personnage est un mécanisme monté sur un seul ressort, ce qui les rend à la fois drôles et inquiétants.`],
    ["Musique, danse et brouille", `La comédie-ballet est un genre que Molière invente avec le compositeur Jean-Baptiste Lully : une pièce mêlant texte parlé, musique et danse, où les intermèdes chantés font partie de l'action au lieu de l'interrompre. Le Bourgeois gentilhomme en est l'exemple le plus abouti, avec sa cérémonie turque finale.

La collaboration se termine mal. Lully obtient du roi un privilège sur l'opéra qui restreint drastiquement le nombre de musiciens et de chanteurs autorisés dans les autres théâtres — dont celui de Molière. La brouille est totale et durable : c'est un conflit d'intérêts commerciaux autant qu'artistiques, dans un monde du spectacle où les monopoles royaux décidaient de tout.`],
    ["Les règles, et la fin", `La règle des trois unités — unité de temps, de lieu et d'action — s'impose au théâtre classique. Molière la respecte inégalement : rigoureusement dans ses grandes comédies en cinq actes, beaucoup plus librement dans ses pièces à machines et ses farces. Il s'en explique avec ironie dans La Critique de l'École des femmes : la grande règle, écrit-il, est de plaire.

Le 17 février 1673, il joue Le Malade imaginaire, où il tient le rôle d'Argan, malade imaginaire pris de convulsions. Il est réellement souffrant, achève la représentation et meurt quelques heures plus tard chez lui — non sur scène, contrairement à la légende. Comédien non repenti, il n'obtient une sépulture chrétienne que par intervention royale, de nuit et sans cérémonie.`],
  ],

  "li2-racine-corneille": [
    ["Deux générations, deux tragédies", `Corneille et Racine sont séparés par une génération et par une conception opposée de la tragédie. Chez Corneille, le héros choisit son destin : il est déchiré entre des exigences contradictoires, mais il tranche, et sa grandeur tient à ce choix. Chez Racine, la passion détruit le personnage sans qu'il puisse rien y opposer ; il sait ce qu'il fait, il le déplore, et il le fait quand même.

Cette différence a des conséquences sur tout : la longueur des pièces, le nombre de personnages, la place de l'action. Corneille bâtit des intrigues politiques complexes ; Racine élague jusqu'à ne garder qu'une situation et quatre ou cinq personnages enfermés ensemble.`],
    ["Corneille et la querelle du Cid", `Le Cid, créé en 1637, remporte un immense succès public et déclenche aussitôt une querelle littéraire. On reproche à Corneille d'avoir violé les règles — la pièce enchaîne trop d'événements en vingt-quatre heures — et surtout d'avoir montré une héroïne qui accepte d'épouser le meurtrier de son père. L'Académie française, sollicitée par Richelieu, rend des Sentiments partagés qui condamnent poliment la pièce.

Le dilemme du Cid est resté le modèle du genre : Rodrigue doit choisir entre son amour pour Chimène et l'honneur de sa famille, offensée par le père de celle-ci. Horace pousse la logique plus loin en opposant trois frères à trois frères, dont l'un est le beau-frère de l'autre camp : le devoir civique y écrase les liens de famille. Cinna, enfin, tourne autour de la clémence du souverain, qui pardonne à ceux qui conspiraient contre lui — sujet politique dans un régime en construction.`],
    ["Racine et l'enfermement", `Racine a été élevé à Port-Royal, foyer du jansénisme, courant religieux qui insiste sur la faiblesse de l'homme et sur la nécessité de la grâce : on ne se sauve pas par sa volonté. Sa formation explique en partie ses personnages, incapables de vouloir leur bien.

Andromaque repose sur une chaîne d'amours non réciproques : Oreste aime Hermione, qui aime Pyrrhus, qui aime Andromaque, qui aime son mari mort. Aucun de ces quatre ne peut être heureux, et chacun le sait dès le premier acte. Phèdre met en scène une reine dévorée d'amour pour le fils de son mari, consciente de l'horreur de sa passion et incapable de s'en défaire. Bérénice, enfin, se résume à une séparation sans mort ni sang : un empereur renvoie la femme qu'il aime parce que Rome ne veut pas d'une reine étrangère — Racine y démontre qu'une tragédie n'a besoin d'aucun cadavre.`],
    ["Le retrait et le retour", `Après l'échec relatif de Phèdre en 1677, Racine cesse d'écrire pour le théâtre public, devient historiographe du roi et se rapproche de la cour. Il ne reviendra à la scène que douze ans plus tard, à la demande de Madame de Maintenon, pour écrire deux tragédies bibliques destinées aux jeunes filles de la maison de Saint-Cyr : Esther et Athalie.

Ces pièces, écrites pour des élèves et sans destination commerciale, comptent parmi ses plus abouties, notamment Athalie avec ses chœurs chantés. Elles rappellent une réalité rarement soulignée : les deux plus grands tragédiens français ont écrit dans un système où le succès dépendait d'une cour, d'un ministre et d'une cabale autant que du public.`],
  ],
  "li2-conte-philosophique": [
    ["Raconter pour démontrer", `Le conte philosophique est un genre du XVIIIe siècle : un récit bref qui met une thèse à l'épreuve d'une fiction. Il n'illustre pas une idée déjà admise, il la soumet à des situations qui la mettent en difficulté — et la conclusion tient souvent dans une formule que le lecteur emporte.

Sa forme n'est pas un choix esthétique gratuit. Le conte déguise l'argumentation en récit pour échapper à la censure : un traité contre l'Église ou la monarchie est saisi, un conte oriental amusant circule. Voltaire n'a d'ailleurs jamais reconnu la paternité de la plupart des siens, publiés sous pseudonyme et à l'étranger.`,
      { image: "lit-voltaire", legende: "Voltaire, qui publiait ses contes anonymement ou sous pseudonyme, souvent à l'étranger, et niait ensuite les avoir écrits — précaution nécessaire dans un pays où l'on était embastillé pour moins que cela." }],
    ["Candide contre l'optimisme", `Candide est dirigé contre l'optimisme, doctrine philosophique selon laquelle nous vivons dans le meilleur des mondes possibles et tout y est pour le mieux. Voltaire l'écrit après le tremblement de terre de Lisbonne de 1755, qui fit des dizaines de milliers de morts un jour de Toussaint : comment soutenir devant cela que tout est bien ?

Le procédé est implacable. Candide et son précepteur Pangloss traversent guerre, viol, esclavage, autodafé et naufrage, et Pangloss continue imperturbablement de démontrer que tout va pour le mieux. Le récit s'achève sur une formule devenue proverbe : il faut cultiver notre jardin. Ce n'est ni un appel au repli ni une conclusion optimiste, mais un renoncement à la métaphysique au profit de l'action limitée et concrète.`],
    ["Trois autres contes de Voltaire", `Micromégas met en scène un géant venu de l'étoile Sirius, haut de plusieurs lieues, qui visite la Terre accompagné d'un habitant de Saturne : le changement d'échelle réduit les hommes à des animalcules dont les guerres et les prétentions philosophiques paraissent dérisoires. C'est l'un des premiers récits de science-fiction philosophique.

Zadig suit les épreuves d'un sage babylonien que sa vertu même précipite dans le malheur, et pose la question de la providence. L'Ingénu prend un chemin inverse : un Huron arrive en France, découvre les institutions, la religion et la Bastille avec un regard neuf, et sa naïveté fait apparaître l'absurdité de ce qui nous semble naturel. C'est le procédé du regard étranger, dont Montesquieu avait donné le modèle dans Les Lettres persanes, roman épistolaire où deux Persans en voyage commentent la société française.`],
    ["Diderot, autrement", `Diderot pratique le genre avec plus de liberté formelle encore. Le Neveu de Rameau est un dialogue entre un philosophe et un parasite cynique, neveu du compositeur : ce dernier tient les propos les plus immoraux avec une lucidité qui désarme son interlocuteur. Le texte, resté inédit du vivant de l'auteur, fascinera Goethe puis Hegel.

Jacques le Fataliste joue avec les conventions du récit : le narrateur interrompt son histoire, prend le lecteur à partie, propose plusieurs suites possibles et refuse de conclure. Deux siècles avant le Nouveau Roman, c'est une machine à démonter le roman de l'intérieur. La Religieuse, enfin, quitte le jeu pour la dénonciation : le récit d'une jeune fille contrainte au couvent contre sa volonté est une charge directe contre les vocations forcées, dans un pays où l'on plaçait couramment ses filles au couvent pour éviter de doter plusieurs héritières.`],
  ],

  "li2-balzac-realisme": [
    ["Un projet d'ampleur inédite", `Balzac ne veut pas écrire des romans, mais faire concurrence à l'état civil : décrire une société entière, ses métiers, ses classes, ses provinces et ses passions. La Comédie humaine réunira près de cent œuvres, avec un plan raisonné — études de mœurs, études philosophiques, études analytiques.

Pour tenir cet ensemble, il invente un procédé que tout le roman moderne lui reprendra : le retour des personnages d'un livre à l'autre. Un comparse d'un roman devient le héros du suivant, un banquier croisé en passant réapparaît vingt ans plus tard, ruiné. Le lecteur qui suit l'ensemble finit par connaître ce monde comme une société réelle, avec ses réputations et ses souvenirs.`],
    ["Paris, la province, l'argent", `Le Père Goriot met en scène un ancien commerçant qui se dépouille de tout pour ses deux filles, lesquelles le laissent mourir seul dans une pension de famille. C'est dans ce roman que Rastignac, jeune provincial ambitieux, lance depuis le cimetière du Père-Lachaise son défi à Paris étendu sous ses pieds — scène devenue l'emblème de l'ambition sociale.

Illusions perdues raconte l'échec de ce parcours : un jeune poète d'Angoulême monte à Paris, découvre le journalisme, la corruption de la critique littéraire et la loi du marché, et rentre ruiné. Eugénie Grandet reste au contraire en province, avec un père avare dont l'obsession détruit la vie de sa fille. Partout, l'argent est le moteur, et Balzac en donne les chiffres exacts — rentes, dots, dettes — avec une précision de notaire.`],
    ["Le fantastique et le pacte", `La Peau de chagrin ajoute une dimension inattendue à cet édifice réaliste. Un jeune homme désespéré acquiert une peau magique qui exauce chacun de ses désirs, mais rétrécit à chaque vœu — et sa vie avec elle. Vouloir, c'est se consumer.

Le récit est fantastique, mais son sujet est celui de toute La Comédie humaine : l'énergie vitale se dépense, et le désir tue celui qui s'y livre. Balzac lui-même écrivait quinze heures par jour, soutenu par des quantités de café dont ses biographes ont fait un motif ; il est mort à cinquante et un ans.`],
    ["Autour de Balzac", `Stendhal, son aîné, publie Le Rouge et le Noir en 1830 : l'ascension d'un fils de charpentier qui, faute de pouvoir faire carrière dans l'armée sous la Restauration, choisit la soutane. Le titre oppose les deux voies. Son écriture sèche et rapide est à l'opposé de la profusion balzacienne, et il prédisait n'être compris qu'en 1935.

Flaubert défend un principe contraire à celui de Balzac : l'impersonnalité, l'auteur devant être dans son œuvre comme Dieu dans la création, présent partout et visible nulle part. Madame Bovary, roman d'une femme lassée de la vie provinciale et de son mari, lui vaut un procès en 1857 dont il sort acquitté. Maupassant, formé par Flaubert, publie Boule de Suif en 1880 et portera la nouvelle à sa perfection française.`],
  ],
  "li2-zola-naturalisme": [
    ["Un programme scientifique", `Zola ne se contente pas d'écrire des romans réalistes : il théorise. Dans Le Roman expérimental, publié en 1880, il propose d'appliquer au roman la méthode expérimentale que Claude Bernard venait de formuler pour la médecine — placer des personnages dans un milieu donné, avec une hérédité donnée, et observer ce qui se produit.

Le programme est intenable au sens strict, puisque le romancier décide de tout ce qu'il prétend observer, et Zola le savait. Mais il fonde une méthode de travail réelle : avant chaque roman, il mène de véritables enquêtes de terrain, descend dans une mine, suit les Halles la nuit, monte sur une locomotive, remplit des carnets de vocabulaire technique et de plans. C'est ce travail documentaire qui donne à ses livres leur densité.`,
      { image: "lit-zola", legende: "Émile Zola. Avant d'écrire « Germinal », il descendit dans une fosse d'Anzin et remplit des carnets entiers de notes techniques, de plans et de mots de métier." }],
    ["Vingt volumes, une famille", `Le cycle des Rougon-Macquart compte vingt romans, sous-titrés Histoire naturelle et sociale d'une famille sous le Second Empire. Chaque volume suit un membre de la famille dans un milieu différent, et l'ensemble balaie la société entière — paysans, ouvriers, boutiquiers, financiers, artistes, prêtres, prostituées.

L'hérédité y tient une place explicite : Zola dresse un arbre généalogique où se transmettent une tare nerveuse et l'alcoolisme, censés expliquer en partie les destins. C'est la part la plus datée de son projet, appuyée sur une science de son temps aujourd'hui abandonnée. Elle n'entame pas la force des romans, où le milieu social pèse en réalité bien davantage que le sang.`],
    ["Quatre mondes", `Germinal est consacré au monde de la mine : conditions de travail, grève, répression, et une lucidité rare sur la difficulté d'une action collective. Le titre annonce une germination — quelque chose lève sous la terre.

L'Assommoir décrit la déchéance d'une blanchisseuse par l'alcool, dans un langage qui emprunte au parler populaire jusque dans la narration : le procédé fit scandale des deux côtés, la bourgeoisie y voyant de la vulgarité et la gauche une insulte au peuple. Au Bonheur des Dames met en scène l'essor des grands magasins et la destruction du petit commerce, avec une fascination assumée pour la machine commerciale. La Bête humaine se déroule dans le monde des chemins de fer, où la locomotive devient un personnage. Le Ventre de Paris, enfin, est un roman des Halles, saturé de nourriture et d'odeurs.`],
    ["Le groupe, et sa dissolution", `Le naturalisme fut aussi une école. Les Soirées de Médan, recueil collectif de six nouvelles paru en 1880, en marque l'acte de naissance : Zola y publie aux côtés de cinq jeunes écrivains, dont Maupassant, qui y donne Boule de Suif — la meilleure du lot, et de loin.

Le groupe se défait rapidement. Dès 1884, Huysmans publie À rebours, roman sans intrigue où un aristocrate neurasthénique se retire du monde pour vivre parmi ses objets, ses parfums et ses lectures. C'est le contraire exact du programme naturaliste : ni milieu social, ni enquête, ni action. Le livre devient la bible du courant décadent, et Zola, qui l'avait accueilli avec inquiétude, y vit à juste titre la fin de son école.`],
  ],

  "li2-proust": [
    ["Sept volumes et une phrase", `À la recherche du temps perdu compte sept volumes, publiés de 1913 à 1927, les trois derniers après la mort de l'auteur. Le premier, Du côté de chez Swann, est refusé par plusieurs éditeurs — dont Gide pour la NRF, qui reconnaîtra plus tard son erreur — et paraît à compte d'auteur. Le deuxième, À l'ombre des jeunes filles en fleurs, obtient le prix Goncourt en 1919 et fait basculer la réputation de Proust.

La Recherche n'est pas un récit chronologique : elle suit le mouvement de la mémoire, avec ses retours, ses arrêts et ses dilatations. Une soirée peut occuper deux cents pages, plusieurs années tenir en une phrase. La longueur des périodes n'est pas une coquetterie : elle épouse le rythme d'une pensée qui se corrige et se précise en avançant.`,
      { image: "lit-proust", legende: "Marcel Proust. Reclus dans une chambre tapissée de liège, il a passé les quinze dernières années de sa vie à écrire et à réécrire un seul livre." }],
    ["La mémoire involontaire", `L'épisode le plus célèbre du livre tient en quelques pages : le narrateur trempe une madeleine dans du thé, et la sensation ressuscite intact un pan de son enfance à Combray, qu'aucun effort volontaire n'avait pu retrouver.

C'est ce que Proust appelle la mémoire involontaire : un souvenir ressuscité par une sensation, hors de tout effort et souvent contre lui. Elle s'oppose à la mémoire volontaire, qui ne restitue que des faits secs, sans la saveur du moment vécu. Le motif revient plusieurs fois dans l'œuvre — pavés inégaux, serviette empesée, bruit d'une cuillère — et fournit la clé de sa construction : ces expériences isolées finiront par révéler au narrateur ce qu'il doit écrire.`],
    ["L'art comme réponse", `Deux œuvres fictives traversent la Recherche. La sonate de Vinteuil, avec sa petite phrase musicale, accompagne l'amour de Swann pour Odette puis revient tout au long du livre. Elstir, peintre imaginaire inspiré des impressionnistes, apprend au narrateur à voir autrement : à peindre la mer comme si elle était terre et la terre comme si elle était mer, c'est-à-dire à restituer la sensation avant que l'intelligence ne la corrige.

Ces figures ne sont pas décoratives. Elles portent la thèse du livre : seul l'art permet de retrouver le temps perdu, parce qu'il fixe ce que la vie ne fait que traverser. Le dernier volume s'achève d'ailleurs sur la décision d'écrire l'œuvre que le lecteur vient de terminer — construction circulaire dont le lecteur ne mesure la portée qu'au tout dernier moment.`],
    ["Le monde et la fabrique", `L'affaire Dreyfus traverse la Recherche et sert de révélateur social : elle divise les salons, redistribue les fréquentations et fait apparaître les antisémitismes ordinaires derrière les politesses. Proust, dont la mère était juive, fut lui-même dreyfusard actif.

Sa méthode de travail est indissociable de l'œuvre. Il écrivait dans une chambre tapissée de liège, largement de nuit, et ne cessait d'ajouter à ses manuscrits des feuillets collés bout à bout, les paperoles, qui pouvaient atteindre plusieurs mètres dépliés. Le livre a grossi sans arrêt jusqu'à sa mort : la version de 1913 n'annonçait que trois volumes. C'est cette croissance ininterrompue, plus qu'un plan initial, qui explique la forme de l'ensemble.`],
  ],

  "li2-existentialisme": [
    ["Une formule et ses conséquences", `L'existentialisme sartrien tient dans une formule : l'existence précède l'essence. Il n'y a pas de nature humaine donnée d'avance, dont chacun serait une réalisation ; on existe d'abord, et l'on se définit ensuite par ce qu'on fait. Il en découle une liberté totale et, avec elle, une responsabilité écrasante — Sartre parle d'être condamné à être libre.

La Nausée, publié en 1938, met cette philosophie en fiction : un homme seul, dans une ville de province, éprouve devant les objets et son propre corps un dégoût qui est la découverte de la contingence — rien n'a de raison d'être là, pas même lui. Huis clos, pièce de 1944, enferme trois morts dans un salon et conclut que l'enfer, c'est les autres : non que les autres soient odieux, mais que notre existence est jugée par leur regard, dont rien ne nous délivre.`],
    ["Simone de Beauvoir", `Le Deuxième Sexe paraît en 1949 et applique cette philosophie à la condition féminine : on ne naît pas femme, on le devient. Ce que l'on prend pour une nature est le produit d'une éducation, d'institutions et d'attentes sociales. Le livre est violemment attaqué à sa sortie, y compris à gauche, et devient l'un des textes fondateurs du féminisme du siècle.

Les Mandarins, roman à clés sur les milieux intellectuels de l'après-guerre, obtient le Goncourt en 1954. Beauvoir y met en scène, sous des noms d'emprunt, les débats et les compromissions de son propre milieu — engagement politique, rapport au Parti communiste, place des femmes dans un cercle d'hommes qui se croient émancipés.`],
    ["Camus, l'absurde et la révolte", `Camus a toujours refusé l'étiquette d'existentialiste que la presse lui accolait. Sa réflexion part d'ailleurs : Le Mythe de Sisyphe, publié en 1942, pose la question du suicide comme seul problème philosophique sérieux, et répond par la conscience lucide de l'absurde — il faut imaginer Sisyphe heureux.

La Peste, en 1947, décrit une ville d'Oran frappée par une épidémie et fermée sur elle-même : chronique d'une catastrophe, roman sur l'occupation et sur toutes les formes de fléau, il vaut d'abord par ses personnages qui font leur métier sans héroïsme. Camus reçoit le prix Nobel de littérature en 1957, à quarante-quatre ans — l'un des plus jeunes lauréats.`],
    ["Écrire, est-ce agir", `L'Homme révolté, publié en 1951, provoque la rupture avec Sartre. Camus y critique les révolutions qui sacrifient des vies présentes à un avenir promis, et met en cause le totalitarisme soviétique que Sartre refusait alors de condamner frontalement. La polémique, publiée dans Les Temps modernes, met fin à leur amitié.

Le débat portait sur la littérature engagée, que Sartre définissait comme une écriture assumant sa responsabilité politique : l'écrivain est en situation, son silence même est une prise de position. Camus ne contestait pas l'engagement mais la subordination de la morale à l'efficacité historique. Soixante-dix ans plus tard, la question qu'ils s'opposaient n'a rien perdu : au nom de quoi accepte-t-on que des moyens injustes servent une fin juste ?`],
  ],

  "li2-litterature-germanique": [
    ["Goethe, ou soixante ans sur un livre", `Faust a occupé Goethe pendant près de soixante ans : il en écrit les premières scènes vers vingt ans et achève la seconde partie quelques mois avant sa mort, à quatre-vingt-deux ans. Le pacte du savant qui vend son âme contre la connaissance et la jouissance devient, sous sa plume, une somme sur l'ambition humaine — et un texte qu'aucune mise en scène ne joue intégralement.

Bien avant cela, en 1774, Les Souffrances du jeune Werther le rend célèbre dans toute l'Europe à vingt-cinq ans. Le roman épistolaire d'un jeune homme qui se suicide par amour déclenche une vague d'imitations : on s'habille en Werther, on écrit comme lui, et une série de suicides réels lui est attribuée — le premier cas documenté de ce que la sociologie appellera l'effet d'imitation médiatique.`],
    ["Avant le romantisme", `Le Sturm und Drang — tempête et élan — précède le romantisme allemand dans les années 1770 : un mouvement de jeunes auteurs qui revendiquent le génie, la passion et la nature contre les règles héritées du classicisme français. Goethe et Schiller y participent avant de s'en éloigner vers un classicisme allemand.

Le romantisme proprement dit suivra, avec sa fascination pour le Moyen Âge, le fantastique, le conte populaire et la nuit. C'est de ce terreau que sortent les recueils des frères Grimm, entrepris comme un travail philologique et non comme un livre pour enfants. Hoffmann von Fallersleben, philologue et poète, écrit en 1841 le Chant des Allemands, dont la troisième strophe est aujourd'hui l'hymne national.`],
    ["Le roman du déclin", `Thomas Mann publie à vingt-cinq ans Les Buddenbrook, qui suit sur quatre générations le déclin d'une famille de négociants de Lübeck : à mesure que la sensibilité artistique grandit dans la famille, l'aptitude aux affaires s'éteint. Le roman lui vaudra le Nobel.

La Montagne magique, en 1924, se déroule dans un sanatorium suisse où un jeune homme venu pour trois semaines reste sept ans. Le temps s'y dilate, les malades débattent de tout, et l'Europe d'avant 1914 s'y regarde sans se voir. Mann quittera l'Allemagne en 1933 et poursuivra son œuvre en exil, aux États-Unis.`],
    ["Kafka, l'inclassable", `Franz Kafka, né à Prague dans une famille juive de langue allemande, employé d'assurances toute sa vie, écrit la nuit et publie peu. Le Procès met en scène un homme arrêté un matin sans qu'on lui dise jamais de quoi il est accusé, et qui s'épuise dans une procédure sans juge accessible ni acte lisible. La Métamorphose s'ouvre sur un commis voyageur qui se réveille changé en insecte, et sur la réaction de sa famille — d'abord la gêne, puis le rejet.

Kafka demanda à son ami Max Brod de brûler ses manuscrits inédits. Brod refusa et les publia : la quasi-totalité de l'œuvre que nous lisons a donc été sauvée contre la volonté de son auteur. L'adjectif kafkaïen, formé sur son nom, désigne depuis toute situation absurde où l'individu se heurte à une machine impersonnelle.`],
    ["L'exil et la mémoire", `Stefan Zweig, Autrichien, écrivain le plus traduit de son temps, fuit le nazisme et écrit au Brésil Le Monde d'hier, souvenirs d'une Europe cosmopolite anéantie. Il se suicide avec sa femme en 1942, désespérant du retour de cette civilisation.

Après la guerre, Günter Grass publie Le Tambour, où un enfant décide à trois ans de cesser de grandir et traverse le nazisme du regard d'un nain au tambour. Le livre force l'Allemagne à regarder ce qu'elle préférait taire, et vaut à son auteur le Nobel en 1999. Grass révélera lui-même en 2006 son engagement adolescent dans la Waffen-SS, aveu tardif qui a rouvert le débat sur sa position morale de conscience de la nation.`],
  ],

  "li2-litterature-francophone": [
    ["Écrire en français, et pourquoi", `Écrire en français hors de France peut être un choix, un héritage colonial, ou les deux à la fois — et la question travaille les œuvres autant que leurs auteurs. Kateb Yacine disait du français qu'il était un butin de guerre.

Aimé Césaire, Martiniquais, publie en 1939 le Cahier d'un retour au pays natal, long poème où il forge avec Senghor et Damas la notion de négritude : revendiquer une identité noire là où l'assimilation exigeait de l'effacer. La démarche sera plus tard critiquée par ses propres héritiers, qui lui reprocheront de figer une essence.`],
    ["Après la négritude", `Édouard Glissant, Martiniquais lui aussi, propose une autre voie : plutôt qu'une identité racine, une identité relation. Sa notion de Tout-monde décrit un monde où les cultures se transforment au contact les unes des autres sans se dissoudre. Patrick Chamoiseau développe de son côté la créolité, qui revendique la langue et l'imaginaire créoles comme matériau littéraire à part entière.

Frantz Fanon, psychiatre martiniquais engagé dans la révolution algérienne, publie en 1961 Les Damnés de la terre, analyse de la violence coloniale et de ses effets psychiques qui deviendra une référence des mouvements de libération du monde entier.`],
    ["L'Afrique et le Maghreb", `Au Sénégal, Mariama Bâ publie Une si longue lettre, roman épistolaire sur la condition des femmes, la polygamie et le veuvage, qui reste l'un des textes africains les plus lus. Cheikh Hamidou Kane, avec L'Aventure ambiguë, met en scène un jeune Peul partagé entre l'école coranique et l'école française : le roman pose la question du prix à payer pour apprendre à vaincre sans avoir raison.

En Algérie, Kateb Yacine publie Nedjma en 1956, roman à la construction éclatée où quatre hommes tournent autour d'une même femme, figure de l'Algérie. Assia Djebar, romancière et cinéaste, consacre son œuvre à la voix des femmes algériennes et entre à l'Académie française en 2005 — première écrivaine du Maghreb à y siéger.`],
    ["Le Québec et l'Europe", `Gabrielle Roy publie en 1945 Bonheur d'occasion, qui décrit la vie d'un quartier ouvrier de Montréal pendant la guerre : c'est l'un des premiers grands romans urbains québécois, à rebours de la littérature du terroir qui dominait.

Michel Tremblay franchit une autre limite en 1968 avec Les Belles-Sœurs : il fait entrer le joual, parler populaire montréalais, sur la scène d'un théâtre institutionnel. Le scandale fut considérable — on y vit une insulte à la langue — et la pièce est aujourd'hui un classique. En Belgique, une tradition francophone distincte a produit Maeterlinck, prix Nobel en 1911, Simenon et ses centaines de romans, ou encore Amélie Nothomb.`],
  ],
  "li2-autobiographie": [
    ["Tout dire", `Les Confessions de Rousseau, publiées après sa mort, inaugurent l'autobiographie moderne par une prétention inédite : tout dire sur soi, y compris le déshonorant. Il y raconte des vols, des lâchetés, l'abandon de ses cinq enfants aux Enfants-Trouvés. Le pacte qu'il propose au lecteur est celui de la sincérité intégrale, et c'est cette exigence, plus que le récit lui-même, qui fonde le genre.

Le titre est emprunté à saint Augustin, dont les Confessions, treize siècles plus tôt, racontaient une conversion : l'aveu des fautes y servait à magnifier la grâce qui en avait délivré. Le déplacement est considérable — chez Rousseau, l'aveu ne mène plus à Dieu mais à la connaissance de soi.`],
    ["Mémoires de cour et d'outre-tombe", `Le duc de Saint-Simon laisse sur la cour de Louis XIV des mémoires d'une acuité féroce : plusieurs milliers de pages où chaque courtisan est peint en quelques lignes définitives. Il écrit pour l'avenir, sans publier de son vivant, et son texte reste la source la plus vivante sur Versailles — à condition de se rappeler qu'il règle aussi ses comptes.

Chateaubriand pousse le procédé jusqu'au titre : ses Mémoires d'outre-tombe ne devaient paraître qu'après sa mort, ce qui lui permettait de parler des vivants sans conséquence. Écrits sur quarante ans, ils traversent la Révolution, l'Empire, la Restauration, et mêlent l'histoire du siècle à celle d'un homme qui se voit finir avec un monde.`],
    ["Témoigner", `Le Journal d'Anne Frank appartient à une autre catégorie : ce n'est pas une œuvre rétrospective mais un journal tenu au présent par une adolescente cachée à Amsterdam pendant deux ans. Elle le retravaillait elle-même en vue d'une publication, ce qu'on oublie souvent. Elle meurt à Bergen-Belsen à quinze ans ; son père, seul survivant de la famille, publie le texte en 1947.

Primo Levi, chimiste italien déporté à Auschwitz, publie Si c'est un homme en 1947 — refusé par les grands éditeurs, il ne connaîtra le succès qu'une décennie plus tard. Son parti pris est celui de l'analyse froide : décrire le fonctionnement du camp, la dégradation méthodique de l'humain, sans imprécation ni pathos. C'est ce qui en fait l'un des témoignages les plus indiscutables du siècle.`],
    ["Se raconter aujourd'hui", `Sartre publie Les Mots en 1964, récit de son enfance et de son entrée en littérature, où il démonte ironiquement la vocation dont il avait fait sa vie. Il refuse le Nobel la même année.

Annie Ernaux transforme le genre : elle fait de sa vie une enquête sociologique, en écrivant sur son milieu d'origine, son ascension par l'école, l'avortement, la honte sociale, avec une langue plate revendiquée et une distance qui exclut la confidence. Serge Doubrovsky, lui, forge en 1977 le terme d'autofiction pour désigner un récit où l'auteur porte son nom mais assume une part de fiction. Georges Perec, enfin, dans W ou le Souvenir d'enfance, alterne un récit d'enfance lacunaire et une fiction insulaire glaçante : les deux textes ne se rejoignent jamais explicitement, et c'est ce blanc entre eux qui dit l'essentiel — la disparition de ses parents dans la guerre.`],
  ],

  "li2-oulipo-experiences": [
    ["Un atelier, pas un mouvement", `L'Oulipo — Ouvroir de littérature potentielle — est fondé en 1960 par Raymond Queneau et le mathématicien François Le Lionnais. Ce n'est pas un mouvement littéraire mais un atelier de recherche : ses membres inventent et testent des contraintes formelles, qu'ils mettent à disposition de qui veut s'en servir. Le groupe ne publie pas de manifeste et n'exclut personne — on n'en démissionne pas, on n'en est excusé que par décès.

Le principe est contre-intuitif : la contrainte n'appauvrit pas, elle engendre. Obligé de contourner un obstacle, l'auteur trouve des tournures et des images auxquelles il n'aurait jamais pensé. C'est l'inverse exact de l'écriture automatique des surréalistes, qui cherchait à libérer.`],
    ["Perec et l'exploit", `Georges Perec écrit La Disparition, roman de trois cents pages sans une seule lettre e — un lipogramme, c'est-à-dire un texte qui s'interdit une ou plusieurs lettres. La performance n'est pas gratuite : le e absent figure le manque, et le roman parle d'une disparition dont personne ne peut prononcer le nom. Plusieurs premiers lecteurs ne remarquèrent rien.

La Vie mode d'emploi est construite sur le plan d'un immeuble parisien : chaque chapitre visite une pièce, et l'ordre des chapitres suit le parcours d'un cavalier sur un échiquier de cent cases. Des dizaines d'autres contraintes gouvernent la répartition des objets et des thèmes. Le lecteur peut tout ignorer : le livre se lit d'abord comme une accumulation d'histoires.`],
    ["Queneau et les combinaisons", `Cent mille milliards de poèmes est un livre de dix sonnets dont chaque vers est imprimé sur une bande découpée : le lecteur peut combiner librement les vers de même rang, ce qui donne dix puissance quatorze poèmes différents, tous grammaticalement corrects. Queneau calculait qu'il faudrait plusieurs centaines de millions d'années pour tous les lire.

Exercices de style raconte quatre-vingt-dix-neuf fois la même scène — un homme aperçu dans un bus, puis revu deux heures plus tard — dans quatre-vingt-dix-neuf manières différentes : en alexandrins, en argot, au passé simple, sous forme de télégramme, de rêve, d'analyse grammaticale. C'est le meilleur cours de style jamais écrit, et il tient en cent pages. Italo Calvino, membre étranger de l'Oulipo, applique l'esprit du groupe au roman avec Si par une nuit d'hiver un voyageur, livre composé de dix débuts de romans interrompus.`],
    ["Le Nouveau Roman", `Parallèlement, un autre groupe déconstruit le récit. Alain Robbe-Grillet formule son programme dans Pour un nouveau roman : plus d'intrigue, plus de personnage psychologique, plus d'auteur omniscient — l'objet décrit avec une précision maniaque remplace le sens.

Nathalie Sarraute explore une autre direction avec ce qu'elle nomme les tropismes : les mouvements infimes de la conscience, les micro-réactions qui précèdent la parole et que le roman classique ignore. Claude Simon, enfin, reçoit le Nobel en 1985 pour une œuvre où mémoire, guerre et phrases interminables composent un flux sans chapitre. L'Oulipo et le Nouveau Roman partagent une conviction : la forme n'est pas l'habillage du sujet, elle est le sujet.`],
  ],
  "li2-lecture-publique": [
    ["Tout garder", `La Bibliothèque nationale de France conserve, au titre du dépôt légal, un exemplaire de chaque document publié en France : livres, périodiques, partitions, cartes, affiches, disques, et depuis 2006 les sites web français. L'obligation remonte à une ordonnance de François Ier de 1537, ce qui en fait l'un des plus anciens dispositifs de conservation au monde.

Cette exhaustivité a un prix : plusieurs dizaines de kilomètres de rayonnages supplémentaires par décennie, et une politique de conservation qui doit arbitrer entre le papier acide du XIXe siècle, les supports magnétiques illisibles et les formats numériques obsolètes. Le dépôt légal ne garantit pas la lecture, seulement la survie du support.`],
    ["Une longue histoire", `La bibliothèque d'Alexandrie reste la plus célèbre du monde méditerranéen : fondée au IIIe siècle avant notre ère par les Ptolémées, elle visait à rassembler tous les livres du monde connu, avec une méthode brutale — on saisissait les rouleaux des navires en escale pour les copier. Sa destruction ne fut pas un événement unique mais une lente dégradation sur plusieurs siècles.

Les incunables, livres imprimés avant 1501, sont aujourd'hui recensés à environ trente mille éditions dans le monde, pour quelques centaines de milliers d'exemplaires conservés. En France, une bibliothèque municipale classée conserve des fonds patrimoniaux — manuscrits, incunables, fonds anciens — sous contrôle scientifique de l'État, souvent hérités des confiscations révolutionnaires.`],
    ["Qui fait lire", `Le critique littéraire analyse et évalue publiquement des œuvres : son rôle est moins de juger que de trier dans une production que personne ne peut embrasser. En France, la rentrée littéraire concentre à la fin de l'été la publication de plusieurs centaines de romans en quelques semaines — un phénomène sans équivalent ailleurs, qui sature la critique et condamne l'immense majorité des titres à passer inaperçus.

La télévision a joué un rôle décisif : l'émission Apostrophes, animée par Bernard Pivot de 1975 à 1990, faisait vendre des dizaines de milliers d'exemplaires en une soirée. Aucune émission n'a depuis retrouvé ce pouvoir de prescription, désormais fragmenté entre libraires, réseaux sociaux et clubs de lecture — ces derniers, groupes se réunissant pour discuter d'ouvrages lus en commun, ayant connu un regain considérable.`],
    ["Prêter, et libérer", `Le prêt numérique en bibliothèque donne un accès temporaire à un livre numérique, avec des conditions négociées avec les éditeurs : nombre de prêts simultanés, durée, nombre total d'emprunts avant réachat. Le modèle reproduit artificiellement la rareté d'un objet physique, ce qui explique qu'un fichier puisse être indisponible parce qu'il est emprunté.

À l'autre bout, le domaine public rassemble les œuvres dont les droits patrimoniaux ont expiré — en France, soixante-dix ans après la mort de l'auteur. Elles peuvent être librement rééditées, traduites, numérisées et adaptées. C'est ce qui permet à des projets bénévoles de mettre en ligne des dizaines de milliers de textes, et ce qui fait de chaque 1er janvier une date suivie par les bibliothécaires : celle où une nouvelle promotion d'auteurs devient libre.`],
  ],

  "li2-prix-litteraires": [
    ["Le Nobel", `Le prix Nobel de littérature est décerné chaque année à Stockholm par l'Académie suédoise, selon le testament d'Alfred Nobel qui demandait de récompenser une œuvre de tendance idéaliste — formulation vague dont l'interprétation a beaucoup varié. Il distingue une œuvre entière, non un livre.

Le premier lauréat, en 1901, fut le Français Sully Prudhomme, choix aussitôt contesté par des écrivains scandinaves qui estimaient que Tolstoï le méritait davantage. Le palmarès a depuis accumulé les absences remarquables — Tolstoï, Proust, Joyce, Woolf, Borges — ce qui rappelle qu'un prix reflète autant l'état d'un jury que celui de la littérature.`],
    ["Les prix français d'automne", `Le prix Goncourt est décerné par un jury de dix membres réunis chez Drouant, restaurant parisien. Sa dotation est symbolique — dix euros — mais son effet commercial est considérable : il multiplie souvent les ventes par dix ou davantage, et assure au lauréat plusieurs centaines de milliers d'exemplaires.

Autour de lui gravitent des prix nés en réaction. Le Renaudot est décerné le même jour, par des journalistes qui attendaient dans le même restaurant que le Goncourt se décide. Le Femina, créé en 1904 par des collaboratrices d'une revue, est décerné par un jury exclusivement féminin, en réponse au machisme du Goncourt de l'époque. Le Médicis, plus récent, récompense un auteur dont la notoriété ne correspond pas encore au talent — formulation qui en dit long sur les positions que chaque prix cherche à occuper.`],
    ["Ailleurs", `Le Booker Prize récompense un roman de langue anglaise publié au Royaume-Uni ; son ouverture aux auteurs américains en 2014 a fait débat. Le Pulitzer, américain, distingue à la fois le journalisme et la littérature, avec des catégories distinctes — c'est l'un des rares prix à honorer les deux.

Le prix Hugo, en science-fiction, se distingue par son mode d'attribution : il est voté par les lecteurs inscrits à la convention mondiale de science-fiction, et non par un jury d'experts. Cette légitimité populaire lui a valu, dans les années 2010, une tentative organisée de noyautage des votes par des groupes militants — épisode qui a montré la fragilité de tout système de vote ouvert.`],
    ["Ce qu'un prix produit", `Un grand prix littéraire ne récompense pas seulement : il fabrique. Il détermine ce qui sera en pile chez les libraires, traduit à l'étranger, étudié en classe et disponible en poche dans dix ans. Un même livre, primé ou non, ne connaît pas la même postérité.

Cette puissance explique la surveillance dont les jurys font l'objet — conflits d'intérêts entre jurés et maisons d'édition, rotation des maisons couronnées, absence de renouvellement des membres. Plusieurs réformes ont limité les cumuls, sans supprimer le fait central : dans un pays qui publie des centaines de romans par saison, quelques dizaines de personnes décident de ce qui sera lu.`],
  ],

  "li3-montaigne-moralistes": [
    ["Essayer sa propre pensée", `Le mot essai, chez Montaigne, n'a pas le sens d'exercice scolaire : c'est une mise à l'épreuve de sa propre pensée. Il ne démontre pas, il examine — reprend un jugement, le retourne, l'abandonne, y revient dix ans plus tard en ajoutant une couche au texte sans supprimer la précédente. Les Essais sont ainsi un livre où l'auteur se contredit, et l'assume.

Sa devise, gravée dans sa librairie, est une question : que sais-je ? Ce scepticisme n'est pas une pose. Montaigne écrit dans un pays déchiré par les guerres de Religion, où l'on tue pour des certitudes ; suspendre son jugement devient une position morale autant qu'intellectuelle. Son ami Étienne de La Boétie, mort jeune, avait écrit dans le même contexte le Discours de la servitude volontaire, qui pose une question demeurée sans réponse satisfaisante : pourquoi tant d'hommes obéissent-ils à un seul ?`],
    ["Pascal", `Les Pensées de Pascal sont des fragments d'une apologie du christianisme restée inachevée : à sa mort, il laisse des centaines de morceaux de papier, dont certains classés en liasses. Toutes les éditions que nous lisons sont donc des reconstructions, et leur ordre est une décision d'éditeur.

L'image du roseau pensant résume sa position : l'homme est le plus faible des êtres, qu'une goutte d'eau suffit à tuer, mais il le sait — et cette conscience fait sa grandeur. Pascal développe parallèlement une analyse du divertissement : nous ne supportons pas de rester en repos dans une chambre, et toute notre agitation sert à ne pas penser à notre condition. C'est l'un des textes les plus durs et les plus lucides de la langue française.`],
    ["Démonter les vertus", `La Rochefoucauld pratique la maxime : une formule brève qui dévoile l'amour-propre derrière les vertus apparentes. Nos vertus ne sont, écrit-il, que des vices déguisés. La forme est aussi un argument — la brièveté interdit la nuance et laisse le lecteur seul avec l'aiguillon.

La Bruyère procède autrement dans Les Caractères : il peint des types sociaux, avec noms d'emprunt et détails concrets, ce qui fit lire son livre comme un jeu de devinettes par la cour. Chamfort, un siècle plus tard, pratique la maxime et l'anecdote avec une amertume plus violente encore, à la veille d'une Révolution qu'il soutiendra avant d'en être victime.`],
    ["Décrire, ne pas prêcher", `On parle de moralistes plutôt que de philosophes parce qu'ils décrivent les mœurs sans construire de système : pas de traité, pas de déduction, mais des observations, des portraits et des formules. Le mot est trompeur en français moderne — ils ne prêchent pas la morale, ils l'observent à l'œuvre.

Leur objet commun est l'idéal social de leur temps, l'honnête homme : un homme cultivé sans pédanterie, capable de parler de tout sans se prévaloir de rien, agréable en société et mesuré en tout. C'est précisément cet idéal que les moralistes examinent — et sous lequel ils trouvent, presque toujours, l'intérêt et la vanité.`],
  ],

  "li3-fables-lafontaine": [
    ["Emprunter les sujets, inventer la forme", `La Fontaine a publié environ deux cent quarante fables, en deux recueils principaux, sur vingt-cinq ans. Il emprunte presque toutes ses intrigues : à Ésope, fabuliste grec, à Phèdre, son adaptateur latin, et à des sources orientales — indiennes et persanes — qui commençaient à être traduites en français.

Son invention est ailleurs, dans la forme. Le vers libre, qui alterne mètres longs et courts au gré du récit, lui permet de raconter avec une rapidité inconnue de ses modèles ; le dialogue, la chute, la variation de ton font le reste. Là où Ésope donne un canevas de quelques lignes et une morale, La Fontaine écrit une petite comédie.`],
    ["Les grandes fables et leurs leçons", `Quatre fables suffisent à montrer l'étendue du registre. La Cigale et la Fourmi oppose prévoyance et insouciance, sans que le texte ne tranche aussi nettement qu'on le croit — la fourmi y est décrite comme n'étant pas prêteuse, et c'est son moindre défaut. Le Corbeau et le Renard démonte le mécanisme de la flatterie, et conclut par une leçon qui vaut bien un fromage.

Le Loup et l'Agneau s'ouvre sur la formule la plus citée de tout le recueil, sur la raison du plus fort toujours la meilleure, et raconte un procès truqué dont l'issue était fixée d'avance. Le Chêne et le Roseau montre la souplesse l'emporter sur la rigidité, dans une fable dont la construction imite le mouvement du vent.`],
    ["Une critique protégée", `Les fables mettent en scène des animaux parce que le détour animalier permet de critiquer sans nommer. Les Animaux malades de la peste en donne la démonstration : devant un fléau, la cour cherche un coupable, le lion et les grands se pardonnent leurs crimes, et c'est l'âne qui a brouté un peu d'herbe qu'on immole. Selon que vous serez puissant ou misérable, conclut la fable, les jugements de cour vous rendront blanc ou noir.

Cette prudence n'était pas superflue. Le premier recueil est dédié au Dauphin, fils de Louis XIV, alors âgé de six ans : dédier au futur roi une leçon sur l'injustice de la cour est un geste habile autant qu'audacieux.`],
    ["Un poète dans la disgrâce", `La Fontaine avait pour protecteur Nicolas Fouquet, surintendant des finances, dont la chute en 1661 fut brutale : arrêté sur ordre de Louis XIV, jugé, condamné à la prison à vie. Presque tous ses obligés se turent. La Fontaine, lui, écrivit une élégie pour demander sa grâce.

Ce courage lui coûta la faveur royale, et il ne fut élu à l'Académie française qu'en 1684, le roi ayant longtemps fait obstacle. Il vécut de protections successives, chez des femmes de la haute société, sans jamais posséder de quoi vivre. Ses fables, lues aujourd'hui comme des textes pour enfants, ont été écrites par un homme qui connaissait précisément le prix de la faveur et de la disgrâce.`],
  ],
  "li3-rousseau-lumieres": [
    ["Un homme des Lumières contre les Lumières", `Rousseau est un homme des Lumières qui en conteste plusieurs présupposés — ce qui explique à la fois son influence et sa solitude. En 1750, son premier discours répond à une question d'académie en soutenant que le progrès des sciences et des arts a corrompu les mœurs, thèse exactement inverse de celle qu'on attendait. Le texte le rend célèbre du jour au lendemain.

Il ne dit pas qu'il faut revenir aux cavernes, contresens répandu. Il soutient que le raffinement d'une civilisation ne produit pas mécaniquement la vertu, et que la culture peut servir à masquer les inégalités plutôt qu'à les réduire. C'est une critique interne du progrès, formulée par quelqu'un qui y croit assez pour s'en inquiéter.`],
    ["L'état de nature et l'inégalité", `L'état de nature, chez Rousseau, n'est pas une période historique mais une hypothèse méthodologique : imaginons l'homme avant toute société, et voyons ce qui, dans ce que nous sommes, vient de la nature et ce qui vient des institutions. Il le dit lui-même — il s'agit d'écarter les faits.

De cette hypothèse sort sa thèse sur l'origine de l'inégalité : elle naît avec la propriété et la vie sociale. Le premier qui, ayant enclos un terrain, s'avisa de dire ceci est à moi et trouva des gens assez simples pour le croire, fut le vrai fondateur de la société civile — phrase qui fera le tour de l'Europe et nourrira deux siècles de pensée politique.`],
    ["Le Contrat social", `La thèse centrale du Contrat social est que la souveraineté appartient au peuple, qu'elle est inaliénable et indivisible : on ne peut ni la vendre, ni la déléguer durablement à un roi ou à des représentants. C'est une rupture avec toute la tradition monarchique et avec les modèles anglais admirés par Montesquieu et Voltaire.

La volonté générale est la notion la plus délicate du livre : c'est la volonté du corps politique orientée vers l'intérêt commun, distincte de la somme des intérêts particuliers. Elle a été lue comme le fondement de la démocratie moderne et, par d'autres, comme la matrice d'un pouvoir qui prétend savoir mieux que les citoyens ce qu'ils veulent. Le débat n'est pas clos, et Rousseau lui-même reconnaissait la difficulté.`],
    ["Éduquer, aimer, se confesser", `Émile expose un projet éducatif qui respecte les étapes du développement de l'enfant : ne rien enseigner avant que l'âge ne le permette, apprendre par l'expérience plutôt que par les livres, et différer l'instruction morale. Le livre a durablement marqué la pédagogie — et contient au dernier chapitre une conception de l'éducation des filles entièrement subordonnée à celle des garçons, que ses lectrices ont très tôt contestée.

Julie ou la Nouvelle Héloïse, roman épistolaire de 1761, connaît un succès sans précédent : on pleure en le lisant, on écrit à l'auteur pour savoir si Julie a existé. Rousseau finit par se raconter lui-même, dans les Confessions puis dans Les Rêveries du promeneur solitaire, restées inachevées à sa mort. Brouillé successivement avec Voltaire, Diderot et Hume, il vécut ses dernières années dans un isolement qu'il jugeait persécuté. Les révolutionnaires de 1789 se réclameront massivement de lui.`],
  ],

  "li3-symbolisme-decadence": [
    ["Suggérer au lieu de nommer", `Le symbolisme cherche à suggérer l'idée par l'image plutôt qu'à la décrire. Son point de départ est un sonnet de Baudelaire, Correspondances, qui pose que les parfums, les couleurs et les sons se répondent : le monde est une forêt de symboles, et le poète celui qui déchiffre ces analogies.

Cette conception fonde la synesthésie poétique, association de sensations relevant de sens différents — un parfum vert, une couleur criarde. Jean Moréas donne au mouvement son nom et son manifeste en 1886, dans un article de journal ; comme souvent, le texte théorique arrive après les œuvres qu'il prétend fonder.`],
    ["Verlaine et Rimbaud", `Verlaine énonce son programme dans un Art poétique qui commence par une exigence : de la musique avant toute chose. Il privilégie les vers impairs, les rimes atténuées, les nuances plutôt que la couleur, et une syntaxe qui laisse le sens flotter.

Rimbaud va beaucoup plus loin. Dans les lettres dites du voyant, écrites à dix-sept ans, il réclame un long, immense et raisonné dérèglement de tous les sens : le poète doit se faire voyant pour atteindre l'inconnu, quitte à s'y détruire. Les Illuminations, composées de poèmes en prose et de vers libres, poussent la langue française à un point de rupture — puis il cesse d'écrire avant vingt et un ans et part faire du commerce en Afrique.`],
    ["Mallarmé", `Stéphane Mallarmé refuse la description : nommer un objet, dit-il, c'est supprimer les trois quarts de la jouissance du poème, qui est faite de deviner peu à peu. Il veut céder l'initiative aux mots, c'est-à-dire laisser leurs sonorités et leurs relations produire le sens plutôt que de les mettre au service d'une intention préalable.

Ses poèmes, d'une difficulté redoutable, ont fait de lui le maître discret de toute la poésie moderne — ses mardis, réunions hebdomadaires chez lui rue de Rome, ont formé une génération entière. Son dernier texte, Un coup de dés jamais n'abolira le hasard, éclate la phrase sur la double page en variant les corps typographiques : la page devient un espace.`],
    ["La fin de siècle", `Parallèlement au symbolisme se développe la décadence, dont À rebours de Huysmans est le bréviaire : un aristocrate neurasthénique se retire du monde et organise sa vie autour de sensations rares — parfums, pierreries, livres, une tortue incrustée de gemmes. Le roman rompt avec le naturalisme dont son auteur venait, et fournit à toute une génération son catalogue de raffinements.

Le mouvement dépasse la France. Le Belge Maurice Maeterlinck écrit Pelléas et Mélisande, drame de la suggestion et du non-dit que Debussy mettra en musique, et recevra le Nobel en 1911. Villiers de L'Isle-Adam, avec L'Ève future, met en scène une créature artificielle construite par Edison pour remplacer une femme décevante — c'est là qu'apparaît, dans son sens moderne, le mot andréide, ancêtre de notre androïde.`],
  ],
  "li3-theatre-xxe": [
    ["Le coup d'envoi", `Le 10 décembre 1896, Ubu roi d'Alfred Jarry s'ouvre sur un mot de cinq lettres qui déclenche un tumulte de quinze minutes dans la salle. La pièce, écrite à l'origine par un lycéen pour se moquer d'un professeur de physique, met en scène un tyran grotesque, lâche et vorace, dans une Pologne de fantaisie.

Le scandale n'est pas seulement verbal : la pièce refuse la psychologie, la vraisemblance et la mesure, et annonce presque tout le théâtre du siècle à venir — le dadaïsme, le surréalisme, l'absurde. Yeats, présent dans la salle, comprit ce soir-là qu'une époque s'achevait.`],
    ["Interroger le théâtre lui-même", `Luigi Pirandello, Italien, met en scène en 1921 six personnages en quête d'auteur : des personnages abandonnés par leur créateur font irruption pendant une répétition et exigent qu'on joue leur histoire. La pièce démonte devant le public la frontière entre la scène et la vie, entre l'acteur et le rôle.

En France, l'entre-deux-guerres voit le mythe grec servir à parler du présent. Jean Giraudoux écrit en 1935 La guerre de Troie n'aura pas lieu, où deux camps tentent d'éviter un conflit que tout le monde sait inévitable — quatre ans avant 1939. Anouilh reprend Antigone en 1944, sous l'Occupation : la pièce fut applaudie à la fois par des résistants qui y voyaient le refus et par des collaborateurs qui approuvaient Créon, ce qui dit assez son ambiguïté calculée.`],
    ["L'absurde et la cérémonie", `Eugène Ionesco part d'un manuel de conversation anglaise pour écrire La Cantatrice chauve, où le langage tourne à vide et où les répliques cessent de communiquer. Rhinocéros, plus tard, raconte la transformation progressive de toute une ville en rhinocéros : c'est une parabole sur les adhésions collectives et le confort de suivre.

Jean Genet suit une autre voie. Dans Les Bonnes, deux domestiques rejouent chaque soir en l'absence de leur patronne un cérémonial où l'une joue la maîtresse et l'autre la servante, jusqu'au meurtre rituel. Le théâtre y devient une machine à faire tourner les rôles sociaux, et la représentation elle-même est le sujet.`],
    ["Le metteur en scène devient auteur", `Le XXe siècle voit le metteur en scène devenir l'auteur du spectacle : jusque-là, on jouait un texte ; désormais, on propose une lecture, avec sa scénographie, son rythme et son parti pris. Un même texte peut être monté de dix façons incompatibles, et c'est le nom du metteur en scène qui figure en tête de l'affiche.

Bertolt Brecht théorise le théâtre épique et la distanciation : couper l'illusion, montrer que l'on montre, empêcher le spectateur de s'identifier pour qu'il juge. En France, Ariane Mnouchkine fonde en 1964 le Théâtre du Soleil, troupe qui pratique la création collective — les spectacles y sont élaborés par le groupe à partir d'improvisations, avec des salaires égaux pour tous. Aujourd'hui, Yasmina Reza est l'une des dramaturges françaises les plus jouées dans le monde, et le théâtre documentaire construit des spectacles à partir de matériaux réels : enquêtes, procès-verbaux, témoignages enregistrés.`],
  ],

  "li3-roman-contemporain": [
    ["Le Nobel de 2014", `Patrick Modiano reçoit le prix Nobel de littérature en 2014. Son œuvre, une trentaine de romans courts, tourne obstinément autour du même noyau : la mémoire trouée de l'Occupation et l'identité incertaine. Ses narrateurs cherchent des adresses disparues, consultent de vieux annuaires, croisent des témoins qui ne se souviennent plus.

Ce ressassement n'est pas une limite mais une méthode : chaque livre est une nouvelle tentative d'approcher ce qui ne se laisse pas reconstituer. Dora Bruder, en 1997, en est le cas le plus net — parti d'un avis de recherche paru dans un journal de 1941, Modiano tente de retracer la vie d'une adolescente juive disparue, et bute sur ce que les archives ne diront jamais.`],
    ["Le roman face à l'histoire", `Une génération d'écrivains a repris l'histoire du XXe siècle par la fiction. Jonathan Littell publie en 2006 Les Bienveillantes, roman de neuf cents pages écrit du point de vue d'un officier SS cultivé — le procédé, très discuté, oblige le lecteur à voir par les yeux d'un bourreau. Le livre obtient le Goncourt.

Laurent Binet raconte dans HHhH l'attentat contre Reinhard Heydrich à Prague, mais en montrant en même temps ses propres doutes d'écrivain : peut-on inventer un dialogue quand on parle de faits réels ? Éric Vuillard obtient le Goncourt 2017 pour L'Ordre du jour, récit bref d'une réunion d'industriels allemands en 1933 venus financer le parti nazi — la grande histoire prise par un détail administratif.`],
    ["Écrire le réel", `La tendance la plus marquée du roman français contemporain est un retour du récit du réel et de l'enquête. Annie Ernaux explore la mémoire familiale et sociale en refusant la fiction : ses livres traitent l'expérience personnelle comme un matériau sociologique, avec une langue volontairement plate.

Emmanuel Carrère brouille systématiquement les frontières entre enquête, biographie et récit de soi : il écrit sur un imposteur meurtrier, sur un écrivain russe, sur les débuts du christianisme, et s'inclut toujours dans le récit en montrant sa position d'enquêteur. Cette hybridation est devenue si courante qu'elle constitue aujourd'hui une manière française reconnaissable.`],
    ["Les autres voies", `Michel Houellebecq occupe une place à part : ses romans sur la solitude contemporaine, le désir et l'épuisement des sociétés occidentales suscitent un débat public à chaque parution, souvent davantage sur les thèses prêtées à l'auteur que sur les livres.

À côté de ces veines, le roman français continue de produire des objets inclassables : L'Anomalie, Goncourt 2020, mêle thriller, science-fiction et réflexion sur le double, avec un avion qui atterrit deux fois à quelques mois d'écart avec les mêmes passagers. Son succès — plus d'un million d'exemplaires — a rappelé que la frontière entre littérature dite blanche et littératures de genre est devenue poreuse, en France plus tardivement qu'ailleurs.`],
  ],
};
