/** Inventions et technologie, premier lot — les cours. */
import type { LotCours } from "../commun";

export const COURS_SCIENCES_TECH: LotCours = {
  "st-informatique-fondements": [
    ["Deux états, et tout le reste", `Un ordinateur ne calcule qu'avec deux états, notés zéro et un : toute l'informatique en découle. Le binaire n'a pas été choisi par élégance mathématique mais par nécessité physique — il est bien plus simple de distinguer deux niveaux de tension que dix. Un octet regroupe huit bits, soit deux cent cinquante-six valeurs possibles, ce qui suffisait à coder un caractère dans les premiers systèmes.

Les fondations théoriques précèdent les machines. Ada Lovelace écrit dans les années 1840, pour la machine analytique de Babbage jamais construite, ce qui est tenu pour le premier programme : elle est aussi la première à comprendre qu'une telle machine pourrait manipuler autre chose que des nombres.`],
    ["Les modèles fondateurs", `En 1936, Alan Turing formalise un modèle théorique de calcul — une machine abstraite lisant et écrivant sur un ruban — qui définit ce qui est calculable et ce qui ne l'est pas. Le résultat est négatif autant que fondateur : certains problèmes n'admettent aucun algorithme.

En 1945, l'architecture décrite par von Neumann stocke le programme et les données dans la même mémoire : c'est ce qui permet à un ordinateur d'être polyvalent, puisqu'il suffit de changer le contenu de la mémoire pour changer de tâche. Trois ans plus tard, Claude Shannon fonde la théorie de l'information en donnant une mesure mathématique de la quantité d'information, indépendante de son sens.`],
    ["Faire tourner les machines", `Un compilateur traduit un code source, écrit dans un langage lisible par un humain, en langage machine exécutable par le processeur. Un système d'exploitation gère le matériel — mémoire, disques, périphériques — et permet aux autres programmes de s'exécuter sans connaître les détails de la machine.

La complexité algorithmique mesure les ressources consommées par un algorithme selon la taille des données : c'est elle qui décide si un programme reste utilisable quand le volume grandit. Un algorithme deux fois plus rapide sur de petites données peut être inutilisable sur de grandes. Quant à la loi de Moore, formulée en 1965, elle observait que le nombre de transistors d'une puce doublait environ tous les deux ans : ce n'est pas une loi physique mais une prévision d'industriel, longtemps auto-réalisatrice, aujourd'hui essoufflée.`],
  ],

  "st-internet-reseaux": [
    ["Le réseau et ses services", `Internet est le réseau ; le Web n'est qu'un des services qui circulent dessus, au même titre que le courrier électronique ou la messagerie instantanée. La confusion est si répandue qu'elle brouille la compréhension du reste.

Internet descend d'ARPANET, réseau financé par l'agence de recherche du département américain de la Défense à la fin des années 1960, conçu pour relier des centres de recherche. Le Web, lui, est inventé en 1989 par Tim Berners-Lee au CERN : il combine des adresses uniformes, un protocole de transfert et un langage de description de pages, et il le publie sans brevet.`],
    ["Comment circule une donnée", `L'information est découpée en paquets. Le protocole IP les achemine entre machines identifiées par une adresse IP, identifiant numérique attribué à chaque équipement connecté. Chaque paquet peut emprunter une route différente et être réassemblé à l'arrivée : c'est ce qui rend le réseau robuste.

Comme les adresses numériques sont impraticables pour un humain, le système DNS traduit un nom de domaine en adresse IP : c'est l'annuaire du réseau, et sa panne suffit à rendre Internet apparemment inaccessible. Le s de https signifie que la connexion est chiffrée, ce qui empêche un tiers de lire ou de modifier ce qui transite.`],
    ["Protéger et gouverner", `Un VPN établit un tunnel chiffré entre un appareil et un serveur distant : le fournisseur d'accès ne voit plus la destination, mais l'opérateur du VPN, lui, la voit — la protection déplace la confiance, elle ne la supprime pas. Le chiffrement de bout en bout va plus loin : seuls l'expéditeur et le destinataire peuvent lire le message, le service qui l'achemine ne le peut pas.

La neutralité du net est un principe de gouvernance : les opérateurs ne doivent pas discriminer les flux selon leur origine, leur destination ou leur contenu. Inscrite dans le droit européen en 2015, elle vise à empêcher qu'un fournisseur d'accès favorise ses propres services ou ceux qui le rémunèrent.`],
  ],

  "st-transports": [
    ["La vapeur et le rail", `James Watt met au point dans les années 1760 une machine à vapeur réellement efficace, en ajoutant un condenseur séparé qui évite de refroidir le cylindre à chaque cycle. Le rendement change d'ordre de grandeur, et la machine cesse d'être cantonnée au pompage des mines.

Le chemin de fer qui en découle impose une transformation inattendue : l'unification de l'heure. Avant lui, chaque ville vivait à son heure solaire, et un horaire de train n'aurait eu aucun sens. C'est le besoin ferroviaire qui a imposé une heure commune sur un même réseau, puis les fuseaux horaires à l'échelle du globe.`],
    ["La route et l'air", `Nicolas-Joseph Cugnot construit en 1769 le premier véhicule automobile à vapeur, un fardier destiné à tirer des canons, lent et difficile à diriger. Il faut attendre 1886 pour que Karl Benz dépose le brevet de la première automobile à moteur à essence. En 1913, Henry Ford généralise la chaîne de montage mobile : la voiture vient à l'ouvrier au lieu de l'inverse, le temps d'assemblage s'effondre, et le prix avec lui.

Dans les airs, les frères Wright réalisent en 1903 le premier vol motorisé contrôlé : leur apport décisif n'est pas le moteur mais le contrôle en roulis par gauchissement des ailes. Un demi-siècle plus tard, le Concorde franchit le mur du son en transport de passagers ; exploité de 1976 à 2003, il n'a jamais été rentable.`],
    ["L'espace et la boîte", `La conquête spatiale commence en 1957 avec Spoutnik 1, premier satellite artificiel, dont le simple bip radio suffit à provoquer une crise politique aux États-Unis. Quatre ans plus tard, Iouri Gagarine devient le premier homme dans l'espace.

Mais l'innovation de transport qui a le plus transformé l'économie mondiale est bien moins spectaculaire : le conteneur normalisé, généralisé à partir des années 1960. En permettant de charger, transporter et décharger sans manipuler la marchandise, il a divisé le coût du fret maritime dans des proportions telles que la localisation des usines a cessé d'être contrainte par la distance.`],
  ],

  "st-energie-technologies": [
    ["Produire de l'électricité", `L'essentiel de l'électricité mondiale est produit de la même façon, quelle que soit la source : un alternateur, où un aimant tournant devant des bobines induit un courant. Charbon, gaz, nucléaire, hydraulique, éolien font tourner cet aimant par des moyens différents — l'éolienne convertit ainsi le vent en faisant entraîner par ses pales un rotor relié à un alternateur.

Le photovoltaïque est l'exception : la lumière y libère directement des électrons dans un semi-conducteur, sans pièce en mouvement. À ne pas confondre avec le solaire thermique, qui concentre le rayonnement pour produire de la chaleur, utilisée telle quelle ou pour faire de la vapeur.`],
    ["Stocker", `Le vrai verrou des énergies renouvelables n'est pas la production mais le stockage : il faut consommer l'électricité au moment où elle est produite, ou la conserver. Le moyen le plus massif reste mécanique : une centrale de pompage-turbinage remonte de l'eau vers un réservoir haut quand l'électricité est abondante, et la turbine quand elle manque.

À plus petite échelle, une batterie lithium-ion stocke l'énergie par déplacement d'ions entre deux électrodes, réversible sur des centaines à des milliers de cycles. La pile à combustible, elle, ne stocke rien : elle produit de l'électricité à partir d'hydrogène et d'oxygène, en rejetant de l'eau — l'hydrogène jouant alors le rôle de vecteur, qu'il faut avoir produit auparavant.`],
    ["Piloter et évaluer", `Un réseau électrique intelligent ajuste production et consommation grâce à des échanges d'information en temps réel : c'est la réponse à l'intermittence, qui consiste à déplacer la demande plutôt qu'à seulement ajouter de l'offre. Le compteur communicant, qui transmet à distance les données de consommation, en est le point d'entrée chez le particulier.

Toute évaluation sérieuse d'une technologie énergétique passe enfin par l'analyse du cycle de vie : un bilan des impacts de l'extraction des matériaux jusqu'au recyclage, en passant par la fabrication, le transport et l'usage. C'est la seule façon de comparer honnêtement des filières dont les impacts ne surviennent pas au même moment.`],
  ],

  "st-medecine-technologies": [
    ["Voir sans ouvrir", `L'imagerie a rendu visible l'intérieur du corps sans l'ouvrir : c'est la rupture du XXe siècle en médecine. Elle commence en 1895, quand Wilhelm Röntgen découvre les rayons X en observant une fluorescence inexpliquée ; il refusera de breveter sa découverte.

Trois techniques se sont ajoutées. Le scanner, ou tomodensitométrie, reconstruit des coupes à partir de multiples radiographies prises sous différents angles. L'échographie repose sur la réflexion d'ultrasons par les tissus, sans rayonnement ionisant, ce qui la rend sûre pour le suivi de grossesse. L'imagerie par résonance magnétique aligne les noyaux d'hydrogène du corps dans un champ magnétique intense, puis mesure leur retour à l'équilibre : elle distingue finement les tissus mous, là où les rayons X voient surtout les os.`],
    ["Réparer et remplacer", `Le stimulateur cardiaque est un appareil implanté qui régule le rythme du cœur par impulsions électriques ; les premiers modèles implantables datent de la fin des années 1950. En 1967, le chirurgien sud-africain Christiaan Barnard réalise la première greffe de cœur humain : le patient survit dix-huit jours, mais la faisabilité est démontrée. Le verrou n'était pas chirurgical mais immunologique, et ce sont les traitements antirejet qui ont rendu la greffe routinière.

La chirurgie assistée par robot transmet le geste du praticien à des instruments articulés introduits par de petites incisions : le robot n'opère pas seul, il filtre les tremblements et démultiplie la précision.`],
    ["Lire et fabriquer le vivant", `La PCR est une technique d'amplification de fragments d'ADN : à partir de quelques molécules, elle en produit des milliards de copies en quelques heures, rendant détectable ce qui ne l'était pas. Elle est devenue familière au grand public avec le dépistage du Covid-19.

Le vaccin à ARN messager applique une autre logique : au lieu d'injecter un agent pathogène atténué ou un antigène, il fournit aux cellules l'instruction de produire elles-mêmes cet antigène. La technologie était en développement depuis des décennies, ce qui explique la rapidité de son déploiement en 2020. La médecine personnalisée, enfin, adapte le traitement aux caractéristiques biologiques du patient — profil génétique d'une tumeur, métabolisme d'un médicament — plutôt qu'à une moyenne de population.`],
  ],

  "st-materiaux-fabrication": [
    ["L'invention qui compte", `L'interchangeabilité des pièces a rendu possible l'industrie moderne, plus encore que la machine à vapeur. Tant que chaque pièce devait être ajustée à la main à son voisine, aucune production en série n'était concevable : la réparation supposait un artisan, et non un magasin de pièces détachées. Rendre les pièces identiques dans une tolérance donnée, c'est rendre possible l'assemblage rapide, la maintenance et la division du travail.

Cette exigence a fait naître la métrologie industrielle, puis les normes. La norme ISO 9001, aujourd'hui, ne certifie pas la qualité d'un produit mais l'existence d'un système de management de la qualité : elle atteste d'une organisation, non d'un résultat.`],
    ["Machines et robots", `Une machine-outil à commande numérique voit ses mouvements pilotés par un programme plutôt que par la main de l'opérateur : la pièce est décrite numériquement, la machine l'exécute à l'identique autant de fois qu'on veut. Un robot industriel est, lui, un manipulateur programmable multi-axes, capable de tâches variées selon son programme et son outil.

L'impression tridimensionnelle par dépôt de matière procède à l'inverse de l'usinage : elle construit couche par couche à partir d'un modèle numérique au lieu d'enlever de la matière. Cela autorise des géométries impossibles à usiner, mais avec des cadences et des propriétés mécaniques encore souvent inférieures.`],
    ["Organiser et durer", `Le lean manufacturing, formalisé chez Toyota, vise à éliminer les gaspillages de production : attentes, stocks, déplacements, défauts. Le juste-à-temps en est la composante la plus connue — approvisionner au moment précis du besoin, sans stock tampon — dont les crises logistiques récentes ont rappelé la fragilité.

Trois notions cadrent aujourd'hui la conception. L'éco-conception intègre dès le départ les impacts sur tout le cycle de vie du produit. L'économie circulaire vise à maintenir les matières en usage le plus longtemps possible, par la réparation, le réemploi et le recyclage. L'obsolescence logicielle, enfin, désigne l'arrêt des mises à jour qui rend un appareil inutilisable ou vulnérable alors qu'il fonctionne encore : c'est devenu le principal facteur de mise au rebut des équipements numériques.`],
  ],

  "st-mathematiques": [
    ["Les nombres", `Un nombre premier est un entier supérieur à un divisible seulement par un et par lui-même. Euclide a démontré il y a plus de deux mille ans qu'il en existe une infinité ; leur répartition reste l'un des sujets les plus actifs des mathématiques, et leur difficulté de factorisation fonde la cryptographie moderne.

Un nombre irrationnel ne peut s'écrire comme quotient de deux entiers : sa découverte, attribuée à l'école pythagoricienne pour la racine de deux, a été un choc philosophique. Pi est le rapport entre la circonférence d'un cercle et son diamètre — irrationnel et même transcendant. Le nombre d'or, environ 1,618, est solution d'une équation du second degré et apparaît dans la suite de Fibonacci ; les propriétés esthétiques qu'on lui prête relèvent souvent de la légende plus que de la mesure.`],
    ["Démontrer", `Le théorème de Pythagore énonce que dans un triangle rectangle, le carré de l'hypoténuse égale la somme des carrés des deux autres côtés. Connu empiriquement de plusieurs civilisations, il doit aux Grecs sa démonstration.

Une conjecture n'est pas un théorème : elle attend une démonstration, parfois pendant des siècles. Le dernier théorème de Fermat, énoncé en 1637 dans une marge, n'a été démontré qu'en 1994 par Andrew Wiles, au terme de sept ans de travail solitaire et par des moyens que Fermat ne pouvait pas connaître. La conjecture de Poincaré, qui portait sur la topologie de l'espace en trois dimensions, a été démontrée en 2003 par Grigori Perelman, qui a refusé la médaille Fields et le million de dollars associés.`],
    ["Reconnaître et buter", `La médaille Fields est la plus haute distinction en mathématiques, remise tous les quatre ans à des chercheurs de moins de quarante ans — il n'existe pas de prix Nobel de mathématiques. Les problèmes du prix du millénaire sont sept problèmes majeurs identifiés en 2000, dotés chacun d'un million de dollars ; un seul, la conjecture de Poincaré, a été résolu.

Les mathématiques connaissent enfin leurs propres limites internes. Les théorèmes d'incomplétude de Gödel, établis en 1931, montrent que tout système formel suffisamment riche contient des énoncés vrais qu'il ne peut pas démontrer en son sein. Le résultat a mis fin au projet de fonder définitivement les mathématiques sur un socle complet et cohérent.`],
  ],

  "st-statistiques-donnees": [
    ["Résumer une population", `La moyenne et la médiane ne disent pas la même chose. La médiane partage la population en deux moitiés égales ; la moyenne, elle, dépend des valeurs extrêmes. Sur des revenus, quelques très hauts salaires tirent la moyenne vers le haut sans déplacer la médiane : c'est pourquoi la médiane est plus parlante pour décrire une situation typique.

L'écart type mesure la dispersion des valeurs autour de la moyenne : deux populations de même moyenne peuvent être radicalement différentes selon qu'elles sont resserrées ou étalées. En économie, un indice rapporte une valeur à une base de référence, souvent fixée à cent : il permet de comparer des évolutions, non des niveaux.`],
    ["Interroger sans tout interroger", `Un échantillon représentatif reproduit la structure de la population étudiée sur les critères pertinents : âge, sexe, catégorie sociale, région. Sa taille compte moins que sa construction — un échantillon mal constitué de dix mille personnes vaut moins qu'un bon échantillon de mille.

La marge d'erreur indique l'intervalle dans lequel se situe probablement la valeur réelle : annoncer un score sans elle est une faute d'interprétation. Deux biais guettent. Le biais de sélection tient à la façon dont l'échantillon a été constitué : un sondage en ligne n'interroge que des gens connectés et volontaires. Le biais du survivant consiste à n'observer que les cas ayant subsisté — étudier les entreprises qui ont réussi sans regarder celles qui ont disparu conduit à des conclusions inversées.`],
    ["Ne pas conclure trop vite", `Une corrélation n'établit jamais une causalité : c'est l'erreur d'interprétation la plus répandue. Deux variables peuvent évoluer ensemble parce que l'une cause l'autre, parce que l'autre cause l'une, parce qu'un facteur tiers les cause toutes deux, ou par pure coïncidence sur un jeu de données assez large.

L'expression toutes choses égales par ailleurs désigne précisément l'effort pour isoler l'effet d'une variable en neutralisant les autres : c'est le geste central de l'analyse statistique, et sa difficulté principale. Enfin, l'anonymisation d'un jeu de données est un traitement rendant impossible la réidentification des personnes ; elle est nettement plus exigeante que la simple suppression des noms, car le croisement de quelques attributs suffit souvent à réidentifier un individu.`],
  ],

  "st-inventions-quotidien": [
    ["L'observation et le hasard", `Beaucoup d'inventions quotidiennes viennent d'une observation faite ailleurs. Georges de Mestral invente le velcro après avoir examiné au microscope les fruits de bardane accrochés au poil de son chien : un système de crochets et de boucles, qu'il reproduit en textile.

Le hasard fait le reste. En 1928, Alexander Fleming remarque qu'une moisissure ayant contaminé une boîte de Petri empêche les bactéries de pousser autour d'elle : c'est la pénicilline, dont l'exploitation industrielle prendra encore quinze ans. En 1945, un ingénieur constate qu'une barre chocolatée a fondu dans sa poche près d'un magnétron de radar : le four à micro-ondes en sort. En 1968, une colle jugée trop faible mise au point chez 3M trouve sa fonction des années plus tard, dans les notes repositionnables.`],
    ["Écrire et voir", `Lewis Waterman met au point à la fin du XIXe siècle le premier stylo-plume à réservoir vraiment fiable, en résolvant le problème de l'alimentation en encre par un conduit à capillarité. Dans les années 1930, le Hongrois László Bíró conçoit le stylo à bille moderne, avec une encre visqueuse à séchage rapide inspirée de l'imprimerie — dans plusieurs langues, le stylo porte encore son nom.

Louis Braille, aveugle depuis l'enfance, invente à seize ans le système de lecture tactile qui porte son nom : six points en relief, combinables, qui permettent de lire mais aussi d'écrire. En 1888, l'appareil Kodak à pellicule souple rend la photographie accessible aux amateurs, avec un slogan qui dit tout du basculement : vous pressez le bouton, nous faisons le reste.`],
    ["Copier et calculer", `En 1938, Chester Carlson met au point la photocopie électrostatique, procédé si peu compris à l'époque qu'une vingtaine d'entreprises le refusent avant qu'une petite société n'en fasse Xerox.

L'invention la plus déterminante de la liste reste sans doute le circuit intégré, mis au point en 1958 : graver plusieurs composants sur une même plaquette de semi-conducteur au lieu de les assembler séparément. Toute l'électronique moderne en découle, et avec elle les ordinateurs, les téléphones et l'essentiel des objets qui nous entourent.`],
  ],

  "st-espace-exploration": [
    ["Aller sur la Lune", `Apollo 11 dépose les premiers hommes sur la Lune en juillet 1969. Six missions Apollo au total y ont posé des équipages, entre 1969 et 1972 — Apollo 13, victime d'une explosion en vol, a dû renoncer et revenir. Douze hommes ont marché sur la Lune, et personne n'y est retourné depuis.

En orbite basse, la Station spatiale internationale est occupée en continu depuis novembre 2000 : c'est le plus long séjour humain ininterrompu hors de la Terre, et l'un des rares programmes de coopération à avoir survécu aux crises diplomatiques entre ses partenaires.`],
    ["Voir loin", `Le télescope spatial Hubble, lancé en 1990, a transformé l'astronomie en s'affranchissant de l'atmosphère terrestre. Son miroir présentait à l'origine un défaut de forme, corrigé lors d'une mission de maintenance en 1993. Le télescope James Webb, lancé en 2021, observe principalement dans l'infrarouge, ce qui lui permet de voir à travers les nuages de poussière et de détecter les objets les plus anciens et les plus lointains.

Les sondes vont plus loin encore. Voyager 1, lancée en 1977, est l'objet humain le plus éloigné de la Terre. Elle est sortie de l'héliosphère, la bulle de vent solaire, mais n'a nullement quitté le système solaire au sens gravitationnel : il lui faudrait des dizaines de milliers d'années pour dépasser le nuage d'Oort.`],
    ["L'Europe et les débris", `L'Agence spatiale européenne coordonne les programmes du continent, avec une répartition industrielle entre États membres. Ses lanceurs de la famille Ariane décollent depuis Kourou, en Guyane, site choisi pour sa proximité de l'équateur — la rotation terrestre y donne un surcroît de vitesse gratuit.

L'Europe a aussi réussi l'une des manœuvres les plus délicates de l'histoire spatiale : la mission Rosetta, après dix ans de voyage, a posé en 2014 le module Philae sur une comète. Reste un problème croissant en orbite basse : le syndrome de Kessler décrit une réaction en chaîne où les collisions de débris engendrent d'autres débris, jusqu'à rendre certaines orbites inexploitables.`],
  ],

  "st-securite-numerique": [
    ["Tromper l'humain", `La faille la plus fréquente n'est pas technique : c'est l'humain qu'on trompe. L'hameçonnage consiste à obtenir des informations — identifiants, coordonnées bancaires — en se faisant passer pour un tiers de confiance : banque, administration, service informatique interne. Aucune protection technique ne suffit si l'utilisateur communique lui-même ses accès.

Le rançongiciel est devenu la menace la plus coûteuse pour les organisations : le logiciel chiffre les données et exige un paiement pour la clé de déchiffrement. La seule parade réellement efficace reste la sauvegarde régulière et déconnectée, testée pour sa capacité effective à restaurer.`],
    ["Se protéger", `Ce qui rend un mot de passe robuste, c'est sa longueur et son imprévisibilité, non la présence obligatoire de caractères spéciaux : une longue phrase aléatoire vaut mieux qu'un mot court truffé de substitutions prévisibles. Un gestionnaire de mots de passe est un coffre chiffré qui stocke et génère des mots de passe uniques pour chaque service, ce qui règle le vrai problème — la réutilisation.

L'authentification à deux facteurs combine deux éléments de nature différente : quelque chose que l'on sait, quelque chose que l'on possède, quelque chose que l'on est. Elle protège même lorsque le mot de passe a fuité.`],
    ["Les techniques et le cadre", `Le chiffrement asymétrique repose sur deux clés : une clé publique, diffusable, qui chiffre, et une clé privée, gardée secrète, qui déchiffre. C'est ce qui permet de communiquer en sécurité avec un inconnu sans lui avoir jamais transmis de secret. La signature électronique en dérive : un procédé cryptographique qui garantit l'origine et l'intégrité d'un document.

Deux menaces plus techniques complètent le tableau. Une faille dite zero-day est une vulnérabilité exploitée avant qu'un correctif n'existe : le défenseur n'a par définition aucun délai. Une attaque par déni de service sature volontairement un service pour le rendre indisponible, souvent depuis des milliers de machines compromises. En France, l'ANSSI, agence nationale de la sécurité des systèmes d'information, accompagne l'État et les opérateurs d'importance vitale.`],
  ],

  "st-histoire-sciences": [
    ["Ce qui fait une science", `Selon Karl Popper, une théorie scientifique doit pouvoir être réfutée : il faut qu'une observation puisse, en principe, la contredire. C'est ce critère de réfutabilité qui distingue une théorie scientifique d'une croyance — une affirmation compatible avec tous les résultats possibles n'apprend rien.

La production du savoir s'organise autour de la relecture par les pairs : avant publication, un article est examiné par des chercheurs du domaine, qui en évaluent la méthode et les conclusions. Le dispositif n'est pas infaillible, comme l'a montré la crise de la reproductibilité : le constat qu'une part importante d'études publiées, notamment en psychologie et en biomédecine, ne se reproduit pas lorsqu'on refait l'expérience.`],
    ["Éprouver un traitement", `Claude Bernard formule en 1865, dans son Introduction à l'étude de la médecine expérimentale, les principes de la méthode expérimentale appliquée au vivant : hypothèse, expérience, contrôle.

L'essai clinique en double aveugle en est l'héritier direct : ni le patient ni le soignant ne savent qui reçoit le traitement et qui reçoit le placebo, ce qui neutralise les attentes des deux côtés. Cette précaution est nécessaire à cause de l'effet placebo, amélioration réelle due à l'attente du patient plutôt qu'au produit administré — effet mesurable, parfois important, et qui rend toute évaluation sans comparateur trompeuse.`],
    ["Ceux qui l'ont faite, et à quel prix", `Galilée est condamné en 1633 pour avoir défendu l'héliocentrisme : l'affaire est devenue le symbole du conflit entre autorité religieuse et démarche scientifique, même si son déroulement réel fut plus politique et plus personnel que ce résumé.

Marie Curie est la seule personne à avoir reçu deux prix Nobel dans deux disciplines scientifiques différentes, en physique puis en chimie. Rosalind Franklin, elle, produit les clichés de diffraction aux rayons X qui permettent d'établir la structure en double hélice de l'ADN ; sa contribution fut longtemps minorée, et elle mourut avant l'attribution du Nobel à ses collègues. Sur le plan des décisions publiques, enfin, le principe de précaution inscrit en droit français impose de prendre des mesures proportionnées face à un risque incertain mais grave : il n'ordonne pas l'abstention, il oblige à agir malgré l'incertitude.`],
  ],

  "st2-textile-industrie": [
    ["La première industrie mécanisée", `Le textile a ouvert la révolution industrielle, et pour une raison simple : c'est un travail répétitif, décomposable en gestes élémentaires, réalisé sur une matière légère. Tout y prédisposait la machine.

La séquence des inventions se lit comme une course. La navette volante de John Kay, en 1733, permet à un seul tisserand de lancer la navette d'un bord à l'autre du métier sans aide : le tissage double de vitesse et la filature ne suit plus. La réponse vient en 1764 avec la spinning jenny de James Hargreaves, qui permet de filer plusieurs fils à la fois — jusqu'à huit d'abord, puis des dizaines. Le déséquilibre bascule alors de l'autre côté, et chaque gain d'un atelier appelle un gain dans l'autre. C'est ce mécanisme d'entraînement mutuel, plus qu'une invention isolée, qui fait démarrer l'industrialisation.`],
    ["Des cartes perforées avant l'informatique", `En 1801, Joseph-Marie Jacquard présente un métier utilisant des cartes perforées : chaque carte commande le relevage des fils de chaîne pour une passe de trame, et la succession des cartes définit le motif. Changer de dessin ne demande plus des jours de réglage mais un nouveau paquet de cartes.

L'idée dépasse largement le textile. Charles Babbage s'en inspire pour sa machine analytique, Herman Hollerith l'utilise pour dépouiller le recensement américain de 1890, et les cartes perforées resteront le support d'entrée des ordinateurs jusqu'aux années 1970. Le premier programme de l'histoire a donc été un motif de tissu — filiation que revendiquait Ada Lovelace elle-même, écrivant que la machine analytique tissait des motifs algébriques comme le métier Jacquard tissait des fleurs.

Lyon, capitale de la soie, adopte massivement le procédé : les canuts de la Croix-Rousse en font l'outil de leur métier, et leurs révoltes de 1831 et 1834 comptent parmi les premiers conflits sociaux de l'ère industrielle.`,
      { image: "st-ada-lovelace", legende: "Ada Lovelace : la filiation entre le métier Jacquard et le programme informatique n'est pas une métaphore rétrospective, elle est revendiquée dès 1843.", alt: "Portrait d'Ada Lovelace" }],
    ["De quoi un tissu est-il fait", `Trois familles de fibres coexistent. Les fibres naturelles — coton, lin, laine, soie — sont prélevées telles quelles. Les fibres artificielles sont fabriquées à partir d'une matière naturelle transformée chimiquement : la viscose, obtenue par dissolution puis régénération de la cellulose du bois, en est le type même. Les fibres synthétiques, elles, sont entièrement fabriquées à partir de composés chimiques issus le plus souvent de la pétrochimie — polyester, nylon, élasthanne.

La distinction artificielle/synthétique est constamment confondue dans le langage courant, alors qu'elle est nette : dans un cas la nature fournit la molécule, dans l'autre elle est construite.`],
    ["Trois façons de faire une étoffe", `Le tissage entrecroise deux ensembles de fils perpendiculaires, la chaîne et la trame : il donne une étoffe stable, peu extensible, qui s'effiloche si on la coupe. Le tricotage forme au contraire des mailles à partir d'un seul fil qui se boucle sur lui-même : l'étoffe est élastique, se déforme, et file si une maille lâche — c'est la différence entre une chemise et un tee-shirt. Un tissu non tissé abandonne les deux principes : c'est une nappe de fibres liées mécaniquement ou chimiquement, procédé rapide et bon marché qui donne les lingettes, les masques et les géotextiles.

L'ornement suit sa propre technique. La teinture par réserve protège certaines zones du tissu de la couleur — par nouage, cire ou pinçage — de sorte que le motif naît de ce qui n'a pas été teint. Batik indonésien, shibori japonais, tie and dye reposent tous sur ce principe.`],
    ["Le prix environnemental", `L'industrie textile représente une part importante de la pollution industrielle de l'eau, notamment par la teinture : bains successifs, sels, métaux, fixateurs, avec des rejets souvent peu traités dans les pays où la production s'est concentrée. La couleur des rivières en aval des zones textiles est devenue un indicateur visuel de la mode de la saison.

S'y ajoutent la consommation d'eau du coton, les microfibres synthétiques relâchées à chaque lavage, et surtout l'accélération des cycles : le nombre de collections annuelles a été multiplié, la durée d'usage d'un vêtement divisée. Le problème n'est donc pas seulement technique — les procédés de teinture sans eau existent — mais volumétrique, et il se joue autant dans les habitudes d'achat que dans les usines.`],
  ],

  "st2-construction": [
    ["Faire tenir une charge", `Toute construction résout le même problème : conduire les charges jusqu'au sol sans que rien ne casse en chemin. Deux logiques structurelles s'y opposent. Un mur porteur supporte les charges de la structure sur toute sa longueur : il est massif, contraint les ouvertures et interdit de modifier les cloisons. Une structure poteau-poutre fait passer les charges par des éléments verticaux et horizontaux ponctuels : les murs ne portent plus rien, les façades se libèrent, les plans deviennent modifiables.

Ce basculement, permis par le béton armé et l'acier, est ce qui rend possible l'architecture du XXe siècle — le plan libre et la façade libre de Le Corbusier ne sont pas des idées esthétiques mais les conséquences directes d'un choix structurel.`],
    ["Le béton armé", `Le béton résiste très bien à la compression et très mal à la traction : il s'écrase difficilement, il se fend facilement. L'acier fait l'inverse. Les associer donne un matériau composite où chacun travaille dans son domaine — c'est l'idée du béton armé, dont Joseph Monier dépose un brevet à la fin du XIXe siècle après avoir commencé par des bacs à orangers.

Le béton précontraint pousse le raisonnement plus loin : on comprime le béton par des câbles tendus avant sa mise en charge, de sorte que les efforts de traction ultérieurs viennent seulement annuler cette compression sans jamais mettre le béton en tension. Eugène Freyssinet en fait un procédé industriel dans les années 1930, ce qui permet des portées bien supérieures et des éléments beaucoup plus minces.`],
    ["Sous le bâtiment, et dans le vide", `Une fondation profonde reporte les charges vers des couches résistantes en profondeur, par pieux ou barrettes, lorsque le sol de surface est trop meuble. Sur un sol argileux ou un remblai, c'est elle qui décide de tout : les désordres les plus coûteux d'un bâtiment viennent presque toujours du sol, jamais de la structure elle-même.

Pour franchir, deux familles. Un pont suspendu porte son tablier par des câbles verticaux accrochés à deux grands câbles tendus entre des pylônes : la structure travaille en traction, ce qui autorise les plus grandes portées jamais construites. Une charpente en treillis répartit au contraire les efforts dans un réseau de barres triangulées — le triangle étant la seule figure indéformable sans articuler ses sommets. C'est le principe des ponts métalliques du XIXe siècle et de la tour Eiffel, qui n'est qu'un treillis vertical.`,
      { image: "tour-eiffel", legende: "La tour Eiffel : un treillis de barres triangulées, calculé pour résister au vent avant tout.", alt: "La tour Eiffel vue depuis le Champ-de-Mars" }],
    ["Ce qui a rendu les tours possibles", `Les gratte-ciel apparaissent à la fin du XIXe siècle grâce à la conjonction de deux innovations. L'acier, d'abord, permet une ossature qui porte le bâtiment à la place des murs, dont l'épaisseur en maçonnerie serait devenue prohibitive au-delà d'une dizaine d'étages. L'ascenseur de sécurité d'Elisha Otis, ensuite, présenté en 1854 avec son parachute bloquant la cabine en cas de rupture du câble : sans lui, personne n'aurait loué un dixième étage.

Une ville verticale suppose donc autant une machine qu'une structure — leçon générale de l'histoire des techniques, où les innovations n'ont d'effet qu'assemblées.`],
    ["Le bâtiment qui perd sa chaleur", `L'isolation thermique par l'extérieur consiste à poser l'isolant sur la façade côté extérieur plutôt qu'à l'intérieur. Le gain est double : la surface habitable est préservée, et surtout l'enveloppe isolante devient continue.

Cette continuité est le vrai sujet. Un pont thermique est une zone où l'isolation est interrompue — jonction d'un balcon, d'un plancher, d'un tableau de fenêtre — et où la chaleur s'échappe par le chemin le plus court. Ces zones concentrent une part disproportionnée des déperditions et provoquent des condensations locales, donc des moisissures. Une isolation intérieure très épaisse mais percée de ponts thermiques performe souvent moins bien qu'une isolation extérieure plus modeste mais continue : en thermique du bâtiment, la faiblesse de la chaîne l'emporte sur l'épaisseur du maillon le plus fort.`],
  ],

  "st2-eau-genie-civil": [
    ["Retenir l'eau", `Un barrage doit encaisser une poussée qui croît avec la profondeur et qui atteint des dizaines de milliers de tonnes. Deux stratégies s'affrontent. Le barrage-poids résiste par sa seule masse. Le barrage-voûte est courbe et reporte la poussée de l'eau sur les rives : la coque travaille en compression, ce que le béton fait très bien, et le volume de matériau est bien moindre — à condition d'une gorge étroite et de rives rocheuses saines, faute de quoi la voûte n'a rien où s'appuyer.

Le barrage des Trois-Gorges, en Chine, est le plus grand du monde par sa puissance installée. Il illustre aussi les coûts non financiers de ces ouvrages : plus d'un million de personnes déplacées, sites archéologiques noyés, sédiments retenus en amont et manquant en aval.`],
    ["Franchir les dénivelés", `Une écluse est un sas permettant à un bateau de franchir une différence de niveau : on l'enferme entre deux portes, on remplit ou on vide, on rouvre. Le principe, connu depuis la Chine médiévale et généralisé en Europe à la Renaissance, a rendu navigables des cours d'eau à pente marquée et permis les canaux de partage entre deux bassins, comme le canal du Midi qui franchit le seuil de Naurouze.

Une digue relève d'une autre fonction : ouvrage linéaire protégeant des inondations ou retenant l'eau, elle défend un territoire au lieu de faciliter un passage. Sa faiblesse est structurelle — elle donne un sentiment de sécurité qui encourage à construire derrière, si bien qu'une rupture, toujours possible, produit des dégâts croissants avec le temps.`],
    ["Percer", `Un tunnelier est une machine creusant un tunnel et posant le revêtement en continu : la roue de coupe attaque le front, les déblais sont évacués vers l'arrière, et des anneaux de béton préfabriqué sont mis en place au fur et à mesure derrière le bouclier. Il peut avancer de plusieurs dizaines de mètres par jour sous une ville habitée, sans creusement à ciel ouvert, avec des tassements de surface contrôlés au millimètre.

Deux ouvrages en donnent la mesure. Le tunnel sous la Manche fait environ cinquante kilomètres, dont trente-huit sous la mer, creusés depuis les deux rives et raccordés en 1990 avec un écart de quelques centimètres. Le tunnel de base du Saint-Gothard, plus long tunnel ferroviaire du monde avec cinquante-sept kilomètres, traverse les Alpes à altitude quasi constante pour supprimer la rampe d'accès — sous jusqu'à deux kilomètres de roche, où la température atteint spontanément quarante-cinq degrés.`],
    ["Le vocabulaire des ouvrages", `Un viaduc est un pont franchissant une vallée à grande hauteur, généralement sur plusieurs travées — le viaduc de Millau en est l'exemple le plus célèbre. Un aqueduc conduit l'eau par gravité sur de longues distances, avec une pente d'une régularité extrême : les aqueducs romains descendaient de quelques dizaines de centimètres par kilomètre sur des dizaines de kilomètres, ce qui suppose un nivellement d'une précision remarquable pour des instruments aussi simples.

Le mot générique est ouvrage d'art : dans le vocabulaire du génie civil, une construction ponctuelle — pont, tunnel, mur de soutènement — implantée sur une infrastructure linéaire. L'expression ne désigne pas une prétention esthétique mais un savoir-faire technique, l'« art » y ayant le sens ancien de métier.`],
  ],

  "st2-armement": [
    ["La poudre change les murs", `La poudre à canon est originaire de Chine, où les alchimistes taoïstes la découvrent au IXe siècle en cherchant un élixir d'immortalité — l'une des ironies les mieux documentées de l'histoire des techniques. Elle arrive en Europe au XIIIe siècle et transforme la guerre de siège à la fin du Moyen Âge avec l'artillerie à poudre.

L'effet est immédiat sur l'architecture. Les hautes murailles verticales, conçues contre l'échelle et le bélier, offrent une cible idéale au boulet. Les châteaux forts perdent en quelques décennies leur raison d'être, et avec eux une part du pouvoir de la noblesse territoriale : seuls les États capables de financer une artillerie de siège peuvent désormais réduire une place forte.`],
    ["Répondre au boulet", `Vauban, ingénieur de Louis XIV, systématise la réponse : des bastions en étoile aux murailles basses et épaisses, souvent enterrées derrière un glacis en pente douce. Le boulet ricoche ou s'enfonce dans la terre au lieu de fracturer la pierre, et la géométrie en étoile supprime les angles morts — chaque face est battue par le feu du bastion voisin.

Cette architecture n'est pas seulement défensive : elle est aussi mathématique, tracée à la règle et au compas selon des règles publiées. Vauban fortifie une frontière entière, du Nord aux Alpes, et son « pré carré » invente l'idée moderne de frontière continue défendue par un réseau plutôt que par des places isolées.`],
    ["Le siècle des masses", `La Première Guerre mondiale voit l'usage généralisé de la mitrailleuse, arme qui inverse le rapport entre attaque et défense : quelques servants tiennent un front que des bataillons ne peuvent plus franchir. La tranchée n'est pas une invention mais une conséquence — la seule manière de survivre à une puissance de feu que la mobilité ne compense plus. Le char, le gaz et l'avion naissent tous de la recherche d'une sortie à cette impasse.

L'arme chimique, qui utilise la toxicité de substances chimiques, y fait son entrée à grande échelle en 1915. Son interdiction par le protocole de Genève de 1925 sera l'un des rares tabous militaires largement respectés au XXe siècle — moins par scrupule que par crainte de la réciprocité et par sa faible efficacité militaire réelle.

Le projet Manhattan, lancé aux États-Unis en 1942, aboutit en 1945 à la bombe atomique. Il inaugure un modèle qui marquera tout l'après-guerre : la « big science », mobilisation de milliers de chercheurs et de moyens industriels considérables sous direction étatique et secret militaire.`,
      { image: "hf-tranchee-verdun", legende: "Verdun : la tranchée est la réponse défensive à une puissance de feu que la mobilité ne compense plus.", alt: "Soldats dans une tranchée à Verdun" }],
    ["Ce que la guerre lègue au quotidien", `De nombreuses technologies civiles courantes ont une origine militaire. Le radar, développé pour détecter les avions et guider la défense aérienne, en est la source la plus fertile : le four à micro-ondes en dérive directement, un ingénieur ayant remarqué qu'une barre chocolatée fondait dans sa poche près d'un magnétron en fonctionnement. ARPANET, réseau informatique financé par l'agence de recherche du Pentagone à la fin des années 1960, est l'ancêtre direct d'internet ; le GPS, la conserve, l'aviation à réaction et une part de l'informatique relèvent de la même filiation.

Il faut se garder d'en tirer que la guerre serait bonne pour l'innovation : ce que l'on observe est un effet de financement massif et sans contrainte de rentabilité immédiate, que des programmes civils comparables ont aussi produit. Les technologies actuelles poursuivent ce va-et-vient — un drone armé, aéronef sans pilote à bord capable de tirer, mobilise les mêmes composants que les drones civils, et pose des questions inédites sur la distance entre l'opérateur et sa cible.`],
  ],

  "st2-audiovisuel-technique": [
    ["Enregistrer le son", `Thomas Edison invente le phonographe en 1877 : une aiguille grave les vibrations sonores sur un cylindre de cire, et la même aiguille les restitue en repassant dans le sillon. Le principe est purement mécanique, sans électricité, et c'est ce qui le rend stupéfiant — un objet inerte rend une voix humaine.

Le cylindre est remplacé au tournant du XXe siècle par le disque plat, mis au point par Émile Berliner : moins fidèle au départ, mais pressable en série depuis une matrice, donc industrialisable. C'est la première fois qu'un choix de support est arbitré par la reproductibilité industrielle plutôt que par la qualité — le débat se rejouera à l'identique pour la cassette, puis pour le MP3.

Après 1945 se généralise la bande magnétique, développée en Allemagne dans les années 1930. Elle apporte quelque chose que ni le cylindre ni le disque n'offraient : le montage. On peut couper, coller, réenregistrer par-dessus, superposer des pistes — et le studio devient un instrument à part entière.`],
    ["Le passage au numérique", `Numériser un signal sonore, c'est le convertir en une suite de valeurs échantillonnées : on mesure l'amplitude à intervalles réguliers, et on code chaque mesure sur un nombre fixe de bits. Le son cesse alors d'être une trace physique pour devenir une liste de nombres — c'est là que le contenu se sépare définitivement de son support.

Combien de mesures par seconde ? Le théorème d'échantillonnage, dit de Nyquist-Shannon, fixe la fréquence minimale pour restituer un signal sans perte : au moins le double de la plus haute fréquence contenue dans le signal. L'oreille humaine plafonnant vers vingt kilohertz, le disque compact échantillonne à 44,1 kHz. Ce n'est pas un réglage empirique mais la conséquence d'un théorème — en dessous, des fréquences parasites apparaissent par repliement de spectre.`],
    ["Compresser", `Un fichier audio ou vidéo brut est énorme, d'où la compression, qui se décline en deux familles radicalement différentes. La compression sans perte réorganise l'information de manière réversible : on retrouve exactement l'original. La compression avec perte supprime définitivement de l'information jugée peu perceptible — masquage psychoacoustique pour le son, détails de couleur pour l'image — et le fichier d'origine est irrécupérable.

Un codec vidéo est le procédé de compression et de décompression des images animées. Son efficacité repose sur la redondance temporelle : d'une image à la suivante, l'essentiel ne change pas, et il suffit de coder les différences. C'est pourquoi une vidéo de scène fixe pèse une fraction d'une vidéo de caméra qui bouge — et pourquoi les plans très agités révèlent les défauts de compression sous forme de blocs.`],
    ["Capter la lumière", `Le capteur d'un appareil photo numérique est un composant convertissant la lumière en signal électrique, par effet photoélectrique : chaque photosite accumule des charges proportionnelles au nombre de photons reçus. La définition d'une image numérique est son nombre total de pixels — souvent citée comme critère de qualité, alors que la taille du capteur, l'optique et le traitement comptent davantage : à définition égale, un grand capteur reçoit plus de lumière par pixel et produit une image bien plus propre en basse lumière.

La haute dynamique désigne une plage étendue entre les zones sombres et les zones claires d'une même image. L'œil s'adapte en permanence et perçoit sans peine un intérieur et une fenêtre ensoleillée ; un capteur, à exposition unique, doit choisir entre brûler la fenêtre ou boucher l'intérieur. Les techniques de haute dynamique combinent plusieurs expositions ou exploitent des capteurs à large plage pour restituer les deux — ce qui rapproche l'image de ce que l'œil voit, non de ce que l'appareil enregistre.`],
  ],

  "st2-robotique": [
    ["Ce qui est difficile pour une machine", `Le paradoxe de Moravec, énoncé dans les années 1980, formule le résultat le plus contre-intuitif de la robotique : les tâches sensorimotrices simples pour l'humain sont extrêmement difficiles pour les machines, tandis que le raisonnement abstrait leur est facile. Une machine bat le champion du monde d'échecs depuis 1997 ; ramasser une chaussette dans une chambre en désordre reste un problème ouvert.

L'explication est évolutive. La perception et la motricité sont le produit de centaines de millions d'années de sélection, si bien qu'elles nous paraissent sans effort — précisément parce qu'elles sont optimisées au point d'être inconscientes. Le raisonnement logique, apparu très récemment, nous coûte visiblement. Nous jugeons donc la difficulté d'une tâche à l'effort qu'elle nous demande, ce qui est un mauvais indicateur pour une machine.`],
    ["Les organes d'un robot", `Un robot se décompose en trois fonctions. Les capteurs le renseignent sur le monde et sur lui-même. Un actionneur produit un mouvement — moteur électrique, vérin, muscle artificiel — et transforme l'énergie en action. Entre les deux, le calculateur décide.

La préhension, capacité à saisir et manipuler des objets, concentre les difficultés. Il faut évaluer la forme, la fragilité, la masse et le frottement d'un objet inconnu, puis doser une force suffisante pour tenir sans écraser. La main humaine y parvient grâce à une densité de capteurs tactiles qu'aucune pince n'égale, et grâce à des réflexes de correction plus rapides que la conscience. Les progrès récents viennent moins de mains plus complexes que de préhenseurs souples, qui épousent l'objet au lieu de le calculer.`],
    ["Savoir où l'on est", `L'odométrie estime le déplacement d'un robot par la mesure de la rotation de ses roues. Simple et peu coûteuse, elle dérive inévitablement : le moindre glissement introduit une erreur qui s'accumule sans jamais se corriger, si bien qu'un robot fiant à sa seule odométrie se croit ailleurs qu'il n'est après quelques dizaines de mètres.

Le SLAM — cartographie et localisation simultanées — résout le problème par un raisonnement circulaire assumé : le robot construit une carte de son environnement tout en s'y localisant, chaque observation corrigeant à la fois sa position estimée et la carte. La reconnaissance d'un lieu déjà visité permet de refermer la boucle et de redistribuer l'erreur accumulée sur tout le parcours. C'est la brique commune aux aspirateurs autonomes, aux véhicules sans conducteur et à la réalité augmentée.`],
    ["Les robots parmi nous", `Un cobot est un robot conçu pour travailler aux côtés d'humains sans barrière de sécurité : bras légers, limitation de force, détection de contact, arrêt immédiat au choc. Il change la logique d'atelier — le robot industriel classique est enfermé dans une cage parce qu'il est aveugle et puissant ; le cobot partage l'établi.

Un exosquelette est une structure portée assistant les mouvements de l'utilisateur, pour soulager le port de charges en logistique ou aider à la rééducation. La vallée de l'étrange décrit un phénomène d'un tout autre ordre : le malaise provoqué par un robot presque, mais pas tout à fait humain. L'acceptation croît avec le réalisme jusqu'à un point où elle s'effondre brutalement, avant de remonter si la ressemblance devient parfaite — ce qui conduit beaucoup de concepteurs à choisir délibérément l'apparence stylisée.

La Corée du Sud possède la plus forte densité de robots industriels au monde, loin devant les autres pays. La question éthique centrale n'y est pas la disparition du travail — l'emploi y reste élevé — mais la répartition des gains de productivité et l'évolution du contenu des emplois : qui capte la valeur créée par la machine, et que devient la qualification de celui qui la surveille.`],
  ],

  "st2-espace-technologies": [
    ["Aller vite, pas haut", `L'intuition trompe : mettre un objet en orbite exige surtout une très grande vitesse horizontale, non de l'altitude. Un satellite en orbite basse tombe en permanence vers la Terre — simplement, il va assez vite latéralement pour que la surface se dérobe sous lui à mesure qu'il descend. L'orbite est une chute perpétuellement manquée, image que Newton avait déjà proposée avec son canon imaginaire au sommet d'une montagne.

Les chiffres le confirment : atteindre cent kilomètres d'altitude coûte relativement peu d'énergie, mais y rester exige environ vingt-huit mille kilomètres par heure. C'est cette vitesse, et non la hauteur, qui absorbe l'essentiel du carburant d'un lanceur — et c'est aussi elle qu'il faut dissiper au retour, d'où l'échauffement extrême des rentrées atmosphériques.`],
    ["Choisir son orbite", `Une orbite géostationnaire place le satellite à environ trente-six mille kilomètres au-dessus de l'équateur, à une altitude où sa période orbitale égale exactement la durée du jour : il paraît immobile au-dessus du même point. C'est ce qui permet aux antennes de télévision de rester fixes. La contrepartie est une distance considérable, donc un délai de transmission perceptible et un signal affaibli.

Une orbite héliosynchrone répond à un autre besoin : son plan tourne au même rythme que la Terre autour du Soleil, si bien que le satellite survole chaque point à la même heure solaire locale. Les images d'observation de la Terre sont ainsi prises sous un éclairage comparable d'un passage à l'autre, ce qui rend les comparaisons possibles. C'est l'orbite des satellites météorologiques défilants et des programmes d'imagerie comme Sentinel.`,
      { type: "tableau", titre: "Trois orbites, trois usages", colonnes: ["Orbite", "Altitude", "Ce qu'elle permet", "Exemples"], lignes: [
        ["Orbite basse", "200 à 2 000 km", "Faible latence, images détaillées, lancement peu coûteux", "ISS, constellations internet"],
        ["Orbite héliosynchrone", "≈ 700 à 800 km", "Même heure solaire à chaque passage", "Satellites d'observation de la Terre"],
        ["Orbite géostationnaire", "≈ 36 000 km", "Position fixe dans le ciel", "Télévision, météo, télécommunications"],
      ] }],
    ["Se débarrasser du poids", `Un étage de lanceur est une section largable une fois son carburant épuisé. Le principe est arithmétique : porter un réservoir vide coûte de l'énergie pour rien, donc mieux vaut le laisser tomber. C'est ce qui rend le vol orbital possible avec des ergols chimiques, un lanceur monoétage restant à la limite du réalisable.

Les lanceurs réutilisables changent l'économie du secteur en récupérant le premier étage, la partie la plus coûteuse. Un vol ne consomme plus une fusée entière mais du carburant, une inspection et une remise en état. Le coût du kilogramme en orbite a chuté d'un ordre de grandeur en une décennie, ce qui a rendu envisageables des projets — constellations de milliers de satellites, tourisme orbital — qui n'étaient pas seulement chers auparavant, mais impensables.`],
    ["Le ciel se remplit", `Une constellation de satellites est un ensemble coordonné assurant une couverture continue : dès qu'un satellite quitte l'horizon, un autre prend le relais. C'est ce qui permet l'internet par satellite à faible latence en orbite basse, ou le positionnement global.

Leur multiplication pose deux problèmes. Aux astronomes d'abord : les traînées lumineuses des satellites zèbrent les poses longues et polluent les observations, particulièrement pour les grands relevés du ciel. Aux opérateurs ensuite : la densité d'objets accroît le risque de collision, et chaque collision engendre des débris qui augmentent le risque suivant — c'est le syndrome de Kessler, scénario où une région orbitale devient inutilisable.

D'où deux pratiques de fin de vie. La désorbitation consiste à placer le satellite sur une trajectoire de rentrée où il se consumera dans l'atmosphère, solution retenue en orbite basse. En orbite géostationnaire, la redescente coûterait trop de carburant : on relègue les satellites sur une orbite cimetière, quelques centaines de kilomètres plus haut, où ils resteront des millions d'années.`],
    ["Voyager sans carburant", `L'assistance gravitationnelle utilise la gravité d'une planète pour accélérer une sonde : en passant derrière la planète dans le sens de son mouvement orbital, la sonde lui emprunte une infime fraction de sa quantité de mouvement et repart plus vite par rapport au Soleil. La planète, elle, ralentit d'une quantité indétectable.

La manœuvre a rendu possibles toutes les missions vers le système solaire externe : Voyager 2 a visité les quatre planètes géantes grâce à un alignement se produisant tous les cent soixante-quinze ans, Cassini a enchaîné Vénus, Vénus, la Terre puis Jupiter avant d'atteindre Saturne. C'est un cas rare où une contrainte physique — l'impossibilité d'emporter assez de carburant — a été contournée par la géométrie plutôt que par la technique.`],
  ],

  "st2-medecine-innovations": [
    ["Lire le génome", `Le séquençage du génome humain est déclaré achevé en 2003, après treize ans de travail international et un coût de plusieurs milliards de dollars. Vingt ans plus tard, séquencer un génome complet se compte en centaines d'euros et en une journée. Cette chute, plus rapide que celle des composants électroniques, est l'une des plus spectaculaires de l'histoire des techniques.

Elle repose sur le séquençage haut débit, technologie permettant de lire massivement de l'ADN en parallèle : au lieu de déchiffrer une séquence à la fois, on fragmente le génome en millions de morceaux lus simultanément, puis on reconstitue l'ensemble par calcul. Le goulot d'étranglement s'est déplacé de la biologie vers l'informatique — produire les données est devenu facile, les interpréter reste difficile.`],
    ["Viser juste en cancérologie", `Une thérapie ciblée vise une anomalie moléculaire précise de la tumeur : une mutation, une protéine anormale, un récepteur surexprimé. À la différence de la chimiothérapie classique, qui attaque toutes les cellules à division rapide — d'où ses effets sur les cheveux, la moelle et l'intestin —, elle ne touche en principe que les cellules porteuses de la cible. Sa condition est de connaître cette cible, ce qui suppose de caractériser la tumeur de chaque patient.

L'immunothérapie procède autrement : elle mobilise le système immunitaire contre la tumeur, généralement en levant les freins que le cancer a détournés pour se rendre invisible. Ses résultats sur certains cancers longtemps sans recours ont été spectaculaires, avec des rémissions durables — mais elle ne fonctionne que chez une fraction des patients, et prédire lesquels reste l'un des grands chantiers ouverts.`],
    ["Opérer et suivre autrement", `La chirurgie mini-invasive intervient par de petites incisions, à l'aide d'instruments longs et d'une caméra. L'intérêt n'est pas cosmétique : moins de traumatisme tissulaire signifie moins de douleur, moins d'infections et une hospitalisation plus courte. Le prix à payer est la perte du toucher direct et une vision indirecte, que la robotique chirurgicale compense en partie par des instruments articulés et une vue en relief.

La télémédecine — exercice de la médecine à distance par les technologies de communication — a franchi en quelques mois de 2020 une adoption que vingt ans de politiques publiques n'avaient pas obtenue. Elle s'accompagne des dispositifs médicaux implantables connectés, implants transmettant des données de suivi : un pacemaker qui signale une arythmie avant le symptôme, une pompe qui ajuste une dose. La question qu'ils ouvrent n'est plus médicale mais informationnelle — sécurité des transmissions, propriété des données, gestion d'alertes en flux continu.`],
    ["Réparer et reconstruire", `La médecine régénérative vise à réparer ou remplacer des tissus endommagés plutôt qu'à compenser leur défaillance : cellules souches, facteurs de croissance, matrices support. Le changement de logique est profond — on ne cherche plus à suppléer un organe défaillant par un médicament ou une machine, mais à lui rendre sa fonction.

La bio-impression pousse l'idée jusqu'à l'impression tridimensionnelle de structures contenant des cellules vivantes, déposées couche par couche dans un gel support. Des tissus simples — peau, cartilage — sont produits en laboratoire ; les organes complexes butent sur la vascularisation, un tissu épais mourant sans réseau capillaire pour le nourrir. Les annonces sur les organes imprimés sont donc à lire avec prudence.

L'intelligence artificielle, enfin, apporte au diagnostic par imagerie une aide à la détection d'anomalies sur de grands volumes d'images : dépistage, tri des urgences, mesure automatique. Sa performance égale ou dépasse celle des experts sur des tâches étroites et bien définies, et s'effondre sur les cas atypiques ou sur des images produites par un appareil différent de ceux ayant servi à l'entraînement. C'est un outil de première lecture, pas un substitut au médecin.`],
  ],

  "st2-communication-histoire": [
    ["L'électricité abolit la distance", `Samuel Morse met au point dans les années 1830 un télégraphe électrique et le code qui porte son nom, où chaque lettre devient une suite de points et de traits. Pour la première fois, un message circule plus vite qu'un messager : l'information se détache du transport physique, rupture plus profonde encore que l'accélération elle-même.

Le premier câble télégraphique transatlantique fonctionne en 1858, quelques semaines seulement avant de rendre l'âme — la reine Victoria et le président Buchanan avaient eu le temps d'échanger des salutations qui mirent des heures à passer. Il fallut attendre 1866 pour une liaison durable. L'épisode illustre une constante des grandes infrastructures : la première réussite technique précède de plusieurs années la fiabilité industrielle.`],
    ["Parler, puis se passer d'opératrice", `Alexander Graham Bell obtient en 1876 le brevet du téléphone aux États-Unis, quelques heures avant Elisha Gray — l'un des dépôts les plus disputés de l'histoire des brevets. Le téléphone transporte non plus un code mais la voix elle-même, ce qui supprime l'intermédiaire du télégraphiste et ouvre l'usage au grand public.

Restait l'opératrice, qui reliait manuellement les abonnés. Le commutateur automatique la remplace, inventé selon la légende par un croque-mort de Kansas City convaincu que l'opératrice locale, épouse d'un concurrent, détournait ses appels. Anecdote invérifiable mais révélatrice : l'automatisation a été perçue dès l'origine comme une garantie d'impartialité, autant que d'économie.

Le multiplexage — transmission de plusieurs communications sur un même support — démultiplie ensuite la capacité des lignes, en séparant les conversations par fréquence puis par intervalle de temps. Sans lui, chaque appel exigerait sa propre paire de fils.`],
    ["Découper l'information", `La commutation par paquets découpe les données en paquets routés indépendamment, chacun trouvant son chemin et l'ensemble étant réassemblé à l'arrivée. Elle s'oppose à la commutation de circuits du téléphone classique, qui réservait une liaison de bout en bout pour la durée de l'appel, occupée même pendant les silences.

L'avantage est double : le réseau se partage entre de nombreuses communications, et il survit à la perte d'un nœud puisque les paquets suivants empruntent une autre route. C'est le principe fondateur d'internet, et l'une des rares idées d'ingénierie dont la robustesse a dépassé de très loin les prévisions de ses concepteurs.`],
    ["Le réseau mobile et ses câbles", `Une cellule est la zone couverte par une antenne relais, d'où le nom de téléphonie cellulaire. Découper le territoire en cellules permet de réutiliser les mêmes fréquences à quelques kilomètres d'écart, donc de servir bien plus d'abonnés qu'un émetteur unique. La troisième génération de téléphonie mobile introduit l'internet mobile à haut débit au début des années 2000, et fait du téléphone un terminal de données autant qu'un appareil de conversation.

Une idée fausse persiste pourtant : que les communications intercontinentales passeraient par les satellites. L'essentiel du trafic internet mondial transite par des câbles sous-marins, à peine plus épais qu'un tuyau d'arrosage, posés sur les fonds océaniques. La raison tient à la latence, délai de transmission d'un signal : un aller-retour vers l'orbite géostationnaire ajoute environ un quart de seconde, insupportable pour un appel ou un jeu. La fibre reste plus rapide, plus capacitaire et moins chère — et beaucoup plus vulnérable qu'on ne l'imagine, quelques ancres de navire suffisant à isoler une région.`],
  ],

  "st2-alimentation-techniques": [
    ["Une invention née d'un concours militaire", `En 1795, le Directoire promet une récompense à qui saura conserver des aliments pour les armées en campagne. Nicolas Appert, confiseur parisien, met au point en réponse un procédé simple : remplir un récipient, le fermer hermétiquement, puis le chauffer longuement au bain-marie. L'appertisation est née, quinze ans avant que ne se généralise la boîte métallique, et un demi-siècle avant que Pasteur n'explique pourquoi cela fonctionne.

Ce décalage est instructif : Appert ignore l'existence des micro-organismes et parle de « principe de fermentation » qu'il faut détruire. Il a raison sur le geste et faux sur la théorie — cas fréquent en histoire des techniques, où la pratique précède souvent la compréhension.`],
    ["Chauffer plus ou moins fort", `Trois traitements thermiques se distinguent par leur intensité. La pasteurisation, autour de soixante-dix degrés, ne détruit pas toutes les formes de vie : elle élimine les pathogènes et une partie de la flore, mais laisse des spores, d'où une conservation limitée et au froid. La stérilisation, au-delà de cent degrés sous pression, détruit tout, spores comprises, au prix d'une altération du goût et des vitamines.

Le procédé UHT — ultra-haute température — cherche le compromis par un chauffage très bref à très haute température, quelques secondes à cent quarante degrés. Les micro-organismes, sensibles à la température, meurent ; les molécules du goût, sensibles à la durée, sont moins affectées. C'est ce qui permet un lait conservable des mois hors réfrigérateur, avec un goût que les amateurs distinguent pourtant sans peine du lait frais.`],
    ["Priver les microbes d'eau", `Le sel conserve en retirant l'eau disponible pour les micro-organismes : par osmose, il abaisse ce que les technologues appellent l'activité de l'eau. Le micro-organisme n'est pas empoisonné, il est asséché. Le sucre agit de même, ce qui explique que confitures et salaisons relèvent du même principe malgré leurs goûts opposés.

Le séchage pousse la logique à son terme. La lyophilisation en est la forme la plus raffinée : on congèle le produit puis on abaisse la pression pour que la glace se sublime — passe directement de l'état solide à l'état gazeux — sans jamais repasser par l'eau liquide. La structure est préservée, la réhydratation quasi parfaite, ce qui en fait le procédé du café instantané haut de gamme, des rations d'expédition et des vaccins.

La fermentation retourne le problème : au lieu d'éliminer les micro-organismes, on en installe de bénéfiques qui acidifient le milieu et rendent le terrain inhospitalier aux autres. Choucroute, yaourt, fromage, kimchi et pain au levain reposent tous sur cette conservation par occupation.`],
    ["Le froid et l'air", `La surgélation est une congélation très rapide, à très basse température, qui forme de petits cristaux de glace. La taille des cristaux est tout l'enjeu : une congélation lente en forme de gros, qui percent les parois cellulaires, d'où l'aliment mou et l'eau qui s'écoule à la décongélation. La chaîne du froid — maintien continu d'une température basse de la production à la consommation — n'a donc pas seulement une fonction sanitaire : une rupture, même suivie d'une recongélation, dégrade irréversiblement la texture.

La conservation sous atmosphère modifiée remplace l'air de l'emballage par un mélange gazeux choisi, généralement appauvri en oxygène et enrichi en azote ou en dioxyde de carbone : la respiration du produit ralentit, les moisissures aérobies sont bridées, et le rouge de la viande peut être préservé. L'ionisation traite les aliments par rayonnement pour détruire les micro-organismes sans chauffage. Efficace, autorisée pour certaines denrées et sans radioactivité induite, elle reste très peu employée en France, sa mauvaise image auprès des consommateurs pesant plus que ses résultats.`],
  ],

  "st2-verre-ceramique": [
    ["Un solide qui n'est pas un cristal", `Le verre ordinaire est composé de silice — le sable —, de soude et de chaux. La soude abaisse la température de fusion de la silice, qui dépasserait autrement mille sept cents degrés ; la chaux rend le verre résistant à l'eau, faute de quoi il se dissoudrait lentement.

Sa particularité est structurelle : le verre est un solide amorphe, dont les atomes n'ont pas d'organisation cristalline régulière. Refroidi trop vite pour cristalliser, il fige le désordre d'un liquide. De là viennent ses propriétés — transparence, absence de plan de clivage, ramollissement progressif au chauffage plutôt que fusion nette à température fixe. C'est ce ramollissement graduel qui permet de le travailler. Précision au passage : le verre des vitraux médiévaux n'est pas plus épais en bas parce qu'il aurait « coulé » en huit siècles, mais parce que les techniques de l'époque produisaient des feuilles irrégulières que les verriers posaient partie lourde en bas.`],
    ["Souffler, puis flotter", `Le soufflage, apparu au Ier siècle avant notre ère au Proche-Orient, révolutionne la production : une paraison de verre en fusion cueillie au bout d'une canne, un souffle, et l'on obtient en quelques secondes un récipient creux qu'il fallait auparavant façonner sur un noyau, laborieusement. Le verre passe d'objet de luxe à contenant courant dans tout l'Empire romain — l'une des rares fois où une innovation a fait chuter aussi vite le prix d'un bien.

Le verre plat a longtemps résisté : coulé et poli, il coûtait cher et gardait des défauts optiques. Le procédé de flottage, mis au point dans les années 1950, résout le problème d'un geste élégant — le verre en fusion est déversé sur un bain d'étain fondu, plus dense, sur lequel il s'étale en une nappe d'épaisseur parfaitement uniforme et aux deux faces parfaitement lisses, sans aucun polissage. La quasi-totalité du verre plat mondial en est aujourd'hui issue.`],
    ["Rendre le verre moins dangereux", `Le verre trempé est traité thermiquement : chauffé puis refroidi brutalement en surface, il conserve une peau en compression et un cœur en tension. Il faut vaincre cette compression avant de le casser, d'où une résistance aux chocs bien supérieure ; et lorsqu'il cède, l'énergie stockée le fragmente en petits morceaux non coupants. C'est le verre des portes, des vitres latérales d'automobile et des écrans de téléphone.

Le verre feuilleté suit un autre principe : deux verres collés par un film plastique. À l'impact, il se fissure mais les morceaux restent solidaires du film — d'où son emploi en pare-brise et en vitrage de sécurité, où l'on veut éviter la projection d'éclats autant que la chute du panneau.`],
    ["Terre cuite, terre vitrifiée", `Les céramiques se classent par leur température de cuisson. La faïence, cuite autour de mille degrés, garde une pâte poreuse qu'il faut recouvrir d'un émail pour la rendre étanche : un éclat sur le bord révèle la terre nue et l'objet boit. Le grès, cuit plus chaud, autour de mille trois cents degrés, vitrifie dans sa masse et devient imperméable même sans émail. La porcelaine exige en plus une argile particulière, le kaolin, argile blanche très pure qui lui donne sa blancheur et sa translucidité — son absence en Europe explique que la porcelaine chinoise y soit restée trois siècles un mystère jaloux, jusqu'à la découverte de gisements en Saxe puis à Limoges.

L'émail céramique est une couche vitreuse fondue à la surface d'une pièce, à la fois étanchéité et décor. Une céramique technique désigne tout autre chose : un matériau céramique aux propriétés mécaniques, thermiques ou électriques spécifiques — bougies d'allumage, prothèses de hanche, blindages, isolants de ligne haute tension. Le verre trouve dans le même registre son application la plus exigeante : la fibre optique demande un verre de très haute pureté, car la moindre impureté absorbe la lumière et limite la portée. Un verre de fenêtre serait opaque sur quelques mètres ; une fibre laisse passer le signal sur des dizaines de kilomètres.`],
  ],

  "st2-mesure-temps": [
    ["Compter avant d'oscillier", `Les premières horloges mesurent un écoulement. Une clepsydre est une horloge à eau : un récipient se vide ou se remplit à débit régulier, et le niveau indique le temps écoulé. Le sablier, le cierge gradué et le cadran solaire relèvent de la même logique de flux ou d'ombre. Tous partagent un défaut — le débit varie avec la pression, la température, la propreté du conduit —, et une horloge à eau soignée dérivait de plusieurs minutes par jour.

Le saut vient du passage du flux à l'oscillation. Un phénomène qui se répète à intervalle constant se compte, et sa régularité ne dépend plus de conditions extérieures difficiles à maîtriser. Toute l'histoire de la mesure du temps depuis le XVIIe siècle consiste à trouver des oscillateurs de plus en plus réguliers.`],
    ["Le pendule et la mer", `Christiaan Huygens applique le pendule à l'horlogerie en 1656, exploitant une propriété observée par Galilée : la période d'un pendule ne dépend pratiquement que de sa longueur, non de l'amplitude de son balancement. L'erreur quotidienne des horloges mécaniques passe de plusieurs minutes à quelques secondes — un facteur cent en une seule invention.

Reste un problème que le pendule ne peut résoudre : la mer. Déterminer sa longitude en mer suppose de comparer l'heure locale, lisible au soleil, à l'heure d'un port de référence — chaque heure d'écart valant quinze degrés. Il faut donc emporter une horloge fiable, ce qu'un pendule ne permet pas sur un navire qui roule. John Harrison y consacre quarante ans et produit des chronomètres à ressort et balancier compensés en température, dont le quatrième dérive de quelques secondes sur une traversée de l'Atlantique. Des milliers de naufrages avaient précédé cette solution.`],
    ["Le quartz, puis l'atome", `Une montre à quartz repose sur la vibration d'un cristal sous tension électrique : le quartz est piézoélectrique, il se déforme quand on lui applique une tension et produit une tension quand on le déforme. Taillé à la bonne dimension, il oscille à trente-deux mille sept cent soixante-huit hertz — une puissance de deux, facile à diviser électroniquement jusqu'à obtenir une seconde. La précision atteint quelques secondes par mois, pour un coût dérisoire, ce qui ruina une grande part de l'horlogerie mécanique dans les années 1970.

Une horloge atomique franchit un ordre de grandeur supplémentaire en s'appuyant sur une transition d'énergie précise d'un atome, souvent le césium. La fréquence de cette transition est une constante de la nature, identique partout dans l'univers : elle ne s'use pas, ne dérive pas et ne dépend d'aucune fabrication. Depuis 1967, la seconde est d'ailleurs définie par elle et non plus par la rotation de la Terre — le temps a cessé d'être astronomique pour devenir atomique.`],
    ["L'heure officielle et ses arrangements", `Le temps universel coordonné est l'échelle de temps de référence mondiale : il combine la régularité des horloges atomiques et la nécessité de rester en phase avec la rotation terrestre, laquelle ralentit irrégulièrement. D'où la seconde intercalaire, ajoutée occasionnellement pour compenser ce ralentissement. Ces secondes en trop ont provoqué assez de pannes informatiques pour que leur abandon ait été décidé à l'horizon 2035.

La Terre compte en théorie vingt-quatre fuseaux horaires d'une heure chacun, mais la carte réelle est bien plus irrégulière : certains pays décalent d'une demi-heure ou d'un quart d'heure, et la Chine, large de cinq fuseaux théoriques, n'en applique qu'un seul par décision politique d'unification — le soleil s'y lève à des heures très différentes selon les provinces. Le changement d'heure saisonnier, décalage de l'heure légale pour mieux profiter de la lumière du soir, obéit à la même logique : l'heure est une convention sociale, pas une donnée astronomique.`],
  ],

  "st2-brevets-innovation": [
    ["Un marché avec la société", `Un brevet confère à son titulaire un monopole d'exploitation temporaire en échange de la publication de l'invention. C'est un contrat explicite : l'inventeur renonce au secret, l'État lui garantit vingt ans d'exclusivité — durée maximale en France comme dans la plupart des pays.

L'idée est que le savoir circule. Sans brevet, un procédé se garde ; avec brevet, il est publié, consultable par tous, et tombe dans le domaine public à l'échéance. Les bases de brevets constituent de ce fait la plus grande bibliothèque technique du monde, largement sous-exploitée : une bonne part de ce qu'elles contiennent est librement utilisable, les brevets anciens étant expirés.`],
    ["Ce qui est brevetable", `Trois conditions cumulatives : la nouveauté — l'invention ne doit pas avoir été rendue accessible au public, y compris par son propre inventeur, d'où la règle absolue de ne rien divulguer avant le dépôt ; l'activité inventive — elle ne doit pas découler de manière évidente de l'état de la technique pour un homme du métier ; et l'application industrielle — elle doit pouvoir être fabriquée ou utilisée.

Une découverte scientifique n'est pas brevetable : constater une loi de la nature, isoler un phénomène, décrire un mécanisme relève de la connaissance, non de l'invention. Seule une application technique peut l'être. La frontière est parfois ténue — une séquence génétique naturelle n'est pas brevetable, un procédé de diagnostic l'exploitant peut l'être —, et elle a nourri des contentieux majeurs en biotechnologie.`],
    ["Où déposer, comment exploiter", `L'INPI est en France l'organisme chargé des brevets, des marques et des dessins et modèles. Un brevet européen relève d'une logique particulière : une procédure d'examen unique devant l'Office européen des brevets délivre non pas un titre unitaire, mais un faisceau de brevets nationaux qu'il faut ensuite valider pays par pays — d'où des coûts de traduction et de maintien longtemps critiqués, que le brevet unitaire entré en vigueur en 2023 vise à réduire.

Un brevet s'exploite rarement seul. Une licence d'exploitation autorise un tiers à l'utiliser contre redevance. Une licence obligatoire est imposée par l'autorité publique dans l'intérêt général : elle permet à un État de faire produire un médicament breveté sans l'accord du titulaire, en cas d'urgence sanitaire — outil rarement employé mais dont la seule existence pèse dans les négociations de prix.`],
    ["Les stratégies de contournement", `Toutes les entreprises ne brevettent pas. Un secret de fabrique est une information tenue confidentielle plutôt que brevetée : ni durée limitée, ni publication, mais aucune protection si un concurrent la retrouve par lui-même. Le calcul dépend de la facilité de rétro-ingénierie — on brevette un mécanisme visible dans le produit, on garde secrète une formule ou un réglage de procédé. La recette du Coca-Cola aurait été dans le domaine public depuis un siècle si elle avait été brevetée.

À l'autre extrémité du spectre, le patent troll est une entité qui rachète des brevets pour attaquer en justice sans rien produire. Son modèle repose sur le coût du contentieux : il est souvent moins cher de transiger que de se défendre, même avec de bons arguments. Le phénomène a pris une ampleur particulière dans le logiciel américain, où des brevets larges et vagues ont été délivrés en nombre, et il illustre la dérive possible d'un dispositif conçu pour encourager l'invention en instrument de rente juridique.`],
  ],

  "st2-cyberespace": [
    ["Un réseau sans propriétaire", `Personne ne possède internet. C'est un réseau de réseaux : des dizaines de milliers d'opérateurs autonomes qui acceptent d'échanger du trafic selon des protocoles communs. Aucune autorité centrale n'accorde d'autorisation d'y entrer, et l'on peut y raccorder un réseau sans demander la permission de quiconque.

Cette absence de propriétaire ne signifie pas absence de pouvoir. Quelques acteurs contrôlent des points critiques : celui qui gère les noms, celui qui écrit les protocoles, ceux qui exploitent les câbles et les grands centres de données. La gouvernance d'internet consiste précisément à savoir qui décide de ces points de passage, et selon quelles procédures.`],
    ["Qui écrit les règles", `Trois organisations principales, aux rôles distincts. L'ICANN gère les noms de domaine au niveau mondial : elle attribue les extensions, encadre les registres et supervise le système d'adressage. Longtemps sous contrat avec le gouvernement américain, elle est passée en 2016 sous une gouvernance multipartite internationale, à l'issue d'un débat diplomatique de dix ans.

L'IETF élabore les standards techniques d'internet — les protocoles eux-mêmes. Son fonctionnement est singulier : ouverte à tous, sans vote formel, elle décide par « consensus approximatif et code qui fonctionne », et sa devise revendiquée rejette les rois et les présidents. Le W3C définit de son côté les standards du Web, distincts de ceux du réseau : HTML, CSS, accessibilité.

Les infrastructures ont leurs propres nœuds. Un point d'échange internet est une installation où les opérateurs interconnectent leurs réseaux, échangeant du trafic localement au lieu de le faire transiter par l'étranger — enjeu de coût, de latence et de souveraineté. Un serveur racine du DNS est au sommet de la hiérarchie de résolution des noms : il ne connaît pas les adresses des sites, mais sait quel serveur interroger pour chaque extension.`],
    ["Les frontières reviennent", `Une extension de nom de domaine nationale est un suffixe attribué à un pays ou territoire, géré par un registre local qui en fixe les règles. C'est le premier point où le droit national reprend prise sur un réseau conçu sans frontières — un État peut décider qui obtient un nom sous son extension, et le retirer.

La fragmentation d'internet désigne la tendance de certains États à créer des espaces numériques cloisonnés, par filtrage, par obligation d'infrastructures locales ou par réseau parallèle. La localisation des données — obligation de stocker certaines données sur le territoire national — participe du même mouvement, avec des motivations très variables selon les pays : protection des données personnelles ici, accès facilité des services de renseignement ailleurs. Le même dispositif technique sert des objectifs opposés, ce qui rend le débat difficile à trancher en bloc.`],
    ["Les limites matérielles", `Le protocole IPv4 offre environ quatre milliards d'adresses, ce qui paraissait inépuisable en 1981 et ne l'est plus depuis longtemps. IPv6 apporte un espace d'adressage pratiquement inépuisable — de l'ordre de trois cent quarante milliards de milliards de milliards de milliards d'adresses, assez pour en attribuer à chaque objet imaginable. Sa migration, entamée dans les années 1990, reste inachevée : les deux protocoles coexistent, faute d'incitation suffisante à basculer tant que des rustines permettent de partager les adresses anciennes.

Le réseau a par ailleurs une réalité physique massive. Un centre de données est une installation regroupant serveurs, stockage et réseau, avec une alimentation électrique redondante et un refroidissement qui représente une part majeure de sa consommation. Le « nuage » est fait de bâtiments, de câbles et de mégawatts — et la question énergétique du numérique se joue autant dans ces halls que dans les terminaux.`],
  ],
};
